### ISSUE TITLE
Wrap compiled code in UMD (for commonJs and AMD support)

### ISSUE THREAD

**Issue by pgilad** [Studio-42/elFinder#1000]
You can still elFinder as a global (like for example Backbone does: https://github.com/jashkenas/backbone/blob/master/backbone.js#L8-L29) but this will allow support for different loaders (commonJs or AMD) without having to shim the file

**Comment by lokothodida** [comment]
I would consider taking this a step further and modifying the elFinder source JS files to be modules as well: the main elFinder entry point (`elFinder.js`) would be written as a UMD module, but the other source files can be AMD/CommonJS/ES6 etc. The major benefit is that regardless of which module system is chosen, Browserify can be used to compile those modules, making the build stage simpler than it currently is. It  would also help to make the dependencies in a given module very explicit, and hopefully allow for current monolithic source files to be broken into smaller, more manageable modules.
