### ISSUE TITLE
Your file downloads are all different.

### ISSUE THREAD

**Issue by neotropic2023** [Studio-42/elFinder#1001]
Downloading files form your main website seem way out of date. And the files here, completely different on top of your demo elfinder.html linking to files that are not in the download. And then the nightlys are different too! WHATS UP!

NOT in the download here.
elfinder.min.css
elfinder.min.js
Yet your demo file in the zip links to them.

I download files from the website, my code to add images/files to tinymce works. but cant delete files.
Download from nightly, code to add images for tinymce breaks. But can delete files. I alter code, but do not ever get full URL. Kinda of aggravating there being so many different version of downloads and not one set or all being the same. I just want one that fully works!

On top of random errors from each version, all different.
One says drivers not found. Another throws errors I do not understand with no message.

**Comment by neotropic2023** [comment]
Sorted my issues out, but the downloads should all be the same atleast. Having old copy from your website download to only tell people to download nightly does not help them.

I do appreciate this application, I LOVE IT! Just confusing with all the different downloads and versions floating around.

**Comment by nao-pon** [comment]
I chose to be released on GitHub. In addition, the demo site also it was established on GitHub. However, I do not have permission to edit elfinder.org.

- https://github.com/Studio-42/elFinder/releases - Releases
- http://studio-42.github.io/elFinder/ - Demo

Thanks.
