### ISSUE TITLE
elfinder.full.js

### ISSUE THREAD

**Issue by Koldar** [Studio-42/elFinder#1004]
Hello to all!
I have a design question about elfindder.full.js. First of all I want to apologize if this isn't the right place to put my question, but I didn't know where to post it.
My question is simple: I want to add to elfinder the possibility to create soft-links to files (atm I'm working only on a local file system). In order to do so, I think I have to change the local file system PHP connector and elfinder.full.js. Since the files are a little big, can I ask you how those files are designed? What is the general data flow of those files (in particular the javascript one), what are the important methods?
Thank you for all the answer

**Comment by nao-pon** [comment]
@Koldar Please check https://github.com/Studio-42/elFinder/wiki/Build-and-compress-elfinder-from-source . elfinder.full.js is built from source(elfinder/js) by jake.
