### ISSUE TITLE
The Photo Manager can't display pictures  on centos

### ISSUE THREAD

**Issue by suhaoxiang** [Studio-42/elFinder#1005]
elFinder can operate normally in local computer yet it can’t display pictures on centos. 
It’s said that some php functions are disabled. Can someone help me out?
![images](https://cloud.githubusercontent.com/assets/8537993/6934271/5595c00e-d864-11e4-935b-9cbc3c517163.jpg)

**Comment by dleffler** [comment]
Are you getting any error messages? Can you display the files, just not the thumbnails? Do you have the 'roots' array set up correctly with path, URL?  What type of OS were you running locally, Windows or Linux based (DIRECTORY_SEPARATOR)?  I had to debug several different scenarios with our implementation.

**Comment by suhaoxiang** [comment]
Thank you for your reply. I have found the reason - disable_function in php.ini hides scandir function. I can see the pictures when I enable scandir function.
