### ISSUE TITLE
validName is not implemented on 2.x

### ISSUE THREAD

**Issue by pgilad** [Studio-42/elFinder#1006]
Only definitions can be seen, no implementation?

**Comment by nao-pon** [comment]
Please check your connector configuration 'acceptedName'.  Its set value is given to "preg_match" or "call_user_func".
code - https://github.com/Studio-42/elFinder/blob/0ab6da28177639bcd29e3ec9cf3f8e2fad787c37/php/elFinderVolumeDriver.class.php#L1885-L1903

**Comment by nao-pon** [comment]
@pgilad You are right. Not implementation of client configuration.
