### ISSUE TITLE
Excel files get corrupted when downloaded

### ISSUE THREAD

**Issue by pbertoni** [Studio-42/elFinder#1011]
Got elFinder `2.1 (Nightly: ff1c846)`, protocol version: `2.0`, jQuery/jQuery UI: `1.8.0/1.8.23`, both on
* localhost (`LAMPP`, Ubuntu `x64` `14.04.2`)
* production ( `Apache 2.4.7`, `Mysql Ver 14.14 Distrib 5.5.41`,  Ubuntu `x64` `14.04`)

with the **same working tree** of my repo, but different things happen when I try to download a `xls` or `xlsx` file via elFinder. In facts, on production site the downloaded file gets corrupted with lots of bad characters and wrong formatting.. a mess, in a few words. 
Note that getting back the hosted file via `scp` does **not** create this bug, so it's download related.
I'll be happy to provide more details, thank you for your courtesy.

**Comment by pbertoni** [comment]
This is solved **externally** of this repo, at nao-pon's branch 2.1_n at commit [477fc6f](https://github.com/nao-pon/elFinder/commit/477fc6f2cce2ae588c89141319696572ecc8c4c7).

**Comment by pbertoni** [comment]
The problem it is surely local to production server, so it's not an elFinder issue. :-)

**Comment by nao-pon** [comment]
I'm happy, too. ;-)
