### ISSUE TITLE
howto display different foldernames or translate folder names?

### ISSUE THREAD

**Issue by sweiguny** [Studio-42/elFinder#1012]
hi everybody.

i am working on a CMS which shall provide more than one language.
therefore i'd like to give the folders, that are managed by elfinder, a name that represents a key of my translation module (kind of array). based on that key, the translated name shall be displayed.

example:
folder structure on filesystem:
```
\home
    \images
        \users
    \files
        \invoices
    ...
```

if a user opens elfinder in english, it shall be like
```
\Home
    \Images
        \Users
    \Files
        \Invoices
    ...
```

if a user opens elfinder in german, it shall be like
```
\Start
    \Bilder
        \Benutzer
    \Dateien
        \Rechnungen
    ...
```

that means, the acutal folder name is replaced by the translation.
does anyone have an idea how to accomplish that?

br

**Comment by nao-pon** [comment]
@sweiguny How about [Google web translation](https://translate.google.com/manager/website/suggestions). It was put on the [demo site](http://hypweb.net/elFinder-nightly/demo/2.1/) on probation. ;-)

**Comment by sweiguny** [comment]
@nao-pon This is not the way I imagine. I want to be independent from externals.
but thank you for your input.

sadly, i don't know, where exactly in the code the filenames (and so the foldernames) are figured out and displayed, cause then i'd like to override this functionality.

**Comment by nao-pon** [comment]
I see. That's something of great interest! :laughing:

**Comment by sweiguny** [comment]
Hi,

well, i now came across the issue, that, if i am going to "open" a file with elfinder...

![image](https://cloud.githubusercontent.com/assets/6470636/9436190/bd98a95e-4a4d-11e5-92cc-adc059a423ad.png)

The opened path will be `.../Intern/Avatare/IMG_1376.JPG` which is, of course, not the real path.

in my getFileCallback i've implemented a function for "retranslating" the path for inserting files into e.g. tinymce.
is there somewhere the possibility to get the real path of the file on opening or quicklook?

**Comment by sweiguny** [comment]
also when i want to display details the "wrong" path is displayed:

![image](https://cloud.githubusercontent.com/assets/6470636/9437815/75d05b6a-4a59-11e5-993d-698ab07d2904.png)

**Comment by sweiguny** [comment]
as i closed this issue accidentially the last time, i think, that it got perished :smile:

**is there somewhere the possibility to get the real path of the file on opening or quicklook?**

im afraid that the only possibility is to implement such a translated path by myself.

**Comment by nao-pon** [comment]
Quoted from the commit log
-----------------------------

**connector** added an option `i18nFolderName`

```php
// enable i18n folder name that convert name to elFinderInstance.messages['folder_'+name]
'i18nFolderName'  => false,
```

**e.g. connector.php**

```php
$opts = array(
    'roots'  => array(
        array(
            'driver'         => 'LocalFileSystem',
            'path'           => '/path/to/files/',
            'i18nFolderName' => true,
        )
    )
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```

**e.g. elfinder.html**

```javascript
// Additional translation messages
var i18nFolderMsgs = {
    'en': {
        'folder_Downloads':   'Downloads',
        'folder_Images':      'Images',
        'folder_LargeVideos': 'Videos',
        'folder_MIME-types':  'MIME types',
        'folder_Welcome':     'Welcome(Multilingual)'
    },
    'jp': {
        'folder_Downloads':   'ダウンロード',
        'folder_Images':      '画像',
        'folder_LargeVideos': '動画',
        'folder_MIME-types':  'MIMEタイプ',
        'folder_Welcome':     'ようこそ(多言語)'
    }
};

var options = {
    url      : 'php/connector.php',
    handlers : {
        init : function(e, fm) {
            // Register additional messages
            $.extend(fm.messages, i18nFolderMsgs.en, i18nFolderMsgs[fm.lang] || {});
        }
    }
}

$('#elfinder').elfinder(options);
```
