### ISSUE TITLE
Firefox only shows parent folders

### ISSUE THREAD

**Issue by basvdheijden** [Studio-42/elFinder#1013]
We've discovered a small problem with ElFinder in the tree view on the left. With the setting 'remember last directory' on, when reloading an ElFinder page the tree loads just fine in most browser.

However, in Firefox, it seems that only the parent folders get loaded in and shown in the tree view. Sibling folders do not show up anymore. When clicking on a parent folder name, however, the underlying folders do get loaded in.

Any idea what might cause this problem?
Thanks in advance.

**Comment by nao-pon** [comment]
@BasVanDerHeijden Certainly, there was such bug before. But then the [latest edition (2.1 Nightly)](https://github.com/nao-pon/elFinder-nightly) is already corrected.Old cache may be a remaining one in your FF browser.

Please check on my demo site. - http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l1_V2VsY29tZS_QlNC-0LHRgNC-INC_0L7QttCw0LvQvtCy0LDRgtGM
