### ISSUE TITLE
is there a mode to display only images/videos/directories?

### ISSUE THREAD

**Issue by sweiguny** [Studio-42/elFinder#1016]
hi,

i'd like to ask if there is a possibility to just display images or videos.
i know i could modify this example...
```php
array( // restrict access to png files
    'pattern' => '/\.png$/',
    'write' => false,
    'locked' => true
)
```
but i do not want to rescrict agains the extension but against the mimetype..
i would like to achieve the same for directories.

is there a possibility within elfinder or do i need to implement this by myself?

br, simon

**Comment by MPK44** [comment]
you can use the accessControll Function to hide them by yourself
in Options add:
```php
	'roots' => array(
		array(
....
			'accessControl' => 'access'
		)
	)
```
and remember to add the according function
```php
function access($attr, $path, $data, $volume) {
	if(mime_content_type($path) == /* types to show */ )
		return null;
	else
		return true;

}
```

**Comment by lokothodida** [comment]
You can do it from the client-side with the [onlyMimes](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#onlymimes) property:

```javascript
$('.elfinder').elfinder({
  // ...
  onlyMimes: ['image'], // restricts to images
  // ...
});
```

**Comment by sweiguny** [comment]
@lokothodida thanks, this works perfect!

for directories: `onlyMimes = ["directory"]`
