### ISSUE TITLE
Timeout forces a "Unable to connect to backend." error

### ISSUE THREAD

**Issue by pbertoni** [Studio-42/elFinder#1019]
I expanded `elFinder` **search** function to crawl inside files in a *grep*-fashion. On a large filesystem, this produces relatively long-running tasks (**up to 2-3 minutes**), but unfortunately after about 40 seconds something interrupts the request, and everything ends in a quite general error of elFinder: "*unable to connect to backend*".
So, I incremented every timeout cap of the server to 5 minutes, *i.e.* 

in `/etc/php5/apache2/php.ini`

 - max_execution_time
 - max_input_time
 - default_socket_timeout
 - mysql_connect_timeout
 - session.cache_expire

in `/etc/apache2/apache2.conf`

 - Timeout

And restarted `apache2` server, but problem still arises. I'm suspecting it is *elFinder* related.

**Comment by rajendra2** [comment]
@pbertoni Did you find a solution ? I am also seeing the same error for long-running tasks.

**Comment by rajendra2** [comment]
I was able to fix it. need to set max_execution_time in php.ini and update fastcgi_read_timeout in nginx configuration.
