### ISSUE TITLE
Not showing response for root directory

### ISSUE THREAD

**Issue by mayararajesh** [Studio-42/elFinder#1020]
@warhawk3407

I am using nightly(elfinder 2.1) version with libssh2 SFTP driver which i had impletemented as like you did using phpseclib.My problem is when i give root path of filesystem("/") its getting the required response but it is unable to display in UI.

And also the same problem not only with SFTP, but others also.

And also i am getting error while uploading zip file, like below:

Fatal error: Call to undefined method elFinderVolumeSFTP::getMimeTable() in /var/www/html/nightly/php/elFinder.class.php on line 1448 

Can you please fix this bug

**Comment by warhawk3407** [comment]
@mayararajesh 

Hello, have you been able to fix your issue ? Have you seen how I have implemented phpseclib in order to solve your issue ?

Regards

**Comment by nao-pon** [comment]
@mayararajesh Please move to https://github.com/warhawk3407/bgpanelv2_webftp/issues .
