### ISSUE TITLE
Update from elfinder 

### ISSUE THREAD

**Issue by barguer** [Studio-42/elFinder#1021]
Hi,
I have to update an old version od elFinder and I have two questions:
1. Which is the recomended version?
from github:
https://github.com/Studio-42/elFinder/archive/2.x.zip
or from the web (the one I'm using right now):
https://github.com/downloads/Studio-42/elFinder/elfinder-2.0-rc1.tar.gz
2. Based on the previous question which jQuery version do you recomend?
Thank you.

**Comment by davo3** [comment]
Hi @barguer , I think in readme file the answer is already provided 
https://github.com/Studio-42/elFinder#which-version-of-elfinder-should-i-use
