### ISSUE TITLE
Symbolic links are not visible

### ISSUE THREAD

**Issue by santosh0705** [Studio-42/elFinder#1022]
Using the 2.1 nightly build, and Im not seeing any symbolic links. Here is my configuration.
<code>
array(
                        'alias'         => 'Local System',
                        'driver'        => 'LocalFileSystem',
                        'path'          => '/',
                        'accessControl' => 'access' 
                ),
</code>

Using elFinder for the first time so I don't know this is the standard or its an issue.

**Comment by nao-pon** [comment]
@santosh0705 , thanks for your post. It's a bug with config ` 'path' => '/'`. I'll fix it.

**Comment by nao-pon** [comment]
related commit 5099017c76f001d17bfd314f3a0514ffff10e04c

**Comment by santosh0705** [comment]
arigatou gozaimasu...
Will test and let you know :)

**Comment by nao-pon** [comment]
You are welcome :smile: 
こちらこそありがとう！（kotirakoso arigatou!）

**Comment by santosh0705** [comment]
It worked!

**Comment by kukko** [comment]
I wan't how the elFinder don't follow symlinks, but I can't disable that. There is any option in the 2.1 version? I need that for the image resize plugin.

Thanks in advance.
