### ISSUE TITLE
Uploading problem

### ISSUE THREAD

**Issue by RedLann** [Studio-42/elFinder#1023]
Hello, i used the elfinder script on my xampp webserver and it was working just fine, now i uploaded everything to an hosting (windows) where the website will be hosted but i cannot either delete files or upload files i get those messages:
Unable to upload "name.jpg".
Unable to remove "name.jpg".
Unable to create folder
It seems i need some permissions but i have the upload folders with 666 permissions and i still cannot get it to work...do i need to set some other permissions?

**Comment by nao-pon** [comment]
May be upload folder's parm should be `0755` or `0777`.
