### ISSUE TITLE
Cross-site scripting (XSS)

### ISSUE THREAD

**Issue by guy-cliqr** [Studio-42/elFinder#1024]
efinder has XSS issue. You can produce the problem in 2 ways:

1. rename a folder to 'a xss test "onmouseover="alert(document.domain)"' (without single quote) and mouse over the folder to trigger the injected script;

2. rename a folder to '.<script>alert("XSS attack")</script>' and the popup dialog will trigger the execution of the injected script.

**Comment by nao-pon** [comment]
Tanks @guy-cliqr
