### ISSUE TITLE
elfinder directory takes too much time

### ISSUE THREAD

**Issue by masdux** [Studio-42/elFinder#1032]
I am using elfinder(2.0) in yii , i have like 2000+ files in start directory,  it takes more than 1 minute to load all , if i remove the tree it opening very quickly , but here comes problem , it always open the last time i opened  directory , and i can't go back parent directory . I don't know what to do ? help me please , I am wating thanks !

**Comment by nao-pon** [comment]
@masdux 

-  it takes more than 1 minute to load all
    - How about 2.1 Nightly? Please try it.
- it always open the last time i opened directory
    - see Wiki - Client configuration options: rememberLastDir <https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#rememberlastdir>
- i can't go back parent directory
    - Do you get error message?

**Comment by masdux** [comment]
thank  you very much , ' rememberLastDir = false ' options work like a charm,
 also before i did not get error massage , and i will try 2.1  thanks again.
