### ISSUE TITLE
How to work with the uncompressed version?

### ISSUE THREAD

**Issue by ERROPiX** [Studio-42/elFinder#1034]
I want to ask if there's any way to test with the uncompressed javascript version.

**Comment by nao-pon** [comment]
Please see https://github.com/Studio-42/elFinder/blob/2.x/elfinder.src.html . :open_hands:

**Comment by lokothodida** [comment]
Here is a [cleaned up version](https://gist.github.com/lokothodida/466a275eb2d137cbe9b2) of the `elfinder.src.html` file that you or others might find useful.

**Comment by ERROPiX** [comment]
Thank you @lokothodida for the cleaned version
