### ISSUE TITLE
ReferenceError: dfrd is not defined

### ISSUE THREAD

**Issue by ERROPiX** [Studio-42/elFinder#1035]
I just downloaded the latest release 2.1, I am using firefox with firebug,
when the page load or when I clickanywhere in the elfinder panel, the console show the following errors
![elfinder-erros](https://cloud.githubusercontent.com/assets/6576868/8163920/cd80c66e-137d-11e5-8e0f-c0b4cad75e91.png)

Also, do you have any page where we can request new features?

**Comment by nao-pon** [comment]
[On my demo site](http://hypweb.net/elFinder-nightly/demo/2.1/) no error on 2.1 (Nightly: 7b47cb8) with jQuery/jQuery UI: 2.1.4/1.11.4. What version of jQuery are you use?

> Also, do you have any page where we can request new features?

To this issues OK. :-)

**Comment by ERROPiX** [comment]
Hi,
I just downloaded the elFinder 2.1 (Nighty) from these links https://github.com/Studio-42/elFinder#downloads and renamed the dist connector in my server, then tested and it show the error.

I didn't modified the jquery, you have in your index file:
```html
<!-- jQuery and jQuery UI (REQUIRED) -->
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/themes/smoothness/jquery-ui.css">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js"></script>
```
I think you should update the jQuery used in the index.html?

**Comment by ERROPiX** [comment]
For suggestions, i don't know if any of these is already done, I analyzed the code of version 2.0, I can see some few enhancements:
- Add notification popup position to configuration
- Now search retrieve files and folders from the root path not the current directory. the search can be more important if it can search in files content, maybe adding some advanced search popup for options will be better?
- Moving files by drag & drop is done very good, but, why not also have copy files by holding ctrl/cmd while dragging the files/directories this is also a good feature to add :)

That's all for now, I will add other later if you allow :)

Thanks

**Comment by nao-pon** [comment]
@ERROPiX please make a new issue of new request. ;-)

About jQuery version. I changed to jQuery/jQuery UI: 1.8.3/1.8.23 of (my demo site)[http://hypweb.net/elFinder-nightly/demo/2.1/]. And there are no errors. Please check in my demo site with your browser.

**Comment by ERROPiX** [comment]
I have checked the demo now and it doesn't show any error, I will try to download the build and test in local

**Comment by nao-pon** [comment]
I found a bug. And it was just corrected exactly. ;-)

**Comment by ERROPiX** [comment]
Should I split my other features request in new issues?

**Comment by nao-pon** [comment]
Yes, that's right.
