### ISSUE TITLE
Search command enhancements

### ISSUE THREAD

**Issue by ERROPiX** [Studio-42/elFinder#1037]
Now search retrieve files and folders from the root path not the current directory. it should only look for files inside the current directory.

The search can be more important if it can search in files content, maybe adding some advanced search popup for options will be better.

**Comment by nao-pon** [comment]
@ERROPiX 
2.1 has option panel of serch cmd.

![elFinder-search-options](http://xoops.hypweb.net/modules/xelfinder/index.php/view/1940/elFinder-search-options.png)

How about it?

**Comment by ERROPiX** [comment]
that's great, so it just need other options to search in 'File names', 'File content' text/* files or both

**Comment by RJRahevar** [comment]
ASP.NET MVC

Now search retrieve files and folders from the root path not the current directory. it should only look for files inside the current directory.

The search can be more important if it can search in files content, maybe add in asp.net into source code

thanks

**Comment by nao-pon** [comment]
To actually add custom searches, you need to extend the volume driver. For details, please see the wiki.

- https://github.com/Studio-42/elFinder/wiki/Custom-search-function
