### ISSUE TITLE
Drag & drop enhancements

### ISSUE THREAD

**Issue by ERROPiX** [Studio-42/elFinder#1038]
Moving files by drag & drop is done very good, but, why not also have copy files by holding ctrl/cmd while dragging the files/directories this is also a good feature to add
For references, this is already implemented in cPanel file manager

**Comment by nao-pon** [comment]
@ERROPiX 

I can't speak English, so it may be misread, but is it such thing?

![elFinder-DnD-copy](http://xoops.hypweb.net/modules/xelfinder/index.php/view/1941/elFinder-DnD-copy.png)

This is on 2.1.

**Comment by ERROPiX** [comment]
Yes, so it's already in 2.1, I only tested in 2.0, Great job guys
