### ISSUE TITLE
missing css file

### ISSUE THREAD

**Issue by achezzoh** [Studio-42/elFinder#1039]
the installation states that we need to include elfinder.css, but i cant find this file in the css folder. somebody help me. also the nighly 2.x seems to have everything and is working fine except that the command buttons show funny titles on hover, is it possible to change that. also the confirm dialog during delete has the same funny names for buttons eg btnConfirm and btnCancel. someone help me solve this.

**Comment by nao-pon** [comment]
@achezzoh You should build elFinder for to get elfinder.full.css or elfinder.min.css OR You have to get [Nightly build](https://github.com/nao-pon/elFinder-nightly).

About 'funny titles on hover etc' -> ref. nao-pon/elFinder-nightly#12

**Comment by achezzoh** [comment]
i didnt know that, am afraid am quite new to these things, anyway i already got the nightly build and its working fine. thanks again...
