### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mime' of undefined

### ISSUE THREAD

**Issue by hedgehog90** [Studio-42/elFinder#1040]
In all the new version I encounter this error quite often:
    Uncaught TypeError: Cannot read property 'mime' of undefined

on this line:
    helper.append(icon(files[hashes[0]].mime)).data('files', hashes).data('locked', false);

It happens when you try to click and drag an image file sometimes. I sort of spam it by dragging releasing repeatedly.

It appears to happen if you try and click and drag the file icon the moment the end of the jquery-ui draggable revert animation ends.
setting revert to false fixes it.

**Comment by nao-pon** [comment]
@hedgehog90 Please check on my demo site of this problem. And please tell a result.

- http://hypweb.net/elFinder-nightly/demo/2.x/
- http://hypweb.net/elFinder-nightly/demo/2.1/

**Comment by hedgehog90** [comment]
Tested both, managed break them both after a few attempts.
For some reason there's a moment at the very end of the transition when you stop dragging, and if you try and re select the file you just dragged, you'll get the error, and it breaks the entire thing.

**Comment by nao-pon** [comment]
ummm... What browser are you using?

**Comment by megadr01d** [comment]
I'm not getting any error in OS X 10.9, Safari 7.1.6 but I found that if I select a file and drag it just a bit (like dragging to the same folder the file is in), the selection gets stuck. So, If I select a second file, I get 2 blue selections. I have to click again on the first file to release the sticky selection.

**Comment by hedgehog90** [comment]
Here's what happens on Chrome.
![demo](https://cloud.githubusercontent.com/assets/5526342/8272896/8f24ad0c-184d-11e5-928f-161b8769f58b.gif)
Again, i should make it clear, it requires some precision timing to trigger the bug, even so I'm surprised it hasn't been reported by other users.

I just tried it again on firefox but it requires that I just click and drag as fast as I can frantically. And instead of the mime error I get a slightly different one:
    TypeError: t is undefined
which is referring to the section:
    s=function(t){var n,i=t.mime;

The 2.0 RC1 version (April 10th 2012) available to download from elfinder.org does not have this issue, most likely due to using an older version of jquery ui.

**Comment by nao-pon** [comment]
Thanks everyone! May be it fixed. Please re-open If did't fix. ;-)

**Comment by megadr01d** [comment]
@nao-pon Thanks, just to report that I'm not getting any console warnings in Safari 7.1.6 but I still get sticky selections (sorry if this is a different issue).

1. Access demo site [test folder](http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l2_bWVnYWRyMDFkLXRlc3Q)

2. Drag some folders and files to the empty space below (it works like when you press <kbd>Cmd/Ctrl + Click</kbd> to select multiple items)

Output: Every dragged item stays selected and is only unselected by clicking on it again
Expected: Clicking on any item or empty space below should unselect everything
