### ISSUE TITLE
Display permessions and owner/group

### ISSUE THREAD

**Issue by ERROPiX** [Studio-42/elFinder#1042]
Can you add display of linux permissions (drwxr-xr-x or -rwxr-xr-x ...)?
Can you also add the display of the owner of the file?

**Comment by nao-pon** [comment]
About `owner`, 2.1 branch that option [uiOptions.cwd.listView.columns](https://github.com/Studio-42/elFinder/blob/9716e35f5a310b65e1ab98eb09d66410416dd7df/js/elFinder.options.js#L327). But LocalFileSystem didn't have stat['owner'] so I did [commit today](https://github.com/Studio-42/elFinder/commit/785542d0768e25dc6703e3e3f0da9c3ae93e0300) for support stat['owner'].

ref. https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#statOwner

**Comment by ERROPiX** [comment]
Yes, that's correct, so option `statOwner`  is only supported by localFileSystemVolume?

**Comment by megadr01d** [comment]
> Can you add display of linux permissions (drwxr-xr-x or -rwxr-xr-x ...)?

I would add the octal representation, eg. **drwxr-xr-x (755)** but although I would like this, it would have to accommodate windows and unix type permissions and without a way to actually change permissions, it would not be of much use.

> FTP driver is supported owner. But LocalFileSystem driver didn't have

What about the group? Is common for FTP listings to show user/group, eg. **admin/nobody**.

**Comment by megadr01d** [comment]
OK, I just saw [this](https://github.com/Studio-42/elFinder/pull/1026) PR.

**Comment by nao-pon** [comment]
Now supported on 2.1 branch. ( diff: https://github.com/Studio-42/elFinder/compare/9b116e40e7f18c66afcf1abcb8fb15ab5137679c...e437147fc5b395c0860985bc099b0edf401b4468 ) 

ListVew option -> https://github.com/Studio-42/elFinder/compare/9b116e40e7f18c66afcf1abcb8fb15ab5137679c...e437147fc5b395c0860985bc099b0edf401b4468#diff-8f21be2aabffef6829e6a54df1769004L325

**Comment by nao-pon** [comment]
@ERROPiX Now `statOwner` is supported FTP too. see - https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#statOwner

**Comment by megadr01d** [comment]
@nao-pon Thank you sir! This is highly appreciated. Since I don't use elFinder internal permissions (everything is read and write because I'm the only one accessing it), UNIX permissions are most useful.

Just found a small bug. After applying new permissions I have to to reload elFinder (toolbar button) for the permissions column to refresh, but then the contextual menu stops working on files (the `cwd` contextual menu works). Only after reloading elFinder a second time I can access the contextual menu again.

**Comment by nao-pon** [comment]
@megadr01d I pushed new version. try that new one.

> Is there a setting to choose between permission representations, like 0755, 755, rwxr-xr-x or both rwxr-xr-x (755)?

I'm thinking add to client configuration it. :-)

**Comment by nao-pon** [comment]
I pushed, [that](https://github.com/Studio-42/elFinder/commit/901bc5144c487a3a6e0a80871ba50e6a0d07ec16) include new option `fileModeStyle`.

ref. Wiki - https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#fileModeStyle

**Comment by megadr01d** [comment]
@nao-pon Thanks a lot my friend. It now refreshes the new permissions automatically. Is it too much to ask for a third option to be `fileModeStyle: 'both'` or `fileModeStyle: ['string', 'octal']`, eg. `rwxr-xr-x (755)`?

> I have to to reload elFinder (toolbar button) for the permissions column to refresh, but then the contextual menu stops working on files (the cwd contextual menu works). Only after reloading elFinder a second time I can access the contextual menu again.

Also, I created a [new](https://github.com/nao-pon/elFinder-nightly/issues/14) issue concerning the contextual menu bug. I think the problem may be in the [Reload function](https://github.com/nao-pon/elFinder-nightly/issues/13).

**Comment by nao-pon** [comment]
> `fileModeStyle: 'both'`
:+1: 

I pushed it function at https://github.com/Studio-42/elFinder/commit/d499cb90bfd753f4df9b1b00f6491c8e294c8ca5.

And set default to 'both', also added values 'modestr', 'modeoct' & 'modeboth' for
`options.cwd.listView.columns`. :-)

**Comment by megadr01d** [comment]
@nao-pon  +:100:!

Amazing. You even added values for different columns. Working great. =)
Thank you for your dedication and amazing developing skills.
