### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by pflind** [Studio-42/elFinder#1044]
What is up with all these confusing versions? Which one can be used in production?

I downloaded both 2.x nightly and 2.1 nightly and they seem buggy. For instance the text on buttons and dialogs don't work, example: btnClose, btnApply, rm, errMkdir and so on instead of Close, Apply, Remove, New folder etc.

**Comment by nao-pon** [comment]
@pflind I made mistake on Jakefile.js. Now fixed. Please try latast version.

**Comment by pflind** [comment]
Okay, thanks! But which version should I use 2.x or 2.1?

**Comment by nao-pon** [comment]
- 2.x - Bug or Security fix only.
- 2.1 - New function, UX optimize, etc...

Please choose the favorite one as the need arises. :-)

**Comment by pflind** [comment]
Thank you for your help! Very nice script. Keep up the good work! :)
