### ISSUE TITLE
elFinderVolumneLocalFileSystem.class.php not php v5.3 compliant

### ISSUE THREAD

**Issue by dleffler** [Studio-42/elFinder#1045]
In the latest code, there is a fragment which fails under php v5.3.  Line #356 
```
$stat['owner'] = $names[$uid] = posix_getpwuid($uid)['name'];
```
should be
```
$pwuid = posix_getpwuid($uid);
$stat['owner'] = $names[$uid] = $pwuid['name'];
```
to work under php v5.3

**Comment by nao-pon** [comment]
@dleffler Thanks ! It fixed on commit https://github.com/Studio-42/elFinder/commit/81ff772e4b28bcbc10cf814c760a31a5904aa1d2 :-)
