### ISSUE TITLE
Archive Buttons Are Always disabled No Matter What

### ISSUE THREAD

**Issue by fluidnotions** [Studio-42/elFinder#1046]
I'm extending the java connector with some of the missing cmds.
But I can't figure out why the archive buttons are always greyed out.
I'm using 2.x nightly build.

I tried adding  
"archivers": [
      "create",
      "extract"
    ]
to the open cmd response and the buttons are still disabled.
I also tried this.alwaysEnabled = true; in elFinder.prototype.command
The JSDoc says: "If true, command can not be disabled by connector."
So I have to assume it's not the connector.

Is there any other reason why they would be disabled. I've been looking through the javascript for the last few hours trying to find out why/under what conditions they would be disabled without coming across anything that has helped me resolve the issue.
I also tried stepping through init() and didn't seem the sort of logic I'd expect that may be responsible.
Any clues would be appreciated.

**Comment by nao-pon** [comment]
@fluidnotions It seems problem of java connector. JSON "options.archivers" should include supported archivers like this.
```json
"archivers": {
    "create": [
        "application/x-tar", 
        "application/x-gzip", 
        "application/x-bzip2", 
        "application/x-xz", 
        "application/zip", 
        "application/x-7z-compressed"
    ], 
    "extract": [
        "application/x-tar", 
        "application/x-gzip", 
        "application/x-bzip2", 
        "application/x-xz", 
        "application/zip", 
        "application/x-7z-compressed"
    ]
}
```

Please check JSON results on my demo site. ( http://hypweb.net/elFinder-nightly/demo/2.x/ )

**Comment by fluidnotions** [comment]
@nao-pon Thanks it works perfectly I suppose I should have just check the JSON from the demo site, would have been a lot easier

**Comment by nao-pon** [comment]
:+1:
