### ISSUE TITLE
Volume icon not showing bug

### ISSUE THREAD

**Issue by pflind** [Studio-42/elFinder#1047]
When directly accessing `elfinder-2.1/elfinder.html` the root `image volume_icon_local.png` is displaying, but if you have elfinder in a subfolder and try to access it outside the subfolder the volume icon is not displaying.

**Comment by nao-pon** [comment]
@pflind Set icon imege URL to volume root option `icon`. Or define constant `ELFINDER_IMG_PARENT_URL`.

```php
array(
	'driver' => 'LocalFileSystem',
	'path'   => 'PATH TO/files/',
	'URL'    => 'URL TO/files/',
	'icon'   => 'URL TO/img/volume_icon_local.png',
),
```

OR

```php
define('ELFINDER_IMG_PARENT_URL', 'URL TO IMG PARENT');
```
Icon URL will be `ELFINDER_IMG_PARENT_URL/img/volume_icon_local.png`.

**Comment by pflind** [comment]
Ah, that solves it :+1:  Thank you again! :)

**Comment by nao-pon** [comment]
:+1:
