### ISSUE TITLE
Integration with codeigniter 3; doesnt show nothing

### ISSUE THREAD

**Issue by HyasKoinoz** [Studio-42/elFinder#1048]
Hello,

I have integrated elfinder with codeigniter 3. (following the guide integration)
The problem is elfinder doesnt show the files, however when i search, show them perfecly and when i remove the filter, doestn show them again.

**Comment by paulcanning** [comment]
Can you show your connector? I have successfully integrated elFinder with CI3.

**Comment by troex** [comment]
@paulcanning can you tell if https://github.com/Studio-42/elFinder/wiki/Integration-with-Codeigniter-2 is different for CI3? Update to the wiki is welcome

**Comment by paulcanning** [comment]
@troex Seems to be the same as what I have. Need to see @HyasKoinoz 's code to try and help.
