### ISSUE TITLE
Not work with TinyMce 4.2

### ISSUE THREAD

**Issue by turbointeractive** [Studio-42/elFinder#1051]
This code not working with new TinyMce 4.2:
```javascript
setUrl: function (url) {
      win.document.getElementById(field_name).value = url;
}
```
I looking very long time and find this solution:
```javascript
setUrl: function (url) {
	var fieldElm = win.document.getElementById(field_name);
	fieldElm.value = url;
	if ("createEvent"in document) {
		var evt = document.createEvent("HTMLEvents");
		evt.initEvent("change", false, true);
		fieldElm.dispatchEvent(evt)
	} else {
		fieldElm.fireEvent("onchange")
	}
}
```

I try somthing tiny, like this:
```javascript
setUrl: function (url) {
	var fieldElm = win.document.getElementById(field_name);
	fieldElm.value = url;
	$(fieldElm).change();
}
```
but, this does not working :(

**Comment by dleffler** [comment]
What is not working?  The url is not being returned?  Or is it the noted issue where the image dimensions are not filled out?  Using the TinyMCE 'file_browser_callback' is known to not change the dimensions.

If that's the case and you are following the wiki article 'Integration with TinyMCE 4.x' at https://github.com/Studio-42/elFinder/wiki/Integration-with-TinyMCE-4.x you could add/change this code fragment within the FileBrowserDialogue.mySubmit() function

```
      // pass selected file path to TinyMCE
      parent.tinymce.activeEditor.windowManager.getParams().setUrl(URL);
      var t = parent.tinymce.activeEditor.windowManager.windows[0];
      t.find('#src').fire('change');

      // close popup window
      parent.tinymce.activeEditor.windowManager.close();
```
I've updated the wiki article to include this...HOWEVER the BEST bet is to switch to using the TinyMCE 'file_browser_callback' function which I'll also attempt to 'add to' the wiki article.
