### ISSUE TITLE
disable thumbs creation

### ISSUE THREAD

**Issue by AlexMcowkin** [Studio-42/elFinder#1052]
Hello.
Please help.
I dont need to create .tmb folder with thumbnails.
How can I disable thumbs creation ?

thnx.

**Comment by nao-pon** [comment]
@AlexMcowkin Try connector roots option `tmbPath` to empty.

```php
'tmbPath' => '',
```

**Comment by nicorac** [comment]
Hi, this doesn't work on elFinder 2.1.x.
Any clue?
