### ISSUE TITLE
How to prevent dialogs (such as confirm) and just run action?

### ISSUE THREAD

**Issue by pgilad** [Studio-42/elFinder#1054]

**Comment by lokothodida** [comment]
Is there a reason that you want to prevent confirmation dialogs from appearing?

**Comment by pgilad** [comment]
The reason is that we added external actions (from outside elfidner) that we want to cause a certain action, such as:
- Delete
- Upload file

And want to bypass the confirmation dialog

**Comment by lokothodida** [comment]
Ok. How have you added the external actions?

**Comment by pgilad** [comment]
Currently I bypass it by simulating user action click:
```
$container.find('.ui-dialog button:contains(Remove)').click();
```

**Comment by lokothodida** [comment]
So I haven't tried this yet, but you might want to give it a shot.

The [js/commands/rm.js](https://github.com/Studio-42/elFinder/blob/fc6d3375f9a417924d67121b66a0c8f134dd0bb5/js/commands/rm.js) file defines the delete command for the front-end. It has some code in it that [triggers the dialog](https://github.com/Studio-42/elFinder/blob/fc6d3375f9a417924d67121b66a0c8f134dd0bb5/js/commands/rm.js#L53).

So if you're willing to modify the core just for your own project, you can remove/comment out the `fm.confirm(/* */)` stuff and replace it with what is defined on the [`accept`](https://github.com/Studio-42/elFinder/blob/fc6d3375f9a417924d67121b66a0c8f134dd0bb5/js/commands/rm.js#L58) callback.

**Comment by lokothodida** [comment]
Or (and this too is untested), so you don't change the functionality of the normal `rm` action, you can copy the `rm.js` file (removing the confirm dialog section) and give the command a unique name:

```javascript
// rmcustom.js
elFinder.prototype.commands.rmcustom = function() {
  // ...
};
```

Load that script after the elFinder core has loaded:

```html
<!-- elfinder core, then: -->
<script src="js/commands/rmcustom.js"></script>
```

Add that command to the elfinder [configuration](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#commands)

```javascript
  commands: [ /* your basic commands, then: */ 'rmcustom' ]
```

Then use the elfinder `instance` to execute your new command

```javascript
var instance = $('.elfinder').elfinder('instance');

// ...
var myCustomCallback = function() {
  var hashes = /* get the hashes for the files that need to be deleted */;
  instance.exec('rmcustom', hashes);
};
```

Then run that callback when you need to. I'm not sure of the best way to get the hashes, though. In terms of the [client event callbacks](https://github.com/Studio-42/elFinder/wiki/Client-event-API#event-list), the `select` callback has an array of the currently selected files on the `event` parameter (`event.data.selected`), so you may need to use that callback to set the data somewhere, then get that data in your custom callback.

**Comment by pgilad** [comment]
Yeah those are great ideas, I was thinking a configuration option is the best way, since it adds flexibility and I don't have to sync my source code with upstream all the time.

**Comment by lokothodida** [comment]
I know what you mean.

Try out the above hacks to see that they actually work. Perhaps ask @nao-pon if he thinks it would be reasonable functionality to add to the core. If he does, I could probably implement it without too much hassle. Something like:

```javascript
commandsOptions: {
  // 'delete' action
  rm: {
    // disable the confirmation dialog
    dialog: false
  }
}

**Comment by lokothodida** [comment]
I've created a branch off to try and add this functionality.

* Changes to [js/elFinder.options.js](https://github.com/lokothodida/elFinder/commit/617a761190b853f6f399b60de5f7d013ab476d37)
* Changes to [js/commands/rm.js](https://github.com/lokothodida/elFinder/commits/2.1-issue-1054/js/commands/rm)

Again, not tested them yet. Do you want to try it out?

**Comment by nao-pon** [comment]
Another solution is...

Send request to connector in your JavaScript

```javascript
var elf_instance = $([elFinder DIV selector]).elfinder('instance');
elf_instance.request({
	data: { cmd: 'rm', targets: [TARGETS ARRAY] },
	preventFail: true
})
.fail(function(error) {
	// any
})
.done(function(data) {
	// any
})
.always(function() {
	// any
});
```

Not tested them yet.
