### ISSUE TITLE
Latest 2.1 Revision Generating "elfinder is not a function" Error

### ISSUE THREAD

**Issue by dano1066** [Studio-42/elFinder#1056]
I have an old version of elfinder and i want to update to the latest. I downloaded the latest 2.1 revision and it is generating the following error when i open the default elfinder.html file (which has incorrect file names)

Uncaught TypeError: $(...).elfinder is not a function

Generated by 

		<script src="js/elFinder.js"></script>

		
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#elfinder').elfinder({
					url : 'php/connector.php'
				});
			});
		</script>

Any idea why this is happening?

**Comment by nao-pon** [comment]
@dano1066 

> `<script src="js/elFinder.js"></script>`

may be `<script type="text/javascript" src="js/elfinder.min.js"></script>`

ref. https://github.com/Studio-42/elFinder/wiki/Install :-)

**Comment by dano1066** [comment]
There is no min file anymore. neither the 2.x or 2.1 have a min file. elFinder.js is the only file.

**Comment by nao-pon** [comment]
Please check my elFinder nightly builds. https://github.com/nao-pon/elFinder-nightly
