### ISSUE TITLE
custom command and UI changes 

### ISSUE THREAD

**Issue by rut2prajapati** [Studio-42/elFinder#1057]
I am working with elfinder for internal communication tool. I want to add functinalty in I can write description for each directory. For that I need to create commands by which I can store description text in database for perticular directory and then whenever that directory opens discription should be there. 

Is there any simple documant available where steps are defined about : How to create custom commands and change UI accordingly ?

**Comment by lokothodida** [comment]
The [Adding file description to Properties dialog](https://github.com/Studio-42/elFinder/wiki/Adding-file-description-to-Properties-dialog) wiki page describes what you are trying to do. It's not an elegant solution however, as it involves editing the elFinder Javascript source code.

**Comment by lokothodida** [comment]
There is now a [2.1 draft](https://github.com/Studio-42/elFinder/wiki/Adding-file-description-to-Properties-dialog-2.1) of this functionality which lets you achieve this in [elFinder 2.1](http://nao-pon.github.io/elFinder-nightly/latests/elfinder-2.1.zip) without editing the Javascript source code (the PHP is identical to before).
