### ISSUE TITLE
TypeError: m[i].proportions is not a function

### ISSUE THREAD

**Issue by lokothodida** [Studio-42/elFinder#1066]
After the recent update in 2.1, the aformentioned error comes up in the console (very frequently). The file causing the change is [jquery.elfinder.js](https://github.com/Studio-42/elFinder/blob/427b6709f4c29df5b86a51c79fc3dcb34105409f/js/jquery.elfinder.js).

I don't know much about the underlying implementation of the jQuery UI library, but in the `droppablesLoop`, is the proportions property meant to be a function or a plain object? And has that changed between jQuery versions? Because when I look in the console log (with the version of jQuery provided in elFinder, `m[ i ].proportions` is an object.

![screenshot from 2015-08-03 12 44 19](https://cloud.githubusercontent.com/assets/4363863/9036876/95b28dea-39dd-11e5-8832-2a8a93b6b144.png)

**Comment by nao-pon** [comment]
oops! I made mistake. I'll fix it. This problem get with jQuery UI < 1.11.0

**Comment by lokothodida** [comment]
:+1 thanks for responding so quickly!

**Comment by nao-pon** [comment]
@lokothodida Thanks! :+1: fixed on 65e22ac565491b4a43af785317be97ddf7e34b3d
