### ISSUE TITLE
After browsing a file(image) no url is set and the image is popuped in new window. 

### ISSUE THREAD

**Issue by mahendrarajdhami** [Studio-42/elFinder#1068]
When i click browse button to  open files to select image, after selecting an image the url is not set in the input field and the image is displayed in new window.

**Comment by nao-pon** [comment]
@mahendrarajdhami URL is hidden on cmd `open`. ref. https://github.com/Studio-42/elFinder/commit/f38a37870d2c25381f48e34b2de0081507ea91b8

You can get URL on info dialog. Please use it.
