### ISSUE TITLE
List of Bugs on elFinder

### ISSUE THREAD

**Issue by WolKlu** [Studio-42/elFinder#1072]
List of Bugs:
1.       Click on Get Info icon> ISSUE: Nice to have Close button on the top of the window.   
![2015-08-17_1048](https://cloud.githubusercontent.com/assets/13872850/9362571/d12092a6-4666-11e5-8e77-881ba26cd2b5.png)

2.       Select any image> Click on Cut icon> Click on other image or Press Esc button to deactivate the “cut” functionality> ISSUE: The cut image is not get back to original or enabled.
 ![2015-08-17_1100](https://cloud.githubusercontent.com/assets/13872850/9362587/ea3686c4-4666-11e5-8972-de192704cf2d.png)

3.       Click on List icon>ISSUE: Good to have Label “Type” instead of “Kind”.  
![2015-08-17_1109](https://cloud.githubusercontent.com/assets/13872850/9362593/faa2a592-4666-11e5-9ec2-24bcc46bb5be.png)

4.       Resize and Rotate window can have “X” button at the top.

5.       Near Search field can have search icon.

6.       What is the name of the label for this icon?
![2015-08-17_1335](https://cloud.githubusercontent.com/assets/13872850/9362603/03fd7a72-4667-11e5-9ce8-43c95d3fb7cf.png)

**Comment by nao-pon** [comment]
@WolKlu Several icons aren't indicated in your elFinder. But it's no problem by my demonstration site. I guess that there is a problem with integration method.

- Demo site
    - http://hypweb.net/elFinder-nightly/demo/2.x
    - http://hypweb.net/elFinder-nightly/demo/2.1
