### ISSUE TITLE
Prevent Listing Some Files

### ISSUE THREAD

**Issue by alenoosh** [Studio-42/elFinder#1073]
Hi

Is there a way to prevent listing some files like hidden files ?

I have found the option to prevent reading or writing to files and also locking the files but I want to hide it from the list view.

Thanks in advance

**Comment by donShakespeare** [comment]
If you set read to false (in either accesControl or attributes, the file will not be shown. That is how precisely the .tmb folders are hidden from view.

**Comment by alenoosh** [comment]
@donShakespeare Thanks alot. It works now.
