### ISSUE TITLE
startPath for multi volumes

### ISSUE THREAD

**Issue by donShakespeare** [Studio-42/elFinder#1074]
I use accessControl to hide the root folders of each volume (Filesystem).
The third volume is accessible to the user but startPath will not work.
Is it possible to use startPath for a volume other than the first volume in which startPath is called?

I am using startPath + folder URL parameter to choose folders dynamically

**Comment by Tiega91** [comment]
i had the same problem, i just kicked the startPath out and used the root-path dynamically. With this solution you dont even need to hide the subfolder^^
