### ISSUE TITLE
elFinder and TinyMCE 4.2

### ISSUE THREAD

**Issue by parkerj** [Studio-42/elFinder#1077]
I am trying to integrate elFinder with TinyMCE using the Advanced method mentioned here: https://github.com/Studio-42/elFinder/wiki/Integration-with-TinyMCE-4.x

When using file_picker_callback, double clicking on a file does nothing. The error message I see in my browser's inspector element is: TypeError: undefined is not an object (evaluating 'win.document')

If I change file_picker_callback to file_browser_callback, the double clicking on the image works as expected, but the file url is not returned. Instead, the box is filled with: [object Object]. And the error message I see in the inspector element is: TypeError: undefined is not an object (evaluating 'e.browser.msie')

Can someone help me figure out how to get this working? Thanks.

**Comment by parkerj** [comment]
Actually, part of what I stated above is wrong because I wasn't using the Advanced method at the time. Now that I am using the advanced method, this is what I am experiencing. By the way, I am using Safari and Chrome.

1. When clicking the folder icon to open elfinder via TinyMCE, the error in the inspector element is TypeError: undefined is not an object (evaluating 'e.browser.msie').

2. When I click on an file to be included as the source using the driver LocalFileSystem, I get the following error in the inspector element: ReferenceError: Can't find variable: meta, and clicking a file does nothing.

3. However, when I am using the S3 driver, I still get the 'e.browser.msie', but when I click on a file to be included in the source, the file opens in a new window instead.

**Comment by parkerj** [comment]
Still looking for help on this. If it helps, I am including a screenshot of the full error I am getting.

![elfinder-error](https://cloud.githubusercontent.com/assets/2042176/9458474/b0aeb11a-4abc-11e5-906a-b8365f84fcc9.png)

**Comment by nao-pon** [comment]
@parkerj I recommend use elFinder nightly build (2.x or 2.1) for operation check.

- https://github.com/nao-pon/elFinder-nightly

**Comment by parkerj** [comment]
Thanks, I will try it and see if I get a different result.

**Comment by parkerj** [comment]
Ok, so I've successfully implemented the nightly build, but I am still get this error message: ReferenceError: Can't find variable: meta

So, under the downloaded package, I created a tinymce.html file and included everything I needed in that file using the advanced method, and I also edited the elfinder.html code.

So, I load tinymce.html into my browser, clicked the insert image icon, click the icon on source for elfinder, clicked on the image, but instead of populated the url into the source box, it instead opens in a new window. At least I am not getting the meta error message, but it still isn't yielding expected results. I've tested this using the regular and advanced method and both bring up the image in a new window.

**Comment by nao-pon** [comment]
OK. I found problem and fixed wiki page.

`function elFinderBrowser (callback, value, meta) {` is correct.

- https://github.com/Studio-42/elFinder/wiki/Integration-with-TinyMCE-4.x/_compare/5ae3880846bea5f2c6e6a3279beedf2929be0cc4

**Comment by parkerj** [comment]
It works. Thank you!!!!!!!

**Comment by nao-pon** [comment]
It's no problem. :-) Please close this issue. ;-)

**Comment by parkerj** [comment]
Done.
