### ISSUE TITLE
getFileCallback for directories

### ISSUE THREAD

**Issue by sweiguny** [Studio-42/elFinder#1078]
hi,

i'd like to use the `getFileCallback` not just for files but also for directories.

e.g. i have a textbox where i want to set the path of a specific directory via elfinder. this directory contains images which shall later be used for a slider.

can i somehow achieve that?

**Comment by nao-pon** [comment]
@sweiguny It possible by `uiOptions.commandsOptions.getfile.folders` to `true`.

```javascript
	commandsOptions : {
		// "getfile" command options.
		getfile : {
			onlyURL  : false,
			// allow to return multiple files info
			multiple : false,
			// allow to return filers info
			folders  : true,
			// action after callback (""/"close"/"destroy")
			oncomplete : ''
		}
	}
```

**Comment by sweiguny** [comment]
unfortunately this seems not to work.

the url is not passed to the callback-function. folders have an dblclick event handler attached which opens the folder, need i to remove this?

**Comment by nao-pon** [comment]
Please re-check on elfinder.full.js of [nightly build](https://github.com/nao-pon/elFinder-nightly).

on 2.x https://github.com/nao-pon/elFinder-nightly-src/blob/cca1e41343d2b58b6f342e2bfb684fd4f0d76d9e/js/elfinder.full.js#L8387, if `uiOptions.commandsOptions.getfile.folders` is `true` then continue exec.

**Comment by sweiguny** [comment]
hi,

with debugging i found out, that the paremeter is not `uiOptions.commandsOptions.getfile.folders` but `commandsOptions.getfile.folders` (without `uiOptions`).

now it works! thank you very much :grinning:
