### ISSUE TITLE
CKeditor intergration with output of localhost

### ISSUE THREAD

**Issue by shinokada** [Studio-42/elFinder#1080]
I follow the [doc](https://github.com/Studio-42/elFinder/wiki/Integration-with-CKEditor) and it is working with CKeditor in my localhost. However the image path is `http://localhost/myweb/files/image1.jpg`.

This means when I put on a live server, I have to change all images again. 
I think I need to modify returned image path, but I am not sure how to do it. I think I need to add `document.location.hostname ` before the `files/images1.jpg` so that I can use it in a live site.

I appreciate any input. Thanks.

script

    // Helper function to get parameters from the query string.
    function getUrlParam(paramName) {
        var reParam = new RegExp('(?:[\?&]|&amp;)' + paramName + '=([^&]+)', 'i') ;
        var match = window.location.search.match(reParam) ;

        return (match && match.length > 1) ? match[1] : '' ;
    }

    $().ready(function() {
        var funcNum = getUrlParam('CKEditorFuncNum');

        var elf = $('#elfinder').elfinder({
            url : 'php/connector.php',
            getFileCallback : function(file) {
                window.opener.CKEDITOR.tools.callFunction(funcNum, file.url);
                window.close();
            },
            resizable: false
        }).elfinder('instance');
    });

**Comment by nao-pon** [comment]
@shinokada, How about that convert to relative path of url?

```javascript
getFileCallback : function(file) {
    var url = file.url.replace('http://localhost', '');
    window.opener.CKEDITOR.tools.callFunction(funcNum, url);
    window.close();
}
```

**Comment by shinokada** [comment]
It works.
Thank you for help.

**Comment by stefman1** [comment]
kind of fixes my relative path requirement :) cheers
