### ISSUE TITLE
Full File URL

### ISSUE THREAD

**Issue by parkerj** [Studio-42/elFinder#1081]
With some help from here, I've been able to implement elFinder and TinyMCE. Forgive me if this has been asked before, I searched but couldn't find the answer. When loading an image into TinyMCE from elFinder, the url is a relative path (../../files/homework.pdf). I want to allow professors the ability to send emails to student and be able to include any files from elFinder which means the full path (http://localhost/username/files/homework.pdf) is needed to do so. Is there are setting or something I need to change in order to make sure that elFinder doesn't truncate the path? Thanks.

**Comment by nao-pon** [comment]
@parkerj TinyMCE config may be...

```javascript
tinymce.init({
    relative_urls: false,
    remove_script_host: false
});
```

**Comment by parkerj** [comment]
Doh! I didn't even think to check TinyMCE configuration. Thank you for this.
