### ISSUE TITLE
Multiple File Download fails or is not consitent among different browsers specially in chrome

### ISSUE THREAD

**Issue by nizamuk** [Studio-42/elFinder#1082]
I have tried to select multiple files and download them though google chrome browser. But as soon as I click download icon or choose download option from right click options, it downloads only one file.
Could someone please help with this issue,.

**Comment by nao-pon** [comment]
May be elFinder 2.0+ or 2.1+ fixed this problem. Please check on [demo sites](https://github.com/Studio-42/elFinder#demo-sites). Close for awhile.
