### ISSUE TITLE
[Bug] Upload breaks with specific MIME-type configuration

### ISSUE THREAD

**Issue by MazeChaZer** [Studio-42/elFinder#1084]
This one should be fairly easy to fix, but I don't have the time to refactor this myself atm.

The following configuration breaks the file upload function completely (including images):

Connector:

```
'uploadAllow' => array('image'),
'uploadOrder' => array('allow', 'deny'),
```

Notice that `uploadDeny` is not configured.

Client:

```
onlyMimes: ['image']
```

The bug occurs because of line 1063 in `elFinderVolumeDriver.class.php`:

```php
	public function mimeAccepted($mime, $mimes = array(), $empty = true) {
		$mimes = !empty($mimes) ? $mimes : $this->onlyMimes; // <-- This line
		if (empty($mimes)) {
			return $empty;
		}
		return $mime == 'directory'
			|| in_array('all', $mimes)
			|| in_array('All', $mimes)
			|| in_array($mime, $mimes)
			|| in_array(substr($mime, 0, strpos($mime, '/')), $mimes);
	}
```

This function is called in `allowPutMime()`:

```php
	protected function allowPutMime($mime) {
		// logic based on http://httpd.apache.org/docs/2.2/mod/mod_authz_host.html#order
		$allow  = $this->mimeAccepted($mime, $this->uploadAllow, null);
		$deny   = $this->mimeAccepted($mime, $this->uploadDeny,  null); // <-- This line
		$res = true; // default to allow
		if (strtolower($this->uploadOrder[0]) == 'allow') { // array('allow', 'deny'), default is to 'deny'
			$res = false; // default is deny
			if (!$deny && ($allow === true)) { // match only allow
				$res = true;
			}// else (both match | no match | match only deny) { deny }
		} else { // array('deny', 'allow'), default is to 'allow' - this is the default rule
			$res = true; // default is allow
			if (($deny === true) && !$allow) { // match only deny
				$res = false;
			} // else (both match | no match | match only allow) { allow }
		}
		return $res;
	}
```

I assume an upload with a MIME type of `image/png` which should be allowed. The problem occurs when the `$deny` variable is calculated. `$this->uploadDeny` is an empty array, so the value of `$this->onlyMimes` is used instead in `mimeAccept()`. `$this->onlyMimes` is equal to `['image']` because of the client configuration, so `$deny` becomes true. Now both `$allow` and `$deny` are true. Because of `'uploadOrder' => array('allow', 'deny')` this results in an upload error.

--> `$this->onlyMimes()` should not be used unconditionally in `mimeAccept()`

Workaround:

It is possible to work around this bug by specifying at least one item in the `uploadDeny` connector configuration. The bug doesn't appear with the following configuration:

Connector:

```
'uploadAllow' => array('image'),
'uploadDeny' => array('php'), // <-- This line is new
'uploadOrder' => array('allow', 'deny'),
```

Client:

```
onlyMimes: ['image']
```

**Comment by nao-pon** [comment]
@MazeChaZer Thanks!

By the way, I recommend next setting
```php
'uploadDeny'  => array('all'),
'uploadAllow' => array('image'),
'uploadOrder' => array('deny', 'allow'),
```
