### ISSUE TITLE
Image Thumbnail in Laravel-elfinder

### ISSUE THREAD

**Issue by tskkh** [Studio-42/elFinder#1085]
Hello all, I'm getting problem with the image thumbnail in laravel-elfinder integrate with CKeditor. It doesn't display the image thumbnail within the file browser display.

Anyone experienced with this please share me the solution.

![screenshot](https://cloud.githubusercontent.com/assets/8650616/9808201/2d403f28-5887-11e5-861a-a4e921ad02b9.png)

**Comment by janokary** [comment]
I have the same problem on Laravel-elfinder.

**Comment by Pezhvak** [comment]
i just had the same problem, check your phpinfo for png support in gd section

**Comment by Tiega91** [comment]
I have the same problem with ZF2. It seems like that you need the URL for the thumbs ZF and Laravel are MVC Framework so i guess that the given URL directs to a 404 Code
