### ISSUE TITLE
How to secure uploaded files

### ISSUE THREAD

**Issue by shinokada** [Studio-42/elFinder#1086]
What is the best practice to secure uploaded files? 

Can I use a password protected directory for elFinder?

Or can I use a directory above the root directory?

I thank you in advance for your help.

**Comment by megadr01d** [comment]
In the [connector configuration](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options), check the [attributes](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#wiki-attributes) option and set `read` to `false` on your upload folder.

**Comment by nao-pon** [comment]
elFinder does not have a user management function. So, we need to be prepared separately.

**Comment by nao-pon** [comment]
There is Basic Auth example -> http://studio-42.github.io/elFinder/#elf_l1_QmFzaWNBdXRoRXhhbXBsZQ

**Comment by shinokada** [comment]
@nao-pon: Where can I download the codes?

**Comment by nao-pon** [comment]
@shinokada I made zip. - http://hypweb.net/elFinder-nightly/demo/Demo/BasicAuthExample/BasicAuthExampleAddon.zip
