### ISSUE TITLE
Error with the call to disable method from resizable widget

### ISSUE THREAD

**Issue by AngelFQC** [Studio-42/elFinder#1088]
In the *quicklook* function for images, when change to the full screen preview I get this problem with Mozilla Firefox and Google Chrome in the Web Console 
`Error: cannot call methods on resizable prior to initialization; attempted to call method 'disable'`

**Comment by nao-pon** [comment]
@AngelFQC , I can't see this error. Please check on my nightly demo sites.

- http://hypweb.net/elFinder-nightly/demo/2.x/#elf_l1_SW1hZ2Vz
- http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l1_SW1hZ2Vz
