### ISSUE TITLE
Release elfinder 2.1

### ISSUE THREAD

**Issue by buckett** [Studio-42/elFinder#1092]
Although this project is progressing it seems that there haven't been any "stable" releases in a while. Having a stable release allows people to grab a copy of the project that is very likely to work and then allows them to see what bugs features have changed so evaluate if they want to upgrade.

**Comment by megadr01d** [comment]
I'd say @nao-pon [2.1 nightly](https://github.com/nao-pon/elFinder-nightly) is pretty stable.

**Comment by buckett** [comment]
Is there anything I can do to help get a release created.

**Comment by nao-pon** [comment]
Hi, @buckett , @megadr01d.

I think so too. However , I do not have permission to release...

**Comment by buckett** [comment]
Is it worth switching development to your fork @nao-pon as you seem to be doing most of the work on elFinder these days and then making releases there?

**Comment by nao-pon** [comment]
After a review of our my authority, administrative privileges had been granted. Now, I can manage the version.

From now, we will contact the Dmitry (dio) Levashov.

**Comment by megadr01d** [comment]
@nao-pon :+1: About time! Great news.

**Comment by buckett** [comment]
Brilliant news.

**Comment by nao-pon** [comment]
elFinder 2.0.3 and 2.1.0 released. https://github.com/Studio-42/elFinder/releases :v:
