### ISSUE TITLE
Languages are not copied right

### ISSUE THREAD

**Issue by birgit774** [Studio-42/elFinder#1093]
Hi all,
 
due to many locales we do have many languages. Currently the languages are not copied well or only english is taken. Apparently some texts were not copied. The slots are empty or absent.
We are working with demandware as our shop software.

Example:
Though the right language (example french) is copied within the copy tool the english version is displayed on the frontend. This is a huge disadvantage regarding our SEO texts. Could you double check this issue? How can you support us?

Thanks
Birgit

**Comment by nao-pon** [comment]
We are waiting for the cooperation of everyone. Please send your translation from [our translation tool](http://studio-42.github.io/elFinder/tools/langman/).
