### ISSUE TITLE
symlink does not show the directory

### ISSUE THREAD

**Issue by Raven3419** [Studio-42/elFinder#1099]
I have elFinder up and running however in the back in I created a Master Folder and with each copy of elFinder I created a symlink to the Master folder.
For some reason the fold does not show up in the elFinder.  

Can someone tell me if this is a bug or a setting i need to fix?

**Comment by megadr01d** [comment]
There was an [issue](https://github.com/Studio-42/elFinder/issues/1022) with symlinks that was fixed in May, for the [2.1 nightly build](https://github.com/nao-pon/elFinder-nightly).
I don't know what version are you on, but I can confirm symlinks show up correctly in the latest 2.1.

![symlinks](https://cloud.githubusercontent.com/assets/9649385/10217537/6a352ca8-6828-11e5-8363-748a398c221a.png)

**Comment by nao-pon** [comment]
At present, it is not possible to display the link that shows the outside
of the volume root. I believe in order to allow it.

**Comment by nao-pon** [comment]
@Raven3419 , @megadr01d Thanks!

**Comment by megadr01d** [comment]
@nao-pon Super-fast!

**Comment by Raven3419** [comment]
I just downloaded the latest version and it still didn't work.  Let me explain the problem in a little more detail.  Once you have it up and running lets say your root path for the folder to show is /var/www/elfinder/files
inside this directory i have created a symlink to a completely different directory out side of the root path.

ln -s /var/www/somedirectory/newFolder  /var/www/elfinder/files/.

if i do a ls inside files i can see my symlink to newFolder however inside the elfinder it does not show.  Any ideas?

**Comment by nao-pon** [comment]
@Raven3419, I found bugs of this problem so I'll fix it. Please wait a little longer.

**Comment by nao-pon** [comment]
Maybe fixed @e07c8222db4680124adb4854dcdf45685763c89b . Please try new nightly.

**Comment by Raven3419** [comment]
I just downloaded the nightly version but something was changed to make
errors.  inside elfinder.html you are calling a css called
css/elfinder.min.css on line 13 that file does not existed in the one you
posted.  also js/elfinder.min.js on line 17

**Comment by nao-pon** [comment]
@Raven3419 You can download [2.1 nightly build](http://nao-pon.github.io/elFinder-nightly/latests/elfinder-2.1.zip) from https://github.com/nao-pon/elFinder-nightly .
