### ISSUE TITLE
VirusTotal states there is some bad code 

### ISSUE THREAD

**Issue by catoegroup** [Studio-42/elFinder#1101]
https://www.virustotal.com/en/file/6a5e2feaa1d6cc0e0e502d91db8cb997c82d245b6a86326de864edfa33ec6689/analysis/

**Comment by nao-pon** [comment]
Probably false positives.　Now is all green.

- https://www.virustotal.com/en/url/2e22b9da0b381a67bcb6b5e7e35a82c5cc514c18ae7e305e2fe9a68ddbe4238a/analysis/1454327077/
