### ISSUE TITLE
add package.json

### ISSUE THREAD

**Issue by maruilian11** [Studio-42/elFinder#1102]
would you please consider adding package.json so that we can add your lib on https://cdnjs.com.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5873

**Comment by buckett** [comment]
Details on what makes up a packages.json are on: http://browsenpm.org/package.json
The only required fields are the name and version.

**Comment by maruilian11** [comment]
ok. thank you.

**Comment by nao-pon** [comment]
I added package.json to 2.0-src and 2.1-src. Is This OK?

**Comment by maruilian11** [comment]
yes, thank you :)

**Comment by nao-pon** [comment]
:+1:
