### ISSUE TITLE
glob() function is disabled

### ISSUE THREAD

**Issue by ferman2147** [Studio-42/elFinder#1103]
Hey everybody,
On most of the servers glob() function is disabled by default for security reasons. Is there any other script or function we can use istead of glob() function in the file elFinderVolumeLocalFileSystem.class.php, around line 435? 
Please help!

**Comment by Tiega91** [comment]
how you want to use a LocalFileSystem without the glob() function? This is impossible...
You should use the FTP solution instead

**Comment by ferman2147** [comment]
You know, what that function in the Elfinder library does, is just checks if a given pathname exists, and if it has at least one child, and if so, returns true. So what I'm asking is is there another way to achieve this without using glob() function. I already found a solution myself using scandir(), but I need en expert eye on this, and if aynone gives a good answer I will use theirs instead.

**Comment by Tiega91** [comment]
yeah sry you are right....
i check my version for glob functions and i didnt even found them. Which version do you use?
I use 2.x and it seems to already use for example scandir()

**Comment by nao-pon** [comment]
I think that's a rare cases thing to disable the `glob ()` so to close this issue.

**Comment by ferman2147** [comment]
Yeah it probably is. I don't really know how rare it is because we work with only two hosting providers and both of them disabled it due to the safety of directories and the possibility of using it to access other important directories so I can't blame them. Like I said glob() wasn't a must have and I was able to use scandir() instead. But then again I would really like to see how your code would look like if you were to remove the glob(). You know, because when it comes to Elfinder, you are one of the kings, Nao :) Let the issue stay closed, I really appreciate it if you could e-mail me your solution.
Thanks very much.

**Comment by nao-pon** [comment]
Currently, we are using a blob in elFinder in seven locations. There is a need to mask the results of scandir for each occurrence.

![elFinder-blob-use.png](http://xoops.hypweb.net/modules/xelfinder/index.php/view/1999/elFinder-blob-use.png)

PHP 5.2.4 and later does not have a directory traversal vulnerability, such as before. It is one of the also solutions to propose a re-examination of the set to the server administrator.
