### ISSUE TITLE
Icons not clickable after upgrading OS X to Mac El Capitan

### ISSUE THREAD

**Issue by shinokada** [Studio-42/elFinder#1105]
I just upgraded OS to Mac El Capitan. Since then icons are not clickable as you see in the image. Is it something to do with permission? How can I fix it? Thanks in advance. 

![image](https://cloud.githubusercontent.com/assets/147320/10563898/8cb93856-75d8-11e5-9449-20ad85185a3c.png)

**Comment by Tiega91** [comment]
The reason these permission issues are arising is a result of Apple's new changes to Mac OS X 10.11 El Capitan called SIP which stands for System Integrity Protector. 

Try and use the path to your root-dir:
sudo chown $(whoami):admin /usr/local && sudo chown -R $(whoami):admin /usr/local

**Comment by shinokada** [comment]
Thank you for your reply. 
I am not sure what "Try and use the path to your root-dir:" means.

I run `sudo chown $(whoami):admin /usr/local && sudo chown -R $(whoami):admin /usr/local` but I'm still not able to click icons.

**Comment by shinokada** [comment]
I tried it on MAMP and it works. But I still want to work in ~/Sites dir. Any more suggestions?

![image](https://cloud.githubusercontent.com/assets/147320/10607506/e4d723c0-7774-11e5-85ef-45746fc2a567.png)

**Comment by nao-pon** [comment]
Please try the FTP driver.
