### ISSUE TITLE
Disable hotkeys

### ISSUE THREAD

**Issue by Tiega91** [Studio-42/elFinder#1107]
Hey o/

is there a function in the .js that i can disable the hotkeys temporary. In my case i added a new function that open a "Bootstrap Modal" but i can't edit inputs in the modal because i always trigger some hotkeys >.<

regards

**Comment by megadr01d** [comment]
https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#allowShortcuts

**Comment by Tiega91** [comment]
yeah i know but i want it temporary, just for the time the modal is open

**Comment by nao-pon** [comment]
@Tiega91 please try `elFinder-Inctance.disable()`
```javascript
var f = $('#elfinder').elfinder({
  url : 'path_to/connector.minimal.php'
}).elfinder('instance');

// call any point for disable elFinder's hotkeys
f.disable();
```
