### ISSUE TITLE
imgResize() fixed

### ISSUE THREAD

**Issue by audino731** [Studio-42/elFinder#1110]
/php/elFinderVolumeDriver.class.php - line 3475 ~ 3479

origin

		list($size_w, $size_h) = array($width, $height);
		
		if ($keepProportions == true) {
		
			list($orig_w, $orig_h) = array($s[0], $s[1]);
		
			/* Resizing by biggest side */
			if ($resizeByBiggerSide) {
				if ($orig_w > $orig_h) {
					$size_h = round($orig_h * $width / $orig_w);
					$size_w = $width;
				} else {
					$size_w = round($orig_w * $height / $orig_h);
					$size_h = $height;
				}
			} else {
				if ($orig_w > $orig_h) {
					$size_w = round($orig_w * $height / $orig_h);
					$size_h = $height;
				} else {
					$size_h = round($orig_h * $width / $orig_w);
					$size_w = $width;
				}
			}
		}

fixed

		list($size_w, $size_h) = array($width, $height);
		list($orig_w, $orig_h) = array($s[0], $s[1]);
		
		if ($keepProportions == true) {
		
			/* Resizing by biggest side */
			if ($resizeByBiggerSide) {
				if ($orig_w > $orig_h) {
					$size_h = round($orig_h * $width / $orig_w);
					$size_w = $width;
				} else {
					$size_w = round($orig_w * $height / $orig_h);
					$size_h = $height;
				}
			} else {
				if ($orig_w > $orig_h) {
					$size_w = round($orig_w * $height / $orig_h);
					$size_h = $height;
				} else {
					$size_h = round($orig_h * $width / $orig_w);
					$size_w = $width;
				}
			}
		}

**Comment by nao-pon** [comment]
@audino731 Thanks! :+1: fixed @465ca4fc270941e111c96bc790e9927c87fe755d
