### ISSUE TITLE
TinyMCE integration

### ISSUE THREAD

**Issue by daslicht** [Studio-42/elFinder#1112]
Hello,
I tried the following:
https://github.com/Studio-42/elFinder/wiki/Integration-with-TinyMCE-4.x

But When i press the *add image* button i just get this presented:

![TinyMCE](http://i.imgur.com/IcllGN8.png)

Any idea? *please*

**Comment by daslicht** [comment]
OK I have the following:
- [x] elFinder is working Stand alone
- [x] elFinder is working with TinyMCE Stand alone , yeah
But as far as I try to integrate it into TinyMCE of GridEditor here:
https://github.com/Frontwise/grid-editor/blob/master/src/js/jquery.grideditor.tinymce.js#L22
The File Dialog Button is not shown.
May I ask you to have a look there, ***please***?
Here is my approach : 
https://gist.github.com/daslicht/740ad9e11ed248daea05#file-grideditor-elfinder-js-L33

**Comment by nao-pon** [comment]
ref. Frontwise/grid-editor#13
> SOLVED ! by using the latest TinyMCE

**Comment by daslicht** [comment]
If anyone need help to integrate I will joyful help

**Comment by nao-pon** [comment]
@daslicht :+1:
