### ISSUE TITLE
How to preserve a file's 'execute' mode

### ISSUE THREAD

**Issue by o771** [Studio-42/elFinder#1116]
I'd like to use elFinder in a situation where executable script files are uploaded to the server, and preserve the X mode. elFinder seems to strip X and just preserve R & W. I've been unable to find any configuration options that would allow this. Is it in fact possible to manage files and preserve their X mode bit? If so, how?

Many thanks.

**Comment by nao-pon** [comment]
@o771 There is a option `fileMode` of LocalFileSystem volume driver.

for example
```php
array(
	'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
	'fileMode'      => 0755,  // permission of the new file
	'path'          => '../files/',         // path to files (REQUIRED)
	'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
	'accessControl' => 'access'             // disable and hide dot starting files (OPTIONAL)
)
```
