### ISSUE TITLE
Select a folder instead of a file in standalone version

### ISSUE THREAD

**Issue by mln-mln-mln** [Studio-42/elFinder#1118]
Hi,
I need to be able to select a folder as well as file using the standalone popup. How can I achieve that?

**Comment by kibercoder** [comment]
Hi bro Nothing

**Comment by nao-pon** [comment]
It can by `commandsOptions.getfile.folders` to `true` in client configuration options.

https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#commandsoptions
