### ISSUE TITLE
Uploading a file of exactly 10 MiB doesn't work (Version 2.1)

### ISSUE THREAD

**Issue by MazeChaZer** [Studio-42/elFinder#1119]
[Here](http://we.tl/DjJyvljZcB) is a test file.
I tested this on the [nightly demo page](http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l2_Lw)
There is no error message, the file simply doesn't show up.

Furthermore, this line doesn't look quite right:

```php
// write counts
file_put_contents($base, "\0", FILE_APPEND) === false;
```

https://github.com/Studio-42/elFinder/blob/2.1/php/elFinder.class.php#L1501

The return value of this comparison is unused.

Edit: [Here](http://we.tl/gogYwCslI8) are two more files for testing, one has a size of 10MiB+1Byte and the other 10MiB-1Byte. They both work properly.

**Comment by nao-pon** [comment]
@MazeChaZer Thanks for your report. It will be fix next commit.

**Comment by nao-pon** [comment]
updated JavaScript. please browser reload before checking.

**Comment by MazeChaZer** [comment]
Thanks for the quick response. Everything works now.

**Comment by nao-pon** [comment]
:+1:
