### ISSUE TITLE
allow unpack .htaccess files ?

### ISSUE THREAD

**Issue by Diablo925** [Studio-42/elFinder#1123]
is there a way to allow .htaccess file ?

**Comment by nao-pon** [comment]
Hi @Diablo925 :smile: 

Please check connector configuration [`acceptedName`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#acceptedname).

default value of `acceptedName` is `'/^[^\.].*/'. It is the file name that begins with a dot will not be allowed.

**Comment by Diablo925** [comment]
thx
