### ISSUE TITLE
Uploading a file with exactly 20MiB/30MiB/40MiB... doesn't work (Version 2.1)

### ISSUE THREAD

**Issue by MazeChaZer** [Studio-42/elFinder#1124]
Seems to be similar to #1119, related to the chunked file upload

There is no error message, tested on the elFinder nightly demo.

Test files: http://we.tl/9ZaExpmt0w

**Comment by nao-pon** [comment]
@MazeChaZer ooooops! oh my.... fixed it. Thanks a lot!　:v:
