### ISSUE TITLE
Invalid image dimensions

### ISSUE THREAD

**Issue by standus** [Studio-42/elFinder#1126]
I got PHP warning:
imagecreatetruecolor(): Invalid image dimensions
in file \elfinder\php\elFinderVolumeDriver.class.php:3489
in function imgResize.

**Comment by nao-pon** [comment]
@standus , This problem fixed on 465ca4fc270941e111c96bc790e9927c87fe755d .Please try [2.1.1](https://github.com/Studio-42/elFinder/archive/2.1.1.zip)+ .
