### ISSUE TITLE
Wrong root path

### ISSUE THREAD

**Issue by standus** [Studio-42/elFinder#1127]
I upgraded to last night version 2.1.1 and found some problems with this:
$this->root = $this->getFullPath($this->root, getcwd());
My ->root is specific location 
$userfiles = realpath(dirname(__FILE__).'/../../..').'/myfiles';
then in options: 'path'          => $userfiles
In versions before it worked well, but in this version I need to disable this new line code.
Otherwise it will generate something like: getcwd path + My absolute path

**Comment by nao-pon** [comment]
@standus, Can you show me value of `realpath(dirname(FILE).'/../../..').'/myfiles'` and `getcwd()` ?

**Comment by standus** [comment]
on my local machine.
getcwd: "C:\xampp\htdocs\mysystem\library\elfinder\php"
path: "C:\xampp\htdocs\mysystem\userfiles"

**Comment by nao-pon** [comment]
OK. I'll fix this issue at next commit. You can try Volume option `systemRoot` to `'C:\'` until next commit.

```php
'systemRoot' => 'C:\',
'path' => $userfiles, 
```
