### ISSUE TITLE
Big files upload error at intranet.

### ISSUE THREAD

**Issue by opessoa** [Studio-42/elFinder#1128]
Hi guys I get a lot of same errors in my tests.

"unlink(C:\Users\OMARPE~1.MIC\AppData\Local\Temp/ELFb7ca3fede48d916378e94b0af619b204.part): No such file or directory in E:\Site\mtfilemanager\app\Helpers\elFinder\elFinder.php on line 1829."

Files bigger than 50MB.

Can you help me guys?

**Comment by nao-pon** [comment]
@opessoa There is a problem with probably short name "OMARPE~1.MIC".. Please try connector main option [`uploadTempPath`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadtemppath) .

```php
$opts = array(
    'uploadTempPath' => 'E:\tmp', // it's an example
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    )
);
```

**Comment by opessoa** [comment]
Error on Nov 13, 2015 13:56PM - unlink(E:\Tmp/ELFf4f11ebca1aa2593e829cd3654b64989.part): No such file or directory in E:\Site\mtfilemanager\app\Helpers\elFinder\elFinder.php on line 1829

Error on Nov 13, 2015 13:56PM - unlink(E:\Tmp/ELF774466ea8f72c3f73fe49c39ecb0a981.part): Permission denied in E:\Site\mtfilemanager\app\Helpers\elFinder\elFinder.php on line 1452

Error on Nov 13, 2015 13:56PM - unlink(E:\Tmp/ELF774466ea8f72c3f73fe49c39ecb0a981.part): Permission denied in E:\Site\mtfilemanager\app\Helpers\elFinder\elFinder.php on line 1452

**Comment by nao-pon** [comment]
Please try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1-src.zip), and please show me errors again.

Downloads - https://github.com/Studio-42/elFinder#downloads

**Comment by opessoa** [comment]
I have tried nightly build, and the errors are the same, when download are finishing.

Error on Nov 13, 2015 15:28PM - unlink(E:\Tmp/ELFb7ca3fede48d916378e94b0af619b204.part): No such file or directory in E:\Site\mtfilemanager\app\Helpers\elFinder\elFinder.php on line 1829
 
But, now, the files are in the directory, but they only appear after F5.

**Comment by nao-pon** [comment]
I want to know the exact line number. Error content and line number of code for the current Nightly does not match.

- https://github.com/Studio-42/elFinder/blob/2.x/php/elFinder.class.php#L1829

**Comment by opessoa** [comment]
Sorry man, I have added a namespace, so the correct line is: **1821**

`<if (! is_uploaded_file($tmpname) && @ unlink($tmpname)) unset($GLOBALS['elFinderTempFiles'][$tmpname]);>`

**Comment by nao-pon** [comment]
Thanks! However, it can not be resolved immediately. Please a little time.

**Comment by opessoa** [comment]
Ok nao-pon. 

Happy to help you to find little bugs!

Thanks for your time.

**Comment by nao-pon** [comment]
@opessoa Thanks a lot ! If there is still the same error, please re-open it with the details. :+1:
