### ISSUE TITLE
weird Signs in addressbar

### ISSUE THREAD

**Issue by Offerel** [Studio-42/elFinder#1129]
If i use elfinder in my environment, there are some signs appended to the url in the adrressbar. So, if i load https://mydomain.de/elfindertest/ (where elfinder loads in the index.html), the url in the adrressbar becomes https://mydomain.de/elfindertest/#elf_l1_QmFja3VwL0FuZHJvaWQ.

How can i get rid of the weird signs in the addressbar?

**Comment by nao-pon** [comment]
@Offerel This is address of folder on elFinder. You can use `useBrowserHistory`(https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#usebrowserhistory).

```javascript
$('#elfinder').elfinder({
	useBrowserHistory : false,
	url : 'php/connector.minimal.php'  // connector URL (REQUIRED)
});
```

**Comment by Offerel** [comment]
Ahhh. I see. Thx for the hint. It works now as expected.
