### ISSUE TITLE
firefox second and more call on same page with elfinder cause error

### ISSUE THREAD

**Issue by ampminfo** [Studio-42/elFinder#1143]
My first initialisation of elfinder on firefox work with problem but next calls of the instance give error

Error: Permission denied to access property "apply" 

in a try catch.

Under chrome and IE,  no problem at all...just firefox give this error and I do not do any cross site in my  code...always the same domain/server all the time.

**Comment by nao-pon** [comment]
@ampminfo I can't see this problem with elFinder 2.1.2 and jQuery 1.11.3 . My test config is like next. What is your configuration?

```html
<script type="text/javascript">
  $().ready(function() {
    // elFinder init
    $('#elfinder').elfinder({
      url : 'path to/connector.minimal.php'
    });
    $('#elfinder2').elfinder({
      useBrowserHistory: false, // disable BrowserHistory
      url : 'path to second/connector.minimal.php'
    });
  });
</script>
```

**Comment by nao-pon** [comment]
Close it. However, please re-open if there is a similar problem.
