### ISSUE TITLE
Filepath in JS?

### ISSUE THREAD

**Issue by t-me** [Studio-42/elFinder#1144]
Hello,

I want to make a module for Contao CMS and was wondering if i can set the file path in the JS instead of the connector.

For each user the file path (homedirectoy) is different,

I did not find it in de options.js. maybe i overlooked it.
Much Thanks

**Comment by nao-pon** [comment]
@t-me How about [`startPathHash`](https://github.com/Studio-42/elFinder/blob/d1a41096a1d81f744d14216e3a61f52971f67208/js/elFinder.options.js#L354)? For example at demo site, [Demo/Download](http://studio-42.github.io/elFinder/#elf_l1_RG93bmxvYWRz)'s hash is `l1_RG93bmxvYWRz`.

**Comment by t-me** [comment]
Hello Nao-Pon,

This is my JS with startPathHash but that wont work is there something i doing wrong? The url end with : #elf_l1_dXNlcl8z (for the dir)

		$('#elfinder').elfinder({
			url : '/php/connector.minimal.php',
			lang: 'nl',
			rememberLastDir : false,
			startPathHash : 'l1_dXNlcl81',
		});

**Comment by nao-pon** [comment]
> `startPathHash : 'l1_dXNlcl81',`

It is illegal as JSON. Because, there is a comma at the end of the property. Or, is it a priority when there is a hash in the browser location.

**Comment by t-me** [comment]
I have removed the comma that did not work.
I also trying to remove everything from JS only the URL and startPathHash but that also did not work for me.

I'm wondering if i get this to work will i be able to see other maps outside of the path?

Like :
   - home
       - user 1
       - user 2

If i get this to word for let's say user 2 that the startPathHash is user 2 will i be able to see folder user 1?

**Comment by nao-pon** [comment]
Oh, what are you want to specify the route holder on elFinder for each user? If so, you need to cope with the connector side.
