### ISSUE TITLE
Page freeze when uploading files on elFinder 2.1.x

### ISSUE THREAD

**Issue by fauri13** [Studio-42/elFinder#1146]
When I try to upload files the whole page freezes and doesn't respond. Version 2.0.4 works well, it's an issue with v 2.1.x (any version). 

It's something with the configuration of the server but don't know what could be...

I use last apache build and last php5 build.

Anyone else with the same issue?

**Comment by nao-pon** [comment]
@fauri13 Try `error_reporting(-1);` in your connector.php for debugging. And check server response.

**Comment by fauri13** [comment]
There are no errors at all in the connector. The post request never reaches the server. I have iptables configured but don't see either that the connection is blocked.

It's like the javascript enters an infinite loop... It starts to use huge amounts of CPU time and memory.

**Comment by fauri13** [comment]
Found the error!

The connector sends to the client the value of upload_max_filesize in the php.ini. If it is set to 0, the uplMaxSize variable is set to "0" (as string, not numeric) and when getting the BYTES_PER_CHUNK, the or between "0" and a number, it returns "0". So 0 minus 8190 is negative and thus it enters an infinite loop.

Pushed the fix if you want to check it.

**Comment by nao-pon** [comment]
@fauri13 Thanks! :+1:
