### ISSUE TITLE
Upload error for big files when uplMaxSize = 0

### ISSUE THREAD

**Issue by fauri13** [Studio-42/elFinder#1149]
Related to #1146
When uploading files that are bigger than the chunk size, it fails as the array for the chunks is not filled correctly. The issue is in here:
```javascript
if (size) {
  c++;
}
if (typeof sfiles[c] == 'undefined') {
  sfiles[c] = [];
  if (isDataType) {
    sfiles[c][0] = [];
    sfiles[c][1] = [];
  }
}
size = fm.uplMaxSize;
```

As the value of c is never incremented (because fm.uplMaxSize is 0). One possible solution is to change that assignment, but I don't know if the variable size is used elsewhere.

**Comment by nao-pon** [comment]
@fauri13 Thanks! :+1:
