### ISSUE TITLE
MP3 Type showing as Application

### ISSUE THREAD

**Issue by kirakhaos** [Studio-42/elFinder#1152]
The file type is MP3, but it is showing as an application instead, how can I fix this?

**Comment by nao-pon** [comment]
@kirakhaos elFinder sends HTTP header "Content-Disposition: inline" by image, text and flash only. And this is not configurable. So I'll make to configurable it by volume driver option.

Thanks!

**Comment by barryvdh** [comment]
@kirakhaos Can you see what the actual mimetype is (not extension) for the file, as returned by the driver? Which driver is it? `audio/mpeg` should display as MP3, but some might use `audio/mpeg3` or `audio/mp3` instead, which isn't recognized.

**Comment by nao-pon** [comment]
I seem to have been misread. Is this issue miss the detection of file type?

**Comment by nao-pon** [comment]
If you want to correct the MIME type of detection,　There is an option `mimeMap` in Volume driver options.

default is
```php
// mime type normalize map : Array '[ext]:[detected mime type]' => '[normalized mime]'
'mimeMap'         => array(
                     'md:application/x-genesis-rom' => 'text/x-markdown',
                     'md:text/plain'                => 'text/x-markdown',
                     'markdown:text/plain'          => 'text/x-markdown',
                     'css:text/x-asm'               => 'text/css'
                    ),
```
