### ISSUE TITLE
Cut and Copy actions stay in context menu even if disabled

### ISSUE THREAD

**Issue by AlgirdasR** [Studio-42/elFinder#1154]
I'm wondering why copy and cut actions are not checking whether they're disabled in right click context menu.
If you disable "cut" and "copy" in connector, these actions only get removed from the toolbar, but not from the context menu.

I saw another thread about removing them manually in client config (https://github.com/Studio-42/elFinder/issues/517), but  this seems like a hack.

Shouldn't their getstate method check for "this._disabled" ?

I'm talking about 
```javascript
	 elFinder.prototype.commands.copy = function() 
	 {
	 	 this.getstate = function(sel) {
		 var sel = this.files(sel),
		 cnt = sel.length;
	 
		 return cnt && $.map(sel, function(f) { return f.phash && f.read ? f : null  }).length == cnt ? 0 : -1;
 	  	 }
  	 }
```

---->

```javascript
return !this._disabled && cnt && $.map(sel, function(f) { return f.phash && f.read ? f : null  }).length == cnt ? 0 : -1; 
```

**Comment by nao-pon** [comment]
@AlgirdasR Thanks! :+1:
