### ISSUE TITLE
AccessControl before bind

### ISSUE THREAD

**Issue by alsantos123** [Studio-42/elFinder#1155]
Hello.

I'm starting use elFinder with my custom file permission, in such way: Only owner of file have write permission, everyone else have only read permission on files.

I have in my connector options a bind:
```php
'bind' => array(
            'mkdir mkfile rename duplicate upload rm paste put resize archive' => 'myBindCallback'
          )
```

So, the 'myBindCallback' function create a record of a new file associated to current logged user, for further use.
So far so good, now on each file added in elFinder, I have a record.

So I follow up with:
```php
'roots' => array(
            array(
              'driver'            => 'LocalFileSystem',  
              'path'              => $path, // path to files (REQUIRED)
              'accessControl'     => 'myAccessControl' , 
              'accessControlData' => $lstUserFiles,
            )
```

In 'myAccessControl' function I check if the current logged user has the $path (file) in your list of files ($lstUserFiles).

```php
 /*
 * @param  string  $attr  attribute name (read|write|locked|hidden)
 * @param  string  $path  file path relative to volume root directory started with directory separator
 * @param  mixed   $lstUserFiles
 * @return bool|null
 **/
function myAccessControl($attr, $path, $lstUserFiles, $volume)
{
     if( isset( $lstUserFiles[$path] ) )
     {
         if( $attr == 'write' || $attr == 'read' )
                  return true;
                else 
                   return false;
            }
            else
            {
                if( $attr == 'write' || $attr == "hidden" )
                  return false;
                else
                  return true;
            }
    }
}
```

Everything works fine, until the user uploaded a new user. The order of execution is: first invoke the 'controlAccess' then the 'bind' function is invoked.

In this way, when a new file is added, via elFinder, the record that associate the user with the file is not created before controlAccess is invoked. 

First, the file is added with success, but the file is locked for the user, after a refresh, on current folder, the user could delete, move or rename his file.

Existis any way to know in 'controlAccess' function, when the $path (a file) is new?

Cheers!

**Comment by alsantos123** [comment]
I discovered that if my 'bind' function returns true, the client will refresh (sync). This almost did the trick but the toolbar of elFinder client keeps with rename and delete actions locked.

**Comment by nao-pon** [comment]
@alsantos123 You can modify array $result in callback.

for exmple
```php
if (!empty($result['added']) {
	foreach($result['added'] as $i => $v) {
		$result['added'][$i]['write'] = 1;
	}
}
```

**Comment by alsantos123** [comment]
Thanks nao-pon.

Works like a charm!

**Comment by nao-pon** [comment]
:+1:

**Comment by paulcanning** [comment]
@alsantos123 I assume your `$lstUserFiles` is an array of folders/files that specific user can access? I'm looking to implement something similar and using the accessControl this way might be the thing I need

**Comment by alsantos123** [comment]
Yes, it is, array of files. For each file that user added to repo a record in database is created.

**Comment by paulcanning** [comment]
Can you give an example of your array? I got this working, but the array had to be structured as such:

```
array(
    'path/to/folder' => true
)
```

instead of simply

```
array(
    'path/to/folder'
)
```

Also it seems like you need full file paths. Ideally I'd like to just put a folder name to allow access to it and all files in it.
