### ISSUE TITLE
Url back

### ISSUE THREAD

**Issue by maga97** [Studio-42/elFinder#1157]
Hi how can I get the url of the selected/uploaded file?
For example I will open your file manager when i click on an input text field so after I choose the file how can his position on the file system to run a query? 
Thank you

**Comment by nao-pon** [comment]
@maga97 You can use client configure [`getFileCallback`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#getFileCallback).

```javascript
<script type="text/javascript" charset="utf-8">
    $().ready(function() {
        var elf = $('#elfinder').elfinder({
            getFileCallback : function(file) {
                window.console.log(file);
            },
            url : 'php/connector.php'
        }).elfinder('instance');
    });
</script>

And closes so it is not a elFinder problems.
```
