### ISSUE TITLE
Upload Files and Create File options disabled in FTP

### ISSUE THREAD

**Issue by snazzysano** [Studio-42/elFinder#1159]
I've setup exactly as said in documentation, and it shows the files, but I can't upload or edit any files. The Upload buttons are disabled.
Please help me...

My Config.:
$opts = array(
	'roots' => array(
        array(
            'driver'      => 'FTP',
            'host'        => '****************',
            'user'        => '****************',
            'pass'       => '****************',
	    'mode'      => 'passive',
	    'owner'     => true,
            'path'        => '/public_html/zero/',
	    'mimeDetect'  => 'auto',
	    'owner'       => true,
            'dirMode'     => 0755,
	    'fileMode'    => 0755,
	    'tmbPath'     => '',
   	    'tmpPath'     => '',
	    'attributes' => array('read'    => true, 'write'   => true),
	    'uploadAllow' => array('image','application','document'),
	    'defaults'    => array('read' => true, 'write' => true),
            'alias'       => 'My FTP'
        ) )
)

P.S.: Folder Creation and Delete(both file and folder) works...

**Comment by nao-pon** [comment]
@snazzysano  
First of all, check with a minimum of options. Then, please set with an understanding of each option.

```php
array(
    'driver'        => 'FTP',
    'host'          => 'localhost',
    'user'          => 'eluser',
    'pass'          => 'elpass',
    'port'          => 21,
    'mode'          => 'passive',
    'path'          => '/'
)
```

I close this, because this issue is not a issue of elFinder.
