### ISSUE TITLE
LocalFileSystem driver not working

### ISSUE THREAD

**Issue by snazzysano** [Studio-42/elFinder#1160]
elFinder says "Invalid Backend configuration. Readable volumes not available." When uploading using ftp, I use "/public_html/" location for uploading files

I have the following configuration,
$opts = array(
	'roots' => array(
        array(
			'driver'        => 'LocalFileSystem',  
			'path'          => '/', 
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/', 
			'accessControl' => 'access',
			'alias'       => 'My Storage'
		)
	)
);

Please help me...

**Comment by nao-pon** [comment]
@snazzysano `path` should be an absolute path on the server.

I close this, because this issue is not a issue of elFinder.
