### ISSUE TITLE
download link in right click menu

### ISSUE THREAD

**Issue by la0wei** [Studio-42/elFinder#1161]
I like elfinder because it support absolute path
like http:///xxx.com/abc.zip,
not http://xxx.com/?page=download&archiveName=abc.zip
but one thing curios,why there is no option in menu that gives download path,I should right click the file and click the file info and then show me the link.why not get the link straight in the menu?
I want to download large files by file download manager,not browser.

**Comment by nao-pon** [comment]
ref. #916

**Comment by la0wei** [comment]
Good job!
