### ISSUE TITLE
Second param to class_exists should always be set to false.

### ISSUE THREAD

**Issue by twisted1919** [Studio-42/elFinder#1162]
Throughout the code `class_exists` calls don't have a second param set to false, which triggers any autoloader if the class does not exists, which is wrong behavior.

**Comment by nao-pon** [comment]
@twisted1919 You're right. I'll fix this.

Thanks! :+1:

**Comment by barryvdh** [comment]
I think you should use false for the native php classes like Imagick and PDO, but you should autoload the volume driver with true.
