### ISSUE TITLE
Uploading Microsoft Word document *.doc file not work with MIME-type restrictions and "application/msword" MIME-type

### ISSUE THREAD

**Issue by ry-ks** [Studio-42/elFinder#1165]
Uploading *.doc file fails if "application/msword" defined by IANA (ftp://ftp.iana.org/assignments/media-types/) is used in php/connector.php file as allowed MIME-type. Problem occured on elFinder 2.1.4.

In php/connector.php I have:

    $opts = array(
        // 'debug' => true,
        'roots' => array(
            array(
                'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
                'path'          => '../files/',                 // path to files (REQUIRED)
                'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
                'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
                'uploadAllow'   => array(
                    'application/msword',
                    //'application/vnd.ms-word',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                    'image',
                    'text/plain',
                ),
                //'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed     to upload
                'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
                'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
            )
        )
    );

if uncomment string `'application/vnd.ms-word'` then upload is successfuly finished.

I found in php\elFinderVolumeDriver.class.php the folowing definition:

    protected static $mimetypes = array(
        // ...
        'doc'   => 'application/vnd.ms-word',
        // ...
    )

May we fix with issue to use standard MIME-type "application/msword" for Microsoft Word documents with doc extensions?

**Comment by nao-pon** [comment]
@ry-ks I think so, that's correct. I'll fix this issue. Thanks! :+1:
