### ISSUE TITLE
[Question] Only create, no permission create, rename. Remove special characters. Unique file.

### ISSUE THREAD

**Issue by nguyentuansieu** [Studio-42/elFinder#1169]
Hello, Everyone!

- I want make permission only create file and folder, no permission create, rename.
- Remove any special characters example:
hình ảnh về quê hương.jpg to hinh-anh-ve-que-huong.jpg or hnh-nh-v-qu-hng.jpg

- Auto add number for file (no duplicate file). example exists file hinh-anh.jpg. if I upload file hinh-anh.jpg. it will rename to hinh-anh-1.jpg

Thank you!

**Comment by nao-pon** [comment]
> I want make permission only create file and folder, no permission create, rename.

use connector volume root option `disabled` - https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#disabled

> Auto add number for file (no duplicate file). example exists file hinh-anh.jpg. if I upload file hinh-anh.jpg. it will rename to hinh-anh-1.jpg

use connector volume root option `uploadOverwrite` - https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#uploadoverwrite

> Remove any special characters example

I added new option `convmap` to plugin `Normalizer` at 171f5c6eb593730f43e8e8d66444363d1e0d3e5f

- Normalizer - https://github.com/Studio-42/elFinder/blob/2.x/php/plugins/Normalizer/plugin.php

config option example
```php
'plugin' => array(
	'Normalizer' => array(
		'convmap' => array(
			' ' => '_',
			'ä' => 'a',
			'ả' => 'a',
			'ê' => 'e',
			'ề' => 'e',
			'ì' => 'i',
			'ö' => 'o',
			'ơ' => 'o',
			'ư' => 'u'
		)
	)
)
```
