### ISSUE TITLE
elFinder v2.1.x allows opening uploaded scripts creating a possible security issue

### ISSUE THREAD

**Issue by dleffler** [Studio-42/elFinder#1170]
It is possible to upload a (html) file with a javascript XSS payload, and then open it from within elFinder regardless of the server settings.  The server settings will prevent opening it when the url link is clicked in the info dialog, but the file will be opened when it is double-clicked file or selected using the 'Open' command.

**Comment by nao-pon** [comment]
@dleffler What about next solution?

define class elFinderMyPluginDownloadCtrl
```php
class elFinderMyPluginDownloadCtrl
{
	public static function cmdPreprocess($cmd, &$args, $elfinder, $volume) {
		if (empty($args['download']) && ($file = $volume->file($args['target']))){
			if (!preg_match('/^image/i', $file['mime'])) {
				$args['download'] = true;
			}
		}
		return true;
	}
}
```

And use it as callback in connector configure

```php
'bind' => array(
	'file.pre' => array(
		'elFinderMyPluginDownloadCtrl::cmdPreprocess'
	)
)
```

**Comment by nao-pon** [comment]
@56906b799722a1bee3a82fded5a9d189f05b6f97 allow change MIME type by 'file.pre' callback functions.

example
```php
class elFinderMyPluginDownloadCtrl
{
	public static function cmdPreprocess($cmd, &$args, $elfinder, $volume) {
		if (empty($args['download']) && ($file = $volume->file($args['target']))){
			if (preg_match('#^text/html$#', $file['mime'])) {
				$args['mime'] = 'text/plain';
			} else if (!preg_match('/^image/i', $file['mime'])) {
				$args['download'] = true;
			}
		}
		return true;
	}
}
```

AND

```php
'bind' => array(
    'file.pre' => array(
        'elFinderMyPluginDownloadCtrl::cmdPreprocess'
    )
)
```

**Comment by dleffler** [comment]
Will probably work (I have a custom 'open' command to circumvent the issue), but the ticket was opened since out-of-the-box, it is a security issue which might sneak by the implementor.

**Comment by nao-pon** [comment]
elFinder 2.1.3+ has volume root option `dispInlineRegex` - https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#dispinlineregex

We can use this option. ex. `'dispInlineRegex' => '^(?:image|text/plain$)'`. What about it?
