### ISSUE TITLE
Create Archive and Extract Archive (Icon toolbar and contestual menu) question

### ISSUE THREAD

**Issue by kipper65** [Studio-42/elFinder#1171]
Hi all!
sorry for my bad english...
elFinder-2.0.5

How should I do to activate the two icons in the toolbar (Create Archive / Extract Archive). Everything works fine but those two icons are visible but are not activated...
I also need these two functions in the context menu of the right mouse button.

I spent many hours but I can not fix :(

Many Thanks in advanced

**Comment by nao-pon** [comment]
@kipper65 To achieve it must be able to perform the archive and extract command in your server. Or need [`ZipArchive`](http://php.net/manual/en/class.ziparchive.php) class on elFinder 2.1 .

**Comment by kipper65** [comment]
OK Naoki,

 

Many Thanks!

 

Da: Naoki Sawada [mailto:notifications@github.com] 
Inviato: giovedì 31 dicembre 2015 16:52
A: Studio-42/elFinder <elFinder@noreply.github.com>
Cc: kipper65 <giuliano@nespoli.eu>
Oggetto: Re: [elFinder] Create Archive and Extract Archive (Icon toolbar and contestual menu) question (#1171)

 

@kipper65 <https://github.com/kipper65>  To achieve it must be able to perform the archive and extract command in your server. Or need  <http://php.net/manual/en/class.ziparchive.php> ZipArchive class on elFinder 2.1 .
