### ISSUE TITLE
Windows: Invalid backend configuration. Readable volumes not available

### ISSUE THREAD

**Issue by heikobihlmaier** [Studio-42/elFinder#1173]
Hello!
Within my windows 10 environment I get the error "Invalid backend configuration. Readable volumes not available" when I open the elfinder.
The folder within the public dir exists and the path is absolute.

Debugbar-Output:
array:1 [
0 => array:4 [
"driver" => "LocalFileSystem"
"path" => "E:\Entwicklung\htdocs\cms\public\files"
"URL" => "http://cms.dev/files"
"accessControl" => "Barryvdh\Elfinder\Elfinder::checkAccess"
]
]

When I load my application into the web with a linux webserver all is okay and I got no error.
I try to debug and it seems, that elfinder cannot mount the folder.

Can u help me here ?

Thanks.

https://github.com/barryvdh/laravel-elfinder/issues/115

**Comment by programmator** [comment]
> 'Undefined index: tmpPath' in \vendor\studio-42\elfinder\php\elFinderVolumeLocalFileSystem.class.php:57

**Comment by nao-pon** [comment]
@heikobihlmaier Prease try `"path" => "E:\\Entwicklung\\htdocs\\cms\\public\files"` or `"path" => "E:/Entwicklung/htdocs/cms/public\files"`

@programmator I'll fix Notice error.

Thanks!
