### ISSUE TITLE
Two elFinder instance on same page not work

### ISSUE THREAD

**Issue by rajasharma27** [Studio-42/elFinder#1174]
Sir, i am facing problem with two elFinder instance on same page.
first instance work fine, but second instance missing or hide folder tree view.

**Comment by rajasharma27** [comment]
this issue facing when elFinder & ckEditor both using on same page.

**Comment by nao-pon** [comment]
@rajasharma27 This is a bug of elFinder. I'll fix it.

Thanks!

**Comment by rajasharma27** [comment]
Thanks Sir,

Now is working fine
