### ISSUE TITLE
AutoResize (plugin) change DPI option

### ISSUE THREAD

**Issue by santaclaus21** [Studio-42/elFinder#1175]
I was wondering about possibility of change DPI in AutoResize Plugin. 

The resason, www popup:
- orginal: JPG 2666x1780, 300DPI (5.8MB!)
- uploaded with plugin (max: 1024:1024, q:85) > 1024x684, 300DPI (2.75MB!) Nothing happened on change quality: 10-90% (connector, and directly in plugin file). Always 2.75MB :(

On website I am using 72DPI (most popular), then file size will be ~100-200kB.
Probably it's possible to change by PHP (http://www.scriptscoop.net/t/dbed0c90633d/having-difficulty-changing-dpi-on-jpeg-with-php.html).

It can be BIG improvement. Orginal image at bottom of topic.

![okropnie duze 2](https://cloud.githubusercontent.com/assets/1121662/12086838/f8ddd60e-b2cd-11e5-9970-922fb516866e.jpg)

**Comment by nao-pon** [comment]
@santaclaus21 I fixed it. It was typo of example code and bug of Imagick function.

Example typo 'PluginAutoResize'. Correctly is 'AutoResize'.
ref. https://github.com/Studio-42/elFinder/commit/53abae10c8833eec329e099022599b48353ca9f9#diff-0eb5195a4a782c3d035821c6f83c9ae6L16

Thanks!

**Comment by santaclaus21** [comment]
It works great! Thank you very much @nao-pon and Happy New Year :)
