### ISSUE TITLE
Feature request: monitor changes using HTTP long polling and inotify/gamin

### ISSUE THREAD

**Issue by priyadi** [Studio-42/elFinder#1176]
It should be possible for any changes in the filesystem to be reflected immediately in elFinder as it happens. Possible mechanism:

* Client sends 'monitor' command with hash and mtime as parameter. Client expects this command will be a long running request.
* Backend records current state of directory, takes the mtime and compare it to the current mtime. If they are different, wait 5 seconds and send the current state to the client.
* If mtimes are the same, put an inotify on the directory. If anything happens, scan for changes and send them to the client. If nothing happens after 30 seconds, send empty changes.
* Client gets the results and update the view if necessary. Client sends 'monitor' command again.

Obviously this should be optional as this won't be feasible with some backends.

**Comment by nao-pon** [comment]
@priyadi elFinder has an option [`sync`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#wiki-sync). However, its function is simplified. I get on with its expansion.

**Comment by priyadi** [comment]
With the sync option, changes are not always immediately seen. We can lower the interval, but it would put an unnecessary work to the server and the browser.

**Comment by nao-pon** [comment]
OK! I done long polling with elFinder stat() on my local server. Next is long polling with `inotifywait` ;-)
