### ISSUE TITLE
Set elFinder upload directory to a UNC path

### ISSUE THREAD

**Issue by Jahedur** [Studio-42/elFinder#1180]
I tried to set a UNC path to elFinder. I have set this in File and Home controllers. When i run the application, it displays the list of directories and files properly. But when i try to open (double-click) a file, it cannot open and displays a message like "c:\inetpub\wwwroot\elfinder\files\test\abc.txt" not found (http error 404.0 - Not Found). But the folder i configured was from a different server that is "\\testserver\files\test\abc.txt".

The problem i assume here is the file url that the application uses is like "http://elfinder/files/test/abc.txt". But the file does not exist at this location. It is located at the unc path.

Please let me know if you have questions. Thanks in advance.

**Comment by nao-pon** [comment]
@Jahedur Please try unset connector root option `URL`.

```php
$opts = array(
    'locale' => '',
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            // (unset) 'URL'    => 'http://localhost/to/files/'
        )
    )
);
```

**Comment by Jahedur** [comment]
Thanks Nao-pon for your response. I will try this. But the unset url seems to be an web url. Would this allow me to set an UNC path like \\fileservername\files\projects\a\abc.docx?

**Comment by nao-pon** [comment]
OK. Please try file URI scheme. ex.  `'URL' => 'file://fileservername/files/',`

**Comment by nao-pon** [comment]
I close this. Please re-open if necessary.

**Comment by Lexipowder** [comment]
My Settings are:
'driver'        => 'LocalFileSystem',  
'path' => //fileservername/Projects/2015/xxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxx_xxxxxxx
'URL' => file:////fileservername/Projects/2015/xxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxx_xxxxxxx
and I'm having the issue as described above, what was the solution?
I see the correct Folder, but if I upload a file, I find it in //fileservername ?

**Comment by nao-pon** [comment]
@Lexipowder Your upload file is into "//fileservername/Projects/2015/xxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxx_xxxxxxx".

**Comment by Lexipowder** [comment]
Sorry, 
it was late yesterday, typing error. 
The setting was 
'URL' => file://fileservername/Projects/2015/xxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxx_xxxxxxx
I changed it to:
'URL' => //fileservername/Projects/2015/xxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxx_xxxxxxx
or
'URL' => //fileservername/Projects/2015/xxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxx_xxxxxxx/
or
'URL' => '//fileservername/Projects/2015/xxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxx_xxxxxxx'
or
'URL' => '//fileservername/Projects/2015/xxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxx_xxxxxxx/'

same result.

Any other Idea? Thanks for your help.

**Comment by nao-pon** [comment]
@Lexipowder To open the location of the file scheme from http scheme of the site you will need to change the browser's security settings. The method is different from the browser. Please try to search on Google.
