### ISSUE TITLE
elFinder with existing S3 buckets

### ISSUE THREAD

**Issue by sheldmandu** [Studio-42/elFinder#1183]
Hi guys, just thought I'd raise that the current implementation of VolumeS3 doesn't seem to work all that great if you're trying to get it to work with an existing S3 bucket (rather than starting with elFinder from scratch).  I've had a look at the code and it seems to have to do with _scandir relying on how elFinder creates directories in S3 in _mkdir.  What would work better and would be more universal is if you used CommonPrefixes returned in the ListBucket response for determining the directories and Contents for files.  This would make it more universal and in-line with how Amazon recommends getting a list of directories.  You also seem to have an empty if statement in there so seems like it's work in progress.

**Comment by nao-pon** [comment]
@sheldmandu s3 driver of elFinder is not active now. As other solution, you can try [flysystem drivers](https://github.com/barryvdh/elfinder-flysystem-driver).

- https://github.com/barryvdh/elfinder-flysystem-driver

In addition, we are looking for a maintainer of s3 driver...

**Comment by troex** [comment]
see #1015
