### ISSUE TITLE
MySQL save on Upload / delete file

### ISSUE THREAD

**Issue by BibiSeal** [Studio-42/elFinder#1184]
Hello,

I want to save in my database filename on Uploading and delete recordwhen the file is deleting.
So i use handlers to to this : 
handlers : {
                        upload : function(event, elfinderInstance) {
                            console.log('UPLOAD');
                            console.log('Upload : ' + (event.data));
                            console.log('Upload : ' + event.data.file[0])
                        },
                        remove : function(event, elfinderInstance) {
                            console.log('DELETE');
                            console.log('Delete : ' + (event.data));
                            console.log('Delete : ' + (event.data.selected)); // selected files hashes list
                        }

But how can i have the name of the file are uploaded or deleted ?
Thanks to your help.

**Comment by nao-pon** [comment]
What about connector configuration options#bind ? - https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#bind

**Comment by nao-pon** [comment]
I close this. Please re-open if necessary.
