### ISSUE TITLE
All search location doesn't work properly

### ISSUE THREAD

**Issue by mleko64** [Studio-42/elFinder#1187]
Hello!
"All" search location doesn't work for me, I'm using lastest version 2.1.5.
When I type something in search input and choose "All" location I get "Error backend respone".
I think the problem is in elFinder.class.php file (near line 2098, method "search").
I dumped $args variable and this is my response:
```
array (size=5)
  'q' => string 'tulips' (length=5)
  'mimes' => string '' (length=0)
  'target' => string 'null' (length=4)
  'debug' => string '' (length=0)
  'sessionCloseEarlier' => boolean true
```
Please note the "target" key. Value is a string instead a null value.
So, in elFinder.class.php file (near line 2098, method "search") is there if-statment:
```
if (!is_null($target)) {
	$volume = $this->volume($target);
	$result = $volume->search($q, $mimes, $target);
} else {
	foreach ($this->volumes as $volume) {
		$result = array_merge($result, $volume->search($q, $mimes));
	}
}
```
In my case $target variable is not NULL (variable is a string with "NULL" value), so this condition:
```
if (!is_null($target)) {
```
is always TRUE. For "All" location search, script should execute else block.

Can someone test and confirm this issue?

**Comment by nao-pon** [comment]
@mleko64 Probably cause I think to be due to differences in each version of PHP. Maybe now this problem has been fixed.　Thanks! :+1:
