### ISSUE TITLE
Drag & Drop file uplaod is not working

### ISSUE THREAD

**Issue by jaganathpanda** [Studio-42/elFinder#1189]
Hi,
 I have downloaded and install elfinder using Java. For me drag and drop from local machine to dropzone area is not working. Please help me.

**Comment by nao-pon** [comment]
Probably, Java connector works with elFinder 2.0. Try 2.0.x or less. In addition, the problem of JAVA connector, please post to https://github.com/Studio-42/elfinder-servlet/issues.
