### ISSUE TITLE
Open an html file is not rendered according to the .htaccess directives

### ISSUE THREAD

**Issue by mlerman** [Studio-42/elFinder#1193]
I have an html file sitting in a directory where I have also .htaccess directives.
When I open the file with elFinder, the file is not rendered according to the .htaccess file.
Earlier revision of elFinder was fine.

**Comment by nao-pon** [comment]
@mlerman Please check out new connector roots option `dispInlineRegex`.

- https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#dispinlineregex

**Comment by mlerman** [comment]
Thank you. I tried but it doesn't make a difference.It allows the popup window and display the content of the file as text.I want the content to be rendered by the browser.Also for images for example here it download the file instead of displaying it. 

 Regards,MiKL~408 564 9578 : Cell408 538 0490 : Voicemail/Text/SMS
ManEstate.com In the meantime connect with me using one of your accounts :

|  |  |  |

**Comment by nao-pon** [comment]
Do you want to open the HTML file as plain text? Well What's the next solution?

```php
function elFinderMyFileCtrl($cmd, &$args, $elfinder, $volume) {
    if ($file = $volume->file($args['target'])) {
        if (preg_match('#^text/html$#', $file['mime'])) {
            $args['download'] = false;
            $args['mime'] = 'text/plain';
        }
    }
    return true;
}

$opts = array(
    'roots'  => array(
        array(
            'dispInlineRegex' => '^(?:image|text/(?:plain|html)$)',
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    )
    'bind' => array(
        'file.pre' => array(
            'elFinderMyFileCtrl'
        )
    )
);


// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```

**Comment by mlerman** [comment]
No actually I don't want it to open as text.Actually I have an html file but it is fake.The filename is open-command-prompt-here.html and his content doesn't matter. It is actually a php file.In the .htaccess file in the same directory
AddType application/x-httpd-php .htmlRewriteEngine on # Turn on the rewriting engine
RewriteRule open-command-prompt-here.html /common/open-command-prompt-here.html?&requri=%{REQUEST_URI}&reqfname=%{REQUEST_FILENAME} [L]
Then when I open the file open-command-prompt-here.html I don't want to see the content but I want another file to render (/common/open-command-prompt-here.html etc...)
It was working fine in an earlier version of elfinder.I just want it to render normally as if it was not intercepted by elfinder.

 Regards,MiKL~408 564 9578 : Cell408 538 0490 : Voicemail/Text/SMS
ManEstate.com In the meantime connect with me using one of your accounts :

|  |  |  |

**Comment by nao-pon** [comment]
Okey, I understood. I'll fix it. Please wait untile 2.1.6 release.

**Comment by nao-pon** [comment]
I fixed it. Please check out 2.1 nightly.

- https://github.com/Studio-42/elFinder/archive/2.1.zip

**Comment by mlerman** [comment]
Thank you I will check. Your project is fabulous. I love it :)

 
 
  On Sun, Jan 17, 2016 at 11:15 PM, Naoki Sawada<notifications@github.com> wrote:   
I fixed it. Please check out 2.1 nightly.
   
   - https://github.com/Studio-42/elFinder/archive/2.1.zip

**Comment by mlerman** [comment]
Perfect! it works :) Regards,MiKL~408 564 9578 : Cell408 538 0490 : Voicemail/Text/SMS
ManEstate.com In the meantime connect with me using one of your accounts :

|  |  |  |

**Comment by nao-pon** [comment]
:+1:
