### ISSUE TITLE
Does Amazon S3 is working ?

### ISSUE THREAD

**Issue by Arnaud-Woufbox** [Studio-42/elFinder#1194]
It's impossible for me to do work elFinder with Amazon S3, does anyone has a config example, or maybe this driver does not work ?
Thanks you

**Comment by barryvdh** [comment]
You can try this if you want: https://github.com/barryvdh/elfinder-flysystem-driver

**Comment by Arnaud-Woufbox** [comment]
@barryvdh thank you !
