### ISSUE TITLE
Request: Creation Date and modification thereof

### ISSUE THREAD

**Issue by rarawls** [Studio-42/elFinder#1196]
Would it be difficult to add functionality for displaying (and perhaps modifying) the creation date of a file?  For example, you scan your tax documents and want to make the date of the file match the date of the document, not the date of the digital file.

I've looked everywhere for a web-based file manager that has this functionality.  Anyone know where I may have missed one?

**Comment by nao-pon** [comment]
@rarawls 

(Google translated)
Common file system does not support the file creation date and time. Therefore, there will be a need to implement and extend the such as MySQL driver to handle it in elFinder.

For now, there are no plans to incorporate this feature as this project.
