### ISSUE TITLE
issue with dialog/tabs 

### ISSUE THREAD

**Issue by p0tvin29** [Studio-42/elFinder#1197]
I'm having this issue when i include elfinder inside my dialog w/tabs. The footer part overlaps the actual height size but once I resize the navbar (red circle) it auto-resizes perfectly. Anyone know how to fix this?

It looks like this at first:
![elfinder-messed](https://cloud.githubusercontent.com/assets/6618644/12602461/88e5c33c-c477-11e5-82fa-79b52d21b9df.png)

Then after I resize the navbar (red circle):
![elfinder-fixed](https://cloud.githubusercontent.com/assets/6618644/12602469/9de3c8a6-c477-11e5-965a-0d253d72858b.png)

This is my connector php config:
$opts = array(
	//'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => 'C:/www/Files',                 // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../../Files', // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array(	
					'image', // any image
					'video', // any video
					'audio' // any audio
					),
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access',                     // disable and hide dot starting files (OPTIONAL)
			'alias' 		=> 'FILES',
			'uploadMaxSize' => '10M'
		),
		array(
			'driver'	=> 'FTP',
			'host'		=> 'ftp.company.com',
			'user'		=> 'test',
			'pass'		=> 'test123',
			'path'		=> '.',
			'alias'		=> 'FTP',
        )
	)
);

and jquery config:
$('#filemanager').elfinder({
		url: '/php/connector.minimal.php',
		defaultView: 'list',
		resizable: false,
		height: 475
	});

**Comment by nao-pon** [comment]
@p0tvin29 Please try trigger `resize` event on tab open.
```javascript
$('#filemanager').trigger('resize');
```

**Comment by p0tvin29** [comment]
Yeah that fixed it..thanks!

**Comment by nao-pon** [comment]
:+1:
