### ISSUE TITLE
Can't upload larg file?

### ISSUE THREAD

**Issue by kjll3r2002** [Studio-42/elFinder#1198]
Hi everybody,

When I choose a larg file to upload, uploader procees is success but file saved with "blob" and it can't to open! I'm using MVC ([Source code](https://elfinder.codeplex.com/SourceControl/latest)) is backend.
Please help me fix it.

Thanks..

P/s: sorry my language is bad..

**Comment by nao-pon** [comment]
@kjll3r2002  Probably ElFinder.Net is not support elFinder 2.1. Please use elFinder 2.0.

**Comment by kjll3r2002** [comment]
Thanks u... it's work!

**Comment by nao-pon** [comment]
elFinder 2.1.7 will support the legacy connector.

ref. 0de3714a44dca8964bff53882e7ed492816d791a
