### ISSUE TITLE
Unable to connect to backend. 

### ISSUE THREAD

**Issue by vladvisinescu** [Studio-42/elFinder#1199]
I know this error popped up for a lot of people, but I didn`t get any resolution.

After following the instructions for integrating tinymce with elfinder I keep getting this error when openning elfinder:

```
Unable to connect to backend.
```

In my Console I get this as a response:

```
ErrorException in ClassLoader.php line 412:
include(/home/test/public_html/dev/vendor/studio-42/elfinder/php/elFinderConnector.class.php): failed to open stream: No such file or directory
```

Reading through other people\`s issues I should point out I\`m on a subdomain (dev). Should this be a problem? Or am I doing something else wrong?

Thanks!

**Comment by nao-pon** [comment]
It looks like there is a problem with your ClassLoader.php.

**Comment by kfelahiju** [comment]
This is because elFinderConnector.class.php not exist in the directory. Check the directory and see elFinderConnector.class.php really does exists or not. 

If the file doesn't exist then get a copy from master branch. This will work.
