### ISSUE TITLE
upload file button not appears

### ISSUE THREAD

**Issue by standus** [Studio-42/elFinder#1200]
When I run EF as popup window from CKEditor it works, but when I integrate into my html page then upload button not work (is clickable but no action), same as D&D:
elfinder debug: [error] [elfinder] Upload error.<br>No files found for upload.

All other buttons and functions works normal.
I have same jQuery 2.1.4 + migrate plugin.

**Comment by nao-pon** [comment]
@standus I was checked on elFinder 2.1.x (master nightly) +  jQuery 2.1.4 + migrate plugin. It has no problems. Please double check your configuration.

**Comment by standus** [comment]
![ef](https://cloud.githubusercontent.com/assets/4818430/12637399/3fa8f13e-c595-11e5-8e91-c28b4aab171b.jpg)
Here is image when button getfile is initialized.
I checked many times and can not find problem why button is clickable and not work.

**Comment by standus** [comment]
![ef1](https://cloud.githubusercontent.com/assets/4818430/12637511/415cb942-c596-11e5-9ce3-86742d49d8ea.jpg)
You can see on picture, that button is clickable, and after click no any error message about any problem.

**Comment by nao-pon** [comment]
The upload button is replaces to `<form>` by "$.fn.elfinderuploadbutton". It HTML is
```html
<div title="Upload files" class="ui-state-default elfinder-button">
 <span class="elfinder-button-icon elfinder-button-icon-upload"></span>
 <form style="display: block;">
  <input multiple="true" title="Select files to upload" type="file">
 </form>
</div>
```
And click event is called the system event handler.

Other JavaScript affect in your HTML page?

**Comment by standus** [comment]
Which function is called for upload? And what function execute on "click" event?

**Comment by nao-pon** [comment]
elFinder is not regist click event. on `<input>` change call [handler of elfinderuploadbutton](https://github.com/Studio-42/elFinder/blob/aa838caebe9a46b8d645da9ffef68e90780f35cf/js/ui/uploadButton.js#L13)

![0c701cfd](https://cloud.githubusercontent.com/assets/1412630/12642646/7e2e9e6c-c5fa-11e5-90dd-31b6b52a212e.png)

You can check on my [develop site](http://hypweb.net/elFinder-nightly/demo/develop/).

**Comment by standus** [comment]
I found problem.
I have own css for input file for some special functionality:
input[type="file"] {
    display: none;
}
So, it will be useful, when you define style for your input directly.
Thank you for.

**Comment by standus** [comment]
This is my request and response:
Request URL:http://localhost/libs/elfinder/php/connector.php?cmd=upload&target=l1_aW1hZ2Vz&name%5B%5D=!BZ1Hqu!CGk-%24(KGrHgoH-C8EjlLlh!lGBKopHKr%2Cgw--_12.JPG&FILES=&_=1454015329151
Request Method:GET
Status Code:200 OK
Remote Address:127.0.0.1:80

Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost https://localhost
Cache-Control:no cache
Connection:keep-alive, Keep-Alive
Content-Length:42
Content-Type:application/json
Date:Thu, 28 Jan 2016 21:12:45 GMT
Keep-Alive:timeout=5, max=99
Server:Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.1
Strict-Transport-Security:max-age=63072000; includeSubDomains
X-Content-Type-Options:nosniff
X-Frame-Options:SAMEORIGIN
X-Powered-By:PHP 7.0.1
X-XSS-Protection:1; mode=block

Request Headers
view source
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate, sdch
Accept-Language:cs-CZ,cs;q=0.8
Connection:keep-alive
Cookie: xxxx
Host:localhost
Referer:http://localhost/admin/fm
User-Agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
X-Requested-With:XMLHttpRequest

Query String Parameters
view source
view URL encoded
cmd:upload
target:l1_aW1hZ2Vz
name[]:!BZ1Hqu!CGk-$(KGrHgoH-C8EjlLlh!lGBKopHKr,gw--_12.JPG
FILES:
_:1454015329151
Name
Path
bmF6ZXY%3D
connector.php?cmd=upload&target=l1_aW1hZ2Vz&name%5B%5D=!BZ1Hqu!CGk-%24(KGrHgoH-C8EjlLlh!lGBKopHKr%2Cgw--_12.JPG&FILES=&_=1454015329151
/libs/elfinder/php

**Comment by nao-pon** [comment]
PHP files looks like old. Check the PHP files to update.

**Comment by standus** [comment]
I used 2.1.6 version of all sources.
But I debug first line of php connector and $_FILES is empty.

**Comment by nao-pon** [comment]
2.1 upload function send two requests. First is preflight  for filename check. That request has an empty $_FILES. Next is FILE post request. That request require $_FILES.

**Comment by standus** [comment]
I see only one request.

**Comment by nao-pon** [comment]
Probably that error sends by php/elFinder.class.php L.1868-. Try check `$args` values.
```php
if (empty($files)) {
	if (!$args['upload'] && $args['name'] && is_array($args['name'])) {
		$error = '';
		$result['name'] = array();
		foreach($args['name'] as $_i => $_name) {
			if (!$volume->isUploadableByName($_name)) {
				$error = $this->error(self::ERROR_UPLOAD_FILE, $_name, self::ERROR_UPLOAD_FILE_MIME);
				break;
			}
			$result['name'][$_i] = preg_replace($ngReg, '_', $_name);
		}
		if ($error) {
			$result['error'] = $error;
			return $result;
		}
		$result = array_merge_recursive($result, $this->ls($args));
		if (empty($result['list'])) {
			$result['name'] = array();
		} else {
			$result['name'] = array_merge(array_intersect($result['name'], $result['list']));
		}
		return $result;
	}
	if (isset($args['upload']) && is_array($args['upload']) && ($tempDir = $this->getTempDir($volume->getTempPath()))) {
		$names = array();
		foreach($args['upload'] as $i => $url) {
			// check chunked file upload commit
			if ($args['chunk']) {
				if ($url === 'chunkfail' && $args['mimes'] === 'chunkfail') {
					$this->checkChunkedFile(null, $chunk, $cid, $tempDir);
					if (preg_match('/^(.+)(\.\d+_(\d+))\.part$/s', $chunk, $m)) {
						$result['warning'] = $this->error(self::ERROR_UPLOAD_FILE, $m[1], self::ERROR_UPLOAD_TRANSFER);
					}
					return $result;
				} else {
					$tmpfname = $tempDir . '/' . $args['chunk'];
					$files['tmp_name'][$i] = $tmpfname;
					$files['name'][$i] = $url;
					$files['error'][$i] = 0;
					$GLOBALS['elFinderTempFiles'][$tmpfname] = true;
					break;
				}
			}
			
			$tmpfname = $tempDir . DIRECTORY_SEPARATOR . 'ELF_FATCH_' . md5($url.microtime(true));
			
			$_name = '';
			// check is data:
			if (substr($url, 0, 5) === 'data:') {
				list($data, $args['name'][$i]) = $this->parse_data_scheme($url, $extTable);
			} else {
				$fp = fopen($tmpfname, 'wb');
				$data = $this->get_remote_contents($url, 30, 5, 'Mozilla/5.0', $fp);
				$_POST['overwrite'] = false;
				$_name = preg_replace('~^.*?([^/#?]+)(?:\?.*)?(?:#.*)?$~', '$1', rawurldecode($url));
				// Check `Content-Disposition` response header
				if ($data && ($headers = get_headers($url, true)) && !empty($headers['Content-Disposition'])) {
					if (preg_match('/filename\*?=(?:(.+?)\'\')?"?([a-z0-9_.~%-]+)"?/i', $headers['Content-Disposition'], $m)) {
						$_name = rawurldecode($m[2]);
						if ($m[1] && strtoupper($m[1]) !== 'UTF-8' && function_exists('mb_convert_encoding')) {
							$_name = mb_convert_encoding($_name, 'UTF-8', $m[1]);
						}
					}
				}
			}
			if ($data) {
				if (isset($args['name'][$i])) {
					$_name = $args['name'][$i];
				}
				if ($_name) {
					$_ext = '';
					if (preg_match('/(\.[a-z0-9]{1,7})$/', $_name, $_match)) {
						$_ext = $_match[1];
					}
					if ((is_resource($data) && fclose($data)) || file_put_contents($tmpfname, $data)) {
						$GLOBALS['elFinderTempFiles'][$tmpfname] = true;
						$_name = preg_replace($ngReg, '_', $_name);
						list($_a, $_b) = array_pad(explode('.', $_name, 2), 2, '');
						if ($_b === '') {
							if ($_ext) {
								rename($tmpfname, $tmpfname . $_ext);
								$tmpfname = $tmpfname . $_ext;
							}
							$_b = $this->detectFileExtension($tmpfname);
							$_name = $_a.$_b;
						} else {
							$_b = '.'.$_b;
						}
						if (isset($names[$_name])) {
							$_name = $_a.'_'.$names[$_name]++.$_b;
						} else {
							$names[$_name] = 1;
						}
						$files['tmp_name'][$i] = $tmpfname;
						$files['name'][$i] = $_name;
						$files['error'][$i] = 0;
					} else {
						@ unlink($tmpfname);
					}
				}
			}
		}
	}
	if (empty($files)) {
		return array_merge(array('error' => $this->error(self::ERROR_UPLOAD, self::ERROR_UPLOAD_NO_FILES)), $header);
	}
}
```

**Comment by standus** [comment]
I changed my special input cleaners for _GET to bypas elfinder requests and now it works.
Hope that it will help you with other solutions.

**Comment by nao-pon** [comment]
OK. If you want request by POST method, you can use `requestType: 'post'` in client configuration.

- https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#requestType
