### ISSUE TITLE
soundPath always default value

### ISSUE THREAD

**Issue by standus** [Studio-42/elFinder#1201]
I defined pth to rm.wav
'soundPath'		=> realpath(dirname(__FILE__).'/..').'/sounds/',

but in <source src="' + soundPath + 'rm.wav" type="audio/wav">
is default value.

**Comment by nao-pon** [comment]
var options = {
    url  : 'php/connector.php',
    soundPath : '(URL)PATH TO SOUNDS'
}
$('#elfinder').elfinder(options);

**Comment by standus** [comment]
Sorry, I defined in $opts .

**Comment by nao-pon** [comment]
No worries. :smile:
