### ISSUE TITLE
Install page in wiki doesn't work

### ISSUE THREAD

**Issue by coyote4til7** [Studio-42/elFinder#1202]
In the very first section of the install page in the wiki (https://github.com/Studio-42/elFinder/wiki/Install), the very elFinder files to include are:
    <link rel="stylesheet" type="text/css" media="screen" href="css/elfinder.min.css">
   <script type="text/javascript" src="js/elfinder.min.js"></script>

But those files do not exist in the (zip) download from github. 
$ unzip elFinder-master.zip
$ cd elFinder-master
$ ls -R . | grep "elfinder.min.css"
$ ls -R . | grep "elfinder.min.js"

No results on either query. The closest I can find is js/elFinder.js on the js side. On the css side I can find anything

I then tried the README.md as shown on github (https://github.com/Studio-42/elFinder#installation)
Builds (compressed)
    Download and unzip one of the builds below to your PHP server
    Rename /php/connector.minimal.php-dist to /php/connector.minimal.php
    Load /elfinder.html in your browser to run elFinder

I do all that with the exception that I have elFinder in /elFinder-master and, when I open /elFinder-master/elfinder.html, Firebug doesn't find the files:
    "NetworkError: 404 Not Found - http://localhost/elFinder-master/css/elfinder.min.css"
elfinder.min.css
    "NetworkError: 404 Not Found - http://localhost/elFinder-master/js/elfinder.min.js"

Even if elFinder weirdly insists on being in / the browser should at least find the files there. BUT, they arn't there.

Can someone update the install instructions in both places so what's shown actually works? Or help me get it working and I'll fix both.

**Comment by nao-pon** [comment]
@coyote4til7 :+1: I rewrote wiki page. - https://github.com/Studio-42/elFinder/wiki/Install

README.md, that has no problems.

Thanks.

**Comment by coyote4til7** [comment]
I think the fundamental problem is that the link that got me to the 
project went straight to the github page. Github, of course, puts all 
the files along with a big fat download zip button at the top and the 
README.md is off the screen. Most of the time, the first step in 
installing software is finding that download button, clicking it and 
then waiting for it to finish. That download button is a bit like the 
bell to pavlov's dog.

A better approach would be to get people to link to whatever the landing 
paper/home page is for elFinder and add something to the top level of 
the raw github download that explains it's the developer code pile 
rather than the deployable.
