### ISSUE TITLE
Reduce file name length in display

### ISSUE THREAD

**Issue by premnath** [Studio-42/elFinder#1203]
Dear team,

 I have recently updated my latest elfinder version. In my old version(Version 2.0 rc1 ). If the file name is bigger. It automatically reduces the characters and display it as filename....

For example : abcdefghtigjlaksdflsfjljsldfsflsjfkl.pdf is displayed to abcdef.... When we mouse over on the file it displays the entire file name. 

May i know can i do any settings manually to do this operations. ?? 

Thanks in advance.

**Comment by nao-pon** [comment]
@premnath elFinder 2.1 is the handling of the ellipsis is difficult because filename displays two lines. This time, I corrected for the webkit.

Thanks!

**Comment by premnath** [comment]
Thanks for your quick response.
