### ISSUE TITLE
zip file uplaod

### ISSUE THREAD

**Issue by nimeshc64** [Studio-42/elFinder#1204]
i install el finder to laravel , it work fine but i try to upload zip file it give  "Unable to upload "my.zip".
File type not allowed"  how can i slove this??

**Comment by nao-pon** [comment]
@nimeshc64 Please check your connector option `uploadAllow`. Maybe default is `'uploadAllow'   => array('image', 'text/plain')`.

**Comment by nimeshc64** [comment]
can you tell where i can fine this file and how to change it

**Comment by nao-pon** [comment]
It is different by how do you installing. If you installed the package of Laravel, it is better that ask to distributor.
