### ISSUE TITLE
Pixlr error

### ISSUE THREAD

**Issue by standus** [Studio-42/elFinder#1205]
Hi,
I tried Pixlr function and I got error:
[IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error

**Comment by nao-pon** [comment]
@standus command pixlr is work on only my [rep. 2.1_n](https://github.com/nao-pon/elFinder). 2.1_n demo is http://hypweb.net/elFinder-nightly/demo/2.1_n/#elf_l2_Lw . If you find any problem please make issue to my repository.

Thanks!
