### ISSUE TITLE
places favorites folder

### ISSUE THREAD

**Issue by rajasharma27** [Studio-42/elFinder#1206]
Sir,
 how to set places favorites folder in elfinder

**Comment by nao-pon** [comment]
@rajasharma27 Please check out https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#ui .

**Comment by rajasharma27** [comment]
Sir,
drag and drop method is working perfectly, but I want to user places default or pre configured favorites folder.

**Comment by rajasharma27** [comment]
Sir,
 drag and drop method in places is working perfectly, but I want to use pre configured places for favorites folder. give me some suggestions

**Comment by nao-pon** [comment]
I'll make event `plasesload` with plases dirs object. You will can preset places dirs data in next version. Please wait.

**Comment by nao-pon** [comment]
@rajasharma27 This is example for for preset places
```javascript
elfinderInstance.bind('placesload', function(e, fm) {
	//if (fm.storage(e.data.storageKey) === null) { // for first time only
	if (!fm.storage(e.data.storageKey)) {           // for empty places
		e.data.dirs[targetHash] = fallbackName;     // preset folder
	}
}
```
You can try on elFinder 2.1.x Nightly - https://github.com/Studio-42/elFinder/archive/2.1.zip

**Comment by rajasharma27** [comment]
where I set folder name

 e.data.dirs[targetHash] = fallbackName

not working

**Comment by rajasharma27** [comment]
ok
now is working 
thanks

**Comment by rajasharma27** [comment]
Sir,
when you release new version
include comments on readme, "Whats New" in version this version

**Comment by rajasharma27** [comment]
Sir,
 when you release new version
 include comments on readme, "Whats New" in this version
