### ISSUE TITLE
Pixlr error on exit

### ISSUE THREAD

**Issue by dleffler** [Studio-42/elFinder#1207]
When using the Pixlr editor it doesn't return correctly.  While the actions taken in Pixlr seem to work (save save-copy), it either displays the text from a json upload error on a simple exit without save, or it displays the web page source instead of rendering it when returning from Pixlr with a save or save copy.

I can not find a demo of elFinder 2.1 with the pixlr command active to try this in another installation.

**Comment by nao-pon** [comment]
@dleffler command `pixlr` is work on only [my rep. 2.1_n](https://github.com/nao-pon/elFinder). 2.1_n demo is http://hypweb.net/elFinder-nightly/demo/2.1_n/#elf_l2_Lw . If you find any problem please make issue to my repository.

Thanks!
