### ISSUE TITLE
Search function recently broken

### ISSUE THREAD

**Issue by dleffler** [Studio-42/elFinder#1208]
elFinder v2.1 throws a fatal error when attempting to search, breaks on line 315 of elFinderVolumeLocalFileSystem.class.php due to 'the Function name must be a string' and it is receiving a 2 element array with element 0 being an elFinderVolumeExponent object and element 1 being a string 'localFileSystemSearchIteratorFilter'

**Comment by nao-pon** [comment]
@dleffler currently elFInderVolumeLocalFileSystem.class.php L.315 is [array_push($new_comps, $comp);](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeLocalFileSystem.class.php#L315). Is this line?

And What is "elFinderVolumeExponent"?

**Comment by dleffler** [comment]
Sorry bad copy/paste, line 15 (#15).  elFinderVolumeExponent  is a simple extends elFinderVolumeLocalFileSystem object.

**Comment by dleffler** [comment]
This appears to be a php v5.3 issue

**Comment by nao-pon** [comment]
I got it. Please check with next.
php/elFinderVolumeLocalFileSystem.class.php L.15
```php
return call_user_func ($this->callback, parent::current(), parent::key(), parent::getInnerIterator());
```

**Comment by nao-pon** [comment]
@dleffler Thanks! :+1:
