### ISSUE TITLE
zIndex is not a function

### ISSUE THREAD

**Issue by GodMod** [Studio-42/elFinder#1211]
With jQuery 2.2, I am getting many errors like "zIndex is not a function".
E.g. `.find('.ui-resizable-handle').zIndex(nav.zIndex() + 10);`

**Comment by wallenium** [comment]
To be clearer, this is an issue with jquery 1.12 beta 1.

https://jqueryui.com/upgrade-guide/1.12/#removed-zindex

zIndex has been removed,

**Comment by GodMod** [comment]
Caused by this: https://jqueryui.com/upgrade-guide/1.12/#removed-zindex

**Comment by nao-pon** [comment]
@GodMod , @wallenium Thanks! I began to fix.

**Comment by aeroson** [comment]
if zIndex() has been removed from 1.12 it should also be removed from documentation: https://api.jqueryui.com/zIndex/
