### ISSUE TITLE
Fix for infinite loop in elFinderConnector->output() (using v2.0.5)

### ISSUE THREAD

**Issue by cmanley** [Studio-42/elFinder#1213]
If ob_end_clean() fails, then elFinderConnector->output() enters an infinite loop.

This is the failure I had:
E_NOTICE with message "ob_end_clean(): failed to delete buffer zlib output compression." at elFinderConnector.class.php line 114

Solution:
Replace these 2 lines after "protected function output(array $data) {":
```
// clear output buffer
while(@ob_get_level()){ @ob_end_clean(); }
```

with:
```
// Try to clear output buffer
while (ob_get_level()) {
	if (!@ob_end_clean()) {
		break;
	}
}
```

**Comment by nao-pon** [comment]
@cmanley Thanks! I done. :+1:
