### ISSUE TITLE
Tip: namespace the session variables

### ISSUE THREAD

**Issue by cmanley** [Studio-42/elFinder#1214]
I suggest using an 'elFinder' session key with an associative array of values, or else multiple session keys all prefixed with 'elFinder.' because sooner or later, this is going to conflict with someone's code:
$_SESSION['LAST_ACTIVITY']

**Comment by nao-pon** [comment]
@cmanley elFinder 2.1 has prefix of session key. Please try 2.1.x.

Thanks!
