### ISSUE TITLE
mysql 不能正常使用

### ISSUE THREAD

**Issue by vipwei** [Studio-42/elFinder#1215]
debug: {connector: "php", phpver: "5.5.12", time: 0.19301104545593, memory: "7240Kb / 4865Kb / 128M",…}
connector: "php"
memory: "7240Kb / 4865Kb / 128M"
mountErrors: ["Driver "elFinderVolumeMySQL" : "]
0: "Driver "elFinderVolumeMySQL" : "
phpver: "5.5.12"
time: 0.19301104545593
upload: ""
volumes: [{id: "l1_", name: "localfilesystem", mimeDetect: "finfo", imgLib: "gd"}]
0: {id: "l1_", name: "localfilesystem", mimeDetect: "finfo", imgLib: "gd"}
id: "l1_"
imgLib: "gd"
mimeDetect: "finfo"
name: "localfilesystem"

应该怎么解决呢？

**Comment by vipwei** [comment]
{error: ["errConf", "errNoVolumes"], debug: ["Driver "elFinderVolume" does not exists"]}
debug: ["Driver "elFinderVolume" does not exists"]
0: "Driver "elFinderVolume" does not exists"
error: ["errConf", "errNoVolumes"]
0: "errConf"
1: "errNoVolumes"

看不懂哪里的问题

**Comment by nao-pon** [comment]
It is presumed to be caused by any of the following

- I can not connect to the MySQL database
- It does not exist table in MySQL database
- It does not exist initial data in the MySQL database table
