### ISSUE TITLE
Can't see the Chinese folder on the server

### ISSUE THREAD

**Issue by vipwei** [Studio-42/elFinder#1219]
Elfinder still can't see the Chinese folder on the server; and created in elfinder Chinese folder name, browser is Chinese, actually in the Windows Server see is garbled
How to deal with it?

**Comment by nao-pon** [comment]
Please set volume root option [`encoding`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding) and [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale-1).

**Comment by wayne1894** [comment]
This seems to be a problem for most Chinese users,
Please set volume root option encoding and locale  ==> Detailed way to write this way? I can not find the exact wording
