### ISSUE TITLE
Hello, not visible button extract

### ISSUE THREAD

**Issue by gcdsm12** [Studio-42/elFinder#1222]
To compress everything is okay but to extract not appear the option of extracting I'm using centOS 7.2

Tested in:
Elfinder 2.x
Elfinder 2.1.6

![elfinder_bug](https://cloud.githubusercontent.com/assets/7134503/13154423/00d7de76-d660-11e5-9b2c-df4fc4341856.png)

**Comment by nao-pon** [comment]
To your server requires unzip command.

Try
`yum install unzip`

**Comment by gcdsm12** [comment]
unzip is already installed

**Comment by nao-pon** [comment]
@gcdsm12  What returns with `unzip --help` on the server shell?

**Comment by nao-pon** [comment]
Is `quarantine` directory writable? Default of `quarantine` is "files/.quarantine" Or value of `quarantine` of volume root config.
