### ISSUE TITLE
Whether to support the window file encoding

### ISSUE THREAD

**Issue by vipwei** [Studio-42/elFinder#1224]
The next version can support the window file encoding, and now can not read the Chinese name in the window GBK environment file.

Or to tell you, you should modify some of the code can be achieved?

**Comment by nao-pon** [comment]
Did you try volume root options [`encoding`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding) and [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale-1)?

**example**
```php
'encoding' => 'zh_CN.gbk',
'locale' => 'Chinese_China.936',
```

**Comment by vipwei** [comment]
@nao-pon add to 'encoding'      => 'GBK' Solved, thank you

**Comment by nao-pon** [comment]
:+1:
