### ISSUE TITLE
There is no upload automatically rename the function

### ISSUE THREAD

**Issue by vipwei** [Studio-42/elFinder#1225]
There is no upload automatically rename the function

**Comment by nao-pon** [comment]
@vipwei What about connector plugin [`Normalizer`](https://github.com/Studio-42/elFinder/blob/2.1-src/php/plugins/Normalizer/plugin.php) or [`Sanitizer`](https://github.com/Studio-42/elFinder/blob/2.1-src/php/plugins/Sanitizer/plugin.php)?

**Comment by vipwei** [comment]
Did not find the tutorial, not very will use the plugin

**Comment by nao-pon** [comment]
What type rename do you want?

**Comment by vipwei** [comment]
Upload all files are directly renamed, can also be individual type

**Comment by nao-pon** [comment]
Is it possible to present a specific pattern?

**Comment by vipwei** [comment]
In the background there is an upload file rename switch, after the opening of the file to be uploaded to rename, can be controlled in the picture type

**Comment by nao-pon** [comment]
Well it is better treated independently by using a bind.

```php
function MyUploadPreCallback (&$path, &$name, $src, $elfinder, $volume)
{
	// rename on your backend
	$name = YourBackendRenameFunction($name);
	return true;
}

$opts = array(
	'roots' = array([Volumes Array]),
	'bind' = array(
		'upload.pre' => array('MyUploadPreCallback')
	),
);
```

**Comment by vipwei** [comment]
OK I'm testing.

**Comment by vipwei** [comment]
Whether there is a plug-in production tutorial, or a simple note of caution, I want to develop a plug-in to achieve, the current function, or further development of other functions

**Comment by nao-pon** [comment]
@vipwei Although there is only a simple note ...

- https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind

Or please refer to the source of each plug-in to reference.

- https://github.com/Studio-42/elFinder/tree/master/php/plugins

**Comment by nao-pon** [comment]
May I close this issue?

**Comment by vipwei** [comment]
OK
