### ISSUE TITLE
sort by clicking on cloumn headers broke in 2.1.7

### ISSUE THREAD

**Issue by flack** [Studio-42/elFinder#1226]
since 2.1.7, clicking on column headers no longer triggers the sort function. This is because `selectable` intercepts the click. In previous versions, it worked because there as a delay before selectable activated. This was removed here:

https://github.com/Studio-42/elFinder/commit/d09694e6b806e796adbc298ad92de6baa68b5fe6#diff-4d004df9a52538c7ef366ec796ff2f6cL437

Is there any way to work around the issue in configuration or do we have to wait for a fix to be released?

**Comment by flack** [comment]
One way around this might be to use the `cancel` option instead of the `filter` option: 

http://api.jqueryui.com/selectable/#option-cancel

The difference is that with cancel, the click event still gets triggered

**Comment by nao-pon** [comment]
@flack `filter` option is also the is good, but it can not start the selection from the header, so I'll resurrected the `delay`.

**Comment by flack** [comment]
@nao-pon `filter` only removes non-matching items from the resultset, i.e. you can still start to select on a filtered element (i.e. the mouse click is captures). `cancel` prevents selectable from activating when you click on an element matching the configured selector, so other event listeners get a chance to act.

But restoring `delay` works for me, too. 

BTW: I've noticed that selection stops working when you sort (at least in list view). Should I open another ticket for that?

**Comment by nao-pon** [comment]
> BTW: I've noticed that selection stops working when you sort (at least in list view). Should I open another ticket for that?

That's right. It seems no longer work after the sort. Please create a new issue.
