### ISSUE TITLE
size/items strings are hardcoded to lowercase

### ISSUE THREAD

**Issue by flack** [Studio-42/elFinder#1227]
in https://github.com/Studio-42/elFinder/blob/master/js/ui/stat.js#L17-L18

this breaks the ability of locales to use capitalized versions here (and AFAICT even in English, these two strings should better be capitalized), so could we remove the `toLowerCase()` calls in these two lines? If you want, I can send a pull requests that does this

**Comment by nao-pon** [comment]
@flack That's right. I think so too. We look forward to your pull request.
