### ISSUE TITLE
Session management

### ISSUE THREAD

**Issue by lonejack** [Studio-42/elFinder#1230]
I'm working with an application built on ZF and I would like to implement elFinder on my app.
After a study on the elF source code, the main ZF integration problem I see regards the Session management. In general ZF dislikes direct write ( $_SESSION[][]=xxx), so I decided to modify the actual version in order to ease the ZF implementation mantaining actual features.
The code I actually working, points to implement a session management and a session namespace management, this is my repo:
https://github.com/lonejack/elFinder
I hope that, if the modification will works (it will mantain exactly the features that actually elFinder has) you will import these modification on the master code.
But before to consider this job completed there are some question that I need to understand...
The session management actually open and close as soon as possible: in particular the close happens on the method "exec". This is good for quasi every command except "netmount" that instead require to re-open the session before to save the new volume on the session with "saveNetVolumes".
I've a problem in this case, that is: during the "mount" of the volume happen this:
- session_start(on netmount);
- mount of the volume;
- during "mount" of the volume happen a "stat" command on the elFinderVolumeDriver that produces a new "$this->sessionRestart();" and a session_write_close();
- after the mount the control return on netmount and will be processed the function "$this->saveNetVolumes($netVolumes)", but, in this situation, the session is closed and nothing will be stored on session;
The main reason why this happens is due to the fact that all other "stat" occurred during the volumes installation don't close the session (elFinder::$sessionClosed=false before the exec). But when "netmount" command happens, we have (elFinder::$sessionClosed=true).

Now, before to find a solution. Do you agree with this?
Thank you,
Claudio

**Comment by nao-pon** [comment]
@lonejack Problem of netmount is a bug of 2.1.6. It was fixed @a619bf43c532e9d8ec8f9406bb82e812bd0f1e86. 
However, I also think your suggestion is a good idea. Can you send a pull request that created a branch from the current master branch?

**Comment by lonejack** [comment]
@nao-pon Let me conclude my modification then I'll send you a pull request.
In the while can you see my code and tell me if you like it...
C.

**Comment by lonejack** [comment]
@nao-pon please take a look at [elFinderVolumeDriver](https://github.com/lonejack/elFinder/blob/elSession/php/elFinderVolumeDriver.class.php) at stat method.
Is it good for you if I move these lines:
 `
// is root
		$rootKey = md5($path);
		$rs = $this->getRootStatCache();
		if (!$this->isMyReload()) {
			// need $path as key for netmount/netunmount
			if (isset($rs->{$rootKey})) {
				if ($ret = elFinder::sessionDataDecode($rs->{$rootKey}, 'array')) {
					return $ret;
				}
			}
		}		
		$this->sessionRestart();
		$rs->{$rootKey} = elFinder::sessionDataEncode($ret);
		elFinder::sessionWrite();
`
under netmount.
In that situation we know that the session is open...

**Comment by nao-pon** [comment]
@lonejack The connector always calling `stat()` of root when volume mount on each request, so it must return the session cache except reload of the current volume for not to lower the performance on multi volumes. So, I would like to maintain the logic of the current `stat()`.

**Comment by barryvdh** [comment]
I would be happy if the session (and response/request) were abstracted to some classes/interfaces, so we can implement our own ones. Similar to https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/HttpDriverInterface.php and https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/PhpHttpDriver.php

**Comment by lonejack** [comment]
@nao-pon I would like to move on netmount only these lines:
$this->sessionRestart();
$rs->{$rootKey} = elFinder::sessionDataEncode($ret);
elFinder::sessionWrite();
The stat will remain as it is....

**Comment by lonejack** [comment]
@barryvdh good idea, this would  be perfect for integration on every environment...

**Comment by nao-pon** [comment]
@lonejack , @barryvdh OK! I will add a session handler to the option of elFinder instance.

**Comment by lonejack** [comment]
@nao-pon, do you want integrate my code(1) or do you intend to start a new development(2)?
if the answer is (1) I need at least one week more.

**Comment by nao-pon** [comment]
@lonejack I chose (2). It has created a [branch(session)](https://github.com/Studio-42/elFinder/tree/session) for this. And it is being considered the interface definition. The idea is in the recruitment at any time!

**Comment by lonejack** [comment]
Ok. I'll wait your code.

**Comment by nao-pon** [comment]
@lonejack Thanks! I will commit the prototype in a few days. Please advice to see it.

**Comment by nao-pon** [comment]
@lonejack , @barryvdh I pushed @2bbcc67646f5208832fd61df928958425d2965d0 to [branch session](https://github.com/Studio-42/elFinder/tree/session). Please check out. :-)

**Comment by barryvdh** [comment]
Haven't tested it, but seems reasonable. Not really sure what the empty checks do, but I guess we wouldn't need that (or the base64) in our own wrappers, right?

**Comment by nao-pon** [comment]
Such as base64 encoded was implemented for a connector option [`base64encodeSessionData`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#base64encodesessiondata) of elFinder.  I think so, that certainly not needed in much case. So it is not required in its own wrapper.

**Comment by nao-pon** [comment]
elFinder 2.1.8 supported custom session handling wrapper. (https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#session-218)

**Comment by barryvdh** [comment]
I've implemented this for Laravel, looks good :)
https://github.com/barryvdh/laravel-elfinder/commit/90a32a00690adb64421d9f39342a737798f4f5ad

**Comment by nao-pon** [comment]
@barryvdh It's so cool! :+1:
