### ISSUE TITLE
Folder icon

### ISSUE THREAD

**Issue by mlerman** [Studio-42/elFinder#1231]
Hello, I would like that when there is a favicon.ico present in the folder, the folder icon shows the favicon instead of the generic folder icon: 
![foldericon1](https://cloud.githubusercontent.com/assets/3161760/13381965/37232b1e-de1e-11e5-88d9-d918ada93a83.png)
. That would be super nice. See below for what I mean.
![foldericon](https://cloud.githubusercontent.com/assets/3161760/13381946/b52a3c6a-de1d-11e5-92ae-69c1bd509a2f.png)

**Comment by nao-pon** [comment]
@mlerman It began. But it can only be the local volume driver.

**Comment by nao-pon** [comment]
@mlerman You can use connector root option `detectDirIcon`.

e.g.
```php
    'roots' => array(
        array(
            'driver'        => 'LocalFileSystem',
            'path'          => '/path/to/files/',
            'URL'           => 'http://localhost/to/files/',
            'detectDirIcon' => 'favicon.ico'
        )
    )
```

**Comment by mlerman** [comment]
You're rock!

 
 
  On Tue, Mar 15, 2016 at 2:12 AM, Naoki Sawada<notifications@github.com> wrote:   
@mlerman You can use connector root option detectDirIcon.

e.g.
    'roots' => array(
        array(
            'driver'        => 'LocalFileSystem',
            'path'          => '/path/to/files/',
            'URL'           => 'http://localhost/to/files/',
            'detectDirIcon' => 'favicon.ico'
        )
    )

**Comment by mlerman** [comment]
Thank you. In which version is this?I've tried 2.1.19 Regards,MiKL~408 564 9578 : Cell408 538 0490 : Voicemail/Text/SMS
ManEstate.com In the meantime connect with me using one of your accounts :

|  |  |  |

**Comment by mlerman** [comment]
I have this. Not sure if it is correct.

    $().ready(function() {          elf = $('#elfinder').elfinder({            height : 650,            rememberLastDir : true,            useBrowserHistory : false,            detectDirIcon : 'favicon.ico',            driver : 'LocalFileSystem',
uiOptions : {    // toolbar configuration    toolbar : [        ['back', 'forward'],        // ['reload'],        ['home', 'up'],        ['mkdir', 'mkfile', 'upload'],        ['open', 'download', 'getfile'],        ['info'],        ['quicklook'],        ['copy', 'cut', 'paste'],        ['rm'],        ['duplicate', 'rename', 'edit', 'resize'],        ['extract', 'archive'],        ['search'],        ['view'],        ['help']    ],
    // directories tree options    tree : {        // expand current root on init        openRootOnLoad : true,        // auto load current dir parents        syncTree : true    },
    // navbar options    navbar : {        minWidth : 500,        maxWidth : 600    },
    // current working directory options    cwd : {        // display parent directory in listing as ".."        oldSchool : true    }},      defaultView : 'list',            uploadMaxSize : '100M',  // 104857600 bytes            customData : {path : getQueryVariable("path")},            url : 'php/connector.minimal.php'  // connector URL (REQUIRED)          });    });

 Regards,MiKL~408 564 9578 : Cell408 538 0490 : Voicemail/Text/SMS
ManEstate.com In the meantime connect with me using one of your accounts :

|  |  |  |

**Comment by nao-pon** [comment]
@mlerman This is on 2.1.10 or later. It has not released. You can try [Nightly Build](https://github.com/Studio-42/elFinder/archive/2.1.zip) until 2.1.10 release.

**Comment by mlerman** [comment]
OK I'll wait the release...Thanks Regards,MiKL~408 564 9578 : Cell408 538 0490 : Voicemail/Text/SMS
ManEstate.com In the meantime connect with me using one of your accounts :

|  |  |  |

**Comment by mlerman** [comment]
Regards,MiKL~408 564 9578 : Cell408 538 0490 : Voicemail/Text/SMS
ManEstate.com In the meantime connect with me using one of your accounts :

|  |  |  |



     
----- Forwarded Message -----
