### ISSUE TITLE
How much is the minimum supported version of PHP

### ISSUE THREAD

**Issue by vipwei** [Studio-42/elFinder#1232]
How much is the minimum supported version of PHP

**Comment by vipwei** [comment]
The test of php5.2.17 does not support FilesystemIterator:: SKIP_DOTS
Php5.2.17 environment error: Class'FilesystemIterator'Fatal error not found in D:\upupw\htdocs\app\app\app\elfinder\admin\elfile\elFinderVolumeLocalFileSystem.class.php on line 550
For a compatible method

**Comment by nao-pon** [comment]
@vipwei It is a bug of 2.1.6 - 2.1.7. but it was fixed @c0fda8074d1136e3f163af235189633fb2f3a1d5. Please check out [current nightly build](https://github.com/Studio-42/elFinder/tree/2.1).
