### ISSUE TITLE
Three the use of FilesystemIterator to repair

### ISSUE THREAD

**Issue by vipwei** [Studio-42/elFinder#1233]
Elfinder2.17 all the documents in that view there are three in the use of FilesystemIterator respectively.
FilesystemIterator:: SKIP_DOTS
FilesystemIterator:: KEY_AS_PATHNAME
FilesystemIterator:: SKIP_DOTS
The restoration of the three can be compatible with the php5.2 version,
I hope the lowest version in the document about reputation elfinder compatible, so as to avoid

**Comment by nao-pon** [comment]
@vipwei This issue was fixed @c0fda8074d1136e3f163af235189633fb2f3a1d5 .
