### ISSUE TITLE
A lot of suffix format can not support

### ISSUE THREAD

**Issue by vipwei** [Studio-42/elFinder#1234]
'archiveMimes'AND'uploadAllow' support Mimetypes type is what format?
My program allows the user to set the file format suffix "rar|zip|sql|doc|pdf|jpg|xls|png|gif|mp3|jpeg|bmp|swf|flv|ico" and other but I through elFinderVolumeDriver:: getMimeTable (), mimetypes control can be used, but the presence of many suffixes can not be used normally, such as ICO, HTML settings also converted mimetypes

**Comment by nao-pon** [comment]
@vipwei `elFinderVolumeDriver::getMimeTable()` became load a file "php/mime.type". Thanks!

**Comment by vipwei** [comment]
Are you saying that php/mime.type was not successful due to loading is it?

**Comment by vipwei** [comment]
@nao-pon Just a .ICO file that does not support or

**Comment by nao-pon** [comment]
@vipwei There was typo in 'mime.type' It fixed @0941454.

**Comment by vipwei** [comment]
@nao-pon I have to fix a ICO, write image/x-ico reasons need to modify the image/x-icon

**Comment by vipwei** [comment]
@nao-pon Together to find the reason, thank you

**Comment by vipwei** [comment]
@nao-pon There are several BUG I also send an article to tell you.
