### ISSUE TITLE
Unable to parse server response

### ISSUE THREAD

**Issue by LakshayaG73** [Studio-42/elFinder#1235]
Hi, 

I am using elfinder 1.2 and keep getting 'Unable to parse server response' whenever I try to upload any file. Any ideas? Help would be very appreciated. 

The error shows up in the k.submit() method
![elfinder-error](https://cloud.githubusercontent.com/assets/1243371/13414183/86971e34-df05-11e5-8cb0-81a2263ff953.png)

Thanks, 
Lakshaya

**Comment by nao-pon** [comment]
@LakshayaG73 elFinder 1.2 is not maintenance. Use the elFinder 2.0.x or 2.1.x.
