### ISSUE TITLE
elfinder changing value of window.name

### ISSUE THREAD

**Issue by laola1technik** [Studio-42/elFinder#1237]
Hello!

We've recently encountered a problem with elFinder, that unintentionally manipulates the value of the variable window.name.

This occurs in the replacement object (:
`replacement = {
				name : function(f) {
					name = fm.escape(f.name);
					!list && (name = name.replace(/([_.])/g, '&#8203;$1'));
					return name;
				},...`

It seems that the variable name isn't properly declared here, leading to the mentioned problem.
Could you possibly add a var in front of name to fix this?
**var** name = fm.escape(f.name);

Thanks!

**Comment by nao-pon** [comment]
@laola1technik Thanks! :+1:
