### ISSUE TITLE
Need to repair BUG

### ISSUE THREAD

**Issue by vipwei** [Studio-42/elFinder#1239]
1. Rename the file or directory when the text color to white #fff can not see

2. FilesystemIterator:: KEY_AS_PATHNAME
FilesystemIterator:: SKIP_DOTS
Not compatible with low version of the PHP problem

**Comment by nao-pon** [comment]
@vipwei (2) was fixed @c0fda8074d1136e3f163af235189633fb2f3a1d5 .ref #1233
