### ISSUE TITLE
click folder to dowload --> Unable to create archive

### ISSUE THREAD

**Issue by allce231** [Studio-42/elFinder#1241]
click folder to dowload --> Unable to create archive
![image](https://cloud.githubusercontent.com/assets/5996940/13623839/5edab032-e5e4-11e5-9fc1-90a531b1ad47.png)
--> success create zip archive
click folder.zip to dowload --> success

liunx  centos 7 x64

ps : http://119.29.146.244/index.php?mod=article&act=elfinder

**Comment by nao-pon** [comment]
@allce231 Please try set connector option [`commonTempPath`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#commontemppath--217)..

**Comment by nao-pon** [comment]
@allce231 Try set a connector config [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale) to your server locale.

**Comment by nao-pon** [comment]
May be fixed it. Plz try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).
