### ISSUE TITLE
Elfinder with Yeeditor

### ISSUE THREAD

**Issue by sauerlu** [Studio-42/elFinder#1242]
Dear sirs, 
I'm using the yeeditor editor for joomla, wich cames with the elfinder 2.0 rc1. Everything works fine.
Because I need the AutoResize Plugin, I have to upgrade to elfinder to 2.1.

After I've done that, everything works fine, unitil I want select an Image. When I make a double click, the Picture opens in a Popup, but in the the old version of elfinder 2.0 rc1, the Image path is posted in an input field. And that's what I want.  
[As it shout be](http://screencast.com/t/BhAZR1KfH8x)

In the Error Console of Firefox, I'm getting this error:
TypeError:file.replace is not a function in the line 30 of my select_image.php

I think somewhere there is the problem...

[select_image.php(http://screencast.com/t/NPmc2M4k)

Or do you have an other idea how can I use the Autoresize Plugin in the version op elfinder 2.0 rc1?

Thanks a lot for your help.

Greetings.
F.

**Comment by nao-pon** [comment]
@sauerlu Please check ["getfile" command options](https://github.com/Studio-42/elFinder/blob/8fa175029dec0ec48336f3c382ace044da134a87/js/elFinder.options.js#L166).

To `onlyURL : true` 

OR change your code.
```javascript
getFileCallback : function(file) {
```
to
```javascript
getFileCallback : function(obj) {
	var file = obj.url;
```

**Comment by sauerlu** [comment]
Thanks a lot for your great support.
onlyURL did it!
Have a nice day sir. :)
