### ISSUE TITLE
Error when copying data from ftp drive to localfilesystem drive

### ISSUE THREAD

**Issue by suiluj** [Studio-42/elFinder#1243]
Hello! :)

I have mounted several localfilesystem drives and one ftp drive.
The ftp drive mounts a ftp connection on localhost.

Everything works well but there is one problem:

Copying **from** the ftp drive **to** different localfilesystem drive gives an error message saying that the data is not in json format.

The files do not appear in elfinder at first but when i refresh the folder view they appear and seem to be fine.

My question is:

Do the files get copied without dataloss and how to get rid of the error?

Thanks for your help 

Regards
Julius

**Comment by nao-pon** [comment]
@suiluj I edited about passive mode. What about this [elFinderVolumeFTP.class.php](http://hypweb.net/elFinder-nightly/demo/Demo/Downloads/debug/elFinderVolumeFTP.class.php) file?

**Comment by suiluj** [comment]
Hello @nao-pon and thanks again for your help

With your new ftp class i get an error:

Call to undefined method elFinder::getStaticVar() .../application/libraries/elfinder/elFinderVolumeFTP.class.php on line 203

i use elfinder with codeigniter (perhaps you need this information because of some relative or absolute paths).
i configurated it just like described on the elfinder docs.

I am just a hobby programmer so perhaps i just don't see my "stupid" mistake.

But just in case i find it i will write here. ;)

**Comment by nao-pon** [comment]
Probably your elFinder is old version. plz try [nightly build version](https://github.com/Studio-42/elFinder/archive/2.1.zip)(recomend for test) or [2.1.8](https://github.com/Studio-42/elFinder/archive/2.1.8.zip).

**Comment by suiluj** [comment]
Ah okay.
Currently i do not have a lot of time so i will test it in the future but sorry for trying the nightly build in the next time.
Since the copying works as expected i will leave it on the stable version for now.

But thank you very much for your kind help! I really appreciate this ;)

**Comment by nao-pon** [comment]
OK. I'm to close once, but if there is a similar problem with the latest version, please re-open.

Thanks! :-)

**Comment by nao-pon** [comment]
I found problem of LocalFileSystem class. I'll fix it.

**Comment by suiluj** [comment]
@nao-pon ah great! You are doing a great job with this project! Thank you very much for your work!! elfinder is perfect!

**Comment by nao-pon** [comment]
@suiluj Thanks! :+1:

**Comment by suiluj** [comment]
I updated my version.
Now everything works perfectly! :+1:
