### ISSUE TITLE
Startpath for a ftp drive

### ISSUE THREAD

**Issue by suiluj** [Studio-42/elFinder#1244]
Hello! ;)

I have installed elfinder with several localfilesystem drive and one ftp drive.

I am able to use the startpath option on localfilesystem drives.
So i can open links and elfinder opens a subfolder in a localfilesystem drive.

But the startpath option seems to be missing for ftp drives.

And when i just change the path for the ftp drive to a subfolder, elfinder does of course not open the ftp drive at the beginning.

Does someone have an idea how i can use something like startpath to create links which open a subfolder in the ftp drive?

Thanks for your help

Julius

**Comment by nao-pon** [comment]
@suiluj I tried, but this is not a problem. Please let us know your volume settings.

**Comment by suiluj** [comment]
Thanks for your try. :)
Then there is a some mistake on my side i think.
I am just a hobby programmer. I will write here in case i will find the reason some day.

here is my configuration (i use alot of path variables)

ftp volume:

array_push($opts['roots'], array(
	'driver' => 'FTP',
	'host'   => 'localhost',
	'user'   => 'xxxx',
	'pass'   => 'yyyy',
	'path'   => '/',
	'alias'  => 'zzzz',
	'tmbPath'	=> $tmbpath,
	'quarantine'	=> $quarantinepath,
	'URL'    => $urlpath . $rootnumber,
	//'startPath'  => $startpath[$rootnumber],
	// more elFinder options here
));

localfilesystem volume:

array_push($opts['roots'], array(
	'driver' => 'LocalFileSystem',
	'path'   => $path[$rootnumber],
	'alias'  => 'zzzz2',
	'tmbPath'	=> $tmbpath,
	'quarantine'	=> $quarantinepath,
	'URL'    => $urlpath . $rootnumber,
	'startPath'  => $startpath[$rootnumber],
	// more elFinder options here
));

**Comment by nao-pon** [comment]
I know at #1243 that your elfinder is old version. This problem is probably resolved in the latest version. Therefore, to close once, but if there is a similar problem with the latest version, please re-open.

PS. `startPath` settings you can specify only one of several volumes.

**Comment by suiluj** [comment]
okay yes.
Thank you again for your kind help and the hints.
I will update my version in the future when i find some time

PS. i know that you only specify `startpath` for one volume at a time. this variable is an empty string if no startpath is set or a startpath is set for another volume. So with LocalFileSystems it works perfectly ;)

i will write here when updated my version and i fixed my problem.
