### ISSUE TITLE
How to show multiple elFinder on one page !

### ISSUE THREAD

**Issue by bratsadlove** [Studio-42/elFinder#1245]
Hi All !

I have page insert multiple elFinder but i have problem. It's not show any name folder or file when create multiple elFinder **( please view file attach )**, but i create only one elFinder on one page then show it's, However i create multiple then opposite. Please help me fix it's 
![noshow](https://cloud.githubusercontent.com/assets/16644762/13549543/e813da34-e339-11e5-92b6-fd64413dc000.png)

This's version: **2.1.3**
Thank's for reading !

**Comment by nao-pon** [comment]
This issue was fixed at #1174. Thanks!
