### ISSUE TITLE
Wordpress extra slash issue.

### ISSUE THREAD

**Issue by aihimel** [Studio-42/elFinder#1246]
Wordpress Version: 4.4.1
PHP Version: 5.5.9
elFinder Version: 2.1.7
OS: Linux Mint 17.5

An extra slash is added when I edit a text/code file when encounters an apostrophe.

It works perfectly when I implement elFinder stand alone.

When I integrate elFinder inside a wordpress plugin it adds extra slash with every apostrophe.

Thanks
Aftabul Islam

**Comment by aihimel** [comment]
I have made a pull request to solve this problem.
Thanks

**Comment by nao-pon** [comment]
@aihimel This is a specific problem of WordPress. You must be fix in a plugin of WordPress.

**Comment by aihimel** [comment]
@nao-pon Is there a way to add a function that will be called inside the input_filter function with the argument?

**Comment by nao-pon** [comment]
Please process the `$_POST` or `$_GET`  before make an instance of elFinderConnector in your back end.

**Comment by aihimel** [comment]
Thanks a lot for your suggestion.

**Comment by nao-pon** [comment]
Sure, no problem. :+1:
