### ISSUE TITLE
I can not create a archive & extract...

### ISSUE THREAD

**Issue by 53ifbb** [Studio-42/elFinder#1247]
`'commonTempPath' => GetSiteRoot().SYS_DIR_TEMP,
'uploadTempPath' => GetSiteRoot().SYS_DIR_TEMP,
....
'quarantine'	=> GetSiteRoot().SYS_DIR_TEMP.'.ElFinder_quarantine'`

temp folders created.

my version 2.1.7
What i must do ?

**Comment by 53ifbb** [comment]
p.s. icons in toolbar - active. But alert an error...

**Comment by nao-pon** [comment]
@53ifbb Is a `GetSiteRoot().SYS_DIR_TEMP.'.ElFinder_quarantine'` wraitable and directory?

**Comment by 53ifbb** [comment]
@nao-pon 
SYS_DIR_TEMP = **tmp/** - 777
**.ElFinder_quarantine** - 777

**Comment by 53ifbb** [comment]
all opts

`array(
	'debug' => true,
	'commonTempPath' => GetSiteRoot().SYS_DIR_TEMP,
	'uploadTempPath' => GetSiteRoot().SYS_DIR_TEMP,
	'roots' => array(
        array(
			'driver'	=> 'LocalFileSystem',
			'path'		=> GetSiteRoot(),
			'startPath'	=> GetSiteRoot().SYS_DIR_UPLOADS,
			//'URL'		=> GetSiteUrl().SYS_DIR_UPLOADS,
			'mimeDetect'	=> 'internal',
			'mimefile'		=> dirname(__FILE__)._DS_.'mime.types',
			//'imgLib'		=> 'imagick',
			'tmbPath'		=> GetSiteRoot().SYS_DIR_TEMP.'.ElFinder_tmb',
			'tmbURL'		=> GetSiteUrl().SYS_DIR_TEMP.'.ElFinder_tmb',
			'tmbSize'		=> 48,
			'tmbCrop'		=> false,
			'tmbBgColor'	=> 'transparent',
			//'accessControl'	=> 'ElFinderAccess',
			'attributes' => array(
                    array(
                        'pattern' => '/(\.ElFinder_tmb|\.ElFinder_quarantine)$/i',
                        'read' => false,
                        'write' => false,
                        //'hidden' => true,
                        'locked' => true
                    )
                ),
			'acceptedName'	=> '/^.*$/',
			'uploadAllow'	=> array('all'),
			'quarantine'	=> GetSiteRoot().SYS_DIR_TEMP.'.ElFinder_quarantine'
        )
    )
);`

**Comment by nao-pon** [comment]
What is the error message you got?

**Comment by 53ifbb** [comment]
> 'errExtract'           : 'Ошибка извлечения файлов из архива "$1".',
> 'errArchive'           : 'Ошибка создания архива.',

**Comment by 53ifbb** [comment]
p.s. I can create ZIp in localhost (win10, apache, php5.3), now.

**Comment by nao-pon** [comment]
I added more error messages to extract function. Plz try & check result of extraction with this [elFinderVolumeLocalFileSystem.class.php](http://hypweb.net/elFinder-nightly/demo/Demo/Downloads/debug/elFinderVolumeLocalFileSystem.class.php).

**Comment by 53ifbb** [comment]
What is new errors ?) I have not new error...(
http://ipic.su/img/img7/fs/elf.1457422882.png
http://ipic.su/img/img7/fs/elf2.1457422935.png
http://ipic.su/img/img7/fs/elf3.1457422951.png
http://ipic.su/img/img7/fs/elf4.1457422961.png

os Linux 3.14.51-grsec x86_64 at gen148.hs.shared
server Apache
php 5.6.17-1+mh1

GZip yes
REGISTER_GLOBALS off
SAFE_MODE off
MAGIC_QUOTES_GPC off
LOCALE ru.CP1251

http://ipic.su/img/img7/fs/cmod.1457423313.png

**Comment by nao-pon** [comment]
OK. Try set a connector config [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale) to 'ru_RU.cp1251' or 'ru.cp1251'.

**Comment by 53ifbb** [comment]
:angry: not work (((

```
'debug' => true,
'locale' => SYS_LOCALE,
```
before
setlocale(LC_ALL, SYS_LOCALE);
before
define('SYS_LOCALE', 'ru_RU.CP1251');

p.s. It is full translate of russian lang for 2.1.7. - http://pastebin.com/download/rg3yVWeC
U have old translate in your builds...

**Comment by nao-pon** [comment]
I missed. Plz try set connector **Root options** [`encoding`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding) to 'cp1251' and [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale-1) to 'ru_RU.CP1251'.

```php
'roots'  => array(
    array(
        'encoding' => 'cp1251',
        'locale' => 'ru_RU.CP1251',
        'driver'     => 'LocalFileSystem',
```

**Comment by 53ifbb** [comment]
`'locale' => 'ru_RU.CP1251',
'encoding' 	=> 'cp1251',
'commonTempPath' => GetSiteRoot().SYS_DIR_TEMP,
'uploadTempPath' => GetSiteRoot().SYS_DIR_TEMP,
'roots' => array(
	array(
		//'encoding' 	=> 'cp1251',
		//'locale' 	=> 'ru_RU.CP1251',

//'locale' => 'ru_RU.CP1251',
//'encoding' 	=> 'cp1251',
'commonTempPath' => GetSiteRoot().SYS_DIR_TEMP,
'uploadTempPath' => GetSiteRoot().SYS_DIR_TEMP,
'roots' => array(
	array(
		'encoding' 	=> 'cp1251',
		'locale' 	=> 'ru_RU.CP1251',
		'driver'	=> 'LocalFileSystem',
		
//'locale' => 'ru_RU.CP1251',
//'encoding' 	=> 'cp1251',
'commonTempPath' => GetSiteRoot().SYS_DIR_TEMP,
'uploadTempPath' => GetSiteRoot().SYS_DIR_TEMP,
'roots' => array(
	array(
		//'encoding' 	=> 'cp1251',
		'locale' 	=> 'ru_RU.CP1251',
		'driver'	=> 'LocalFileSystem',`

all manipulations were not successful

**Comment by nao-pon** [comment]
Probably elFinderVolumeDriver::makeArchive and elFinderVolumeDriver::unpackArchive are has problem, but I can't see this problem. Can you debug these method? 

**php/elFinderVolumeDriver.class.php - makeArchive() & unpackArchive**
- `chdir` executable?
- Is $cmd value valid?

**Comment by lucaneli** [comment]
good evening,
not activate the button to create files or remove file elements .

**Comment by lucaneli** [comment]
I can create Zip,Tar, Gzip,Bzip  in localhost but when i upload all files to the web server don´t activated

**Comment by nao-pon** [comment]
@lucaneli It requires Archive/Extract commands that is executable on the server. elFinder supported these commands. `tar`. `gzip`, `bzip2`, `xz`, `zip`, `unzip`, `rar`, `7za`, `7z` and PHP Class `ZipArchive`.

**Comment by lucaneli** [comment]
thanks for your answer @nao-pon , so I can check with phpinfo

**Comment by nao-pon** [comment]
@53ifbb Please check your php config open_basedir.

**Comment by lucaneli** [comment]
ok thanks @nao-pon , i checked de php config and activate all commands. tar. gzip.bzip2.....  thanks for all

**Comment by lucaneli** [comment]
Can i activate All comands  fron one .htacess or one  php.ini in my host , i don't acces to the php.ini to the server. Enviado desde Yahoo Mail para iPhoneEl 09/03/2016 02:42:51, Naoki Sawada escribió:@53ifbb Please check your php config open_basedir.

**Comment by allce231** [comment]
![image](https://cloud.githubusercontent.com/assets/5996940/13623949/4880f232-e5e5-11e5-987d-31b6a1d7fe76.png)
![image](https://cloud.githubusercontent.com/assets/5996940/13623953/52c65f66-e5e5-11e5-95a8-ea24571ee00a.png)

unable to create archive!!!

but 


![image](https://cloud.githubusercontent.com/assets/5996940/13623967/5f24f326-e5e5-11e5-8e06-0239a20edbcc.png)

![image](https://cloud.githubusercontent.com/assets/5996940/13623971/688d5dc2-e5e5-11e5-8d3d-5fe7dbaf8b90.png)

success!!!

**Comment by nao-pon** [comment]
May be fixed it. Plz try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by 53ifbb** [comment]
@nao-pon open_basedir	no value	no value
http://support.masterhost.ru/phpinfo56_gen_mphp.php

**Comment by 53ifbb** [comment]
I will try with [https://github.com/Studio-42/elFinder/commit/adbba7e2ddd1086c2ea5f16f6c73a6f71658b99d](url), later and send you a message...

**Comment by 53ifbb** [comment]
I applied fix 

> [php] use `opendir()` instead to `scandir()` 
not fixed my problem(

and why is this `return $this->setError('Root folder does not exists.');
return $this->setError('Root folder has not read and write permissions.');
$this->setError('Can not open local directory.');
return $this->setError('Path undefined.');` have not elFinder::... ?

**Comment by 53ifbb** [comment]
@nao-pon p.s. my scripts using  Class ZipArchive and can create/extract zip archives

**Comment by nao-pon** [comment]
I got it. Your system php has `disable_functions` directive. it value include 'proc_open'. I'll fix of detect of archiver.

**Comment by lucaneli** [comment]
I download this file
(May be fixed it. Plz try nightly build.) of @nao-pon and the program it's ok , Good Job , thank's @nao-pon.
One Question nao this program can read files xls of Excel office thank's for All

**Comment by 53ifbb** [comment]
@nao-pon Congratulations! I'm happy. :smile: 
i can create *zip.

**Comment by nao-pon** [comment]
@53ifbb Yeah! :+1:
