### ISSUE TITLE
Unable to remove 'xxxxx', but localhost can

### ISSUE THREAD

**Issue by allce231** [Studio-42/elFinder#1248]
Delete folder failed, but delete file successfully

liunx centos 7 x64

test address : http://119.29.146.244/index.php?mod=article&act=elfinder

phpinfo :http://119.29.146.244/xephpinfo.php

**Comment by nao-pon** [comment]
@allce231 Try set a connector config [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale) to your server locale.

**Comment by nao-pon** [comment]
I missed. Plz try set connector Root options encoding to 'YOUR SERVER ENCODING' and locale to 'YOUR SERVER LOCALE'.

**Comment by allce231** [comment]
add :
locale: 'zh_CN.utf8',
encoding:'utf-8'
?

still Unable to remove 

@nao-pon

**Comment by nao-pon** [comment]
I changed elFinderVolumeDriver::rmdirRecursive.  What about this [elFinderVolumeDriver.class.php](http://hypweb.net/elFinder-nightly/demo/Demo/Downloads/debug/elFinderVolumeDriver.class.php)?

**Comment by nao-pon** [comment]
@allce231 Please check your php config `open_basedir`. And please correct it

**Comment by allce231** [comment]
@nao-pon 

/**
	 * Remove directory recursive on local file system
	 *
	 * @param string $dir Target dirctory path
	 * @return boolean
	 * @author Naoki Sawada
	 */
	public function rmdirRecursive($dir) {
		if (!is_link($dir) && is_dir($dir)) {
			@chmod($dir, 0777);
			foreach (array_diff(scandir($dir), array('.', '..')) as $file) {
				@set_time_limit(30);
				$path = $dir . DIRECTORY_SEPARATOR . $file;
				if (!is_link($dir) && is_dir($path)) {
					$this->rmdirRecursive($path);
				} else {
					@chmod($path, 0666);
					@unlink($path);
				}
			}
			return @rmdir($dir);
		} else if (is_file($dir) || is_link($dir)) {
			@chmod($dir, 0666);
			return @unlink($dir);
		}
		return false;
	}

**Comment by nao-pon** [comment]
@allce231 Plz try this [elFinderVolumeDriver.class.php](http://hypweb.net/elFinder-nightly/demo/Demo/Downloads/debug/elFinderVolumeDriver.class.php).

**Comment by allce231** [comment]
replace elFinderVolumeDriver.class.php.

an error

Invalid backend configuration.
Readable volumes not available.

**Comment by allce231** [comment]
@nao-pon I am replace elFinderVolumeDriver::rmdirRecursive 

from [elFinderVolumeDriver.class.php](http://hypweb.net/elFinder-nightly/demo/Demo/Downloads/debug/elFinderVolumeDriver.class.php).

folder can delete!!!

Thank you very much!!!!

**Comment by nao-pon** [comment]
May be fixed it. Plz try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).
