### ISSUE TITLE
Unable to upload file, giving error "Undefined variable: file"

### ISSUE THREAD

**Issue by furmanali8nxb** [Studio-42/elFinder#1251]
Working on laravel 5.2 with elfinder,
Unable to upload file, giving error "Undefined variable: file"

**Comment by IgnitedCoder** [comment]
Same issue here after updating. Help please.. using this on a live site and clients are in an uproar. :(

Thanks

**Comment by nao-pon** [comment]
@furmanali8nxb , @IgnitedCoder It is duplicate to #1249. I’ll tagging to 2.1.9 in a soon. Maybe today or tomorrow.
