### ISSUE TITLE
button for select files not active

### ISSUE THREAD

**Issue by 53ifbb** [Studio-42/elFinder#1252]
Why ?
http://ipic.su/img/img7/fs/Bezymyannyj.1457641096.png

version 2.1.7 & applied all last fixes from https://github.com/Studio-42/elFinder/commits/master

i need this function, because i can not select * kn tablets pC

**Comment by nao-pon** [comment]
@53ifbb The `select` button will never be effective when `getFileCallback` has not been specified. I'll fix so that this button does not display if `getFileCallback` has not been specified. 

In the touch device allows multiple selection with the long tap.

**Comment by 53ifbb** [comment]
@nao-pon Thanks !
