### ISSUE TITLE
Upload Problems

### ISSUE THREAD

**Issue by mash180** [Studio-42/elFinder#1253]
I'm trying the versions 2.1.8 and 2.1.9 and always get this error when upload files:

Warning:  fopen() [<a href='function.fopen'>function.fopen</a>]: open_basedir restriction in effect. File(C:WindowsTempphp3D6B.tmp) is not within the allowed path(s):

As you can see the separator is missing in the path "C:WindowsTempphp3D6B.tmp"

I can create new dirs but can't rename it.

I already checked the permissions three times and everything looks fine.

Any help?

**Comment by nao-pon** [comment]
@mash180 Please check your temp_dir path.

What is result? of 
```php
$temppath = sys_get_temp_dir();
var_dump($temppath);
```

**Comment by mash180** [comment]
The result is:

string(16) "C:\Windows\TEMP\"

**Comment by nao-pon** [comment]
Can you show us your connector configuration?

**Comment by mash180** [comment]
I'm using this configuration in another app with and older version and work just fine:

I try to use uploadTempPath and it does not work either.

`$opts = array(
	// 'debug' => true,
       //'uploadTempPath' => 'MY_PATH',
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
			'path'          => '../UpFiles/' . $_REQUEST['FolderName'] . '/Albumes',         // path to files (REQUIRED)
			//'URL'           => '../UpFiles/' . $_REQUEST['FolderName'] . '/Albumes', // URL to files (REQUIRED)
			'accessControl' => 'access',             // disable and hide dot starting files (OPTIONAL)
			'alias'			=> '',
			'uploadOverwrite' => false,
			'uploadAllow'	=> array('image/png','image/jpeg','image/jpg','image/bmp'),
			'uploadDeny'  	=> array('all'),
			'uploadTotalSize' => '50M',
			'uploadMaxSize' => '2M',
			'defaults'		=> array(
				'read' => true,
				'write' => true
			),
			'attributes'	=> array(
				array( // Hide _*
					'pattern'	=> '/\_tmb/',
					'write'		=> false,
					'read'		=> false,
					'hidden'	=> true
				)
			),
			'tmbPath'		=> '_tmb',
			'tmbURL'		=> '../../UpFiles/' . $_REQUEST['FolderName'] . '/Albumes/_tmb',
		),
		array(
			'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
			'path'          => '../UpFiles/' . $_REQUEST['FolderName'] . '/Doc',// path to files (REQUIRED)
			 //'URL'        => dirname($_SERVER['PHP_SELF']) . '/../_files/', // URL to files (REQUIRED)
			'accessControl' => 'access', // disable and hide dot starting files (OPTIONAL)
			'alias'			=> 'Docs',
			'uploadOverwrite' => false,
			'uploadAllow'	=> array('application/pdf','application/vnd.ms-word','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.openxmlformats-officedocument.wordprocessingml.document'),
			'uploadDeny'  	=> array('all'),
			'uploadTotalSize' => '50M',
			'uploadMaxSize' => '2M',
			'defaults'		=> array(
				'read' => true,
				'write' => true
			),
			'attributes'	=> array(
				array( // Hide _*
					'pattern'	=> '/\_tmb/',
					'write'		=> false,
					'read'		=> false,
					'hidden'	=> true
				)
			),
			'tmbPath'		=> '_tmb',
			'tmbURL'		=> '../../UpFiles/' . $_REQUEST['FolderName'] . '/Doc/_tmb'
		),
		array(
			'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
			'path'          => '../UpFiles/' . $_REQUEST['FolderName'] . '/FileComPago',// path to files (REQUIRED)
			//'URL'           => '../UpFiles/' . $_REQUEST['FolderName'] . '/FileComPago', // URL to files (REQUIRED)
			'accessControl' => 'access',             // disable and hide dot starting files (OPTIONAL)
			'alias'			=> 'ComPag',
			'uploadDeny'  	=> array('all'),
			'defaults'		=> array(
				'read' => true,
				'write' => false
			),
			'attributes'	=> array(
				array(
					'pattern' => '/.*/',
					'locked'    => true
				),
				array( // Hide _*
					'pattern'	=> '/\_tmb/',
					'write'		=> false,
					'read'		=> false,
					'hidden'	=> true
				)
			),
			'tmbPath'		=> '_tmb',
			'tmbURL'		=> '../../UpFiles/' . $_REQUEST['FolderName'] . '/FileComPago/_tmb'
		)
	)
);`

**Comment by nao-pon** [comment]
Setting seems not a problem.

> Warning: fopen() [function.fopen]: open_basedir restriction in effect. File(C:WindowsTempphp3D6B.tmp) is not within the allowed path(s):

Which file and line number?

**Comment by mash180** [comment]
This is the full error:

<b>Warning</b>:  fopen() [<a href='function.fopen'>function.fopen</a>]: open_basedir restriction in effect. File(C:WindowsTempphpA544.tmp) is not within the allowed path(s): (C:/Inetpub/vhosts/gcon.com\;C:\Windows\Temp\) in <b>C:\Inetpub\vhosts\gcon.com\httpdocs\FileMgr\elFinder.class.php</b> on line <b>2086</b><br />
<br />
<b>Warning</b>:  fopen(C:WindowsTempphpA544.tmp) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Operation not permitted in <b>C:\Inetpub\vhosts\gcon.com\httpdocs\FileMgr\elFinder.class.php</b> on line <b>2086</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at C:\Inetpub\vhosts\gcon.com\httpdocs\FileMgr\elFinder.class.php:2086) in <b>C:\Inetpub\vhosts\gcon.com\httpdocs\FileMgr\elFinderConnector.class.php</b> on line <b>134</b><br />
{"added":[],"warning":["errUploadFile","imgtest.jpg","errUploadTransfer"],"removed":[]}

**Comment by nao-pon** [comment]
OK, I got it. This reason is $_FILES filtered by `stripslashes()` with `magic_quotes_gpc = on`. I'll fix it. Plz wait next nightly|version.

**Comment by mash180** [comment]
Thanks you very much

**Comment by nao-pon** [comment]
I fixed @244382249137fa9e4619205ebd086eecb16fc92f. Please try [Nightly](https://github.com/Studio-42/elFinder/archive/2.1.zip) until 2.1.10 release.
