### ISSUE TITLE
Use ANSI-SQL-compliant string quoting characters in MySQL queries

### ISSUE THREAD

**Issue by MazeChaZer** [Studio-42/elFinder#1254]
ANSI-SQL standard for quoting characters:

```
' --> string
" --> identifier (talbe, column...)
` --> not defined
```

MySQL quoting characters:

```
' --> string
" --> string
` --> indentifier
```

MySQL running in [ANSI mode](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi) quoting characters:

```
' --> string
" --> identifier
` --> identifier
```

I would like to run MySQL in ANSI mode, but this is not possible because the double quotation character (`"`) is used for quoting strings. In ANSI mode, stuff inside double quotes is treated as an identifier.

I would like to propose a new quoting convention for the SQL strings:

- Use ' (single quotation mark) for strings
- Use ` (backtick) for identifiers

Before

```php
$sql = 'SELECT * FROM `user` WHERE `username` = "johndoe"';
```

After

```php
$sql = "SELECT * FROM `user` WHERE `username` = 'johndoe'";
```

This way the SQL queries will always work in MySQL, wether it runs in ANSI mode or not.

I am willing to refactor the SQL strings and send a pull request, but I wanted to ask for your opinions beforehand.

**Comment by nao-pon** [comment]
@MazeChaZer :+1: Please send PR.
I recommend to
```php
$sql = 'SELECT * FROM `user` WHERE `username` = \'johndoe\'';
```
Because "..." with variable expansion.

**Comment by Maison-stingy** [comment]
> [@MazeChaZer](https://github.com/MazeChaZer) 👍 Please send PR. I recommend to
> 
> $sql = 'SELECT * FROM `user` WHERE `username` = \'johndoe\'';
> Because "..." with variable expansion.





https://pinia84.github.io/5AF9VA1sGERK4U9Y9ZU1zSPzc7Jjh2oMJRyZtX9VRkcOFyfb3r1tnBDycFQ5gLvblw/
