### ISSUE TITLE
I need all descriptions for all opts in js init

### ISSUE THREAD

**Issue by 53ifbb** [Studio-42/elFinder#1255]
не нашел в **Вики **описание всех ключей для массива opts в **Js**.
нету **title, destroyOnClose, autoOpen** и т.д.
эти параметры мне понятны, но я хочу видеть весь список который мне доступен, для более детальной настройки. И так же список команд

п.с. для вызова **dialogelfinder**. версия 2.1.7

**Comment by 53ifbb** [comment]
I found :smiling_imp: https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js
But not in the Wiki. The wiki is not complete

**Comment by nao-pon** [comment]
@53ifbb I know also Wiki content is poor. But, Wiki can be edited everyone! We welcome everyone's Wiki editing at any time. :+1:

**Comment by 53ifbb** [comment]
Closed :ok_hand:
