### ISSUE TITLE
PHP version is not compatible with BUG

### ISSUE THREAD

**Issue by vipwei** [Studio-42/elFinder#1257]
1, php5.2.5 version, the invalid end of the invalid prompt response.

2, php5.3.27 version, document editing, input Chinese preservation, preservation of the contents is garbled

3, create a file, the default is to create TXT format; first initialization problem set the HTML format is not supported, but modify the format of HTML can successfully create a file, not editing tips do not support; the second initialization support HTML format, successfully created equally editor's note does not support;

4, create, initialize the format does not support type is invalid, modify what formats can be created successfully

**Comment by vipwei** [comment]
4, create, initialize the format does not support type is invalid, modify what formats can be created successfully

**Comment by nao-pon** [comment]
@vipwei  What version is your elFinder? 

About (2), elFinder supports UTF-8 only.

**Comment by vipwei** [comment]
elFinder 2.17

**Comment by vipwei** [comment]
I will be here this program is integrated into a CMS background, compared with many people, the PHP environment encountered more

My background is UTF-8 encoding

Then please exhibitions, I also participated in the

**Comment by nao-pon** [comment]
1)
I tested on PHP 5.2.9 (XAMPP Windows Version 1.7.1). There is no problem.

2)
document editing with multi bytes character is no problem. Please check on [demo site](http://studio-42.github.io/elFinder/#elf_l2_Lw). And please check with standalone elFinder on your server.

3), 4)
MIME determination by the file content is required [finfo extension](http://php.net/manual/ref.fileinfo.php).

**Comment by vipwei** [comment]
1, currently found only in the php5.2.5 version, php5.2.17 are supported, php5.3 also supports

At present, 2 found that 5.3 is not supported by the version of PHP upgrade to php5.4 is not garbled

**Comment by nao-pon** [comment]
> 1, currently found only in the php5.2.5 version, php5.2.17 are supported, php5.3 also supports

OK, Can you know php errors? With `error_reporting(-1);` and watch server response in developer tool of browser.

**Comment by nao-pon** [comment]
> At present, 2 found that 5.3 is not supported by the version of PHP upgrade to php5.4 is not garbled

I think that there is problem in the configuration of PHP. Please check the settings for character encoding

**Comment by vipwei** [comment]
Now can not get, before allowing users to upgrade the PHP version to solve, and then encounter a record

**Comment by vipwei** [comment]
The second question, I'll test it later.

**Comment by nao-pon** [comment]
About (1), May be fixed @4edf186ee2a74ccde646d00b653841ddf942aa0e.

**Comment by vipwei** [comment]
OK
