### ISSUE TITLE
Dialog window has not z-index

### ISSUE THREAD

**Issue by 53ifbb** [Studio-42/elFinder#1258]
modal window of TinyMCE has z-index 300001
This is a problem when integrating

**Comment by nao-pon** [comment]
@53ifbb There is no problem in [my demo site](http://hypweb.net/elFinder-nightly/demo/tinymce/).

**Comment by 53ifbb** [comment]
@nao-pon U have z-index !
ninyMCE z-index: 65536; z-index: 65537;
elFinder z-index: 65538;

`var opts = {
			url : \'index.php?name=...',
			lang : \'ru\',
			commandsOptions:{
				getfile: {
					//onlyURL: true,
					folders: false,
					multiple: false,
					oncomplete: "destroy"
				}
			},
			getFileCallback: function(file, el){
				aWin.document.forms[0].elements[aFieldName].value = file.url;
			},
			title				: \'Файловый менеджер\',
			width				: 960,
			height				: 500,
			resizable			: false,
			rememberLastDir		: false,
			autoOpen			: true,
			destroyOnClose		: true,
			debug				: false
		};
		$("<div>").dialogelfinder(opts);`

This is not correctly:
$("<div>").css({"z-index":"999999"}).dialogelfinder(opts);

**Comment by nao-pon** [comment]
elFinder dialog has class "ui-front" for [jQuery UI Stacking Elements](https://api.jqueryui.com/theming/stacking-elements/). Can you solve this problem by TinyMCE also use the "ui-front" class?

**Comment by 53ifbb** [comment]
I will try with new version UI
p.s. current v1.9.2 (with edited)

**Comment by 53ifbb** [comment]
Because_ I forgot_ **jquery-ui.structure.css**
