### ISSUE TITLE
Very big problem with URL in opts

### ISSUE THREAD

**Issue by 53ifbb** [Studio-42/elFinder#1259]
Как установить URL значение "пусто". При вызове Elfinder, через модальное окно необходимо получить относительный путь к файлу. (getFileCallback). ?
п.с. Файловый менеджер может делать обзор с корня где установлен сайт.

**Comment by 53ifbb** [comment]
http://ipic.su/img/img7/fs/Bezymyannyj.1457718261.png

**Comment by 53ifbb** [comment]
'URL' => 'if empty' - not work (

**Comment by 53ifbb** [comment]
/ - can be used (link valid) but i can not open files in not dialog...
Dublicate array $opts ? For dialog & for insert on page?

**Comment by nao-pon** [comment]
@53ifbb What about `'URL => 'http://(Your Server Domain)/''`?

**Comment by 53ifbb** [comment]
@nao-pon if my system & elfinder installed in subfolder... sorry, this is not correctly.
I need start path from "**GetSiteDir()**", but directory of a site should not be in the address.

if 'URL' => '/' - it is start from dir of site, if elFinder can see root directiry. But other users have access to folders under... I need in all embodiments to have the correct path.

there is only one solution?
`if(isset($_REQUEST['elFinder_dialog'])){
	if(permission ... )...
	$opts['roots']['URL'] = '/';
if(permission ... )...
	if(permission ... )...
}`

**Comment by nao-pon** [comment]
OK, Please try next...
- Set **full url** to connector.php to client configuration.
- Unset 'URL' from connector root configuration.

**Comment by 53ifbb** [comment]
@nao-pon no no no)) if Unset 'URL' from connector root configuration then i have not correctle url in "the tag input".

http://pastebin.com/dbg9BGKL
http://pastebin.com/EEKRj12R
see my code. Not correctly now. Because .. . see screenshort

**Comment by nao-pon** [comment]
What `data.content` dose `$(".filemanager_icon")` have? Do you see file.url as a URL?

**Comment by nao-pon** [comment]
@53ifbb ping. May I close it?

**Comment by 53ifbb** [comment]
@nao-pon sorrrrry, now I have no time. Later I will answer.

**Comment by nao-pon** [comment]
:+1: Please reopen if needed. :-)
