### ISSUE TITLE
Incorrect files selected with ctrl-a after Search.

### ISSUE THREAD

**Issue by YanareKu** [Studio-42/elFinder#1260]
**Steps to reproduce:**
1) Navigate to any directory with files in it.
2) Search for any term with "All" by "Filename".
3) ctrl-a.

**Expected:**
Files in search are selected and the UI bar at bottom displays the correct number of 'selected items'.

**Actual:**
The files in the workarea are all highlighted and visually look as though they have been selected, but the files that are actually being selected are the ones in the directory I was in previous to using the search function.  The UI at the bottom showing the number of 'selected items' in the folder prior to searching.

**Comment by nao-pon** [comment]
@YanareKu This problem was already fixed @5e2987e9faab8ca807d81a0d53f09f3ff408f5a9.  Please check latest version or on [demo site](http://studio-42.github.io/elFinder/).
