### ISSUE TITLE
select and return an array of selected files in elfinder

### ISSUE THREAD

**Issue by ahmadbadpey** [Studio-42/elFinder#1261]
I'm using **elFinder** file manager. that is great and easy to use.

that has multi select files capability . but I want to use it for select some files then by pressing **enter **keyboard button, path of those files Be returned as an Javascript Array.

This is My code to initialize elFinder instance :

```
$('.add-item').on('click', function () {

    var filesArr = [];

    $('<div id="editor" />').dialogelfinder({
        url: './elfinder/php/connector.minimal.php',
        getFileCallback: function (file) {
            $('#editor').dialogelfinder('close');
            console.log(file.url);
        }
    });


});
```
that works when select one file but when user select multi files and press **enter**, all selected files opens for preview only.

How can I do that?

**Comment by 53ifbb** [comment]
`commandsOptions:{
				getfile:{
					onlyURL: true,
					folders: false,
					multiple: false,
					oncomplete: "destroy"
				}
			},`

**Comment by nao-pon** [comment]
@ahmadbadpey for example
```javascript
commandsOptions: {
    getfile: { multiple: true }
},
getFileCallback : function(file) {
    var urls = $.map(file, function(f) { return f.url; });
    console.log(urls);
},
```

**Comment by ahmadbadpey** [comment]
@nao-pon, your solution is true but I have a new Problem.

this is my Complete code : 
```
$('.add-item').on('click', function () {

        $('<div id="editor" />').dialogelfinder({
            url: './elfinder/php/connector.minimal.php',
            commandsOptions: {
                getfile: { multiple: true }
            },
            getFileCallback : function(file) {
                $('#editor').dialogelfinder('close');

                var urls = $.map(file, function(f) { return f.url; });
                console.log(urls);
            }

        });
    });
```

problem is that in the first initialization of elfinder by clicking on **.add-item** button all things works fine but in the next initializations when I select multi files , elfinder dialoge Stays open.

What is problem?

**Comment by redhabravo** [comment]
where I can find complete tutorial? I using codeigniter, bootstrap and I want to get selected url file to input text

**Comment by carriopablo** [comment]
Solved there #3027

**Comment by goodPointP** [comment]
How do I get the selected filepath (not only the name)?

**Comment by johnfort** [comment]
> How do I get the selected filepath (not only the name)?

`getFileCallback: function( file, fm ){
	console.log(file['url']);
}`
