### ISSUE TITLE
path return backslash but url return slash in getFileCallback

### ISSUE THREAD

**Issue by ahmadbadpey** [Studio-42/elFinder#1263]
this code is for select and return path of multi file selection in elFinder as an Array : 
```
commandsOptions: {
                getfile: {
                    multiple: true ,
                    oncomplete : 'destroy'
                }
            },
            getFileCallback : function(file) {
                var allPath= $.map(file, function(f) {
                    return f.path;
                });
                console.log(allPath);
            }
```
I found that when using **path** property for **file** parameter passed to **getFileCallback** function that return path of file with **backslash** like this:
`["userfiles\pic1.jpg"]`

but when use **url** property for **file** returned path contains slashes like this : 
```
["/photoManager/elfinder/php/../../userfiles/pic1.jpg"]
elfinder.min.js:10 elfinder debug: [event-destroy] [editor] undefined
```

I want **path** property also use slashes as file and folder separation like **url** property .

I am using windows and localhost

**Comment by nao-pon** [comment]
@ahmadbadpey Directory separater of `path` is server's directory separater. so it uses `\` on Windows server.

**Comment by ahmadbadpey** [comment]
@nao-pon , thanks but is there a way to Correct this difference in widows and other operating system

**Comment by nao-pon** [comment]
How is this?
```javascript
getFileCallback : function(file, fm) {
	var replace = fm.option('separator') === '\\';
	var allPath = $.map(file, function(f) {
		return replace? f.path.replace('\\', '/') : f.path;
	});
	console.log(allPath);
},
```

**Comment by ahmadbadpey** [comment]
Thanks @nao-pon
