### ISSUE TITLE
global configuration for all elfinder instances

### ISSUE THREAD

**Issue by ahmadbadpey** [Studio-42/elFinder#1264]
I want to set some global configuration options for all instances of elFinder that created in whole a website.
For example I want all elFinder instances be have specific _width_ ,  _height_  or  _locale_ option. 

i do not want to repeat this options on each **elfinder** calling.

is there a way to do that?

**Comment by nao-pon** [comment]
@ahmadbadpey Overwrite `elFinder.prototype._options`.

```html
<script src="js/elfinder.min.js"></script>
<script type="text/javascript" charset="utf-8">
var myOpts = {
    url: ''
}
$.extend(true, elFinder.prototype._options, myOpts);
</script>
```
There is full options in [`elFinder.options.js`](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js).

(I have not tested.)

**Comment by ahmadbadpey** [comment]
@nao-pon ,Thanks that works fine
