### ISSUE TITLE
image thumbnails does not show in windows and linux server

### ISSUE THREAD

**Issue by ahmadbadpey** [Studio-42/elFinder#1265]
I test elfinder on **windows localhost** and on a **linux server** but while thumbnail image has created in _.tmb_ folder but has no preview on the elFinder instances.

this is a elfinder dialog window: 
 
![elfinder](http://oi64.tinypic.com/2uogq2q.jpg)

I test 755 , 775 permissions for .tmb folder on the linux server but the problem is not resolved.

what is problem and haw can I solve that?

**Comment by nao-pon** [comment]
@ahmadbadpey Please try a volume root config [`tmbURL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#tmbURL).

**Comment by ahmadbadpey** [comment]
@nao-pon , I test it already like :
```
'tmbURL'        => dirname($_SERVER['PHP_SELF']) . '/../../userfiles/.tmb/',
'tmpPath'       =>  '/../../userfiles/.tmb/',
```
folder _userfiles_ that holds pictures are in same directory that _elfinder_ folder is.

of course when I inspect placeholder thumbnails icon in elfinder , address of picture that is applied to background-image is right and when I opens it in new tab , it shown very well.

![http://tinypic.com/r/2wdaxk8/9](http://tinypic.com/r/2wdaxk8/9)

but I do not know why it Not shown

**Comment by nao-pon** [comment]
umm... What about default theme?

**Comment by ahmadbadpey** [comment]
ohhh, it works on default theme but not in moono theme?
whyyyy?

**Comment by nao-pon** [comment]
This is by design of moono theme.

effects css is next

theme.css L.54
```css
.elfinder-cwd-icon {
  background-image: none !important;
  overflow: hidden;
}
```
AND
theme.css L.111
```css
/* images */
.elfinder-cwd-icon-image:before,
.elfinder-cwd-icon-vnd-adobe-photoshop:before,
.elfinder-cwd-icon-postscript:before {
  /*! content: '\f1c5'; */
}
```

**Comment by ahmadbadpey** [comment]
@nao-pon , Thanks , you are amazing
