### ISSUE TITLE
Maximum ascension while searching

### ISSUE THREAD

**Issue by kukko** [Studio-42/elFinder#1266]
Hello!

It think it would be great if there would be an option whisch describe how the searchin how many folders can ascend from the current folder or we could write a regular expression and elFinder ascend from the current folder until it's don't find a folder which name is equal the expression or it's don't reach the "root" which the elFinder can work in. Or we can define a fix folder name, when which is found it's will not go upper.

**Comment by nao-pon** [comment]
@kukko I'm just thinking now. What about search word "png -img"? Do search "png" but exclude "img" directory.

**Comment by kukko** [comment]
I think the users will not type this all the time, because not all of them are programmers or IT technicians.

**Comment by nao-pon** [comment]
@kukko Are you want add a config of volume root options? e.g. `serachExcludeDirs`?

P.S. "Maximum ascension" option is difficult, because some volume driver dose not use recursive processing.

**Comment by nao-pon** [comment]
@kukko Added volume root config
```php
// Search exclusion directory regex pattern (require demiliter e.g. '#/path/to/exclude_directory#i')
'searchExDirReg'  => '',
```
