### ISSUE TITLE
Return focus to input after failing to rename file

### ISSUE THREAD

**Issue by svetlanadzhura** [Studio-42/elFinder#1269]
Hi! Is it possible to return focus to input area after renaming was failed? For example, I try to rename file with new name which is the same name as an existing file. I get a warning message "File named $1 already exists." After closing that dialog I would like to have my cursor back to the input textarea to continue renaming. Thanks

**Comment by nao-pon** [comment]
@svetlanadzhura Thanks!

**Comment by svetlanadzhura** [comment]
Brilliant! Thank you!

**Comment by svetlanadzhura** [comment]
During renaming I tried to enter empty name (that is empty file name and file extension) . Now I get constantly Error dialog - trying to close one dialog I get another one again and again until I press escape. And sometimes after finally closing Error dialog by escape elfinder gets unresponsive (what is linked with modal mode I suppose)

**Comment by nao-pon** [comment]
@svetlanadzhura Thanks! :+1:

**Comment by svetlanadzhura** [comment]
just applied changes @ 667b1d1. Fix works perfectly, thank you, amazing work as always!
