### ISSUE TITLE
version 1 proxy fails for version 2.0.6 open command

### ISSUE THREAD

**Issue by wolfmanx** [Studio-42/elFinder#1270]
the frontend 'open' command has been changed to call the backend 'file' command directly:

			var params = $.extend({}, fm.options.customData, {
				cmd: 'file',
				target: file.hash
			});

however the necesary translation to a backend 'open' command for the version 1 proxy is missing:

			if (fm.oldAPI) {
				params.cmd = 'open';
				params.current = file.phash;
			}

**Comment by nao-pon** [comment]
@wolfmanx Thanks! 2.1(master) is supported API v1 at now. My test site is [here](http://hypweb.net/elFinder-nightly/demo/develop/elfinder10.html).
