### ISSUE TITLE
Unable to delete lots of files at the same time

### ISSUE THREAD

**Issue by svetlanadzhura** [Studio-42/elFinder#1271]
I try to delete 150+ with total size 15 Mb together but get error message "Unable to connect to backend". Is there any size/number of files restriction for file deletion? Thank you!

**Comment by nao-pon** [comment]
@svetlanadzhura Please try clientcconfiguration [`requestType`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#requesttype) to `'post'`.

**Comment by svetlanadzhura** [comment]
It works! Thank you for your help and quick response!
