### ISSUE TITLE
Modified date

### ISSUE THREAD

**Issue by 200MPH** [Studio-42/elFinder#1272]
I'm experiencing and issue with modified date.

On the FTP server I have one file create per day but elFinder shows me many files modified today with future date.

I though upgrade will help but not, still having same issue.

My current version is 2.1.9 (6fce215)

Regards,

**Comment by nao-pon** [comment]
@200MPH What is your FTP server? And Can you show of raw data of FTP LIST or FTP MLST?

**Comment by 200MPH** [comment]
Server is PROFTPD raw data (timestamp) is correct, looks like java script
convert it wrong. My local time is also set correct.

**Comment by nao-pon** [comment]
What value of timestamp? And Is elFinder to show how timestamp to you?

**Comment by 200MPH** [comment]
I picked timestamp value from json output and convert it to real date time
value which is correct, however elFinder display wrong week day for
modified date like "Today, 14:25" which has been modified last week
therefore I can't sort by modified  column.

I back on Monday from holiday so I will send you more examples as screen
shots.

**Comment by nao-pon** [comment]
Does your PC clock is correct date? Is the same also by changing the browser?

**Comment by 200MPH** [comment]
Clock is ok.

I will check on another browser

**Comment by 200MPH** [comment]
OK,

Sorry for deleyed respond.

Google & Firefox the same issue.
I've noticed problem occured in folders contains 150+ files.

Please see attachment.
![elfinderbug](https://cloud.githubusercontent.com/assets/16258307/14706085/96b9f5de-07b4-11e6-9e57-f15e559be9f6.png)

I made the screen shot at 11:15 AM.
As you see there is future date like "Today 2.30 PM"

I will try update jQuery library and see what happen.

**Comment by nao-pon** [comment]
@200MPH I found a bug in php/elFinderVolumeFTP.class.php. I'll fix it.

**Comment by nao-pon** [comment]
@200MPH Thanks! :+1:
