### ISSUE TITLE
Is Client Server API 2.1 the most recent documentation?

### ISSUE THREAD

**Issue by ma2tkraus** [Studio-42/elFinder#1274]
There appear to be quite a few differences between the current live demo and the documentation.  
https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1

- The file/directory object docs show a "tmb" object but the demo does not use it. It appears to have been replaced by "tmbUrl".
- The demo has a "isowner" element. missing form the docs.
- The demo has a "csscls" element, missing from the docs.
- "uiCmdMap" ditto

Open command options:
- uploadOverwrite missing
- uploadMaxSize missing
- dispInlineRegex missing
- jpgQuality missing
- createeext missing
- archivers changed format

Hopefully there are newer docs someone can point me to.

Thanks

**Comment by nao-pon** [comment]
I have been aware of is that you are not equipped with the development of the document. However, there is no time to do it now. We are now looking for the cooperator to wiki editing.

**Comment by ma2tkraus** [comment]
The good news is that the API has evolved quite a bit and is much more capable than documented. If you can update two commands a day you can be done in a week.  Keep up the good work.

**Comment by nao-pon** [comment]
mostly fixed.
