### ISSUE TITLE
elFinder 2.1 slower than 2.0

### ISSUE THREAD

**Issue by kukko** [Studio-42/elFinder#1276]
Hi!

I updated the elFinder on my system a few days ago and the previous 2.0 version was really fast. But the new 2.1 is so slow. When I try to upload file, or select, delete, rename a file, it's think some seconds.

Can I set something in the options to make it faster?

**Comment by nao-pon** [comment]
@kukko My elFinder 2.1 is not slow. Please check on [Demo site](http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l2_Lw). Can you debug in elFinder? I can take steps when the bottle neck is found where it is.

**Comment by kukko** [comment]
Debugging is enabled in VolumeLocalFileSystem, but it's not create any log file in the temp folder.

**Comment by nao-pon** [comment]
Client-side or server-side, which is do you know the cause?

**Comment by kukko** [comment]
The server side cause the problem. A single request takes for seconds until the first bite.

**Comment by nao-pon** [comment]
How many files/directories exists in the target directory?

**Comment by kukko** [comment]
In one of the folders are 306 files, an other have 4 and there is an empty directory. And a symlink, which isn't followed by elFinder, so I think It's not counting.

**Comment by nao-pon** [comment]
It number of files does not appear to be a problem...

Please check on standalone If it is integrated to something.

**Comment by kukko** [comment]
I tried it, but it is still produce the same speed.

**Comment by nao-pon** [comment]
It is difficult to find the cause because there is no problem here. Can you locate the bottleneck by providing a measurement point of execution time in the code on your side?

**Comment by kukko** [comment]
I tried some things (I turned off debugg mode and logging), but these didn't helped. I think I can figure out why it's not create any log file, I can do some steps towards solving the problem.

**Comment by kukko** [comment]
Excuse me, that's my fault. I not commented out the FTP driver settings, which is tried to connect to a server, but because it's can't, the connection attempts freezed the connector for some time.

**Comment by nao-pon** [comment]
@kukko Don't worry. Cause is found I also was relieved. :grinning:
