### ISSUE TITLE
[VolumeDropbox] I can not make it work

### ISSUE THREAD

**Issue by Kravalg** [Studio-42/elFinder#1277]
I want to use elFinder as viewer folders and files in dropbox. But I keep getting an error message: "The OAuth class could not be found! Did you install and enable the oauth extension?" or "The OAuth class could not be found".
composer.json:
"require": {
        "php": ">=5.2",
        "dropbox-php/dropbox-php": "dev-master",
        "pear/auth": "dev-master",
        "pear/http_request2": "dev-master",
        "pear/net_url2": "dev-master"
    },
connector.minimal.php:
include_once '../vendor/autoload.php';

include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderConnector.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinder.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeDriver.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeDropbox.class.php';

define('ELFINDER_DROPBOX_CONSUMERKEY',    '----------------');
define('ELFINDER_DROPBOX_CONSUMERSECRET', '----------------');

$opts = array(
	'debug' => true,
	'netVolumesSessionKey' => 'netVolumes',
	'roots' => array(
		array(
			'driver'        => 'Dropbox',           // driver for accessing file system (REQUIRED)
			'consumerKey'       => '----------------------',
			'consumerSecret'    => '----------------------',
			'accessToken'       => '-----------------------------------------------------',
			'accessTokenSecret' => '---------------------------------------------------',
			'path' => '/',
                        ...

Already running the command "composer update".
I don `t know already that and try. Help...

**Comment by nao-pon** [comment]
@Kravalg Plz try `composer require pear/http_oauth` and newest [elFinderVolumeDropbox.class.php](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeDropbox.class.php).

Thanks! :+1:

**Comment by Kravalg** [comment]
This thank you for your efforts :)
