### ISSUE TITLE
How to disable folder download?

### ISSUE THREAD

**Issue by svetlanadzhura** [Studio-42/elFinder#1278]
Is there any options to disable 'Download' icon in toolbar and 'Download' item in context menu for folders? Im using mvc connector and It would be helpful to be able to disable folder download somehow, for example through option 'commandsOptions:{download:{folder:false}}' or somehow else (if such option does not exist yet). Thank you!

**Comment by nao-pon** [comment]
@svetlanadzhura You can use connector root config [`disabled`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#disabled).
```php
'disabled' => array('zipdl')
```
I can found tyny bug in elFinder.js. But fixed https://github.com/Studio-42/elFinder/commit/7a4d8202e8ba16c3c4d54d5297f977d5629d8463.

**Comment by svetlanadzhura** [comment]
Thank you for response! This disabling works perfectly for folders in root dir, but does not work for subfolders

**Comment by nao-pon** [comment]
> but does not work for subfolders

This is currently bug. It was fixed. Please wait next release or try nightly.
