### ISSUE TITLE
[ Dropbox Authenticate ] Dropbox error

### ISSUE THREAD

**Issue by Kravalg** [Studio-42/elFinder#1279]
Error:
 "Dropbox error: Forbidden. Bad or expired token. This can happen if the user or Dropbox revoked or expired an access token. To fix, you should re-authenticate the user."

'consumerKey'       => 'o--------------', //app key
'consumerSecret'    => 'f--------------', //app secret
'accessToken'       => '------------------------------------------------------------------------------------', //oauth access token
'accessTokenSecret' => '-----------------------------------------------------------------------------',//oauth access token

Or if I change the place of their:

'consumerKey'       => '-----------------------------------------------------------------------------',//oauth access token
'consumerSecret'    => '-----------------------------------------------------------------------------',//oauth access token
'accessToken'       => 'o--------------', //app key
'accessTokenSecret' => 'f--------------', //app secret

I get error: "Dropbox error: Forbidden. This could mean a bad OAuth request, or a file or folder already existing at the target location."

Why there should be two access tokens if dropbox gives only one access token, one app key and one app secret key??

They may be the same?
accessToken and accessTokenSecret?

**Comment by nao-pon** [comment]
Dropbox driver of elFinder is using OAuth 1.0. it requires four tokens('consumerKey', 'consumerSecret', 'accessToken', 'accessTokenSecret') if you want to a permanent mount.
If the net mount, can operate by the user authentication and two tokens('consumerKey', 'consumerSecret').
