### ISSUE TITLE
[Flysystem Dropbox] Too long waiting time

### ISSUE THREAD

**Issue by Kravalg** [Studio-42/elFinder#1281]
I waited 19 seconds to find that the folder is empty.
Stack trace: 
{"cwd":{"size":0,"ts":1458659319,"read":1,"write":1,"mime":"directory","hash":"fls1_cm96c3plcnpvbnl3b2x1bWluLzIwMTYvMTQ2XzIwMTYvc3RyYXogZ3Jhbmljem5h"
,"name":"straz graniczna","phash":"fls1_cm96c3plcnpvbnl3b2x1bWluLzIwMTYvMTQ2XzIwMTY","volumeid":"fls1_"
},"options":{"path":"rozszerzonywolumin\/rozszerzonywolumin\/2016\/146_2016\/straz graniczna","url":""
,"tmbUrl":"","disabled":["archive","extract","chmod"],"separator":"\/","copyOverwrite":1,"uploadOverwrite"
:1,"uploadMaxSize":9223372036854775807,"dispInlineRegex":"^(?:(?:image|text)|application\/x-shockwave-flash$
)","jpgQuality":100,"archivers":{"create":[],"extract":[],"createext":[]},"uiCmdMap":[],"syncChkAsTs"
:0,"syncMinMs":30000},"files":[],"debug":{"connector":"php","phpver":"7.0.4","time":19.19310593605,"memory"
:"4034Kb \/ 2238Kb \/ 128M","upload":"","volumes":[{"id":"fls1_","name":"flysystem","mimeDetect":"finfo"
,"imgLib":"gd"}],"mountErrors":[]}}

I use Flysystem connector.

My connector.minimal.php file:

$client = new Client('-----------------------------------------------------------------', '----------------------');
$localAdapter = new DropboxAdapter($client);

$cacheStore = new CacheStore();
$adapter = new CachedAdapter($localAdapter, $cacheStore);
$filesystem = new Filesystem($adapter);

$opts = [
	'debug' => 1,
	'treeDeep' => 1,
	'roots' => [
		[
			'driver' => 'Flysystem',
			'path' => 'rozszerzonywolumin',
			'filesystem' => $filesystem
		]
	]
];

In general, all actions based on a sample listing of folders and files is very slow. How can I speed up the loading or otdebazhit which component slows down?

**Comment by nao-pon** [comment]
@Kravalg I've never had to use the Dropbox adapter of FlySystem, I think that it is necessary to be comfortable to use some of the expansion in elFinder.

Not enough for Dropbox driver of elFinder?

**Comment by Kravalg** [comment]
Yours Dropbox driver use old library dropbox-php. This library is no longer a supported. Flysystem Dropbox driver use dropbox-sdk-php (https://github.com/dropbox/dropbox-sdk-php).
Especially because I still could not make work your extension.

**Comment by Kravalg** [comment]
Could you help me to debug it?
I can not believe that it can be processed as long request to open an empty folder.

**Comment by nao-pon** [comment]
@Kravalg I tried FlySystem-Dropbox with memcached.with [nao-pon/flysystem-cached-extra](https://packagist.org/packages/nao-pon/flysystem-cached-extra).

It will be displayed in an instant or two to three seconds.

```php
$cache = null;

$cacheKey = 'HypElfDropbox';
$memcached = new Memcached();
if ($memcached->addServer('localhost', 11211)) {
	class myCachedAdapter extends \League\Flysystem\Cached\Storage\Memcached
	{
		use \Hypweb\Flysystem\Cached\Extra\Hasdir;
	}
	$cache = new myCachedAdapter($memcached, $cacheKey2, 300);
}

$client = new \Dropbox\Client($accessToken, $appSecret);

$service = new \League\Flysystem\Dropbox\DropboxAdapter($client, $rootpath);

if ($cache) {
	$adapter = new \League\Flysystem\Cached\CachedAdapter($service, $cache);
} else {
	$adapter = $service;
}

$filesystem = new \League\Flysystem\Filesystem($adapter);

$dropbox = [
    'driver' => 'Flysystem',
    'alias'  => 'Dropbox-Flysystem',
    'filesystem' => $filesystem,
    'fscache' => $cache
];

$opts['roots'][] = $dropbox;
```

**Comment by Kravalg** [comment]
Thank you.
I don't have access to the server, that is memcached I can hardly put.
But I'm still wondering why so long to work out the script?
Walk a few abstractions, make a request, send it to the server, receive the response, decrypt and send to the client. What could slow down here?

**Comment by nao-pon** [comment]
The new [elfinder-flysytem-driver 0.2.x](https://github.com/barryvdh/elfinder-flysystem-driver) is faster by eliminating the detection of subfolders by default.

I close this once.

**Comment by Kravalg** [comment]
Composer said:
 > Composer require barryvdh/elfinder-flysystem-driver
Using version ^0.2.0 for barryvdh/elfinder-flysystem-driver
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for studio-42/elfinder No version set (parsed as 1.0.0) -> satisfiable by studio-42/elfinder[No version set (parsed as 1.0.0)].
    - barryvdh/elfinder-flysystem-driver v0.2.0 requires studio-42/elfinder ^2.1.10 -> satisfiable by studio-42/elfinder[2.1.10, 2.1.11].
    - Can only install one of: studio-42/elfinder[2.1.10, No version set (parsed as 1.0.0)].
    - Can only install one of: studio-42/elfinder[2.1.11, No version set (parsed as 1.0.0)].
    - Installation request for barryvdh/elfinder-flysystem-driver ^0.2.0 -> satisfiable by barryvdh/elfinder-flysystem-driver[v0.2.0].


Installation failed, reverting ./composer.json to its original content.

**Comment by nao-pon** [comment]
please try

```
composer remove studio-42/elfinder
```

or If you want elFinder nightly version

```
composer require studio-42/elfinder:2.1.x@dev
```

**Comment by Kravalg** [comment]
Okay, I installed this extension. But how do I use it?

**Comment by Kravalg** [comment]
And please add "version": "2.1.11", into composer.json file in project.
