### ISSUE TITLE
Implemented Google Cloud Storage, volume icon not showing

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1282]
I used Flysystem to add GCS support and it is working nicely, however, the root entry for my GCS bucket is trying to load the volume icon from the wrong directory.

I have a root entry for a local directory, and that shows the volume icon nicely in the file tree view.

I installed elFinder from Composer (actually as a dependency from another module) so the icon lives in "http://localhost/app/vendor/studio-42/elfinder/img/volume_icon_local.png" (and this is loaded for the local directory. But the GCS entry is trying to load "http://localhost/app/img/volume_icon_local.png"

Is there a way to tell the root entry to look at a specific icon to load in the file tree?

**Comment by nao-pon** [comment]
@paulcanning Constant "ELFINDER_IMG_PARENT_URL" is available.

e.g.
```php
define('ELFINDER_IMG_PARENT_URL', 'http://localhost/app/');
```

ref. https://github.com/barryvdh/elfinder-flysystem-driver/blob/master/src/Driver.php#L100

**Comment by paulcanning** [comment]
Thank you! Where do I set this exactly?

**Comment by nao-pon** [comment]
Anywhere OK before it create an instance of the class elFinder.

**Comment by paulcanning** [comment]
I figured it out not long after :) Think I need to do the same for sounds
