### ISSUE TITLE
Cannot access root volume after removing access attributes

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1283]
I have a root volume pointing at a local folder and was testing the access attributes, which I still can't figure out properly (poor documentation)

So I removed the attributes entirely, but now I cannot see the root volume at all. The directory and files are there when I use Windows Explorer, but they are not visible in elFinder.

EDIT - If I add a new volume, with a new new directory name, I can see it. I renamed this new folder and changed the volume name to match, and it's still not visible.

**Comment by nao-pon** [comment]
What is new folder name? Other than the ascii string are often can not handle correctly on windows server.

**Comment by paulcanning** [comment]
I was using the same name throughout, "files"

**Comment by nao-pon** [comment]
Can you show your connector.php here?

**Comment by paulcanning** [comment]
```
public function elfinder_init()
	{
		$this->load->helper('path');
		$opts = array(
				array(
					'driver' => 'LocalFileSystem',
					'path' => set_realpath('files'),
					'URL' => base_url('files') . '/'
				)
			)
		);
		$this->load->library('elfinder_lib', $opts);
	}
```

I used the example access control from the wiki.

**Comment by nao-pon** [comment]
Where is `accessControl` option and that function?

**Comment by paulcanning** [comment]
The location was correct. And I explained, I removed the accessControl, but the option I used was the same as in your wiki, so I didn't see a need to include the code.

**Comment by nao-pon** [comment]
Since the root of the information in the session data is cached, please check in once destroys the session data.
