### ISSUE TITLE
elfinder doesn't create thumbnails in the thumbnails directory

### ISSUE THREAD

**Issue by Ybalrid** [Studio-42/elFinder#1284]
Hi there, 
I'm running the latest release available.

I have a folder with a bunch of images (regular jpeg files), but elfinder doesn't show thumnails. 

here's my connector config : 

```
$opts = array(
	'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '/home/files/',                 // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../..', // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			//'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access',			// disable and hide dot starting files (OPTIONAL)
			'mimeDetect' => 'internal',
			'imgLib'     => 'gd',
			'tmbPath' => '/home/files/thumbs',
			'tmbUrl' => dirname($_SERVER['PHP_SELF']) . '/../../thumbs'
			
		)
	)
);

```
elfinder is installed into a "TEST" subdirectory on the server. this explain the /../.. added in the URL to get the root,
the URL varaible is set corectly (I can get the files by cliking on them) so browsing the files is working correctly.
/home/files is the document root of the webserver.
the folder /home/files/thumbs has been created with 777 right by elfinder itself but *stay empty*.

The server is running PHP 7.0.4 with gd activated. "GD imaging" is present in the "modules" section of my phpinfo.

I don't get any error message anywhere. 

I hope I'm not missing something stupid. I'm playing around with the tmb* config variables but I can't get thumbnails created nor displayed...

**Comment by nao-pon** [comment]
@Ybalrid Please check xhr request. Can you see cmd=tmb request?

**Comment by arianmares** [comment]
I have the same issue. No, there are not cmd-tmb requests.

**Comment by nao-pon** [comment]
@arianmares Please check return value is `true` of [`elFinderVolumeDriver::canCreateTmb()`](https://github.com/Studio-42/elFinder/blob/b0e2c1a4856dbeb82f35057b20f59c55f223270d/php/elFinderVolumeDriver.class.php#L3941-L3947)

```php
	protected function canCreateTmb($path, $stat, $checkTmbPath = true) {
		return (!$checkTmbPath || $this->tmbPathWritable) 
			&& (!$this->tmbPath || strpos($path, $this->tmbPath) === false) // do not create thumnbnail for thumnbnail
			&& $this->imgLib 
			&& strpos($stat['mime'], 'image') === 0 
			&& ($this->imgLib == 'gd' ? in_array($stat['mime'], array('image/jpeg', 'image/png', 'image/gif', 'image/x-ms-bmp')) : true);
	}
```

**Comment by arianmares** [comment]
Yes, this was very helpfull. $this->imgLib was returning nothing because gd was not installed. 
Thanks

**Comment by Ybalrid** [comment]
@nao-pon Can you elaborate? cmb=tmb? What should I do?

**Comment by nao-pon** [comment]
![](http://xoops.hypweb.net/modules/xelfinder/index.php/view/2025/elFinderF12.png)
@Ybalrid Open webmaster tools network tab(XHR) of browser. And make a new image file(upload or duplicate). You can see cmd=tmb request if tmb function is enabled.

**Comment by Ybalrid** [comment]
![ss 2016-03-25 at 01 53 37](https://cloud.githubusercontent.com/assets/1816251/14035259/75995ff4-f22c-11e5-995b-f81905a1b396.png)

This is what I have after uploading a jpeg file. 
I don't see a cmb=tmb request, as you can see by the screengrab

**Comment by nao-pon** [comment]
Probably result of `elFinderVolumeDriver::canCreateTmb()` is `false`. please check it.

ref. https://github.com/Studio-42/elFinder/issues/1284#issuecomment-200815335

**Comment by Ybalrid** [comment]
Can you tell me how to check that? I didn't took the time to dive into elfinder source code, sorry.

**Comment by nao-pon** [comment]
Add next code to your connector.php
```php
function debug() {
    $arg = func_get_args();
    ob_start();
    foreach($arg as $v) {
        var_dump($v);
    }
    $o = ob_get_contents();
    ob_end_clean();
	file_put_contents('debug.txt', $o, FILE_APPEND);
}
```
And edit your php/elFinderVolumeDriver.class.php

```php
	protected function canCreateTmb($path, $stat, $checkTmbPath = true) {
		return (!$checkTmbPath || $this->tmbPathWritable) 
			&& (!$this->tmbPath || strpos($path, $this->tmbPath) === false) // do not create thumnbnail for thumnbnail
			&& $this->imgLib 
			&& strpos($stat['mime'], 'image') === 0 
			&& ($this->imgLib == 'gd' ? in_array($stat['mime'], array('image/jpeg', 'image/png', 'image/gif', 'image/x-ms-bmp')) : true);
	}
```
to
```php
	protected function canCreateTmb($path, $stat, $checkTmbPath = true) {
		debug('path', $path);
		debug('tmbPath', $this->tmbPath);
		debug('tmbPathWritable', $this->tmbPathWritable);
		debug('imgLib', $this->imgLib);
		debug('mime', $stat['mime']);
		return (!$checkTmbPath || $this->tmbPathWritable) 
			&& (!$this->tmbPath || strpos($path, $this->tmbPath) === false) // do not create thumnbnail for thumnbnail
			&& $this->imgLib 
			&& strpos($stat['mime'], 'image') === 0 
			&& ($this->imgLib == 'gd' ? in_array($stat['mime'], array('image/jpeg', 'image/png', 'image/gif', 'image/x-ms-bmp')) : true);
	}
```
And check debug.txt (there is in directory of connector.php)

**Comment by nao-pon** [comment]
@Ybalrid Did you solve?

**Comment by nao-pon** [comment]
@Ybalrid Prease reopen if you don't have solved.

**Comment by ducvu91** [comment]
hi, in localhost it work good, but when up hosting, in hosting this prevent folder public and then, i put it folder upload with root path. finally, elFinder can't not run
![Screenshot_3](https://user-images.githubusercontent.com/19793530/56453791-a3ad2b00-6371-11e9-8235-2ef640e52145.png)
