### ISSUE TITLE
Error moving file from one GCS bucket (in sub-folder) to another bucket (root folder)

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1285]
NB - I have posted this here as the file giving me the error is from the elFinder base library.

I get the following error when trying to move a file from "my-bucket/sub-doler/file.txt" to "my-other-bucket/file.txt"

Fatal error: Nesting level too deep - recursive dependency? in C:\wamp\www\my-app\application\libraries\elfinder\elFinderVolumeDriver.class.php on line 1887

Update - I get the same error trying when no sub-folder is involved.

**Comment by paulcanning** [comment]
I fixed the issue, I'll do a pull request

**Comment by nao-pon** [comment]
@paulcanning Please send PR to master.
