### ISSUE TITLE
How to add additional file "meta-data" from database?

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1286]
I have a requirement and I'm unsure as to whether this is possible with elFinder?

Ideally I need to list files (from Google Cloud Storage, this bit I have managed with elFinder extensions) and include additional "meta-data" that is stored in a database.

Files are going to be organised into folders with a name representing a "job" e.g. job_abc123, and this folder will contain various files for that job.

So, we can fairly easily reference a single file using the job folder name and the file name itself (ignore possible duplication issues for now)

Is there a way to use elFinder to call a database and append the data to the file information?

**Comment by nao-pon** [comment]
@paulcanning. Is the [`bind`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind) your helpful?

**Comment by paulcanning** [comment]
I'm not sure. Bind seems like it works after an action is performed? I need to get data form the database when files are displayed. If bind can do this, then yes. But I cannot find any example of how to parse through each file to add the extra data

**Comment by nao-pon** [comment]
> I need to get data form the database when files are displayed. If bind can do this

Yes, here is example.

**connector side**
```php
function addExtra($cmd, &$result, $args, $fm) {
	if (isset($result['cwd']) && $result['cwd']['volumeid'] === 'l1_') {
		foreach($result['files'] as $i => $file) {
			$result['files'][$i]['extra'] = 'Extra data of '.$file['name'];
		}
	}
}
$opts = array(
	//'debug' => 1,
	'sessionCacheKey' => 'elfinder-elf',
	'bind' => array('open' => array('addExtra')),
	'roots' => array([vollume roots])
);
```
**client side**
```javascript
$('#elfinder').elfinder({
	url : 'connector.php',
	commandsOptions : {
		info : {
			custom : {
				extra : {
					label : 'Extra data',
					tpl : '<div class="elfinder-info-extra"><span class="elfinder-info-spinner"></span></div>',
					action : function(file, fm, dialog) {
						dialog.find('div.elfinder-info-extra').html(file.extra || 'None');
					}
				}
			}
		}
	}
});
```
You can see the Extra data in info dialog.

**Comment by paulcanning** [comment]
I have added the above code into my project, but I cannot see any extra info alongside the file.

If I open the file (a text file) I simply get the popup window with the file contents in it.

Hovering over the file just shows the date.

**Comment by paulcanning** [comment]
Turns out the function has to be added to the Elfinder_lib.php file.

**Comment by nao-pon** [comment]
`open` is called when open the folder. If not called, the function is not enabled call.

**Comment by paulcanning** [comment]
`info` doesn't seem to do anything?

**Comment by nao-pon** [comment]
`Info` is different from the client of the info command. It has been used in such as confirmation of the file information in the pre-flight of the other commands.

**Comment by paulcanning** [comment]
Is there a way to include the extra data in a column in the list view?

**Comment by paulcanning** [comment]
I found out by looking in the issue list. Can you please update the 2.1 documentation? It is way behind and lacks a lot of information.
