### ISSUE TITLE
Available bind actions

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1288]
Can someone provide a full list of the available actions that can be used for the bind callbacks.

The documentation states `mkdir mkfile rename duplicate upload rm paste` - is this all the available actions?

**Comment by nao-pon** [comment]
@paulcanning There is in source code of [elFinder.class.php](https://github.com/Studio-42/elFinder/blob/master/php/elFinder.class.php#L117-L145).

**Comment by paulcanning** [comment]
Can this be documented please?

**Comment by nao-pon** [comment]
Unfortunately cannot provide immediately, so that document is not written.

**Comment by nao-pon** [comment]
I edited [section bind of Wiki](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind).
