### ISSUE TITLE
Lazy load bug

### ISSUE THREAD

**Issue by dneykov** [Studio-42/elFinder#1293]
Hi everyone,
I'm having trouble with lazy loading files. Is not working I'm trying changing the threshold but no differences. Anyone have suggestion?
Thank

**Comment by nao-pon** [comment]
@dneykov 
The Wiki offers a Lazy Load, but to be precise is Lazy Rendering. From the server you will receive all of the items at one time. Lazy function of Rendering is working without any problems.

**Comment by dneykov** [comment]
@nao-pon 
Yes you are right, from the server i'm receiving all files. But only 30 of them are showed, when I scroll down to the end no more files are showed. In my case I have 45 files (15 missing).
If I set showFiles to 50 for example all files are showed.
