### ISSUE TITLE
Doc for Dropbox Conenction

### ISSUE THREAD

**Issue by fastesol** [Studio-42/elFinder#1294]
Hello,
First of all, I'd like to say congratulations to your team for the awesome File Manager. 
I want to know the step by step guide for dropbox setup - I didn't see there any documentation within the elFinder package. Although, I got the Dropbox sdk and place it in the server and **Mount Network Volume** always says "Host Required". and here is the json reply **{"exit":true,"body":"{msg:errNetMountNoDriver}"}**

Also, I've a suggestion for you to integrate the GitRep :)

**Comment by fastesol** [comment]
well, I was alone to fix that issue. I installed http/oauth etc but now there is another issue
**Fatal error: Class 'Dropbox_OAuth_PEAR' not found in /home/[username]/public_html/php/elFinderVolumeDropbox.class.php on line 157**

That's so annoying...

**Comment by fastesol** [comment]
at the end, I had to download the Pear.php class from https://codeload.github.com/Symfony-Plugins/idlDropboxPlugin/zip/master and added to the File Manager to make it work. 
Looks too much incomplete code in Dropbox SDK.

But Still, I'm struggling for Dropbox authentication. it's saying **{"error":"Failed getting token and token secret from response","sync":true}**

**Comment by nao-pon** [comment]
@fastesol Please try `composer require dropbox-php/dropbox-php dev-master@dev` And use newest  nightly And define "token" and "token secret" And set  in your connector.php.

e.g.
```php
// load composer autoload.php
require './vendor/autoload.php';
// define Dropbox tokens
define('ELFINDER_DROPBOX_CONSUMERKEY',    'YOUR KEY');
define('ELFINDER_DROPBOX_CONSUMERSECRET', 'YOUR SECRET');
// enable netmount
elFinder::$netDrivers['dropbox'] = 'Dropbox';
```

**Comment by nao-pon** [comment]
OR e.g. to static mount
```php
// load composer autoload.php
require './vendor/autoload.php';
$roots = array(
	'driver'            => 'Dropbox',
	'consumerKey'       => 'CONSUMER KEY',
	'consumerSecret'    => 'CONSUMER SECRET',
	'accessToken'       => 'ACCESS TOKEN',
	'accessTokenSecret' => 'ACCESS TOKEN SECRET',
);
```

**Comment by fastesol** [comment]
Thank you Naoki!

I'm able to configure everything. but a few things are not working properly. 
For example: I can see the list of directories and files under dropbox. But I can't do anything with them. e.g: can't delete/edit/open/download/copy/move etc etc.
See the attached image. this error comes when I tried to create a file.

![screenshot 2016-03-29 22 15 10](https://cloud.githubusercontent.com/assets/12485556/14117058/4f25fc5a-f5fc-11e5-9f42-ae6d128b43c8.png)

**Comment by fastesol** [comment]
I tried to connect with Google Drive. but a couple of issues.
![screenshot 2016-03-30 09 13 13](https://cloud.githubusercontent.com/assets/12485556/14131833/6f8e08c8-f658-11e5-8762-0bf73cf7fcf1.png)

It says invalid json response. and when I press close and again click on the mount button see what happened in the below image.
![screenshot 2016-03-30 09 15 19](https://cloud.githubusercontent.com/assets/12485556/14131836/73cdc07c-f658-11e5-98e3-4645c69df14c.png)

**Comment by fastesol** [comment]
**Unable to create file ....** error only comes when you choose **App folder– Access to a single folder created specifically for your app.** while creating the app in dropbox. It works fine with **Full Access**.
Anyway, the GoogleDrive issue still persists.

**Comment by nao-pon** [comment]
@fastesol Can you check server response on error of GoogleDrive?

**Comment by nao-pon** [comment]
@fastesol Please close this issue, And make a new issue of GoogleDrive problem.
