### ISSUE TITLE
How to easily implement permissions for a large number of folders under root volume?

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1295]
So here is my scenario - I have various users, with different permissions. User A is allowed to see certain folders, and User B can see other certain folders. Maybe they can both see some of the same ones, that's fine.

In my PHP elFinder connector, what is the easiest way to implement this?

As far as I can tell, access to folders can be done using by matching the folder name using the a regex pattern in the attributes?

But when I have, say, 100 folders in that root volume, must I have some huge regex pattern for the current logged in user that means they only see their folders?

Or am I going about this the wrong way?

The other option I see is to have all these sub folders as root volumes themselves, which means I can dynamically loop through a list of folders to add as a volumes array?

Any ideas?

**Comment by nao-pon** [comment]
@paulcanning What about dynamically multi volume?


```php
$groupDir = '/path/to/group_dir/';
$userDir = '/path/to/user_dir/';
```

```php
'roots'  => array(
    array(
        'driver' => 'LocalFileSystem',
        'path'   => '/path/to/public_dir/',
        'alias'  => 'Public',
    ),
    array(
        'driver' => 'LocalFileSystem',
        'path'   => $groupDir,
        'alias'  => 'Group',
    ),
    array(
        'driver' => 'LocalFileSystem',
        'path'   => $userDir,
        'alias'  => 'Private',
    ),
)
```

**Comment by paulcanning** [comment]
Yes, this was my thinking, but might look a bit "ugly".

The folders that I am limiting access to are for "jobs" and will each contain various files. Root volumes can and would work, but there is likely to be maybe 100+ folders per user.

Added to this, I will likely use Google Cloud Storage, and whilst I can target a folder in GCS as a root volume, it'd be nicer to have the one root volume, e.g. "user A jobs" then underneath, each job folder.

I'll do some test with root volumes, see what the performance is like.

**Comment by nao-pon** [comment]
Well smartest way I think it make the driver to return to the GCS any folder appropriate tree based on the login information.

**Comment by paulcanning** [comment]
How can I modify/extend the driver to do this exactly?

**Comment by nao-pon** [comment]
I think it is not as simple can be explained here. I have to tell as one of the ideas.

**Comment by paulcanning** [comment]
Seems accessControl can do it, just need to refine how I check the users allowed folders

**Comment by nao-pon** [comment]
This is one of the tips.
```php
function debug() {
	$arg = func_get_args();
	ob_start();
	foreach($arg as $v) {
		var_dump($v);
	}
	$o = ob_get_contents();
	ob_end_clean();
	file_put_contents('debug.txt', $o, FILE_APPEND);
}

function access($attr, $path, $data, $volume) {
	debug($attr, $path, $data);
	// you can check args value in ./debug.txt
	$allow = true; // or $allow = false;
	if ($allow) {
		return ($attr === 'read' || $attr === 'write'); //read,write: true, locked,hidden: false
	} else {
		return !($attr === 'read' || $attr === 'write'); //read,write: false, locked,hidden: true
	}
}

// add config 'accessControl' => 'access' to volume root option
```
