### ISSUE TITLE
Elfinder Validation With Jquery Validate

### ISSUE THREAD

**Issue by YanMagale** [Studio-42/elFinder#1296]
Hi Everyone.

How to a validate elfinder with jquery validate? I want to detect if a content elfinder not empty.

**Comment by nao-pon** [comment]
@YanMagale You can use [bind]() to `change` event.

e.g.
```javascript
var elfinderInstance = $('#elfinder').elfinder({
	url : 'php/connector.php',
}).elfinder('instance');

(function() {
	var tm;
	elfinderInstance.bind('change', function(e) {
		var file;
		if (e.data.changed && e.data.changed.length === 1) {
			file = e.data.changed[0];
			if (file.mime.indexOf('text/') === 0 && file.size == 0) {
				tm && clearTimeout(tm);
				tm = setTimeout(function() {
					alert('Content is empty');
				}, 10);
			}
		}
	});
})();
```

**Comment by YanMagale** [comment]
Hmmm ok @nao-pon ... but, its make possible validate elfinder with jquery validate (http://jqueryvalidation.org/) ?

**Comment by nao-pon** [comment]
It was a little different from my post of last time. Your issue to resolve might may want to define a new editing function in the editing options.

- https://github.com/Studio-42/elFinder/blob/775acaeaf9b1f3ca868e42547f8559090fb4dc0c/js/elFinder.options.js#L193-L244
