### ISSUE TITLE
Errors/Missing Files

### ISSUE THREAD

**Issue by fastesol** [Studio-42/elFinder#1297]
Hello, I just checkout the latest code and got lots of errors in console. Some files are missing and other jQuery errors.
Please check the screenshot
![screenshot 2016-03-29 20 10 22](https://cloud.githubusercontent.com/assets/12485556/14113059/bfcd7efe-f5ea-11e5-8b04-200b02bbb3be.png)

**Comment by fastesol** [comment]
"elfinder.html" should replace by "elfinder.src.html". elfinder.html having older code.

**Comment by nao-pon** [comment]
@fastesol Please use [stable release or nightly build](https://github.com/Studio-42/elFinder#downloads).
