### ISSUE TITLE
Duplicate sub folders being shown

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1298]
Using the Google Cloud Flysystem extension, I am getting an odd duplication for sub folders. This does not happen for a local filesystem.

- Main Bucket
- - Top Folder
- - - Sub Folder A
- - - - Another folder
- - - - Another folder < -- duplicate of above
- - - Sub Folder B
- - - - etc

**Comment by nao-pon** [comment]
@paulcanning This might be a problem of flysystem-google-storage adapter. Can you see the raw data of flysystem-google-storage adapter of the output result?

**Comment by paulcanning** [comment]
Below is a pastebin of the response form one of the folders that is showing duplicate folders inside it.

Just to highlight, the `path` variable in `options` is incorrect. This is coming from GCS, so the path is basically the URL - it doesn't have a file path as such. I think this path problem is causing other issues I have posted.

**Comment by nao-pon** [comment]
Other adapter (GoogleDrive, Dropbox) of Flysystem In There is no similar problem. I think probably there is a problem with the GoogleCloud adapter side.

**Comment by paulcanning** [comment]
It is very odd, as I have another GCS bucket with nested folders, and they are not duplicated. On another browser, it is the same. Some duplicated nested folders, others are OK

**Comment by baturman** [comment]
I am having duplicate folders shown in the tree when i select a sub-folder and refresh the editor. Please check the attached files.

Version: 2.1
I just run the downloaded scripts, no integration or something.

Reproduce:
1. Create a folder
2. Create two sub folders in that folder
3. Select a subfolder
4. Refresh page (You will see two parent folders)
![screenshot 2016-04-11 16 39 51](https://cloud.githubusercontent.com/assets/6068433/14429173/f7efab3a-0004-11e6-8545-9493502e395a.png)
![screenshot 2016-04-11 16 40 39](https://cloud.githubusercontent.com/assets/6068433/14429174/f7f69c10-0004-11e6-94a4-6920499abdd1.png)
If subfolders are not selected, no duplicates produced.

**Comment by nao-pon** [comment]
@baturman Which version of elfinder-flysystem-driver are you using? Please check with latest version.

**Comment by nao-pon** [comment]
Probably this is not a problem of elFinder.
