### ISSUE TITLE
Some root volumes are locked for no reason

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1299]
I am experimenting with various root volumes and found an issue where one of my Google Cloud Storage volumes is being locked for no reason.

I am not using any form of access control.

Connector:

public function elfinder_init()
	{
		$this->load->helper('path');
		$opts = array(
			'roots' => array(
				array(
					'driver' => 'Flysystem',
					'alias' => 'GCS thumb',
					'URL' => 'https://storage.googleapis.com/thumbnails/',
					'filesystem' => new Filesystem($this->googleCloud('adgen-dev-thumbnails')),
					'separator' => '/'
				),
				array(
					'driver' => 'Flysystem',
					'alias' => 'GCS assets',
					'URL' => 'https://storage.googleapis.com/assets/',
					'filesystem' => new Filesystem($this->googleCloud('assets')),
					'separator' => '/'
				),
				array(
					'driver' => 'Flysystem',
					'alias' => 'GCS rss',
					'URL' => 'https://storage.googleapis.com/rss/',
					'filesystem' => new Filesystem($this->googleCloud('rss')),
					'separator' => '/'
				)
			)
		);
		$this->load->library('elfinder_lib', $opts);
	}

[This is the tree view I see](http://imgur.com/pLbTj6h). Notice that one of the roots has the blue arrow? It won't let me in to that volume.

Now, if I removed some of the other volumes, e.g. the ones at the top, local folders, the "locked" GCS volume is unlocked.

Next, I just had 2 GCS root volumes, again, both without any form of access control. [Here is what I see.](http://imgur.com/USDvGT5)

You'll see two volumes, both without any form of access or permission control. Top one shows a lock, second doesn't. You can see in the info, the first volume is read only and locked, no idea why. Second is read and write, and locked. again, no idea why?!

This is in Chrome by the way. In another browser, everything is OK.

I even have "useBrowserHistory: false" in the client options.

Why are access and permissions being cached?!

**Comment by nao-pon** [comment]
@paulcanning elFinder is caching root stat. That cache key is volume ID and Path. In your case, path is same in each volume. I'll also add 'alias' as key.

Another way is to be set a config `id` of volume root.

e.g.
```php
{
	$this->load->helper('path');
	$opts = array(
		'roots' => array(
			array(
				'id' => 'gt',
				'driver' => 'Flysystem','
				'alias' => 'GCS thumb',
				'URL' => 'https://storage.googleapis.com/thumbnails/',
				'filesystem' => new Filesystem($this->googleCloud('adgen-dev-thumbnails')),
				'separator' => '/'
			),
			array(
				'id' => 'ga',
				'driver' => 'Flysystem',
				'alias' => 'GCS assets',
				'URL' => 'https://storage.googleapis.com/assets/',
				'filesystem' => new Filesystem($this->googleCloud('assets')),
				'separator' => '/'
			),
			array(
				'id' => 'gr',
				'driver' => 'Flysystem',
				'alias' => 'GCS rss',
				'URL' => 'https://storage.googleapis.com/rss/',
				'filesystem' => new Filesystem($this->googleCloud('rss')),
				'separator' => '/'
			)
		)
	);
	$this->load->library('elfinder_lib', $opts);
}
```

**Comment by paulcanning** [comment]
The path isn't the same though? Or do you mean, because I have not set the path, e.g. it is techincally `null` or `""` that it think they are the same?

I'll add the ID and see if that helps.

**Comment by nao-pon** [comment]
Default value of path is '/'. ref. https://github.com/barryvdh/elfinder-flysystem-driver/blob/master/src/Driver.php#L58-L66

**Comment by paulcanning** [comment]
Gotya. Yea, maybe make the caching key use options that _must_ be set and that are unique :)
