### ISSUE TITLE
Cannot edit text files in Google cloud storage, can edit local files

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1300]
So I found out I cannot edit text files from Google Cloud Storage using elFinder. However, I can edit local files.

I did some digging and I believe it's because the path is not being passed through to the decode method in elFinderVolumeDriver.class.php

I believe it is because for GCS, `path` does not need setting on the connector (in fact it stops it working if you use `path`).

Seeing as `path` isn't a required option, something might need changing to fix this issue.

**Comment by nao-pon** [comment]
GCS adapter use [`StreamedReadingTrait`](https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Polyfill/StreamedReadingTrait.php#L20). Please check to `tmpfile()` in your server.

**Comment by paulcanning** [comment]
Sorry I don't understand what you mean. 

I'm pretty sure it's caused by the path being wrong, but if I put the path as the bucket public URL (same as URL option) the root volume stops working. So I left path out.

**Comment by paulcanning** [comment]
I checked and using a breakpoint on StreamingReadingTrait, and it is never hit when trying to edit a text file.

**Comment by nao-pon** [comment]
Sorry I made a mistake. `readStream()` used in `copy` or `move`. `edit` uses `read()`.

There are breakpoints for debugging.

- vendor/barryvdh/elfinder-flysystem-driver/src/Driver.php `_getContents()`
- vendor/superbalist/flysystem-google-storage/src/GoogleStorageAdapter.php `read()`

**Comment by paulcanning** [comment]
OK, found the problem. Looks like an empty file e.g. a newly created text file, returns the contents as false, and therefore errors out.

I can see where this happens, it's getting set to false in vendor/superbalist/flysystem-google-storage/src/GoogleStorageAdapter.php `read()` but this is passed to vendor/league/flysystem/src/Filesystem.php `read()` where the contents are actually returned.

So where does this need fixing? If I know which package should be fixed, I can attempt a patch.

**Comment by paulcanning** [comment]
As for moving a file form GCS to local, the error is happening in the `saveCE()` method.

In elFinderVolumeDriver.class.php, line 3765, `$path` is returning false from `$this->saveCE(...)` and again, I think this may be due to GCS not needing the `path` option

**Comment by nao-pon** [comment]
Maybe `saveCE()` called by LocalFileSystem driver. I think it can not read contents from GCS. Please check content data from the GCS adapter is able to get.

About `path`, I think In elfinder-flysystem-driver, it does not problem if you do not specify `path`. The Flysystem will process properly based on the path that is a option of Flysystem abapter. On Dropbox, GoogleDrive adapter, there is no problem even if it dose not specify the `path`.

**Comment by paulcanning** [comment]
Surely this is now enough information for someone to start looking at a fix?

**Comment by nao-pon** [comment]
Probabuly this is not a problem of elFinder.
