### ISSUE TITLE
Selecting multiple files to download does not work

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1303]
Selecting two text files form Local root volume and trying to download does not work.

ZIP dialog shows, but then disappears and no ZIP is made.

I put a break point on the Zipdl method but it is not being hit.

Response from server:

`{"zipdl":{"file":"zdl863E.tmp","name":"files_Files.zip","mime":"application\/zip"}}`

After that there is a fail response to http://localhost/fileportal/index.php/ex_cont/elfinder_init with the following data:

```
cmd:zipdl
download:1
targets[]:l2_TmV3RmlsZS50eHQ
targets[]:zdl863E.tmp
targets[]:files_Files.zip
targets[]:application/zip
```

I am using the 2.1.x-dev nightly

**Comment by nao-pon** [comment]
Problem in the response of zipdl seems not. Can you download on the [demo site](http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l1_SW1hZ2Vz)? Also, please try in elFinder of stand-alone in your server.

**Comment by paulcanning** [comment]
Demo site works.

What do you mean "Also, please try in elFinder of stand-alone in your server."? I already did try, that's how I found the problem...

**Comment by nao-pon** [comment]
Do you try elFinder alone? Is connetor url "http://localhost/fileportal/index.php/ex_cont/elfinder_init"? Please show me your connector.php and elfinder.html.

**Comment by paulcanning** [comment]
Yes that's the connector URL. I'll post my exact code later, but I don't understand what you mean "do you try elFinder alone?"

**Comment by nao-pon** [comment]
Please install elFinder by next steps, and test alone without integrate with other systems.

1. [Download latest nightly](https://github.com/Studio-42/elFinder/archive/2.1.zip) and unzip to your PHP server
2. Rename /php/connector.minimal.php-dist to /php/connector.minimal.php
3. Load /elfinder.html in your browser to run elFinder
