### ISSUE TITLE
Bootstrap Style Theme for elfinder.

### ISSUE THREAD

**Issue by StudioJunkyard** [Studio-42/elFinder#1306]
Just wanted to let you all know, for those that use elfinder with Bootstrap that I've modded a theme to make elFinder look closer to Boostrap, which also uses LibreICONS SVG Icons, as I also use elFinder with Summernote WYSIWYG Editor so the theme fits in with it's icons as well.

Anyway, enjoy, make suggestions or whatever.

https://github.com/StudioJunkyard/elfinder-bootstrap-theme

**Comment by eman1986** [comment]
looks nice, am going to try it

**Comment by nao-pon** [comment]
I added link to your theme repository into https://github.com/Studio-42/elFinder#3rd-party-themes . Thanks! :+1:

**Comment by StudioJunkyard** [comment]
Awesome, I hope others find it useful as well.

**Comment by barryvdh** [comment]
That looks nice :) Also seems to fit nicely with TinyMce: http://archive.tinymce.com/tryit/basic.php

It looks a bit similar to https://github.com/lokothodida/elfinder-theme-moono 
Maybe you can combine them for less work?

I'm not a super big fan of the big black folder icons, perhaps a less solid one could be used for the bigger icons?

**Comment by StudioJunkyard** [comment]
I might have a look at doing something else for those folders, they do look ugly. I'm still playing around with the theme, so updates and suggestions are welcome.

I modded the theme to fit in with Bootstrap (obviously), and Summernote, which uses Bootstrap for styling.

I ended up making my own Font Icon (LibreICONS) to use with the CMS I've been building (LibreCMS). Summernote uses their own Font Icons, but were originally using Font Awesome, but it had a lot of Icons missing that I needed, hence making my own Font Icon, but I also include the SVG Source files, which I used for this theme. I have also included markup within the LibreICONS CSS that makes transitioning from Font Awesome, Summernote's Font Icons, Glyphicons, and even Octicons much easier.

**Comment by StudioJunkyard** [comment]
@barryvdh I've changed the Folder Icon in the file window. I've also added FontAwesome and LibreICONS versions of the theme as well.

**Comment by paulcanning** [comment]
This really shouldn't be called a Bootstrap theme, as you are using your own font.

Call it "Libre Theme".

A "proper" Bootstrap theme would be nice as well, using Glyphicon.

**Comment by StudioJunkyard** [comment]
You are aware the Bootstrap will be dropping the Glyphicons?
Beside's, plenty of people use Font Awesome with Bootstrap instead of Glyphicons.

Also, it's more to do with the look, and using the Bootstrap Classes.
