### ISSUE TITLE
Как правильно подключить плагин?

### ISSUE THREAD

**Issue by vkirpa** [Studio-42/elFinder#1307]
добавил код:
```php
'plugin' => array(
		'Normalizer' => array(
			'convmap' => array(
				"а" => "a", 
				"б" => "b", 
				"в" => "v", 
				"г" => "g", 
				"д" => "d", 
				"е" => "e", 
				"ё" => "e",  
				"ж" => "zh", 
				"з" => "z", 
				"и" => "i", 
				"й" => "j", 
				"к" => "k", 
				"л" => "l", 
				"м" => "m", 
				"н" => "n", 
				"о" => "o", 
				"п" => "p", 
				"р" => "r", 
				"с" => "s", 
				"т" => "t", 
				"у" => "u", 
				"ф" => "f", 
				"х" => "h", 
				"ц" => "ts", 
				"ч" => "ch", 
				"ш" => "sh", 
				"щ" => "shch", 
				"ы" => "y", 
				"э" => "e", 
				"ю" => "yu", 
				"я" => "ya",
				" " => "_"
			)
		)
	),
```
но он не работает. Что еще нужно прописать?

**Comment by vkirpa** [comment]
кажется нашел. 
`		'bind' => array(
 *			'upload.pre mkdir.pre mkfile.pre rename.pre archive.pre' => array(
 *				'Plugin.Normalizer.cmdPreprocess'
 *			),
 *			'upload.presave' => array(
 *				'Plugin.Normalizer.onUpLoadPreSave'
 *			)
 *		),`

**Comment by vkirpa** [comment]
How to plug a challenge to launch its function to remove special characters and translation of all simolov to lowercase.
If you use the `'lowercase' => true,` the file encoding 1251 (Cyrillic) then use `'convmap'` meaningless.

**Comment by vkirpa** [comment]
Думаю есть смысл добавить еще один параметр в плагин "specialchar" где можно было бы нормализировать имя, иначе пользоваель просто не увидит  этого файла.

**Comment by nao-pon** [comment]
@vkirpa If  special characters are `'\','/',':','*','?','"','<','>','|'`, you can use Sanitizer plugin.

And I edited plugin Normalizer @6407c4f. Does this help you?
