### ISSUE TITLE
2.1 / Nightly is broken: Uncaught TypeError: Cannot read property 'namespace' of undefined

### ISSUE THREAD

**Issue by barryvdh** [Studio-42/elFinder#1308]
The nightly builds for 2.1 are broken: http://studio-42.github.io/elFinder/
 > Uncaught TypeError: Cannot read property 'namespace' of undefined

**Comment by nao-pon** [comment]
@barryvdh I fixed @f702996 . Please check on 2.1-src Nightly: f702996. Thanks! :+1:

**Comment by barryvdh** [comment]
Great, thanks!
Btw, I've made some changes to the flysytem driver to increase performance and reduce requests.
Let me know if this breaks anything!
https://github.com/barryvdh/elfinder-flysystem-driver/compare/80df7e54e6b65e49ddc92e590679979ca280605b...master?w=1

**Comment by nao-pon** [comment]
OK, I'm checking with barryvdh/elfinder-flysystem-driver dev-master (603afb0). And i send [PR](https://github.com/barryvdh/elfinder-flysystem-driver/pull/36). Thanks!
