### ISSUE TITLE
Get file dimensions on select handler

### ISSUE THREAD

**Issue by northernlite69** [Studio-42/elFinder#1309]
I am using the (wonderful) elfinder in a popup dialog to select 1 or more files.  This works but inconsistently and strangely.

The "file" parameter returned via "getFileCallback" is an ARRAY containing file.name, file.url, file.width, file.height, etc.

However, when I use the "select" handler thus

`var file = elf.file(e.data.selected[i]);`

I only get file.name and not file.url, file.width, file.height etc.

Basically, I need to get dimensions of image files, similar to what appears in the Get Info dialog, but I would like to establish this onSelect inside the elfinder dialog before passing anything back.

Even stranger, if I push the file objects into an array inside the "select" handler the objects dont contain dimension properties until AFTER "getFileCallback" is triggered!?

I am also overriding the "dblclick" handler because I want to close elfinder via a "select" button, not automatically on double-click.

All this works, except for the inconsistencies in what is returned and via where.

**Comment by nao-pon** [comment]
@northernlite69 I think the [source of getfile](https://github.com/Studio-42/elFinder/blob/master/js/commands/getfile.js) would be helpful.

**Comment by northernlite69** [comment]
Ahhhh got it, great work, thanks!
