### ISSUE TITLE
Check for the existence of the file

### ISSUE THREAD

**Issue by vkirpa** [Studio-42/elFinder#1310]
using the plugin 'Normalizer' and replacing the characters in 'convmap', there is no check on the existence of a file with a new name and a warning to overwrite. The file with a new name simply overwrites the file with a duplicate name.

**Comment by nao-pon** [comment]
@vkirpa Thanks! I fixed it. Prease try nightly build and Add "ls.pre", "ls" to bind function.

e.g.
```php
'upload.pre mkdir.pre mkfile.pre rename.pre archive.pre ls.pre' => array(
	'Plugin.Normalizer.cmdPreprocess'
),
'ls' => array(
	'Plugin.Normalizer.cmdPostprocess'
),
```

**Comment by nao-pon** [comment]
@vkirpa Thanks! :+1:
