### ISSUE TITLE
Scrolling down and column headers in list view mode

### ISSUE THREAD

**Issue by svetlanadzhura** [Studio-42/elFinder#1311]
When you have lots of files in list view and scroll down the column headers disappear.  Is it possible to fix the column headers so that they are always visible even if you scroll down?

**Comment by troex** [comment]
I'm not sure there is easy trick to do, elfinder header in list view is `<thead>` and files are in `<tbody>` if you can fix position of `thead` probably you will get what you want. There are some hacks for this https://jsfiddle.net/dPixie/byB9d/3/

**Comment by nao-pon** [comment]
I'm WIP.

**Comment by svetlanadzhura** [comment]
Just applied these changes and got the issue: if you go to the empty folder and try to create new folder in it, the label 'Folder is empty' stays there and columns all are screwed. Could you pls take a look at this?

**Comment by nao-pon** [comment]
> if you go to the empty folder and try to create new folder in it, the label 'Folder is empty' stays there and columns all are screwed.

It was already fixed at @eb6021e9434e89faa91e69979157e2c2f70e9376 and more enhancement @66b75c443eb1db8d37156f0922a9b6341152c3d7.
