### ISSUE TITLE
How to make elfinderdialog modal?

### ISSUE THREAD

**Issue by svetlanadzhura** [Studio-42/elFinder#1312]
How to make elfinderdialog modal? If I change default setting modal to true then after closing dialog I get unresponsive elfinder

```
$.fn.elfinderdialog.defaults = {
	cssClass  : '',
	title     : '',
	modal     : true,
	resizable : true,
	autoOpen  : true,
	closeOnEscape : true,
	destroyOnClose : false,
	buttons   : {},
	btnHoverFocus : true,
	...
}
```

In case I change destroyOnClose to true too notification dialogs dont appeared at all. Thank you

**Comment by nao-pon** [comment]
@svetlanadzhura "jquery.dialogelfinder" dose not has `modal` option. Please use another dialog solution.

e.g. jQuery UI dialog
```javascript
$('<div id="elfinder"/>').elfinder({
	url : 'connector.minimal.php'
}).dialog({
	modal: true
});
```

**Comment by svetlanadzhura** [comment]
The code I posted above is a part of elfinder.js. If elfinderdialog does not have modal option, then what is 'modal' options ab out? When I change that option to 'true' all elfinder dialogs get really modal.

**Comment by nao-pon** [comment]
Sorry, I was a misunderstanding. I said about "[jquery.dialogelfinder.js](https://github.com/Studio-42/elFinder/blob/master/js/jquery.dialogelfinder.js)". Do you want to make modal dialog in all of elFinder?

**Comment by svetlanadzhura** [comment]
Yes, thats correct. I would like to have all dialogs of elfinder modal. Thank you!

**Comment by nao-pon** [comment]
@svetlanadzhura You can set `$.fn.elfinderdialog.defaults.modal = true` with @ec004778f2efd496d54cfdbd48c3c390d3608650. Thanks!

**Comment by svetlanadzhura** [comment]
Elfinderdialog now works good, no unresponsive behavior. But the same issue is with confirmation dialog. If I change option modal to true, elfinder gets hanging after closing confirmation dialog
```
confirm : function(opts) {
		var self     = this,
			complete = false,
			options = {
				cssClass  : 'elfinder-dialog-confirm',
				modal     : true,
				resizable : false,
				title     : this.i18n(opts.title || 'confirmReq'),
				buttons   : {},
				close     : function() { 
					!complete && opts.cancel.callback();
					$(this).elfinderdialog('destroy');
				}
			},
```

**Comment by svetlanadzhura** [comment]
Another place... If you rename folder in the tree with name which already exists you get error dialog 'File name "xxx" already exists', after closing that dialog elfinder gets unresponsive again. If I change modal to false in error call (see code fragment below) then no hanging.

						
```
if (fm.fileByName(name, file.phash)) {
							inError = true;
							fm.error([file.mime != 'directory' ? 'errExists' : 'errDirExists', name], {modal: true, close: select});
							return false;
					
```	}
```

**Comment by nao-pon** [comment]
I edited again. Please check with latest nightly.
