### ISSUE TITLE
не работают оба плагина Normalizer и AutoResize. 

### ISSUE THREAD

**Issue by vkirpa** [Studio-42/elFinder#1313]
```php
		'bind' => array(
			'upload.pre mkdir.pre mkfile.pre rename.pre archive.pre ls.pre' => array(
				'Plugin.Normalizer.cmdPreprocess'
			),
			'ls' => array('Plugin.Normalizer.cmdPostprocess'),
			'upload.presave' => array('Plugin.Normalizer.onUpLoadPreSave',  	'Plugin.AutoResize.onUpLoadPreSave')
		),
	'plugin' => array(
		'Normalizer' => array(
				'enable'    => true,  // For control by volume driver
				'nfc'       => false,  // Canonical Decomposition followed by Canonical Composition
				'nfkc'      => false  // Compatibility Decomposition followed by Canonical
				'lowercase' => false, // Make chars lowercase	
				'convmap' => array(
					"А" => "A", "Б" => "B", "В" => "V", "Г" => "G", "Ґ" => "G", "Д" => "D", "Е" => "E", "Є" => "E", "Ё" => "E",  "Ж" => "Zh", "З" => "Z", "І" => "I", 
					"И" => "I", "Й" => "I", "К" => "K", "Л" => "L", "М" => "M", "Н" => "N", "О" => "O", "П" => "P", "Р" => "R", "С" => "S", "Т" => "T", "У" => "U", 
					"ф" => "F", "Х" => "Kh", "Ц" => "Ts", "Ч" => "Ch", "Ш" => "Sh", "Щ" => "Sch", "Ы" => "Y", "Э" => "E", "Ю" => "Yu", "Я" => "Ya", "Ї" => "Yi", 
					"а" => "a", "б" => "b", "в" => "v", "г" => "g", "ґ" => "g", "д" => "d", "е" => "e", "є" => "e", "ё" => "e",  "ж" => "zh", "з" => "z", "и" => "i", 
					"і" => "i", "й" => "i", "к" => "k", "л" => "l", "м" => "m", "н" => "n", "о" => "o", "п" => "p", "р" => "r", "с" => "s", "т" => "t", "у" => "u", 
					"ф" => "f", "х" => "h", "ц" => "ts", "ч" => "ch", "ш" => "sh", "щ" => "sch", "ы" => "y", "э" => "e", "ю" => "yu", "я" => "ya", "ї" => "yi", 
					"ь" => "", "ъ" => "", "Ь" => "", "Ъ" => "", "’" => ""  
				)
			)
	),
```

**Comment by vkirpa** [comment]
after the upgrade to version elFinder 2.1.x (Nightly) are not running both plugins Normalizer and AutoResize.

**Comment by vkirpa** [comment]
where to find the mime template for adding .word, .excel, .word, .excel, (MS Office)

**Comment by nao-pon** [comment]
@vkirpa Please try `'upload.presave' => array('Plugin.AutoResize.onUpLoadPreSave', 'Plugin.Normalizer.onUpLoadPreSave')` (AutoResize to first).

> where to find the mime template for adding .word, .excel, .word, .excel, (MS Office)

What mean is it? Don't the elFinder detect MIME-Type of MS Office files?

**Comment by vkirpa** [comment]
1) after resetting, nothing has changed, 'convmap'. It does not replace symbols. AutoRe not work.    
2) when downloading files (MS Office) says "invalid file type".
I ordered 
`								'uploadAllow' => array('image', 'video', 'audio', 'vnd', 'video/x-flv', 'application/flash-video flv', 'text/rtf', 'text/plain', 'application/pdf', 'application/x-shockwave-flash', 'application/vnd.ms-powerpoint', 'application/msword', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'),   
                                'uploadDeny' => array('all'),
                                'uploadOrder' => 'deny,allow',
                                'mimeDetect'   => 'internal', // (auto, internal, finfo, mime_content_type)
`

**Comment by vkirpa** [comment]
Can not I downloaded the installer package?
Provide a link to the latest version. elFinder 2.1.x (Nightly).

**Comment by vkirpa** [comment]
downloaded elFinder 2.1.x (Nightly) -51961fb

**Comment by vkirpa** [comment]
с ошибкой разобрался. В новой версии нужны одинарные кавычки ` 'convmap' => array(
                    "А" => "A") `
