### ISSUE TITLE
Merge folders, not just replace

### ISSUE THREAD

**Issue by svetlanadzhura** [Studio-42/elFinder#1315]
If you have folder named "A" at root level. Then a folder named "B" at root level.  Within "A" and "B" you have a subfolder named "C".  If you drag the "C" folder in "B" to the "A" folder it says, "File named "C" already exists.  Replace old file with new one?"  Is it possible to merge folders, not replace them?

**Comment by nao-pon** [comment]
elFinder is not support merge folder on paste. It is difficult.

**Comment by svetlanadzhura** [comment]
Ok, in that case there is an error: after replacing one folder by another one the tree still keeps the structure of the old folder (not updating accordingly to changes)

**Comment by nao-pon** [comment]
Which volume driver are you testing? I was checked LocalFileSystem & FTP. It seems no problem.

**Comment by svetlanadzhura** [comment]
I reproduce that issue on local

**Comment by nao-pon** [comment]
Please try 2.1 nightly build. Then please make new issue If you have this problem yet.

**Comment by nao-pon** [comment]
Let's get back on track. I found volume root option
```php
// if true - join new and old directories content on paste
'copyJoin'        => true,
```
but it feature does not seem to be implemented, I began to implement.
