### ISSUE TITLE
Setting  setLocale and lang correctly reflect the content.

### ISSUE THREAD

**Issue by vkirpa** [Studio-42/elFinder#1316]
Setting '' setLocale '=>' ru_RU.utf 8 '' and lang: 'ru' correctly reflect the content.

**Comment by vkirpa** [comment]
when you select multiple files and call menu. The name is displayed in English instead of the installed languages

**Comment by vkirpa** [comment]
I found the reason. file   `js/i18n/elfinder.ru.js`  must be recoded in ANSI.

**Comment by vkirpa** [comment]
when you select multiple files and call menu. The name is displayed in English instead of the installed languages (Selected Items)

**Comment by vkirpa** [comment]
`			'getLink'         : 'Отримати URL посилання', 
			'selectedItems'   : 'Вибрано елементів ($1)', 			
`
you need to add two lines to the file elfinder.uk.js and also elfinder.ru.js

**Comment by nao-pon** [comment]
@vkirpa Please use [translation tool](http://studio-42.github.io/elFinder/tools/langman/#2.1:uk) and send pull request.
