### ISSUE TITLE
text file can't save context when it's end with /n

### ISSUE THREAD

**Issue by jerry0908mo** [Studio-42/elFinder#1321]
1. when one text file is end with \n or [blank]  things. ( tap ENTER or  SPACE BAR  or TAB keys)
2. save it.
3.  reopen it, the [blank]  things were not been saved.

```
BTW 
upload a text file end with 'blank', and open it , that can work well. but when i save it  on elFinder. 
the 'blank' context was lost.
```

**Comment by nao-pon** [comment]
@jerry0908mo Thanks! :+1:

**Comment by jerry0908mo** [comment]
my pleasure
