### ISSUE TITLE
Fix `jake release` version

### ISSUE THREAD

**Issue by troex** [Studio-42/elFinder#1322]
Old method using `git describe --tags` is not reliable anymore as tags are used for compiled code.

**Comment by nao-pon** [comment]
@troex Hi! :smile:  Are you need tags for source version (e.g. 2.1.11-src)?

**Comment by troex** [comment]
yes, I was thinking about it... when you release new version you tag it as `2.1.x` on `2.1` branch, I think it would be good if you also create tag `2.1.x-src` on the `2.1-src` branch.
