### ISSUE TITLE
Script don't unpacking archives with .* files

### ISSUE THREAD

**Issue by serofir** [Studio-42/elFinder#1323]
For security reason denied to unpack archives contains symlinks or files with not allowed names.
(.tx, .gitignore, etc)
I can't extract my archive, how can I disable this "security reason"?
Elfinder 2.1

**Comment by nao-pon** [comment]
@serofir It controlled by connector root configuration `accessControl`. Please check your configuration.

**Comment by serofir** [comment]
Okay.
This is my configuration.

			'uploadDeny'    => array('none'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('all'), // Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)

How to disable?

**Comment by nao-pon** [comment]
remove `accessControl`.

```php
        'uploadDeny'    => array('none'),                // All Mimetypes not allowed to upload
        'uploadAllow'   => array('all'), // Mimetype `image` and `text/plain` allowed to upload
        'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
```

**Comment by serofir** [comment]
Okay, I removed this line. I was try again, and what I got : 

Unable to extract files from "web/mydomain.com/public_html/test/master.zip".
Unable to save ".gitignore".
For security reason denied to unpack archives contains symlinks or files with not allowed names.

**Comment by nao-pon** [comment]
Sorry, I made a mistake.

use an option `acceptedName`.

e.g.
```php
'acceptedName'  => '/^[^\/\\?*:|"<>]*[^.\/\\?*:|"<>]$/',
```
.

**Comment by serofir** [comment]
Ok, now it works.
Thank you very much for your help.

**Comment by VikasWebuzo** [comment]
> 

Will this also allow symlinks to extract ? 
As one of the zip file has symlinks and when i tried to extract it it given me same error of security reason.
