### ISSUE TITLE
Upload progress in % not possible

### ISSUE THREAD

**Issue by dup2** [Studio-42/elFinder#1324]
Trying to use the information at #364, we could not get an upload progress to work.

We try to implement a visual progress bar in % for a single file upload, the default shows a progressbar which is just animated but reveals no state of the operation. 

It seems the notify function does not really work with upload progress information.

**Comment by nao-pon** [comment]
@dup2 Simple example for single file upload. (I have not tried.)

```javascript
var req = new XMLHttpRequest();

var finish = function() {
	elfInstance.notify({type : 'upload', cnt : -1});
};

req.addEventListener('progress', function(e) {
	elfInstance.notify({type : 'upload', cnt : 0, progress: e.loaded / e.total});
}, false);

req.addEventListener('load', finish, false);
req.addEventListener('error', finish, false);
req.addEventListener('abort', finish, false);

req.open();
elfInstance.notify({type : 'upload', cnt : 1, progress: 0});
```

**Comment by dup2** [comment]
Thanks, I'll try this asap. Is there any chance to hook this into the existing upload info dialog?

**Comment by dup2** [comment]
This works. Thanks again for your support :+1:
