### ISSUE TITLE
How to prevent switching of mkdir mode?

### ISSUE THREAD

**Issue by svetlanadzhura** [Studio-42/elFinder#1325]
How to prevent switching of mkdir mode? Is it possible to keep the same functionality for toolbar button 'New folder' regardless if folder/file is selected? That is never to switch to 'In new folder' mode, thank you!

**Comment by nao-pon** [comment]
@svetlanadzhura OK, It's the function of the tool button switches is likely to be confused. So that it can be enabled in the command options.

`commandsOptions.mkdir.intoNewFolderToolbtn` (true / false default is false)

**Comment by svetlanadzhura** [comment]
Thank you! Just applied changes and all work perfectly fine!
