### ISSUE TITLE
Connector cmd=archive GET request

### ISSUE THREAD

**Issue by ma2tkraus** [Studio-42/elFinder#1326]
I am trying to implement the connector command for archive.  For most commands the elFinder client will generate a GET request with a parameter cmd=X, where X is the command.  For elFinder 2.1.7, I cannot get it to produce cmd=archive.

The client appears to operating fine.  I can select a couple of files and then the command ZIP Archive and expect to see a GET request. 

Suggestions appreciated.

https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#archive

**Comment by nao-pon** [comment]
@ma2tkraus Please include options.archivers in JSON results.

e.g.
```json
{
    "api": "2.1", 
    "cwd": {}, 
    "files": [], 
    "netDrivers": [], 
    "options": {
        "archivers": {
            "create": [
                "application/x-tar", 
                "application/x-gzip", 
                "application/zip"
            ], 
            "createext": {
                "application/x-gzip": "tgz", 
                "application/x-tar": "tar", 
                "application/zip": "zip"
            }, 
            "extract": [
                "application/x-tar", 
                "application/x-gzip", 
                "application/zip"
            ]
        }, 
        "copyOverwrite": 1, 
        "disabled": [], 
        "dispInlineRegex": "^(?:image|text/plain$)", 
        "jpgQuality": 100, 
        "path": "Test here", 
        "separator": "/", 
        "syncChkAsTs": 1, 
        "syncMinMs": 30000, 
        "tmbUrl": "", 
        "uiCmdMap": [], 
        "uploadMaxSize": 1073741824, 
        "uploadOverwrite": 1, 
        "url": ""
    }, 
    "uplMaxFile": "20", 
    "uplMaxSize": "20M"
}
```

**Comment by ma2tkraus** [comment]
Good feedback.  I am doing this now for the open command but does this also need to be included in other commands?  

When two files are selected, the popup menu says "Selected items (2) at the top and second from the bottom is "Create archive > ZIP archive".  This part works.

![screen shot 2016-04-14 at 9 23 33 pm](https://cloud.githubusercontent.com/assets/16022959/14560158/c673102c-02db-11e6-8d15-4da5f5bc1e77.png)

**Comment by nao-pon** [comment]
I fixed Wiki [Archive](https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#archive) / [Extract](https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#extract) section. But another sections WIP..

**Comment by ma2tkraus** [comment]
Docs are improved but **Archive** also needs *name* and *type*

> http://hypweb.net/elFinder-nightly/demo/2.1/php/connector.minimal.php?
> cmd=archive
> &name=Archive.zip
> &target=l2_TmV3Rm9sZGVyL3Rlc3Q
> &targets%5B%5D=l2_TmV3Rm9sZGVyL3Rlc3QvZW1wdHkgZm9sZGVy
> &targets%5B%5D=l2_TmV3Rm9sZGVyL3Rlc3QvY29sb3Vyc29mZmFsbC5qcGc
> &targets%5B%5D=l2_TmV3Rm9sZGVyL3Rlc3Qv0YLQtdGB0YIuanBn
> &type=application%2Fzip
> &_=1460671443521

**Comment by nao-pon** [comment]
OK. I edited again.
