### ISSUE TITLE
 How to synchronize upload file to another folder ?

### ISSUE THREAD

**Issue by linlong3388** [Studio-42/elFinder#1331]
I have two folder "resources/bigSize" and "resources/smallSize". I want to upload "resources/bigSize"
after auto synchronize upload to "resources/smallSize". So i setting two roots , but it seems not my
want? :(

```php
$opts = array(
  'bind' => array(
		//'duplicate upload rm paste' => 'elfinder_upload_rename' ,
	  	  'upload.presave' => array(
						'Plugin.AutoResize.onUpLoadPreSave'
					)
	  	   ),
	
  'roots' => array(
		      array(
				'driver'  => 'LocalFileSystem',
				'path'    => set_realpath('./resources/bigSize/'),
				'URL'     => site_url('resources/bigSize/'),
				'accessControl' => 'elfinder_access',
				'uploadAllow' => array('image'),
				'attributes'  => array(
					array(
						'pattern' => '/.*/',
						'read'  => true,
						'write' => true
						)
				),
			),

			array(
			   'driver' => 'LocalFileSystem',
			   'path'   => set_realpath('./resources/smallSize/'),
		  	   'URL'    => site_url('resources/smallSize/'),
		       'plugin' => array(
				  'AutoResize' => array(
					 'enable'         => true,    
					 'maxWidth'       => 300,    
					 'maxHeight'      => 300,   
					 'quality'        => 70,      
					 'preserveExif'   => false,
					 'targetType'     => IMG_GIF|IMG_JPG|IMG_PNG|IMG_WBMP
					)
				)
			)
		)
	
	
		);
		
		$this->load->library('elfinder_cls', $opts);
```

**Comment by nao-pon** [comment]
@linlong3388 What about it? But it require newest nightly build.

```php
$opts = array(
  'bind' => array('upload' => array('smallImage'))
);

function smallImage($cmd, $result, $args, $elfinder, $volume) {
	// make image maxsize
	$maxWidth = 300;
	$maxHeight = 300;
	$jpgQuality = 70;
	$smallsDir = set_realpath('./resources/smallSize/');
	if ($volume && $result && isset($result['added'])) {
		foreach($result['added'] as $item) {
			if ($file = $volume->file($item['hash'])) {
				$path = $volume->getPath($item['hash']);
				if (strpos($file['mime'], 'image/') === 0 && ($srcImgInfo = @getimagesize($path))) {
					$zoom = min(($maxWidth/$srcImgInfo[0]),($maxHeight/$srcImgInfo[1]));
					$width = round($srcImgInfo[0] * $zoom);
					$height = round($srcImgInfo[1] * $zoom);
					$tfp = tmpfile();
					$info = stream_get_meta_data($tfp);
					$temp = $info['uri'];
					if ($src = fopen($path, 'rb')) {
						stream_copy_to_stream($src, $tfp);
						fclose($src);
						if ($volume->imageUtil('resize', $temp, compact('width', 'height', 'jpgQuality'))) {
							@copy($temp, $smallsDir . '/' . $file['name']);
						}
					}
				}
			}
		}
	}
}
```

**Comment by uktamovdilshod** [comment]
You may use this plugin https://github.com/uktamovdilshod/Thumbnails

**Comment by onionstand** [comment]
I get PHP Error:
Fatal error: Call to undefined function set_realpath() in ...elfinder\php\connector.minimal.php

**Comment by vahidalvandi** [comment]
> @linlong3388 What about it? But it require newest nightly build.
> 
> ```
> $opts = array(
>   'bind' => array('upload' => array('smallImage'))
> );
> 
> function smallImage($cmd, $result, $args, $elfinder, $volume) {
>     // make image maxsize
>     $maxWidth = 300;
>     $maxHeight = 300;
>     $jpgQuality = 70;
>     $smallsDir = set_realpath('./resources/smallSize/');
>     if ($volume && $result && isset($result['added'])) {
>         foreach($result['added'] as $item) {
>             if ($file = $volume->file($item['hash'])) {
>                 $path = $volume->getPath($item['hash']);
>                 if (strpos($file['mime'], 'image/') === 0 && ($srcImgInfo = @getimagesize($path))) {
>                     $zoom = min(($maxWidth/$srcImgInfo[0]),($maxHeight/$srcImgInfo[1]));
>                     $width = round($srcImgInfo[0] * $zoom);
>                     $height = round($srcImgInfo[1] * $zoom);
>                     $tfp = tmpfile();
>                     $info = stream_get_meta_data($tfp);
>                     $temp = $info['uri'];
>                     if ($src = fopen($path, 'rb')) {
>                         stream_copy_to_stream($src, $tfp);
>                         fclose($src);
>                         if ($volume->imageUtil('resize', $temp, compact('width', 'height', 'jpgQuality'))) {
>                             @copy($temp, $smallsDir . '/' . $file['name']);
>                         }
>                     }
>                 }
>             }
>         }
>     }
> }
> ```

how i can use this ?
