### ISSUE TITLE
Bug [dialogelfinder]: endless ajax-requests with "cmd=parents"

### ISSUE THREAD

**Issue by side-by-side** [Studio-42/elFinder#1334]
Hello. There is a bug a had faced.
elFinder 2.1.11.
My related config:
```javascipt
commandsOptions: {
    getfile: {
        oncomplete: 'destroy'
    }
}
```
Using dialog (```$.fn.dialogelfinder```) to select a file, there are two requests on opening:
1. First ```?cmd=open&target=&init=1&tree=1&_=1461087915921``` to show files in the directory.
2. Second ```?cmd=parents&target=l1_Y3Nz&_=1461087915922``` to show parents in a tree.

If we selecting a file slowly, everything is fine.
But if we selecting file fast — here we go. If a dialog is destroyed **until** the second request is finished, there are keep going endless ```?cmd=parents``` requests:

![sc-001](https://cloud.githubusercontent.com/assets/7204866/14649840/7fa69ff8-0671-11e6-84fd-6bbc7e0ada40.jpg)

Tens, thousands, until page reload.
It is so when using ```sync``` option. After instance is destroyed, ```info``` requests keeps going.

**Comment by nao-pon** [comment]
@side-by-side Thanks! :+1:

**Comment by side-by-side** [comment]
Thank you for speed!

**Comment by zc888168** [comment]
I have  come across the same problem,try many methods and then annotate like this:
//cwdhash == cwd.hash && fm.visible() && sync(noCwd); it's ok now

**Comment by zc888168** [comment]
it is like endless loop when i am executing paste command

**Comment by nao-pon** [comment]
I'll correct to a more strict check in `fm.visible()`.

**Comment by nao-pon** [comment]
@zc888168 Thanks! Please try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).
