### ISSUE TITLE
Checking mime with dblclick event

### ISSUE THREAD

**Issue by bitbybit** [Studio-42/elFinder#1336]
I changed default action for `dblclick` event to open editor instead of showing file, but because of that I can not open directories. `event` variable only contains filename. Is there any way to know what I clicked, file or directory? Or maybe there is another simpler solution to change default behaviour from open to edit files?
```
          dblclick: function(event,elfinderInstance) {
            if(mycustomcondition && event.data.file) {
              elfinderInstance.exec('edit',event.data.file);
              return false;
            }
          },
```

**Comment by nao-pon** [comment]
@bitbybit You can use client configuration option [getFileCallback](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#getFileCallback "getFileCallback").

```javascript
getFileCallback : function(file, fm) {
    fm.exec((file.write && file.mime.indexOf('text') === 0)? 'edit' : 'open', file.hash);
},
```

**Comment by bitbybit** [comment]
Thank you
