### ISSUE TITLE
'Copy' command is enabled for locked folders/files

### ISSUE THREAD

**Issue by svetlanadzhura** [Studio-42/elFinder#1337]
'Copy' command is still enabled for locked folders/files (that is for folders and files with permission='read' only). Is that bug or work as designed(wad)? If that behavior is wad then is there any option to disable Copy for locked items? Thank you

**Comment by nao-pon** [comment]
@svetlanadzhura  The readable items are possible to copy. You need to be unreadable to copy not allow.

Or, please add a `copy` to the [`disabled`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#disabled) option of connector root config.

**Comment by svetlanadzhura** [comment]
Setting files to unreadable solves the problem for files. But setting folders to unreadable makes folders unable to open. Is there any other option to disable Copy command for locked folders? Thank you!

**Comment by troex** [comment]
@svetlanadzhura what you ask it not really compatible with each other. If you are able to 'read' than you able to 'copy' it's not finder limitation but file system.

'locked' files & folders are something elfinder specific so maybe easier way do prevent copy files if they are locked:

https://github.com/Studio-42/elFinder/blob/a210790a2d47a3509ebbe2f768b959e6b4a733fe/js/commands/copy.js#L19

```... { return f.phash && f.read ? f : null  } ...```

if you change it to something like:

```... { return f.phash && f.read && !f.locked ? f : null  } ...```

It should do the trick and you will not be able to copy locked files.

@nao-pon correct me if I'm wrong?

**Comment by nao-pon** [comment]
@troex You are right. I think so.

@svetlanadzhura `locked` mean is the contents of unwritable directory. That are readable and copyable.

Still, do you want to ban the Copy on the client? Well you can respond by changing the function as in the proposal of troex. But it is possible to copy by issuing the command directly because of the connector-side functionality is not disabled.

```javascript
var elfinderInstance = $('#elfinder').elfinder({ opts }).elfinder('instance');
elfinderInstance._commands['copy'].getstate = function(sel) {
    var sel = this.files(sel),
        cnt = sel.length;
    return !this._disabled && cnt && $.map(sel, function(f) { return f.phash && f.read  && !f.locked ? f : null  }).length == cnt ? 0 : -1;
};
```

**Comment by nao-pon** [comment]
I will close this issue. Because this is not a problem of elFinder.
