### ISSUE TITLE
Disabled toolbar for treeview

### ISSUE THREAD

**Issue by svetlanadzhura** [Studio-42/elFinder#1338]
When you click a folder in the treeview the toolbar icons are not enabled.  But you can right click and delete a folder etc.  Can the toolbar be enabled with the following options enabled: Cut, Copy, Paste, Delete, Rename?

**Comment by nao-pon** [comment]
@svetlanadzhura This was fixed @300f0946862a8121c839184f21c4afa43bd192b8. Please wait 2.1.12. or You can try nightly build.
