### ISSUE TITLE
"beforeunload" event interferes file selection (while integrating with some editor, etc.)

### ISSUE THREAD

**Issue by side-by-side** [Studio-42/elFinder#1340]
Hello. I don't now, maybe it's not a bug, but it's very annoying.

When we need to select some file and elFinder is opened in a separate browser window (like in integration with editors, for example with CKEditor (https://github.com/Studio-42/elFinder/wiki/Integration-with-CKEditor)), after file had been selected and ```getFileCallback``` is executed, this opened window is about to close (``` window.close();```). But immediately after file selection, elFinder popup "Acquiring image dimension" is shown and browser asks: "Are you sure you want to leave this page"? After several clicks on "yes" it is finally closed.

![sc-001](https://cloud.githubusercontent.com/assets/7204866/14717711/4f1f8274-07fb-11e6-9346-362d1d61e07b.jpg)

It seems that ```getFileCallback``` is executed immediately after file selection and before image dimensions are acquiried. Because ``` window.close();``` is in ```getFileCallback```.
Maybe we should change the order of these tasks? To:
1. First: acquiring image dimension and any other operations.
2. Second: call ```getFileCallback```.

En event set here: https://github.com/Studio-42/elFinder/blob/master/js/elFinder.js#L2411 .
Like temp workaround I'm removing event by this:
```javascript
$(window).off('beforeunload');
```

P.S. Is there any guide how to integrate elFinder with CKEdtor using native ```dialogelfinder``` and not a separate browser window?

**Comment by nao-pon** [comment]
@side-by-side  What about it?
```javascript
    $().ready(function() {
        var funcNum = getUrlParam('CKEditorFuncNum');

        var elf = $('#elfinder').elfinder({
            url : 'php/connector.php',
            getFileCallback : function(file) {
                window.opener.CKEDITOR.tools.callFunction(funcNum, file.url);
                elf.destroy();
                window.close();
            },
            resizable: false
        }).elfinder('instance');
    });
```

**Comment by nao-pon** [comment]
And You will can disable action that getting image size in next version with an option `commandsOptions.getfile.getImgSize`.

```javascript
$().ready(function() {
    var funcNum = getUrlParam('CKEditorFuncNum');

    var elf = $('#elfinder').elfinder({
        url : 'php/connector.php',
        commandsOptions: {
            getfile: { 
                getImgSize: false
            }
        },
        getFileCallback : function(file) {
            window.opener.CKEDITOR.tools.callFunction(funcNum, file.url);
            elf.destroy();
            window.close();
        },
        resizable: false
    }).elfinder('instance');
});
```

**Comment by nao-pon** [comment]
I changed default value of `commandsOptions.getfile.getImgSize` to `false` at be03221f4c317976fd7a539435a9eef7d3ff90f3.

**Comment by side-by-side** [comment]
@nao-pon, wow, these changes fully covers my and other's needs, thank you again!
