### ISSUE TITLE
tinyMCE integration with <img src="data:..."

### ISSUE THREAD

**Issue by RolfBensch** [Studio-42/elFinder#1343]
i've got a nice working tinyMCE-4-integration with file_picker_callback. I cannot ensure that img-files are dateless present. Is there a way to push files as data-objects as src of img-tags?

**Comment by nao-pon** [comment]
@RolfBensch It is one of examples.

```javascript
      getFileCallback: function(file) { // editor callback
        // Require `commandsOptions.getfile.onlyURL = false` (default)
        if (file.mime.indexOf('image/') === 0) {
          $('<img/>').attr('src', file.url)
          .on('load', function() {
            var canvas = document.createElement('canvas');
            canvas.width = this.width;
            canvas.height = this.height;
            canvas.getContext('2d').drawImage(this, 0, 0);
            file.url = canvas.toDataURL(file.mime);
            FileBrowserDialogue.mySubmit(file, elfinderInstance);
          })
          .on('error', function() {
            FileBrowserDialogue.mySubmit(file, elfinderInstance);
          });
        } else {
          FileBrowserDialogue.mySubmit(file, elfinderInstance);
        }
      }
```

**Comment by RolfBensch** [comment]
Wow, great answer! It works smart - with a little issue. getFileCallback allways returns a proper file.url (shown in tinyMCE-Dialog). Inserting an image, tinymce results in an src="blob:https...". Replacing this image with the same source results in src="data:image...". Cause getFileCallback allways returns data:image..., i think this is a tinymce-issue and i have to look for the reason.

thanks a lot! (as well for elfinder - great work)

**Comment by nao-pon** [comment]
You are welcome!
