### ISSUE TITLE
Fallback for system without GD-Image

### ISSUE THREAD

**Issue by StudioJunkyard** [Studio-42/elFinder#1344]
Is there a work around, or anything planned for servers that can't, or don't have GD-Image installed. I was thinking something along the lines, that if GD isn't installed, that instead of showing no image for the thumbnail at all, that at least the full image is shown. Slow I know, but it would be better than no image. Maybe elFInder could throw a warning, or display in the help dialog that certain dependencies aren't installed.

**Comment by nao-pon** [comment]
@StudioJunkyard Thanks! :+1: 

- Add a volume root option `tmbFbSelf` default is `true`
  - Fallback self image to thumbnail (nothing imgLib)
- New setting value "self" of volume root option `tmbURL`
  - If you want chose original image as thumbnail it is able to set 'self'
- Show information of `options` `debug` server response into "debug" tab
  on "help" dialog when the connector configuration has `debug` to `true`
![elfinder-help-debug](https://cloud.githubusercontent.com/assets/1412630/14876085/544843ca-0d4c-11e6-9a9d-87faeb3910ea.png)

**Comment by StudioJunkyard** [comment]
Awesome, thank you. I'm sure other will like this too. Great work.
