### ISSUE TITLE
ownCloud Driver

### ISSUE THREAD

**Issue by adrianopedro** [Studio-42/elFinder#1347]
Hello all,

I've bee using elfinder  for a long time connected to a localstorage on the system.
Is there or has anybody tried to connect the elfinder to a owncloud system?
ownCloud has an API similar to dropbox, so I think it wouldn't be that complicated and also has webDav.

Thank you,
AP

**Comment by troex** [comment]
Currently elFinder has integration with https://github.com/thephpleague/flysystem this is best option so far. You can try to search ownCloud implementation for flysystem or write own.

**Comment by mathiastm** [comment]
Hi @dbugit , did you find a solution? i'm trying to connect elFinder with nextcloud...

**Comment by nao-pon** [comment]
c.f #2082

**Comment by dbugit** [comment]
Hi,

I have the solution implemented for this along time ago and using [flysystem](https://github.com/thephpleague/flysystem).
It integrates elfinder with any system using webdav (in this case was with owncloud).

```
use Sabre\DAV\Client;
use League\Flysystem\Filesystem;
use League\Flysystem\WebDAV\WebDAVAdapter;
use Sabre\CalDAV\Plugin;

require './vendor/autoload.php';

$settings = array(
			'baseUri' 	=> $GLOBALS['config']['ocurl'], 
			'userName' 	=> $clientdata->user,
			'password' 	=> $clientdata->ocpass,
			'authType'	=> Client::AUTH_BASIC
		);
	$client 		        = new Client($settings);
	$webdavAdapter 	= new WebDAVAdapter($client,"/remote.php/webdav/");
	$webdavfs		= new Filesystem($webdavAdapter);


'roots' => array(
		array(
				'driver' 		=> 'Flysystem',
				'filesystem' 	=> $webdavfs,
			        'mimeDetect' 	=> 'internal',
			        'imgLib'     	=> 'gd',
			        'tmbPath'    	=> '../../userfiles/thumbnails',
			        'tmbURL'    	=> '../../userfiles/thumbnails',
			        'tmbCrop'    	=> false,
			     // 'URL'		=> $settings['baseUri']."/remote.php/webdav/",						
				'accessControl' => 'access',// disable and hide dot starting files (OPTIONAL)
				'alias'			=> 'ownCloud',						
				'debug'			=> false,	
				'cache'			=> false,
			),
		)
```

Hope I've helped.

Regards,
AP
