### ISSUE TITLE
bower.json must only include front-end part

### ISSUE THREAD

**Issue by troex** [Studio-42/elFinder#1354]
Bower is usually used for installing front-end libraries and dependencies, I think we should add ignore for php files in bower.json

@nao-pon do you have any suggestions about it?

**Comment by nao-pon** [comment]
@troex I do not know a lot about bower...

‐ Is it better to include `main` and `ignore` sections?
- require `version` in 2.1 and 2.0 branch's bower.json?

**Comment by troex** [comment]
I'll check myself on it. I used bower in angular projects with node and rails backends, so bower is mostly used for front-end components, node server packages usually installed with npm, and front-end with bower, so I think we should remove php from bower.

About `version` I'm not totally sure, bower should be able to use git tags as version, but I'll check it. Maybe we will generate it on `jake build`.

Also I think bower.json is only needed in `2.0` and `2.1` branches, we don't need bower.json (and composer.json) in any other, for development users must use `git clone`.

Bower and Composer are distribution systems we should only deliver ready built versions with it and not src, nobody wants to download src version of jquery to use it on the site.

**Comment by nao-pon** [comment]
> Also I think bower.json is only needed in 2.0 and 2.1 branches, we don't need bower.json (and composer.json) in any other, for development users must use git clone.

Think so. @troex I'll leave it up to you. Thanks!

**Comment by lianee** [comment]
since the javascript and php part are tied in functions, removing the php part in bower will make it useless.

**Comment by troex** [comment]
@lianee I'm not agree because there are different connectors as well, people who do not use PHP do not need it, and bower used with different languages as well like ruby/node/python. If you use PHP I consider you should use composer elfinder package instead, it will come with both PHP and JS parts

**Comment by lianee** [comment]
Well, I now use composer (just in case), but I'm pretty sure many people using bower actually rely upon the PHP code provided, and their install will break if you take out the PHP code from the next update.

**Comment by troex** [comment]
@lianee thanks for your feedback, I'll make more research on it, but I believe distributing php with bower is considered a bad practise, and possibly can be security issue because usually `bower_components` folder is open to the web.

**Comment by nao-pon** [comment]
I plan to accept the pull request of #1711. Please tell me the opinions of everyone.

**Comment by nao-pon** [comment]
Merged #1711. so close.
