### ISSUE TITLE
Invalid backend response. Data is not JSON.Spring boot app

### ISSUE THREAD

**Issue by BSalah** [Studio-42/elFinder#1355]

**Comment by nikosites** [comment]
Hi
After I load the main file (elfinder.html) from elFinder's root folder I got error modalbox: 
"Invalid backend response.
Data is not JSON."
(I mean elFinder 2.1.11)

**Comment by troex** [comment]
@BSalah, @nikosites check connector.php output in Inspector/Firebug

**Comment by nikosites** [comment]
No needed to inspect it in Inspector/Firebug, I just renamed two files: "connector-minimal.php-dist" and "connector.php-dist" just removing "-DIST" at the end of both files (dont know why they had -dist?) and it worked.
I spent so much time inspecting and looking for the problem and did not pay attention to this extra extension =D

**Comment by troex** [comment]
Sorry, I thought it's obvious, added a note to wiki Install
