### ISSUE TITLE
Please update the 2.1 documention

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1356]
Is severely lacks a lot of information such as how to change the columns visible in the list view.

I love this plugin, but the crappiness of the documentation is really off-putting.

**Comment by nao-pon** [comment]
We are aware. However, the resource is missing. We are looking for a person to develop a document.

If there is no document, please to resolve read the source. Or, please ask with a "elfinder" tag in [StackOverflow](http://stackoverflow.com/questions/tagged/elfinder).

In addition, we are appreciate if you reflected in the document.
