### ISSUE TITLE
How to add custom data on upload using a form

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1358]
Is there anyway to include a custom form to allow the user to add some custom data (description text for example) on upload?

Perhaps in the upload dialog itself?

I'd like my users to be able to upload a file, include some descriptive text and save that data in my database, which I can then recall later on (already got the answer to the last part)

**Comment by nao-pon** [comment]
We have decided to use only for the development of the issues of Github. Questions will be asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/elfinder) with a "elfinder" tag.

If there is a bug or feature requests here please let us know.
