### ISSUE TITLE
Must be Responsive

### ISSUE THREAD

**Issue by SacDin** [Studio-42/elFinder#1359]
Must be Responsive and mobile friendly

**Comment by Kravalg** [comment]
@SacDin , And there is. True need a hack.

**JS:**
```
$('#elfinder').elfinder({
       ...
       resizable: false,
       ...
});
```
and

```
$(window).resize(function () {
      var h = $(window).height();
      if ($('#elfinder').height() != h) {
          $('#elfinder').height(h).resize();
      }
});
```

**CSS**

```
body {
      margin: 0;
}

#elfinder {
      border: none;
}

.elfinder-toolbar, .elfinder-statusbar {
      border-radius: 0 !important;
}
```

**Comment by troex** [comment]
elFinder uses jQuery UI, so it's responsive as jQuery UI is. About mobile friendly... it's likely another feature. There are no plans for it yet.

**Comment by Kravalg** [comment]
@SacDin , @troex : Developers always on the right things is not enough time. So, we can relax and continue to use hacks or add your own Pull request.

**Comment by dleffler** [comment]
Maybe a partial implementation would be to:

- Allow the cwd tree to be fully hidden (with an icon to expand/collapse?), currently has a minimum/maximum width, but is resizable (there is an option to put the 'up folder level' entry into the file pane I believe)
- Allow the toolbar to be fully hidden (with an icon to expand/collapse)

**Comment by nao-pon** [comment]
> Allow the cwd tree to be fully hidden

What about swipe to close/open ?
[![Swipe to navbar close/open](https://img.youtube.com/vi/9ckpfrvncDg/0.jpg)](https://www.youtube.com/watch?v=9ckpfrvncDg)

**Comment by nao-pon** [comment]
And I added swipe to open/close toolbar. You can try on [demo site](http://studio-42.github.io/elFinder/#elf_l2_Lw).
[![Swipe to navbar close/open](https://img.youtube.com/vi/y3hPkoOTCwk/0.jpg)](https://www.youtube.com/watch?v=y3hPkoOTCwk)

**Comment by CodeLyokotEAM** [comment]
File drag&drop funtion isn't work with my mobile browser

**Comment by nao-pon** [comment]
In elFinder 2.1.12 it will be pretty much fixed.(ref. #1373) So I close this issue. And we waiting more requests. Please make new issues of that.

**Comment by ahrasis** [comment]
@Kravalg Where did you add those codes you mentioned above?
