### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1362]
error
"Unable to connect to backend.
Backend not found."
what I do for this?

**Comment by nao-pon** [comment]
@CodeLyokotEAM Why do you think a bug? We will not be able to do anything and there is no additional information.

- Which version of elFinder?
- Which connector are you using?
- What is your connector & client configuration?

**Comment by CodeLyokotEAM** [comment]
I didn't change any thing.
but my browser said,

Request URL:http://127.0.0.1/elFinder-2.1.11/php/connector.minimal.php?cmd=open&target=&init=1&tree=1&_=1462187657270
Request Method:GET
Status Code:404 Not Found
Remote Address:127.0.0.1:80

**Comment by CodeLyokotEAM** [comment]
After I copy & Rename "connector.minimal.php-dist" to "connector.minimal.php" problem is solved.
