### ISSUE TITLE
FTP Driver issues... It does not work :-(

### ISSUE THREAD

**Issue by MG73** [Studio-42/elFinder#1363]
Hi,
I can successfully use elfinder 2.1.11 with LocalFileSystem but it does not work with FTP driver...
I can access my FTP remote server and it displays files and folder in root but I can't open any folder to access subfolders. (Error message I get: Unable to open "name of the folder".
Folder not found.)
Moreover: I can upload files and create new folders (in this case I can also open), but the file uploaded or the folder just created gets a \ (backslash) at the beginning of his name when the filelist is refreshed...
I also cannot view the thumbnails...
Here are my connector options:

                        'driver' => 'FTP',
                        'host'   => 'xxx',
                        'user'   => 'xxx',
                        'pass'   => 'xxx',
                        'mode'   => 'passive',
                        'path'   => '/',
                        'tmpPath' => 'tmp',
			'uploadDeny'    => array('all'),  
			'uploadAllow'   => array('image', 'text/plain'),
			'uploadOrder'   => array('deny', 'allow'),
			'accessControl' => 'access'

Anyone can help me please ? Thanks

**Comment by troex** [comment]
This really can depend on FTP server you use, driver should work with most unix ftp server, backslash in the file name... probably you are using windows ftp server which may need some hacks if it doesn't support MLST and MLSD commands.

**Comment by nao-pon** [comment]
@MG73 There is not similar problem in I've tried. What kind FTP server?

**Comment by MG73** [comment]
Thank you for helping... My server is Linux OS, I am trying to use it in localhost (with XAMPP) connecting to a remote FTP...

**Comment by MG73** [comment]
I solved it... Used from server to server it works... The issue is only from windows localhost to remote server... Thanks for the hint :-)

**Comment by nao-pon** [comment]
> The issue is only from windows localhost to remote server.

Exactly! I'll fix it.

**Comment by nao-pon** [comment]
@MG73 @troex Thanks! :+1:
