### ISSUE TITLE
contextmenu in bootstrip model

### ISSUE THREAD

**Issue by bilaljaffer** [Studio-42/elFinder#1364]
When an elFinder (2.1.11) html is loaded into bootstrap modal (http://getbootstrap.com/javascript/#modals). The context menu is disabled. What is the problem with the model. or there is some best way to load the elfinder in bootstrap modal.
If we initialize elfinder not in modal it works perfectly.

**Comment by troex** [comment]
Not totally sure but I think it's the problem with z-index of context menu, probably bootstrap model z-index. Try setting css:
```css
.elfinder .elfinder-contextmenu,
.elfinder .elfinder-contextmenu-sub {
  z-index: 1100; // value higher than bootstrap modal, I think it's 1040 by default
}

**Comment by bilaljaffer** [comment]
I have tried, but the same results, i think it's some js issue.

**Comment by nao-pon** [comment]
@bilaljaffer I did a modification of the z-index on or after 2.1.11. Please try the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by bilaljaffer** [comment]
![image](https://cloud.githubusercontent.com/assets/19148672/14954847/013faee8-108f-11e6-94c1-4d32192d53ef.png)
The contextmenu is is now active, but can you see the screen shot, where i click, and where the menu is open??

**Comment by nao-pon** [comment]
@bilaljaffer Did you try to update the browser cache?

**Comment by bilaljaffer** [comment]
yes i try but the same results.

**Comment by nao-pon** [comment]
I'm testing in http://hypweb.net/elFinder-nightly/demo/develop/bootstrap.html. It seems no problem.
