### ISSUE TITLE
How i can get the link to the folder in file manager?

### ISSUE THREAD

**Issue by Kravalg** [Studio-42/elFinder#1365]
I need to know how are generated the names of the paths to folders in elfinder, to enable my clients to move through it and get to this folder in your file manager

**Comment by troex** [comment]
Generally elFinder uses base64 to encode file paths, it also prepends root number with `elf_l{root number usually 1}_{base64 of directly}` if you know the path you can generate link to it

**Comment by troex** [comment]
closed due to inactivity
