### ISSUE TITLE
Upload file from URL

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1366]
can you improve file upload to web link file upload?

**Comment by troex** [comment]
There is currently no plans for it, but it's possible to write a plugin for it. I'll leave it as feature request

**Comment by nao-pon** [comment]
This has already been run on elFinder 2.1.

**These can be**
- Paste URL list in the upload dialog
- URL list DnD to elFinder
- DnD from other browser window / tab elements.

**Comment by troex** [comment]
@nao-pon if I press upload icon in toolbar it opens system OS dialog to select files to upload, but if I right click in workzone and select `Upload files` it opens elfinder dialog, I think toolbar should also open elfinder dialog. Can you please check it?

**Comment by CodeLyokotEAM** [comment]
you correct. but I try to upload "https://codeload.github.com/Studio-42/elFinder/zip/master"
It say uploading file but still shows uploading file. 
![image](https://cloud.githubusercontent.com/assets/18566890/14958453/793cec44-10a8-11e6-9d07-c0613f4839a3.png)

**Comment by nao-pon** [comment]
It is no problem on [demo site](http://studio-42.github.io/elFinder/#elf_l2_Lw). Please check firewall etc of your localhost.

**Comment by nao-pon** [comment]
@troex 
>  I think toolbar should also open elfinder upload dialog. Can you please check it?

Yes, I'll check it.

**Comment by nao-pon** [comment]
@troex I changed default value of `commandsOptions.upload` form 'uploadbutton' to 'button'.
