### ISSUE TITLE
It broken backward compatible to jQuery UI < 1.11

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1367]
version  - elFinder-master

I try to file drag & drop same pales(not to folder or different pales--- I mean somewhere in work zone.).but file icon is stuck.

**Comment by troex** [comment]
I'm not sure I understand what you mean, does it happens on [demo](http://studio-42.github.io/elFinder/)? Can you please attach screenshot, also browser you are using

**Comment by CodeLyokotEAM** [comment]
![image](https://cloud.githubusercontent.com/assets/18566890/14958510/c00cbe2e-10a8-11e6-986e-65abbb921ce9.png)

**Comment by troex** [comment]
Looks strange... I don't have this issue and it works for me on demo, are you using touchscreen to interact with elfinder?

**Comment by nao-pon** [comment]
@CodeLyokotEAM DnD is move itmes. DnD + [Shift] or [Ctrl] to copy items.

**Comment by CodeLyokotEAM** [comment]
No, I download "https://codeload.github.com/Studio-42/elFinder/zip/master" & Rename '/php/connector.minimal.php-dist' to '/php/connector.minimal.php'

after I create folder and  its drag & drop same palse in browser scren

**Comment by nao-pon** [comment]
@CodeLyokotEAM Thanks! :+1:
