### ISSUE TITLE
Cannot display Thumbnails (FTP driver)

### ISSUE THREAD

**Issue by MG73** [Studio-42/elFinder#1369]
I am currently using Elfinder perfectly working on my server but I cannot view image thumbnails, here's my connector options, where is my mistake ? Thanks in advance for helping.

           'driver'    => 'FTP',
                        'host'      => 'ftp.myserver.net',
                        'port'      => '21',
                        'user'      => 'xxx',
                        'pass'      => 'xxx',
                        'mode'      => 'passive',
                        'path'      => '/',
                        'URL'       => 'http://www.myserver.net',
                        'tmbURL'    => 'http://www.myserver.net/tmb',
                        'alias'     => 'Home',
                        'tmpPath'   => '/tmp',
                        'tmbPath'   => '/tmb',
                        'defaults'      => array('read' => true, 'write' => true),
			'uploadDeny'    => array('all'), 
			'uploadAllow'   => array('image', 'text/plain'),
			'uploadOrder'   => array('deny', 'allow'),  
			'accessControl' => 'access'

**Comment by nao-pon** [comment]
@MG73 Thumbnails will be stored on the server placed the connector. FTP server and Web server are running on a same server?

**Comment by MG73** [comment]
I tried both with no luck... Maybe am I wrong with slashes or absolute path ?
Or do you mean tmb folder must be in the php folder where exactly is the connector file ?
Thanks

**Comment by troex** [comment]
@MG73 as nao-pon said thumbnails will be created on the server where connector.php is located, so `/tmb` probably will not work try to specify different directory where your web document root is located usually `/var/www/...` or `/home/user/...` depends on your web server configuration

**Comment by MG73** [comment]
It was /home/hd_www/ on my server, then I also needed to give 777 permission to the tmb folder, now it works !!! Thank you very much :-)
