### ISSUE TITLE
Original LastWriteTime for uploaded file

### ISSUE THREAD

**Issue by svetlanadzhura** [Studio-42/elFinder#1370]
On server side during request cmd='upload' there is no correct LastWriteTime file info. Is it possible to send LastWriteTime some how as extra parameter for each file or as part of HttpFileCollection in order to extract the original LastWriteTime on server? Thank you

**Comment by troex** [comment]
That is not something that depends on elfinder, elfinder uses `mtime` of `stat()` to get last modification time http://php.net/manual/en/function.stat.php. When you upload a file it is actually created on the server, so creation time (and last modification `mtime`) is time when it was uploaded and not when file was created on your computer.

It's general filesystem design and we're not going to break it.

**Comment by svetlanadzhura** [comment]
@nao-pon

**Comment by nao-pon** [comment]
@svetlanadzhura I am in the planning is to be sent a mtitme during file upload. However, it does not process in the core. You will be able to handle a callback by bind.

**Comment by nao-pon** [comment]
I thought at the time that this implementation. It is a copy or move on the local file system is that we should keep the time stamp.

I am thinking the introduction of options.

For example,
```php
$ This-> options [ 'keepTimestamp'] = array ( 'copy', 'move'); // keep timestamp at inner filesystem allowed 'copy', 'move' and 'upload'
```
What do you think @svetlanadzhura @troex ?

**Comment by svetlanadzhura** [comment]
For me that is fine
