### ISSUE TITLE
Focus after download

### ISSUE THREAD

**Issue by svetlanadzhura** [Studio-42/elFinder#1371]
After file downloading some toolbar icons get disabled. I suppose that happens since elfinder loses focus. Is it possible return focus to elfinder right after download completion? Thank you!

**Comment by nao-pon** [comment]
@svetlanadzhura If there is another node in the HTML page, it should be disabled When elFinder has lost its focus. However, if there is only elFinder node to HTML pages, there is no need to disable the elFinder. I will fix this.

Thanks!
