### ISSUE TITLE
Mobile friendly

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1373]
I think its add more mobile friendly

Also I saw another web file manger I think its more mobile friendly but its funtions are week than elfinder.

https://github.com/joni2back/angular-filemanager

 you can get ideas from it

**Comment by nao-pon** [comment]
Please give if there is a specific improvement matters.

**Comment by CodeLyokotEAM** [comment]
Can you add file selecting for mobile browser like this ?
![screenshot_2016-05-07-18-57-52](https://cloud.githubusercontent.com/assets/18566890/15092408/7445aa3c-1486-11e6-9075-f0aae270492c.png)
(Like mediafire)becuse too hard for selecting files one by one in elfinder in mobile browser.

**Comment by CodeLyokotEAM** [comment]
Its work perfect. But the check box in near by name tab doesn't work correctly.
![screenshot_2016-05-08-21-35-57](https://cloud.githubusercontent.com/assets/18566890/15098863/18201c76-1565-11e6-8e73-ceb78924a93b.png)

I think its select all files but its doesn't work.

**Comment by CodeLyokotEAM** [comment]
Its work perfectly.Thank you.

**Comment by CodeLyokotEAM** [comment]
This is not bug but I think selecting all files in check box near name bar & disselecting a one of selected files & after auto disselect tick check box near the name bar.
![cfjf](https://cloud.githubusercontent.com/assets/18566890/15099135/3fa3df2a-156b-11e6-8bfc-985a99af17eb.jpg)

**Comment by troex** [comment]
@nao-pon can you make these checkboxes optional?

**Comment by nao-pon** [comment]
@troex OK. I'll add an option. e.g. `selectCheckboxUA: [ 'Touch' ]`

**Comment by CodeLyokotEAM** [comment]
After close navigation panal ,
Can you add like this.
![untitled](https://cloud.githubusercontent.com/assets/18566890/15149826/ad872834-16e8-11e6-8891-cb5dc36b3569.jpg)
Becuse to navigate the file re-open the navigation panal.

**Comment by CodeLyokotEAM** [comment]
Its work perfect. After close navigation panal its too hard for re-open it.  But tool panal is open easy.

**Comment by nao-pon** [comment]
I tuned up. :smiley:

**Comment by CodeLyokotEAM** [comment]
This is't bug.but I think
Manually select all of files &auto tick checkbox near the name bar.
![untitled](https://cloud.githubusercontent.com/assets/18566890/15250180/1c79be32-1941-11e6-8826-bd324e47f1a5.jpg)

**Comment by CodeLyokotEAM** [comment]
Can you add bar to re-open the navigtion panal like picture becuse some mobile device  too difficult to open navigation panal. (becuse the edge is not touch) 
![picsart_05-17-05 05 37](https://cloud.githubusercontent.com/assets/18566890/15321247/dc8e7e4c-1c52-11e6-9dae-dffe31d581fc.jpg)

**Comment by nao-pon** [comment]
@CodeLyokotEAM You can start swipe in the area of 50px from the edge of the elFinder node. I will the modifications to visualize the area.

**Comment by CodeLyokotEAM** [comment]
can you add small icon or something near path in status bar to choose the drivers in el-finder without opening navigation panel ? (because go to another drive in mobile browsers user must re-open the navigation panel.)

**Comment by CodeLyokotEAM** [comment]
Its work perfect.

**Comment by CodeLyokotEAM** [comment]
can you add small icon or something near path in status bar to choose the drivers in el-finder without opening navigation panel ? (because go to another drive in mobile browsers user must re-open the navigation panel.)

**Comment by nao-pon** [comment]
Yes, I have begun. :-)

**Comment by CodeLyokotEAM** [comment]
Its work perfect. ;-)

**Comment by paulcanning** [comment]
How do I activate the mobile view?

I do not get any mobile view when accessing via my phone.

**Comment by nao-pon** [comment]
@paulcanning What is your phone?

**Comment by paulcanning** [comment]
Oneplus One, running COS 13 (Android 6.0.1), Chrome v50.0.02661.89

**Comment by nao-pon** [comment]
@paulcanning to #1425

**Comment by CodeLyokotEAM** [comment]
I try to edit image file in elfinder image editor in mobile devise but I can't control adjusting dots.

**Comment by nao-pon** [comment]
In elFinder 2.1.12 it will be pretty much fixed. So I close this issue. And we waiting more requests. Please make new issues of that.
