### ISSUE TITLE
Create a new folder dos not refresh the folder

### ISSUE THREAD

**Issue by mcarropellicer** [Studio-42/elFinder#1374]
Good morning, 

I'm using elFinder 2.1.0, after create a new folder, the newly created folder doesn't appear unless the view is refreshed.

The latest versions are not affected, can anyone help me to resolve it?

Thanks in advance.

**Comment by troex** [comment]
Please update to latest version `2.1.12`, we do not support older versions.
Also check your connector output there might be some warning preventing ui update.

**Comment by mcarropellicer** [comment]
@troex Thanks for the response.

Unfortunately i cannot upgrade to 2.1.12 at this moment, so i will search for the particular fix of this issue.

Is there any official instance to test older versions like 2.1.0? I want to reproduce the problem and search for the commit that resolved it.

Thanks again!

**Comment by troex** [comment]
there is example http://jsbin.com/boqeho/22/edit?html,output but it uses latest connector, UI is from 2.1.0.

Can you show connector output after creating new folder?
