### ISSUE TITLE
codemirror doesn't work with PHP + how to turn on autocomplete ?

### ISSUE THREAD

**Issue by MG73** [Studio-42/elFinder#1378]
Thanks by @nao-pon and @troex I successfully got Codemirror working with elfinder but:
- don't know why it doesn't work with PHP even if I added specific mime types and specific file...
- how to turn on autocomplete function ?
Here's my addons:

```
 commandsOptions: {
                        edit: {
                          mimes: [],
                          editors: [{
                            mimes: ['text/plain', 'text/x-php', 'application/x-httpd-php', 'text/html', 'text/javascript'],
                            load: function(textarea) {
                              var mimeType = this.file.mime;
                              return CodeMirror.fromTextArea(textarea, {
                                mode: mimeType,
                                lineNumbers: true,
                                indentUnit: 4
                              });
                            },
                            save: function(textarea, editor) {
                              $(textarea).val(editor.getValue());
                            }
                          }]
                        }
                      }
```
and of course I also added:

`<script src="codemirror/mode/php/php.js"></script>`
...Then, about autocomplete I added the following lines with no luck:

```
                <link href="codemirror/addon/hint/show-hint.css" rel="stylesheet" type="text/css"/>
                <script src="codemirror/addon/hint/show-hint.js" type="text/javascript"></script>
                <script src="codemirror/addon/hint/css-hint.js" type="text/javascript"></script>
                <script src="codemirror/addon/hint/html-hint.js" type="text/javascript"></script>
                <script src="codemirror/addon/hint/javascript-hint.js" type="text/javascript"></script>
```

**Comment by troex** [comment]
Here is working example with PHP code, you need to include `clike.js` mode for codemirror http://codemirror.net/mode/php/
> Simple HTML/PHP mode based on the C-like mode. Depends on XML, JavaScript, CSS, HTMLMixed, and C-like modes.

From elFinder side you need to make sure mime-type is correctly detected, use inspector/firebug to check connector output.
![8f22450eb4](https://cloud.githubusercontent.com/assets/436912/15114026/81a59202-1600-11e6-8baa-157dafee1b78.png)

Example: http://jsbin.com/boqeho/18/edit?html,js,output

@MG73 hint and anything else this is out of elFinder scope, please read the docs and source code of codemirror to understand how it works, or ask about codemirror on stackoverflow.

**Comment by MG73** [comment]
Thanks @troex it works now.
