### ISSUE TITLE
Always same filename on upload with iOS devices

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1379]
I haven't much details about this bug.
My friend said he try to upload image files in elfinder & all files are upload same name. He used apple iphone.
Please Can you check it?

**Comment by troex** [comment]
Can't check since I don't have iPhone, but it probably can be true since I phone doesn't have direct access to file system so probably filename isn't passed. What was the the filename?

**Comment by nao-pon** [comment]
I got this problem. filename is "image.jpeg", "image.jpg", or "capturedvideo.MOV". I will think of a method such as that using the file time stamp to the file name.

**Comment by nao-pon** [comment]
My plan is the filename incrementation, because it is impossible to get time stamp of the upload file on iOS.
