### ISSUE TITLE
Can't rotate image. Ver 2.1.11

### ISSUE THREAD

**Issue by bbfriend** [Studio-42/elFinder#1380]
I can't rotate image.

Ver 2.1.11

http://...../elfinder/elfinder.html ,
 all defaut Setting.(Nothing has been set)
 upload image ･･ OK
resize ,crop , rename ･･ OK

But can't rotate.
 example ,rote_tab -> rotate 90 -> Click Apply 
I get message to ~~Error Unable to connect to backend~~
"Invalid backend response.
Data is not JSON."

What do configuration and operating conditions I need?
 Github Demo http://studio-42.github.io/elFinder/ is rotate OK.

~~*addition) now I checked by Firebug.
"NetworkError: 500 Internal Server Error - http://..../elfinder/php/connector.minimal.php?cmd=resize&target=l1_MTIyLmpwZw&width=228&height=328&degree=90&quality=100&mode=rotate&_=1462804481335~~

**Comment by nao-pon** [comment]
@bbfriend Have you more infomation about php errors from server log?

**Comment by StudioJunkyard** [comment]
@nao-pon on this subject, what PHP libraries need to be installed to allow image resizing, rotating, and so on with the editing options?

**Comment by nao-pon** [comment]
@bbfriend I fixed notice error in rotate function @b98d582b785fb4211e6f0b1a79025dda37adcebc.But it was Notice error, It may not be the cause of this problem

**Comment by nao-pon** [comment]
@StudioJunkyard elFinder use php imagick extention, GD, or server command convert(imagimagick). And rotate function use server command exiftran or jpegtran if it is possible.

**Comment by StudioJunkyard** [comment]
Ah ok, I've stayed away from imagick as there's currently an open security issue with it (might be patched now), that was posted about in /r/netsec in Reddit.
I've got GD2 installed on the live server, but the edit, for resize and rotate isn't working according to client reports, I haven't had time to test it myself. Is there something that needs to be enabled in the connector settings, or elsewhere?

**Comment by StudioJunkyard** [comment]
https://blog.cloudflare.com/inside-imagetragick-the-real-payloads-being-used-to-hack-websites-2/

**Comment by nao-pon** [comment]
@StudioJunkyard Use GD(2) to image libs with connector root config `'imgLib' => 'gd'`.

**Comment by StudioJunkyard** [comment]
Thanks @nao-pon, much appreciated. Client's have been loving using your project in my CMS, it's made things so much easier. Using it as an addon for Summernote WYSIWYG editor, and as a Media Manager embedded in a page.

**Comment by bbfriend** [comment]
@nao-pon　私は、日本人です。　Error message was different. エラーを間違ってました。
”Invalid backend response.
Data is not JSON.”　
and Firebug does not have an error. 

*Apache/2.2.15
CentOS 6.2
libjpeg-turbo.x86_64  1.2.1-3.el6_5
php-gd.x86_64  5.3.3-46.el6_7.1

＊http://cmsimple-jp.org/xh2/test/elfinder.html

**Comment by bbfriend** [comment]
And ,Strange phenomenon?
elfinder.html changes in PHP execution form.

Apache Module 
![apache_module](https://cloud.githubusercontent.com/assets/14984349/15185204/25e222b2-17d3-11e6-85a7-b043fd389787.gif)

Apache CGI ,FastCGI 
![cgi](https://cloud.githubusercontent.com/assets/14984349/15185231/3c500186-17d3-11e6-8c18-85da1362f653.gif)

**Comment by bbfriend** [comment]
Find! 
elFinderVolumeDriver.class.php　About line4495


```php
protected function imgRotate($path, $degree, $bgcolor = '#ffffff', $destformat = null, $jpgQuality = null) {  
    debug($path, $degree);  
    if (($s = @getimagesize($path)) == false || $degree % 360 === 0) {
```
to
```php
protected function imgRotate($path, $degree, $bgcolor = '#ffffff', $destformat = null, $jpgQuality = null) {  
//    debug($path, $degree); 
    if (($s = @getimagesize($path)) == false || $degree % 360 === 0) {
```

**Comment out**  ` debug($path, $degree); `

”rotate image”　work fine! 
Thanks for the tip.@nao-pon

**Comment by StudioJunkyard** [comment]
For me it was at line 4460.

**Comment by StudioJunkyard** [comment]
Actually, for me the radio buttons are disabled.

**Comment by bbfriend** [comment]
Hi! StudioJunkyard.
you're right.  Line 4460.

**Comment by nao-pon** [comment]
@bbfriend @StudioJunkyard This bug was already fixed in master branch. Please check with nightly build.

Thanks!

**Comment by StudioJunkyard** [comment]
Cheers @nao-pon keep up the great work.

**Comment by StudioJunkyard** [comment]
I just update everything, even cleared my browser cache to be sure the updated code is being used. I can resize image, but the crop and rotate radio buttons are still disabled. Is there maybe some setting I need to enabled, or apache/PHP library that needs to be installed?

**Comment by StudioJunkyard** [comment]
Actually, I just noticed all three radio buttons are disabled. But the resize still works.

**Comment by StudioJunkyard** [comment]
I should check things a bit more closely. When I actually go to perform the resize on an image, I get back a dialog with an error: Invalid parameters for command "resize".

**Comment by bbfriend** [comment]
@nao-pon
> This bug was already fixed in master branch. Please check with nightly build.

I'm going to publish as a plugin [CMSimple](http://www.cmsimple-xh.org/),stable(regular) version is required.
ありがとう。

**Comment by nao-pon** [comment]
@StudioJunkyard Perhaps ... It seems there are problems in the JavaScript or theme side. Please create a new issue, if necessary.

**Comment by nao-pon** [comment]
@bbfriend OK. 2.1.12 coming soon.

**Comment by StudioJunkyard** [comment]
@nao-pon, currently client's just upload a thumbnail image they wish to use, as I use elF in three ways. As a plugin to Summernote for media management, as a file uploader and selector within an input field for main and thumbnail images for products, blog cover images, and as a stand alone media manager on it's own page. It would be handy to for client's to edit a single upload image by duplicating it, renaming it, and cropping or rotating to use a thumbnail.
