### ISSUE TITLE
dialogHeight or overriding the dialog window

### ISSUE THREAD

**Issue by MG73** [Studio-42/elFinder#1381]
Is there a way to set the dialogHeight as it is possible to do it with dialogWidth ?
Or...
Is there a way to override the dialog window when opening a file and redirect the content in a custom container div ?
Thanks in advance.

**Comment by troex** [comment]
dialog is `height: auto;` so you need to adjust you content editor height. you can do it with css too

```css
.elfinder-file-edit {
  height: 800px;
}
```
