### ISSUE TITLE
NodeJS adapter

### ISSUE THREAD

**Issue by matankadosh-softangible** [Studio-42/elFinder#1382]
would love to know if there are any estimation about a NodeJS adapter.
As more and more web developers moving to nodejs it becomes much more essential.

**Comment by troex** [comment]
This is good idea and I know node is getting more popular lately, however we don't have any plans for writing node connector on our own, there are a lot of community connectors for asp/python/ruby and others, so all the hope is on community.

**Comment by kadosh1000** [comment]
@troex ,
Is there any sort of document specifing all the possible commands and what it expects to get back?

**Comment by troex** [comment]
Sure it's API doc https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.0 see [commands list](https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.0#command-list) the minimum required I believe are first five _open, tree, file, parents, ls_ if you implement these five commands on your backend it elFinder client should start working with limited functionality

**Comment by dekyfin** [comment]
I have created an elFinder adapter for NodeJS. Check it out at https://github.com/dekyfin/elfinder-node

**Comment by nao-pon** [comment]
@dekyfin Thanks! 👍 I added to [README.md](https://github.com/Studio-42/elFinder/commit/39bdf2cd4513e0c334e867e75e1fb1476fd8615d).

**Comment by nao-pon** [comment]
It is settled by using a third party connector.
