### ISSUE TITLE
Drag and drop files to desktop

### ISSUE THREAD

**Issue by dipens** [Studio-42/elFinder#1383]
Hello,

Is it possible to drag and drop files back to desktop (how gmail does it explained [here](www.thecssninja.com/javascript/gmail-dragout)).

If not, it would be nice to have a feature like that on elFinder. Please share your thoughts.

**Comment by nao-pon** [comment]
@dipens [Shift] + drag start to drag out. But Google Chrome only

**Comment by dipens** [comment]
@nao-pon Wow thank you. Didn't know about this one.
