### ISSUE TITLE
Files are missing

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1384]
I try to open elfinder.html my browser console said "404 not found css/elfinder.min.css, js/elfinder.min.js "

**Comment by troex** [comment]
if you're using git version you need to [build elfidner](https://github.com/Studio-42/elFinder/wiki/Build-and-compress-elFinder-from-source) first

**Comment by bgbruno** [comment]
pls attach this into github too - it's too complicated everytime compile - I just want download from github and run it

**Comment by nao-pon** [comment]
@bgbruno Please use the [2.1 branch](https://github.com/Studio-42/elFinder/tree/2.1). It is built frequently.
