### ISSUE TITLE
Trigger getFileCallback on selecting download option

### ISSUE THREAD

**Issue by idkl** [Studio-42/elFinder#1385]
i want to implement a getFileCallback on double click and on selecting the download option after rightclicking a file.

For example the following only triggers on doubleclick
```
getFileCallback: function(file, fm) {
				alert(file.url);
		                $('#elfinder').elfinder('instance').exec('download');
            }
```
how can i also trigger this on the download option?

thanks all for helping

**Comment by nao-pon** [comment]
@idkl You can with ...
```javascript
getFileCallback : function(file, fm) {
	fm.exec('download', [ file.hash ]);
},
```
