### ISSUE TITLE
getting filename on download handler

### ISSUE THREAD

**Issue by idkl** [Studio-42/elFinder#1386]
hello all, i am using the following handler
```
handlers: {
        			dblclick: function(event, elfinderInstance) {
            			var file = event.data.file;
				alert('dblclick ' + file);     
        			},
        			download: function(event, elfinderInstance) {
            			var file = event.data.file;
				alert('download ' + file);     
        			}
    			}

```
on doubleclick i get a response but on download i get undefined, how can i get the filname on download?

thanks for helping

**Comment by nao-pon** [comment]
@idkl `download` is not binded to handlers. but you can use `bind`.

e.g.
```javascript
var elfinderInstance = $('#elfinder').elfinder({
    // your options object
}).elfinder('instance')
.bind('download', function(event) {
	elfinderInstance.log(event); // print to browser console
});
```

**Comment by idkl** [comment]
@nao-pon after some tinkering i found the following solution to get the filename on download
handlers: {
        			download: function(event, elfinderInstance) {
				var file = event.data.files[0].hash;
				myfunction(file); // do whatever
        			}
        			}

Thanks for helping 

regards Ingolf
