### ISSUE TITLE
photography image folder

### ISSUE THREAD

**Issue by donraton** [Studio-42/elFinder#1387]
There is possibility to change the image of a photograph folder ?.
I have several folders, and each corresponds to a product and would like to change the icon carmeta for the product image.

Thank you

**Comment by StudioJunkyard** [comment]
You can change the folder icons via CSS, but it would change all the folder icons, I don't think it would change a specific one. Not unless there was something like a folder type class or other way to designate the type of folder. Maybe if the the folder has a specific name, you could possible target the folder via CSS, and apply a style for that. I've never noticed if, for e.g. the name of the folder which is displayed as text, also has an attribute like name="photography", or title="photography", then you could do something like `.folder[name=photography]{}`.
I might actually give this a go, as representing folders for the content they contain might be handy for client's.

**Comment by StudioJunkyard** [comment]
@nao-pon I just had a look after my above comment. This would be doable if there was a title, or other attribute in the element that's generated that displays the actual icon.
````
<div id="" class="elfinder-cwd-file directory ui-corner-all ui-droppable native-droppable" title="[this contains a date]">
  <div class="elfinder-cwd-icon elfinder-cwd-icon-directory ui-corner-all" unselectable="on" [some attribute]="[folder name]"></div>
</div>
<div class="elfinder-cwd-filename ui-draggable ui-draggable handle" title="[folder name]">[folder name]</div>
````
As you can see the `[folder name]` is after the element that is styled to display the folder icon. If there was an attribute with the [folder name] in the styled element then we could assign an icon to use as per the original Issuer's request using only CSS.

**Comment by nao-pon** [comment]
@donraton , @StudioJunkyard If you are using LocalFileSystem driver, you can use volume root option `detectDirIcon`. I've just added to the [Wiki](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#localfilesystem).

ref. #1231 - Folder icon

By the way it is it is a good idea to add an HTML attribute. e.g. "data-dirname" attribute...

**Comment by nao-pon** [comment]
I have also forgotten but had been in `getClass` client option.

`uiOptions.tree.getClass` and `uiOptions.cwd.getClass` I think this in enough.

ref. #1061 and https://github.com/Studio-42/elFinder/blob/bf1fc1520a9226e204960ba66231f4da7d46978f/js/elFinder.options.js#L509-L519, https://github.com/Studio-42/elFinder/blob/bf1fc1520a9226e204960ba66231f4da7d46978f/js/elFinder.options.js#L551-L561.

**Comment by donraton** [comment]
Thank you for your comments but I could tell that document I have to change it ?.
I care not pay for the modification as it is a commission from a client

**Comment by StudioJunkyard** [comment]
If the Icon markup appeared after the folder name in the DOM, then we could easily target the Icon using the next sibling abilities of CSS, as it is, CSS can't traverse backwards, only forwards. Hence, why it can't be targeted using CSS.

**Comment by nao-pon** [comment]
For example to using CSS.

**Additional CSS**
```css
<style>
	.elfinder-cwd-file.picture-folder .elfinder-cwd-icon {
		background:url("[PATH TO]/MyPictures.png") 0 0 no-repeat;background-size:contain;
	}
</style>
```

**elFinder  client configuration**
```javascript
uiOptions: {
	cwd: {
		getClass : function(file) {
			return file.name.match(/photo|picture|image/i)? 'picture-folder' : '';
		}
	}
}
```

Then -> http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l2_UGhvdG9z

**Comment by StudioJunkyard** [comment]
Ah, now I see what you mean. I was hoping for a solution without having to add more js, lol. Will have to add this option to the bootstrap-theme, and add extra folder types.

**Comment by donraton** [comment]
The example you mention, no use to me as I want to replace the folder icon for an image called imagen.png

**Comment by StudioJunkyard** [comment]
Yeah, replace the image reference in the code that @nao-pon showed you, with the image you want to use. It's pretty easy, I used SVG Icons with what I did from the examples, and even added more folder types so different folders can have different icons.

**Comment by donraton** [comment]
I can indicate that file is elFinder client configuration

**Comment by StudioJunkyard** [comment]
The `uiOptions` goes in the javascript options when calling the elFinder instance.

**Comment by donraton** [comment]
thanks for taking your time to my question, but I'm a klutz

**Comment by donraton** [comment]
To Modify be kind enough to tell me ?, you the files that files have to send them

**Comment by donraton** [comment]
I would like to make a donation to the creator of the application

**Comment by StudioJunkyard** [comment]
Not sure what you mean on the comment above I added a confused icon too.

There's a donate button on the site below:
http://studio-42.github.io/elFinder/#elf_l1_YV9sb3Rfc2FtcGxl

**Comment by donraton** [comment]
Not like modify files that comment me, you want me modificasen.

**Comment by StudioJunkyard** [comment]
Yes you need to make the modifications, we don't have access to your stuff to do it for you. Plus, it'll be a learning experience for you.

**Comment by donraton** [comment]
You could send me indicate that files for editing and make a donation
