### ISSUE TITLE
add google drive login form

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1388]
So far this module works great. I wish if u can add a google drive login form to this. So then user can transfer files to his own drive very easily. Maintain  this project, so we can use this for future uses. Thumbs up. Keep it up

**Comment by nao-pon** [comment]
@CodeLyokotEAM It's already been implemented available. Please read connector.minimal.php-dist source code comment. - https://github.com/Studio-42/elFinder/blob/master/php/connector.minimal.php-dist#L36-L47
