### ISSUE TITLE
Major caching issues

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1390]
There are still massive issues with caching.

I am connecting to Google Cloud Storage and after making a new folder in the bucket (which shows up in my GCS console) and I refresh the page, the folder is **_NOT_** visible.

**Comment by paulcanning** [comment]
My root options:

```
array(
					'id' => 'blah',
					'driver' => 'Flysystem',
					'alias' => 'CS Root',
					'URL' => 'https://storage.googleapis.com/MY_BUCKET/',
					'filesystem' => new Filesystem($this->googleCloud('MY_BUCKET')),
					'separator' => '/'
				)
```

**Comment by paulcanning** [comment]
It gets worse. If I change the target bucket back and forth, and even change the ID attribute, I can land in a bucket and see an old, now deleted sub folder.

**Comment by barryvdh** [comment]
https://github.com/barryvdh/elfinder-flysystem-driver/issues/43

Can you avoid creating multiple same issues, or at least reference them.

The flysystem drivers caches in the session by default, so when you load the contents in elfinder, then do something in the cloud console directly, it will indeed not show up. But hitting the refresh button in elfinder should clear the cache. You can also set the `cache`  option to `false`

**Comment by paulcanning** [comment]
Sorry, I am unsure where the problem lies so put issues on each repo. I'll make sure to reference in future. 

I understand I wouldn't see changes in elFinder after doing stuff in the console until I refresh elFinder. But even so, folders made in the console do not show up after a refresh. 

Also, if I create a folder in elFinder, navigate into it and try to upload a file, I get an error saying the folder doesn't exist.

**Comment by nao-pon** [comment]
@paulcanning Perhaps, this problem would not be due to elFinder. However, If you find the matters to be corresponding to elFinder, please let us know and then re-open.
