### ISSUE TITLE
Chunked file uploading: CIDs are always same as PHP_INT_MAX

### ISSUE THREAD

**Issue by Seungcheol-Lee** [Studio-42/elFinder#1391]
Hi, I am working on finding out how to implement 'Continue uploading when an uploaded file which is larger than 1G has been stopped being uploading intentionally or not, even when web browser was closed for 6 hours or so' kind of thing.

And I found a line of code at
php/elFinder.class.php :: Line# 1974
```php
$cid    = $args['cid']? (int)$args['cid'] : '';
```
which it always cast cid into integer, however this cid seams to be generated on client side by
js/elFinder.js :: Line# 3510
```javascript
chunkID = new Date().getTime(),
```

So I think the cid on the back end is always same as PHP_INT_MAX, because obviously javascript date.getTime() always return a number larger than that.
And also I don't think this implementation was intentional.

But this unchanging cid is kinda helping me to get to my goal easily.

p.s I am new to GitHub and this is my first article on GitHub. AND my English skill is kinda crappy. So please let me know if I've done something wrong. Regards.

**Comment by nao-pon** [comment]
@Seungcheol-Lee I did not think about the integer maximum value of 32-bit systems. I will fix this. Thanks! :+1:
