### ISSUE TITLE
Can you add create password protected zip?

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1392]
Can you add Zip fie created with password protected?

&bug- I try to extract password protected zip file in elfinder but 0 byte in all files.

Found usefull site,
http://php.net/manual/en/class.ziparchive.php

**Comment by standus** [comment]
ziparchive native class, doesnt support create password protected archive. Only unzip is possible.

**Comment by CodeLyokoXtEAM** [comment]
@standus 
This is only suggestion but I noticed someone try to unzip password protected zip in elfinder, its impossible

**Comment by CodeLyokoXtEAM** [comment]
useful projects: 
https://github.com/comodojo/zip
https://github.com/alchemy-fr/Zippy
https://github.com/Chumper/Zipper

**Comment by CodeLyokoXtEAM** [comment]
I started devolpe zip editing php
This still developing. 
```
<?php
$ZipFileName='zip.zip';//zip file path
$cmd='get'; //'get','rename'
$index='2' ; //calling index
$rname='ee';//new file name for rename

$zip = new ZipArchive;

if($zip->open($ZipFileName) == TRUE);
{
	if ($cmd=='get')
	{
		for ($i=0; !empty($zip->statIndex($i)['name']); $i++)
		{//generating list (including identification index, name or path, size)of folders and files inside the zip
		echo "index: ".$i." | ";
			if(substr($zip->statIndex($i)['name'], -1)=='/')
			{
				echo "Folderpath: ";
			} 
			else
			{
				echo "Filepath: ";
			};
			echo $zip->statIndex($i)['name']." | Size: ".$zip->statIndex($i)['size']." bytes<br>";
		};
	};
	
	if ($cmd=='rename')
	{//rename using index given file or folder rname
		$zip->renameIndex($index,$rname);
		if($zip->statIndex($index)['name']==$rname)
		{
			echo "rename success";
		}
		else
		{
			echo "faild to rename";
		};
	};
	
	
};

$zip->close();

?>
```
But I doesn't know how to attach it to elfinder.

**Comment by CodeLyokoXtEAM** [comment]
But its impossible to rename folders inside zip

**Comment by CodeLyokoXtEAM** [comment]
Also its impossible to create password protected zip in php
