### ISSUE TITLE
How to use Google Drive?

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1394]
I cannot find any proper documentation on how to setup a Google Drive root.

Can anyone point me in the right direction on how to use Drive with elFinder?

**Comment by nao-pon** [comment]
@paulcanning Please read connector.minimal.php-dist source code comment. - https://github.com/Studio-42/elFinder/blob/master/php/connector.minimal.php-dist#L36-L47

ref. #1388

**Comment by paulcanning** [comment]
Yea, that documentation is useless to me.

I want to add Google Drive alongside a LocalFileSystem. Can You please provide correct documentation and not just link to some terrible comments?

**Comment by nao-pon** [comment]
What about https://github.com/nao-pon/flysystem-google-drive#usage-to-with-elfinder ?

**Comment by paulcanning** [comment]
Much better. Just trying it now. Where do I get the Client ID, secret and refresh token from? I cannot see anything like that in my Drive API credentials.

**Comment by nao-pon** [comment]
e.g. http://stackoverflow.com/questions/8942340/get-refresh-token-google-api

**Comment by ShyamSunderSuthar** [comment]
can you just provide the changes including the google drive setup and so that we just have to add our client id and secret and token to just get and go no need to do all the things mentioned...

**Comment by musaddiq-pk** [comment]
Hello, I just installed elFinder and only changed the few lines in _php/connector.minimal.php_

`elFinder::$netDrivers['googledrive'] = 'GoogleDrive';
// // GoogleDrive Netmount driver need next two settings. You can get at https://console.developers.google.com
// // AND reuire regist redirect url to "YOUR_CONNECTOR_URL?cmd=netmount&protocol=googledrive&host=1"
define('ELFINDER_GOOGLEDRIVE_CLIENTID',     'MY_ID');
define('ELFINDER_GOOGLEDRIVE_CLIENTSECRET', 'SECRET');
// // Required case of without composer
define('ELFINDER_GOOGLEDRIVE_GOOGLEAPICLIENT', '../google-api-php-client-master/vendor/autoload.php');`

Would it upload file to google drive or I have to do little more work?

Thanks
![connector](https://user-images.githubusercontent.com/11736070/61294526-6d0b7300-a7ef-11e9-9fbf-1e95cb8d9525.png)

**Comment by nao-pon** [comment]
@musaddiq-pk If you use the Autoload mechanism, please load autoload.php.

**ex.**
```php
// load composer autoload before load elFinder autoload If you need composer
require '../google-api-php-client-master/vendor/autoload.php';

// elFinder autoload
require './autoload.php';
// ===============================================

elFinder::$netDrivers['googledrive'] = 'GoogleDrive';
// // GoogleDrive Netmount driver need next two settings. You can get at https://console.developers.google.com
// // AND reuire regist redirect url to "YOUR_CONNECTOR_URL?cmd=netmount&protocol=googledrive&host=1"
define('ELFINDER_GOOGLEDRIVE_CLIENTID',     'MY_ID');
define('ELFINDER_GOOGLEDRIVE_CLIENTSECRET', 'SECRET');
```

**Comment by musaddiq-pk** [comment]
@nao-pon thanks! Yes, it's missing and I included it as suggested. But on uploading file to via elFinder still no file uploaded to googe drive. The connector.minimal.php file I'm using is attached here.
[connector.minimal.txt](https://github.com/Studio-42/elFinder/files/3398245/connector.minimal.txt)

**Comment by musaddiq-pk** [comment]
I've did everything what I was missing i.e register a url as can be seen in attached snap.
Now I'm confused 
`// AND reuire regist redirect url to "YOUR_CONNECTOR_URL?cmd=netmount&protocol=googledrive&host=1"` 
what this line means. I picked it as to require it like 
`require 'http://www.jobmoqa.pk/elFinder/my-redirect.php?cmd=netmount&protocol=googledrive&host=1';`
Can you please verify that I'm doing it in a right way. It gives no error but no upload to Google Drive.

Thanks
![elFinder-reg-url](https://user-images.githubusercontent.com/11736070/61974649-7de29280-b000-11e9-8142-58feec35a0ca.png)

**Comment by nao-pon** [comment]
@musaddiq-pk Please comment out this line.

`define('ELFINDER_GOOGLEDRIVE_GOOGLEAPICLIENT', '../google-api-php-client-master/vendor/autoload.php');`

Also, this configuration allows GoogleDrive to be network mounted. If you want a permanent mount, you need to configure it as a fixed drive.

Please search by [“refresh_token”](https://github.com/Studio-42/elFinder/issues?utf8=%E2%9C%93&q=refresh_token).

**Comment by gustavognu** [comment]
> I've did everything what I was missing i.e register a url as can be seen in attached snap.
> Now I'm confused
> `// AND reuire regist redirect url to "YOUR_CONNECTOR_URL?cmd=netmount&protocol=googledrive&host=1"`
> what this line means. I picked it as to require it like
> `require 'http://www.jobmoqa.pk/elFinder/my-redirect.php?cmd=netmount&protocol=googledrive&host=1';`
> Can you please verify that I'm doing it in a right way. It gives no error but no upload to Google Drive.
> 
> Thanks
> ![elFinder-reg-url](https://user-images.githubusercontent.com/11736070/61974649-7de29280-b000-11e9-8142-58feec35a0ca.png)

es muy sencillo en eso se refiere solo agregar esta ruta (en mi caso local puerto 9000
![Captura de pantalla de 2019-11-25 10-55-53](https://user-images.githubusercontent.com/49495898/69561045-5847a480-0f72-11ea-90bb-6466e0668981.png)
