### ISSUE TITLE
File size upload issue

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1395]
I have set both `post_max_size` and `upload_max_filesize` to '10G' and also set `'uploadMaxSize' => '10G'` for my LocalFileSystem adapter.

Despite this, I cannot upload files larger then 2G.

**Comment by StudioJunkyard** [comment]
Did you restart Apache/nGinx (or whatever your using)? Also, does your server side script limit the file size of uploaded files. There's also a PHP setting for .htaccess that can limit uploaded file sizes.

**Comment by paulcanning** [comment]
I restarted WAMP several times. No .htaccess file in use. I am using Codeigniter 3, but there doesn't seem to be any default file size limit.

**Comment by StudioJunkyard** [comment]
hm, WAMP, not sure if there'a anything else that could be stopping it. I haven't used WAMP for over 10 years or so, surprised it's still around. Personally, I use Linux, and a LAMP stack. If I think of anything else that could be an issue, I'll let you know.

**Comment by paulcanning** [comment]
Well is pretty much the same, just running on Windows.

**Comment by StudioJunkyard** [comment]
I know what WAMP is, and there are some differences.

**Comment by StudioJunkyard** [comment]
In your PHP connector for elFinder, check that there isn't a file size limit option set. I didn't see one in mine, but I have extensively modified mine so the folders resolve correctly so I may have removed it if it was there.

**Comment by paulcanning** [comment]
I have it set to `0` which should mean unlimited

**Comment by StudioJunkyard** [comment]
maybe try removing the option in the connector file (or comment it out), and see if that helps. Ideally you should only need to set the options in the connector file.

**Comment by paulcanning** [comment]
Tried that, no luck.

**Comment by lianee** [comment]
Create a file info.php (for example) and put the following in it:
`<?php phpinfo(); ?>`
call that file in your browser and look if you can find something limiting your uploads, I bet you'll do

**Comment by nao-pon** [comment]
Probably in the 32-bit system is likely to files over 2GB PHP can not handle properly. Try a 64-bit system.

**Comment by StudioJunkyard** [comment]
oh FFS, I thought you were trying to upload 2MB, lol. I think @nao-pon may be on the mark with this, file system limitations.

**Comment by paulcanning** [comment]
I am using Windows 10 64bit.

@lianee I checked phpinfo(), and all my PHP settings are fine, as stated above.

**Comment by StudioJunkyard** [comment]
Are you running the 64-bit version of WAMP?

**Comment by paulcanning** [comment]
@StudioJunkyard aha, no I'm not! It's 32 bit, for some odd reason haha!

Is there a way to upload these large files, chunked to 2gb?

**Comment by StudioJunkyard** [comment]
WAMP being 32bit, will more than likely be the issue.
Also, what could you possibly be uploading that 2GB?

**Comment by nao-pon** [comment]
elFinder can not upload a file that exceeds the value of PHP_INT_MAX. This is by design.

**Comment by paulcanning** [comment]
I need to upload files bigger the n 2GB, possibly up to 100GB.

**Comment by nao-pon** [comment]
@paulcanning You will need to use the more than 64-bit systems.

**Comment by paulcanning** [comment]
OK, I am using WAMP 64 bit, PHP 5.6 64bit, which allows for larger then 2GB file uploads http://php.net/releases/5_6_0.php

Yet elFinder still fails to let me upload files larger then 2GB.

**Comment by nao-pon** [comment]
@paulcanning What is result in next?
```php
<?php
echo 'PHP_INT_SIZE: ' . PHP_INT_SIZE . ' , PHP_INT_MAX: ' . PHP_INT_MAX;
```

**Comment by paulcanning** [comment]
Well this is buggered.

I am on 64bit Windows, running 64bit WAMP (Apache) and 64bit PHP v5.6.21. My PHP_INT_MAX should be `9223372036854775807`

`PHP_INT_SIZE: 4 , PHP_INT_MAX: 2147483647`

**Comment by StudioJunkyard** [comment]
There must be another setting overriding your edited setting somewhere.

**Comment by paulcanning** [comment]
The only place `PHP_INT_MAX` is mentioned is in the elFinder library.

**Comment by StudioJunkyard** [comment]
Does that get set by elFinder, or does it get the setting from somewhere else? If so, do a search in the elFinder source to see where it gets the setting from.

**Comment by paulcanning** [comment]
elFinder check to see if it is set, if not, it sets it.

The test I just did does not even load elFinder, so the issue is not with elFinder, or my project. Something up with WAMP or Windows.

**Comment by StudioJunkyard** [comment]
ah ok, you must be getting close to what's going on. I just resolved an issue I was having between Bootstrap and elFinder. Always a good feeling when something is worked out.

Silly question. Have you tried doing a search in google for say "wamp file size limitation upload large files" or something like that?

**Comment by phtsaibb** [comment]
I also have the same 2GB upload issue. Change the setting 'uploadMaxSize' to 0 to make chunk upload, also got the error. Does paulcanning solve the issue?

**Comment by paulcanning** [comment]
@phtsaibb I think the issue lies with Windows and PHP. There is some info online about it, and the solution tended to be "use Linux".

We have a linux server we pay for, so I may try and test on there.

**Comment by phtsaibb** [comment]
We use Debian OS.
I found the setting be re-set at elfinder.full.js about line 1340 by response.options:
`cwdOptions = $.extend({}, cwdOptions, response.options); `

**Comment by paulcanning** [comment]
@phtsaibb AFAIK if you are running 64bit Linux, with 64bit Apache and PHP 5.6+, with the php.ini settings sorted, you should be able to upload more then 2gb.

**Comment by phtsaibb** [comment]
@paulcanning  Thanks your advise. We use 32 bit Debian.
