### ISSUE TITLE
Clicking off the file during a rename crashes the browser

### ISSUE THREAD

**Issue by frazjp65** [Studio-42/elFinder#1399]
When I rename a file, it works fine if I change the name and press enter when completed. If I change the name of a file, then click on the file manager, it pops up numerous dialogs saying "Unable to rename file. File not found." and the page becomes unresponsive. 

The debug logs keep repeating: 
elfinder debug: [event-select] [userFilesManager] Object {selected: Array[0]}
(program):10 elfinder debug: [event-lockfiles] [userFilesManager] Object {files: Array[1]}

It also has repeated failed ajax requests to "cmd=parents&target=l1_Lw&_=1463499678619", "cmd=rename&target=l1_aGVhZGVyLWxvZ28uanBn&name=header.jpg&_=1463499678594", and "cmd=open&reload=1&target=l1_Lw&tree=1&_=1463499678722". 

If I rename the file and click somewhere else on the page, the file is renamed and the page does not crash.

**Comment by nao-pon** [comment]
@frazjp65 Probably, duplicated to #1269. It was fixed.
