### ISSUE TITLE
Cannot hide directories under root volume with bind

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1403]
I am trying to hide certain folders under the root volume using a bind callback on the `parents` command.

I am using the following code:

```
public function check_access($cmd, &$result, $args, $elfinder)
	{
		$user_jobs = $this->job_model->get_jobs_by_user($this->aauth->get_user_id());

		$job_numbers = array();

		foreach ($user_jobs as $job)
		{
			$job_numbers[] = $job->job_number;
		}

		foreach ($result['tree'] as $i => $tree)
		{
            if ($i > 0) // ignore the first entry, as it is the root volume
            {
	            if (in_array($tree['name'], $job_numbers))
	            {
		            $result['tree'][$i]['hidden'] = 0;
	            }
	            else
	            {
		            $result['tree'][$i]['hidden'] = 1;
	            }
            }
		}
	}
```

It is successfully setting the value, but all folders are visible under the root volume, even ones with `hidden` set to `0`.

Seems like elFinder is not taking this options into account?

Options like `read`, `write` and `locked` work fine, but I want to hide the folders entirely.

**Comment by StudioJunkyard** [comment]
You can hide folders using the below in the connector.php file inside the roots array, the `folder|to|hide` is the list of folders to hide using the pipe character as a deliminator:
```PHP
            'attributes'=>array(
                array(
                    'pattern'=>'!^/folder|to|hide!',
                    'hidden'=>true
                )
            )
```

**Comment by paulcanning** [comment]
That pattern isn't a valid regex pattern, how on earth does it work?!

**Comment by StudioJunkyard** [comment]
Not sure about the bind callback, but regex can take many forms, and can have differences between languages. Not sure what they are using is strictly regex for that, but it works.

**Comment by paulcanning** [comment]
@nao-pon is there a reason why I cannot use the `hidden` attribute in a bind callback?

**Comment by nao-pon** [comment]
@paulcanning Please also be applied to the `open` command.

**Comment by paulcanning** [comment]
That is not a valid answer. I know I could use it, but I want to use the bind callback. Please look at adding in the hidden attribute. 

It makes zero sense that you can set read and write with bind, but not hidden.

**Comment by nao-pon** [comment]
I've confirmed. Hidden items not included in the volume driver response. Therefore, please remove the item you want to hide.

```php
bind => array('open tree' => array('hideCheck')),
```

```php
function hideCheck($cmd, &$result, $args, $elfinder, $volume) {
	if (! empty($result['files'])) {
		foreach($result['files'] as $i => $file) {
			if ($file['name'] === 'hidden') {
				unset($result['files'][$i]);
			}
		}
		$result['files'] = array_values($result['files']);
	}
	if (! empty($result['tree'])) {
		foreach($result['tree'] as $i => $file) {
			if ($file['name'] === 'hidden') {
				unset($result['tree'][$i]);
			}
		}
		$result['tree'] = array_values($result['tree']);
	}
}
```

**Comment by nao-pon** [comment]
By the way, There is a way to use `accessControl`.

```php
'roots' => array(
	array(
		'driver'        => 'LocalFileSystem',
		'path'          => '../files/',
		'accessControl' => 'access'
	)
);
```

```php
function access($attr, $path, $data, $volume) {
	if ($attr === 'hidden') {
		if (preg_match('#/hidden(?:/|$)#', $path)) {
			return true;
		}
	}
	return null;
}
```
