### ISSUE TITLE
Attribute patterns do not work correctly

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1404]
I have an attribute pattern as follows:

'attributes' => array(
						array(
							'pattern' => '/(123)/',
							'write' => false
						)
					)

With two folders, "123" and "qwerty123", the folder "123" should be read only.

But both folders are set to read only.

This is a valid regex pattern, as tested here: https://regex101.com/r/pV3rA5/1

**Comment by nao-pon** [comment]
@paulcanning PHP regex is PCRE. - http://php.net/manual/book.pcre.php

Pattern what you want is `'/^123/'`.

**Comment by paulcanning** [comment]
Argh, I tried that before and it was not working! now it is. Nvm.

**Comment by paulcanning** [comment]
Right, the solution you gave me does **not** work.

Using `/^123$/` as the pattern, and setting write to false and locked to true, neither attributes are set.

If I use `!^/123!` the attributes are correctly set.
