### ISSUE TITLE
Allow upload of .vcf Contact Card

### ISSUE THREAD

**Issue by northernlite69** [Studio-42/elFinder#1405]
Hi!  I've tried every mime type imaginable, but still failing to allow upload of a vCard.vcf standard text file.  Is this the fault of the server or incorrect Allow Upload mime type?

Thanks!

**Comment by nao-pon** [comment]
@northernlite69 First of all, please refer to the [Wiki](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadAllow). And, Questions, please ask in [stackoverflow](http://stackoverflow.com/questions/tagged/elfinder).
