### ISSUE TITLE
How to enable "Mount Network Volume"

### ISSUE THREAD

**Issue by huzaifa-khambaty** [Studio-42/elFinder#1407]
I am using version 2.1.11
"Mount Network Volume" Button is disabled. How can I enable it and have the functionality of Drop Box, Google Drive, FTP as working in live demo.

**Comment by paulcanning** [comment]
you have to add , for example, a root FTP volume in the connector, then the button is enabled (strange I know!)

**Comment by nao-pon** [comment]
Please read source code comment of connector.minimal.php-dist.

- https://github.com/Studio-42/elFinder/blob/89bbcab742122404c471d0898770956f871bc0ff/php/connector.minimal.php-dist
- for elFinder > 2.1.11 - https://github.com/Studio-42/elFinder/blob/master/php/connector.minimal.php-dist
