### ISSUE TITLE
Unable to use attribute options to change single file properties

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1408]
I want to target a single file, matching it's name, so I can set them to read only.

Using

```
array(
    'pattern' => "/^ExactFileName.txt$/",
    'write' => FALSE
)
```

This does not work.

I also tried `"!^ExactFileName.txt!"` for the pattern, as this pattern works for directories. It does not work for the single file.

**Comment by nao-pon** [comment]
@paulcanning Pattern matching is used full path.
