### ISSUE TITLE
can you add mount network drive http://mediafire.com/

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1409]
can you add mount network drive http://mediafire.com/  mange files in elfinder?

**Comment by nao-pon** [comment]
There is no plan at the moment. We would welcome the PR.

**Comment by CodeLyokotEAM** [comment]
I found useful site.

https://github.com/MediaFire/mediafire-php-open-sdk/blob/master/upload.php

**Comment by CodeLyokotEAM** [comment]
@nao-pon I found useful site.

https://github.com/MediaFire/
https://github.com/MediaFire/mediafire-php-open-sdk
