### ISSUE TITLE
Setting read access to false does not stop users downloading file

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1411]
Setting a files read access to false, whilst stopping you "opening" the file in elFinder and, if it was an image for example, viewing it in a popup windows, does NOT stop the user right clicking and selecting "download".

Ideally it should, seeing as if the user has no read access, they should not be able to view the file, ever.

Right now, they can simply download it and view it.

**Comment by paulcanning** [comment]
Ha, well this just gets better.

I disabled read and write access for a XML file, and elFinder let me download it.

If you then open it, it turns out to be the HTML output of the page elFinder is in.

Utter garbage.

Why is the download option even available?! And why is it downloading the HTML source?!

**Comment by nao-pon** [comment]
@paulcanning Thanks!
