### ISSUE TITLE
deny to drag & drop into folder avilable in places

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1413]
I try to drag & drop file into folder witch is available in places.But its deny.

![untitled](https://cloud.githubusercontent.com/assets/18566890/15449081/4857a356-1f91-11e6-9b8a-23a887b7d76b.png)

Also I try to drag & drop file into the original folder its allowed to drop.

![untitled](https://cloud.githubusercontent.com/assets/18566890/15449093/aabaf7be-1f91-11e6-88a8-fb733943626a.png)

**Comment by nao-pon** [comment]
@CodeLyokotEAM This is not a bug. It can be registered only folder to Places.
