### ISSUE TITLE
Icon Layout Problem with Nanohttpd on Android

### ISSUE THREAD

**Issue by TeamNuvolect** [Studio-42/elFinder#1414]
We are seeing an odd layout problem with Icon view in elFinder 2.1.9. The problem is easy to reproduce. Zip and upload the elFinder demo MIME-Types folder. Unzip the archive and note the stacked icons. The odd behavior is the same on Chrome, Firefox and Safari. 

elFinder is hosted on Android and either runs internally using a WebVew or externally from any browser on your WiFi LAN. You can try it yourself, search Google Play for "Media MicroCloud".

This is an early Beta release.  Feedback and suggestions welcome.

<img width="1034" alt="elfinder-mimetypes" src="https://cloud.githubusercontent.com/assets/19307825/15449334/aac33530-1f48-11e6-9748-fd9f3aaab6ac.png">

**Comment by nao-pon** [comment]
@TeamNuvolect Do you have the same problem in the [nightly builds](https://github.com/Studio-42/elFinder/archive/2.1.zip)?

**Comment by TeamNuvolect** [comment]
In elFinder-master, "css/elfinder.min.css" is missing.
<link rel="stylesheet" type="text/css" href="css/elfinder.min.css">

Yet in elFinder-2.1.7 and elFinder-2.1.9 the file is right where it should be.

**Comment by nao-pon** [comment]
Prease read README.md . Master branch has not been built. Please look at the [2.1 branch](https://github.com/Studio-42/elFinder/tree/2.1).

**Comment by TeamNuvolect** [comment]
Thanks for the tip, the 2.1 nightly branch has the same problem.  The problem seems to start with the "Presentation Tips.ppt" file. Looking at the HTML, the pattern changes on this file. There is a pattern of divs, 1 for each file.  When it gets to the Presentation Tips.ppt file, its div contains divs for all the files that are stacked under it. It seems divs for all of these files should be one level higher in order to continue the pattern.

![div pattern change](https://cloud.githubusercontent.com/assets/19307825/15468085/2520cb40-20b0-11e6-84fe-e3df7c23a2c5.png)

**Comment by nao-pon** [comment]
I do not know whether this correction is correct. Please check the nightly build. Do not forget to update the JavaScript cache.

**Comment by TeamNuvolect** [comment]
About this software is showing 2.1.11 (2.1-src Nightly: c9a66de), protocol version: 2.1 jQuery/jQuery UI: 1.12.0/1.11.4 and JavaScript cache is clear.

Exploring features, I found that the problem goes away when the Quicklook plugin is enabled, the icons all line up nicely.  I can't use Quicklook however, given all the files are on Android and not public. A standalone file viewer would make a nice addition BTW.

I can probably find a way to copy-paste the HTML if it will help.


![elfinder-about](https://cloud.githubusercontent.com/assets/19307825/15504035/ff0c2284-218a-11e6-856a-5e25175e3479.png)

**Comment by nao-pon** [comment]
What about newest nightly bae4125?

**Comment by TeamNuvolect** [comment]
Looks good, bae4125 works, problem solved!  I'll continue testing and let you know if I find anything else. Again, Nice Work!
