### ISSUE TITLE
Custom Icon for specific filetypes?

### ISSUE THREAD

**Issue by YanareKu** [Studio-42/elFinder#1417]
elFinder displays a Zip icon for .idml files, because it uses Zip compression.  Unfortunately, seeing a Zip icon confuses my users into thinking their idml file is now a zip file.  

If I create a custom icon for .idml - is there a way for me to change what icon is displayed for .idml files in elfinder?  Thank you.

**Comment by StudioJunkyard** [comment]
You can change the icons via the CSS styles.

**Comment by nao-pon** [comment]
@YanareKu Please try an option [`mimeMap`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#mimeMap).

```php
'mimeMap'         => array(
		'md:application/x-genesis-rom' => 'text/x-markdown',
		'md:text/plain'                => 'text/x-markdown',
		'markdown:text/plain'          => 'text/x-markdown',
		'css:text/x-asm'               => 'text/css',
		'ico:image/vnd.microsoft.icon' => 'image/x-icon',
		'csv:text/plain'               => 'text/csv',
		'm4a:video/mp4'                => 'audio/mp4',
		'oga:application/ogg'          => 'audio/ogg',
		'ogv:application/ogg'          => 'video/ogg',
		'idml:application/zip'         => 'application/octet-stream'
 	),
```

**Comment by YanareKu** [comment]
Thank you very much, nao-pon!  You answered so fast!

This and the answer to this issue [https://github.com/Studio-42/elFinder/issues/1436](url) gave me exactly what I needed. :)
