### ISSUE TITLE
missing select or getfile icon from toolbar in version 2.1.11

### ISSUE THREAD

**Issue by rajasharma27** [Studio-42/elFinder#1418]
Sir,
select or getfile icon missing in this version

**Comment by nao-pon** [comment]
I'm not sure. Can you explain in detail along with a screen shot?

**Comment by rajasharma27** [comment]
/**
	 * History object. Store visited folders
	 *
	 * @type Object
	 **/
	this.history = new this.history(this);
	
	// in getFileCallback set - change default actions on double click/enter/ctrl+enter
	
	if (this.commands.getfile) {
		if (typeof(this.options.getFileCallback) == 'function') {
			this.bind('dblclick', function(e) {
				e.preventDefault();
				self.exec('getfile').fail(function() {
					self.exec('open');
				});
			});

			this.shortcut({
				pattern     : 'enter',
				description : this.i18n('cmdgetfile'),
				callback    : function() { self.exec('getfile').fail(function() { self.exec(self.OS == 'mac' ? 'rename' : 'open') }) }
			})
			.shortcut({
				pattern     : 'ctrl+enter',
				description : this.i18n(this.OS == 'mac' ? 'cmdrename' : 'cmdopen'),
				callback    : function() { self.exec(self.OS == 'mac' ? 'rename' : 'open') }
			});


		} else {
			//delete this.commands.getfile;  
		}
	}

====================================================

//delete this.commands.getfile;  
just comment this getfile icon display in elfinder toolbar

**Comment by rajasharma27** [comment]
http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l1_RG93bmxvYWRz

not showing "Select File" arrow icon button in elFinder icon

**Comment by rajasharma27** [comment]
![image](https://cloud.githubusercontent.com/assets/16103829/15509538/7bb16a22-21f1-11e6-8a50-bf2173d99fbe.png)

**Comment by nao-pon** [comment]
Since the demo site does not specify a `getFileCallback` icon will not be displayed.

**Comment by rajasharma27** [comment]
but working in old version 2.1.7

**Comment by rajasharma27** [comment]
http://hypweb.net/elFinder-nightly/demo/tinymce/
working perfectly with your demo

but not working with my case

![image](https://cloud.githubusercontent.com/assets/16103829/15510829/b1e303e4-21f6-11e6-8ebd-546d4cf257cb.png)

**Comment by rajasharma27** [comment]
in version 2.1.7 working both ( Select Icon  or  contacts menu) , but both options not showing in 2.1.11 in my case

**Comment by nao-pon** [comment]
Please use an option [`getFileCallback`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#getFileCallback).

**Comment by rajasharma27** [comment]
thanks
