### ISSUE TITLE
On file upload, how can I get the parent directory?

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1421]
When uploading files, I need to get data about the parent directory, such as the name, so I can log the data in my database.

I am using a `bind` callback, on the `upload` command, to get the file details, but there is no information about the parent directory.

**Comment by nao-pon** [comment]
@paulcanning 
```php
function setToken($cmd, &$result, $args, $elfinder, $volume) {
	$parentPath = $volume->getPath($args['target']));
}
```

elFinder 2.1.12 or nightly required.

**Comment by paulcanning** [comment]
There is no 2.1.12 package available via composer

**Comment by nao-pon** [comment]
`composer require studio-42/elfinder:2.1.x-dev` to install nightly build.
