### ISSUE TITLE
File parth mismatch

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1422]
I use mobile server & my contender.minimal is

			'driver'        => 'LocalFileSystem',
			'path'          => '//storage/',
			'URL'           => dirname($_SERVER['PHP_SELF']) . '//storage/',

Driver &files load sussesfully.
But I try to open files in separate window its path is invalid.
Its path is like this "**http://localhost/elFinder-master/php//storage/NewFile.jpg**"
& browser said 404 file not found. The file real path is **//storage/NewFile.jpg**
& localhost Path is **//storage/sdcard0/www/**
Can you check it?

**Comment by nao-pon** [comment]
@CodeLyokotEAM What is correct URL(Scheme + URI)?

**Comment by paulcanning** [comment]
`$_SERVER['PHP_SELF']` fetches the lcoation of the script being run. Problem seems to be your code.

**Comment by nao-pon** [comment]
@CodeLyokotEAM How was it?

**Comment by CodeLyokotEAM** [comment]
I think its My problem.
Because the path is out side of localhost & it have't access in viva localhost but its only access viva php or some other codes.
 
I can resolve it for my server if path
 "http://localhost/elFinder-master/php//storage/NewFile.jpg"
 to
"http://localhost/elFinder-master/php/?//storage/NewFile.jpg"
(http://localhost/elFinder-master/php/?'path')

How I change it?

**Comment by nao-pon** [comment]
Please try `'URL' => ''` or don't set. It use the connector to file open.

**Comment by CodeLyokotEAM** [comment]
Thankz.
