### ISSUE TITLE
Confirm file upload, and add additional text on upload and in elFinder window?

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1424]
1. Is there a way to have the user confirm file uploads before they actually upload? This is especially useful for multiple uploads, as the user may accidentally add an incorrect file that needs removing form the queue
2. Is there a way to allow the user to add custom text (via input box) for a file, which can then be picked up in the `bind` callbacks?
3. Is there a way to let users edit custom data inside the elFinder window? Perhaps in the info popup? Or in the column view?

**Comment by nao-pon** [comment]
@paulcanning It is not equipped with their functions to elFinder. To equipped with those features require extend function of elFinder. Please try to ask in such StackOverFlow because it does not support its own function here.

**Comment by paulcanning** [comment]
I think having a modal to show a confirmation for upload should be a feature of elFinder.

**Comment by nao-pon** [comment]
I'm thinking that upload confirmation is no need. Because it can cancel or can remove the item. Excessive confirmation will deteriorate UX.
