### ISSUE TITLE
Mobile interface not loading

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1425]
the mobile version of Elfinder does not seem to load for me.

I am using the nightly release, and can see the touch CSS classes in the CSS files, but when I load my local project on my phone, I just get the desktop view.

No touch classes are added.

**Comment by nao-pon** [comment]
@paulcanning elFInder detect user device by `elFinder.UA.Mobile` & `elFinder.UA.Touch`. Please make sure not interfere with this work on your project.

```javascript
	/**
	 * User browser UA.
	 * jQuery.browser: version deprecated: 1.3, removed: 1.9
	 *
	 * @type Object
	 **/
	this.UA = (function(){
		var webkit = !document.uniqueID && !window.opera && !window.sidebar && window.localStorage && typeof window.orientation == "undefined";
		return {
			// Browser IE <= IE 6
			ltIE6:typeof window.addEventListener == "undefined" && typeof document.documentElement.style.maxHeight == "undefined",
			// Browser IE <= IE 7
			ltIE7:typeof window.addEventListener == "undefined" && typeof document.querySelectorAll == "undefined",
			// Browser IE <= IE 8
			ltIE8:typeof window.addEventListener == "undefined" && typeof document.getElementsByClassName == "undefined",
			IE:document.uniqueID,
			Firefox:window.sidebar,
			Opera:window.opera,
			Webkit:webkit,
			Chrome:webkit && window.chrome,
			Safari:webkit && !window.chrome,
			Mobile:typeof window.orientation != "undefined",
			Touch:typeof window.ontouchstart != "undefined",
			iOS: navigator.platform.match(/^iP(?:[ao]d|hone)/)
		};
```

**Comment by paulcanning** [comment]
I'm not interfering with any of that script.

Even in my browser, using Chrome tools to make the site appear as it would on mobile, my project just won't show the mobile view, but I can view your demo page on desktop, with Chrome tools, as a mobile page, and it works.

Is there anything else I can try? I need to support a mobile view!

**Comment by nao-pon** [comment]
Stand-alone elFinder is no problem, if there is a problem in your project, I think that there is a problem with the integration with your project.

Please check one by one what is the difference. And please tell me if there is a thing to be improved to elFinder.

**Comment by paulcanning** [comment]
Scripts in header

```
<link rel='stylesheet' href='//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css'>
<link rel='stylesheet' href='http://192.168.1.17/fileportal/vendor/studio-42/elfinder/css/elfinder.full.css'><link rel='stylesheet' href='http://192.168.1.17/fileportal/vendor/studio-42/elfinder/css/theme.css'><script src='//ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js'></script>
<script src='//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js'></script>
<script src='http://192.168.1.17/fileportal/vendor/studio-42/elfinder/js/elfinder.full.js'></script>
```

Client script

```
$(document).ready(function() {
	$('#elfinder').elfinder({
		url : 'http://192.168.1.17/fileportal/index.php/elfinder/connector/elfinder_init',
		soundPath: 'http://192.168.1.17/fileportal/vendor/studio-42/elfinder/sounds',
		rememberLastDir: false,
		defaultView: 'list',
		dateFormat: 'M d, y H:i',
		fancyDateFormat: '$1 H:i'
	});
});
```

No major differences, if any.

**Comment by nao-pon** [comment]
I do not know on our side about your project. Please let us know if you encounter similar trouble by the stand-alone specific options.

**Comment by paulcanning** [comment]
Point is, I am using the same JS and CSS files client side, but it doesn't work.Is there anyway to test the UA detection built into elFinder?

**Comment by nao-pon** [comment]
It is due to the CSS in my guess. Please try to disable non elFinder CSS.

**Comment by paulcanning** [comment]
I don't have any. See my code above, that's it.

**Comment by nao-pon** [comment]
How is JavaScript or HTML? Cause you can see if you changed to your implementation little by little from a normal state in a stand-alone.

**Comment by paulcanning** [comment]
My page source http://pastebin.com/PeqgizxJ

**Comment by paulcanning** [comment]
If you can explain exactly how elFinder figures out if you are on mobile, I may be able to start digging to find the issue

**Comment by paulcanning** [comment]
Working. The JS file had not been updated properly.

**Comment by paulcanning** [comment]
Nav bar is hiding itself, but the left side directory list doesn't hide itself, and I cannot swipe it away?

**Comment by paulcanning** [comment]
I updated to 2.1.12 (I was using 2.1.x-dev, but this did not grab 2.1.12?) and whilst using my desktop browser in mobile mode, both nav and side bar auto hide, but on my phone, only the nav bar does?

My phone is running the latest Chrome browser.
