### ISSUE TITLE
Open Folder hangs using Firefox

### ISSUE THREAD

**Issue by tx350z** [Studio-42/elFinder#1426]
Browsing to http://studio-42.github.io/elFinder/#elf_l2_Lw using FireFox 46.0.1 hangs on initial Open Folder. Browsing away from the page brings up the confirmation pop-up. When "Leave" is clicked an "Unable to connect to backend" error is displayed briefly.

Additional: I have the Vipre Internet Security plug-in for FireFox installed.

Everything seems to work OK on IE 11.

UPDATE: http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l1_Lw works OK on FireFox.

**Comment by nao-pon** [comment]
@tx350z I'm checked on Firefox 46.0.1 (Windows 7 64bit). It was no problem. Please check to disable any extensions.

P.S. http://studio-42.github.io/elFinder/ use CORS connecting. Perhaps Will your extension is blocking it.
