### ISSUE TITLE
Problem of empty holder achiving on zipdl

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1427]
Create New folder & open it. After open the folder Create Another new folder & This folder must empty. Now go back to Fist New Folder & right click and select download option. Open the zip file You can see the second folder shows like file (Not a folder). Can you Check it?

**Comment by nao-pon** [comment]
I checked, but it was no problem. I attach sample archive.
[test(Zip 2.32).zip](https://github.com/Studio-42/elFinder/files/285560/test.Zip.2.32.zip)
[test(ZipArchive).zip](https://github.com/Studio-42/elFinder/files/285561/test.ZipArchive.zip)

**Comment by CodeLyokotEAM** [comment]
Don' downlad after create zip. Only download right click folder & select downlad option.
I double check in my server & demo site its always same situation.

**Comment by nao-pon** [comment]
I got it. I'll fix it. Thanks!
