### ISSUE TITLE
Is it able to fetch(GET) filename only (don't want to display thumbnails) on ELFinder's display

### ISSUE THREAD

**Issue by helloooideeeeea** [Studio-42/elFinder#1430]
I have used elfinder on S3(aws).
When I opened elfinder's display,  Loading is too long.
if I can display filename only on Elfinder.
Is it able to?

thanks.

**Comment by nao-pon** [comment]
@helloooideeeeea Which volume driver do you using? Can you show us your connector configurations?

**Comment by helloooideeeeea** [comment]
@nap-pon
Thanks for quick response.
I'm using volume driver is flysystem.(https://github.com/thephpleague/flysystem)
and it is used FMEIfinderBundle(https://github.com/helios-ag/FMElfinderBundle) on Symfony2.8.
Is this a was good response ?

Just to be sure, I write FMElfinderBundle's settings on below.

```
fm_elfinder:
    instances:
        default:
            locale: %locale%
            editor: ckeditor
            path_prefix: "" 
            include_assets: true 
            connector:
                debug: true
                roots: 
                    aws_s3:
                        driver: Flysystem
                        url: http://s3-ap-northeast-1.amazonaws.com/xxxx/uploads/
                        path: uploads
                        flysystem:
                            type: aws_s3_v2
                            options:
                                aws_s3_v2:
                                    key: %aws_key%
                                    secret: %aws_secret%
                                    region: %aws_s3_region%
                                    bucket_name: xxxx
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif']
                        upload_deny: ['all']
                        upload_max_size: 4M
```

**Comment by nao-pon** [comment]
FMEIfinderBundle use [ElFinderPHP](https://github.com/helios-ag/ElFinderPHP). It is different to our elFinder. You should ask to FMEIfinderBundle.

Thanks.

**Comment by helloooideeeeea** [comment]
@nao-pon I'm sorry. thanks.
