### ISSUE TITLE
Can improve image editor?

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1431]
I found some php code for image edit in php

Opensource free codes
http://www.jpie.net/
http://www.amitpatil.me/php-and-ajax-image-editor/

**Comment by barryvdh** [comment]
There is also this for frontend: https://github.com/fengyuanchen/cropper
Which can be used to manipulate/crop/resize on the frontend, and send the cropped image.

Or you could do it serverside with a composer package like https://github.com/Intervention/image or https://github.com/avalanche123/Imagine

**Comment by nao-pon** [comment]
There is also a [elFinder 2.1_n](http://hypweb.net/elFinder-nightly/demo/2.1_n/#elf_l2_Lw) as one of the choices. 2.1_n is the image can be edited in pixlr.com.

**Comment by CodeLyokotEAM** [comment]
Its perfect but some users is't like third party web sites 
I think image editor is like this.
https://github.com/MattKetmo/darkroomjs

**Comment by lianee** [comment]
this pixlr integration works a treat, is there any plan to have it with the standard elFinder distribution?

**Comment by nao-pon** [comment]
@lianee It is difficult to incorporate third-party services to the main stream. We need to create a mechanism that allows we to edit the item by the plugins.

ref. #1449

**Comment by lianee** [comment]
I agree, front-end plugins would be great

**Comment by nao-pon** [comment]
I will accept elFinder's edit command other than text files. This will make JavaScript editors (such as [Adobe's Creative SDK](https://creativesdk.adobe.com/features/#/creative-tools.html)) available.
