### ISSUE TITLE
Basic Authentication using htaccess

### ISSUE THREAD

**Issue by tracyliu2084** [Studio-42/elFinder#1432]
In Basic Authentication Example, the user accounts are defined inside the script. Can elFinder check folder permission on web server, e.g using htaccess?

I set these in apache config
<Directory "/var/www/html/protected">
  AuthType Basic
  AuthName "Authentication Required"
  AuthUserFile "/etc/htpasswd/.htpasswd"
  Require valid-user

  Order allow,deny
  Allow from all
</Directory>

but the the file manager does not show any login prompts when I click protected folder

**Comment by nao-pon** [comment]
@tracyliu2084 elFinder read the file system directly. (Not the HTTP protocol) Therefore I think it's impossible that you want.
