### ISSUE TITLE
Can video file thumbnail default is the screenshot capture from the video?

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1433]
This plugin is great.

The only problem I encounter is , when I upload a video, after upload complete it is a video logo , unlike the case of image, it is the actual image thumbnail.

Therefore, I wonder are there any way to change the video file thumbnail? either it capture a frame of the video / customized to upload the thumbnail are ok

Thanks a lot for helping.

**Comment by nao-pon** [comment]
@leo1989work  I'll implement function to make thumbnail from the video file by server side command `ffmpeg`.

**Comment by nao-pon** [comment]
You can try on [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip). Thanks!

**Comment by leo1989work** [comment]
Thanks for help, one question , when I upload video e.g. sample^1.mp4 , It shows TypeError: Cannot read property 'phash' of undefined(…) , and there is no thumbnail, any ideas?

**Comment by nao-pon** [comment]
@leo1989work I was tested on demo site. It was no problem. Please try clear of browser cache.

**Comment by leo1989work** [comment]
I have replaced the old files , those PHP, javascript , CSS etc... Is that work by default or I need to write some code config for that? Thanks.

**Comment by nao-pon** [comment]
This works with the default settings. Create a thumbnail if available the ffmpeg on the server.

If you got a JavaScript error, please let me know the location by using the elfinder.full.js.

**Comment by leo1989work** [comment]
`        $ffmpeg = trim(shell_exec('type -P ffmpeg'));

        if (empty($ffmpeg)) {
            die('ffmpeg not available');
        } `

yes, tested the server not have ffmpeg installed, will further check after install. Thanks a lot !

**Comment by nao-pon** [comment]
The state of ffmpeg has been stacked in a session variable. Please try again confirmed with a new session when installed ffmpeg.
