### ISSUE TITLE
Multiple extra data in info dialog?

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1434]
As usual, the documentation just doesn't offer any help.

I currently have some extra data inserted into the info window using the Client API `commandOptions` as below:

```
commandsOptions : {
						info : {
							custom : {
								description : {
									label : 'Description',
									tpl : '<div class="elfinder-info-extra"><span class="elfinder-info-spinner"></span></div>',
									action : function(file, fm, dialog) {
										dialog.find('div.elfinder-info-extra').html(file.description || 'None');
									}
								}
							}
						}
					}
```

Now, is I have some more data, example, "File uploaded by User X", how can I add this to the `commandOptions` ?

Also, the above code, which came from the documentation examples, is more geared towards fetching the data from a method, I assume asynchronously. However, the extra data is added to the file results during the `open` command.

So how can I added the data, without using the action function? Or must I use the action function?

**Comment by nao-pon** [comment]
It can be processed in the action as well as the description by assigning the data in the file object in the open command.

If the document is not enough to combine with its own project elFinder, you will need to read and understand the program source. Here it can not be supported for that matter.
