### ISSUE TITLE
getFileCallback not work when two Instance Integrate on same page

### ISSUE THREAD

**Issue by rajasharma27** [Studio-42/elFinder#1435]
sir, getFileCallback not work when two Instance Integrate on same page

<script type="text/javascript" charset="utf-8">
			// Documentation for client options:
			// https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
			$(document).ready(function() {
				$('#elfinder').elfinder({
					url : 'php/connector.minimal.php'  // connector URL (REQUIRED)
					// , lang: 'ru'                    // language (OPTIONAL)
				});
				
				$('#elfinder2').elfinder({
					url : 'php/connector.minimal.php',  // connector URL (REQUIRED)
					// , lang: 'ru'                    // language (OPTIONAL)
					getFileCallback: function (file,fm) {
					}
				});
			});
		</script>
	</head>
	<body>

		
		<div id="elfinder"></div>
		<div id="elfinder2"></div>

**Comment by nao-pon** [comment]
@rajasharma27 I'm not sure. Next example work well.

```javascript
$(function() {
	$('#elfinder').elfinder({
		// Connector URL
		url : 'php-dev/connector.minimal.php',

		// Callback when a file is double-clicked
		getFileCallback : function(file) {
			alert(file.url);
		}
	});
	$('#elfinder2').elfinder({
		// Connector URL
		url : 'php-dev/connector.minimal.php',

		// Callback when a file is double-clicked
		getFileCallback : function(file) {
			alert(file.url);
		}
	});
});
```

```html
<body>
	<div id="elfinder"></div>
	<div id="elfinder2"></div>
</body>
```

**Comment by rajasharma27** [comment]
Sir,
when using getFileCallback in first Instance and second without getFileCallback  then work is perfectly
but when first instance without getFileCallback   and second instance using with getFileCallback   then not work.

**Comment by nao-pon** [comment]
OK, I got it. I'll fix this bug.

Thanks!

**Comment by rajasharma27** [comment]
thanks sir
