### ISSUE TITLE
The sorting : base on file type ,  is not working as expected

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1437]
Hi developers,

In the file manager there is a sorting base on file type function, 

the ordering is like this:

doc -> pdf -> xls -> ppt -> docx

because it is based on digit and 4 character for docx?

If ideally can group doc and docx together ? Same case for xls with xlsx etc..as it seems make more sense. 

Thanks a lot for your effort.  

![test](https://cloud.githubusercontent.com/assets/14356169/15706033/3a14067c-2824-11e6-8595-b6a4c52f7402.png)

**Comment by nao-pon** [comment]
@leo1989work Sort of File type (kind) will be evaluated in the MIME type. So if you want to sort by file extension, use the client configuration `sortRules`.

e.g.
```javascript
$('#elfinder').elfinder({
	// Connector URL
	url : 'php/connector.minimal.php',

	sortRules: {
		kind: function(file1, file2){
			return file1.name.split('.').pop().toLowerCase().localeCompare(file2.name.split('.').pop().toLowerCase());
		}
	}
});
```
