### ISSUE TITLE
Can add Confirm navigation panel?

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1439]
![ugggggntitled](https://cloud.githubusercontent.com/assets/18566890/15715821/a062eace-283d-11e6-99ac-5c4293604215.png)

i try edit image in elfinder& in my mistake its close. Because the page close in elfinder while open image editor.can you add it?

**Comment by dleffler** [comment]
FYI, A way to remove the 'Page/Document has Expired' message in the browser when trying to go 'back' from a page in the php code

```
ini_set('session.cache_limiter','public');
session_cache_limiter(false);

**Comment by nao-pon** [comment]
@CodeLyokotEAM Already, elFinder show the confirm dialog of window closing when it has notify dialog. Do you want show confirm dialog always?

**Comment by CodeLyokotEAM** [comment]
In use image editor in elfinder its reload&close confirme dialog is not availabe.I saw another functions in use reload &close is confirme dialog is available.
