### ISSUE TITLE
Hide the next /prev button if there is no more next/prev item in preview

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1441]
Hi developer, the preview is working fine, only one suggestion:

when there is no more next/prev item, are there any indicator to "dim" the button, you may refer to the screenshot. There is total 3 items and no more next item, the next button can be shaded ?

Thanks for helping.

![preview](https://cloud.githubusercontent.com/assets/14356169/15741393/197e42f6-28ec-11e6-8dcc-1f44ac3df2cf.png)

**Comment by nao-pon** [comment]
@leo1989work :+1:

**Comment by leo1989work** [comment]
Thanks a lot for your work, some problems when there is one file 

1) the next button is still there.
2) when I close the preview and open again, the preview content is disappeared

please take a look if you have spare time, thanks 

![image 6](https://cloud.githubusercontent.com/assets/14356169/15815178/da63a31c-2bfd-11e6-96da-75083e3a1acf.png)

**Comment by nao-pon** [comment]
@leo1989work 

> 1) when there is only one file , the next button is still there.

It was already fixed @2e43f5370b958c143500ac680308070203136fe6

> when I close the preview and open again, the preview content is disappeared

I fixed @d97359aa5c0015b2d98607f5e4d2ce8fd96e170b

Thanks! :+1:

**Comment by leo1989work** [comment]
sorry , just find one problem:

it work fine if  I open the preview box and press the next / prev button.

However, if I resize the preview box window , the next / prev button will not work, there is no JS error but nothing happen after clicking on the next/prev button

**Comment by leo1989work** [comment]
I have downloaded the latest night build and the problem is exist

**Comment by nao-pon** [comment]
@leo1989work There is no problem in the [demo site](http://studio-42.github.io/elFinder/). Probably I think that there is a cause to your theme or integrated environment.
