### ISSUE TITLE
File Info Displays the incorrect date

### ISSUE THREAD

**Issue by eternelpanic** [Studio-42/elFinder#1444]
A minor bug where File info always displays yesterday.

The bug is in elfinder.js
Line 4852 needs to change from: 
`format = ts >= this.yesterday`
to: 
`format = ts >= (this.yesterday * 1000)`

And same with line 4880 from:  
`return ts >= this.yesterday`
to: 
`return ts >= (this.yesterday * 1000)`

This is because the timestamp (ts) is in miliseconds, while ts.yesterday is not.

**Comment by eternelpanic** [comment]
Sorry, on further investigation - it may be my backend that handing through ms timestamps - so this might not be relevant for everyone...

If it is though, line 4841 needs to change to:
`date = new Date(ts);`

A smarter way might be to check the timestamp and format it appropriately so that it can handle either seconds or milliseconds depending on what is presented.

**Comment by nao-pon** [comment]
@eternelpanic Volume driver (backend) must return a UNIX timestamp as `ts`. Please correct the volume driver side.

Thanks.
