### ISSUE TITLE
qout and &

### ISSUE THREAD

**Issue by orpat** [Studio-42/elFinder#1446]
Hello!
I use your file manager and is very happy. But I have an error when saving files after editing. All quotes are stored as &quot, and sign & save as &amp. etc. What could be the problem? Thanks for the help.

**Comment by nao-pon** [comment]
@orpat Which version are you using? There aren't any problems in [demo site](http://studio-42.github.io/elFinder/).

**Comment by orpat** [comment]
I used version 2.0, I try to upgrade to 2.1. But the problem persists. I found your plugin sanitayzer. I understand he has to solve my problem? If this is true, I do not quite understand how to connect it. The fact that I do not use connector.php. The data for the connection specified in javascript. Where do I prescribe URL, language, toolbar ... And how to connect the plug-in through the Client configuration options I did not understand. There is a point "сommandsOptions" but did not find the description of how to connect through this plugin

**Comment by nao-pon** [comment]
I am guessing that you are integrated with some other systems. Perhaps this is not a elFinder problems. Please re-open if there is a similar problem in stand alone elFinder.

PS. Probably sanitizer plugin will not be to your help.

**Comment by orpat** [comment]
I changed the connection method. Now login, password, host, and I pass through html:
			$(document).ready(function() {
				$('#elfinder').elfinder({
					//url : '/servers/control/getftp/<?php echo $server['server_id']  ?>'  // connector URL (REQUIRED)
					url : '/elFinder/php/connector.minimal.php',
					//lang: 'ru',                    // language (OPTIONAL)
					customData : {
					host: '<?php echo $server['location_ip'] ?>',
					user: 'gs<?php echo $server['server_id']  ?>',
					pass: '<?php echo $server['server_password'] ?>',
					}
				});
			});
The connector I have prescribed the following settings:
'driver' => 'FTP',
			'host'   => $_GET['host'],
			'user'   => $_GET['user'],
			'pass'   => $_GET['pass'],
			'port'   => '21',
			'mode'   => 'passive',
			'path'          => '/',			// path to files (REQUIRED)
				    'timeout'       => 20,
	    'owner'         => true,
	    'tmbPath'       => '.tmb',
	    'utf8fix'       => true,
            'tmbCrop'       => false,
            'tmbBgColor'    => 'transparent',
            'accessControl' => 'access',
            'acceptedName'  => '/^[^\.].*$/',
            'disabled'      => array('extract', 'archive', 'mkdir', 'netmount'),
            'tmbSize'       => 128,
	    'tmpPath'       => '',
	    'dirMode'       => 0755,
	    'fileMode'      => 0644,
	    'rootCssClass'  => 'elfinder-navbar-root-ftp'
When I rename a file or folder with quotes problem and sign & no. But there was another. I can not upload new files and modify existing ones. I get an error: Invalid backend configuration.
Readable volumes not available. 
But I can delete, rename, copy files and folders. If I point out these connections only in the connector, then everything works fine. This error may be due to what?

**Comment by nao-pon** [comment]
@orpat File upload uses `POST` method. So you will fix with `$_REQUEST`.

```php
'host' => $_REQUEST['host'],
'user' => $_REQUEST['user'],
'pass' => $_REQUEST'pass'],
```

**Comment by orpat** [comment]
Thank you very much! Everything is working.
