### ISSUE TITLE
Can you add reading word & excel file in elfinder?

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1449]
Can you add reading (+edit) word & excel & other office file in elfinder?

Found useful site.
https://github.com/PHPOffice

**Comment by nao-pon** [comment]
@CodeLyokotEAM elFinder will need to be a mechanism that can be edited just not other types of file text file to allow the plug-in format.  It is a future challenge.

**Comment by CodeLyokotEAM** [comment]
Its ok. Keep it up.

https://github.com/OfficeDev/office-js-docs

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Editing using Zoho Editor is available in elFinder 2.1.30 or later. And, with 2.1.40 or later, it is possible to preview using Microsoft Office Viewer.
