### ISSUE TITLE
Hide folder, but still make opening folder possible

### ISSUE THREAD

**Issue by wolfgangihloff** [Studio-42/elFinder#145]
I nearly achieved my hack to have a folder that is accessible by trash button but not listed in the tree, I modified updateTree to omit my .archive folder like this:

```javascript
else {
							if (dir.hash=='l1_LmFyY2hpdmU') {
								parent.append(html).hide();
							  continue;
						    }
```
However that seems not working too well since its seems to be stuck in a loop, since requests to connector.php are continuously sent out. However it achieves my goal of removing it from the directory tree. How would I go about valid removal from this, but not getting it stuck in the orphans loop. The hide() does not work here.

**Comment by nao-pon** [comment]
ref.  #129
