### ISSUE TITLE
Can mount origion mounted usb pen drive as ftp drive?

### ISSUE THREAD

**Issue by phtsaibb** [Studio-42/elFinder#1451]
USB Pen drive have mounted to the OS and can be access.
I want to have a command icon to add this mounted point as mount net drive.
Does anybody have do this function?
Thanks.

**Comment by nao-pon** [comment]
@phtsaibb If you want to mount as an FTP drive, you need to be able to access from the FTP server to the USB device.

**Comment by phtsaibb** [comment]
Maybe you misunderstand my meaning. I can manual mount the usb drive to elfinder through the 'roots' setting. If this manual mount can be like the net drive mount (as FTP or Google Drive), it will be more convenient.

**Comment by nao-pon** [comment]
I got it. It is easy. But it should not be used in any public area. It will be **_vulnerable of security_**.

**client configuration**
```javascript
commandsOptions : {
	netmount : {
		localfilesystem : {
			name : 'LocalFileSystem',
			inputs: {
				host     : $('<input type="hidden" value="localhost"/>'),
				path     : $('<input type="text" value="/"/>')
			}
		}
	}
}
```

**connector.php**
```php
// regist network mount volume
elFinder::$netDrivers['localfilesystem'] = 'LocalFileSystem';

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```
