### ISSUE TITLE
Help with Authorization

### ISSUE THREAD

**Issue by Gokujo** [Studio-42/elFinder#1452]
Hey guys,
i don't have https for this manager and I tried the files which you gave for basics, but I cannot login with simple login and pass. it want that I retype those data but without any effect

**Comment by nao-pon** [comment]
@Gokujo I am guessing that you are to try a sample of the basic authentication. Basic authentication does not have a log-out of the mechanism during the session. To log out, such as closing the browser, it requires destruction of the session.

If you need a mechanism of logout, there is a need to integrate with any login/logout system, but does not provide such an example.

**Comment by Gokujo** [comment]
hey. to test that i have to log in. but i can't. this is the problem. maybe, there some requirements to php?

**Comment by nao-pon** [comment]
I thought that you are trying [BasicAuthExample](http://studio-42.github.io/elFinder/#elf_l1_QmFzaWNBdXRoRXhhbXBsZQ). was it different?

**Comment by Gokujo** [comment]
nope, that is it.
look: http://file.nasche-reiseburo.de
login and pw: user

**Comment by nao-pon** [comment]
Did you added `'user' => 'user'` into `$auths`?

**Comment by Gokujo** [comment]
Yes

**Comment by nao-pon** [comment]
Please make sure the session is working properly.

**Comment by Gokujo** [comment]
ok, how can I find out?

**Comment by nao-pon** [comment]
Perhaps in your server `$_SERVER [ 'PHP_AUTH_USER']` and `$_SERVER [ 'PHP_AUTH_PW']` has not been assigned. Please perform the server set to be assigned them.

**Comment by Gokujo** [comment]
okay, it didn't helped either... thx for closing
