### ISSUE TITLE
Cancellation of when closes dialog by clicking (x) icon at file editing

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1453]
I edit the txt file in elfinder & mistake I click close icon (x) & prompt the txt file save dialog& I want to re-edit text without closing it. I click close icon (x)  in prompt dialog & auto close txt editing window without saving it.

**Comment by nao-pon** [comment]
@CodeLyokotEAM This is not a bug. I believe it is rare to accidentally click the Close button （x）. Since the editor is open in the Ctrl + E after closing the editor, I think it good enough.

**Comment by CodeLyokotEAM** [comment]
I got it.
