### ISSUE TITLE
Problem with office/pdf preview 2.0

### ISSUE THREAD

**Issue by raffaelescarcella** [Studio-42/elFinder#1454]
Hi,
i have again the same [problem](https://github.com/Studio-42/elFinder/issues/1447).
now i copy my project online and the problem isn't to work with localhost.
You can test yourself the problem:  [elFinder](http://elfinder1.altervista.org/).

**Comment by nao-pon** [comment]
@raffaelescarcella elFinder 2.0 is not support office document preview. And pdf preview.require the Adobe Acrobat browser plugin.

I checked on [your elFinder](http://elfinder1.altervista.org/) with the Adobe Acrobat browser plugin. It's work fine.
