### ISSUE TITLE
Upload progress customisation

### ISSUE THREAD

**Issue by tscholz** [Studio-42/elFinder#1456]
Hi,

is there a way to customise the upload progress notification? Instead of the '100%' I'd like to show a message.

**Comment by nao-pon** [comment]
@tscholz You can use client configuration [handlers](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#handlers).

e.g. (use [kamranahmedse/jquery-toast-plugin: Highly customizable jquery plugin to show toast messages](https://github.com/kamranahmedse/jquery-toast-plugin "kamranahmedse/jquery-toast-plugin: Highly customizable jquery plugin to show toast messages"))

```javascript
handlers : {
	upload : function(e, fm) {
		$.toast({
			text: " It was uploaded successfully completed.", // Text that is to be shown in the toast
			heading: 'Uploaded', // Optional heading to be shown on the toast
			showHideTransition: 'fade', // fade, slide or plain
			allowToastClose: true, // Boolean value true or false
			hideAfter: 3000, // false to make it sticky or number representing the miliseconds as time after which toast needs to be hidden
			stack: 5, // false if there should be only one toast at a time or a number representing the maximum number of toasts to be shown at a time
			position: 'top-right', // bottom-left or bottom-right or bottom-center or top-left or top-right or top-center or mid-center or an object representing the left, right, top, bottom values
			
			bgColor: '#00c131',	 // Background color of the toast
			textColor: '#ffffff',  // Text color of the toast
			textAlign: 'center',  // Text alignment i.e. left, right or center
		});
	}
},
```

**Comment by tscholz** [comment]
@nao-pon

Thank you very much for your quick response. The handler is called after the upload has finished, thats too late for our use case.

Our app is processing uploads inside/at the end of the file upload request. Currently an upload shows progress but for the user it seems to hang when reaching 100% because of our upload processing inside the request. That's why I'm looking for a way to customise the upload progress bar to show a message when reaching 100% or so. Do you have any suggestions how to do that?

I know the cause of the issue is the way our app works, but I can't change it's behaviour right now. On the other hand moving a large file after upload from the servers local file system to a network storage may also cause the behaviour I'm describing. So I'm looking for a workaround to show the user what's going on.

**Comment by nao-pon** [comment]
Progress notification of server side has been stacked in #1357. However, I think that this support will be heavy work in the formulation of specifications and technical support.

We are looking for collaborators.

Thanks!
