### ISSUE TITLE
Context menu, add link?

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1458]
I need to add a link in the context menu, that will take a user to a different page, based on properties of the file e.g the files name, or its parent directory.

I am following the example [here](http://stackoverflow.com/questions/16604842/adding-a-custom-context-menu-item-to-elfinder/) but I am unsure how to actually add the link.

**Comment by nao-pon** [comment]
It is a issue of your project, not the issue of elFinder.
