### ISSUE TITLE
Mobile view, side nav does not autohide

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1459]
As per the title. I downloaded 2.1.12 and whilst the top toolbar does autohide, the side nav does not.

Not only does it not autohide, I cannot swipe it closed either.

**Comment by paulcanning** [comment]
I got it to autohide, but now when I swipe it open, I cannot swipe it closed

**Comment by paulcanning** [comment]
https://github.com/Studio-42/elFinder/blob/2.1.12/js/elfinder.full.js#L2765

Going through step by step, with a break point here, sliding the nav bar, right to left, `navhide` is set, but not triggered.

Pretty sure the math is off.

on my phone, lastX = 168.17799377441406, x = 161.81300354003906, node width = 330

So

```
if (Math.abs(168.17799377441406 - 161.81300354003906) > Math.min(200, (330 * .5))) {
    alert('success');
} else {
    alert('fail');
}
```

Alert shows "fail". Hence the navbar does not hide when swiping right to left.

**Comment by nao-pon** [comment]
Please take the distance to swipe long. Because it wait the horizontal scrolling.
