### ISSUE TITLE
Column widths in list view?

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1460]
How can we control column width in list view?

I am adding a custom column, and I'd like to ive it a larger width then it has, and minimise the wdiths of the size and date columns.

**Comment by nao-pon** [comment]
It is difficult to control the current. I'm planning to be able to control the CSS to give the name of the class to the TD element.

**Comment by paulcanning** [comment]
Is this ready?

**Comment by nao-pon** [comment]
@paulcanning Please check out [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip) or [demo site](http://studio-42.github.io/elFinder/#elf_l1_Lw).
