### ISSUE TITLE
Set default files/folder on (script) init

### ISSUE THREAD

**Issue by Yves-K** [Studio-42/elFinder#1462]
Wouahou... Such a great tool !

Is ther a way to :
1. set default directory on init (script init not connector init)
2. set files as selected on init (script init for instance passing pathes array)

**Comment by nao-pon** [comment]
@Yves-K You can use an option [`startPathHash`](https://github.com/Studio-42/elFinder/blob/c6c0e90633e92b2696b612360866a612f29f4168/js/elFinder.options.js#L453-L459) to set initial open folder.

And example to auto select on initial open.
```javascript
var elfinderInstance = $('#elfinder').elfinder({
	url : 'php/connector.php',
	startPathHash : 'l1_Lw'
}).elfinder('instance');

elfinderInstance.one('open', function() {
	var hashes = ['l1_SW1hZ2Vz', 'l1_QmFzaWNBdXRoRXhhbXBsZQ'];
	$.each(hashes, function(i, hash) {
		$('#'+elfinderInstance.cwdHash2Id(hash)).trigger('select');
	});
});
```

You can get folder hash from browser location hash, And You can get items hash from HTML Elements  in browser developer tool Or next PHP script.
```php
<?php

include_once '../php/autoload.php';

// Your connector $opts
$opts = array(
	'roots' => array(
		array(
			'driver' => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
			'path'   => '../Demo/',       // path to files (REQUIRED)
		),
	)
);

$elfinder = new elFinder($opts);
$volume = $elfinder->getVolume('l1_'); // Volume driver ID + Increment integer + '_'
$hash = $volume->getHash('/Images');

echo $hash;
```
