### ISSUE TITLE
Please Add Wiki

### ISSUE THREAD

**Issue by bbfriend** [Studio-42/elFinder#1463]
Hi!
flat-file CMS:  [CMSimple_XH](http://www.cmsimple-xh.org/) 's elFinder_plugin  is  [complete](http://cmsimpleforum.com/viewtopic.php?f=12&t=10524), please register to Modules of Wiki.
Thank you

flat-file CMS :CMSimple_XH 
https://github.com/bbfriend/elfinder_xh

**Comment by nao-pon** [comment]
@bbfriend Sounds good! :+1:  Please edit [3rd party connectors, plugins, modules · Studio-42/elFinder Wiki](https://github.com/Studio-42/elFinder/wiki/3rd-party-connectors%2C-plugins%2C-modules "3rd party connectors, plugins, modules · Studio-42/elFinder Wiki") by yourself. And please close this issue after completion.

Thanks!

**Comment by bbfriend** [comment]
@nao-pon  
I did not know.It can be edited in my own.　:sweat_smile:
Now edited.
Thank you
