### ISSUE TITLE
How to us elfinder.chmod from UI

### ISSUE THREAD

**Issue by gebrerv** [Studio-42/elFinder#1465]
Hi,

I want to give some of our users the possibility to change the file permissions of files they have uploaded.

In elFinder.class.php i found that there is a protected command chmod, in document Client Server API 2.1 I also also found 
 "uiCmdMap"        : { "chmod" : "perm" }, //  Command conversion map for the current volume (e.g. chmod(ui) to perm(connector))

This looks to me as if there might be a way to give users the possibility to change permissions of files via the elfinder UI, but i found no hint how to achieve this

My connector.php options contain  'allowChmodReadOnly' => true and 'StatOwner'     => true,
elfinder.html uioptions contain 
toolbar : [ ['quicklook', ... 'chmod'] ]

contextmenu : {
            files  :  [ 'getfile', ... ,'chmod']

Pressing refresh shows for very short time an empty icon at the end of the toolbar, contextmenu apparently is not different.

How to make command chmod to appear in the UI ? 

Thanks in advance

**Comment by nao-pon** [comment]
@gebrerv In LocalFileSystem and FTP driver `uiCmdMap` is not required. Please check your [`commands`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#commands) option.

**Comment by gebrerv** [comment]
Hi Naoki,

Thanks for your very fast response. Unfortunately adding chmod to the options.commands did not solve the issue.
I only found a little additional hint whats going on : In internet explorer, pressing refresh, i can see for a very short time the icon in the toolbar, it is the forth image in the file toolbar.png ( orange coloured star), possibly class .elfinder-button-icon-chmod     { background-position: 0  -48px; }.

Neither in toolbar nor in contextmenu chmod is shown.

**Comment by nao-pon** [comment]
Please double check that 'allowChmodReadOnly' and 'StatOwner' contains in volume roots (each volumes) options.

**Comment by gebrerv** [comment]
Hi Naoki,

I did some debugging and found three things that maybe bugs and one error caused by missing php module posix.  I use elFinder-master from 2016-06-13 15:14



1)     Documentation says that one has to set StatOwner to true, cause StatOwner by default is false and disables command chmod.



In elFinderVolumeDriver.class.php , line 739 statOwner is checked instead of Statowner. (lower case s)

if (empty($this->options['statOwner'])) {

                                   $this->disabled[] ='chmod';

                       }

Solution :  changed the option in connector.php to use statOwner.


2)     elfinder.src.html  contains no link to file js/commands/chmod.js ,

Solution : loaded this file



Now the button appears in toolbar, but remains disabled.



3)     js/commands/chmod.js , line  53, in function this.getstate contains statement

self.checkstate(this.files(sel), this cause error in javascript console : “self.checkstate is no function” , Chrome 51



Solution : change self.checkstate to this.checkstate.

The error disappears, but button is still disabled.



4)     this.checkstate has returned false, cause statement return (f.isowner && f.perm && isPerm(f.perm) && (cnt == 1 || f.mime != 'directory')) ? f : null;

returns null. Reason is that f.isowner is false, caused by undefined function posix_getuid() , missingPHP module posix.



Solution : Installed module php-posix.



Now chmod apparently works.

Thanks for Your hints , it would be nice if You could check whether the things I found are really bugs and incorporate the changes in the actual release

Best regards Gerhard

Von: Naoki Sawada [mailto:notifications@github.com]
Gesendet: Mittwoch, 15. Juni 2016 02:33
An: Studio-42/elFinder
Cc: gebrerv; State change
Betreff: Re: [Studio-42/elFinder] How to us elfinder.chmod from UI (#1465)


Please double check that 'allowChmodReadOnly' and 'StatOwner' contains in volume roots (each volumes) options.

**Comment by nao-pon** [comment]
@gebrerv Thanks a lot! I'll fix it. But I can't found 'StatOwner'(uppercase S) in documents. Please tell me where it is.

**Comment by gebrerv** [comment]
Hi Naoki,

sorry, seemingly I copied Statowner from somebody else’s example. I checked the documents and can find only statOwner , not Statowner, so the documents are ok (-:

regards Gerhard

Von: Naoki Sawada [mailto:notifications@github.com]
Gesendet: Mittwoch, 15. Juni 2016 13:13
An: Studio-42/elFinder
Cc: gebrerv; Mention
Betreff: Re: [Studio-42/elFinder] How to us elfinder.chmod from UI (#1465)


@gebrerv<https://github.com/gebrerv> Thanks a lot! I'll fix it. But I can't found 'StatOwner'(uppercase S) in documents. Please tell me where it is.
