### ISSUE TITLE
Check the size quota before upload  

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1467]
```
        elfinder.upload = function (files) {
            var file_size;
            
            //get file size
        
            //check quota
            $.post("<?= site_url("api/check_quota"); ?>", {files_size: files_size}, function (res) {
                var obj = $.parseJSON(res);
                if (obj.result === "success") {
                    return elfinder.transport.upload(files, elfinder);
                } else {
                    elfinder.error('File quota reach limit, fail to upload');
                    return $.Deferred().reject();
                }
            });
        };
```

I would like to have an ajax checking before the upload file(s), currently I have already override the upload action, the problem is how to manipulate the files object. That means, how to get the total upload file(s) size from the files object?

Thanks a lot for helping.

**Comment by nao-pon** [comment]
@leo1989work You can check files object with `elfinder.log(files)` in browser console. files object has a property `type`. That is 'files', 'data', or 'html'. You need to do the processing by their types. (Size acquisition of html type might be difficult)

It's processed by [uploads.checkFile](https://github.com/Studio-42/elFinder/blob/47f49700ea7231aa3a8837ae3ff93ffc13bf65be/js/elFinder.js#L3187-L3371) In elFinder.js.

**Comment by leo1989work** [comment]
the type is data 

![image](https://cloud.githubusercontent.com/assets/14356169/16070685/b509ffe0-3309-11e6-9263-bb48ceb7d85f.png)


would you mind explain briefly about the how to use the checkFile?

thanks

**Comment by nao-pon** [comment]
You will need to code the program such as `checkFile`. But we can not support to more detail. Please ask to StackOverFlow or any agent as a business.

**Comment by leo1989work** [comment]
Thanks, one last question , now I can grab the total upload file size, however, the override upload function seems does not allow to use ajax for checking, it return 

elfinder.full.js:17958 Uncaught TypeError: Cannot read property 'fail' of undefined

due to sync problem

My code is like this:

```
        elfinder.upload = function (files) {
            var total_byte = 0;
            var uploads = files.files;
            var upload_list = uploads.files;

            $.each(upload_list, function (index, entry) {
                total_byte += entry.size;
            });

            $.post("<?= site_url("API/check_quota"); ?>", {upload_size: total_byte}, function (res) {
                var obj = $.parseJSON(res);
                if (obj.result === "success") {
                    return elfinder.transport.upload(files, elfinder);
                } else {
                    elfinder.error('Quota reach limit');
                    return $.Deferred().reject();
                }
            });
        };
```

Thanks a lot

**Comment by nao-pon** [comment]
@leo1989work Maybe fixes with
```javascript
        elfinder.upload = function (files) {
            var total_byte = 0;
            var uploads = files.files;
            var upload_list = uploads.files;
            var dfd = $.Deferred();

            $.each(upload_list, function (index, entry) {
                total_byte += entry.size;
            });

            $.post("<?= site_url("API/check_quota"); ?>", {upload_size: total_byte}, function (res) {
                var obj = $.parseJSON(res);
                if (obj.result === "success") {
                    dfd = elfinder.transport.upload(files, elfinder);
                } else {
                    elfinder.error('Quota reach limit');
                    dfd.reject();
                }
            });

            return dfd;
        };
```
(Not tested)

**Comment by leo1989work** [comment]
Thanks, tested but no luck. When I drag the file to upload it doesn't upload , but no error message , and the check_quota is called. Just nothing happen after success. I tried the error condition and it success pop up the error message.  Any idea for that? 
it seems the dfd is return before assign dfd = elfinder.transport.upload(files, elfinder);?

thanks

**Comment by leo1989work** [comment]
the reason may be :As of jQuery 1.8, the use of async: false with jqXHR ($.Deferred) is deprecated

**Comment by leo1989work** [comment]
seems async : false work fine, for reference
            $.ajax({
                type: "POST",
                url: '<?= site_url("API/check_quota"); ?>',
                data: {upload_size: total_byte},
                async: false,
                success: function (res) {
                    var obj = $.parseJSON(res);
                    if (obj.result === "success") {
                        return elfinder.transport.upload(files, elfinder);
                    } else {
                        elfinder.error('Quota limit reach');
                        return dfd.reject();
                    }
                },
                error: function () {
                }
            });

**Comment by taylankasap** [comment]
For future readers: If you try to log the files object and see that there are no files this it doesn't mean there are no files. It just means what devtools already told you. Hover to the blue info icon.

In other words in `elfinder.upload` method do this `console.log(files.files.files)` instead of `console.log(files)` if you want to see the files in the console.

**Comment by dogmaxpeppe** [comment]
> @leo1989work Maybe fixes with
> 
> ```js
>         elfinder.upload = function (files) {
>             var total_byte = 0;
>             var uploads = files.files;
>             var upload_list = uploads.files;
>             var dfd = $.Deferred();
> 
>             $.each(upload_list, function (index, entry) {
>                 total_byte += entry.size;
>             });
> 
>             $.ajax({
>                 type: 'POST',
>                 dataType: 'json',
>                 url: '<?= site_url("API/check_quota"); ?>',
>                 data: {upload_size: total_byte}
>             }).done(function (res) {
>                 if (res.result === 'success') {
>                     dfd = elfinder.transport.upload(files, elfinder);
>                 } else {
>                     dfd.reject();
>                     elfinder.error('Quota reach limit');
>                 }
>             }).fail(function() {
>                 dfd.reject();
>                 elfinder.error('Quota check error');
>             });
> 
>             return dfd;
>         };
> ```
> 
> (Not tested)
> 
> (rewrite with $.ajax ref. #1501)

I try to post here because I'm facing the same problem. I write a code like this:

`elfinderInstance.upload = function(files) {
                var totSize = 0;
                var dfd = $.Deferred();

                if ( files && files.input && files.input.files ) {
                    $.each(files.input.files, function (key, file) {
                        if ( file )
                            totSize += file.size;
                    });

                    totSize = totSize / 1048576;

                    $.ajax({
                        url: "urlToCheckCurrentSize",
                        method: "GET",
                        async: false,
                        success: function(data) {
                            if ( (Number(data) + totSize) <= 30 )
                                dfd = elfinderInstance.transport.upload(files, elfinderInstance);
                            else {
                                elfinderInstance.error("{#maximum_size_reached_folder#}");
                                dfd.reject();
                            }
                        },
                        error: function (data) {
                            console.log(data);
                        }
                    });
                }

                return dfd;
            };`

But nothing happens. It appears only Loading file window on top-right side of the File Manager, ma no errors appear, nothing appears. I also tried async: false, but didn't work for me
