### ISSUE TITLE
Display by grid view , but the icon is not the list view one

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1468]
![image](https://cloud.githubusercontent.com/assets/14356169/16039114/a96597b2-325a-11e6-8bb4-c8e31a99f5c7.png)

![image](https://cloud.githubusercontent.com/assets/14356169/16039230/380e6b4c-325b-11e6-99eb-db08163d8fee.png)

By default, it is display as grid view , but the icon is grid view one , which should be list view one.
But after I switch between grid / list one time, then it return to normal. 

After checking the css , at the beginning it is elfinder-button-icon-view instead of elfinder-button-icon-view-list, is it the cause of the problem and how to fix it? 

Thanks

**Comment by nao-pon** [comment]
@leo1989work I think this is the theme of the issue. Please re-open if there is a similar problem with the default theme.
