### ISSUE TITLE
Preview videos in "avi" , "mpg" and "wmv" format

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1469]
Currently the preview is very smooth and work fines for MP4 files. It is implemented by the HTML5 video? As when I test the avi , mpg or wmv file it does not play the video. One suggestion is enhance the support format to avi, mpg and wmv . e.g. use ffmpeg to stream for it, thanks.

**Comment by nao-pon** [comment]
@leo1989work Video that can be previewed in elFinder only HTML5 videos. Other types of video are possible if there is a plug-in to the browser. There are no plans to add functionality to stream conversion on the server side.

Thanks.
