### ISSUE TITLE
How to set only not allow to upload file on root folder

### ISSUE THREAD

**Issue by ghost** [Studio-42/elFinder#1471]
From the document , I can set the permission for different root (volume) . 

e.g. in the connector.php

```
'uploadDeny' => array('all'),
'uploadOrder' => array('allow','deny')
```

that will disable the upload function for the whole volume. The problem is , how to set only the root folder not allow to upload file? And set custom message for that e.g. 'The root folder is not for upload file' etc... 

Thanks for help

**Comment by leo1989work** [comment]
Great. The test link in that link is exactly what I would like to achieve.

Only one problem, for the code mentioned 
```
function function access($attr, $path) {
    if (rtrim($path, '/') === '/ABSOLUTE_PATH_TO/elfinder_root/files') {
        return strpos(basename($path), '.') === 0       // if file/folder begins with '.' (dot)
            ? !($attr == 'read' || $attr == 'write')    // set read+write to false, other (locked+hidden) set to true
            : ($attr == 'read' || $attr == 'locked');   // set read+locked to true, other (write+hidden) set to false
    }
}

```

It seems this is just for handle 

1)  .tmb , .quantue files will hidden and locked
2) other files will be locked 

How does it related to not allow upload only in root folder? Thanks for helping

**Comment by nao-pon** [comment]
@leo1989work I edited [linked post](https://github.com/Studio-42/elFinder/issues/1457#issuecomment-225169495). It has been deleted the unnecessary code.

**Comment by leo1989work** [comment]
thanks, the problem is , for an empty root folder:

 var_dump(rtrim($path, '/')); inside the access function , only show this two folder:

string(53) "/home/in002/public_html/popular/uploads/file/544/.tmb"
string(60) "/home/in002/public_html/popular/uploads/file/544/.quarantine"

I can set locked for those two folder , but not the root folder it self

it should be something like :
```
 if (rtrim($path, '/') === ''/home/in002/public_html/popular/uploads/file/544") {
             return ($attr == 'read' || $attr == 'locked');  
}
```

but in fact the access function does not include the root folder itself, how to fix that? 

Thanks

**Comment by leo1989work** [comment]
one problem left , now I successfully locked the home folder, however, is it allow to create directory (only not allow create / copy / upload files), that means, the root folder should only allow folder type. Thanks
