### ISSUE TITLE
Multi non-english files downloaded as an archive, filename error after extracted at Windows

### ISSUE THREAD

**Issue by phtsaibb** [Studio-42/elFinder#1472]
Select multi files (filenames are traditional chinese) to download will download as a zip file.
After downloaded the zip file and extract at my Windows 7, the filename become nonsense.

This also happen when download a folder with chiense filenames files inside.

My elFinder is setup at a linux system.

**Comment by nao-pon** [comment]
@phtsaibb This is by design, not a bug. File names are encoded in UTF-8. Please use the extracting tool that corresponds to the UTF-8.

**Comment by phtsaibb** [comment]
@nao-pon Could you suggest such extracting tool? I use Windows default zip viewer and 7z, but both fail.

**Comment by nao-pon** [comment]
@phtsaibb What about [PeaZip | Free archiver, free RAR TAR ZIP files utility](http://www.peazip.org/)?
