### ISSUE TITLE
Hide the file extension and also not allow to rename the extension

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1476]
Right now the user see the file extension and rename it, I wonder are there any options to disable this feature , to prevent user carelessly rename the extension.

Thanks, really appreciate your help.

**Comment by nao-pon** [comment]
You can normalize the user input in the [bind option](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind) of the connector.

It is a simple example
```php
function myRenamePre($cmd, &$args, $elfinder, $volume) {
	$target = $args['target'];
	$newName = $args['name'];
	if ($org = $volume->file($target)) {
		$orgInfo = pathinfo($org['name']);
		$newInfo = pathinfo($newName);
		if ($orgInfo['extension'] !== $newInfo['extension']) {
			$args['name'] = $newInfo['filename'] . ($orgInfo['extension']? '.' . $orgInfo['extension'] : '');
		}
	}
}
```
```php
'bind' => array('myRenamePre'),
```

**Comment by ghigio2000** [comment]
@nao-pon is the above solution still valid? I get an error 500 from the server trying to use this solution.
Isn't there any new option to hide the file extension from the list view? Thanks for your help.
