### ISSUE TITLE
List view column width in bootstrap 3

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1477]
![image](https://cloud.githubusercontent.com/assets/14356169/16146240/a49eb068-34af-11e6-92bd-e96be48341d0.png)

The elfinder so far work perfectly with the bootstrap 3, the only problem is , if the folder only have directory , then the file size column in list view will cut some part of that, would you mind expand a little for that therefore can show all the wordings inside the column?

Thanks. Have a nice day

**Comment by leo1989work** [comment]
I browse the site using 1920px resolution

**Comment by nao-pon** [comment]
@leo1989work What about CSS `.elfinder-cwd table td { min-width: 3em; }`?

**Comment by leo1989work** [comment]
yes , ok now , thanks a lot
