### ISSUE TITLE
Problem In move colums in mobile browser

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1479]
In move custom column on list view in mobile devices ,
Columns move corecctly.
But in coner columns move to second column (while second column not visible in list) this list can't move to it. because column list isn't scroll automatic.

Also I try to move column in mobile device (a long tap in column) its open list of tool.

Also I try to move column before the last column to last column its impossible. But its can move last column to another place.

**Comment by nao-pon** [comment]
@CodeLyokotEAM Auto scroll does not. Please refer to the pre-scroll with your own. Also, it is a specification of the context menu in the long tap is displayed.

Thanks!
