### ISSUE TITLE
Thumbnails not loading with 2.1.12 (work with 2.1.11)

### ISSUE THREAD

**Issue by buckett** [Studio-42/elFinder#1480]
Our connector is returning thumbnail URLs along the lines of:

http://localhost:8080/elfinder-servlet/connector?cmd=tmb&target=A_L290aGVyL1NjcmVlbiBTaG90IDIwMTYtMDYtMDggYXQgMDkuMTcuMDIucG5n

for each file. Under 2.1.11 these images get loaded, but under 2.1.12 the request never gets made. The `tmb()` function always returns false for us.

**Comment by buckett** [comment]
I'm guessing this got introduced in #1344 as that looks to be what has changed here recently.

**Comment by nao-pon** [comment]
@buckett Thanks for your reports! :+1:
