### ISSUE TITLE
elFinder is very slow when loading 6000+ images

### ISSUE THREAD

**Issue by nbulusanjr** [Studio-42/elFinder#1483]

**Comment by nao-pon** [comment]
@nbulusanjr elFinder's performance will degrade as the number of items increases. We are waiting for the proposal to improve the performance at any time.

Items in the holder exceeds the thousands and will be quite slow. We are aware of it.
- http://studio-42.github.io/elFinder/#elf_l1_YV9sb3Rfc2FtcGxl

**Comment by nbulusanjr** [comment]
Can we implement a different approach wherein metadata(filename,mime,size,timestamp) of the file will be saved on a Sqllite database and the file will be still saved on the local filesytem although I'm not very familiar with PHP.
