### ISSUE TITLE
elfinder height can not

### ISSUE THREAD

**Issue by ExtremeYu** [Studio-42/elFinder#1484]

**Comment by ExtremeYu** [comment]
![qq 20160620132745](https://cloud.githubusercontent.com/assets/16620268/16183976/f2203e32-36ea-11e6-9e6a-767edf8fed30.png)

**Comment by ExtremeYu** [comment]
![qq 20160620132914](https://cloud.githubusercontent.com/assets/16620268/16183986/0fd01c04-36eb-11e6-8275-3acd5903e3f4.png)
this is the  image showing the consequence when change the value of elfinder height

**Comment by nao-pon** [comment]
@ExtremeYu option `height` allow number only. There is typo in code comments. I'll fix it.

**Comment by nao-pon** [comment]
Thanks! :+1:

**Comment by ExtremeYu** [comment]
it’s means that the elfinder does not support auto-height？

**Comment by nao-pon** [comment]
That's right. It need JavaScript adjustment.

**Comment by ExtremeYu** [comment]
oh that‘s too bad..... is there any way  to let elfinder adjust height automaticly ？

**Comment by nao-pon** [comment]
e.g. fit to window size
```javascript
var elfinderInstance = $('#elfinder').elfinder({
	width: '100%',
	height: height: $(window).height() - 20
}).elfinder('instance');

// fit to window.height on window.resize
var resizeTimer = null;
$(window).resize(function() {
	resizeTimer && clearTimeout(resizeTimer);
	resizeTimer = setTimeout(function() {
		var h = parseInt($(window).height()) - 20;
		if (h != parseInt($('#elfinder').height())) {
			elfinderInstance.resize('100%', h);
		}
	}, 200);
});
```

**Comment by ExtremeYu** [comment]
![qq 20160620203433](https://cloud.githubusercontent.com/assets/16620268/16194296/6f5f0492-3726-11e6-857b-d7577127e097.png)

**Comment by arnisjuraga** [comment]
I noticed today, that using `height: '70%',` in client config works. `70%` is then converted to pixels automatically uppon window load. 
Is this officially supported? Wiki says, that height must be `number` in pixels: https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#height

**Comment by nao-pon** [comment]
@arnisjuraga Yes, recent versions now accept the "%" designation. The wiki will be fixed.

Thanks!
