### ISSUE TITLE
column bug

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1486]
goto this link 
http://studio-42.github.io/elFinder/#elf_l2_Lw

reset column width & reload the page
&scrolldown the bottem.
You can see like this.

![image](https://cloud.githubusercontent.com/assets/18566890/16197057/2a10b4ba-371e-11e6-9530-4267b549f7d8.png)

its mismatch the columns.

**Comment by nao-pon** [comment]
@CodeLyokotEAM It seems no problem.
![elfinder-list-scroll](https://cloud.githubusercontent.com/assets/1412630/16198042/5ba69f96-373f-11e6-9e4d-69216af4c5f1.gif)

**Comment by CodeLyokotEAM** [comment]
its work correct in small window.
But maximize the chrome window & adjust work space to see all the columns & try it.

**Comment by CodeLyokotEAM** [comment]
also columns bar little bit up for good interface.

![untitled](https://cloud.githubusercontent.com/assets/18566890/16200370/ae516150-372a-11e6-97a8-a084611388a1.png)

**Comment by CodeLyokotEAM** [comment]
also another bug found.
doable click the name bar & scroll down you can see some files & folders are missing in the list.

**Comment by CodeLyokotEAM** [comment]
http://studio-42.github.io/elFinder/#elf_l2_TmV3Rm9sZGVyIDE
I check & its same happening.
can you check thees bugs?

**Comment by nao-pon** [comment]
OK, I got it! I'll fix it.

Thanks!
