### ISSUE TITLE
Permission for allow create directory , not allow create / upload / paste file

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1487]
From the doc it mentioned I can set permission in root opts

'accessControl' => 'access'

And write a custom permission option

```
function access($attr, $path) {
    if (rtrim($path, '/') === '/ABSOLUTE_PATH_TO/elfinder_root/files') {
        return strpos(basename($path), '.') === 0       // if file/folder begins with '.' (dot)
            ? !($attr == 'read' || $attr == 'write')    // set read+write to false, other (locked+hidden) set to true
            : ($attr == 'read' || $attr == 'locked');   // set read+locked to true, other (write+hidden) set to false
    }
}
```

The $attr == 'read' || $attr == 'locked' is readable only, which lock the roots and not allow to write files, but also the directory , the problem is , are there any way to allow write dir , but not allow write files? 

Thanks  for helping

**Comment by dleffler** [comment]
Why allow someone to create a new directory and not be able to use it...defies the unix permissions logic...e.g., the permissions used to create the folder are inherited by the new folder and it's (future) contents???

**Comment by leo1989work** [comment]
the logic is , 
e.g. folder A is root folder, and folders inside folder A can share to the other user (have implemented)
 ,  but since only folder share is allowed, the root folder doesn't need to upload files/ copy files , so I would like to find some workaround to disable the file operation at that folder, only allow folder operation

**Comment by nao-pon** [comment]
@leo1989work This is not possible in elFinder. However, on the back-end level made possible by the custom driver that meet this request.

**Comment by leo1989work** [comment]
thanks for reply. would you mind explain briefly about how to make that custom driver?

**Comment by nao-pon** [comment]
e.g. (Just a hint only. Not tested)
```php
class elFinderVolumeMyLocalFileSystem extends elFinderVolumeLocalFileSystem
{
	public function mkfile($dst, $name) {
		if ($this->root === $this->decode($dst)) {
			return false;
		}
		return parent::mkfile($dst, $name);
	}

	public function paste($volume, $src, $dst, $rmSrc = false, $hashes = array()) {
		if ($this->root === $this->decode($dst)) {
			return false;
		}
		return parent::paste($volume, $src, $dst, $rmSrc, $hashes);
	}

	public function upload($fp, $dst, $name, $tmpname, $hashes = array()) {
		if ($this->root === $this->decode($dst)) {
			return false;
		}
		return parent::upload($fp, $dst, $name, $tmpname, $hashes);
	}
}
```
