### ISSUE TITLE
How to detect exist roots

### ISSUE THREAD

**Issue by phtsaibb** [Studio-42/elFinder#1495]
Follow issue #1451, we can add any root at the nav. tree. Then how to prevent adding an existed root? 
If I can find each root at the nav. tree, I think I can avoid it. But I did not familiar with the code, please somebody help. Thanks.

**Comment by nao-pon** [comment]
@phtsaibb You can get netvolumes config with `$this->session->get('netvolume', array())` in volume driver.

Extends the volume class. e.g. case of  #1451(LocalFileSystem)
```php
class elFinderVolumeMyLocalFileSystem extends elFinderVolumeLocalFileSystem
{
	public function netmountPrepare($options) {
		$netVolumes = $this->session->get('netvolume', array());
		foreach($netVolumes as $nv) {
			if ($nv['protocol'] === $options['protocol'] && $nv['host'] === $options['host']) {
				if (strpos($options['path'], $nv['path']) === 0) {
					return array(
						'exit'  => true,
						'error' => 'Parent folder is already mounted.'
					);
				}
			}
		}
		return $options;
	}
}
// register as netmount drive
elFinder::$netDrivers['localfilesystem'] = 'MyLocalFileSystem';
```
