### ISSUE TITLE
Quick look and thumbnail bug

### ISSUE THREAD

**Issue by pflind** [Studio-42/elFinder#1496]
I found these two bugs in elFinder-2.1.12, under OS X 10.11.5 and PHP 5.4.42.

When invoking Quick look in Safari 9.1.1 the popup is empty and cannot be closed. The browser becomes unresponsive and is ready to crash.

When mounting a second root the custom thumbnail path is ignored (this bug is also present in 2.0 rc1).

**Comment by tnichols86** [comment]
See if you can upgrade your version I use 7.0.7 and it works fine

**Comment by nao-pon** [comment]
@pflind Is a quick look bug related to #1478? And Please explain more details of custom thumbnail path problem. e.g. your configuration etc...

**Comment by nao-pon** [comment]
Since the reaction is not to close it.
