### ISSUE TITLE
img-edit dialog layout disordered when resizing window

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1498]
I edit image & I goto image rotate panel. 
It user interface is not correct in mobile browsers.

**Comment by nao-pon** [comment]
@CodeLyokotEAM I tested on [demo site](http://studio-42.github.io/elFinder/#elf_l1_RXhhbXBsZXMvVmlkZW9z). It seems no problems.

http://hypweb.net/elFinder-nightly/demo/Demo/Examples/Videos/rotate%20android%205.1.1%20chrome.mp4

**Comment by CodeLyokotEAM** [comment]
Goto "test here/bugatti chiron.jpg" & rotate
![screenshot_2016-06-30-19-42-27](https://cloud.githubusercontent.com/assets/18566890/16491368/48b1168c-3efb-11e6-833e-1a94a7b9d171.png)

**Comment by CodeLyokotEAM** [comment]
Also in edit window drag&drop upper&down you can see work space upper toobar is auto show & hide.

**Comment by nao-pon** [comment]
@CodeLyokotEAM I got it. I'll fix it.
