### ISSUE TITLE
The upload dialog does not close if override the upload event with handler

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1501]
The below screen cap is the upload dialog

![image](https://cloud.githubusercontent.com/assets/14356169/16550182/df1157c8-41d9-11e6-9a1c-0dca6c8662c4.png)

The problem is , it does not close after the upload is completed.

If I override like the code below, it works fine and just closed after upload completed:

```
        elfinder.upload = function (event) {
            return elfinder.transport.upload(event, elfinder);
        };
```

However, If I use ajax before the upload , and override the code like this, the dialog will not close after upload complete (but the file is successfully uploaded)

```
       elfinder.upload = function (event) {
            var dfd = $.Deferred();

           // ....ajax checking before upload
           $.ajax({
                    type: "POST",
                    url: '<?= site_url("API/check_quota"); ?>',
                    data: {upload_size: total_byte},
                    async: false,
                    success: function (res) {
                        var obj = $.parseJSON(res);
                        if (obj.result === "success") {
                            return elfinder.transport.upload(event, elfinder);
                        } else {
                            elfinder.error('Quota exceed');
                        }
                    },
                    error: function () {
                    }
                });

            return dfd;
        };
```

Any callback I need to manually handle / how to fix that?

Thanks a lot

**Comment by nao-pon** [comment]
@leo1989work I rewritten #1467 [comment](https://github.com/Studio-42/elFinder/issues/1467#issuecomment-226474613).
