### ISSUE TITLE
Customize the folder permission in either server/ client config

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1502]
There are several folder like this:

upload/admin/folder1
upload/admin/folder2
upload/admin/folderABC

etc...

For those folders under admin folder, I would like to have the following permission:

rename - not allow
copy - not allow
cut - not allow
delete - not allow

upload file - allow
delete file - allow
copy/paste file inside folder - allow 

As the file operation is allow by default, what I need to achieve is to disable the rename , copy , cut , delete ...

How can I achieve that (in either server / client approach) ? , thanks

**Comment by nao-pon** [comment]
@leo1989work It is duplicate to #1487.

**Comment by atulk101992** [comment]
I am getting error while creating new Folder in Elfinder with azure server using Laravel, but its allow me to create new Folder when i used Elfinder with s3 and locar driver using, so can anyone Please help me to solve this or please give any suggestion to solve this issue
