### ISSUE TITLE
can you add navigate files in keyboard letters?

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1503]
windows can navigate folders or files pressing first letter in keyboard current folder.
Can you add this future to el-finder ?

**Comment by nao-pon** [comment]
@CodeLyokotEAM This is difficult because elFinder include a lazy loading. You can use the incremental search instead on elFinder >= 2.1.13.  Incremental search can experience in the [demo site](http://studio-42.github.io/elFinder/).
