### ISSUE TITLE
After the Disable real file path from being shown

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1507]
After the Disable real file path from being shown,
Right click folder & goto get info.
Click 'link' & you can see its shows 'File not found'
Can I list files in folder?
(Because outside server files can only manage through php. So its may not available real server path.& I want to manage files[listed in files and folders] in virtual path elfinder provided.)

Re:
I search in github ' file manager in php/js' that list isn't included elfinder.

**Comment by nao-pon** [comment]
@CodeLyokotEAM link to the elFinder manegaer url with folder hash is OK?
