### ISSUE TITLE
problem with names

### ISSUE THREAD

**Issue by luisgazui** [Studio-42/elFinder#1508]
Hi, I make a correction on elfinder.full.js to preview files and folders with special characters if you are interesting in that correction I can give it to you my mail is luisgazui@gmail.com thanks you

**Comment by nao-pon** [comment]
@luisgazui Please send pull request to master branch. I will consider from a look at its contents.

Thanks!

**Comment by nao-pon** [comment]
I will close it. However, PR is always welcome.
