### ISSUE TITLE
How to lock specific subdirectories?

### ISSUE THREAD

**Issue by juanmaussa** [Studio-42/elFinder#1509]
Hi! 
I have the following folder structure:
root
   Folder2015
      Sub1
      Sub2
   Folder2016
      Sub1
      Sub2

I want to lock the Sub1 and Sub2 of Folder2016 but the names are equal to Folder2015 subdirectories.

If I use the expression:

'attributes' => array(
    array(
        'pattern' => '/Sub1|Sub2/',
         'read'    => true,
         'write'   => true,
         'hidden' => false,
         'locked'  => true
     ),
)

The subdirectories of Folder2015 and Folder2016 are locked but I need Folder2015 and all its subdirectories active.
any idea?
Thx!

**Comment by nao-pon** [comment]
@juanmaussa Please see [PCRE Pattern Syntax](http://php.net/manual/reference.pcre.pattern.syntax.php). e.g.  `'pattern' => '/Folder2016\/(?:Sub1|Sub2)/',` or `'pattern' => '/(?<!Folder2015)\/(?:Sub1|Sub2)/',` is OK.

**Comment by juanmaussa** [comment]
@nao-pon Thanks for your help!
