### ISSUE TITLE
Strange behavior for uploads when setting path dynamically

### ISSUE THREAD

**Issue by ColbySargent** [Studio-42/elFinder#1511]
Hi,
First of all - great work & thank you! elFinder has really helped an online system I've been developing!

But I have hit an issue:
My system has a directory of folders, each made for different products.
I'm trying to set the path so it opens elFinder on the specific product's folder - without making the entire directory available / showing at all.
Currently in the client config, I'm setting customData to pass on the path it should start from.
Using this data in the connector config however, is where my problem's are. I've tried a few different things, and here's what happens with each:

1) Hard Coding a String.
`'path' => '../../../../path/to/folder', //in connector config`
    If I do this, everything works perfect & as expected

2) Using the $_GET request
`'path' => '../../../../'.$_GET["startPath"], //in connector config`
    Connects fine, can create, rename & delete files/folders. But when trying to upload something, I receive the error: `'Invalid backend configuration. Readable volumes not available.'`

3) setting a variable as the $_GET request
`$startPath=$_GET["startPath"];`
`'path' => '../../../../'.$startPath, //in connector config`
    Connects fine, can create, rename & delete files/folders. Also files show when uploaded - but are not actually uploaded, so it can not be used at all and when the view is refreshed, its gone again.

`$_GET["startPath"]==='path/to/folder'` is true

with debug on, there is a slight difference between 1) & 3) in the add/upload events. In the returned object.
the 'removed' array has 1 string (the hash of the uploaded file) in method 1),
the 'removed' array has 2 strings (both the hash of the uploaded file) in method 1),

Not sure if this is anything from my side, or elFinder itself - any help appreciated!
Thanks

**Comment by nao-pon** [comment]
@ColbySargent elFinder use POST method for upload function. Please try
```php
$startPath = $_SERVER['REQUEST_METHOD'] === 'POST'? $_POST['startPath'] : $_GET['startPath'];
```

**Comment by ColbySargent** [comment]
Working perfect, thanks!
