### ISSUE TITLE
Stable build CSS problem

### ISSUE THREAD

**Issue by Stiropor** [Studio-42/elFinder#1512]
Downloading stable build from http://studio-42.github.io/elFinder/, following installation (though I've set up and used elFinder before) and opening elfinder.html doesn't quite work correctly:

![screen shot 2016-07-08 at 10 27 13](https://cloud.githubusercontent.com/assets/365876/16681763/fc2329ac-44f6-11e6-923f-f68b1f802cca.png)

After changing CSS file from .min to .full it works, must be some problem with minimizing CSS. This problem is not new, I wanted to update elFinder to newer version few months ago and had the same issue, but didn't have time to find the problem.

**Comment by nao-pon** [comment]
@Stiropor I've cheeked with Chrome 51, Firefox 47, edge 25 and IE11. There are no problems.

**Comment by Stiropor** [comment]
Weird, I tested with latest Chrome, Chrome Canary (dev), Firefox 47, no IE on this machine though. I tested again with 2.1.13, works like a charm now. If I notice it again I'll let you know. Thanks for response :)
