### ISSUE TITLE
The new version - update Polish language

### ISSUE THREAD

**Issue by Chaffinch** [Studio-42/elFinder#1513]
Browsing the repositories:
https://github.com/Studio-42/elFinder/blob/master/js/i18n/elfinder.pl.js
I noticed that the file is,very outdated :-((
I decided to upgrade to the latest version:
https://github.com/Studio-42/elFinder/blob/master/js/i18n/elfinder.LANG.js  ->> version 2016-06-30

So the question.
Are you interested this new version?
Best Regards
Bogdan

**Comment by nao-pon** [comment]
@Chaffinch Of course yes, I recommend to use [translation tool](http://studio-42.github.io/elFinder/tools/langman/#2.1:pl).

Thanks!

**Comment by Chaffinch** [comment]
Hi Naoki
Allow me to add a file are ready :-)). Perhaps, it will be easy to read. Link to my server:
http://www.krynica.malopolska.pl/elfinder.pl.zip
Best Regards
Bogdan

**Comment by nao-pon** [comment]
I merged it. Thanks! :+1:

**Comment by Chaffinch** [comment]
Update elfinder.pl.js
Correction translation/phrases
https://github.com/Chaffinch/elFinder/blob/master/js/i18n/elfinder.pl.js

**Comment by nao-pon** [comment]
@Chaffinch It was some of the items revert to English. Is it OK? - https://github.com/Chaffinch/elFinder/commit/0d917b65a69b4e29a9c7af9bfada4dd99a709b85

**Comment by Chaffinch** [comment]
I noticed in elfinder.pl.js,items marked in red.I translated English to Polish
Mount network volume
Reset column width	
Move
Volume
Mounting network volume	
Unmounting network volume e.t.c
http://studio-42.github.io/elFinder/tools/langman/
That's all :-)))
So look at my:
http://krynica.malopolska.pl/elfinder2115/elfinder.src.html#elf_l1_Lw

**Comment by nao-pon** [comment]
@Chaffinch Would you make Pull Request by http://studio-42.github.io/elFinder/tools/langman/#2.1:pl ?

Procedure will be displayed when you click the "Make It!" Button after editing it in langman.

**Comment by Chaffinch** [comment]
I do not know why, but I can not see translations

line 134: 'cmdnetmount'  : 'Mount network volume', // added 18.04.2012 
to
'cmdnetmount'  : 'Zamontuj wolumin sieciowy', // added 18.04.2012   :-((

So I have a request.Could you to change phrases: 
Mount network volume
to
Zamontuj wolumin sieciowy 
In my is correctly :-))  line 134:
https://github.com/Chaffinch/elFinder/blob/master/js/i18n/elfinder.pl.js

Thank you very much for your help.
Have a nice day

**Comment by nao-pon** [comment]
@Chaffinch There are two items about netmount.

- L.134 `'cmdnetmount' : 'Mount network volume', // added 18.04.2012`
- L.182 `'ntfnetmount' : 'Zamontuj wolumin sieciowy', // added 18.04.2012`

in English
- `'cmdnetmount' : 'Mount network volume', // added 18.04.2012`
- `'ntfnetmount' : 'Mounting network volume', // added 18.04.2012`

What translation for  `cmdnetmount`?

**Comment by Chaffinch** [comment]
English
'cmdnetmount' : 'Mount network volume', // added 18.04.2012 
Polish
'cmdnetmount'  : 'Zamontuj wolumin sieciowy', // added 18.04.2012
English
'ntfnetmount' : 'Mounting network volume', // added 18.04.2012
Polish
'ntfnetmount' : 'Montaż woluminu sieciowego', // added 18.04.2012

Thx 
Bogdan

----- Original Message -----

**Comment by nao-pon** [comment]
I done! Thanks! :+1:
