### ISSUE TITLE
external archivers can be tricked into unintended actions with filenames starting with dash

### ISSUE THREAD

**Issue by neex** [Studio-42/elFinder#1514]
When a file name passed to external archiver command starts with a dash, it will be interpreted as a command line option. It can lead to unexpected behaviour, including execution of arbitrary commands (with tar).

Steps to reproduce:

1. Create empty files with names `--info-script=sh script.sh` and `-L10`, file `script.sh` containing commands to be executed, and `padding.bin` with size at least 10kbytes (contents doesn't matter).
    
    This step can be easily done by unpacking an archive containing all files listed above.
2. Select files `--info-script=sh script.sh`, `-L10` and `padding.bin` and choose "Create archive -> TAR archive" in context menu.
3. `script.sh` will be executed. It happens because function `makeArchive` internally constructs command like `tar -cf archive.tar padding.bin -L10 "--info-script=sh script.sh"`. That means "create a multivolume tar archive containing file `padding.bin` with maximum volume size of 10 bytes, executing command `sh script.sh` at the end of creating each volume.

**Comment by nao-pon** [comment]
@neex Thanks for your report. :+1:
