### ISSUE TITLE
Root directory for files

### ISSUE THREAD

**Issue by Anhellian** [Studio-42/elFinder#1516]
Hello,
I have some problem, i´am trying to chagne root folder in connector.minimal.php
`$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '/home/users/sportisimo/sportisimo.cz/web/pub',                 // path to files (REQUIRED)
			'URL'           => 'http://localhost/sportisimo.cz/pub', // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		)
	),`
and it will end on this error.
"Invalid backend configuration.
Readable volumes not available."
I´am using wamp2 on C:\Wamp2 and have alias to D:\work\www\sportisimo.cz

**Comment by nao-pon** [comment]
@Anhellian Maybe, the set value of the `path` is incorrect.

It is `'path' => 'D:\\work\\www\\sportisimo.cz\\pub'` ?
