### ISSUE TITLE
Possible JS injection in filename

### ISSUE THREAD

**Issue by vongruenigen** [Studio-42/elFinder#1518]
We're using elFinder as a frontend for our backend store of files together with a custom version of the ``elFinder::Connector`` gem (found [here](https://github.com/phallstrom/el_finder)).

We noticed, that if you add a file with a special name (e.g. ``"onmouseover="alert('fooBar')";test.php``) that we could add javascript which is executed on the specified event (e.g. ``onmouseover``).

This problem occurs due to the fact, that elFinder simply takes the name of a file which it gets from the backend and writes it to the ``title`` attribute of the ``div`` representing the file without escaping it properly. This problem only occurs in the tile view, not in the list view.

Is there an easy way to mitigate this problem? It would be nice if we could do this without escaping all filenames in the backend which results in filenames like ``&quot;onmouseover=&quot;alert(&#x27;fooBar&#x27;)&quot;;test``, which are ugly and confuse the user because it doesn't match what they entered before. IMO this is nothing which should be delegated to the backend but instead should be handled by the client-side library.

**Comment by vongruenigen** [comment]
@zzplab, no, we cannot use this plugin because we're using a ruby based backend (see [here](https://github.com/phallstrom/el_finder)) and not the default PHP backend. Even though, this would not solve our problem since we're also offering access to the files via FTP. Users could still upload files with fishy names this way.

We would need a solution on the frontend which ensures that the filenames are properly escaped and not just simply written out the way they come from the backend.

**Comment by nao-pon** [comment]
@vongruenigen What version of the elFinder are you using? It was fixed on elFinder >= 2.0.3, >= 2.1.0 .

**Comment by vongruenigen** [comment]
We're still using version 2.0. And yes, you're right, after checking the newest version (2.1.13) I can confirm that this bug is really fixed, sorry for the trouble, next time I'm going to check the latest version BEFORE I open an issue. Thanks a lot!
