### ISSUE TITLE
Increase chunk size?

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1520]
Is there a way to have a chunk size larger then 10mb?

**Comment by nao-pon** [comment]
@paulcanning There is client configuration `[uploadMaxChunkSize](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L66-L72)`

**Comment by paulcanning** [comment]
Typically, it's not in the documentation, https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1

**Comment by nao-pon** [comment]
> Typically, it's not in the documentation,

Yes, So wrote in Wiki.

> Note: This page is in progress and as such will not list everything. For more options and further documentation, see inside the js/elFinder.options.js file. 

Wiki can be edited by anyone. We are looking forward to contribute of everyone.

**Comment by paulcanning** [comment]
Edited for you.

**Comment by nao-pon** [comment]
@paulcanning Thanks! :+1:
