### ISSUE TITLE
So what one should be downloaded and....

### ISSUE THREAD

**Issue by neotropic2023** [Studio-42/elFinder#1521]
Nevermind. I placed info in wrong place.
Was having issue getting AutoResize to work. Now it is.

But AutoRotate does not. I keep getting "Unable to connect to back end" when enabled.

**Comment by neotropic2023** [comment]
Ya no, never downloading any other version again. Especially if they do not ever work right away as well as with way, way to many changes that take more time trying to resolve and get working than it should be. I should be able to easily copy my settings over as well as add custom buttons, like I have to my own better image editor. But does not and can not in this latest one, whatever one people are supposed to download. I will just keep this version, whatever it is I have, and work from that.

**Comment by nao-pon** [comment]
@neotropic2023 Current plug-ins may not work only in the current version. Please use the plug-in version you are using.

- https://github.com/Studio-42/elFinder/tags
