### ISSUE TITLE
Upload Max Connections not increasing

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1522]
Using the example in the repo, by default it seems like there are 3 connections made at a single time.

I changed this to 10, using the connector option `uploadMaxConn` - however, only 5 connections are made, when I inspect the network traffic using Chrome Inspector.

Is there something else that needs to be done?

**Comment by nao-pon** [comment]
It is probably the browser restrictions. The number of concurrent connections in most of the browser is limited to 6 connections.
