### ISSUE TITLE
Can't remove "Open" action

### ISSUE THREAD

**Issue by nicorac** [Studio-42/elFinder#1523]
I've configured elFinder like this (stripped OT lines):
```php
$root = array(
    'driver'          => 'LocalFileSystem',
    'disabled'        => array('open', 'edit', 'view'),
    'path'            => $path,
    ...
);
$opts = array(
    'roots' => $root,
    ...
);
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```
but when I right click on a file the "Open" action (the first one in the context menu) is still there.
"Edit" action disappears as expected.

Am I missing something?

**Comment by nicorac** [comment]
The bug appears also to other context menu items.
I've disabled the "paste" command too; it disappeared from the toolbar but still available (and working) in context menu.
```php
$root = array(
    'driver'          => 'LocalFileSystem',
    'disabled'        => array('open', 'edit', 'view', 'paste'),
    'path'            => $path,
    ...
);
$opts = array(
    'roots' => $root,
    ...
);
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```

**Comment by nao-pon** [comment]
@nicorac `open` command It is unexpected to disable because it also serves as the action to open the folder.
For `paste` command, it seems to function properly without being displayed in the context menu. I'm checked in elFinder 2.1.13.

**Comment by nicorac** [comment]
After furter testing I've found what's going on; hope you can understand my explanation, otherwise I'll set up a test environment.

I'm adding "quota" limit to my volumes, so I've bound actions that change root folder size to a callback function that recalculate volume size.
My code is like this:
```php
    $root = array(
        'driver'          => 'LocalFileSystem',
        'disabled'        => <function that returns 2 different arrays based on the user over-quota status>,
        'path'            => $path,
        ...
    );
    $opts = array(
      'roots' => $roots,
      'bind'  => array(
         'edit extract mkdir mkfile rm duplicate paste upload put' => 'clear_size_cache',
      ),
    );
```

Function clear_size_cache() returns TRUE to force elFinder to update itself.

When the user gets over-quota, elFinder gets a different array of **disabled** actions.
Toolbar actions are correctly removed, context menu are not.
After a full page refresh will update the context menu correctly.

**Comment by nao-pon** [comment]
@nicorac Which version of elFinder are you checking?

**Comment by nicorac** [comment]
Version 2.1.13.
Will now try latest master, if it matters.

I'm wondering if the 'disabled' root parameter affects only the client-side or the server-side too.
I mean: on my side **paste** is one of the disabled actions. It disappeared from the toolbar but still present in the context menu (after bind callback is executed not after a **full page reload**).
So I think the action is only hidden and not disabled and the server-side connector will still execute it; if so, what if the client sends a "specially crafted" AJAX request with the **paste** command?

**Comment by nicorac** [comment]
Just to be clearer: returning a different list of disabled actions (after an action is executed) affects only the toolbar and not the context menu.

**Comment by nao-pon** [comment]
You can refresh the elFinder view by in the connector callback returns the value `true`. First of all, please try it.

**Comment by nicorac** [comment]
Tried with master and have the same behavior.
As I wrote in my [previous comment](https://github.com/Studio-42/elFinder/issues/1523#issuecomment-232392354) my call back already returns TRUE: in fact the toolbar updates but the context menu doesn't.

**Comment by nao-pon** [comment]
Do you have disabled `open` command? There is a possibility of unexpected behavior to disable the `open` command.

**Comment by nicorac** [comment]
No, open is not disabled, but what I supposed being a bug is just a "misbehavior".
I have a sample to show what I mean, but will start another more specific issue.
