### ISSUE TITLE
Customize status bar text

### ISSUE THREAD

**Issue by nicorac** [Studio-42/elFinder#1524]
Is there a way to customize status bar text?
I'm implementing a "quota system" for my volumes so I'd like to show something like:
**"10MB still available"**
and update that text after each operation (I already have a disk-usage cache).
When the user goes over-quota, the message becomes **"No space left on volume"**.

I tried to show that text just below the elFinder DOM element, but it won't get updated because elFinder uses AJAX calls...

Any suggestion?

**Comment by nao-pon** [comment]
@nicorac It is a simple example.
```javascript
$().ready(function() {
	var elf = $('#elfinder').elfinder({
		url : 'php/connector.php'
	}).elfinder('instance');
	elf.bind('open', function() {
		var info = $('<span class="elfinder-stat-quota"/>').html('10MB still available');
		elf.getUI('stat').append(info);
	});
});
```

**Comment by nicorac** [comment]
That's fine, but how could I update it after a, say, **copy/paste** action?
I mean, paste action will trigger an AJAX request that updated files list.
Is there a way to add custom data to be sent to the client within the same AJAX request of paste action?
Or maybe add custom data to each root object (quota value) and update the status bar when user switches between roots?

**Comment by nao-pon** [comment]
Use connector option `bind`.
**connector.php**
```php
function checkQuota($cmd, &$result, $args, $elfinder, $volume) {
	$result['_quota'] = 0;
}

$opts = array(
	'root' => array(/* Roots options*/),
	'bind' => array(
		'paste' => 'checkQuota',
	),
);

$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```

**elfinder.html**
```javascript
$().ready(function() {
    var elf = $('#elfinder').elfinder({
        url : 'php/connector.php'
    }).elfinder('instance');
    elf.bind('paste', function(e) {
        var quota = e.data._quota;
    });
});
```

**Comment by nicorac** [comment]
That's good, will try soon.
Thanks.

**Comment by nicorac** [comment]
I've tried your suggestion on my side but it doesn't work:

connector.php
```
    ...
    $opts = array(
      'roots' => $roots,
      'bind'  => array(
        'open' => '_mitrol_fm_update_cache',
      ),
    );
}
function update_size($cmd, &$result, $args, $elfinder, $volume) {
    $result['_volume_size'] = 100;
    return TRUE;
}
```
client.js
```
elf.bind('open', function(e) {
    var size = e.data._volume_size;   // NULLHERE
});
```
I'm sure PHP function is called and $result array is correctly populated.
Debugging .js at line **NULLHERE** I see that `e.data` is always `null`... what's wrong?

**Comment by nao-pon** [comment]
@nicorac I checked. There was no problem. If you have functions for `open`, the same key can not be specified in the bind function. Please check it.

```php
      'bind'  => array(
        'open' => 'update_size',
        'open' => 'othore_func'
      ),
```
TO
```php
      'bind'  => array(
        'open' => array(
           'update_size',
           'othore_func'
        )
      ),
```

**Comment by nicorac** [comment]
I have only one PHP function bound to 'open', and this callback function is called correctly.
Here I set the $results['_volume_size'] element without errors.

The issue is **at the client side**, where js function receives a **null `e.data` value**.
```
elf.bind('open', function(e) {
    var size = e.data._volume_size;   // <-- *** e.data IS NULL! ***
});
```

**Comment by nao-pon** [comment]
@nicorac There is [Demo on jsfiddle](http://jsfiddle.net/naopon/qc0ygmd5/17/). Please check it.

**Comment by nicorac** [comment]
My bad, I forgot the `.elfinder('instance')` part, so I was binding to something else.

It now works but still have another quirk:
the additional <span> appears correctly in status bar then it suddenly disappears.
I suppose it's because of the `true` returned by PHP callback that forces elFinder to refresh.

I tried to bind to `sync` command but it doesn't work...
Which event is raised when returning `true` from PHP callback?

**Comment by nao-pon** [comment]
@nicorac Yes, you can use `sync`.

e.g. [Demo on JSFiddle](http://jsfiddle.net/roaku53j/)
```javascript
  var elfinderSetVolumeSize = function() {
  	var info = $('<span class="elfinder-stat-quota"/>').html(' ' + elf.getUI().data('_volume_size') + 'MB free');
    elf.getUI('stat').append(info);
  };
  elf.bind('open', function(e, fm){
  	/*fm.confirm({
    	title : 'Debug',
    	text: 'e.data._volume_size: ' + (e.data._volume_size || 'undefined'),
      accept: {label: 'ok', callback: function(){}},
      cancel: {label: 'close', callback: function(){}}
    });*/
    fm.getUI().data('_volume_size', e.data._volume_size);
    elfinderSetVolumeSize();
  })
  .bind('sync', function() {
  	elfinderSetVolumeSize();
  });
```

**Comment by nicorac** [comment]
That's exactly what I was looking for: a local storage for custom data sent trough AJAX.
Thanks a lot.
