### ISSUE TITLE
Deny mime type before uploading?

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1525]
Currently, to disallow a mime type, the file has to be upload to the server first then it comes back saying the file type is not allowed.

This is useless for huge files, as I need to be able to have elFinder inform the user that the mime type is not allowed after then select a file, before it gets uploaded.

I cannot use the client option `onlyMimes` as the list is huge and allowed types may change quickly and frequently. I only need to stop certain ones e.g .exe

Is this possible?

**Comment by paulcanning** [comment]
Also, to add to this (unless there is a solution already) can we check file extensions, rather then mime types? I want to allow users to add their own extensions to a deny list in a backend system, but they might not know the exact mime type for a particular file extension.

**Comment by nao-pon** [comment]
We plan to use the MIME type of the type property of the browser of file objects. It does not check when the MIME type can not be acquired.

**Comment by paulcanning** [comment]
Is there anyway to use the client option `onlyMime` to deny file types right now?

For example, I want to hide files with extension `exe` in the file dialog window, but `onlyMimes` is a list of allowed file types as it stands.

**Comment by nao-pon** [comment]
`onlyMime` is allowed filter only. By the way what about volume option `accessControl`?

e.g. **in [accessControl call back function](https://github.com/Studio-42/elFinder/blob/b3e92120a8657bdd263ad750dc9760c8d5aa2a89/php/connector.minimal.php-dist#L47-L59)**
```php
if ($attr === 'hidden') {
	if (preg_match('/\.exe$/i', $path)) {
		return true;
	}
}
```

**Comment by paulcanning** [comment]
How will the new check work? Is it a client option? And when will it be ready to roll out? :)
