### ISSUE TITLE
stop image popup

### ISSUE THREAD

**Issue by Poppoll** [Studio-42/elFinder#1528]
How can I stop the image preview popup When I double click a file.
I want the file to open in tinymce.
Paul

**Comment by nao-pon** [comment]
@Poppoll Please use [`getFileCallback`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#getFileCallback) option. There is a wiki page [Integration with TinyMCE 4.x](https://github.com/Studio-42/elFinder/wiki/Integration-with-TinyMCE-4.x).
