### ISSUE TITLE
Click-n-drag graphical glitch

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1529]
I am experiencing graphical issues when clicking and dragging with the mouse inside the file list window.

Please see the image [here](http://imgur.com/iuV6ixT)

This was done by simply clicking under the file list, and dragging upwards. You can see the dotted selection box is misplaced.

**Comment by nao-pon** [comment]
@paulcanning I can not see the trouble. Do you have this problem in the [demo site](http://studio-42.github.io/elFinder/)?

**Comment by paulcanning** [comment]
Hmm, no I don't.

Could it be affected by some odd CSS?

**Comment by nao-pon** [comment]
Probably I think that it is due to other CSS or JavaScript is being read into the page. Please let us know, and then re-open When you have found it to be improved in elFinder side.

**Comment by paulcanning** [comment]
Yea, this seems to be fixed if I removed a custom stylesheet. I'll have words with the frontend dev.
