### ISSUE TITLE
elFinder  don't create thumbnails when using google drive

### ISSUE THREAD

**Issue by freccon** [Studio-42/elFinder#1530]
elFinder only create the .tmb folder but not the thumbnails for googledrive.

GD is installed, and driver creat only thumbnails for files on the server.
![gd](https://cloud.githubusercontent.com/assets/20467856/16860780/b722bbe2-4a00-11e6-9b28-dc4923675dbf.jpg)

Help.

**Comment by nao-pon** [comment]
@freccon There is an option ['optionsNetVolumes'](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#optionsnetvolumes-2113) of connector main.

e.g.
```
$opts = array(
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    ),
    'optionsNetVolumes' => array(
        'googledrive' => array( // or `'*' => array(` for all netmount drive
            'tmbPath' => 'Path to tmb directory',
            'tmbURL'  => 'URL to tmb directory',
        )
    )
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```

Note: It require elFinder >= 2.1.13

**Comment by freccon** [comment]
Thanks somuch
