### ISSUE TITLE
Search using custom column content

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1531]
I have a custom column that displays a description of the file (pulled from a database and attached to the file data)

Is there a way to get the search box to include this column when looking for results?

**Comment by nao-pon** [comment]
@paulcanning Please correspond with [doSearch](https://github.com/Studio-42/elFinder/blob/5f479c1d7e87bd098bec72d15a4a6c6e578045d4/php/elFinderVolumeDriver.class.php#L3903-L3912) method to extend the volume driver. We can not support for more information how to do this.

**Comment by paulcanning** [comment]
Do you have any more info on implementing this?

Seeing as custom columns can be added easily enough with elFinder, extending the search should be via elFinder
