### ISSUE TITLE
[ui:cwd] can not use the `_` in custom column name

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1532]
I have one working custom column, and want to add a second.

The data is being added to the file object, the same as the working one.

I can see the data is there using the network inspector tools.

I have the following code for the client options:

```
cwd: {
							listView: {
								columns: ['description', 'uploaded_by', 'size', 'kind', 'date'],
								columnsCustomName: {
									description: 'Description', // this one works
									uploaded_by: 'Uploaded By' // this doesn't
								}
							}
						}
```

In the column, under "Uploaded By" it just shows `{uploaded_by}` instead of the data attached to the file.

**Comment by paulcanning** [comment]
To add to this, my second.custom column was.appearing at the end of the.columns, instead of being second.

I ordered the columns in the.client options, a such

Custom column 1, custom column 2, size, modified, type

Yea column 2 was shown last.

**Comment by nao-pon** [comment]
I think the order of the column has been set.

rel. #1535
