### ISSUE TITLE
Context menu available actions not updated after bind callback

### ISSUE THREAD

**Issue by nicorac** [Studio-42/elFinder#1533]
I'm adding quota feature to elFinder: when an user goes "over-quota", some actions will be disabled until he/she gets back under the quota limit.

To disable actions, connector tests quota status and returns a different array to 'disabled' parameter based on user over/under quota status. Connector binds a callback to "sensitive" actions like **paste, rm, duplicate** which updates quota and returns TRUE to let elFinder update itself.
The expected effect is actions disabled immediately after the action that caused the over-quota (and restore them after, say, deleting some files), but actually only toolbar actions are updated (i.e. Paste disappears) but not the context menu.

To demonstrate this "misbehavior" I've setup a [sample repository here](https://github.com/nicorac/elfinder-sample).
It features a simpler quota algorithm (to keep things simple): quota is not "folder size"  but "files count" related: you're allowed to store up to 3 files in the volume, when you add the 4th you'll switch to readonly access.

Since a video is better then a thousand words, take a look to [sample video](https://github.com/nicorac/elfinder-sample/blob/master/video.mp4?raw=true) in the same repo.

**Comment by paulcanning** [comment]
Your repo contains no `connector.php` file, which is what is referenced in `index.html`

**Comment by nicorac** [comment]
Oops, you're right.
I've cleaned it up too much, now fixed ;)

**Comment by nao-pon** [comment]
@nicorac This bug reason is that dosn't update cmd status at sync. I'll fix it.

**Comment by nicorac** [comment]
Great, will wait next Nightly build then delete my test repo.
