### ISSUE TITLE
Column alignment issues

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1534]
The column headers are not lining up with the column info.

Please see [here](http://imgur.com/v5TuUYf) for a screenshot.

**Comment by nao-pon** [comment]
There is no problem on demo site. Please check on stand alone elFinder (with out any other CSS & JavaScript). Please reopen this issue, if you got same problem on stand alone elFidner

**Comment by paulcanning** [comment]
On your demo site you do not have custom columns, like I do. So of coruse you see no issue on the demo site.

Add a custom column and you'll see what I mean (like my screenshot)

**Comment by nao-pon** [comment]
I added custom column `url`. -> http://output.jsbin.com/honaqa#elf_l2_Lw

It seems no problem.

**Comment by paulcanning** [comment]
Please use 2 custom columns for a proper comparison.

What version of elFinder are you using? I am using 2.1.14

**Comment by nao-pon** [comment]
Update http://output.jsbin.com/honaqa#elf_l2_Lw with 2 custom columns. It use git nightly version. Please check with nightly if you want to report a bug.

**Comment by paulcanning** [comment]
Thing is, when I reported this issue and you said there isn't a problem on the demo site, 2.1.14 was the latest version at that time AND your demo site didn't show 2 custom fields.

I'll try the latest version and see if that helps.

**Comment by paulcanning** [comment]
So this is what it looks like with the 2.1.16 nightly. I also added some content for the description column just to be safe.

You can see that the end column is totally borked and they are all misaligned.

http://imgur.com/uImFtaP

**Comment by paulcanning** [comment]
OK, looks like the issue is a conflict with Bootstrap's CSS file.

**Comment by mauleous** [comment]
Hi @paulcanning , do you find a solution for this conflict with Bootstrap's CSS? 
I also have the same problem and I wonder if not using Bootstrap's CSS is the only solution.

**Comment by paulcanning** [comment]
The only solution was to have the elFinder window on a blank page and use an iframe to embed it into the bootstrap main site. Bit of a hack but it works.

**Comment by mauleous** [comment]
Ah cool, thanks for the answer! :)

**Comment by Joosakur** [comment]
Setting listView.fixedHeader to false also helps with the alignment, but the resizing still doesn't work perfectly. Often on release the column sizes jump weirdly. I don't think this issue should be closed.

**Comment by paulcanning** [comment]
@Joosakur You're right, the main problem here is that it conflicts massively with Bootstrap. I understand that it's a big ask to have something be compatible with someone else's work, but now the problem has been brought to attention, it'd be great if I didn't have to use an iframe to skirt the issue.

**Comment by dadicsb** [comment]
Hello, is can be fixed by this
`.elfinder-cwd table tr td {
    box-sizing: content-box !important;
}`

**Comment by nao-pon** [comment]
@dadicsb I fixed itwith 4f858d5. Thanks! 👍
