### ISSUE TITLE
Re-ordered columns, cannot reset

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1535]
How do you reset the columns (widths and order)?

I tried adding in the client option `reloadClearHistory` but that doesn't help.

I cleared my CodeIgniter sessions as well.

Anything else?

Also, how can stop them being re-ordered?

**Comment by nao-pon** [comment]
There is no way to reset the order of the column. Why do you need to be reset?

**Comment by paulcanning** [comment]
If I reorder them and refresh, how does elfinder know how they are ordered? Is it stored in a cookie?

I want to reset the order just because I want to.

**Comment by nao-pon** [comment]
Data is stored in a local storage of the browser. If necessary in debug as a developer is available from the Web console.

`window.localStorage.removeItem(window.location.pathname+'-elfinder-cwdCols'+'<elfinder dom id>')`

e.g.
`window.localStorage.removeItem(window.location.pathname+'-elfinder-cwdCols'+'elfinder')`

And reload browser window.
