### ISSUE TITLE
getPath() returns false when renaming a file in a directory

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1536]
Using `$volume->getPath($args['target'])` (where the `$args['target']` is a hash) returns false when you rename a file in a sub directory.

The file path would be `dir/file.jpg` and when the file hash is passed to `getPath()` , `false` is returned, rather then the file path.

Below is the code in my `bind` callback for the `rename` command:

```
public function file_rename($cmd, &$result, $args, $elfinder, $volume)
{
	$parentPath = $volume->getPath($args['target']); // returns false for a file e.g. 'path/file.jpg'
}
```

**Comment by nao-pon** [comment]
This issue duplicated to #1527.

**Comment by paulcanning** [comment]
So is there an update? I'm using 2.1.13...

**Comment by nao-pon** [comment]
Please wait 2.1.14 or try nightly build.
