### ISSUE TITLE
Logger can't reach $volume object after every command

### ISSUE THREAD

**Issue by kukko** [Studio-42/elFinder#1537]
The logger method didn't get the $volume object in the 5th parameter at RM, PASTE and DUPLICATE commands, so I can't get the path of the affected files.

**Comment by nao-pon** [comment]
@kukko `$volume` is available since elFinder2.1.12.

**Comment by nicorac** [comment]
In 2.1.13 Nightly build (2016-07-17) `$volume == false` for `rm` command.

**Comment by nao-pon** [comment]
@nicorac 
pass $volume to the callback function in elFinder.class.php L.702
```php
				if (call_user_func_array($handler,array($cmd, &$result, $args, $this, $volume))) {
```
Please check your loaded elFinder.class.php.

**Comment by nao-pon** [comment]
@nicorac Your are right. $volume is `false` if cmd has `targets`(multi targets). You can get like this.
```php
function callback($cmd, &$result, $args, $elfinder, $volume) {
	if (! $volume && isset($arg['targets']) && is_array($arg['targets'])) {
		foreach($arg['targets'] as $target) {
			$volume = $elfinder->getVolume($target);
		}
	}
}
```

**Comment by nicorac** [comment]
Yes it works.
I only had to change your sample from `$arg` to `$args` (in function body).

Thanks

**Comment by nao-pon** [comment]
> I only had to change your sample from $arg to $args (in function body).

Oh, my... I corrected it. Thanks!
