### ISSUE TITLE
Can't Drag n Drop Upload Directory

### ISSUE THREAD

**Issue by yuseilee1992** [Studio-42/elFinder#1538]
I can't even drag and drop upload folders from my computer and it keep pop out the "Connection Aborted." message. 
Any solution? I'm using Safari version 9.0. I tried others browsers and it is work except Safari.

Thanks.

**Comment by nao-pon** [comment]
@yuseilee1992 elFinder supports folder uploading only Google chrome. Other browsers will be possible if the supported [DirectoryReader API](https://developer.mozilla.org/en-US/docs/Web/API/DirectoryReader).
