### ISSUE TITLE
Mount error - Driver "elFinderVolumeLocalFileSystem" : Root folder does not exists

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1539]
I am seeing this error in the debug object when uploading files to Cloud Storage.

The file seems to be uploading correctly, so why am I seeing the error?

Also, there is a spelling mistake. It should be "exist", not "exists"

**Comment by nao-pon** [comment]
@paulcanning Perhaps, it is due to your configuration. We do not have a way to resolve the. Please let us know, and then re-open if there is a problem with the elFinder side.

----

> Also, there is a spelling mistake. It should be "exist", not "exists"

I fixed it. Thanks.
