### ISSUE TITLE
Large Video preview problem

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1540]
In preview Large Video file (like file size in 2 GB) in el-finder, server memory is highly decrease.
in computer 6GB RAM is 99% is get to server & stuck computer.

**Comment by nao-pon** [comment]
@CodeLyokotEAM Which connector are you using? I checked with LocalFileSystem that was no problem. Please show us your  connector configuration.

**Comment by nao-pon** [comment]
@CodeLyokotEAM  close this, but please re-open if necessary.

**Comment by CodeLyokotEAM** [comment]
Its happening after disable original path,
// 'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/',
I'm Using wamp server64 in windows 10.
