### ISSUE TITLE
URL to specific volume and folder not working

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1541]
elFinder uses URL variables to let you navigate to a specific volume/folder (and use browser controls to go back and forth) and they usually work well, however, When I try to go to a URL that points at a AWS S3 volume, is ends up redirecting to a URL for the other volume, which is Google Cloud Storage.

In the connector, they both have different IDs and Aliases.

Why would a redirect be happening?

**Comment by nao-pon** [comment]
If the folder of the specified hash does not exist in the data driver returns, and redirects to the default folder. This problem appears to be of the AWS driver problem. Maybe it is related to #1543.

**Comment by paulcanning** [comment]
The folder definitely exists, because the testing was done in a matter of seconds.

**Comment by nao-pon** [comment]
Perhaps I think volume driver does not return the correct data. This would not be elFinder problems. I will close this issue, but please re-open when you have found a problem in elFinder.

**Comment by paulcanning** [comment]
Do folders need a specific mime type or something for elFinder to recognise it as a folder?

**Comment by nao-pon** [comment]
Yes, the folder mime type is "directory".

**Comment by paulcanning** [comment]
Hmm, that's what is is showing as. so I think there may be an elFinder issue?
