### ISSUE TITLE
Root volume sub folders not selected when reloading page

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1543]
I am using `rememberLastDir` to let the user land in the last visited directory in the AWS volume.

However, lets say they should land in `ROOTVOLUME/sub-folder/` they will land there, but in the side tree menu, the volume stays closed and the directory is not selected.

**Comment by nao-pon** [comment]
@paulcanning I checked with LocalFileSystem, FTP, Dropbox and GoogleDrive volumes. There is no problem. Probably, this is AWS volume problem.

**Comment by paulcanning** [comment]
Can you check with AWS?

**Comment by nao-pon** [comment]
I can not. I don't have AWS account.

**Comment by paulcanning** [comment]
You can get a free one, which is perfect for testing purposes.

**Comment by nao-pon** [comment]
For now I do not need the AWS. There is also no time to test. This would not be elFinder problems. I will close this issue, but please re-open when you have found a problem in elFinder.
