### ISSUE TITLE
ui-droppable class missing on directories

### ISSUE THREAD

**Issue by vongruenigen** [Studio-42/elFinder#1544]
I'm currently updating our elFinder to the newest available version 2.1.13. Everything is working fine, except for Drag & Drop, more precise, the drop is not working. I can drag directories and files around and elFinder recognises that by showing a different cursor icon. But as soon as I hover over a directory it doesn't change the icon of the directory to the "open" version.

I debugged the problem and it looks like the problem occures because the jQuery UI css class ``ui-droppable`` is not applied on the directories and hence the jQuery UI droppable isn't initialized. I digged through the source code of elFinder and found out that this class is applied in the ``makeDroppable()`` function in ``cwd.js`` (see [here](https://github.com/Studio-42/elFinder/blob/master/js/ui/cwd.js#L843)):

```javascript
makeDroppable = function(place) {
  var targets = (place || cwd).find('.directory:not(.'+clDroppable+',.elfinder-na,.elfinder-ro)');
  if (fm.isCommandEnabled('paste')) {
    targets.droppable(droppable);
  }
  if (fm.isCommandEnabled('upload')) {
    targets.addClass('native-droppable');
  }
},
```

I stepped through this function via the webkit developer tools available in my chrome browser. It looks like it doesn't find any ``targets`` on the first line of the function:

<img width="1280" alt="screen shot 2016-07-21 at 14 50 00" src="https://cloud.githubusercontent.com/assets/789513/17023207/822f21c6-4f52-11e6-8518-212d52a4ca03.png">

I currently really don't know why this is happening. If I compare the code of the ``makeDroppable`` function with the previous versions, the only real thing which changed is the addition of the ``place`` parameter. And yes, the ``past`` command is enabled.

Now, my question is, if any of you could imagine what the problem might be here? We're also having some custom css styling and some custom plugins. But these were also used in the old version and haven't caused any problems whatsoever.

Thanks in advance!

**Comment by nao-pon** [comment]
@vongruenigen 2.1.13 uses a DocumentFragment to DOM build than to improve performance. Since there is no problem it is a stand-alone state, perhaps there is a problem with the integrity with your customization. Please let me know if there is a point to be addressed something in elFinder.

**Comment by vongruenigen** [comment]
@nao-pon, thanks for the quick response. Even after disabling / removing all customizations and plugins, it still doesn't work. I'm initializing it the as follows (note: I'm using coffeescript):

```coffeescript
$ ->
  @el = $('#elfinder')
  @el.elfinder
    url: @el.data('elfinder-api-url')
    lang: @el.data('i18n-locale')
    transport: new elFinderSupportVer1()
```

I cannot imagine what might cause the problem here. I'm including the ``elfinder.full.css`` and ``elfinder.full.js`` files from the release 2.1.13 zip. The problem is still the same, the ``ui-droppable`` class is missing on directories.

**Comment by vongruenigen** [comment]
@nao-pon, I just tried the version 2.1.12 instead of 2.1.13, and it working. I saw that you made changes to the ``makeDroppable()`` function between 2.1.12 and 2.1.13 (see 695b0c5bd814221668c134c81f97aa5166bb5549). I'm not sure if this is the change which causes the problem.

Do you have a public availably and running demo of the version 2.1.13 where I could debug the code? Cause the demo on the elfinder homepage uses the minified version, with which it's not possible to debug any code.

**Comment by nao-pon** [comment]
@vongruenigen You can debug with full.js version in (JS Bin)[http://jsbin.com/qaxebix/edit?html,output]. Please check it.

**Comment by vongruenigen** [comment]
@nao-pon, thanks again! I'll give it a try, maybe I can find what the problem is.

**Comment by vongruenigen** [comment]
Ok, I've tried it out and if I copy all source which you were using in your JSBin example, it's working! But I currently really don't understand what's the problem here, because we're using jQuery in the version 1.11.1 and jQuery-UI in version 1.11.4, which are both sufficient according to the wiki. If I'm using the versions 1.12.0-pre and 3.1.1-pre respectively, it suddenly starts to work.

I updated the [JSBin example](http://jsbin.com/yivibitebi/edit?html,output) you provided earlier to use the exact same versions as we do and finally, I can reproduce the issue!

@nao-pon, what do you think? Are the minimal requirements for jQuery and jQuery-UI to "low" for the new version?

**Comment by nao-pon** [comment]
@vongruenigen Oh! OK! I broke the downward compatibility. I will fix it.

Thanks! :+1:

**Comment by vongruenigen** [comment]
@nao-pon, thanks a lot! After testing the new version 2.1.14, I can confirm that this issue is fixed.
