### ISSUE TITLE
Please disconnect delete and rename

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1545]
So it seems that the only way to allow renaming of a file is to have it unlocked (`locked = 0`)

But doing so also lets the user delete the file.

I want to let users rename, but not delete.

Can you either add in a flag for delete protection, or disconnect rename and delete so I can do one but not the other?

**Comment by nao-pon** [comment]
@paulcanning 

> I want to let users rename, but not delete.

What about `write = 1`?

**Comment by paulcanning** [comment]
I tried `read`, `write` and `locked` with all combinations of `0` and `1`.

Files were only re-nameable when `locked` was set to `0`

**Comment by paulcanning** [comment]
[Here](http://imgur.com/QvUWruL) is a screenshot showing a file that has the following attributes:

`read = 1`
`write = 0`
`locked = 0`

As you can see, the rename icon is clickable (not muted/greyed out)

**Comment by nao-pon** [comment]
Renamable operate on files of the write-protected is a specification of the common file system, such as Linux.

**Comment by paulcanning** [comment]
I am running this on a Linux server, connected to Google Cloud Storage.

I have provided evidence that `write` does not effect renaming, and that renaming and delete are both connected to `locked`.

They need to be separated.

**Comment by nao-pon** [comment]
The operation of elFinder by the file attribute is by design. If you need to change the specifications, please customize the elFinder.

**Comment by paulcanning** [comment]
If that is the case, can you provide information on how to enable/disable certain toolbar icons based on specific file attributes?

Example, if I give a file an extra attribute of `rename = false` then the rename icon *only* is disabled.

**Comment by nao-pon** [comment]
**Example to disable `rm` of not writable items in selected volume** elFinder >= 2.1.15

- Front end  - JavaScript
```javascript
// command `rm2` extends `rm`
(elFinder.prototype.commands.rm2 = function() {
	this.getstate = function(sel) {
		var fm = this.fm;
		sel = sel || fm.selected();
		return !this._disabled && sel.length &&
			// check `write` too
			$.map(sel, function(h) { var f = fm.file(h);
return f && f.phash && !f.locked && f.write ? h : null }).length ==
sel.length
			? 0 : -1;
	};
}).prototype = {
	extendsCmd : 'rm', // extends command name
	forceLoad    : true // to force load
};

var options = {
    url  : 'php/connector.php',
}
$('#elfinder').elfinder(options);

```
- Back end - PHP connector
```php
// customized volume driver
class elFinderMyVolumeLocalFileSystem extends
elFinderVolumeLocalFileSystem extends
{
    protected function remove($path, $force = false) {
        if (! $force && ($stat = $this->stat($path)) && !
$stat['write']) {
            return $this->setError(elFinder::ERROR_PERM_DENIED,
$this->path($stat['hash']));
        }
        return parent::remove($path, $force);
    }
}

$opts = array(
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/',
        ),
        array(
            'driver' => 'MyLocalFileSystem',
            'path'   => '/path/to/files2/',
            'URL'    => 'http://localhost/to/files2/',
            'uiCmdMap' => 'array('rm' => 'rm2'), // use `rm2` instead `rm`
        ),
    )
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```
