### ISSUE TITLE
Replace underscore with zero width space

### ISSUE THREAD

**Issue by vongruenigen** [Studio-42/elFinder#1548]
Why do you prepend zero width spaces ("&amp;#8203;") before underscores in file names (see [here](https://github.com/Studio-42/elFinder/blob/5a9c26772da7893b2a1cb35381b698b90dd318c1/js/ui/cwd.js#L212))?

This breaks some of our code where we're actually iterating over the directories DOM elements and marking them on matching their title with a name from an array of strings.

Thanks in advance!

**Comment by nao-pon** [comment]
@vongruenigen This replacement function is configurable by [uiOptions.cwd.replacement](https://github.com/Studio-42/elFinder/blob/7c46ada56fe200284fa5cfe6ccfaa70155c83033/js/elFinder.options.js#L576-L593).

Please try next example.
```javascript
uiOptions : {
  cwd : {
    replacement : {
      name : function(f, fm) {
        return name = fm.escape(f.i18 || f.name);;
      }
    }
  }
}
```

**Comment by vongruenigen** [comment]
@nao-pon, thanks, your tip solved my issue. I would suggest that you extend the wiki page about client options to include this, what do you think?

**Comment by nao-pon** [comment]
OK. I [added link](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#uioptions) to [elFinder.options.js](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js).

Thanks!

**Comment by vongruenigen** [comment]
@nao-pon, exactly what I was thinking about. Thank you too for your excellent managing of the project!
