### ISSUE TITLE
How to hide/disable toolbar icons based on file attributes/properties

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1549]
How can I hide or disable an icon in the toolbar e.g. the delete button, based on a selected files attributes.

E.g. I currently add custom properties to each file when they are loaded, using the `bind` options in my connector. I would like to hide (or disable) the delete icon if a selected file has a specific custom property of `do_not_delete = 1`

**Comment by nao-pon** [comment]
@paulcanning If you want the same behavior in all of the volume...
```javascript
var options = {
    url  : 'php/connector.php',
    handlers : {
        init : function(e, fm) {
            fm._commands.rm.getstate = function(sel) {
                this.fm;
                sel = sel || fm.selected();
                return !this._disabled && sel.length &&
                    // check `do_not_delete` too
                    $.map(sel, function(h) { var f = fm.file(h); return f && f.phash && !f.locked && !f.do_not_delete ? h : null }).length == sel.length
                    ? 0 : -1;
            }
        }
    }
}
$('#elfinder').elfinder(options);
```

If you have control over roll operation for each volume, please refer to 0360abe29d2e4dbbb7dbefaa370b3706ee522270 [commit log](https://github.com/Studio-42/elFinder/commit/0360abe29d2e4dbbb7dbefaa370b3706ee522270) to reference.

In addition, you will not be able to control show/hide state for each item.

**Comment by paulcanning** [comment]
1. How are you specifically targeting the delete icon? How can I target other buttons?
2. What do you mean by "In addition, you will not be able to control show/hide state for each item."?

**Comment by nao-pon** [comment]
1. > Please read [js/commands](https://github.com/Studio-42/elFinder/tree/master/js/commands) source.

2. > It can enable/disable control but can not show/hide control.

**Comment by paulcanning** [comment]
You really need to put this kind of stuff in the wiki rather then people ask and refer them to the source code.

**Comment by nao-pon** [comment]
@paulcanning This project is issued under a [3-clauses BSD license](https://github.com/Studio-42/elFinder#license). If you can not accept this license, you will not be able to use the elFinder.
