### ISSUE TITLE
i have a idea about dragging files

### ISSUE THREAD

**Issue by zc888168** [Studio-42/elFinder#1551]
it can drag files from windowns 8 to elFinder UI. Can next generation drag files drectly from elFinder to windows 8 .

**Comment by nao-pon** [comment]
@zc888168 You can drag-out from elFinder by `Shift key + Drag start`. But to download with Google Chrome only.

**Comment by paulcanning** [comment]
I tried this, but I get a "Forbidden" error when Chrome tries to download the file

**Comment by nao-pon** [comment]
@paulcanning Did you try the [demo site](http://studio-42.github.io/elFinder)?

Item URL that elFInder offerings must have been published.

**Comment by paulcanning** [comment]
Sorry, what do you mean "Item URL that elFInder offerings must have been published."?
