### ISSUE TITLE
After Drag and drop Unable to re-generate thumbnail

### ISSUE THREAD

**Issue by smitshah81** [Studio-42/elFinder#1556]
Hello,

I am not able to generate thumbnail after drag-drop image.

for example

1. upload image to root (this will create thumbnail in thumb folder)
2. create one folder say "test"
3. drop image to "test",thumb image will disappear.

But when you go in to drop location "test" folder then after it will create thumbnail again...

Do I need go to drop folder everytime?

Is there any way to regenerate thumb after drag and drop event?

**Comment by nao-pon** [comment]
@smitshah81 You can immediately make thumbnails by the client configuration option of "[handlers](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#handlers).paste".

e.g.
```javascript
handlers : {
	paste : function(e, fm) {
		if (e.data && e.data.added) {
			var tmbNum = fm.options.loadTmbs > 0 ? fm.options.loadTmbs : 5,
				tmbs = $.map(e.data.added, function(f) { return f && f.tmb && f.tmb == '1' ? f.hash : null; }),
				gets = function() {
					if (tmbs.length) {
						fm.request({
							data : {cmd : 'tmb', targets : tmbs.splice(0, tmbNum)},
							preventFail : true
						}).always(gets);
					}
				};
			tmbs.length && gets();
		}
	}
}
```

**Comment by smitshah81** [comment]
Sorry for late response,

Thanks for your response,I will implement above code in drop method.

**Comment by smitshah81** [comment]
1 more Question..

How we can create Thumb for uploaded Video? "Not Default Image"

**Comment by nao-pon** [comment]
@smitshah81 If command `ffmpeg` is available on the server side, elFinder will try create a icon of the video file.
