### ISSUE TITLE
 Why doesn't it use the defualt apache umask that I've assigned? How can I use a umask of 002? to Is there a way to set the default ownership of new uploaded/created files either uploaded/created in the code?

### ISSUE THREAD

**Issue by ecsumed** [Studio-42/elFinder#1557]
Correct me if I'm wrong, but it seems to be using the system umask of 022 instead of the one I've specified for the apache process 002. How can I override this behaviour? I want all the uploads/new files to follow the umask of 002.

Edit: Sorry. I think I figured it out. This is where the variables 'dirMode' and 'fileMode' can be used. Default fileMode=0644, that's why I thought the umask 022 was being used.

**Comment by nao-pon** [comment]
@ecsumed There are connector options [`dirMode` and `fileNode`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#volume-driver-specific-options). Please use them.
