### ISSUE TITLE
commandsOptions.quicklook.googleDocsMimes

### ISSUE THREAD

**Issue by standus** [Studio-42/elFinder#1558]
Hi,

please can you explain how to implement this functionality:
Set `commandsOptions.quicklook.googleDocsMimes` to enable this plugin, quicklook plugin that is the Google docs online viewer
?
I can not find any example.

Thank you.
S

**Comment by nao-pon** [comment]
@standus 

> Set commandsOptions.quicklook.googleDocsMimes to enable this plugin, quicklook plugin that is the Google docs online viewer

That's OK. However, it is assumed that with a URL which the target of the item was published.

e.g. [JS Bin online demo](http://jsbin.com/serumeb/1/edit?html,output)
```
commandsOptions : {
  quicklook : {
    googleDocsMimes : ['application/pdf', 'image/tiff', 'application/vnd.ms-office', 'application/msword', 'application/vnd.ms-word', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
  }
}
```
