### ISSUE TITLE
Sort within folders?

### ISSUE THREAD

**Issue by labeshops** [Studio-42/elFinder#1559]
Is it possible to set a sort within the folders? I would like to have the most recently uploaded file at the top of the folder since those are the ones I'm working with at the moment.

**Comment by nao-pon** [comment]
@labeshops I have an idea to add a menu "Also treeview" (also applies to the tree view) into sort menu. Is it matches your wants?

**Comment by labeshops** [comment]
Sorry but not sure what a treeview is?

I add images to products as I add the product, so in 1.5 opencart, I had modified the sort order to show images I recently uploaded at the top of the folder – sort by date desc. That is what I want to do in elfinder so I don’t have to search for the image I just added 2 seconds ago all the time.

Lori

**Comment by nao-pon** [comment]
Treeview is
![fireshot capture 2 - elfinder 2 1 x - file manager for web_ - http___studio-42 github io_elfinder_](https://cloud.githubusercontent.com/assets/1412630/17296454/5fc1c1f0-583c-11e6-8447-9d1a285e3e0f.png)
I was misreading.

If the sort mode is set to date - desc, newly uploaded files will be added to the top.
![elfinder-upload](https://cloud.githubusercontent.com/assets/1412630/17296732/9c0409b0-583d-11e6-83f1-e592c0571815.gif)

**Comment by labeshops** [comment]
Right, I want newly added files to be shown at the top. 

How do I set that?

Lori

**Comment by nao-pon** [comment]
check "by date - desc" and un-check "Folders first" that's all.
![sketch-1470197158365](https://cloud.githubusercontent.com/assets/1412630/17353517/51ea24ce-597b-11e6-916b-c83b18903d0f.jpg)

**Comment by labeshops** [comment]
I am sorry but where do I find this??

**Comment by labeshops** [comment]
Okay I figured out there is a new version of elfinder – I hav .12 and the new one is .14. Since I installed your mod originally thru ocmod though, not sure where I need to upload the new version??? What directory should it be uploaded into??

Lori

**Comment by nao-pon** [comment]
If you are using the elFinder as an extension of opencart, I do not know that the details regarding it. Please ask the extension of the developers.

Me to guess, I think that it is because the sort command is not enabled.

**Comment by labeshops** [comment]
I am sorry, I thought you were the developer of the extension? 

Lori

**Comment by nao-pon** [comment]
Please don’t worry. Good luck!
