### ISSUE TITLE
Make to possible to apply sort mode in tree in navbar

### ISSUE THREAD

**Issue by nao-pon** [Studio-42/elFinder#1560]
Add a menu in the sort dialog, to be able to apply the sort mode for the tree in navbar.

**Comment by nao-pon** [comment]
![elfinder-also-treeview](https://cloud.githubusercontent.com/assets/1412630/17297417/a164bfa0-5840-11e6-840d-8701755c94de.gif)

**Comment by bgbruno** [comment]
Hello @nao-pon,

still the best is your #elfinder thx

Q pls from which version is this available?
Q is it possible make it default without choose?

Bruno
