### ISSUE TITLE
folder short bug

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1562]
Goto this & try to short by name
http://studio-42.github.io/elFinder/#elf_l1_Lw
You can see **"plenty items"** folder is always top of list. But first folder should be **'BasicAuthExample'** folder.
![image](https://cloud.githubusercontent.com/assets/18566890/17322523/706f8c42-58bb-11e6-8a04-059dd92956c2.png)

I think its because **'plenty items'** folder isn't real name in server side its name **'a_lot_sample'**.
![image](https://cloud.githubusercontent.com/assets/18566890/17322494/4f91dcdc-58bb-11e6-80b5-405f1549ebfa.png)
(this site didn't close file accessing)

also You can see it try to copy **'plenty items'** folder to anther pales its name is **'a_lot_sample'** (try to copy & refresh site as soon as because its has too many folders)

**Comment by nao-pon** [comment]
@CodeLyokotEAM Yes, It is a bug of `elFinder._sortRules`. I'll fix it. Thanks! :+1:
