### ISSUE TITLE
When will 2.1.15 be released?

### ISSUE THREAD

**Issue by vongruenigen** [Studio-42/elFinder#1567]
I'm currently having some nasty issues regarding the usage of commands on elements from the tree-view. When I try to rename a directory in the tree-view, I'm always getting strange error messages because multiple ajax requests are started and aborted quickly after (see screenshots).

When renaming:
<img width="708" alt="screen shot 2016-08-04 at 11 53 16" src="https://cloud.githubusercontent.com/assets/789513/17397819/1c910256-5a3a-11e6-83b4-afe4a3836e96.png">
After hitting the enter button:
<img width="713" alt="screen shot 2016-08-04 at 11 53 28" src="https://cloud.githubusercontent.com/assets/789513/17397827/28a5511e-5a3a-11e6-8029-258961c1bcc3.png">

However, if I try the whole thing with the current nightly version (as of 2016-04-08), everything works fine. My question now is, when do you plan to release the next minor version so that we can use it to fix our problems?

Thanks in advance!

**Comment by nao-pon** [comment]
@vongruenigen I think that there was such a bug on the API v1, but it is certainly fixed. About 2.1.15, It does not have schedule. Well, I'm thinking early September.

**Comment by vongruenigen** [comment]
@nao-pon, ok thanks for the answer. I'm going to try the nightly builds and upgrade as soon as you release 2.1.15.
