### ISSUE TITLE
full screen bug

### ISSUE THREAD

**Issue by CodeLyokotEAM** [Studio-42/elFinder#1568]
@nao-pon 
Right click & select full screen.
after edit txt file & select that txt edit window full screen button.
you can see what is bug.

also css&js problems are everywhere(after adding full screen option)
- drag & drop error in full screen mode(drag & drop is successful but its not shown in mouse)
- normal screen mode work space resize errors

normal mode
![image](https://cloud.githubusercontent.com/assets/18566890/17398906/d08f03d0-5a5c-11e6-8574-7c3c56cad185.png)

errors
![image](https://cloud.githubusercontent.com/assets/18566890/17398907/dac67a0e-5a5c-11e6-87cd-61f6d49cf7d5.png)
![image](https://cloud.githubusercontent.com/assets/18566890/17398915/e54d7b62-5a5c-11e6-8edc-1fe9390ebdb5.png)

**Comment by nao-pon** [comment]
@CodeLyokotEAM I fixed! Thanks! :+1:
