### ISSUE TITLE
still not fix full screen one bug

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1569]
@nao-pon 

ref #1568
> Right click & select full screen.
> after edit txt file & select that txt edit window full screen button.
> you can see what is bug.

**Comment by nao-pon** [comment]
@CodeLyokotEAM This is in such behavior because it is difficult to full screen the different elements from the full-screen mode.  When you click full-screen button on title bar again, Edit window will be full screen.

**Comment by CodeLyokotEAM** [comment]
but its work in preview mode 

select full screen
after select image & select large button
its work in full screen

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM OK. Change to the maximum instead of the full screen of the dialog.
