### ISSUE TITLE
[ui:cwd] reset the column width may not applied to the header

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1576]
@nao-pon 
I test this only mobile device.
Reset columns,
Adjust permissions tab & shot files by name clicking name tab.
Goto the corner.
![screenshot_2016-08-05-21-21-15](https://cloud.githubusercontent.com/assets/18566890/17442276/a0bca5e4-5b52-11e6-8b6c-21883043f5fd.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks! :+1:
