### ISSUE TITLE
multiple file select

### ISSUE THREAD

**Issue by ab2llah** [Studio-42/elFinder#1579]
hi.i am trying to select multiple files using elfinder form field type.
i am using FMElfinder bundle for symfony and the ElfinderType creates this input and script on my page:
```
<input type="text" id="form_parts" name="form[parts]" required="required" class="form-control" placeholder="click to select files" value="/dl/web/uploads/IMG_0001.JPG" data-type="elfinder-input-field">
            <script type="text/javascript" charset="utf-8">
            document.addEventListener("DOMContentLoaded", function(event) {
                $('[data-type="elfinder-input-field"][id="form_parts"]').on("click",function() {
                    var childWin = window.open("/dl/web/app_dev.php/elfinder/form?id=form_parts", "popupWindow", "height=450, width=900");
                });
            });
            
            function setValue(value, element_id) {
                $('[data-type="elfinder-input-field"]' + (element_id ? '[id="'+ element_id +'"]': '')).val(value).change();
            }
        </script>
```
i already tried changing the commandsOptions multiple to true,but when i do that the select option only becomes enabled and does nothing when i select none image files.not even when i select only 1 file.i mean that it becomes disabled and does nothing but it's not disabled as an html element!
when i select multiple images , a popup opens : acquiring image dimentions and from this point forward, nothing else happens! neither the popup is closed nor the opened elfinder page!
please help.

**Comment by ab2llah** [comment]
this is my commandsOptions : 
```
        commandsOptions: {
            getfile: {
                onlyURL: !1,
                multiple: true,
                folders: !1,
                oncomplete: "close"
            },
```

**Comment by nao-pon** [comment]
@ab2llah for example -> [JS Bin online demo](http://jsbin.com/pahove/edit?html,output)
```javascript
	 getFileCallback: function(files) {
            var res = $('#getfile-results').empty();
            $.each(files, function(i, f) {
              res.append($('<div>').text(f.name));
            });
          },
          commandsOptions: {
            getfile: {
              multiple: true
            }
          },
```

However, FMElfinder might different implementation to elFinder. Please ask the developers of FMElfinder to details.
