### ISSUE TITLE
jquery 3.0 Deprecated functions

### ISSUE THREAD

**Issue by wallenium** [Studio-42/elFinder#1582]
Hi Folks,
Jquery 3.0 deprecates some functions, which elfinder uses. Some of them are pretty easy to fix, maybe this could be done in the next release to get rid of the jquery.migrate warnings if using elfinder in one of the Projects. Just some examples...

- [parseJSON()](http://jquery.com/upgrade-guide/3.0/#deprecated-jquery-parsejson)
- [document Ready function](http://jquery.com/upgrade-guide/3.0/#deprecated-document-ready-handlers-other-than-jquery-function)
- [Callback exit](http://jquery.com/upgrade-guide/3.0/#callback-exit)
- [bind, unbind](http://jquery.com/upgrade-guide/3.0/#deprecated-bind-and-delegate)

**Comment by nao-pon** [comment]
@wallenium Thanks!

Those that can be use on "jQuery 1, 2" of the alternatives that are encouraged on jQuery 3 is I want to replace at any time. Also welcome PR of those.

For features that are not available in "jQuery 1, 2" it is scheduled to sequentially corresponding with elFinder 2.2 or later.

**Comment by nao-pon** [comment]
- [ ] [Breaking change: .show(), .hide(), and .toggle() methods now respect more stylesheet changes](https://jquery.com/upgrade-guide/3.0/#breaking-change-show-hide-and-toggle-methods-now-respect-more-stylesheet-changes)
    - The code that jQuery uses to show and hide elements has been updated to focus on inline rather than computed styles.

**Comment by nao-pon** [comment]
I checked in the latest nightly, but a new problem has not been found. Thus, to close this issue.

Everyone, please re-open an issue #1584 with its details When you have found a new problem.
