### ISSUE TITLE
Folder not found: Error 

### ISSUE THREAD

**Issue by girishkv** [Studio-42/elFinder#1589]
Hi, while browsing from S3, 

 i am getting this error, here I'm able browse the direct files not the content inside the directory.
![selection_010](https://cloud.githubusercontent.com/assets/11501732/17580801/f3d6521e-5fbe-11e6-801f-d2d08dbe4243.png)

And in console , i am getting  this reponse :
{"error":["errOpen","#fls2_Q2VydGlmaWNhdGVz","errFolderNotFound"]}

The permission is public for directory in S3.

It would be great if this issue is solved.

**Comment by nao-pon** [comment]
@girishkv Isn't that an issue with elfinder-flysystem-driver or Flysystem?

- barryvdh/elfinder-flysystem-driver#44
-  thephpleague/flysystem-aws-s3-v3#46

**Comment by girishkv** [comment]
@nao-pon Thanks for your help.
 I got solution from 
barryvdh/elfinder-flysystem-driver#44
by commenting 
// return empty on failure
if (!$meta) {
    return array();
}
in vendor/barryvdh/elfinder-flysystem-driver/src/Driver.php
