### ISSUE TITLE
How to preview image and show image thumb?

### ISSUE THREAD

**Issue by winds1983** [Studio-42/elFinder#1591]
How to preview image and show image thumb? current we just show image as a icon with image name.

**Comment by nao-pon** [comment]
Please check your connector configurations [`tmbPath`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#tmbpath) and [`tmbURL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#tmburl).
