### ISSUE TITLE
Next Items on scroll

### ISSUE THREAD

**Issue by standus** [Studio-42/elFinder#1595]
Hi,
is it possible to make scroll down functionality and how?
I would like to show 20-30 files. After scroll I want to open next 20-30 files, etc.....
How to do it please?
Very important for remote files.

Has elfinder some events?

**Comment by nao-pon** [comment]
@standus API of elFinder will request the item data in the current working directory at a time. Mechanism of division acquisition is not.

**Comment by standus** [comment]
It means that it is impossible? It will rapid speed up request/response for remote files, Dropbox for example with thousands files. I just want to list some files per page (20 for example) and when I scroll down (in the end), it will send request for next 20 files.

**Comment by nao-pon** [comment]
> It means that it is impossible?

Yes, it is. That's right. elFinder is not designed to split get the cwd item data.
