### ISSUE TITLE
ftp folder trouble

### ISSUE THREAD

**Issue by Miromani4** [Studio-42/elFinder#1597]
не открываются папки в FTP диске. Полный доступ к папкам есть. 
мои настройки connector.php

>   'driver'        => 'FTP',
>     'host'          => '5.100.67.123',
>     'user'          => 'dw',
>     'pass'          => 'my pass',
>     'port'          => 21,
>     'mode'          => 'passive',
>     'path'          => '/',
>     'timeout'       => 10,
>     'owner'         => true,
>     'tmbPath'       => '',
>     'tmpPath'       => '',
>     'tmp' 		=> '',
>     'dirMode'       => 0755,
>     'fileMode'      => 0777,

помогите разобраться в данной проблеме

**Comment by nao-pon** [comment]
@Miromani4 Please set config [`debug` ](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#debug)to `true` and Please check about dialog - debug tab. 
Can you find any errors in there?

**Comment by Miromani4** [comment]
ok, debug set true.

**Comment by nao-pon** [comment]
@Miromani4 Did you solved it?

**Comment by Miromani4** [comment]
@nao-pon Unfortunately, the problem is still relevant

**Comment by nao-pon** [comment]
Steps for debug

- Connector configuration `debug` to `true`
- Enable error reporting in your connector.php
```php
error_reporting(-1); // Set E_ALL for debuging
ini_set('diaplay_errors', '1');
```
- Open elFinder and check debug tab in info dialog

Did you find any errors in that debug tab?

**Comment by Miromani4** [comment]
@nao-pon 
thank you tab activated

**Comment by Miromani4** [comment]
@nao-pon that's just the problem, that does not display debug errors, and ftp folder will still not open

**Comment by nao-pon** [comment]
elFinder doesn't show anything errors when you open a folder?

**Comment by nao-pon** [comment]
If encoding of server file system is not UTF-8, please try volume roots option [`encoding`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding) and [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale-1).

e.g.
```php
'encoding' => 'ISO-8859-5',
'locale' => 'ru_RU.iso88595',
'driver' => 'FTP',
'host' => '5.100.67.123',
'user' => 'dw',
'pass' => 'my pass',
'port' => 21,
'mode' => 'passive',
'path' => '/',
'timeout' => 10,
'owner' => true,
'tmbPath' => '',
'tmpPath' => '',
'tmp' => '',
'dirMode' => 0755,
'fileMode' => 0777,
```

**Comment by Miromani4** [comment]
@nao-pon 
the problem persists when your configurations, it seems to me that by default disabled permission to open the folder. I'm not good at php, so he would be able to understand

Thank you for helping me to understand my problem.

**Comment by Miromani4** [comment]
When you connect to another FTP server, this problem does not occur ...
I would change the FTP server to another.

**Comment by nao-pon** [comment]
OK, I will close it. Please let me know if you find any bugs of elFinder.

**Comment by vahidalvandi** [comment]
why cant create tmb file
