### ISSUE TITLE
[VD:Dropbox] API v1 is deprecated

### ISSUE THREAD

**Issue by nao-pon** [Studio-42/elFinder#1598]
On June 28, 2017, API v1 will be turned off, so it's time to move to API v2.
- https://www.dropbox.com/developers/reference/migration-guide

**Comment by standus** [comment]
When it will be ready for testing please?

**Comment by standus** [comment]
Do you plan fix it please?

**Comment by nao-pon** [comment]
@standus At the latest we want to handle up to V1 is finished, but I have not enough time now. 2017 first quarter about somehow to ...

**Comment by standus** [comment]
Time is very very fast.

**Comment by nao-pon** [comment]
There is no official APIV2 PHP SDK, so we need to select a third party SDK.

Currently there are two SDKs.
- https://github.com/kunalvarma05/dropbox-php-sdk
- https://github.com/Alorel/dropbox-v2-php

I will select [kunalvarma05/dropbox-php-sdk](https://github.com/kunalvarma05/dropbox-php-sdk). I ask for your opinion.

**Comment by standus** [comment]
When it will be ready for testing?

**Comment by nao-pon** [comment]
@standus I started coding from today. I think that it will be possible to test in a couple of days.

**Comment by nao-pon** [comment]
I done. We can be testing in [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

Thanks! 😄

**Comment by standus** [comment]
Can you publish your config for Dropbox please? I tested with my old config and it doesn`t work.
This is my config:
```
if($dropboxDB) {
    $opts['roots'][]=array(
        'driver'            => 'Dropbox2',
        'path'              => '/',
        'quarantine'        => $quarantinefiles,
        'tmpPath'           => $tmpfiles,
        'tmbPath'           => $tmbfiles,
        'tmbURL'            => $tmpurl,
        'tmbCrop'           => false,
        'tmbSize'           => 150,
        'alias'             => 'Dropbox',
        'tmbBgColor'        => 'transparent',
        'consumerKey'       => $dropbox['consumerKey'],
        'consumerSecret'    => $dropbox['consumerSecret'],
        'accessToken'       => $dropbox['accessToken'],
        'accessTokenSecret' => $dropbox['accessTokenSecret'],
        'URL'               => $url.$subFolder,
    );
}
```

**Comment by standus** [comment]
If anybody will test it on localhost with this error:
cURL error 77: error setting certificate verify locations: CAfile: C:\xampp\apache\conf\cacert.pem CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
I solved it by this solution:
http://stackoverflow.com/questions/30240840/laravel-5-socialite-curl-error-77-error-setting-certificate-verify-locations#answer-37011569

**Comment by standus** [comment]
OK Naoki, 
I think that it work as expected but I am not soo lucky. Why? You used 3rd party library which is dependent on another 3rd party libs.
In final Dropbox 2 driver needs next 125kb + 655kb depend source code. Ohh. 
In my another project I used very simple DropBox 2 class with 25kb of size: 
https://github.com/f4bsch/DropPHP/tree/api-v2 , without dependencies.
I understand that its very very simple use 3rd party code, but solutions like this is very expensive for any project. 
Kunnu DB lib is very early version v0.1.x ! Looks good how complex it is, but is it needed for EF?
When developers will using solutions like this, their projects will looks like big pile of mess. 
For only one functionality its to much code and files.
Otherwise thank you for your very good work.

**Comment by nao-pon** [comment]
I did not know DropPHP until now. The size of the library is small and good, but I think that Kunnu DB lib has versatility.
Additional third party library guzzlehttp/guzzle is also used with the Google Drive driver, it is very useful to have centralized control with composer.

By the way, it's about configure.

Changed option name `consumerKey` to `app_key` and `consumerSecret` to`app_secret` or define constant `ELFINDER_DROPBOX_APPKEY` and `ELFINDER_DROPBOX_APPSECRET`.

Dropbox2 use the OAuth2 so it need access token for OAuth2. You can get it from https://www.dropbox.com/developers/apps (Generated access token).

Code example is
```php
// load composer autoload before load elFinder autoload If you need composer
require './vendor/autoload.php';

// elFinder autoload
require './autoload.php';
// ===============================================

// Required for Dropbox network mount
// Installation by composer
// `composer require kunalvarma05/dropbox-php-sdk`
// Enable network mount
elFinder::$netDrivers['dropbox2'] = 'Dropbox2';
// Dropbox2 Netmount driver need next two settings. You can get at https://www.dropbox.com/developers/apps
// AND reuire regist redirect url to "YOUR_CONNECTOR_URL?cmd=netmount&protocol=dropbox2&host=1"
define('ELFINDER_DROPBOX_APPKEY',    'YOUR APP KEY');
define('ELFINDER_DROPBOX_APPSECRET', 'YOUR APP SECRET');
// ===============================================
```

AND

```php
array(
	'alias'        => 'elFinder@Dropbox',
	'driver'       => 'Dropbox2',
	'path'         => '/Public/elFinder',
	'access_token' => 'YOUR TOKEN You can get from https://www.dropbox.com/developers/apps',
),
```
