### ISSUE TITLE
Can you add change upload path in upload dialog?

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1600]

**Comment by nao-pon** [comment]
What about upload from folder's contextmenu?

**Comment by CodeLyokoXtEAM** [comment]
Yes. It can upload target folder.
but I think user can change upload path, selected upload button in toolbar.
(default path is current folder & click on it show tree view or something to change path)

**Comment by CodeLyokoXtEAM** [comment]
also file-types .apk .crdownload like files deny upload, after the upload.
(I know elfinder check file name before upload file, but this files are check after upload it.)

**Comment by nao-pon** [comment]
> also file-types .apk .crdownload like files deny upload massage show, after the upload.

elFinder do checking by MIME type that notified from browser, but browser does not know all file types. If elFinder does not obtained the MIME type, can not pre-check.

**Comment by CodeLyokoXtEAM** [comment]
Thanks, I understand it.

**Comment by nao-pon** [comment]
> I think user can change upload path, selected upload button in toolbar.

Its implementation is a little difficult.

I have a one draft. It is possible to select target folder of the current working directory before clicking the upload button. How is it?

**Comment by CodeLyokoXtEAM** [comment]
I think Its may complicated to users.
because if user didn't know this, user try to upload files current folder before click sub folder. its can't understand for them.

**Comment by CodeLyokoXtEAM** [comment]
I think elfinder tree view use to select folder.
![image](https://cloud.githubusercontent.com/assets/18566890/17732514/c5eb7732-648f-11e6-85fb-bbaac45ffbc0.png)

**Comment by nao-pon** [comment]
Upload dialog is modal. Therefore, to use a tree view is difficult. I am considering the selector display of child folder of the current working directory.

**Comment by nao-pon** [comment]
It's done. @CodeLyokoXtEAM Thanks! :+1:
