### ISSUE TITLE
ASP.NET connector - thumbnails are not generated

### ISSUE THREAD

**Issue by streamy878** [Studio-42/elFinder#1601]
Hello everyone! I installed ELFinder.Connector.NET from Nuget into my project. I've got a problem - the thumbnails are not generated. I built ELFinder.WebServer.ASPNet project - there are not any problem. Where is can I check the generation of images in the code? Are there any ideas on this? Thanks.

**Comment by nao-pon** [comment]
@streamy878 I think this is the ASP.NET connector problem. You can get the information in a [Wiki about Client-Server API](https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1).

- https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#information-about-filedirectory

> "tmb"    : 'bac0d45b625f8d4633435ffbd52ca495.png' // (String) Only for images. Thumbnail file name, if file do not have thumbnail yet, but it can be generated than it must have value "1"
    "alias"  : "files/images",       // (String) For symlinks only. Symlink target path.

- https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#tmb

> Background command. Creates thumbnails for images that do not have them.
