### ISSUE TITLE
Large video preview problem in configuration that disabled real path

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1602]
link to #1540

after disable real-path,
`#'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/'`
I try to preview large video file.
but my wamp-server-64 is highly decrease RAM.
but not disable real-path its work fine.
can you check it?

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM I checked 2.24GB video file on XAMPP 5.6.23 (Windows 10 64bit/RAM 4GB). There was no significant change in the amount of memory at the time of preview in my environment. Play in part read by the HTTP 206 also was started immediately.

I recommend the confirmation of the setting of the output buffering of PHP.

- http://php.net/manual/outcontrol.configuration.php

**Comment by CodeLyokoXtEAM** [comment]
thakz. Its solved after change php.ini  value to `output_buffering = 0`
