### ISSUE TITLE
Elfinder returning object object or relative path

### ISSUE THREAD

**Issue by Vartex05** [Studio-42/elFinder#1604]
Hi, I have problem with integrating Elfinder with TinyMCE4. Everything is fine, when i click on insert image in TinyMCE, Elfinder opens, then i choose image, but elfinder returns object object or relative path... I tried both methods posted on wiki, but with no result. When i use the first integration method, elfidner returns object object, and with second method elfinder returns relative path. Any ideas how to fix this problem?

**Comment by nao-pon** [comment]
@Vartex05 In first method in Wiki example, change
From
```javascript
FileBrowserDialogue.mySubmit(file);
```
To
```javascript
FileBrowserDialogue.mySubmit(file.url);
```
will be solved.

And If you need absolute URL. Please set absolute URL to volume roots option [`URL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#url).

**Comment by Vartex05** [comment]
I did that but it still returns adresses like ../../../assets/js/elfinder/files/images.png, so when i save it and  display the content of tinymce area on another site, the images wont load

**Comment by nao-pon** [comment]
Could you show me your connector configuration?

**Comment by Vartex05** [comment]
$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '../files/',                 // path to files (REQUIRED)
			'URL'           => 'http://localhost/tabule/assets/js/elfinder/files/', // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		)
	)
);

**Comment by Vartex05** [comment]
weird think is, that if u choose insert video in tinymce, elfinder returns correct adress. But in case of image it returns relative adress...

**Comment by nao-pon** [comment]
It's odd. Probably, volume driver returning relative URL in the url of the item data. Are you extend something volume driver? e.g. bind action...

As one of the solution there is a way to convert the relative URL to an absolute URL.
```javascript
getFileCallback: function(file, fm) { // editor callback
	file.url = fm.convAbsUrl(file.url);
	// do something...
}
```

**Comment by Vartex05** [comment]
I tried that solution but even after i convert url it returns relative path :/ Its really very odd

**Comment by Vartex05** [comment]
Ok i solved the problem, TinyMCE in default convertns any urls to relative... It must be tun off in settings... Anyway thx for help and your time...

**Comment by nao-pon** [comment]
Could you check in browser console like next. replace `#elfinder` to your one
```javascript
$('#elfinder').elfinder('instance').convAbsUrl('../../../assets/js/elfinder/files/images.png')
```
What is return?

**Comment by nao-pon** [comment]
OK, i got it. Congratulation!
