### ISSUE TITLE
property 'length' of undefined

### ISSUE THREAD

**Issue by standus** [Studio-42/elFinder#1606]
Hi,
today I got error:
Error: Uncaught TypeError: Cannot read property 'length' of undefined
Url: /elfinder/js/elfinder.full.js
Line: 1809
its on 

			for (i = 0; i < l; i++) {
				// only callback has argument
				if (handlers[i].length) {
					if (!allowModify) {
						// to avoid data modifications. remember about "sharing" passing arguments in js :) 
						event.data = isopen? JSON.parse(jst) : $.extend(true, {}, data);
					}
				}

I tested fast switching between mode root locations.

**Comment by nao-pon** [comment]
@standus This problem has been corrected at the same time of @b747a8c7cec914c2c652c989b8dfeb56a5e025b3.

Thanks for your reports.
