### ISSUE TITLE
Feature: Code Editor

### ISSUE THREAD

**Issue by darrylyeo** [Studio-42/elFinder#1607]
The current pop-up file editor is fine for quick and dirty changes to text files, but developers will find it much more useful to have a fully integrated code editor, such as [ACE](https://ace.c9.io/).

If nothing else, the text field should be wider and have a monospaced font.

**Comment by nao-pon** [comment]
@darrylyeo Please read [Wiki - Using custom editor to edit files within elfinder](https://github.com/Studio-42/elFinder/wiki/Using-custom-editor-to-edit-files-within-elfinder). It will be your help.
