### ISSUE TITLE
How to use files from Volume Drivers of remote files

### ISSUE THREAD

**Issue by standus** [Studio-42/elFinder#1608]
Hi,
I see that using other Drivers is not what I expected in CKEditor.
FTP Driver:
`<p><img alt="" src="/elfinder/php/connector.php?folder=images&amp;keyword=&amp;img_width=&amp;img_height=&amp;cmd=file&amp;target=f4_aS1lc2hvcC5jei9odG1sL3RlbXBsYXRlcy9kZWZhdWx0L2ltZy9mb2xkZXIucG5n"></p>`
Dropbox Driver:
`<p><img alt="" src="https://dl.dropboxusercontent.com/s/sfhdyjsvvbsfb/photo.jpg" style="width: 100px; height: 133px;"></p>`

But I want using remote files as local files. Using this way will not works for public content.
Soo, how to use/copy remote files with EF to use on local platform? Otherwise other Drivers are unusable.

I expect something like:
mydomain/files/file1.jpg
etc.

**Comment by nao-pon** [comment]
- FTP Driver
    - Please set connector roots option `URL` correctly.
- Dropbox, GoogleDrive Driver
    - Please make public link by `Get URL Link` button in info dialog.

**Comment by standus** [comment]
Thats nice, but images are always stored remotely. I want copy images to local files storage after I chose it.

**Comment by nao-pon** [comment]
@standus elFinder is can be copied between volumes. Please copy the target file to the local file system volume.

**Comment by standus** [comment]
Is anywhere some example howto do it automaticaly after I choose any remote image? Please.

**Comment by nao-pon** [comment]
This is a basic example. But it require [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip) or elFinder >= 2.1.15.

```javascript
commandsOptions : {
	getfile : {
		onlyURL  : false,
		// allow to return multiple files info
		multiple : false,
		// allow to return filers info
		folders  : false,
		// get image sizes before callback call
		getImgSize : false
	}
},
getFileCallback : function(file, fm) {
	var localId = 'l2_';
	var localTargetHash = localId + 'Lw'; // 'Lw' = '/' = root
	
	if (file.hash.indexOf(localId) !== 0) {
		var dfd = $.Deferred();
		
		fm.clipboard([ file.hash ], 0);
		
		fm.exec('paste', localTargetHash)
		.done(function(copy, paste) {
			if (paste && paste.added && paste.added.length) {
				return fm.exec('getfile', paste.added[0].hash);
			}
			dfd.reject();
		})
		.fail(function() {
			dfd.reject();
		});
		
		return dfd;
	} else {
		fm.log(file.url);
	}
}
```

**Comment by standus** [comment]
![screenshot 2016-08-21 17 39 06](https://cloud.githubusercontent.com/assets/4818430/17838171/5e401f68-67c6-11e6-9032-f54986ce7a06.png)
Not processed by : .done(function(copy, paste)

**Comment by nao-pon** [comment]
@standus [This](http://jsbin.com/tefodu/edit?html,output) is live demo. You can try Dropbox driver by netmount.

**Comment by standus** [comment]
Your demo is OK, but on my site it not works. Is it correct on screenimages?
![screenshot 2016-08-22 10 35 22](https://cloud.githubusercontent.com/assets/4818430/17848543/6255e6a8-6854-11e6-813e-91746b83141e.png)

**Comment by standus** [comment]
In scope I see errCopy.
![screenshot 2016-08-22 12 04 51](https://cloud.githubusercontent.com/assets/4818430/17851147/c6db4148-6860-11e6-88ee-633ab2b20145.png)

**Comment by standus** [comment]
I found what is the problem.
var localId = 'l2_'; //l2_
var localTargetHash = localId + 'Lw'; // 'Lw' = '/' = root

You wrote example for fixed second local location. 
I changed for my locations, but it is not dynamically. Its fixed. And mainly localTargetHash is different manytimes.

What about solution copy it to temp folder and get it from there?

**Comment by nao-pon** [comment]
Volume ID can be fixed in the connector roots option `id`.
```php
'roots'  => array(
    array(
        'driver' => 'LocalFileSystem',
        'path'   => '/path/to/files/',
        'URL'    => 'http://localhost/to/files/',
        'id'     => 'tmp_'
    )
)
```
Volume ID become "ltmp_".

Does [this post](https://github.com/Studio-42/elFinder/issues/1564#issuecomment-237479979) will be your help for localTargetHash?

**Comment by nao-pon** [comment]
Since the execution timing of the call-back of the command has changed, you need to call back in the `pastedone`.

I was fixed the [previous code example](https://github.com/Studio-42/elFinder/issues/1608#issuecomment-241255375).

**Comment by applibs** [comment]
After long time unused this feature and all updates from that time it stopped work.

**Comment by applibs** [comment]
I changed paste call like this and it is processed but with permision error:
`fm.exec("paste", null, null, localTargetHash)`
because it checking write permision for source path except destination path.

**Comment by applibs** [comment]
Ohh it has soo many bugs. Nextone:
this line:
`if (handlers[i].call(event, event, this) === false || event.isDefaultPrevented())`

never get boolean because it call this function:
`fm.bind('exec', function(e) {....`
which return void/undefined.

I would like to say, that this solution how to use remote file over copy/paste does not work.

**Comment by applibs** [comment]
How to select/focus target driver before call paste command?
