### ISSUE TITLE
Hangs when a large quantity of folders

### ISSUE THREAD

**Issue by operatorpro** [Studio-42/elFinder#1611]
So, hangs when many folders... why?(

**Comment by nao-pon** [comment]
@operatorpro How many folders in your target folder? elFinder will be heavy processing as the folder increases.

**Comment by operatorpro** [comment]
1142 folders

**Comment by operatorpro** [comment]
If you wait - the browser tab crashed

**Comment by nao-pon** [comment]
Which browser are you using? Normally, it is no problem with about 1k folders. Can you open next link(it has 7k folders)? - http://studio-42.github.io/elFinder/#elf_l1_YV9sb3Rfc2FtcGxlLzdrX2RpcnM

**Comment by operatorpro** [comment]
chrome. He opened at once. First floating, then uploaded

**Comment by nao-pon** [comment]
> First floating, then uploaded

What mean? I can't understand by my poor English skill.

**Comment by operatorpro** [comment]
Sorry, my english very bad( At first browser hung up, but minute later all downloaded

**Comment by nao-pon** [comment]
OK, Would you try the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip) in your site?

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon can you add loading first set of folders in working space & after load step by step folders set?

**Comment by nao-pon** [comment]
Since the registration process of droppable is heavy so I'll try to perform distributed processing.

**Comment by nao-pon** [comment]
I updated [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip) now. You can try latest nightly for check of this issue.

**Comment by nao-pon** [comment]
After that, I adjusted the loading method and so on. I'll close this issue.
