### ISSUE TITLE
proc_open not support my serv

### ISSUE THREAD

**Issue by 53ifbb** [Studio-42/elFinder#1612]
MyLog:
> ...
> [20-Aug-2016 19:51:57 Europe/Moscow] Предупреждение!: proc_open() has been disabled for security reasons (PATH/elfinder/elFinderVolumeDriver.class.php : 4410)
> [20-Aug-2016 19:51:57 Europe/Moscow] Предупреждение!: proc_open() has been disabled for security reasons (PATH/elfinder/elFinderVolumeDriver.class.php : 4410)
> [20-Aug-2016 19:51:57 Europe/Moscow] Предупреждение!: proc_open() has been disabled for security reasons (PATH/elfinder/elFinderVolumeDriver.class.php : 4410)
> ...

`protected function procExec(....`

Version 2.1.7 (2016-02-21) + very big fixes

**Comment by nao-pon** [comment]
@53ifbb I'll fix it. It will be check by php.ini `disable_functions`. Thanks! :+1:
