### ISSUE TITLE
Problem with uploading multiple files when one of them is uploaded by parts.

### ISSUE THREAD

**Issue by rooney1237** [Studio-42/elFinder#1614]
when you try to upload multiple files and one or more of them is uploaded by chunks the input get mixed between chunk parts and whole files. I managed to fix the problem by adding the following code.
![screenshot_1](https://cloud.githubusercontent.com/assets/14030381/17863726/8a7894a6-68a3-11e6-9a94-54e7b2ec9c42.png)

**Comment by nao-pon** [comment]
@rooney1237 Would you show this code as text?

**Comment by nao-pon** [comment]
@rooney1237 Probably fixes with next code. Please try it.
from
```javascript
							if (chunk == null) {
								self.error(self.i18n('errUploadFile', blob.name) + ' ' + self.i18n('errUploadFileSize'));
								cnt--;
								total--;
							} else {
								total += chunks;
						}
```
to
```javascript
							if (chunk == null) {
								self.error(self.i18n('errUploadFile', blob.name) + ' ' + self.i18n('errUploadFileSize'));
								cnt--;
								total--;
							} else {
								total += chunks;
								c++;
							}
```

**Comment by rooney1237** [comment]
Worked too, thank you!

**Comment by nao-pon** [comment]
Thanks. You,too. :+1:
