### ISSUE TITLE
Invalid parameters for command "resize"

### ISSUE THREAD

**Issue by tereaksmey123** [Studio-42/elFinder#1618]
if i use default elfinder.html it work for Resize plugin but i follow ur ckeditor with elfinder 2.1 and change location elfinder.html to other place .. i can upload file but resize plugin not work give an error Invalid parameters for command "resize". pls help .
+ this my php connector
```
$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '../../../media-lib/',                 // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '../../../../media-lib/', // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                   // disable and hide dot starting files (OPTIONAL)
			
		)
	)
);
```
+ my elfinder call
    

```
- $().ready(function() {
- 		var heightt = (window.innerHeight > 0) ? window.innerHeight : screen.Height;
-         var elf = $('#elfinder').elfinder({
- 			width:'100% !important',
- 			height:heightt-(51),
-            lang: 'en',             // language (OPTIONAL)
-             url : '../component/elFinder/php/connector.minimal.php'  // connector URL (REQUIRED)
-         }).elfinder('instance');            
-     });
```

**Comment by nao-pon** [comment]
@tereaksmey123 Would you show us XHR request parameters of resize command?

for example
```
cmd=resize
target=l2_c3RpYW1vYXNjaXVnYW5kbyBjb3B5IDEuanBn
width=800
height=500
quality=100
mode=resize
_=1472036024426
```

**Comment by tereaksmey123** [comment]
connector.minimal.php?cmd=resize&target=l1_TmV2ZXJ3aW50ZXItRHVuZ2VvbnMtYW5kL

```
cmd:resize
target:l1_TmV2ZXJ3aW50ZXItRHVuZ2VvbnMtYW5kLURyYWdvbnMuanBn
quality:100
mode:
_:1472041506879
```

**Comment by nao-pon** [comment]
Which version of jQuery, jQueryUI are you using?

**Comment by nao-pon** [comment]
I was editing a part of resize.js which I'm worrying about a little things. Would you try [latest nightly](https://github.com/Studio-42/elFinder/archive/2.1.zip)?

**Comment by tereaksmey123** [comment]
if i run ur default index.html (test with newest jquery-ui-1.12.0, jquery-3.1.0) it work no problem . but i move it to plugin folder store and call it with my new php file and different location. problem is resize cmd .. xhr mode is null no value is get.. i will try nightly build will confirm u

**Comment by tereaksmey123** [comment]
elfinder-2.1_n (2.1.8) both default jquery+ ui &&  jquery-ui-1.12.0+jquery-3.1.0 (test) . same problem run ur default index.html resize work 
```
cmd:resize
target:l1_MjAxNi0wOC0xMV8xNDMzNDUucG5n
width:422
height:245
quality:0
mode:resize
_:1472108796906
```
run with my new file and new location problem is mode no value get
```
cmd:resize
target:l1_MjAxNi0wOC0xMV8xNDMzNDUucG5n
quality:0
mode:
_:1472108950475
```

**Comment by nao-pon** [comment]
Were you checking with[ elFinder-2.1 latest nightly](https://github.com/Studio-42/elFinder/archive/2.1.zip)? - https://github.com/Studio-42/elFinder/archive/2.1.zip

**Comment by tereaksmey123** [comment]
thz ur link above is work right now with jquery 3.1.0 and with new location now can be resize and mode get resize value ; )
