### ISSUE TITLE
Issue calling elfinder in JQuery dialog

### ISSUE THREAD

**Issue by Yves-K** [Studio-42/elFinder#1619]
Hello,

First thank you very much for this **wonderfull tool.**..

We integrate elfinder in a jQuery dialog and it works like a charm... **most of the times**

Our intregration is in a Joomla! backoffice custom field
Current files are listed on a div,
By clicking on the div 
  => opens a new ui.dialog with an empty div in 
  => creates a elfinder instance ($div.elfinder(options))

elfinder is always loaded correctly but sometimes the root page displays just after !

any ideas ?

Best reagards

**Comment by standus** [comment]
I can confirm another issue. After I close jQuery dialog and onclose event I destroy elfinder instance by elfinder.destroy(); elfinder instance still exists.
After I reopen / reinitialize elfinder I miss search box on top right place.

**Comment by nao-pon** [comment]
@standus "destroy()" will be elFinder DOM deletes and events unbinds. Destruction of instances are not.

@Yves-K , @standus Would you show us your HTML, JavaScript code?

**Comment by Yves-K** [comment]
Hello Nao Pon, of course, here it is
	.elFinder is a class for the div in dialog.

```
$nj('.elFinder', container).each(function(){
		initFinder($nj(this));
})

function initFinder(object){
	
	var options 	= {
		url : 			'/index.php?option=com_abcvittonj&task=ajax&action=finder',
		height: 		object.height(),
		container : 	object,
		handlers : {
			select : 	function(event, finderInstance) {
						finderSelect(event, finderInstance, object);
					}
		}
	};
	
	var instance = object.elfinder(options).elfinder('instance');
	object.data('njInstance', instance);
}
```

Best regards

**Comment by nao-pon** [comment]
@Yves-K How many instance of elFinder? Is this is all at the same time of the instance is generated on loaded the page?

**Comment by Yves-K** [comment]
@nao-pon In this test we jus have one instance

Found a clue as mootols (yes there is still some mootols in J backOffice) is called as we create the elFinder instance
<img width="938" alt="elfinder-research-17" src="https://cloud.githubusercontent.com/assets/4093906/17961655/4dbb6528-6aad-11e6-8ffd-13407bb20a2e.png">

**Comment by Yves-K** [comment]
Just to confirm about Mootools and creating an instance of elFinder :

Mootools IS NOT loaded = works like a charm 
Mootools IS loaded = loads this rootpath page after elFinder is initialized.

And, yes, mootools is loaded AFTER jQuery !!! (we will try to work on this)
But this is why we use a named instance of jQuery and not '$'...

**Comment by standus** [comment]
My code is like this:
`var wHeight = jQuery(window).height();
    var fmHeight = wHeight * 0.85;
    filemanagerDialog = jQuery('<div id="filemanagerDialog"\>').dialog({
        modal: true, 
        width: "85%",
        height: fmHeight,
        title: "", 
        zIndex: 99999,
        create: function (event, ui) {
            if(elfinder) {
                elfinder.destroy();
                elfinder = null;
            }
            elfinder = jQuery(this).elfinder(opts).elfinder('instance');
        },
        close: function(event, ui) { 
            if(elfinder) {
                elfinder.destroy();
                elfinder = null;
            }
            filemanagerDialog.dialog("close");
            filemanagerDialog.remove();
        } 
    });`

**Comment by nao-pon** [comment]
@standus I found a bug in current nightly. That is enbug of @0360abe29d2e4dbbb7dbefaa370b3706ee522270. I'll fix it.

**Comment by nao-pon** [comment]
@Yves-K Are you using elfinder.full.js or elfinder.min.js? If not, please try it.

OR... How is it?
```javascript
(function($) {
    var instance = object.elfinder(options).elfinder('instance');
})(jQuery);
```

**Comment by Yves-K** [comment]
@nao-pon 
Going forward with these tests we commented lines 12064 and 12065 in 
elfinder.full.js from Version 2.1.14 (2016-07-25)

![image](https://cloud.githubusercontent.com/assets/4093906/17968927/d79f3626-6acf-11e6-9643-e8656d7d91c9.png)

An this solves the name conflict with Mootools => elFinder works then perfectly

**How can we help any futher ?**

Best regards

**Comment by nao-pon** [comment]
@Yves-K Did you get what is problem of these lines?

**Comment by nao-pon** [comment]
@standus I fixed enbug of @0360abe29d2e4dbbb7dbefaa370b3706ee522270. Would you try & check with [latest nightly](https://github.com/Studio-42/elFinder/archive/2.1.zip)?

**Comment by standus** [comment]
Looks that my bug is solved.

**Comment by nao-pon** [comment]
@standus Please see https://github.com/Studio-42/elFinder/issues/1608#issuecomment-242789577.

**Comment by standus** [comment]
Looks OK now. Thank you.

**Comment by Yves-K** [comment]
@nao-pon Hello,

In fact we just commented **self.trigger('load');**
That is calling **any 'load' event binded by any library to any element** of the DOM tree in current selector.

This caused the problem with Mootools.

on('load') seems only used in (12131)
```
fm.bind('load', function() {
	swipeHandle = $('<div class="elfinder-toolbar-swipe-handle"/>').appendTo(fm.getUI());
	if (swipeHandle.css('pointer-events') !== 'none') {
		swipeHandle.remove();
		swipeHandle = null;
	}
});
```

Perhaps a simple function could do the job ?

**Comment by nao-pon** [comment]
@Yves-K I replaced `self.trigger('load')` to `fm.trigger('toolbatload')`. Thanks! :+1:
