### ISSUE TITLE
resize crop rotate button disable when call in difference location from default

### ISSUE THREAD

**Issue by tereaksmey123** [Studio-42/elFinder#1620]
file from  [ https://github.com/Studio-42/elFinder/archive/2.1.zip](https://github.com/Studio-42/elFinder/archive/2.1.zip)
![2016-08-25_150306](https://cloud.githubusercontent.com/assets/21218369/17961336/4a1f38ae-6ad5-11e6-9da7-bb962eb5b3f0.png)
![2016-08-25_150337](https://cloud.githubusercontent.com/assets/21218369/17961337/4a663178-6ad5-11e6-9444-fc49ee026ffe.png)

**Comment by nao-pon** [comment]
@tereaksmey123 I edited a little. Would you try & check with [latest nightly](https://github.com/Studio-42/elFinder/archive/2.1.zip)?

**Comment by tereaksmey123** [comment]
default elfinder.html work Normal, on difference location resize button when click error .
`jquery-ui.min.js:8 Uncaught TypeError: Cannot read property 'classes' of undefined`

**Comment by nao-pon** [comment]
Probably, jQuery and some other libraries have caused the collision. Please to resolve this conflicts.

**Comment by tereaksmey123** [comment]
thz... disable button fix but a sad thing i remove each js and found it conflicts with bootstrap.min.js.. is there any way to make it work and can use bootstrap.min.js together ?

**Comment by nao-pon** [comment]
OK. This is duplicate to #1398. Please check #1398.
