### ISSUE TITLE
Group Roots

### ISSUE THREAD

**Issue by BitStinker** [Studio-42/elFinder#1622]
This may be useful for others also.

I have a system where users can access files and folders directly on a NAS. The web app can also access these via FTP. The web app also generates its own files in its own file system not on the NAS. So, I have the elFinder set to give access to both folders. I would like to "pretty" it up by grouping the folders.

Now:
FT1760-Proj (on the NAS via FTP)
FT1760-CuEx (on the local web app file system)

Want:
FT1760 (dummy grouping folder)
--Proj
--CuEx

Maybe make a special 'root' that is an array of roots with just an alias?

Here is a snip of what it looks like now

![image](https://cloud.githubusercontent.com/assets/9723336/17976365/fd0bfd96-6aa1-11e6-9a11-d4d84e4dfa7f.png)

**Comment by nao-pon** [comment]
@BitStinker It good idea! :+1:

**Comment by nao-pon** [comment]
@BitStinker I have implemented this. Please refer to the [Wiki](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#roots).

- https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#roots
- https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#phash-elfinder--2115

**Comment by BitStinker** [comment]
I see version 2.1.14, but not 2.1.15 in the releases. Am I missing something?

![image](https://cloud.githubusercontent.com/assets/9723336/18033202/af41be16-6cd1-11e6-8f1d-30ee11a77c65.png)

**Comment by nao-pon** [comment]
@BitStinker 2.1.15 has not been released yet. Until the release You can try the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by BitStinker** [comment]
Perhaps I am not understanding properly. The hash value of the volume is required to fill in phash, but the volume has not yet been mounted when setting up the configuration. How does one assume a volume hash value when it is not yet defined?

**Comment by nao-pon** [comment]
@BitStinker Volume ID is determined in the following manner.

- $volume->driverId + [Incremental numbers] + '_'
or
- $volume->driverId + $volume->options['id'] + '_'

Thus, it is possible to control by the volume roots option `id`.

**Comment by BitStinker** [comment]
Works like a charm! 

For the uninitiated, the hash for the group volume appears to be

$volume->driverId + $volume->options['id'] + '_Lw'

where the ending "Lw" is the hash for "/".

![image](https://cloud.githubusercontent.com/assets/9723336/18056295/290d3948-6dc0-11e6-9ea9-2e1ff12e6c1d.png)

**Comment by jaime070791** [comment]
Hi good day!
I do not quite understand how they could connect to a NAS disk, could you give me an example?
I need to connect to a NAS disk that is in the path "smb://192.168.xxx.xx/folder" on Linux.
I would be very grateful.

**Comment by BitStinker** [comment]
I FTP to the NAS using the elfinder FTP volume. I actually do it to two different NAS boxes. One onsite, the other offsite.

**Comment by jaime070791** [comment]
Hello @BitStinker
And you know how to connect to the NAS by SMB (Samba) and if possible ?.
A greeting.

**Comment by BitStinker** [comment]
I don't know if it is possible without using FTP. Sorry.
