### ISSUE TITLE
Invalid backend response. Data is not JSON.

### ISSUE THREAD

**Issue by paul-100** [Studio-42/elFinder#1625]
Hi,

I am getting the above error, i thought it was an easy install, i am using php5.5.9, renamed the connector files and still getting the error please assist

![image](https://cloud.githubusercontent.com/assets/9849488/18015354/0c1aba64-6bd0-11e6-87f2-1b1f848d083d.png)

**Comment by CodeLyokoXtEAM** [comment]
Is you edit 'connector.minimal.php-dist' to 'connector.minimal.php' ?

**Comment by paul-100** [comment]
@CodeLyokoXtEAM yes renamed the files plus the jqueryui was incorrect there is no such thing as 1.12.0

**Comment by CodeLyokoXtEAM** [comment]
Can show your network tab (not consol tab) after the page refresh.

**Comment by paul-100** [comment]
![image](https://cloud.githubusercontent.com/assets/9849488/18015819/025ad9bc-6bd2-11e6-8b1a-0a7f278bd97f.png)

**Comment by CodeLyokoXtEAM** [comment]
You using elfinder.src.html ?

**Comment by paul-100** [comment]
no elfinder.html which i renamed to index.html

**Comment by CodeLyokoXtEAM** [comment]
Please try elfinder.src.html

**Comment by paul-100** [comment]
i don't have such file in my download I am using elfinder-2.1

**Comment by CodeLyokoXtEAM** [comment]
Please try 
https://github.com/Studio-42/elFinder/archive/master.zip

**Comment by paul-100** [comment]
i am downloading it i will let you know in a few

**Comment by paul-100** [comment]
same issue

![image](https://cloud.githubusercontent.com/assets/9849488/18016246/11b028de-6bd4-11e6-9b48-3a1d5aa741e0.png)

**Comment by CodeLyokoXtEAM** [comment]
Oky. This issue can only handle @nao-pon please wait his respond for this.

**Comment by dleffler** [comment]
This may not be the case, but if PHP has spit out any warnings/errors from like XDebug, it'll mess pu the JSON record and appear as bad JSON. In the Browser Developer, Network Tab you might try selecting 'XHR' instead of 'JS' filter, reloading elFinder and when you see the url being called via AJAX, you can click on it and be able to see the raw response, a preview, headers, etc...

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon I think ubuntu server has diferent relative path sys.

**Comment by nao-pon** [comment]
@paul-100 It is probably PHP is causing something error. `error_reporting (-1);` the in addition to connector.php, please check the error log of PHP.

**Comment by paul-100** [comment]
Actually i was able to fix it, by installing `apt-get install libapache2-mod-php7.0 ` for ubuntu 16.04
