### ISSUE TITLE
Normalize plugin not works

### ISSUE THREAD

**Issue by fullflash** [Studio-42/elFinder#1627]
Autoresize plugin works but getting error cannot connect backend error 500
Normalizer Plugin not working here is error log

```
'upload.pre mkdir.pre mkfile.pre rename.pre archive.pre ls.pre'=>array(
                        'Plugin.Normalizer.cmdPreprocess'
                    ),
                    'ls'=>array(
                        'Plugin.Normalizer.cmdPreprocess'
                    ),
                    'upload.presave' => array(
                        'Plugin.AutoResize.onUpLoadPreSave',
                        'Plugin.Normalizer.onUpLoadPreSave'
                    )

...
'plugin' => [
                    'AutoResize' => [
                        'enable' => true,
                        'maxWidth'  => 1000,
                        'maxHeight'  => 1000,
                        'quality' => 90
                    ],
                    'Normalizer' => [
                        'enable'    => true,  // For control by volume driver
                        'nfc'       => false,  // Canonical Decomposition followed by Canonical Composition
                        'nfkc'      => false,  // Compatibility Decomposition followed by Canonical
                        'lowercase' => true, // Make chars lowercase
                        'convmap' => [
                            ' ' => '_',
                            ',' => '_',
                            '^' => '_',
                            'à' => 'a',
                            'ä' => 'a',
                            'é' => 'e',
                            'è' => 'e',
                            'ü' => 'u',
                            'ö' => 'o',
                            'ə' => 'e',
                            'ı' => 'i',
                        ]
                    ],
```

 exception 'yii\base\ErrorException' with message 'Call to undefined method elFinder::getOptionsPlugin()' in project...\\vendor\studio-42\elfinder\php\plugins\Normalizer\plugin.php:132
Stack trace:
#0 project...\\vendor\studio-42\elfinder\php\elFinder.class.php(702): elFinderPluginNormalizer->cmdPreprocess()
#1 project...\\vendor\studio-42\elfinder\php\elFinder.class.php(702): ::call_user_func_array:{project...\\vendor\studio-42\elfinder\php\elFinder.class.php:702}()
#2 project...\\vendor\studio-42\elfinder\php\elFinderConnector.class.php(125): elFinder->exec()
#3 project...\\vendor\mihaildev\yii2-elfinder\views\connect.php(10): elFinderConnector->run()

**Comment by nao-pon** [comment]
@fullflash Would you try & check with [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip)?

**Comment by fullflash** [comment]
i am using mihaildev elfinder wrapper i can't just change the build
sanitize plugin is just a simple plugin it is weird 2.1 version and this plugins don't work.

anyway thanks

**Comment by nao-pon** [comment]
You can install nightly build with `composer require studio-42/elfinder:2.1.x-dev`.
