### ISSUE TITLE
"Unable to upload <file name>. <filename> transfer error."

### ISSUE THREAD

**Issue by wamft** [Studio-42/elFinder#1628]
I have been using elfinder for a while now and lately I have been getting a "Unable to upload <file name>. <filename> transfer error."

What is causing this error please and how do I fix it?

I use it on two different web hosting setups and both have issues in uploading files.

**Comment by nao-pon** [comment]
@wamft At first, please try & check with [latest nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by wamft** [comment]
I have installed the latest nightly pack but no change. Still unable to upload the file.

**Comment by nao-pon** [comment]
I updated nightly build for easy debugging. Please try latest nightly again, and check section "upload" in debug tab in dialog "About this software". (Don't forget clear cache of your browser)

![fireshot capture 5 - elfinder 2 1 x - file manager for web_ - http___studio-42 github io_elfinder_](https://cloud.githubusercontent.com/assets/1412630/18082918/d2a54650-6edb-11e6-87dd-5b224c1947a4.png)

**Comment by wamft** [comment]
Getting an upload error code: 3

What is this?

**Comment by nao-pon** [comment]
@wamft This is an error of PHP. Please search on the web.

- e.g. https://www.google.com/search?q=php+upload+file+error+code+3
