### ISSUE TITLE
Hide Toolbar Options

### ISSUE THREAD

**Issue by yc-public** [Studio-42/elFinder#1629]
Recently i downloaded a 2.0 night build, the toolbar options are too much for me, i wishes to hide some of them, how could i do this? i means in which files i can configure something like hide/disabled array options?  Please give a specific answer thanks

**Comment by nao-pon** [comment]
@yc-public Please set the [`desabled`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#disabled) ([commands list](https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#command-list)) of volume roots option to disable the function and the display of the command. If may be a limitation of only on the display, please set the [`uiOptions.toolbar`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#uioptions) and [`contextmenu`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#contextmenu) of the client option.
