### ISSUE TITLE
Image Droppable Field sending to connector

### ISSUE THREAD

**Issue by Yves-K** [Studio-42/elFinder#1632]
Hello,
We realy LOVE elFinder more and more ;-)

Thinking of users profile pictures or instant easy slider and so many situations users need to just drop one or a few image(s).

We could create a tiny jquery pluging (or function for your plugin) allowing  a single text area to  :  
- display images (get them from connector) 
- allow drop of image(s) (and send them to connector)

What's the idea :
- elFinder has a serious and robust architecture
- Great authentication ant path management in the background
- It can use extensions on the background (resizing and so much more)
- We just have to configure a new port to the connector

Befor we go on we'd like to know :
- did we miss something and it's already available ?
- is someone requesting or still working on this ?
- do you have (or imagine) a prefered way to do it ?
- do you prefer us to do it on our own or try to extend your library ?
- can we reuse parts or your library ?

Anyway, it's a real pleasure to work with your tool and we will try to help.

Best regards

**Comment by nao-pon** [comment]
@Yves-K Thanks for your post. I'm not sure yet, that detail. Would you show us something example or PR?

**Comment by Yves-K** [comment]
@nao-pon 
OK, we'll create a smple an then discuss about it
Best regards

**Comment by Yves-K** [comment]
@nao-pon 
Hello, after a while we come back to this idea...

I just would like to create a droppable div where a user can drop images (easy)
Then i'd like to **send this image to the server using the elFinder connector** using JS.

Any idea on how to do this ?

**Comment by nao-pon** [comment]
@Yves-K Where from do you want to drag? And what data is image?

**Comment by Yves-K** [comment]
@nao-pon Hello Nao Pon,

Yes, this is the excellent elFinder user interface.
When you drop images or documents it SENDS data to the elFinder connector.
This connector is excellent too !

What i imagine is a simple <div /> accepting drops (so easy to do)
and i'd like to send this dropped imgae (or doc) to the same elFinder connector.

Think about a user profile with a picture.
We dont want the user to open a dialog, select a directory, drop his image, select it and validate the dalog.
We just want the user to drop his/her picture in the <div /> and its done.

The question is :  How do i call the connector, what ajax parameters do i need ?

**Comment by nao-pon** [comment]
@Yves-K You can use `elFInderInstance.upload()` to file uploading.

- Live example is [here](http://jsbin.com/gafive/edit?html,output).
```javascript
var elf = $('#elfinder').elfinder({
	url : '//hypweb.net/elFinder-nightly/demo/2.1/php-jsb/basic.php'
}).elfinder('instance');
$('#dropfield')
	.on("dragenter", function(e){
		e.stopPropagation();
		e.preventDefault();
	})
	.on("dragover", function(e){
		e.stopPropagation();
		e.preventDefault();
	})
	.on('drop', function(e) {
		e.stopPropagation();
		e.preventDefault();
		var target = 'l3_Lw';
		var file = false,
			type = '',
			data = null,
			trf = e.originalEvent.dataTransfer || null,
			kind = (trf.items && trf.items.length && trf.items[0].kind)? trf.items[0].kind : '';

		if (trf) {
			if (kind === 'file' && (trf.items[0].getAsEntry || trf.items[0].webkitGetAsEntry)) {
				file = trf;
				type = 'data';
			} else if (kind !== 'string' && trf.files && trf.files.length && $.inArray('Text', trf.types) === -1) {
				file = trf.files;
				type = 'files';
			}
		}
		if (file) {
			elf.upload({files : file, type : type, target : target})
				.done(function() {
					elf.exec('open', target);
				});
		}
	});
```
