### ISSUE TITLE
Filename Alias

### ISSUE THREAD

**Issue by BitStinker** [Studio-42/elFinder#1633]
Another enhancement that might be useful is the ability to set an alias for a file. Perhaps in the accessControl function, e.g.,

```
function access( $attr, $path, $data, $volume ) {
	$ret = null;
	
	if( $attr == 'alias' ) {										// new $attr
		$bn = basename( $path );
		if( $bn == "__quote2.pdf" )									// alias __quote2 --> Proposal
			$ret = "Proposal.pdf";
		else if( $bn == "__quote.pdf" )								// alias __quote --> Quote
			$ret = "Quote.pdf";
		else if( strpos( $bn, "__install" ) === 0 )					// alias __install --> Phase_??
			$ret = "Phase_" . laborPhase( $bn ) . ".pdf";
	} else if( $attr == 'hidden' ) {								// ...or...
		$path_info = pathinfo( $path );
		if( isset( $path_info[ 'extension' ] ) && strlen( $path_info[ 'extension' ] ) > 0 ) {
			$ret = !preg_match( "/^({$data})/", $path_info[ 'basename' ] );
		}
	}
	
	return $ret;
}
```

In my application there are a number of files that are named for machine use that are pretty unfriendly to users. So, being able to alias those would be very cool. I suppose one could also alias subfolder names using the same idea.

In the same vein, it would be nice to know the mime type of the $path sent to the accessControl function. This would allow one to hide files without an extension but still show folders.

Just a thought.

**Comment by nao-pon** [comment]
@BitStinker Perhaps, it will connector's [`bind`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind) option is your help.

**Comment by BitStinker** [comment]
Perfect!
