### ISSUE TITLE
Extract button hidden

### ISSUE THREAD

**Issue by consc198** [Studio-42/elFinder#1637]
Hey guys,

I was wondering whether there are any server-side dependencies for the extract button? We've integrated Elfinder into our own private Wordpress plugin and the extract button shows and works fine on my test VPS but the extract button isn't showing on my client servers.

Both my test VPS and client servers are using Ubuntu 14.04 LTS however maybe there is a specific dependency that is needed?

Thanks in advance for the help

**Comment by consc198** [comment]
Actually i'm going to update this issue myself.

If I specify a specific directory in Elfinder such as /srv/users/serverpilot/apps/0default/public (that is the web root) the extract button works fine.

If i specify a directory in Elfinder such as /srv/users/serverpilot/apps/ the extract button hides.

Why does this issue occur?

**Comment by consc198** [comment]
Sorry again for bumping this, it seems the issue is caused by the fact that /srv/users/serverpilot/apps/ is chowned to root:serverpilot - if we chown that directory to serverpilot:serverpilot the exctract command displays fine.

Do you think there is any workaround we can code within the file manager to resolve this issue without needing to chown the apps directory to root:serverpilot ?

**Comment by nao-pon** [comment]
@consc198 Probably, volume roots option [`quarantine`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#quarantine) will be your help. Please try set to writable directory.

**Comment by consc198** [comment]
@nao-pon thanks for that, using the quarantine option fixed the issue for us!

Keep up the great work with elfinder, its probably the best file managers out there!
