### ISSUE TITLE
Passing data to a handler

### ISSUE THREAD

**Issue by BitStinker** [Studio-42/elFinder#1639]
Is it possible to pass data to an event handler? For example, I have revision folders

Revision 1
Revision 2
Revision 3
Revision 4
...

I would like to pass which revision is "active" so I can list these as

Revision 1
Revision 2 (Active)
Revision 3
Revision 4
...

This is just too much fun!

Thanks!

**Comment by nao-pon** [comment]
@BitStinker #1524 will help you?

**Comment by BitStinker** [comment]
Actually, I came up with a solution by just creating the event handler on the fly in the PHP script.

But thanks for that link. It will be useful in other ways!
