### ISSUE TITLE
ctrl+shift while fileselecting does not work properly

### ISSUE THREAD

**Issue by Pruegeler** [Studio-42/elFinder#1646]
If you select some items in the filelist with control and then select an area of items with control + shift, then the area is not selected from the last selected item but from the next item to top.

for example:
filelist: 1.ex, 2.ex, ...., 10.ex
select file 1.ex, 8.ex and 6.ex while pressing ctrl, then keep pressing ctrl and pressing shift to click on the file 4.ex. It should now be selected file 1.ex, 8.ex, 4.ex -> 6.ex, but file 1.ex -> 4.ex, 6.ex, 8.ex are selected.

It is tested with the demo of elFinder on "http://studio-42.github.io/elFinder/"

**Comment by Pruegeler** [comment]
Edited

**Comment by nao-pon** [comment]
@Pruegeler Thanks for your report. I'll fix it. :+1:
