### ISSUE TITLE
Howto: Multi User with PDO script

### ISSUE THREAD

**Issue by viraladmin** [Studio-42/elFinder#1648]
I thought I would share this as it took me a while to find the solutions and thought it may be beneficial to others. 

So I have a script entirely written in pdo. I am not fluent with mysqli, so re-writing this to work in pdo was not an option. So to make it work multi-user I did some very unconventional things, but they work rather well. 

**First**:
In connector.php I added an include line for my own pdo database connections.
`include $_SERVER['DOCUMENT_ROOT'] . '/includes/config.php';`

**Second**:
I went into my cpanel, and create a table just for the use of elFinder.

**Third**:
In my includes/config.php file I created a pbo connection for the new database:
```
try {
	//create PDO connection
	$db2 = new PDO("mysql:host=".DBHOST.";dbname=".DBNAME2, DBUSER2, DBPASS2);
	$db2->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

} catch(PDOException $e) {
	//show error
    echo '<p class="bg-danger">'.$e->getMessage().'</p>';
    exit;
}
```

**Fourth**:
In connector.php I set the driver to MySQL, the path to 1 and the url to 0.
```
		array(
			'driver'        => 'MySQL',   // driver for accessing file system (REQUIRED)
			'path'          => 1,         // path to files (REQUIRED)
			'URL'           => 0, // URL to files (REQUIRED)
			'accessControl' => 'access'             // disable and hide dot starting files (OPTIONAL)
		)
```

**Fifth**:
In elFinderVolumeMySQL.class.php I set the files_table to use the user sessions from my members database.
```
	public function __construct() {
$username = $_SESSION[username];
		$opts = array(
			'host'          => 'localhost',
			'user'          => '',
			'pass'          => '',
			'db'            => '',
			'port'          => null,
			'socket'        => null,
			'files_table'   => 'elfinder_file_'.$username,
			'tmbPath'       => '',
			'tmpPath'       => ''
		);
```

**Sixth**:
In elFinderVolumeMySQL.class.php I added a test to see if the user has a files table, and if not to create one, and to insert the correct data if it does not exist. This code is added just before the line _$this->db->set_charset('utf8');_
```
$this->db->query("CREATE TABLE IF NOT EXISTS elfinder_file_".$username." (
  `id`        int(7) unsigned NOT NULL auto_increment,
  `parent_id` int(7) unsigned NOT NULL,
  `name`      varchar(256) NOT NULL,
  `content`   longblob NOT NULL,
  `size`      int(10) unsigned NOT NULL default '0',
  `mtime`     int(10) unsigned NOT NULL,
  `mime`      varchar(256) NOT NULL default 'unknown',
  `read`      enum('1', '0') NOT NULL default '1',
  `write`     enum('1', '0') NOT NULL default '1',
  `locked`    enum('1', '0') NOT NULL default '0',
  `hidden`    enum('1', '0') NOT NULL default '0',
  `width`     int(5) NOT NULL,
  `height`    int(5) NOT NULL,
  `time`      TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY  `parent_name` (`parent_id`, `name`),
  KEY         `parent_id`   (`parent_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci");


$res1 = $this->query("SELECT COUNT(*) AS cnt FROM elfinder_file_".$username." WHERE id='1'");
$r = $res1->fetch_assoc();
if ($r[cnt] == '0') {
$this->db->query("
INSERT INTO elfinder_file_".$username."
(`id`, `parent_id`, `name`,     `content`, `size`, `mtime`, `mime`,      `read`, `write`, `locked`, `hidden`, `width`, `height`) VALUES 
('1',  '0',         'DATABASE', '',        '0',    '0',     'directory', '1',    '1',     '0',      '0',      '0',     '0');
");
}
```

Note I also added a time field that auto increments so I could sort the data based on time outside of elFinder.

At this point, the data can be accessed anywhere in a PDO script just as one would normally call data from a database. 

Example:
```
if ($db2->query(
                   "SHOW TABLES LIKE 'elfinder_file_".$username."'"
               )->rowCount() > 0
   ){

$stmt=$db2->prepare("SELECT * FROM elfinder_file_".$username." WHERE mime <> 'directory'  AND size < '50000' ORDER BY time LIMIT 18");
$stmt->execute();
$row = $stmt->fetchAll();

foreach ($row AS $row) {
echo '<a rel="group" href="#" onclick="$.fancybox.open({href:\'data:'.$row[mime].';base64,'.base64_encode( $row['content'] ).'\'});">
<img src="data:'.$row[mime].';base64,'.base64_encode( $row['content'] ).'" class="img-polaroid" /></a>';
} }
```

Not sure if this will help anyone or if this was the wrong place to post this or what have you, but I truly hope others find this helpful in some way, and if this is posted in the wrong place, my apologies.

**Comment by nao-pon** [comment]
@viraladmin Thank you for sharing your ideas. Would you please make a page with same contents to the Wiki?
