### ISSUE TITLE
download file more than 1GB failed !

### ISSUE THREAD

**Issue by johnstevewang** [Studio-42/elFinder#1650]
i configured the connector.minimal.php on my web server like this:
$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '/usr/local/apache/htdocs/www/download',                 // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../download', // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		)
);

when I download file size larger than 1GB  from web ,then faield on 1GB downlogding?
how can I configure the download size?

**Comment by nao-pon** [comment]
@johnstevewang elFInder doesn't has any configurations about download size. Please chack your server configrations (e.g. [PHP - `output_buffering` to `0`](http://php.net/manual/outcontrol.configuration.php)).
