### ISSUE TITLE
Howto: Get thumbnails outside elFinder

### ISSUE THREAD

**Issue by rzegwaard** [Studio-42/elFinder#1651]
I'm using elFinder to let users maintain there image-library.
The uploaded images are being used in an external application.
This application also need to get the thumbnails.

How can i find/download the thumbnails of each image?

**Comment by rzegwaard** [comment]
To be more precise:
I need to write a callback-function which gets the full path / url to a image-file which is under control of elFinder, and returns the url of the thumbnail.

Thanks in advance for any help.

Robert

**Comment by nao-pon** [comment]
@rzegwaard There is a answer in https://github.com/Studio-42/elFinder/issues/277#issuecomment-6158683. ;-)

>
```javascript
commandsOptions : {
  getfile : {
    onlyURL : false
  }
},
getFileCallback : function(file, fm) {
  console.log(file.tmb);
}
```

**Comment by rzegwaard** [comment]
Hi Nao-Pon, 
Thanks for your reply.
Your funcion is on the client-side (javascript).
I need to do this in php (server-side).
Any solution?

**Comment by nao-pon** [comment]
Standard of the file name of the thumbnail is a hash + timestamp + ". png". Please refer to #1564 about hash. Or, please refer to #1515 if you want to control the file name of the thumbnail.
