### ISSUE TITLE
Volume info isn't show correctly

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1652]
Right click volume & click get info.
You can see its shows it is folder & icon is also like a folder.

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks! :+1:

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon still not correct volume type is show its a folder.
Also volumes add to place its icon like a folder.

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon how to remove folders in place on mobile browser?
