### ISSUE TITLE
How can I set the default owner/group of the uploaded files?

### ISSUE THREAD

**Issue by ecsumed** [Studio-42/elFinder#1661]
How can I set the ownership of the uploaded file depending on the logged in user?

As it stands, I've added the code to dynamically change the root directory based on the login with something like:

'path'   => '/mydir/.$_SESSION['var1'],

But I haven't been able to change the ownership yet. Is there a setting similar to dirMode or fileMode that can change the ownership and the group?

If not, can you please point me in the best direction for me to implement it?

**Comment by nao-pon** [comment]
@ecsumed You can use connector main option [`bind`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind).

For example.
**PHP should have been run in the super-user privileges.**
```php
$opts = array(
    'bind' => array('upload' => array('uploadCallBack')),
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    )
);

function uploadCallBack($cmd, $result, $args, $elfinder, $volume) {
    if ($volume && $result && isset($result['added'])) {
        $user = 'user';
        $group = 'group';
        foreach($result['added'] as $item) {
            if ($file = $volume->file($item['hash'])) {
                $path = $volume->getPath($item['hash']);
                chown($path, $user);
                chgrp($path, $group);
            }
        }
    }
}
```

**Comment by toastbrotch** [comment]
when your callback function returns true, elfinder will refresh...
