### ISSUE TITLE
Know the current folder when loading the page

### ISSUE THREAD

**Issue by jesusvpct** [Studio-42/elFinder#1663]
I want to set the title of the page of the current main folder (when loaded with a link with hash) with javascript. I've seen the elfinder-path element, but when I get the data, it's only `&nbsp; `

How can I get the folder name when page is loaded? (This is only for main path loaded with a link with hash of the folder)

Thanks.

**Comment by nao-pon** [comment]
@jesusvpct you can use open cmd [`handlers`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#handlers).

```javascript
var options = {
	url	 : 'php/connector.php',
	handlers : {
		open : function(ev, fm) {
			var path = ev.data.options.path;
			fm.log(path); // shows into browser console
		}
	}
}
$('#elfinder').elfinder(options);
```

**Comment by jesusvpct** [comment]
Good! That's working fine. But I've changed to ev.data.cwd.name to get the folder name. Thank you so much!!!!!
