### ISSUE TITLE
Weird issue with forward slash added to all single quotes

### ISSUE THREAD

**Issue by consc198** [Studio-42/elFinder#1664]
Hello,

One of our users reported an issue issue with editing files in the file manager, lets say for example I have a file with the following in it:

define('WP_MEMORY_LIMIT', '256M');

After editing the file and saving it, it will be saved as: (notice the forward slashes)

define(\'WP_MEMORY_LIMIT\', \'256M\');

I'm sure its probably something i'm missing on my end in the file manager configuration but i'm not sure what it would be.

**Comment by nao-pon** [comment]
@consc198 If you are integrated with any other system (WordPress?), It seems to $_POST and $_GET etc values has been escaped by that system. Please restore to the original values before processing with elFinder, or please try the following example.

```php
class My_elFinderConnector extends elFinderConnector
{
	protected function input_filter($args) {
		if (is_array($args)) {
			return array_map(array(& $this, 'input_filter'), $args);
		}
		$res = str_replace("\0", '', $args);
		$res = stripslashes($res);
		return $res;
	}
}

// run elFinder
$connector = new My_elFinderConnector(new elFinder($opts));
$connector->run();
```

**Comment by consc198** [comment]
Yes we did integrate elfinder into a wordpress plugin, I will try your suggestion and report back

**Comment by consc198** [comment]
Just to confirm where would I place that code? in the connector.minimal.php file or some other file?

**Comment by nao-pon** [comment]
@consc198 Probably, elfinder.php if you are using https://ja.wordpress.org/plugins/file-manager/ .

**elfinder.php**
```php
<?php
class My_elFinderConnector extends elFinderConnector
{
    protected function input_filter($args) {
        if (is_array($args)) {
            return array_map(array(& $this, 'input_filter'), $args);
        }
        $res = str_replace("\0", '', $args);
        $res = stripslashes($res);
        return $res;
    }
}

/**
 * 
 * Security check. No one can access without Wordpress itself
 * 
 * */
defined('ABSPATH') or die();

// Including necessary files
include_once( 'php' . DS . 'elFinderConnector.class.php' );
include_once( 'php' . DS . 'elFinder.class.php' );
include_once( 'php' . DS . 'elFinderVolumeDriver.class.php' );
include_once( 'php' . DS . 'elFinderVolumeLocalFileSystem.class.php' );

/**
 * 
 * elFinder class to manipulate elfinder
 * 
 * */

class FM_EL_Finder{
	
	// Important data
	
	/**
	 * 
	 * @var array $base_path Base url(s) for the current user
	 * 
	 * */
	public $base_path;
	
	/**
	 * 
	 * Constructor function
	 * 
	 * */
	public function __construct(){
	
		
	}
	
	/**
	 * 
	 * Connect function
	 * @return object
	 * 
	 * */
	public function connect($options){
		
		return new My_elFinderConnector(new elFinder($options));
		
	}
	
}
```

**Comment by consc198** [comment]
@nao-pon i've added the code as per your instructions but unfortunately it seems the issue still exists

**Comment by nao-pon** [comment]
@consc198 I was checked. elFinder that are included in the [WP plugin](https://wordpress.org/plugins/file-manager/) is no problem that is measures already. When the elFinder directory overwrite with the our project original source code and this problem has occurred, but has been improved by measures that I showed.

I do not know any more of it. Please ask the WP plugin developers.

**Comment by consc198** [comment]
@IsaacHub thanks a lot, I just tried that aswell and it fixed the issue for me aswell!
