### ISSUE TITLE
How To Disable Keyboard Delete in elFinder ?

### ISSUE THREAD

**Issue by desawarna** [Studio-42/elFinder#1665]
I am using elFinder , I want user can not delete using Delete Keyboard / How to **disable Delete** Key in elFinder ?

**Comment by nao-pon** [comment]
@desawarna We can use client configuration [`commandsOptions`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#commandsoptions).

```javascript
commandsOptions : {
	rm : {
		shortcuts : []
	}
}
```

**Comment by desawarna** [comment]
Thank , It Works
