### ISSUE TITLE
Detect whose was delete the file & folder

### ISSUE THREAD

**Issue by neong** [Studio-42/elFinder#1668]
I really love your product. However, I was one question,  can system detect whose was delete, move, rename the file and folder? Thanks.

**Comment by nao-pon** [comment]
@neong Please check connector main option [`bind`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind) or client option [`handlers`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#handlers) in the Wiki.

**Comment by nao-pon** [comment]
@neong Did you solve it?

**Comment by neong** [comment]
Sorry for that. Recently a bit busy and not yet try it out. However, after
going thru the document. I think that was what I want. Thanks. Bro.
