### ISSUE TITLE
How To Streaming PDF on elFinder 

### ISSUE THREAD

**Issue by desawarna** [Studio-42/elFinder#1672]
Hi, friends
I want streaming PDF on browser using elFinder.
How To Streaming PDF on elFinder  ?

**Comment by nao-pon** [comment]
@desawarna THere is a connector volume roots option [`dispInlineRegex`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#dispinlineregex). Please try use it.

e.g.
```php
'dispInlineRegex' => '^(?:image|(?text/plain|application/pdf)$)'
```

**Comment by desawarna** [comment]
Thans sir ,

Which files that I will edited

Sorry I am a newbie :smile:

**Comment by nao-pon** [comment]
`dispInlineRegex` is a connector volume roots option. Please check out [Wiki](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1).

Standard in the distribution file is [connector.minimal.php](https://github.com/Studio-42/elFinder/blob/master/php/connector.minimal.php-dist).

**Comment by desawarna** [comment]
Thanks very much Sir, 
i Will try It.

**Comment by netdeveloper1job** [comment]
Hi
I want streaming Word and excel on browser using elFinder.
How To Streaming  Word and excel on elFinder ?
