### ISSUE TITLE
Problem with function sessionWrite()

### ISSUE THREAD

**Issue by thanhansoft** [Studio-42/elFinder#1673]
Hi all,
I'm using Elfinder version 2.1.9, everything works normally. But I find this line error messages with IDE Phpstorm

$this not use in static function
public static function sessionWrite() {
        $this->session->close();
    }

see picture: http://s17.postimg.org/pp0m5avj3/2016_09_26_202748.png

it can affect secure?

**Comment by nao-pon** [comment]
@thanhansoft This problem was already fixed. Please try use newest elFinder.
