### ISSUE TITLE
CustomData not passed with every request

### ISSUE THREAD

**Issue by QueroBartK** [Studio-42/elFinder#1675]
It seems that the CustomData is not always passed.
When using CustomData instead of placing the parameters in the url directly everything except the file upload seems to work. When uploading files it seems like a request is done without the CustomData (but with the URL) that results in an error (we'll an error as we expect the custom data to always be provided so we didn't return the correct result from the server.)

**Comment by nao-pon** [comment]
@QueroBartK Please try use client option [`customData`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#customdata).

**Comment by QueroBartK** [comment]
@nao-pon I'm not sure if I was unclear but I had the problem while using [customData](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#customdata).
So adding an option to [customData](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#customdata) and it seemed to not be pass during a file upload. If however I use Url and append it to the end of the url it does get passed. (So I can get it working but I'd rather use [customData](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#customdata) as it leads to cleaner code)

**Comment by nao-pon** [comment]
I was checked on [online demo example](http://jsbin.com/rareda/edit?html,output). It seems no problem.

**Comment by QueroBartK** [comment]
Actually you can see it too when using the [online demo example](http://jsbin.com/rareda/edit?html,output). 
I used chrome and did the following:
F12 for the developer console and go to Network.
Go to the "Test here" directory
use the clear button in the developer console so you can clearly see what requests are going to be send
(created a small text file locally to upload)
drag and drop file
you'll see that two request will be made to basic.php
the second request won't have the custom: test

**Comment by nao-pon** [comment]
I checked Firefox/49.0.1/Win10 and Chrome/53.0.2785.116 m/Win10, I could not found problem.

![b7e8b3ce](https://cloud.githubusercontent.com/assets/1412630/18868345/d1e60f2a-84e2-11e6-8704-23aeb8b39638.png)
![cf06c4a3](https://cloud.githubusercontent.com/assets/1412630/18868349/d4112c94-84e2-11e6-80bc-4ae1c6c012fa.png)

**Comment by QueroBartK** [comment]
Ok, I see what the problem is. My colleague whom did the server side only checked the $_GET variables and not the $_POST. So I guess the problem was more that the parameter suddenly was passed as a post variable instead of a get variable. By adding it to the url string it is always passed as a get variable.

Sorry for the confusion.

**Comment by nao-pon** [comment]
OK, I see. I recommend to use $_SERVER variable to the paramater check. :-)
