### ISSUE TITLE
Reload elfinder with a new target

### ISSUE THREAD

**Issue by CraigDunn** [Studio-42/elFinder#1676]
Hello there,
What would be the correct way to set a new folder target and then cause the UI to reload, opening at the specified folder?
A javascript or jQuery code example would be wonderful!

I am doing it this way:
var startPath = "cd_input";
var volumeId = 'v1_';
var path = "\\\" + startPath; // without root path
var hash = volumeId + btoa(path).replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '.').replace(/\.+$/, '') + "0";
// added the trailing zero because btoa(path) does not generate it
var url = '@Url.Action("Index", "Files")' + '#elf_' + hash;
// url is: http://localhost:51350/files#elf_v1_XGNkX2lucHV00
location.href = url;
return false;

but neither location.href nor location.replace cause the page to load: I have to click in the address bar and do Enter ??

Isn't there a way to reload the UI at the new target folder without reloading the page?

Thanks for your time,
Craig.

**Comment by nao-pon** [comment]
@CraigDunn You can use `elfinderInstance.exec('open', 'TARGET HASH')` to open target folder.

e.g.
```javascript
var options = {
    url  : 'php/connector.php'
}
var elfInstance = $('#elfinder').elfinder(options).elfinder('instance');
var btn = $('div').on('click', function() {
    elfInstance..exec('open', 'TARGET HASH');
});
```

By the way, how to obtain the hash is incorrect. `\` not need to head of the path.

```javascript
var startPath = "cd_input";
var volumeId = 'v1_';
var path = startPath;
var hash = volumeId + btoa(path).replace(/+/g, '-').replace(/\//g, '').replace(/=/g, '.').replace(/.+$/, '');
```

**Comment by CraigDunn** [comment]
Thank you nao-pon san, .exec() does indeed work nicely.
But I still have an issue with generating the hash - let me explain:

In the DOM, for my folder "cd_input", I see hash "v1_XGNkX2lucHV00"
if I use btoa("cd_input")... I get "Y2RfaW5wdXQ=" - which is certainly incorrect.
If I use btoa("\\cd_input")... I get "XGNkX2lucHV0" - which is almost correct, but it needs to have one more zero appended.

elfInstance.exec('open', 'v1_XGNkX2lucHV0'); does not work.
elfInstance.exec('open', 'v1_XGNkX2lucHV00'); does work.

Also, in some cases, I see in the DOM that the appendage needs to be a 2, not a zero.

Can you help me to understand this please?

Thanks,
Craig.

**Comment by nao-pon** [comment]
@CraigDunn Please try newest elFinder (2.1.15 or nightly) if you are using old version.

**Comment by CraigDunn** [comment]
Hello nao-pon san,

I am using 
elfinder.min.js 2.1.15
with
jquery-2.2.4.min.js
and
jquery-ui-1.11.4.js

 - but still the same issue as described above.

Are there other files which I need to update? - 
Where is the html for the elfinder files-view generated - in the elfinder.js or elsewhere?

Thanks for your help - 
Craig.

**Comment by nao-pon** [comment]
Umm... I'm not sure. Could you show your connector configurations?

**Comment by CraigDunn** [comment]
I think you're probably right about that - I'll confer with our project-leader who set it all up in the first place and get back to you.

Thank you,
Craig.
