### ISSUE TITLE
Hashes for folder paths are appended 0 or 1 or 2 

### ISSUE THREAD

**Issue by CraigDunn** [Studio-42/elFinder#1677]
Hi there,

Comparing hashes of folder paths produced by btoa(path) to the <tr IDs I see in the DOM, I see that elfinder seems to have appended either a 0, or a 1, or a 2.

May I know the rules which govern these appendages? - I cannot find a consistent logic to it.

Thanks,
Craig.

**Comment by nao-pon** [comment]
Probably, It related to #1676. Please try newest elFinder, if you are using old version.
