### ISSUE TITLE
Permission problem : return errUploadFile when upload ,errMkdir when create folder

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1678]
Thanks for the plugin,  it is great and work fine.

Recently I move the programs to server but the plugin is not working:

it seems to be the permission problem 

![image](https://cloud.githubusercontent.com/assets/14356169/18900338/48ca23d0-84f5-11e6-87af-6d9ffe2993a1.png)

![image](https://cloud.githubusercontent.com/assets/14356169/18900336/4452c6fe-84f5-11e6-8992-fcacfd416a78.png)

files are PHP,  would you mind provide some idea to get further debug message beyond errUploadFile  and errMkdir.

Also , if it is about the permission, any advice to fix e.g. change whole project e.g JS to 777, and the owner etc...

Thanks a lot for your help

**Comment by nao-pon** [comment]
@leo1989work Please give enough permission to `path` of volume roots option. It require writable permission from PHP.
