### ISSUE TITLE
Operation timed out after 100000 milliseconds

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1680]
I just updated to the latest elFinder and GCS FlySystem Adapter.

Uploading a 500MB file, after the progress bar was full, it showed a popup saying"Doing something" then eventually died.

I've uploaded larger files previously without issue...

**Comment by nao-pon** [comment]
@paulcanning I checked on newest nightly elFinder with FlySystem - Google Drive adapter. That is no problem. I guess this problem is issue of Google Cloud adapter.

**Comment by paulcanning** [comment]
I got these errors in the request that timed out

> 0:"WARNING: preg_match(): Unknown modifier '\' in elFinderVolumeDriver.class.php line 2910."
> 1:"NOTICE: Undefined index: added in C:\wamp\www\fileportal\application\controllers\elfinder\connector.php line 205."
> 2:"WARNING: Invalid argument supplied for foreach() in C:\wamp\www\fileportal\application\controllers\elfinder\connector.php line 205."

Is the first error possibly the cause?

When elFinder displays "Doing something" what is it meant to be doing exactly?

**Comment by nao-pon** [comment]
Which version of elFinder are you using? Not match "elFinderVolumeDriver.class.php line 2910" in [latest version](https://github.com/Studio-42/elFinder/blob/2.1.15-src/php/elFinderVolumeDriver.class.php#L2910).

> When elFinder displays "Doing something" what is it meant to be doing exactly?

Perhaps, It saving the uploaded data to the server to GCS.

**Comment by nao-pon** [comment]
Please check without all of your `bind` functions.

**Comment by paulcanning** [comment]
I'm using 2.1.15.

I am using the following for my `bind` functions

```
'bind' => [
	'open search' => [$this, 'add_file_data'],
	'upload' => [$this, 'file_upload'],
	'rm' => [$this, 'file_remove'],
	'rename' => [$this, 'file_rename']
]
```

The functions are doing basic things such as adding data to the DB.

**Comment by nao-pon** [comment]
> I'm using 2.1.15.

Your environment is different from the JavaScript and PHP connector versions of elFinder. PHP of the file does not seem to be updated.

**Comment by paulcanning** [comment]
What do you mean? I updated to 2.1.5 via Composer. I don't know what else to do?

**Comment by paulcanning** [comment]
Nevermind, think I sorted it. I'm using CodeIgniter, so I have to copy the PHP library files to the CI library folder

**Comment by nao-pon** [comment]
@paulcanning Did you solved it? Please close this isuue if you got it.

**Comment by nao-pon** [comment]
Perhaps, because I think that is a GCS FlySystem Adapter of the problem, I will close it. Please re-open if necessary.
