### ISSUE TITLE
Google Cloud Storage - Root path is not passed through accessControl callback

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1687]
I am still having issues with https://github.com/Studio-42/elFinder/issues/1457

Using the `accessControl` parameter for a GCS root volume, the root path e.g. `/` is **NOT** passed through to the callback, meaning I am unable to set any permissions on the root volume.

Example

- ROOT <-- NOT passed through
- - a_sub_folder <-- passed through
- - a_file.txt <-- passed through
- - another_file.jpg <-- passed through

In the linked issue, a couple of people stated it should work, but I have tried it even with a local file system root volume, and I can guarantee 100% that the root path is not passed through.

If you use the following default `accessControl` callback, and stick a breakpoint on it, you will see that the root path, `/`, is never passed.

```
    public function accessControl($attr, $path, $data, $volume)
    {
        if (rtrim($path, "\\") === "\\") // Stick breakpoint here. You can change this to whatever, depending on server environment.
        {
            return ($attr == 'write' || $attr == 'locked');
        }
    }
```

**Comment by nao-pon** [comment]
@paulcanning Please check the value of $path.

e.g.
```php
public function elfDebug()
{
    $arg = func_get_args();
    ob_start();
    foreach($arg as $v) {
        var_dump($v);
    }
    $o = ob_get_contents();
    ob_end_clean();
    file_put_contents('./debug.txt', $o, FILE_APPEND);
}

public function accessControl($attr, $path, $data, $volume)
{
    $this->elfDebug($attr, $path);
    return strpos(basename($path), '.') === 0       // if file/folder begins with '.' (dot)
        ? !($attr == 'read' || $attr == 'write')    // set read+write to false, other (locked+hidden) set to true
        :  null;                                    // else elFinder decide it itself
}
```

**Comment by paulcanning** [comment]
OK, I am now seeing `/` at the end of the log file. How do I declare the attribute settings?

e.g. I want the root to be read only, no uploading or deleting allowed

**Comment by nao-pon** [comment]
> I am now seeing / at the end of the log file.

e.g.
```php
    public function accessControl($attr, $path, $data, $volume)
    {
        if ($path === "/")
        {
            return ($attr === 'read' || $attr === 'locked');
        }
        return null;
    }
```

**Comment by paulcanning** [comment]
Right, this is STILL not working.

I just re-tested logging the results to a text file, and now the root path is NOT there.

I tripled checked the accessControl callback and the root path ('/') is a 100000000000% NOT passed through to this callback.

**Comment by paulcanning** [comment]
So I did some testing, and as soon as I change the `accessControl` callback to 

```
if ($path === "/")
        {
            return ($attr === 'read' || $attr === 'locked');
        }
        return null;
```

Rather then just `return null;` the root path, `/` is not logged!

**Comment by paulcanning** [comment]
I got this working somehow on my local machine (Windows), but it is not working when deployed to a live server (Linux)

I have used `if ($path === "/" || $path === "\\")` to cover both bases.

Oddly, on local, the root volume states `Permissions: read, Locked: yes` but the live server states `Permissions: read and write, Locked: yes`

Could this be a caching issue (like we've seen before with elFinder)?
