### ISSUE TITLE
elFinder hangs on "Doing something" with large file upload

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1688]
With the latest elFinder and FlySystem Google  Cloud Storage adapter, elFinder is showing "Doing something" for quite a long time, after the upload bar is at 100%.

For a 100mb file, there are 10 small XHR requests, around 600-700 Bytes, then a final request (which starts when "Doing something" is displayed) which seems to be the actual file upload.

Something is clearly not right here. Any idea?

**Comment by nao-pon** [comment]
It is related to #1680

**Comment by paulcanning** [comment]
I am still having this issue.

For example, I tried uploading a 1GB file. The upload bar went up slowly to 100% (in about 5 minutes), but then shows a 2nd box showing "Doing something" which stays at 100% till it times out (PHP set to 10 minutes by default)

What is the "Doing something" operation? The upload bar had already gone from 0 to 100%, so the upload should be complete? I am using the very latest GCS Flysystem adapter which uses streams instead of dumping the file to memory.

I don't understand what this second operation is and it should not be needed as my files are being streamed to the storage adapter.
