### ISSUE TITLE
Uncaught TypeError: Cannot set property 'disabled' of undefined - elfinder.full.js:4978

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1689]
I am suddenly  seeing this appear in the console.

**Comment by paulcanning** [comment]
```
// for compat <= v2.1.13
if (file.disabled) {
	self.volOptions[file.volumeid].disabled = file.disabled;
}
```

Seems file.disabled is coming through as an array, so I think this is totally broken. I've commented it out and everything works fine for me, but if you want the backwards compatibility, you need to fix this.

**Comment by nao-pon** [comment]
@paulcanning Thanks! By the way, your environment is different from the JavaScript and PHP connector versions of elFinder. PHP of the file does not seem to be updated.

**Comment by paulcanning** [comment]
All my files are up to date... v 2.1.15
