### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by Gosokan** [Studio-42/elFinder#1694]
Hello, want to ask about basic auth elfinder
1. How to not showing anything if user not login?  Because with current basic authentication, user still can download and opening directory (read only mode).
2. Is there any other authentication method other than basic auth? which can be used to provide access to different directory. 
Eg: if login with username "alex" then provide access to "../files/alex", if login with username "john" then provide access to "../files/alex"

Thank you before..

**Comment by nao-pon** [comment]
@Gosokan Everything OK, if the authentication mechanism that can get the login user name in the PHP. It define in connector.php.
```php
$username = 'auth_user_name';
$opts = array(
    'locale' => '',
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/'.$username.'/',
            'URL'    => 'http://localhost/to/files/'
        )
    )
);
```
