### ISSUE TITLE
Access files owned by different users

### ISSUE THREAD

**Issue by jitkang** [Studio-42/elFinder#1696]
Is that possible for the file manager to access the files in each user directory in linux OS? Currently the system has more than 100 users with their home directory located in `/home/{user}` and all the files are owned by these users with file permission 744. 

I wanted to use Elfinder to access and manage each user's files, but as the web server is running as apache user, it has no permission to modify any user files. I do not want to chmod all the files to 777 as it is a serious security issue. What other option do I have other than using SFTP connector in Elfinder?

**Comment by nao-pon** [comment]
@jitkang Please run the PHP by each user account. e.g. suExec...

Related to http://stackoverflow.com/questions/39973078/manage-users-files-with-apache
