### ISSUE TITLE
Make custom root folder as elfinder root folder

### ISSUE THREAD

**Issue by salahsaleh** [Studio-42/elFinder#1697]
Hello All,
I am trying to make my custom folder which is inside 'files' folder, I tried both through client side configuration and server side configuration. My application is of jQuery and PHP.

Following is the code which I used at client side:
```
$('#elfndrPrfsrRsrc').elfinder({
            driver : 'LocalFileSystem',
            path: '../files/Spring16/Technology/',
            url : 'php/connector.minimal.php'  // connector URL (REQUIRED)
        });
```
When I am using above code, custom root folder is not set to which I want. Custom folder is files itself.

Following is the code which I tried at server side:
```
  $midDirPath = '\\files\Spring16\\';
    $opts = array(
        'locale' => '',
        'roots'  => array(
            array(
                'driver' => 'LocalFileSystem',
                'path'   => basename(__DIR__).$midDirPath.DIRECTORY_SEPARATOR.'Technology',
                'URL'    => 'php/connector.minimal.php'
            )
        )
    );

    // run elFinder
    $connector = new elFinderConnector(new elFinder($opts));
    $connector->run();
```
If I use above code then I am getting error message of "elFinderVolumeLocalFileSystem\"

`{"error":["errConf","errNoVolumes"],"debug":["Driver \"elFinderVolumeLocalFileSystem\" : Root folder does not exists."]}`

Note: I am not using both ways client side and server side together. I tried them separately.

**Comment by nao-pon** [comment]
@salahsaleh I guess `'path'   => basename(__DIR__).$midDirPath.DIRECTORY_SEPARATOR.'Technology'` is not correct.

**Comment by salahsaleh** [comment]
@nao-pon 
Ok, can you please let me know the correct way and is client configuration correct??

**Comment by nao-pon** [comment]
What is value of `basename(__DIR__).$midDirPath.DIRECTORY_SEPARATOR.'Technology'`? Is it correct?

**Comment by salahsaleh** [comment]
I apologize, I looked into my code, yup.. value I was passing to the 'path' was incorrect. I rectified it.

This is my new code:
```
$opts = array(
        'locale' => '',
        'roots'  => array(
            array(
                'driver' => 'LocalFileSystem',
                'path'   => 'C:\wamp\www\\'.basename(__DIR__).$midDirPath.'Technology',
                'URL'    => 'php/connector.minimal.php',
                'uploadMaxSize' =>  '10M'
            )
        )
    );
``` 

After modifying the value of path, the previous error is gone. But I am getting new error now. which stats: 
`
{"error":["errUpload","errUploadTotalSize"]}
` 
though I didn't intend to upload any large size but I still gave 'uploadMaxSize' property some value to bypass this issue. 
I even changed 'post_max_size' in php.ini to 13MB but still I am facing this issue.


Now the path value is:
`"C:\wamp\www\PHP_test\files\Spring16\Technology"`

**Comment by nao-pon** [comment]
Please check your php.ini.

- [upload_max_filesize](http://www.php.net/manual/ini.core.php#ini.upload-max-filesize)
- [post_max_size](http://www.php.net/manual/ini.core.php#ini.post-max-size)
- [memory_limit](http://www.php.net/manual/ini.core.php#ini.memory-limit)
- [max_execution_time](http://www.php.net/manual/info.configuration.php#ini.max-execution-time)
- [max_file_uploads](http://www.php.net/manual/ini.core.php#ini.max-file-uploads)

**Comment by salahsaleh** [comment]
I have checked it, all look fine
Below are the values of them:

```
upload_max_filesize	= 64M/128
post_max_size	= 64M/128M
memory_limit	= 128M
max_execution_time	= 120
max_file_uploads	= 20

```

**Comment by nao-pon** [comment]
It seems no problem. Can you try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip)?
