### ISSUE TITLE
No thumbnails after upload (2.1.16)

### ISSUE THREAD

**Issue by alexantr** [Studio-42/elFinder#1701]
After elFinder was updated to 2.1.16 I see one bug.
Thumbnails are not showing for just uploaded images. Only when I click "Reload" they begin showing.

Just uploaded:
![1](https://cloud.githubusercontent.com/assets/4941848/19343685/f078919c-913f-11e6-8446-052e88881c4a.png)

After reloading:
![2](https://cloud.githubusercontent.com/assets/4941848/19343726/036b749a-9140-11e6-9cdf-44d749a0727f.png)

Tested on php 5.6 & php 7.0 with GD extension on Windows and Linux (CentOS) in latest Chrome  & Firefox, jQuery/jQuery UI: 2.2.4/1.11.4

**Comment by nao-pon** [comment]
@alexantr Probably fixed @c3f4709b8776787579fff4f2f6945267a47bdeb3. Please try and check on [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

Thanks!

**Comment by alexantr** [comment]
@nao-pon Yes. It's fixed now!
👍

**Comment by nao-pon** [comment]
@alexantr Thanks for your time.

**Comment by webuntu** [comment]
> Thumbnails are not showing for just uploaded images.
"Thumbnails are not showing for just uploaded images" fixed, thank you, but this situation remaining after cropping, rotation and resizing operations. Please, can you fix it also?

**Comment by nao-pon** [comment]
@webuntu I was checked in [our demo site](http://studio-42.github.io/elFinder/#elf_l2_Lw). There was no problem. Would you check in [our demo site](http://studio-42.github.io/elFinder/#elf_l2_Lw)?

**Comment by webuntu** [comment]
Sorry, it is really ok on demo site. I had to check it there foremost. Excuse me.

**Comment by webuntu** [comment]
> I was checked in our demo site. There was no problem.

It seems to me, the reason of different behavior is in jquery version. In elfinder.html from [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip) used jquery v.1.12.4 and [on demo site](http://studio-42.github.io/elFinder/#elf_l2_Lw) - v.3.1.1. Now i am using jquery-3.1.1.min.js and everything ok on my local copy.

**Comment by nao-pon** [comment]
@alexantr You are right! I'll fix it. Thanks!

**Comment by webuntu** [comment]
Now it's ok. Thank you!
