### ISSUE TITLE
After enable text label in mobile browser.

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1702]
I noticed two problems in Mobile view.
1. Show & hide toolbar touch area is middle of toolbar.
2. Working area is closed & user must resize working window.
Can you check it?

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM 

> 2. Working area is closed & user must resize working window.

What's mean? I'm not sure. Would you please explain more detail?

Thanks!

**Comment by CodeLyokoXtEAM** [comment]
Yes.

**Comment by nao-pon** [comment]
OK, I'll fix it. :ok_man:
