### ISSUE TITLE
No video thumbnails

### ISSUE THREAD

**Issue by Shadowfied** [Studio-42/elFinder#1703]
Hiya.

I just set up elFinder and I love it. It's great. Everything seems to work great, except that I'm not getting video thumbnails. Picture thumbnails work fine.
I'm running Debian 8.6 Jessie on Linux 3.16.-0-4 64, using nginx and PHP7.

I've Googled and searched but haven't found anyone with the same issue.

What do I do?

**Comment by nao-pon** [comment]
@Shadowfied Video thumbnail feature require the `ffmpeg` on the server.

Please try install the `ffmpeg` into your server.

**Comment by Shadowfied** [comment]
ffmpeg is already installed.

**Comment by nao-pon** [comment]
What results do you get of `ffmpeg -version` on your server shell?

**Comment by Shadowfied** [comment]
```
ffmpeg version N-81502-ga13a81a Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 4.9.2 (Debian 4.9.2-10)
configuration: --prefix=/home/shadowfied/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/shadowfied/ffmpeg_build/include --extra-ldflags=-L/home/shadowfied/ffmpeg_build/lib --bindir=/home/shadowfied/bin --enable-gpl --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree
libavutil      55. 29.100 / 55. 29.100
libavcodec     57. 54.101 / 57. 54.101
libavformat    57. 48.101 / 57. 48.101
libavdevice    57.  0.102 / 57.  0.102
libavfilter     6. 58.100 /  6. 58.100
libswscale      4.  1.100 /  4.  1.100
libswresample   2.  1.100 /  2.  1.100
libpostproc    54.  0.100 / 54.  0.100

```

I did build ffmpeg from source and I thought maybe that could be the culprit, but I have a friend who installed ffmpeg straight from pacman (Arch, Manjaro) and he has the same issue - no video thumbs.

**Comment by nao-pon** [comment]
This is test script. (test.php)
```php
<?php
$tmp = 'test.mp4';
$file = 'test.png';
$ss = 6;
$cmd = sprintf('ffmpeg -ss 00:00:%.3f -vframes 1 -i %s -f image2 %s', $ss, escapeshellarg($tmp), escapeshellarg($file));
$o = array('Results:');
exec($cmd, $o);
echo join("<br>\n", $o);
```

- test.php
- [test.mp4](http://hypweb.net/elFinder-nightly/demo/Demo/MIME-types/test.mp4)
- test.png -> This will made at the time of success.

**Comment by Shadowfied** [comment]
@nao-pon 
`Option vframes (set the number of video frames to output) cannot be applied to input file test.mp4 -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for input file test.mp4.
Error opening input files: Invalid argument
Results:%                                 `

**Comment by nao-pon** [comment]
Please try from download [test.mp4](http://hypweb.net/elFinder-nightly/demo/Demo/MIME-types/test.mp4) in the same directory as the test.php.

**Comment by nao-pon** [comment]
How is `$cmd = sprintf('ffmpeg -i %s -f image2 -ss 00:00:%.3f -vframes 1 %s', escapeshellarg($tmp), $ss, escapeshellarg($file));`?

**Comment by Shadowfied** [comment]
I did put the files in the same directory.

It worked with your updated command. Works fine. Got a test.png frame.

**Comment by nao-pon** [comment]
@Shadowfied OK, I got it. It is a bug. I'll fix it. Thanks! 👍

**Comment by nao-pon** [comment]
@Shadowfied You can try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip) until release 2.1.17.

Thanks for your time!

**Comment by Shadowfied** [comment]
That fixed it. Huge thanks :D
