### ISSUE TITLE
Restart elFinder

### ISSUE THREAD

**Issue by BitStinker** [Studio-42/elFinder#1709]
Is it possible to completely restart elFinder programmatically. That is, I instantiate elFinder with

$( '#elf' ).elfinder( opts );

I would like to start it again in a menu item exec like this:

`this.exec = function( hashes, opt ) {
	fm.request( { 'data' : data } )
	.done( function( data ) {
		nuke_and_restart();
	} );
};
`

Where nuke_and_restart() completely starts over with the connector doing it's initialization, etc.

The purpose for this is that the database can change requiring different volumes, so it needs to completely start again.

I suppose I could do something like...

`$( '#elfcontainer' ).find( '#elf' ).remove().end().append( "<div id='elf'/>" ).find( '#elf' ).elfinder( opts );`

but I expect you have something more elegant.

**Comment by nao-pon** [comment]
@BitStinker There is an option `destroy` in elfinder object.

e.g. `$('#elf').elfinder('destroy').elfinder(opts);`

**Comment by BitStinker** [comment]
Thanks for that! You always come through.
