### ISSUE TITLE
File upload on paste does not work

### ISSUE THREAD

**Issue by doncaz** [Studio-42/elFinder#1718]
steps to reproduce:

1. Copy few files from folder
2. Click on elfinder add file icon
3. Focus on input box "Drop or Paste files here"
4. Click paste
5. Got error : No files found for upload

if try to paste screen shot everything is ok, drag drop ok, but paste files not. 

Does it even work? :)

**Comment by nao-pon** [comment]
@doncaz 

> Copy few files from folder

Where copied from? from your local PC?

**Comment by nao-pon** [comment]
I checked it on windows PC. It can by `Ctrl+v` only Firefox. Other browser was impossible. 
Perhaps, this is due to the browser specifications. So please use DnD upload or file picker.

**Comment by doncaz** [comment]
yes from local PC, Firefox for me does not work too, so if paste not working do not confuse users and change text of input from "Drop or Paste files here" to "Drop files here" :)

**Comment by nao-pon** [comment]
OK, I am considering a change of message, but my English is not perhaps well. Please suggest a better wording.

My wording is "Drop or Paste Files, Images, URL-list to here (File drop only)".

**Comment by doncaz** [comment]
I suggest "Drop files, Paste URL or Screenshot here"

**Comment by nao-pon** [comment]
@doncaz Thanks!

What about "Drop files, Paste URL or Image data here"?

**Comment by doncaz** [comment]
Screenshot for me more clearly, but it is decision for you :)

**Comment by nao-pon** [comment]
It is possible to paste image data of the clipboard that is not limited to the screenshot, so I'm selecting "Image data".

Thanks so much!
