### ISSUE TITLE
Proper procedure for altering session

### ISSUE THREAD

**Issue by BitStinker** [Studio-42/elFinder#1720]
I have a routine that allows a user to redefine ancestor projects. When they do, I need the new related project folders to show in elfinder. Here is what I do in pseudo code:

js.new.contextmenu.option.handler: send new ancestor project data

php.extended.finder.menu.option.handler: 
1. add ancestor project to database
2. change session variables to match
3. rebuild elfinder opts to match
4. save elfinder opts in session
5. return result

js.new.contextmenu.option.handler: receive result - reload elfinder

When elfinder is reloaded the changed session variable for the options has reverted to its initial value.

If I check the session variables before and after changing them, they have been changed as necessary. I'm certain this is a session_write_close() issue with one session writing after the changes have been made.

What is the recommended procedure for an elfinder extension member function changing the session variables?

Thanks!

**Comment by BitStinker** [comment]
Here is the js code:

`$( '#prj-explore-div' ).hide().parent().find( '#qxp-progress' ).show();
var data = {
	'cmd' 	: 'chgref', 
	'op'	: (opt == -1 ? 'add' : 'remove'),
	'target': _tag,
	'ref'	: newref
};
fm.request( { 'data' : data } )
.done( function( data ) {
	if( data.op == 'add' )
		prjRefs[prjRefs.length] = data.ref;
	setTimeout( function() { 
		var t = $( '#tabs' );
		$( 'body' ).height( t.offset().top + t.height() );
		panelht = t.height() - t.find( '.ui-tabs-nav' ).height() - 20;
		$( '#prj-explore-div' ).elfinder( 'destroy' ).elfinder( elfopts ).height( panelht - 10 );
		$( '#prj-explore-div' )
		.elfinder( 'destroy' )
		.elfinder( elfopts )
		.height( panelht - 10 )
		.show()
		.parent()
		.find( '#qxp-progress' )
		.hide();
	}, 10 );
} );
`

**Comment by BitStinker** [comment]
Here is the php code:

`protected function chgref( $args ) {
	global $qxSQL;
	
	$cat = substr( $args['target'], 0, 6 );
	
	file_put_contents( "chgref.txt", print_r( $args, true ) );
	$sQ = "SELECT Ancestors FROM tblProjects WHERE ProjectTag LIKE '%{$cat}%' LIMIT 1";
	file_put_contents( "chgref.txt", print_r( Array( 'sQ' => $sQ ), true ), FILE_APPEND );
	if( $result = $qxSQL->q( $sQ ) ) {
		if( $row = $result->fetch_row() ) {
			$a = explode( ',', $row[0] );
			if( $args['op'] == 'add' )
				$a[] = $args['ref'];
			else
				$a = array_diff( $a, Array( $args['ref'] ) );
			$a = array_unique( $a );
			$row[0] = implode( ',', $a );
			$sQ = "UPDATE tblProjects SET Ancestors = '{$row[0]}' WHERE ProjectTag LIKE '%{$cat}%';";
			file_put_contents( "chgref.txt", print_r( Array( 'sQ' => $sQ ), true ), FILE_APPEND );
			$qxSQL->q( $sQ );
			$this->makeOpts( $args['target'], true );
			if( !session_id() )
				$this->session->start();
			$this->sessionWrite();
			$this->session->start();
		}
	}
	
	$result = $args;
	
	return $result;
}
`

**Comment by nao-pon** [comment]
@BitStinker Please try `$this->session->set($key, $val)` and `$this->session->get($key)`.

ref. https://github.com/Studio-42/elFinder/blob/master/php/elFinderSessionInterface.php

**Comment by nao-pon** [comment]
Did you got it?

**Comment by BitStinker** [comment]
Sorry I didn't respond earlier. Yes, I got it and tested it. It does work, but I found a more responsive way of handling the issue without bogging down in the elFinder engine.

Thank you for your help!
