### ISSUE TITLE
Unable to paste / duplicate , and finding ways to debug

### ISSUE THREAD

**Issue by leo1989work** [Studio-42/elFinder#1722]
![image](https://cloud.githubusercontent.com/assets/14356169/19755792/a1fbda9a-9c4a-11e6-924a-5b87f4962ac2.png)

Currently I find the plugin can not paste / duplicate the file

And I test few case:

Success case:
1) if the directory has no file, then can paste/duplicate

Fail Case:
1) if the directory has file,  can not paste/duplicate
2) for any file , can not paste/duplicate

Thanks

**Comment by leo1989work** [comment]
And the error is output at elFinderVolumeDriver.class.php

In the function:

protected function copy($src, $dst, $name)

the last line:

return $this->setError(elFinder::ERROR_COPY, $this->path($srcStat['hash']));

Thanks

**Comment by leo1989work** [comment]
also , the condition of:

$this->_copy($this->convEncIn($src), $this->convEncIn($dst), $this->convEncIn($name))

is false at #4049 , for reference, thanks

**Comment by nao-pon** [comment]
@leo1989work Which volume driver are you using? please check function _copy() of your use volume driver.

**Comment by leo1989work** [comment]
don't know why the _copy() function have the return false at the start of the function....
comment it and work fine now
thanks a lot for helping.
