### ISSUE TITLE
Option For Always Fullscreen

### ISSUE THREAD

**Issue by Flamenco** [Studio-42/elFinder#1728]
I embed elFinder, and would find it useful for an option to:

- [x] 1. make the component 100% of parent by default
- [ ] 2. remove expand/restore icon
- [ ] 3. remove expand/restore messages 
- [ ] 4. remove all relevantkeyboard shortcuts

I currently call this, it works, but is not complete.

`var instance = $elfinder.elfinder('instance');
  instance.exec('fullscreen');
`

**Comment by nao-pon** [comment]
@Flamenco 
> 2 . remove expand/restore icon

There is a client configuration option [`uiOptions.toolbar`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#uioptions).

>3 . remove expand/restore messages
>4 . remove all relevantkeyboard shortcuts

What mean is it? Could you please explain more detail?

**Comment by Flamenco** [comment]
I would like to specify, as a config option, that the finder must always be in full screen mode, with no user-controlled option to restore it.

**Comment by nao-pon** [comment]
There is no way to prohibit canceling the full screen mode. It is the specification of browser (or OS).

**Comment by Flamenco** [comment]
I only want all the icon, keyboard shortcuts, and help references gone, and open full screen by default on launch.

**Comment by nao-pon** [comment]
Are you want like this? -> http://jsbin.com/gowemuq/edit?html,output

```javascript
var elf = $('#elfinder').elfinder({
	url : 'php/connector.php',
	ui : ['tree', 'path', 'stat'],
	allowShortcuts : false
}).elfinder('instance').exec('fullscreen');
```

**Comment by Flamenco** [comment]
Basically I want 'the works' less the expand icon. I thought there was also a keyboard shortcut but I can't seem to find it now.

Although I can just comment the expand icon out of the source, I thought it would be nice for a user to just do declare

fullScreen:[always | start | default]

and not have to worry about anything else.

**Comment by nao-pon** [comment]
What you want is maximized in the browser, not in full screen mode?

Live demo example -> http://jsbin.com/gowemuq/edit?output
Source -> http://jsbin.com/gowemuq/edit?html

Full screen mode on the OS can not be started without user action.

**Comment by Flamenco** [comment]
Here's a screen shot.  I want all these actions gone.  I already have it starting in 'full screen' mode.  My issue is more about removing access any 'reinstate; items, while setting fullscreen on startup, using a single option.

In this example, full screen is not 'full user window'.  Its 100% of it's parent.  I don't want the user to be able to restore it.

![screen shot 2016-11-09 at 11 04 07 pm](https://cloud.githubusercontent.com/assets/819940/20164285/726822e8-a6d1-11e6-8c7d-2726f8975ffd.png)

**Comment by Flamenco** [comment]
Maybe I should not be saying 'Full Screen'...

**Comment by nao-pon** [comment]
I think that [Live demo example](http://output.jsbin.com/gowemuq) is what you want, is not it?

```javascript
$(document).ready(function() {
	var myCommands = elFinder.prototype._options.commands;
	if ($.inArray('*', myCommands) !== 0) {
		myCommands = Object.keys(elFinder.prototype.commands);
	}
	var disabled = ['fullscreen'];
	$.each(disabled, function(i, cmd) {
		(idx = $.inArray(cmd, myCommands)) !== -1 && myCommands.splice(idx,1);
	});
	var elf = $('#elfinder').elfinder({
		url : 'php/connector.php',
		height : $(window).height(),
		resizable: false,
		commands : myCommands
	}).elfinder('instance');
	var resizeTimer;
	$(window).resize(function() {
		resizeTimer && clearTimeout(resizeTimer);
		if (! $('#elfinder').hasClass('elfinder-fullscreen')) {
			resizeTimer = setTimeout(function() {
				var h = parseInt($(window).height());
				if (h != parseInt($('#elfinder').height())) {
					elf.resize('100%', h);
				}
			}, 200);
		}
	});
});
```

**Comment by Flamenco** [comment]
The `$(window).resize(...)` along with adding allowFullScreen to the iframe`<iframe ... allowFullScreen='true' />` fixed all my issues.  Now the full screen function works, and that is an added bonus, because before these changes, pressing full screen would _restore_ my 100% sized elFinder to a less-than-full-sized div.

Thank you Naoki.

**Comment by nao-pon** [comment]
Currently elFinder has client config option `height`. see https://github.com/Studio-42/elFinder/issues/2305#issuecomment-348948836 .

**Comment by awsmthx** [comment]
i tried to copy the code from Live demo example into elfinder.html to have fullscreen by default aswell but it doesn't change a thing
my code looks like this now:
`<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>elFinder 2.1.x source version with PHP connector</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2" />

		
		
		<script data-main="./main.default.js" src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.min.js"></script>
		<script>
			define('elFinderConfig', {
				// elFinder options (REQUIRED)
				// Documentation for client options:
				// https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
				defaultOpts : {
					url : 'php/connector.minimal.php' // connector URL (REQUIRED)
					,commandsOptions : {
						edit : {
							extraOptions : {
								// set API key to enable Creative Cloud image editor
								// see https://console.adobe.io/
								creativeCloudApiKey : '',
								// browsing manager URL for CKEditor, TinyMCE
								// uses self location with the empty value
								managerUrl : ''
							}
						}
						,quicklook : {
							// to enable preview with Google Docs Viewer
							googleDocsMimes : ['application/pdf', 'image/tiff', 'application/vnd.ms-office', 'application/msword', 'application/vnd.ms-word', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
						}
					}
					// bootCalback calls at before elFinder boot up 
					,bootCallback : function(fm, extraObj) {
						/* any bind functions etc. */
						fm.bind('init', function() {
							// any your code
						});
						// for example set document.title dynamically.
						var title = document.title;
						fm.bind('open', function() {
							var path = '',
								cwd  = fm.cwd();
							if (cwd) {
								path = fm.path(cwd.hash) || null;
							}
							document.title = path? path + ':' + title : title;
						}).bind('destroy', function() {
							document.title = title;
						});
					}
				},
				managers : {
					// 'DOM Element ID': { /* elFinder options of this DOM Element */ }
					'elfinder': {}
				}
			});
		</script>
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				var myCommands = elFinder.prototype._options.commands;
				if ($.inArray('*', myCommands) !== 0) {
					myCommands = Object.keys(elFinder.prototype.commands);
				}
				var disabled = ['fullscreen'];
				$.each(disabled, function(i, cmd) {
					(idx = $.inArray(cmd, myCommands)) !== -1 && myCommands.splice(idx,1);
				});
				var elf = $('#elfinder').elfinder({
					url : 'https://hypweb.net/elFinder-nightly/demo/2.1/php-jsb/basic.php',
					height : $(window).height(),
					resizable: false,
					commands : myCommands
				}).elfinder('instance');
				var resizeTimer;
				$(window).resize(function() {
					resizeTimer && clearTimeout(resizeTimer);
					if (! $('#elfinder').hasClass('elfinder-fullscreen')) {
						resizeTimer = setTimeout(function() {
							var h = parseInt($(window).height());
							if (h != parseInt($('#elfinder').height())) {
								elf.resize('100%', h);
							}
						}, 200);
					}
				});
			});
		</script>
	</head>
	<body style="margin:0; padding:0;">
		<div id="elfinder" style="width:100%; height:100%; border:none;"></div>
	</body>
</html>
`

**Comment by nao-pon** [comment]
@awsmthx elFinder is double-started with main.default.js with requireJS and $(document).ready(). If you use main.default.js, processing with $(document).ready() is not necessary.  And You can use `height: '100%'` to fit to window height.

```html
<title>elFinder 2.1.x source version with PHP connector</title>
    <!-- Require JS (REQUIRED) -->
    <!-- Rename "main.default.js" to "main.js" and edit it if you need configure elFInder options or any things -->
    <script data-main="./main.default.js" src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.min.js"></script>
    <script>
        define('elFinderConfig', {
            // elFinder options (REQUIRED)
            // Documentation for client options:
            // https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
            defaultOpts : {
                url : 'php/connector.minimal.php' // connector URL (REQUIRED)
                ,commandsOptions : {
                    edit : {
                        extraOptions : {
                            // set API key to enable Creative Cloud image editor
                            // see https://console.adobe.io/
                            creativeCloudApiKey : '',
                            // browsing manager URL for CKEditor, TinyMCE
                            // uses self location with the empty value
                            managerUrl : ''
                        }
                    }
                    ,quicklook : {
                        // to enable preview with Google Docs Viewer
                        googleDocsMimes : ['application/pdf', 'image/tiff', 'application/vnd.ms-office', 'application/msword', 'application/vnd.ms-word', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
                    }
                }
                // bootCalback calls at before elFinder boot up 
                ,bootCallback : function(fm, extraObj) {
                    // disable fullscreen cmd
                    delete fm.commands.fullscreen;
                    /* any bind functions etc. */
                    fm.bind('init', function() {
                        // any your code
                    });
                    // for example set document.title dynamically.
                    var title = document.title;
                    fm.bind('open', function() {
                        var path = '',
                            cwd  = fm.cwd();
                        if (cwd) {
                            path = fm.path(cwd.hash) || null;
                        }
                        document.title = path? path + ':' + title : title;
                    }).bind('destroy', function() {
                        document.title = title;
                    });
                }
                ,height : '100%' // you can use '100%' to fit window height
                ,resizable: false
            },
            managers : {
                // 'DOM Element ID': { /* elFinder options of this DOM Element */ }
                'elfinder': {}
            }
        });
    </script>
</head>
<body style="margin:0; padding:0;">
    <div id="elfinder" style="width:100%; height:100%; border:none;"></div>
</body>
```

**Comment by awsmthx** [comment]
thanks, works like intended now :+1:
