### ISSUE TITLE
avoid web browser listing of user storage folder

### ISSUE THREAD

**Issue by mustaqim313** [Studio-42/elFinder#1730]
How could I automatically add the index.php / .html file when new storage folder is added?

where could I edit the code so it could do this function?

**Comment by nao-pon** [comment]
@mustaqim313 Such a thing is I think that it is better to do in a server-side script.

If you want to do something about the action that the user performs on the elFInder you can use the '[bind](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind)' option.

**Comment by mustaqim313** [comment]
thanks for reply. Will check it out
