### ISSUE TITLE
Not able to upload word documents

### ISSUE THREAD

**Issue by saudisoftech** [Studio-42/elFinder#1733]
i was trying to upload Microsoft documents like word,excel

.doc, docx, xls 

but getting error.
Unable to upload "file.docx". File type not allowed.
can anyone help me in this matter.

**Comment by nao-pon** [comment]
@saudisoftech Please check the Wiki page. -> https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadallow
