### ISSUE TITLE
disabledCommands do nothing

### ISSUE THREAD

**Issue by ipppinto** [Studio-42/elFinder#1734]
Hi,

Can you tell me what is disabledCommands? I my case do nothing.

How can I use this:

Command list

open - open directory and initializes data when no directory is defined (first iteration)
file - output file contents to the browser (download/preview)
tree - return child directories
parents - return parent directories and its subdirectory childs
ls - list files in directory
tmb - create thumbnails for selected files
size - return size for selected files or total folder(s) size
dim - return image dimensions
mkdir - create directory
mkfile - create text file
rm - delete files/directories
rename - rename file
duplicate - create copy of file
paste - copy or move files
upload - upload file
get - output plain/text file contents (preview)
put - save text file content
archive - create archive
extract - extract archive
search - search for files
info - return info for files. (used by client "places" ui)
resize - modify image file (resize/crop/rotate)
netmount - mount network volume during user session. Only ftp now supported.

**Comment by nao-pon** [comment]
@ipppinto There is an option `[disabled](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#disabled)` of volume roots.

e.g.
```php
$opts = array(
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'disabled' => array('rm', 'rename'),
        )
    )
);
```
