### ISSUE TITLE
Custom column not showing on live site

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1735]
I have an odd issue, where one of my two custom columns is not showing on my live site, but does on my local dev server.

I have two columns that add extra text information to each file when elFinder fetches the file data.

On my local server, both are working, but on the live site, only one is showing.

Both show simple text and checking the JSON object, the information is there, for both columns.

Why would one show and not the other?

Below is how I'm defining the columns in the elFinder setup

```
                               cwd: {
					listView: {
						columns: ['description', 'uploaded', 'size', 'date'],
						columnsCustomName: {
							description: 'Description',
							uploaded: 'Uploaded'
						}
					}
				}
```

**Comment by paulcanning** [comment]
and the JSON object

```
description:"here is another version"
file_id:98
hash:"flsGCS_TkVXX0pPQi9Xb3JkUHJlc3MtUGx1Z2luLUJvaWxlcnBsYXRlLW1hc3Rlci0xLnppcA"
mime:"application/zip"
name:"WordPress-Plugin-Boilerplate-master-1.zip"
phash:"flsGCS_TkVXX0pPQg"
read:1
size:"28179"
ts:1475587649
uploaded:"Pablo Canning"
write:1
```

**Comment by nao-pon** [comment]
@paulcanning The local storage value of the browser may be affecting it. Please check in secret(Incognito) mode of browser.

**Comment by paulcanning** [comment]
It is fine in incognito. How do I clear the part of the cache effecting this? Or will is sort itself out?

**Comment by nao-pon** [comment]
Please see https://github.com/Studio-42/elFinder/issues/1535#issuecomment-233101512

**Comment by paulcanning** [comment]
The problem is that it is effecting not just me, but other people. I can't exactly tell them to remove the local storage cache. I don't even know how the one column got hidden, as since I put it in, it's always been there.
