### ISSUE TITLE
Delete confirm dialog is hidden by preview window.

### ISSUE THREAD

**Issue by Flamenco** [Studio-42/elFinder#1736]
When previewing a file, and then pressing delete keyboard shortcut, the confirm dialog shows up behind the preview window.

**Comment by nao-pon** [comment]
@Flamenco There is no problem in demo site. Please check on newest version or nightly build.

![fireshot capture 5 - elfinder 2 1 x - file manager for web_ - http___studio-42 github io_elfinder_](https://cloud.githubusercontent.com/assets/1412630/20125225/82a3dbfa-a66f-11e6-9c5c-191ed30f55e2.png)

**Comment by Flamenco** [comment]
This is what shows up for me (mac - chrome - Version 54.0.2840.87 (64-bit).  If I don't move the preview window from the center, you don't even see the confirm dialog.

<img width="676" alt="screen shot 2016-11-09 at 5 11 09 pm" src="https://cloud.githubusercontent.com/assets/819940/20156739/a268ebda-a69f-11e6-8259-92af4d37e1a2.png">

**Comment by nao-pon** [comment]
Did you checked on [our demo site](https://studio-42.github.io/elFinder/#elf_l2_Lw)?

**Comment by Flamenco** [comment]
It works perfect on your demo site.  Not in my use case though.

**Comment by nao-pon** [comment]
@Flamenco Please try latest version or [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by Flamenco** [comment]
Yep, working now. Thank you!
