### ISSUE TITLE
Do no retry uploading if getting an error

### ISSUE THREAD

**Issue by pgilad** [Studio-42/elFinder#1738]
Currently if server sends "File too large" error the client retries to upload. This makes no sense as nothing changed. There are also many other errors that shouldn't trigger a retry.

In fact I think retry should be opt-in, and only handled for very specific cases (broken xhr or timeout)

**Comment by nao-pon** [comment]
@pgilad Please consider using the config value `[uploadMaxSize](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadmaxsize)`.

**Comment by pgilad** [comment]
How does that relate to the retries the client does on upload?

**Comment by nao-pon** [comment]
elFinder will try a retry to recover from a very short network error when chunked file uploading. You can adjust the chunk size with the `[uploadMaxChunkSize](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#uploadmaxchunksize)` client option.

**Comment by pgilad** [comment]
I set it to `0` and it's still uploading

**Comment by nao-pon** [comment]
The connector config `[uploadMaxConn](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadMaxConn)` to `-1` to disable chunked file upload. Please try it.

**Comment by nao-pon** [comment]
@pgilad I'll fix to retry uploading only on connection aborted.
