### ISSUE TITLE
How to enlarge the "quicklook" window?

### ISSUE THREAD

**Issue by YavuzTR** [Studio-42/elFinder#1740]
Hi,
How can I change the standard size of this window?
http://prnt.sc/d53b22

Default size: Width: 450 and Height: 360px
i change width: 850 px, height: 500px?

**Comment by nao-pon** [comment]
@YavuzTR There are client configurations `commandsOptions.quicklook.width` and `commandsOptions.quicklook.height`.

e.g.
```javascript
var options = {
    url  : 'php/connector.php',
    commandsOptions : {
        quicklook : {
            width: 850,
            height: 500
        }
    }
}
$('#elfinder').elfinder(options);
```
