### ISSUE TITLE
Invalid backend configuration error  occurred using IE11

### ISSUE THREAD

**Issue by anagaok** [Studio-42/elFinder#1741]

**Comment by anagaok** [comment]
I'm using elFinder 2.1.16 with tinyMCE and encounterd the error "Invalid backend configuration.Readable volumes not available." using IE11 of Windows10. 
![2016-11-10 15 46 05](https://cloud.githubusercontent.com/assets/1378443/20167165/f5a6bd46-a75c-11e6-8109-434c34260144.png)

But there are no errors using Edge of Windows10.
![2016-11-10 15 48 27](https://cloud.githubusercontent.com/assets/1378443/20167196/2c2342ae-a75d-11e6-8e16-0a1f737b4ba7.png)

Settings in connector.minimal.php are:

$dir1 = '../../../../uploadImg/';
$dir2 = '/images/';
$user = '2';

$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => $dir1 . $user . '/' . $dir2,                 // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/' . $dir1 . $user . '/' . $dir2, // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image'),              // Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access',                    // disable and hide dot starting files (OPTIONAL)
                        'disabled'      => array( 'netmount', 'upload', 'edit', 'archive', 'resize' ),           // disable commands
		)
	)
);

Please let me know what is the cause of this error.

**Comment by anagaok** [comment]
I changed the settings a bit as below.
$dir1 = '../../../../uploadImg/';
$dir2 = '/images/';
$user = '2';

$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => $dir1 . $user . '/',                 // path to files (REQUIRED)
                        'startPath'     => $dir1 . $user . $dir2,
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/' . $dir1 . $user . '/', // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image'),              // Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access',                    // disable and hide dot starting files (OPTIONAL)
                        'disabled'      => array( 'netmount', 'upload', 'edit', 'archive', 'resize' ),           // disable commands
		)
	)
);

The error is disappeared. But root path is incorrect.
![2016-11-10 16 11 01](https://cloud.githubusercontent.com/assets/1378443/20167712/96441322-a760-11e6-843c-1aa28eca0fab.png)

**Comment by nao-pon** [comment]
@anagaok 

>$dir1 = '../../../../uploadImg/';
>$dir2 = '/images/';
>$user = '2';

and

>'path' => $dir1 . $user . '/' . $dir2

The path became `../../../../uploadImg/2//images/`

I'm guessing that correct setting is `'path' => $dir1 . $user . $dir2`.

**Comment by anagaok** [comment]
@nao-pon 
Thank you for pointing out my mistake.
I change the setting as below and try it again. But the result is same.

$dir1 = '../../../../uploadImg/';
$dir2 = '/images/';
$usr = '2';

$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => $dir1 . $user . $dir2,                 // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/' . $dir1 . $user . $dir2, // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image'),              // Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access',                    // disable and hide dot starting files (OPTIONAL)
                        'disabled'      => array( 'netmount', 'upload', 'edit', 'archive', 'resize' ),           // disable commands
		)
	)
);
<img width="1084" alt="2016-11-10 23 54 45" src="https://cloud.githubusercontent.com/assets/1378443/20181332/1b081a5a-a7a1-11e6-8b93-ab2868aa6ee1.png">

**Comment by nao-pon** [comment]
However, it is very strange that there is only a problem with IE. There is no problem with IE in the demo site, so I do not know any more.

I think that this problem is not a problem of elFinder and I will close it. Please let me know if you find a problem with elFinder.

**Comment by anagaok** [comment]
I checked my environment again, and found the condition the error occured.
The value of the variable $user is set in "connector.minimal.php" when I described above.
 I confirmed the error didn't occur at this contidion.
The error occured it was set using HTTP GET. Is it impossible using HTTP GET?
Below is a part of "connector.minimal.php".

`$dir1 = '../../../../uploadImg/';
$dir2 = '/images/';

if ($_SERVER['REQUEST_METHOD'] == 'GET') {
  $user = filter_input( INPUT_GET, "user" );
  if ($user == null ) {
    $user = "";
  }
} else {
  $user = "";
}

$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => $dir1 . $user . $dir2,                 // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/' . $dir1 . $user . $dir2, // URL to files (REQUIRED)
`
