### ISSUE TITLE
Add filters for images uploads

### ISSUE THREAD

**Issue by leveller101** [Studio-42/elFinder#1742]
Was looking to see if i could add another filter based on image dimensions?   I want to be able to restrict the uploading of images that are under a specific pixel width.

Was looking to add the filter somewhere next to the check where the max file size is checked but  cant see to trap the exact point in which to measure the width and then exit if under the pixel limit.

**Comment by nao-pon** [comment]
@leveller101 There is a plugin [`AutoResize`](https://github.com/Studio-42/elFinder/blob/2.1-src/php/plugins/AutoResize/plugin.php). Will it help you?

**Comment by leveller101** [comment]
Thanks will take that apart to see if helps..
