### ISSUE TITLE
Change the image quality during upload, even if the image is not going to be resized

### ISSUE THREAD

**Issue by ToX82** [Studio-42/elFinder#1746]
I am using the AutoResize plugin and it does its job perfectly.

Anyway, sometimes I need to upload images that area already smaller than the AutoResize maxWidth/maxHeight options, and I want their quality to be set to 85. Since the uploaded images are already small, the AutoResize plugin is not triggered and the original quality is preserved.

Would it be feasible to have AutoResize to optimize image quality to all the images, regardless if they are going to be resized or not?

**Comment by nao-pon** [comment]
@ToX82 I added plugin option `'forceEffect`. Please set it to `true`.

```php
'plugin' => array(
	'AutoResize' => array(
		'enable'         => true,       // For control by volume driver
		'maxWidth'       => 1024,       // Path to Water mark image
		'maxHeight'      => 1024,       // Margin right pixel
		'quality'        => 95,         // JPEG image save quality
		'preserveExif'   => false,      // Preserve EXIF data (Imagick only)
		'forceEffect'    => true,       // For change quality of small images
		'targetType'     => IMG_GIF|IMG_JPG|IMG_PNG|IMG_WBMP // Target image formats ( bit-field )
	)
)
```

Thanks! 👍

**Comment by ToX82** [comment]
Wow so fast, thank you!
