### ISSUE TITLE
Open File Browser on upload button directly

### ISSUE THREAD

**Issue by pingtux** [Studio-42/elFinder#1747]
Hi,

Is it possible to open the OS file browser on click on the "upload" button directly (instead of opening the overlay with the pastebox)?

**Comment by nao-pon** [comment]
@pingtux Please set a client option [`commandsOptions.upload.ui`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#commandsoptions) to 'uploadbutton';

**Comment by mgrabazey** [comment]
Hi.
I do it, but have:
