### ISSUE TITLE
Resize before add watermark

### ISSUE THREAD

**Issue by tranbinhcse** [Studio-42/elFinder#1756]
Hello!
How to Resize before adding watermark, because if like add watermark ago when resize the watermark will be small, asynchronous

**Comment by nao-pon** [comment]
@tranbinhcse  Please apply AutoResize plugin first.

e.g.
```php
'upload.presave' => array(
	'Plugin.AutoResize.onUpLoadPreSave',
	'Plugin.Watermark.onUpLoadPreSave',
),
```
