### ISSUE TITLE
Is that possible to create multiple thumbnails of uploaded image

### ISSUE THREAD

**Issue by ercanertan** [Studio-42/elFinder#1763]
I was checking around to create multiple thumbnails of uploaded image but could't see anything related.
How to create multiple thumbnails with different provided size of uploaded image

Example

My_Photo_small.png
My_Photo_medium.png
My_Photo_big.png

Thanks

**Comment by nao-pon** [comment]
@ercanertan Please check #1331. Maybe that will help you.
