### ISSUE TITLE
Relocating toolbar buttons under file rows

### ISSUE THREAD

**Issue by mauleous** [Studio-42/elFinder#1768]
Hi there, 

As part of my UI design exercise, I am trying to relocate the buttons from the toolbar into a hidden bar under each file row in the file listing.
I managed to add the hidden bar under each file. However, I don't know how to make the buttons functional. 

I attached a GIF animation of what I have got so far.
![elfinder hidden bar](https://cloud.githubusercontent.com/assets/16491906/20566803/12a8d82e-b19f-11e6-94e9-9c2e12e7d33c.gif)

Can anyone give me some clues on how I can achieve this?

Thanks a bunch!

**Comment by nao-pon** [comment]
@mauleous Are you accept replace it with a context menu?

![fireshot capture 8 - elfinder 2 1 x - file manager for web_ - https___studio-42 github io_elfinder_](https://cloud.githubusercontent.com/assets/1412630/20584187/a0626876-b233-11e6-8a8e-332d5f8aabac.png)

**Comment by mauleous** [comment]
@nao-pon Oh true! Actually it has the same functionality to a context menu 😄 

However, the idea is to allow user to access those buttons without having to 'right-click' and at the same time to increase (a bit) the area of the file browsing area by hiding the toolbar.
Therefore, I am trying to have those buttons in a hidden bar.

**Comment by nao-pon** [comment]
OK, You can get toolbar DOM by `fm.getUI('toolbar')` and controllable it.

There is a live example for it. -> http://jsbin.com/nerese/edit?html,output

**Comment by mauleous** [comment]
Awesome! 😮  Thank you very much @nao-pon ! 

I will try to continue from what you wrote there... And if I may, I would like to clarify some things to make sure that I understand your code with inline comments:



```javascript
$('#elfinder').elfinder({
    url : 'php/connector.php',
    handlers: {   
        init: function(e, fm) {    // Question 1: "handlers:{ init:" is this how we can add new function to elFinder?
            fm.one('open', function() {     //Question 2: what is "fm.one('open' "?  
                var tm,
                    toolbarLive,
                    clearTm = function() {
                        tm && clearTimeout(tm);
                    },
                    toolbar = fm.getUI('toolbar')   // get the toolbar :D
                        .addClass('ui-front')  // add 'ui-front' class to the toolbar
                        .css({position:'absolute'})  // add a style to the toolbar
                        .hide() 
                        .on('mouseenter', function() {  // add new action when cursor move into toolbar
                            toolbarLive = true;
                        })
                        .on('mouseleave', function() {  // add new action when cursor move away from toolbar
                            toolbarLive = false;
                            toolbarHide();
                        }),
                    toolbarHide = function() {   // a function to hide the toolbar. Toggle the boolean toolbarLive and then hide the toolbar
                        clearTm();
                        tm = setTimeout(function() {
                            ! toolbarLive && toolbar.hide();
                        }, 500);
                    };
                fm.trigger('uiresize');  //Question 3: what does this do?
                fm.getUI('cwd') // Question 4: Is this to get every row in the file listing?
                    .on('mouseenter', '[id]', function() {   //when cursor move into the row, then...
                        var $this = $(this);
                        clearTm();
                        tm = setTimeout(function() {
                            var offset = $this.offset();
                            toolbar.css({top: offset.top+$this.height()}).show();   //... add a style to position the toolbar, and then show it
                        }, 1500);
                    })
                    .on('mouseleave', '[id]', function() {  // when cursor move away from the row, then...
                        toolbarHide(); // ...hide the toolbar 
                    });
            });
        }
    }
});
```

**Comment by nao-pon** [comment]
> Question 1: "handlers:{ init:" is this how we can add new function to elFinder?

There is a method `bind` in elFinder instance. see https://github.com/Studio-42/elFinder/wiki/Client-event-API .

e.g.
```javascript
var fm = $('elfinder').elfinder(opts).elfinder('instance');
fm.bind('init', function(event, fm) {});
fm.bind('init', function(event, fm) {});
```

> Question 2: what is "fm.one('open' "?  

also see https://github.com/Studio-42/elFinder/wiki/Client-event-API .

> fm.trigger('uiresize');  //Question 3: what does this do?

Fit height to elFinder node height of tree and cwd and also call any binding functions.

> fm.getUI('cwd') // Question 4: Is this to get every row in the file listing?

The node obtained by `fm.getUI('cwd')` is the parent node containing each items.

**Comment by mauleous** [comment]
Cool! Thank you for the help @nao-pon ! :D
