### ISSUE TITLE
Why does pasting files to the dropPasteFiles area converts to PNG?

### ISSUE THREAD

**Issue by taylankasap** [Studio-42/elFinder#1769]
For example if I copy a .jpg file and paste it, it's automatically converted to PNG & filesize is much higher than the original file.

Or if I copy & paste a .doc file it gets uploaded, it makes me wait, but nothing changes in the folder.

See [here](https://studio-42.github.io/elFinder/#elf_l2_cG9ucG9u). Download the doc file to your computer, copy it in your computer, go to elfinder, click upload button, paste to the dropPasteFiles area.

Shouldn't all files be uploaded as they are? Or is this related to browser support?

**Comment by nao-pon** [comment]
@taylankasap 

> For example if I copy a .jpg file and paste it, it's automatically converted to PNG & filesize is much higher than the original file.

That is the specification of the browser. If you want to upload a file, please drag and drop or paste the image URL.

> Download the doc file to your computer, copy it in your computer, go to elfinder, click upload button, paste to the dropPasteFiles area.

Only images or text data can be pasted. If you want to upload a file, drag and drop it or use the file selection dialog.
