### ISSUE TITLE
Some thing wrong in lang.js

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1770]
![screenshot_2016-11-24-22-52-55](https://cloud.githubusercontent.com/assets/18566890/20606778/2ba11ca6-b299-11e6-87a8-25f8734ac3f9.png)

**Comment by CodeLyokoXtEAM** [comment]
some times it happen. I try to refresh page several times.
![image](https://cloud.githubusercontent.com/assets/18566890/20641976/a374b062-b429-11e6-9750-9ec26cdc02b0.png)

**Comment by CodeLyokoXtEAM** [comment]
![image](https://cloud.githubusercontent.com/assets/18566890/20641993/ea421e3a-b429-11e6-911f-2bf14ca87a8c.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks! 👍
