### ISSUE TITLE
Find the size of the deleted folder

### ISSUE THREAD

**Issue by taylankasap** [Studio-42/elFinder#1772]
```php
// other codes...
'bind' => array(
    'rm' => 'on_remove'
)
// other codes...

function on_remove($cmd, $result, $args, $elfinder, $dstVolume) {
     // I need the total size of the deleted folder
}
```

How can I get the total size of the deleted folder?

**Comment by taylankasap** [comment]
I found a way but is there a better way to do this?

```php
'bind' => array(
    'rm.pre' => 'on_pre_remove',
    'rm' => 'on_remove'
)

function on_pre_remove($cmd, $args, $elfinder, $dstVolume) {
    $pathToFolder = $dstVolume->getPath($args['targets'][0])
    $sizeVariableAccessableFromOnRemoveFunction = calculate_folder_size_manually($pathToFolder);
}

function on_remove($cmd, $result, $args, $elfinder, $dstVolume) {
    var_dump($sizeVariableAccessableFromOnRemoveFunction);
}
```

**Comment by nao-pon** [comment]
@taylankasap Yes, that way is fine. Since elFinder does not record the file size when deleting files, you need to obtain the size of the target item before deleting the file.

Alternatively, if you extend the volume driver, you can record the size in file deletion. In that case extend the `elFinderVolumeDriver :: delTree ()` method.

**Comment by taylankasap** [comment]
OK, thanks. I also found the way to calculate the size via the help of the elfinderVolumeDriver without extending it:

```php
function on_pre_remove($cmd, $args, $elfinder, $dstVolume) {
    $totalSize = 0;

    foreach ($args['targets'] as $targetHash) {
        $totalSize += $dstVolume->size($targetHash);
    }
}
```

@nao-pon You should add howto label to this issue, it might help someone.
