### ISSUE TITLE
hashes argument for custom command is empty

### ISSUE THREAD

**Issue by taylankasap** [Studio-42/elFinder#1780]
I created a custom command and added it to the context menu & the toolbar. Using the context menu works but using the toolbar button doesn't: `hashes` argument is undefined.

**Reproduce:**

1. [Install elfinder](https://github.com/Studio-42/elFinder#installation)

2. Replace the document ready code with this in `elfinder.html`:

```javascript
$(document).ready(function() {
    elFinder.prototype.i18.en.messages['cmdshare'] = 'Share';
    elFinder.prototype._options.commands.push('share');
    elFinder.prototype.commands.share = function() {
        this.exec = function(hashes) {
            console.log(hashes);
        }
        this.getstate = function() {
            return 0;
        }
    };
    $('#elfinder').elfinder({
        url : 'php/connector.minimal.php',
        contextmenu: {
            files: ['share']
        },
        uiOptions: {
            toolbar : [
                ['share']
            ]
        }
    });
});
```

3. Upload a file

4. Right click -> Share -> Now you can see an array with 1 item in the devtools console

5. Now instead of right clicking, select the file and click the share button in toolbar. Now in the devtools console there is an `undefined` instead of an array

**Note:** Using `this.hashes()` in `exec` method still works.

**Comment by nao-pon** [comment]
@taylankasap Please use `this.hashes(hashes)` for get selected items hash.

```javascript
this.exec = function(hashes) {
    var selHashes = this.hashes(hashes);
    console.log(selHashes);
}
```

**Comment by taylankasap** [comment]
What is the use of `hashes` parameter? Using `this.hashes()` without an argument works too.

**Comment by nao-pon** [comment]
The hashes parameter is assigned a target when called from a context menu or the like. When an item is selected and called from the toolbar, it is necessary to acquire the selected items.

see https://github.com/Studio-42/elFinder/blob/master/js/elFinder.command.js#L271-L282
