### ISSUE TITLE
Can I have equal file hashes between multiple elFinder instances?

### ISSUE THREAD

**Issue by mungurs** [Studio-42/elFinder#1781]
I have several elFinder instances with same config but different roots attributes. 
Is there a way to have equal file hashes between instances? 
I can see that $volumesCnt is static and it is incremented in every instance, thats why volume ids and file hashes are not equal.

**Comment by mungurs** [comment]
Looks like only way is to set $_SERVER['HTTP_X_ELFINDER_VOLUMESCNTSTART'] manuali.

**Comment by nao-pon** [comment]
@mungurs There is an option `id` of connector configuration.

e.g.
```
'roots'  => array(
    array(
        'id'     => 'a',
        'driver' => 'LocalFileSystem',
        'path'   => '/path/to/files/',
        'URL'    => 'http://localhost/to/files/'
    )
)
```
`hash` become `la_xxx`

**Comment by mungurs** [comment]
Thanks you!
