### ISSUE TITLE
Eldfinder-Codeigniter integration root not found

### ISSUE THREAD

**Issue by rochellecanale** [Studio-42/elFinder#1784]
Hi there,
I followed every steps in integrating elfinder together with my elfinder but I got this error:
`{"error":["errConf","errNoVolumes"],"debug":["Driver \"elFinderVolumeLocalFileSystem\" : Root folder does not exist."]}`

Here's my config sample:

`
public function elfinder_init() {
        $this->load->helper('path');
        
        $opts = array(
            'debug' => true, 
            'roots' => array(
                array( 
                    'driver' => 'LocalFileSystem', 
                    'path'   => base_url('file_uploads') . '/', 
                    'URL'    => base_url('file_uploads') . '/'
                ) 
            )
        );
        $this->load->library('elfinder_lib', $opts);
    }
`

I put my file_uploads directory to the root of my website.
`
mywebsite
    - file_uploads
    - application
    - system
   ....
`

Can you help me with this?

**Comment by rochellecanale** [comment]
I already changed my URL to this:
`'URL'    => site_url('system/elfinder_init')`
But still same effect

**Comment by rochellecanale** [comment]
Ok I managed to solve it. :)

**Comment by satanand7** [comment]
Any update with it or not.. I am also waiting for codeigniter integration.
