### ISSUE TITLE
CakePHP + TinyMce + Elfinder

### ISSUE THREAD

**Issue by starstrap** [Studio-42/elFinder#1786]
Hello everyone. I'm facing a problem since i'm trying to install Elfinder plugin for Tinymce on Cakephp 2.x.

I've followed the guide provided by https://github.com/hashmode/Tinymce-Image-Upload-Cakephp and all seems to be ok, except when i click on browse button to search or upload for an image. The popup opens, but probably the variable "window_url" (part of $config) in elfinder.php points to the wrong url. Browser's console gives me this url: "http://localhost/uniman-admin/app/help_desks/elfinder". help_desks is the controller. is it the right path?

CakePhp's debug tells me that "../../Plugin/TinymceElfinder/View/TinymceElfinders/elfinder.ctp", i can't uderstand why path is wrong.

I'm attaching some code:

this is javascript tinymce init in template file:
`<script type="text/javascript"> 
tinymce.init({
  selector: 'textarea',
  height: 500,
  menubar: false,
  plugins: [
    'advlist autolink lists link image charmap print preview anchor',
    'searchreplace visualblocks code fullscreen',
    'insertdatetime media table contextmenu paste code'
  ],
  toolbar: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
  content_css: '//www.tinymce.com/css/codepen.min.css',
  **file_browser_callback: elFinderBrowser** //calls elFinder plugin for image browser/upload
});
</script> ` 
still in the same file, according to official guide, i've added this line :
`$this->TinymceElfinder->defineElfinderBrowser();`

this is the Helper provided by the plugin:
`class TinymceElfinderHelper extends AppHelper {
	
	public function defineElfinderBrowser($inline = true) {
		Configure::load('elfinder');
		$script = '
		function elFinderBrowser (field_name, url, type, win) {
			  tinymce.activeEditor.windowManager.open({
			    file: "'.Configure::read('Elfinder.window_url').'",
			    title: "'.Configure::read('Elfinder.title').'",
			    width: '.Configure::read('Elfinder.width').',  
			    height: '.Configure::read('Elfinder.height').',
			    resizable: "'.Configure::read('Elfinder.resizable').'"
			  }, {
			    setUrl: function (url) {
			      win.document.getElementById(field_name).value = url;
			    }
			  });
			  return false;
			}
		';
		if ($inline) echo '<script type="text/javascript">' . $script . '</script>';
		return $script;
	}`
everything seems to be ok.

This is elfinder.php config file that i've added in /Config directory
`<?php
$config = array (
	'Debug'	=> true,
	'Elfinder' => array (
		'title' => ('Title'),
		'width' => 900,
		'height' => 500,
		'resizable' => 'yes',
			
'window_url' => **Router::fullbaseUrl().'/uniman-admin/help_desks/elfinder**',		// call elfinder window
		**'connector_url' => Router::fullbaseUrl().'/uniman-admin/help_desks/connector'**,
		'locale' => 'en', 
	
	'options' => array(
			'debug' => true,
			'roots' => array(
				array(
					'driver'        => 'LocalFileSystem'
					'URL'   		=> Router::fullbaseUrl().'/uniman-admin/img/faq',
					'path'          => IMAGES.'faq',	        				
	                                'accessControl' => 'access', 
					'attributes' => array(
						array(
							'pattern' => '!\.html$!',
							'hidden' => true
						)
					),
					'tmbPath' => 'tumbnails',
					'uploadOverwrite' => false,
				)
			)
		)
	) 
);
?>`
the only edit i've done is changing 'my_controller'
'window_url' => Router::fullbaseUrl().'/my_controller/elfinder',
'connector_url' => Router::fullbaseUrl().'/my_controller/connector',
 with my real controller's name
'window_url' => Router::fullbaseUrl().'/uniman-admin/help_desks/elfinder',
'connector_url' => Router::fullbaseUrl().'/uniman-admin/help_desks/connector',

This is part of Controller's code related to elfinder's methods (according to official guide):

`public function elfinder() {
		$this->TinymceElfinder->elfinder();

    }
    
    public function connector() {
        $this->TinymceElfinder->connector();
    }`

do you think i'm doing something wrong? Is it a cakephp problem? 

thank you

**Comment by starstrap** [comment]
Hello everyone. I'm facing a problem since i'm trying to install Elfinder plugin for Tinymce on Cakephp 2.x.

I've followed the guide provided by https://github.com/hashmode/Tinymce-Image-Upload-Cakephp and all seems to be ok, except when i click on browse button to search or upload for an image. The popup opens, but probably the variable "window_url" (part of $config) in elfinder.php points to the wrong url. Browser's console gives me this url: "http://localhost/uniman-admin/app/help_desks/elfinder". help_desks is the controller. is it the right path?

CakePhp's debug tells me that "../../Plugin/TinymceElfinder/View/TinymceElfinders/elfinder.ctp", i can't uderstand why path is wrong.

I'm attaching some code:

this is javascript tinymce init in template file:
`<script type="text/javascript"> 
tinymce.init({
  selector: 'textarea',
  height: 500,
  menubar: false,
  plugins: [
    'advlist autolink lists link image charmap print preview anchor',
    'searchreplace visualblocks code fullscreen',
    'insertdatetime media table contextmenu paste code'
  ],
  toolbar: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
  content_css: '//www.tinymce.com/css/codepen.min.css',
  **file_browser_callback: elFinderBrowser** //calls elFinder plugin for image browser/upload
});
</script> ` 
still in the same file, according to official guide, i've added this line :
`$this->TinymceElfinder->defineElfinderBrowser();`

this is the Helper provided by the plugin:
`class TinymceElfinderHelper extends AppHelper {
	
	public function defineElfinderBrowser($inline = true) {
		Configure::load('elfinder');
		$script = '
		function elFinderBrowser (field_name, url, type, win) {
			  tinymce.activeEditor.windowManager.open({
			    file: "'.Configure::read('Elfinder.window_url').'",
			    title: "'.Configure::read('Elfinder.title').'",
			    width: '.Configure::read('Elfinder.width').',  
			    height: '.Configure::read('Elfinder.height').',
			    resizable: "'.Configure::read('Elfinder.resizable').'"
			  }, {
			    setUrl: function (url) {
			      win.document.getElementById(field_name).value = url;
			    }
			  });
			  return false;
			}
		';
		if ($inline) echo '<script type="text/javascript">' . $script . '</script>';
		return $script;
	}`
everything seems to be ok.

This is elfinder.php config file that i've added in /Config directory
`<?php
$config = array (
	'Debug'	=> true,
	'Elfinder' => array (
		'title' => ('Title'),
		'width' => 900,
		'height' => 500,
		'resizable' => 'yes',
			
'window_url' => **Router::fullbaseUrl().'/uniman-admin/help_desks/elfinder**',		// call elfinder window
		**'connector_url' => Router::fullbaseUrl().'/uniman-admin/help_desks/connector'**,
		'locale' => 'en', 
	
	'options' => array(
			'debug' => true,
			'roots' => array(
				array(
					'driver'        => 'LocalFileSystem'
					'URL'   		=> Router::fullbaseUrl().'/uniman-admin/img/faq',
					'path'          => IMAGES.'faq',	        				
	                                'accessControl' => 'access', 
					'attributes' => array(
						array(
							'pattern' => '!\.html$!',
							'hidden' => true
						)
					),
					'tmbPath' => 'tumbnails',
					'uploadOverwrite' => false,
				)
			)
		)
	) 
);
?>`
the only edit i've done is changing 'my_controller'
'window_url' => Router::fullbaseUrl().'/my_controller/elfinder',
'connector_url' => Router::fullbaseUrl().'/my_controller/connector',
 with my real controller's name
'window_url' => Router::fullbaseUrl().'/uniman-admin/help_desks/elfinder',
'connector_url' => Router::fullbaseUrl().'/uniman-admin/help_desks/connector',

This is part of Controller's code related to elfinder's methods (according to official guide):

`public function elfinder() {
		$this->TinymceElfinder->elfinder();

    }
    
    public function connector() {
        $this->TinymceElfinder->connector();
    }`

do you think i'm doing something wrong? Is it a cakephp problem? 

thank you

**Comment by nao-pon** [comment]
@starstrap We do not know about Tinymce-Image-Upload-Cakephp. Please ask to Tinymce-Image-Upload-Cakephp developers.
