### ISSUE TITLE
no Preview for pdf / office-files in elFinder

### ISSUE THREAD

**Issue by uh1959** [Studio-42/elFinder#1787]
Hello,
i can do whatever I want whether with the version 2.1 or 2.1.10 or the current 2.1.18 I get no preview of pdf or Office files it always appears only the dark popup-window with the file information. Only with jpg appears the spinner briefly and then the desired preview. 
Do I have to set any parameters?  In the elfinder.html i activated quicklook.googledocs.js

example: http://online1967.de/elfinder/elfinder.html

![1](https://cloud.githubusercontent.com/assets/24320468/20841992/23da3e8a-b8b6-11e6-8ac5-f7beee6816e2.jpg)
![2](https://cloud.githubusercontent.com/assets/24320468/20841996/2d094c1c-b8b6-11e6-926a-c9210f86e7f9.jpg)

**Comment by uh1959** [comment]
Hi again,

now i have an preview, but only in Ver. 2.1
The next big problem are the German Umlaute eg. Ü Ä ü ä ß. The Files or Directory with this dosn´t display. The old Workorund with:
protected function array_walk_deep(&$items){
foreach ($items as &$item) {
    if(is_array($item)) {
        $this->array_walk_deep($item);
    } else {            
        $item = utf8_encode($item);
    }}
dont work.

**Comment by uh1959** [comment]
Now it work´s but only in the Version 2.1 an only by jpg and pdf.

**Comment by nao-pon** [comment]
@uh1959 Please set client configuration `commandsOptions.quicklook.googleDocsMimes`.

e.g.
```javascript
commandsOptions: {
	quicklook: {
		googleDocsMimes : ['application/pdf', 'image/tiff', 'application/vnd.ms-office', 'application/msword', 'application/vnd.ms-word', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
	}
}
```

Note:
`quicklook.googledocs.js` is preview plugin for Google Apps contents on the GoogleDrive volume.

**Comment by uh1959** [comment]
Hello again,
i have the file quicklook.googledocs.js attentively studied, unfortunately, but I have no idea where I should insert the commandOptions lines. Be so kind as to give me another hint.
 Greeting Uwe

**Comment by nao-pon** [comment]
It is "[client configuration](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#commandsoptions)". Please check out WIki(https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#commandsoptions).

**Comment by uh1959** [comment]
Thank you :-)
