### ISSUE TITLE
Problem on upload file which has size more than 2 MB

### ISSUE THREAD

**Issue by ramin-gitt** [Studio-42/elFinder#1788]
Hi. We upgraded elfinder from 2.1.14 version to 2.1.18 version. After upgrade we can not upload file which has size more than 2 MB. Process stops after upload 2 MB chunk. It shows from screen  and network manager. You can see from attached file. [http://auroarchitect.az/ramin/elfinder.jpg
![elfinder](https://cloud.githubusercontent.com/assets/24373118/20867968/f25c339e-ba69-11e6-947e-931898008e42.jpg)
But we have not problem in previous version.

**Comment by nao-pon** [comment]
@ramin-gitt What about [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip)? Please check on [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon I try to upload 54mb file to your Site. But connection is break complete half of it. Can you check it?

**Comment by nao-pon** [comment]
@ramin-gitt , @CodeLyokoXtEAM I found a bug of xhr.timeout, so I will fix it. Thanks!
