### ISSUE TITLE
Crop dimensions automatically changes

### ISSUE THREAD

**Issue by ramin-gitt** [Studio-42/elFinder#1789]
Hi. I have problem with cropping image. In some of dimensions (width and height). After clicked to image automatically change dimensions.
Example: I set width and height to 1349 x 362. After clicked to image automatically width and height changed to 1336 x 360. I attached 2 image (before and after clicked to image).
![elfinder-crop-before-mouse](https://cloud.githubusercontent.com/assets/24373118/20868785/46842e5a-ba7d-11e6-9065-0b02cc02954c.jpg)
![elfinder-crop-after-mouse](https://cloud.githubusercontent.com/assets/24373118/20868791/4e312e6e-ba7d-11e6-87a3-df744bc66187.jpg)

**Comment by nao-pon** [comment]
@ramin-gitt When the 8px grid is enabled, it changes in units of 8px. However, even if it is disabled, the vertical and horizontal values change with dragging. This is a bug so I will fix it.
