### ISSUE TITLE
Unable to download file even small file

### ISSUE THREAD

**Issue by rochellecanale** [Studio-42/elFinder#1790]
Hi admin,

I am successfully integrated my elfinder into my Codeigniter application. But my problem for now is I can't download my uploaded file.  Here's my sample output error:

```
File not found

Firefox can’t find the file at http://localhost/teradasys/index.php/system/elfinder_init?cmd=file&target=l1_VW50aXRsZWQucG5n&download=1&perm_type=2&string_lookup=CROSS_POWER_PHILIPPINES_INC.

    Check the file name for capitalization or other typing errors.
    Check to see if the file was moved, renamed or deleted.

```

But if I try to right click the file then get info and click the link there I can download the file without error.
Can you help me?

**Comment by rochellecanale** [comment]
This happens if I try to load the elfinder using Bootstrap modal. But if the elfinder is in one page it can download without any error.

**Comment by rochellecanale** [comment]
When I checked the uploaded file there are some files that can not download and others are fine. Why is it happening? When I checked my console tab the error is 404 not found.

**Comment by nao-pon** [comment]
@rochellecanale Probably the URL of the roots of the connector option is not set correctly. Please ask to the CodeIgniter side.
