### ISSUE TITLE
Syntax error connector.php-dist

### ISSUE THREAD

**Issue by wintstar** [Studio-42/elFinder#1793]
Last Pull Request => [cmd:resize] fix #1789 bug that crop image size is change while dragging

elFinder/php/connector.php-dist, line 343. Missing here a comma?
find
```
				array(
					'pattern' => '/^\/icons$/',
					'read' => true,
					'write' => false
				)
			)
```
replace with
```
				array(
					'pattern' => '/^\/icons$/',
					'read' => true,
					'write' => false
				)
			),
```

![syntax-error](https://cloud.githubusercontent.com/assets/2753863/20896198/ddad498e-bb1c-11e6-8b37-5e27c653767e.png)

**Comment by nao-pon** [comment]
@wintstar Thanks!
