### ISSUE TITLE
How to make each subfolder has its own .tmb folder?

### ISSUE THREAD

**Issue by drmohm** [Studio-42/elFinder#1795]
elfinder is really a perfect browser and I really like it, but I cannot achieve the following
I want the thumbnails for each subfolder to be created in .tmb folder inside that subfolder, how I can do this?

could you please help me?

**Comment by mungurs** [comment]
I don't think its possible per folder basis. You could create multiple roots and have tmb folder in each on them. 
You could explain your problem more in detail. There could be another solution.

**Comment by drmohm** [comment]
I'm working on a photo gallery script which use the thumbnails created by elfinder.
Also I modify the elfinder  tmbname() to generate the thumbnail filename that is identical as the original file name (i.e  original_file_name.png ).

The problem occurs when 2 images in different directories has the same name, and because elfinder uses a single .tmb folder so I'will always have one thumbnail for both images.

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon how about save tmb file like 'hash of path _ file name'?

**Comment by mungurs** [comment]
Or you can just append hash at the end of file name?

**Comment by drmohm** [comment]
Thanks, for your help
I slightly modify your ideas and I solve it by appending the timestamp to the file name while upload.
which may help later in file sorting

thanks again

**Comment by nao-pon** [comment]
@drmohm This is simply example of extended class of LocalFileSystem.

```php
class elFinderVolumeMyLocalFileSystem extends elFinderVolumeLocalFileSystem
{
	protected function tmbname($stat) {
		$dir = $this->relpathCE($this->decode($stat['phash']));
		if (! is_dir($this->tmbPath.DIRECTORY_SEPARATOR.$dir)) {
			$dirs = explode(DIRECTORY_SEPARATOR, $dir);
			$target = $this->tmbPath;
			foreach($dirs as $_dir) {
				if (! is_dir($target . DIRECTORY_SEPARATOR . $_dir)) {
					mkdir($target . DIRECTORY_SEPARATOR . $_dir);
				}
				$target = $target . DIRECTORY_SEPARATOR . $_dir;
			}
		}
		return $dir . DIRECTORY_SEPARATOR . $stat['name'];
	}
}
```

**Comment by isreehari** [comment]
Can anyone update on this please, I am having the same issue. @nao-pon

> but have small problem , after upload dont show thumb , but after refresh show thumb

Thanks,
Hari

**Comment by nao-pon** [comment]
@isreehari I tested on above custom volume driver with elFinder 2.1.38. That is in no problems.

**Comment by isreehari** [comment]
Thank you for the quick update. Let me tell you when this happening I am using the preUpload method and when ever user upload a file I am moving under subfolder like this file-root-folder/year/month/file.ext eg: spfiles/2018/05/file.ext. Please find the following code. 





```
public function preUpload(&$path, &$name, $src, $elfinder, $volume){            

            $currentYear = date("Y");
            $currentMonth = date("m");
            
            $realpath = $elfinder->realpath($path);
            $realpath =  $realpath. '/' .$currentYear;

            if(!file_exists($realpath) || !is_dir($realpath)){
                $args = array('target' => $path, 'name' => $currentYear, 'reqid' => '' );
                $result = $elfinder->exec('mkdir', $args);
                if($result && $result["added"]){
                    $path = $result['added'][0]['hash'];         

                    $realpath = $realpath . '/' .  $currentMonth;
                    $args = array('target' => $path, 'name' => $currentMonth, 'reqid' => '' );
                    $result = $elfinder->exec('mkdir', $args);
                    if($result && $result["added"]){
                        $path = $result['added'][0]['hash'];    
                    }else{
                        return false;
                    }
                }else{
                    return false;
                }              
            }else{
                $realpath = $realpath . '/' .  $currentMonth;
                if(!file_exists($realpath) || !is_dir($realpath)){
                    $args = array('target' => $path, 'name' => $currentMonth, 'reqid' => '' );
                    $result = $elfinder->exec('mkdir', $args);
                    if($result && $result["added"]){
                        $path = $result['added'][0]['hash'];    
                    }else{
                        $path = $volume->getHash($path, $currentMonth);
                        return true;
                    }
                }                

            }

            $path = $volume->getHash($realpath, '');

            return true;
    }   

```

**Comment by nao-pon** [comment]
@isreehari This problem is caused by the fact that the elFinder class does not support multi-level directory creation when uploading. Please create a new Issue.

Thanks! 👍

**Comment by isreehari** [comment]
Thank you and sure.

**Comment by mathiuleo** [comment]
Hello,

Thanks for the solution.
I am succesful to create thumbnail in .tmb folder inside that subfolder.

But when I delete the sub folder from its original place. The sub folders inside the .tmb are still exist and not deleted.
How do I sync folders when I rename or delete the sub folders?

Thank you and kind regards
