### ISSUE TITLE
How to mkdir and mkfile without rename ?

### ISSUE THREAD

**Issue by limars** [Studio-42/elFinder#1796]
Hi all:
I have a question to ask. I wanna achieve a function on elfinder. when I click mkfile or mkdir on toolbar, the file or folder will be created and wait for your rename, but I wanna remove the rename action on this command (mkdir and mkfile). How to do that ?
Thanks

**Comment by nao-pon** [comment]
@limars This is a simple example to it. ([Live demo](http://jsbin.com/hixeti/edit?js,output))

```javascript
var elf = $('#elfinder').elfinder(opts).elfinder('instance');

// Auto blur to mkdir and mkfile without rename
elf.getUI('cwd').on('focus', '.elfinder-cwd-file-tmp textarea,.elfinder-cwd-file-tmp input', function() {
	var input = this;
	setTimeout(function() {	
		input.blur();
	}, 100);
});
```
