### ISSUE TITLE
Text editor settings bugs.

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1798]
1. There is available filed 'option' value is says 'undefined'
2. In mobile browsers,
        full screen mode, can't open text setting window.
        Settings close only click outside of edge.(close slide or back button.)

**Comment by CodeLyokoXtEAM** [comment]
Also its must be saved last user selected values

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM 
> Also its must be saved last user selected values

Since it is an example for demonstration, it is not to implement.

Thanks!
