### ISSUE TITLE
Download a folder can be faster?

### ISSUE THREAD

**Issue by phtsaibb** [Studio-42/elFinder#1799]
Download a folder, elFinder will create an archive file for dowloading.
I found it will first copy the folder into a temp place, and then archive this temp folder.
But if I just archive a folder, it will archive the origin folder.

Is there any special reason to copy the origin folder to a temp folder?
If remove the process of copy the origin folder to a temp folder, and directly archive the origin folder to the temp place, the download performance will be better.

**Comment by nao-pon** [comment]
It is necessary for exclude items that are not allowed to read on elFinder. However, if it can use a hard link, that can expect some performance improvement, so I will implement it like that.
