### ISSUE TITLE
elfinder-quicklook-fullscreen

### ISSUE THREAD

**Issue by wintstar** [Studio-42/elFinder#1802]
elFinder 2.1.19

Arrows and close button moved.

![elfinder_fullscreen](https://cloud.githubusercontent.com/assets/2753863/21076464/6cda6ed0-bf2c-11e6-9806-2bc95478d813.PNG)

**Comment by nao-pon** [comment]
@wintstar Which browser are you using? Please also check on our [demo site](https://studio-42.github.io/elFinder/).

**Comment by wintstar** [comment]
Firefox 50.0,2. In the demo, the arrows and the close button are in the right place. I will check this again with at me.

**Comment by wintstar** [comment]
Sorry, it was on another stylesheet of my website. With version 2.1.19, it is now much easier to integrate elFinder into own website. Simply these 2 codes and elfinder.min.css a little bit customize, finish.
into head
```
		<!-- Require JS (REQUIRED) -->
		<!-- Rename "main.default.js" to "main.js" and edit it if you need configure elFInder options or any things -->
		<script data-main="./org-main.default.js" src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.3.2/require.min.js"></script>
```
an this in content
`<div id="elfinder"></div>`

@nao-pon , A great software you created. Thanks

**Comment by nao-pon** [comment]
@wintstar Thanks!
