### ISSUE TITLE
Each root with own permission

### ISSUE THREAD

**Issue by neong** [Studio-42/elFinder#1806]
Can elFinder perform for each root have own permission like delete, upload, rename and etc? If yes, can you teach me how to do it? Thanks.

**Comment by nao-pon** [comment]
@neong Did you check the [Wiki - disabled](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#disabled) or [Wiki - attributes](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#attributes)?

**Comment by neong** [comment]
Yes. I check on it. But that was not I want that which user have different
permission for different root. For example, user can access root1 and
root2. While user click on root1, user can delete file and folder but when
click on root2, user have no right to perform delete file and folder.

**Comment by nao-pon** [comment]
I'm not sure. Isn't a like this?
```php
$opts = array(
    'locale' => '',
    'roots'  => array(
        array(
            'alias'  => 'root1',
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        ),
        array(
            'alias'  => 'root2',
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files2/',
            'URL'    => 'http://localhost/to/files2/',
            'disabled' => array('mkdir','mkfile','rm','rename','duplicate','paste','upload','put','archive','extract','resize')
        )
    )
);
```

**Comment by neong** [comment]
Thanks Naoki. I may try it out. It's look like what I needs. You help was
very meaningful to me.
