### ISSUE TITLE
How and when to use cssAutoLoad / loadCss?

### ISSUE THREAD

**Issue by mungurs** [Studio-42/elFinder#1809]
I would love to hear the use cases for [cssAutoLoad](https://github.com/Studio-42/elFinder/search?utf8=%E2%9C%93&q=cssAutoLoad) and [elFinder.prototype.loadCss](https://github.com/Studio-42/elFinder/search?utf8=%E2%9C%93&q=loadCss) .

**Comment by nao-pon** [comment]
@mungurs [Here](http://jsbin.com/qaxebix/edit?html,js,output) is an example using RequireJS.

**Comment by nao-pon** [comment]
@mungurs Have you got it?

**Comment by mungurs** [comment]
Can I autoload css files via cssAutoLoad option setting? To me it looks like they are doing the same thing.

**Comment by nao-pon** [comment]
Yes, elFinder load elfinder.min.css and theme.css automatically with using elfinder.min.js or elfinder.full.js.

**Comment by mungurs** [comment]
Thanks
