### ISSUE TITLE
chdir no working

### ISSUE THREAD

**Issue by kerker** [Studio-42/elFinder#1810]
hi, I have a problem when trying to create archive or extract the file.
It's happened after copy from old server.It's work fine before
The old platform is Solaris 5.10 & PHP 5.5.24 & elFider 2.1.11 -> It's work fine
Now platform is  RedHat 6.5 & PHP 7.0.8 & elFider 2.1.11 -> create archive or extract the file fail

I'm trying to find the problem
I dump the L:5014 $cwd and $dir in elFinderVolumeDriver.class.php 
It's no happened after It's going to chdir($dir), It's jump to the next code
just like the code chdir is not exist. no matter the path i change it.

I think maybe is the permission problem, 
but chdir() is work in the other project, it's also the same server
do you have any idea about the issue?

**Comment by nao-pon** [comment]
@kerker Please check permission of the directory that volume root option [`quarantine`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#quarantine).

**Comment by kerker** [comment]
I've checked the folder ./.quarantine permission of the directory.
It's set to 0777 still no work.

**Comment by nao-pon** [comment]
What is result of next test.php code?

- test.php (save into same directory to your connector.php)
```php
<?php
error_reporting(-1);

$path = '../files/'; // value of volume roots option `path`

$cwd = getcwd();
$res1 = chdir($path . '.quarantine');
$res2 = chdir($cwd);

var_dump($res1);
var_dump($res2);
```
