### ISSUE TITLE
how Elfinder Connect to Google Storage?

### ISSUE THREAD

**Issue by richseyha** [Studio-42/elFinder#1813]
Dear Sir/Madam,

Now, I am having a big problem that I can not integrate between Elfinder and Google Cloud Storage.
I try to search on google to much but no result for me.

Thanks in advance for your help. Please give me some guide to configure this problem.

Best Regards,

**Comment by nao-pon** [comment]
@richseyha There isn't GCS volume driver to elFinder. But you can use [Superbalist/flysystem-google-cloud-storage](https://github.com/Superbalist/flysystem-google-cloud-storage) on [barryvdh/elfinder-flysystem-driver](https://github.com/barryvdh/elfinder-flysystem-driver). Please check out it.

Thanks!

**Comment by richseyha** [comment]
Yes, thanks you so much for your idea...!
