### ISSUE TITLE
Error on duplicated name

### ISSUE THREAD

**Issue by jhon100** [Studio-42/elFinder#1814]
When trying to rename a file, if the filename exists, an alert is shown and:
- Closing the alert, correcting the filename and clickout (but inside elfinder area), dont removes the focus of filename edition. 
- The focus only is removed (and the renaming is accepted) if press, tab, enter or right clickout.

If there is no duplicated name problem, clicking out after rename removes the focus and accept the new name. I think the same behavior must occur when dealing with duplicated name after correction.

**Comment by nao-pon** [comment]
@jhon100 Thanks! 👍

**Comment by jhon100** [comment]
Thanks @nao-pon , to have this modification I use this?
https://github.com/Studio-42/elFinder/tree/42002388bc6f64c56daedb3e95ebdf9bbd946cec#downloads
- elFinder 2.1.x (Nightly)
