### ISSUE TITLE
Automount Drive on Startup?

### ISSUE THREAD

**Issue by navijo** [Studio-42/elFinder#1815]
Is it possible to automount a Drive folder when the user enters to elFinder?

Thanks!

**Comment by nao-pon** [comment]
@navijo What is "Drive" that you say?

**Comment by navijo** [comment]
Sorry, I mean Google Drive

**Comment by nao-pon** [comment]
Do you want to mount fixed GoogleDrive storage for all access users? Or is it GoogleDrive for each individual?

**Comment by navijo** [comment]
If it's possible, a GoogleDrive storage for all access users.

Thanks

**Comment by nao-pon** [comment]
OK. A refresh token is required to make a permanent mount.

simply example of volume roots option
```php
array(
	'driver' => 'GoogleDrive',
	'path' => '0Byxxxxxx', // folder ID
	'refresh_token' => '1/S-p6xxxxxxxxxxxxxxxxxxxxxxxx',
),
```
To acquire the refresh token with elFinder, you can check it on the debug tab of the info dialog displayed in the [debug mode of the connector](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#debug) by mounting with offline access options when mounting as a network drive.

e.g.
![googledrive refreshtoken](https://cloud.githubusercontent.com/assets/1412630/21287479/dedc4728-c4af-11e6-96ad-c1de08589399.png)

**Comment by AnilaKhan10** [comment]
**nao-pon**
hello this is very Good Working but how can set more mount network see the screenshot thank you
http://clearmobileapss.com/drive/test5/1.png

**Comment by navijo** [comment]
It's working. @nao-pon,Thanks for your help
@AnilaKhan10 You have to configure which options are available in connector.php file

**Comment by AnilaKhan10** [comment]
**navijo**
i am the added 
but still not work please check screenshot thank you 
// define('ELFINDER_GOOGLEDRIVE_CLIENTID',     '');
// define('ELFINDER_GOOGLEDRIVE_CLIENTSECRET', '');

http://clearmobileapss.com/drive/2.jpg
http://clearmobileapss.com/drive/3.jpg

**Comment by navijo** [comment]
You have to install google-api-client by composer: composer require google/apiclient:^2.0
or directly download it from https://github.com/google/google-api-php-client/releases and configure it on connector.php 

`elFinder::$netDrivers['googledrive'] = 'GoogleDrive';
// // GoogleDrive Netmount driver need next two settings. You can get at https://console.developers.google.com
// // AND reuire regist redirect url to "YOUR_CONNECTOR_URL?cmd=netmount&protocol=googledrive&host=1"
define('ELFINDER_GOOGLEDRIVE_CLIENTID','XXXXXXXXXXXX-XXXXXXXXXXX.apps.googleusercontent.com');
define('ELFINDER_GOOGLEDRIVE_CLIENTSECRET', 'XXXXXXXXXXXXXXXXXXXXXX');
// // Required case of without composer
 define('ELFINDER_GOOGLEDRIVE_GOOGLEAPICLIENT', '/YOURPATH/php/plugins/google-api-php-client-2.1.0/vendor/autoload.php');`

**Comment by AnilaKhan10** [comment]
**navijo**
i am tired still not working please correct that i am providing my cpanel pass and name
FTP server: clearmobileapss.com/cpanel
FTP Username: bestamateur
FTP Password: Ab10203040
clearmobileapss.com/Install_To_This_Folder.png
Thank You........

**Comment by navijo** [comment]
Hi @AnilaKhan10 !
I've uploaded elFinder with google-drive-php-client on the folder that you specified. However, it's not public accessible and I couldn't try if it's working. By the way, if you make it public, you should be able to connect to your Google Drive by mounting a new unit via the elFinder UI. 

If you want to automount the unit, you should follow @nao-pon indications on how get the refresh token. You have also to configure your folderId and this refresh token in connector.php file.

Furthermore, change your cPanel credentials because it's not a good idea to expose them anywhere, for instance, here... :)

Hope it works!

**Comment by AnilaKhan10** [comment]
**navijo**
still not working some problem check screenshot
http://clearmobileapss.com/Still_Not_Work_Please_Check.png
Thank You **navijo**

**Comment by navijo** [comment]
I can help you on this error, the same code works for me. Maybe some missing module on your PHP? 

Have you configured your callback URL when configuring your credentials on Google?

**Comment by nao-pon** [comment]
@AnilaKhan10 There are things you need to do to solve yourself. For example, to [search on Google](https://www.google.com/search?q=fatal+error+call+to+undefined+function+guzzlehttp%5Chandler%5Ccurl_reset()) ...
In this case PHP version is too low. It is also specified in the google-api-php-client documentation.
> Requirements : PHP 5.4.0 or higher

**Comment by AnilaKhan10** [comment]
**nao-pon**
i am changed my php version now (Current PHP version:  5.6) check screenshot 
http://clearmobileapss.com/php_version.png
http://clearmobileapss.com/another_problem_now.png
Thank You..............

**Comment by navijo** [comment]
Remove the default GoogleDrive from the roots array in connector.php.
