### ISSUE TITLE
How to show owners of files uploaded by authenticated users  in listview

### ISSUE THREAD

**Issue by gebrerv** [Studio-42/elFinder#1816]
Hi,
We want to use elfinder as frontend for fileexchange with external companies, where every company gets its own elfinder instance.  
For every write access ( delete, upload, remove and the like) we want to force the user from the external company to login, i found the basic authentication example that we can use as starting point.

Also we want to have the Owner of a file displayed in listview, that is possible  setting the cwd listview option "owner and statOwner to true.
The owner that is shown apparently is the user  under which the http demon runs, it is possible to change the ownership of a file on OS , then this user is shown.

What possibilities exist to show the user that has logged in and later uploaded a file without having to create/ use an OS user identical to the user logged on and to perform a chown for uploaded files ?

regards Gerhard

**Comment by nao-pon** [comment]
@gebrerv In such a case, it seems that PHP is executed with each user privilege with FastCGI etc. in many cases. If that is impossible, you need to save it as metadata associated with the file in some database and return the owner information with the expanded volume driver.

**Comment by gebrerv** [comment]
Hi Naoki,

thanks for your fast response. You’re right, I already feared that I have to manage the user as metadata and extend the file system driver accordingly but hoped that somebody else did this exercise before …

Best regards Gerhard

Von: Naoki Sawada [mailto:notifications@github.com]
Gesendet: Montag, 19. Dezember 2016 14:31
An: Studio-42/elFinder
Cc: gebrerv; Mention
Betreff: Re: [Studio-42/elFinder] How to show owners of files uploaded by authenticated users in listview (#1816)


@gebrerv<https://github.com/gebrerv> In such a case, it seems that PHP is executed with each user privilege with FastCGI etc. in many cases. If that is impossible, you need to save it as metadata associated with the file in some database and return the owner information with the expanded volume driver.

**Comment by nao-pon** [comment]
"Using LocalFileSystem together with MySQL #1808" It may help you. And since this issue is not an issue of elFinder, close it.

Thanks!
