### ISSUE TITLE
Open media files (which can be read by browser) in new tab of the network drive?

### ISSUE THREAD

**Issue by kkotowick** [Studio-42/elFinder#1823]
For file types such as PDF or WAV files, most web browsers can read them and will open them in the browser when you click them (on most websites). In elFinder, however, it will always download the file instead of opening it in the browser. Is there a configuration setting to change this?

EDIT: I have the configuration option set:

`'dispInlineRegex' => '.'`

And this makes it open a new window, but it still won't open a PDF or WAV in the new window, it still downloads it.

**Comment by nao-pon** [comment]
@kkotowick 
> `'dispInlineRegex' => '.'`

Since it is a regular expression, `'dispInlineRegex' => '.*'` Is required to allow all types inline. However, whether it is displayed inline or not is controlled by the browser.

**Comment by kkotowick** [comment]
Ok, that makes sense. You might want to update your Wiki (Connector configuration page) then, as it gives the following example (single '.' to show all MIME types):

![capture](https://cloud.githubusercontent.com/assets/5480106/21506947/82116a08-cc31-11e6-803b-9af2390e111e.PNG)

**Comment by nao-pon** [comment]
Oh! OK, I done fixed Wiki. However, Did you get clear about this issue?

**Comment by kkotowick** [comment]
That made PDFs work properly. However, I'm still having some issues. I'm testing it with a .WAV file, using `'dispInlineRegex' => '.*'`. If I use the "preview" button, it will play properly. If I double-click it though, it opens in-line and will not play. Could you try this on your server and see if it has the same issue? I'm using the Dropbox driver.

**Comment by nao-pon** [comment]
To play media using the browser window on a network drive, you need to publish the target item. You can use the getFileCallback option to open a file and publish it at the same time.

**simple example**
```javascript
var options = {
    url  : 'php/connector.php',
    getFileCallback : function(file, fm) {
        fm.exec('open', file.hash);
    }
}
$('#elfinder').elfinder(options);
```

**Comment by kkotowick** [comment]
Ok, that seems to work, although I don't really like the fact that it shows the published link in the new window's URL.

Is there a way to make it open the file in a new tab, instead of a new window?

**Comment by nao-pon** [comment]
> Is there a way to make it open the file in a new tab, instead of a new window?

I opend new issue. #1844
