### ISSUE TITLE
Empty dialog on elfinder load

### ISSUE THREAD

**Issue by jhon100** [Studio-42/elFinder#1824]
I'm not sure if the problem is related with the change made in #1814 , because before that I was using version 2.1.18, but after I updated to 

https://github.com/Studio-42/elFinder/tree/42002388bc6f64c56daedb3e95ebdf9bbd946cec#downloads >
elFinder 2.1.x (Nightly)

Some times on load, an empty dialog appear in elfinder area.
![elfinder](https://cloud.githubusercontent.com/assets/16785000/21455460/6b3b53a2-c907-11e6-9e9e-0d95db874b53.PNG)

Is not easy to reproduce the error as it occur very randomly. Most of the time the empty dialog does not appear.

The markup of the empty dialog is this:

```html
<div class="ui-front ui-dialog ui-widget ui-widget-content ui-corner-all ui-draggable std42-dialog touch-punch elfinder-dialog elfinder-dialog-notify" style="width: 280px; height: auto; top: 58px; right: auto; position: absolute; opacity: 0.75; bottom: auto; left: 499px;">
    <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
        <span class="ui-widget-header ui-dialog-titlebar-close ui-corner-all elfinder-titlebar-button elfinder-titlebar-button-right">
            <span class="ui-icon ui-icon-closethick"></span>
        </span>
        <span class="elfinder-dialog-title">&nbsp;</span>
    </div>
    <div class="ui-dialog-content ui-widget-content"></div>
</div>
```

**Comment by jhon100** [comment]
Here the image with default theme
![elfinder](https://cloud.githubusercontent.com/assets/16785000/21455769/22a558c4-c90a-11e6-8a04-8b8a2dd7c6b2.PNG)

**Comment by nao-pon** [comment]
I can not reproduce such a problem. Is there a similar problem even if elFinder is used standalone?

**Comment by jhon100** [comment]
@nao-pon, I found that the error occur only when the elfinder container is initialy hidden. In my case I'm using elfinder inside bootstrap collapse but you can reproduce the error setting the  elfinder container display property to none and change it in browser developer console. 

I don't know why but you will reproduce the error more easily with a fresh opened browser. In this way the error always occur but if other tabs or windows of the same browser are opened the error occur very randomly.

**Comment by nao-pon** [comment]
> you can reproduce the error setting the elfinder container display property to none and change it in browser developer console.

I can't see yet that error. -> [online test case](http://jsbin.com/kowuqi/edit?html,output)

**Comment by jhon100** [comment]
I tried both versions and the error happened:

![capturar2](https://cloud.githubusercontent.com/assets/16785000/21512005/19a97e3e-cc8f-11e6-8827-a5fcace94a82.PNG)

Did you tried in a fresh opened browser?
Also, I need to wait a little to reproduce the error... If you click in the button while elfinder is 'loading' (with a dialog 'open folder' and progress bar visible) no error occur. You will see the error if you click the button after elfinder is loaded. Try wait about 5 seconds before clicking...

**Comment by nao-pon** [comment]
Umm...  I can't see yet. I tested like this.
![wrongdialogtest](https://cloud.githubusercontent.com/assets/1412630/21512742/e16ce7ee-ccf3-11e6-83e0-fba33be64e38.gif)

**Comment by jhon100** [comment]
With a small width as in your capture I had dificulty to reproduce the error too. Try with this link: http://output.jsbin.com/kowuqi.

![22](https://cloud.githubusercontent.com/assets/16785000/21513868/aca02b1a-cca4-11e6-8958-bf81a7506dc8.gif)

As you can see in my capture, instead of waiting about 5 seconds you can monitore when the ajax call ends, so you can click,

It seems the problem is related with the initial 'loading' dialog header not being removed if the container is hidden. In my capture you see that if I change to a folder that takes a long time to load and you hide elfinder before the loading is complete, when click to show elfinder (after the folder is loaded)  the empty dialog appear.

**Comment by nao-pon** [comment]
@jhon100 OK, I got it! You are right so I'll fix it. Please wait until fix it. Thanks!

**Comment by jhon100** [comment]
Thanks a lot @nao-pon .
