### ISSUE TITLE
Slow after ftp mount

### ISSUE THREAD

**Issue by nomaes** [Studio-42/elFinder#1825]
Its fast but it becomes extremely slow after network mounting... am i missing something? or is there any way to speed it up?

Thanks.

**Comment by nao-pon** [comment]
@nomaes As you can see, it depends on the response speed of the FTP server. Specifically, how long is it late?

On the [demo site](https://studio-42.github.io/elFinder/), FTP net mount is possible. Please check it there.

**Comment by nomaes** [comment]
@nao-pon Thanks... I did try, but i found that it wasn't as fast with mounts... I just needed something on my web app on the localhost that could upload images to a web server on the net from ckeditor and get images from the server. FTP mount seemed perfect.

**Comment by nao-pon** [comment]
@nomaes Please check your FTP server. One way is to change the FTP server.
