### ISSUE TITLE
Non‐English characters problem

### ISSUE THREAD

**Issue by senhorT** [Studio-42/elFinder#1827]
Hello, i have some problems, i'm totally newbie.

![elfinder - copia2](https://cloud.githubusercontent.com/assets/24761135/21470179/2574d114-ca64-11e6-834f-126ef5548676.png)

I'm using xampp 5.6.28 on Windows 10 x64. 
how can i fix this?

Thanks in advance!

**Comment by nao-pon** [comment]
@senhorT Please set volume roots option [`encoding`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding) and [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale-1) correctly.

**Comment by senhorT** [comment]
After 2 hours searching, i finally found.
Thanks alot for your time and your help @nao-pon .
This project is awesome!

If anyone is searching for this, my changes are:
in "elFinderVolumeDriver.class.php"
I changed "encoding" to "iso-8859-1" and "locale" to "pt_BR.UTF-8"

I think this is alright.
Sorry about my english.

**Comment by nao-pon** [comment]
@senhorT congratulation! I do not know about Windows server well, but in your environment the following settings may be good.

```php
$opts = array(
    'locale' => 'Portuguese_Brazil.65001', // CP65001 = UTF-8 https://msdn.microsoft.com/library/windows/desktop/dd317756(v=vs.85).aspx
    'roots'  => array(
        array(
            'locale' => 'Portuguese_Brazil.1252', // https://msdn.microsoft.com/library/cc233982.aspx
            'encoding' => 'ISO-8858-1',
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    )
);
```

**Comment by senhorT** [comment]
@nao-pon I think you put the wrong encoding.
```
$opts = array(
    //'locale' => 'Portuguese_Brazil.65001', // CP65001 = UTF-8 https://msdn.microsoft.com/library/windows/desktop/dd317756(v=vs.85).aspx
    'locale' => 'Portuguese_Brazil', // Windows dose not support 65001(UTF-8)
    'roots'  => array(
        array(
            'locale' => 'Portuguese_Brazil.1252', // https://msdn.microsoft.com/library/cc233982.aspx
            'encoding' => 'ISO-8859-1',
            'driver' => 'LocalFileSystem',
            'path'   => '../Arquivos/',
            'URL'    => 'http://localhost/arq/Arquivos/',
            'accessControl' => 'access'// disable and hide dot starting files (OPTIONAL)
        )
    )
);
```
It's working. Thank you again.

**Comment by fangchen000** [comment]
@senhorT If I'm coding in Chinese, how do I change it? I tried many combinations, but they didn't work.such as
$opts = array(
    //'locale' => 'Portuguese_Brazil.65001', // CP65001 = UTF-8 https://msdn.microsoft.com/library/windows/desktop/dd317756(v=vs.85).aspx
    'locale' => 'Portuguese_Brazil', // Windows dose not support 65001(UTF-8)
    'roots'  => array(
        array(
            'locale' => 'Portuguese_Brazil.50935', //(Portuguese_Brazil.51936,Portuguese_Brazil.52936) https://msdn.microsoft.com/library/cc233982.aspx
            'encoding' => 'x-cp50227',
            'driver' => 'LocalFileSystem',
            'path'   => '../Arquivos/',
            'URL'    => 'http://localhost/arq/Arquivos/',
            'accessControl' => 'access'// disable and hide dot starting files (OPTIONAL)
        )
    )
);
Please help me, thanks.
