### ISSUE TITLE
raspberry pi media server

### ISSUE THREAD

**Issue by mkeyno** [Studio-42/elFinder#1828]
sorry guys to open ticket for my question , but I'm trying to let my raspberry pi connected client, share media files from storage connected to raspberry pi , I've already install NAS server but its not beautiful as your file manger lib , can you advise me how to use your lib for such media server

**Comment by nao-pon** [comment]
@mkeyno You need a web server and PHP. You can use elFinder if you install and setup them.

**Comment by mkeyno** [comment]
thanks @nao-pon I've install php server and elfinder but not yet figure out how to connected to my FTP server , do you know any link or guy who attempt to such way?

**Comment by nao-pon** [comment]
Did you check the [Wiki](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1)?

**Comment by mkeyno** [comment]
yes but this is instruction and I was hopping somebody have done such actual project

**Comment by nao-pon** [comment]
I close this issue as this issue is not an issue with elFinder. Since it is a place of development here, it would be better to ask more about StackOverflow and so on.
