### ISSUE TITLE
Allow to set error message on 4/5xx

### ISSUE THREAD

**Issue by romaricdrigon** [Studio-42/elFinder#1832]
Hello,

Right now, if we want to display a message to the user, we return a 200 response with `errCustom` and a custom error message.
An enhancement would be to be able to do the same, but over 4xx or 5xx responses. The issues with using 200 is that HTTP middleware (logging, proxies, Varnish...) will never get there are error happening, and won't work then.

**Comment by nao-pon** [comment]
@romaricdrigon Do you mean that you want to display messages to users with 4xx or 5xx HTTP response codes?

**Comment by romaricdrigon** [comment]
Exactly!

**Comment by romaricdrigon** [comment]
Great, thank you very much!
