### ISSUE TITLE
Exec('reload') does not update view

### ISSUE THREAD

**Issue by romaricdrigon** [Studio-42/elFinder#1833]
Hello,

We have a custom command that delete an element.
Once this command is done, we want to refresh the view, so we call `elf.exec('reload')`.
But nothing happens. It looks like an Ajax query is rightfully made, but the UI won't update.
Do we miss something?

Thanks!

**Comment by nao-pon** [comment]
@romaricdrigon Which part do you want to redraw? What about `elf.trigger('uiresize')`?

**Comment by romaricdrigon** [comment]
Hello @nao-pon !
We want to reload the folder/files list. Was it the correct method to use?

**Comment by nao-pon** [comment]
> We want to reload the folder/files list. Was it the correct method to use?

Yes, `elf.exec('reload')` requests file information to the back end and will be updated if there is a change. If the screen is not updated, it means that the information returned by the backend is not different from the current data. Please check the data returned by the backend.
