### ISSUE TITLE
What means 8px grid and how disable it?

### ISSUE THREAD

**Issue by ramin-git** [Studio-42/elFinder#1834]
What does it mean 8px grid and how change default status from enable to disable?

**Comment by nao-pon** [comment]
@ramin-git JPEG images are optimized more beautifully by processing in units of 8px. The 8px grid is for using this specification.

This default value can not be specified at present. I will make it possible.

Thanks!

**Comment by nao-pon** [comment]
To change default status to "disabled"

```javascript
opts = {
    url : 'connector.php',
    commandsOptions : {
        resize : {
            // defalt status of snap to 8px grid of the jpeg image ("enable" or "disable")
            grid8px : 'disable'
        }
    }
};
```
