### ISSUE TITLE
How to apply custom theme properly on elFinder 2.1.19?

### ISSUE THREAD

**Issue by mauleous** [Studio-42/elFinder#1836]
Hi,

How do you apply custom theme properly on elFinder 2.1.19?

It seems that in elFinder version 2.1.19, my custom theme CSS always gets overridden by elFinder's default theme CSS.
I tried to modify main.js to have something like:

```javascript
// Start elFinder (REQUIRED)
start = function(elFinder) {
		...
		elFinder.prototype.loadCss('./themes/myCustomTheme/css/theme.css');
		...
}
```
But still it gets overridden by the default elFinder's theme CSS.
		
Is there a way to have the custom theme CSS to override elFinder's theme CSS (not the other way around)?

Cheers!

**Comment by nao-pon** [comment]
@mauleous You can use client configuration `cssAutoLoad` to load additional CSS.

e.g.
```javascript
opts = {
    url : 'connector.php',
    cssAutoLoad  : [
        './themes/myCustomTheme/css/theme.css'
    ]
};
```

**Comment by mauleous** [comment]
It works perfectly! Thank you!! 😄
