### ISSUE TITLE
ElFinder is not a function? :/

### ISSUE THREAD

**Issue by LewisHolt** [Studio-42/elFinder#1838]
I'm currently trying to install ElFinder onto an XenForo Page Node.

I've put the code below into the Template HTML field in the Page Options but it doesn't seem to generate the file browser. I checked the console and I got a error that elfinder is not a function. Does anyone know how I can solve this? I've never used ElFinder before. It works fine when I view it normally at /fm/elfinder.html.

```
<link rel="stylesheet" type="text/css" media="screen" href="fm/css/elfinder.min.css">
<script type="text/javascript" src="fm/js/elfinder.min.js"></script>

<!-- Mac OS X Finder style for jQuery UI smoothness theme (OPTIONAL) -->
<link rel="stylesheet" type="text/css" media="screen" href="fm/css/theme.css">

<script type="text/javascript" charset="utf-8">
    $().ready(function() {
        var elf = $('#elfinder').elfinder({
            // lang: 'en',             // language (OPTIONAL)
            url : 'fm/php/connector.minimal.php'  // connector URL (REQUIRED)
        }).elfinder('instance');            
    });
</script>

<!-- Element where elFinder will be created (REQUIRED) -->
<div id="elfinder"></div>
```

^^ Here's the code I've put into the page node.

This is the error VV

`Uncaught TypeError: $(...).elfinder is not a function
    at HTMLDocument.<anonymous> (index.php?pages/fm/:426)
    at j (jquery-1.11.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js:2)
    at Function.ready (jquery-1.11.0.min.js:2)
    at HTMLDocument.K (jquery-1.11.0.min.js:2)`

**Comment by nao-pon** [comment]
@LewisHolt Perhaps fm/js/elfinder.min.js is not loaded. Please check the URL.

**Comment by ferdinand64** [comment]
Hi, I had this problem on my wamp localhost. Windows has renamed one of two elfinder folders on elfinder.1. because it does not distinguish between upper case letters.  Renaming the elFinder to something else and elfinder.1 back to elfinder did the trick.
