### ISSUE TITLE
How to prohibit uploading dot files?

### ISSUE THREAD

**Issue by dleffler** [Studio-42/elFinder#1843]
Is it possible to prohibit the uploading of 'dot' files to prevent someone from rewriting/removing the .htaccess, etc... file?

```
 curl "[exponent]/framework/modules/file/connector/elfinder.php" -F "cmd=upload" -F "target=l1_" -F "upload[]=" -F chunk="../[exponent]/files/.htaccess"

**Comment by dleffler** [comment]
or is the fix to turn OFF 'uploadOverwrite'?

**Comment by nao-pon** [comment]
@dleffler There is a serious security problem. I will fix it soon. Thank you so much.
