### ISSUE TITLE
how to make elfinder "focus" on a specific file path? 

### ISSUE THREAD

**Issue by estrica2000** [Studio-42/elFinder#1847]
after elfinder is loaded i'd like to be able to focus / select a specific file location dynamically. Is it possile? like imagine i know a file location and i click on a button which on click set's the elfinder focus on this specific file. Example: if quick preview is enabled it should preview this file automatically.

**Comment by nao-pon** [comment]
@estrica2000 You can use client configuration `startPathHash` and `fm.one('cwdrender', function)`.

e.g. ([Live Demo](http://jsbin.com/didehexubu/1/edit?js,output)) 
**However, the target item must be displayed in CWD.**
```javascript
(function(){
	var jqver = '3.1.1',
		uiver = '1.12.1',
		// elFinder options (REQUIRED)
		// Documentation for client options:
		// https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
		opts = {
			url : 'connector.php', // connector URL (REQUIRED
			startPathHash : 'l1_SW1hZ2Vz' // start path hash
		},
		// Start elFinder (REQUIRED)
		start = function(elFinder) {
			// load jQueryUI CSS
			elFinder.prototype.loadCss('//cdnjs.cloudflare.com/ajax/libs/jqueryui/'+uiver+'/themes/smoothness/jquery-ui.css');
			$(function() {
				// Make elFinder (REQUIRED)
				var fm = $('#elfinder').elfinder(opts).elfinder('instance');
				var initialItemHash = 'l1_SW1hZ2VzL3N0b25laGVuZ2UuanBn';
				fm.one('cwdrender', function() {
					setTimeout(function() {
						$('#'+fm.cwdHash2Id(initialItemHash)).trigger('scrolltoview').click();
						fm.exec('quicklook');
					}, 500);
				});
			});
		},
		// JavaScript loader (REQUIRED)
		load = function() {
			require([ 'elfinder' ],
				start,
				function(error) {
					alert(error.message);
				}
			);
		},
		// is IE8? for determine the jQuery version to use (optional)
		ie8 = (typeof window.addEventListener === 'undefined' && typeof document.getElementsByClassName === 'undefined');

	// config of RequireJS (REQUIRED)
	require.config({
		baseUrl : '//studio-42.github.io/elFinder/demo/js',
		paths : {
			'jquery'   : '//cdnjs.cloudflare.com/ajax/libs/jquery/'+(ie8? '1.12.4' : jqver)+'/jquery.min',
			'jquery-ui': '//cdnjs.cloudflare.com/ajax/libs/jqueryui/'+uiver+'/jquery-ui.min',
			'elfinder' : 'elfinder.min'
		},
		waitSeconds : 10 // optional
	});
	// load JavaScripts (REQUIRED)
	load();
})();
```

**Comment by estrica2000** [comment]
Brilliant! Thanks a lot and full respect! i need now  to make  plain string from file names  and locations into hashes! I still didn't find tho!  hope it's possible

**Comment by estrica2000** [comment]
as complementary question: as taken from the source: 
var volumeId = 'l1_'; // volume id
var path = 'path/to/target'; // without root path
var path = 'path\\to\\target'; // use \ on windows server* var hash = volumeId + btoa(path).replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '.').replace(/\.+$/, '');

how can we hash the VolumeId? i assume volumeId refers to something like "files" or "s3".

**Comment by nao-pon** [comment]
> 

`volumeid` can not be hashed. If you want to control the value of `volumeid` you can use the `id` of the roots option of the connector.

```php
$opts = array(
    'locale' => '',
    'roots'  => array(
        array(
            'id' => 'a',
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    )
);
```
`volumeid` will be `la_`.

**Comment by estrica2000** [comment]
thank you!
