### ISSUE TITLE
Security Issue : Server Side Request Fogery

### ISSUE THREAD

**Issue by semplon** [Studio-42/elFinder#1848]
Hello @nao-pon, I've used elFinder for my CMS, and there is security issue regarding this implementation. see details here : https://github.com/semplon/GeniXCMS/issues/64 

Can this fixed on elFinder side ? which handle the upload files. 

thanks,

**Comment by nao-pon** [comment]
@semplon elFinder's default connector does not have an access control mechanism. If you need to hide the connector you need to properly implement the connector yourself.

Please send PR if you need something elFinder side for implement it.

Thanks!
