### ISSUE TITLE
Windows Path for different drives or ../ doesn't work

### ISSUE THREAD

**Issue by recognizerHD** [Studio-42/elFinder#1854]
If I reference 'path' => 'logs/' in my connector, it works.
If I reference 'path' => '../api/logs' in my connector, it doesn't work.
Also, if I reference a different drive i.e. F:/files it also doesn't work.

What I've found is that when the path includes '../', then the base is added to it as absolute path. Essentially the same as the third scenario.

It seems to work if I update the following line: 
`if (substr($path, 0, 2) === '.' . $separator || $path[0] !== '.') {

// with

if (substr($path, 0, 2) === '.' . $separator || ($path[0] !== '.' && substr($path,1,2) !== ':'.$separator )) {`

I'm checking for a :\ which I think is applicable for windows drives.

**Comment by nao-pon** [comment]
@recognizerHD I tested on XAMPP for Windows 5.6.23 + elFinder 2.1.20 or latest nightly build. That was no problem. In which environment do you get problems?

**Comment by recognizerHD** [comment]
My apologies, it works perfectly fine. My composer entry wasn't referencing the correct version. All is good.

+1 shame to me.

**Comment by nao-pon** [comment]
It's OK don't worry. :-)
