### ISSUE TITLE
Can't upload more than 16kb

### ISSUE THREAD

**Issue by wamft** [Studio-42/elFinder#1856]
I cannot load any file without getting a file transfer error. It always stops at the 16kb. Smaller files it uplaods no problems. I cannot find where to change the max file size to get this to work.

**Comment by nao-pon** [comment]
@wamft If elfinder does not limit upload maximum size, the system limit will be applied. Please check your system limit.

**Comment by wamft** [comment]
System limit it 20MB

**Comment by nao-pon** [comment]
Please make sure that it is not restricted by transmission route or other integrated program.

**Comment by wamft** [comment]
This case is getting even more curious now, I can upload 395kb file from my Laptop but from the PC it wont allow me to upload above 16kb.

 

Is this a setting somewhere in my browsers that is stopping this?

 

Where would I start to look here?

**Comment by nao-pon** [comment]
I guess that there is no problem if you change the terminal is a problem on your terminal side. We cannot know the cause.
