### ISSUE TITLE
Add and Hide rows in the result table

### ISSUE THREAD

**Issue by ErvanSalin** [Studio-42/elFinder#1859]
Is it possible to add a column with the path to the file or folder in the list view or hide columns like "Permissions".
I'd like to show the path to differentiate search results for example.
If someone has already set up this feature I would like to know the best solution to achieve this.

**Comment by nao-pon** [comment]
@ErvanSalin Please check [Client configuration `uiOptions.cwd.listView`](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L508).
