### ISSUE TITLE
how to edit file option custome extention file 

### ISSUE THREAD

**Issue by RJRahevar** [Studio-42/elFinder#1862]
hello sir..

i have create .audio and .video extention file and try to edit option on this file
but not available option please suggest me ...

thanks

**Comment by nao-pon** [comment]
@RJRahevar What kind of specification is it? Working only on the client side? Or work with the back end?

**Comment by RJRahevar** [comment]
![1-20-2017 2-51-43 pm](https://cloud.githubusercontent.com/assets/9314456/22143513/463f885a-df20-11e6-9480-84e7405b96e7.png)

**Comment by nao-pon** [comment]
@RJRahevar Sorry to my no response. On the client side, processing is done with [edit command](https://github.com/Studio-42/elFinder/blob/master/js/commands/edit.js), but this command only takes text files into consideration. You'd better create a new command to handle various other content types.

**Comment by nao-pon** [comment]
Binary file can be edited from elFinder 2.1.15. Data is exchanged using the character string of Data URI Scheme.

The basic structure of the editor setting is as follows.

```javascript
commandsOptions : {
	edit : {
		// Regular expression of MIME type corresponding to editors
		binMimeRegex : /^audio\/(?:mpeg|x-wav)/,
		editors : [
			{
				// MIME types to accept
				mimes : ['audio/mpeg', 'audio/x-wav'],
				// HTML of this editor
				html : '<div style="width:100%;height:200px;text-align:center;"><audio/></div>',
				// Initialization of editing node
				init : function(id, file, content, fm) {
					// content is the string of Data URI Scheme
					var node = $(this).children('audio:first')
					
					node.attr('id', id+'-sound')
						.attr('src', content);
				},
				// Get data uri scheme
				getContent : function() {
					return $(this).children('audio:first').attr('src');
				},
				// Launch media editor when dialog open
				load : function(base) {
					var self = this,
						fm = this.fm,
						node = $(base).children('audio:first'),
						elfNode = fm.getUI(),
						editor = new AnyMediaEdior();

					// return media editor instance
					return editor;
				},
				// Convert content url to data uri scheme to save content
				save : function(base, editor) {
					var node = $(base).children('audio:first');
					if (node.attr('src').substr(0, 5) !== 'data:') {
						node.attr('src', makeDataUriAnyFunction(node));
					}
				}
			}
		]
	}
}
```
