### ISSUE TITLE
Chunk File Upload

### ISSUE THREAD

**Issue by krunaltasolglobal** [Studio-42/elFinder#1863]
Hello,

I am using this package with laravel 5.2 but not able to find out chunk upload option in this package.

**Comment by nao-pon** [comment]
@krunaltasolglobal The elFinder chunk upload is enabled by default. However, a connector compatible with elFinder API 2.1 (such as the included PHP connector) is required.

**Comment by krunaltasolglobal** [comment]
Any Guideline for "**connector compatible**" and implement guideline too ?

**Comment by nao-pon** [comment]
There is a wiki page "[Client Server API 2.1](https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1)". And you can see API protocol version in "About this software" dialog.

![](https://cloud.githubusercontent.com/assets/1412630/22192124/7627d990-e174-11e6-99c7-efbd847ae133.png)
