### ISSUE TITLE
how to onclick show the quicklook when it's already opened

### ISSUE THREAD

**Issue by estrica2000** [Studio-42/elFinder#1864]
i've been trying to do something like this: 
$('#'+elf.cwdHash2Id(path_hash)).trigger('scrolltoview').click();
 elf.exec('quicklook');

but what happens is if the quicklook is already opened it will close the quicklook instead of opening it! 

i also tried :  $('#'+elf.cwdHash2Id(path_hash)).trigger('select') but since a file is already selected and quicklook previewing it! this will be the second file selected and so the preview does not change. I would achieve what i'd like if just this one got selected.

It would nice if the quicklook could be  always opened! even with no files selected too

**Comment by nao-pon** [comment]
@estrica2000 for example
```javascript
$('#'+elf.cwdHash2Id(path_hash)).trigger('scrolltoview').click();
if (elf.getUI().children('div.elfinder-quicklook').is(':hidden')) {
    elf.exec('quicklook');
}
```

**Comment by estrica2000** [comment]
thanks but seems my problems is that:
1)  $('#'+elf.cwdHash2Id(path_hash)).trigger('scrolltoview').click();

closes the quicklook window. Any way to "force" not closing the window? 

2) Alternatively Earlier i tried with select but then i get 2 files selected. Is there something like this?$('#'+elf.cwdHash2Id(path_hash)).trigger('SELECTJUSTONE') 

Alternatively if i use unselect all and then select i have the same problem has in 1)

Many many thanks!

**Comment by nao-pon** [comment]
>1. $('#'+elf.cwdHash2Id(path_hash)).trigger('scrolltoview').click();
>closes the quicklook window. Any way to "force" not closing the window?

I checked on elFinder 2.1.20 and that was no problem. Which version are you using?

**Comment by estrica2000** [comment]
that was it! Thank you. Very nice.
