### ISSUE TITLE
Viewing PDF's doesn't work in Safari on MacOS

### ISSUE THREAD

**Issue by spotUP** [Studio-42/elFinder#1865]
Hi! Viewing PDF's just show binary data in Safari on OSX.
Latest OS, latest Safari.

**Comment by nao-pon** [comment]
@spotUP Please check connector roots configuration [`dispInlineRegex`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#dispInlineRegex).

e.g.
```php
'dispInlineRegex' => '^(?:(?:image|text)|(?:application/x-shockwave-flash|application/pdf)$)',
```

**Comment by spotUP** [comment]
I am not a coder, what am i looking for?

**Comment by spotUP** [comment]
And where is that file located?

**Comment by nao-pon** [comment]
@spotUP Please read a wiki page. -> https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1
