### ISSUE TITLE
Missing Folder

### ISSUE THREAD

**Issue by DavidKurtz1** [Studio-42/elFinder#1867]
As you can see in the print screen the elFinder does not show all the folder in the source directory.
From a short examine it looks as if the missing files & folders are due to a different language in the file name / folder name.

What configuration variable should I twick to fix it?

Thank in advance,
David.
 
http://prntscr.com/dz4pyo

**Comment by nao-pon** [comment]
@DavidKurtz1 Please set connector **roots options** [`encoding`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding) and [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale-1) to fit to your servers one.

**Comment by DavidKurtz1** [comment]
Thanks a lot.
Working Perfectly.
