### ISSUE TITLE
Back and Forward Navigation breaks if user does not wait for loading to complete

### ISSUE THREAD

**Issue by wolfgangihloff** [Studio-42/elFinder#187]
1) Clicking on the 'Back' button multiple times before the document view has reloaded can cause the navigation functionality to break in regards to the history - the user will go back two levels, but all history previous to that will be lost; the 'Forward' button will be active, but instead of navigating to what should be the skipped level the user is brought to the level they were at when they multi-clicked the 'Back' button.

2) Navigating back several previous levels and then clicking on the 'Forward' button multiple times before the document view has reloaded can cause navigation history to be lost in a similar way - the user will go forward two levels, but all history after that will be lost; the 'Back' button will be active, but instead of navigating to what should be the skipped level the user is brought to the level they were at when they multi-clicked the 'Forward' button.

**Comment by troex** [comment]
inactive
