### ISSUE TITLE
How to access the element by id on jquery and elfinder ?

### ISSUE THREAD

**Issue by limars** [Studio-42/elFinder#1870]
I tried to input below code  this on elfinder, but it's undefined.  
could you give me any example ?
console.log("output="+$("#elfinder #nav-l1_Lw").html());

**Comment by nao-pon** [comment]
@limars Please wait for completion of DOM construction and get it.

e.g.
```javascript
var fm = $('#elfinder').elfinder(opts).elfinder('instance');
fm.bind('opendone', function() { // when done cmd `open`
	fm.log($('#'+fm.navHash2Id('l1_Lw')).html();
});
```
