### ISSUE TITLE
Unable to connect to backend

### ISSUE THREAD

**Issue by emnoze** [Studio-42/elFinder#1871]
Hi all,
I followed the doc install with ckeditor.
When i try tu upload an upload, I got the message ' Unable to connect to the backend'

` http://127.0.0.1/myproject/web/app_dev.php/efconnect?mode=&cmd=upload&target=l1_XA&name%5B%5D=water_PNG3290.png&FILES=&_=1485344164486 500 (Internal Server Error)`

My config is 
ivory_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []

I think the pb is from my  filebrowserBrowseRouteParameters: []
but I don't know how to fix it..
Thx for help

**Comment by nao-pon** [comment]
@emnoze you ware saying `app_dev.php/efconnect` and `ivory_ck_editor`. It seems to be using some extended integration. We can not guess about troubles during integration. Please ask with each project.
