### ISSUE TITLE
how to set quicklook position based on Elfinder Window and not in the middle height to page

### ISSUE THREAD

**Issue by estrica2000** [Studio-42/elFinder#1872]
The position of quicklook seems to be based on height of the page instead of the position of the elfinder window , at least for me,  i try to set in my css: 
div.elfinder-quicklook{
   top:0;
}

or in:
commandsOptions : {
      quicklook : {  top:0}
}

or elf.getUI().children('div.elfinder-quicklook').css('top',  '0px');

all of them are ignored and quicklook always appears with top equal to something like 600 , which +- the middle of the page where elfinder and other stuff fit.

**Comment by nao-pon** [comment]
@estrica2000 

e.g.
```javascript
var fm = $('#elfinder').elfinder(opts).elfinder('instance');
fm.getCommand('quicklook').window.on('open', function(){
  $(this).promise().done(function() {
    $(this).css('top', '0');
  });
});
```

**Comment by estrica2000** [comment]
thank you for the recipe! one thing i don't like the solution you kindly given is that i can see the window moving from the "default" middle height position to the 0 px. It's ugly seeing it moving.
I need to make it always top:0  since ever , to avoid seeing it moving

**Comment by nao-pon** [comment]
e.g.
```javascript
var fm = $('#elfinder').elfinder(opts).elfinder('instance');
fm.getCommand('quicklook').window.on('open', function(){
  $(this).hide()..promise().done(function() {
    $(this).css('top', '0').show();
  });
});
```
