### ISSUE TITLE
Changing iFrame `src` to new elFinder URL does not work

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1875]
I am using elFinder in an iFrame (due to conflicts with Bootstrap) and I have some links on the page that are shortcuts to different folders.

I am using the following jQuery to change the iFrame src (note; this is the correct way to change the iFrame `src` and load new content)

''
'$('iframe').attr('src', 'http://localhost/index.php/elfinder#elf_flsGCS_' + hash);
'''

`hash` is the folder name, base 64 encoded.

Sadly, nothing happens. The explorer window does not open the folder when clicking the link.

**Comment by nao-pon** [comment]
@paulcanning This is not an issue of elFinder.

Probably,
```
'$('iframe').get(0).contentDocument.location.replace('http://localhost/index.php/elfinder#elf_flsGCS_' + hash);
```
