### ISSUE TITLE
Disabling quicklook is no effect on context menu.

### ISSUE THREAD

**Issue by changkejun** [Studio-42/elFinder#1876]
I try to make a java connector for elFinder2.1.20 in my project.
When I set open command return with options.disabled:["quicklook"], I found the icon is unvisable but the context menu is still visable. Is it a bug?

**Comment by nao-pon** [comment]
@changkejun The command `quicklook` is not a server side command. You can configure in client configuration option [`commands`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#commands).

**Comment by changkejun** [comment]
I deleted some difficult commands program from elfinder.full.js, then everything is good, no icon and no context menu in the same way.  Is it a good idea to select some commands for self customize version ?
