### ISSUE TITLE
(Question) Show files' meta data in the icons view

### ISSUE THREAD

**Issue by k4200** [Studio-42/elFinder#1878]
I modified the connector so it can add files' meta data using the "bind" mechanism, and there's no problem with it. Now, I'd like to show one of the meta data fields instead of the file name in the "icons" view.

I was able to show the meta data in the list view by following the issues below, but couldn't figure out how to achieve this for the icons view:
#1286 #1859

Thanks.

**Comment by nao-pon** [comment]
@k4200 Please extend `uiOptions.cwd.replacement` of the client configuration option.

e.g.
```javascript
uiOptions : {
	cwd : {
		replacement : {
			name : function(f, fm) {
				var list = fm.viewType === 'list';
				var name;
				if (list) {
					 name = fm.escape(f.i18 || f.name);
					 name = name.replace(/([_.])/g, '&#8203;$1');
				} else {
					name = fm.escape(f.yourMetaData);
				}
				return name;
			}
		}
	}
}
```

**Comment by k4200** [comment]
Thanks for the tip. It works!
