### ISSUE TITLE
Is it possible to return a list of files one page at a time?

### ISSUE THREAD

**Issue by glen-84** [Studio-42/elFinder#1879]
For example, if the folder contains a large number of files, then it doesn't make sense to return all of these files in a single request. Is it possible for the client to request a certain number of files, with a specific offset or file to start from?

**Comment by nao-pon** [comment]
@glen-84 Since elFinder's current API performs sorting and incremental search on the client side, it is necessary to acquire item data at once. Since it is necessary to extend the API, it is a future issue.
