### ISSUE TITLE
move (paste) with elFinderSupportVer1.js errors

### ISSUE THREAD

**Issue by dup2** [Studio-42/elFinder#1880]
When moving an object (a jpeg file) to a folder, we get an error indicating that the file already exists at the new location - this is not true however the backend copies/moves the file correctly to the new location and returns a JSON fragment with the cwd, cdc and tree attributes.

How to reproduce
* Drag a file to a folder (move)
* The backend get's a "paste" request with a "dst" parameter and a target array with one element
* The backend moves the file and returns a JSON with cwd, cdc and tree attributes and HTTP status 200
* The frontend displays the error message
* A subsequent reload displays a correct file listing in the source directory (file not there anymore) and the target directory (file is there - the move was performed)

Environment:
* elFinder version 2.1.20
* JQuery 1.11.4
* Using transport proxy for version 1 (due to the backend API)

In this screenshot, the file "iMac-24.jpg" is being dragged and dropped onto the "Test" folder.

<img width="842" alt="screen shot 2017-02-01 at 22 14 52" src="https://cloud.githubusercontent.com/assets/124815/22526594/22353be8-e8cc-11e6-80f8-7cdabc58bb49.png">

**Comment by nao-pon** [comment]
@dup2 Thanks! 👍

**Comment by dup2** [comment]
Thanks for this quick fix! I'll test it asap to confirm.

**Comment by dup2** [comment]
Works, Cheers!
