### ISSUE TITLE
elf.getUI('cwd').trigger('unselectall') is being "arbitrarily" ignored

### ISSUE THREAD

**Issue by estrica2000** [Studio-42/elFinder#1881]
elf.getUI('cwd').trigger('unselectall') in  //(*) is being "arbitrarily" ignored, and elfinder selects the file next to the one  which was previously selected 

elf.bind('cwdrender', function() {
      setTimeout(function() {
         var path = $('#elfinder').attr('url'); //which holds file names that might exist or not
         var path_hash = 'l1_' + btoa(path).replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '.').replace(/\.+$/, '');

         if (typeof $('#'+elf.cwdHash2Id(path_hash))[0]=="undefined"){
               elf.getUI('cwd').trigger('unselectall');   //(*)
               
          }
         else{
                   file  exists 
         }
         (...)
    }
}

Between , i would like to know how to do this per purpose for future developments, is there a commmand that makes this "Select the next file to the one selected"?

Big big thanks

**Comment by nao-pon** [comment]
@estrica2000 What about `$(document).trigger($.Event('keydown', { keyCode: $.ui.keyCode.RIGHT, ctrlKey : false, shiftKey : false, altKey : false, metaKey : false }));`?

**Comment by estrica2000** [comment]
thank you  nao-pon! i've been focus on other parts! will be back to this in near project! all good the best !
