### ISSUE TITLE
Error if commandsOptions.upload.ui = 'uploadbutton'

### ISSUE THREAD

**Issue by mgrabazey** [Studio-42/elFinder#1885]
Hi.

I do it (#1747), but have:
Uncaught TypeError: Cannot read property '0' of null
at elFinder.commands.upload.exec (elfinder.full.js:22380)
at HTMLInputElement. (elfinder.full.js:15582)
at HTMLInputElement.dispatch (jquery.min.js:3)
at HTMLInputElement.q.handle (jquery.min.js:3)
after selected the file.

but if i change cmd.exec({input : _input.remove()[0]}); to cmd.exec({input : _input.remove()[0], target: cmd.fm.cwd().hash}); in elfinder.full.js:15582 the error not fire.

have You a better solution?)

**Comment by nao-pon** [comment]
@mgrabazey I checked on the latest elFinder -> http://jsbin.com/dulekip/edit?js,output

That was no problem. Please try elFinder 2.1.20 or nightly.

**Comment by mgrabazey** [comment]
@nao-pon thanks for your time
I also use elFinder 2.1.20 but the error is still there

**Comment by mgrabazey** [comment]
@nao-pon
Today I checked your code http://jsbin.com/dulekip/edit?output and saw the same problem
<img width="1392" alt="2017-02-04 15 34 53" src="https://cloud.githubusercontent.com/assets/13850340/22618860/51e29edc-eaf0-11e6-9032-f60b11d7a626.png">
please check again if you have time)
Thanks!

**Comment by nao-pon** [comment]
@mgrabazey Oh, You are right. I got it so I'll fix it.

**Comment by nao-pon** [comment]
@mgrabazey Thanks! 👍
