### ISSUE TITLE
I made a connector to 2.1 only for some limited commands.

### ISSUE THREAD

**Issue by changkejun** [Studio-42/elFinder#1886]
Do I have the honor to be joined my link as a 3rd party connectors of elFinder ?

My connector is coded by javascript on efw3.X framework  ( a server side javascript framework based on javax.script ).

The supported commands is the next.
download,upload, duplicate, file, get, ls, mkdir, mkfile, open, parents, paste, put, rename, rm, size, tree, 

I packaged it as a jsp tag <efw:elFinder /> , so it is very easy to use in java apps. The help is at the next url.
https://github.com/efwGrp/efw3.X/blob/master/help/api_efw_tag.md

All sources about the tag in the next url.
https://github.com/efwGrp/efw3.X/tree/master/source%20for%20jar/elFinder

**Comment by nao-pon** [comment]
@changkejun Sure! Please send PR to master:README.md.

Thanks!
