### ISSUE TITLE
if path has "files" at the end, directory is locked

### ISSUE THREAD

**Issue by Offerel** [Studio-42/elFinder#1889]
I have installed Version: 2.1.14 of elfinder. If i use a path like the following in connector.minimal.php, the Root Path and all its files, have a Lock-Icon-Overlay.

`path'          => '/media/stick/webdav/'.$_SERVER['PHP_AUTH_USER'].'/files',`

**Comment by nao-pon** [comment]
@Offerel Please check the permission for PHP execution user.

**Comment by Offerel** [comment]
That was my first thought also, but this wasn't the case. All permissions are correct. I use the same path with SabreDAV and this was no Problem. I have restarted my server instances today and the Problem doesn't occur again, i haven't changed anything in the config or elfinder files. The only thing i could think about, is some caching problem, since i use caching really heavily on my Raspberry Pi to gain a little bit more speed.

Since the Problem seems to be gone now, i close this request. If it occurs again, i reopen it with more infos.
