### ISSUE TITLE
Thumbnails not displaying

### ISSUE THREAD

**Issue by BuffaloBrennan** [Studio-42/elFinder#1892]
Hi Everyone

I've now managed to get elFinder up and running on Windows IIS and browsing folders, etc absolutely fine, however I can not get the thumbnails to appear.

All I've done is in the "Connector" changed, path, startPath and URL:
		array(
			'driver'        => 'LocalFileSystem',       
			'path'          => '**C:\\Work Files\\PHP Projects\\JLDocumentRoot\\**',   
                         'startPath'     => '**C:\\Work Files\\PHP Projects\\JLDocumentRoot\\Quotes\\**',
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/', D)

The thumbnails are produced in the folder C:\\Work Files\\PHP Projects\\JLDocumentRoot\\**.tmb**  but not replacing the standard .JPG icons.

Anyone got any ideas?

**Comment by nao-pon** [comment]
@BuffaloBrennan Please set appropriate value for [`tmbUrl`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#tmburl) of connector roots setting.
