### ISSUE TITLE
Locking all folders except 1

### ISSUE THREAD

**Issue by BuffaloBrennan** [Studio-42/elFinder#1894]
Hi Everyone

I'm enjoying this component/feature very much - taking some getting used to but it looks like a great piece of software, well done to the developers

I'm stuck on 1 thing... I  can prevent deleting and renaming of files for everyone using the " 'disabled' =>  array('rename, 'rm') and I can lock individual folders (using the attribute  pattern feature).  however.  What I want to do is allow the user to have full access without being able to delete or rename (using the 'disabled' feature except for a specific folder where they need full access.  In this case, where the sales people are working on quotes - they need to have full access to that folder BUT not the rest - to stop them from accidentally deleting all files from the system.

This is what I have so far - but can't get the test folder (Q17-00002) to become fully editable.  Has anyone got any ideas I can try?

$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => 'C:/Work Files/PHP Projects/JLDocumentRoot/',                 // path to files (REQUIRED)
         'tmbPath'        => 'C:\\Work Files\\PHP Projects\\job Log\\thumbnails\\',
         'startPath'     => 'C:\\Work Files\\PHP Projects\\JLDocumentRoot\\Quotes\\',
         'tmbURL'        => 'http://localhost:8080/thumbnails/', // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access',                     // disable and hide dot starting files (OPTIONAL)
         **'disabled'      => array('rename', 'rm'),**
         'attributes'    => array(
               array(
                  'pattern' => '(**Q17-00002**)+', // from ROOT:    **\Quotes\Q17\Q17-00000-Q17-00999\Q17-00002**
                  'read'  => true,
                  'write' => true, 
                  'locked' => false
               )
         )
      )
	)
);

Again, thank you in advance for any help given.

**Comment by BuffaloBrennan** [comment]
LOL Sorry guys I have a work around for now - but would really love a better solution.   I've basically removed the 'disabled' attribute and added 2 'Attributes' patterns.  the first sets every file to be "locked" and the second "unlocks" all the files in the folder Q17-00002 and any subfolders (I think).  Here is my $opts:

$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => 'C:/Work Files/PHP Projects/JLDocumentRoot/',                 // path to files (REQUIRED)
         'tmbPath'        => 'C:\\Work Files\\PHP Projects\\job Log\\thumbnails\\',
         'startPath'     => 'C:\\Work Files\\PHP Projects\\JLDocumentRoot\\Quotes\\Q17\\Q17-00000-Q17-00999\\Q17-00002\\',
         'tmbURL'        => 'http://localhost:8080/thumbnails/', // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access',                     // disable and hide dot starting files (OPTIONAL)
         'attributes'    => array(
               array(
                  'pattern' => '/(.)+/', 
                  'read'  => true,
                  'write' => true, 
                  'locked' => true
               ), 
               array(
                  'pattern' => '/(Q17-00002)+/', // from ROOT:    \Quotes\Q17\Q17-00000-Q17-00999\Q17-00002
                  'read'  => true,
                  'write' => true, 
                  'locked' => false
               )
         )
      )
	)
)

**Comment by BuffaloBrennan** [comment]
Small point - but just notices the folder itself Q17-00002 can be deleted also using the above code... not the end of the world... but would love to prevent this also.

**Comment by nao-pon** [comment]
@BuffaloBrennan Please try :-)
```php
'attributes' => array(
	array(
		'pattern' => '/.*/',
		'locked' => true
	),
	array(
		'pattern' => '~/Q17-00002/.+~',
		'locked' => false
	),
),
```

**Comment by BuffaloBrennan** [comment]
Thank you nao-pon that worked a treat.
