### ISSUE TITLE
Does the HTML and JS have to be in the Root?

### ISSUE THREAD

**Issue by BuffaloBrennan** [Studio-42/elFinder#1897]
Hi Everyone

I've got my system to browse a folder, subfolder and set up the security as I nearly like it.  Ive now come to do a little house keeping with the page that shows the elfinder <DIV> and the JS script.... but I can't move them.  They work fine in the root, but once i try moving them to a sub folder, i.e. **/system/BrowseFolders** it comes up with a scripting error within elfinder.

Is it possible to move these files.  I've tried every combination I can think of for the data-main in the following with no joy.

<script **data-main="/main.quotes.js"** src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.3.2/require.min.js"></script>

Thank you in advance for any help given.

**Comment by LIDJungle** [comment]
**data-main="/main.quotes.js"** 

Make sure you point to the new folder

**data-main="/system/BrowseFolders/main.quotes.js"**

**Comment by BuffaloBrennan** [comment]
Thank you LIDJungle, I tried that one and still get the scripting error:

   <script data-main="**/system/BrowseFolders/main.quotes.js**" src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.3.2/require.min.js"></script>

but still get the scripting error. In main.quotes.js I've not changed the opts from the one that works in the root:

		opts = {
			url : **'/php/connector.quotes.php**', // connector URL (REQUIRED)
			lang: lang,                         // auto detected language (optional)
         defaultView: 'list',
         rememberLastDir: false
		},

**Comment by LIDJungle** [comment]
Is that where the connector file is?

Or is it /system/BrowseFolders/php/connector.quotes.php?

Otherwise, can you let me know what scripting error you're getting? 

You might also need to update the require.config in your js file...

```// config of RequireJS (REQUIRED)
	require.config({
		baseUrl : 'js',
		paths : {
			'jquery'   : '//cdnjs.cloudflare.com/ajax/libs/jquery/'+(ie8? '1.12.4' : jqver)+'/jquery.min',
			'jquery-ui': '//cdnjs.cloudflare.com/ajax/libs/jqueryui/'+uiver+'/jquery-ui.min',
			'elfinder' : 'elfinder.min'
		}
	});```

Change the "baseUrl" to your new baseUrl: /system/BrowseFolders/js

**Comment by BuffaloBrennan** [comment]
I've left the connector file in the php folder from the root, along with the rest of the rest of the elfinder php code. Thanks again LIDJungle

**Comment by BuffaloBrennan** [comment]
Thank you LIDJungle.... I moved the the front end - and the .js files into the **/system/BrowseFolders.**

in the front end the script is now:
<script data-main="**/system/BrowseFolders/main.quotes.js**" src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.3.2/require.min.js"></script>

 and changed the baseUrl in the above .js to file baseUrl : '**/js**',  I've left the connector in the php folder from the Website root and it works!

**Comment by LIDJungle** [comment]
Glad to hear you got it squared away. :)
