### ISSUE TITLE
[cmd:help] error ".tabs is not a function" without JqUI tabs widget

### ISSUE THREAD

**Issue by LIDJungle** [Studio-42/elFinder#1898]
Hoping you guys can help me out.

We have a webapp that has been using elFinder for 2-3 years now. We recently wanted to add quotas, and I had to upgrade to the latest version to get that working.

This is part of a much larger Angular.js codebase.  I already have jQuery and jQuery-UI loaded for other parts of my app. I'd like to keep the code in my controller without having to completely rewrite my project to use require.js

I've tried creating a standalone version of elfinder that does not use require.js.

I get this error:
TypeError: T.find(...).children(...).tabs is not a function

URL: http://shineemc.com/elf/index.html

I load my site's jQuery and the elFinder.js library
```
                <!-- jQuery jQueryUI is needed for el-finder. -->
		<script src="/shine/js/jquery/jquery.min.js"></script>
		<script src="/shine/js/jquery/jquery-ui.min.js"></script>
		<script src='/elf/js/elfinder.min.js'></script>
		<script src='/elf/js/i18n/elfinder.LANG.js'></script>
```

Then activate the Theme and Manager:
```
elFinder.prototype.loadCss('//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.1/themes/smoothness/jquery-ui.css');
$('#elfinder').elfinder({url : '/elf/php/connector.php'});
```

I CAN include the elfinder.html in a route with the default.main.js, but it only runs on page load. (When the js is parsed and run on page load) Subsequent loads show no file manager. 

I've been reading require.js docs for a day now, and it seems to be all or nothing. I don't see any easy way to shoehorn this requirement into my project. I'm not even sure what "children(...).tabs" is referring to.

Any help you can offer would be very much appreciated.

**Comment by nao-pon** [comment]
@LIDJungle elFinder has debug tab in info dialog, that is required jQueryUI Tabs Widget. However, it is a bug that causes an error, so I will fix it.

Thanks!

**Comment by nao-pon** [comment]
I done, please try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

Thanks! 👍

**Comment by LIDJungle** [comment]
Domo arigato!

Thank you very much!
