### ISSUE TITLE
Rotating image breaks itself if exiftran and jpegtran command are not installed.

### ISSUE THREAD

**Issue by czbone** [Studio-42/elFinder#1899]
Rotating image breaks itself in the environment that exiftran and jpegtran command are not installed.

JPEG images are operated unconditionally　by those commands at imgRotate() in elFinderVolumeDriver.class.php.

It occurs in PHP5.3 on CentOS6.
It does not occur in PHP5.6 on Fedora23.

Please check the environment like this.
``
if ($this->procExec('wich exiftran') === 0 && $this->procExec('wich jpegtran') === 0){
``

**Comment by nao-pon** [comment]
@czbone OK, I'll use `exiftran -h` and `jpegtran -version` to command exists check.

Thanks!
