### ISSUE TITLE
List view - Folders do not show the size of the contents within the folder. The size of the folder remains at 0 b. 

### ISSUE THREAD

**Issue by wolfgangihloff** [Studio-42/elFinder#190]
Steps to reproduce:
Create and choose a folder and upload a file to that folder. Make sure you are in view by list mode and click on the folder directory.

Expected outcome:

The size of the folder should be the same as the sum of the contents of the folder. 

However the info view shows the correct content size.

**Comment by EWindfield** [comment]
Another way to make it "look" better, at least not to confuse the user that their folder is empty (0b) is to replace directory size label to "-". 

/**
			 * Template placeholders replacement rules
			 *
			 * @type Object
			 **/
			replacement = {
				....
				size : function(f) {
                    if(f.mime=='directory'){
                        return '-';
                    }else{
                        return fm.formatSize(f.size);
                    }
				},

**Comment by troex** [comment]
displays `-` now by default in list view
