### ISSUE TITLE
How to config only allow extension .phtml

### ISSUE THREAD

**Issue by thanhansoft** [Studio-42/elFinder#1900]
Hi,
I' using Elfinder new version,
How to config allow: image, txt and .phtml (edit, upload, create)
 Please help me

**Comment by nao-pon** [comment]
@thanhansoft 

Please set config `mimeMap` of connector roots option.

```php
'mimeMap'         => array(
    'md:application/x-genesis-rom' => 'text/x-markdown',
    'md:text/plain'                => 'text/x-markdown',
    'markdown:text/plain'          => 'text/x-markdown',
    'css:text/x-asm'               => 'text/css',
    'ico:image/vnd.microsoft.icon' => 'image/x-icon',
    'csv:text/plain'               => 'text/csv',
    'm4a:video/mp4'                => 'audio/mp4',
    'oga:application/ogg'          => 'audio/ogg',
    'ogv:application/ogg'          => 'video/ogg',
    'zip:application/x-zip'        => 'application/zip',
    'php:unknown'                  => 'text/x-php',
    'php:text/plain'               => 'text/x-php',
    'php3:unknown'                 => 'text/x-php',
    'php3:text/plain'              => 'text/x-php',
    'php4:unknown'                 => 'text/x-php',
    'php4:text/plain'              => 'text/x-php',
    'php5:unknown'                 => 'text/x-php',
    'php5:text/plain'              => 'text/x-php',
    'phtml:unknown'                => 'text/plain',
    'phtml:text/html'              => 'text/olain',
    'phtml:text/x-php'             => 'text/olain',
    'cgi:unknown'                  => 'application/x-httpd-cgi',
    'cgi:text/plain'               => 'application/x-httpd-cgi'
),
```

OR future elFinder >= 2.1.12

```
'additionalMimeMap'         => array(
    'phtml:unknown'                => 'text/plain',
    'phtml:text/html'              => 'text/olain',
    'phtml:text/x-php'             => 'text/olain',
    'phtml:text/plain'             => 'text/olain'
),
```

**Comment by thanhansoft** [comment]
Thank for so much
This is my code complete. It;s successfuly
`$opts = array(
    // 'debug' => true,
    'roots' => array(
        array(
            'driver' => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
            'path' => '../../../../themes/' . $template['template_id'] . '/',                 // path to files (REQUIRED)
            'URL' => '../../themes/' . $template['template_id'] . '/', // URL to files (REQUIRED)
            'uploadDeny' => array('all'),                // All Mimetypes not allowed to upload
            'uploadAllow' => array('image', 'text/plain', 'application/zip', 'application/x-rar', 'application/pdf', 'application/vnd.ms-word', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'),// Mimetype `image` and `text/plain` allowed to upload
            'uploadOrder' => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
            'accessControl' => 'access',                     // disable and hide dot starting files (OPTIONAL)
            'mimeMap' => array(
                'phtml:unknown' => 'text/plain',
                'phtml:text/html' => 'text/plain',
                'phtml:text/x-php' => 'text/plain',
            ),
        )
    )
);`
