### ISSUE TITLE
Google chrome incognito mode session problem

### ISSUE THREAD

**Issue by Mozhdeh-d** [Studio-42/elFinder#1902]
Hi,
After updating Elfinder to the latest version, I faced a problem in google chrome browser incognito mode.
When I open Elfinder, it opens but then it destroy all my sessions and log me out of the panel for instance.
I checked it in other browsers say Firefox and IE, and the problem doesn't exist there. also, there's no problem in google chrome normal mode.

p.s : My previous version was 15 and it worked properly.

**Comment by nao-pon** [comment]
@Mozhdeh-d I tried `netmount` to check session on our demosite with Chrome 56.0.2924.87 (64-bit) incognito mode. I didn't have any problems. Do you have any additional informations?

**Comment by Mozhdeh-d** [comment]
Hi,
After some messing around with my code, I figure out what the problem is. In my login page when I want to start the session, I use the code below:

$domain = example.com
session_set_cookie_params(0, '/', $domain);
session_start();

When I comment 'session_set_cookie_params', everything works fine. And as I mentioned before the problem just occurs when I work with google chrome incognito mode.

Thank you for your attention
