### ISSUE TITLE
connector won't work in elfinder.php

### ISSUE THREAD

**Issue by andreasw525** [Studio-42/elFinder#1905]
Hello,
I tryed to run the connector.php in the elfinder.php (elfinder.html) but it doens't work...
I want to run the script with mysql echo's and want wo include the connector.php in the elfinder.php and i don't want the script load the connector.php (url: 'php/connector.minimal.php', ... ) cause the echo's doesn't work if the script load the connector.

is it possible to run the connector.php in the elfinder index? and let the script know to run this "connector" in the index?

**Comment by nao-pon** [comment]
@andreasw525 Do you mean that you want to make the front end and back end a single script? If so, What about it to divide the case of XHR request and include the connector?

This is not a elFiner's issue, so I'll close this.

Thanks.
