### ISSUE TITLE
 File Upload Fails

### ISSUE THREAD

**Issue by ticflexo** [Studio-42/elFinder#1906]
We use conector minimal to a remote ftp server. When we try to upload few files, not all the files are upload.

**Comment by nao-pon** [comment]
@ticflexo Is there a similar problem with [netmount of our demo site](https://studio-42.github.io/elFinder/)? Please check the cause first. For example, timeout or memory shortage or FTP connection error etc.

**Comment by ticflexo** [comment]
@nao-pon Hello

I've been doing tests and there are no mistakes from those guys.

You mysteriously upload 5 files and leave 3, but in the network inspector, it does not come out as it sends them, the array appears empty and if they exit the 2 that goes up.

If you upload them later separately, they all upload without problem.

Any ideas?

We are attacking a local FTP server using an internal ip.

Thanks!
![captura de pantalla 2017-02-22 a las 13 19 28](https://cloud.githubusercontent.com/assets/25928905/23211257/7c600a54-f901-11e6-8946-83d8d7dcaa42.png)

**Comment by nao-pon** [comment]
@ticflexo Please try debug of PHP backend.

1. Set error reporting value to `-1` in your connector php. `error_reporting(-1);`
2. Catch php error in call back fuunction.
e.g.
```php
class mydebug
{
    public function debugLog() {
        if (! defined('ELFINDER_API_VER')) {
            if (elFinder::$phpErrors) {
                $o = join("\n", elFinder::$phpErrors) . "\n";
                file_put_contents(__DIR__ . '/.debuglog.txt', $o, FILE_APPEND);
            }
        }
    }
}
$opts = array(
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    ),
    'bind' => array(
        '*' => array($mydebug, 'debugLog'),
    ),
);
// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```
