### ISSUE TITLE
Unable to connect to backend. HTTP error 504

### ISSUE THREAD

**Issue by marcozink** [Studio-42/elFinder#1908]
Hello,

I am running verision 2.1 with Nginx in a Debian 8 EC2. Everything is working fine, however when I try to create an archive from the root, which would create a 2G+ zip or tar.gz file, the interface starts working and after a few seconds I get a 504 error.

I can see the file being generated in the directory, even after the error, if I click the close button the process starts over and another file starts being generated.
![captura](https://cloud.githubusercontent.com/assets/2729387/23183045/430d9ecc-f840-11e6-9ce0-1f4caa9c0e6d.PNG)

I've updated some php.ini variables but it doesn't seem to make any difference, any ideas?

Thanks in advance

**Comment by nao-pon** [comment]
@marcozink "HTTP error 504" is gateway timeout, probably that is timeout of Nginx(fast cgi?). Please check configure of Nginx(`max_execution_time` or `fastcgi_read_timeout`?) .

This is not an issue with elFinder, so I'll close it.

**Comment by tukusejssirs** [comment]
@nao-pon, I’ve run to to this issue too, however, I use Apache. I have already set `max_execution_time` to `0` in the connector file and in the client file, but it did not help.

I need to connect to a remote share (SMB v1.0) on a local network (elFinder sees this share as a local folder, as I need to manage the access outside of elFinder), therefore it is very, very slow to gather all the metadata (there are 615 small files of total 5.6 MiB in size in one folder).

Thanks in advance for any help or hint. :wink:

**Comment by mguinness** [comment]
From https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time

> Your web server can have other timeout configurations that may also interrupt PHP execution. Apache has a Timeout directive and IIS has a CGI timeout function. Both default to 300 seconds. See your web server documentation for specific details.
