### ISSUE TITLE
startPathHash in elf 2.1.21 visually duplicates two-level deep folders 

### ISSUE THREAD

**Issue by donShakespeare** [Studio-42/elFinder#1909]
Since startPath stopped working, I now use startPathHash - wonderful idea.
This is my url structure
http://example.com/browser.html?folder=manager **(works fine)**
http://example.com/browser.html?folder=manager/min **(starts to cause the visual error)**
http://example.com/browser.html?folder=manager/min/css **(same error)**
http://example.com/browser.html?folder=manager/min/css/and/so/on/and/so/forth **(same error)**

**ERROR**:
In the folder navigation sidebar tree, the last folder in the url parameter will be temporarily visually duplicated.
Same in the folder parent.

This can take about two elfinder reloads to clear out.
See image below

![image](https://cloud.githubusercontent.com/assets/5103329/23271924/9b0259fc-f9b6-11e6-88a8-51d52e403a4c.png)

**Comment by donShakespeare** [comment]
This also affects the nightly build
```
Version: 2.1.21 (2.1-src Nightly: 443b156), protocol version: 2.1
jQuery/jQuery UI: 3.1.1/1.12.1
```

**Comment by nao-pon** [comment]
@donShakespeare It seems no problems.

Output example

- http://output.jsbin.com/kahaze?folder=BasicAuthExample
- http://output.jsbin.com/kahaze?folder=BasicAuthExample/BasicAuthExampleAddon
- http://output.jsbin.com/kahaze?folder=BasicAuthExample/BasicAuthExampleAddon/js

JavaScript example

- http://jsbin.com/kahaze/edit?js

**Comment by donShakespeare** [comment]
@nao-pon  Thanks for checking, sir. I will return to do some more homework.
Great salutations for all your work here.
