### ISSUE TITLE
unable to rename folder

### ISSUE THREAD

**Issue by erny83pd** [Studio-42/elFinder#1911]
I've this problem when I try to rename a folder
![elfinder error](https://cloud.githubusercontent.com/assets/17987671/23305656/2cc18522-faa0-11e6-97f6-24910330ab51.jpg)

**Comment by nao-pon** [comment]
@erny83pd Yes, this is a bug of PHP class elFinderVolumeDriver. I'll fix it.

Thanks! 👍
