### ISSUE TITLE
how i can chnage language 

### ISSUE THREAD

**Issue by vahidalvandi** [Studio-42/elFinder#1912]
'locale' => 'en_US.UTF-8'

i need to change other language but not work

**Comment by nao-pon** [comment]
@vahidalvandi What part is "language" you say? Back-end processing language? Or the file manager's UI language?

**Comment by vahidalvandi** [comment]
i need change UI langauge like menu , buttons,..

**Comment by vahidalvandi** [comment]
how i can use this
[](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#localization)
