### ISSUE TITLE
Connector for .NET Core

### ISSUE THREAD

**Issue by gordon-matt** [Studio-42/elFinder#1913]
Hi there. I have created a new connector for ASP.NET Core, based on leniel's original. You can find it here: https://github.com/gordon-matt/elFinder.NetCore. Please add it to the list in your README file for others to find.

**Comment by nao-pon** [comment]
@gordon-matt Thank you for your contribute! Would you make Pull Request to master branch about your edited README.md?

Thanks!

**Comment by gordon-matt** [comment]
Done, as requested.  :-)
