### ISSUE TITLE
How to section elfinder instances?

### ISSUE THREAD

**Issue by LewisHolt** [Studio-42/elFinder#1914]
I've got Elfinder Instance A & ElFinder Instance B with Roots created for both of them. 

Do you know how I can section them off so Instance A will only show Root A and Instance B will only show Root B?

Right now all elfinder instances are showing all of the roots which I don't want to happen.

**Comment by donShakespeare** [comment]
Depending on your environment, the task could be much easier. Try passing a value via URL parameter to the connector, then do some logic there to show what roots depending on what value of
 `elfinder.html?roots=a`

 `elfinder.html?roots=b`
