### ISSUE TITLE
Problem with Laravel 5.4 Update

### ISSUE THREAD

**Issue by skatsaounis** [Studio-42/elFinder#1916]
I encountered the following problem while trying to update Laravel to 5.4.

file: php/elFinderVolumeDropbox.class.php
line: 892
share() is no longer supported in Laravel 5.4

It should be nice to be updated.

Thank you for your time.

Kind regards,
Stamatis

**Comment by nao-pon** [comment]
@skatsaounis `elFinderVolumeDropbox.class.php` will be disabled due to deprecation of APIv1. Please use `elFinderVolumeDropbox2.class.php` which will be included in elFinder 2.1.23. Currently you can try it with [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).
