### ISSUE TITLE
Expose connector options to client

### ISSUE THREAD

**Issue by donShakespeare** [Studio-42/elFinder#1917]
Is it possible to return volume root options to the client, like alias, id, etc?
I have been digging how to **natively expose** the volume id.

My workaround method is to append the volume `id` to the volume `alias`, then extract the `id` from the `file.path` during client `getFileCallback` . But there is only so much I can add to the alias without clogging it up.

Is this the only option?
https://github.com/Studio-42/elFinder/wiki/Adding-file-description-to-Properties-dialog

Thanks in advance

**Comment by nao-pon** [comment]
@donShakespeare The `volumeid` is included in the file stat of each directory.
