### ISSUE TITLE
url not start with slash 

### ISSUE THREAD

**Issue by mus-int** [Studio-42/elFinder#1919]
hi
I'm using elfinder with Tinymce.
It works well but if I choose the file the elfinder return the file url without slash at the beginging.
say I chose a file `mycar.jpg` at `pubfiles` folder then the url should be: `/pubfiles/mycar.jpg`.
But the elfinder return the url like this: `pubfiles/mycar.jpg`.
Is it a bug ?

**Comment by nao-pon** [comment]
@mus-int Is the [tmbURL](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#tmburl) option properly set?
