### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by standus** [Studio-42/elFinder#1920]
Close button of Elfinder window is not translated. Other texts are OK.

**Comment by nao-pon** [comment]
@standus Do you have any screenshots?

**Comment by standus** [comment]
![fireshot capture 23 - coumes - nastaveni - https___www coumes com_admin111_setting_slider elf_l1_xa](https://cloud.githubusercontent.com/assets/4818430/23697695/059c32ce-03e9-11e7-90ba-c006f5f08519.png)

**Comment by nao-pon** [comment]
It seems to be a problem with your dialog.

**Comment by standus** [comment]
Ohh, soo sory, I will check it.
