### ISSUE TITLE
HTTP 503 going from old live server to new live server

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1921]
Recently moved servers and I am now getting HTTP 503 error when trying to load elFinder.

Wondering if anyone had any ideas?

I am using Flysystem and the Google Cloud adapter, so I will post there too.

On localhost, it loads fine (pointed at a live Google Cloud account)

The URL that fails is http://domain.com/index.php/elfinder/connector/elfinder_init?cmd=open&target=flsGCS_&init=1&tree=1&_=1489073114807

On localhost, this URL loads fine and shows the root volumes.

New server seems to be very similar to the old one, with PHP 5.6. Is there anything I could be missing?

**Comment by nao-pon** [comment]
@paulcanning Please allow concurrent access with your server settings.
