### ISSUE TITLE
Large size photos can not be displayed after thumbnails

### ISSUE THREAD

**Issue by yinmingming** [Studio-42/elFinder#1922]
Hi Everyone！
I uploaded a photo, size 20MB (8352 × 2208), generated thumbnail size into 40kb (8352 × 2208), I have set the 'tmbSize' => '600', and the thumbnail can not be displayed. But another 12MB (4032 × 3024) after uploading into a 30kb (600 x 600) can be displayed.

**Comment by nao-pon** [comment]
@yinmingming  If you are using GD for image processing, I think that there is insufficient memory of PHP.

In the case of JPEG images, 6 to 10 times as much memory as the number of pixels is required. (8,352 × 2,208 × 10 = 184,412,160 bytes)

Please consider using Imagick or convert.

**Comment by yinmingming** [comment]
@nao-pon Thank you very much！Use imagick successfully

**Comment by learningcentrum** [comment]
if a use the directory of the course owner it works fine
 You can use the directory of the course owner, this work
you can use the directory of the course this don't work with the pictures, this is the problem , the rights are the same
