### ISSUE TITLE
[ui:cwd] first letter search & navigation in cwd

### ISSUE THREAD

**Issue by N73dp** [Studio-42/elFinder#1923]
Can i somehow do a letter navigation  files?
And can someone help me hide section with volumes.
Thanks
So ok,hide section with css.
.elfinder-navbar{
    display: none!important;
}
Is Letter navigation possible?

**Comment by N73dp** [comment]
Maybe i explain not clearly,want to search files when press on letter buttons,can someone help?Please

**Comment by nao-pon** [comment]
@N73dp Is incremental search a substitute for it? `Ctrl + F` and press `a` and next characters.

**Comment by nao-pon** [comment]
> hide section with volumes

There is a client configuration `ui`.
e.g. `['toolbar', 'path', 'stat']`

**Comment by nao-pon** [comment]
The elFinder performs lazy loading of items. It is difficult to handle when all items are not loaded.

> Can i somehow hide rights column in table of files?

You can use a client configuration `uiOptions` ([uiOptions.listview.columns](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L513-L518)).

> where is text "search results is empty..."need to translate it.

Which language are you using? We are welcome your translations. There is [translation tool](http://studio-42.github.io/elFinder/tools/langman/). Please visit it.

**Comment by N73dp** [comment]
Thanks for answers, i use russian language, there is no this string in translation file,so thereis no decision for my  task?

**Comment by nao-pon** [comment]
I updated template file.so you be able to find "Search results is empty in current view.\APress [Enter] to expand search target." in [translation tool(RU)](http://studio-42.github.io/elFinder/tools/langman/#2.1:ru) now. Please change this input filed, and of course, you can change other words and phrases. Then please click "Make it!", and Please send a pull request with reference to the displayed contents.

Thanks!

**Comment by N73dp** [comment]
Can i somehow simulate events of live search?
