### ISSUE TITLE
PLEASE Help!

### ISSUE THREAD

**Issue by phpprousa** [Studio-42/elFinder#1924]
I had elFinder working fine on one server.  Moved it to another (same code) and NO MATTER what I do the files folder WILL NOT unlock.  Any ideas?

$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '../files/',                 // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
			'defaults' => array('read' => true, 'write' => true),
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		)
	)
);

**Comment by phpprousa** [comment]
Also running CentOS 6.8 on trouble machine

**Comment by FelipeGrijo** [comment]
@phpprousa Have you tried set permission on folder? sudo chmod...

**Comment by phpprousa** [comment]
Yes but it just won't unlock.

**Comment by phpprousa** [comment]
Just FYI, I got it to work with 777 permissions, but I feel that is insecure

**Comment by nao-pon** [comment]
Another solution is to use the FTP driver.

**Comment by yangzhengpk** [comment]
sorry my friend,I think in CentOS 7 are given 0777 folder permissions can be used, I was so stupid.But I still can not find the so-called executive PHP.FTP need to modify some code,  I think the problem is in the background of Linux.
