### ISSUE TITLE
Original folder name show in Preview Window

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1926]
You Can see it.

**Also if you copy that folder,it copy with its Original name.**

![image](https://cloud.githubusercontent.com/assets/18566890/23910430/b9b9c86e-08ff-11e7-8b58-44d71df0e068.png)

**Comment by CodeLyokoXtEAM** [comment]
Also in Preview window doesn't show folders specific icons.

![image](https://cloud.githubusercontent.com/assets/18566890/23910761/c1c5ca8e-0900-11e7-8a3e-c610b6d803eb.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks! 👍

**Comment by CodeLyokoXtEAM** [comment]
Still not fix this.
![untitled](https://cloud.githubusercontent.com/assets/18566890/24157790/67ac0f06-0e80-11e7-8429-e069c03c72d9.png)

Also I found Another Bug.
Try to copy "Welcome(Multilingual)" folder.(real name changed folders)
Its impossible.

Can you Check it?

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Yes, I'll fix it.

> Also I found Another Bug.
Try to copy "Welcome(Multilingual)" folder.(real name changed folders)
Its impossible.

This is not a bug. That is an operational problem. However, the error message is incorrect. I will fix this.

Thanks!
