### ISSUE TITLE
Is it possible to return a info of video file?

### ISSUE THREAD

**Issue by SkyTaurus** [Studio-42/elFinder#1927]
Is it possible to return extension info of video file?
I need duration, frame rate, resolution.
The command ffmpeg -i <filename> can return info.

**Comment by nao-pon** [comment]
@SkyTaurus Next HowTo may help you.

- [Using LocalFileSystem together with MySQL](https://github.com/Studio-42/elFinder/issues/1808)
- [Customize status bar text](https://github.com/Studio-42/elFinder/issues/1524)
- [(Question) Show files' meta data in the icons view](https://github.com/Studio-42/elFinder/issues/1878)
