### ISSUE TITLE
elRTE + elFinder 2.1

### ISSUE THREAD

**Issue by Poxos** [Studio-42/elFinder#1928]
Hi,
I have the following issue,
1. I click on Image icon of elRTE - it opens Image dialog: https://ibin.co/3Fn9SdKpHqDb.png
2. then I click on "Open elFinder" button.
The problem is - the elFinder dialog is opened on the back side of Image dialog like this: https://ibin.co/3Fn7oqmeko0g.png

How to bring it to the front, thank you.

**Comment by nao-pon** [comment]
Probably, it seems to be a problem of z-index. Please try specifying the z-index of the base element of elFinder.
