### ISSUE TITLE
help : please give connector configuration for gridfs adapter

### ISSUE THREAD

**Issue by dipenpatel235** [Studio-42/elFinder#1930]
Hello,
i want to setup 
https://flysystem.thephpleague.com/adapter/gridfs/

so i have also done composer required elfinder-flysystem-driver

Now not idea what changes required in connector.minimal.php or autoload.php
so please guide to me what need to do for that ?

Thanks

**Comment by nao-pon** [comment]
@dipenpatel235 Please refer to the README of [elFinder Flysystem Driver](https://github.com/barryvdh/elfinder-flysystem-driver/blob/master/readme.md).

**Comment by dipenpatel235** [comment]
Hello..
Thanks for that suggestion.
I have already read that but not getting any idea.
Thats why I am came here.

So please help me some more guidelines.

Thanks.

**Comment by nao-pon** [comment]
Moved to https://github.com/barryvdh/elfinder-flysystem-driver/issues/56
