### ISSUE TITLE
"Unable to create folder!" with Drupal 7 plugin.

### ISSUE THREAD

**Issue by blacRose** [Studio-42/elFinder#1934]
My file path is `/var/www/i3/sites/default/files/i3`. It worked in the past with the same permissions, using Apache. But I switched to nginx/php-fpm. Watching htop as I do modifications, php-fpm is running as user www-data. That directory was `chmod -R 777` and I did `chown -R www-data:www-data /var/www`. But I still get the error. I tried to use a random php file with

    <?php mkdir('/var/www/i3/sites/default/files/i3/bob'); ?>

but when I `curl` the url, it returns nothing and the dir isn't made.

I CAN make files, everywhere it's set to be 0666 for them, but when I DO make them, they're 0644 in the file system.

Was any of this fixed in a more recent version? And, do you have any other suggestions?

**Comment by nao-pon** [comment]
@blacRose It is due to permission or web server configuration, it is not an issue on the elFinder side.

**Comment by blacRose** [comment]
Turns out, `/` was out of space. Closing.
