### ISSUE TITLE
Disable move/copy/paste command?

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1938]
Is there a way to disable these commands?

And the drag-n-drop function?

**Comment by nao-pon** [comment]
@paulcanning Please use a connector option [`disabled`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#disabled).

e.g, `'disabled' => array('cut', 'copy', 'paste'),`

There is a related fix.

- [[ui: cwd] disable dragable when copy command is invalid](https://github.com/Studio-42/elFinder/commit/38059f2d6b3e6c5e67375b66d4921d3add0d2852)

Until the 2.1.23 release, you can try nightly builds.

**Comment by paulcanning** [comment]
I have added that in, and I can still drag icons about, as if to copy/move them. Is there a way to fully disable the drag-n-drop feature?

Also, how do I upgrade from 2.1.16 to the latest version? The main elFinder JS file has been renamed and there are now seperate UI JS files?

**Comment by nao-pon** [comment]
That problem has been fixed and is included in 2.1.23. If you want to check early, you can try the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

> how do I upgrade from 2.1.16 to the latest version?

Please overwrite with the new version.

**Comment by paulcanning** [comment]
Simply overwrite to upgrade? What about the fact that the main JS file is named differently? Guessing it is more then _just_ overwriting?

**Comment by nao-pon** [comment]
The minimum required file in js is elfinder.min.js. There is no change in this file name.
