### ISSUE TITLE
Menubar Auto-Collapse on Touch Devices

### ISSUE THREAD

**Issue by Nuvolect** [Studio-42/elFinder#1939]
On Android touch devices the elFinder 2-1-22 menu bar collapses when starting, every time.
The menu bar can be expanded by carefully dragging the top of the file area down.
It happens every time, from an Android WebView, from Chrome or from Firefox.

On non-touch devices, on Chrome from my Mac it does not collapse.

![elfinder header collapse webview](https://cloud.githubusercontent.com/assets/19307825/24429087/95daaa0a-13de-11e7-9825-8a0207d1abcb.png)
![elfinder header collapse chrome](https://cloud.githubusercontent.com/assets/19307825/24429088/95dc3d48-13de-11e7-93a2-e74b96670396.png)

You can see the [configuration in GitHub](https://github.com/Nuvolect/SecureSuite-Android/blob/master/SecureSuite/src/main/assets/elFinder-2.1.22/ss_finder.html).

If you want to run it, the app is [free in Google Play](https://play.google.com/store/apps/details?id=com.nuvolect.securesuite).

**Comment by nao-pon** [comment]
There is client config option [`uiOptions.toolbar.autoHideUA`](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L469).

e.g.
```javascript
uiOptions : {
	toolbar : {
		autoHideUA: []
	}
}
```

However, please remember that this initial state will be stored in the browser.

**Comment by Nuvolect** [comment]
Still not working. It seems to ignore the autoHideUA setting.  I even edited elfinder.full.js, removed 'mobile', the behavior is the same.

**Comment by Nuvolect** [comment]
Version 2.1.11 works fine.  It only started auto-hiding when I upgraded.

Is this correct? 

`<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <title>SecureSuite</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2" />

    
    <link rel="stylesheet" type="text/css" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

    
    <link rel="stylesheet" type="text/css" href="css/elfinder.full.css">
    <link rel="stylesheet" type="text/css" href="css/theme.css">

    
    <script src="js/elfinder.full.js"></script>

    
    <script type="text/javascript" charset="utf-8">
			// Documentation for client options:
			// https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
			$(document).ready(function() {
				$('#elfinder').elfinder({
					url : '/connector',  // connector URL (REQUIRED)
					lang: 'en',          // language (OPTIONAL)
					docked: true,
					defaultView: 'list',
					uiOptions:{
					  toolbar: [
					    // extra options
					    {
					      autoHideUA: []
					    }
					  ],
					  navbar: {
					    autoHideUA: []
					  }
					}
				});
			});
        </script>

    
    <style type="text/css">
        html, body {
        height: 100%;
        margin: 0;
        }

        #elfinder {
        min-height: 100%;
        }
    </style>
    
    
</head>
<body>


<div id="elfinder"></div>

</body>
</html>
`

**Comment by nao-pon** [comment]
@Nuvolect Sorry, I made mistake. uiOptions.toolbar is Array so this option requires all of items.

e.g.
```javascript
uiOptions : {
	toolbar : [
		['back', 'forward'],
		['netmount'],
		['mkdir', 'mkfile', 'upload'],
		['open', 'download', 'getfile'],
		['info', 'chmod'],
		['quicklook'],
		['copy', 'cut', 'paste'],
		['rm'],
		['duplicate', 'rename', 'edit', 'resize'],
		['extract', 'archive'],
		['search'],
		['view', 'sort'],
		['help'],
		['fullscreen'],
		// extra options
		{
			// also displays the text label on the button (true / false)
			displayTextLabel: false,
			// Exclude `displayTextLabel` setting UA type
			labelExcludeUA: ['Mobile'],
			// auto hide on initial open
			autoHideUA: []
		}
	]
}
```

Please check in private (secret) mode to avoid memory of the browser when testing.

**Comment by nao-pon** [comment]
However, this is inconvenient, so fix extra options so that it can be specified separately.

**Comment by nao-pon** [comment]
You can set like this from elFinder >= 2.1.24 or [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

```javascript
uiOptions : {
	toolbarExtra : {
		autoHideUA: []
	}
}
```

**Comment by nao-pon** [comment]
Live demo: http://output.jsbin.com/regigu
JavaScript: http://jsbin.com/regigu/edit?js

**Comment by Nuvolect** [comment]
Problem solved @nao-pon, Many Thanks!
#1949 issue resolved
