### ISSUE TITLE
Ability to set a pattern for folder names?

### ISSUE THREAD

**Issue by twisted1919** [Studio-42/elFinder#1942]
Hi,

Is it possible to have an option where we can set a pattern for the folder names, so that if new folders are created or exiting ones are renamed, and they don't follow the pattern, they get some error?

My use case, i'm using elFinder for adding assets in emails, and because of white spaces in folder names, some email clients will have issues displaying images(even if the space is encoded).

Thank you.

**Comment by nao-pon** [comment]
@twisted1919 There is an option of connector roots. That is [`acceptedName`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#acceptedname).

Please be careful not to make it vulnerable to security.
