### ISSUE TITLE
using elfinder with asp.net mvc or core?

### ISSUE THREAD

**Issue by aloksharma1** [Studio-42/elFinder#1943]
hello,

i want to use elfinder with .net core (c#) while your provided examples are php only. is there any alternate available for other languages or do i need to write one?

thanks 

PS: in case i need to write one , please guide me on how to so i can share my solution .

**Comment by swindy1** [comment]
https://github.com/gordon-matt/elFinder.NetCore

**Comment by nao-pon** [comment]
@aloksharma1 Please read README - [3rd party connectors](https://github.com/Studio-42/elFinder#3rd-party-connectors).

@swindy1 Thanks!
