### ISSUE TITLE
ElFinder connect to MySQL correctly but doesn't insert data to MySQL

### ISSUE THREAD

**Issue by VahidLotfi** [Studio-42/elFinder#1945]
I configure everything, ElFinder connect to MySQL correctly and give number of tables 
when i make directory,  make file, upload file method `init` in `elFinderVolumeMySQL.class.php` called and initilizie the options  of connecting to database but method `_mkdir `and `_mkfile` never called.
This is my opions in elfinder 2.1.23:

>         
        array(
            'driver'     => 'LocalFileSystem',
            'path'       => 'G:/PhpStorm/Storage/',
            'URL'        => 'http://localhost:8000/storage',
            'tmbPath'    => 'Thumbnails',
            'quarantine' => 'Quarantine',
            'tmbSize'    => 64,
            'attributes' => array(
                array(
                    'pattern' => '/\.png$/',
                    'write'   => false,
                    'locked'  => true
                )
            )
        ),
        array(
            'driver'      => 'MySQL',
            'host'        => 'localhost',
            'port'        => '3306',
            'user'        => 'root',
            'pass'        => 'root',
            'db'          => 'dbName',
            'files_table' => 'elfinder_file',
            'path'        => 1,
            'URL'        => 'http://localhost:8000/storage',
            'tmbPath'    => 'Thumbnails',
            'accessControl' => 'access'
        )

What is my problem ?
1 - Cache of Elfinder
2 - Bugs in the ElFinder
3 - Xampp when i using
4 - ....

**Comment by nao-pon** [comment]
@VahidLotfi There is no problem with the test I did. Have you got any errors?
