### ISSUE TITLE
add file permissions (chmod/chown)?

### ISSUE THREAD

**Issue by pedroponte** [Studio-42/elFinder#1946]
can you add file permission editing on elfinder (chmod/chown)?

Thanks!

**Comment by nao-pon** [comment]
@pedroponte There is an option [`statOwner`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#statowner) in volume roots options. That make to activate the chmod command. There is no way to activate the chown command. Because chown require root of PHP run account.
