### ISSUE TITLE
Menubar Auto-Collapse on Touch Devices

### ISSUE THREAD

**Issue by Nuvolect** [Studio-42/elFinder#1949]
Having spent more time on it, version 2.1.11 works fine but the versions 2.1.22 and 2.1.23 do not work.  I believe functionality on mobile/touch devices is broken.

```
  uiOptions:{
    toolbar: [        
      // extra options  
      {                 
        autoHideUA: []    
      }                 
    ],                
    navbar: {         
      autoHideUA: []    
    }                 
  }  
```

More details are provided in issue: #1939 
https://github.com/Studio-42/elFinder/issues/1939

**Comment by nao-pon** [comment]
@Nuvolect Please read my comments.

- https://github.com/Studio-42/elFinder/issues/1939#issuecomment-291478320
- https://github.com/Studio-42/elFinder/issues/1939#issuecomment-291478538
- https://github.com/Studio-42/elFinder/issues/1939#issuecomment-291489773

Live demo: http://output.jsbin.com/regigu
JavaScript: http://jsbin.com/regigu/edit?js
