### ISSUE TITLE
after file upload , get the file.url not be urlencode

### ISSUE THREAD

**Issue by iridance** [Studio-42/elFinder#1952]
if i upload file name is "中文.jpg"

after upload and select the new file, file.url is get "/uploads/中文.jpg"

the url not be urlencode.

**Comment by nao-pon** [comment]
@iridance There is no problem on [demo site](https://studio-42.github.io/elFinder/#elf_l1_V2VsY29tZS_mraHov47lhYnoh6g).

If the connector returns the item URL it will be used as it is, so it may be a problem with the connector. Which connector do you use?

**Comment by iridance** [comment]
Hi nao-pon

demo site cannot do upload file, so cannot reproduce the issue

this issue occurs while uploaded and selecting a new file at the same time

version : 2.1.23
connector : elFinderConnector
driver : LocalFileSystem

**Comment by nao-pon** [comment]
You can upload to https://studio-42.github.io/elFinder/#elf_l2_Lw . Please test in that.

**Comment by nao-pon** [comment]
Oh, OK. I found problem return value file.url in files array is not urlencoded. So I'll fix it.

@iridance Thanks!

**Comment by iridance** [comment]
Yes!

I did not clearly describe the issue. sorry

thanks a lot
