### ISSUE TITLE
PHP Error on my Server

### ISSUE THREAD

**Issue by rajasharma27** [Studio-42/elFinder#1955]
Unable to connect to backend
HTTP Error 500

Sir,
When i click image folder elfinder open folder and create thumbnail, during thumbnail creation click another folder then showing error on my server, but working perfect on localhost machine.
![image1](https://cloud.githubusercontent.com/assets/16103829/24809890/f4a57da6-1bdd-11e7-92c5-04b06047ff08.jpg)

**Comment by nao-pon** [comment]
@rajasharma27 Does the error come out when the open command is executed? Or Is it a running tmb command?

**Comment by rajasharma27** [comment]
when open image folder it start create thumbnail, suppose 10 image in the folder, after create 3-4 thumbnail.
that time open another folder it showing error

**Comment by nao-pon** [comment]
Observe the XHR request in the browser developer tool and let me know which request is in error.

**Comment by rajasharma27** [comment]
HTTP404:  NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR): GET - http://fast.fonts.net/cssapi/e6dc9b99-64fe-4292-ad98-6974f93cd2a2.css

elfinder debug: [error] [elfinder] Unable to connect to backend.<br>HTTP error 500
elfinder.full.js (7024,44)

HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.
(XHR): GET - http://www.onlinewebplace.com/controlpanel/filemanager/php/connector.minimal

**Comment by nao-pon** [comment]
It seems that your server has set the number of concurrent connections to PHP files extremely low. Operating elFinder on such a server is quite restrictive.

**Comment by rajasharma27** [comment]
thanks sir
