### ISSUE TITLE
upload progress in some div

### ISSUE THREAD

**Issue by SkyTaurus** [Studio-42/elFinder#1957]
Whenever I upload a files I want to see 2 progress bar - all files uploaded and the current progress  in a certain place on the screen.  I'm using angular and when I switch to another form I need to have the files uploaded in the background process and progress be visible. How to do it?

**Comment by nao-pon** [comment]
According to the specification of Client - [Server API 2.1 (upload)](https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#upload), we can upload files by sending POST data to the server.

However, there is no API that obtains progress information during processing on server side.

There is a related issue(#1357).
