### ISSUE TITLE
Does Version 2.1.23 break all the 3rd Party Skins?

### ISSUE THREAD

**Issue by donShakespeare** [Studio-42/elFinder#1958]
Windows-10, Moono and Material all seem to be broken. Has anyone succeeded in loading skins, with the new way elFinder client is initiated?

**Comment by nao-pon** [comment]
@donShakespeare Please use client configuration `cssAutoLoad` to load additional CSS.

e.g.
```javascript
opts = {
    cssAutoLoad : ['themes/moono/css/theme.css'], // Array of additional CSS URLs
    url : 'php/connector.minimal.php', // connector URL (REQUIRED)
    lang: lang                         // auto detected language (optional)
}
```

**Comment by donShakespeare** [comment]
Perfect! Case 1 solved all my issues. All the themes are working.
I did not know about case 1 but I have fought with case 2 and some CSS is applied wrongly.

Thanks for the excellent help.
