### ISSUE TITLE
4 bugs report

### ISSUE THREAD

**Issue by 98549844** [Studio-42/elFinder#1960]
background :　i am using java servlet to build and test elfinder
using this version: https://github.com/bluejoe2008/elfinder-2.x-servlet

1. setting access right issue
i cant setup access right according user id or user properties to grand access right
please help

2. multi upload file will occur file missing
eg: i select some .mp3 file and some .xlsx together to upload. but the result is 20%~30% are uploaded and must file are .mp3 type file

3. multi download file will occur error : Unknown command.zipdl

4. new a newText file and rename to 1111.xlsx and download to local pc.
   the file will rename to connector.xlsx

if need provide source , please email to me : garlam_au@qq.com

thanks so much

**Comment by nao-pon** [comment]
@98549844 That is the subject of bluejoe 2008/elfinder-2.x-servlet, not Studio-42/elFinder. Please report with bluejoe 2008/elfinder-2.x-servlet.
