### ISSUE TITLE
File seems to upload, elFinder stuck on "Processing the uploaded file"

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1961]
I am using elFinder 2.1.23 along with the latest GCS FlySystem Adapter v5.0.0, which streams large files, rather than uploading them to memory.

Uploading a fairly small 300Mb file shows the upload progress bar and it goes from 0 to 100% quite quick on our office Internet connection.

However, after getting to 100%, there is a new progress bar, that is instantly on 100% and stays there, thats says "Processing the uploaded file".

What is it doing exactly? and Why does it take so long to disappear?

Surely my file was already uploaded?

NB - I just checked a 1Gb file. The upload progress bar is completed in about 25 seconds, which is fast, even for our connection speed. It seems the upload progress is fake, and the "Processing the uploaded file" is the real upload?

**Comment by nao-pon** [comment]
@paulcanning "Processing the uploaded file" means that the item uploaded to the web server is being uploaded to GCS. On network drives often require considerably more time than uploading to the web server. Also, since elFinder does not have an API to know the progress status on the Web server, it can not display its progress.

**Comment by paulcanning** [comment]
It should not be uploaded to the server first, it should be streamed straight to GCS, surely?

**Comment by nao-pon** [comment]
It is impossible with the current elFinder API.

**Comment by paulcanning** [comment]
elFinder can use FlySystem, which in turn can use the GCS adapter. So why wouldn't it be possible?

**Comment by nao-pon** [comment]
If you use FlySystem, you need to upload the file to the web server. To send directly to GCS stream, you need to send it directly to GCS from the browser. elFinder does not have such a mechanism.

**Comment by paulcanning** [comment]
It does, I just told you it does. elFinder > FlySystem > GCS Adapter

**Comment by nao-pon** [comment]
FlySystem supports streams. The situation does not change even if the connector driver of elFinder on web server directly uses the GCS adapter.

The elFinder client does not have an API to access the GCS connector or GCS directly.

**Data sequence of the file upload**
```
                Browser      Web server         GCS
Show first progress|------------->|              |
                   |Chunked upload|              |
Redraw progress bar|<-------------|              |
                   |------------->|              |
                   |Chunked upload|              |
Redraw progress bar|<-------------|              |
Show 2nd progress  |------------->|              |
                   |     Done     |              |
                   |              |------------->|
                   |              |Chunked upload|
                   |              |<-------------|
                   |              |------------->|
                   |              |Chunked upload|
                   |              |<-------------|
                   |              |------------->|
                   |              |     Done     |
                   |              |<-------------|
                   |              |    Results   |
Redraw progress bar|<-------------|              |
                   |   Results    |              |

```

**Comment by paulcanning** [comment]
So, despite using the elFinder FlySystem connector, FlySystem and finally the GCS FlySystem Adapter, elFinder still won't utilise the streaming capabilities of the GCS Adapter? 

Well, that is really unfortunate... 

Do you know of anyway to get this resolved? 

Honestly, I don't think I'm wrong to assume that streaming to GCS should work, seeing as I have the other components in play? 

Is this salvageable at all?

**Comment by nao-pon** [comment]
Have you understood the diagram of "Data sequence of the file upload"? It is as shown in that figure.

To upload directly from the browser to GCS, you need to have a connector that works with JavaScript. We do not have that plan.

There is no choice but to wait for you to make or someone else to make it.

**Comment by paulcanning** [comment]
Yes I have, thank you. 

Hmm, surely this should still work, as a chunked upload to the web server initially should work right? 

Otherwise, what is needed to utilise the GCS Adapter streaming methods? I assume they would work if I just used FlySystem without elFinder? 

So how exactly would javascript hook into the streaming methods? If I can at least be pointed in the right direction I can look to see if it's even possible?

**Comment by nao-pon** [comment]
I do not know what you want, but FileStream's handling is as follows.

- elFinder client do chunked upload to elFinder connector
- After upload is complete, elFinder connector pass thru file stream to FlySystem driver
- FlySystem driver pass thru file stream to FlySystem
- FlySystem pass thru file stream to GCS adapter

If the GCS adapter can handle file streams, I think uploading to GCS will be done in the stream,  but I do not know that part.

**Comment by paulcanning** [comment]
What if chunked uploads were disabled?

**Comment by nao-pon** [comment]
- elFinder client do upload to elFinder connector
- After upload is complete, elFinder connector pass thru file stream to FlySystem driver
- FlySystem driver pass thru file stream to FlySystem
- FlySystem pass thru file stream to GCS adapter
