### ISSUE TITLE
how upload thumbnail in same name directory source

### ISSUE THREAD

**Issue by vahidalvandi** [Studio-42/elFinder#1962]
hello

i create a folder like "banner"  when i upload a image in banner folder i need create a folder with name "banner" in thumbnail folder and upload thumb size in it.

please help

**Comment by nao-pon** [comment]
Duplicated to #1795.

**Comment by vahidalvandi** [comment]
thanks you it work fine , but have problem , in file explorer in sub folder dont show thumb image 
i uploaded sample screenshot
![untitled](https://cloud.githubusercontent.com/assets/17952925/24955073/33e953ea-1f97-11e7-8145-1486294a36da.jpg)

**Comment by nao-pon** [comment]
If you specify the `tmbPath` option, set the` tmbURL` option appropriately accordingly.

**Comment by vahidalvandi** [comment]
this my config , in root show thumb ,  because   thumb have  in sub folder

```
   'roots' => array(
        array(
            'alias'         => 'Host',
            'driver'        => 'MyLocalFileSystem',
            'path'          => $_SERVER['DOCUMENT_ROOT'].'/uploads/source',
            'URL'           => DIR.'uploads/source/',
            'mimeDetect'    => 'internal',
            'tmbPath'       => $_SERVER['DOCUMENT_ROOT'].'/uploads/thumbs',
            'quarantine'    => $_SERVER['DOCUMENT_ROOT'].'/uploads/quarantine',
            'tmbURL'        => DIR.'uploads/thumbs/',
            'utf8fix'       => true,
            'tmbCrop'       => true,
            'tmbSize'       => 150,
            'acceptedName'  => '/^[^\.].*$/',
            'accessControl' => 'access',
            'dateFormat'    => 'j M Y H:i',
            'defaults'      => array('read' => true, 'write' => true),
			'plugin' => array(
 					'Sanitizer' => array(
 						'enable' => true,
 						'targets'  => array('\\','/',':','*','?','"','<','>','|',' '), // target chars
 						'replace'  => '_'    // replace to this
 					),
					'Normalizer' => array(
 						'enable'    => true,
 						'nfc'       => true,
 						'nfkc'      => true,
  						'lowercase' => true,
 						'convmap'   => array()
 					)
 			)
 
 
        ),
 
        )
```

**Comment by nao-pon** [comment]
@vahidalvandi Is your elFinder running on a Windows server?

**Comment by nao-pon** [comment]
I updated  of https://github.com/Studio-42/elFinder/issues/1795#issuecomment-265627105. Please check out.

**Comment by vahidalvandi** [comment]
thanks , but have small problem , after upload dont show thumb , but after refresh show thumb

**Comment by nao-pon** [comment]
Oh, I updated [comment of https://github.com/Studio-42/elFinder/issues/1795#issuecomment-265627105. Please check out again.

**Comment by vahidalvandi** [comment]
thank you.

**Comment by isreehari** [comment]
Can any update on this please, I am having the same issue.  @nao-pon 
> thanks , but have small problem , after upload dont show thumb , but after refresh show thumb


Thanks,
Hari
