### ISSUE TITLE
How to resolve Conflict of search url parameter and other apps

### ISSUE THREAD

**Issue by donShakespeare** [Studio-42/elFinder#1963]
![image](https://cloud.githubusercontent.com/assets/5103329/24978232/c4352b94-1f84-11e7-927f-0ba0703f3434.png)

If you press enter on the search, an `&q=search_query` is sent to the backend to your connector url.
Many other apps, including CMSes, and google plugins, already use that parameter to redirect their pages via .htaccess.

Is there a way to extend/customize the function that sends this url parameter?
Even a capitalized letter would resolve this conflict `&Q=search_query`

Thanks.

**Comment by nao-pon** [comment]
@donShakespeare Please try set client configuration [`requestType`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#requesttype) to 'post'.

**Comment by donShakespeare** [comment]
Thanks.
I tried that. The mother CMS/htaccess still redirects it.
I reckon that the best solution would be to able to alter the parameter name before it is sent to backend.

**Comment by nao-pon** [comment]
> I tried that. The mother CMS/htaccess still redirects it.

Is the POST method request redirected too?

Have you refreshed your browser's cache? Please check POST method transmission in the browser developer tool etc.

**Comment by donShakespeare** [comment]
![image](https://cloud.githubusercontent.com/assets/5103329/24986599/03f02402-1fb0-11e7-8910-c3347b9293c0.png)

My **connector file** is not an actual physical file, but rendered by _MODX CMS_.

Everything works superbly with `requestType: post`
`XHR finished loading: POST "http://localhost:81/DEV/elfinder.html`

Except when there is a `q` sent by post or get.
`elfinder.html    ....	POST    ....	404    ....	xhr    ....	Other    ....	34.3 KB	`

If I go into my CMS and modify the request param to `q_private`
And change its htaccess rule to ...
```
# The Friendly URLs part
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?q_private=$1 [L,QSA]
```
... then elFinder extended search works perfectly when enter is pressed.

**Comment by nao-pon** [comment]
OK, In that case, please overwrite `elFinder.request()`.

e.g.
```javascript
var elf = $('#elfinder').elfinder(opts).elfinder('instance');
var elf_request = elf.request;
elf.request = function(opts) {
	if (opts.data && opts.data.cmd && opts.data.cmd === 'search') {
		opts.data.q_private = opts.data.q;
		delete opts.data.q;
	}
	return elf_request.call(elf, opts);
};
```

**Comment by donShakespeare** [comment]
This approach works flawlessly with `requestType: get`

But returns a consistent error with `requestType:post` (with or without the CMS htaccess rewrite)
Too bad, because `post` is great for basic hiding of url parameters. 
`Invalid parameters for command "search"`
![image](https://cloud.githubusercontent.com/assets/5103329/24996552/218f7a84-1fe8-11e7-8458-95cb1f3c0963.png)

**Comment by nao-pon** [comment]
Please assign parameter `q_private` to `q` in your connector.

```php
if (isset($_POST['q_private'])) {
    $_POST['q'] = $_POST['q_private'];
}
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```

**Comment by donShakespeare** [comment]
That is exactly it! @nao-pon . The missing piece!
Excellent victory!

Many thanks to you, this conflict is now simply non-existent.


**FINAL CODE**
In your Client config (JS)
```js
requestType: 'post', // post or get (optional)
//...
// Start elFinder (REQUIRED)
start = function(elFinder) {
    //...
    // load jQueryUI CSS
    $(function() {
        //...
        // Make elFinder (REQUIRED)
        var elf = $('#elfinder').elfinder(opts).elfinder('instance');
        var elf_request = elf.request;
        elf.request = function(opts) {
            if (opts.data && opts.data.cmd && opts.data.cmd === 'search') { //fire only when search request is made
                opts.data.q_my_own_parameter = opts.data.q; //swap in your own parameter
                delete opts.data.q; //remove the conflict to survive htaccess redirect
            }
            return elf_request.call(elf, opts); //continue business as usual - send the info to backend
        };
    });
},
```

In your Connector (PHP)

```php
//since elFinder needs back the &q parameter, 
//you can safely reassign it here because the htaccess is done with redirecting
//Conflict resolved!!!!!!

if (isset($_POST['q_my_own_parameter'])) { //if client JS requestType is 'post'
    $_POST['q'] = $_POST['q_my_own_parameter'];
}

if (isset($_GET['q_my_own_parameter'])) {  //if client JS requestType is 'get'
    $_GET['q'] = $_GET['q_my_own_parameter'];
}

//...
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```
