### ISSUE TITLE
images dispear in some directeries

### ISSUE THREAD

**Issue by learningcentrum** [Studio-42/elFinder#1964]
2 main places for documents and images
user dir (mijn bestanden) en the courses dir (ZCO Documenten)
in the courses dir the images don't dispay and the can't place the images
the richts are 775 or 664

![filemanager chaminlo](https://cloud.githubusercontent.com/assets/26379170/24994569/be4b6b4c-202b-11e7-84cd-82328759103e.jpg)
![filemanager-2](https://cloud.githubusercontent.com/assets/26379170/24994572/be4f11ac-202b-11e7-883e-14d6462120fa.jpg)
![file manager](https://cloud.githubusercontent.com/assets/26379170/24994570/be4c1b96-202b-11e7-9208-b9f3fe359c90.jpg)
![filemager-1](https://cloud.githubusercontent.com/assets/26379170/24994571/be4da2ea-202b-11e7-8c7b-2e1ad9ee157a.jpg)

**Comment by nao-pon** [comment]
@learningcentrum `files/.tmb` or indicated by connector setting `tmbPath` is nothing or you do not have write permission, or the setting of` tmbURL` in the connector setting is incorrect.

**Comment by learningcentrum** [comment]
I can not find the .tmb file

**Comment by nao-pon** [comment]
`files/.tmb` is a writable directory. If tmbPath is not specified, the child directory `.tmb` of the directory specified by the 'path' option is used as the thumbnail directory.

**Comment by learningcentrum** [comment]
not only the thumbnail is missing, the picture can't put in the text, if I select it, it won't be in imported in the text editor
![thumb](https://cloud.githubusercontent.com/assets/26379170/25236111/507139be-25e7-11e7-8628-a5411af9afda.jpg)

![message_error](https://cloud.githubusercontent.com/assets/26379170/25235605/f1779d28-25e5-11e7-8545-0c6f3dc246db.png)

**Comment by nao-pon** [comment]
If there is no mistake in the setting of `tmbPath` and `tmbURL`, there may be a memory shortage of PHP.

see #1922.

**Comment by nao-pon** [comment]
Oh, is it a permission problem? Is it possible to solve by setting the permission of the thumbnail directory to 777?
