### ISSUE TITLE
Disable delete for folders ONLY, allow for files?

### ISSUE THREAD

**Issue by paulcanning** [Studio-42/elFinder#1967]
Is there a way to only allow the delete command to be present in the right-click context menu for files?

I want to stop folders being deleted and only let files be deleted.

Is this possible?

**Comment by nao-pon** [comment]
@paulcanning Yes.

Use connector roots option [`accessControl`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#accesscontrol).

e.g.
```php
function access($attr, $path, $data, $volume, $isDir) {
	// set locked all of folder
	if ($attr === 'locked' && $isDir) {
		return true;
	}
	
	return null; // or your controlling code
}
```
