### ISSUE TITLE
How to close notify ?

### ISSUE THREAD

**Issue by limars** [Studio-42/elFinder#1969]
Hi all:
if I create a notify on my own command.js  such as 
fm.notify({type : 'copy', cnt : 1, hideCnt : true});
but I cannot find a way to close the notify manually.
such as 
1. fm.notify(close);
2. fm.notify({type : 'copy', cnt : -1, hideCnt : true});

Thanks for your help

**Comment by nao-pon** [comment]
@limars That's OK.

1. show notify
    `fm.notify({type : 'copy', cnt : 1, hideCnt: true});`
2. close notify
    `fm.notify({type : 'copy', cnt : -1});`
