### ISSUE TITLE
How to set default options?

### ISSUE THREAD

**Issue by Greendeviate** [Studio-42/elFinder#1970]
I would like to make it default to full screen and maybe list mode as well when it is opened? I cant seem to find where that would be located.

**Comment by nao-pon** [comment]
@Greendeviate There is a client configuration option [`defaultView`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#defaultview) to set default view.

Transition to full screen is impossible without user intervention. That is the specification of the browser. However, it is possible to fit in the browser window. See #1965.
