### ISSUE TITLE
Thumbnails not created when configured outside of root

### ISSUE THREAD

**Issue by SquawkWoof** [Studio-42/elFinder#1971]
I need to have a configuration where elfinder can list files in a directory, but the user cannot upload or change them.  I have configured a **writable** thumbnails directory, but it doesn't seem to generate thumbnails.

**connector.php**

    $opts = array(
        'roots' => array(
            array(
                'driver'        => 'LocalFileSystem',
                'URL'           => 'non-writable-directory',
                'uploadDeny'    => array('all'),
                'uploadAllow'   => array(),
                'uploadOrder'   => array('deny', 'allow'),
                'accessControl' => 'access',
                'owner'         => true,
                'dirMode'       => 0755,
                'fileMode'      => 0644,
                'imgLib'        => 'auto',
                'path'          => '/absolute/path/non-writable-directory',
                'tmbPath'       => '/absolute/path/writable-thumbs-directory'
                'tmpURL'        => 'writable-thumbs-directory'
                'tmbPathMode'   => 0777,
                'tmpPath'       => '/absolute/path/temp-directory'
            )
        )
    );

I've double and triple checked that the thumbnail and temp paths are, in fact, writable.  I've checked the directory contents by hand and there are **no** thumbnails present.

If the `path` is writable and the thumbs directory is inside it, I get thumbnails.

**Comment by nao-pon** [comment]
@SquawkWoof If the setting of the path is correct, I guess it restricted by PHP setting "open_basedir".

**Comment by SquawkWoof** [comment]
@nao-pon I should clarify, the path is still inside the site's document root.  I'm not seeing any `open_basedir` errors in the server's PHP error log with `E_ALL`.

**Comment by nao-pon** [comment]
Umm... I'm not sure. Can you debug of `createTmb()` of class elFinderVolumeDriver?

**Comment by dleffler** [comment]
I've had issues in the past with using different test (windows) and production (Linux) servers. You may need to change the '/' in all paths to DIRECTORY_SEPARATOR like this
``` php
'tmbPath'         => BASE . 'tmp' . DIRECTORY_SEPARATOR . 'elfinder',

**Comment by SquawkWoof** [comment]
@nao-pon: I added some logging to the `createTmb()` method, it appears it's not even being called (the log is empty)

@dleffler: it's in a Linux environment.  The directory separator is correct, and I've `stat`ed the paths on the server to ensure they're present.

**Comment by SquawkWoof** [comment]
`tmbURL` needs to be set in the connector configuration.

**Comment by donShakespeare** [comment]
@SquawkWoof have you tested this with multiple roots?
