### ISSUE TITLE
Feature: Add driver id prefix to connector option

### ISSUE THREAD

**Issue by donShakespeare** [Studio-42/elFinder#1974]
`elfinder.html#elf_l1_XA` //default is 'elf_' + `l` +' _...'

Sometimes a plugin will change the prefix:
`elfinder.html#elf_fls1_XA` // changed to `fls` by e,g Barryvdh flysystem
```php
class Driver extends elFinderVolumeDriver
{
     protected $driverId = 'fls';
```

What would be great is an `id_prefix`
```php
            $opts = array( 
                'driver'         => 'LocalFilesystem',
                'id'               => generated(),
                'id_prefix'    => 'fls', //or back to  'l' //feature
```

**Comment by donShakespeare** [comment]
Right, I succeeded in doing this. Maybe this is the correct way, and this is not a feature or issue at all.
```php
class elFinderVolumeFlysystem extends \Barryvdh\elFinderFlysystemDriver\Driver {
    protected $driverId = 'l';
}
```

**Comment by nao-pon** [comment]
@donShakespeare OK. I'll make an option `driverId` so that it can be specified more easily.

**Comment by nao-pon** [comment]
Done, Thanks! 👍

**Comment by donShakespeare** [comment]
Works perfectly! Thanks.
