### ISSUE TITLE
after upload file reload directory

### ISSUE THREAD

**Issue by SkyTaurus** [Studio-42/elFinder#1976]
After upload file i need get additional data from server.
I need event in connector to get data.
Now i use code for existing files:
`
'bind' => 'open ' => ['addExtra']
`
I need a event after upload.

**Comment by nao-pon** [comment]
@SkyTaurus What about
```php
'bind' => [ 'open upload' => ['addExtra'] ]
```
```php
functioin addExtra($cmd, $result, $args, $elfinder, $volume) {
    if ($cmd === 'open' || ! empty($result['added'])) {
        // your job
    }
}
```

**Comment by SkyTaurus** [comment]
In which field should I return additional parameters? I tried -$result['added'] and $result['files'] they do not come.

**Comment by nao-pon** [comment]
Here is a related issue, see #1808.

**Comment by nao-pon** [comment]
Sorry, There was a mistake in the previous comment.

Please change `$result` to `&$result`. (I edited previous comment)

And set `$result['sync'] = 1;` to refresh cwd.

**Comment by SkyTaurus** [comment]
Thanks
