### ISSUE TITLE
How to do callback when toolbar has been rebuilt/refreshed

### ISSUE THREAD

**Issue by donShakespeare** [Studio-42/elFinder#1978]
When moving from Volume to Volume (of different drivers), the menus (toolbar etc) will refresh to accommodate whatever the `commands` you have enabled for this or that volume.

The Problem!
I have the same toolbars on all roots ...
I have some jQuery tweaks on the toolbar div: I added dynamic username, and added new classnames to certain button groups.
![image](https://cloud.githubusercontent.com/assets/5103329/25276399/ea5716c2-264e-11e7-9b8d-002a9f99d041.png)

I lose all my toolbar tweaks when the toolbar is rebuilt, i.e when I click another Driver volume.
But if there was a callback fired each time the toolbar is refreshed, I could re-run my taking function to fix the issue.

![image](https://cloud.githubusercontent.com/assets/5103329/25276451/252f43aa-264f-11e7-9434-ad69d1c9a506.png)

**Comment by nao-pon** [comment]
@donShakespeare You can catch toolbar refresh event by elFinder event `toolbarload`.

```javascript
fm.bind('toolbarload', function() {
    // add your changes
    // .....
    // trigger `uiresize` If the height of the toolbar changes
    fm.trigger('toolbarload').trigger('uiresize');
});
```

**Comment by donShakespeare** [comment]
Perfect. This official way is best. Now I am going to learn all the other events
https://github.com/Studio-42/elFinder/issues/1972#issue-222624708

**Comment by donShakespeare** [comment]
Oops, @nao-pon this fails for the Recycle Group.

For some reason I lose my toolbar because the `toolbarload` means nothing to the Recycle section
I have to put that logic in `load` and some how find a way to prevent the script from firing every time a `load` is made.
