### ISSUE TITLE
errUploadTotalSize

### ISSUE THREAD

**Issue by dennisfair** [Studio-42/elFinder#1981]
How can I solve this issue? I have to upload two files, one is 175MB, other one 1.5GB - thought there was no restriction on this matter.
![unbenannt](https://cloud.githubusercontent.com/assets/27910110/25310999/5427569c-27f4-11e7-8544-a155a2b9b850.JPG)

**Comment by nao-pon** [comment]
@dennisfair Perhaps PHP settings `memory_limit` or `post_max_size` values are less than the `upload_max_filesize` value.
