### ISSUE TITLE
Get logged out from my App after elFinder window has been opened.

### ISSUE THREAD

**Issue by marcelwirtz** [Studio-42/elFinder#1984]
Hey, 
i try to secure the connector a bit in my backend system. I use a self written session handler for my backend which stores the session data in a mysql table.

As soon as i include my session handler into the connector php file to check if a user is actual logged in into the backend, my session seems to be cleared and if i switch to another page in my backend i get logged out.

When i logged in, i can see my session data in the mysql table, after opening the elFinder window i have my session data + the elFinder session data, but if i switch the page the session data is empty.

It works if i don't include my session handler to the elFinder connector, but without that i cannot secure it to work only with a logged in user.

Is it possible elFinder does not deletes only his own data from the session?

EDITED: I have tested to implement the elFinderSessionInterface into my session handler, and set it to the options but it does not help.

Kind regards and thanks for advice,
Marcel

**Comment by nao-pon** [comment]
@marcelwirtz elFinder handles `$_SESSION` directly only in the elFinderSession class (elFinderSession.php). Also, elFinder does not touch about session variable members unknown to elFinder.

However, in order to support multi-access, elFinder closes sessions early during command execution, so there is a possibility of improving by saving your session data before executing elFinder connector.

**Comment by marcelwirtz** [comment]
@nao-pon Thanks for answering, i took a look into the elFinderSession.php and in the close function elFinder seems to restore the previous value if i get this right. But in line 68 shouldn't it be

`$_SESSION = $this->prevVal;`
instead of
`$this->prevVal = $_SESSION;`

if i change if and put this statement before the session_write_close(); function it works for me.

Or is it a thought mistake on my side? 😄 

Kind regards,
Marcel

**Comment by nao-pon** [comment]
My commitment (da0ee16b2768935926b6626c7a10d1b5009557cf) may have been wrong.

Change in line 66 of elFinderSession.php
```php
if ($this->started && $this->prevVal !== $_SESSION) {
```
to
```php
if ($this->started) {
```
It may be solved by this one change. Could you test it?

**Comment by marcelwirtz** [comment]
Tested it only with the change you advised, but it did not work.

I think you have to restore the $_SESSION variable before you close the session like in the snipped above..

**Comment by nao-pon** [comment]
If restore the $_SESSION variable, elFinder session data will not be saved. Perhaps the database column size is too small?

**Comment by marcelwirtz** [comment]
No, it's a text field and i can see the elFinder data in there after i opened it.

**Comment by nao-pon** [comment]
I checked with next simple test case.
```php
<?php

session_start();
if (empty($_SESSION['mySessionData'])) {
	$_SESSION['mySessionData'] = time();
}
$mySessionData = $_SESSION['mySessionData'];

$opts = array(
	'bind' => array(
		'open' => array(function($cmd, &$result) {
			global $mySessionData;
			$result['myDebug'] = $mySessionData;
		}),
	),
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '../files/',                 // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
		)
	)
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```
In this case, the value of $_SESSION['mySessionData'] is retained.

Could you please re-check your session handler?

**Comment by daniluski** [comment]
Hi, I have the same problem, did get someone a solution to it?

**Comment by marcelwirtz** [comment]
I sticked with my solution above that time

**Comment by santaclaus21** [comment]
I have the same problem. I have updated from 2.1.5 (2.1 Nightly: 417f845) to 2.1.61 (via composer now, v. 2.1.61 (2.1-src Nightly: 1733024) and after open elFinder in popup, my session data in parent window are destroyed. CRY...
