### ISSUE TITLE
Browser hangs on opening folder

### ISSUE THREAD

**Issue by axelocz** [Studio-42/elFinder#1986]
We are experiencing a strange issue with 2.1.23 where the browser would hang with elFinder showing opening folder. This happens quite randomly both on browser window refresh and the reload button. When this happens the browser will keep consuming CPU until the process is killed.
We are using our own custom backend which we just upgraded to match the 2.1 API. Any ideas are more then welcome.

**Comment by nao-pon** [comment]
@axelocz What about [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip)?

**Comment by axelocz** [comment]
Checked the server side logs and it hangs hard = no subsequent requests are running at all. Basically it seems like if it was having issues to process the server response and gets stuck in some odd loop. We do have another background XHR requests on the page that are being called every 10 seconds and those keep coming so it's clearly not killing the browser thread completely just taking up a lot of resources with no real result. I wonder if it might have something to do with the tree syncing and the data we are sending from our backend although we've been running 2.0 for ages and 1.x before that with no similar problems (but again the API changed over time and maybe we have something a bit off in our 2.1 implementation).

**Comment by nao-pon** [comment]
There was a part to worry about, so I tried to fix it. Please try it with the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).``

**Comment by axelocz** [comment]
Hi, this build behaves exactly the same.

**Comment by axelocz** [comment]
Maybe the server response will give you a clue about what may be wrong. The same response works for initial load but will hang the browser when refreshing. [elfinder_server-resp.txt](https://github.com/Studio-42/elFinder/files/960800/elfinder_server-resp.txt)

**Comment by nao-pon** [comment]
First, from the point I noticed. It is necessary to return the value of `api` in the response of the initial request.

- https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#open

**Comment by axelocz** [comment]
Hi, for initial request the API is present. see file for the initial call response
[elfinder_server-resp.txt](https://github.com/Studio-42/elFinder/files/960921/elfinder_server-resp.txt)

**Comment by nao-pon** [comment]
OK, go next. Object `tree` is not needed.

**Comment by axelocz** [comment]
Tree dumped, no change.  Note that when the "refresh" button in elfinder is used the tree always disappears and causes the browser to hang - this has been the case even before the tree object has been removed. Also posting the response for the reload cmd
[elfinder_server-resp-reload.txt](https://github.com/Studio-42/elFinder/files/960997/elfinder_server-resp-reload.txt)

[elfinder_server-resp-simple.txt](https://github.com/Studio-42/elFinder/files/960988/elfinder_server-resp-simple.txt)

**Comment by nao-pon** [comment]
I checked with next simple test script, but there was no problems.

**test.php**
```php
<?php
if (! empty($_GET['init'])) {
	$file = 'elfinder_server-resp-simple.txt';
} else {
	$file = 'elfinder_server-resp-reload.txt';
}
readfile($file);
```

- set elFinder client option `url` to 'test.php';
- open elFinder
- trigger command `reload`

That's no problem.

**Comment by axelocz** [comment]
Could it be cause by the jquery version we are using? We will try to figure out if there is possibly any conflict with Kendo UI or other scripts on page.

**Comment by nao-pon** [comment]
I think that there is no problem if it is jQuery 1.8.0+. Please let me know if there is a correction to elFinder side.

**Comment by axelocz** [comment]
We are running 1.12.3 so it has to be ok from this standpoint. Just did some tests, try the following with the sample data - init, open folder, click on Home and then reload. At one point cmd parents is called and it seems that the crash is related to that call.

**Comment by nao-pon** [comment]
Please inform me of all JSON responses from initial request to hangs to reproduce in my environment.

**Comment by axelocz** [comment]
Hi, i have prepared a sequence that always crashes my browser:
1) init
2) select folder Jakub from the tree panel
3) select Home from the tree panel
4) click reload button in elFinder
[4-reload-home.txt](https://github.com/Studio-42/elFinder/files/963583/4-reload-home.txt)
[3-open-home.txt](https://github.com/Studio-42/elFinder/files/963581/3-open-home.txt)
[2-open-jakub.txt](https://github.com/Studio-42/elFinder/files/963582/2-open-jakub.txt)
[1-init.txt](https://github.com/Studio-42/elFinder/files/963584/1-init.txt)

**Comment by nao-pon** [comment]
3-open-home.txt data invalid.

- Self hash is specified in the phash parameter of the cwd object.
- The files object does not contain the data of the Home directory.

**Comment by nao-pon** [comment]
I took measures to prevent infinite loops with unauthorized response data in elFinder. So close this issue. Please fix so that your backend connector will send the correct data.

Thanks!
