### ISSUE TITLE
Elfinder with mysql

### ISSUE THREAD

**Issue by ShinJii89** [Studio-42/elFinder#1987]
Hi,

How to configure elfinder to working with mysql like I want to, here's example:

1. I have some lessons with unique IDs
2. When I go to lesson ID 2 I want that it read files from specific folder assigned to this lesson
3. When I add files I want that it will connect to mysql and add this record with that lesson's unique ID  - how to do this?

**Comment by nao-pon** [comment]
@ShinJii89 There is similar issue #1808.
