### ISSUE TITLE
Changing delete function.

### ISSUE THREAD

**Issue by Greendeviate** [Studio-42/elFinder#1988]
I have seen a couple different issues about adding a Recycle Bin but do not think I have seen the idea of changing the delete function to just move the file to a certain directory and was wondering how possible it would be in trying that? 
 I have seen this in "elFinderVolumeLocalFileSystem.class" but am Unsure of how I would change it to just move the file instead of removing.
`		
	/**
	 * Remove file
	 *
	 * @param  string  $path  file path
	 * @return bool
	 * @author Dmitry (dio) Levashov
	 **/
	protected function _unlink($path) {
		$ret = unlink($path);
		$ret && clearstatcache();
		return $ret;
	}

	/**
	 * Remove dir
	 *
	 * @param  string  $path  dir path
	 * @return bool
	 * @author Dmitry (dio) Levashov
	 **/
	protected function _rmdir($path) {
		$ret = rmdir($path);
		$ret && clearstatcache();
		return $ret;
	}`

**Comment by nao-pon** [comment]
@Greendeviate I started to develop #1065. Please wait that function. Thanks!

**Comment by nao-pon** [comment]
Closes via 1f1e6ea384bee66f8641c921441b38a9ade85644
