### ISSUE TITLE
ignore specified files

### ISSUE THREAD

**Issue by mmickelson** [Studio-42/elFinder#1989]
Is there a way to ignore certain files or patterns? For example, the .gitignore shows up in the directory contents but I don't want it to show. If this option isn't available yet, perhaps an option to create a blacklist or whitelist array of file patterns could be added.
`'blacklist' => [".gitignore","*.zip"] // don't show these types`
OR
`'whitelist' => ["*.png","*.jpg","*.jpeg"] // only show these types`

**Comment by donShakespeare** [comment]
I think you might be in luck ...
`[{"pattern":"/.tmb|.gitignore|*.zip/","hidden":true}]`

**elFinder Attributes**
https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#attributes
