### ISSUE TITLE
sometimes get 500 error

### ISSUE THREAD

**Issue by SkyTaurus** [Studio-42/elFinder#1990]
in connector i have this code
`  'bind' => ['mkfile rename duplicate upload rm paste ' => [ [$fileSync, 'sync'] ],
               'open upload' => [ [$fileSync, 'addExtra'] ],
                ],
`

and sometimed i get error
"PHP message: PHP Fatal error:  Uncaught TypeError: Argument 5 passed to leafFileSync::addExtra() must be an instance of elFinderVolumeDriver, boolean given, called in /var/XXXX/frontend/web/assets/global/plugins/elFinder/php/elFinder.class.php on line 839 and defined in /var/XXXX/frontend/web/assets/global/plugins/elFinder/php/sync.php:10
Stack trace:
#0 /var/XXXX/frontend/web/assets/global/plugins/elFinder/php/elFinder.class.php(839): leafFileSync->addExtra('open', Array, Array, Object(elFinder), false)
#1 /var/XXXX/frontend/web/assets/global/plugins/elFinder/php/elFinderConnector.class.php(155): elFinder->exec('open', Array)
#2 /var/XXXX/frontend/web/assets/global/plugins/elFinder/php/connector.minimal.php(319): elFinderConnector->run()
#3 {main}
  thrown in /var/XXXX/frontend/web/assets/global/plugins/elFinder/php/sync.php on line 10" while reading response header from upstream, client: 192.168.1.1, server: , request: "GET /assets/global/plugins/elFinder/php/connector.minimal.php?cmd=open&target=&init=1&tree=1&_=1493651212539 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "XXXXX", referrer: "XXXX"

if i commented line
 ``  'bind' => ['mkfile rename duplicate upload rm paste ' => [ [$fileSync, 'sync'] ],
     //          'open upload' => [ [$fileSync, 'addExtra'] ],
                ],
``

and refresh page and uncomment my code worked fine

**Comment by nao-pon** [comment]
This problem seems to be due to the function you specified for bind. It can not be solved here.

**Comment by SkyTaurus** [comment]
no, if i set wrong password to connect to ftp i got message "debug":["Driver \"elFinderVolumeFTP\" : Unable to login into 192.168.1.1"]" - its correct message
if i set correct password i got error.
in file elFinder.class.php line 840
`if (call_user_func_array($handler,array($cmd, &$result, $args, $this, $dstVolume))) {`

$dstVolume  = false

**Comment by nao-pon** [comment]
Oh, OK. I got it. I think that it has been fixed by [the previous correction](c2d14aac2def1b260d607f7bcf6778845b686ef0). Please try the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by SkyTaurus** [comment]
i got 500 error.
param $args in function exec
array(6) {
  ["target"]=>
  string(0) ""
  ["tree"]=>
  string(1) "1"
  ["init"]=>
  string(1) "1"
  ["mimes"]=>
  string(0) ""
  ["compare"]=>
  string(0) ""
  ["debug"]=>
  string(0) ""
}

**Comment by nao-pon** [comment]
If the target volume can not be detected, $dstVolume became to false. In callback, it is necessary to correspond to the case of false.

**Comment by SkyTaurus** [comment]
I have only one volume 

`array(3) {
  ["debug"]=>
  bool(true)
  ["bind"]=>
  array(2) {
    ["mkfile rename duplicate upload rm paste "]=>
    array(1) {
      [0]=>
      array(2) {
        [0]=>
        object(leafFileSync)#1 (1) {
          ["enableLog":"leafFileSync":private]=>
          bool(true)
        }
        [1]=>
        string(4) "sync"
      }
    }
    ["open upload"]=>
    array(1) {
      [0]=>
      array(2) {
        [0]=>
        object(leafFileSync)#1 (1) {
          ["enableLog":"leafFileSync":private]=>
          bool(true)
        }
        [1]=>
        string(8) "addExtra"
      }
    }
  }
  ["roots"]=>
  array(1) {
    [0]=>
    array(17) {
      ["id"]=>
      string(2) "14"
      ["driver"]=>
      string(3) "FTP"
      ["alias"]=>
      string(10) "my channel"
      ["host"]=>
      string(12) "192.168.1.1"
      ["user"]=>
      string(7) "userftp"
      ["pass"]=>
      string(7) "userftp"
      ["mode"]=>
      string(7) "passive"
      ["port"]=>
      string(2) "21"
      ["systemRoot"]=>
      string(18) "/home/userftp/ftp/"
      ["path"]=>
      string(1) "/"
      ["tmpPath"]=>
      string(4) "/tmp"
      ["imgLib"]=>
      string(4) "auto"
      ["tmbPath"]=>
      string(1) "/"
      ["tmbSize"]=>
      int(640)
      ["uploadAllow"]=>
      array(1) {
        [0]=>
        string(3) "all"
      }
      ["uploadOrder"]=>
      array(2) {
        [0]=>
        string(4) "deny"
        [1]=>
        string(5) "allow"
      }
      ["accessControl"]=>
      string(6) "access"
    }
  }
}

`

**Comment by nao-pon** [comment]
@SkyTaurus This cause was found and fixed. Thanks!
