### ISSUE TITLE
Improve trash feature

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1991]
Finally its working☺☺☺

1. massage box for confirm move files to trash or delete it. 
2. I saw that inside of trash you can create new folders (its unnecessary). 
3. Copy function is unnecessary & it's function to restore & cut (use fix folder structure to restore it).

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM 

1. You can delete it without going through the trash by `Ctrl + Delete` or Delete icon in the context menu.
2. It is necessary to remember the folder tree.
3. I implemented the restore function. In Trash Volume, the copy command is replaced with the restore command. Also, the cut command is left for when the restore destination can not be detected.

**Comment by CodeLyokoXtEAM** [comment]
there is little bugs in drag & drop.

1. user can drag & drop file into any path in trash.(but only this happen first or second drag & drop)
I think user drag file any path in trash that file must go to original deleted path.

![image](https://cloud.githubusercontent.com/assets/18566890/25670825/927b2a86-304b-11e7-83ee-9c78f8fc157b.png)

2. also press 'ctrl' & drag file to trash it not deleted & copy file to trash.

![image](https://cloud.githubusercontent.com/assets/18566890/25671050/4b5e4a38-304c-11e7-8627-61eee4de5014.png)

**Comment by nao-pon** [comment]
OK, Try to disable dropping in the trash.
