### ISSUE TITLE
Restore function bug

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#1993]
If you restore file that same name still available file in volume its overwrite the restored file.

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks! However, when restoring folders, Do not check recursively the folders.

**Comment by CodeLyokoXtEAM** [comment]
I think its rename to 'filename_restored_1'

**Comment by nao-pon** [comment]
> Folders don't want to rename.

I think so... I'll try it.
