### ISSUE TITLE
How to remove systax php when add, edit file

### ISSUE THREAD

**Issue by thanhansoft** [Studio-42/elFinder#1995]
Hi admin,
I want to remove systax <? ?> of php when guest create file, edit file. 
Please help me

**Comment by nao-pon** [comment]
@thanhansoft There is an option [`disabled`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#disabled) in connector roots options. However, since elFinder does not have user control function, it needs to be combined with some kind of login system.

**Comment by thanhansoft** [comment]
Please help me file name.php for saved file. I want to customize it

**Comment by nao-pon** [comment]
If you read and installed the "install" page of the wiki, it is `php / connector.minimal.php`. Other than that, we do not know.
