### ISSUE TITLE
Dropping file on elFileManager from dot net ListView not working

### ISSUE THREAD

**Issue by Jahedur** [Studio-42/elFinder#1997]
I'm trying to allow dragging files from a windows application into a web page that hosts elFinder. The web page is capable of accepting dropped files coming from windows explorer. But when I try to drag a file from my windows app (.net) on the web page, it does not recognize and shows cross (X) sign.

I have set below lists with valid data in the DataObject class:

`    [0]: "Preferred DropEffect"
    [1]: "Shell IDList Array"
    [2]: "FileDrop"
    [3]: "FileNameW"
    [4]: "FileName"`

This works fine when I drop the file on windows explorer. I have built another test form that shows above data formats are present in the DragEventArgs parameter in the DragDrop event.
Can anyone please let me know if I need to set the data in the DataObject in a different format?
FYI: The listview is in a windows form within an Outlook 2016 vsto addin. I know dragging outlook mail/attachment are not recognized on the browsers because of the special data formats. But, my winform within the addin just sets the data format so that anyone can recognize. I'm not sure what I am doing wrong.

**Comment by nao-pon** [comment]
@Jahedur elFinder catch the drop data in [js/commands/upload.js:197-214](https://github.com/Studio-42/elFinder/blob/master/js/commands/upload.js#L197-L214).  Would you explain which data should be caught here?
