### ISSUE TITLE
Fix composer install

### ISSUE THREAD

**Issue by Ange7** [Studio-42/elFinder#1998]
I think composer installation is not up to date 

```
# composer require pear/auth #
Using version ^1.6 for pear/auth
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing pear/auth (1.6.4): Downloading (failed)    Failed to download pear/auth from dist: The "https://api.github.com/repos/hostnet/Auth/zipball/c8830e1223e1067461a7bd6cd0560ea394de54d2" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing pear/auth (1.6.4): Cloning c8830e1223
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is xxxxx
Are you sure you want to continue connecting (yes/no)? yes

Installation failed, reverting ./composer.json to its original content.

  [RuntimeException]
  Failed to clone https://github.com/hostnet/Auth.git via https, ssh protocols, aborting.
  - https://github.com/hostnet/Auth.git
    Cloning into '/home/guest/[..]/vendors/elfinder/vendor/pear/auth'...
    remote: Invalid username or password.
    fatal: Authentication failed for 'https://github.com/hostnet/Auth.git/'
  - git@github.com:hostnet/Auth.git
    Cloning into '/home/guest/[...]/vendors/elfinder/vendor/pear/auth'...
    Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
```

and 

```
# composer require dropbox-php/dropbox-php dev-master #
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing dropbox-php/dropbox-php (dev-master de6495d): Cloning de6495d56d
Package dropbox-php/dropbox-php is abandoned, you should avoid using it. Use dropbox/dropbox-sdk instead.
```

**Comment by nao-pon** [comment]
@Ange7 Yes, dropbox-php/dropbox-php(Dropbox API  v1) will be unavailable soon and will be fixed.

**Comment by nao-pon** [comment]
I done. Thanks!

**Comment by Ange7** [comment]
> guest@josephine:~/CRM/public/vendors/elfinder$ composer require dropbox/dropbox-sdk
> Using version ^1.1 for dropbox/dropbox-sdk
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 1 install, 0 updates, 0 removals
>   - Installing dropbox/dropbox-sdk (v1.1.7): Downloading (100%)
> Package dropbox-php/dropbox-php is abandoned, you should avoid using it. Use dropbox/dropbox-sdk instead.
> Writing lock file
> Generating autoload files

**Comment by nao-pon** [comment]
To use the new Dropbox driver please install `kunalvarma05/dropbox-php-sdk`.

`composer require kunalvarma05/dropbox-php-sdk`

Then make the following settings with the connector.

```php
elFinder::$netDrivers['dropbox2'] = 'Dropbox2';
// Dropbox2 Netmount driver need next two settings. You can get at https://www.dropbox.com/developers/apps
// AND reuire regist redirect url to "YOUR_CONNECTOR_URL?cmd=netmount&protocol=dropbox2&host=1"
define('ELFINDER_DROPBOX_APPKEY',    '');
define('ELFINDER_DROPBOX_APPSECRET', '');

```

**Comment by Ange7** [comment]
Doesn't work 

`guest@josephine:~/CRM/public/vendors/elfinder$ composer require kunalvarma05/dropbox-php-sdk
Using version ^0.2.0 for kunalvarma05/dropbox-php-sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package dropbox-php/dropbox-php is abandoned, you should avoid using it. Use dropbox/dropbox-sdk instead.
Generating autoload files
guest@josephine:~/CRM/public/vendors/elfinder$
`

**Comment by nao-pon** [comment]
Do not need dropbox-php/dropbox-php.
`composer remove dropbox-php/dropbox-php`

**Comment by Ange7** [comment]
it works ! thx

**Comment by ProgrammerAuditore** [comment]
Hello, I need help connecting to dropbox
