### ISSUE TITLE
[QUESTION] How to catch elFinder events

### ISSUE THREAD

**Issue by JuanWilde** [Studio-42/elFinder#2001]
I'm trying to catch elFinder events, for example, when an user upload a file, download it and things like that. I could do it inside controllers, but I don't want to do it since they are in `vendor` folder.

How can I catch an event to create a Log file with that info?

Thanks in advance!

**Comment by nao-pon** [comment]
@JuanWilde Have you read the [Wiki bind](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind) entry?

**Comment by DimasOdessa** [comment]
Hi!
I have same issue, and it doesn't' work for me. I was tried put my function into 
**vendor\barryvdh\laravel-elfinder\src\Connector.php**
And add bind to 
**config\elfinder.php** 
and to 
**vendor\barryvdh\laravel-elfinder\config\elfinder.php**
I placed like this - http://ipic.su/img/img7/fs/kiss_125kb.1494895645.png
and anyway not work =(
Help me please.

**Comment by JuanWilde** [comment]
Yes. And after that I wrote the question above. I mean, I have a controller who loads the view with elFinder instance.

            var asset_id = id;
            $(function () {
            var elf = $('#elFinderDiv').elfinder({
                customData: {
                    _token: '{{ csrf_token() }}',
                    _path: '{{ Config::get('path.to.folder') . '/' . $item->getId() }}',
                    _alias: asset_id,
                },
                rememberLastDir: false,
                useBrowserHistory: false,
                resizable: false,
                defaultView: 'list',
                url: '{{ route("elfinder.connector") }}',
                height: 300,
                width: '100%',
                uiOptions: {
                    toolbar: [
                        ['upload'], ['back', 'forward'], ['mkdir'], ['copy', 'paste', 'rm'], ['download'], ['resize']
                    ]
                },
            }).elfinder('instance');
        });


But my issue is that I don't know where to place the callback function in my laravel project to catch events.

**Comment by nao-pon** [comment]
> But my issue is that I don't know where to place the callback function in my laravel project to catch events.

About laravel, you may not get an answer here. Ask in the [barryvdh/laravel-elfinder](https://github.com/barryvdh/laravel-elfinder) or community of laravel.

**Comment by JuanWilde** [comment]
Ok. Thanks for your time again :)
