### ISSUE TITLE
Data Empty / Data is not JSON using AutoResizePlugin

### ISSUE THREAD

**Issue by ratmalwer** [Studio-42/elFinder#2002]
SKIP THIS -> SUDDENLY IT WORKS WITH SAME PARAMETERS ??? !!!

My elfinderconfiguration is working.
Now I tryed to use the AutoResizePlugin I get this error.
(Data Empty with debug off / Data is not JSON with debug on).

Here my configuration: 

$opts = array(
	//'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',     
			'path'          => '../../objekte',              
			'URL'           => 'http://mydomain/objekte',
			'uploadDeny'    => array('all'),            
			'uploadAllow'   => array('image', 'text/plain','video/mp4','audio/mpeg','application/pdf'),
			'uploadOrder'   => array('deny', 'allow'),  
			'accessControl' => 'access')
	),
// Autoresize test	
    'bind' => array(
        'upload.presave' => array(
            'Plugin.AutoResize.onUpLoadPreSave'
        )
    ),
    'plugin' => array(
        'AutoResize' => array(
        'enable' => true,
        'maxWidth'  => 1200,
        'maxHeight'  => 1200,
        'quality' => 95
        )
    )
);

I am using elFinder (2.1.21)
Any hints?

**Comment by nao-pon** [comment]
@ratmalwer It is probably the same problem as #1994. Can you catch anything about PHP errors?

**Comment by ratmalwer** [comment]
@nao-pon  As I comented in Top-Line of this topic -> suddenly it worked. The only thing I did was adding the Watermark-plugin as I found it in the example. After that worked I removed it again and it still worked. The only faint explanation I have is, that I copyed a nonprintable charakter from the expample I found in the web???

**Comment by nao-pon** [comment]
Okay, it may be because the Web server was unstable???, I'll close this Issue.
