### ISSUE TITLE
Not work in firefox normal mode

### ISSUE THREAD

**Issue by emitchan** [Studio-42/elFinder#2003]
firefox V53.0.2  Blank and sometime shown "Unable to connect to backend. Backend not found."
ReferenceError: jQuery is not defined[更多資訊]  elfinder.min.js:25:1
TypeError: elFinder is undefined[更多資訊]  main.default.js:43:4

Work on firefox private mode perfectly.
chrome ok
opera ok
safari ok
IE11 ok
edge ok

**Comment by nao-pon** [comment]
@emitchan There is no problem for me. Please try clearing browser cache and data storage.

**Comment by emitchan** [comment]
Thank you! let me try now.

**Comment by nao-pon** [comment]
I checked your site with Firefox 53.0.2(64bit) that was no problem.

Screen shot -> http://oc.emit.hk/files/image.png

**Comment by emitchan** [comment]
Dear noa-pon
Thank you for your helping. But I still facing the problem.
By the way, I had checked with mobile browser, It's seen that the same problem
Only work on Android incognito tab
Only work on mobile firefox private tab.
Anway, thank you for your helping!
Emit Chan

**Comment by emitchan** [comment]
Problem solved.
Since I have upgrade form 2.0 to 2.1.23
But my server buffered elfinder.min.js 2.0 version then sent to firefox.
I wonder why other browser read 2.17 version of elfinder.min.js
but firrefox always read the buffered version 2.0 js file.
Finally, deleted virtual host then setup again at my server.
I seem everything OK.
Thank you for supporting.
