### ISSUE TITLE
Sanitize Norwegian characters Æ Ø Å æ ø å in file name

### ISSUE THREAD

**Issue by shinokada** [Studio-42/elFinder#2004]
Is there any way to sanitize Norwegian characters in a uploaded file name? I checked [Sanitizer plugin](https://github.com/Studio-42/elFinder/blob/2.1/php/plugins/Sanitizer/plugin.php), but it seems it can't be used for Norwegian.

**Comment by nao-pon** [comment]
@shinokada I'll add an option to the Normalizer plugin that convert umlauts with their closest 7 bit ascii equivalent.

**Comment by nao-pon** [comment]
I done. You can try it with [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip). Thanks!
