### ISSUE TITLE
Wrong path to files in filemanager in chamilo

### ISSUE THREAD

**Issue by harryarnold79** [Studio-42/elFinder#2012]
Hi there

I am using this in Chamilo LMS and I can upload files no problem but the problem occurs when I use the filemanager to insert a file. I can see the path that it is showing the wrong path. The path should be www.mydomain.com/chamilo/....  but the path is going to www.mydomain.com  without the chamilo directory.

Where can I change the path so that it goes to the right address?

Thanks

**Comment by nao-pon** [comment]
@harryarnold79 Please check volume roots option [`URL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#url). Probably that configuration is wrong.

**Comment by harryarnold79** [comment]
@nao-pon I tried that but it didn't seem to do anything.

As you can see from the picture attached, the link at the bottom shows https://mydomain.com/courses/... 
but it should be https://mydomain.com/**chamilo**/courses/.....
Could you or anyone tell me where I can change this path and which file exactly especially if anyone is familiar with chamilo.

Thanks
![image](https://cloud.githubusercontent.com/assets/28757625/26248696/09564a70-3cac-11e7-8b23-55ec45ff328c.png)

**Comment by harryarnold79** [comment]
Actually I found the issue. It was in the chamilo configuration file. Thanks anyway
