### ISSUE TITLE
elFinder 2.1.x requires PHP 4 or above

### ISSUE THREAD

**Issue by alexandre51** [Studio-42/elFinder#2014]
Although the README file states that PHP 2 is the minimum required  ( "PHP 5.2+ (Recommend PHP 5.4 or higher)", if you use PHP 5.3 you will get a syntax error in module connector.[minimal.]php, because of the following statement:

line 85: return basename($path)[0] === '.'

It seems that this way of referencing to a single character can only be used directly on returned value of a function from PHP 4.

So, if you want to use the latest version of elFinder and you still have PHP3, upgrade PHP or change the  above mentioned module to use an intermediate variable before the comparison  statement.

**Comment by nao-pon** [comment]
@alexandre51 I fixed. Thanks! 👍
