### ISSUE TITLE
How to fix the size of the crop  and can not be edited 

### ISSUE THREAD

**Issue by newbie7777** [Studio-42/elFinder#2016]
```
                                .resizable({
                                    containment: B,
                                    handles: "all"
                                }).draggable({
                                    handle: G,
                                    containment: K,
                                }), 
```
I try to fix 400x400 pixels to crop the photo without moving the table. But when I set a fixed size 
                        maxHeight: 400,
			maxWidth: 400,
			minHeight:399,
			minWidth: 399

The table itself broke, аnd it does not work. :(

**Comment by nao-pon** [comment]
@newbie7777 It is impossible at present. It is possible to extend the function to provide preset values, but do you need it?

**Comment by newbie7777** [comment]
Yes , yes, friend. I rellay like to be able to fix the size of cut.

**Comment by newbie7777** [comment]
You're a great brother!

**Comment by nao-pon** [comment]
Yep, Thanks! 👍
