### ISSUE TITLE
run elFinderVolumeMyLocalFileSystem in option Root

### ISSUE THREAD

**Issue by vahidalvandi** [Studio-42/elFinder#2018]
i have bellow elFinderVolumeMyLocalFileSystem 

`
class elFinderVolumeMyLocalFileSystem extends \elFinderVolumeLocalFileSystem
{

	protected function tmbname($stat) {
		$dir = $this->relpathCE($this->decode($stat['phash']));
		if (!is_dir($this->tmbPath.DIRECTORY_SEPARATOR.$dir)) {
			$dirs = explode(DIRECTORY_SEPARATOR, $dir);
			$target = $this->tmbPath;
			foreach($dirs as $_dir) {
				if (! is_dir($target . DIRECTORY_SEPARATOR . $_dir)) {
					mkdir($target . DIRECTORY_SEPARATOR . $_dir);
				}
				$target = $target . DIRECTORY_SEPARATOR . $_dir;
			}
		}
		return $dir . DIRECTORY_SEPARATOR . $stat['name']  ;
	}

	protected function gettmb($path, $stat) {
		if ($name = parent::gettmb($path, $stat)) {
			$name = str_replace('\\', '/', $name); // For windows server
			$name = str_replace('%2F', '/', rawurlencode($name));
		}
		return $name;
	}

	public function tmb($hash) {
		if ($name = parent::tmb($hash)) {
			$name = str_replace('\\', '/', $name); // For windows server
			$name = str_replace('%2F', '/', rawurlencode($name));
		}
		return $name;
	}
 

	function hashedName(&$path, &$name, $src, $elfinder, $volume) {
		$ext = '';
		if ($pos = strrpos($name, '.')) {
			$ext = substr($name, $pos);
		}
		$name = md5($name) . $ext; // With your preferred hashing method
	}
 
} `

this bellow function located in another function in other php file 

```

class ElfinderController extends Controller
{
  
    public function showConnector()
    {
		
		
        $roots = $this->app->config->get('elfinder.roots', []);
        if (empty($roots)) {
            $dirs = (array) $this->app['config']->get('elfinder.dir', []);
            foreach ($dirs as $dir) {
                $roots[] = [
                    'driver' => 'MyLocalFileSystem', // driver for accessing file system (REQUIRED)
                    'path' => public_path($dir), // path to files (REQUIRED)
                    'URL' => url($dir), // URL to files (REQUIRED)
                    'accessControl' => $this->app->config->get('elfinder.access') // filter callback (OPTIONAL)
                 ];
            }

            $disks = (array) $this->app['config']->get('elfinder.disks', []);
            foreach ($disks as $key => $root) {
                if (is_string($root)) {
                    $key = $root;
                    $root = [];
                }
                $disk = app('filesystem')->disk($key);
                if ($disk instanceof FilesystemAdapter) {
                    $defaults = [
                        'driver' => 'Flysystem',
                        'filesystem' => $disk->getDriver(),
                        'alias' => $key,
                    ];
                    $roots[] = array_merge($defaults, $root);
                }
            }
        }

        if (app()->bound('session.store')) {
            $sessionStore = app('session.store');
            $session = new LaravelSession($sessionStore);
        } else {
            $session = null;
        }

        $rootOptions = $this->app->config->get('elfinder.root_options', array());
        foreach ($roots as $key => $root) {
            $roots[$key] = array_merge($rootOptions, $root);
        }

        $opts = $this->app->config->get('elfinder.options', array());
        $opts = array_merge($opts, ['roots' => $roots, 'session' => $session]);

        // run elFinder
        $connector = new Connector(new \elFinder($opts));
        $connector->run();
        return $connector->getResponse();
    }

 
}

```

how i can call MyLocalFileSystem  in 
  'driver' => 'MyLocalFileSystem', // driver for accessing file system (REQUIRED)

??

**Comment by donShakespeare** [comment]
You are right, just use
`'driver' => 'MyLocalFileSystem'`

**Comment by vahidalvandi** [comment]
How should define class elFinderVolumeMyLocalFileSystem extends \elFinderVolumeLocalFileSystem 
to Identify?

i use mvc model laravel
