### ISSUE TITLE
[cmd:resize] conflict with the bootstrap.js

### ISSUE THREAD

**Issue by Nuvolect** [Studio-42/elFinder#2019]
When selecting an image, and the command Resize & Rotate, the dialog box no longer appears. The REST interface is quiet. It does not ask for a "file", "dim" or any command at all. Resize worked properly with this connector in earlier versions.

The API 2.1 document states:  

> To be able to resize the image, cdc record file must be specified and resize dim. resize must be in true dim and contain a line with dimensions of height and width (like "600x400"). If specified without resize dim resize the dialog will not work correctly.

There is no reference to "cdc record file" in the documentation. It is unclear what this is. Just guessing but it appears that earlier version of elFinder relied on the "dim" property of a file object. The object file provided includes a dim property with the accurate dimensions.

Guidance appreciated.

**Comment by nao-pon** [comment]
@Nuvolect The description about "cdc - dim" in the document is API 1, so API 2.0 or later is not necessary. I deleted the description earlier.

Which connector do you use?

**Comment by Nuvolect** [comment]
Java Android connector for 2.x
https://github.com/Nuvolect/SecureSuite-Android/tree/master/SecureSuite/src/main/java/com/nuvolect/securesuite/webserver/connector

**Comment by nao-pon** [comment]
No request is made by XHR at the time the resize dialog is opened. Is there a JavaScript error?

**Comment by Nuvolect** [comment]
Good call:

> Uncaught TypeError: Cannot read property 'classes' of undefined
    at String.<anonymous> (https://10.0.1.2:8002/js/jquery-ui.min.js:8:11128)
    at Function.each (https://10.0.1.2:8002/js/jquery-3.1.1.min.js:2:2865)
    at t.(anonymous function).(anonymous function)._resolveClassesValues (https://10.0.1.2:8002/js/jquery-ui.min.js:8:11094)
    at t.(anonymous function).(anonymous function)._resolveClassesValues (https://10.0.1.2:8002/js/jquery-ui.min.js:6:4499)
    at HTMLButtonElement.<anonymous> (https://10.0.1.2:8002/js/jquery-ui.min.js:8:9373)
    at Function.each (https://10.0.1.2:8002/js/jquery-3.1.1.min.js:2:2815)
    at r.fn.init.each (https://10.0.1.2:8002/js/jquery-3.1.1.min.js:2:1003)
    at String.<anonymous> (https://10.0.1.2:8002/js/jquery-ui.min.js:8:9205)
    at Function.each (https://10.0.1.2:8002/js/jquery-3.1.1.min.js:2:2865)
    at t.(anonymous function).(anonymous function)._initWidgets (https://10.0.1.2:8002/js/jquery-ui.min.js:8:8750)
(anonymous) @ jquery-ui.min.js:8
each @ jquery-3.1.1.min.js:2
_resolveClassesValues @ jquery-ui.min.js:8
(anonymous) @ jquery-ui.min.js:6
(anonymous) @ jquery-ui.min.js:8
each @ jquery-3.1.1.min.js:2
each @ jquery-3.1.1.min.js:2
(anonymous) @ jquery-ui.min.js:8
each @ jquery-3.1.1.min.js:2
_initWidgets @ jquery-ui.min.js:8
(anonymous) @ jquery-ui.min.js:6
refresh @ jquery-ui.min.js:8
(anonymous) @ jquery-ui.min.js:6
_enhance @ jquery-ui.min.js:8
(anonymous) @ jquery-ui.min.js:6
_create @ jquery-ui.min.js:8
(anonymous) @ jquery-ui.min.js:6
_createWidget @ jquery-ui.min.js:6
t.(anonymous function).(anonymous function) @ jquery-ui.min.js:6
(anonymous) @ jquery-ui.min.js:6
each @ jquery-3.1.1.min.js:2
each @ jquery-3.1.1.min.js:2
t.fn.(anonymous function) @ jquery-ui.min.js:6
open @ elfinder.full.js:23352
exec @ elfinder.full.js:23482
(anonymous) @ elfinder.full.js:10796
(anonymous) @ elfinder.full.js:10456
dispatch @ jquery-3.1.1.min.js:3
q.handle @ jquery-3.1.1.min.js:3

**Comment by Nuvolect** [comment]
I bumped jquery to 3.2.1 from 3.1.1 but no difference. 
Image preview pop-up works fine.

**Comment by Nuvolect** [comment]
It fails in Chrome, Safari and Firefox.  Here is the error in Firefox:
![screen shot 2017-05-24 at 11 05 25 am](https://cloud.githubusercontent.com/assets/19307825/26410364/03bebc1e-4071-11e7-8102-7da16f68fd66.png)

**Comment by nao-pon** [comment]
What about using jQueryUI 1.12.1?

**Comment by Nuvolect** [comment]
Looks like the same error:

![screen shot 2017-05-24 at 12 25 49 pm](https://cloud.githubusercontent.com/assets/19307825/26414142/3ba1a83e-407c-11e7-8186-ffaabcfb8862.png)

**Comment by nao-pon** [comment]
Not jQuery 1.12.1, JQuery**UI** 1.12.1.

Or, Have you loading any other JavaScript libraries?

**Comment by Nuvolect** [comment]
OK, JQueryUI 1.12.1 is now being loaded, same error.

List of all JS libraries:
    <script src="/js/jquery-3.2.1.min.js"></script>
    <script src="/js/jquery-ui.min.js"></script>
    <script src="js/elfinder.full.js"></script>
    <script src="/js/angular.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>

![screen shot 2017-05-25 at 1 19 41 pm](https://cloud.githubusercontent.com/assets/19307825/26461942/d90087aa-414c-11e7-9003-763a4a46dee2.png)

**Comment by nao-pon** [comment]
This is caused by conflicts with the bootstrap. Since there are similar issues in the past, I'll take measures on the elFinder side.

rel. #740, #1398, #1620

**Comment by nao-pon** [comment]
@Nuvolect Thanks! 👍
