### ISSUE TITLE
display issue, and field text doesn't work

### ISSUE THREAD

**Issue by Cyril6789** [Studio-42/elFinder#2021]
Hello,

I'm trying to integrate elfinder in my webside but I encounter some problems :

I use the next source :
`<script src=/js/elfinder.min.js></script>
 <script src=/js/i18n/elfinder.LANG.js></script>
                
<div id="elfinder"></div>

<script>
                    elFinder.prototype.loadCss('//studio-42.github.io/elFinder/demo/css/elfinder.min.css');
                    elFinder.prototype.loadCss('//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css');
                    
                    $('#elfinder').elfinder({url : '/php/connector.minimal.php'});                    
</script>`

But first, my display is not quite the same as the demo  : https://snag.gy/nRVkdE.jpg

And other big problem : my field text around the elfinder plugin doesn't work anymore..

I can type text, but the "space", "backspace", "return" keys doesn't work anymore.

you just must know I include elfinder in a purchased template. 

thank you for helping

**Comment by nao-pon** [comment]
There is no problems.

**Live demo**

- HTML & JavaScript - http://jsbin.com/wohisuq/edit?html,js
- Result View - http://output.jsbin.com/wohisuq

**Comment by Cyril6789** [comment]
Thank you for answer

Yes I know in this contexte elfinder working correctly, but I said I integrated itin a Full purschased Template.
And in this case, I suppose it conflicts with the CSS, or JS file of the Template and then, my field text doesn't work correctly et and my display is not correct as you can see here : https://snag.gy/nRVkdE.jpg

Thank you for helping

**Comment by nao-pon** [comment]
Please make sure 'css/theme.css' is loaded. There is an example "[elfinder.legacy.html](https://github.com/Studio-42/elFinder/blob/master/elfinder.legacy.html)". Please resolve conflicts with other CSS yourself. Please let me know if there is anything to fix on elFinder side.

**Comment by Cyril6789** [comment]
Thank you for answer, I Will check if my CSS file is correctly loader.

> Please resolve conflicts with other CSS yourself.

How can I do that ? There are no error JS in my console...

**Comment by nao-pon** [comment]
Perhaps, it is based on the CSS priority. Please check the other CSS you are loading to find out what is affecting elFinder.

**Comment by Cyril6789** [comment]
I'm sorry to re-open this post, but I have the same problem today and don't know how to fix it

you can see it in this page : 

http://dbtech.di67.fr/elfinder.html

Click to the search field and type something.. 
You won't be able to type space, or delete some letter...

Can you help me to know why I have this problem ?

Thx !

**Comment by nao-pon** [comment]
@Cyril6789 There is an error in require.js. Please refer to [elfinder.legacy.html](https://github.com/Studio-42/elFinder/blob/master/elfinder.legacy.html) and try not to use require.js.

**Comment by Cyril6789** [comment]
Thank you for answering, but i putten the line in wrong place, if I put it after all Js files include, it works better without any error, but still not the text field arround.

But I've a clue for this problem : 
I noticed that each key which doesn't work in arround text field is in reallity a ShortKey for ElFinder usage !
Like, "backspace" is a shortcut for browse the parent directory !
The "F5" (refresh button which doesn't work anymore) refresh in reallity the inside of ElFinder !!

So this probleme is not really a probleme ! It's juste because ElFinder Capture my Shortcut and use it for itselfes functionnalities !! 

So how can I disable this functionalities ?

**Comment by Cyril6789** [comment]
I found the solution !

in main Js just add "allowShortcuts: false" here

opts = {
	url : './templates/v4/assets/elfinder/php/connector.minimal.php', // connector URL (REQUIRED)
	lang: lang,                         // auto detected language (optional)
	**allowShortcuts: false**
},

And it works ! 

Thank you !
