### ISSUE TITLE
Browse ftp files and folders in elfinder

### ISSUE THREAD

**Issue by jasneet-bhatia** [Studio-42/elFinder#2023]
I want to use elfinder to manage my ftp files.I want to use ftp in which elfinder works.So i found a way in which i don't need to give details of ftp .How to connect with ftp files by just giving path.

**Comment by nao-pon** [comment]
I'm sorry I can not understand what you mean.

**Comment by jasneet-bhatia** [comment]
I mean to say that in elfinder i create roots in connector.php like that:
'roots' => [
'driver' => 'FTP',
'host' => '100.0.0',
'user' => 'user',
'pass' => 'mypass',
'port' => 21,
]
like that but in this we give all details like host ,user ,pass.and its working fine
but I want to connect with this ftp without giving this detail.Is there any way to do this?
this elfinder files are keep in this ftp.please help if possible

**Comment by nao-pon** [comment]
It is impossible to connect to FTP without such information unless that FTP server allows anonymous users to connect.

**Comment by jasneet-bhatia** [comment]
When I give details it worked fine but very slow browsing which is the main problem .It takes a lot of time to browsing files.Is it possible to increase the speed of browsing/
