### ISSUE TITLE
how to define Mylocadriver in another class and define it in root option?

### ISSUE THREAD

**Issue by vahidalvandi** [Studio-42/elFinder#2024]
i have custom driver

```

class elFinderVolumeMyLocalFileSystem extends \elFinderVolumeLocalFileSystem
{
protected function tmbname($stat) {
	$dir = $this->relpathCE($this->decode($stat['phash']));
	if (!is_dir($this->tmbPath.DIRECTORY_SEPARATOR.$dir)) {
		$dirs = explode(DIRECTORY_SEPARATOR, $dir);
		$target = $this->tmbPath;
		foreach($dirs as $_dir) {
			if (! is_dir($target . DIRECTORY_SEPARATOR . $_dir)) {
				mkdir($target . DIRECTORY_SEPARATOR . $_dir);
			}
			$target = $target . DIRECTORY_SEPARATOR . $_dir;
		}
	}
	return $dir . DIRECTORY_SEPARATOR . $stat['name']  ;
}

protected function gettmb($path, $stat) {
	if ($name = parent::gettmb($path, $stat)) {
		$name = str_replace('\\', '/', $name); // For windows server
		$name = str_replace('%2F', '/', rawurlencode($name));
	}
	return $name;
}

public function tmb($hash) {
	if ($name = parent::tmb($hash)) {
		$name = str_replace('\\', '/', $name); // For windows server
		$name = str_replace('%2F', '/', rawurlencode($name));
	}
	return $name;
}


function hashedName(&$path, &$name, $src, $elfinder, $volume) {
	$ext = '';
	if ($pos = strrpos($name, '.')) {
		$ext = substr($name, $pos);
	}
	$name = md5($name) . $ext; // With your preferred hashing method
}
}
```

it work fine with old cms , now i have define top class in external file and define option and connector in a another

driver.php
connector.php 

i have this option in connector.php  but MyLocalFileSystem not detect and not work . please help me.

              $roots[] = [
                    'driver' => 'MyLocalFileSystem', // driver for accessing file system (REQUIRED)
                    'path' => public_path($dir), // path to files (REQUIRED)
                    'URL' => url($dir), // URL to files (REQUIRED)
                    'accessControl' => $this->app->config->get('elfinder.access') // filter callback (OPTIONAL)
                 ];

**Comment by nao-pon** [comment]
@vahidalvandi Perhaps the file that defines the class is not loaded.

**Comment by vahidalvandi** [comment]
how i can load driver.php file?

import ?
use ?
new obj()?

**Comment by vahidalvandi** [comment]
i define this 
require(app_path() . '\functions\elFinderVolumeMyLocalFileSystem.php');

this my markup

namespace Barryvdh\Elfinder;

require(app_path() . '\functions\elFinderVolumeMyLocalFileSystem.php');

class ElfinderController extends Controller
{
    public function showConnector()

                $roots[] = [
                    'driver' => 'MyLocalFileSystem', 
                    'path' => public_path($dir), 
                    'URL' => url($dir), 
                    'accessControl' => $this->app->config->get('elfinder.access')
                 ];
    }

   
}

**Comment by vahidalvandi** [comment]
i sole this , be remove **namespace Barryvdh\Elfinder;** in driver and  require(app_path() . '\functions\elFinderVolumeMyLocalFileSystem.php');
