### ISSUE TITLE
Cannot edit any files (including txt)

### ISSUE THREAD

**Issue by Jeffery4000** [Studio-42/elFinder#2025]
When i try to edit some txt or md files. It prompt an error
![image](https://cloud.githubusercontent.com/assets/27762422/26517545/45e0dcfe-42cd-11e7-9981-86b71f8b4dde.png)
I tried creating a empty txt file with elFinder but the result is still the same. 
Any advice?

**Comment by nao-pon** [comment]
@Jeffery4000 This is currently nightly's bug. I'll fix it.

**Comment by nao-pon** [comment]
@Jeffery4000 Thanks!
