### ISSUE TITLE
send Base64 instead of image file

### ISSUE THREAD

**Issue by shahab19** [Studio-42/elFinder#2029]
Hi
How can send Base64 data instead the original image file? Meaning cut and decreasing size in client side.

**Comment by nao-pon** [comment]
@shahab19 An example of this is in "js/extras/editors.default.js".

- https://github.com/Studio-42/elFinder/blob/master/js/extras/editors.default.js#L179-L196

**Comment by shahab19** [comment]
im override upload fnction
how use for base64?

elf.upload = function(files) {
            var hasError;
            if (hasError) {
                elf.error('upload error');
                return $.Deferred().reject();
            } else {
                return elf.transport.upload(files, elf);
            }
        };

**Comment by nao-pon** [comment]
If you want to upload a file with Base64, it is not a general usage of elFinder, so it can not be supported here. You will need to design both the backend and the client. Please challenge yourself.
