### ISSUE TITLE
Give path of a specific file in elfinder

### ISSUE THREAD

**Issue by jasneet-bhatia** [Studio-42/elFinder#2030]
$opts = array(
	 'debug' => true,
	'roots' => array(
		array(
                    'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => here we can give folder path but i want to give single file path                  // path to files (REQUIRED)
				'accessControl' => 'access' 
		)
	)
);
This is my connector file i want to open a php file when elfinder open how it is possible

**Comment by donShakespeare** [comment]
I do not think it is possible to assign file path to backend config directly.
Here is a (client-side) technique shared here on elFinder issues
http://jsbin.com/nehubazuvu/1/edit?html,js,output

**Comment by jasneet-bhatia** [comment]
ok thanks
