### ISSUE TITLE
Edit template file with elfinder

### ISSUE THREAD

**Issue by jasneet-bhatia** [Studio-42/elFinder#2031]
I am using elfinder to edit my files of php ,css and javascript.It is worked fine for all but edit option is not enabled for template files.Is there any special thing which needs to be done with that?

**Comment by nao-pon** [comment]
@jasneet-bhatia Please set the MIME type of the template file to be text.

In Connector config [`additionalmimemap`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#additionalmimemap).

**Comment by jasneet-bhatia** [comment]
Thanks a lot .

**Comment by jasneet-bhatia** [comment]
thanks a lot
