### ISSUE TITLE
Multipart rar files

### ISSUE THREAD

**Issue by TimT78** [Studio-42/elFinder#2035]
Creating and Extracting single file rar, 7z, zip, and tar files works fine.  But if I have a multipart rar file, it either shoots back an error:  "Unable to extract files from...", or it only extracts files from the first rar file ignore r01, r02, r03 etc.

**Comment by nao-pon** [comment]
@TimT78 Yes, it is impossible currently. So I'll implement this feature. But it only the LocalFileSystem driver.

**Comment by nao-pon** [comment]
@TimT78 Thanks! 👍

**Comment by TimT78** [comment]
Thank you for the fix!  It now works as expected for the "Extract from archive -> Here" command, except "Extract from archive -> New Folder" moves the first rar file to the New Folder path, and extracts the files to the source path of the archive.

**Comment by nao-pon** [comment]
In our demo site that was no problems both function. Is there problem after rebooting your browser?

**Comment by TimT78** [comment]
It must have something to do with the Windows version of unrar, because it does work on the demo.

After changing lines 5724 to 5733 to handle extraction of rar files with 7z on my Windows server it works as expected:

$this->procExec('rar --version', $o, $c);
			if ($c == 0 || $c == 7) {
				$arcs['create']['application/x-rar']  = array('cmd' => 'rar', 'argc' => 'a -inul', 'ext' => 'rar');
				$arcs['extract']['application/x-rar'] = array('cmd' => '7z', 'argc' => 'x -trar -y', 'ext' => 'rar', 'toSpec' => '-o');
			} else {
				unset($o);
				$test = $this->procExec('unrar', $o, $c);
				if ($c==0 || $c == 7) {
					$arcs['extract']['application/x-rar'] = array('cmd' => '7z', 'argc' => 'x -trar -y', 'ext' => 'rar', 'toSpec' => '-o');
				}

Thank you again!

**Comment by nao-pon** [comment]
OK, I modified function `getArchivers` please check with [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).
