### ISSUE TITLE
Invalid backend response. Data is not JSON.

### ISSUE THREAD

**Issue by Mozhdeh-d** [Studio-42/elFinder#2036]
Hi,
elFinder works fine on my localhost and on all my hosts. but I have a host that when I want to open elFinder this error appears: 
Invalid backend response. Data is not JSON.
I'm sure that it's my host problem. but I don't know what the problem is :(

any suggestion ?

**Comment by nao-pon** [comment]
@Mozhdeh-d Please check the response from the server with the browser's developer tool etc. Are there any error messages?

**Comment by Mozhdeh-d** [comment]
There's no error in console tab. but also there's no response for connector.php in network tab :(

![1](https://cloud.githubusercontent.com/assets/3941739/26752067/dc357b3a-485c-11e7-9886-f084a147c502.jpg)
![2](https://cloud.githubusercontent.com/assets/3941739/26752068/dc5ceb70-485c-11e7-8b2f-8a3ccab47262.jpg)
![3](https://cloud.githubusercontent.com/assets/3941739/26752069/dc65ae72-485c-11e7-9fdd-73086acfdee6.jpg)
![4](https://cloud.githubusercontent.com/assets/3941739/26752070/dc8059ca-485c-11e7-9eb5-a4a7845fce6b.jpg)

**Comment by nao-pon** [comment]
Please use `error_reporting` ,  `display_errors` of PHP to display the error.

**Comment by mcarpenterjr** [comment]
what's `'driver'` set to?

**Comment by nao-pon** [comment]
To access the file system on the server by 'LocalFileSystem'.

**Comment by fbdlcm** [comment]
Same issue here. I get no response/errors from connector.php even using error_reporting /  display_errors but still get the "Invalid backend response. Data is not JSON." Driver is set to LocalFileSystem and works fine locally.

**Comment by nao-pon** [comment]
If you have PHP 7.1 or higher on your server, there is a bug in Fatal error. Please try the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

c.f. #2040

**Comment by nao-pon** [comment]
Error handling extended of the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip). If you set the connector option `debug` to` true`, you may be able to see something error message. Please try the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by isadev** [comment]
Hi is this issue resolved?, i have the same error, none error display on the console and all the http request return response 200...is there any solution?

**Comment by wintstar** [comment]
I have the same problem. With Version 2.1.29 and with with the above linked nightly build.

PHP: 7.1.11
Server Version: Apache/2.2.31 (Unix)

**Comment by nao-pon** [comment]
@isadev , @wintstar First of all, please set `'debug'` of the connector setting to `true`.

Please find the problem request in the browser developer tool and access the request URL directly in the browser, and look at the response.

Then let me know the request and response and your connector settings.

**Comment by nao-pon** [comment]
With the default installation method, there is no problem with my test site (2.1.29 (2.1 - src Nightly: 9b8c92b) on PHP 7.2.0 RC 4 on nginx / 1.6.2).

**Comment by wintstar** [comment]
Found the bug.
- baseUrl => was wrong
- defaultOpts : {url  => was wrong

many thanks nao-pon

**Comment by nao-pon** [comment]
How about you @isadev ?

**Comment by trantien1999kg** [comment]
I am also getting error "Invalid backend response. Data is not JSON " when browsing the server with elfinder , help me , please!!!!
![image](https://github.com/Studio-42/elFinder/assets/97332508/d6e73162-2f90-41f7-b971-6ddc6ed02262)

**Comment by instantflorian** [comment]
Had this issue too. Inthe PHP confuration of the server is no value set for maxexecution_time. So the function set_time_limit throws an exception:

> There was an unknown exception: set_time_limit(): Argument #1 ($seconds) must be of type int, string given in line (4848) of /elfinder/ef/php/elFinder.class.php

I added a stupid workaround before line 4848:
`if (!is_int($time)) {$time=100;}`
which obviously fixes the issue.

**Comment by khaidev** [comment]
This issue occur with me and i found a reason and solved it success.

Check all everything api is return ok, but do not work.

- Reason: json return property name case intensive not match
E.g: { "name" : "ABC"} / {"Name": "ABC"}
- Solved: Check you config api return json format
