### ISSUE TITLE
Deleting folder which is not empty take very long time.

### ISSUE THREAD

**Issue by Jeffery4000** [Studio-42/elFinder#2042]
Hi, after the nightly build bug fix on #2040, deleting a folder with size 20MB take 66685ms to response, only some specif folder not all. Especially this one after extract:
[php-7.1.5.tar.gz](https://github.com/Studio-42/elFinder/files/1062878/php-7.1.5.tar.gz)

**Comment by Jeffery4000** [comment]
And those delete file trying to appear again after clearing the trash.
![image](https://user-images.githubusercontent.com/27762422/26960816-b6d089de-4d0c-11e7-9d8b-7157ea1ca61b.png)

**Comment by nao-pon** [comment]
@Jeffery4000  "In to Trash" takes more time than deletion. If it is more than the prescribed number of items, I'll consider a mechanism to shift to delete command.

**Comment by nao-pon** [comment]
@Jeffery4000 Thanks! 👍

**Comment by Jeffery4000** [comment]
@nao-pon its the fix for nightly build? Because i dont find any in js/commands/rm.js , i dont even have the commands folder.
