### ISSUE TITLE
Not able to load the file manager on Joomla 3.7 website.

### ISSUE THREAD

**Issue by vijaykumarkn** [Studio-42/elFinder#2044]
Hi

I have installed Unite Gallery for Joomla 3.7, when I try to add images, The file manager just not load. It stays saying open folder. nothing happens further.
![screen shot 2017-06-09 at 8 47 10 pm](https://user-images.githubusercontent.com/29309225/26982101-eaa2ddaa-4d54-11e7-8a51-6c40dde068e3.png)

**Comment by nao-pon** [comment]
@vijaykumarkn Probably JavaScript has stopped with some error. It may be conflicting with another script that is loading the page. Please check with Developer Tools etc.
