### ISSUE TITLE
How to set default height and directory when launching Nightly build?

### ISSUE THREAD

**Issue by Jeffery4000** [Studio-42/elFinder#2046]
As title, how do i edit my elfinder **nightly build** default height and directory when its launching? I tried editing js/elfinder.full.js but doesnt seems help. Any advice?

**Comment by CodeLyokoXtEAM** [comment]
This guide you to set Default height. 
https://github.com/Studio-42/elFinder/issues/1860
https://github.com/Studio-42/elFinder/commit/1bc260026a0e6bfe1f6a2f4e184973cdccb53bfc

**Comment by CodeLyokoXtEAM** [comment]
Default opening path setting
https://github.com/Studio-42/elFinder/issues/1462
https://github.com/Studio-42/elFinder/blob/c6c0e90633e92b2696b612360866a612f29f4168/js/elFinder.options.js#L453-L459

**Comment by CodeLyokoXtEAM** [comment]
Or read
https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#width

**Comment by nao-pon** [comment]
And In the current nightlife it is an example that you can specify options in elfinder.html. Please check out.
