### ISSUE TITLE
Unable to delete images in image manager, please help..

### ISSUE THREAD

**Issue by FLsales3** [Studio-42/elFinder#2048]
Hi. I clicked the browse files and tried to delete all the unused images. After right clicked the unused image and clicked "Delete" button, it showed "Are you sure you want to remove files? This cannot be undone!". After that, I clicked "Remove" button, but it showed an error window and mentioned "Unable to remove". What should I do then I only can delete the images. Please help.. Thank you..
![image 1](https://user-images.githubusercontent.com/29423244/27118875-f4f02df8-510f-11e7-8930-334dfaff2443.jpg)
![image 2](https://user-images.githubusercontent.com/29423244/27118882-fb0caf04-510f-11e7-97b2-c49544ecdec7.jpg)

**Comment by nao-pon** [comment]
@FLsales3 What connector do you use? It probably is due to connector problems or file permissions on the server.

**Comment by FLsales3** [comment]
Hi, thanks for your reply. I always login as an admin to delete the images, but we never facing this problem before. And do you mean the network connector?

**Comment by nao-pon** [comment]
I thought that you were using a third party connector. Are you using the standard PHP connector elFinder? OK, If you have problems after updating elFinder, please try the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).
