### ISSUE TITLE
No error recovery, no error logging

### ISSUE THREAD

**Issue by joshribakoff** [Studio-42/elFinder#2050]
![screen shot 2017-06-15 at 7 31 19 pm](https://user-images.githubusercontent.com/4021306/27209577-7c513a66-5201-11e7-873f-3c22841fa851.png)

When uploading a large directory tree some files did not upload. The script output a 500 status code & nothing was logged to my PHP error log, the response itself was also blank, no sort of json despite debug mode being enabled. If I insert errors at the top of connector.php I do get errors in the log, so this seems to suggest it may be the connector.php outputting an invalid status code via a header() call as opposed to a PHP crash. Or maybe I'm wrong

Either way the client should handle errors, but does not appear to. Instead it seems to get "stuck" forever (shown in screenshot). Some files did upload, and some did not. But it tells me to keep waiting for no reason, instead it should just tell me how many files failed & which files they were.

**Comment by nao-pon** [comment]
@joshribakoff This is a client bug. I'll fix it. Thanks!
