### ISSUE TITLE
Crashes on dot files

### ISSUE THREAD

**Issue by joshribakoff** [Studio-42/elFinder#2051]
![screen shot 2017-06-15 at 8 36 02 pm](https://user-images.githubusercontent.com/4021306/27210895-850473b8-520a-11e7-9c5b-ad1b6af1763f.png)

Upon uploading a folder with a few files, I get the above error. Upon deleting the dot files `.DS_Store` created by mac & `.idea` folder created by PHPStorm, it does upload without the error. I believe this indicates the elFinder is crashing whenever it encounters dot file(s) / folder(s). At the very least the error message should say the name of the file instead of blank string.

**Comment by nao-pon** [comment]
@joshribakoff This is a PHP connector bug. I'll fix it. THanks!
