### ISSUE TITLE
Opens multiple (numerous, excessive) error dialogs

### ISSUE THREAD

**Issue by joshribakoff** [Studio-42/elFinder#2052]
![screen shot 2017-06-15 at 9 04 34 pm](https://user-images.githubusercontent.com/4021306/27211465-51d4b9ea-520e-11e7-8b5a-9d5d0042cdc1.png)

This can happen for a variety of innocent reasons. The most simple way to replicate, create the root files directory then load elFinder. After it loads, delete the directory & then upload files. There is a dialog created for each request to the server, each with the same error message. (Note - if you do reload elFinder, it blocks the whole UI with a single "directory missing" error, however if something happens to the directory afterwards, this gives bad user experience.) The user then must click out of 50 dialogs or reload the page.  A better solution would be to wait until all downloads fulfill or reject, then display a single dialog summarizing what worked & what went wrong.

**Comment by nao-pon** [comment]
@joshribakoff This seems to be caused by a bug in #2050. It will be solved with #2050.
