### ISSUE TITLE
[VD:abstract] to use the same hash value as Linux on Windows server

### ISSUE THREAD

**Issue by w32gold** [Studio-42/elFinder#2054]
Target folder "#t1_Lw" not found.

**Comment by nao-pon** [comment]
@w32gold This is probably because your server is Windows. Since Windows's directory separator is `\`, it has a hash value different from Linux etc. However, since the user will be confused, I will also add an option on Windows server that can use the same hash value as Linux etc ..

**Comment by nao-pon** [comment]
@w32gold Thanks! 👍 You can try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip) until release elFinder 2.1.25.
