### ISSUE TITLE
Trash funtion bugs

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2057]
1. If trash path is invalid el-finder not show trash icon but still available 'Into trash' button & select it error massage show '**Unable to create folder "". Target folder "#t1_Lw" not found.**'  (because .trash folder doesn't create automatically.)
2. empty folders couldn't restore & Show error massage 'file not found' & it automatically delete in trash.

3. some sub-files & sub-**empty folders** include main folder restoring complete with error.
(main folder icon is hidden until refresh browser window & still remaining empty folders without restore.)
![image](https://user-images.githubusercontent.com/18566890/27336668-e6d0c146-55ed-11e7-9b45-38f3afa1036e.png)

**Comment by CodeLyokoXtEAM** [comment]
Also how-about **empty trash** function add to trash menu list.

**Comment by nao-pon** [comment]
> Also how-about 'empty trash' function add to trash menu list.

It will sets it as future issue #2061.

Thanks!
