### ISSUE TITLE
[How to] View System Log of elFinder

### ISSUE THREAD

**Issue by w32gold** [Studio-42/elFinder#2058]
Can you please show me the location of the system log?
Like when we perform adding, moving, deleting of files, etc., does it show in the log?
Thanks.

**Comment by nao-pon** [comment]
@w32gold Please check the Wiki. - https://github.com/Studio-42/elFinder/wiki/Logging

**Comment by w32gold** [comment]
@nao-pon .. Got it..thank you ...
closing this thread.
