### ISSUE TITLE
uploading Thumbs.db error in windows

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2059]
if upload Thumbs.db directly to elfinder show this massage.
![image](https://user-images.githubusercontent.com/18566890/27343093-8aa562f2-55ff-11e7-8eaa-23b4f1a73c32.png)

if upload folder has Thumbs.db elfinder automatically reject this file without  showing any massage.

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM There is an option [`folderUploadExclude`](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L90-L99) of client.

```javascript
	/**
	 * Regular expression of file name to exclude when uploading folder
	 * 
	 * @type Object
	 * @default { win: /^(?:desktop\.ini|thumbs\.db)$/i, mac: /^\.ds_store$/i }
	 */
	folderUploadExclude : {
		win: /^(?:desktop\.ini|thumbs\.db)$/i,
		mac: /^\.ds_store$/i
	},
```

**Comment by CodeLyokoXtEAM** [comment]
Got it.
