### ISSUE TITLE
how can i set edit permissions other format files?

### ISSUE THREAD

**Issue by russh3l** [Studio-42/elFinder#2060]
hello,

i want to define to file's edit permissions, like .ini format etc ... i can edit just .txt right now ...

thanks!

**Comment by nao-pon** [comment]
@russh3l Please check #1900. There is an option [`additionalMimeMap`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#additionalmimemap) of connector volume root option.

```php
'additionalMimeMap'         => array(
    'ini:*'                => 'text/plain'
),
```

**Comment by russh3l** [comment]
thank you very much!
