### ISSUE TITLE
Trash volume

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2068]
![screenshot_2017-06-25-08-52-26](https://user-images.githubusercontent.com/18566890/27513455-c30b825c-5983-11e7-8547-a13ddefb3651.png)

I think its 'volume root' to 'trash root' or something.

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM "Trash" is also one of the volumes like "LocalFileSystem", "FTP",  etc... so I think it's no issue.

Thanks :-)
