### ISSUE TITLE
Determine current version of installed elFinder

### ISSUE THREAD

**Issue by alexantr** [Studio-42/elFinder#2069]
Please add constant to `elFinder` class, e.g. `VERSION = '2.1.25';` or static function:
```php
public static function getVersion()
{
    return '2.1.25';
}
```
Need to know what features already implemented when using elFinder with 3rd party extensions.

**Comment by nao-pon** [comment]
@alexantr I want to know why you need it.

Thanks!

**Comment by nao-pon** [comment]
@alexantr I added `elFinder::getApiFullVersion()` to getting full version of API that this connector supports all functions.

Thanks!
