### ISSUE TITLE
How to use elFinder.options.js in Stable builds?

### ISSUE THREAD

**Issue by jcaira** [Studio-42/elFinder#2072]
I have downloaded the stable build and the elFinder.options.js file doesnt exist. If I use the development branch it does exist and I can use it for customisation such as height and toolbar options.
How can I get the stable build to use the elFinder.options.js file?

**Comment by nao-pon** [comment]
@jcaira Please check out [Wiki - Client configuration options 2.1](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1).
