### ISSUE TITLE
Invalid backend configuration. Readable volumes not available.

### ISSUE THREAD

**Issue by fangchen000** [Studio-42/elFinder#2075]
The following is the error message on the server:
http://localhost/intranet/index.php/Home/File/connect.html?cmd=open&target=&init=1&tree=1&_=1498637967640
error message:
{error: ["errConf", "errNoVolumes"],…}
debug
:
["Driver "elFinderVolumeLocalFileSystem" : Root folder does not exist.",…]
error
:
["errConf", "errNoVolumes"]

If not in thinkPHP, place it directly under the web root directory,it's OK:
http://localhost/elFinder-master/php/connector.minimal.php?cmd=open&target=l1_Lw&init=1&tree=1&_=1498636717613
error message:
{,…}
api
:
2.1025
cwd
:
{isowner: false, ts: 1498634157, mime: "directory", read: 1, write: 1, size: 0, hash: "l1_Lw",…}
files
:
[{isowner: false, ts: 1498634157, mime: "directory", read: 1, write: 1, size: 0, hash: "l1_Lw",…},…]
maxTargets
:
1000
netDrivers
:
["ftp"]
options
:
{path: "files", url: "/elFinder-master/php/../files/", tmbUrl: "/elFinder-master/php/../files/.tmb/",…}
uplMaxFile
:
"20"
uplMaxSize
:
"100M"

I'm bad English,I hope you can help me.Thank you  Thank you

**Comment by jcaira** [comment]
I am very new to elfinder so apologies if this does not help but

Have you made sure that the URL section for the connector you have added is correct? Looking at the error it looks like the URL is using  ../files which is the default. So unless your folder structure reflects this, I dont think it will work.
So for example, if your path is /var/www/elfinder-master/documents, your url needs to be /.../documents/

**Comment by fangchen000** [comment]
@jcaira I think this is my framework for thinkPHP problem, because when I put the project integrated into the thinkPHP, it will report this error, and I know is'driver'=>'LocalFileSystem', because when I put it in a separate, this line of code will be reported and commented, in the framework of the same mistake, but I won't whether or not to modify the elFinderVolumeLocalFileSystem.class.php file into the corresponding location, if you know anything about thinkPHP, please help me, thank you very much. You can refer to http://www.thinkphp.cn/topic/6410.html

**Comment by fangchen000** [comment]
@nao-pon I want to know'driver'=>'LocalFileSystem'code, because when I hit the elfinder into their own framework (thinkPHP), it will go wrong, and I know the reason of this code, but because they do not understand it, so I do not know how to modify it in my frame, please answer for me, thank you very much

**Comment by fangchen000** [comment]
@jcaira @nao-pon 

The problem is that my path is not configured properly. Sorry, but I have another problem. How to set the file under the files folder can not be removed, and other operations can be performed

**Comment by fangchen000** [comment]
@nao-pon Thank you very much for your help. I think I know

**Comment by fangchen000** [comment]
@nao-pon I have a new problem, when I upload a file to the Chinese name elfinder, which display is normal, is Chinese name, but when I entered into the actual storage path of the file, which is the files folder, its name display is not normal, when I gave it the name change in elfinder Chinese after it disappeared, I do not know how to modify****

**Comment by fangchen000** [comment]
@nao-pon I have a new problem, when I upload a file to the Chinese name elfinder, which display is normal, is Chinese name, but when I entered into the actual storage path of the file, which is the files folder, its name display is not normal, when I gave it the name change in elfinder Chinese after it disappeared, I do not know how to modify. By the way, my server is windows system.

**Comment by nao-pon** [comment]
@fangchen000 When contents change, please make a new issue.

Well, Your new problem will be #937, #1827 related.

**Comment by kkumarsantosh90** [comment]
I am facing the same issue, I am creating the dynamic path , For some of the path it is working but for few it throw as error.
