### ISSUE TITLE
Full screen & preference tab

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2076]
If someone change Preference tab settings in mobile browser on full-screen, window size change like this.(Tested Chrome on Android latest version). 

(Edited: same as desktop) 

![screenshot_2017-06-28-21-22-28](https://user-images.githubusercontent.com/18566890/27647346-cc6f6c9c-5c48-11e7-9a11-26da28c9f168.png)

**Comment by CodeLyokoXtEAM** [comment]
Also its best look to readjustment areas.
![screenshot_2017-06-28-21-35-51](https://user-images.githubusercontent.com/18566890/27647748-f2b24bd0-5c49-11e7-8332-ee462d0cbbb3.png)
![screenshot_2017-06-28-21-36-00](https://user-images.githubusercontent.com/18566890/27647754-f8727b44-5c49-11e7-9150-adc83779e09a.png)
![screenshot_2017-06-28-21-36-09](https://user-images.githubusercontent.com/18566890/27647759-fe8e27bc-5c49-11e7-8ec3-6c84c5c8c894.png)

**Comment by alexantr** [comment]
Confirm second bug. Popup height not adjusting. In last stable release (2.1.25) this bug is absent.

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM , @alexantr Thanks!

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon still not fix first comment.
and
This happen After reset & goto fullscreen & click Help.
![image](https://user-images.githubusercontent.com/18566890/27698926-3c415648-5d16-11e7-9465-c755015f527a.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks, What about currently? I think fixed it. (Please don't forgot clear browser cache)

**Comment by CodeLyokoXtEAM** [comment]
I try it after clear browser cache
here the steps.
full-screen
about this software
Preference
Reset

![image](https://user-images.githubusercontent.com/18566890/27744047-bc0f1962-5ddb-11e7-8aa1-39d99fd226ce.png)

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon 
I try it after clear browser cache
here the steps.
full-screen
about this software
Preference
Reset or change lang.
(if select reset Its automaticly fit with width but not hight, change lang both of it not fit, also full-screen icon is wrong)
![image](https://user-images.githubusercontent.com/18566890/27744047-bc0f1962-5ddb-11e7-8aa1-39d99fd226ce.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM I got it.

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks! 👍
