### ISSUE TITLE
volume file size bug

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2077]
![image](https://user-images.githubusercontent.com/18566890/27652800-af9ff76e-5c5a-11e7-992a-358d2e8384ff.png)

Check Right Bottom corner. It show 'Size: 0 b'

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM This is a not bug. The status bar shows the sum of the file sizes of the current folder. The contents of subfolder are not calculated.
