### ISSUE TITLE
Toolbar buttons not restored  after leaving trash

### ISSUE THREAD

**Issue by alexantr** [Studio-42/elFinder#2081]
1. Open "Trash" volume
2. Open "files" volume again
3. "Restore" button is still on toolbar instead "Copy" and "Paste" buttons.

"New folder" button is lost too:
![buttons_bug](https://user-images.githubusercontent.com/4941848/27712239-c56852ba-5d2e-11e7-8e71-8b627666a854.png)

And we can see error when pressing on "Restore" button:
![trash_bug](https://user-images.githubusercontent.com/4941848/27711604-5ec11364-5d2c-11e7-9cf0-56e62f5d82fd.png)

**Comment by nao-pon** [comment]
@alexantr Thanks! 👍
