### ISSUE TITLE
into trash & delete icon mix

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2086]
befor R-click tool box
![image](https://user-images.githubusercontent.com/18566890/27761353-ec607f42-5e77-11e7-96f1-33a6b379d5bb.png)

after R-click tool box
![image](https://user-images.githubusercontent.com/18566890/27761350-e0d3a992-5e77-11e7-8cb2-d40393880930.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks! 👍
