### ISSUE TITLE
Into trash icon not disable

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2087]
After referring page default disable trash icon in toolbar. 
if select file or folder its enable normally. 
But after dissected file and folder its still Remaining enable icon in toolbar.

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM When do not display the `rm` icon on the toolbar, a JavaScript error will occur, so I'll fix it.

**Comment by CodeLyokoXtEAM** [comment]
Also enable text label and refresh page. You can see delete icon lable is show cmdundifind while loadingetting.

**Comment by CodeLyokoXtEAM** [comment]
I think this get ideas from this Interface to improve el finder.
https://github.com/kalcaddle/KodExplorer

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks! About UI, It's future topics of discussion.
