### ISSUE TITLE
Symbolic Link yet not visible

### ISSUE THREAD

**Issue by erickeas** [Studio-42/elFinder#2097]
The **elFinder Version: 2.0** rc1 inside K2 last **Joomla package version 3.7.x** doesn´t show symbolic links. 
But the other media manager of the same Joomla version shows.
Then, it seems to be a bug because only elFinder doesn´t show.
How (where) can I change de code to fix it?
Very gratefully for help...
Erick

**Comment by nao-pon** [comment]
@erickeas There is a security vulnerability in elFinder Version: 2.0 rc1 and should not be used. Please use the latest version (2.1.25 at currently).
Also, please do check operation with [Nightly Build](https://github.com/Studio-42/elFinder/archive/2.1.zip) when reporting bugs.

Thanks.
