### ISSUE TITLE
Java- connector   - br.com.trustsystems.elfinder.command.ZipdlCommand class not found exception

### ISSUE THREAD

**Issue by rajayogadharasan** [Studio-42/elFinder#2099]
i connect the java connector ,then i download folder that time occurred the Java- connector   - br.com.trustsystems.elfinder.command.ZipdlCommand class not found exception

Give the solution

**Comment by nao-pon** [comment]
Fixed via 7e2750443816253c1ddc99cea91389bed0bda121 . @rajayogadharasan Thanks!

**Comment by rajayogadharasan** [comment]
Thanks nao-pon
