### ISSUE TITLE
disks permissions like for roots

### ISSUE THREAD

**Issue by froid24** [Studio-42/elFinder#2101]
I'm using elfinder with the disks array, which is a list of 2 previously defined disks, files (local) and dropbox.
How can I set permissions on these disks?

'disks' => [
'files',
'dropbox',
],

'roots' => [

],
'options' => [

],
I saw some ideas about applying permissions to roots, but i have nothing defined in the roots array, the disks above act like roots for me.

I really need to provide some permission levels to users, at least at top level.
Thank you so much for the help.

**Comment by nao-pon** [comment]
@froid24 elFinder (official PHP connector) has no setting `disks`. Since I guess you are integrating with some framework, ask the developers of that framework.

Thanks.
