### ISSUE TITLE
Error in diagnostic message in elFinderVolumeDriver.class.php

### ISSUE THREAD

**Issue by cpnemo19** [Studio-42/elFinder#2102]
file: elFinderVolumeDriver.class.php
............................
	public function rename($hash, $name) {
.............................		
		if (!$this->nameAccepted($name, $isDir)) {
--			return $this->setError(elFinder::ERROR_INVALID_DIRNAME);
++			return $this->setError($isDir ? elFinder::ERROR_INVALID_DIRNAME : elFinder::ERROR_INVALID_NAME);**
		}

**Comment by nao-pon** [comment]
@cpnemo19 Thanks! Would you make a pull request? It's easy by edit icon at https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeDriver.class.php .

**Comment by nao-pon** [comment]
@cpnemo19 Thanks! 👍
