### ISSUE TITLE
Notice thrown with php 7.1

### ISSUE THREAD

**Issue by tseho** [Studio-42/elFinder#2104]
Hey, I'm having this notice thrown with php 7.1:

> Notice: A non well formed numeric value encountered in /app/vendor/studio-42/elfinder/php/elFinder.class.php at line 3632 

https://github.com/Studio-42/elFinder/blob/2.1.26/php/elFinder.class.php#L3632

I'm using php:7.1-fpm with xdebug.

Before 7.1,
```
$val = "128M";
$val *= 1024;
var_dump($val); // int(131072)
```

Since 7.1,
```
$val = "128M";
$val *= 1024; // Notice thrown
var_dump($val); // int(131072)
```

In my case, It's only happening since 2.1.25 because getIniBytes() was not called before.

A solution would be to cast to int before the switch.

**Comment by nao-pon** [comment]
@tseho Thanks! 👍
