### ISSUE TITLE
why Integration with CodeIgniter not working always show {"error":["errUnknownCmd"]} please help...

### ISSUE THREAD

**Issue by EroticCode** [Studio-42/elFinder#2105]
This is my controller
`<?php  
	defined('BASEPATH') OR exit('No direct script access allowed');
	
	class Home extends CI_Controller {
	
		public function index()
		{
			echo "my page";
		}

		function elfinder_init()
		{
		  

		  $this->load->view('site/page');

		  $this->load->helper('path');
		  $opts = array(
		    // 'debug' => true, 
		    'roots' => array(
		      array( 
		        'driver' => 'LocalFileSystem', 
		        'path'   => set_realpath('files'), 
		        'URL'    => base_url('files') . '/'

		      ) 
		    )
		  );
		  $this->load->library('elfinder_lib', $opts);
		}
	
	}
	
	/* End of file Home.php */
	/* Location: ./application/controllers/Home.php */
?>`
Lib file
`<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elfinder/elFinderConnector.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elfinder/elFinder.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elfinder/elFinderVolumeDriver.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elfinder/elFinderVolumeLocalFileSystem.class.php';

class Elfinder_lib 
{
  public function __construct($opts) 
  {
    $connector = new elFinderConnector(new elFinder($opts));
    var_dump($connector);
    $connector->run();
  }
}`
this is my view
`
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
	<meta charset="utf-8">
	<title>elFinder 2.1.x source version with PHP connector</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2" />

	
	
	<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

	
	<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/plugins/elFinder/') ?>css/elfinder.min.css">
	<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/plugins/elFinder/') ?>css/theme.css">
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	
	<script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

	
	<script src="<?php echo base_url('assets/plugins/elFinder/') ?>js/elfinder.min.js"></script>

	
	<script src="<?php echo base_url('assets/plugins/elFinder/') ?>js/extras/editors.default.js"></script>

	<script src="<?php echo base_url('assets/plugins/elFinder/') ?>/js/i18n/elfinder.ca.js"></script>

	
	

	
	<script type="text/javascript" charset="utf-8">
			// Documentation for client options:
			// https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
			$(document).ready(function() {
				$('#elfinder').elfinder(
					// 1st Arg - options
					{
						cssAutoLoad : false,               // Disable CSS auto loading
						baseUrl : './',                    // Base URL to css/*, js/*
						url : 'php/connector.minimal.php'  // connector URL (REQUIRED)
						// , lang: 'ru'                    // language (OPTIONAL)
					},
					// 2nd Arg - before boot up function
					function(fm, extraObj) {
						// `init` event callback function
						fm.bind('init', function() {
							// Optional for Japanese decoder "extras/encoding-japanese.min"
							delete fm.options.rawStringDecoder;
							if (fm.lang === 'jp') {
								fm.loadScript(
									[ fm.baseUrl + 'js/extras/encoding-japanese.min.js' ],
									function() {
										if (window.Encoding && Encoding.convert) {
											fm.options.rawStringDecoder = function(s) {
												return Encoding.convert(s,{to:'UNICODE',type:'string'});
											};
										}
									},
									{ loadType: 'tag' }
								);
							}
						});
						// Optional for set document.title dynamically.
						var title = document.title;
						fm.bind('open', function() {
							var path = '',
								cwd  = fm.cwd();
							if (cwd) {
								path = fm.path(cwd.hash) || null;
							}
							document.title = path? path + ':' + title : title;
						}).bind('destroy', function() {
							document.title = title;
						});
					}
				);
			});
		</script>
</head>
<body>
	<div id="elfinder">
		
	</div>
</body>
</html>

		
	

`
I follow https://github.com/Studio-42/elFinder/wiki/Integration-with-CodeIgniter and i think my code not miss any step.
Sorry if have problem with my ENG BAD

**Comment by nao-pon** [comment]
@EroticCode I re-written [Wiki - Integration with CodeIgniter](https://github.com/Studio-42/elFinder/wiki/Integration-with-CodeIgniter). Please check out it.
