### ISSUE TITLE
Weird 0 size when upload file

### ISSUE THREAD

**Issue by MickaelTH** [Studio-42/elFinder#2107]
Hi,

When upload a file it then appears with a size of 0.

I always need to reload to make it display the correct size.

Am I missing a setup somewhere?

![01](https://user-images.githubusercontent.com/26375917/28411222-5219bc76-6d6a-11e7-9184-3ece4e2be11b.png)
![02](https://user-images.githubusercontent.com/26375917/28411223-521c28f8-6d6a-11e7-84e0-bcaefae234f8.png)
![03](https://user-images.githubusercontent.com/26375917/28411225-523362a2-6d6a-11e7-8379-c2b98b61431e.png)

**Comment by nao-pon** [comment]
@MickaelTH Which connector are you using? Official PHP connector? Which is version? And please check and inform `added` of server response of upload command request. 

like this
```
"added":[{"isowner":false,"ts":1500553910,"mime":"text\/plain","read":1,"write":1,"size":"3268","hash":"l2_dGVzdC50eHQ","name":"test.txt","phash":"l2_Lw","url":"\/\/hypweb.net\/elFinder-nightly\/demo\/develop\/files\/test.txt"}]
```

**Comment by MickaelTH** [comment]
@nao-pon 

Thanks for answer.

So, I am using elfinder from Laravel with SFTP connector. I don't think this is the PHP connector, should I change it?

I tried to reproduce the issue on the elfinder demo and it is showing size properly, so I assume this may be related to the SFTP Service Provider or the laravel package?

Any help to start investigation should be appreciate. And I am sorry I don't know where to add "added" you asked above.

![2017-07-26 001883](https://user-images.githubusercontent.com/26375917/28619977-2c4d17c0-7235-11e7-8ad6-3a8db4ade9b9.png)

**Comment by nao-pon** [comment]
> Any help to start investigation should be appreciate. And I am sorry I don't know where to add "added" you asked above.

Please check the value of the `"added"` parameter of the JSON data of the server response. If the `"size"` value in the data is incorrect, I think there is a problem with the SFTP adapter or cache mechanism.

**Comment by MickaelTH** [comment]
@nao-pon Can you tell me where to add this "added" parameter? I cannot find any documentation about it.

**Comment by nao-pon** [comment]
@MickaelTH Sorry for my poor English. The meaning I said is to check the response data from the server. If there is a problem with the `added` data in the server response, it means that it is a problem on the connector side.

**Comment by heyonghong** [comment]
Is your problem solved?I meet the  same question

**Comment by nao-pon** [comment]
@MickaelTH , @heyonghong  The cause of this problem seems to be in barryvdh / elfinder-flysystem-driver. I confirmed that the problem is solved by disabling the cache setting of elfinder-flysystem-driver.

**for example**
```php
[
    'driver' => 'Flysystem', 
    'path' => '/',
    'filesystem' => new Filesystem(new SftpAdapter([
        'host' => 'example.com',
        'port' => 22,
        'username' => 'username',
        'password' => 'password',
        'privateKey' => 'path/to/or/contents/of/privatekey',
        'root' => '/path/to/root',
        'timeout' => 10,
        'directoryPerm' => 0755
    ])),
    'cache' => false, // 'session', 'memory' or false
]
```

**Comment by nao-pon** [comment]
OK, I found an elFinder's bug of PHP volume driver. so I'll fix it.

**Comment by MickaelTH** [comment]
@nao-pon Thank you very much for this fix and your great follow-up on this. Do you know when this will be available? I've done composer update and now I cannot see the changes on 2.1.26. I assume this will take some day to appear.

**Comment by nao-pon** [comment]
@MickaelTH I am planning to release 2.1.27 within one to two weeks. Please wait for that 2.1.27, or update it with Developer Channel until then.

`composer require studio-42/elfinder:2.1.x-dev`

**Comment by MickaelTH** [comment]
@nao-pon Thank you for confirmation. I will wait for 2.1.17 as this is a minor issue with working workaround (reload page).

**Comment by MickaelTH** [comment]
Just to confirm version 2.1.17 fixed the issue, thank you!
