### ISSUE TITLE
Read / Write and Deny permission

### ISSUE THREAD

**Issue by thatobabusi** [Studio-42/elFinder#2111]
Hi, I am working on the Laravel implementation of this and having the following issue:
I want to have files that are read only depending on whether a person has permissions or not but cannot find the right place and method to add this to. Can someone please lead me in the right direction, I have exhausted all options

**Comment by nao-pon** [comment]
@thatobabusi There is a config [accessControl`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#accesscontrol) of volume roots options on elFinder PHP connector. We can control thoroughly by callback function registered in `accessControl`. However, I do not know how to use the Laravel user role, so please ask in the Laravel community.

Thanks!
