### ISSUE TITLE
Hi Naoki ../i18n/help/pl.html

### ISSUE THREAD

**Issue by Chaffinch** [Studio-42/elFinder#2112]
On:
https://github.com/Chaffinch/elFinder-Ver-2.1.26/blob/master/js/i18n/help/pl.html
I added: translation for help/pl.html >>> elFinder Ver: 2.1.26

Additional question:
In which place,i can change language name.

I tried to change in file:
\js\commands\**help.js** no effect :-((
https://github.com/Chaffinch/elFinder-Ver-2.1.26/blob/master/js/commands/help.js
Line: 186 to 223

**Comment by nao-pon** [comment]
@Chaffinch Thank you for your work.

> I tried to change in file: https://github.com/Chaffinch/elFinder-Ver-2.1.26/blob/master/js/commands/help.js

Yes, you are right. It's OK. so I marged your commits 83fc8094474bda02ac0e1ecbf660f0bd53bb5164 and 440a8eee1ed4a0fff3e25d5de243859266451758 in to master branch.

Thanks again! 👍
