### ISSUE TITLE
how can i set install permission .dll files ?

### ISSUE THREAD

**Issue by russh3l** [Studio-42/elFinder#2113]
Cant install .dll files i could not find, can someone explain ? thanks !

**Comment by nao-pon** [comment]
@russh3l Please check out Wiki - Connector root option [`uploadAllow`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadallow), [`uploadDeny`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploaddeny) and [`uploadOrder`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadorder).
