### ISSUE TITLE
When I create the local folder with special characters

### ISSUE THREAD

**Issue by hiagobury** [Studio-42/elFinder#2114]
When I create the local folder with special characters
**Ex: (Apresentação) (ção)**
It does not appear on my system

**Comment by nao-pon** [comment]
Please check #1827, #1867, Or [search result of issues(encoding locale)](https://github.com/Studio-42/elFinder/issues?utf8=%E2%9C%93&q=encoding%20locale.).

**Comment by nao-pon** [comment]
I made a typo in the commit log of 896af8cb44f7eb51a280ba834bc4799f8d634703.
