### ISSUE TITLE
upload button is not showing

### ISSUE THREAD

**Issue by ashickurnoor** [Studio-42/elFinder#2117]
Here is my elfinder configaration. I want to show a upload button. But button is not showing.  How I can show a upload button?

```
$('#elfinder').elfinder({
url : 'explorer/php/connector.minimal.php', 
ui : [],
commandsOptions : {
upload : {
ui : 'uploadbutton'
},
},
width : 600,
height: 400
});
```

![firefox_screenshot_2017-07-31t10-38-41 789z](https://user-images.githubusercontent.com/905903/28774295-bd516e74-760e-11e7-9386-98f5737ab720.png)

**Comment by nao-pon** [comment]
@ashickurnoor It's example to only show the upload button in toolbar.

```javascript
$('#elfinder').elfinder({
    url : 'explorer/php/connector.minimal.php', 
    ui : [ 'toolbar' ],
    uiOptions : {
        toolbar: [ ['upload'] ]
    },
    commandsOptions : {
        upload : {
            ui : 'uploadbutton'
        },
    },
    width : 600,
    height: 400
});
```

**Comment by ashickurnoor** [comment]
@nao-pon  not it is clear.
