### ISSUE TITLE
[cmd:help] controling to show / hide toolbar icons in preference tab

### ISSUE THREAD

**Issue by nao-pon** [Studio-42/elFinder#2118]
In title.

**Comment by CodeLyokoXtEAM** [comment]
also how about add tick to auto hide on startup toolbar & navigation panel in mobile view

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM 

>selection to auto hide or not on startup toolbar

The previous state is restored for the show/hide status of toolbar.

> navigation panel

What is it like?

**Comment by CodeLyokoXtEAM** [comment]
There is little problem. 
If someone disable 'about this software' icon,
After in computer can reach it pressing F1 but mobile browsers can't reach it for change settings. 
I think there is separate option available for change settings & its icon can't be disabled. (or 'about this software' icon can't disabled.) 

Also in mobile browser
Available option for 'The previous state is restored for the show/hide status of toolbar.'(default set) 
If someone disable it. User can decide to auto hide or not on startup toolbar & navigation panel separately. 

Also Ticks are re-arrangement for better look.

**Comment by CodeLyokoXtEAM** [comment]
If someone disabled all icons toolbar is hide. So computer can only reach settings by F1(right click options are not working(toolbar settings)). But mobile F1 option not available also long click & reach the settings is too hard.

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks a lot !. 👍 

Preservation of the previous value in the initial state of the tool bar show / hide is always enabled at present. (It can not be invalidated) I can not think of the situation of the request that the installer wants to invalidate it...

However, I'll be waiting for you if there is a better proposal.

Thanks!

**Comment by CodeLyokoXtEAM** [comment]
there is preference 3 tabs available
every reset multipli preference tab like this
![image](https://user-images.githubusercontent.com/18566890/28926655-0f0229ce-7886-11e7-84ea-87e4e1b537e7.png)

**Comment by nao-pon** [comment]
It was my simple mistake and it has already been fixed.

Thanks!

**Comment by CodeLyokoXtEAM** [comment]
how about if user disable all icon then add preferences settings icon to right click menu list. without add icon to tool bar.

**Comment by nao-pon** [comment]
That's nice! I'll try it. I think that it is better to always display it in the context menu. And, I think that the automatic display on the tool bar is optional.

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM I done. Thanks! 👍
