### ISSUE TITLE
cmd 'open' for files

### ISSUE THREAD

**Issue by terraplane** [Studio-42/elFinder#2119]
Please help, 
docx/odt files cant be downloaded on double click. Instead that el-finder is trying to open the file as a directory. Plain txt files, jpg -- all workslike a charm. 
I use ruby on rails connector for backend, it returns JSON with correct mime types. On browser file icons are correct according their files types.
Any ideas?

**Comment by nao-pon** [comment]
@terraplane This seems to be a ruby on rails connector problem. Please ask the developer of that connector.

Thanks.
