### ISSUE TITLE
OneDrive mount atomatically

### ISSUE THREAD

**Issue by alsantos123** [Studio-42/elFinder#2121]
It's possible, after the first authorization, get mt OneDrive netdrive mount automatically? and specify the directory inside my onedrive to mount? 

I really need specify, through my php connector, what directory, inside my OndeDrive, I want to be mounted.

Cheers.

**Comment by nao-pon** [comment]
@alsantos123 To do that you need to get an access token.

**e.g**
```php
array(
	'driver' => 'OneDrive',
	'path' => '/', // or folder ID (not path)
	'accessToken' => '{"expires":1501753851,"data":{"token_type":"bearer","expires_in":3600,"scope":"wl.skydrive_update wl.offline_access","access_token":"xxxxxxxxxx"}}',
),
```

**Comment by nao-pon** [comment]
You can find access token in the debug tab of the help dialog with debug mode (in connector configuration).

![170803-233820](https://user-images.githubusercontent.com/1412630/28929463-efa38d8c-78aa-11e7-8737-906730226e87.png)

**Comment by alsantos123** [comment]
Thanks nao-pon! =)
