### ISSUE TITLE
windows reposition bug in bottom margin

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2124]
This is rare to happen but
if someone drag window like this(Bottem or right margin)
![image](https://user-images.githubusercontent.com/18566890/28994191-e0490632-79e5-11e7-9072-f187967ac3a1.png)

in full screen mode not showing window

I think it's better to reposition like this 
![image](https://user-images.githubusercontent.com/18566890/28994210-57d85860-79e6-11e7-87a1-89bc063ecc3f.png)

![image](https://user-images.githubusercontent.com/18566890/28994250-ec5fba1e-79e6-11e7-8bea-b37ebb7b0899.png)

**Comment by CodeLyokoXtEAM** [comment]
Also still present this bug.

https://github.com/Studio-42/elFinder/issues/2087

> After refreshing page default disable trash icon in toolbar.
> if select file or folder its enable normally.
> But after dissected file and folder its still Remaining enable icon in toolbar.

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks! 👍

**Comment by CodeLyokoXtEAM** [comment]
There is in mobile browser reposition can't move window
![screenshot_2017-08-07-11-13-06](https://user-images.githubusercontent.com/18566890/29013625-dcfdd71e-7b61-11e7-9eb7-282b1e6dba32.png)

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon 

There is in mobile browser reposition can't move window
![screenshot_2017-08-07-11-13-06](https://user-images.githubusercontent.com/18566890/29013625-dcfdd71e-7b61-11e7-9eb7-282b1e6dba32.png)

**Comment by nao-pon** [comment]
OK, I will adjust it to go to the left a little more.
