### ISSUE TITLE
How can I remove "Save As" based on file mime type in Image resize dialog ?

### ISSUE THREAD

**Issue by codemilan** [Studio-42/elFinder#2127]
I want to delete/hide "SaveAs" button only in image Resize dialog not for txt file save dialog, since "SaveAs" is not working for image files, it's making image files corrupted due to mkfile cmd accepting 'txt' only mime type. I would like to know, how can I delete/hide "SaveAs" button, Also I would like to get some links/resources to good tutorial about elfinder's working (client side), which could help me in easy customization as per my need, thankyou all, Hoping for kind responses.

**Comment by nao-pon** [comment]
@codemilan I'll fix it. It is a bug that the SaveAS button is shows even though saving of the image file is not allowed.

Thanks!

**Comment by codemilan** [comment]
Thankyou for the response @nao-pon
