### ISSUE TITLE
[i18n:pl] update to 2.1.27

### ISSUE THREAD

**Issue by Chaffinch** [Studio-42/elFinder#2128]
Updated elfinder.pl.js to v2.1.27 added 06.08.2017
https://github.com/Chaffinch/elFinder/blob/master/js/i18n/elfinder.pl.js

**Comment by nao-pon** [comment]
@Chaffinch Would you please send pull request?

**Comment by Chaffinch** [comment]
I see changes in the script, so i updated: elfinder.pl
The update mainly covers : strings completed -> // from v2.1.27 added 03.08.2017
That's all
Regards
Bobby
  ----- Original Message -----

**Comment by nao-pon** [comment]
OK, I merged at 5ba56d6d67671097e3888e1fed1d2e3d4453bafc. By the way, it is very helpful to [use the Pull Request](https://help.github.com/articles/about-pull-requests/). I'm glad to if you sent pull requests in the future. 

Thanks!
