### ISSUE TITLE
Change file type 

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2134]
If someone rename to 'X.txt' to 'Y.png' or  'Y' but still elfinder recognize it is text & icon not Change.
Its present all file types.

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM This is the specification of the PHP connector. The PHP connector detects MIME type by file contents by default. To detect by file extension, please set `'mimeDetect' => 'internal'` with the volume roots option.
