### ISSUE TITLE
请问下关于elfinder在linux端无法上传文件问题？

### ISSUE THREAD

**Issue by yangzhengpk** [Studio-42/elFinder#2135]
在wamp测试，修改代码后可以上传图片包括pdf，但对中文的支持很差，看到论坛上有说在linux后台运行对中文支持比较好，于是乎在自己搭建的linux后台测试，wamp的后台apache是2.21版本，而linux的apaceh版本为2.4.1，发现liunx后端会无法上传文件，但如果在服务器端拖入中文文件是可以显示的，请问下如何解决linux端上传被禁用的问题。

**Comment by nao-pon** [comment]
@yangzhengpk Sorry, I don't understand Chinese, so would you please post with English?

**Comment by yangzhengpk** [comment]
Sorry my friend,I try to write this bug in English.In the Windows 7 I make wamp , modify the code to upload images including PDF, but the Chinese support is very poor,such as "派" can not input elfinder.I see the forum said that in the background of the Linux operation of the Chinese support is good, so using Linux to build Apache background to run elfinder.But found in the Linux background, elfinder can not directly drag and drop file upload, browser is chrome 47.0.2526.111, elfinder version is the latest. Directly through the background of the PDF or picture files directly copied to the file folder, the front end can display.

**Comment by yangzhengpk** [comment]
I would like to ask if this situation can be solved by modifying the elfinder code Or Apache version of the problem?

**Comment by nao-pon** [comment]
see #2137
