### ISSUE TITLE
A questions about elfinder unable to upload files at CentOS 7?

### ISSUE THREAD

**Issue by yangzhengpk** [Studio-42/elFinder#2137]
Sorry my friend,I try to write this bug in English.In the Windows 7 I make wamp , modify the code to upload images including PDF, but the Chinese support is very poor,such as "派" can not input elfinder.I see the forum said that in the background of the Linux operation of the Chinese support is good, so using Linux to build Apache background to run elfinder.But found in the Linux background, elfinder can not directly drag and drop file upload, browser is chrome 47.0.2526.111, elfinder version is the latest. Directly through the background of the PDF or picture files directly copied to the file folder, the front end can display.I would like to ask if this situation can be solved by modifying the elfinder code Or Apache version of the problem?

**Comment by nao-pon** [comment]
@yangzhengpk 

1. When using elFinder on a Windows server, you need to specify the proper [locale](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale-1) and [encoding](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding) of connector roots options. Please investigate appropriate values in each country.

2. One of the reasons why files can not be uploaded on Linux servers is that directory permissions are insufficient.

**Comment by yangzhengpk** [comment]
I chmod 777 elfinder,check the files is rwxrwxrwx,but I still no write permission,I don't understant why the files permissions not valid?

**Comment by nao-pon** [comment]
If the directory permission referred to by elFinder is 0777, there is no permission problem. There is something else problematic. Can you show your elFinder's connector settings?

**Comment by yangzhengpk** [comment]
This is the activation file in the tutorial: connector.minimal.php, and another connector.php-dist is not active. I just added the support PDF upload in the first PHP file

![_20170810150404](https://user-images.githubusercontent.com/30853283/29158546-03a48222-7dde-11e7-9550-105a1ce7d829.png)

**Comment by yangzhengpk** [comment]
![only read](https://user-images.githubusercontent.com/30853283/29161298-4dec3d70-7de8-11e7-8dd6-73da29ac1d57.png)

**Comment by yangzhengpk** [comment]
centos 7 as shown in the figure above.

**Comment by yangzhengpk** [comment]
![linux2](https://user-images.githubusercontent.com/30853283/29164134-1ba8339c-7df1-11e7-955a-5baf4076f0e2.png)
![linux3](https://user-images.githubusercontent.com/30853283/29164135-1ba8818a-7df1-11e7-921c-784d6baa14d1.png)

**Comment by nao-pon** [comment]
The screenshot showss that PHP's execution account is not authorized to write to the "files" directory.

Also, it is not normally necessary for permissions of all files and directories to be 0777.

I think this problem is specific to your server. I think that you should learn more about web server operation.

**Comment by yangzhengpk** [comment]
OK,thx,I will try to learn more about centos 7  how to support elfinder,thank you for your reply.
