### ISSUE TITLE
AutoLoading of language files

### ISSUE THREAD

**Issue by Yves-K** [Studio-42/elFinder#2138]
Hello,
Using version 2.1.27
I'm trying to use language autoLoading that was introduced in core in version elFinder (2.1.26)
But really can't figure how it works ???

Is there any parameter to set ? where ?

Best regards

PS : could never thank you all enough for this MasterPiece

**Comment by nao-pon** [comment]
@Yves-K The setting is 'lang' only. However, since the previous language is stored in the browser, you need to initialize the settings on the Preferences tab of the help dialog to check the initial status.
