### ISSUE TITLE
Error creating bean with name 'connectorController': Injection of resource dependencies failed;

### ISSUE THREAD

**Issue by rajayogadharasan** [Studio-42/elFinder#2139]
Error creating bean with name 'connectorController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elfinderStorageFactory' defined in br.com.trustsystems.elfinder.support.spring.ElfinderRootConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [br.com.trustsystems.elfinder.service.ElfinderStorageFactory]: Factory method 'getElfinderStorageFactory' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elfinderStorage' defined in br.com.trustsystems.elfinder.support.spring.ElfinderRootConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [br.com.trustsystems.elfinder.service.Elfinder

Integrate with spring the error is coming

**Comment by nao-pon** [comment]
@rajayogadharasan I don't know about connectors other than the official PHP connector. Please ask the developer of the connector you are using.

Thanks.
