### ISSUE TITLE
[ui:cwd] sync problem of  col-width of table header when item add/remove

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2140]
in list view,

if user try to rename file list is not aligned
![image](https://user-images.githubusercontent.com/18566890/29207412-b7b68556-7ea3-11e7-910c-54c60d29be97.png)

and

rename short name to long name
![image](https://user-images.githubusercontent.com/18566890/29207318-5dccaea8-7ea3-11e7-8903-70e5ce5612dd.png)

or  

long name to short name
![image](https://user-images.githubusercontent.com/18566890/29207355-84da8790-7ea3-11e7-9504-ab0bb45fd116.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks! 👍
