### ISSUE TITLE
[ui:button] cmd dose not work when variants.length = 1

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2141]
my server is only available Zip function & Create Zip successfully.
![image](https://user-images.githubusercontent.com/18566890/29217350-1dd15e44-7ecf-11e7-8dda-4da5800f9adf.png)

But using toolbar create achieve it's not work when there are other types not available(when only Zip available)
![image](https://user-images.githubusercontent.com/18566890/29217532-b7c3309a-7ecf-11e7-8b8f-b07752cb2318.png)

**Comment by CodeLyokoXtEAM** [comment]
Also How Can I add different icon to 'Create New Folder' and 'Into New Folder'?

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks! 👍

**Comment by CodeLyokoXtEAM** [comment]
Also How Can I add different icon to 'Create New Folder' and 'Into New Folder'?

**Comment by nao-pon** [comment]
It is a problem of the theme. Please ask the developers of the theme, or adjust CSS by yourself.

**Comment by CodeLyokoXtEAM** [comment]
Got it.  👍 
`.elfinder .elfinder-button-icon-mkdir { background:url('../img/button/button-icon-Into-New-Folder.ico')  no-repeat;}`
adding to contextmenu.css

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon
unfortunately 
Both of them are defined is same in context menu
![image](https://user-images.githubusercontent.com/18566890/29241285-08d797f4-7f94-11e7-97c5-2bdbe629e16f.png)
![image](https://user-images.githubusercontent.com/18566890/29241293-3cae676a-7f94-11e7-94a7-a5099380d30c.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM OK, I'll add CSS class "elfinder-button-icon-mkdirin" to button <span>

**Comment by nao-pon** [comment]
I done at 09a26df32efcd2f5d434e00726d31cc85827c00a. (#2142)
