### ISSUE TITLE
[cmd] add cmds `select(all|none|invert)` & show `up` button as default

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2144]
there is back button.
But if user start in some path & go to up foder they must use tree view(back button is disabled becuz  it purpose goto previous folder)
so its nice to add folder up button
in windows 10 like this,
![image](https://user-images.githubusercontent.com/18566890/29247614-0ddce9c4-8026-11e7-8154-72c0288a0164.png)

**Comment by CodeLyokoXtEAM** [comment]
also how about these buttons 
![untitled](https://user-images.githubusercontent.com/18566890/29251688-03d562d4-8077-11e7-8445-6c3fba5fbb4d.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM "Home", "Up", and "Reload" buttons are not displayed by default. However, since the user can now control the button display, they should be displayed by default as well.

Then, the "Select all", "Select none", "Invert selection" button adds a new command and implements it.
