### ISSUE TITLE
Target folder "#" not found. BackPack Elfinder

### ISSUE THREAD

**Issue by grupaoem** [Studio-42/elFinder#2147]
Hi I have problem with upload files...
![image](https://user-images.githubusercontent.com/3195513/29354207-12de7aa2-826d-11e7-83df-c3d260bc8018.png)

In console i  have error

![image](https://user-images.githubusercontent.com/3195513/29361877-bf1b5fd0-8289-11e7-8a46-f912cbf1ef48.png)

**Comment by nao-pon** [comment]
The problem of "BackPack Elfinder" can not be solved here. Ask the developer of "BackPack Elfinder".

If you have problems with elFinder itself, please let me know with its contents.

Thanks.
