### ISSUE TITLE
What is the use of '_' parameter in el_finder's request ?

### ISSUE THREAD

**Issue by coderubyonrails** [Studio-42/elFinder#2148]
I saw url like 'htttp://localhost/el_finder/mint3.jpg?_=0.24507729591587601' in request. What is the use of '_' param ? Thankyou.

**Comment by nao-pon** [comment]
@coderubyonrails It is a simple trick to suppress browser caching and request to the server.

**Comment by coderubyonrails** [comment]
Awesome !!! Thank you @nao-pon
