### ISSUE TITLE
Log for the download functionality

### ISSUE THREAD

**Issue by w32gold** [Studio-42/elFinder#2154]
Hi,
The 'DOWNLOAD' log won't appear when I download something.

Have the codes below in the connector script... 
`'bind' => array(
        	'download mkdir mkfile rename duplicate upload rm paste edit' => 'logger'
    	),		
'roots' => array(..)`

Maybe this is a bug.
Thanks!

**Comment by nao-pon** [comment]
@w32gold This is not a bug. Please use 'file' instead 'download'.

e.g
```php
'bind' => array(
    'file' => array(function($cmd, $result, $args) {
        if (! empty($args['download'])) {
            $downloadInfo = $result['info'];
        }
    }),
),
```

**Comment by w32gold** [comment]
@nao-pon  .. thanks for the quick response.
I'm confused in the implementation of the 'download log'

I have here the options:

`$opts = array(
		// 'debug' => true,
		'bind' => array(
        	'mkdir mkfile rename duplicate upload rm paste edit file' => 'logger'
    	),
    	

		'roots' => array(
			// Items volume
			array(
				'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
				'path'          => '../files/',                 // path to files (REQUIRED)
				'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
				'trashHash'     => 't1_Lw',                     // elFinder's hash of trash folder
				'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
				'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
				'uploadAllow'   => array('all'),// Mimetype `image` and `text/plain` allowed to upload
				'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
				'accessControl' => 'access',                     // disable and hide dot starting files (OPTIONAL)
				'disabled'		=> array('help')
			),
			// Trash volume
			array(
				'id'            => '1',
				'driver'        => 'Trash',
				'path'          => '../files/.trash/',
				'tmbURL'        => dirname($_SERVER['PHP_SELF']) . '/../files/.trash/.tmb/',
				'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
				'uploadDeny'    => array('all'),                // Recomend the same settings as the original volume that uses the trash
				'uploadAllow'   => array('all'),// Same as above
				'uploadOrder'   => array('deny', 'allow'),      // Same as above
				'accessControl' => 'access',                    // Same as above
				'disabled'		=> array('help')
			)
		)
	);`

And I have this method to store the logs in a text file:

`function logger($cmd, $result, $args, $elfinder) {
	$user_ID = explode(",", $_SESSION['login_user']);

    $log = sprintf($user_ID[1].'::'.$user_ID[2]. ' --> [%s]:  %s', date('l jS \of F Y h:i:s A'), strtoupper($cmd));
    foreach ($result as $key => $value) {
        if (empty($value)) {
            continue;
        }
        $data = array();
        if (in_array($key, array('error', 'warning'))) {
            array_push($data, implode(' ', $value));
        } else {
            if (is_array($value)) { // changes made to files
                foreach ($value as $file) {
                    $filepath = (isset($file['realpath']) ? $file['realpath'] : $elfinder->realpath($file['hash']));
                    array_push($data, $filepath);
                }
            } else { // other value (ex. header)
                array_push($data, $value);
            }
        }
        $log .= sprintf(' %s(%s)', $key, implode(', ', $data));
    }
    $log .= "\n\n";

    $logfile = '../logs/log.txt';
    $dir = dirname($logfile);
    if (!is_dir($dir) && !mkdir($dir)) {
        return;
    }
    if (($fp = fopen($logfile, 'a'))) {
        fwrite($fp, $log);
        fclose($fp);
    }
}`

Where should I place your provided code snippet?
Thanks again..

**Comment by nao-pon** [comment]
Please logging value of $results, $args and implement by your selfs. Also I recommend to logging `zipdl`.

e.g.
```php
function debug() {
    $arg = func_get_args();
    ob_start();
    foreach($arg as $v) {
        var_dump($v);
    }
    $o = ob_get_contents();
    ob_end_clean();
    file_put_contents('.debug.txt', $o, FILE_APPEND);
}
```

```php
'file zipdl' => array(function($cmd, $result, $args) {
    debug(array('$cmd' => $cmd, '$result' => $result, '$args' => $args));
}),
```

**Comment by w32gold** [comment]
@nao-pon ... thank you for this.. 
closing this issue.
regards.

**Comment by pribeirojtm** [comment]
Hello, 

This closed issue may no be the appropriate place to ask this, but it is related with logging preview(or quicklook) functionality **for PDF** files. Somehow I can log preview (quickview) of other file types than pdf using:
```php
'bind' => array(
                'mkdir mkfile rename duplicate upload rm paste put get file url quicklook' => array($elFinderSimpleLogger, 'log'),
            ),
```
and command `get` is triggered and logged. But it seems the preview of PDF files are a "fake" preview, because the file is totally loaded into the iframe of quicklook and I can't catch the get of that file. No even passes in `$elFinderSimpleLogger->log($cmd, $result, $args, elFinder $elfinder)` method.

Do you have the same problem? Do you have any clue on how to log these pdf previews? It works for other file types...

Thanks.
