### ISSUE TITLE
How to add an ability to edit a restricted file

### ISSUE THREAD

**Issue by johnjohansen** [Studio-42/elFinder#2165]
Hello everybody!

I'd like to edit csv files using any of installed editors. How to exclude such type of file from restricted mimetypes (or include to allowed ones)?
Thank you in advance!

**Comment by nao-pon** [comment]
@johnjohansen Do you have problems that CSV files can not be uploaded? 
In that case, you can allow CSV file upload in the following way.

**connector roots options**
```php
'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
'uploadAllow'   => array('image', 'text/plain', 'text/csv'),// Mimetype `image` and `text/plain` allowed to upload
'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
```

**Comment by johnjohansen** [comment]
@nao-pon No, I've already solved this problem. Now I'd like to get ability to edit csv by ACE, CodeMirror etc.

**Comment by nao-pon** [comment]
What is the MIME-type of *.csv in your elFinder? "text/csv"?
![170824-202719](https://user-images.githubusercontent.com/1412630/29664528-e9510fca-890a-11e7-91da-04041078cb63.png)

If it is "text/csv" it will be editable by reading js/extras/editors.default.js or js/extras/editors.default.min.js.

**see**
- https://github.com/Studio-42/elFinder/blob/master/main.default.js
- https://github.com/Studio-42/elFinder/blob/master/elfinder.legacy.html

**Comment by johnjohansen** [comment]
Yes, the mime type of .csv is text/csv. Here is the screenshot, and there is no "edit file" link.
![csv](https://user-images.githubusercontent.com/3884034/29665555-3fe6f3fa-88dd-11e7-8e55-a6a140d1d9cf.png)

**Comment by nao-pon** [comment]
Please check with next steps.

+ Download 2.1.28 and Extract to web server
+ rename php/connector.minimal.php-dist to php/connector.minimal.php
+ change `'uploadAllow'   => array('image', 'text/plain'),` to `'uploadAllow'   => array('image', 'text/plain', 'text/csv'),`
+ check CSV file on elfinder.html of your web server

I tried this steps. It's no problems.

**Comment by johnjohansen** [comment]
@nao-pon Thank you! The problem is solved. Have a nice day!
