### ISSUE TITLE
Crop and Rotatate button not visible in image Resize dialog ?

### ISSUE THREAD

**Issue by coderubyonrails** [Studio-42/elFinder#2168]
When I run elfinder-2.1.27 front-end with elfinder gem as backend, I can't see crop and rotate button in image resize elfinder dialog. When I run php version of elfinder the buttons are seen but when I use elfinder in rails app using the elfinder gem buttons are not seen/created. Elfinder version I'm using is 2.1.27 with elfinder gem as backed connector.

**Comment by nao-pon** [comment]
@coderubyonrails I think that it is probably a problem of the gem backend, so please ask the developer of it.
