### ISSUE TITLE
Disable real path and use nice URL?

### ISSUE THREAD

**Issue by X-Coder** [Studio-42/elFinder#2169]
Hi, I'm trying to hide URLs like https://example.com/plugins/elfinder/php/connector.php?cmd=file&target=l1_MTlmMmN behind a nicer URL and make use of [Disable real file path from being shown](https://github.com/Studio-42/elFinder/wiki/Disable-real-file-path-from-being-shown) at the same time.

For example I want to use a rewrite rule in my .htaccess like:
```
RewriteRule ^media/(.*) plugins/elfinder/php/connector.php?cmd=file&target=$1  [QSA,L]
```
So the actual link should end up in http://example.com/media/l1_MTlmMmN.

For getFileCallback I already have it working, just by using file.hash and constructing my own url.

But how can I get the nice URL into the "Get info" dialog's link field or any other place that displays the long connector.php URL?

How can I configure elfinder, so this is possible?

**Comment by nao-pon** [comment]
@X-Coder You can use connector option [`bind`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind).

```php
'bind' => [
    '*' => [function($cmd, &$result, $args, $elfinder, $volume) {
        $addUrl = function(& $data) {
            foreach($data as $idx => $file) {
                if ($file['mime'] !== 'directory') {
                    $data[$idx]['url'] = 'http://example.com/media/' . $file['hash'];
                }
            }
        };
        ! empty($result['files']) && $addUrl($result['files']);
        ! empty($result['added']) && $addUrl($result['added']);
        ! empty($result['changed']) && $addUrl($result['changed']);
    }]
]
```

**Comment by X-Coder** [comment]
Thank you, your solution works perfect.
