### ISSUE TITLE
Clarify which "older versions" are vulnerable

### ISSUE THREAD

**Issue by greggles** [Studio-42/elFinder#2173]
Hello,

On the project page it says: "WARNING: IF YOU HAVE OLDER VERSIONS OF ELFINDER ON PUBLIC SERVERS, IT MAY CAUSE SERIOUS DAMAGE TO YOUR SERVER AND VISITED USER. YOU SHOULD UPDATE TO THE LATEST VERSION OR REMOVE IT FROM THE SERVER."

Can you update this in the README to clarify which older version (via release number of commit hash or date) is vulnerable?

Thanks.

**Comment by nao-pon** [comment]
@greggles We know that a security vulnerability exists in version 2.1.20 or earlier. I fixed README.md.

Thanks! 👍

**Comment by greggles** [comment]
Thanks for the quick clarification @nao-pon! I notice there's a typo in that commit (no space before the parenthesis: "OLDER(IN").

**Comment by nao-pon** [comment]
I done! :-)
