### ISSUE TITLE
UPLOAD tmp folder path settings

### ISSUE THREAD

**Issue by kevinstyle** [Studio-42/elFinder#2174]
Hi, elFinder team,
Is possible to set tmp folder path same as each upload dst folder path, rather than fixed path ? If this feature is supported, it will greatly reduce the upload time cost.

**Comment by nao-pon** [comment]
@kevinstyle There is an option `tmpPath` in LocalFileSystem driver. Please use it.

```php
'roots'  => array(
    array(
        'driver' => 'LocalFileSystem',
        'path'   => '/path/to/files/',
        'URL'    => 'http://localhost/to/files/',
        'tmpPath' => '/path/to/tmp'
    )
)
```
