### ISSUE TITLE
elFinder only shows photos nothing else

### ISSUE THREAD

**Issue by berk-can** [Studio-42/elFinder#2175]
```php
/**
 * Simple function to demonstrate how to control file access using "accessControl" callback.
 * This method will disable accessing files/folders starting from '.' (dot)
 *
 * @param  string    $attr    attribute name (read|write|locked|hidden)
 * @param  string    $path    absolute file path
 * @param  string    $data    value of volume option `accessControlData`
 * @param  object    $volume  elFinder volume driver object
 * @param  bool|null $isDir   path is directory (true: directory, false: file, null: unknown)
 * @param  string    $relpath file path relative to volume root directory started with directory separator
 * @return bool|null
 **/
function access($attr, $path, $data, $volume, $isDir, $relpath) {
	$basename = basename($path);
	return $basename[0] === '.'                  // if file/folder begins with '.' (dot)
			 && strlen($relpath) !== 1           // but with out volume root
		? !($attr == 'read' || $attr == 'write') // set read+write to false, other (locked+hidden) set to true
		:  null;                                 // else elFinder decide it itself
}


// Documentation for connector options:
// https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options
$opts = array(
	// 'debug' => true,
	'roots' => array(
		// Items volume
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '../files/',                 // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
			'trashHash'     => 't1_Lw',                     // elFinder's hash of trash folder
			'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
            'uploadAllow'   => array('all'),
            'uploadDeny'    => array('text/plain'),
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access',                     // disable and hide dot starting files (OPTIONAL)
            'uploadMaxSize' => 0
        ),
		// Trash volume
		array(
			'id'            => '1',
			'driver'        => 'Trash',
			'path'          => '../files/.trash/',
			'tmbURL'        => dirname($_SERVER['PHP_SELF']) . '/../files/.trash/.tmb/',
			'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
			'uploadDeny'    => array('all'),                // Recomend the same settings as the original volume that uses the trash
			'uploadAllow'   => array('image', 'text/plain'),// Same as above
			'uploadOrder'   => array('deny', 'allow'),      // Same as above
			'accessControl' => 'access',                    // Same as above
		)
	)
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();

```

My config code is above, but screen only shows images, videos are not shown (tested video is ~200MB)

What is wrong, should I add another config for it?

**Comment by cagatayyucelen** [comment]
exactly same issue
`'uploadAllow'   => array('image', 'video', 'video/mp4'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('allow', 'allow', 'allow'),      // allowed Mimetype `image` and `text/plain` only`

all these rows does not affecting anything. Even if i denied every mimetype i can still upload every file to elfinder and also seeing only images.

**Comment by nao-pon** [comment]
@berk-can , @cagatayyucelen Is it a plain elFinder that is not integrated with other projects? Also, please learn how to set uploadAllow, uploadDeny, uploadOrder.

- https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadorder

**Comment by berk-can** [comment]
@nao-pon I know how to use uploadAllor0w deny and order, and I tested it, so I can upload videos without problem,
But they are not showing on elFinder UI
Al thr permissions for folder and all files inside is given,
And it is plain Elfinder which has new javascript functions added,
Is it possible that newly added js files might have broken it?
Or are there any other configuration for filtering showed media in the elFinder?

**Comment by nao-pon** [comment]
@berk-can OK, please try the [Nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip). Current nightly has item filter in client side but it is disabled in default. Previous version has not item filter.

Please don't forget clearing browser caches before checking.

**Comment by nao-pon** [comment]
Please check if the data of the video item is included in the response data from the server. You can determine whether the problem is on the connector side or on the client side.

**Comment by berk-can** [comment]
@nao-pon wow how I couldnt think that
Now tried it, and server doesnt seem returning video at all there are only folder and image files in json's 'files' key  (I checked connector.minimal.php It is the one that sends files right?)

Now I will try nightly build

Thanks for the help

**Comment by berk-can** [comment]
@nao-pon I also tried elFinder 2.1 momentarily and it shows videos as well but also UI seems a bit different (new one has every files type on left up side) 
Maybe we will try using this version, thanks for the help again
