### ISSUE TITLE
Filename Filter

### ISSUE THREAD

**Issue by Flamenco** [Studio-42/elFinder#2176]
I need to filter filenames;  The client must specify the filter.  In some cases, it is fixed (**.txt) and in others the client has a picker.  I see the option for filtering in the server API, but that does not seem to work for my use case.

I see two options here.  
1. Send all the results to the client and then let the client filter.
2. The client passes a filter hint to the server when getting directory contents.

Do you have any thoughts on which option is better?  I am leaning towards the client option, as servers will not need to implement additional functionality.

**Comment by Flamenco** [comment]
I put this in filter, and it works perfectly...

                    if (file.mime !== 'directory' && self.options.filenameFilter) {
                        try {
                            if (!self.options.filenameFilter.test(file.name)) {
                                return null;
                            }
                        } catch (e) {
                            // Invalid filename filter or filter is not a RegExp
                            return null
                        }
                    }

Would you accept this for PR?

**Comment by nao-pon** [comment]
@Flamenco Thare is an option `validName` in client configurations. Please check out [this option](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L899-L910).

```javascript
	/**
	 * Additional rule to valid new file name.
	 * By default not allowed empty names or '..'
	 * This setting does not have a sense of security.
	 *
	 * @type false|RegExp|function
	 * @default  false
	 * @example
	 *  disable names with spaces:
	 *  validName : /^[^\s]+$/,
	 */
	validName : false,
```

**Comment by Flamenco** [comment]
Is that for saving new names, or filtering displayed names?

**Comment by nao-pon** [comment]
Oh, you needed a filter for display. `validName` is a filter for for saving new names. It may be better to use the callback on the connector side. I will write that method later.

**Comment by Flamenco** [comment]
I don't think a connector filter will work.  The client needs to dynamically set it.  Also, I have several server implementations that I would prefer not to mess with.  

We could offer both filters, client side and server side.  Yes?  If so, I will issue a PR and add some documentation.

**Comment by nao-pon** [comment]
**Simple example of the [`bind`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind) option**

```php
'bind' => [
    'open' => [function($cmd, &$result, $args, $elfinder, $volume) {
        if (!empty($result['cwd'])) {
            $cwdHash = $result['cwd']['hash'];
            $cwdPath = $volume->getPath($cwdHash); // you can filtering with $cwdPath
            if (!empty($result['files'])) {
                $files = [];
                foreach($result['files'] as $file) {
                    if ($file['phash'] === $cwdHash && $file['mime'] !== 'directory') {
                        $name = basename($volume->getPath($file['hash']));
                        debug($name);
                        if (preg_match('/\.txt$/i', $name)) {
                            $files[] = $file;
                        }
                    } else {
                        $files[] = $file;
                    }
                }
                $result['files'] = $files;
            }
        }
    }]
]
```

**Comment by nao-pon** [comment]
@Flamenco The client side would be more convenient if you need to set it dynamically. Please send PR. I would like to consider it.

**Comment by nao-pon** [comment]
see #2178
