### ISSUE TITLE
$ul.append in elFinder dialog(getFileCallback) failure

### ISSUE THREAD

**Issue by yuanstef** [Studio-42/elFinder#2181]
ul.append failure but div.append success,why?
My codes:
var elfinder = $('#elfinder').elfinder({
				// set your elFinder options here
				url: 'http://localhost:8080/elfinder-servlet-2/elfinder-servlet/connector', // connector URL
				resizable: false,
				uiOptions: {
	                    // toolbar configuration
	                    toolbar: [
	                        ["reload"],
	                        ["getfile"],
	                        //["duplicate", "rename", "edit", "resize"],
	                        ["quicklook", "info"],
	                        ["search"],
	                        ["view", "sort"]
	                    ]
	            },
				commandsOptions: {
					getfile: {
						oncomplete: 'destroy',
						folders: false,
						multiple: true
					}
				},
				getFileCallback: function (files) {
					var res = $('#getfile-results').empty();
					var $ul=$('#galleryFiles');
					var str='<li>sdfsdf</li>';
					$.each(files, function (i, f) {
						//res.append(str);//success
						//$ul.append(str);//error
						
					});
					$('#elfinder').dialog("close");
				}
			}).dialog({
				title: "文件选择",
				resizable: true,
				width: 920,
				height: 500
			});
Errors:
Uncaught TypeError: Cannot read property 'height' of null
    at HTMLDivElement.<anonymous> (elfinder.full.js:14625)
    at HTMLDivElement.a (jquery.flot.resize.min.js:1)
    at HTMLDivElement.dispatch (jquery-1.7.2.min.js:3)
    at HTMLDivElement.i (jquery-1.7.2.min.js:3)
    at Object.trigger (jquery-1.7.2.min.js:3)
    at HTMLDivElement.<anonymous> (jquery-1.7.2.min.js:3)
    at Function.each (jquery-1.7.2.min.js:2)
    at init.each (jquery-1.7.2.min.js:2)
    at init.trigger (jquery-1.7.2.min.js:3)
    at HTMLDivElement.<anonymous> (jquery.flot.resize.min.js:1)

**Comment by nao-pon** [comment]
@yuanstef At first, Version of jQuery does not satisfy usage requirement (jQuery> = 1.8). And please check without "jquery.flot.resize".

**Comment by yuanstef** [comment]
@nao-pon Thank you very much for your reply!
I did as you told me,but it still failed.
I use "div.append" instead.It worked well.
Thank you all the same.
