### ISSUE TITLE
Is it possible to Files locked while editing? 

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2184]
If someone editing text or image another user delete it that edited text is impossible to save. 
(like target folders locked while uploading) 
![screenshot_20170901-114627](https://user-images.githubusercontent.com/18566890/29957462-3b8b84fe-8f0b-11e7-956d-9480eda50266.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Item locking while editing is difficult. However, it is not a good to lose edits, so I will make to able to "Save As" when saving fails.

**Comment by CodeLyokoXtEAM** [comment]
How about editing window send every 15s a request lockdown file 20s or something.
But I think there is security issues may be begun. Someone create a bot and can lockdown files in server.
So encrypted request must send to server on time depend.

**Comment by CodeLyokoXtEAM** [comment]
And also this future can enable/disable

**Comment by nao-pon** [comment]
"elFinder >= 2.1.29" can be "Save As" if saving failed.
