### ISSUE TITLE
.psd & .psb are same type tag in elfinder

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2185]
.psd & .psb both `'Content-Type:image/vnd.adobe.photoshop'` identify in browser.
So in elfinder its detect as psd.
Is there any method to we define file type by .file_type in elfinder ?
(Only if we define it. Else get file type by browser define type)
Is it possible to change icons that defined types? 
![image](https://user-images.githubusercontent.com/18566890/29997007-bb546ec8-9026-11e7-92f8-7c8723e62c57.png)

edited:-
![image](https://user-images.githubusercontent.com/18566890/29997024-16561c54-9027-11e7-899b-d94596663aa2.png)

**Comment by CodeLyokoXtEAM** [comment]
Also is there any method to change icon tag file type (like I want to only .psd files icon tag is blue or add tag as png given by me. Others are different colors or different image)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM There is an option [`additionalMimeMap`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#additionalMimeMap) to adds custom mime-type.

```php
'additionalMimeMap' => array(
    'pdb:image/vnd.adobe.photoshop' => 'image/x-photoshop' // '[ext]:[Detected MIME Type]' => '[Normalized MIME Type]'
),
```

so ".psb" file icon has CSS class "elfinder-cwd-icon-image elfinder-cwd-icon-x-photoshop" you can control style completely under CSS.

**Comment by CodeLyokoXtEAM** [comment]
is there any option to "I want to only .psd files icon tag is blue or add tag as png given by me. Others are different colors or different images"

**Comment by nao-pon** [comment]
It can be controlled with CSS.

e.g.
```css
.elfinder-cwd-icon-image.elfinder-cwd-icon-vnd-adobe-photoshop::before {
	background-color: blue;
}
```
