### ISSUE TITLE
open elFinder dialog in IE8 

### ISSUE THREAD

**Issue by yuanstef** [Studio-42/elFinder#2186]
I can not understand that i use click enven of "a" tag to open elFinder dialog in IE8，it doesn't work.
It took my long time to debug.
Then i use Button instead,and it worked well.
It's amazing~!
The codes like this:
$("#a.id or button.id").click(function (e) {
     //open elFinder...
})

**Comment by nao-pon** [comment]
@yuanstef Thank you for your Tips! By the way, since I have a large cost to support IE 8, I'm thinking to remove IE 8 from the support targets in the near future, so please be aware.

Thanks!
