### ISSUE TITLE
Disable toolbar and tree view

### ISSUE THREAD

**Issue by ford442** [Studio-42/elFinder#2188]
Hi,
I am trying to configure the UI to remove buttons or the whole toolbar as well as the tree view leaving just the drag/drop area, but I am stuck as to where to make the changes.
I tried adding the  " ui : ['toolbar', 'path', 'stat'], " option to remove the 'tree' view, but it didn't work where I tried to add it. Shouldn't that prevent the tree ui plugin from loading?

**Comment by nao-pon** [comment]
@ford442 It be able to hide `toolbar` and `tree` with ...
```javascript
ui : ['path', 'stat'],
```
Live demo is [here](http://jsbin.com/kafolom/edit?js,output).

**Comment by ford442** [comment]
It is working now. Thanks! It took closing my browser fully and reloading to get the altered .js going.
