### ISSUE TITLE
quicklook has suboptimal positioning

### ISSUE THREAD

**Issue by flack** [Studio-42/elFinder#2191]
The position of the quicklook overlay is always relative to the browser window. So when you have elfinder in an overlay that is not exactly centered in the middle of the screen, the position is such that only a part of the overlay is visible. See here for example:

![elf1](https://user-images.githubusercontent.com/425166/30055739-a577983a-9230-11e7-9be0-2556a1a4c1a4.png)

![elf2](https://user-images.githubusercontent.com/425166/30055746-aa468b5a-9230-11e7-9023-b6a37327aa81.png)

It would be better if the overlay would be positioned relative to the elfinder root node, or alternatively, if the overlay would be attached to the document body, not the elfinder root node

**Comment by nao-pon** [comment]
@flack There is no problem if it is placed flat on the page, so I'll add an option to deal with this problem.

**commandsOptions.quicklook.coutain
```javascript
quicklook : {
	autoplay : true,
	width    : 450,
	height   : 300,
	// Maximum characters length to preview
	textMaxlen : 2000,
	// quicklook window must be contained in elFinder node on window open (true|false)
	contain : false,
	// preview window into NavDock (true|false)
	docked   : false,
	// Docked preview height ('auto' or Number of pixel) 'auto' is setted to the Navbar width
	dockHeight : 'auto',
	// media auto play when docked
	dockAutoplay : false,
	// MIME types to use Google Docs online viewer
	// Example ['application/pdf', 'image/tiff', 'application/vnd.ms-office', 'application/msword', 'application/vnd.ms-word', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
	googleDocsMimes : [],
	// URL of hls.js
	hlsJsUrl : '//cdnjs.cloudflare.com/ajax/libs/hls.js/0.7.11/hls.min.js',
	// URL of dash.all.js
	dashJsUrl : '//cdnjs.cloudflare.com/ajax/libs/dashjs/2.5.0/dash.all.min.js',
	// URL of run_prettify.js
	prettifyUrl : '//cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js'
},
```

**Comment by nao-pon** [comment]
@flack Thanks! 👍

**Comment by flack** [comment]
Looks good, thanks!
