### ISSUE TITLE
quicklook: Strange behavior with next/previous arrows

### ISSUE THREAD

**Issue by flack** [Studio-42/elFinder#2192]
When the quicklook overlay is open, and you click anywhere on an empty area of elfinder cwd, it is treated as a next or previous arrow click, depending on whether you click left or right of the overlay. for example:

![elf](https://user-images.githubusercontent.com/425166/30068013-bed437b2-925c-11e7-9c6d-5d895cb45de3.png)

If I click right where my mouse cursor is in the screenshot, it behaves as if I click on the right arrow

**Comment by nao-pon** [comment]
@flack This behavior is due to the implementation of the old design. Currently this behavior is not necessary so I will fix this.
