### ISSUE TITLE
Context menu Trash/RM issue

### ISSUE THREAD

**Issue by hrnmodi** [Studio-42/elFinder#2193]
When I remove rm from context menu it automatically removes Info Trash button from files menu(see image). Is there any way trash button stay as it is and I can removed delete from trash(see image)?
![image](https://user-images.githubusercontent.com/6830265/30110452-c09cc430-9327-11e7-8987-e36e24c77d40.png)
![image](https://user-images.githubusercontent.com/6830265/30110469-d1adcd78-9327-11e7-895b-67d353520d1d.png)

**Comment by nao-pon** [comment]
@hrnmodi Since the "into trash" command is part of the "rm" command, it is not currently possible to disable only the "rm" command.

Thanks.
