### ISSUE TITLE
Ftp server with Virtual users and the ftp owner configuration option

### ISSUE THREAD

**Issue by arubalucalasagni** [Studio-42/elFinder#2194]
Many ftp servers can be accessed by a **Virtual User**.
For Example with [pure-ftpd](https://www.pureftpd.org/project/pure-ftpd) you can configure an ftp user that it isn't a system user. In that case the user logged is different from the owner of the files but the virtual user could have the write permissions, i.e. it could be menage the file like the real owner, see [Virtual user](https://download.pureftpd.org/pub/pure-ftpd/doc/README.Virtual-Users).
We spotted some bugs when we tried to use the Ftp Drive with a Virtual User.
To show this problems I have prepared a ftp server to be accessed both a System User and a Virtual User that has the same permissions (it is like an alias of the owner) and after I have configured a connector with four ftp drivers, changing the owner option and creating a lot of files with different permissions and owners.

### 1. Ftp Driver, Virtual User, option owner = true
![ftpdrivervirtualuserownertrue2](https://user-images.githubusercontent.com/24244107/30116586-3bc62b7e-931e-11e7-80c7-9d3dcf9a21af.png)
Here we don't have the write permissions for the owner files but actually we could write them. 
Oddly it seems that we have write permissions for this two root objects but it's not true:
1. F755root.txt
2. F644root.txt
  
### 2. Ftp Driver, Virtual User, option owner = false
![ftpdrivervirtualuserownerfalse2](https://user-images.githubusercontent.com/24244107/30116948-23401ea6-931f-11e7-8195-d9c58685f36d.png)
Here we have the same problems with the owner files, we could write them but we cannot. 
Now the problem with the root files is disappeared.
There is a little green icon in any item. 

### 3. Ftp Driver, user Owner, option owner = true
![ftpdriverrealuserownertrue2](https://user-images.githubusercontent.com/24244107/30117406-6672310e-9320-11e7-8a9a-1cf812a94e34.png)
Here is the best configuration but it's not always possible use a system user to make an ftp access.
There is the same bug with the first configuration:
1. F755root.txt
2. F644root.txt

### 4. Ftp Driver, user Owner, option owner = false
![ftpdriverrealuserownerfalse3](https://user-images.githubusercontent.com/24244107/30118209-b9decab2-9322-11e7-9f56-926968dce1a6.png)
Here we aren't able to create new files or folders even if we are in a folder with write and read permissions nevertheless we can edit or rename the existing files.
There is a little green icon in any item. 

It's not clear the usage of the option owner it seems that it has to be set to True always.

```php
array(
    'driver'        => 'FTP',
    'host'          => 'localhost',
    'user'          => 'eluser',
    'pass'          => 'elpass',
    'port'          => 21,
    'mode'          => 'passive',
    'path'          => '/',
    'timeout'       => 10,
    'owner'         => true,
    'tmbPath'       => '',
    'tmpPath'       => '',
    'dirMode'       => 0755,
    'fileMode'      => 0644
)
```
We are fixing this problems by ourself, I will make you a pull request as soon as possible.

**Comment by nao-pon** [comment]
Closes with #2195 @arubalucalasagni Thank you so match! 👍
