### ISSUE TITLE
Open picture / PDF / ... in Windows System

### ISSUE THREAD

**Issue by Ange7** [Studio-42/elFinder#2197]
hey all 

How we can open picture from elFinder in Windows System ? Not in browser.

Thank you

Alex

**Comment by nao-pon** [comment]
@Ange7 There is an opntion `dispInlineRegex`(https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#dispinlineregex) of connector roots options.

```php
'dispInlineRegex' => '^$',
```

Whether to download the file or open it in the application depends on the setting of the browser.
