### ISSUE TITLE
AutoResize/AutoRotate/Watermark fail if php fileinfo module not loaded

### ISSUE THREAD

**Issue by dleffler** [Studio-42/elFinder#2198]
These 3 plugins assume the mime_content_type() call will succeed, which is only true when the php fileinfo module is loaded. Furthermore, most alternate mime_content_type() functions do not work since they use the passed filetype/extension and the plugin receives the temp file name $src and acts on it...however the passed $name does contain the filetype.

**Comment by nao-pon** [comment]
@dleffler Thanks! 👍
