### ISSUE TITLE
elFinder is not php v7.2 compliant

### ISSUE THREAD

**Issue by dleffler** [Studio-42/elFinder#2199]
There are several calls to create_function() in elFinder.class.php and elFinderVolumeDrive.class.php. This function is deprecated in php v7.2.

**Comment by nao-pon** [comment]
@dleffler Yes, I know. Since anonymous functions can not be used for PHP 5.2 compliance, I will replace them with fixed functions.

**Comment by nao-pon** [comment]
@dleffler Thanks! 👍
