### ISSUE TITLE
PHP 7.2 Fatal error because of duplicate imagecreatefrombmp()

### ISSUE THREAD

**Issue by wallenium** [Studio-42/elFinder#2200]
In PHP 7.2, a new function imagecreatefrombmp() was introduced: http://php.net/manual/de/function.imagecreatefrombmp.php

This function is already used in following file:
> PHP Fatal error:  Cannot redeclare imagecreatefrombmp() in ../core/libraries/elfinder/php/libs/GdBmp.php on line 70

Maybe use the PHP core function if it does the same as the custom one, i did not check it. My automatic linter highlighted this fatal. Not even sure if this file is still used.

**Comment by nao-pon** [comment]
@wallenium Since GdBmp.php is loaded only if `imagecreatefrombmp ()` is not defined, there is no problem. However, I fix it so that no error occurs with the Linter.

**Comment by nao-pon** [comment]
@wallenium Thanks! 👍

**Comment by wallenium** [comment]
@nao-pon Thanks a lot for the quick fix.
