### ISSUE TITLE
v.2.1 /tmp openbasedir error

### ISSUE THREAD

**Issue by stalker780** [Studio-42/elFinder#2205]
Many shared hostings have problems with openbasedir and /tmp folder

WARNING: finfo_file(): open_basedir restriction in effect. File(/tmp/phpoIyUCq) is not within the allowed path(s): (/var/www/website/data:.) in elFinder.class.php line 2123.

WARNING: finfo_file(/tmp/phpoIyUCq): failed to open stream: Operation not permitted in elFinder.class.php line 2123.

WARNING: file_get_contents(): open_basedir restriction in effect. File(/tmp/phpoIyUCq) is not within the allowed path(s): (/var/www/website/data:.) in elFinder.class.php line 2891.

WARNING: file_get_contents(/tmp/phpoIyUCq): failed to open stream: Operation not permitted in elFinder.class.php line 2891.

WARNING: is_readable(): open_basedir restriction in effect. File(/tmp/phpQNdVDX) is not within the allowed path(s): (/var/www/website/data:.) in elFinderVolumeDriver.class.php line 4195.

This happens when I try to resize an image and press Save As.

Is it possible to use commonTempPath instead of sys_get_temp_dir() and tmpfile()?

**Comment by nao-pon** [comment]
@stalker780 Thanks! 👍
