### ISSUE TITLE
Error on elFinder 2.1.28

### ISSUE THREAD

**Issue by camgullo** [Studio-42/elFinder#2209]
I have looked around at other people having this issue but haven't seen a definite answer. 

I installed elFinder 2.1.28 and renamed the connector files. I get this error saying,
"Invalid backend response.
Data is not JSON."
With the contents of the connector files displayed after the error message. Here is a screenshot, 
<img width="1438" alt="screen shot 2017-09-18 at 11 17 36 pm" src="https://user-images.githubusercontent.com/3457784/30574384-9651bbb4-9cc7-11e7-9c74-cafc8eaa54c6.png">

Thanks,
Cam

**Comment by CodeLyokoXtEAM** [comment]
Elfinder run only in server which can simulate php functions. Not directly run simple double click on elFinder.Src.Html if you on windows platform you must download wamp server or xamp application to simulate php functions.

> Server
> 
> Any web server
> PHP 5.2+ (Recommend PHP 5.4 or higher) 

I think this must help for you.

**Comment by CodeLyokoXtEAM** [comment]
That error massage is show that conector.php dosen't simulate correctly in your server.
