### ISSUE TITLE
parent dialog boox does't close 

### ISSUE THREAD

**Issue by RJRahevar** [Studio-42/elFinder#2211]
hello sir,,

i have use elfinder.js Version 2.1.28 (2017-08-17) in our project but some issue in my site
i have submit file and fite below function 
i have use this code dialog into dialog box
>  parent.dialog.elfinderdialog('close');

doest not work 
please suggest me

**Comment by nao-pon** [comment]
@RJRahevar Have you got any JavaScript error?

**Comment by nao-pon** [comment]
Please let me know the minimum test case that can reproduce this problem.

**Comment by RJRahevar** [comment]
parent.dialog is undefined error 
and same case i have use  elfinder.js Version 2.1 dialog box close ..
working currectly

**Comment by nao-pon** [comment]
I'm not sure since your code is not presented, but so it can close the dialog at the completion of upload with the following code.

```javascript
var fm = $('#elfinder').dialogelfinder(opts).elfinder('instance');
fm.bind('upload', function(e) {
    e.data && e.data.added && e.data.added.length && fm.getUI().dialogelfinder('close');
});
```
