### ISSUE TITLE
Search Command doest not work ElFinder.Net

### ISSUE THREAD

**Issue by RJRahevar** [Studio-42/elFinder#2214]
hiiii
**down source code of ElFinder.Net Connector and elFinder ASP.NET Connector and set "search" to toolbar but it show " Unknown command". I can't find any document to implement command search. I see demo on elfinder.org and they can search with return of json, but i don't know how to create correct json on server. Can u help me ?**

**Comment by nao-pon** [comment]
@RJRahevar Please check the Wiki - https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#search .
