### ISSUE TITLE
Set maximum root size

### ISSUE THREAD

**Issue by camgullo** [Studio-42/elFinder#2215]
Hello,

Is there a way to set a size limit on how much MB can be in the root folder?

Thanks,
Cam

**Comment by nao-pon** [comment]
@camgullo Does #1657 help you?

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon 
Is it possible to show in ui percentage or capacity like this.
![1506083960267-1424961458](https://user-images.githubusercontent.com/18566890/30744767-3aa1d3c4-9fc1-11e7-82d7-f62004df4c54.jpg)

**Comment by camgullo** [comment]
In regards to #1657 
I tried implementing the connector files but I am getting error,
Invalid backend response.
Error occurred on the server side.
HTTP error 500

In browser dev console I get, 
/php/connector.minimal.php?cmd=open&target=l1_Lw&init=1&tree=1&_=1506098053110 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by nao-pon** [comment]
@camgullo Is there a missing callback argument? What about next...

```php
function preCheckDiskFull($cmd, $args, $elfinder, $volume) {
```

```php
function checkDiskFull($cmd, $result, $args, $elfinder, $volume) {
```
