### ISSUE TITLE
Dropbox Configuration

### ISSUE THREAD

**Issue by kkotowick** [Studio-42/elFinder#2220]
I need to update my elFinder configuration since Dropbox stopped supporting APIv1. However, I can't seem to find any info in the elFinder wiki about how to configure it for Dropbox. Would it be possible to include a minimal configuration example somewhere for connecting to a Dropbox account?

Thanks!

**Comment by nao-pon** [comment]
@kkotowick Please check source code comment of [connector.minimal.php-dist](https://github.com/Studio-42/elFinder/blob/2.1/php/connector.minimal.php-dist).

```php
// // Required for Dropbox network mount
// // Installation by composer
// // `composer require kunalvarma05/dropbox-php-sdk`
// // Enable network mount
// elFinder::$netDrivers['dropbox2'] = 'Dropbox2';
// // Dropbox2 Netmount driver need next two settings. You can get at https://www.dropbox.com/developers/apps
// // AND reuire regist redirect url to "YOUR_CONNECTOR_URL?cmd=netmount&protocol=dropbox2&host=1"
// define('ELFINDER_DROPBOX_APPKEY',    '');
// define('ELFINDER_DROPBOX_APPSECRET', '');
```

**Comment by kkotowick** [comment]
Thanks, I understand now. Is there a way to use a pre-existing API token though, instead of having to register it?

**Comment by nao-pon** [comment]
@kkotowick Example of roots array()

```php
array(
	'driver' => 'Dropbox2',
	'path' => '/',
	'access_token' => 'YOUR ACCESS TOKEN',
)
```
