### ISSUE TITLE
Model folder path to view

### ISSUE THREAD

**Issue by joaocarvaaalho** [Studio-42/elFinder#2223]
Is it possible to create abstract / imaginary directories? For my application the files are saved on the server with different names and paths than I want to show for display. My structure is developed with a logic that involves the database so I need it. Would you help me? Thank you in advance.

**Comment by nao-pon** [comment]
@joaocarvaaalho I am developing a system that works with XOOPS of CMS. The driver's source code for that may help you.

- https://github.com/nao-pon/xelfinder/blob/master/xoops_trust_path/modules/xelfinder/plugins/xelfinder_db/driver.class.php
