### ISSUE TITLE
Bug in mobile browser

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2224]
In mobile browser,
Open folder
Create new folder but not complete the action that mean without entering folder name click back button in device and goto back folder.
first its bg color is dark & click workspace then look like this. 
![screenshot_20170926-200510](https://user-images.githubusercontent.com/18566890/30866277-61b1bbc2-a2f6-11e7-9658-83090731790c.png)

**Comment by CodeLyokoXtEAM** [comment]
Also there is another bug. This bug is presented before but I get it now how it present. 
Open folder that only have one sub folder.
Then create new folder but not complete the action and click workspace.
Select all square is automatically ticked but nothing selected.
![screenshot_20170926-202036](https://user-images.githubusercontent.com/18566890/30866929-322e409e-a2f8-11e7-9561-617163be8c92.png)

**Comment by CodeLyokoXtEAM** [comment]
Open folder only have four sub folder or files.
Then select one of them and select into new folder but not complete the action.
Then select other folders without removing selected file tick.
![screenshot_20170926-205319](https://user-images.githubusercontent.com/18566890/30868608-c7d2b478-a2fc-11e7-8f65-d074a3adccd9.png)
![screenshot_20170926-205324](https://user-images.githubusercontent.com/18566890/30868626-cfba84cc-a2fc-11e7-9dcb-3e3d4e27c104.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks! 👍
