### ISSUE TITLE
bug when cropping .jpeg pictures

### ISSUE THREAD

**Issue by q3dm0** [Studio-42/elFinder#2225]
found a small bug when cropping a picture is jpeg format, its size increases (KB, MB), with png everything is fine
![image001](https://user-images.githubusercontent.com/6460600/30903303-f38271a6-a376-11e7-8056-b65ac9a1ab3c.png)
![image003](https://user-images.githubusercontent.com/6460600/30903306-f3873cd6-a376-11e7-8a92-9474c4934626.png)
![image005](https://user-images.githubusercontent.com/6460600/30903304-f385e3fe-a376-11e7-88da-95e1c5d0c62b.png)
![image006](https://user-images.githubusercontent.com/6460600/30903305-f386404c-a376-11e7-9739-32c778e0852a.jpg)
![image007](https://user-images.githubusercontent.com/6460600/30903307-f3983504-a376-11e7-99d8-7a8a53b1acab.png)

**Comment by nao-pon** [comment]
@q3dm0 The file size of the JPEG file depends on the quality at the time of saving. I changed the value set by the user to specification to store in the browser.(e7c51f39771e8471d09e3ece904b2dd800a9e3ef)

Thanks!

**Comment by q3dm0** [comment]
very thanks to you!

**Comment by q3dm0** [comment]
Hi! I see the bug with the image quality turns out to be when is saved at 100%, the image even with a smaller resolution from the original takes a size more approximately in double, but when using for example the image quality of 90%, everything is fine
