### ISSUE TITLE
upload some files, input some words search->x，browser list files doubled!

### ISSUE THREAD

**Issue by jeremyzhou2001** [Studio-42/elFinder#2229]

**Comment by nao-pon** [comment]
@jeremyzhou2001 Can you reproduce similar problems on our demo site? If there is no problem on the demo site, there may be a problem with the connector you are using.

**Comment by jeremyzhou2001** [comment]
@nao-pon how cloud i check the elfinder version?
![11111](https://user-images.githubusercontent.com/29558548/31007432-34e30634-a533-11e7-8f37-ba88eda88ad3.png)

**Comment by nao-pon** [comment]
Please check elfinder.(full|min).js loading on web page. If you are using a PHP connector, you can find the connector version in elfinder.class.php in the php directory.

**Comment by jeremyzhou2001** [comment]
@nao-pon 
i just modify the file elfinder.full.js, black bold charactors, just  fix this problem
but brings more problem on search function 

abort = function() {
	input.data('inctm') && clearTimeout(input.data('inctm'));
	input.val('').blur();
	if (result || incVal) {
		result = false;
		incVal = '';
		fm.lazy(function() {
			**fm.trigger('incsearchend');**
		});
	}

**Comment by jeremyzhou2001** [comment]
/*!
 * elFinder - file manager for web
 * Version 2.1.16 (2.1-src Nightly: 3f9f47a) (2016-10-25)
 * http://elfinder.org
 *
 * Copyright 2009-2016, Studio 42
 * Licensed under a 3-clauses BSD license
 */

**Comment by nao-pon** [comment]
@jeremyzhou2001 Since elFinder you are using is old, please check it with latest version or [latest nightly](https://github.com/Studio-42/elFinder/archive/2.1.zip).
