### ISSUE TITLE
Managing the user wise access with number of files and storage limitation

### ISSUE THREAD

**Issue by mehuljogi** [Studio-42/elFinder#2232]
I am new for elfinder, have just configure normal configuration,But I want to make user wise folder with managing the database and with user-wise access and also number of files and storage limitation.

can you guide me or give me some ref-feral links so will checkout it.

**Comment by CodeLyokoXtEAM** [comment]
How about this for storage limitations
https://github.com/Studio-42/elFinder/issues/2215

**Comment by mehuljogi** [comment]
your above ans will be work for storage limitations
can I store the all activity into the database, means like which user have created,edited or deleted which folder and files?

**Comment by mehuljogi** [comment]
I am using below code to insert the activity into the database can you let me know what I am doing wrong to insert the data into the database, actually my function is not calling which is NewNotification under condition

`<?php
@session_start();
include_once '../../functions/global.php';
$loggedUser = $_SESSION['user'];
class elFinderSimpleLogger {

    /**
     * Log file path
     *
     * @var string
     * */
    protected $file = '';
    protected $loggedUser = '';

    /**
     * constructor
     *
     * @return void
     * @author Dmitry (dio) Levashov
     * */
    public function __construct($path, $loggedUser) {
        $this->file = $path;
        $this->loggedUser = $loggedUser;
        $dir = dirname($path);
        if (!is_dir($dir)) {
            mkdir($dir);
        }
    }

    /**
     * Create log record
     *
     * @param  string   $cmd       command name
     * @param  array    $result    command result
     * @param  array    $args      command arguments from client
     * @param  elFinder $elfinder  elFinder instance
     * @return void|true
     * @author Dmitry (dio) Levashov
     * */
    public function log($cmd, $result, $args, $elfinder) {
        $log = $cmd . ' [' . date('d.m H:s') . "]\n";

       
        if (!empty($cmd) && $cmd == 'mkfile') {
            foreach ($result['changed'] as $file) {
                $log = $this->loggedUser['fname'] . ' ' . $this->loggedUser['lname'] . " has create new file: " . $elfinder->realpath($file['hash']);
            }
            NewNotification($this->loggedUser['idd'], 1, '', $log, 'NOTREAD');
        }

        $this->write($log);
    }

    /**
     * Write log into file
     *
     * @param  string  $log  log record
     * @return void
     * @author Dmitry (dio) Levashov
     * */
    protected function write($log) {
        if (($fp = @fopen($this->file, 'a'))) {
            fwrite($fp, $log . "\n");
            fclose($fp);
        }
    }

}

$myLogger = new elFinderSimpleLogger('../files/temp/log-2.txt', $loggedUser);
$link = $_GET['link'];
$httppath = $_GET['httppath'];

$opts = array(
        // 'debug' => TRUE,        
        'bind' => array(
            'file mkdir mkfile rm rename duplicate paste upload get put' => array($mylogger, 'log'),
        ),
        'roots' => array(
            array(
                'driver' => 'LocalFileSystem', // driver for accessing file system (REQUIRED)                
                'alias' => 'My Documents',
                'path' => $link, // path to files (REQUIRED)
                'URL' => $httppath, // URL to files (REQUIRED)
                'trashHash' => 't1_Lw', // elFinder's hash of trash folder
                'winHashFix' => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too                
                'accessControl' => 'access', // disable and hide dot starting files (OPTIONAL)
                'attributes' => array(
                    array(
                        'pattern' => '/.+/', // Read+Write Settings for all Folders and Files
                        'read' => TRUE,
                        'write' => TRUE,
                        'locked' => FALSE
                    )
                ),
            

> )

        )
    );

$connector = new elFinderConnector(new elFinder($opts));
$connector->run();`

**Comment by nao-pon** [comment]
@mehuljogi There is a related issue "[Using LocalFileSystem together with MySQL](https://github.com/Studio-42/elFinder/issues/1808)". Please check out it.

**Comment by mehuljogi** [comment]
Thanks nao-pon, I got the solution. I am just doing silly mistake. I have to just decalare $loggedUser as global under the log function so I can access my data into the log function.
