### ISSUE TITLE
bug when cropping .jpeg pictures

### ISSUE THREAD

**Issue by q3dm0** [Studio-42/elFinder#2235]
Hi! I see the bug with the image quality turns out to be when is saved at 100%, the image even with a smaller resolution from the original takes a size more approximately in double, but when using for example the image quality of 90%, everything is fine

**Comment by nao-pon** [comment]
@q3dm0 This is not a bug. In JPEG image editing, JPEG images are once decoded and then recompressed at the specified compression rate. The saved size may be larger than the original image, but this is a JPEG format specification.

**Comment by mkvdrat** [comment]
thanks

**Comment by Kadetff** [comment]
@nao-pon In other image editors (for example, Microsoft image editor) the saved image size after cropping always is less than the original size. Examples in the attachement:
Original-image: 129kB, 848*310px
Cropped-by-microsoft: 101kB, 800*292px
Cropped-by-Elfinder: 327kB, 800*292px
![cropped_by_microsoft](https://user-images.githubusercontent.com/32481232/31119301-26f5b46e-a839-11e7-9ea5-81aa83153004.jpg)
![cropped_by-elfinder](https://user-images.githubusercontent.com/32481232/31119303-27068690-a839-11e7-9514-b268ce7dd304.jpg)
![original_size](https://user-images.githubusercontent.com/32481232/31119302-26f92ee6-a839-11e7-9291-4254762763d5.jpg)

**Comment by nao-pon** [comment]
The size of JPEG depends on the quality. The original JPEG size does not matter. Please adjust the quality to the desired size.
