### ISSUE TITLE
Is there a way to change wording in alert box?

### ISSUE THREAD

**Issue by evenloooo** [Studio-42/elFinder#2236]
Hi all,

I would like to change wording in alert box, as below:
![image](https://user-images.githubusercontent.com/9351031/31218889-46faad2a-a981-11e7-93fc-d82f7a02e14b.png)

I want to change `File named "aaa.txt" already exists.` to `Path "/uploads/xxx/aaa.txt" already exists.`.

Thanks.

**Comment by nao-pon** [comment]
@evenloooo Is it OK to include the path when uploading to other than CWD?
