### ISSUE TITLE
Always same filename on upload with iOS devices

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2238]
This bug still present.
https://github.com/Studio-42/elFinder/issues/1379

I recently try to upload images in iphone. always every images name is 'Images.jpeg' & Overwrite one another and only upload last image of list.

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM I tested iOS 11.0.1. That was no problem. However, it may vary depending on the iOS version. What is the exact file name? "images.jpeg" or "image.jpeg"?

**Comment by CodeLyokoXtEAM** [comment]
Sorry its 'Image.jpeg'

**Comment by CodeLyokoXtEAM** [comment]
I'm not try it on demo site. Only download https://github.com/Studio-42/elFinder/archive/master.zip and set connector.minimal.php and upload files. I didn't know ios version. I try it in safari browser.

**Comment by nao-pon** [comment]
OK, In currently only target "image.jpg" so I'll fix this problem by add "image.jpeg" to target.
