### ISSUE TITLE
Basic auth with Edge browser

### ISSUE THREAD

**Issue by hintau** [Studio-42/elFinder#2241]
The login button on the demo (https://studio-42.github.io/elFinder) doesn't work on Microsoft Edge or IE. When I add the basic auth example to my own install, IE works (even though the login prompt is behind the main window) but still no luck with Edge.

I know this is likely a microsoft issue but any suggestions on how to get this working?

Thanks

**Comment by nao-pon** [comment]
@hintau MS Edge now possible to login with the own login form without using the browser's basic authentication dialog. I edited "[elfinderBasicAuth.js](https://studio-42.github.io/elFinder/#elf_l1_QmFzaWNBdXRoRXhhbXBsZS9CYXNpY0F1dGhFeGFtcGxlQWRkb24vanM)". Please check out it.

**Comment by hintau** [comment]
Thanks for the prompt response.

The elFinder demo login appears properly in all browsers now. 

When I copy the updapted files to my install, chrome and firefox bring up the new login window, IE doesn't do anything and it still fails in edge with the same message as before:

> HTTP401: DENIED - The requested resource requires user authentication.
> (XHR)GET - https://#######.com/uploader/php/connector.basicauth.php?login

I use IIS 7.5 with Anonymous Authentication (as per advice from PHP manual) so my IIS config must be the issue. I'll investigate. Thanks

**Comment by nao-pon** [comment]
Did you clear the browser's cache?

**Comment by hintau** [comment]
Thankyou that did it! Working on all browsers now. It also solves the issue of logging back in without password on all browsers apart from Chrome which isn't an issue for me.

The security addition really completes elfinder for me... I'd like to make a donation, how can I do this?

**Comment by nao-pon** [comment]
@hintau Thank you for your mind. There is a donate button in https://studio-42.github.io/elFinder/ . Also, f you want to donate to me (individual) you can also send gift certificates from Amazon.com or Amazon.com to Gmail's hypweb (hypweb[at]gmail.com). 👍

**Comment by hintau** [comment]
*Sorry, should have edited my comment not deleted it. I had another issue but that isn't related to this one.*

Yes the clearing of the cache worked thanks for that! It's hit and miss with re-logging in without having to enter credentials again but that appears to be unrelated to elfinder.. ultimately you still need the password to login initially so I think that is OK for my intended usage.

Thankyou again for your help, I will be donating this week.
