### ISSUE TITLE
Basic authentication - user related directories

### ISSUE THREAD

**Issue by hintau** [Studio-42/elFinder#2244]
Using information posted here (  [https://github.com/Studio-42/elFinder/issues/1694](url) ). I've setup root folders that can only be seen depending on the logged in user. 

> 'path'   => '/path/to/files/'.$username.'/',

It works well, login and the drive appears, logout it disappears but I can't open or download any file in that user specific folder. new tab appears saying "File not found". The root folder "Public" that everyone (logged in or not) can see works fine. It seems the root folder ID link (l1,l2,etc) is correct (l2 for user root folder,l1 for public) but the file function can't see it.

I don't use URL when setting up the root folders but I'd prefer Elfinder to control security (my folders aren't in the wwwroot folder) and not have direct links..could this be the problem?

For now I get around it by showing all root folders and using username to either show or hide subfolders but that isn't ideal.

Thanks

**Comment by nao-pon** [comment]
@hintau I got it. So I edited example "[connector.basicauth.php](https://studio-42.github.io/elFinder/#elf_l1_QmFzaWNBdXRoRXhhbXBsZS9CYXNpY0F1dGhFeGFtcGxlQWRkb24vcGhw)".

```php
if (!empty($_SESSION['ELFINDER_AUTH_USER']) && !empty($_SERVER['PHP_AUTH_USER'])) {
	$uname = ($_SESSION['ELFINDER_AUTH_USER'] === $_SERVER['PHP_AUTH_USER'])? $_SERVER['PHP_AUTH_USER'] : '';
}
```
to
```php
if (! empty($_SESSION['ELFINDER_AUTH_USER'])) {
	$uname = $_SESSION['ELFINDER_AUTH_USER'];
}
```

Please try it.

**Comment by hintau** [comment]
That works great nao-pon, thankyou.

**Comment by hintau** [comment]
The changes do work, thanks for that, but discovered an issue with Safari on the Iphone.

If you enter enter a wrong user/pass on the form. Safari opens up the standard basic authentication form rather than saying "Login failed "user:pass" and taking you back to the form login.

if you enter correct password in basic authen screen, it logs in but then you can't change users unless you close out of Safari.

**Comment by nao-pon** [comment]
Please check out newest version of [BasicAuthExample](https://studio-42.github.io/elFinder/#elf_l1_QmFzaWNBdXRoRXhhbXBsZS9CYXNpY0F1dGhFeGFtcGxlQWRkb24). I checked with iOS 11.0.2, that is work fine.

**Comment by hintau** [comment]
Yes agreed, thanks again for your prompt responses.
