### ISSUE TITLE
[i18n:pl] update to 2.1.29

### ISSUE THREAD

**Issue by Chaffinch** [Studio-42/elFinder#2245]
Updated Polish language to ver 2.1.9
https://github.com/Chaffinch/elFinder/blob/master/js/i18n/elfinder.pl.js

**Comment by nao-pon** [comment]
@Chaffinch Thanks! Please make a Pull Request to master branch.

**Comment by nao-pon** [comment]
[I send PR](https://github.com/Chaffinch/elFinder/pull/1) to your master branch to make possible make pull request to Studio-42/master.
