### ISSUE TITLE
Invalid parameters for command "src"

### ISSUE THREAD

**Issue by RJRahevar** [Studio-42/elFinder#2246]
hello..,

i have use elfinder new version .. but i have one issue copy and cur folder/file into paste another folder
generate dipslay   "Invalid parameters for command "src"" alert box 

**working** -Same folder into cut and paste working porperly ...
plaesse suggest me .. 

thanks

**Comment by nao-pon** [comment]
@RJRahevar That error message means that the elFinder client is requesting the "src" command, but there is no "src" in the official command. I guess there is a problem with the command you extended.
