### ISSUE TITLE
Cannot view folder content in FTP Driver

### ISSUE THREAD

**Issue by ManuSori** [Studio-42/elFinder#2248]
Hi!
 
After navigating through the different possible solutions, I was forced to write.
I can't see the contents of the folders on an FTP connection with elFinder.

My settings for FTP are as follows:
		array(
			'driver'		=> 'FTP',
			'alias'		=> 'FTP Berkon',
			'host'		=> 'URL',
			'user'		=> 'kiosco-web',
			'pass'		=> 'pass',
			'port'		=> 21,
			'mode'		=> 'passive',
			'path'		=> '/',
			'separator'        => '/',
			'timeout'		=> '10',
			'owner'		=> true,
			'tmbPath'		=> '/tmp',
			'tbpPath'		=> '/tmp',
			'tmpPath'		=> '/tmp',
			//'defaults'	=> array('read' => true, 'write' => true),
			'dirMode'		=> 0755,
			'fileMode'		=> 0644
			)

I have tried to change the permissions of the folders, of the files, I have also tried to modify the path of the temporary folders, and even to try some of the created folders as a starting path. Surprisingly, if I start the path in a created folder it works. But if I'm in the root directory (or any other directory) that contains folders and I try to enter one, I can't get in.
![carpetapropiedades](https://user-images.githubusercontent.com/32877896/31677205-526ab734-b36a-11e7-9087-9416822b4aea.jpg)
The properties that the folder gives me says that I only have write permission (Not even read). I mean, I can drag files into those folders, but then I can't open those folders to view them. This is insane! I can also rename and delete folders. But I can't go into the folders to see their contents.

The debug console tells me that there are no errors in PHP or anything similar. It's very strange. It's the only thing I can't do: View the contents of folders 
 
![debugconsole](https://user-images.githubusercontent.com/32877896/31677278-8de522ea-b36a-11e7-8cd7-acd017104740.jpg)
 
Obviously, with any FTP client (Filezilla, WinSCP...) I can access the created folders, but with elFinder I cannot.

I have mounted elFinder on two different servers and I have exactly the same problem. So I don't know what to do anymore.

**Comment by nao-pon** [comment]
@ManuSori It seems that directory permissions are missing. Please check permissions and owner such as directory "Carpeta". Or if you can debug the FTP driver, check the raw data of the response from the FTP server.

**Comment by ManuSori** [comment]
Hi nao!
 
I'm not as good at programming in PHP as you are, but from what I'm reviewing and checking, it seems that the server gives me problems because of its age.
 
It's an FTP server mounted on Windows, it's called "Serv-U" (serv-u.com) but in version 5.0 (currently serving 15.0).
 
I have made two more tests with the demo version of Serv-U (15.0) mounted on Windows, and also with proFTPD in a Debian 9. I haven't had any problems opening folders in either of them. So I'm going to try to put debugging functions in the FTP Class to see if I can get the error message that gives me with the folder permissions.
 
If you come up with any ideas for debugging, I'm all eyes for reading.

A greeting.

**Comment by nao-pon** [comment]
@ManuSori This is simply debug function.
```php
function debug() {
    $arg = func_get_args();
    ob_start();
    foreach($arg as $v) {
        var_dump($v);
    }
    $o = ob_get_contents();
    ob_end_clean();
    file_put_contents('.debug.txt', $o, FILE_APPEND);
}
```
so you put into connector.php this function then you can use `debug($val);` any point. You will to able to check with `.debug.txt` in directory that include connector.php.

Please check functions `_stat()`, and `parseRaw()`.

**Comment by nao-pon** [comment]
@ManuSori Did you solve this problem? If you have anything to fix in elFinder, please propose that fix.

**Comment by ManuSori** [comment]
Hi Nao!
Let me explain, 

 

I think there is a conflict with the functions that PHP uses to manage the FTP server we have installed. But it's an old-fashioned problem with our server. This server is installed on a 32-bit Windows XP and is 13 years old. So it's absurd to look for a solution for elFinder. I have already proposed to make a server change and update it. There are open source servers that work very well with "elFinder" and I don't want headaches for a “fopen” function with an obsolete server.

Anyway, don't think we're going to change the server for your application. We are going to do so because it is clear that we will continue to have problems of incompatibility.

 

If you want, I'll explain it in the forum, or you can close the conversation. But it doesn't really matter.

 

Manu Soriano

 

De: Naoki Sawada [mailto:notifications@github.com] 
Enviado el: viernes, 10 de noviembre de 2017 13:23
Para: Studio-42/elFinder <elFinder@noreply.github.com>
CC: ManuSori <regiem5@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [Studio-42/elFinder] Cannot view folder content in FTP Driver (#2248)

 

@ManuSori <https://github.com/manusori>  Did you solve this problem? If you have anything to fix in elFinder, please propose that fix.

**Comment by nao-pon** [comment]
@ManuSori Thank you for your response. I got it, so I'll close this issue.

Thanks!
