### ISSUE TITLE
Cannot drag navbar on mobile devices

### ISSUE THREAD

**Issue by vareAs** [Studio-42/elFinder#2250]
Hi,
Cannot drag navbar on mobile devices.
I tried on Android, iPhone.

I tried too on Chrome developer tools and set "Responsive, Mobile(on touch)", I cannot drag navbar same as mobile devices.

I tried on 2.1.29 and 2.1.x(Nightly).

I realized the following.
When I try on Chrome(Windows), show up resize bar.
But on mobile devices, do not show up.

Like this one.
![default](https://user-images.githubusercontent.com/12601969/31729154-2ead5c84-b469-11e7-9ee9-5a55256ba977.png)

This is probably effecting that.

Is this bug?

**Comment by nao-pon** [comment]
@vareAs This is not a bug. Can't resize navbar on mobile devices. Instead there is a action "Show/Hide" with swipe on mobile devices so like this...

![ezgif-4-f37cbfbcdd](https://user-images.githubusercontent.com/1412630/31752921-7bd72f58-b4c8-11e7-9cdd-e0c93670f72e.gif)

**Comment by vareAs** [comment]
Thanks.
I could be confirmed how to hide navbar.
Thank you for your kindness.
