### ISSUE TITLE
Resize/crop/rotate: Use optimized image to speed up preview load time.

### ISSUE THREAD

**Issue by bwaindwain** [Studio-42/elFinder#2251]
To resize an image, the preview is only 400px wide, but the entire image must be loaded. For big images on a slow connection, this means the user has to wait a long time while the image preview loads.

It would be nice if a 400px preview were created on upload (just like thumbnails) so that image editing happens faster.

![image](https://user-images.githubusercontent.com/2658754/31785470-7def7a30-b4c2-11e7-9d99-a431723bed2f.png)

**Comment by nao-pon** [comment]
@bwaindwain elFinder is reading the complete image for obtaining the image size. Consider using [AutoResize](https://github.com/Studio-42/elFinder/blob/master/php/plugins/AutoResize/plugin.php) plugin if you are using PHP connector.

**Comment by bwaindwain** [comment]
Thanks for the reply and suggestion about autoresize.

But I wasn't asking a question, I was suggesting a new feature on behalf of our clients who are on slow connections. Get info returns the image dimensions without loading the entire image on the client side. 

Thanks for considering this.

**Comment by nao-pon** [comment]
I think so that it is a good idea to acquire only the image size so that editing can be started as soon as possible, so I will implement it like that.
On the other hand, it is maybe useless to prepare images for the resize screen beforehand for all of the images so we will not adopt it this time.

Thanks! 👍

**Comment by bwaindwain** [comment]
One idea would be to create a 400px wide preview image temporarily and serving it to the client as needed. It doesn't have to be stored on the server.

**Comment by nao-pon** [comment]
@bwaindwain Please tell me about the network speed and the image file size that you assume.

**Comment by bwaindwain** [comment]
Our clients are usually in developing countries with networks speeds that vary from 2mb/s and up. Images range from 3-5 mb. At that speed, a 4mb jpg could take up to 15 seconds to load on the client side.

Compare that with creating a 10kb preview jpg temporarily server side, sending it to the client side. Total time would be a lot less. 

Our organization helps minority people groups in remote parts of the world create and maintain websites for the promotion of literacy, language and culture. 

Thanks for considering this.

**Comment by nao-pon** [comment]
@bwaindwain I done. I added the following two options on the client side config `commandsOptions.resize`.

```javascript
// File size (bytes) threshold when using the `dim` command for obtain the image size necessary to start editing
getDimThreshold : 204800,
// File size (bytes) to request to get substitute image (400px) with the `dim` command
dimSubImgSize : 307200
```

Thanks! 👍

**Comment by bwaindwain** [comment]
Very cool. Thanks!!
