### ISSUE TITLE
auth login without $server 'php_auth_user'

### ISSUE THREAD

**Issue by daniresa** [Studio-42/elFinder#2252]
I couldn't set $_SERVER variables... Is it possible set connector.php with $_SESSION variables? Thanks

**Comment by nao-pon** [comment]
@daniresa This is an example to simply auth with HTTP header. (Based on [Basic auth example](https://studio-42.github.io/elFinder/#elf_l1_QmFzaWNBdXRoRXhhbXBsZQ))

**PHP connector Auth part**
```php
// simply auth
session_start();
$admins = array('hypnaopon' => true);
if (isset($_GET['login']) || isset($_GET['logout']) || isset($_GET['status'])) {
	$auths = array(
		'admin' => 'admin_pass',
		'user1' => 'user1_pass'
	);
	header('Content-Type: application/json; charset=utf-8');
	header('Cache-Control: no-store, no-cache, must-revalidate');
	header('Cache-Control: post-check=0, pre-check=0', false);
	header('Pragma: no-cache');
	if (isset($_GET['logout'])) {
		unset($_SESSION['ELFINDER_AUTH_USER']);
		echo '{"uname": ""}';
	} else if (isset($_GET['status'])) {
		echo '{"uname": "'.(isset($_SESSION['ELFINDER_AUTH_USER'])? $_SESSION['ELFINDER_AUTH_USER'] : '').'"}';
	} else {
		if (isset($_SERVER['HTTP_X_ELFINDERUSER']) && isset($auths[$_SERVER['HTTP_X_ELFINDERUSER']]) && $auths[$_SERVER['HTTP_X_ELFINDERUSER']] === $_SERVER['HTTP_X_ELFINDERPASS']) {
			$_SESSION['ELFINDER_AUTH_USER'] = $_SERVER['HTTP_X_ELFINDERUSER'];
			echo '{"uname": "'.$_SERVER['HTTP_X_ELFINDERUSER'].'"}';
		} else {
			header('Content-Type: application/json; charset=utf-8');
			echo '{"error": "Login faild."}';
		}
	}
	exit();
}
$uname = '';
if (! empty($_SESSION['ELFINDER_AUTH_USER'])) {
	$uname = $_SESSION['ELFINDER_AUTH_USER'];
}
$isAdmin = isset($admins[$uname]);
$isUser = $uname? true : false;
```

**elfinderBasicAuth.js**
```javascript
(function(root, factory) {
	if (typeof define === 'function' && define.amd) {
		define(['jquery', 'elfinder'], factory);
	} else if (typeof exports !== 'undefined') {
		module.exports = factory(require('jquery'), require('elfinder'));
	} else {
		factory(root.jQuery, root.elFinder);
	}
}(this, function($, elFinder) {
try {

(function(){
	var style = document.createElement('style'),
		sheet;
	document.head.appendChild(style);
	sheet = style.sheet;
	sheet.insertRule('.elfinder-button-icon.elfinder-button-icon-login { background:url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAYAAAAbifjMAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wwODgkfXMcF3gAAA0ZJREFUSMftlVFo1VUYwH/nf+/uvW4O3NA23R0uHdPV1qJ6CwwiCgKfJNCXIiuxKAipoIdi9Bb1WA8rCcKXJMQgjIweTCgUdWipTMttuEWhbd61sf3/5/u+c3rYdrcbblhvQQcO39P3+w7nfN/vOP7FunjwlXdDsANmOp3/J4mXP3n15xCss7ChlZHRSzQnBa0C+vv7YwiBxW1m1bi3J5IQKKxvYe3dnQQLxJGfEMmoAsyMcrkMgHOuJsZ4kaaHHgYc2cwEJhkxBkSUZDkA4ER6nEjEOVfdZkYwI62MI7NTBPHEYIhktQDnHH9kN/mq8kUNQNUTTDD1BPUEzYgh4H1KfucHj8VggQt6isFbP9DR1oGqcXTsMLva9szD1RNVCeIx9RAdMQRUUvKmxlOP7kKCoaZoUMSEM+k5Phs+xJ6tTyMLlU0yoqa0bLjBL1HxPiOvYngVJtNJvAliAji679nOYHqer0eP0VEPpor5jMaGWzSvm6AuN8e0pCSqRmaeQlKkmCtRzJXIuRxnzw1SGf+TJ7fsRCQlaIZJRmUyx+joejJfN/+MKsrhLz9HxTA1yuU2NBhT49M8f99+nHN4nxFUCJJhIkxkeQgBEU9y8u3T7vt3zrru3/p4+d4DTP06w8T1Ci/0vbj0CpLO34EKpguwEFD1S42kqjjniBbZf/9LNc3kJZtPlowgHucCMa4A2Nu3r1p5ESAyX7W+qZ2ggmazEH/HTHEDAwNxaGiIsbGxmv5fHndvGaWhsZFiqYFCqZ66QpHpmQrXrwzedHcyhR8/136XmW41k24z7QrBykm+sNskm3L/+6B2nCORE+nxavKd+KDmBN/OHWPKV3D1rqYX/u4DcEs+WAQMNZ9nU8tGmmwdh4YPYmrV+fiw/YGVfQDwxPuP/Ni6qZXerl40KNs7tyELXjhy5OjqPnj8vR2fbt64ube3q4dKWmFWZhETfBAa8mtRNUT8yj745vWTz1wZvnrp9IUzJC5HMVeilF9DKbeGzDwqtroPAL5761TPjjdcnEvnUFWuXRvBNGBqBAur+qB6iVtubGPEXSWJOV578M2aXtDLH9X4wLl81QfJ8nF+tnsf0Wr/hNv5IIi/vQ+SJPkP+uAvyoJNfRlNM5QAAAAASUVORK5CYII="); background-position: 0 0; }', 0);
	sheet.insertRule('.elfinder-button-icon.elfinder-button-icon-logout { background-position: 0 -16px; }', 1);
})();
$.fn.elfinderloginbutton = function(cmd) {
	return this.each(function() {
		var button = $(this).elfinderbutton(cmd),
			icon   = button.children('.elfinder-button-icon');
		cmd.change(function() {
			var logined = cmd.value? true : false;
			icon.toggleClass('elfinder-button-icon-logout', logined);
			button.attr('title', logined? cmd.fm.i18n('logout', cmd.value) : cmd.fm.i18n('login'));
		});
	});
}
elFinder.prototype.commands.login = function() {
	var self = this,
		fm   = this.fm,
		url  = fm.options.url,
		aopt = {
			dataType: 'json',
			headers: fm.options.customHeaders,
			xhrFields: fm.options.xhrFields
		};
	this.alwaysEnabled  = true;
	this.updateOnSelect = false;
	this.options = {
		ui       : 'loginbutton',
		loginUrl : url+'?login',
		logoutUrl: url+'?logout',
		statusUrl: url+'?status'
	};
	this.value = null;
	this.handlers = {
		'open': function(){
			if (self.value === null) {
				self.value = '';
				$.ajax(self.options.statusUrl, aopt).done(function(res){
					self.value = res.uname? res.uname : '';
					self.update(void(0), self.value);
				});
			}
		} 
	};
	
	this.getstate = function() {
		return this.value? 1 : 0;
	};
	
	this.exec = function() {
		var dologin = (! self.value),
			getAjax = function(opt) {
				return $.ajax(self.options[dologin? 'loginUrl' : 'logoutUrl'], opt).done(function(res){
					if (res.error) {
						fm.error(res.error);
					} else {
						self.update(void(0), res.uname? res.uname : '');
						var tm,
							dfd = fm.sync().always(function() { 
								tm && clearTimeout(tm); 
							});
							
						tm = setTimeout(function() {
							fm.notify({type : 'reload', cnt : 1, hideCnt : true});
							dfd.always(function() { fm.notify({type : 'reload', cnt  : -1}); });
						}, fm.notifyDelay);
					}
				}).fail(function(e) {
					var res = e.responseText;
					try {
						res = JSON.parse(res);
					} catch(e) {
						res = {};
					}
					res.error && fm.error(res.error);
				});
			},
			btn = {},
			req = function() {
				if (user.val() && pass.val()) {
					aopt['headers']['X-elFInderUser'] = user.val();
					aopt['headers']['X-elFInderPass'] = pass.val();
				}
				getAjax(aopt).done(function() {
					dfd.resolve();
				}).fail(function(e) {
					dfd.reject();
				}).always(function() {
					dialog.elfinderdialog('destroy');
				});
			},
			dfd, dialog, user, pass, form;
		if (dologin) {
			dfd = $.Deferred();
			user = $('<input class="elfinder-tabstop" type="text" placeholder="demouser">');
			pass = $('<input class="elfinder-tabstop" type="password" placeholder="demouser">');
			form = $('<div style="text-align:center;">').append($('<p>').append('Username: ', user), $('<p>').append('Password: ', pass))
				.on('keyup keydown keypress', function(e) {
					e.key !== 'Escape' && e.key !== 'Tab' && e.stopPropagation();
					if (e.type === 'keypress' && e.key === 'Enter') {
						if (user.val() !== '' && pass.val() !== '') {
							req();
						} else {
							(user.val()? pass : user).focus();
						}
					}
				});
			btn[fm.i18n('login')] = req;
			btn[fm.i18n('btnCancel')] = function() {
				dialog.elfinderdialog('destroy');
			};
			dialog = fm.dialog(form, {
				title: fm.i18n('login'),
				buttons: btn,
				allowMinimize: false,
				destroyOnClose: true,
				open: function() {
					user.focus();
				},
				close: function() {
					(dfd.state() !== 'resolved') && dfd.reject();
				}
			});
			return dfd;
		} else {
			return getAjax(aopt);
		}
	};
}
elFinder.prototype._options.commands.push('login');
elFinder.prototype._options.uiOptions.toolbar.push(['login']);
elFinder.prototype.i18.en.messages.logout = '$1: logout';

} catch(e) {}
}));
```

**Comment by daniresa** [comment]
ummm, login and logout works but... files are not protected... I can delete, move, etc them even I´m logout

**Comment by daniresa** [comment]
I tried in your demo... login as demouser. Which differences are into be logged or not? I can´t see them!

**Comment by nao-pon** [comment]
If there is no problem logging in, there probably is a problem with the connector setting. Please present your connector settings.

**Comment by daniresa** [comment]
connector.minimal.php

`<?php

error_reporting(0); // Set E_ALL for debuging

// load composer autoload before load elFinder autoload If you need composer
//require './vendor/autoload.php';

// elFinder autoload
require './autoload.php';
// ===============================================

// Enable FTP connector netmount
elFinder::$netDrivers['ftp'] = 'FTP';
// ===============================================

/**
 * # Dropbox volume driver need `composer require dropbox-php/dropbox-php:dev-master@dev`
 *  OR "dropbox-php's Dropbox" and "PHP OAuth extension" or "PEAR's HTTP_OAUTH package"
 * * dropbox-php: http://www.dropbox-php.com/
 * * PHP OAuth extension: http://pecl.php.net/package/oauth
 * * PEAR's HTTP_OAUTH package: http://pear.php.net/package/http_oauth
 *  * HTTP_OAUTH package require HTTP_Request2 and Net_URL2
 */
// // Required for Dropbox.com connector support
// // On composer
// elFinder::$netDrivers['dropbox'] = 'Dropbox';
// // OR on pear
// include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeDropbox.class.php';

// // Dropbox driver need next two settings. You can get at https://www.dropbox.com/developers
// define('ELFINDER_DROPBOX_CONSUMERKEY',    '');
// define('ELFINDER_DROPBOX_CONSUMERSECRET', '');
// define('ELFINDER_DROPBOX_META_CACHE_PATH',''); // optional for `options['metaCachePath']`
// ===============================================

// // Required for Google Drive network mount
// // Installation by composer
// // `composer require nao-pon/flysystem-google-drive:~1.1 nao-pon/elfinder-flysystem-driver-ext`
// // Enable network mount
// elFinder::$netDrivers['googledrive'] = 'FlysystemGoogleDriveNetmount';
// // GoogleDrive Netmount driver need next two settings. You can get at https://console.developers.google.com
// // AND reuire regist redirect url to "YOUR_CONNECTOR_URL?cmd=netmount&protocol=googledrive&host=1"
// define('ELFINDER_GOOGLEDRIVE_CLIENTID',     '');
// define('ELFINDER_GOOGLEDRIVE_CLIENTSECRET', '');
// ===============================================

/**
 * Simple function to demonstrate how to control file access using "accessControl" callback.
 * This method will disable accessing files/folders starting from '.' (dot)
 *
 * @param  string  $attr  attribute name (read|write|locked|hidden)
 * @param  string  $path  file path relative to volume root directory started with directory separator
 * @return bool|null
 **/
function access($attr, $path, $data, $volume) {
	return strpos(basename($path), '.') === 0       // if file/folder begins with '.' (dot)
		? !($attr == 'read' || $attr == 'write')    // set read+write to false, other (locked+hidden) set to true
		:  null;                                    // else elFinder decide it itself
}


// Documentation for connector options:
// https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options
$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '../Todo Gibraljaire/',                 // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../Todo Gibraljaire/', // URL to files (REQUIRED)
			'uploadDeny'    => array(''),                // All Mimetypes not allowed to upload
			 'uploadAllow' => array('all'),
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		)
	)
);

// simply auth
session_start();
$admins = array('hypnaopon' => true);
if (isset($_GET['login']) || isset($_GET['logout']) || isset($_GET['status'])) {
	$auths = array(
		'admin' => 'admin',
		'user1' => 'admin'
	);
	header('Content-Type: application/json; charset=utf-8');
	header('Cache-Control: no-store, no-cache, must-revalidate');
	header('Cache-Control: post-check=0, pre-check=0', false);
	header('Pragma: no-cache');
	if (isset($_GET['logout'])) {
		unset($_SESSION['ELFINDER_AUTH_USER']);
		echo '{"uname": ""}';
	} else if (isset($_GET['status'])) {
		echo '{"uname": "'.(isset($_SESSION['ELFINDER_AUTH_USER'])? $_SESSION['ELFINDER_AUTH_USER'] : '').'"}';
	} else {
		if (isset($_SERVER['HTTP_X_ELFINDERUSER']) && isset($auths[$_SERVER['HTTP_X_ELFINDERUSER']]) && $auths[$_SERVER['HTTP_X_ELFINDERUSER']] === $_SERVER['HTTP_X_ELFINDERPASS']) {
			$_SESSION['ELFINDER_AUTH_USER'] = $_SERVER['HTTP_X_ELFINDERUSER'];
			echo '{"uname": "'.$_SERVER['HTTP_X_ELFINDERUSER'].'"}';
		} else {
			header('Content-Type: application/json; charset=utf-8');
			echo '{"error": "Login faild."}';
		}
	}
	exit();
}
$uname = '';
if (! empty($_SESSION['ELFINDER_AUTH_USER'])) {
	$uname = $_SESSION['ELFINDER_AUTH_USER'];
}
$isAdmin = isset($admins[$uname]);
$isUser = $uname? true : false;


// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();`

**Comment by nao-pon** [comment]
@daniresa It is necessary to switch the operation of the connector according to login information. Please refer to the [connector.basicauth.php](https://studio-42.github.io/elFinder/#elf_l1_QmFzaWNBdXRoRXhhbXBsZS9CYXNpY0F1dGhFeGFtcGxlQWRkb24vcGhw) as an example to fix it.
