### ISSUE TITLE
Questions about file format restrictions in elfinder

### ISSUE THREAD

**Issue by shape-of-you** [Studio-42/elFinder#2254]
elfinder version: 2.1.29
At present, in my local environment test can only upload txt files and pictures, the other such as: to word, go as a suffix of the document can not upload. How to modify the upload file format limit?

**Comment by nao-pon** [comment]
@shape-of-you Please check the [Wiki (`uploadAllow`, `uploadDeny` and `uploadOrder`)](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadallow).

Thanks.
