### ISSUE TITLE
Help with Drupal integration

### ISSUE THREAD

**Issue by bwaindwain** [Studio-42/elFinder#2255]
I'm trying to get v2.1.29 working with Drupal 7.56 and I need some help. 

Version 2.1.7 worked fine. But when I put in ver 2.1.29, and go to the elfinder connector URL all I see is

>Fatal error: Call to a member function get() on null in /var/www/html/elfinder/sites/all/libraries/elfinder/php/elFinder.class.php on line 1085

Seems to be something with the replaceable session handling wrapper (elFinderSessionInterface
[see elfinder commit](https://github.com/Studio-42/elFinder/commit/78452f3429a64db43e068146bf91c030bab2ca5d) )

Do I need to extend the elFinderSession class with my own? 

In the Drupal module, there already is a 
`class elFinderDrupal extends elFinder {...}`

Should I add a `$this->session->set()` to it? And what should I set it to?

Thanks. I'm new to OOP.

**Comment by nao-pon** [comment]
@bwaindwain I think that is a problem of class elFinderDrupal. It seems that it is not properly booted up in the constructor.

**Comment by bwaindwain** [comment]
Thanks. I got it fixed with some help from https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options. 

Here's my class

    class elFinderDrupal extends elFinder {
      // Run the parent constructor and register 'desc' as a new command
      public function __construct($opts) {
        parent::__construct($opts);
        $this->commands['desc'] = array('target' => TRUE, 'content' => FALSE);
        $this->commands['owner'] = array('target' => TRUE, 'content' => FALSE);
      }
    ...
