### ISSUE TITLE
Changing filter target back to "Here" doesn't update search results

### ISSUE THREAD

**Issue by bwaindwain** [Studio-42/elFinder#2256]
Changing the search filter target from "Here" to "All" then back to "Here" doesn't updated the search results. To reproduce:

1. upload a file called "foo" to root folder
1. create a folder called asdf
1. copy foo to asdf
1. type foo in search box
1. notice search results are correct: 1 foo
1. change filter target to ALL
1. notice search results are correct: 2 foo
1. change filter target back to HERE
1. notice search results are incorrect: 2 foo (it should only be 1)

![image](https://user-images.githubusercontent.com/2658754/32068368-63b884e6-ba43-11e7-8408-505d36318111.png)

**Comment by nao-pon** [comment]
@bwaindwain "Here" also includes the current folder and folders below it. To search only the current folder, please use incremental search (not press Enter).
