### ISSUE TITLE
UTF8 encoded filename problem

### ISSUE THREAD

**Issue by kaiqueg** [Studio-42/elFinder#2258]
Well, **I searched about this problem** here and some people said that's over, but not for me and my case is really interesting.
Elfinder is ok with files **without** accentuation but when I upload an PDF, for example, I can't open it from my main folder (/files).
[![404 NOT FOUND](https://preview.ibb.co/g7zLLm/Print_229.png)](https://ibb.co/eZPn0m)

Now you say: "_yeah, that's what everyone was saying_". But when I move that file to **trash folder**, I can open it!
[![Success](https://preview.ibb.co/g3CUD6/Print_230.png)](https://ibb.co/cgskmR)
So that's not my browser, right?. Can somebody help me?

> **Chrome version:** 61.0.3163.100 64bits
> **Apache version:** 2.4.4
> **PHP version:** 5.4.16

**Comment by nao-pon** [comment]
@kaiqueg Please set connector roots options [`encoding`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding) and [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale-1) to fit to your server environment.

**Comment by kaiqueg** [comment]
@nao-pon That's my configuration:
```
$def_uploadAllow = array('image', 'audio', 'video', 'text/plain', 'application/pdf', 'application/msword', 'application/excel', 'application/vnd.ms-excel', 'application/x-msexcel', 'application/x-excel', 'application/powerpoint', 'application/ms-powerpoint', 'application/x-compressed', 'application/x-zip-compressed', 'application/zip', 'multipart/x-zip');
$opts = array(
	'locale' => 'pt_BR.UTF-8',
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',
			'alias'         => 'Arquivos',
			'path'          => '../files/',
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/',
			'trashHash'     => 't1_Lw',
			'winHashFix'    => DIRECTORY_SEPARATOR !== '/',
			'uploadDeny'    => array('all'),
			'uploadAllow'   => $def_uploadAllow,
			'uploadOrder'   => array('deny', 'allow'),
			'accessControl' => 'access'
		),
		array(
			'id'            => '1',
			'driver'        => 'Trash',
			'alias'         => 'Lixeira',
			'path'          => '../files/.trash/',
			'tmbURL'        => dirname($_SERVER['PHP_SELF']) . '/../files/.trash/.tmb/',
			'winHashFix'    => DIRECTORY_SEPARATOR !== '/',
			'uploadDeny'    => array('all'),
			'uploadAllow'   => $def_uploadAllow,
			'uploadOrder'   => array('deny', 'allow'),
			'accessControl' => 'deny'
		)
	)
);
```
It's the same to both drivers, right? Why am I able to open my files in the trash and not the main root?
Don't worry too much, I already solved my problem using the Normalizer plugin. But I think this is a huge problem as other people may want to keep the original name of the files.

**Comment by nao-pon** [comment]
Volumes that have 'URL' set open files directly on the server whereas volumes that do not set 'URL' will open the file via elFinder's connector. In order to open the file directly on the server, you need to specify the volume encoding appropriately.

**Comment by kaiqueg** [comment]
Now I understood! Thank you @nao-pon , I'll close this.
