### ISSUE TITLE
It's possible to add a exception for allowing changes in lockeds files/foders ? 

### ISSUE THREAD

**Issue by gabrieldaj** [Studio-42/elFinder#2259]
Hi, after a few searches i didn't figure out how to allow a specified user to change restricted files/folders, i'm working with .net driver and  using a custom control to catch the permissions for a currently user based in group policies.

It's possible to change the way that elfinder-contextmenu show the commands ?, something like when i select a image file that ables a resize command.

Where that rule are?(case of a image file)

I think that i could change a rule who is responsable for mount the context menu (or add a specifed role for my case) and solve my problem..

I'm sorry for being a noob in javascript, actualy a prefer C# (i know just a bit more but ok kkk)

![image](https://user-images.githubusercontent.com/17691200/32113709-d3e1cf20-bb1f-11e7-8ed5-fce6908cf4e8.png)

**Comment by nao-pon** [comment]
@gabrieldaj Your screenshot shows that the command on the .net connector is not valid. Please ask the developer of the .net connector.

**Comment by gabrieldaj** [comment]
Thanks @nao-pon, but in original elFinder, where can i see the rules responsable for allow that commands like rename, cut and delete.. in contextmenu ?, Do you have a doc for this commands things ?

**Comment by nao-pon** [comment]
Please check the wiki [`uiOptions`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#uioptions) and [`contextmenu`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#contextmenu).
