### ISSUE TITLE
How to connect in a FTP server without connector.php?

### ISSUE THREAD

**Issue by Heronbeluci** [Studio-42/elFinder#2260]
i have a project, my project dont runs PhP and i want to use elFinder with my explorer, have a method to do this without a php connector? im using NodeJS in my project... and i already have a FTP server to connect i need only the FTP client...

**Comment by nao-pon** [comment]
@Heronbeluci elFinder requires a connector to scan the file system of the server. If you can only use NodeJS on the server, you need to have a [connector for NodeJS](https://www.google.com/search?q=elFinder+NodeJS).

Refer to the wiki page for [client / server connection API](https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1).
