### ISSUE TITLE
focus follows mouseover

### ISSUE THREAD

**Issue by bwaindwain** [Studio-42/elFinder#2264]
The focus always changes when the mouse hovers over another element. This means I have to click in the input again to start typing. 
For example:

1. Click to resize an image
1. Click in width input to place cursor
1. Move mouse down so that you can see what you're typing. Make sure to move it over the height input
1. Cursor is no longer in the width input, and I can't type a width anymore

 Is this a conflict with touch device support?

![image](https://user-images.githubusercontent.com/2658754/32294220-240b0ca2-bf0b-11e7-8eba-2a4b12188ce2.png)

**Comment by nao-pon** [comment]
@bwaindwain ui.dialog has such a function. I will add an option that can disable that feature.

Thanks!
