### ISSUE TITLE
same browser can not  open the frame, chrome version 59.0.3071.86

### ISSUE THREAD

**Issue by jeremyzhou2001** [Studio-42/elFinder#2269]
![image](https://user-images.githubusercontent.com/29558548/32430933-50e11276-c30c-11e7-9f20-8365913b6311.png)
![image](https://user-images.githubusercontent.com/29558548/32430948-64517eea-c30c-11e7-8ce7-0b5950e7c9da.png)

**Comment by nao-pon** [comment]
@jeremyzhou2001 The code you indicated is customized. It is not a problem of elFinder, it can not find a problem if there is no whole code.

If I guess, the error message says that require.js is not loaded and your JavaScript is syntactically incorrect.
