### ISSUE TITLE
`Script error for "elfinder" needed by:elfinder.lang http://requirejs.org/docs/errors.html#scripterror`

### ISSUE THREAD

**Issue by oitsuki** [Studio-42/elFinder#2273]
I follow the instructions ckeditor to adapt my elfinder version to the last but now I have this error
I don't change anything inside the element wrote in the instruction and downloaded main.cke.js

Thank you

Error
`Script error for "elfinder" needed by:elfinder.lang http://requirejs.org/docs/errors.html#scripterror`

`my url : ...../elFinder-master/elfinder-cke.html?CKEditor=customers_response&CKEditorFuncNum=1&langCode=fr`

my call is 
```
CKEDITOR.replace(\'' . HTML::output($name) . '\',
    {
        width : '. $height .',
        toolbar : "Full",
        filebrowserBrowseUrl :"' . OSCOM::link('Shop/ext/elFinder-master/elfinder-cke.html') . '",
    });
```

**Comment by nao-pon** [comment]
@oitsuki I re-written a section that "[Update the elFinder page being called by CKEditor](https://github.com/Studio-42/elFinder/wiki/Integration-with-CKEditor#update-the-elfinder-page-being-called-by-ckeditor)" of Wiki page to fit to current version of the elFinder. Please checkout it. 

Thanks! 👍

**Comment by oitsuki** [comment]
Thank you,
It's my false, I forget that!
But the problem is always the same.
