### ISSUE TITLE
how to open ms office file directly on elfinder?

### ISSUE THREAD

**Issue by kyuik** [Studio-42/elFinder#2274]
Hi. thanks for great tool

i wanna open ms office file from elfinder directly-not through download- and also want to save it on elfinder directly. 
is there any way to make these?

**Comment by nao-pon** [comment]
@kyuik Please check connector root option [`dispInlineRegex`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#dispinlineregex). Thanks!

**Comment by kyuik** [comment]
thank for reply ,
but my devs not understand your command very well
it is really appreciated if you give more detail tip of it

**Comment by nao-pon** [comment]
If all of the content on elFinder on your site is trustworthy, you can use
`'. *'`
To allow inline display of all content. If you are worried about XSS attacks, specify the MIME type of the trusted file with a regular expression. For example
`'^(?:image|application/(?:vnd\.)?(?:ms(?:-office|word|-excel|-powerpoint)|openxmlformats-officedocument)|text/plain$)'`
However, I have not confirmed the operation of this regular expression. There may be errors. In that case, please correct as appropriate.

**Comment by kyuik** [comment]
thank. 
but he couldn't find the option you described. could you let me know exact path to approach above option?

**Comment by nao-pon** [comment]
For example. In default [connector.minimal.php](https://github.com/Studio-42/elFinder/blob/2.1/php/connector.minimal.php-dist).

```php
$opts = array(
    // 'debug' => true,
    'roots' => array(
        // Items volume
        array(
            'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
            'path'          => '../files/',                 // path to files (REQUIRED)
            'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
            'trashHash'     => 't1_Lw',                     // elFinder's hash of trash folder
            'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
            'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
            'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
            'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
            'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
        ),
        // Trash volume
        array(
            'id'            => '1',
            'driver'        => 'Trash',
            'path'          => '../files/.trash/',
            'tmbURL'        => dirname($_SERVER['PHP_SELF']) . '/../files/.trash/.tmb/',
            'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
            'uploadDeny'    => array('all'),                // Recomend the same settings as the original volume that uses the trash
            'uploadAllow'   => array('image', 'text/plain'),// Same as above
            'uploadOrder'   => array('deny', 'allow'),      // Same as above
            'accessControl' => 'access',                    // Same as above
        )
    )
);
```
**TO**
```php
$opts = array(
    // 'debug' => true,
    'roots' => array(
        // Items volume
        array(
            'dispInlineRegex' => '^(?:image|application/(?:vnd\.)?(?:ms(?:-office|word|-excel|-powerpoint)|openxmlformats-officedocument)|text/plain$)',
            'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
            'path'          => '../files/',                 // path to files (REQUIRED)
            'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
            'trashHash'     => 't1_Lw',                     // elFinder's hash of trash folder
            'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
            'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
            'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
            'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
            'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
        ),
        // Trash volume
        array(
            'dispInlineRegex' => '^(?:image|application/(?:vnd\.)?(?:ms(?:-office|word|-excel|-powerpoint)|openxmlformats-officedocument)|text/plain$)',
            'id'            => '1',
            'driver'        => 'Trash',
            'path'          => '../files/.trash/',
            'tmbURL'        => dirname($_SERVER['PHP_SELF']) . '/../files/.trash/.tmb/',
            'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
            'uploadDeny'    => array('all'),                // Recomend the same settings as the original volume that uses the trash
            'uploadAllow'   => array('image', 'text/plain'),// Same as above
            'uploadOrder'   => array('deny', 'allow'),      // Same as above
            'accessControl' => 'access',                    // Same as above
        )
    )
);
```

**Comment by netdeveloper1job** [comment]
Hi,
"'dispInlineRegex' => '^(?:image|application/(?:vnd\.)?(?:ms(?:-office|word|-excel|-powerpoint)|openxmlformats-officedocument)|text/plain$)',"
Its not working for word file (.doc and .docx) both . its still open a popup and download automatically

**Comment by nao-pon** [comment]
@netdeveloper1job If it is downloaded after the browser window is opened, it depends on the setting of the browser. It is probably not set to open Word files in your browser.

**Comment by netdeveloper1job** [comment]
@nao-pon Yes I installed a extension on my browser it working But only on my pc. Is there any possibality for write code like extension in script .

**Comment by nao-pon** [comment]
@netdeveloper1job There is a plugin to preview with GoogleDocs viewer, but it's only preview not editable. If you think enough by preview, please set next config.

**client config [`commandsOptions`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#commandsoptions)**

```javascript
commandsOptions : {
    quicklook : {
        googleDocsMimes : ['application/pdf', 'image/tiff', 'application/vnd.ms-office', 'application/msword', 'application/vnd.ms-word', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
    }
}
```

Note: From elFinder >= 2.1.30 User can selectable an action of file selecting.

![171125-142036](https://user-images.githubusercontent.com/1412630/33227763-c4dfcc04-d1ed-11e7-8682-d487f78948db.png)

And User can edit with Zoho Office Editor.  c.f #2280.

![fireshot capture 2 - test here_elfinder - web fil_ - https___studio-42 github io_elfinder_ elf_l2_lw](https://user-images.githubusercontent.com/1412630/33227785-8d7ba610-d1ee-11e7-9ad0-4d1d9fe03715.png)

**Comment by netdeveloper1job** [comment]
HI,
I have not seen this feature on my browser
![image](https://user-images.githubusercontent.com/11452542/33228144-247da974-d1da-11e7-8c38-85d6f23ac9b6.png)

**Comment by netdeveloper1job** [comment]
![image](https://user-images.githubusercontent.com/11452542/33228148-4030bc88-d1da-11e7-9f79-36c67d926164.png)

**Comment by nao-pon** [comment]
It's from elFinder >= 2.1.30, currently 2.1.29 now. Please try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip) until releases 2.1.30. And please don't forget clear cache of your browser.

**Comment by netdeveloper1job** [comment]
Hi,
After installation new version I got this error.  
![image](https://user-images.githubusercontent.com/11452542/33228978-ad10d8d6-d1eb-11e7-9325-a121c63f73c6.png)

**Comment by nao-pon** [comment]
In order to use GoogleDocs viewer, content must be placed on the published web.
