### ISSUE TITLE
Loading folder with ~300 files takes 10 seconds

### ISSUE THREAD

**Issue by drago-96** [Studio-42/elFinder#2275]
Hello, my problem is that when I try to open some folders with 300-500 files in it, the server takes more than 10 seconds to answer.
I am mounting an AFS volume as a LocalFileSystem; I know AFS could be the bottleneck, but `ls` is fast, and also [phpNavigator](http://navphp.sourceforge.net) works fine.
Maybe elFinder is trying to write something to the directories it opens, but www-data doesn't have the permission...

Then after the first loading, the next openings take the usual short time, thanks to caching I assume.

Can someone tell me which might be the critical points to debug, or how to increase the cache duration?
Thank you very much!

**Comment by nao-pon** [comment]
@drago-96 If there are many directories that are not displayed in elFinder in the current directory, performance will degrade. Using the connector 's roots option[ `'checkSubfolders' => -1`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#checksubfolders) will asynchronously check the subdirectory. Please try that setting.

**Comment by drago-96** [comment]
I was finally able to debug this issue.
It seems that the bottleneck is to detect the mimetype. In particular, `finfo_file` takes about 30ms per file, which is huge when I have hundreds of files.
The solution for me was simply to put [`'mimeDetect'=>'mime_content_type'`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#mimeDetect)

**Comment by curry684** [comment]
That comment saved us a lot of work, it should really be part of documentation somewhere. We had a customer complaining about initial load taking over 2 minutes (!!!). After switching detect method down to 9 seconds which is entirely acceptable (13500 images...)

**Comment by curry684** [comment]
Added a section to the Wiki:

https://github.com/Studio-42/elFinder/wiki/Common-issues
