### ISSUE TITLE
Testing version 2.1-src

### ISSUE THREAD

**Issue by Chaffinch** [Studio-42/elFinder#2279]
I'm testing version 2.1-src on:

http://elfinder.krynica-zdroj.eu

It's a strange mistake  :-((
There are files in the package:

http://elfinder.krynica-zdroj.eu/elfinder.src.html     	  ->>	It is O.K

http://elfinder.krynica-zdroj.eu/elfinder.playground.html ->>	It gives an error
Trash hash "t1_Lw" was not found or not writable.

http://elfinder.krynica-zdroj.eu/elfinder.html   	             ->>	It gives an error
1) Script error for "elfinder"
http://requirejs.org/docs/errors.html#scripterror

2) Script error for "extras/editors.default.min"
http://requirejs.org/docs/errors.html#scripterror
Then the white page

http://elfinder.krynica-zdroj.eu/elfinder.legacy.html     ->>	white page

**Comment by nao-pon** [comment]
@Chaffinch There is an error in the example of connector.php which elfinder.playground.html calls, so fix it. Since elfinder.html is for release package (2.1), it does not work on 2.1-src.

Thanks!
