### ISSUE TITLE
Auto Mount Google Drive On Load

### ISSUE THREAD

**Issue by Twinsen343** [Studio-42/elFinder#2281]
Hey Everyone,

I have checked the closed tickets in particular #1815 and am having some trouble achieving this.
I can manually mount the Google Drive via the Mount Network button no problem.

In my Roots array in the connector file I have the below and have got the refresh token by putting the package into debug as mention in the above issue\howto.

`array(`
`'driver' => 'GoogleDrive',`
`'alias' => 'Google Drive Root Folder',`
`'path' => 'root',`
`'refresh_token' => '1/**********************'`
`)`

Within the debug screen,  I have below where I get the refresh token  when I manually mount **mountErrors** stating

> Driver "elFinderVolumeGoogleDrive" : Class Google_Client not found.

However this is a little confusing as my paths are correct as it works when I manually mount the google drive so I know elFinder can see what it requires  & if I change anything with that then the Manual Mount does not work.

Any assistance would be great.

Cheers

**Comment by nao-pon** [comment]
@Twinsen343 This is a bug so I'll fix it. Thanks! 👍
