### ISSUE TITLE
get tmb form file name

### ISSUE THREAD

**Issue by vahidalvandi** [Studio-42/elFinder#2282]
hello , very thanks for awesome elfinder.
i use elfinder in my shop managment , then with dialog select the image, and save file name in db,

how i can get tmb name ?

**Comment by nao-pon** [comment]
@vahidalvandi You can get tmbname as "file.tmb" in `getFileCallback` callback function.

```javascript
getFileCallback : function(file, fm) {
    var url = file.url;
    var tmbname = file.tmb;
}
```

**Comment by vahidalvandi** [comment]
how i can dynamic tmb file name ?

i save original filename in db then in site display filename.jpg how i can get hash filename from   filename.jpg ??

**Comment by nao-pon** [comment]
Can you explain more concretely because I do not clearly understand what you want to do?

**Comment by nao-pon** [comment]
Since no response so I'll close it.
