### ISSUE TITLE
The Dropbox API v2 does not support mimetypes

### ISSUE THREAD

**Issue by MickaelTH** [Studio-42/elFinder#2285]
Hi,

Found a weird issue, not sure it is related to your script but maybe you found this before. I can see the folders, but then I cannot access folders with files:

![2017-11-18 002318](https://user-images.githubusercontent.com/26375917/32979448-fd9b4976-cc87-11e7-991a-83bb21e2bf68.png)

Any idea? Thanks.

**Comment by nao-pon** [comment]
@MickaelTH I guess "[spatie/flysystem-dropbox](https://github.com/spatie/flysystem-dropbox)" is issuing that message. If you are using that resource please ask their developers.

**Comment by MickaelTH** [comment]
Sure thing I wasn't sure where the issue came from. Thanks for reply.

**Comment by MickaelTH** [comment]
I just tried another one (https://packagist.org/packages/benjamincrozat/laravel-dropbox-driver) and still get the same message.

Am I wrong to assume elFinder is using mimetype to define files? Because it seems Dropbox v2 is using file extension instead.

**Comment by MickaelTH** [comment]
Ok this has been fixed in the adapter: https://github.com/spatie/flysystem-dropbox/commit/6af2f52fa14406d03031581a2969fb0d94832fb9
