### ISSUE TITLE
Thumbnail preview not showing

### ISSUE THREAD

**Issue by lab21gr** [Studio-42/elFinder#2296]
Hello i searched the other issues but i could not find an answer.

When i open elfinder, i see all my files & images but without preview

![image](https://user-images.githubusercontent.com/8777043/33269889-e020e568-d38a-11e7-8f02-6b26e38e86ac.png)

On my config i have tried setting 
`'tmbPath' => '',`

and also:

```
'tmbURL'        => $websiteURL.'uploaded/.tmb/',
'tmbPath'        => $websiteFolder.'uploaded/.tmb/',
```
both with no success.

my config:

```
$opts = array(
	'debug' => true,
    'modal' => true,
    'locale' => 'en_US.UTF-8',
	'roots' => array(
		// Items volume
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => $websiteFolder.'uploaded/',                 // path to files (REQUIRED)
			'URL'           => $websiteURL.'uploaded/',   // URL to files (REQUIRED)
                        'tmbPath' => '',

			'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access',                     // disable and hide dot starting files (OPTIONAL)

		)		
	)
);
```
What am i missing?

**Comment by nao-pon** [comment]
@lab21gr 

```php
'tmbURL'        => $websiteURL.'uploaded/.tmb/',
'tmbPath'        => $websiteFolder.'uploaded/.tmb/',
```

If there is no mistake in path and url, there is no. tmb directory or write permission for the PHP execution account.

**Comment by lab21gr** [comment]
Hello and thanks for the quick reply. No the folder is there with permissions 777. I can see the thumbs created in it. I just do not get a preview as you can see on the screenshot on my previous post.
If i inspect the code from the developer tools on my browser i do not see any background image applied to "elfinder-cwd-icon" class, as i see it on the online demo.

**Comment by nao-pon** [comment]
Please check your server responce of cmd `open`. Can you see `tmb` data of each item in `files` array?

**Comment by lab21gr** [comment]
I enabled the debug mode. On my console i see

elfinder debug: [event-open] [] 
{…}
api: "2.1029"
cwd: Object { isowner: false, ts: 1475567554, mime: "directory", … }
debug: Object { connector: "php", phpver: "7.1.8", time: 0.2116680145263672, … }
files: […]
0: Object { isowner: false, ts: 1509978996, mime: "directory", … }
1: {…}
hash: "l1_ZG93bmxvYWQtaWNvbnMvZG93bmxvYWRzX2F1dG9jYWQucG5n"
isowner: false
mime: "image/png"
**name: "downloads_autocad.png"**
phash: "l1_ZG93bmxvYWQtaWNvbnM"
read: 1
size: "2600"
tmb: "l1_ZG93bmxvYWQtaWNvbnMvZG93bmxvYWRzX2F1dG9jYWQucG5n1432189488.png"
ts: 1432189488
write: 1
....

If this is what you wanted, then yes i do see contents in the `file` array inside `event-open`.

`event-request.open` and `event-opendone` are empty. 

I open elfinder as a dialog:

```
$('<div></div>').dialogelfinder({
            debug: true,
            url: cmslink + 'vendor/elFinder/php/connector.minimal.php',
            commandsOptions: {
                getfile: {
                    oncomplete: 'destroy'
                }
            },
            getFileCallback: function(file, fm) {
                $("#"+inputId).val(file.url.replace(uploadedFolder, ''));
            },
            closeOnEditorCallback : true,
            width: 880,
            height: 590
});
```

**Comment by nao-pon** [comment]
OK, What value of `cwd` ? (detail of `cwd: Object { isowner: false, ts: 1475567554, mime: "directory", … }`)

**Comment by lab21gr** [comment]
You mean what is the value of cwd?

cwd: {…}
hash: "l1_ZG93bmxvYWQtaWNvbnM"
isowner: false
mime: "directory"
name: "download-icons"
phash: "l1_Lw"
read: 1
root: "l1_Lw"
size: 0
ts: 1475567554
volumeid: "l1_"
write: 1

**Comment by nao-pon** [comment]
No, I want see value of `cwd: {…}`.

**Comment by lab21gr** [comment]
sorry. here it is:

cwd: {…}
csscls: "elfinder-navbar-root-local"
dirs: 1
disabled: […]
0: "chmod"
length: 1
__proto__: Array []
hash: "l1_Lw"
isowner: false
isroot: 1
locked: 1
mime: "directory"
name: "uploaded"
phash: ""
read: 1
root: "l1_Lw"
rootRev: ""
size: 0
tmbUrl: "https://www.asset.gr/uploaded/.tmb/"
ts: 1510310897
volumeid: "l1_"
write: 1

**Comment by nao-pon** [comment]
Well. . . If it's that data thumbnail URL should be set. Does the same problem occur even with [nightly builds](https://github.com/Studio-42/elFinder/archive/2.1.zip)?

**Comment by lab21gr** [comment]
I will check...it works locally but not online. I will check and let you know.
thank you

**Comment by nao-pon** [comment]
For now, I will close this. Please reopen if elFinder finds something to fix.

**Comment by lab21gr** [comment]
Hello again

i have tried both the latest release and the nightly build as you suggested with no results.
On my localhost everything works fine.
However, online it does not.
The ONLY difference is that online i do not see the inline background image on the 'elfinder-cwd-icon' class as you can see below:
Locally:
`<div class="elfinder-cwd-icon elfinder-cwd-icon-image elfinder-cwd-icon-jpeg ui-corner-all elfinder-cwd-bgurl elfinder-cwd-bgurl-crop" unselectable="on" style="background-image: url(&quot;http://localhost/project/uploaded/.tmb/l1_bW9iaWxlX3Njcm9sbF90ZXN0LmpwZw1431677494.png?_t=1431677494&quot;);"></div>`
Online:
`<div class="elfinder-cwd-icon elfinder-cwd-icon-image elfinder-cwd-icon-jpeg ui-corner-all" unselectable="on"></div>`

Any ideas? I have tried everything...

**Comment by nao-pon** [comment]
@lab21gr If thumbnails are correctly created on the connector side, each file data should contain the value of tmb. Is there a problem with that value?

e.g
```json
{
  "isowner": false,
  "mime": "image/jpeg",
  "ts": 1448205671,
  "read": 1,
  "write": 0,
  "locked": 1,
  "size": "284800",
  "hash": "l1_SW1hZ2VzL2NvbG91cnNvZmZhbGwuanBn",
  "name": "coloursoffall.jpg",
  "phash": "l1_SW1hZ2Vz",
  "tmb": "l1_SW1hZ2VzL2NvbG91cnNvZmZhbGwuanBn1448205671.png"
}
```

**Comment by lab21gr** [comment]
Could you explain a bit more? where do i find this value?

**Comment by nao-pon** [comment]
In results of open request. It in `files` array.

**Comment by lab21gr** [comment]
The value for the first element is:

files: […]
0: {…}
csscls: "elfinder-navbar-root-local"
dirs: 1
disabled: Array [ "chmod" ]
hash: "l1_Lw"
isowner: false
isroot: 1
locked: 1
mime: "directory"
name: "uploaded"
phash: ""
read: 1
rootRev: ""
size: 0
tmbUrl: "https://www.domain.com/uploaded/.tmb/"
ts: 1513849201
volumeid: "l1_"
write: 1

**Comment by nao-pon** [comment]
It is the stat data of the directory. Look for the stat data of the file of the type in which the thumbnail is displayed.

**Comment by lab21gr** [comment]
I am sorry i do not understand what you need....can you be more specific?
I have the debug enabled so i looked into
elfinder debug: [event-open]  ->  files array 
and sent you the value for the first file.

**Comment by nao-pon** [comment]
OK, Please check server responce in browser developper tool's Network tab(XHR).

![171221-223659](https://user-images.githubusercontent.com/1412630/34257999-8cac6da8-e69f-11e7-8783-c8742747f4cd.png)

**Comment by lab21gr** [comment]
Great now i got it!

so for a file the value is

isowner: false
mime: image/jpeg
ts: 1431706296
read: 1
write	:1
size: 280375
hash: l1_bW9iaWxlX3Njcm9sbF90ZXN0Mi5qcGc
name: mobile_scroll_test2.jpg
phash: l1_Lw
tmb: l1_bW9iaWxlX3Njcm9sbF90ZXN0Mi5qcGc1431706296.png

**Comment by nao-pon** [comment]
OK, can you access to "https://www.domain.com/uploaded/.tmb/l1_bW9iaWxlX3Njcm9sbF90ZXN0Mi5qcGc1431706296.png" with the browser and thumbnail image is displayed?

**Comment by lab21gr** [comment]
No, i get 404 error.
However, if i go to the physical folder i can see the file.

**Comment by lab21gr** [comment]
I removed the dot from the begging of the folder .tmb and now it works!! it must be some server configuration...
Thanks for pointing me to the right direction!
Have a nice day!

**Comment by nao-pon** [comment]
Congrats! :+1:

**Comment by oleshek** [comment]
Hi, I have the same problem. Thumbnails are generated, access mode to them is 777, and I can view thumbnail from my brother if enter path to them but they are not related to files.

I'm using: 
[FMElfinderBundle](https://github.com/helios-ag/FMElfinderBundle)
Symfony 5.2
PHP 8.0.3

```
# config/packages/fm_elfinder.yaml
fm_elfinder:
    #assets_path: / # default is /assets, this is where css/js elfinder files are
    instances:
        form:
            locale: '%kernel.default_locale%' # defaults to current request locale
            editor: form # other choices are tinymce or simple, and form
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            connector:
                debug: true # defaults to false
                roots: # at least one root must be defined
                    uploads:
                        driver: LocalFileSystem
                        path: '%alert_files_base_url%'
                        url: '%alert_files_base_url%'
                        tmb_url: '%alert_files_base_url%/tmb/'
                        tmb_path: '%alert_files_base_url%/tmb/'
                        img_lib: gd
                        upload_allow: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'video/mp4', 'audio/mpeg', 'video/quicktime']
                        upload_deny: [ 'all' ]
                        upload_max_size: 20M
```
![img](https://user-images.githubusercontent.com/17884467/126160100-154f80d5-b3f1-40df-9227-440f5a808bae.png)
