### ISSUE TITLE
question: files php to edit?

### ISSUE THREAD

**Issue by wintstar** [Studio-42/elFinder#2297]
PHP: 7.1.11
Server Version: Apache/2.2.31 (Unix)

With Version 2.1.19  I could edit the php files. In the current version this does not work anymore. I have no special editor installed.

![edit-php](https://user-images.githubusercontent.com/2753863/33360916-310d8476-d4d6-11e7-96ae-9804dd485b8e.png)

**Comment by nao-pon** [comment]
@wintstar Is it possible to upload PHP files in your settings? PHP uploading is required to edit it.

**Comment by wintstar** [comment]
This is it, thank you. I noticed that the German language file is no longer up to date. Can I insert it in a new issue as a zip file? I don't know how to create a pull request with github.

**Comment by nao-pon** [comment]
Thank you for your notice. Please try the [i18n Translation Tool](http://studio-42.github.io/elFinder/tools/langman/#2.1:de).

**Comment by wintstar** [comment]
> Thank you for your notice. Please try the i18n Translation Tool.


Missing strings are translated. Did it according to the instructions.

**Comment by nao-pon** [comment]
OK, Please make new pull request on your https://github.com/wintstar/elFinder/tree/patch-1 .

**Comment by wintstar** [comment]
Sorry, but now it worked.
