### ISSUE TITLE
can't exit from error popup when creating duplicated folder name

### ISSUE THREAD

**Issue by badsaarow** [Studio-42/elFinder#2299]
I'm using a latest elFinder from master branch.  
I found weird popup when creating duplicated folder name.  My expectation is it allow to rename folder name.

step.
1. make new folder as "1"
2. try to make new folder as "1" - same folder name
3. elfinder show error  popup "File name 1 already exists."
4. Even if click "close" button or "x" icon, this error popup appear again.  So I can't rename folder name. 
 Only ESC key is working.  After pressing ESC key, I can rename folder name.

![elfinder](https://user-images.githubusercontent.com/6446223/33412804-1378d84c-d5d1-11e7-9960-c3472729f00d.png)

**Comment by nao-pon** [comment]
@badsaarow It seems that there is no problem with the latest 2.1.30 I tried. Please use the latest version and check if there is a similar problem.

**Comment by badsaarow** [comment]
@nao-pon I missed browser information.  
That occurs only IE.  Currently My IE is 11.1000.17025.0
When I tested firefox and chrome, it works correctly.

**Comment by nao-pon** [comment]
OK, I also checked with IE 11.729.15063.0 - 11.0.48(KB4047206). But there is no problems. I can close dialog with Enter, [Close], or  [X], Is there a similar problem on [our demo site](https://studio-42.github.io/elFinder/#elf_l2_Lw)?

**Comment by badsaarow** [comment]
There no similar problem on your demo site.  It work well.
I pulled again with latest version.  it's 2.1.30.  But still produce in my computer.
It might be my pc's problem.
I'm using elfinder.src.html.  I'll check again my condition.

**Comment by badsaarow** [comment]
@nao-pon 
I found IIS affect this.

I tried to compare IIS and apache.  
Other condition is equal.  OS is Windows 10 Home edition.
IIS + PHP : cannot close dialog with Enter, Close or X.
Apache + PHP : can close dialog.

But I don't know how I can make working in IIS condition?

**Comment by nao-pon** [comment]
I do not think that this problem is different due to the difference of the back end. However, there may be some error in the previous request. Is there a JavaScript error in developer tool?

**Comment by badsaarow** [comment]
There is no javascript error in console at developer tools.  
If you let me know where can I leave log message, it will be helpful to trace it.

**Comment by nao-pon** [comment]
The dialog closing behavior is executed in [dialog.js](https://github.com/Studio-42/elFinder/blob/master/js/ui/dialog.js#L384). Please check whether the sequence arrives there.

**Comment by badsaarow** [comment]
From javascript source tracing, 
1. click "close" button.
2. dialog.js's close event is excuted.
3. dialog.js's open event is excuted immediately.

I don't know why dialog's "open" event is triggered after close event.

Below is the call stack when "open" event triggered.
![el-js](https://user-images.githubusercontent.com/6446223/33421799-a74c7d2e-d5f6-11e7-9636-32859522e48a.png)

**Comment by nao-pon** [comment]
It is a very strange behavior. However, when I checked the code, I found another point to fix and fixed it. Please reacquire the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip) or [master](https://github.com/Studio-42/elFinder/archive/master.zip) and try it. (Do not forget to clear the cache of the browser)

**Comment by badsaarow** [comment]
It resolved by latest master.  Thank you.
