### ISSUE TITLE
uploading failed for Korean file name

### ISSUE THREAD

**Issue by badsaarow** [Studio-42/elFinder#2301]
I have a trouble in uploading Korean file name file.

My working environment is below.
1. elFinder version : 2.1.30 (master branch source)
2. Server : IIS Express 11.0 + FastCGI php handler
3. Client : IE 11, Firefox, Chrome
4. upload file name : "테스트.txt" - fail
5. upload file name : "1.txt" - success (just rename above file)

My tries.
1. Checking in your demo site.  it works. no problem
2. Compare mine and demo site.

connector responded with content-type : text/html
![elfinder-my](https://user-images.githubusercontent.com/6446223/33418779-d95bc3ee-d5ea-11e7-9b8a-d701180e4e76.png)

and response's body is below.
![elfinder-my2](https://user-images.githubusercontent.com/6446223/33418829-101b690c-d5eb-11e7-9ffe-23ef27491765.png)

Difference is connector's response.  It should respond with application/json content-type like as your demo site.  

What I checked to resolve this?

**Comment by nao-pon** [comment]
@badsaarow To handle file systems other than UTF-8 in elFinder, you need to specify the [locale](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locallocale) and [encoding](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding) of the connector roots setting appropriately.

The locale setting in the Windows environment is "<language>_<country>.<code_page>". Also in the case of Korean encoding is "CP949"? I do not know well.

**Comment by badsaarow** [comment]
@nao-pon 
Thank you.
With your help, I can upload Korean file named file.  
I added "encoding'      => 'CP949'," to my connector roots setting.
