### ISSUE TITLE
Open html files in browser instead of downloading

### ISSUE THREAD

**Issue by bisherbas** [Studio-42/elFinder#2302]
I have got html files uploaded to the file manager. When I double click on the html file, I would like it to open in a new browser tab. But the file gets downloaded instead. How can I accomplish this? I am new to elFinder so please tell me what file to change if you make any suggestions. Thanks a lot!

**Comment by nao-pon** [comment]
@bisherbas Please check connector roots option [`dispInlineRegex`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#dispinlineregex) in the Wiki And client config [`commandsOptions.open.into`](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L254-L256).

Notice: Please keep in mind that you should only allow trusted files for HTML inline display to avoid creating XSS vulnerabilities.
