### ISSUE TITLE
context menu is not working before refresh

### ISSUE THREAD

**Issue by badsaarow** [Studio-42/elFinder#2304]
When I try to context menu after uploading file, it doesn't work.
Demo site works well.  It happen only my environment.

Server: IIS 10.0 + PHP
Client : IE 11.    (Firefox and chrome works well).
elFinder version : today's latest version

Reproduce step.
1. upload file
2. click right button of new uploaded-file, but no response.
3. reload,  now context menu working.

**Comment by nao-pon** [comment]
@badsaarow IE is in compatibility mode. Please add `<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">` to maneger HTML.

So I'll fix example HTML files.

**Comment by badsaarow** [comment]
Thanks.  Now it works.
