### ISSUE TITLE
Full screen works only IE, not firefox and chrome.

### ISSUE THREAD

**Issue by badsaarow** [Studio-42/elFinder#2305]
How to launch elFinder to full screen mode?

My code is below.

```
var instance = $('#elfinder').elfinder(
...
).elfinder('instance');
instance.exec('fullscreen');
```
It works only IE.  
My test url is  http://test.park119.com/admin/elFinder/elfinder.src.html

How can I do to work?

**Comment by nao-pon** [comment]
@badsaarow With the modern browser, full screen mode can not be switched without user intervention.

**Comment by badsaarow** [comment]
@nao-pon  I want to use full screen as http://output.jsbin.com/gowemuq#elf_l1_Lw.  I think this demo doesn't require user intervention.

**Comment by nao-pon** [comment]
OK, You can use client configuration option `height` to `'100%'` if  you want to fit size to browser window.

``` javascript
opts : {
    url : 'php/connector.minimul.php',
    width: '100%',
    height: '100%',
    resizable: false
}
```

And I think that it is a good idea to eliminate the margin of <body> and the border of the elFinder node.

```html
<body style="margin:0; padding:0;">
    <div id="elfinder" style="width:100%; height:100%; border:none;"></div>
</body>
```
