### ISSUE TITLE
Image URL returns as elfinder/connector? not absolute path

### ISSUE THREAD

**Issue by packytagliaferro** [Studio-42/elFinder#2307]
What I did:

Clicked on WYSIWIG to add image in text. Elfinder pops up and I click browse. I can see all the images in my Digital Ocean Spaces server and their path. I click on one and it adds it to my WYSIWYG.

What I expected to happen:

Add image with correct url to the image (https://acoolsite.nyc3.digitaloceanspaces.com/posts/10578_432266693547706_1658074314_n.jpg)

What happened:

Get some funky url that will only work if user is signed in. It needs to be the absolute path to the image. (http://acoolsite.dev/admin/elfinder/connector?_token=uTw17WEtWI4oZM8fvAHK6riPs8mwIEquK0zt1Kzd&cmd=file&target=fls2_cG9zdHMvMTI3MTEzMDhfMTAxNTI5NjM2NTI3ODI4MjRfNjcxMTM1ODEzMjMzMTIzNjExOF9vLmpwZw)

What I've already tried to fix it:

Config the elFinder and ask on StackOverflow

Currently using elFinder with  Laravel 5.5 | Backpack ^3.2

**Comment by nao-pon** [comment]
@packytagliaferro Please set connector roots option [`URL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#URL).
