### ISSUE TITLE
can't upload by "paste url or images" on IE

### ISSUE THREAD

**Issue by badsaarow** [Studio-42/elFinder#2312]
elFinder's uploading feature provides "pasteURL" or "iamges(clipboard)".
But These are not working in IE. (My IE is 11).
Compared to Firefox, it works.  So it happens only IE.

I tried to test in demo site, today demo site(https://studio-42.github.io/elFinder/) is not working at all in IE.

**Comment by nao-pon** [comment]
@badsaarow I checked on our demo site with IE 11.729.15063.0 (Windows10 64bit). It was no problems. Is there any error on the browser console?

**Comment by badsaarow** [comment]
@nao-pon Now demo site become works well.   But still mine has problem.

console message is "elfinder debug: [event-destroy"

browser's error popup is "Upload error.  No files found for upload."

It might be caused my invalid setting.  I'll check my source again.

**Comment by nao-pon** [comment]
Specify document mode as edge for IE.

c.f f040fe041a4dfff6530c8545767d5f81636b6a59

**Comment by badsaarow** [comment]
@nao-pon I had specified that mode.  But same error occurs.

When I checked network, connector returns as below.
`{"error":["errUpload","errUploadNoFiles"]}`

Here are my browser's request.

**request header**
```
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: ko-KR
Cache-Control: no-cache
Connection: Keep-Alive
Content-Length: 5700
Content-Type: multipart/form-data; boundary=---------------------------7e154288075c
Cookie: wcs_bt=a0650b9a7166a4:1510642836|52366354c02098:1510642836; PHPSESSID=u8urtbb2g7c4mlfcgmi5s5cq8k; ASPSESSIONIDCQSDDQBR=NONFFKJDHMKJFIOPGBJLJKJO; _gid=GA1.2.1396140972.1513062167; _ga=GA1.2.1504835335.1510632839
Host: test.park119.com
Referer: http://192.168.123.123/admin/elFinder/elfinder.src.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko
X-Requested-With: XMLHttpRequest
```

**request body**
```
----------------------------7e154288075c
Content-Disposition: form-data; name="reqid"

16049de66171ca
-----------------------------7e154288075c
Content-Disposition: form-data; name="cmd"

upload
-----------------------------7e154288075c
Content-Disposition: form-data; name="target"

l1_TmV3Rm9sZGVyIDE
-----------------------------7e154288075c
Content-Disposition: form-data; name="upload[]"

data:image/png;base64,
......
-----------------------------7e154288075c
Content-Disposition: form-data; name="name[]"

171212-173640.png
-----------------------------7e154288075c
Content-Disposition: form-data; name="mtime[]"

0
-----------------------------7e154288075c
Content-Disposition: form-data; name="overwrite"

0
-----------------------------7e154288075c--
```

**Comment by nao-pon** [comment]
On my test site, there is no problem with the next transmission data. I can not reproduce the problem, so I do not know the cause.

**request header**
```
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: ja-JP
Cache-Control: no-cache
Connection: Keep-Alive
Content-Length: 339663
Content-Type: multipart/form-data; boundary=---------------------------7e123a2e6d07d6
Cookie: _ga=GA1.xxxxxxxxxxxxxxxx; PHPSESSID=xxxxxxxxxxxxxxxx
Host: hypweb.net
Referer: https://hypweb.net/elFinder-nightly/demo/2.1/
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
```

**request body**
```
-----------------------------7e123a2e6d07d6
Content-Disposition: form-data; name="reqid"

1604b2d953022a
-----------------------------7e123a2e6d07d6
Content-Disposition: form-data; name="cmd"

upload
-----------------------------7e123a2e6d07d6
Content-Disposition: form-data; name="target"

l3_YWFhMQ
-----------------------------7e123a2e6d07d6
Content-Disposition: form-data; name="upload[]"

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABVYAAAMACAYAAADPPjzCAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcE
....
-----------------------------7e123a2e6d07d6
Content-Disposition: form-data; name="name[]"

171212-234246.png
-----------------------------7e123a2e6d07d6
Content-Disposition: form-data; name="mtime[]"

0
-----------------------------7e123a2e6d07d6
Content-Disposition: form-data; name="overwrite"

0
-----------------------------7e123a2e6d07d6--
```

**Comment by badsaarow** [comment]
@nao-pon   It's weird.  
If you are available, could you visit my test site http://test.park119.com/admin/elFinder/elfinder.src.html.  This issue happen only IE.    
When I compared request between IE and FF,chrome, I didn't find differences.

**Comment by nao-pon** [comment]
I found a bug that can not this function with PHP setting `allow_url_fopen` and `allow_url_include` are off. so   I fixed it.

**Comment by badsaarow** [comment]
Greate!.
Thank you.

**Comment by badsaarow** [comment]
@nao-pon The issue still remains on mime.  Could you visit again http://test.park119.com/admin/elFinder/elfinder.src.html?  It was applied till 7f9e31c, 12 Dec master branch
