### ISSUE TITLE
showing file with it's directory name

### ISSUE THREAD

**Issue by badsaarow** [Studio-42/elFinder#2314]
I'm using elFinder on IIS 11.0 on Windows 2008 Korean edition.

If file exist in Korean folder name, elFinder show with folder name.

![image](https://user-images.githubusercontent.com/6446223/33644981-b7ad13b0-da8b-11e7-9b63-5e86679b8e6d.png)

When I check the body packet.
connector returns with "name":"\ub9e4\ub274\uc5bc\\manual.pdf"

If folder name is English, it works well.  It is only occurred Korean folder name.

My connector is set as below.
```
'roots' => array(
	// Items volume
	array(
		'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
		'path'          => '/WebPark/GwanParking_Files/elFinder/',                 // path to files (REQUIRED)
		'URL'           => '', // URL to files (REQUIRED)
		'trashHash'     => 't1_Lw',                     // elFinder's hash of trash folder
		'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
		'uploadDeny'    => array('exe', 'asp', 'aspx', 'php', 'js'),                // All Mimetypes not allowed to upload
		'uploadAllow'   => array('all'),// Mimetype `image` and `text/plain` allowed to upload
		'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
		//'encoding'      => 'CP949',
		'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
	),

```

**Comment by nao-pon** [comment]
@badsaarow Please try setting the `'locale'` of the `'roots'` option correctly.

**Comment by badsaarow** [comment]
@nao-pon 
I set locale with below values.

'locale'        => 'korean_korea.949',
'locale'        => 'korean_korea.CP949',
'locale'        => 'ko_KR.UTF-8',
'locale'        => 'ko_KR.EUC-KR',
'locale'        => 'ko_KR.CP949',

But result is same.

Could you please let me know where I can check by adding console.log or logging in connector php?

**Comment by nao-pon** [comment]
There is probably a problem in the part using the `dirname()`, `basebname()` function.

And, please try next setting.
```php
'locale' => 'korean_korea.65001', // or 'locale' => 'korean_korea.1252',
'roots' => array(
	// Items volume
	array(
		'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
		'path'          => '/WebPark/GwanParking_Files/elFinder/',                 // path to files (REQUIRED)
		'URL'           => '', // URL to files (REQUIRED)
		'trashHash'     => 't1_Lw',                     // elFinder's hash of trash folder
		'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
		'uploadDeny'    => array('exe', 'asp', 'aspx', 'php', 'js'),                // All Mimetypes not allowed to upload
		'uploadAllow'   => array('all'),// Mimetype `image` and `text/plain` allowed to upload
		'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
		'encoding'      => 'CP949',
		'locale'        => 'korean_korea.949',
		'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
	)
)
```

**Comment by nao-pon** [comment]
@badsaarow Please try PHP 7.1 or higher if possible. Since it supports UTF - 8 path, it may be good without setting `encoding`.

**Comment by badsaarow** [comment]
@nao-pon 
My PHP version is 7.2.0.  
And my setting is
```
	'roots' => array(
		// Items volume
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '/WebPark/GwanParking_Files/elFinder/',                 // path to files (REQUIRED)
			'URL'           => '', // URL to files (REQUIRED)
			'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
			'uploadDeny'    => array('exe', 'asp', 'aspx', 'php', 'js'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('all'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'locale'        => 'korean_korea.1252',  //'korean_korea.65001' is also result.
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		)
	)
```
I also fetch latest master branch with "[php] correction to PHP >= 7.1 supported UTF-8 path on Windows"

But result is same.

**Comment by nao-pon** [comment]
@badsaarow I do not know the cause. Do you have any information on the handling of Korean pass on Windows server?

**Comment by badsaarow** [comment]
@nao-pon On Windows server, I don't think path scheme is different from others.   I think it may same scheme to Japanse.   My little guess is php code on windows have some issue on getting directory list.

I hope I could debugging connector code. 
Unfortunately, I have no knowledge about PHP.  If you let me know debugging point for php file, I might find some clue.

**Comment by nao-pon** [comment]
@badsaarow Please try next settings. and Please check result of [`elFinderVolumeLocalFileSystem::_basename()`](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeLocalFileSystem.class.php#L268-L270).

```php
	'locale' => 'korean_korea.65001', // or 'locale' => 'korean_korea.1252',
	'roots' => array(
		// Items volume
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '/WebPark/GwanParking_Files/elFinder/',                 // path to files (REQUIRED)
			'URL'           => '', // URL to files (REQUIRED)
			'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
			'uploadDeny'    => array('exe', 'asp', 'aspx', 'php', 'js'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('all'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			// (comment out) 'locale'        => 'korean_korea.1252',  //'korean_korea.65001' is also result.
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		)
	)
```

**Comment by badsaarow** [comment]
@nao-pon `'locale' => 'korean_korea.1252' ` works perfectly!

Would you let me understand the reason?  
I'm wonder that should be mandatory option for all Korean Windows users.  
As far as I know, "1252" is not related to Korean encoding.  But why this fix this issue?

Thank you very much.

**Comment by nao-pon** [comment]
@badsaarow Since elFinder is being processed by UTF-8, it is necessary to specify the locale setting to UTF-8 (Windows code page 65001), but it seems that it can not be set to 65001. Thus, setting the standard code page 1252, it make reduce the problem of UTF-8 processing.

**Comment by nao-pon** [comment]
@badsaarow I tried setting "C" locale for Windows server. Please let us know the result of using [that version](https://github.com/Studio-42/elFinder/blob/42b0c0ef1477c60f9f7df1d54654de9fcd7a5e8e/php/elFinder.class.php).

**Comment by badsaarow** [comment]
@nao-pon It works well.   
I modifed to 

> 'locale' => 'C'

Your latest master branch works well in my condition.
Thank you.

**Comment by nao-pon** [comment]
@badsaarow Thank you for your contribute!
