### ISSUE TITLE
Multiple files rename suggestions

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2315]
Its better if we can rename user given pattern or some words can add original file name. 
Also its better if user can rename extention every selected files in multiple rename. 
![screenshot_20171206-132204](https://user-images.githubusercontent.com/18566890/33650640-daf0e304-da88-11e7-8cf1-19359a69f5fa.jpg)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thanks! I done.

- add an extras icon to open batch rename dialog in contextmenu
- it can be to use query word "*" that original filename at inline rename input box
    - original filename is "text.txt"
        - "*abc.txt" to "textabc.txt"
        - "abc*.txt" to "abctext.txt"
        - "*.csv" to "text.csv"

**Comment by CodeLyokoXtEAM** [comment]
I think user can short files number oder. I mean number oder can set using created date, file size or alphabetical oder (user selected oder).
Also its impossible to rename if user selected different file types files.

**Comment by CodeLyokoXtEAM** [comment]
Also I wanted to rename files like 1.jpg, 2.jpg, .......
But there isn't any option to do it.
So I leave space in name & it say it will be rename like this
![screenshot_20171208-183657](https://user-images.githubusercontent.com/18566890/33767264-f111f56e-dc46-11e7-8395-fc3310209a44.jpg)

But actually it rename like this
![screenshot_20171208-183725](https://user-images.githubusercontent.com/18566890/33767287-0658fe54-dc47-11e7-882c-4279a15622ec.jpg)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM The order is processed in the order selected by the user. However, since the current sort order is not applied when choosing the whole, I will fix it.

Also, I will modify it so that I can make a batch rename only by increment numbers.

However, it is a desigin that you can not batch rename files with different extensions.
