### ISSUE TITLE
Can't Open Backend

### ISSUE THREAD

**Issue by amcap2** [Studio-42/elFinder#2317]
When trying to upload and image for a open cart (1.5) listing we get "Can't Open Backend" error message.  Please advise.

Thank you,
Amcap2

**Comment by amcap2** [comment]
Revised "Unable to Connect to the Backend"

Thank you for your help,

Amcap2

**Comment by nao-pon** [comment]
Please enable [`debug`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#debug) in the connector setting and check the details of the error. However, I do not know the error caused by the open cart.

**Comment by terrysharp** [comment]
Hello,

I have to a backend error.
"Mauvaise réponse du backend.
Un erreur est survenue du côté serveur.
HTTP error 500"

My path is : 'driver'        => 'LocalFileSystem',
                        'path'          => FCPATH . '/medias',
                        'URL'           => base_url('medias'),

**Comment by nao-pon** [comment]
@terrysharp HTTP error 500 indicates that PHP stopped with an error. You need to know the details of the error. Have you tried 'connector' setting [`debug`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#debug)?

**Comment by terrysharp** [comment]
Hello, thanks for reply.
Yes I activate debug but it give me no more details about the error (se below). 
Was it possible that eflinder display the interface but dont find the function connector to connect to backend ?
**************************************
$opts = array(
                'debug' => true,
                'roots' => array(
                    array( 
                        'driver'        => 'LocalFileSystem',
                        'path'          => FCPATH . '/medias',
                        'URL'           => base_url('medias'),
                        'uploadDeny'    => array('all'),  // All Mimetypes not allowed to upload
                        'uploadAllow'   => array('image', 'text/plain', 'application/pdf'),// Mimetype `image` and `text/plain` allowed to upload
                        'uploadOrder'   => array('deny', 'allow'), // allowed Mimetype `image` and `text/plain` only
                        'accessControl' => array($this, 'elfinderAccess'),// disable and hide dot starting files (OPTIONAL)
                        // more elFinder options here
                    ) 
                ),
            );
            $connector = new elFinderConnector(new elFinder($opts));
            $connector->run();
**************************************************

**Comment by nao-pon** [comment]
@terrysharp Have you looked at the Wiki page ([Integration with CodeIgniter](https://github.com/Studio-42/elFinder/wiki/Integration-with-CodeIgniter)) and integrated it? The autoloader does not seem to work.

**Comment by terrysharp** [comment]
Hey, it's exactkly this code I use.
But I find weird that we use "$connector = new elFinderConnector(new elFinder($opts));"
and the class is called "connector" !!

**Comment by nao-pon** [comment]
Since `$connector` is a variable name, there is no problem. Please make sure CodeIgniter config `$config['composer_autoload'] = TRUE;`

By the way, it has nothing to do with the problem this time, but I edited the wiki. See [Diff](https://github.com/Studio-42/elFinder/wiki/Integration-with-CodeIgniter/_compare/6e2ebe3e926be8c06a8fb680e5c9d60ca4f1893a...7def3770f35a2c71606fa0fd01897fa1c6a0fda6).
