### ISSUE TITLE
A version without external requests?

### ISSUE THREAD

**Issue by Offerel** [Studio-42/elFinder#2319]
Hi there,

is there a way that i can please have a elFinder Version without external requests like them to Cloudflare?

**Comment by nao-pon** [comment]
@Offerel Yes of course.

Please rewrite next URL to local location.
- elfinder.html
    - [require.min.js](https://github.com/Studio-42/elFinder/blob/master/elfinder.html#L11)
- main.default.js
    - require.config
        - [paths](https://github.com/Studio-42/elFinder/blob/master/main.default.js#L112-L113)
- client config option
    - [cdns](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L13-L26)
    - an example on [elfinder.html](https://github.com/Studio-42/elFinder/blob/master/elfinder.html#L55-L58)
```javascript
managers : {
    // 'DOM Element ID': { /* elFinder options of this DOM Element */ }
    'elfinder': {
        cdns : {} // if you don't need extra editor and viewer.
    }
}

**Comment by Offerel** [comment]
i try my luck in the evening and report if it works. main reason is, that i have a relative strict CSP Header definition on my own nginx server and me and my family are the only person's who use this server currently.

BTW: i would like you to know, that i have made a experimental plugin for Roundcube Webmailer, which includes elFinder directly in to Roundcube. It was in first place only for my personal needs, but i think it's ok to share it with the community. You can find it at https://github.com/Offerel/roundcube_storage

**Comment by nao-pon** [comment]
@Offerel Invalidating options.cdns requires setting each value to empty instead of `{}`. However, since there was a problem that some empty values could not be accepted, So I fixed it with a commit a935bf5e5bf6596c1a0f50eb1f7cb625c1c160c8.

```javascript
cdns : {
    // for editor etc.
    ace        : null, // or your location
    codemirror : null, // or your location
    ckeditor   : null, // or your location
    tinymce    : null, // or your location
    simplemde  : null, // or your location
    // for quicklook etc.
    hls        : null, // or your location
    dash       : null, // or your location
    prettify   : null, // or your location
    psd        : null, // or your location
    rar        : null, // or your location
    zlibUnzip  : null, // or your location
    zlibGunzip : null  // or your location
}
```

BTW, I added a link of your https://github.com/Offerel/roundcube_storage into README.md. Thanks! 👍

**Comment by Offerel** [comment]
Great, i change this in a next release. Currently I'm in the hospital, my gallbladder must be removed urgently. I had the additional idea, that i could use elfinder also for adding and saving attachments from and within the webmail GUI. I will try to implement this. However the current implementation was a first start. With this and my calendar plugin, Roundcube works really fast and better as a Nextcloud instance on the same hardware.

**Comment by nao-pon** [comment]
I do hope you feel better soon and I am wishing you a speedy recovery. And when you recover please let me know your great ideas!

**Comment by Offerel** [comment]
Just let you know I'm back. There are now 2 new versions of the plugin. The version of just now adds the function to select attachments directly from elFinder and attach them to the mail.

A kind of notebook function is now planned. You should be able to create and change notes in HTML format with tinyMCE and elFinder. If I have the time for Android, there will be a companion app for Android. I've just never been into Android development before.

**Comment by Offerel** [comment]
One question to this topic. I have checked out now elFinder-2.1.31 and want to try a local ckeditor. But now, when i rightclick on a html file, there is no edit-submenu. Is this a bug?

**Comment by nao-pon** [comment]
@Offerel Yes, I found a bug of editing with local CKEditor. So I'll fix it.

**Comment by nao-pon** [comment]
@Offerel I fixed it. Please try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

with...
```javascript
opts : {
    url : 'php/connector.php',
    cdns : {
        // for editor etc.
        ace        : null, // or your location
        codemirror : null, // or your location
        ckeditor   : 'Your CKEditor directory location (without last `/`)',
        tinymce    : null, // or your location
        simplemde  : null, // or your location
        // for quicklook etc.
        hls        : null, // or your location
        dash       : null, // or your location
        prettify   : null, // or your location
        psd        : null, // or your location
        rar        : null, // or your location
        zlibUnzip  : null, // or your location
        zlibGunzip : null  // or your location
    }
}
```

**Comment by Offerel** [comment]
ahh this works better. Sorry for this late reply but my good old Rasperry Pi died at the weekend and i could by today a new one. I try now to config my local CKEditor
