### ISSUE TITLE
Files with the same name on upload are always replaced, regardless of uploadOverwrite option

### ISSUE THREAD

**Issue by apotheosis91** [Studio-42/elFinder#2320]
Steps to reproduce:
1. Go to the [page with elFinder](https://studio-42.github.io/elFinder).
2. Click on `Upload files` button, then on `Select files` and upload the file with the name `file.txt`.
3. Repeat step 2.
4. In the appeared `file already exists` window click on the `rename` button.
5. The file is not renamed, but replaced.😞

When I drag the file to elFinder, renaming works fine. 

After some debugging, I found a [commit](https://github.com/Studio-42/elFinder/commit/4ecbf70969435bc718b3a7ef61bd8cc8c8a01f7f), after which, probably, this issue occurs. 
Function `isNameExists` overriden in `elFinderVolumeLocalFileSystem.class` and returns boolean. And because of it, [this check](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeDriver.class.php#L2356-L2367) can not be passed.

I tried to delete this overridden function and, it seems, in my case, all works fine. But I use elFinder with many disabled options and I'm not sure I did not break anything else. :smile:

**Comment by nao-pon** [comment]
@apotheosis91 I found a client bug in elfinder.js. so I'll fix it.

Thanks! 👍
