### ISSUE TITLE
how to restrict upload the max file sizes  

### ISSUE THREAD

**Issue by jeremyzhou2001** [Studio-42/elFinder#2322]
1. elfinder version is 2.1.29
2 php7/php.ini
; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 1024M

; Whether PHP will read the POST data.
; This option is enabled by default.
; Most likely, you won't want to disable this option globally. It causes $_POST
; and $_FILES to always be empty; the only way you will be able to read the
; POST data will be through the php://input stream wrapper. This can be useful
; to proxy requests or to process the POST data in a memory efficient fashion.
; http://php.net/enable-post-data-reading
enable_post_data_reading = On

; Maximum size of POST data that PHP will accept.
; Its value may be 0 to disable the limit. It is ignored if POST data reading
; is disabled through enable_post_data_reading.
; http://php.net/post-max-size
post_max_size = 1024M

but it doesn't work

**Comment by nao-pon** [comment]
@jeremyzhou2001 Please check the Wiki's Connector roots option [`uploadMaxSize`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadmaxsize).

**Comment by jeremyzhou2001** [comment]
@nao-pon thanks!
