### ISSUE TITLE
roots alias is wrong sometimes, why and how to solve it ?

### ISSUE THREAD

**Issue by fjibj** [Studio-42/elFinder#2325]
i found a problem when i use elfinder with layer ui:
i have a list in index.html, each line has different hostname and ip，and a button "SFTP" to open a layer of elfinder dialog(asset_sftp.html), it's code as:
```
<a href="#"><li class="btn btn-sm btn-info" onclick="return file_browser(this.value)" value="{{ host.id }}">SFTP</li></a>
<script>
function file_browser(n){
	layer.open({
    type: 2,
    title: 'file browser',
    closeBtn: 1,
	maxmin: true,
	moveOut: true,
    area: ['700px', '600px'],
    shadeClose: true, 
    content: ['/cmdb/asset/sftp/' + n,],
  });
}
```
asset_sftp.html:
```
<div>
{{ obj.hostname }}-{{ obj.ip }} <button type="button" onclick="closeElfinder()">Close</button>
</div>
<div id="elfinder"></div>
<script type="text/javascript">
	//alert(hostname);
	//$().ready(function() {
	var elf = $('#elfinder').elfinder({
			resizable: false,
			height: '100%',
			url : '/elfinder/yawd-connector/sftp/{{ obj.hostname }}/',
			lang: 'en'                    
		}).elfinder('instance');
		
	//});

	function closeElfinder() {
		if(elf) elf.destroy();
		elf = null;
		var index = parent.layer.getFrameIndex(window.name); 
        parent.layer.close(index);
	}
</script>
```
in most time in open layer, "{{ obj.hostname }}-{{ obj.ip }} " and elfinder "root alias" are same, but sometimes they are different, "{{ obj.hostname }}-{{ obj.ip }} " is always right , but root alias(in the left corner of elfinder tree list) was wrong( so it maybe open a wrong host). i think maybe some reason of cache, but  i have destroy the elfinder instance. 
why and how to resolve it , pls help me.

**Comment by nao-pon** [comment]
@fjibj That is due to cache as you guessed. Please specify the unique value of each host in the volume roots option [`rootRev`](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeDriver.class.php#L212-L213).

**Comment by fjibj** [comment]
i have add rootRev as below but the problem is still.
`optinon_sets = {
				'debug' : True,
				'roots' : [
					{
						'id' : 'pdfid',
                        'rootRev' : server_object.ip,
						'alias' : '{0}-{1}'.format(server_object.hostname,server_object.ip),                        
						'driver' : ElfinderVolumeStorage,
						'storageClass': 'storages.backends.sftpstorage.SFTPStorage',
						'keepAlive' : False,
						'cache' : 300
					} 
				]  
			}`

**Comment by nao-pon** [comment]
@fjibj Is elFinder the latest version?

**Comment by fjibj** [comment]
2.1.30

**Comment by nao-pon** [comment]
If you are using [barryvdh/elfinder-flysystem-driver ](https://github.com/barryvdh/elfinder-flysystem-driver)please try set `'cache'` to `'memory'` or `false`.

**Comment by fjibj** [comment]
when i set 'cache' to false, it's worked.  thanks very much. @nao-pon
