### ISSUE TITLE
Загрузка файлов другого формата

### ISSUE THREAD

**Issue by Mandzuk** [Studio-42/elFinder#2327]
Добрый день. Подскажите, пожалуйста, как можно реализовать загрузку других файлов, к примеру формата mp3 ? Вот мой конфиг
`'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\Controller',
            'access' => ['@'],
            'disabledCommands' => ['netmount'], 
            'roots' => [
                [
                    'baseUrl'=>Yii::$app->params['frontend_url'],
                    'basePath'=>'@frontend/web',
                    'path' => 'files/global',
                    'name' => 'Global',
                ],
            ]
        ]
    ]`

**Comment by nao-pon** [comment]
@Mandzuk Sorry, Please English toking.

**Comment by Mandzuk** [comment]
Sory.  How I can load files format mp3 and pdf ?
