### ISSUE TITLE
Is elFinder streaming files when clicking on a folder?

### ISSUE THREAD

**Issue by MickaelTH** [Studio-42/elFinder#2328]
Hi,

Very strange things here, but after 2 days of investigation we found something that may be related to issue #2041

When clicking on a folder from a disk, it often finishes with 504, meaning timeout:

![2017-12-13 002424](https://user-images.githubusercontent.com/26375917/33947731-c72aacfe-e057-11e7-9095-27a797b8f8cd.png)

For testing we installed the same elFinder on 3 locations (UK, US, SG) and linked to the same VMs in UK. And tried to read the list of files elFinder via SFTP.

UK was fine (2-3 seconds), but US and SG just timeout.

Ok something fishy here, maybe network? No we tested and we had in UK 10ms, and US and SG displayed 110ms.

After 2 days of investigation, we found that, when we clicked on a folder on elFinder, the actual command in the VM (in UK if you followed until here), elFinder was reading/streaming files on the VMs.

The screenshot below show that commands from elFinder reading a 24Mb mp4 files instead of only doing listing.

![img_13122017_194631_0](https://user-images.githubusercontent.com/26375917/33948154-c8654812-e058-11e7-8b35-76cdc1f0f0fe.png)

By doing that, elFinder timeout on US and SG as we have folders displaying 100+Mb. 

Any idea why is that? Something we forgot to setup or anything that can help us to continue investigation?

Thank you

**Comment by nao-pon** [comment]
@MickaelTH Are you using FlySystem's adapter? Depending on the configuration, the adapter may request content for MIME-Type determination. (I do not know well)

**Comment by MickaelTH** [comment]
@nao-pon Thanks for quick answer.

Yes we are using FlySystem adaptor. I thought it was issue with it, but when I use it stand alone without involving ElFinder, then we got list of all the files in 2-3 seconds from every locations.

The MIME-Type determination can be a way to start digging into it.

What tests can we make in order to exclude issue from ElFinder?

**Comment by MickaelTH** [comment]
I did another test, just running the command from the adaptor without involving ElFinder:

$contents = $filesystem->listContents();
(based on https://flysystem.thephpleague.com/api/)

And I got the data in 2-3s. So I'm thinking something the ElFinder request to the adaptor that makes it READ files instead of LIST files?

**Comment by nao-pon** [comment]
@MickaelTH It seems that elfinder-flysystem-driver is doing. Please ask with elfinder-flysystem-driver repository.

- https://github.com/barryvdh/elfinder-flysystem-driver/blob/master/src/Driver.php#L303-L323

**Comment by MickaelTH** [comment]
Hi @nao-pon Very nice discovery, and thanks for the time you spent finding this, I will check with the elfinder-flysystem-driver from now.

**Comment by MickaelTH** [comment]
Just in case anyone is looking for the same issue, here workaround I've found, thanks to @nao-pon 👍 

https://github.com/barryvdh/elfinder-flysystem-driver/issues/66
