### ISSUE TITLE
problem with relative path without folder name in roots for localfilesystem connector

### ISSUE THREAD

**Issue by kruvas** [Studio-42/elFinder#2329]
hello, i stuck with problem - i need to set path relative to connector folder on above level without setting exact folder name. i.e. 
../../
but this trick not work - i can see root dir on initial refresh. but when i try to work with files and folder - elfinder say that it "file not found" "folder not found"
only work like this
../../../folderName/

i think its because connector elfinder treat last parent folder ident (..) as folder name and remove last slash and when compare child folder/file path against root folder path - comparison failed

how to solve this problem without setting exact folder name of root?

ps I teston on latest versions 2.1.28 +

**Comment by nao-pon** [comment]
@kruvas Can you use PHP constant [`__DIR__`](http://php.net/manual/language.constants.predefined.php) in your case?

**Comment by kruvas** [comment]
i think no (or dont want). i need portable version with constant settings that i can copy to folder to work with his files.
obviously i can calc absolute path of needed relative path, but this problem with elfinder didn't disappear with that solution )
also for root folder in function _normpath in /php/elFinderVolumeLocalFileSystem.class.php exist workaround. so maybe similar need for relative path without foldername

**Comment by nao-pon** [comment]
@kruvas elFinder converts the path based on the given path and "cwd ()" to an absolute path. A bug was found in the conversion process so I will fix this.

Thanks! 👍
