### ISSUE TITLE
Strange Server error 500 on Nginx

### ISSUE THREAD

**Issue by Offerel** [Studio-42/elFinder#2330]
I would like to build the root path dynamically, based on session variable. If i enter the path in connector.minimal.php manually, this works without any problem. However to get parts of the path, i must use the following php statement:

```
define('INSTALL_PATH', realpath(__DIR__ . '/../') . '/');
require_once INSTALL_PATH . 'dev/includes/iniset.php';
$env= userdev::get_instance();
$user = $env->users->get_var().'/files';
$path = '/mount/harddrive/userfiles/'.$user;
```
This code is no problem. The content in variable $path has now the correct path-string.

However, at the last line in connector.minimal.php `$connector->run();` i get a http server error 500 with nginx. First, i don't know why i get such a error and secondly, the real strange thing is, that i get this error only in access.log of nginx and not in error.log. PHP is called via Unix Socket as PHP-Fpm.

I don't have any glue, whats going on here. I have no trace of this error at other places in my system.

**Comment by nao-pon** [comment]
@Offerel First of all, check the contents of the server error and make sure that elFinder is causing the error.

**Comment by Offerel** [comment]
It seems, i have found the problem. Since this was part of a plugin development for roundcube, it seems that a function, a variable or some other thing collides with a name defined in elfinder. I have now renamed my roundcube plugin and rewritten the auth mechanism. This solves the problem. You can find the Roundcube elFinder Plugin at https://github.com/Offerel/roundcube_elfinder
