### ISSUE TITLE
How to configure the buttons on overwrite dialog

### ISSUE THREAD

**Issue by ForgotToPickAName** [Studio-42/elFinder#2331]
Hi,

when uploading files with elFinder to a folder where a file with the same name already exists, a dialog is opened and offering the following buttons/actions:

Yes - Overwrites the existing file.
No - Cancels the upload of the current file and continues with the next file (if multiple files are uploaded).
Rename - Adds a number to the file name.
Backup - Adds ~ to the file name.
Cancel - Cancels all outstanding uploads.

In our case we don't need both of rename and backup. One of them would be enough (anyway, who needs two different renaming functions?).
Cancel is another button we don't need, because the X (close) at the top right of the dialog is doing the same thing (or clicking no for all files). 

We looked at the code and it seems that there is no possibility to configure what buttons should be shown (it's hardcoded and the buttons have no individual IDs).

So, how can we configure the visibility of the buttons (other than make them invisible with CSS by their order which will possibly cause issues when elFinder is updated with a different button order)?

Alternatively, why are there buttons with duplicate functionalities?

Any help is very much appreciated.

**Comment by nao-pon** [comment]
@ForgotToPickAName Give the CSS class name so that it can be controlled by CSS.

For example
```css
.elfinder-confirm-upload .elfinder-confirm-btn-backup {
	display: none;
}
```
**OR**
```css
.elfinder-confirm-upload .elfinder-confirm-btn-rename {
	display: none;
}
```
Certainly [Cancel] and [X] buttons have duplicate functions, but that is a elFinder's specification. The [Cancel] and [No] buttons have functions that are slightly different so both are present.

**Comment by flack** [comment]
@nao-pon is there any special configuration option you have to set to get the additional CSS classes? I just tried this in two different elFinder integrations, and the buttons in the dialog only have CSS classes like this: `ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only elfinder-btncnt-3 elfinder-tabstop`. I can see the classes in your demo site, but I don't see them in my own setups (e.g. here: http://demo.openpsa2.org/documents/). Tested with jquery UI 1.11.4 and 1.12.1

**Comment by flack** [comment]
P.S.: I've also tried with the bundled `elfinder.html` (no modifications made), and this also only gives me `elfinder-btncnt-3` and so on, not semantiv classnames like `elfinder-confirm-btn-rename`

**Comment by nao-pon** [comment]
@flack This feature is not release yet. It will on elFinder 2.1.31. Please try the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip) until 2.1.31 release.

**Comment by flack** [comment]
ah, ok, sorry, I didn't see that this was closed via a commit. Thanks @nao-pon !
