### ISSUE TITLE
CORS detection gives false positive on IE11

### ISSUE THREAD

**Issue by gcompton** [Studio-42/elFinder#2332]
There's a quirk in the way IE11 handles HTTPS URLs in anchor elements, and it causes elFinder to enable its CORS mode unnecessarily.  This is an issue for us because CORS mode forces POST, which our backend doesn't currently support.

elFinder decides on CORS mode by comparing the window.location to opts.url, by way of an HTMLAnchorElement to help parse the URL.  On an HTTPS page, when you don't have an explicit port number, window.location.host returns just the host name.  However, in IE11, HTMLAnchorElement.host returns the host name _and_ a deduced ":443" port.  The extra port info makes elFinder think it's a different host, so it turns on CORS mode.

You can see this in IE11's debug console.  Here's what the variables look like on Google's HTTPS home page.

`window.location.href`
`"https://www.google.com/?gws_rd=ssl"`
`window.location.host`
`"www.google.com"`
`window.location.hostname`
`"www.google.com"`
`window.location.port`
`""`
`mya = document.createElement("a")`
`<a></a>`
`mya.href = "https://www.google.com/?gws_rd=ssl"`
`"https://www.google.com/?gws_rd=ssl"`
`mya.host`
`"www.google.com:443"`
`mya.hostname`
`"www.google.com"`
`mya.port`
`"443"`

I think elFinder will need to look at the URL scheme to figure out what the default port number is (80 or 443), and then compare the hostname and port separately, assuming the default port if it's not set.  

Alternatively, you could add an option to skip the automatic CORS detection entirely.  Or more flexibly, add an "isCors" option that can be set to true or false, and only run the automatic detection if it's not set.

**Comment by nao-pon** [comment]
@gcompton I fixed. Thanks! 👍
