### ISSUE TITLE
Disable multi selection

### ISSUE THREAD

**Issue by matpen** [Studio-42/elFinder#2334]
I am trying to use elFinder as a file picker. For this, it would be great to disable the "multiple selection" feature. However, I cannot find a way to achieve this, and [this question](https://stackoverflow.com/questions/30988315/disable-multiple-file-select-in-elfinder) has got no answer...

**Comment by nao-pon** [comment]
@matpen With elFInder 2.1.17 or higher, the connector main option [`maxTargets`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#maxtargets-2117) is available. This is an option to suppress the load on the connector side, but it is also effective for this case.

```php
$opts = array(
    'maxTargets' => 1,
    'roots' => array( .... ),
);
```

**Comment by matpen** [comment]
Thank you, @nao-pon ! That worked. 

For others looking up the same answer, I simply added the 'maxTargets' option seen above in my `connector.minimal.php` and the client now refuses to select multiple items: if attempting to select with `ctrl` pressed, a message pops up saying "Max number of selectable targets is 1".
