### ISSUE TITLE
Browser extension conflicting with ElFinder

### ISSUE THREAD

**Issue by kagagnon** [Studio-42/elFinder#2337]
*This issue has been documented in another thread  on the Backpack for Laravel repository: https://github.com/Laravel-Backpack/CRUD/issues/389*

When opening the ElFinder, I receive the following error in the console: `elfinder debug: [error] [elfinder] Unable to open "#".<br>Folder not found.` Upon inspection, I've found the problem.

On the line 3895 of [elFinder.js](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.js#L3895), there is an event bound on the window called `message` which call an additional request. When calling a new request, it aborts current requests of type open.

Now, some extensions installed on Chrome, Grammarly in my case, can cause problems. That extension was triggering the event `message` on page load, aborting the initial request of elFinder. When it was doing the `.sync`, the `target` param sent in `get` was empty, causing the error.

Now, the fix was easy, disabling the extension solved everything, but it is not practical. Would using a less generic name or a prefix instead of a namespace for the event be possible? It would solve that problem at least.

**Comment by nao-pon** [comment]
@kagagnon This is a elFinder's bug. so I'll fix it.

Thanks! 👍

**Comment by nao-pon** [comment]
@kagagnon Probably, it was fixed on 08f801abb95872600536a3d4d89fcde3ea82e749. Please check with [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by kagagnon** [comment]
It indeed is fixed, great work!
