### ISSUE TITLE
Adding elfinder Summernote Integration to awesome-summernote plugins repo.

### ISSUE THREAD

**Issue by DiemenDesign** [Studio-42/elFinder#2338]
Hi @nao-pon I noticed you added https://github.com/Studio-42/elFinder/wiki/Integration-with-Multiple-Summernote-%28fixed-functions%29

Do you mind if I add a link to this page on the awesome-summernote page?
https://github.com/summernote/awesome-summernote

**Comment by nao-pon** [comment]
@DiemenDesign Sure of course! Also edit the wiki at any time as it is editable. :-) :+1:
