### ISSUE TITLE
Some Issues In eLfinder!

### ISSUE THREAD

**Issue by vdanelia** [Studio-42/elFinder#2339]
**Hello I have 2 Questions...**

1. elfinder not sorting files as needed 
![elf](https://user-images.githubusercontent.com/8805696/34245916-bbc52abc-e645-11e7-96a6-efa3dfb3479b.jpg)
I need to be displayed by order (Book-1, Book-2 etc) Where I must change that option?

2. Sometimes in error log i see this error: "PHP Warning:  array_keys() expects parameter 1 to be array, null given in /myhome/myrootdir/public_html/_javascript/elfinder/connectors/php/elFinder.class.php on line 321"

The line 321 From elfinder.class.php

`$this->_result['params']['extract'] = array_keys($this->_options['archivers']['extract']);`

Please Help to fix these issues

P.S. My elfinder is old version Version: 1.1 RC3

Thank You In Advanced

**Comment by nao-pon** [comment]
@vdanelia elFinnder 2.0 and below are not maintained. Also, please use the latest version because it is vulnerable to security.

**Comment by vdanelia** [comment]
Привет Димитрий Hello Dmitry, I knew that you would say that, to update :) 
I tried also but it is very difficult, because these builds differ from each other, once you helped me many years ago :) 

The old version works perfectly does it's best, but these 2 issues only... If you could help would be great...

**Comment by nao-pon** [comment]
Sorry, the old version can not be supported here and will not be fixed.
