### ISSUE TITLE
elfinder: Unable to open '#' Folder not found.

### ISSUE THREAD

**Issue by sharifzadesina** [Studio-42/elFinder#2342]
Hi
We sometimes face this problem in chrome browser, it seems this is cause of conflict between event/methods of elfinder with chrome extensions. for fixing this you can add a namespace to your global events.
for more info: https://github.com/Laravel-Backpack/CRUD/issues/389

**Comment by nao-pon** [comment]
@sharifzadesina This problem was fixed with #2337. Thanks!

**Comment by sharifzadesina** [comment]
@nao-pon in which version we can test it?

**Comment by nao-pon** [comment]
Please try the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

- https://github.com/Studio-42/elFinder#downloads

**Comment by nao-pon** [comment]
@sharifzadesina Just today, elFinder 2.1.31 was released. Please use it.

**Comment by sharifzadesina** [comment]
@nao-pon Thank you.
