### ISSUE TITLE
dialog not close

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2343]
try to close this dialog
![image](https://user-images.githubusercontent.com/18566890/34360998-47058f28-ea8c-11e7-8928-d5dd2f6916c3.png)

**Comment by CodeLyokoXtEAM** [comment]
also there is another bug.

![image](https://user-images.githubusercontent.com/18566890/34361112-52514312-ea8d-11e7-90a2-18d3a9fba5b5.png)

close that error massage.
you can see background files can select now (background disable layer has gone)

![image](https://user-images.githubusercontent.com/18566890/34361126-729c441e-ea8d-11e7-9318-46f4f12d3c4f.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM I can not reproduce the second problem (about netmount dialog). Do you have detailed procedures that can be reproduced?

**Comment by CodeLyokoXtEAM** [comment]
second bug is not present now.
I'll check if its present special procedure.

**Comment by nao-pon** [comment]
OK, Please create a new issue if the second bug is reproduced.
