### ISSUE TITLE
can we used third party component like nsoftware with this control for cloud storage?

### ISSUE THREAD

**Issue by ckvnahsik** [Studio-42/elFinder#2344]
Hello,

can we used third party component like nsoftware with this control for cloud storage?

**Comment by nao-pon** [comment]
@ckvnahsik It is unknown what kind of things you want, but it is possible from the server side if you get a response along with [Client - Server API 2.1](https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1).
