### ISSUE TITLE
Disable client-side caching of file URLs

### ISSUE THREAD

**Issue by kkotowick** [Studio-42/elFinder#2347]
I'm using the Dropbox2 driver, and have done some funky stuff with file content URLs. Due to this, I would like to disable the URL caching that seems to be happening (i.e. if you try to open the same file twice in a row, it doesn't run the PHP connector the second time, just re-opens the URL that the connector returned the first time). 

This is certainly happening on the JS/client side of things, but I can't seem to find a way to disable it. Is there a setting for this? If not, any suggestions on how to prevent it?

**Comment by nao-pon** [comment]
@kkotowick In my testing environment, for example on the [demo site](https://studio-42.github.io/elFinder/), it is opened by connector.php every time. Can you explain in more detail?
