### ISSUE TITLE
[VD:Dropbox2] Edit File not respecting filename capitalization

### ISSUE THREAD

**Issue by kkotowick** [Studio-42/elFinder#2348]
Having some issues with filename capitalization, where it renames the file to all-lower-caps letters when using the "Edit File" context menu item.

Steps to reproduce:
1) use Dropbox2 drive
2) upload file named "HelloWorld.txt"
3) right-click file, select "Edit file"
4) make a change, click "Save & Close"
5) notice that once it refreshes the directory, the file is now named "helloworld.txt"

This same issue happens when using the "New text file" context menu item. I think it has something to do with the target hash/unhash system not respecting capitalization.

**Comment by nao-pon** [comment]
@kkotowick This is a bug of the Dropbox2 volume driver, so I'll fix it.

Thanks! 👍
