### ISSUE TITLE
Specifying base directory for sound files

### ISSUE THREAD

**Issue by KyleKotowick** [Studio-42/elFinder#2349]
I have the following file structure (I have to do this with the legacy style, without Require JS, because I'm using a Wordpress install and getting Require JS to work with that is a pain):

Client: `/base/pages/my_elFinderClient.php`
Connector: `/base/backend/my_elFinderConnector.php`
elFinder library: `/base/libraries/elFinder`

So in my "my_elFinderClient.php" file, it looks something like this:

```
<script type='text/javascript' src='base/libraries/elFinder/js/elfinder.min.js?ver=4.9.1'></script>
<script>
	jQuery().ready(function() {
		var elf = jQuery('#elfinder').elfinder({
			requesttype: 'post',
			url : '/base/backend/my_elFinderConnector.php'
		}).elfinder('instance');
	});
</script>
```

This works perfectly, except for one thing. It appears that the URLs for all of the sound effects are programmed as relative to the client page (e.g. "/base/pages/sounds/rm.wav"), which doesn't work if the elFinder library is installed somewhere else (in my case, it should be "/base/libraries/elFinder/sounds/rm.wav"). Is there any way to make it so the sound files paths work in this scenario?

**Comment by kkotowick** [comment]
After looking at the source code, I see that in the client configuration you can specify a "soundpath" option, which fixed the issue when I set it as the actual path of the sound files. This configuration option is not listed in the Wiki for the [Client Configuration Options](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options) though, so you may want to add that.

**Comment by nao-pon** [comment]
@kkotowick Thank you for your advising. Of course yes, Please edit the Wiki page.
