### ISSUE TITLE
How to config/extend CKEditor?

### ISSUE THREAD

**Issue by Offerel** [Studio-42/elFinder#2350]
For editing HTML files, i prefer CKEditor over TinyMCE (Mostly since inserting pictures, results in inserting them as base64 instead of a reference link). However, i miss the ability to edit Document Properties, like Metatags for Keywords and so on. I have seen, that there is a "Document Properties" plugin for CKEditor, which should do the job. But i didn't know, how i can add this plugin in to CKEditor of elFinder. 

Or can i use a local copy of CKEditor, instead of the one from cloudflare?

Additionally, it would like to have a way, to disable other editor for HTML, so that i have only CKEditor for HTML files and not the other editors also, or if i cant them disable, maybe i can set one of this editor as default editor, so that i can load the html file with a double-click in to this editor, instead of downloading it?

**Comment by nao-pon** [comment]
@Offerel There is a [related issue](https://github.com/Studio-42/elFinder/issues/2319#issuecomment-355670899).
