### ISSUE TITLE
Invalid backend response. Error occurred on the server side. HTTP error 500

### ISSUE THREAD

**Issue by Afolabidivia** [Studio-42/elFinder#2351]
I implemented elfinder on a local server which it works perfectly but I have been trying to implement it on a live server but it kept prompting an error "Invalid backend response.
Error occurred on the server side.
HTTP error 500". I don't seems to get what really caused it.
I would so much appreciate your solution. Thanks.

**Comment by nao-pon** [comment]
@Afolabidivia Please check with a connector option [`debug`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#debug) (`'debug' => true`).

**Comment by siyakant** [comment]
I have also same problem how to solve it:-

**Comment by siyakant** [comment]
I have also same problem how to solve its.....

**Comment by tukusejssirs** [comment]
> @Afolabidivia Please check with a connector option [`debug`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#debug) (`'debug' => true`).

@nao-pon, I have encountered similar issue (although the code is `504`) and I have set `debug` to `true`, but where could I see the logs? There are no logs in the web browser console.

**Comment by mguinness** [comment]
IIRC the error messages are shown in debug tab of `help` dialog.

**Comment by tukusejssirs** [comment]
> IIRC the error messages are shown in debug tab of `help` dialog.

Well, if you mean the `help` dialog of elFinder, I can’t see it there.

<img src="https://user-images.githubusercontent.com/5111894/114772885-dbcb8680-9d5d-11eb-910c-308b99bfc7cf.png" width="48%" height="48%">

**Comment by mguinness** [comment]
See https://github.com/Studio-42/elFinder/issues/1597#issuecomment-240311094
