### ISSUE TITLE
Disable all editors and also Textarea

### ISSUE THREAD

**Issue by Offerel** [Studio-42/elFinder#2354]
I have configured elFinder now to use a local instance of ckeditor for editing html files. All other editors for html files are disabled:
```
cdns : {
						// for editor etc.
						ace        : null, // or your location
						codemirror : null, // or your location
						ckeditor   : 'js/ckeditor',
						tinymce    : null, // or your location
						simplemde  : null, // or your location
						// for quicklook etc.
						hls        : null, // or your location
						dash       : null, // or your location
						prettify   : null, // or your location
						psd        : null, // or your location
						rar        : null, // or your location
						zlibUnzip  : null, // or your location
						zlibGunzip : null  // or your location
					}
```
But when i rightclick on a html file, the editor "Textarea" apears also as editor. How can i disable TextArea for html files, but allow it for pure textfiles?

**Comment by nao-pon** [comment]
@Offerel Please load the configuration that does not include the text area editor instead of "js/extras/editors.default.js", or remove the text area editor from the default editor.

```javascript
opts : {
    bootCallback : function(fm, extraObj) {
        elFinder.prototype._options.commandsOptions.edit.editors.pop();
    },
    url : 'php/connector.php'
}
```

**Comment by Offerel** [comment]
Ahh thx for the tip. I have changed editors.default.js to this:

```
{
			// Simple Text (basic textarea editor)
			info : {
				name : 'TextArea',
				useTextAreaEvent : true
			},
			mimes : [
				'text/txt',
				'text/csv'
			],
			load : function(){},
			save : function(){}
		}
```
for the Textarea editor. Now i have only the editor i want. 

BTW: There is a small translation error for TextArea Editor or maybe the translation variable is not available. When you select a html file and look in the Main Toolbar, the word for TextArea is untranslated, where in the RightClick menu it is translated (in my case German).

**Comment by nao-pon** [comment]
> BTW: There is a small translation error for TextArea Editor or maybe the translation variable is not available. When you select a html file and look in the Main Toolbar, the word for TextArea is untranslated, where in the RightClick menu it is translated (in my case German).

Yes, you are right! I'll fix it.
