### ISSUE TITLE
Mime.types file not includes all mime type standarts

### ISSUE THREAD

**Issue by Qh0stM4N** [Studio-42/elFinder#2358]
I use the mime.types file as a reference, so the value I'm using does not actually meet the uploaded file.

does not it have to be a more general list? Can a file extension correspond to more than one mime type? For example, the following rar file corresponds to more than one mime type value in the same project.

This mime types not uniquie a file ext.

php/elFinderVolumeDriver.class.php file has included 
```php
protected static $mimetypes = array(
//...
//...
'rar'   => 'application/x-rar',
//...
//...
)
```
But The same file extension in the rar file is entered in mime.types file

```
...
application/x-rar-compressed rar
...
```

mime.types files referenced with https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types

this file not included "audio/mp3" but browser direct supported with playing "audio/mp3" mime types ref: https://cs.chromium.org/chromium/src/net/base/mime_util.cc?q=%22audio/mp3%22&sq=package:chromium&dr=C&l=86

**Comment by nao-pon** [comment]
@Qh0stM4N About mime-type of mp3 It is registered as "audio/mpeg" in the mime.types file. This "audio/mpeg" can be played in the browser.

If you want "audio/mp3" under your circumstance, you can control MIME - Type with [`additionalMimeMap`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#additionalmimemap) of the connector route option. For example ...

```php
'additionalMimeMap' => array(
    'mp3:audio/mpeg' => 'audio/mp3'
)
```

**Comment by Qh0stM4N** [comment]
These standards are fully valid for the apache server, as apache has stated. Other software standards may be different. I assume that it is our priority in a php based application. It's a good practice to be able to specify different types outside the line.

@nao-pon If we do not have the ability to add more than one record pointing to the same file extension in the mime.types file, this issue open status is unnecessary.
