### ISSUE TITLE
how to allow more mime types to upload

### ISSUE THREAD

**Issue by awsmthx** [Studio-42/elFinder#2360]
issue: i can't figure out ;)
how would i allow more mimetypes to upload? i tried like this:
```
defaultOpts : {
                url : 'php/connector.minimal.php' // connector URL (REQUIRED)
				,lang: 'en'
				,uploadAllow : [
				   'application/pdf',
				   'application/vnd.koan'
				]
....
```
thanks!

**Comment by nao-pon** [comment]
@awsmthx [`uploadAllow`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadallow) is a connector roots option it's not a client option.
