### ISSUE TITLE
Trash on mysql volume

### ISSUE THREAD

**Issue by cuongnguyenvn** [Studio-42/elFinder#2361]
Hi guys,
Im trying to use custom MySQL volume driver. I created one root folder for item (MySQL based) and one for Trash (MySQL based, same table for elfiles).
I adjusted delete item to move into trash folder always but I can't restore the folder in Trash. I got error message in restore action:
 "Unable to restore from the trash. Can't identify the restore destination.
Folder not found."
The error seems to be shown before sending request to the connector.
Could you advise me what is wrong?

Thanks,
Cuong

**Comment by nao-pon** [comment]
@cuongnguyenvn Please change the elFinderVolumeTrash class and create a new class elFinderVolumeTrashMySQL extended the elFinderVolumeMySQL class and use it.

- **elFinderVolumeTrashMySQL**
```php
<?php
/**
 * elFinder driver for trash bin at local filesystem.
 *
 * @author NaokiSawada
 **/
class elFinderVolumeTrashMySQL extends elFinderVolumeMySQL
{
    /**
     * Driver id
     * Must be started from letter and contains [a-z0-9]
     * Used as part of volume id.
     *
     * @var string
     **/
    protected $driverId = 'tm';

    public function __construct()
    {
        parent::__construct();
        // original option of the Trash
        $this->options['lockEverything'] = false; // Lock all items in the trash to disable delete, move, rename.

        // common options as the volume driver
        $this->options['alias'] = 'Trash';
        $this->options['quarantine'] = '';
        $this->options['rootCssClass'] = 'elfinder-navbar-root-trash';
        $this->options['copyOverwrite'] = false;
        $this->options['uiCmdMap'] = array('paste' => 'hidden', 'mkdir' => 'hidden', 'copy' => 'restore');
        $this->options['disabled'] = array('archive', 'duplicate', 'edit', 'extract', 'mkfile', 'places', 'put', 'rename', 'resize', 'upload');
    }

    public function mount(array $opts)
    {
        if ($this->options['lockEverything']) {
            if (!is_array($opts['attributes'])) {
                $opts['attributes'] = array();
            }
            $attr = array(
                'pattern' => '/./',
                'locked' => true,
            );
            array_unshift($opts['attributes'], $attr);
        }
        // force set `copyJoin` to true
        $opts['copyJoin'] = true;

        return parent::mount($opts);
    }
}
```

**Comment by nao-pon** [comment]
I added [elFinderVolumeTrashMySQL.class.php](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeTrashMySQL.class.php) to repository.

**Comment by cuongnguyenvn** [comment]
@nao-pon I want to implement Trash and restore function for root items and Trash, both use MySQL. Any advice?

**Comment by cuongnguyenvn** [comment]
I tried with MySQL trash, but in restore action the folder/file is copied to the "live" folder but it did not get removed from Trash as it must

**Comment by nao-pon** [comment]
I tested next settings, that is no problems.

```php
array(
    'driver' => 'MySQL',
    'trashHash' => 'tm1_MQ',
    'path' => 1,
    'host' => '192.168.1.xxx',
    'user' => 'xxxx',
    'pass' => 'xxxx',
    'db' => 'elfinder',
    'files_table' => 'elfinder_file',
    'tmpPath'       => 'PATH TO/.tmp',
    'uploadMaxSize' => '10M',
),
array(
    'id' => '1',
    'driver' => 'TrashMySQL',
    'path' => 1,
    'host' => '192.168.1.xxx',
    'user' => 'xxxx',
    'pass' => 'xxxx',
    'db' => 'elfinder',
    'files_table' => 'elfinder_trash',
    'tmpPath'       => 'PATH TO/.tmp',
    'uploadMaxSize' => '10M',
),
```

**Comment by cuongnguyenvn** [comment]
I see in your options, root folder and trash have same value "path", is it require to get the Trash MySQL work?

**Comment by nao-pon** [comment]
The values of path need not be the same. However, with the MySQL volume driver, there was a problem that it was not possible to set the folder with the parent as the root, so I modified it with commit (ef6e182cc98b57b763804ae7b1528e64ba978fba).
