### ISSUE TITLE
VestaCP - breaks files into chunks while uploading and gives "unable to upload <name>.N_<maxN>.part transfer error

### ISSUE THREAD

**Issue by sunblur** [Studio-42/elFinder#2362]
Version: 2.1.11, protocol version: 2.1
jQuery/jQuery UI: 1.12.0/1.11.4

There's a screenshot: https://i.imgur.com/Vn7Tb37.jpg
php.ini is here: https://pastebin.com/hsFntWnd  (post/upload max size are 10gig, temp upload folder is accessible).
apache config: https://pastebin.com/c9r8EApM 
nginx config: https://pastebin.com/pxE7213C

Whenever I try to upload a file larger than around 10megabytes elfinder gives that error. With smaller files there's none (it seems like its fine when it doesnt break files to pieces).
Considering *.part name of the files in error the problem is when large file is being broken to pieces. 
I have this problem on all servers where I use VestaCP and no problem on other servers. VestaCP is using apache 2 with nginx as proxy. I attached nginx and apache configs at the top.

connector setting: https://pastebin.com/E9zQppWp (again it works perfect on servers not on VestaCP so I think it should be a server config problem)
connector minimal: https://pastebin.com/31dptGSf

Any suggestions what could be causing it? 
Thanks.

**Comment by nao-pon** [comment]
@sunblur I think that there is probably a cause in the server configuration, but just in case please check it with elFinder latest version. Also ask VestaCP about the cause of the server side.
