### ISSUE TITLE
SaveAs button for resize image window doesn't work

### ISSUE THREAD

**Issue by mkhomytsya** [Studio-42/elFinder#2366]
I download and unzip default elfinder installation on my server,
rename connector.minimal.php.dist to connector.minimal.php

Resize and  save works fine, but resize and save as create 0 size image and error that it is not possible to resize.

But here https://studio-42.github.io/elFinder/ I can not reproduce this issue, shall I add edit some extra settings to allow this functionality ?

**Comment by nao-pon** [comment]
@mkhomytsya Please check "[Requirements - Server](https://github.com/Studio-42/elFinder#server)"

- PHP 5.2+ (Recommend PHP 5.4 or higher) And for **_thumbnails - GD / Imagick module / convert(imagemagick) require_**

**Comment by mkhomytsya** [comment]
yes I checked it out
everything is ok
the issue that if I use normal save button everything works fine and resizing ok
only if I use saveas button that makes issue

**Comment by nao-pon** [comment]
Oh, sorry. I missed read clearly this title. Are you trying in elFinder 2.1.31? What about [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip)?

**Comment by mkhomytsya** [comment]
the same issue :(

I see the following requests to server

1 . php/connector.minimal.php?cmd=mkfile&name=bug.png&target=l1_YQ&reqid=16108eebc362f4
response
{"added":[{"isowner":false,"ts":1516273319,"mime":"image\/png","read":1,"write":1,"size":"0","hash":"l1_YS9idWcucG5n","name":"bug.png","phash":"l1_YQ","tmb":1}],"changed":[{"isowner":false,"ts":1516273319,"mime":"directory","read":1,"write":1,"size":0,"hash":"l1_YQ","name":"a","phash":"l1_Lw","volumeid":"l1_"}]}

2 . php/connector.minimal.php
form data
cmd=put&target=l1_YS9idWcucG5n&encoding=scheme&content=http%3A%2F%2F127.0.0.1%3A4570%2Ftmp%2FelFinder-2.1%2Ffiles%2Fa%2FicoTest_passed_selected.png&reqid=16108eebc9b2a7

response

{"changed":[{"isowner":false,"ts":1516273319,"mime":"image\/png","read":1,"write":1,"size":"21","hash":"l1_YS9idWcucG5n","name":"bug.png","phash":"l1_YQ","tmb":1}]}

3. php/connector.minimal.php?cmd=tmb&targets%5B%5D=l1_YS9idWcucG5n&reqid=16108eebcafc2
response
{"images":{"l1_YS9idWcucG5n":"l1_YS9idWcucG5n1516273319.png"}}

4. php/connector.minimal.php?target=l1_YS9idWcucG5n&width=33&height=33&quality=0&bg=&mode=resize&cmd=resize&reqid=16108eebd5818d
response
{"error":["errResize","files\/a\/bug.png"]}

as result I see alert with "{"error":["errResize","files\/a\/bug.png"]}"

**Comment by nao-pon** [comment]
Is the value of "URL" in connector roots config correct? "http://127.0.0.1:4570/tmp/elFinder-2.1/files/a/icoTest_passed_selected.png" is the URL of the original file, can the server PHP access the location?

**Comment by mkhomytsya** [comment]
yes it is correct

**Comment by nao-pon** [comment]
Please try set a connector main option [`commonTempPath`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#commontemppath--217) to readable/writable directory for PHP.

```php
$opts = array(
    // 'debug' => true,
    'commonTempPath' => 'Readable/Writable directory',
    'roots' => array(
        // Items volume
        array(
            'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
            'path'          => '../files/',                 // path to files (REQUIRED)
            'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
            'trashHash'     => 't1_Lw',                     // elFinder's hash of trash folder
            'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
            'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
            'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
            'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
            'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
        ),
        // Trash volume
        array(
            'id'            => '1',
            'driver'        => 'Trash',
            'path'          => '../files/.trash/',
            'tmbURL'        => dirname($_SERVER['PHP_SELF']) . '/../files/.trash/.tmb/',
            'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
            'uploadDeny'    => array('all'),                // Recomend the same settings as the original volume that uses the trash
            'uploadAllow'   => array('image', 'text/plain'),// Same as above
            'uploadOrder'   => array('deny', 'allow'),      // Same as above
            'accessControl' => 'access',                    // Same as above
        )
    )
);
```

**Comment by nao-pon** [comment]
@mkhomytsya In the latest nightly build, I modified to acquire contents for copying inside the connector instead of over HTTP. Please try the latest nightly build. (Do not forget to update the cache of the browser)

**Comment by mkhomytsya** [comment]
now it works!
There is only issue with thumb, it doesn't update properly.

Great job! Thanks for help!
