### ISSUE TITLE
Folder Permissions Error

### ISSUE THREAD

**Issue by ntrimg** [Studio-42/elFinder#2367]
I just took a project over that is using elfinder and I'm getting an error with one particular folder out of dozens, where when a file located within is clicked, it gives me an error of : ...Root folder has not read and write permissions.

I've just noticed that it seems to pertain to .rtf files only. 

Since I'm not familiar with elfinder, is this an issue with these types of files?  Or is there something that can be done to allow the viewing/download of the .rtf files?

**Comment by nao-pon** [comment]
@ntrimg By default, pdf can not be uploaded, but there is no display / download restriction. So I think that this behavior is restricted in your server environment.
