### ISSUE TITLE
Error: "Unable to make temporary file for upload."

### ISSUE THREAD

**Issue by kkotowick** [Studio-42/elFinder#2368]
I have my "uploadMaxSize" variable set to 100+ MB (all php.ini settings are higher than this). However, whenever I try to upload a file larger than about 10MB, I get the following error:

```
Unable to upload (filename).
Unable to make temporary file for upload.
```

After some debugging, it seems that this error is being generated on [Line 2615 of elFinder/php/elFinder.class.php](https://github.com/Studio-42/elFinder/blob/ef6e182cc98b57b763804ae7b1528e64ba978fba/php/elFinder.class.php#L2615). Here are some of the variable values at that point when it threw the error:

```
$len: 10485760
$csize: 13981072
$start: 0
$size: 81072298,
$tmpExists: false
filesize($tmp): 81072298
```

It appears to fail because `$len != $csize`. Any idea what's going on here?

**Comment by nao-pon** [comment]
@kkotowick $len is the size of blob data sliced with JavaScript and $csize is the size of uploaded blob data. Normally $csize will not be bigger. There is a possibility that data has been changed somewhere. Please explore it.

**Comment by kkotowick** [comment]
I'm using the "upload.pre" callback function to encrypt the file before it is sent to Dropbox. Since it's using base64 encoding after the encryption, the size of the file sent to Dropbox is notably larger than the size of the file that the user was trying to upload. Is there no way to override this check for this kind of use case? I thought that's what the point of the "upload.pre" callback was for.

**Comment by nao-pon** [comment]
@kkotowick For such this case please use "upload.presave" hook point.

- https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind
