### ISSUE TITLE
Uploading duplicate folder does not replace.

### ISSUE THREAD

**Issue by todhing** [Studio-42/elFinder#2369]
When I upload a folder with the same name of a folder that already exist, I am prompted to replace the folder.  When I select replace, it merges the contents instead of replacing.

**Comment by nao-pon** [comment]
@todhing The folders are merged. Only files are overwritten. To replace the folder, select "Backup". In relation I fixed the dialog message.

![fireshot capture 12 - test here_test_elfinder 2 1_ - https___hypweb net_elfinder-nightl](https://user-images.githubusercontent.com/1412630/35211083-48efc8f0-ff98-11e7-8a27-6eb59ec9b01b.png)

**Comment by todhing** [comment]
@nao-pon Thank you so much for the reply and update.  The Backup option is not so intuitive.  Would it be possible to add dialog that selecting Backup will backup the folder and then replace?

**Comment by todhing** [comment]
@nao-pon Perhaps I can suggest the following text...(If it contains folders, it will be merged. To backup and overwrite, select Backup.)

**Comment by nao-pon** [comment]
@todhing Thanks! 👍
