### ISSUE TITLE
Can I hide columns in list view?

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2370]
if user want to hide columns in list view, I think its better elfinder have option that user can control it.
![untitled](https://user-images.githubusercontent.com/18566890/35259275-f2f0f27e-002a-11e8-8bd8-24503436e4c8.png)

when select 'more'
![untitled](https://user-images.githubusercontent.com/18566890/35259339-46ab616a-002b-11e8-93d3-7d28dbda2123.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM I'm trying implement this feature now.

Thanks! 👍
