### ISSUE TITLE
watermarks not working

### ISSUE THREAD

**Issue by hayes-seyah09354085977** [Studio-42/elFinder#2372]
i use the watermarks plugins but nothing happen no watermarks on a file or image i upload

**Comment by nao-pon** [comment]
@hayes-seyah09354085977 Would you show your connector configuration?

**Comment by hayes-seyah09354085977** [comment]
$opts = array(
			'bind' => array(
				'upload.presave' => array(
					'Plugin.Watermark.onUpLoadPreSave'
				)
			),
			// global configure (optional)
			'plugin' => array(
				'Watermark' => array(
					'enable'         => true,       // For control by volume driver
					'source'         => 'logo.png', // Path to Water mark image
					'marginRight'    => 5,          // Margin right pixel
					'marginBottom'   => 5,          // Margin bottom pixel
					'quality'        => 95,         // JPEG image save quality
					'transparency'   => 70,         // Water mark image transparency ( other than PNG )
					'targetType'     => IMG_GIF|IMG_JPG|IMG_PNG|IMG_WBMP, // Target image formats ( bit-field )
					'targetMinPixel' => 200,        // Target image minimum pixel size
					'interlace'      => IMG_GIF|IMG_JPG, // Set interlacebit image formats ( bit-field )
					'offDropWith'    => null        // To disable it if it is dropped with pressing the meta key
					                                // Alt: 8, Ctrl: 4, Meta: 2, Shift: 1 - sum of each value
					                                // In case of using any key, specify it as an array
				)
			),
			// each volume configure (optional)
			'roots' => array(
				array(
					'driver' => 'LocalFileSystem',
					'path'   => '../files/',
					'URL'    => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
					'plugin' => array(
						'Watermark' => array(
				 			'enable'         => true,       // For control by volume driver
							'source'         => 'logo.png', // Path to Water mark image
							'marginRight'    => 5,          // Margin right pixel
							'marginBottom'   => 5,          // Margin bottom pixel
							'quality'        => 95,         // JPEG image save quality
							'transparency'   => 70,         // Water mark image transparency ( other than PNG )
							'targetType'     => IMG_GIF|IMG_JPG|IMG_PNG|IMG_WBMP, // Target image formats ( bit-field )
							'targetMinPixel' => 200,        // Target image minimum pixel size
							'interlace'      => IMG_GIF|IMG_JPG, // Set interlacebit image formats ( bit-field )
							'offDropWith'    => null        // To disable it if it is dropped with pressing the meta key
							                                // Alt: 8, Ctrl: 4, Meta: 2, Shift: 1 - sum of each value
							                                // In case of using any key, specify it as an array
						)
					)
				)
			),
		
		);

**Comment by nao-pon** [comment]
There seems to be no problem in setting. I made error messages displayed in debug tab of information dialog by enabling debug mode. Please observe if any errors are displayed on the latest version of the nightly build.

```php
$opts = array(
			'debug' => true, // to enable debug mode
			'bind' => array(
				'upload.presave' => array(
					'Plugin.Watermark.onUpLoadPreSave'
				)
			),
.....
```

![180203-001738](https://user-images.githubusercontent.com/1412630/35741000-eaa1ed38-0879-11e8-84c9-65689de4e827.png)

![180203-001758](https://user-images.githubusercontent.com/1412630/35741003-eec8ea06-0879-11e8-89df-599944a344f2.png)
