### ISSUE TITLE
Not an Issue - a Query

### ISSUE THREAD

**Issue by BuffaloBrennan** [Studio-42/elFinder#2375]
Is it possible for elFinder to encrypt a file on upload to server and decrypt on download from server?

**Comment by nao-pon** [comment]
@BuffaloBrennan With the [`bind`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind) option, it is possible to change the contents of the file at the time of uploading, but I think that it is not possible to change the file and output it at the time of downloading. However, there is a way to extend the [`file()`](https://github.com/Studio-42/elFinder/blob/master/php/elFinder.class.php#L1622-L1734) function of the elFinder class and change the contents of the file when downloading.
