### ISSUE TITLE
File outside webroot

### ISSUE THREAD

**Issue by RRangioni** [Studio-42/elFinder#2376]
Howto setup the access, preview and thumbnails when files are on different mount then web-root.

Web-root:   /var/www/html/elf 
Files:           /data/elf/files

Can see the files, but cannot preview them.
Totally lost :-)

**Comment by nao-pon** [comment]
@RRangioni Please try to omit (disable) [`URL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#url) option in connector.php file. Please check the [Wiki](https://github.com/Studio-42/elFinder/wiki/Disable-real-file-path-from-being-shown).
