### ISSUE TITLE
Select Folder to upload issue

### ISSUE THREAD

**Issue by todhing** [Studio-42/elFinder#2378]
When I select a folder to upload I get inconsistent behavior.  Sometimes the upload will include the folder I selected and everything below it, which is what I expect to happen.  But other times, it will only select the files and folder below the main folder I selected (It does not include the top level folder name I selected).  I do not see this issue when I use drag and drop.  I only see the issue when I use the upload icon or select file/folder option.

**Comment by nao-pon** [comment]
@todhing I tried several patterns with Windows 10/64 bit Chrome 64 and Firefox 58, but I could not reproduce this problem.

Can you show the procedure to reproduce this problem?

**Comment by todhing** [comment]
[studyx.zip](https://github.com/Studio-42/elFinder/files/1708930/studyx.zip)

I have a file structure similar to the attached zip.  If I try to upload any of the folders 2 or more levels deep, nothing happens.  It does not upload the folder.

**Comment by nao-pon** [comment]
@todhing The cause of this problem is that the directory selector does not include directories that do not contain files in the file data obtained by the directory selector.

Since elFinder does not support such data, there is a bug that nothing happens. I will fix this, but the directory which does not contain the file will be skipped and uploaded.

**Comment by todhing** [comment]
But if the folder below it has files it still does not upload.  I would think that it would check for files in the sub-directories as well.

**Comment by nao-pon** [comment]
@todhing I fixed this issue. Please try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip). so please don't forget browser cache clearing.

**Comment by nao-pon** [comment]
Chrome has a related bug. - [Webkitdirectory input returns wrong path of selected files](https://bugs.chromium.org/p/chromium/issues/detail?id=124187)

**Comment by todhing** [comment]
@nao-pon I tested the new build and it does fix one of the issues.  However, if you test with the zip file here, you will notice that when you try to upload folder subject05 or subject06, It will start with the "hurdle" subfolder.  It should start with subject05 or subject06.  It works as expected when uploading subject16.

[subject.zip](https://github.com/Studio-42/elFinder/files/1719003/subject.zip)
