### ISSUE TITLE
arabic file name

### ISSUE THREAD

**Issue by aminbaik** [Studio-42/elFinder#2385]
Hello,
i install elfinder and point to my data directory.
but elfinder not show Arabic files if i try to change it to English its work fine. also when i upload file with Arabic name it's work too but not showing existing Arabic files.
thanks.

**Comment by aminbaik** [comment]
please note that i try to add  'locale' => 'Windows -1256', on connector file but nothing changes.
thanks.

**Comment by nao-pon** [comment]
@aminbaik Please try connector roots option [`encoding`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding).

```php
$opts = array(
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/',
            'encoding' => 'cp1256'
        )
    )
);
```
