### ISSUE TITLE
delete confirmation dialog [object Object]

### ISSUE THREAD

**Issue by bwaindwain** [Studio-42/elFinder#2388]
In my implementation in Drupal, instead of the delete confirmation dialog showing the filename you're about to delete, it just says "[object Object]". I'm stumped how to fix this. Any ideas out there?

Using elfinder 2.1.31

![image](https://user-images.githubusercontent.com/2658754/36325492-2e23713a-1315-11e8-8ca8-970e858b2219.png)

**Comment by bwaindwain** [comment]
I found that if I replace "$" with "jQuery" in elFinder.prototype.commands.rm() it works
`text = [$(tpl.replace('{class}', fm.mime2class(f.mime)).replace('{title}', '<strong>' + fname + '</strong>').replace('{desc}', descs.join('<br>')))];`

`text = [jQuery(tpl.replace('{class}', fm.mime2class(f.mime)).replace('{title}', '<strong>' + fname + '</strong>').replace('{desc}', descs.join('<br>')))];`

This may have something to do with Drupal using it's own jquery v1.4 and the elfinder module using jquery 1.12.

Now, how can I fix this without hacking elfinder...

**Comment by nao-pon** [comment]
@bwaindwain Please try use elfinder.min.js or elfinder.full.js .
