### ISSUE TITLE
fetch address of the file then transfer to another folder 

### ISSUE THREAD

**Issue by hayes-seyah09354085977** [Studio-42/elFinder#2394]
my boss asking to get the address of the file by right clicking on it how to do that?

**Comment by nao-pon** [comment]
@hayes-seyah09354085977 A URL link is set to the arrow icon to the right of the download of the context menu.

**Comment by hayes-seyah09354085977** [comment]
how to fetch the url from the link Button?

**Comment by nao-pon** [comment]
It is the same as ordinary HTML <A>.

**Comment by hayes-seyah09354085977** [comment]
i figure out ** var file = this.files(hashes);** thanks
