### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined in main.js

### ISSUE THREAD

**Issue by rwilkin** [Studio-42/elFinder#2396]
I think I am doing something wrong.
I have elfinder in it's own folder on my server and I am trying to get it to work in a php file in the directory above. 

So elfinder is in /public_html/elfinder
and I'm trying to get it to work from /public_html/index.html

Whenever I do that I get this error in the console:
**Uncaught TypeError: Cannot read property 'prototype' of undefined
    at start (main.js:34)
    at Object.execCb (require.min.js:1)
    at b.check (require.min.js:1)
    at b.<anonymous> (require.min.js:1)
    at require.min.js:1
    at require.min.js:1
    at each (require.min.js:1)
    at b.emit (require.min.js:1)
    at b.check (require.min.js:1)
    at b.enable (require.min.js:1)
start @ main.js:34
execCb @ require.min.js:1
check @ require.min.js:1
(anonymous) @ require.min.js:1
(anonymous) @ require.min.js:1
(anonymous) @ require.min.js:1
each @ require.min.js:1
emit @ require.min.js:1
check @ require.min.js:1
enable @ require.min.js:1
init @ require.min.js:1
h @ require.min.js:1
completeLoad @ require.min.js:1
onScriptLoad @ require.min.js:1**

If I use the same index.html file from the elfinder directory it works fine. 
So /public_html/elfinder/index.html works with no issues but /public_html/index.html doesn't work with the above error. Both index files are exactly the same.

Looking at the error in developer tools it shows this line:
```
start = function(elFinder, editors, config) {
			// load jQueryUI CSS
			elFinder.prototype.loadCss('//cdnjs.cloudflare.com/ajax/libs/jqueryui/'+uiver+'/themes/smoothness/jquery-ui.css');
```

Then looking at the elFinder and editors parameters they are both undefined. 

How can I get the /public_html/index.html file to work?

Sorry if this doesn't make much sense, I've been awake for about 29 hours now.

Thank you in advance for your help.

**Comment by nao-pon** [comment]
@rwilkin Please try
```javascript
baseUrl : 'js'
```
to
```javascript
baseUrl : 'elfinder/js'
```
in your main.js.

**Comment by rwilkin** [comment]
That worked perfectly. Thank you

**Comment by parvanova** [comment]
OK. I gave it a  fresh new try. 

From https://github.com/Studio-42/elFinder/wiki/Integration-with-CKEditor-(jQuery-UI-dialog-mode)
I copied the .html and main.ckedialog.js files.
The elfinder is in  dir elfinder. (just downloaded)

Result - opening the html in browser - 

 Uncaught ReferenceError: $ is not defined    at elfinder.js:5186
 Uncaught TypeError: Cannot read property 'prototype' of undefined - main.ckedialog.js:35

What am I doing wrong?
Please advice!
Thank you

**Comment by nao-pon** [comment]
@parvanova If your directory pattern is as follows...
```
./index.html
./main.ckedialog.js
./elfinder/js/elfinder.min.js
./elfinder/php/connector.minimal.php
```
You need to modify main.ckedialog.js.
`elfUrl = './php/connector.minimal.php'` to `elfUrl = './elfinder/php/connector.minimal.php'`
And
`baseUrl : 'js'` to `baseUrl : 'elfinder/js'`
That's all.

**Comment by parvanova** [comment]
I changed my file structure to be as the one you described.
I also changed elfUrl and baseUrl in main.ckedialog.js.

Unfortunately the errors are still the same

Uncaught ReferenceError: $ is not defined at elfinder.js:5186
Uncaught TypeError: Cannot read property 'prototype' of undefined - main.ckedialog.js:35

I need the CKeditor and Elfinder for a project done with CodeIgniter. But as I wasn't able to make it work in the project now I am testing it outside of the project just to be sure that nothing from the CI project causes the errors. 


Thank you for helping me!

**Comment by nao-pon** [comment]
> Uncaught ReferenceError: $ is not defined at elfinder.js:5186

Please load elfinder.min.js or elfinder.full.js instead of elfinder.js.

**Comment by parvanova** [comment]
where should I take it from?

in js directory there is only elFinder.js and it is not minifyed

**Comment by parvanova** [comment]
OK. I took the elfinder.full.js from https://hypweb.net/elFinder-nightly/demo/2.1/ and now almost everything works.
Browsing the server works. Inserting images in CKeditor works. 
 But when the "Send it to the server" button is clicked the error  in console is "main.ckedialog.js:68 Uncaught TypeError: Cannot read property 'convAbsUrl' of undefined". In fact the file is uploaded but the tab is not switched.

**Comment by parvanova** [comment]
To fix the above error I took main.ckediealog.js from https://hypweb.net/elFinder-nightly/demo/2.1/ too.

I had to edit the elfUrl, baseUrl, filebrowserUploadUrl, imageUploadUrl.
No everything works fine

Thank you!

**Comment by nao-pon** [comment]
@parvanova You can download elFinder on https://github.com/Studio-42/elFinder/releases .
