### ISSUE TITLE
Problem with german umlauts in Dowload and zip (LocaleVolumeDriver)

### ISSUE THREAD

**Issue by dkaar** [Studio-42/elFinder#2399]
There are some problems with german umlauts, when downloading or zipping files or folders.

Files with special characters get skipped when downloading them from a folder oder when more files are choosen and get zipped to download, teh same happens with folders.

Furthermore if you unzip a Folder files with a umlaut also get skipped and not copied to the folder.

**Comment by nao-pon** [comment]
@dkaar elFinder treats the file name as UTF-8. To decompress the archive compressed with elFinder use an archiver that can handle UTF-8.

To decompress archives containing files other than UTF - 8 on elFinder, use a library that converts the encoding to UNICODE.

For example in the Japanese environment "https://github.com/polygonplanet/encoding.js" is used.
```javascript
fm.registRawStringDecoder(function(s) {
	return Encoding.convert(s, {to:'UNICODE',type:'string'});
});
```
