### ISSUE TITLE
Why I cannot Upload a epub file into elFinder or Where can I give permission for certain format files?

### ISSUE THREAD

**Issue by zamebit** [Studio-42/elFinder#2400]
![image](https://user-images.githubusercontent.com/1704345/36507283-31d598a6-1727-11e8-8a77-b24e31b7f747.png)

**Comment by nao-pon** [comment]
@zamebit Please check the Wiki. There is a connector roots option  [`uploadAllow`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadallow).
