### ISSUE TITLE
elFinder is not compatible with the latest version of jQuery

### ISSUE THREAD

**Issue by MonkeyMaster** [Studio-42/elFinder#2401]
JQMIGRATE: jQuery.fn.click() event shorthand is deprecated
JQMIGRATE: jQuery.fn.mousedown() event shorthand is deprecated
JQMIGRATE: jQuery.fn.resize() event shorthand is deprecated
JQMIGRATE: jQuery.fn.hover() is deprecated
JQMIGRATE: jQuery.fn.focus() event shorthand is deprecated
JQMIGRATE: jQuery.fn.blur() event shorthand is deprecated

**Comment by MonkeyMaster** [comment]
Looks like .on('hover' is also removed:
http://api.jquery.com/on/
"Deprecated in jQuery 1.8, removed in 1.9: The name "hover" used as a shorthand for the string "mouseenter mouseleave""

**Comment by nao-pon** [comment]
@MonkeyMaster Thanks!

**Comment by MonkeyMaster** [comment]
another one:
JQMIGRATE: jQuery.fn.mousedown() event shorthand is deprecated
js/elfinder.full.js:11794:5

**Comment by nao-pon** [comment]
@MonkeyMaster Thanks! I'll fix it. 👍
