### ISSUE TITLE
Option to use dynamic memory allocation for large images

### ISSUE THREAD

**Issue by bwaindwain** [Studio-42/elFinder#2402]
Image operations in elfinder are done by PHP  (make thumbnail/resize/rotate/crop) and are subject to the PHP's memory_limit. If an image has too many megapixels, the "PHP allowed memory size of x bytes exhausted..." is triggered.

It would be nice if there was an option in elfinder to allow it to dynamically change PHP's memory_limit to allow image processing to succeed. It should default to OFF so as not to offend any server admins.

See sample code at http://php.net/manual/en/function.imagecreatefromjpeg.php#60241

Note: this is related to # of pixels of the image, not file size.

related https://github.com/Studio-42/elFinder/issues/1922

**Comment by nao-pon** [comment]
@bwaindwain Thanks! 👍
