### ISSUE TITLE
How can i change path in every page in elfinder

### ISSUE THREAD

**Issue by badrizahra** [Studio-42/elFinder#2404]
i have a problem with elfinder . i set path in config file in connector.minimal.php file like this : 
        'path'          => '../../upload/'

and in my view page i use this : 
 select_img=function()
        {
            var id = '{{ $item->id }}';
            var elfinder = $('#elfinder').elfinder({

                url: '{{ asset('elFinder/php/connector.minimal.php') }}'

                resizable: false,
                getfile : {
                    onlyURL  : true,
                    multiple : false,
                    folders  : false,
                    oncomplete : ''
                },
                handlers: {
                    dblclick: function(event, elfinderInstance) {
                        fileInfo = elfinderInstance.file(event.data.file);

                        if (fileInfo.mime != 'directory')
                        {
                            var s=elfinderInstance.url(event.data.file);
                            var pos = s.indexOf("/elFinder/php/../../");
                            s=s.slice(pos);
                            var ss=s.replace('/elFinder/php/../../','');
                            $("#logo").val(ss);
                            var img='<img src="<?= url('').'/' ?>'+ss+'" style="width:100%;height:120px;"  />';
                            $("#img_box").html(img);
                            elfinderInstance.destroy();
                            //$('#elfinder').dialog('close');
                            return false; // stop elfinder
                        }
                    },
                    destroy: function(event, elfinderInstance) {
                        elfinder.dialog('close');

                    }
                }
            }).dialog({
                title: 'select image',
                resizable: true,
                width:800,
                height: 500
            });
        }

i want to select diffrent path in every page and dont allow to user to access to all folders in every page. how can i set this path for every page : path: '../../upload/seller/'+id+'/'
??!!
thanks

**Comment by nao-pon** [comment]
@badrizahra You can set user ID in connector.minimal.php isn't it?
