### ISSUE TITLE
Direct use from PHP

### ISSUE THREAD

**Issue by Yves-K** [Studio-42/elFinder#2409]
Hello, 

elFinder provides extraordinary tools for picture and file management.

But i can't find a way to use the connector directly from PHP.

I'm migrating many images files and would like to use the elfinder connector to process and get the json success data (if success) on each of the files (i have a SplFileObject for each).

Any idea ?

Best regards

**Comment by nao-pon** [comment]
@Yves-K You can access the connector URL directly.

ex.
- https://hypweb.net/elFinder-nightly/demo/2.1/php/connector.minimal.php?cmd=open&target=l1_Lw

see - [Client Server API 2.1](https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1)

**Comment by Yves-K** [comment]
Thank you for your answer @nao-pon .

But i'd lookinf for ow to  **create a connector instance and address it's methods**

Regards

**Comment by nao-pon** [comment]
In that case please inherit the elFinderConnector class or create a new connector class and use it.
