### ISSUE TITLE
http error 503

### ISSUE THREAD

**Issue by michalm2018** [Studio-42/elFinder#2410]
I have a problem with "Backend connection error http 503 error". It shows the moment I try to open the elfinder. 
<img width="667" alt="screenshot at mar 04 07-29-43" src="https://user-images.githubusercontent.com/11843322/36942890-7595dd08-1f7e-11e8-8f98-be2396062cdc.png">

Any suggestions?

**Comment by nao-pon** [comment]
@michalm2018 Please try the cliant configlaton `requestMaxConn`. It is a setting concerning simultaneous request limitation.

ex.
```javascript
var options = {
	url  : 'php/connector.php',
	requestMaxConn : 1
}
$('#elfinder').elfinder(options);
```
