### ISSUE TITLE
question bug or normal

### ISSUE THREAD

**Issue by hayes-seyah09354085977** [Studio-42/elFinder#2416]
handlers : {
        
                  remove : function(event, elfinderInstance) {
                   console.log('delete');
                 },
                 rename  : function(event, elfinderInstance) {
                  console.log("rename");
                   }
}

after i rename something the delete console is showing? is that a normal or a bug?

**Comment by hayes-seyah09354085977** [comment]
handlers : { 
               remove : function(event, elfinderInstance) {
               console.log('delete');
             },
                 mkdir  : function(event, elfinderInstance) {
                  console.log("mkdir");
                   },
}

here after i delete mkdir is reading the function

**Comment by nao-pon** [comment]
@hayes-seyah09354085977 It is not a bug. From the manager's perspective, the rename will be deleted and added. Then the rename event fires when the rename command completes.

**Comment by hayes-seyah09354085977** [comment]
which handler should i use i monitor what file is openned?
i use:

open  : function(event, elfinderInstance) {
                    
               console.log("folder open");
                },
it only works for folder :D thanks in advance

**Comment by nao-pon** [comment]
@hayes-seyah09354085977 Since an XHR request to the back end does not occur when the file is opened, please use "exec" with 2.1.35 or later.

```javascript
exec : function(e, fm) {
    var data = e.data;
    if (data.cmd === 'open') {
        fm.log(data);
    }
}
```

**Comment by hayes-seyah09354085977** [comment]
thank you sir :D so much!
