### ISSUE TITLE
ELFINDER TOKEN AUTHENTICATION, maybe you want to publish it somewhere

### ISSUE THREAD

**Issue by BjornMelgaard** [Studio-42/elFinder#2418]
https://gist.github.com/BjornMelgaard/ed861ef96ef50b25ad75762a36551592

**Comment by nao-pon** [comment]
@BjornMelgaard I added to the Wiki - https://github.com/Studio-42/elFinder/wiki/HOWTOs-by-external-sites . Thanks! 👍
