### ISSUE TITLE
PHP compatibility problem

### ISSUE THREAD

**Issue by MonkeyMaster** [Studio-42/elFinder#2425]
ini_set(): Use of mbstring.internal_encoding is deprecated (D:\Web\intranet\web\protected\vendor\studio-42\elfinder\php\elFinder.class.php:467)

http://php.net/manual/en/mbstring.configuration.php#ini.mbstring.internal-encoding
> This feature has been DEPRECATED as of PHP 5.6.0. Relying on this feature is highly discouraged.

**Comment by nao-pon** [comment]
@MonkeyMaster Yes, I know. That part is ...
```php
if (ini_get('mbstring.internal_encoding')) {
	ini_set('mbstring.internal_encoding', '');
}
```
That is, it will only be executed if `mbstring.internal_encoding` is set in php.ini or on before elFinder instance creation.

Please check the value of `mbstring.internal_encoding` in your environment.

**Comment by enlivenapp** [comment]
I'm using PHP 7.1.8 and have a similar issue on dev and production servers.

    ini_set(): Use of iconv.internal_encoding is deprecated
    Filename: php/elFinder.class.php
    Line Number: 464

and 

    Message: ini_set(): Use of mbstring.internal_encoding is deprecated
    Filename: php/elFinder.class.php
    Line Number: 467

If these two things are depreciated in PHP 5.6+, why are you specifically checking for PHP >= 5.6 to set them?  Wouldn't you want to check for lower versions and not bother with any higher version?
 
below makes elfinder usable, as does commenting out both `ini_set()`s.

    if (version_compare(PHP_VERSION, '5.6', '<')) {

Additionally, the latests elfinder release (2.1.35) gives me this error:
 
    http://requirejs.org/docs/errors.html#scripterror

**Comment by nao-pon** [comment]
@enlivenapp If values are set in iconv.internal_encoding or mbstring.internal_encoding in the environment of PHP 5.6 or higher, those settings are invalidated by setting an empty value. If those errors are reported, It shows those values are set in php.ini etc.

**Comment by enlivenapp** [comment]
@nao-pon,

Because they have a value does not mean they are set in php.ini! I understand you're invalidating them, my problem is first, `iconv.internal_encoding` is not even present in my .ini, and second `mbstring.internal_encoding` is commented out which means they're being set by the `default_charset` value which defaults to `UTF-8`.  See below.

According to PHP (http://php.net/manual/en/iconv.configuration.php)

    PHP 5.6 and later users should leave this empty and set default_charset instead.

So why not leave `iconv.internal_encoding` or `mbstring.internal_encoding` alone (since they cause depreciation errors and the PHP group says to do so) and deal with it through default_charset which defaults to UTF-8

    http://php.net/manual/en/ini.core.php#ini.default-charset
    default_charset string
    In PHP 5.6 onwards, "UTF-8" is the default value and its value is used as the default character
    encoding for htmlentities(), html_entity_decode() and htmlspecialchars() if the encoding parameter
    is omitted. The value of default_charset will also be used to set the default character set for iconv
    functions if the iconv.input_encoding, iconv.output_encoding and iconv.internal_encoding 
    configuration options are unset, and for mbstring functions if the mbstring.http_input
    mbstring.http_output mbstring.internal_encoding configuration option is unset.
    ...
    internal_encoding string
    Available from PHP 5.6.0. This setting is used for multibyte modules such as 
    mbstring and iconv. Default is empty. If empty, default_charset is used.

**Comment by enlivenapp** [comment]
@nao-pon 

Regarding require.js errors.

2 Console errors;

    Failed to load resource: http://cdnjs.cloudflare.com/ajax/libs/elfinder/2.1.35/js/elfinder.min.js
    Failed to load resource: http://cdnjs.cloudflare.com/ajax/libs/elfinder/2.1.35/js/extras/editors.default.js

No change when emptying cache.

**Comment by nao-pon** [comment]
@enlivenapp The value of `iconv.internal_encoding` or `mbstring.internal_encoding` are empty value as default. Please check all ini files php reads.

However, if its value is `UTF-8`, it does not interfere with the operation of elFinder, so I'll add checking if it is `UTF-8` in elfinder.class.php.

```php
if (($_val = ini_get('iconv.internal_encoding')) && strtoupper($_val) !== 'UTF-8') {
    ini_set('iconv.internal_encoding', '');
}
if (($_val = ini_get('mbstring.internal_encoding')) && strtoupper($_val) !== 'UTF-8') {
    ini_set('mbstring.internal_encoding', '');
}
if (($_val = ini_get('internal_encoding')) && strtoupper($_val) !== 'UTF-8') {
    ini_set('internal_encoding', '');
}
```

**Comment by enlivenapp** [comment]
@nao-pon Thanks for looking into all of that.  It's appreciated.

I'll keep an eye on the cdnjs bit and use 2.1.35 when that's all resolved.
