### ISSUE TITLE
Elfinder is not working on production server

### ISSUE THREAD

**Issue by gadangmadhulika** [Studio-42/elFinder#2427]
Hi nao-pon,
Elfinder is working well, locally and on test server but its not working on production server.

![elfinder_500_issue](https://user-images.githubusercontent.com/29269101/37597992-fadeaa4c-2ba6-11e8-8327-408d0d04aa98.png)

**Comment by gadangmadhulika** [comment]
@nao-pon 
Appreciate for your quick response
Thanks

**Comment by nao-pon** [comment]
@gadangmadhulika What is PHP version and elFinder version? Did you have try the debug mode of elFinder? 

```php
$opts = array(
    'debug' => true,
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    )
);
```

**Comment by gadangmadhulika** [comment]
@nao-pon 
Hi,
1.Elfinder version:2.1.10
2.Locally we are using php version:7.1

we tried Debug=>true property in config/elfinder.php ,but no effect.

Console error:
/elfinder/connector?_token=hAB5MBsrmIPi3Op11GtReXd3EbNv7lPBozu71jz8&cmd=open&target=&init=1&tree=1&_=1521465462016

**Comment by nao-pon** [comment]
@gadangmadhulika The version of elFinder is too old. Please check with the latest version. Please let me know the error that PHP will issue with the latest elFinder.

**Comment by SantoshTirukkovilour** [comment]
@nao-pon 
I have the same issue with latest elfinder.  I dont think it would be a issue if we use ^2.1.10 in composer.json

What PHP version will supports latest Elfinder?

**Comment by venukommu** [comment]
@nao-pon - We are using PHP v 7.0 and Ubuntu 16.04 on production server.

**Comment by venukommu** [comment]
@nao-pon 
![image](https://user-images.githubusercontent.com/31344811/37604407-edb97ac6-2bb6-11e8-97d6-763cdff45fa7.png)

**Comment by nao-pon** [comment]
The version of PHP supported by elFinder is 5.2 or higher. I am checking the operation with PHP 5.3, 5.5, 5.6 and 7.2.

Screenshots seem to be integrated with something, but please check the operation with plain elFinder. Then let me know the error message that PHP reports.

**Comment by Colinax** [comment]
This must be an internal problem, sometimes it is enough to press F5 to reload elfinder and the error is gone. (elFinder 2.1.33)

**Comment by nao-pon** [comment]
@Colinax Does the error occur if you do not integrate elFinder anything?

**Comment by venukommu** [comment]
@nao-pon 
As we stated above, we are able to run the File Manager successfully on Staging, there we are using PHP 7.1.12-3+ubuntu16.04.1+deb.sury.org+1 (cli)

But not running well on Production even though we moved the same code, there we are using PHP 7.1.11-1+ubuntu16.04.1+deb.sury.org+1 (cli)

Is it any issue ?
Appreciate your quick help

**Comment by nao-pon** [comment]
@venukommu Your screenshot is integrated with something else application. Please verify with elFinder which does not integrate in order to determine whether the problem is elFinder or its application.

**Comment by venukommu** [comment]
@nao-pon - But it was working well on the Staging server. We just moved whatever we have in the Staging to Production. We are getting this issue with only Production. Please check the following error which is captured from error log file.

[2018-03-23 06:37:26] staging.ERROR: Class replace-this-with-your-middleware doe
s not exist {"exception":"[object] (ReflectionException(code: -1): Class replace
-this-with-your-middleware does not exist at /var/www/builds/360/vendor/laravel/
framework/src/Illuminate/Container/Container.php:752)

**Comment by Colinax** [comment]
I saw this bug in my other test environment, in my current test environment I tried to reproduce the bug (as built-in and stand alone) with PHP 7.2.1, 7.2.2 and 7.2.3, without success.

When you want I can check it to with some 7.1.x versions.

**Comment by venukommu** [comment]
Thank you everyone for participating to help us. We made so many changes to fix this issue, but gracefully all the issues were resolved when cleared the cache using following commands on Production. It could be there is just an error somewhere.

php artisan cache:clear
php artisan config:clear
php artisan route:clear

@barryvdh - Thanks.
https://github.com/barryvdh/laravel-elfinder/issues/52

**Comment by sbekzhan** [comment]
so how i can decide this problem , i am working with yii2 and elfinder i also getting error 500
