### ISSUE TITLE
max connection limit with http response 429

### ISSUE THREAD

**Issue by standus** [Studio-42/elFinder#2430]
Hi,
I have some problem with connection limit for security reason.
One of my custom connector downloading preview images from source which is limited by security reason.
Exists or is possible in elfinder core prepare option something like: maxConnection, which will tell to core that it can connect in same time only with max connections? 
Or maxConnection per minute, etc..
Other assets will wait in queue.
Thank you very much

**Comment by nao-pon** [comment]
@standus There are some options in connector side and client side.

**Connector side**
- [uploadMaxConn](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadmaxconn-elfinder--2112)

**Client side**
- [loadTmbs](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#loadtmbs)
- [requestMaxConn](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L58-L63)
