### ISSUE TITLE
the http requests need about 30seconds from web to mysql

### ISSUE THREAD

**Issue by xizan** [Studio-42/elFinder#2438]
please help me solve this question,when i get the http request from web to mysql，you can look the picture! thank you for help me!
![qq 20180323141818](https://user-images.githubusercontent.com/16182518/37814457-1131efec-2ea5-11e8-8055-cae4661ac35e.png)

**Comment by nao-pon** [comment]
@xizan Is #2384 related? If it is the cause it has been fixed since 2.1.33.

**Comment by xizan** [comment]
@nao-pon   yes，i use the lastest version 2.1.35 ,but this is the same proplem. the link address "http://localhost:8088/php/connector.minimal.php?cmd=open&target=m1_NA&init=1&tree=1&_=1522027849545"  needs 30s to request。 so can you give me a new and useful veison to my email "1587516339@qq.com". Thank you very much.
![qq 20180326100020](https://user-images.githubusercontent.com/16182518/37883355-8ab4da76-30dc-11e8-9721-9c5608c6f5a3.png)

**Comment by xizan** [comment]
@nao-pon  thank you ! but i use the lastest version 2.1.35 ,the same as that ,when the requests  access web with  mysql driver.
![qq 20180326154021](https://user-images.githubusercontent.com/16182518/37893076-81b6bdec-310c-11e8-888f-12982616459b.png)

**Comment by xizan** [comment]
@nao-pon what's your versions of php and mysql ? And what should i notice?

**Comment by nao-pon** [comment]
@xizan I'm checking with PHP 5.5/MySQL 5.1. There are no problems. Please check your API protocol version is 2.1035.
![inkedfireshot capture 9 - demo_elfinder 2 1 - https___hypweb net_elfinder-nightly_demo_develop_ elf_l1_lw_li](https://user-images.githubusercontent.com/1412630/37960564-e55c1470-31f0-11e8-94be-ebc4fefabe3d.jpg)
