### ISSUE TITLE
Missing 'src' on Paste command

### ISSUE THREAD

**Issue by actorius** [Studio-42/elFinder#2439]
Then trying paste copied file between folders i get error `Invalid parameters for command "src".`

Headers:
```
cmd:paste
dst:v1_TWVkaWE1
targets[]:v1_XDI0LjAzLjIwMTgg0KHQv9Cw0YDRgtCw0LrQuNCw0LTQsCBjb3B5XDI0LjAzINCh0L_QsNGA0YLQsNC60LjQsNC00LAgY29weS5tcDQ1
cut:0
suffix:~
_:1522044619457
```
Response:
`{"error":["errCmdParams","src"]}`

ElFinder Client:
Version: 2.1.33, protocol version: 2.0
jQuery/jQuery UI: 3.3.1/1.12.1

**Comment by nao-pon** [comment]
@actorius Since API 2.0 also includes directory information in target, the src parameter is not necessary. However, the description of the wiki page seems to be wrong. In order to maintain compatibility, I also add src parameters for 2.0 connectors.

Thanks!
