### ISSUE TITLE
the video uploading have a problem

### ISSUE THREAD

**Issue by xizan** [Studio-42/elFinder#2443]
the uploading  mp4 version of videos don't success , help me to solve it .thank you !
![qq 20180327140947](https://user-images.githubusercontent.com/16182518/37949878-0c3362ce-31c9-11e8-9e3e-e735af519e11.png)

**Comment by xizan** [comment]
![qq 20180327142520](https://user-images.githubusercontent.com/16182518/37950342-bf82b252-31ca-11e8-9b68-dffe638a5e6f.png)

**Comment by nao-pon** [comment]
@xizan Please make `LOAD_FILE` available in MySQL configuration or adjust the value of `max_allowed_packet`.
