### ISSUE TITLE
Thumbnail url error when has params "?_t=xxxxxx"

### ISSUE THREAD

**Issue by NinaSts** [Studio-42/elFinder#2444]

**Comment by nao-pon** [comment]
@NinaSts Are you having any problems?

**Comment by NinaSts** [comment]
@nao-pon Sorry for this topic. First time i got problem with folder "/.tmb/" cuz my vps config prevent "dot" on url. But i fixed it, so i thing need delete topic to save both time. Thank you, btw your code is rock :D

**Comment by nao-pon** [comment]
@NinaSts OK, It can't delete the issue on GitHub, so I'll close this.
