### ISSUE TITLE
would like to remove permissions and locked description from GetInfo popup

### ISSUE THREAD

**Issue by gadangmadhulika** [Studio-42/elFinder#2445]
Hi,@nao-pon 
![info](https://user-images.githubusercontent.com/29269101/38007708-4cd77d0c-3268-11e8-9332-dd473e4c1b24.png)

I would like to remove permissions and locked property from GetInfo dialog popup in elfinder,please let me know how can i do that.
Appreciate your quick response

**Comment by nao-pon** [comment]
@gadangmadhulika Since it can not be hidden under present conditions, I plan to add an option to make it possible.

Thanks!

**Comment by gadangmadhulika** [comment]
Thank you so much @nao-pon

**Comment by SantoshTirukkovilour** [comment]
Hi @nao-pon, @gadangmadhulika 

I tried to hide get info items like below, but its not working, could you check and correct me if I'm wrong with below code

//inside command options
info : {
        hideItems : ['path']
}


Thank you for your quick response .

**Comment by nao-pon** [comment]
@SantoshTirukkovilour That's correct. However, the setting saved in the browser takes precedence. Please check with reset your preferences.

**Comment by gadangmadhulika** [comment]
Hi @nao-pon 
I tried by clearing browser history but no luck.
How to reset preferences?

**Comment by nao-pon** [comment]
@gadangmadhulika There is the "Reset" button in reset tab in preferences dialog on elFinder.
