### ISSUE TITLE
Mass file download will be interrupted

### ISSUE THREAD

**Issue by llovvoll** [Studio-42/elFinder#2446]
Hi,

I found that large files (5GB) will be automatically interrupted when downloaded.
I have set set_time_limit(0);, will have the same situation
What will be the problem?

Thanks so much.

**Comment by nao-pon** [comment]
@llovvoll Is it due to the web server or php-fpm timeout?

**Comment by llovvoll** [comment]
Have you encountered the same situation? Web server and php-fpm, set value I have confirmed

**Comment by nao-pon** [comment]
@llovvoll In my test environment (Apache 2.2 + mod_xsendfile + PHP module), such problems can not be reproduced. You'd better consider using 'X-Sendfile' or 'X-Accel-Redirect'.

**Comment by nao-pon** [comment]
There is no problem in the environment of Apache 2.2 + PHP module without mod_xsendfile. I tested the file download of about 8 GB and completed normally in about 30 minutes.

**Comment by nao-pon** [comment]
@llovvoll I got that [`fpassthru()` has a bug](https://bugs.php.net/bug.php?id=66736) in the output of large size files if PHP version is less than 5.6. So I'll fix it by elFinder side.

**Comment by nao-pon** [comment]
@llovvoll Please try the [Nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).
