### ISSUE TITLE
what's the path and codes when i insert  into the mysql  with uploading some files

### ISSUE THREAD

**Issue by xizan** [Studio-42/elFinder#2447]
i  know the codes when i create some files ,for example the first picture.But i don't know what's  the code when i upload some files.
![qq 20180328164256](https://user-images.githubusercontent.com/16182518/38018426-6fc82656-32a7-11e8-9ea1-effd1008dd57.png)

**Comment by xizan** [comment]
![qq 20180328174054](https://user-images.githubusercontent.com/16182518/38021383-4173f908-32af-11e8-9e68-7eb48bd8c8ee.png)
![qq 20180328174100](https://user-images.githubusercontent.com/16182518/38021384-41b7ad24-32af-11e8-85ad-9bb68e53191e.jpg)

**Comment by nao-pon** [comment]
@xizan `_save()` is that. Probably you will be check `_copy()` too to support user_id.
