### ISSUE TITLE
Can't display image inline when upload image and duble click it.

### ISSUE THREAD

**Issue by mshayashi** [Studio-42/elFinder#2450]
When I upload image and duble click the uploaded image on elFinder, content url is wrong on popup window.
1. uploaded 17.jpg.
2. double click uploaded 17.jpg.
3. popup window's url is https://localhost/7.jpg

https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeDriver.class.php
I think it should not add 1 on the source code of getContentUrl method on 2981 line.

```
$path = str_replace($this->separator, '/', substr($this->decode($hash), strlen($this->root) + 1));
```
It might be below is correct.
```
$path = str_replace($this->separator, '/', substr($this->decode($hash), strlen($this->root) ));
```

Is this a bug, or another reasons?

**Comment by nao-pon** [comment]
@mshayashi This is a bug. There is a problem when $root is "/". so I'll fix it.

Thanks! 👍
