### ISSUE TITLE
the files  dynamic show in php codes 

### ISSUE THREAD

**Issue by xizan** [Studio-42/elFinder#2451]
I want to use php codes instead of something that  the js codes controll the label show.  How  can i do !
 thank you !
![qq 20180330155338](https://user-images.githubusercontent.com/16182518/38129839-37da7a86-3433-11e8-9493-c70b16a7ff66.png)

**Comment by xizan** [comment]
And I need  some relationship introductions  between  file and file directory in php and js !

**Comment by xizan** [comment]
And I need some relation introductions between file and file directory in php and js !

**Comment by nao-pon** [comment]
@xizan Please chack the Wiki - https://github.com/Studio-42/elFinder/wiki/Custom-context-menu-command . And make extended class that inherits elFinder.class.php and add custom command for back end.
