### ISSUE TITLE
how can i know the account's admin or others ,i want to see the code between login and mysql 

### ISSUE THREAD

**Issue by xizan** [Studio-42/elFinder#2456]
how can i know the account's admin or others ,i want to see the code between login and mysql ? Thank you!
![qq 20180402215946](https://user-images.githubusercontent.com/16182518/38199028-ae28d706-36c1-11e8-9c4f-674b29146f7a.png)

**Comment by nao-pon** [comment]
@xizan Please check out "[Basic auth example](https://studio-42.github.io/elFinder/#elf_l1_QmFzaWNBdXRoRXhhbXBsZQ)".
