### ISSUE TITLE
Move settings from "Preference" tab to separate window

### ISSUE THREAD

**Issue by alexantr** [Studio-42/elFinder#2458]
It's not intuitive to look for settings under help button.

We have so many settings now. They deserve separate window and button on toolbar near help button.

For example:
![settings](https://user-images.githubusercontent.com/4941848/38214120-4cb7ce22-36cc-11e8-8f1c-53f5af9e7bb7.png)

**Comment by nao-pon** [comment]
@alexantr I done. Thanks! 👍
