### ISSUE TITLE
handlers: remove

### ISSUE THREAD

**Issue by hiagobury** [Studio-42/elFinder#2464]
remove: function (event, fm) {
     event.data.removed[0].name
}

I need the name of the file that was removed

**Comment by nao-pon** [comment]
@hiagobury Catch the exec event and obtain the file which will be deleted in advance.

```javascript
var staged = {};
var elf = $('elfinder').elfinder('instance'); 

elf.bind('exec', function(e, fm) {
    if (e.data.cmd === 'rm') {
        staged = {};
        $.each(e.data.files, function(i, h) {
            staged[h] = fm.file(h);
        });
    } 
});

elf.bind('remove', function(e, fm) {
    var names;
    if (e.data.removed.length) {
        names = $.map(e.data.removed, function(h) {
            return staged[h]? staged[h].name : null;
        });
        fm.log(names);
    }
});
```

**Comment by hiagobury** [comment]
does not work

elf.bind('exec', function(e, fm) {

});

it's not running

**Comment by hiagobury** [comment]
thank you very much

**Comment by hiagobury** [comment]
`e.data.files` is undefined =(

**Comment by hiagobury** [comment]
everything perfect, I was letting something happen at the beginning of the file your solution is fine, thank you
