### ISSUE TITLE
Elfinder-windows cannot open the folder dialog occurs,when we click the downloaded zip folder

### ISSUE THREAD

**Issue by gadangmadhulika** [Studio-42/elFinder#2465]
Hi @nao-pon 
![ziperror](https://user-images.githubusercontent.com/29269101/38405251-9d55bd72-398c-11e8-9e0b-873518d48124.png)
when we select more than one file and select download option,then we are getting the above message.
Appreciate your quick response,
Thank you.

**Comment by nao-pon** [comment]
@gadangmadhulika Recent elFinder has a bug that creates a zip file in tar.gz format. This has [already been fixed](https://github.com/Studio-42/elFinder/commit/28689015412ab726fed4b5239a2672c7c4855a0c) and will be reflected in the next version. Please check the operation with [Nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

Thanks!
