### ISSUE TITLE
mkdir 'Into new folder' always on

### ISSUE THREAD

**Issue by bwaindwain** [Studio-42/elFinder#2466]
According to the source, mkdir.intoNewFolderToolbtn defaults to false. But it seems like it's always on. Even in the demo, it's switched on. Or maybe I'm misunderstanding this feature. 

See also https://github.com/Studio-42/elFinder/issues/1325

**Comment by nao-pon** [comment]
@bwaindwain I done fix it. Thanks! 👍

**Comment by bwaindwain** [comment]
I think this is still not working right in 2.1.38. The "New folder" button behaves like "Into new folder".

In the demo at https://studio-42.github.io/elFinder/

1. select a file
2. right-click and see "Into new folder"
3. on the toolbar, mkdir button changes tooltip to "New folder" but behaves like "Into new folder" 

![image](https://user-images.githubusercontent.com/2658754/39830973-36b88974-5380-11e8-8a6a-55bcecefbfb9.png)

**Comment by nao-pon** [comment]
Yes, looks wrong...

**Comment by nao-pon** [comment]
@bwaindwain Thanks! 👍

**Comment by bwaindwain** [comment]
great, thanks
