### ISSUE TITLE
Unable to upload

### ISSUE THREAD

**Issue by arp3van1** [Studio-42/elFinder#2474]
elfinder works properly unless we try to upload a file - we can duplicate files, create folders etc.. except upload
we use php 7.0
updated to latest version of elfinder2.1.37
anytime we try to upload a file we get "unable to upload - Transfer Error" no logs, no errors etc..
any help would be apprechiated

**Comment by Kreyco** [comment]
Hi, did you check folder permissions? Please send a screenshot from network tab (Developer tools).

**Comment by nao-pon** [comment]
@joemassa Please check with 'debug' of connector main option to show upload error.

**In "About this software" dialog**
![180412-000053](https://user-images.githubusercontent.com/1412630/38625276-0ad5023e-3de5-11e8-935e-94f15ad083e2.png)
debug.

**Comment by joemassa** [comment]
Is there a place where we can enable debug?

![aboutsoftware](https://user-images.githubusercontent.com/38289595/38625526-ac902b3e-3d78-11e8-949b-12042247a6b2.JPG)

**Comment by nao-pon** [comment]
Please set an option [`'debug'`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#debug) to `true` of connector main option.

```php
<?php

$opts = array(
    'debug' => true,
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    )
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```

**Comment by joemassa** [comment]
The odd thing is, that seems to be on. 

Below is the code for connector.php

<?php

error_reporting(0); // Set E_ALL for debuging

include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderConnector.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinder.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeDriver.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeLocalFileSystem.class.php';
// Required for MySQL storage connector
// include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeMySQL.class.php';
// Required for FTP connector support
// include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeFTP.class.php';


/**
 * Simple function to demonstrate how to control file access using "accessControl" callback.
 * This method will disable accessing files/folders starting from  '.' (dot)
 *
 * @param  string  $attr  attribute name (read|write|locked|hidden)
 * @param  string  $path  file path relative to volume root directory started with directory separator
 * @return bool|null
 **/
function access($attr, $path, $data, $volume) {
	return strpos(basename($path), '.') === 0       // if file/folder begins with '.' (dot)
		? !($attr == 'read' || $attr == 'write')    // set read+write to false, other (locked+hidden) set to true
		:  null;                                    // else elFinder decide it itself
}

$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)

			'path'          => "../../../../clientuploads/".$_GET['uid']."/",         // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . "/../../../../clientuploads/".$_GET['uid']."/", // URL to files(REQUIRED)
			// 'path'          => '../files/',         // path to files (REQUIRED)
			// 'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
			'accessControl' => 'access'             // disable and hide dot starting files (OPTIONAL)
		)
	)
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();

**Comment by nao-pon** [comment]
Debug tab require jQueryUI "tabs" and elFinder client option `commandsOptions.help.view` array need 'debug' (It's defailt).

**Comment by joemassa** [comment]
I think the issue might be with php not liking the tmp folder location. Is there a way to change it from /tmp to a spot within the website home docs directory?

**Comment by nao-pon** [comment]
Please check the Wiki - [`uploadTempPath`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadtemppath).

**Comment by joemassa** [comment]
Im getting this error in the debug: 

WARNING: is_writable(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/var/www/webdata:/var/www/whmcs_templates_c:/var/www/whmcs_attachments:/var/www/whmcs_tmp) in elFinder.class.php line 591

I have the path set for /var/www/whmcs_tmp in the connector code, not sure why it's still looking for /tmp

![connector](https://user-images.githubusercontent.com/38289595/38629081-0a5f188a-3d81-11e8-9ae3-7a3cfbce9367.JPG)

**Comment by nao-pon** [comment]
`uploadTempPath.` and `commonTempPath` are main options, they are not roots options.

**Comment by joemassa** [comment]
We left it as /tmp and seems to be working. Thanks for the assistance.
