### ISSUE TITLE
How to use Digital Ocean spaces for Elfinder

### ISSUE THREAD

**Issue by gadangmadhulika** [Studio-42/elFinder#2476]
Hi@nao-pon,Iam facing the below error,please help me. 
![doerror](https://user-images.githubusercontent.com/29269101/38726693-85521d8c-3f28-11e8-964f-b38f30203a7b.png)

Appreciate your quick response,
Thank you.

**Comment by nao-pon** [comment]
@gadangmadhulika I am not sure about third-party libraries or integration. Please ask the third party developer. And please let us know if you found the fixes of elFinder.
