### ISSUE TITLE
Uploading large number of files not working correctly

### ISSUE THREAD

**Issue by santoshray02** [Studio-42/elFinder#2479]
Hi,

I am trying to upload a folder contains 50,004 images (.png files)  but after upload is finished only 49984 images (.png files) in the respective directory.
I am running the elFinder inside the docker with latest pull .  

![screenshot from 2018-04-13 14-16-15](https://user-images.githubusercontent.com/12428112/38725868-341e85d8-3f26-11e8-8235-81d0f3a1346e.png)

**Comment by nao-pon** [comment]
@santoshray02 Have you tried a few times and got the same result always?

**Comment by santoshray02** [comment]
Yes ,
I have tried many times getting the same

**Comment by nao-pon** [comment]
OK,  Since 20 items are not enough, it probably means that one request has not been successfully processed. Is there no error message?

**Comment by santoshray02** [comment]
I have not got any error message

**Comment by nao-pon** [comment]
If you increase the value of [`max_file_uploads`](http://php.net/manual/ini.core.php) in php.ini (eg 30) what happens?

**Comment by santoshray02** [comment]
it worked 

Thanks
