### ISSUE TITLE
How can mount network volume S3-BUCKET to elfinder ?

### ISSUE THREAD

**Issue by santoshray02** [Studio-42/elFinder#2483]
I want one more option for aws s3bucket so that i can also mount the s3 volume 
![screenshot from 2018-04-18 15-59-25](https://user-images.githubusercontent.com/12428112/38926799-824867f2-4321-11e8-8238-f946ae631693.png)

Thanks

**Comment by nao-pon** [comment]
@santoshray02 As far as I know there is no driver for network mount of Amazon S3, so you need to create your own. You need to create a driver class or create a network mount driver that uses FlySystem.

There are similar drivers for [Box](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeBox.class.php), [Dropbox](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeDropbox2.class.php), [GoogleDrive](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeGoogleDrive.class.php) ([with FlySystem](https://github.com/Studio-42/elFinder/blob/master/php/elFinderFlysystemGoogleDriveNetmount.php)), [OneDrive](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeOneDrive.class.php). Will the source code help you?

**Comment by santoshray02** [comment]
Thanks @nao-pon 
Let me try it once .

**Comment by nao-pon** [comment]
@santoshray02 Please notify here when you got it.

**Comment by 3DUNAPI** [comment]
I'm also interested in getting this working.  I have tried to add the following to the connector.minimal.php file, but no luck as yet. Not really sure what else needs to be done.

`	//S3 Attempt
		array(
			'id'            => '1',
            'driver' => 'S3',
            'path' => 's3-eu-west-1.amazonaws.com',
            'URL' => 'https://s3-eu-west-1.amazonaws.com/',
            "s3" => array(
                "key" => "xxxxxxxxx",
                "secret" => "xxxxxxxxxx",
                "region" => "eu-west-1"
            ),
            "bucket" => "xxxxxxx",
            "acl" => "private"
        ),`

**Comment by bayucandra** [comment]
I made a working demo of S3 connector with full code example at this repo: https://github.com/bayucandra/ckeditor-elfinder . Please check README.md for detail how it was built and how to run the repo. Hope it helps someone.
