### ISSUE TITLE
How to adjust speed of animation in elFinder?

### ISSUE THREAD

**Issue by mauleous** [Studio-42/elFinder#2485]
Hi there,

Is there a way to customize the speed of animation in elfinder?

For example, when creating a new folder, there is this animation that blink the folder. And also, there is animation when expanding/collapsing a folder (in the folder tree pane on the left). 

![animation in elfinder](https://user-images.githubusercontent.com/16491906/39051581-cacf7484-44b1-11e8-83cf-52239694eb21.gif)

I would like to adjust this animation to play quicker.

Thanks in advance!

**Comment by mauleous** [comment]
Ah, for the blinking animation when a new folder is created, I think I found a way to do it:
``` 
// First, I created a function based on elFinder's Blink function and then reduce the timing
function blink(elm, mode) {
	var acts = {
		slowonce : function(){elm.hide().delay(150).fadeIn(250).delay(100).fadeOut(500);},
		lookme   : function(){elm.show().fadeOut(100).fadeIn(150);}
	}, func;
	mode = mode || 'slowonce';
		
	func = acts[mode] || acts['lookme'];
		
	elm.stop(true, true);
	func();
}

// and then I override the elFinder's blink function through its instance
elFinderInstance.resources.blink = blink;
```

I'm not sure if this is the right way to do this. But this works for me. 🙂 

However, I still can't find a way to adjust the animation of expanding/collapsing folder tree.
Can anyone help me with this?

**Comment by nao-pon** [comment]
@mauleous I added an option `uiOptions.tree.durations` to the client options.

```javascript
uiOptions : {
    tree : {
        // Durations of each animations
        durations : {
            slideUpDown : 'fast',
            autoScroll : 'fast'
        }
    }
}
```

**Comment by Giacomino1** [comment]
It's excellent but I have a problem with the external memory sd and so for now I can not download anything!
