### ISSUE TITLE
popup box blank in firefox

### ISSUE THREAD

**Issue by ianhaney** [Studio-42/elFinder#2486]
I have installed ckeditor 4.9.2 and integrated elfinder and followed the guide from here: https://github.com/Studio-42/elFinder/wiki/Integration-with-CKEditor

I integrated it using method 2 but when I click on the image icon in ckeditor and then click browse server, a box pops up but it is blank

Can anyone help please?

Thank you in advance

**Comment by nao-pon** [comment]
@ianhaney Is the setting value of `filebrowserBrowseUrl` correct?
