### ISSUE TITLE
invalid backend response, data is not json

### ISSUE THREAD

**Issue by wegeeus** [Studio-42/elFinder#2489]
Hi, 

when i upload the image, it comes "invalid backend response, data is not json"

**Comment by nao-pon** [comment]
@wegeeus Please check with a connector option [`debug`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#debug) (`'debug' => true`).

**Comment by wegeeus** [comment]
how to do it? and now i can't set image as product image

**Comment by wegeeus** [comment]
@nao-pon i even down grade the php to 7.1, but it still have problem, i can't set image as product main image or gallery.

**Comment by nao-pon** [comment]
Using the connector option [`debug`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#debug) you can get server side error messages. [See the wiki.](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#debug) In addition, elFinder supports PHP 5.2 to 7.2.

What is "product image"? I do not understand the meaning.

**Comment by wegeeus** [comment]
@nao-pon i'm using your extension for opencart 2.3. Now i can't set image for product image. can you send email to us? that will be more convenience. i can't post images here. i tried to contact you in opencart order system, but they said you disabled the extension.
my email is jay@wegee.us

**Comment by nao-pon** [comment]
@wegeeus I do not know about opencart. Please let me know if there is a problem when using elFinder standalone.

**Comment by wegeeus** [comment]
so you didn't see your extension for opencart?

**Comment by wegeeus** [comment]
can you tell us how to check a connector option debug ('debug' => true). which file we should edit

**Comment by nao-pon** [comment]
I do not know any extensions for opencart. I can not answer because I do not know how the extension is configured. You should ask the developer of the extension for opencart instead of here.

**Comment by wegeeus** [comment]
ok, thanks anyway
