### ISSUE TITLE
custom search that i can look inside at the content for PDF and image

### ISSUE THREAD

**Issue by hayes-seyah09354085977** [Studio-42/elFinder#2490]
im adding a function using OCR and adding the value to database 
my problem can you help me to add that thing to elfinder.js i want to add the button between filename and mime type TIA.

**Comment by nao-pon** [comment]
@hayes-seyah09354085977 It is related to #1037. I will add a client option that can send a search type identifier to the connector.

**Comment by nao-pon** [comment]
@hayes-seyah09354085977 Thanks! 👍 

To actually add custom searches, you need to extend the volume driver. For details, please see the wiki.

- https://github.com/Studio-42/elFinder/wiki/Custom-search-function

**Comment by hayes-seyah09354085977** [comment]
thank you very much i will share this one once its done
