### ISSUE TITLE
elFinder is used in servers with a lot of picture data

### ISSUE THREAD

**Issue by yinmingming** [Studio-42/elFinder#2492]
Hi
   My data storage server hard disk has 20T, most of which are stored in png, jpg, tif file format, each picture has about 100M. Now using elFinder to set the ` 'driver' => 'LocalFileSystem',` but the server will be very slow, so how can we speed up access?
 Thanks！

**Comment by nao-pon** [comment]
@yinmingming Because of elFinder's specification, we collect item information in directory at once. Therefore, in order to raise the response performance, it is necessary to reduce the number of items in the directory, one of which is a multi-level directory structure.

**Comment by yinmingming** [comment]
Ok  I got it!  Thank you very much!
