### ISSUE TITLE
How to use custom replacer with the Sanitizer plugin

### ISSUE THREAD

**Issue by hayes-seyah09354085977** [Studio-42/elFinder#2494]
i have a filename "test 20.1.txt" and i sanitize ( . ) and replace it "new". and the output is test 20 new.1new.text. my question is if it possible to sanitize the dot that next to extension name? if possible can you help me how TIA

**Comment by nao-pon** [comment]
@hayes-seyah09354085977 You can use an option `callback`.

```php
'plugin' => array(
    'Sanitizer' => array(
        'enable' => true,
        'callBack' => function($name, $options) {
            $ext = '';
            $pos = strrpos($name, '.');
            if ($pos !== false) {
                $ext = substr($name, $pos);
                $name = substr($name, 0, $pos);
            }
            return str_replace('.', 'new', $name) . $ext;
        }
    )
)
```

**Comment by nao-pon** [comment]
@hayes-seyah09354085977 Yes, It correct. I tested with elFinder 2.1.38. Rename "A.txt" to "A.B.C.txt", it became "AnewBnewC.txt".

**Comment by hayes-seyah09354085977** [comment]
the output must be A.B.C new.txt how to do that?

**Comment by CodeLyokoXtEAM** [comment]
if you want to change "A.B.C.txt" to "A.B.C new.txt"
change code `return str_replace('.', 'new', $name) . $ext;`  to `return $name . " new" . $ext;`

**Comment by hayes-seyah09354085977** [comment]
thank you so much @nao-pon and @CodeLyokoXtEAM
