### ISSUE TITLE
After success file rename do some code - how?

### ISSUE THREAD

**Issue by ShinJii89** [Studio-42/elFinder#2498]
Hi,
I want to do some code after success rename files, how to do that and where? connector.php? or just JS (how) and then call php file?

Something like if(rename==success) { do some code about that renamed file } is this possible?

**Comment by nao-pon** [comment]
@ShinJii89 Bind your function to the rename command with connector.php.

See
- https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind
- https://github.com/Studio-42/elFinder/wiki/Logging

**Comment by ShinJii89** [comment]
I finally sat today to this and one question - after renamed file I have in connector in $result only ['added'] and ['removed'] - why? why it's not ['changed'] ? how should I know it's renamed and not just fresh uploaded?...

**Comment by ShinJii89** [comment]
Second question - how to give with bind my own JSON response? for example if I have limited disk space for every user I have to check this in php and then give some error after upload in elfinder etc. and delete this file/files and maybe check this before uploading.
