### ISSUE TITLE
image thumb in ftp not display

### ISSUE THREAD

**Issue by vahidalvandi** [Studio-42/elFinder#2500]
why in ftp thumb image not show and in ftp can create thumbnail image like local host . with option tmbSize ,... ??

![untitled-1](https://user-images.githubusercontent.com/17952925/39906450-e58364d8-54f7-11e8-9a3e-7db7c9c3a321.jpg)

  		[
			'driver' => 'Flysystem',
			'URL' => 'http://dl.webine.ir',
			'alias' => 'FTP',
 
			'filesystem' => new Filesystem(new FtpAdapter(
					[
						'host' => 'dl.webine.ir',
						'username' => 'dlwebine',
						'password' => '4u3G6Ir8ul',
						 'root' => '/public_html',
					]
				)),
		],

**Comment by nao-pon** [comment]
@vahidalvandi It require [`tmbPath`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#tmbpath) and [`tmbUrl`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#tmburl) options. Or It seems it can with to [use Glide on the Flysystem driver](https://github.com/barryvdh/elfinder-flysystem-driver#displaying-thumbnailsimages-through-glide).
