### ISSUE TITLE
How do I make the php connector work without JSON errors? Even setting options as per documentation doesn't work.

### ISSUE THREAD

**Issue by DiemenDesign** [Studio-42/elFinder#2501]
I've had to add in options for client's to have their uploaded images automatically resize if they are larger than set width in my CMS's options, but I haven't been able to work out if there are options to force that resize maintain the original images Aspect Ratio. Does anyone know how to do this?

**Comment by nao-pon** [comment]
@DiemenDesign There isn't JavaScript option fot that. but, however there is a PHP plugin ["AutoResize"](https://github.com/Studio-42/elFinder/blob/master/php/plugins/AutoResize/plugin.php).

**Comment by DiemenDesign** [comment]
I just noticed that Chrome throw this error when an image is selected:
````
Uncaught TypeError: Cannot read property 'promise' of null
    at v (elfinder.min.js:11)
    at XMLHttpRequest.<anonymous> (elfinder.min.js:11)
v @ elfinder.min.js:11
(anonymous) @ elfinder.min.js:11
load (async)
xhr @ elfinder.min.js:11
f @ jquery-2.1.3.min.js:1
upload @ elfinder.min.js:9
g @ elfinder.min.js:23
v @ elfinder.min.js:23
(anonymous) @ elfinder.min.js:23
dispatch @ jquery-2.1.3.min.js:1
r.handle @ jquery-2.1.3.min.js:1
````

**Comment by DiemenDesign** [comment]
Silly me, I commented out the `error_reporting()` function, now when selecting an image I get:
![screenshot from 2018-05-14 10-39-09](https://user-images.githubusercontent.com/32765473/39973414-1d13c1c8-5763-11e8-8ef6-3b73a3346688.png)

**Comment by DiemenDesign** [comment]
In the log file I get:
````text
[18-May-2018 19:44:20 Australia/Melbourne] PHP Fatal error:  Class 'elFinderPlugin' not found in /var/www/LibreCMS/core/elfinder/php/plugins/AutoResize/plugin.php on line 63
````

**Comment by nao-pon** [comment]
It seems [autoload.php](https://github.com/Studio-42/elFinder/blob/2.1/php/autoload.php) has not been loaded or [php directory](https://github.com/Studio-42/elFinder/tree/2.1/php) placement is incomplete.

**Comment by DiemenDesign** [comment]
It was the `autoload.php`. I wasn't sure if it was being loaded elsewhere when the php is being called on the backend. I added it to the top of the includes area, now it works fine. Thanks for your help.
