### ISSUE TITLE
Replace blurry icons

### ISSUE THREAD

**Issue by alexantr** [Studio-42/elFinder#2503]
After "Icon Size" feature was integrated, need to replace blurry png icons (

- [x] volume_icon_* (f9b0e53d63d99e98c66cdd74d6c34e82b22bfe7e)
- [ ] icons-big
    - [x] overwrite type badge of icon image by CSS badge (c1a9f3afbce3aaa85640ff0a7bb3b98ca144ab73)

) with SVG or larger PNG files.

---
![uuc5ig4](https://user-images.githubusercontent.com/4941848/39923106-f34e48e8-552a-11e8-8ebf-0d6845e372e8.png)
---
![p80nur2](https://user-images.githubusercontent.com/4941848/39923130-07ad07b6-552b-11e8-9615-935d5ff45001.png)
---

**Comment by nao-pon** [comment]
@alexantr For volume icons, I'll replace them with SVG images. For type icons, it takes time and effort to use CSS sprites. We are looking for PR for this.

**Comment by alexantr** [comment]
At first it will be good to replace extensions on icons with text like on flv, amr, md and other.
Problem extensions:
![tjphjso](https://user-images.githubusercontent.com/4941848/39987646-07df6356-576e-11e8-9a49-5fec2cb23de0.png)

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon 
I'm creating some windows 10 icons svg (not completed yet) for my project.
https://github.com/CodeLyokoXtEAM/icons
if you want some of icons, you can use it. But its alike original windows 10/office/any other software  icons. So it may have copyright issues.

**Comment by nao-pon** [comment]
@alexantr Thanks! I'm using the[ Icons8's SVG icons](https://icons8.com/icon/). They are's size(1x) is 40px maybe. but i'm newcomer in the image editing, welcome your advicing.
