### ISSUE TITLE
how to change connector without reloading elfinder.html

### ISSUE THREAD

**Issue by hayes-seyah09354085977** [Studio-42/elFinder#2504]
`	array(
			
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '../files/',                 // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
			'trashHash'     => 't1_Lw',                     // elFinder's hash of trash folder
			'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		),`

i want to change the path without reloading the whole page

**Comment by nao-pon** [comment]
@hayes-seyah09354085977 In JavaScript.

```javascript
var options = {
	url  : 'php/connector.php'
}
$('#elfinder').elfinder(options);

var instance = $('#elfinder').elfinder('instance');

var volumeId = 'l1_';
var path = 'path/to/target'; // without root path
var hash = volumeId + btoa(path).replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '.').replace(/\.+$/, '');

// open target holder
instance.exec('open', hash);
```

**Comment by hayes-seyah09354085977** [comment]
i'll try this

**Comment by hayes-seyah09354085977** [comment]
how that code work?

**Comment by nao-pon** [comment]
Maybe `var path = 'content';`

**Comment by hayes-seyah09354085977** [comment]
i also try this 
var path = '../content/';
var path = 'c:/content/';

no luck

**Comment by nao-pon** [comment]
Does the "../files/content" directory exist?

Please describe the scenario you desire in detail. (Open new elFinder? Or change the folder of open elFinder? ... etc)

Or please show me the script of your web page.

**Comment by hayes-seyah09354085977** [comment]
i want to change the root directory or path dynamically
![capture](https://user-images.githubusercontent.com/35753309/40227531-5f80e14c-5ac1-11e8-92a7-7ab99617caff.PNG)

we building a search file via content using database and OCR
1st after the uploading the file the OCR function fetch the data and save it to database 
2nd to search the file we click the content it will find a search in content and copy it in content folder (temp folder) 
![capture2](https://user-images.githubusercontent.com/35753309/40228141-0756d290-5ac3-11e8-889e-fd9e2c2183d0.PNG)
3rd after the search the elfinder display the result of content folder

here my code 
var eto;

$(window).load(function() {
    $('div#elfinder').on("click","label:contains(Content)",function(){
        eto = $('div#elfinder').find('input#sseearch')[0].value;
        $.ajax({
            type: 'GET',
            async:true,
            url: "search.php",
            data: {eto:eto},
            success: function(result){
            result = $.parseJSON(result);
                console.log('search result', result);
                // console.log(result.length)
                // console.log(result)
                result.forEach(function(element){
                    
                    var loc = element.Location;
                    var file = element.Filename;
                    $.post('locator.php',{loc:loc,file:file},function(data){
                        console.log(data)
                    });
                })  
           
                var options = {
                    url  : 'php/connector.minimal.php'
                }
                $('#elfinder').elfinder(options);
        
                var instance = $('#elfinder').elfinder('instance');
                
                var volumeId = 'l1_';
                var path = 'content'; // without root path
                var hash = volumeId + btoa(path).replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '.').replace(/\.+$/, '');
                console.log(hash)
              
               instance.exec('open', hash);
            }
        });
       
    }); 
}); 



or how can i put this to your elfinder search machine

**Comment by nao-pon** [comment]
What is the need to change the root directory dynamically? It seems enough to [implementing the custom search function](https://github.com/Studio-42/elFinder/wiki/Custom-search-function).

**Comment by hayes-seyah09354085977** [comment]
honestly i don't know how to use that :(

**Comment by hayes-seyah09354085977** [comment]
what is the step to implement custom search?

**Comment by nao-pon** [comment]
Please return true if you search your database using $path and $query and match. This method is called for all target items.

**Comment by nao-pon** [comment]
I do not know the details because the structure of your database is unknown. What I can say is that the function `searchMatchContents($name, $query, $path)` needs to return `true` if the item of `$path` matches `$query`.

**Comment by richard100589** [comment]
![capture](https://user-images.githubusercontent.com/39425691/40409174-90a38c64-5e9c-11e8-9ef0-f00230ecd568.PNG)
my database structure location(path) filename and content. what am i missing?

**Comment by nao-pon** [comment]
Probably,

```php
protected function searchMatchContents($name, $query, $path) {
    static $results = null;
    if ($results === null) {
        $results = array();
    }
    if (!isset($results[$query])) {
        $sth=$dbDB->prepare("select * from [OCRTest] where Content LIKE '%".$query."%'");
        $sth->execute();
        $results[$query] = array_flip($sth->fetchAll(PDO::FETCH_COLUMN, 0));
    }
    return isset($results[$query][$this->_relpath($path)]);
}
```

However, the value of Location should be relative path from the root path. (Remove "/php/../files/")

**Comment by hayes-seyah09354085977** [comment]
here my result after i change the location data to my db
![2](https://user-images.githubusercontent.com/35753309/40417281-f69a1f6e-5eb1-11e8-8038-9373b5ef0b6b.PNG)
![3](https://user-images.githubusercontent.com/35753309/40417288-fae16c94-5eb1-11e8-8920-5703951ff7ba.PNG)

i try to search 'tr' to content
i double check if my db connector is correct and my connection is working

**Comment by nao-pon** [comment]
Since `$dbDB` is undefined it is natural to get an error. Even if copy paste is done as it is, it does not work. You need to understand the contents and respond by yourself.
