### ISSUE TITLE
How to setup FTP in elfinder. When I change connector, It gives Invalid backend configuration. Readable volumes not available

### ISSUE THREAD

**Issue by prashantrijal96** [Studio-42/elFinder#2505]
How to setup FTP in elfinder. When I change connector, It gives Invalid backend configuration. Readable volumes not available. I want to make my own file manager in my hosting domain

**Comment by nao-pon** [comment]
@prashantrijal96 Please check the Wiki - https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1 .

**Comment by prashantrijal96** [comment]
It donot work for me
please can u share connector code
