### ISSUE TITLE
[cmd:edit] not work if the "commandsOptions.edit.editors" is empty

### ISSUE THREAD

**Issue by pflind** [Studio-42/elFinder#2507]
Why don't you test the software before labelling it stable?

The so called stable release is throwing a bunch of errors right out of the zip-file. Such as "Failed to load resource: resource unavailable".

Also I tried upgrading from 2.1 to 2.1.38 and fixed all the missing resources, but then editing text files doesn't even work; `TypeError: undefined is not an object (evaluating 'r.done')`

This was once a great application but it has turned into shit in later years. People with low skills have effectively destroyed Elfinder with their incompetence.

**Comment by nao-pon** [comment]
@pflind 

1. Download elFinder-2.1.38.zip from https://github.com/Studio-42/elFinder/archive/2.1.38.zip
2. Extract to /elFinder-2.1.38 all of items
3. Rename /elFinder-2.1.38/php/connector.minimal.php.dist to /php/connector.minimal.php
4. Access to /elFinder-2.1.38/elfinder.html with newest Chrome/Firefox/IE11/Edge/Opera
5. There is nothing wrong

**Comment by pflind** [comment]
Not working with Safari/Mac, does not load.

**Comment by nao-pon** [comment]
I can not verify right away because I do not have the Mac. [My test site](https://hypweb.net/elFinder-nightly/demo/develop/?full=1) is loading the full source of JavaScript. Can you debug on that [site](https://hypweb.net/elFinder-nightly/demo/develop/?full=1)?

**Comment by nao-pon** [comment]
I found a problem. It happens when no editor is defined, such as not loading "js/extras/editors.default.js". So I will fix this.
