### ISSUE TITLE
Error When Editing

### ISSUE THREAD

**Issue by parkerj** [Studio-42/elFinder#2510]
I updated two different projects that went from version 2.1.33 to 2.1.38 and both face the same issue. When I right click on a file to edit, nothing happens. Below is a screenshot of the error message I get.

<img width="600" alt="elfinder" src="https://user-images.githubusercontent.com/2042176/40265545-7f7514a4-5b08-11e8-8644-3b61b696a70e.png">

**Comment by nao-pon** [comment]
@parkerj That is a bug. It can be avoided by loadding "js/extras/editors.default.js".

cf. #2257.

**Comment by parkerj** [comment]
Awesome, thanks.
