### ISSUE TITLE
re-arrange context menu

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2512]
I think its better to re-arrange context menu view option & add ascending and descending to short option
![image](https://user-images.githubusercontent.com/18566890/40308042-84e60cf6-5d22-11e8-93a5-29a0dfe812ef.png)

![image](https://user-images.githubusercontent.com/18566890/40308082-a781f87e-5d22-11e8-9cf3-fc3b33751c0f.png)

and new group option
![image](https://user-images.githubusercontent.com/18566890/40308139-c7c0ed98-5d22-11e8-896d-9ba222b5afdc.png)

**Comment by CodeLyokoXtEAM** [comment]
and also if space isn't enough to open sub menus in context menu, its better to open it other side.

![image](https://user-images.githubusercontent.com/18566890/40309201-4a9fb03e-5d26-11e8-8704-c5a605160350.png)
![image](https://user-images.githubusercontent.com/18566890/40309235-66e70292-5d26-11e8-905c-ef76bcedb513.png)

![image](https://user-images.githubusercontent.com/18566890/40309254-7af60be8-5d26-11e8-8dc5-abb9245d60fc.png)
![image](https://user-images.githubusercontent.com/18566890/40309275-89f4387c-5d26-11e8-836a-8b39c735780d.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM I completed tasks other than grouping function. Since we want to make the grouping function a future issue, please create a new issue individually.

Thanks! 👍
