### ISSUE TITLE
Multi Level directory creation when uploading

### ISSUE THREAD

**Issue by isreehari** [Studio-42/elFinder#2515]
My Root Folder  is : spfiles

I am in spfiles folder and upload a image then preUpload method saved the image in spfiles/2018/05/file.ext but it's not generating the thumbnail in spfiles/.tmb/ but MyLocalFileSystem class is creating folder structure in spfiles/.tmb/2018/05/. 

1.  If I remove the preUpload method it's creating the thumbnail without any issue with sub folders. 
2.  if preUpload method is **on**, then the thumbnails will creating only when we refresh the spflies/.tmb/2018/05 folder. 
3. **It seems like there is a problem with my preUpload function if so please let me know.** 

Please find the following code. 

```php
public function preUpload(&$path, &$name, $src, $elfinder, $volume){            

            $currentYear = date("Y");
            $currentMonth = date("m");
            
            $realpath = $elfinder->realpath($path);
            $realpath =  $realpath. '/' .$currentYear;

            if(!file_exists($realpath) || !is_dir($realpath)){
                $args = array('target' => $path, 'name' => $currentYear, 'reqid' => '' );
                $result = $elfinder->exec('mkdir', $args);
                if($result && $result["added"]){
                    $path = $result['added'][0]['hash'];         

                    $realpath = $realpath . '/' .  $currentMonth;
                    $args = array('target' => $path, 'name' => $currentMonth, 'reqid' => '' );
                    $result = $elfinder->exec('mkdir', $args);
                    if($result && $result["added"]){
                        $path = $result['added'][0]['hash'];    
                    }else{
                        return false;
                    }
                }else{
                    return false;
                }              
            }else{
                $realpath = $realpath . '/' .  $currentMonth;
                if(!file_exists($realpath) || !is_dir($realpath)){
                    $args = array('target' => $path, 'name' => $currentMonth, 'reqid' => '' );
                    $result = $elfinder->exec('mkdir', $args);
                    if($result && $result["added"]){
                        $path = $result['added'][0]['hash'];    
                    }else{
                        $path = $volume->getHash($path, $currentMonth);
                        return true;
                    }
                }                

            }

            $path = $volume->getHash($realpath, '');

            return true;
    }   



class elFinderVolumeMyLocalFileSystem extends elFinderVolumeLocalFileSystem
{
	protected function tmbname($stat) {
		$dir = $this->relpathCE($this->decode($stat['phash']));
		if (! is_dir($this->tmbPath.DIRECTORY_SEPARATOR.$dir)) {
			$dirs = explode(DIRECTORY_SEPARATOR, $dir);
			$target = $this->tmbPath;
			foreach($dirs as $_dir) {
				if (! is_dir($target . DIRECTORY_SEPARATOR . $_dir)) {
					mkdir($target . DIRECTORY_SEPARATOR . $_dir);
				}
				$target = $target . DIRECTORY_SEPARATOR . $_dir;
			}
		}
		return $dir . DIRECTORY_SEPARATOR . $stat['name'] . '.png';
	}

	protected function gettmb($path, $stat) {
		if ($name = parent::gettmb($path, $stat)) {
			$name = str_replace('\\', '/', $name); // For windows server
			$name = str_replace('%2F', '/', rawurlencode($name));
		}
		return $name;
	}

	public function tmb($hash) {
		if ($name = parent::tmb($hash)) {
			$name = str_replace('\\', '/', $name); // For windows server
			$name = str_replace('%2F', '/', rawurlencode($name));
		}
		return $name;
	}
}
```

**Comment by nao-pon** [comment]
@isreehari This issue related from #1795. The elFinder's php class "elFinder" does not support multi-level directory creation when uploading. So I'll fix this issue.

By the way, thumbnails are created when the file is displayed on the client side. Is that OK?

Thanks!

**Comment by isreehari** [comment]
@nao-pon  I tried to do some Donation to elFinder (nao-pon) through paypal but it does not go through please check it once. 


Thanks,
Hari

**Comment by nao-pon** [comment]
@isreehari Thanks!

> I tried to do some Donation to elFinder (nao-pon) through paypal but it does not go through please check it once.

I updated "Donate" section of https://studio-42.github.io/elFinder/ . Please send e-mail to me ( hypweb+elfinder@gmail.com ), If you got any problems yet.

**Comment by isreehari** [comment]
It worked. 


Thanks,
Hari

**Comment by nao-pon** [comment]
@isreehari I recived it. Thank you!

I fixed this issue. Please check with the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by isreehari** [comment]
@nao-pon oh yeah, now it's creating multi level directories but it's not solve the origin problem. Upload command ( cmd="upload") is not calling the create thumbnail command by default ( cmd ="tmb" ) for image uploads. Thumbnail creating command is issuing only when we refresh or reload the original image's folder ( if the user enabled the thumbnails in configuration file). 

![elfinderuploadimageissue](https://user-images.githubusercontent.com/3519250/40564049-c81e70a0-602c-11e8-8f78-f250bae76893.jpg)

**Comment by nao-pon** [comment]
@isreehari  Thumbnails are created according to the instructions of the client as necessary. That is the specification of elFinder. If you need to create thumbnails at the same time as uploading, you need to respond like the code you presented.

**Comment by isreehari** [comment]
But some people like me who are started to use the elFinder felt that the thumbnails will create automatically when we upload the image. Anyhow, thank you so much for your very quick support. It's very nice and best tools to use. All the best. 


Thanks,
Hari

**Comment by sashsvamir** [comment]
@isreehari Can i ask you, how you added ```public function preUpload()```?
There elfinder api allowing append pre upload action or you just inject execution this function to raw source?

**Comment by isreehari** [comment]
I did this long ago and need to check it.

Thanks,
Sree

Sent from my iPhone, please ignore if there are any typos.

On Jun 29, 2019, at 4:39 AM, Alexander Shchukin <notifications@github.com<mailto:notifications@github.com>> wrote:


@isreehari<https://github.com/isreehari> Can i ask you, how you added public function preUpload()?
There elfinder api allowing append pre upload action or you just inject execution this function to raw source?
