### ISSUE TITLE
locked file detecting bug

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2516]
![image](https://user-images.githubusercontent.com/18566890/40572639-b4fc9946-60ce-11e8-9a60-c0f953f13aa4.png)

try to create "forDemoUser" folder zip or any other archive.
That created file will be locked.
and unzip that archives. that created folders also locked.

![image](https://user-images.githubusercontent.com/18566890/40572672-a62022ac-60cf-11e8-8a3e-dacc0e16c563.png)

also if copy folder name "forDemoUser-_word here_" to where locked folder placed, that copied folder also locked.

![image](https://user-images.githubusercontent.com/18566890/40574787-8490cb74-60f6-11e8-8e02-2eb922a89138.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM This is an error of configuration of demo site. so I was fixed it. Thanks! 👍
