### ISSUE TITLE
FTP File not found

### ISSUE THREAD

**Issue by llovvoll** [Studio-42/elFinder#2518]
Dear teams,

I use FTP connection successfully and also have write permission, i can see all files and create a folder
However, File not found will appear when  download the file
Can't believe this is where the problem is?

My environment:
(A) Windows Server 2008 R2 + IIS7 + PHP7.2.6
(B) QNAP TS-431XU-RP

Connection method:
(A) <> IIS7+PHP <> elFinder_web <> FTP <> (B)

Hope can tell me where have error
Thanks you so much

		array(
		    'driver'        => 'FTP',
		    'host'          => '172.17.100.116',
				'alias'					=> 'Software Media Library',
		    'user'          => 'user',
		    'pass'          => 'user',
		    'port'          => '21',
		    'mode'          => 'passive',
		    'path'          => '/',
		    'timeout'       => '10',
				'defaults'   => array('read' => true, 'write' => false, 'locked' => true),
				'attributes'   => array(
			 array(
					 'pattern' => '/@Recycle/', // Dont write or delete to this and all subfolders
					 'read'  => false,
					 'write' => false,
					 'hidden' => true,
					 'locked' => false
				 ),
				 array(
						 'pattern' => '/@Recently-Snapshot/', // Dont write or delete to this and all subfolders
						 'read'  => false,
						 'write' => false,
						 'hidden' => true,
						 'locked' => false
					 )
	)
		)

**Comment by nao-pon** [comment]
@llovvoll Please enable "allow_url_fopen" in PHP or specify a writable directory in volume option "tempPath".

**Comment by llovvoll** [comment]
@nao-pon 

Thanks your reply   My php.ini "allow_url_fopen" it is enable now , but the problem did not improve
I also try to open the FTP account with maximum privileges , but no help T_T

**Comment by nao-pon** [comment]
@llovvoll Did you set a writable directory in volume option "tempPath"?

**Comment by llovvoll** [comment]
@nao-pon  Thanks you help !! The problem is solved after change "tmpPath"

**Comment by llovvoll** [comment]
I would like to ask what type of communication mode FTP is using.

I found that when downloading large files, Web server cpu will be used to 100%, and downloading files will fail

Is there a way for the Client to access the NAS directly via the web using ftp?

**Comment by nao-pon** [comment]
There is no function to communicate directly with FTP in elFinder clients.

On the Windows server, since the communication time with the outside is included in PHP execution time, it may be time out. Please retry with change the "_fopen ()" function of "elFinderVolumeFTP.class.php L. 1046" as follows.

```php
	protected function _fopen($path, $mode='rb') {
		// try ftp stream wrapper
		if ($this->options['mode'] === 'passive' && ini_get('allow_url_fopen')) {
			$url = ($this->isFTPS? 'ftps' : 'ftp').'://'.$this->options['user'].':'.$this->options['pass'].'@'.$this->options['host'].':'.$this->options['port'].$path;
			if (strtolower($mode[0]) === 'w') {
				$context = stream_context_create(array('ftp' => array('overwrite' => true)));
				$fp = fopen($url, $mode, false, $context);
			} else {
				$fp = fopen($url, $mode);
			}
			if ($fp) {
				return $fp;
			}
		}
		
		if ($this->tmp) {
			$local = $this->getTempFile($path);
			$fp = fopen($local, 'wb');
			$ret = ftp_nb_fget($this->connect, $fp, $path, FTP_BINARY);
			while ($ret === FTP_MOREDATA) {
				elFinder::extendTimeLimit();
				$ret = ftp_nb_continue($this->connect);
			}
			if ($ret === FTP_FINISHED) {
				return $fp;
			}
			fclose($fp);
			is_file($local) && unlink($local);
		}
		
		return false;
	}
```

**Comment by llovvoll** [comment]
@nao-pon Thanks you so much :)

**Comment by nao-pon** [comment]
@llovvoll Is the problem solved?

**Comment by llovvoll** [comment]
@nao-pon 
The current test result is failed.

**Comment by nao-pon** [comment]
@llovvoll It’s unfortunate. I do not know much about Windows server. Please let me know if you notice something.

**Comment by nao-pon** [comment]
@llovvoll There is a bug in the `_fopen()` function shown above. Please try with the following code.
```php
	protected function _fopen($path, $mode='rb') {
		// try ftp stream wrapper
		if ($this->options['mode'] === 'passive' && ini_get('allow_url_fopen')) {
			$url = ($this->isFTPS? 'ftps' : 'ftp').'://'.$this->options['user'].':'.$this->options['pass'].'@'.$this->options['host'].':'.$this->options['port'].$path;
			if (strtolower($mode[0]) === 'w') {
				$context = stream_context_create(array('ftp' => array('overwrite' => true)));
				$fp = fopen($url, $mode, false, $context);
			} else {
				$fp = fopen($url, $mode);
			}
			if ($fp) {
				return $fp;
			}
		}
		
		if ($this->tmp) {
			$local = $this->getTempFile($path);
			$fp = fopen($local, 'wb');
			$ret = ftp_nb_fget($this->connect, $fp, $path, FTP_BINARY);
			while ($ret === FTP_MOREDATA) {
				elFinder::extendTimeLimit();
				$ret = ftp_nb_continue($this->connect);
			}
			if ($ret === FTP_FINISHED) {
				fclose($fp);
				$fp = fopen($local, $mode);
				return $fp;
			}
			fclose($fp);
			is_file($local) && unlink($local);
		}
		
		return false;
	}
```

**Comment by mchupp** [comment]
Your last change fixed my issue on Windows Server 2008 R2. Thank you!
