### ISSUE TITLE
migration to java

### ISSUE THREAD

**Issue by curiousPup** [Studio-42/elFinder#2520]
Is there a way to migrate it from php to Java?

**Comment by simialbi** [comment]
You can find alternative connectors etc. here:
[https://github.com/Studio-42/elFinder/wiki/3rd-party-connectors%2C-plugins%2C-modules](https://github.com/Studio-42/elFinder/wiki/3rd-party-connectors%2C-plugins%2C-modules)

**Comment by nao-pon** [comment]
@curiousPup Currently, there are no developers of Java, so there is no plan to officially support it.

**Comment by curiousPup** [comment]
Thanks @nao-pon 
@simialbi thanks but do you have or know of some user guide for these connectors ?
