### ISSUE TITLE
how to enable Sort, auto reload or sync and list view?

### ISSUE THREAD

**Issue by richard100589** [Studio-42/elFinder#2524]
![untitled](https://user-images.githubusercontent.com/39425691/40837947-a6349558-65ce-11e8-8efa-8b1fbea4cf6b.png)

thanks in advance

**Comment by nao-pon** [comment]
@richard100589 Please check tha Wiki.

- [sortType](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#sorttype)
- [sortOrder](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#sortorder)
- [sortStickFolders](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#sortstickfolders)
- [sync](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#sync)

And that extra icon of view command is new feature of elFinder >= 2.1.39. Please wait new version or try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).
