### ISSUE TITLE
creating temp file location (elfinder/php/.tmp)

### ISSUE THREAD

**Issue by richard100589** [Studio-42/elFinder#2527]
![capture](https://user-images.githubusercontent.com/39425691/40907507-a8bc767a-6816-11e8-90ba-403b1c18662e.PNG)
![capture2](https://user-images.githubusercontent.com/39425691/40907544-c8744c5e-6816-11e8-9bb2-bd1238016727.PNG)

way too many is this normal?

**Comment by nao-pon** [comment]
@richard100589 These files are connection flag files. It is normal if there is no old timestamp file. See the [wiki (Connector main option "connectionFlagsPath")](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#connectionflagspath--2129).
