### ISSUE TITLE
Drag and drop of folder is not working in internet explorer 11

### ISSUE THREAD

**Issue by alexgiovi** [Studio-42/elFinder#2528]
In Internet Explorer 11. 48.17134.0, when I'm trying to drag and drop a folder from my desktop inside   elfinder, I receive an error message, this error doesn't happen when I'm using other browsers (Firefox, Edge, Chrome).
I've been trying with single files or with a selection of multiple files, and this errore message isn't displayed, it only happens when I'm dragging a folder.
I've tryed in your installation: (https://studio-42.github.io/elFinder/#elf_l2_Lw)

### **Drag and Drop image**
![drag_drop](https://user-images.githubusercontent.com/39825582/40910792-5e130978-67ed-11e8-8558-37286fa18186.png)

### **Error Message image**
![error_message](https://user-images.githubusercontent.com/39825582/40910924-b06c4838-67ed-11e8-9691-fb0caa40c6ab.png)

**Comment by nao-pon** [comment]
@alexgiovi IE 11 does not support folder uploading. I will modify it so that I issue the appropriate error message.
