### ISSUE TITLE
Button Upload folder missing in Internet Explorer 11

### ISSUE THREAD

**Issue by alexgiovi** [Studio-42/elFinder#2529]
In Internet Explorer 11. 48.17134.0, when clicking the upload button, in the modal window that is opened, the button of upload folder is missing.
This button is present in Chrome,Edge and Firefox.
Maybe this behavior could be coherent if the bug #2528 was notorious.
Obviously, dragging a folder inside the box, I'll have the same error that is quoted in bug #2528.

###  **Cliccking button of Upload Internet Explorer**
![immagine](https://user-images.githubusercontent.com/39825582/40911909-6588fef8-67f0-11e8-92ae-8428a8adace8.png)

###  **Cliccking button of Upload Firefox**
![immagine](https://user-images.githubusercontent.com/39825582/40912790-e8fd073c-67f2-11e8-95b8-2439910f4655.png)

**Comment by nao-pon** [comment]
IE 11 does not support folder uploading.
