### ISSUE TITLE
Option to set default action when double clicking a file

### ISSUE THREAD

**Issue by bawNg** [Studio-42/elFinder#253]
I find the default action that opens files in a new window when double clicking on them rather ugly and useless. 

Personally I would suggest making preview the default action for all supported files, but an option to be able to set it to edit or preview would be very useful.

**Comment by biswajit-paul** [comment]
How can I make "custom command" as default on dblclick on files only while still opening directories? Please help me where to update with the newest "**File Manager Plugin For Wordpress v7.0**" plugin code.
