### ISSUE TITLE
Full screen button missing after resizing the screen

### ISSUE THREAD

**Issue by alexgiovi** [Studio-42/elFinder#2530]
The Full screeen button is missing after you re-minimize the window.
When we click the _full screen_ button  and then we click on the _Reinstate button_, the _full screen_ button is missing and _**instead we can see the home button.**_

### **Start View** 
![immagine](https://user-images.githubusercontent.com/39825582/40913127-df6f6c4a-67f3-11e8-8df4-7bba48eded65.png)

### **Full Screen** 

![immagine](https://user-images.githubusercontent.com/39825582/40913179-102ca848-67f4-11e8-8bdc-9c35cd6f1640.png)

### **Normal view after the full screen** 
![immagine](https://user-images.githubusercontent.com/39825582/40913738-cd250796-67f5-11e8-95e3-7b1b5a8263c4.png)

**Comment by nao-pon** [comment]
@alexgiovi Thanks! 👍
