### ISSUE TITLE
Drag-drop folder sanitize problem

### ISSUE THREAD

**Issue by aktolu** [Studio-42/elFinder#2532]
I have a problem on drag-drop multi-level hierarchical folders and files.

example folder stucture:

öfolder/
öfolder/öfile.jpg

After drag-drop on server:
öfolder/ofile.jpg
// filename right but folder name is not have sanitize

Why folders not have saniteze?

My bind:
```php
'bind' => array(
	'mkdir.pre mkfile.pre rename.pre' => array(
		'Plugin.Sanitizer.cmdPreprocess',
	),
	'upload.presave' => array(
		'Plugin.Sanitizer.onUpLoadPreSave',
	)
),
```
Thank you

**Comment by nao-pon** [comment]
@aktolu This is a bug of  plugins (Sanitizer and Normalizer). So I'll fix it.

Thanks! 👍

**Comment by nao-pon** [comment]
@aktolu I done. Please change your bind to more correctly.

```php
'bind' => array(
	'upload.pre mkdir.pre mkfile.pre rename.pre archive.pre ls.pre' => array(
		'Plugin.Sanitizer.cmdPreprocess',
	),
	'upload.presave' => array(
		'Plugin.Sanitizer.onUpLoadPreSave',
	)
),
```

**Comment by aktolu** [comment]
@nao-pon THANK YOU VERY MUCH.

I was update Sanitizer and Normalizer plugins, after change yor say binds and works fine.

Cheers!
