### ISSUE TITLE
edit .htaccess file

### ISSUE THREAD

**Issue by camaran** [Studio-42/elFinder#2536]
i cannot edit .htaccess file

**Comment by nao-pon** [comment]
@camaran For security reasons, handling of files beginning with "." (dot) is prohibited by default setting.

See,
- acceptedName : https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#acceptedname
- accessControl :  https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#accesscontrol
    - https://github.com/Studio-42/elFinder/blob/master/php/connector.minimal.php-dist#L84-L102
