### ISSUE TITLE
FTP driver, support for more FTP servers

### ISSUE THREAD

**Issue by rufdev** [Studio-42/elFinder#254]
is their something wrong with my ftp connection?..i can open the root directory but when i access the folders it gives an error (Unable to open "Folder" Folder not found)..

array(
		 	'driver' => 'FTP',
		 	'host' => '172.16.2.30',
		 	'user' => 'anonymous',
		 	'pass' => 'xxxxx',
		 	'path' => '/mnt/array1/eCabinet',
		 'tmpPath' => '../files/ftp',
		 	'utf8fix' => true,
		 	'attributes' => array(
		 		array(
		 			'pattern' => '/^\/\./',
		  		'read' => true,
		 			'write' => true,
		 			'hidden' => true,
		 			'locked' => true
		 		),
		 	)
		 ),

**Comment by troex** [comment]
Closed due to inactivity
