### ISSUE TITLE
stopped generating preview images

### ISSUE THREAD

**Issue by standus** [Studio-42/elFinder#2540]
I see that EF stopped generate preview images.
Only old images created in the past are exists. New are like default icon only.
I checked function createTmb in elFinderVolumeDriver
and
imagick throw error: NoDecodeDelegateForThisImageFormat `JPEG' @ error/constitute.c/ReadImage/501
But nowhere is this information.
I disabled imagick and EF uses gd but preview images are created.

**Comment by nao-pon** [comment]
@standus Probably this is not an issue with elFinder. Please check ImageMagick's configure.

cf. https://github.com/ImageMagick/ImageMagick/issues/192

**Comment by standus** [comment]
i mean if is possible to do some fallback when one image procesor will fail 
it will try process with second?

---------- Původní zpráva ----------
Od: Naoki Sawada 
Datum: 9. 6. 2018 v 09:51:47
Předmět: Re: [Studio-42/elFinder] stopped generating preview images (#2540)


@standus(https://github.com/standus) Probably this is not an issue with 
elFinder. Please check ImageMagick's configure.

cf. ImageMagick/ImageMagick#192
(https://github.com/ImageMagick/ImageMagick/issues/192)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
(https://github.com/Studio-42/elFinder/issues/2540#issuecomment-395949154), 
or mute the thread

**Comment by nao-pon** [comment]
@standus What about commit 50fa81456475e71f2f5e254e5ae82a6a25d1088a ? Does it solve your case?
