### ISSUE TITLE
[cmd:rm] to be able to customize the action of to put in the trash

### ISSUE THREAD

**Issue by hardiktailored** [Studio-42/elFinder#2541]
"Into Trash" removes file/folder from main volume and creates full tree of the path deleted file or folder. And when you remove parent folder after deleting sub folder, it creates another copy of folder and restoring also creates same new folder to the main volume, which is incorrect.

Solution is show only file or folder deleted in Trash volume like Windows and no sub folder or files should be accessible.

I see "toTrash function" in JS that is creating parent directories and paste, so is there any way to override Trash functionality to just create file/folder deleted directly on Trash volume and update elfinder_file table?

I am using this Laravel package: https://github.com/barryvdh/laravel-elfinder

**Comment by nao-pon** [comment]
@hardiktailored Since elFinder does not have a database as a standard, this behavior is the specification at present. However, I think that it is a good idea to be able to customize the action of to put in the trash, so I will extend the client side of elFinder to be able to that.

Thanks! 👍
