### ISSUE TITLE
Error upload file

### ISSUE THREAD

**Issue by sclolo** [Studio-42/elFinder#2547]
Hello. I get "errUpload" and "errUploadNoFiles" when i try to upload some files. I use Symfony 4 and all work fine except upload. I take the same configuration from my symfony 3 website where all work fine.

Thank's for your help.
Best regards.

{"error":["errUpload","errUploadNoFiles"],"debug":{"connector":"php","phpver":"7.1.17","time":0.007328987121582031,"memory":"3964Kb \/ 1879Kb \/ 512M","upload":"","volumes":[{"id":"l1_","name":"localfilesystem","mimeDetect":"finfo","imgLib":"imagick"}],"mountErrors":[],"phpErrors":[]}}

**Comment by nao-pon** [comment]
@sclolo Please check the setting related to file upload of Symfony 4 and PHP. If there is no problem with Symfony 3, there is something wrong with those settings.
