### ISSUE TITLE
It freezes while creating and extracting a zip archive 

### ISSUE THREAD

**Issue by unigia** [Studio-42/elFinder#2549]
Hi, 
when you try to creating or extracting a folder with a large number of files, elfinder freezes. 
I have uploaded on night build in your volume "Test Here" a file named "randfile.zip", that contains 500 files of 1kb,  that you should use for replicate the issue.
The problem is that zip commands write in a stout is very large number of row, with -q added to arguments work properly.

**Comment by arubalucalasagni** [comment]
This happens  only with the .zip archives with a lot of files. 
![image](https://user-images.githubusercontent.com/24244107/41415005-cdb5b454-6fe7-11e8-81e4-bc26d6354b7d.png)

after 4 minutes...

![image](https://user-images.githubusercontent.com/24244107/41415205-5029f6b6-6fe8-11e8-9249-4f5ce5e70831.png)

**Comment by nao-pon** [comment]
@unigia , @arubalucalasagni Thanks! 👍
