### ISSUE TITLE
elfinder crashing when more images are uploaded

### ISSUE THREAD

**Issue by gadangmadhulika** [Studio-42/elFinder#2550]
Hi @nao-pon 
In elFinder, if we upload high resolution images(more than 20 images) then the performance of elfinder is very very slow and features(like GetInfo) is taking more time to load.
Appreciate your quick response,
Thank you.

**Comment by gadangmadhulika** [comment]
Hi @nao-pon 
I tried by increasing memory limit in php.ini file but no improvement.

**Comment by nao-pon** [comment]
@gadangmadhulika I tested it, uploading 30 images of 4592 x 3056 pixels (total size 139 MB) took about 1 minute. It will vary depending on server specifications and network environment, but I think that it is rare to crash on the way. What exactly is your problem?

**Comment by gadangmadhulika** [comment]
Hi @nao-pon 
I uploaded 78 images of 3840x2160 pixels (total size 157.29 MB), then it is very slow and it is not responding.Even the scroll bar is not responding,Please see the screencast below,
https://www.screencast.com/t/2xkeLSD3BF.

**Comment by gadangmadhulika** [comment]
Hi @nao-pon 
I tried in Firefox its working good but its crashing on chrome browser even after clearing the browser's cache.

**Comment by nao-pon** [comment]
@gadangmadhulika Is it same on the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip) too?

**Comment by nao-pon** [comment]
@gadangmadhulika Does Chrome's browser extension have any impact?

**Comment by gadangmadhulika** [comment]
@nao-pon, I dont have any extensions linked to my browser.

**Comment by nao-pon** [comment]
@gadangmadhulika I created [a sample folder on the demo site](https://studio-42.github.io/elFinder/#elf_l1_SW1hZ2VzL0hpZ2hSZXNvSW1ncw). There is no problem in my environment ( Chrome: 67.0.3396.87 (Official Build) (64 bit/Windows 10)).

- https://studio-42.github.io/elFinder/#elf_l1_SW1hZ2VzL0hpZ2hSZXNvSW1ncw

**Comment by gadangmadhulika** [comment]
@nao-pon  Okay thanks for your quick response and your support. Iam having same issue only in chrome in my environment (Chrome:Version 67.0.3396.87 (Official Build) (64-bit)).

**Comment by nao-pon** [comment]
@gadangmadhulika If you have same problem in our demo site, I guess your PC has any problems. Please try to check with other any PC.
