### ISSUE TITLE
Ability to control edit dialog size and position

### ISSUE THREAD

**Issue by tristanleboss** [Studio-42/elFinder#2551]
I think it would be great to allow for more control over the edit dialog size and position.

Indeed, I would like to customize the pixel location (top and left) of the edit dialog along with its size (width and height) and, of course, to have eveyrhing updatable when the user resize the editor even if a dialog is active.

I think it would be great to add an event which receives the size and position as an array before they are applied to the dialog. I managed to change the dialog width using the "resize" event but changing its position is  a no-go: I tried to edit the css `top` and `left` properties but it seems something is updating them afterwards?!

**Comment by nao-pon** [comment]
@tristanleboss Please check the setting related to file upload of Symfony 4 and PHP. If there is no problem with Symfony 3, there is something wrong with those settings.

**Comment by nao-pon** [comment]
@tristanleboss I done.

Example: Make the edit dialog the same size as the elFinder node

To define with `handlers.dialogopen: [Fn]` of the client setting or `elFinderInstance.bind('dialogopen', [Fn])`.

```javascript
handlers : {
    dialogopen : function(e, fm) {
        var dialog = e.data.dialog,
            elfNode;
        if (dialog.hasClass('elfinder-dialog-edit')) {
            elfNode = fm.getUI();
            dialog.css({
                top: 0,
                left: 0,
                width: elfNode.width(),
                height: elfNode.height()
            }).trigger('resize', { init : true });
        }
    }
}
```

Thanks! 👍
