### ISSUE TITLE
Preventing Deleting/Renaming of Files via Right Click

### ISSUE THREAD

**Issue by ntrimg** [Studio-42/elFinder#2554]
I'm trying to prevent users from deleting or renaming files.  I've modified the toolbar to remove those options, but I noticed that people can simply right click on the file and delete it or rename it.  Is there a way to prevent this from happening?

**Comment by nao-pon** [comment]
@ntrimg Because suppressing by UI option is apparent, please use the connector side option to invalidate the function itself.

If it is an [official PHP connector](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#disabled) ...
```php
'disabled' => array('rm', 'rename'),
```''

**Comment by nao-pon** [comment]
@ntrimg These are connector side options. Please set it at the connector side.

- https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#disabled
