### ISSUE TITLE
Duplication of xhtml files - Wrong Renaming 

### ISSUE THREAD

**Issue by alexgiovi** [Studio-42/elFinder#2555]
As shown in the picture, if you duplicate an xtml file (ex. file.xhtml), the duplicated file would be named file.xhtml copy 1 instead of: file copy1.xhtml as every other file extension.

### **DUPLICATION**
![immagine](https://user-images.githubusercontent.com/39825582/41598737-620aa67c-73d1-11e8-98e2-2fd7ee502ed0.png)

**Comment by nao-pon** [comment]
@alexgiovi Currently, elFinder detect up to 4 characters as the file extension, So I'll change it to 10 characters.

Thanks! 👍
