### ISSUE TITLE
tiny bugs

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2560]
1) open text editor(or any other windows) & position like this
![image](https://user-images.githubusercontent.com/18566890/41816816-22fef7e2-77ac-11e8-8051-bf3d37cd53e0.png)

2) Minimize window
![image](https://user-images.githubusercontent.com/18566890/41816817-30605854-77ac-11e8-8757-572ed310d352.png)

3) full-screen
![image](https://user-images.githubusercontent.com/18566890/41816819-388575f0-77ac-11e8-8c50-a32c0a1aef8d.png)

4) maximize window
![image](https://user-images.githubusercontent.com/18566890/41816823-4be5ed8c-77ac-11e8-8528-aa983ca70082.png)

You can see what's wrong.
Also this happen bottom margin & right margin

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Thank you for the detailed reproduction method!
