### ISSUE TITLE
customData is not passed to the connector script when upload file

### ISSUE THREAD

**Issue by wanminxg** [Studio-42/elFinder#2561]
I use customData to pass information. All requests are normal except uploading files.When upload file, the customData is not passsed to the connector script.
I user elfinder 2.1.37

**Comment by nao-pon** [comment]
@wanminxg I checked with `$_REQUEST`. That was no problem.

**Comment by wanminxg** [comment]
Thanks! I have found my problem.The first time elfinder sents the data was with the POST method, and later with the GET method,  which caused the data not being available in $_POST.
