### ISSUE TITLE
[cmd:empty] change title "Empty the folder" to "Delete All" in the trash volume

### ISSUE THREAD

**Issue by hardiktailored** [Studio-42/elFinder#2562]
Is it possible to have "Delete All" option in Trash volume?

**Comment by nao-pon** [comment]
@hardiktailored Is that about "Empty the folder"? If right, please add 'empty' to roots option [`disabled`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#disabled).

**Comment by nao-pon** [comment]
Sorry, I misread the question. I will check the source code.

**Comment by hardiktailored** [comment]
Okay, understood. Made copy of "Empty" cmd and then give title we want to the new command. And then map empty to the new command. Cool. Thanks.
