### ISSUE TITLE
zoho editor - save not work properly depend of php version

### ISSUE THREAD

**Issue by jacceko** [Studio-42/elFinder#2564]
Zoho editor work in php 5.4 ok with all file formats .doc, docx, .xls, .xlsx,
but with  php 5.6, 7.0, 7.1, 7.2 when I save .docx or .xlsx - it make some big file which is not properly saved office files, (but old word file .doc is saved OK)

**Comment by nao-pon** [comment]
@jacceko The Zoho editor plugin receives uploads from the Zoho server, assigns the data to variables, and processes them. It is probably due to differences in upload limit or memory limit, not due to server version differences.

Please check those settings on your server.

**Comment by jacceko** [comment]
Memory limit and upload limit - is the same it is the same server with few instalation of php and same user.ini with custom memory limit and upload limit, but I investigate a little more and find out that is not problem with saving file but with reading.  

Just after saving from in php 5.4 (ok) I change to php 7.0 and then I see that the same file is not possible to read. The same file is possible to read or not depend of php version.  Maybe you know that it can be, because after change to 7.0 icon of the file is different - file is still .docx but icon from typical .docx is changed to .bin ?? (and icony only changed with file saved by zoho, copy of the same file not resaved with zoho has normal icon). User writes on server for both files are the same ?

**Comment by nao-pon** [comment]
@jacceko It seems that there is a problem with detection of MIME-Type. In PHP 7, when you hover over the file type of the file information dialog of the bin icon, the MIME-Type is displayed on the tooltip. What is that MIME-Type?

**Comment by jacceko** [comment]
In php 7 (5.6 too) - file type is displayed: Application 
but on second file with the same extension is displayed: Microsoft Word Document (this not resaved by Zoho)

How it recognize mime type if not base of extension ?

**Comment by nao-pon** [comment]
@jacceko I think that this problem was fixed.

Note: elFinder detects MIME-Type by file contents as much as possible for security reasons. If you want to detect MIME-Type with only the file extension, set "[mimeDetect](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#mimeDetect)" of the connector roots option to "internal".

Thanks! 👍
