### ISSUE TITLE
Additions to image edit: sharpen, auto tone, brightness, contrast

### ISSUE THREAD

**Issue by nmpetkov** [Studio-42/elFinder#2565]
In resize dialog we now have:
resize, crop, rotate

It will be very useful if we have also:
sharpen
brightness, contrast
auto tone, auto contrast (like in Photoshop)

**Comment by nao-pon** [comment]
@nmpetkov elFinder can incorporate any editor as a plug-in. Pixlr editor, Criative Cloud editor, etc. are already installed. However, since they work with external services, they can not be used to edit confidential data, I know. If it is an editor working with JavaScript, so that is not send data to externally. Please let us know if you have any editors you recommend.

Thanks!

**Comment by nmpetkov** [comment]
http://camanjs.com/ looks like a suitable library, but the project is not actively developed in last few years.
http://fabricjs.com/ seems actively developed project.

**Comment by nao-pon** [comment]
I found [tui.image-editor](https://github.com/nhnent/tui.image-editor). it looks like a good editor, so i was started implementing it.

**Comment by nao-pon** [comment]
@nmpetkov Thanks! 👍

**Comment by nmpetkov** [comment]
Thank you @nao-pon I will test it. Looks really nice!!

**Comment by masihfathi** [comment]
how to use tui.image-editor in the elfinder config?

**Comment by nao-pon** [comment]
@masihfathi Please load "js/extras/editors.default.min.js". It is designed to load by default.

- https://github.com/Studio-42/elFinder/blob/master/main.default.js#L92
or
- https://github.com/Studio-42/elFinder/blob/master/elfinder.legacy.html#L31

**Comment by masihfathi** [comment]
thanks, my issue solved with your help
and thanks again for adding this photo editor.

**Comment by masihfathi** [comment]
one issue is files permitted to edited once and I can not edit a file multiple in the file manager, i try to edit multiple time but changes not applied while thumbnails affected by changes, 
is this behavior normal?
or is it related to my elfinder config?

**Comment by nao-pon** [comment]
@nmpetkov Multiple edits are fine. Is the impact of browser caching?

**Comment by masihfathi** [comment]
yes, you are right. i check cache issue; it was relate to cloud CDN caching level.
