### ISSUE TITLE
ms office viewer online without account

### ISSUE THREAD

**Issue by jacceko** [Studio-42/elFinder#2567]
Maybe it is easy to add Ms Office viewer - it is free and without ms account - send by url similar to zoho and google:
Docs: https://products.office.com/en-us/office-online/view-office-documents-online

Sample: https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fcalibre-ebook.com%2Fdownloads%2Fdemos%2Fdemo.docx

**Comment by jacceko** [comment]
I download newest version (mime work ok for zoho, for google viewer work all type of file with application/postscript too - .ai and .eps now work), but MS Office Viewer not work.

When I put both googleDocsMimes with all options and officeOnlineMimes with all options  - work only Google. When I put  googleDocsMimes empty, and officeOnlineMimes full options from example, it not work,  It not show progress circle even! 
(to be sure that is not problem of browser cache I use another browser and for test I change php version)

I put in my main.js:
 googleDocsMimes :['application/pdf', 'image/tiff', 'application/vnd.ms-office', 'application/msword', 'application/vnd.ms-word', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/postscript'],
 officeOnlineMimes : ['application/msword', 'application/vnd.ms-word', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
i try too:
 googleDocsMimes : [],
officeOnlineMimes : ['application/msword', 'application/vnd.ms-word', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
					
I try to put it direct to elFinder.options.js but now luck too.

**Comment by nao-pon** [comment]
@jacceko Are you trying the [Nightly Build](https://github.com/Studio-42/elFinder/archive/2.1.zip)? How about on [our demo site](https://studio-42.github.io/elFinder/#elf_l1_TUlNRS10eXBlcw)?

**Comment by jacceko** [comment]
Thanks nightly build - OK !

**Comment by nihal1234ouali** [comment]
hello jacceko,

can you help me and tell me how to preview an excel file please? i want to use office viewer

**Comment by SophieRoyal** [comment]
> 
> 
> Thanks nightly build - OK - my fault
> Office Viewer work excellent - faster then google, big thanks :-)

I need help, how to show office. My version is the latest 
`quicklook: {googleDocsMimes : ['application/pdf',..}`.But it doesn't show. Error code:`An error occurred
We're sorry, but for some reason we can't open this for you.`
