### ISSUE TITLE
images: open one format save to another

### ISSUE THREAD

**Issue by jacceko** [Studio-42/elFinder#2568]
ElFinder has good support for image files, but limited file types.
I investigate something more - it will be very useful to open one file and save it with another extension - because some editors open some files but not always save it and sometimes save to more then format then it is possible to open.

For now we have:
Pixlr: jpg, png (but is possible .gif but readonly, save to .jpg, .png)
Pixlr: jpg (but is possible png maybe add it, and possible gif read only, save to  .jpg . png, .bmp, .tiff)
Creative Cloud: jpg, png (but possible to add.gif and .svg read only - save to .png, .jpg,)

**Comment by nao-pon** [comment]
@jacceko Current elFinder does not support changing file types when editing files. It is necessary to take care not to make it a security hole. I will start to think about its specifications and implementation.

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM I'd like to change the file type conversion to the Online-Convert of the edit plugin.

For the integration of external services, i will add the Integrations tab in the help dialog and enumerate it there.

Thanks!

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon 
Is gh-page disabled pixlr editor?

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM No, There aren't disabled. But there aren't list up on some devices that hasn't the Flash plugin.

**Comment by nao-pon** [comment]
This request is likely to be solved by extending the "SaveAs" function, so I started this.

**Comment by nao-pon** [comment]
@jacceko , @CodeLyokoXtEAM Thanks! 👍
