### ISSUE TITLE
one click format converter of images, docs, music, video - who want?

### ISSUE THREAD

**Issue by jacceko** [Studio-42/elFinder#2570]
It will be useful to convert one file type to another by one click in ElFinder menu.
It is easy to convert many files by: https://www.online-convert.com/
It support most of images, document, audio and video at it has API.

Api: https://apiv2.online-convert.com/,  conver remote; https://apiv2.online-convert.com/docs/getting_started/job_remote_file.html, convert upload:  https://apiv2.online-convert.com/docs/getting_started/job_uploading_file.html

It has additionally php class: https://github.com/onlineconvert/onlineconvert-api-sdk-php

It is free with big free limit:  30 minutes conversion by website a day and max 100M one file it is enough to convert many things a day.

Additionally is many useful functions:

- Image: crop, normalize, deskew, sharpen, antialias, remove background, color to (gray, monochrome, negate, etc.), 
- Audio: crop, normalize
- Video: frame frate, cut, change audio
- Documents: ocr

**Comment by jacceko** [comment]
@nmpetkov ask about some image enhancement tools too, this will be possible with this converter.

**Comment by nao-pon** [comment]
The online-convert.com has many options, and it takes a lot of time to use the API. It is easy to create a command that opens a new tab with content URL, how about it?

**Comment by CodeLyokoXtEAM** [comment]
@nao-pon how about using iframe?

**Comment by jacceko** [comment]
My idea was such, if press right button on for example file.jpg in context memu I have: Convert - and submenu for ex: .bmp, gif, png, bmp, tiff.  I click one of it format and conversion is made.
By this simplest api below if possible (first or second - by upload or by url):
https://apiv2.online-convert.com/docs/getting_started/job_remote_file.html, 
https://apiv2.online-convert.com/docs/getting_started/job_uploading_file.html
Last option will be: Custom (additionally adjustment) and then when you press custom then it will be open new tab as suggest @nao-pon or iframe like suggest @CodeLyokoXtEAM where you adjust additional convert param like size of image, color etc.
Is it possible ?

**Comment by jacceko** [comment]
It will be only 3 class for converts the "format to" (they are short enough for submenu):
**images**: bmp eps gif exr ico jpg jpeg png svg tga tiff wbmp webp + custom
**document**: doc docx sxw html odt pdf ppt pptx rtf txt + custom
**audio**: acc aiff flac m4a mmf mp3 ogg opus wav wma + custom
I think that we can ommit: archive converter, ebook converter, webservice or hash generator
video - Custom option only, because too big files etc.

**I can prepare exact matrix which format** can convert to which format @nao-pon

**Comment by nao-pon** [comment]
I have created a test cases that does not use the API.

One is an implementation as an editing plugin and the other is an implementation of an independent command.
Edit plugin opens to iframe, command opens online-convert.com on tab.

You can try them on [my developer site](https://hypweb.net/elFinder-nightly/demo/develop/#elf_l2_Lw).

**Comment by jacceko** [comment]
Your are fast :-) @nao-pon 
- I only can't see anything on link to "my developer site" I see only: aaa
nothing more (in source is many scripts etc) but on screen (html) is only: aaa
Then I can't try your solution

**Comment by nao-pon** [comment]
Sorry, please scroll down to find elFinder manager.

**Comment by jacceko** [comment]
Iframe is better for sure, but from me is the most important is that file will be saved to ElFinder, but not downloaded to disk. I think about usability for user, are you look already at this simple useage too for direct conversion: https://apiv2.online-convert.com/docs/getting_started/job_remote_file.html 

some onlineconverter bug additionally:
Online converter has problem with url with spaces -in this example normally when click convert work, but when go to small link: for ex. change setting of jpg - then special character for space is changed to white space and then not work when try to convert.

**Comment by jacceko** [comment]
Thanks a lot for your work :-) @nao-pon

**Comment by nao-pon** [comment]
The problem of the space character of file name is a bug of online-convert.com. I reported this issue to support.

Regarding API usage, I will consider how to implement polling.

**Comment by jacceko** [comment]
:-)

**Comment by jacceko** [comment]
I am happy to see, on dev site working example with saving to ElFinder :-)

**Comment by nao-pon** [comment]
Currently I'm developping in "https://github.com/nao-pon/elFinder/tree/onlineconvert".

**Comment by nao-pon** [comment]
@jacceko , @CodeLyokoXtEAM Thanks! 👍

**Comment by CodeLyokoXtEAM** [comment]
I think this link must be correct
https://github.com/Studio-42/elFinder/blob/master/php/connector.minimal.php-dist#L79

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM I [fixed](https://github.com/Studio-42/elFinder/commit/4be3d67342ef796437d64fba3dc48c9a3de723f1) it. Thank you! 👍
