### ISSUE TITLE
Code to get hash path is wrong on wiki page

### ISSUE THREAD

**Issue by rfiedler** [Studio-42/elFinder#2572]
I´m using elfinder  Version 2.1.38 (2.1-src Nightly: 92bd133) (2018-05-15)

Wiki´s page [Getting encoded hash from the path](https://github.com/Studio-42/elFinder/wiki/Getting-encoded-hash-from-the-path) has the example code : 

```
PHP

$volumeId = 'l1_';
$path = 'path/to/target'; // without root path
//$path = 'path\\to\\target'; // use \ on windows server
$hash = $volumeId . rtrim(strtr(base64_encode($path), '+/=', '-_.'), '.');
```

Filling the variables with my values:

```
PHP

$volumeId = 'l1_';
$path = '924433/2018/07';  
$hash = $volumeId . rtrim(strtr(base64_encode($path), '+/=', '-_.'), '.');
```

Only $path has change to **924433/2018/07**.
That code return this hash : **l1_OTI0NDMzLzIwMTgvMDc**

But accessing the file manager from my browser the hash for the same path **(924433/2018/07)** is **l1_MjAxOC8wNw**

See the image below
![elfinder01](https://user-images.githubusercontent.com/1020057/42293105-fd697200-7fad-11e8-891d-130ce061518f.JPG)

I believe that example is wrong. What the correct way to get path hash ?

**Comment by nao-pon** [comment]
@rfiedler "$path" is relative from the root path.

```php
<?php
$volumeId = 'l1_';
$path = '2018/07'; // without root path
$hash = $volumeId . rtrim(strtr(base64_encode($path), '+/=', '-_.'), '.');
echo $hash;
```

`l1_MjAxOC8wNw`

**Comment by rfiedler** [comment]
Structure is **/uploads/924433/2018/07** 

I thought **uploads** was the root folder

THANKS !!!!!!
