### ISSUE TITLE
simple autocad/design/architect file viewer

### ISSUE THREAD

**Issue by jacceko** [Studio-42/elFinder#2575]
Maybe you can add simple autocad/design/architect viewer - it is very simple
Files: DWG, DXF, DWF, HPGL, PLT, SPL; STEP STP, IGES IGS, SAT, CGM, SVG,  CGM, EMF, WMF, 

Sample code:
`<iframe src="https://sharecad.org/cadframe/load?url=http://www.cadsofttools.com/dwgviewer/floorplan.dwg" scrolling="no"></iframe>`
Simple api: http://beta.sharecad.org/pl/DWGOnlinePlugin
More info: http://beta.sharecad.org/

**Comment by nao-pon** [comment]
@jacceko Thanks! 👍
