### ISSUE TITLE
Triggering file overwrite prompt when drag and drop file (upload) onto el finder file manager

### ISSUE THREAD

**Issue by T0nyKo** [Studio-42/elFinder#2578]
Right now, the file overwrite prompt executes when i copy and paste a file from my desktop into elfinder, but will not prompt overwrite if i drag and drop the file from my desktop to el finder. I was wondering if anyone has gotten this to work. I'm using the elfinder.full.js library and calling the functions from javascript on my aspx page. 
![elfinder](https://user-images.githubusercontent.com/31359386/42459720-20522e28-8351-11e8-9ae3-69a5352daf16.JPG)

Any help or guidance would be greatly appreciated. 
Best Regards,
Tony

**Comment by nao-pon** [comment]
@T0nyKo Please observe what kind of data can be caught with `elfinder.log (event)`.
