### ISSUE TITLE
suggestion Multiple files convert in www.online-convert.com

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2579]
@nao-pon 
For Now in el-finder if we select multiple files & edit it, its open separate windows for each.
But they said it can upload multiple files for convert

https://apiv2.online-convert.com/docs/uploading_files/job_uploading_multiple_files.html
https://apiv2.online-convert.com/docs/uploading_files/chunked_upload.html
https://apiv2.online-convert.com/docs/examples/multiple_outputs_instead_of_zip.html

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Yes, I know. But this integration of online-convert.com on elFInder, that used edit command. The edit command is not support mulitiple item handling in on window. So maybe it impossible in currently.

Thanks!
