### ISSUE TITLE
List view column headers don't match up on browser resize

### ISSUE THREAD

**Issue by bwaindwain** [Studio-42/elFinder#2582]
When resizing the browser window with elfinder at 100% or auto width, the table column headers don't line up.

1. go to https://studio-42.github.io/elFinder/
2. switch to list view
3. notice table headers line up
4. make the browser window wider
5. notice table headers don't match 

![image](https://user-images.githubusercontent.com/2658754/42716015-c02eb638-86b6-11e8-8657-dd215ca22a7b.png)

maybe related to https://github.com/Studio-42/elFinder/issues/2179#issuecomment-326193534

**Comment by nao-pon** [comment]
@bwaindwain Thanks! 👍
