### ISSUE TITLE
Hide root folder in treeview

### ISSUE THREAD

**Issue by technologiesorion** [Studio-42/elFinder#2584]
Hi, 
I try to hide the root folder in the treeview, but I can't find the pattern to use in attributes config in order to do it.
Any idea ??
thanks in advance

**Comment by technologiesorion** [comment]
Sorry for the question. I did it with styling the  elfinder-navbar-root class with css...

**Comment by nao-pon** [comment]
@technologiesorion elFinder is a multi-root supported file manager, it is not thought to hide the root. If you hide it with CSS you can hide it with the following style.

```css
span.elfinder-navbar-root {
    display: none;
}
```

**Comment by oriontechno** [comment]
Yes ! thanks for your reply. As I've said previously, I done it like you.
