### ISSUE TITLE
If Dinamicly js/css = not will open tree (

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2585]
I use ajax.
1. Insert <link> tag for css
2. Insert <script> tag with src for js
3. Insert code jQuery(function($){..init elf..}); in HEAD tag
4. Elf opening (2.1.7), but none navbar.

```
.elfinder .elfinder-navbar {
	    display: none;
}
```
If not dinamicly js/css then Elf added display: block.
Why?)

**Comment by fortcms** [comment]
*3. It in head tag

**Comment by nao-pon** [comment]
@fortcms There is no problem in this [example](https://jsbin.com/magodiw/edit?html,output) ( https://jsbin.com/magodiw/edit?html,output ).

**Comment by fortcms** [comment]
Latest version have not this problem. Thanks for help
