### ISSUE TITLE
Why I have not fullscreen icon in toolbar ?

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2586]
none fullscreen icon (
`uiOptions: {
	toolbar: [['fullscreen']...`

**Comment by nao-pon** [comment]
@fortcms It is displayed in the latest version with the default options.

**Comment by fortcms** [comment]
@nao-pon my version 2.1.7. in this version does not work?

**Comment by fortcms** [comment]
It's work in latest version. Closed.
