### ISSUE TITLE
Some questions - bind, quicklook, json messages

### ISSUE THREAD

**Issue by ShinJii89** [Studio-42/elFinder#2590]
I don't know if you can see my replies in previous closed thread so I'm writing a new one with some questions:

1. When is in 'bind' command a variable $result['changed']? I thought it's after rename file but I see it's 'removed' & 'added', not 'changed'

2. Is this possible to see upload transfer? Not only uploadbar but also speed?

3. How to do something before upload? I guess something like "upload.preupload" because I need to check before every upload if that files which someone is uploading do not exceed the disk space so I need to abort upload if yes.

4. How to write JSON messages from connector after some errors or successful commands for things as in the third point above? For example "Files uploaded fine" or "You can't upload those files because it exceed the disk space" etc.?

5. Is this possible to do quicklook video/audio files with Videojs? (version 5.x)

6. Is this possible to turn this "subtitles" on by default not by clicking in the icon after right button mouse
![screenshot_2018-07-16 panel administracyjny - media asdfa](https://user-images.githubusercontent.com/6643364/42785909-6848a51e-8954-11e8-8214-81d130ed8601.png)
?

7. I turned on plugin "sanitizer" with option `'targets' => array('\\', '/', ':', '*', '?', '"', '<', '>', '|', '\'', '$', '[', ']', '%', '!', '^', '&', '#', '(', ')', '+', ';', ',', '~', '`')` - but it also (or not this plugin?) changed my filename from 01_filename.mp4 to C1_filename.mp4 ? Why? Why it can't be 01_ and it's C1_?

Regards :)

**Comment by nao-pon** [comment]
@ShinJii89 

1. Like the file system, elFinder also treats renames as item movements.
2. Can't  it currently. see #1357, #1667.
3. You can use a deregate point `upload.presave` like this.
```php
'bind' => [
    'upload.presave' => [
        function($thash, $name, $src, $elfinder, $volume) {
            $isFull = true; // or false
            if ($isFull) {
                unlink($src); // It will be triggered an warning error.
                // customized error message
                $GLOBALS['my_elfinder_upload_error'] = 'You can\'t upload those files because it exceed the disk space';
            }
        }
    ],
    'upload' => [
        function($cmd, &$result, $args, $elfinder, $volume) {
            if (!empty($GLOBALS['my_elfinder_upload_error'])) {
                $result['warning'][] = $GLOBALS['my_elfinder_upload_error'];
                unset($GLOBALS['my_elfinder_upload_error']);
            }
        }
    ],
]
```
4. see (3.).
5. Yes. but it need customize of quickllook plugin. see - https://github.com/Studio-42/elFinder/blob/master/js/commands/quicklook.plugins.js
6. See [uiOptions.toolbarExtra.displayTextLabel](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L657-L658).
7. It probably will not matter Sanitizer Plugin. I think that some other setting is affecting. But i don't know.

**Comment by ShinJii89** [comment]
Thanks for reply!
In point 3 - how to check filesize of uploaded files?

**Comment by nao-pon** [comment]
@ShinJii89 `$src` is a path to uploaded temporary file. So you can check file size with `filesize($src)`. And there are problems on elFinder <= 2.1.40 to this issue. Please try with the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by ShinJii89** [comment]
Yeah now it works! Really thank you!! Elfinder is the best filemanager <3

**Comment by nao-pon** [comment]
Thanks! 👍

**Comment by ShinJii89** [comment]
Ouch - last question - how to show by default all filenames in folder? not shorted. For example "98fds8f8df8s8fds.mp4" not "98fds8f8d"

**Comment by nao-pon** [comment]
@ShinJii89 Would you explain with some screenshots?

**Comment by nao-pon** [comment]
Long filenames are omitted because it is displayed in limited space. You can adjust CSS and show it all, but that will be bad results. Is not it a mouse over tool tip?

![180718-223228](https://user-images.githubusercontent.com/1412630/42884941-9f0ce394-8ada-11e8-8f09-6d55128b1524.png)

**Comment by ShinJii89** [comment]
Ok I understand, thanks :)
