### ISSUE TITLE
Issues with File and Folder Upload

### ISSUE THREAD

**Issue by dhirusarania** [Studio-42/elFinder#2593]
I have 2 issues.

**1. Files are uploaded outside.**

   If i drag a folder to upload, files inside it are uploaded outside of the folder. For example, i uploaded 'Test Folder' with a lot of PDF files and most of the PDF files are uploaded outside of it. Only some of them are inside it.

 ![capture](https://user-images.githubusercontent.com/33983632/42955638-957553d6-8b9b-11e8-8e85-5cf4a8e7b6a9.PNG)

**2. Large size PDF not uploaded**
 
If i try to upload small sized PDF, they are uploading fine but larger PDF are stuck. See the image below. 

![capture](https://user-images.githubusercontent.com/33983632/42978660-22bcbcd0-8c09-11e8-9273-3d47c662e2a7.PNG)

We are using AWS to host our site with Apache and PHP v5.4.45 

There are the current values for PHP.ini

max_execution_time => 0 => 0
max_file_uploads => 15000 => 15000
max_input_nesting_level => 64 => 64
max_input_time => -1 => -1
max_input_vars => 100000 => 100000
memory_limit => -1 => -1
post_max_size => 0 => 0

**Comment by nao-pon** [comment]
@dhirusarania Please try setting the appropriate value for `post_max_size`.

see - http://php.net/manual/en/ini.core.php#ini.post-max-size

> 5.3.4 | post_max_size = 0 will not disable the limit when the content type is application/x-www-form-urlencoded or is not registered with PHP.

**Comment by dhirusarania** [comment]
I increase the post_max_size to 1000 and tried uploading but got 'Upload error.
Data exceeds the maximum allowed size.'

![22](https://user-images.githubusercontent.com/33983632/42995833-ce1c951c-8c4c-11e8-93ac-a1d25574f5aa.PNG)

Also added uploadMaxSize as 1G but still same

![3](https://user-images.githubusercontent.com/33983632/42995892-f8910116-8c4c-11e8-9243-25bb18f24f00.PNG)

**Comment by nao-pon** [comment]
@dhirusarania Please read the manual of PHP. http://php.net/manual/en/ini.core.php#ini.post-max-size . 1000 is 1000 bytes. That's too small.

**Comment by dhirusarania** [comment]
@nao-pon Thanks, the above solution worked. I have increased it to 10000000000. But if i upload a folder, some of the files inside it are still uploaded outside.

![capture](https://user-images.githubusercontent.com/33983632/43031307-34eb9706-8cda-11e8-8492-1bab0b3a3036.PNG)

In the above image, all of the images should be inside the folder there.

**Comment by nao-pon** [comment]
I can not reproduce similar problems with folder uploading issues. Are you specifying options other than the default settings?

**Comment by dhirusarania** [comment]
No. They are all default settings.

**Comment by nao-pon** [comment]
Umm...

Please try
```
post_max_size 24M
upload_max_filesize 20M
max_file_uploads 50
```
