### ISSUE TITLE
How can i hide these  buttons?

### ISSUE THREAD

**Issue by xizan** [Studio-42/elFinder#2599]
Hello，i want to hide these buttons，but i can find files about them。
You can see below pictures。
Thank you for your help!

![1](https://user-images.githubusercontent.com/16182518/43377394-fab5bc54-93f2-11e8-9e7d-0a87385ee3b6.png)
![2](https://user-images.githubusercontent.com/16182518/43377403-0c35f7c8-93f3-11e8-918d-476e668396eb.png)

**Comment by nao-pon** [comment]
@xizan I implemented this feature. Please merge next config into your config and try with [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

```javascript
commandsOptions : {
    quicklook : {
        // ControlsList of HTML5 audio/video preview
        // see https://googlechrome.github.io/samples/media/controlslist.html
        mediaControlsList : 'nodownload', // e.g. 'nodownload nofullscreen noremoteplayback'
        // Show toolbar of PDF preview (with <embed> tag)
        pdfToolbar : false
    }
}
```

Thanks! 👍
