### ISSUE TITLE
Some exec spamming my .tmp

### ISSUE THREAD

**Issue by Poldan** [Studio-42/elFinder#2603]
On every open elfinder window - files in php/.tmp creating.
Debug bug trace show:

Array
(
    [name] => Array
        (
            [0] => ZohoOffice
            [1] => ZipArchive
            [2] => OnlineConvert
        )

    [method] => enabled
    [args] => 
    [reqid] => 164eff232e1126
    [debug] => 
)

**Comment by nao-pon** [comment]
@Poldan There are [connection flag files](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#connectionflagspath--2129). They are necessary for elFinder's smart action.

**Comment by Poldan** [comment]
> it is deleted at the end of the request
No. Files still existing.
Or garbage collector will delete they later?

**Comment by nao-pon** [comment]
Are those filenames starting with "elfreq" and never deleted and keeping increasing?

If the answer is "yes", activation of shutdown function has failed. If you are integrating with something else, please find what is blocking the shutdown function.

However, these files may be deleted by garbage collection after 12 hours.

**Comment by Poldan** [comment]
Yes, it's elfreq*.
No, it's clean build. No integrations. 
Now, i deleted .tmp folrder, so, finder use /tmp.
Some sort of solution.

**Comment by Poldan** [comment]
Found:
public static function onShutdown() {
 ...
 echo 'realpath: ' . realpath('./.tmp');
}

I got: '/'.
My root folder, not near elFinder.class.php.
Can fix by __DIR__ . '/.tmp', but seems bad solution.
Any ideas?

**Comment by nao-pon** [comment]
@Poldan Yes, The cause of this problem is that commonTempPath is a relative path. I will fix this.

Thanks! 👍
