### ISSUE TITLE
elfinder upload ends with errUploadTransfer code 6

### ISSUE THREAD

**Issue by woodbumper** [Studio-42/elFinder#2604]
php 7 with lastest elfinder working release. php.ini settings allow maximum of 10mb.  temp upload folder rights are set to 755, so everything should be fine. But it ends up with a errUploadTransfer error. Any clue?

**Comment by nao-pon** [comment]
@woodbumper see http://php.net/manual/features.file-upload.errors.php

> UPLOAD_ERR_NO_TMP_DIR
Value: 6; Missing a temporary folder. Introduced in PHP 5.0.3.

Please check your php configuration.

**Comment by woodbumper** [comment]
@nao-pon
Thx a lot. That did the trick. Could be an issue in the debug log feature for less experienced folk, just to avoid future questions like mine ;)
