### ISSUE TITLE
Control File Access with elFinder ?

### ISSUE THREAD

**Issue by Nick3523** [Studio-42/elFinder#2608]
Hello World ! 

I am using elFinder for a little project, I made a system that shows/hides specifics directoires depending on which user is connected. 

My trouble is that, the files are not protected, for example, if someone wants to share the link of a specific file, like in the example : 

![screenshot_15](https://user-images.githubusercontent.com/18366055/43770399-867340b4-9a3c-11e8-936a-7c224d3bf997.png)

So, someone who has acces to this PDF, and simply sends the link to another person who is not allowed to view the PDF, this last person can see the PDF. 

I read about [showing a fake path](https://github.com/Studio-42/elFinder/wiki/Disable-real-file-path-from-being-shown), but this changes only the link, the document stil can be accessed through the link. 

Is there any way that elFinder could generate a unique path that will work only for the user allowed to view the document ? Any suggestion please that could solve my problem ? 

I thank you for all your help :+1:

**Comment by nao-pon** [comment]
@Nick3523 Place the directory referred to by elFinder outside the document root and access it via connector referring to "[showing a fake path](https://github.com/Studio-42/elFinder/wiki/Disable-real-file-path-from-being-shown)".

Next, [bind](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind) the user function to the pre.file event. You can decide whether the user has access rights within that function.

```php
'bind' => [
    'file.pre' => [
        function($cmd, $args, $elfinder, $volume) {
            $relPath = $volume->path($args['target']);
            $allow = relPathIsAllowed($resPath); // Your any function
            if (!$allow) {
                return array(
                    'preventexec' => true,
                    'results' => array(
                        'error' => 'Access denied',
                        'header' => 'HTTP/1.0 403 Access Denied',
                        'raw' => true
                    )
                );
            }
        }
    ]
]
```

**Comment by Nick3523** [comment]
Thank you for your quick and complete answere @nao-pon-sama ! 

Works like a charm =D

**Comment by nao-pon** [comment]
@Nick3523 You are welcome! 😃
