### ISSUE TITLE
How to make trash readonly

### ISSUE THREAD

**Issue by yakupdemirci** [Studio-42/elFinder#2614]
Hello there; i want my users to be able to send items to trash, but not delete items from trash completely. When i make trash readonly, users can not put items to trash. Any ways to achieve this?

**Comment by nao-pon** [comment]
@yakupdemirci Please add a setting of volume roots configuration.
```php
'uiCmdMap' => array('rm' => 'hidden', 'paste' => 'hidden', 'mkdir' => 'hidden', 'copy' => 'restore')
```
# add `'rm' => 'hidden'` to default of [elFinderVolumeTrash](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeTrash.class.php#L29).
