### ISSUE TITLE
settings is not working

### ISSUE THREAD

**Issue by CodeLyokoXtEAM** [Studio-42/elFinder#2615]
just download elfinder & run it in server (& rename connector to work), there isn't setting button.
also when click toolbar settings there's no settings dialog show.
![image](https://user-images.githubusercontent.com/18566890/44191090-54aa5880-a147-11e8-923e-6d9470cc4e63.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM I checked with 2.1.40 and 2.1.40 (2.1-src Nightly: e929d13). There are no problems. Please check with clear your browser cache.

![fireshot capture 14 - files_elfinder 2 1 _ - https___hypweb net_elfinder-2 1_elfinder html elf_l1_lw](https://user-images.githubusercontent.com/1412630/44208992-0aec5d00-a19d-11e8-9d52-2671a909308e.png)

**Comment by CodeLyokoXtEAM** [comment]
https://codeload.github.com/Studio-42/elFinder/zip/master
https://codeload.github.com/Studio-42/elFinder/zip/e929d134db2075f5a2f0c959f86d02e6b7fcee30

also I try it in chrome incognito mode. But There is no hope.

![image](https://user-images.githubusercontent.com/18566890/44210385-f6e83180-a183-11e8-88c5-ba99c9e2cffe.png)

![image](https://user-images.githubusercontent.com/18566890/44210448-2434df80-a184-11e8-8bdc-f40118a44ebf.png)
![image](https://user-images.githubusercontent.com/18566890/44210460-2b5bed80-a184-11e8-85c2-b63e3d87f379.png)

**Comment by CodeLyokoXtEAM** [comment]
I'm also test it with internet explorer. but same result
![image](https://user-images.githubusercontent.com/18566890/44211418-8e4e8400-a186-11e8-9f44-eb4113c8285e.png)

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM Have you any JavaScript errors in the browser console?

**Comment by CodeLyokoXtEAM** [comment]
![image](https://user-images.githubusercontent.com/18566890/44211756-60b60a80-a187-11e8-876f-edd6a423bb95.png)

**Comment by CodeLyokoXtEAM** [comment]
found it 
this line is missing in "elfinder.src.html"
	<script src="js/commands/preference.js"></script>

**Comment by nao-pon** [comment]
@CodeLyokoXtEAM OK, You're right! I'll fix it. Thanks! 👍
