### ISSUE TITLE
these pdfs and videos  have  save buttons ,how can i remove them ?

### ISSUE THREAD

**Issue by xizan** [Studio-42/elFinder#2617]
you can see these pictures , i can remove these buttons , thank you !
![qq 20180817092227](https://user-images.githubusercontent.com/16182518/44243134-158c0e00-a200-11e8-907a-74d6674fb9e4.png)
![12](https://user-images.githubusercontent.com/16182518/44243192-54ba5f00-a200-11e8-8b73-e4fe51067543.png)

**Comment by nao-pon** [comment]
@xizan There is a similar issue. see #2599. Thanks.
