### ISSUE TITLE
how can i hide files ? hide files problem

### ISSUE THREAD

**Issue by russh3l** [Studio-42/elFinder#2618]
my connector php ;

> $opts = array(
	// 'debug' => true,
	'roots' => array(
		// Items volume
		array(
			'driver' => 'FTP',
      'host'   => $result2["server_ip"],
      'user'   => $result2["ftp_user"],
      'pass'   => $aes->decrypt($result2["ftp_pass"]),
      'path'   => str_replace($result2["ftp_root"], "", $result["server_dir"]).$game,
			'URL'           => "indirmeyok", // URL to files (REQUIRED)
			'uploadAllow'   => array('all'),
			//'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			//'uploadAllow'   => array('image', 'text/plain', 'model/vnd.valve.source.compiled-map', 'audio/mpeg mpga mp2 mp2a mp3 m2a m3a', 'audio/midi mid midi kar rmi', 'audio/ogg oga ogg spx', 'model', 'application/octet-stream', 'application/x-bzip2', 'application/octet-stream bin dms lrf mar so dist distz pkg bpk dump elc deploy', 'application/octet-stream bin dms lrf mar so dist distz pkg bpk dump elc deploy bsp'),// Mimetype `image` and `text/plain` allowed to upload
			//'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access',                    // disable and hide dot starting files (OPTIONAL)
			'disabled' => array('zipdl')
            'attributes' => array(
                array(// hide anything else
                    'pattern' => '/\.png$/',
                    'hidden' => true
                )
            )
        ),
    )
);

when i add this part im getting http 500 error 

>    'attributes' => array(
                array(// hide anything else
                    'pattern' => '/\.png$/',
                    'hidden' => true
       )

**Comment by nao-pon** [comment]
@russh3l PHP syntax error has occurred because you added config.
