### ISSUE TITLE
Edit mkdir function

### ISSUE THREAD

**Issue by Nick3523** [Studio-42/elFinder#2620]
Hello .

For my project, I wanted to add a feature that, once we create a directory, we are asked to input a name (not the directory name) and we have to do this with a popup.

For the moment, I disabeled the function mkdir in the file : elFinderVolumeDriver.class.php and I have this result : 

![screenshot_24](https://user-images.githubusercontent.com/18366055/44267028-ff487700-a22c-11e8-86c2-3624275f143b.png)

Juste by returning at the beggining of mkdir function :
 
`return $this->setError(elFinder::ERROR_PERM_DENIED);
`

Instead of showing an error,
I want to obtain something like this after creating a folder (Here for example Test) : 

![screenshot_24](https://user-images.githubusercontent.com/18366055/44267177-872e8100-a22d-11e8-994d-6a0dd6ed3105.png)

The thing is, I  think that I have to do this in JavaScript, and then get the value of the input and send it to PHP so that I can store it in a database, editing the function `mkdir($dsthash, $name)` and trying to show a popup is not possible and this is giving me error : "Data is not in JSON format". 

Is there anyway to edit the existing function, or maybe another way to do this ? 

Many thanks for your help, and for elFinder :)

**Comment by nao-pon** [comment]
@Nick3523 Is your goal to make the directory creation an authentication function?

**Comment by Nick3523** [comment]
@nao-pon  Thank you for your answere, Not really, because a folder is seen in database as a component, and the name I want to submit, is the name of the provider of this component.

So I want to show a popup that asks for the name of the provider, and then store it in the database, is that possible ? If I wanted to create this feature, which files should I see/edit ? 

Many thanks for your help :)

**Comment by Nick3523** [comment]
Maybe to be more clear, What I want to do is execute a PHP Script after every creation of subfolder (Level 1). 

But the matter is to execute this script, I have to redirect to this one, What I tried is editing mkdir function and adding : 

`header("location: http://www.myscript.com/");` 

Cannot not work, because the header can't open a new page but redirects the actual page, so the function mkdir will not return. 

The other alternative I tired was by JavaScript, which I think is the only way : 

`?>
<script type="text/javascript" language="Javascript">window.open('http://www.myscript.com/');</script>
<?php`


But the error "Data is not in JSON format" occurs again.

So the question would be, how to execute my PHP script right after creation of my subfolder ?

Thanks again =)

**Comment by Nick3523** [comment]
Maybe to be more clear, What I want to do is execute a PHP Script after every creation of subfolder (Level 1). 

But the matter is to execute this script, I have to redirect to this one, What I tried is editing mkdir function and adding : 

`header("location: http://www.myscript.com/");` 

Cannot not work, because the header can't open a new page but redirects the actual page, so the function mkdir will not return. 

The other alternative I tired was by JavaScript, Insering this JS code in the PHP function mkdir :  


`<script type="text/javascript" language="Javascript">window.open('http://www.myscript.com/');</script>`



But the error "Data is not in JSON format" occurs again.

So the question would be, how to execute my PHP script right after creation of my subfolder ?

Thanks again =)

**Comment by nao-pon** [comment]
@Nick3523 Use the [bind option](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind) to execute your own PHP script immediately after creating the directory.

```php
'bind' => [
    'mkdir' => [
        function($cmd, &$result, $args, $elfinder, $volume) {
            if ($result && !empty($result['added'])) {
                $newDir = $result['added'][0];
                $newDirPath = $volume->path($newDir['hash']);
                // and more your script...
                // Changing $result also changes the data returned to the client.
            }
        }
    ]
]
```

**Comment by Nick3523** [comment]
@nao-pon  I also thought about bind option, but I don't think that it will work. 

My PHP script has to interract with client, with an input form, so I have to redirect/popup to the PHP page, and trying to redirect to my script using : 



```
'bind' => [
    'mkdir' => [
        function($cmd, &$result, $args, $elfinder, $volume) {
            if ($result && !empty($result['added'])) {
                $newDir = $result['added'][0];
                $newDirPath = $volume->path($newDir['hash']);
                header("location: http://www.myscript.com/params");
            }
        }
    ]
]
```

Gives me the error : "Impossible to log to backend. HTTP error 0". 

I also have the error "Datas is not in JSON format" trying to redirect with JavaScript, using 

`echo "<script type=\"text/javascript\"language=\"Javascript\">window.open('http://www.example.com');</script>";
`

**Comment by Nick3523** [comment]
Is it possible to create an new error box, but instead of showing the usual message with close button, replace it with a button that opens a new tab, and in this tab I can launch my PHP script, a way like this : 

![screenshot_24](https://user-images.githubusercontent.com/18366055/44329765-a152a400-a465-11e8-8ba4-6742bbaeec0f.png)


Replace it with : 

![screenshot_24](https://user-images.githubusercontent.com/18366055/44329780-a9124880-a465-11e8-9ced-f1b0a75be386.png)


And then, in mkdir function : 

`return $this->setError(elFinder::MY_NEW_ERROR);`

 Do you think this is possible ?

**Comment by nao-pon** [comment]
I may not understand correctly because I am not good at English.

If the user needs an input value each time the user creates a directory, it is necessary to create a new mkdir command (mkdir 2, etc.).

Or, if there is enough user authentication information, it will solve by combining some login mechanism.

If you have a diagram of user input and data processing at the server I think that I can give better advice.

**Comment by Nick3523** [comment]
After a long thinking, I changed the way I have defined my project, so I will not touch to this function and I will do it in another PHP Page, it is better and easier I think .

Thank you for always answering and helping @nao-pon :smile:
