### ISSUE TITLE
Watermark in full image

### ISSUE THREAD

**Issue by vkirpa82** [Studio-42/elFinder#2621]
Can you make an option to have the watermark stretch over the entire image?

**Comment by nao-pon** [comment]
@vkirpa82 That is a good idea. I will start on this.

**Comment by nao-pon** [comment]
@vkirpa82 Please try plugin options...
```php
'ratio'    => 1,    // Ratio to original image (ratio > 0 and ratio <= 1)
'position' => 'CM', // Position L(eft)/C(enter)/R(ight) and T(op)/M(edium)/B(ottom)
'marginX'  => 0,    // Margin horizontal pixel
'marginY'  => 0,    // Margin vertical pixel
```
with [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

Thanks! 👍
