### ISSUE TITLE
Connector configuration option "rename" still showing although disabled

### ISSUE THREAD

**Issue by Shadi-Ayoub** [Studio-42/elFinder#2622]
I used the disabled option of my connector root to make using commands very strict. All were reflected on the UI perfectly except for the "Rename" on the root context menu. It is disabled for files and in the tool bar. see snapshot. Is this a bug?!

![image](https://user-images.githubusercontent.com/42518677/44310925-87767a00-a3ef-11e8-826c-1f81947a63f5.png)

**Comment by nao-pon** [comment]
@Shadi-Ayoub Since the rename of the volume root is not changed on the connector side but is changed only on the client's browser, it is not affected by the connector setting.

**Comment by Shadi-Ayoub** [comment]
I see. Thanks man!!
