### ISSUE TITLE
Saving preferences information

### ISSUE THREAD

**Issue by Shadi-Ayoub** [Studio-42/elFinder#2623]
Can someone explain where do the preferences information is being saved?! I am developing a multi-user application and want to make sure that a user changing the preferences of the client will not affect the preferences of other users using their own accounts.

![image](https://user-images.githubusercontent.com/42518677/44311181-d8886d00-a3f3-11e8-9e50-9cea3a30bc00.png)

**Comment by nao-pon** [comment]
@Shadi-Ayoub Preference settings are saved in client's browser local storage.

**Comment by Shadi-Ayoub** [comment]
Thank you @nao-pon !!!
