### ISSUE TITLE
uploadAllow and uploadDeny

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#2624]
Hi,

I am trying to use the elFinder 2.1.40 with the following connector configuration:

'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
'uploadAllow'   => array('application/vnd.google-earth.kmz','application/vnd.google-earth.kml+xml','application/gpx+xml'),
'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only

If I remove (comment) the "uploadDeny" instruction then I can upload/copy&paste/move any GPX, KML or KMZ file. While If I leave the "uploadDeny" then I can manage only KMZ files.

Is there an error in my configuration?

Thanks for your help.
Giorgio

**Comment by nao-pon** [comment]
@ghigio2000 The cause of this problem is that detecting MIME-Type by finfo causes all XML files to become "application/xml". I will fix this.

Thanks! 👍

**Comment by nao-pon** [comment]
@ghigio2000 Please try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip) to check this issue.

**Comment by ghigio2000** [comment]
@nao-pon yes it works. Thanks a lot for your help.
