### ISSUE TITLE
TypeError: "cannot use 'in' operator to search for 'length'

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#2625]
Implementing the elFinder in my code I get the following error:

TypeError: "cannot use 'in' operator to search for 'length' in .....

This error seems causing the left column (root with folders list) in the tree is not displayed.

What could be the root of this issue?

Using the same elfinder lib with your elfinder.html (same configuration, I hope) it is working without error and showing the left tree column properly.

**Comment by nao-pon** [comment]
@ghigio2000 Can you use elfinder.full.js of version 2.1.41 to report the line number where the error occurred?

**Comment by nao-pon** [comment]
Perhaps the event handlers you added to the elFinder client are affecting. What kind of event handlers do you add?

**Comment by ghigio2000** [comment]
I have added the "select" handler, but I got the error before adding it. 
Even if I comment that handler I still get the error.

Below is my elfinder client configuration, maybe you see something wrong, there is also the handlers.
..............................................................................................................
var elf = $('#elfinder1').elfinder({
	// elFinder options (REQUIRED)
	// Documentation for client options:
	// https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
	url : 'elFinder-2.1.40/php/connector.minimal.php?username='+username // connector URL (REQUIRED)
	,commandsOptions : {
		edit : {
			extraOptions : {
				// set API key to enable Creative Cloud image editor
				// see https://console.adobe.io/
				creativeCloudApiKey : '',
				// browsing manager URL for CKEditor, TinyMCE
				// uses self location with the empty value
				managerUrl : ''
			}
		}
		,quicklook : {
			// to enable preview with Google Docs Viewer
			googleDocsMimes : ['application/pdf', 'image/tiff', 'application/vnd.ms-office', 'application/msword', 'application/vnd.ms-word', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
		}
	}
	// bootCalback calls at before elFinder boot up 
	,bootCallback : function(fm, extraObj) {
		/* any bind functions etc. */
		fm.bind('init', function() {
			// any your code
		});
		// for example set document.title dynamically.
		var title = document.title;
		fm.bind('open', function() {
			var path = '',
				cwd  = fm.cwd();
			if (cwd) {
				path = fm.path(cwd.hash) || null;
			}
			document.title = path? path + ':' + title : title;
		}).bind('destroy', function() {
			document.title = title;
		});
	}
	,contextmenu : {
		// navbarfolder menu
		navbar : [],
	
		// current directory menu
		cwd    : [],
	
		// current directory file menu
		files  : ['rename']
	}
	,width: 400
	,height: 600
	,ui: ['toolbar', 'tree', 'path']
	,uiOptions : {
		toolbar : [
//						['back', 'forward'],
			// ['reload'],
			// ['home', 'up'],
			['mkdir'],
//						['open', 'download', 'getfile'],
//						['info'],
//						['quicklook'],
//						['copy', 'cut', 'paste'],
			['rm'],
			['rename'],
//						['extract', 'archive'],
			['search'],
			['view'],
//						['help']
		],
		cwd :{
			listView : {
				// columns to be displayed. default settings are:
				columns : ['date'],
			}
		},
	}
	,managers : {
		// 'DOM Element ID': { /* elFinder options of this DOM Element */ }
		'elfinder': {}
	},
	handlers : {
		select : function(event, elfinderInstance) {
			var selected = event.data.selected;
			console.log(elfinderInstance);
			if(selected.length > 0){
				var thisfilepath = elfinderInstance.path(selected[0]);
				var thisfilename = elfinderInstance.file(selected[0]);
				thisfilename = thisfilename.name;
				console.log(thisfilepath);
				console.log(thisfilename);
				var thisextension=thisfilename.substring(thisfilename.length-3,thisfilename.length);
				var thisfilenoex=thisfilename.substring(0,thisfilename.length-4);
				thisextension=thisextension.toLowerCase();
				if (thisextension=="kmz"){
					kml="userareas/"+username+"/"+thisfilenoex+"/doc.kml";
				} else {
					kml="userareas/"+thisfilepath;
				}
				FillTrackDataView("");
			}
		}
	}
});
........................................................................................................

**Comment by ghigio2000** [comment]
it is a "other library" conflict problem. I commented all the other libs I use in my app and so it worked. I will investigate how to fix it, thanks and sorry for your time spent on my error.

**Comment by nao-pon** [comment]
@ghigio2000 OK, Please let me know if there is a part to adjust on elFinder side.

**Comment by nao-pon** [comment]
I close this, but you can reopen it if necessary.
