### ISSUE TITLE
Input Type Text

### ISSUE THREAD

**Issue by rmcdahal** [Studio-42/elFinder#2628]
I have successfully implemented elfinder with TinyMce, Now i am stuck on issue that i can not init elfinder on input type = text,
I am searching the solutions like wordpress featured images button ,when i click on button this should open dialog box and insert images

**Comment by nao-pon** [comment]
@rmcdahal I made [online demo](https://jsbin.com/xoyeraq/edit?html,js,output). Is that what you want?

**Comment by rmcdahal** [comment]
Thanks for quick reply,This is what i wants, now how can i get relative path on input text ? i am working on CI and full file path is inserted on database,
![screenshot_1](https://user-images.githubusercontent.com/1020935/44508301-884c2c00-a6cd-11e8-99b5-99d761e189cd.png)

**Comment by nao-pon** [comment]
@rmcdahal Use "file.url" only or remove unnecessary part.
