### ISSUE TITLE
Retrieve Selected files on button click

### ISSUE THREAD

**Issue by chiragparekh** [Studio-42/elFinder#2629]
Hi,

I am trying to find solution that in elfinder how can I retrieve selected flies information on click of button in javascript?

Here below I attached an image I need to retrieve files on click of select button

![capture](https://user-images.githubusercontent.com/1888712/44460680-b4af6c00-a62b-11e8-85f6-538c4e5b5ba7.PNG)

**Comment by rmcdahal** [comment]
which editor? tinymce or ckeditor ?

**Comment by chiragparekh** [comment]
Just a standalone elfinder no editor.

**Comment by nao-pon** [comment]
@chiragparekh A simple example. Will it be helpful?
```javascript
elf = $('#elfinder').elfinder('instance');
$('<button>').html('Select').on('click', function() {
    var files = $.map(elf.selected(), function(h) {
        return elf.file(h);
    });
    elf.log(file);
});

**Comment by chiragparekh** [comment]
@nao-pon  Yes, this is what I need. That's helpful. Thank you.
