### ISSUE TITLE
Getting error: Root folder has not read and write permissions.

### ISSUE THREAD

**Issue by ntrimg** [Studio-42/elFinder#2631]
I just noticed in one of the folders where there are a bunch of images, when an image is clicked, a pop-up window opens and displays the following error:

{"error":["errConf","errNoVolumes"],"debug":["Driver \"elFinderVolumeLocalFileSystem\" : Root folder has not read and write permissions."]}

I see that the image is in the folder, and when right-clicking on the image and clicking "Preview", it does display.  It only shows this error when double-clicking on the image or trying to open it.  

Any suggestions on how to fix this, or what might be the problem?

**Comment by nao-pon** [comment]
@ntrimg Something you've done affects something. Please examine what is affecting compared with [standalone elFinder](https://github.com/Studio-42/elFinder#builds-compressed).

**Comment by nao-pon** [comment]
By default, the URL when the file is opened is the URL of the content itself. It is not via the connector (connector.minimal.php).

**Comment by ntrimg** [comment]
Oh ok.  Where is that setting usually changed?

**Comment by nao-pon** [comment]
By default it is connector.minimal.php.
