### ISSUE TITLE
Files uploads on Yearly/monthly auto folder,but have some problems

### ISSUE THREAD

**Issue by rmcdahal** [Studio-42/elFinder#2632]
I have pre save statements as
 `public function preUpload(&$path, &$name, $src, $elfinder, $volume) {

		$currentYear = date("Y");
		$currentMonth = date("m");

		$realpath = $elfinder->realpath($path);
		$realpath = $realpath . '/' . $currentYear;

		if (!file_exists($realpath) || !is_dir($realpath)) {
			$args = array('target' => $path, 'name' => $currentYear, 'reqid' => '');
			$result = $elfinder->exec('mkdir', $args);
			if ($result && $result["added"]) {
				$path = $result['added'][0]['hash'];

				$realpath = $realpath . '/' . $currentMonth;
				$args = array('target' => $path, 'name' => $currentMonth, 'reqid' => '');
				$result = $elfinder->exec('mkdir', $args);
				if ($result && $result["added"]) {
					$path = $result['added'][0]['hash'];
				} else {
					return false;
				}
			} else {
				return false;
			}
		} else {
			$realpath = $realpath . '/' . $currentMonth;
			if (!file_exists($realpath) || !is_dir($realpath)) {
				$args = array('target' => $path, 'name' => $currentMonth, 'reqid' => '');
				$result = $elfinder->exec('mkdir', $args);
				if ($result && $result["added"]) {
					$path = $result['added'][0]['hash'];
				} else {
					$path = $volume->getHash($path, $currentMonth);
					return true;
				}
			}

		}

		$path = $volume->getHash($realpath, '');

		return false;
	}`
Problem Is when i click on root folder and upload files then get uploaded to right folder,but if i click on monthly folder and uploaded then another year / month folder created, how to prevent this ? 
Below is screenshots 
![screenshot_1](https://user-images.githubusercontent.com/1020935/44536256-c4a67900-a71b-11e8-94bd-f1bfba8c88da.png)

**Comment by nao-pon** [comment]
@rmcdahal Do processing according to the value of `$path`.
