### ISSUE TITLE
Basic package of elFinder

### ISSUE THREAD

**Issue by alexantr** [Studio-42/elFinder#2634]
Often using elFinder as CMS built-in file manager for text fields, editors or just file uploader. Now elFinder 2.1 has many unnesesary additions for that functionality, like file viewers, editors, converters, custom settings. `elfinder.full.js` grows up from ~300 KB to ~1 MB - is too large.

2.0 branch would be good choise for that but it is deprecated and doesn't have last bug fixes.

It would be nice to have some package versions, like [CKEditor has](https://ckeditor.com/ckeditor-4/download/).

**Comment by nao-pon** [comment]
@alexantr I made a new task of Jake build. And added "[elfinder-minimal-2.1.zip](https://hypweb.net/elFinder-nightly/demo/Demo/Downloads/Latest%20Nightlys/elfinder-minimal-2.1.zip)" to [nightly builds](https://studio-42.github.io/elFinder/#elf_l1_RG93bmxvYWRzL0xhdGVzdCBOaWdodGx5cw). However, the file size did not become as small as I expected, it is 658 KB (320 KB - minimized).

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
