### ISSUE TITLE
jquery  1.12.4  Vulnerability

### ISSUE THREAD

**Issue by racoon-attack** [Studio-42/elFinder#2637]
https://snyk.io/test/npm/jquery/1.12.4 [ medium - XSS ]

elfinder.legacy.html  on

**Comment by nao-pon** [comment]
@racoon-attack About jQuery 1.12.4, only IE 8 is loaded. IE 8 is because jQuery 3 does not work. Although elFinder supports IE 8 for convenience, IE 8 is not encouraged due to expiration of vendor support.
