### ISSUE TITLE
How can I switch from min.css to full.css ?

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#2638]
I would like to customize the button icons size, but I do not find a way to switch ELFINDER from using the min.css to the full.css.
Is that the right way to try resizing the icons?
Thanks for your help.

**Comment by nao-pon** [comment]
@ghigio2000 Please check [elfinder.legacy.html](https://github.com/Studio-42/elFinder/blob/master/elfinder.legacy.html).

Please adjust the size of the icon with your CSS.
