### ISSUE TITLE
prevent upload some file format

### ISSUE THREAD

**Issue by farhadst** [Studio-42/elFinder#2640]
Hi
1. I want to prevent some formats, such as png and gif, from uploading.
I deleted the png and gif format in the "elFinder-2.1.41\php\mime.types" , and I also placed the following code in the "elFinder-2.1.41\php\connector.minimal.php-dist" but the problem was not fixed.
`'uploadDeny'    => array('image/png', 'image/gif'), `

2. I want to prevent uploading files name unicode, like the تست.jpg
and replace space in file name by underline, like test 2.jpg tp test_2.jpg

Thanks in advance

**Comment by nao-pon** [comment]
@farhadst About Upload Restrictions Please familiarize yourself with [uploadAllow](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadallow), [uploadDeny](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploaddeny) and [uploadOrder](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadorder) of Wiki. If uploadOrder in your configuration is `array ('deny', 'allow')`, it allows all types!

For the file name, refer to the [`acceptedName`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#acceptedname) setting and the [Normarizer plugin](https://github.com/Studio-42/elFinder/blob/master/php/plugins/Normalizer/plugin.php).
