### ISSUE TITLE
upload identical file within subfolder event error

### ISSUE THREAD

**Issue by weiluo8791** [Studio-42/elFinder#2641]
Given I have the following in the root folder
bad.html
test\image.jpg
test\bad.html

If I try to upload the same bad.html and test subfolder into the root (drag and drop)  the overwrite window will prompt ONLY for the test folder.

File named "test" already exists.
Replace old file with new one?
Yes No Cancel

and I will see the following in the remove event.
![image](https://user-images.githubusercontent.com/25639166/44674534-d037bf80-a9fb-11e8-9376-ae3dcfdf346f.png)

However if I upload the same thing again the overwrite window will prompt but this time I see the apply to all checkbox and I can answer yes for test folder and bad.html

However the removed event looks to be incorrect. Look under removed: the index is having the value of NaN 
![image](https://user-images.githubusercontent.com/25639166/44674783-94e9c080-a9fc-11e8-9bf3-d734267c324a.png)

I can reproduce this on your demo site https://studio-42.github.io/elFinder/#elf_l2_Lw
Although I can not see the remove event I can see the same overwrite window behavior. 

1. Upload a file and the same file within subfolder
2. Upload same thing first time will only prompt overwrite for anything but the file that existed in the subfolder)
3. Upload same thing second time will prompt overwrite for all but the remove event value having error on the index.

**Comment by nao-pon** [comment]
@weiluo8791 There are bags in elFinder.class.php and elFinderVolumeDriver.class.php. I'll fix it. Thanks! 👍
