### ISSUE TITLE
Info dialog - how to hide MD5 and SHA256?

### ISSUE THREAD

**Issue by mozan** [Studio-42/elFinder#2645]
As in subject. Are there any options?

**Comment by nao-pon** [comment]
@mozan There is an option [`commandsOptions.info.showHashAlgorisms`](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L500). Please set empty array `[]`.

**Comment by mozan** [comment]
Works perfectly. Thank you.
