### ISSUE TITLE
Info dialog - how to hide link for a folder

### ISSUE THREAD

**Issue by mozan** [Studio-42/elFinder#2646]
`
commandsOptions: {
	info : {
		hideItems : ['link']
	}
},
`

Pretty much something like that - but just for folders.

**Comment by nao-pon** [comment]
@mozan There is no option to hide the folder only, so I will add an option. Please tell me why you need this feature to determine what options are best.

**Comment by mozan** [comment]
@nao-pon Well I need it, because the URL generated for folders do not have any meaning on my system.

**Comment by nao-pon** [comment]
@mozan I done. Please try with [volume roots option `'dirUrlOwn' => 'hide'`](https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeDriver.class.php#L228-L229) with nightly build. Thanks! 👍

**Comment by mozan** [comment]
@nao-pon Perfect! Thank you :)
