### ISSUE TITLE
Unable to prevent file uploading

### ISSUE THREAD

**Issue by Joramt** [Studio-42/elFinder#2648]
Hey there

I'm having a bit of trouble with blocking the upload of a specific file. I've read https://github.com/Studio-42/elFinder/issues/1657 and tried to apply the solution, but failed. I'm using the Laravel ( current version 5.4 ) implementation of barryvdh https://github.com/barryvdh/laravel-elfinder, therefore i don't really have access to the connector options as easily as your snippet, it's a config file that gets loaded - which gave me a lot of headaches to configure a root drive per user ( the solution was to override the config at runtime via a middleware https://github.com/barryvdh/laravel-elfinder/issues/62 ). 

I tried to implement at least a front end validation for now, with the clear intention of getting back at this problem later on. So here's my code
```
var newFileSize = 0;
var currentFolderSize = 0;
var shouldRejectUpload = false;

$().ready(function () {
    var elf = $('#elfinder').elfinder({

        @if($locale)
            lang: '{{ $locale }}', // locale
        @endif
        customData: {
            _token: '{{ csrf_token() }}'
        },
        url: '{{ route("elfinder.connector") }}', 
        soundPath: '{{ asset($dir.'/sounds') }}',
        dialog: {width: 900, modal: true, title: 'Select a file'},
        resizable: false,
        height:  $(window).height()-20,
        handlers : {
            add : function(event, instance) {

                var uploadedFiles = event.data.added;
                for (i in uploadedFiles) {
                    var file = uploadedFiles[i];
                    newFileSize += file.size;
                }

                var limitSize = '{{env('MAX_TOTAL_UPLOAD_SIZE')}}';
                var totalSize = currentFolderSize + newFileSize;

                if(totalSize > limitSize){
                    shouldRejectUpload = true;
                }

            },
        },
        commandsOptions: {
            getfile: {
                oncomplete: 'destroy'
            },
            onlyURL  : false,
            multiple : false,
        },
        getFileCallback: function (file) {
            var AWS_FLYSYSTEM_BUCKET_URL = '{{env('AWS_FLYSYSTEM_BUCKET_URL')}}'
            var uploadedFileUrl = AWS_FLYSYSTEM_BUCKET_URL + '/' + file.url;
            window.parent.processSelectedFile(uploadedFileUrl, '{{ $input_id  }}');
            parent.jQuery.colorbox.close();
        }
    }).elfinder('instance');

    elf.bind('upload', function(e){
        if(shouldRejectUpload){
            elf.error('upload error');
            e.data.result = false;
            return jQuery.Deferred().reject();
        } else {
            return jQuery.Deferred().resolve();
        }
    });

});

```

I've tried to bind the upload function after `elfinder` was instantiated, as well as within its handlers. I do see the pop up saying 'Upload error' and as far as i can tell, the ` jQuery.Deferred().reject()` gets called too.
What am i doing wrong?

**Comment by Joramt** [comment]
i also tried to put the logic within the anonymous function binded to the `upload` event inside the `add` event - i was hoping it would prevent the file from being added - without success either.

**Comment by nao-pon** [comment]
@Joramt Client side restrictions have no security implications. To restrict the upload function, you should restrict it on the connector side.

PHP can also use anonymous functions, so I think that it can be done more easily.

```php
'disks' => [
    'local',
    'my-disk' => [
        'URL' => url('to/disk'),
        'alias' => 'Local storage',
        'bind' => [
            'upload.pre' => [function() {
                $isFull = function() {
                    // Your logic
                    return true;
                };
                if ($isFull()) {
                    // prevent uploading...
                    return array(
                        'preventexec' => true,
                        'results' => array('error' => 'Disk capacity is now full.')
                    );  
                }
            }]
        ]
    ]
],
```

**Comment by Joramt** [comment]
```
    'disks' => [
        'my-disk' => [
                'URL' => url('to/disk'),
                'alias' => 'Local storage',
                'bind' => [
                    'upload.pre' => [function() {
                        $isFull = function() {
                            // Your logic
                            return true;
                        };
                        if ($isFull()) {
                            // prevent uploading...
                            return array(
                                'preventexec' => true,
                                'results' => array('error' => 'Disk capacity is now full.')
                            );
                        }
                    }]
                ]
            ]
    ],
```

this is my elfinder.php config file. Sadly the file gets uploaded without a hitch, not even an error message displayed.
Also, what do you mean by client side has no security implications? Shouldn't it be possible to prevent the upload clientSide? according to your demo ( http://jsbin.com/nacoti/edit?js,output ) from your example https://github.com/Studio-42/elFinder/wiki/Client-event-API this should be doable

**Comment by nao-pon** [comment]
@Joramt Is the version of elFinder old? Please try with the latest version. Also, client side restrictions can be avoided by the user accessing the connector directly.
