### ISSUE TITLE
Download img when do a double click

### ISSUE THREAD

**Issue by carlosgg93** [Studio-42/elFinder#2651]
Hi,

I have a question, its posible to download a image when you do double click?
Now the browser open the image in a new tab when you do double click.

Thanks!

**Comment by nao-pon** [comment]
@carlosgg93 There is a menu "Action when select file" in "Preferences - Work Space". Please use it.

![180910-214705](https://user-images.githubusercontent.com/1412630/45298678-3c5e0b80-b544-11e8-8977-a2d1cb417881.png)

**Comment by carlosgg93** [comment]
Yes @nao-pon i see it but this option is saved in localStorage and the first time that i open elfinder the option by default is "open" because localStorage is empty.

it is possible that there is only the option download? and that this option is by default?

Thanks

**Comment by nao-pon** [comment]
@carlosgg93 OK, now elFinder has no option to set default value, so I will add an option to enable it. Thanks! 👍

**Comment by carlosgg93** [comment]
@nao-pon  I found a "work arround" putting  localStorage.setItem("elfinder-selectActionelfinder", "download"); in open function of elfinder.full.js

**Comment by nao-pon** [comment]
@carlosgg93 An option was added so that it can be set more easily.

see https://github.com/Studio-42/elFinder/commit/ae9e90803b3d77c3ea1914c35ad06201a2e618bd#diff-8f21be2aabffef6829e6a54df1769004

**Comment by carlosgg93** [comment]
Thanks! @nao-pon
