### ISSUE TITLE
Add Custom Checkbox column in listview (not showSelectCheckboxUA)

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#2653]
I would like to have a column of checkboxes in the listview.
I tried using "showSelectCheckboxUA" and it works, but I need to avoid "unselect all" on a filename selection in the listview.
I try to explain better my need.
When the user check the checkbox for a series of files I will display the files-content on a map. While on dblclick on one filename I will open the details of that particular file only. 
So when dblclick on a file I do not want to uncheck all those checked.
Hope it is clear.

thanks for your help.

**Comment by ghigio2000** [comment]
Maybe I have not explained properly, let me try to rephrase my question.
I would like to add in the listview a new column to set a file property.
It is a checkbox that I will use onchecked or onunchecked for my scope.

Hope this is possible, if not please answer me anyway. Thanks, appreciated.

**Comment by ghigio2000** [comment]
@nao-pon 
do you have any suggestion?
Thanks in advance for your help.

**Comment by ghigio2000** [comment]
@nao-pon What I want is to have a checkbox for each file in the listview, that I can check or uncheck as I wish and have an event linked to this click.

**Comment by nao-pon** [comment]
@ghigio2000 You can add a check box with the following settings. However, since there are some problems with check box event handling, I will fix it.

```javascript
uiOptions : {
    cwd : {
        listView : {
            columns : ['perm', 'date', 'size', 'kind', 'sel']
        },
        replacement : {
            sel : function(f, fm) {
                return '<input type="checkbox" class="elfinder-cwd-nonselect elfinder-cwd-list-sel" data-hash="'+f.hash+'"/>';
            }
        }
    }
}
```

**Comment by nao-pon** [comment]
@ghigio2000 I fixed a bug. Please try with...
```javascript
bootCallback : function(fm, extraObj) {
    fm.bind('init', function() {
        fm.getUI('cwd').on('click', 'input.elfinder-cwd-list-chk', function() {
            var chk = $(this);
            fm.log([chk.data('hash'), chk.is(':checked')]);
        });
    });
},
uiOptions: {
    cwd: {
        listView : {
            columns : ['url', 'date', 'size', 'kind', 'chk']
        },
        replacement : {
            chk : function(f, fm) {
                return '<input type="checkbox" class="elfinder-cwd-nonselect elfinder-cwd-list-chk" data-hash="'+f.hash+'"/>';
            }
        }
    }
}
```

**Comment by ghigio2000** [comment]
Thanks it works.
It would be perfect, if I can select multiple files and then press once a checkbox to check/uncheck all those selected.
thanks a lot for your work and help.

**Comment by nao-pon** [comment]
@ghigio2000 

1. Please implement it yourself using sessionStorage etc.

2. Calling `elfinderInstance.selected()` will get an array of hashes of the selected items. Please implement it yourself using this.

**Comment by ghigio2000** [comment]
@nao-pon I do not find any documentation/explanation of the sessionStorage you mention above.

**Comment by nao-pon** [comment]
@ghigio2000 elFinder does not use sessionStorage. You need to handle sessionStorage using JavaScript. I'd suggest checking the sessionStorage with 'replacement' and adding the checked attribute as necessary.

**Comment by ghigio2000** [comment]
@nao-pon 

Hi, I almost completed my implementation of these checkbox but testing on mobile they are not showing the tick when checked (it looks like they are disabled, but in reality the bootCallback works).
Can you fix it?
thanks

**Comment by nao-pon** [comment]
@ghigio2000 Yes, I was able to reproduce the problem. I will fix this.
