### ISSUE TITLE
Bug: Matching file names with different casing in extension

### ISSUE THREAD

**Issue by Shadi-Ayoub** [Studio-42/elFinder#2654]
The system allows copying or uploading a file into a folder that contains a file with the same name and type but with different casing in extension. Example: test.**jpg** into a folder having test.**JPG**.
Try moving one file into the trash then restore it, the file simply disappears.

The system apparently deals with file names in a case-insensitive approach but it is not handled properly in special cases like the one i explained.

![image](https://user-images.githubusercontent.com/42518677/45447517-dce93280-b6e0-11e8-93ae-6578a3f068ff.png)

**Comment by nao-pon** [comment]
@Shadi-Ayoub Does the [demo site](https://studio-42.github.io/elFinder/#elf_l2_Lw) reproduce the same problem?

**Comment by Shadi-Ayoub** [comment]
@nao-pon I cannot test the scenario on the demo site as the available commands are restricted (cannot copy-paste or upload). I am sure that I did not alter any core code in the version I am using (2.1.41).

**Comment by nao-pon** [comment]
@Shadi-Ayoub According to your screenshot you put "image003.jpg" into trash be "image003.JPG". This is a strange behavior. Have you customized anything?
