### ISSUE TITLE
no error logging in elfinder.connector class for run method

### ISSUE THREAD

**Issue by nadorator** [Studio-42/elFinder#2657]
Hello,

in the run method of elfinder.connector class there is no any error logging from the exception before the exit function. 

A simple syslog(LOG_DEBUG, $e->getMessage().' '.$e->getTraceAsString()); 

would be a huge help when a checkAbort() method return a throw.

**Comment by nao-pon** [comment]
@nadorator I'll add a connector main option `throwErrorOnExec` (Default: false). Thanks! 👍
