### ISSUE TITLE
[ISSUE] When maxTargets = 1. Elfinder can't call loadThumbnails if images are more than one.

### ISSUE THREAD

**Issue by ethaizone** [Studio-42/elFinder#2664]
**Reproduce step.**
1. Set option maxTargets be 1.
2. Upload multiple images by drag and drop.
3. Image uploaded success but problem is incoming. (LOL)

After that ELFinder try to refresh UI and call `loadThumbnails`
https://github.com/Studio-42/elFinder/blob/632bc974529fc820b54fd4805f58651443c3a46f/js/ui/cwd.js#L1254

then `request` will call
https://github.com/Studio-42/elFinder/blob/632bc974529fc820b54fd4805f58651443c3a46f/js/ui/cwd.js#L1285-L1288

but it will stop because these lines.
https://github.com/Studio-42/elFinder/blob/632bc974529fc820b54fd4805f58651443c3a46f/js/elFinder.js#L2272-L2275

after that UI have problems.
- Can't show thumbnail.
- Can't delete file or directory.
- Can't create new directory.

**Comment by nao-pon** [comment]
@ethaizone On the handling of `maxTargets` option some problems on the client side were found and I fixed it. Thanks! 👍

**Comment by ethaizone** [comment]
> @ethaizone On the handling of `maxTargets` option some problems on the client side were found and I fixed it. Thanks! 👍

Good to hear. Thx. :)
