### ISSUE TITLE
Bug - Chrome 69.0.3497.100 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by mozan** [Studio-42/elFinder#2665]
There's no way to upload a file via drag & drop.

Upload works as usual:
- if I select a file via system wise file chooser (tested on windows).
- in Firefox (61.0.2 (32-bit)) - both methods (drag & drop and via file chooser)
- in Opera 56.0.3051.18 - both methods
- in Microsoft Edge 42.17134.1.0 - both methods

Tested on my own app and https://studio-42.github.io/elFinder/#elf_l2_Lw

Looks like the problem shows up just in Chrome.

**Comment by nao-pon** [comment]
@mozan I tried uploading on a [demo site](https://studio-42.github.io/elFinder/#elf_l2_Lw) using Windows 10 Chrome (69.0.3497.100 (Official Build) (64 bit)), but there was no problem with DnD and file selector. Is your Chrome extension affecting something?

**Comment by mozan** [comment]
You're right. Somehow Chrome after the update didn't allow me to DnD pretty much everywhere. My bad I didn't test somewhere else, just focused on elFinder.

Apologies for the false alarm!

**Comment by nao-pon** [comment]
@mozan No problem. Do not worry. 👍
