### ISSUE TITLE
hundredth time - video thumbnails

### ISSUE THREAD

**Issue by hopelang727** [Studio-42/elFinder#2669]
I'm sorry this has been asked a hundred times already, but the previous answers are not helping me.
I am not getting my video thumbnails appear.
I have ffmeg installed;
Here is the version info;

ffmpeg version N-91990-g49c67e7 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-28)
  configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --extra-libs=-lpthread --extra-libs=-lm --bindir=/root/bin --enable-gpl --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree
  libavutil      56. 19.101 / 56. 19.101
  libavcodec     58. 30.100 / 58. 30.100
  libavformat    58. 18.101 / 58. 18.101
  libavdevice    58.  4.103 / 58.  4.103
  libavfilter     7. 32.100 /  7. 32.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
[NULL @ 0x27cf500] Unable to find a suitable output format for 'pipe:'
pipe:: Invalid argument

I used the manual install right off of ffmpeg.org

I am using "nightly" 2.42 and it's basically a vanilla install.
PNG thumbs work fine.

**Comment by hopelang727** [comment]
BTW I got rid of the pipeline error by re-doing h265

ffmpeg version N-91995-gcbe5c7e Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-28)
configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --extra-libs=-lpthread --extra-libs=-lm --bindir=/root/bin --enable-gpl --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
libavutil      56. 19.101 / 56. 19.101
libavcodec     58. 30.100 / 58. 30.100
libavformat    58. 18.102 / 58. 18.102
libavdevice    58.  4.103 / 58.  4.103
libavfilter     7. 32.100 /  7. 32.100
libswscale      5.  2.100 /  5.  2.100
libswresample   3.  2.100 /  3.  2.100
libpostproc    55.  2.100 / 55.  2.100

**Comment by nao-pon** [comment]
@hopelang727 If you can not execute the command with just `ffmpeg`, please set the path.

In your connector.php.
```php
define('ELFINDER_FFMPEG_PATH',   '/root/ffmpeg_build/ffmpeg');
```

**Comment by nao-pon** [comment]
Yes, you can do it anywhere before creating an elFinder instance. In addition, if ffmpeg can be executed from PHP, it will be enabled by default.
