### ISSUE TITLE
Video uploads

### ISSUE THREAD

**Issue by hopelang727** [Studio-42/elFinder#2670]
I'm using "nightly" 2.42
PNGs etc upload fine.
I can't upload mp4 files - it says;
 File type not allowed. (video/mp4)

There is so much OLD out of date info about this on here, I can not work out the current state of play.

Any help would be much appreciated.

**Comment by nao-pon** [comment]
Please check the Wiki - https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadAllow .

In connector.minimal.php (as default)
```php
'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
'uploadAllow'   => array('image/x-ms-bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/x-icon', 'text/plain'), // Mimetype `image` and `text/plain` allowed to upload
'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
```
You can set
```php
'uploadAllow'   => array('image/x-ms-bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/x-icon', 'text/plain', 'video/mp4'), // Mimetype `image` and `text/plain` allowed to upload
```

**Comment by nao-pon** [comment]
You are welcome. Anyone can edit the wiki freely. We welcome informative edits any time. 👍
