### ISSUE TITLE
Plz, rename - mime.types

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2671]
Not a unique name...

**Comment by nao-pon** [comment]
@fortcms What's the problem you have? Please explain concretely.

**Comment by fortcms** [comment]
@nao-pon How can I use namespaces?

**Comment by fortcms** [comment]
P.s. How to create namespaces in elFinder?

**Comment by nao-pon** [comment]
The mime.types file is automatically loaded internally. It is not necessary to set auto loading. see https://github.com/Studio-42/elFinder/blob/master/php/elFinderVolumeDriver.class.php#L4370-L4399

**Comment by fortcms** [comment]
file name - mime.types it is ok.
But i want use namespaces for elffinder.
How to use correct ?)

**Comment by nao-pon** [comment]
As of now, elFinder supports PHP 5.2. Therefore, in order to introduce the namespace, we have to stop supporting PHP 5.2. That decision should be careful.

**Comment by fortcms** [comment]
@nao-pon PHP 5.2 is hopelessly outdated.
My system does not support 5.2))
Tell us how to properly edit the files for my purposes?

**Comment by nao-pon** [comment]
> PHP 5.2 is hopelessly outdated.

I understand it well. However, it is certain that a server running PHP 5.2 still exists. I agree to truncate the outdated PHP, but because of the policy to support PHP 5.2 as a project, it requires development of two lines of legacy and edge. However, there is not enough power for that.
