### ISSUE TITLE
Maybe edited - autoload.php ?

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2672]
`'elFinderVolumeGoogleDrive' => ELFINDER_PHP_ROOT_PATH . '/elFinderVolumeGoogleDrive.class.php',
		'elFinderVolumeGroup' => ELFINDER_PHP_ROOT_PATH . '/elFinderVolumeGroup.class.php',
		'elFinderVolumeLocalFileSystem' => ELFINDER_PHP_ROOT_PATH . '/elFinderVolumeLocalFileSystem.class.php',
		'elFinderVolumeMySQL' => ELFINDER_PHP_ROOT_PATH . '/elFinderVolumeMySQL.class.php',
		'elFinderVolumeTrash' => ELFINDER_PHP_ROOT_PATH . '/elFinderVolumeTrash.class.php',
	);
	if (isset($map[$name])) {
		return include_once($map[$name]);
	}`
as
`'elFinderVolumeGoogleDrive' => 'elFinderVolumeGoogleDrive.class.php',
		'elFinderVolumeGroup' => 'elFinderVolumeGroup.class.php',
		'elFinderVolumeLocalFileSystem' => 'elFinderVolumeLocalFileSystem.class.php',
		'elFinderVolumeMySQL' => 'elFinderVolumeMySQL.class.php',
		'elFinderVolumeTrash' => 'elFinderVolumeTrash.class.php',
	);
	if (isset($map[$name])) {
		return include_once(ELFINDER_PHP_ROOT_PATH . '/' . $map[$name]);
	}`

**Comment by fortcms** [comment]
p.s. for a smaller file size

**Comment by nao-pon** [comment]
@fortcms Yes, you are right! I will fix this. Thanks!
