### ISSUE TITLE
Disable some right click menus

### ISSUE THREAD

**Issue by uche40** [Studio-42/elFinder#2673]
I would like to disable SOME of the file click click menu options leaving only, - Open, Download and Preview - . Attached is my main.default.js file as i currently have it for my elfinder install located here https://mypancho.com/apps/videostock/. So far i was able to completely remove the right click option, but i want to only have  Open, Download and Preview , when a user right clicks a file. I am using the Material Theme. I'm not a programmer so i would appreciate a sample code or possible an updated version of my main.default.js  would be greatly appreciated. See screenshot
![test here elfinder - web file manager - open source project under the 3-clause bsd license](https://user-images.githubusercontent.com/8086604/45918111-bada7780-be79-11e8-90c7-7509b1680ab1.png)

see my main.default.js  file
[main.zip](https://github.com/Studio-42/elFinder/files/2407846/main.zip)

**Comment by CodeLyokoXtEAM** [comment]
This will help you.
https://github.com/Studio-42/elFinder/wiki/Custom-context-menu-command

**Comment by uche40** [comment]
I looked at that and it is referring to adding a custom context menu. So that does not help me. I do NOT want to add a new or custom context menu, I simply want code to disable/hide/remove the existing ones except the Open, Download and Preview menu.

**Comment by CodeLyokoXtEAM** [comment]
sorry
https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#contextmenu

**Comment by uche40** [comment]
Yep i saw that already but not sure how to tweak it to achieve what i need. I'm ntot a programmer. lol.  attached is my current main.default.js file for https://mypancho.com/apps/videostock/
[main.zip](https://github.com/Studio-42/elFinder/files/2408074/main.zip) any pointer on where and what code i need would be welcome.

**Comment by uche40** [comment]
below is my  main.js file code

`/**
 * elFinder client options and main script for RequireJS
 *
 * Rename "main.default.js" to "main.js" and edit it if you need configure elFInder options or any things. And use that in elfinder.html.
 * e.g. `<script data-main="./main.js" src="./require.js"></script>`
 **/
(function(){
	"use strict";
	var // jQuery and jQueryUI version
		jqver = '3.3.1',
		uiver = '1.12.1',
		
		// Detect language (optional)
		lang = (function() {
			var locq = window.location.search,
				fullLang, locm, lang;
			if (locq && (locm = locq.match(/lang=([a-zA-Z_-]+)/))) {
				// detection by url query (?lang=xx)
				fullLang = locm[1];
			} else {
				// detection by browser language
				fullLang = (navigator.browserLanguage || navigator.language || navigator.userLanguage);
			}
			lang = fullLang.substr(0,2);
			if (lang === 'pt') lang = 'pt_BR';
			else if (lang === 'ug') lang = 'ug_CN';
			else if (lang === 'zh') lang = (fullLang.substr(0,5).toLowerCase() === 'zh-tw')? 'zh_TW' : 'zh_CN';
			return lang;
		})(),
		
		// Start elFinder (REQUIRED)
		start = function(elFinder, editors, config) {
			// load jQueryUI CSS
			elFinder.prototype.loadCss('//cdnjs.cloudflare.com/ajax/libs/jqueryui/'+uiver+'/themes/smoothness/jquery-ui.css');
			
			$(function() {
			    
			//var myCommands = ['*'];
			var myCommands = ['preview','sort','view','fullscreen'];
			//var myHelp =  ['about', 'shortcuts', 'help'];
			var myHelp =  { view: ['MyPancho'] };
			//var myHelp = { Xview : ['Xabout', 'shortcuts', 'help'] };
			var myMenu = { toolbar : [
					['back', 'forward'],
					// ['reload'],
					['home', 'up'],
					//['mkdir', 'mkfile', 'upload'],
					['open', 'download', 'getfile'],
					//['info'],
					['quicklook'],
					//['copy', 'cut', 'paste'],
					//['rm'],
					//['duplicate', 'rename', 'edit', 'resize'],
					//['extract', 'archive'],
					['search'],
					['view'],
					['sort'],
					['fullscreen']
					//,['help']
				] 
			};
			
			var mySub = {
				// navbarfolder menu
				//navbar : ['open', '|', 'copy', 'cut', 'paste', 'duplicate', '|', 'rm', '|', 'info'],
				// current directory menu
				//cwd    : ['reload', 'back', '|', 'upload', 'mkdir', 'mkfile', 'paste', '|', 'info'],
				// current directory file menu
				//files  : [ 'getfile', '|','open', 'quicklook', '|', 'download', '|', 'copy', 'cut', 'paste', 'duplicate', '|', 'rm', '|', 'edit', 'rename', 'resize', '|', 'archive', 'extract', '|', 'info' ]
				files: ['|'],
				navbar: ['|'],
				cwd: ['|']
			};
			
			    
				var optEditors = {
						commandsOptions: {
							edit: {
								editors: Array.isArray(editors)? editors : []
							}
						}
					},
					opts = {
						url : 'php/connector.minimal.php', // connector URL (REQUIRED)
						width : 'auto',
						height : '100%',
						cssAutoLoad : ['themes/material/css/theme.css'], // Array of additional CSS URLs
						commands : myCommands,
						//help : myHelp,
						uiOptions : myMenu,
						contextmenu : mySub,
						dragUploadAllow : false,
						lang : 'en'                         // auto detected language (optional)
					};
				
				// Interpretation of "elFinderConfig"
				if (config && config.managers) {
					$.each(config.managers, function(id, mOpts) {
						opts = Object.assign(opts, config.defaultOpts || {});
						// editors marges to opts.commandOptions.edit
						try {
							mOpts.commandsOptions.edit.editors = mOpts.commandsOptions.edit.editors.concat(editors || []);
						} catch(e) {
							Object.assign(mOpts, optEditors);
						}
						// Make elFinder
						$('#' + id).elfinder(
							// 1st Arg - options
							$.extend(true, { lang: lang }, opts, mOpts || {}),
							// 2nd Arg - before boot up function
							function(fm, extraObj) {
								// `init` event callback function
								fm.bind('init', function() {
									// Optional for Japanese decoder "encoding-japanese"
									if (fm.lang === 'ja') {
										require(
											[ 'encoding-japanese' ],
											function(Encoding) {
												if (Encoding && Encoding.convert) {
													fm.registRawStringDecoder(function(s) {
														return Encoding.convert(s, {to:'UNICODE',type:'string'});
													});
												}
											}
										);
									}
								});
							}
						);
					});
				} else {
					alert('"elFinderConfig" object is wrong.');
				}
			});
		},
		
		// JavaScript loader (REQUIRED)
		load = function() {
			require(
				[
					'elfinder'
					, 'extras/editors.default.min'               // load text, image editors
					, 'elFinderConfig'
				//	, 'extras/quicklook.googledocs.min'          // optional preview for GoogleApps contents on the GoogleDrive volume
				],
				start,
				function(error) {
					alert(error.message);
				}
			);
		},
		
		// is IE8 or :? for determine the jQuery version to use (optional)
		old = (typeof window.addEventListener === 'undefined' && typeof document.getElementsByClassName === 'undefined')
		       ||
		      (!window.chrome && !document.unqueID && !window.opera && !window.sidebar && 'WebkitAppearance' in document.documentElement.style && document.body.style && typeof document.body.style.webkitFilter === 'undefined');

	// config of RequireJS (REQUIRED)
	require.config({
		baseUrl : 'js',
		paths : {
			'jquery'   : '//cdnjs.cloudflare.com/ajax/libs/jquery/'+(old? '1.12.4' : jqver)+'/jquery.min',
			'jquery-ui': '//cdnjs.cloudflare.com/ajax/libs/jqueryui/'+uiver+'/jquery-ui.min',
			'elfinder' : 'elfinder.min',
			'encoding-japanese': '//cdn.rawgit.com/polygonplanet/encoding.js/1.0.26/encoding.min'
		},
		waitSeconds : 10 // optional
	});

	// check elFinderConfig and fallback
	// This part don't used if you are using elfinder.html, see elfinder.html
	if (! require.defined('elFinderConfig')) {
		define('elFinderConfig', {
			// elFinder options (REQUIRED)
			// Documentation for client options:
			// https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
			defaultOpts : {
				url : 'php/connector.minimal.php' // connector URL (REQUIRED)
				,commandsOptions : {
					edit : {
						extraOptions : {
							// set API key to enable Creative Cloud image editor
							// see https://console.adobe.io/
							creativeCloudApiKey : '',
							// browsing manager URL for CKEditor, TinyMCE
							// uses self location with the empty value
							managerUrl : ''
						}
					}
					,quicklook : {
						// to enable CAD-Files and 3D-Models preview with sharecad.org
						sharecadMimes : ['image/vnd.dwg', 'image/vnd.dxf', 'model/vnd.dwf', 'application/vnd.hp-hpgl', 'application/plt', 'application/step', 'model/iges', 'application/vnd.ms-pki.stl', 'application/sat', 'image/cgm', 'application/x-msmetafile'],
						// to enable preview with Google Docs Viewer
						googleDocsMimes : ['application/pdf', 'image/tiff', 'application/vnd.ms-office', 'application/msword', 'application/vnd.ms-word', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/postscript', 'application/rtf'],
						// to enable preview with Microsoft Office Online Viewer
						// these MIME types override "googleDocsMimes"
						officeOnlineMimes : ['application/vnd.ms-office', 'application/msword', 'application/vnd.ms-word', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.spreadsheet', 'application/vnd.oasis.opendocument.presentation']
					}
				}
			},
			managers : {
				'elfinder': {},
			}
		});
	}

	// load JavaScripts (REQUIRED)
	load();

})();
`

**Comment by CodeLyokoXtEAM** [comment]
![image](https://user-images.githubusercontent.com/18566890/45920936-1c760280-bec9-11e8-815d-39f03431026e.png)

**Comment by uche40** [comment]
Let me try that....

**Comment by uche40** [comment]
it kinda works but only for the file context menu, i wanted to remove some folder menu and some nav bar menu too. I actually saw this file but not sure how i can apply it .https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L1150-L1158  it seems i can just easily make my changes in that options file much easier, but how do i include it in elfinder. do i just place it in a folder or what.

**Comment by nao-pon** [comment]
@uche40 Your site has an error in index.html. 
![180923-213357](https://user-images.githubusercontent.com/1412630/45928066-7aadee80-bf78-11e8-8a6b-dbb2937c326e.png)

You can change the setting in main.js as you are doing, or you can change the default option in index.html. On your site, context menu is not displayed due to the setting in main.js you did. It is because the download is not functioning because `var myCommands = ['preview', 'sort', 'view', 'fullscreen'];` does not contain `download`.

Debugging JavaScript is useful when using the browser's developer tool.

**Comment by uche40** [comment]
I have now added download like so to var myCommands = ['preview','sort','view','download','preview','view','quicklook','fullscreen'];

but i do not see the preview and open options.

Additionally,  As for this file, not sure how i can apply it .https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L1150-L1158 it seems i can just easily make my changes in that options file much easier, but how do i include it in elfinder. do i just place it in a folder or what.

**Comment by theangular** [comment]
https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api



i found out the solution

**Comment by theangular** [comment]
it’s all here https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
> I would like to disable SOME of the file click click menu options leaving only, - Open, Download and Preview - . Attached is my main.default.js file as i currently have it for my elfinder install located here https://mypancho.com/apps/videostock/. So far i was able to completely remove the right click option, but i want to only have Open, Download and Preview , when a user right clicks a file. I am using the Material Theme. I'm not a programmer so i would appreciate a sample code or possible an updated version of my main.default.js would be greatly appreciated. See screenshot ![test here elfinder - web file manager - open source project under the 3-clause bsd license](https://user-images.githubusercontent.com/8086604/45918111-bada7780-be79-11e8-90c7-7509b1680ab1.png)
> 
> see my main.default.js file [main.zip](https://github.com/Studio-42/elFinder/files/2407846/main.zip)





https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api
