### ISSUE TITLE
Add flysystem driver to core

### ISSUE THREAD

**Issue by SamMousa** [Studio-42/elFinder#2675]
Currently the packagist package has 900k downloads.
The flysystem connector driver by @barryvdh has 500k downloads on packagist.

The package works great but since elFinder comes bundled with several drivers it makes sense to bundle a driver for Flysystem as well.

In the future this could even lead to reduced maintenance required since elFinder drivers could be replaced with FlySystem drivers, which have excellent test coverage and a good reputation overall.

**Comment by nao-pon** [comment]
@SamMousa Thank you for your request.

When using flysystem driver I think that composers are often used to add additional adapters. Therefore, I think that it is not very useful to include only flysystem driver in the core.

**Comment by SamMousa** [comment]
I'm not saying only have flysystem. But having it in the core would be good.

**Comment by nao-pon** [comment]
What I would like to say is that composers are often used when introducing adapters of Flysystem so it is not very useful to put only Flysystem drivers in the core. I think that it is enough to install the Flysystem driver together when installing Flysystem's adapter by composer.

What are the advantages of maintaining Flysystem's drivers here?

**Comment by SamMousa** [comment]
> only Flysystem

That's not the goal.

> What are the advantages of maintaining Flysystem's drivers here?

It becomes a first-class citizen like the FTP, OneDrive and MySQL drivers.
The advantages are the same for any sufficiently popular driver:
- Better support
- Reduced maintenance load
- Less dependencies and trust required for users.

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
