### ISSUE TITLE
Image upload size

### ISSUE THREAD

**Issue by shinokada** [Studio-42/elFinder#2676]
Is there any setting that limits the upload image?
When I am not able to upload more than 1MB.

**Comment by nao-pon** [comment]
@shinokada Did you check the wiki? https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadmaxsize

**Comment by shinokada** [comment]
Thank you for a quick reply.
I will set it with a bigger value.
BTW, why the default value is 0?

**Comment by nao-pon** [comment]
@shinokada "0" is the default because it does not limit it.
