### ISSUE TITLE
custom submenu in menu

### ISSUE THREAD

**Issue by giokats** [Studio-42/elFinder#2677]
Hello. 
I want to create a new right-click command with submenu options but i have really confused. Could you give me an example? 

Thank you in advance.

**Comment by giokats** [comment]
Finally, i found it.  Thank you anyway.

**Comment by d0coco** [comment]
I want do that too, where do you found, can you help me??

**Comment by giokats** [comment]
Sorry for the delay. I did like something "Sort" command. This is my code:
`setVar = function() {
            self.variants = [];
            self.variants.push([
                {
                    type  : 'Validation',
                },
                ('<span class="ui-icon ui-icon-check"/>' + '&nbsp;' + fm.i18n('cmdADIScriptValidation'))
            ]);
            self.variants.push([
                {
                    type  : 'ValidationRecurcive',
                },
                ('<span class="ui-icon ui-icon-rotate-r"/>' + '&nbsp;' + fm.i18n('cmdADIScriptValidationRecurcive'))
            ]);
            self.variants.push('|');
            self.variants.push([
                {
                    type  : 'Ingestion',
                },
                ('<span class="ui-icon ui-icon-check"/>' + '&nbsp;' + fm.i18n('cmdADIScriptIngestion'))
            ]);
};`

Hope to help you.
