### ISSUE TITLE
elfinder default size changing 

### ISSUE THREAD

**Issue by yatheeshkm** [Studio-42/elFinder#2679]
i am trying from so many days to change the default size it is showing that 'style="width: auto; height: 400px;" ' i have tried by changing the default size in the elfinder.js file but no changes happened so please help where i can change that default size property.

**Comment by nao-pon** [comment]
@yatheeshkm Please check the Wiki - https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#width .
