### ISSUE TITLE
ELFileManager shows blank screen

### ISSUE THREAD

**Issue by rsthomas100** [Studio-42/elFinder#2680]
After working fine for quite awhile, ELFileManager quit switching to different folder when one was selected.  Then one day after having logged out and coming back in later the ELFileManager screen was virtually blank.  See attached file.  

I have reinstalled ELFileManager but still get the same blank screen.  

![elfilemanagerscreen](https://user-images.githubusercontent.com/43638732/46138892-21b1b500-c21b-11e8-8299-dcf35474c462.png)

**Comment by nao-pon** [comment]
@rsthomas100 It does not seem to be an issue with elFinder. Please check the source application.
