### ISSUE TITLE
One click select possible?

### ISSUE THREAD

**Issue by praad** [Studio-42/elFinder#2681]
It would be good to use elfinder to one file input field but in this case two click on the chosen file is completely unnecessary. Is there any way to remap this behaviour?

**Comment by nao-pon** [comment]
@praad You can use event handler of `select`.

```javascript
handlers : {
    select : function(e, fm) {
        var data = e.data;
        if (data.origin && data.origin === 'cwd') {
            fm.exec('getfile', data.selected)
        }
    }
}
```
