### ISSUE TITLE
Error saving file with zoho

### ISSUE THREAD

**Issue by padre** [Studio-42/elFinder#2682]
First of all, thank you very much for the plugin, it's wonderful.

My problem is that when I edit a document with zoho and hit the "save" button, zoho shows me the following tooltip:

"There was an error saving the content. Export a local copy and try again later.

The response POST https://writer.zoho.eu/writer/remotesave.im: 
{"statusValue": "publicexportError"}

The var saveurl is correct. 

Has anyone had the same problem? Thanks!

**Comment by nao-pon** [comment]
@padre It seems to be an error on zoho side. Please ask in the zoho community.
