### ISSUE TITLE
Set default folder on googleDrive on Init

### ISSUE THREAD

**Issue by daebak74** [Studio-42/elFinder#2683]
Hi, first at all thanks for your support.
I am using Auto mount Gdrive with refresh token and I would like to set dynamicaly client side a defaul folder. 

$('#elfinder').elfinder({
    url : link_connector+'/connector.minimal.php',
    lang: 'en',
    startPathHash : 'gd3_Lw',
    rememberLastDir : 'false'
});

Using this code work and on init show google drive root but HOW to pass the folder path ?

**Comment by nao-pon** [comment]
@daebak74 Please check the DOM id of the corresponding element in the folder tree with the developer tool of the browser.
![180929-015605](https://user-images.githubusercontent.com/1412630/46222472-678d8b00-c38b-11e8-8763-9592c59231aa.png)

**Comment by daebak74** [comment]
@nao-pon thanks for your fast reply I saw that the id is in the list but is not so much helpfull for my case or I should to save in db all the ID and I would to get on fly. Maybe I didn't explain well my problem. In web app I have a db with contacts and for each contact I create in google drive a folder. the folder name of coarse has the unique id of the relative contact. 

So for example
DB -> CONTACT 1 -> ID 1 -> FORLDER CONTACT_1
DB -> CONTACT 2 -> ID 2 -> FORLDER CONTACT_2

ON document load I can get the id and show the relative folder of that contact.

I belived that was possible to use the hash for get the path but that work only for the file saved on local server and not for file/folder in cloud. so there is a way to get the path without need to save into db ?

Thanks again for your support.

**Comment by nao-pon** [comment]
> I belived that was possible to use the hash for get the path

In the case of the Google Drive driver, you can access that folder by encoding "Target parent ID/Target folder ID". Please try it.

**Comment by daebak74** [comment]
:( I tried everything to hash but I don't get the result. Maybe I am fused :) Can you tell me what I have to pass in encoding for get the right path. I f I wanna load on Init I need to use the ID saved in DB so the folder "customer_1" is "customer_" + ID

`<?php
	$volumeId = 'gd4_';
        $path = '????'; // without root path
	$hash = $volumeId . rtrim(strtr(base64_encode($path), '+/=', '-_.'), '.');
	echo $hash; 
?>`
![image](https://user-images.githubusercontent.com/11459528/46245829-c2a79800-c3f4-11e8-94ea-150a95587ee5.png)

Thanks!!!

**Comment by nao-pon** [comment]
The ID used for the folder hash is the item ID on GoogleDrive. So you will need to store the ID on GoogleDrive in your database as well. Or I think that hash on elFinder may be good.

**Comment by daebak74** [comment]
@nao-pon  Ok what i was thinking. If I need to save the Google ID I save directly the elfinder url. Or there is a way to get the elfinder path in callback function and select after init ?
Thanks!

**Comment by nao-pon** [comment]
> Or there is a way to get the elfinder path in callback function and select after init ?

Using the following code, you can open the specified folder at any time.
```javascript
var hash = 'gd3_Lw';
elFinderInstance.request({
    data   : {cmd  : 'open', target : hash},
    notify : {type : 'open', cnt : 1, hideCnt : true},
    syncOnFail : true,
    lazy : false
});
```

> By the way would be great to get the Google drive ID from elfinder API :)

You can get the ID path by decoding hash.

e.g in PHP
```php
$id = 'gd3_';
// cut volume id after it was prepended in encode
$hash = substr($hash, strlen($id));
// replace HTML safe base64 to normal
$idPath = base64_decode(strtr($h, '-_.', '+/='));
```

**Comment by daebak74** [comment]
@nao-pon both solution need to store the hashed path in DB because in GD we can't get the hash by folder name. 
In local server or in php or in js we just need to know the folder name for get the path 
$hash = 'L1_' . rtrim(strtr(base64_encode('folder'), '+/=', '-_.'), '.');

In GD we need to know the GD id for each folder created so need to store in DB

One solution for get onFly the hashed path would be to add a class or data attribute on elfinder rendered tree with the name of folder that in JSON response is cwd->name.

get the path is fast $('#nav-gd4_Lw .elfinder-navbar-subtree').find('.folder').attr('id');

For don't save the path hashed path or GD ID in DB I'll try this direction but I think that could to added in code and be helpfull for others too.

Thanks
