### ISSUE TITLE
Inserting image and auto height

### ISSUE THREAD

**Issue by shinokada** [Studio-42/elFinder#2684]
I have CSS `width:100%; height: auto;` for different devices so that it won't squeeze the image.

When I insert an image without entering the width and height, elFinder insert the width and height automatically. And it overwrites my CSS. I tried to enter `auto` to the height but it requires a number.

Is there any setting so that elFinder won't insert the width and height?

Thank you in advance.

**Comment by nao-pon** [comment]
@shinokada What is "Inserting image"?

**Comment by nao-pon** [comment]
Is that something on the WYSIWYG editor? If so, the place you should ask is the WYSIWYG editor repository.

**Comment by shinokada** [comment]
Ok, thanks.
