### ISSUE TITLE
errResize issue

### ISSUE THREAD

**Issue by mparfeniuk** [Studio-42/elFinder#2685]
Guys maybe you could help me? 
After migration to nginx/php7.2 I can't do manipulations (resize, rotate e.t.c.) with images. Chmod for all images 777. 
What I missed? Do I need some specific php module or nginx configuration? 

Response from connector: 
**{"error":["errResize","uploads\/articles\/2\/image.png"]}**

**Comment by nao-pon** [comment]
@mparfeniuk PHP requires GD or Imagick. Or, the web server needs the ImageMagick `convert` command. Please check them.

**Comment by mparfeniuk** [comment]
Yes, after sudo apt-get install php7.2-gd and reloading php7.2-fpm all works good. Thanks Naoki.
