### ISSUE TITLE
AccessControl path for GoogleDrive

### ISSUE THREAD

**Issue by mit-ems** [Studio-42/elFinder#2687]
I'm transitioning from a Dropbox backend to a GoogleDrive backend, and having an issue. I previously used the "accessControl" function to set access permissions, which worked fine with Dropbox because the "path" and "relpath" arguments were the actual directory names. With GoogleDrive though, the "path" and "relpath" attributes are the GoogleDrive folder IDs, which makes it extremely difficult to effectively manage the permissions. Is there any way to have the "path" attribute show the folder name instead of the folder ID when using the GoogleDrive driver?

**Comment by nao-pon** [comment]
@mit-ems The GooglrDrive driver holds folder information in the session. However, since you do not have access rights to the session object, you can not use it. So extend it to get the session object. Once this is possible, session data can be obtained as follows.

```php
'accessControl' => function($name, $path, $accessControlData, $volume) {
    $session = $volume->getSession();
    $id = $volume->id();
    $cacheData = $session->get($volume->id() . $volume->netMountKey);
}
```
