### ISSUE TITLE
The file or directory to be published does not exist: D:\OpenServer\domains\ust/vendor/studio-42/elfinder

### ISSUE THREAD

**Issue by sbekzhan** [Studio-42/elFinder#2688]
What is the problem???

**Comment by sbekzhan** [comment]
The file or directory to be published does not exist: D:\OpenServer\domains\ust/vendor/studio-42/elfinder 
how i can decide this??

**Comment by nao-pon** [comment]
@sbekzhan This seems to be due to your integration, not the elFinder problem.
