### ISSUE TITLE
Getting the path of pasted image

### ISSUE THREAD

**Issue by uru** [Studio-42/elFinder#2689]
Hi,
I have a callback function that works with uploading and pasting from Bind actions.
```
'bind' => array( 'upload paste' => array('smallImage'))
```
With this callback function, I automatically generate many different sizes of the uploaded image. While doing this, I find the path of the image with the `url` parameter in the `$result` variable. But the paste action that works with Drag&Drop has no url parameter in the `$result` variable. How can I get the path of an image that is copied and pasted?

**Comment by nao-pon** [comment]
@uru You can get URL with `getContentUrl`.

```php
function smallImage($cmd, &$result, $args, $elfinder, $volume) {
    if (!empty($result['added'])) {
        foreach($result['added'] as $i => $f) {
            if (empty($f['url'])) {
                $result['added'][$i]['url'] = $volume->getContentUrl($f['hash']);
            }
        }
    }
}
```

**Comment by uru** [comment]
Thank you @nao-pon, The important point is `$volume->getContentUrl()` function 👍
