### ISSUE TITLE
Mobile Navbar 

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#2690]
I am checking my page on the mobile and I am stuck with the NAVBAR almost closed not able to open it again, see the screen shot below.

![img_5270](https://user-images.githubusercontent.com/4995563/46485468-fff89500-c7fb-11e8-82e2-e0cdbd1b4de8.PNG)

On the PC I can use the resize button to open the navbar, but in the mobile it is not available and only a swipe is possible.
I do not understand how can I reduce so much the navbar if the resize is not available.
Also my navbar has a minWidth of 50px so should be not possible to have this situation.
I have tried to work on the css but no result so far.
Please help. Thanks a lot.

P.S.: also if you see the additional chk (checkbox) are disabled (do not show the think when clicked) on the mobile ?

**Comment by ghigio2000** [comment]
I do not know what happened but I solved it.

**Comment by ghigio2000** [comment]
Again it happened but I am not able to understand why

**Comment by nao-pon** [comment]
@ghigio2000 Please trigger resize event to window on just after showing the elFinder node.
