### ISSUE TITLE
Download event

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#2692]
I am trying to apply "event.preventDefault()" on the download event but it still show me the "save" dialog.
Is it possible to avoid this?

below my code in the handler:

	download : function(event, elfinderInstance) {
		console.log(event);
		event.preventDefault();

               alert('ciao');

        },

![immagine](https://user-images.githubusercontent.com/4995563/46533841-60441100-c8a6-11e8-9b3e-04c9de9c03bb.png)

**Comment by nao-pon** [comment]
@ghigio2000 The `download` callback fires after being downloaded. Therefore, you can not stop the download.
