### ISSUE TITLE
Download multi files in a single zip

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#2693]
@nao-pon 

I love the automatic creation of a zip if I select multiple files and then press the download.

I tried to catch the download event but the event it self does not return the zip, it returns the selected files.

Is there a way to get the temporary zip file url during the download event handling?

thanks for your help.

**Comment by nao-pon** [comment]
@ghigio2000 To realize that, there is a method to create your own download command (eg mydownload) with reference to the download command and use it.

Refer to https://github.com/Studio-42/elFinder/issues?q=uiCmdMap+label%3Ahowto for how to use the volume driver option `uiCmdMap`.

**Comment by ghigio2000** [comment]
thanks I will give it a try
