### ISSUE TITLE
Custom checkbox column does not show tick on mobile/Safari

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#2694]
@nao-pon

Hi, I completed my implementation of these checkbox (input.elfinder-cwd-list-chk) and they works ok on PC. But testing on mobile they are not showing the tick (checked symbol) when checked (it looks like they are disabled, but in reality the bootCallback works).
Can you fix it?
thanks

**Comment by nao-pon** [comment]
@ghigio2000 This is related with https://github.com/Studio-42/elFinder/issues/2653#issuecomment-427359505. I'll fix it. Thanks! 👍

**Comment by ghigio2000** [comment]
thanks so I will close this

**Comment by nao-pon** [comment]
@ghigio2000 I tried it on iPhone 6s + iOS 12.0, but there is nothing wrong with it. However, since the touch point is sensitive, I think it would be better to take measures such as setting a margin in the check box.
![fa7a6577-bbb5-452d-95b4-e7dc4134d63e](https://user-images.githubusercontent.com/1412630/46913022-2cf93480-cfc0-11e8-9ff4-7812f708fbb0.png)

**Comment by ghigio2000** [comment]
I updated using the last night library, but I am still having the same problem using Safari (not only with the touch but also on the PC using the mouse).
If I use Firefox everything is ok.
Could you please give a try to this:

http://globalterramaps.com/TerraVENEW.html?GEC=5

thanks.

**Comment by nao-pon** [comment]
I checked on iPhone 6s iOS 12.0.1 Safari. Column size are strange a little but display and operation are no problems.

![15b0473e-5d3e-40d5-8680-777b6c218c2e](https://user-images.githubusercontent.com/1412630/46950996-8eed9300-d0c1-11e8-9a26-f56cd1915b82.png)

**Comment by ghigio2000** [comment]
@nao-pon I am still having the same problem
In the screen shot above I do not see any checkbox ticked.
Can you please tick one and resend me the screen shot?

We use iPhone 7, iPad, iPad Pro, iPhone 8 with different iOS version, including 12.0.1 and also we used Safari from PC Mac, but NONE of them are able to tick these checkboxs. The operation work but the checkbox is not ticked.

Please let me know, I am really sorry having completed my project and I cannot publish it for this reason.
Thanks as usual for your help.

**Comment by nao-pon** [comment]
- First item (pippo folder) checked
![233ea96f-240b-4645-9ab0-89aa4b10c9cb](https://user-images.githubusercontent.com/1412630/47358619-30e62e80-d705-11e8-9e15-a2620cf86a35.png)

- Second item (BHavCove.gpx)
![22db7b1c-70ac-464d-971a-6f0e36f45549](https://user-images.githubusercontent.com/1412630/47358620-32175b80-d705-11e8-99fd-a17e4f184248.png)

**Comment by ghigio2000** [comment]
@nao-pon 

At this point I do not understand anymore how can this be possible.
Do you think it is a matter of our Safari configuration? 
Are you using Safari? I am asking just to be sure.

**Comment by ghigio2000** [comment]
Sorry, I am able to reproduce your situation. I am sure I can fix it now.
Sorry again.

**Comment by nao-pon** [comment]
@ghigio2000 Perhaps by increasing the padding size of the checkbox on touch devices I think that erroneous touch can be prevented. For touch devices, elFinder nodes are given the "elfinder-touch" class.

**Comment by ghigio2000** [comment]
@nao-pon mine seems to be a Safari checkbox problem.
In a particular situation I check/uncheck programmatically those checkbox.
It works in Firefox works this command 
checkbox.checked=true or false 
With Safari it is not working.

**Comment by ghigio2000** [comment]
In you comments above you mentioned there are strange column size, how can I set a column size programmatically?

**Comment by nao-pon** [comment]
There is no problem in my test environment, so CSS of your environment may be affecting. Usually the column size will not be shifted. Since the column size is calculated according to the header line, there is a possibility that there may be a problem with acquiring the header size.

**Comment by ghigio2000** [comment]
I now fixed all about the checkbox thanks a lot.

You mean I cannot change column size programmatically?
