### ISSUE TITLE
RE: Automount a specific GoogleDrive folder for all users on start-up

### ISSUE THREAD

**Issue by uche40** [Studio-42/elFinder#2697]
We studied this old ticket and attempted to try and it didn't work. https://github.com/Studio-42/elFinder/issues/1815 . Please can you give us a correct direction to enable 'Automount a specific GoogleDrive folder for all users on start-up'. Below is the link to our set-up http://mypancho.com/apps/stockvideo/

**Comment by nao-pon** [comment]
@uche40 You need to configure GoogleDrive to mount by network mount. Next, add 'refresh_token' option to GoogleDrive's volume root setting.

**Comment by uche40** [comment]
I believe i already tried that, maybe i'm missing something, could you be a little more detailed. Maybe some sample code, I know its a lot to ask but I really appreciate your responses.

**Comment by nao-pon** [comment]
@uche40 The minimum setting is that GoogleDrive is available on network mount and the following volume root setting.
```php
array(
    'driver' => 'GoogleDrive',
    'path' => '/', // or folder id of the GoogleDrive,
    'refresh_token' => 'Your Refresh Token',
)
```

**Comment by uche40** [comment]
Ok thanks

**Comment by hopelang727** [comment]
@nao-pon LOVE what you have done with ELFINDER, but I am finding it confusing too.

Is there not a COMPLETE example using google drive?
Last I tried it said, drive not available or something :-(

As far as I understand so far, we have main.js and connector.php

In which file and which SECTION does
array(
    'driver' => 'GoogleDrive',
    'path' => '/', // or folder id of the GoogleDrive,
    'refresh_token' => 'Your Refresh Token',
)
go?

What is actually needed to create the
"network mount"
And what is actually needed to set the
"volume root setting"

In which file/s and in which sections?
Do those sections already exist, or do we have to create them?

Is asking for the 2 complete files set up with gdrive too much to ask for?

I see it in main js, but adding it there created not mounteed AFAIR.
I have uncommented the gdrive part in connector and added my api etc.
but I do not see a place in connector to add any other google dive info.

It's only 2 files. Could we not have a FULL example using google drive? (with redacted api keys of course)

I appreciate it is super easy for you and you expect us to know as well, but sometimes knowing which file and exactly in which place, coupled with all the usual issues of programming syntax, make it very hard.

Ideally there would be a wizard installer ;-)
Meantime 2 complete files using a google drive would take all the pain away. Please!

If there is an FAQ or HowTo somewhere, I am sorry I have missed it.
There are so many OUTDATED THREADS going back years, it's hard to know what is current and what isn't and sometimes they even conflict and have false info in them

Could we just have the two FULL sample files using google drive ?
Of course I am "assuming" only main.js and connector.php need setting to make gdrive work?

Then non programmers can see where to put their own API details and just be running - which I'm sure is what you really want ;-)

Many thanks.

**Comment by uche40** [comment]
Hey nao-pon , any response to hopelang727 's comment?
