### ISSUE TITLE
Add/Remove or Hide/Show button from the toolbar dinamically

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#2699]
@nao-pon 

can I **dinamically** add/remove or hide/show a button from the toolbar ?

I searched a lot on the web but I did not find any solution so far.

I tried something like this but it does not work (elf3 is the definition of my elfinder instance):

elf3[0].elfinder.options.uiOptions.toolbar.push(['switchlisttomap']);

**Comment by nao-pon** [comment]
@ghigio2000 You can hide it for each volume using the `disabled` root option of the PHP connector, but there is no mechanism to dynamically change with JavaScript after instance creation.

**Comment by nao-pon** [comment]
@ghigio2000 See "[commands/view.js](https://github.com/Studio-42/elFinder/blob/master/js/commands/view.js)" and "[ui/viewbutton.js](https://github.com/Studio-42/elFinder/blob/master/js/ui/viewbutton.js)". The points of view.js are `this.options = {ui: 'viewbutton'};` and `this.exec()`.
