### ISSUE TITLE
Inactive icons

### ISSUE THREAD

**Issue by alexandrovsergii** [Studio-42/elFinder#2700]
https://prnt.sc/l3ibte
When I enter File Manager all icons are inactive. As soon as I click any icon (sometimes I click within the icons panel) icons become active.

**Comment by nao-pon** [comment]
@alexandrovsergii Please try an option [`enableAlways : false`](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L1160-L1167) of client options.
