### ISSUE TITLE
oldschool true

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#2701]
Hi,

on mobile I decided to hide the navbar and leave only the listview.
To drive thru the tree I left "oldschool: true".
But on mobile the dblclick is not available (as far as I know), so how can I move a folder up by just select the ".." folder ? 
The select event is not working on this kind of object. 
What's the best solution?

**Comment by nao-pon** [comment]
This is a bug so i'll fix it. Thanks! 👍
