### ISSUE TITLE
Elfinder div does not resize with its container

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#2703]
I have configured the elfinder instance with :

height: $('#middle').height()-2

here is the "middle" height
![immagine](https://user-images.githubusercontent.com/4995563/46661493-9c82b480-cbb9-11e8-894c-555b6692f9c8.png)

here is the "elfinder3" height
![immagine](https://user-images.githubusercontent.com/4995563/46661558-ba501980-cbb9-11e8-8018-30bac561541f.png)

**Comment by nao-pon** [comment]
@ghigio2000 Prese try...
```javascript
height: '100%',
heightBase: $('#middle'),
```
