### ISSUE TITLE
Files with 0 Byte are not shown anymore

### ISSUE THREAD

**Issue by flack** [Studio-42/elFinder#2704]
I'm using elfinder with a database backend (custom `elFinderVolumeDriver`), and I've noticed when I upgrade to 2.1.41+, files with a size of 0 bytes are not shown any more. I have bisected the issue and it comes from this change:

https://github.com/Studio-42/elFinder/commit/da91c03faf79f46c8181559ea1c30c4300d235e4#diff-5fbe229771e2478f38d552503c8f5e15R4155

If I remove the third parameter (`$stat['size']`) form the `$this->mimetype` call, everything works normally again. I am not exactly sure what the problem is, but I have noticed that for 0 byte files, the `mimetype` is empty in the `cmd=tree` response, which then somehow causes the files to be not shown in the elFinder frontend.

Maybe this is something I have to fix in my custom driver, but I'm really not sure, because I don't understand the changeset. For now I have a workaround that always outputs a dummy size, but that is kind of hacky as a solution

**Comment by nao-pon** [comment]
@flack There is a bug in `elFinderVolumeDriver::mimetype()` so i'll fix it. Thanks! 👍

**Comment by flack** [comment]
Thanks for the quick fix!

i just tested and 0 byte files are listed again with your change. There is still one difference to how it behaved before: In 2.1.40, elFinder would display the mimetypes from my custom driver (i.e. what I return from the `_stat()` function), and in the new version, everything that is 0 bytes has `text/plain`. Is that intentional?

**Comment by nao-pon** [comment]
@flack It should use the MimeType that is notified by the volume driver. I will fix this.

**Comment by flack** [comment]
@nao-pon looks good, thanks again!
