### ISSUE TITLE
failed to delete buffer zlib output compression

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2705]
> [10-Oct-2018 19:21:51 America/Matamoros] 
>  Notice => ob_end_clean(): failed to delete buffer zlib output compression
>  - - - - - - - - - - - - - - - - - -
>  URI	=> /jf/call.php?get=elfinder
>  File	=> /jf/core/apps/_specific_/elFinder_2.1/elFinderConnector.class.php
>  Line	=> 347
>  Stack 	=> 1. /jf/call.php:20
>  	=> 2. /jf/core/apps/_base_/PnP.class.php:150
>  	=> 3. /jf/core/functions.php:17
>  	=> 4. /jf/plugins/elfinder/call.php:43
>  	=> 5. /jf/core/apps/_specific_/elFinder_2.1/elFinderConnector.class.php:113
>  	=> 6. /jf/core/apps/_specific_/elFinder_2.1/elFinderConnector.class.php:282
>  	=> 7. /jf/core/apps/_specific_/elFinder_2.1/elFinderConnector.class.php:347

My code:

> .htaccess - not used zlib.
> .php - // no output contents for client after!
> // GZip
> if(extension_loaded('zlib') && isset($_SERVER['HTTP_ACCEPT_ENCODING']) && strpos($_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip') !== false){
> 	if(SYS_USE_GZIP)
> 		ini_set('zlib.output_compression', 1024 * 8);
> 	else
> 		ini_set('zlib.output_compression', 'Off');
> }
> ob_start();

Where is error ?

**Comment by fortcms** [comment]
if not correct path

> 'roots' => array(array(	'driver'	=> 'LocalFileSystem',
> 					'path'		=> NOT CORRECT,

Then error....

**Comment by nao-pon** [comment]
@fortcms What is the problem with actual operation?

**Comment by fortcms** [comment]
@nao-pon no)
