### ISSUE TITLE
Why is there hard coding ?? i18n

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2706]
> 24298 helpSource = fm.baseUrl + 'js/i18n/help/%s.html.js';
> 4472 langJs = self.baseUrl + 'js/i18n/elfinder.' + lang + '.js',

**Comment by fortcms** [comment]
I created an option to switch languages. i18nPath.
But I do not know how to add this to help files.
Help me.

**Comment by fortcms** [comment]
> 24339 helpSource = fm.i18nPath + 'help/%s.html';
I do not known init i18nPath in here...

**Comment by fortcms** [comment]
> uiCmdMapPrev = '',
> gcJobRes = null,
> i18nPath = 'js/i18n/',
...
> this.i18nPath = i18nPath;
...
> if (this.options.i18nPath) {
> 	i18nPath = this.options.i18nPath;
> 	this.i18nPath = this.options.i18nPath;
> }
...
> langJs = i18nPath + 'elfinder.' + lang + '.js',
...
> helpSource = fm.i18nPath + 'help/%s.html';

It's true ??? Working...

**Comment by nao-pon** [comment]
@fortcms I'll add an option `i18nBaseUrl`. Thanks! 👍
