### ISSUE TITLE
commandsOptions : preference

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2708]
None in wiki...
https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#commands

**Comment by nao-pon** [comment]
The wiki is not complete yet.

> Note: This page is in progress and as such will not list everything. For more options and further documentation, see inside the js/elFinder.options.js file.

Anyone can edit the wiki freely. Everyone's participation is always welcome.
