### ISSUE TITLE
my i18n recommendations

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2709]
1 Language files self switch language when connected (then you cannot use the 'lang' option).
2 Do not include the language file in the final build.
3 If I did not connect the file of language and decided to use automatic loading using the “lang” option, then it is necessary to make the path to the files dynamic.

**Comment by nao-pon** [comment]
@fortcms Do you mean that you want to change the default language?

**Comment by fortcms** [comment]
@nao-pon The default language should always be a separate file.

**Comment by nao-pon** [comment]
@fortcms The language "en" is a fallback language and is mandatory for the system. If you want the default language other than "en" when browser language is not in elFinder language file, use customized main.js instead of main.default.js.
