### ISSUE TITLE
disable toolbarExtra. How?

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2710]
i want disable for all...

**Comment by nao-pon** [comment]
@fortcms There is an option [`ui`](ui) of client options.

```javascript
ui: ['tree', 'path', 'stat'],
```

**Comment by nao-pon** [comment]
You can set next settings when this issue fixed.

```javascript
uiOptions : {
    toolbarExtra : {
        // also displays the text label on the button (true / false / 'none')
        displayTextLabel: 'none',
        // show Preference button into contextmenu of the toolbar (true / false)
        preferenceInContextmenu: false
    }
}
```

**Comment by fortcms** [comment]
@nao-pon DO NOT forget that the “Settings” button is on the screen when it is disabled.

> bootCallback : function(fm, extraObj){
> 					delete fm.commands.preference;
> 				}
