### ISSUE TITLE
Basket list of selected files with download option to send in email

### ISSUE THREAD

**Issue by jancarlopacanza** [Studio-42/elFinder#2711]
Hi,

I am just starting to implement this great file manager for web. 
I am using 2.1.x nightly build. So my question is, how can I implement such requirements:

1.) Add checkbox to each items for multiple selection
2.) Live preview of selected items that will be shown at the right sidebar (like a basket list)
3.) With the selected files, the user can choose between downloading the files (as zip) or sending the files by e-mail. If by e-mail the user must enter an e-mail address (probably a simple popup form)

I hope you can help me with this :)

Thanks

**Comment by nao-pon** [comment]
@jancarlopacanza 

1. There is a client option [`uiOptions.cwd.showSelectCheckboxUA`](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L765-L766).
2. There is a client option [`commandsOptions.quicklook.docked`](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L322-L323).
3. It is necessary to expand and implement the volume driver yourself.

**Comment by jancarlopacanza** [comment]
Hi @nao-pon  thanks for the response.

I have tried and confirmed this to be working. Thank you 👍 
> There is a client option uiOptions.cwd.showSelectCheckboxUA.

On this one
> There is a client option commandsOptions.quicklook.docked.

After trying this, I was able to show and moved the navdock (quicklook) to the right sidebar. However the default functionality of quicklook does not fit with what I wanted to do. Therefore, can you show me how to display selected items in a list view style with thumbnail column and name column only (not as showing only the number of items selected). _Please advise if I need to create a separate issue for this_

With regards to this one
> It is necessary to expand and implement the volume driver yourself.

My apology that I am clueless on how will I start doing this :( so I will be needing your expert guide again on this one. _Please advise if I need to create a separate issue for this_

**Comment by nao-pon** [comment]
@jancarlopacanza Please make a new Issue with detailed explanation as much as possible if requested about the behavior of Quick Look. However, I do not know if it will be implemented.

Unfortunately there is no detailed technical documentation of elFinder. Please understand by reading the source code and implement it. (I also did so). I think that technical data should be present, but at the moment human resources are not enough.

Thanks!

**Comment by jancarlopacanza** [comment]
Created a new issue for 
> @jancarlopacanza Please make a new Issue with detailed explanation as much as possible if requested about the behavior of Quick Look. However, I do not know if it will be implemented.

https://github.com/Studio-42/elFinder/issues/2719#issue-370489359


Will do this
> Unfortunately there is no detailed technical documentation of elFinder. Please understand by reading the source code and implement it. (I also did so). I think that technical data should be present, but at the moment human resources are not enough.

Thanks for your time answering my questions @nao-pon
