### ISSUE TITLE
Usage of Zero Width Space #8203 in info.js

### ISSUE THREAD

**Issue by nanghele** [Studio-42/elFinder#2712]
Hi,
I saw in js/commands/info.js  is used the zero width space  entity #8203 to mark the any single element of a file path. 
As you can see in the screenshot below the info box displays correctly the informations but when I copy the path displayed  and I past it in a browser  I get a 404 error since the browser considers the #8203 as a regular char.

Is it possible to remove  #8203 from the displayed path ?

![image](https://user-images.githubusercontent.com/11394020/46858911-a2240880-ce0c-11e8-88c6-e9e770f6ee11.png)

**Comment by fortcms** [comment]
I support this question

**Comment by nao-pon** [comment]
@nanghele , @fortcms "Zero Width Space" is inserted for the purpose of appropriately breaking a long path when the dialog width is narrow. If you want to get the item URL, right click on the "link" item and obtain the URL.

**Comment by fortcms** [comment]
@nao-pon the link to the entry point (

**Comment by nanghele** [comment]
@nao-pon in the screenshot the field "Percorso" is not a link. It would be nice an useful to copy this path string  and paste into a browser as a part of URI without bringing that special char.

**Comment by nao-pon** [comment]
OK, I see. I'll make implement remove ZWSP with mousedown event.
