### ISSUE TITLE
netmount - not work (

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2714]
<img width="895" alt="netmount_elf" src="https://user-images.githubusercontent.com/17702803/46881770-28643d00-ce55-11e8-9487-58982d8e32a2.png">

**Comment by nao-pon** [comment]
@fortcms There is a bug in environments where network mount is not enabled, so I will fix this. Thanks! 👍

**Comment by fortcms** [comment]
@nao-pon What to add to the connector for be show the list?

**Comment by nao-pon** [comment]
@fortcms Please check `elFinder::$netDrivers` of [connector.minimal.php.dist](https://github.com/Studio-42/elFinder/blob/master/php/connector.minimal.php-dist) .

**Comment by fortcms** [comment]
@nao-pon Thanks

**Comment by bgbruno** [comment]
Hello @nao-pon I added that "elFinder::$netDrivers" and nothing happened.

Q can you help? how can I debug this?
