### ISSUE TITLE
I can not create hidden files starting with dots

### ISSUE THREAD

**Issue by ji-ryoo** [Studio-42/elFinder#2716]
I can not create new .htaccess etc files on elfinder.
Version is 2.1.42

'accessControl' => 'access' is commented out.

I can drag and drop .htaccess onto elfinder.

I allow filenames starting with dots using 'acceptedName'.
That's it .txt and .css can be created. (File name starting from dot)

Attempting to create .htaccess disappears.

How can I make it possible to create .htaccess from right click on elfinder?

By the way, it was done in Ver 2.1.29.

**Comment by nao-pon** [comment]
@ji-ryoo I checked with... on the Nightly build.
```php
'accessControl' => null,
'attributes'    => array(),
'acceptedName'  => '/^[^\/\0]+$/',
```
It can...
- Make a file ".htaccess" was OK
- Edit was OK
- Preview was OK
- Delete  was OK

**Comment by ji-ryoo** [comment]
I can it on the Nightly build.

Thank you !
