### ISSUE TITLE
[js:core] implementation of theme changer

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2720]
Plz, add themesBasePath, themes, themes in preference and author (maybe parse comment in css (if exits)) of theme in about the software.

**Comment by fortcms** [comment]
next request of fix (see screen)
<img width="894" alt="opera _2018-10-16_231126_localhost" src="https://user-images.githubusercontent.com/17702803/47044691-836d9b00-d199-11e8-8e6c-be58ae91ac90.png">

**Comment by fortcms** [comment]
@nao-pon Plz, delete:

> html.push(sep);
> html.push('<div class="'+lic+'">'+fm.i18n('icons')+': Pixelmixer, <a href="http://p.yusukekamiyamane.com" target="_blank">Fugue</a>, <a href="https://icons8.com" target="_blank">Icons8</a></div>');

I'm not use this icon...

**Comment by nao-pon** [comment]
@fortcms 

>I'm not use this icon...

They are included in the distribution package and can not be deleted.

**Comment by fortcms** [comment]
@nao-pon Create new tab "Theme info" similar as 'Help'

**Comment by nao-pon** [comment]
@fortcms There is a tab "Theme".

**Comment by fortcms** [comment]
@nao-pon Where can I download themes shown on the screen?)

**Comment by fortcms** [comment]
@nao-pon I thought you would do differently.
Drop-down list of topics and their instant applyed.
And the tab in the "about topic" in the "help".

**Comment by nao-pon** [comment]
Please try https://github.com/nao-pon/elfinder-theme-manifests .

**Comment by fortcms** [comment]
i will test it tomorrow
