### ISSUE TITLE
Questions about css

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2724]
I want to use a icon not of "accept" in contextmenuToolbar.
<img width="893" alt="default" src="https://user-images.githubusercontent.com/17702803/47084162-65e11580-d21b-11e8-8d2e-b44a6972fde5.png">
Where else is used .elfinder-button-icon-accept ??

p.s. Do not close the topic. I will write more questions.

**Comment by fortcms** [comment]
class .elfinder-symlink not use now ?

**Comment by fortcms** [comment]
> /* for CSS style priority to ui-state-disabled - "background-image: none" */
> .elfinder .elfinder-button-icon.ui-state-disabled{
> 	background-image: url('../../img/scripts/elfinder/toolbar.png') !important;
> }

Not actual ?
Could not create this situation.

**Comment by fortcms** [comment]
> 2700 .elfinder-spinner{

Not actual ?

**Comment by nao-pon** [comment]
@fortcms Please grep search in js directory about CSS class name.

**Comment by fortcms** [comment]
@nao-pon I searched and none results

**Comment by nao-pon** [comment]
> Where else is used .elfinder-button-icon-accept ??

It is also used in the reload command.

> background-image: url('../../img/scripts/elfinder/toolbar.png') !important;

"../../img/scripts/elfinder/toolbar.png" is not in the source of elFinder.

> 2700 .elfinder-spinner{
 
```
Searching 123 files for "elfinder-spinner"

js/commands/preference.js:
  117  				$.each(fm.options.themes, function(id, val) {
  118  					var opt = $('<option class="elfinder-theme-option-'+id+'" value="'+id+'">'+fm.i18n(id)+'</option>'),
  119: 						dsc = $('<fieldset class="ui-widget ui-widget-content ui-corner-all elfinder-theme-list-'+id+'"><legend>'+fm.i18n(id)+'</legend><div><span class="elfinder-spinner"/></div></fieldset>'),
  120  						tm;
  121  					themeSel.append(opt);
  122  					list.append(dsc);
  123  					tm = setTimeout(function() {
  124: 						dsc.find('span.elfinder-spinner').replaceWith(fm.i18n(['errRead', id]));
  125  					}, 10000);
  126  					fm.getTheme(id).always(function() {
  ...
  148  						val = val.add(dl);
  149  						val = val.add($('<div class="elfinder-preference-theme-btn"/>').append($('<button class="ui-button ui-corner-all ui-widget"/>').data('themeid', id).html(fm.i18n('select'))));
  150: 						dsc.find('span.elfinder-spinner').replaceWith(val);
  151  					}).fail(function() {
  152: 						dsc.find('span.elfinder-spinner').replaceWith(fm.i18n(['errRead', id]));
  153  					});
  154  				});

js/commands/rm.js:
   15  				cwd = fm.cwd().hash,
   16  				descs = [],
   17: 				spinner = fm.i18n('calc') + '<span class="elfinder-spinner"/>',
   18  				dialog, text, tmb, size, f, fname;
   19  			
   ..
   85  			if (getSize) {
   86  				getSize = fm.getSize($.map(files, function(f) { return f.mime === 'directory'? f.hash : null; })).done(function(data) {
   87: 					dialog.find('span.elfinder-spinner').parent().html(fm.i18n('size')+': '+data.formated);
   88  				}).fail(function() {
   89: 					dialog.find('span.elfinder-spinner').parent().html(fm.i18n('size')+': '+fm.i18n('unknown'));
   90  				}).always(function() {
   91  					getSize = false;

js/extras/editors.default.js:
  693  							fontSize: '16pt'
  694  						})
  695: 						.html(fm.i18n('nowLoading') + '<span class="elfinder-spinner"/>')
  696  						.appendTo(ifm.parent()),
  697  					getType = function(mime) {
  ...
 2016  							fontSize: '16pt'
 2017  						})
 2018: 						.html(fm.i18n('nowLoading') + '<span class="elfinder-spinner"/>')
 2019  						.appendTo(ifm.parent()),
 2020  					cdata = function() {
 ....
 2423  							fontSize: '16pt'
 2424  						})
 2425: 						.html('<span class="elfinder-edit-loadingmsg">' + fm.i18n('nowLoading') + '</span><span class="elfinder-spinner"/>')
 2426  						.appendTo(ifm.parent()),
 2427  					_url = null,

10 matches across 3 files
```

**Comment by johnfort** [comment]
> "../../img/scripts/elfinder/toolbar.png" is not in the source of elFinder.

see line 1307

> It is also used in the reload command.

I do not understand what is the function there? I was looking at iphone
Plz, rename class for "Text label"

**Comment by johnfort** [comment]
U renamed class="elfinder-spinner" in js/commands/rm.js ))) Thanks

**Comment by johnfort** [comment]
@nao-pon U forgot about
.elfinder-rtl .elfinder-cwd-view-list .elfinder-perms
.elfinder-rtl .elfinder-cwd-view-list .elfinder-lock
.elfinder-rtl .elfinder-cwd-view-list .elfinder-symlink

<img width="448" alt="opera _2018-10-22_182843_studio-42 github io" src="https://user-images.githubusercontent.com/17702803/47301796-78e35380-d628-11e8-8e66-1dffe7ca90d4.png">
![opera _2018-10-22_182943_localhost](https://user-images.githubusercontent.com/17702803/47301802-7a148080-d628-11e8-922f-d385fb4a9cbd.png)

**Comment by nao-pon** [comment]
@johnfort Thanks! 👍

**Comment by johnfort** [comment]
@nao-pon There is a difference in .std42-dialog and .elfinder-dialog ?

**Comment by nao-pon** [comment]
@johnfort It is before I participate in development, so I do not know the clear meaning.

**Comment by johnfort** [comment]
@nao-pon 
<img width="448" alt="opera _2018-10-25_181431_studio-42 github io" src="https://user-images.githubusercontent.com/17702803/47511049-0a99cd80-d882-11e8-8eef-b4363b17af2a.png">
The buttons overlay on the text.

**Comment by nao-pon** [comment]
@johnfort In the case of long file names, that can not be helped.

**Comment by johnfort** [comment]
@nao-pon Plz, change places for elements.
<img width="680" alt="opera _2018-10-25_181431_studio-42 github io" src="https://user-images.githubusercontent.com/17702803/47515290-281f6500-d88b-11e8-9de6-7b87f9f0e00c.png">

**Comment by johnfort** [comment]
@nao-pon see L3076 /elfinder.css, property    

>  word-break: break-word;

not work in FireFox! Replace to word-break: break-all;

**Comment by nao-pon** [comment]
@johnfort The quick look title bar does not break, the overflowed part is not displayed.

![fireshot capture 30 - test here_elfinder - web fi_ - https___studio-42 github io_elfinder_ elf_l2_lw](https://user-images.githubusercontent.com/1412630/47546435-48533080-d92c-11e8-86ed-815f021c70be.png)
![fireshot capture 31 - test here_elfinder - web fi_ - https___studio-42 github io_elfinder_ elf_l2_lw](https://user-images.githubusercontent.com/1412630/47546437-49845d80-d92c-11e8-9377-a9ee59bf5a9a.png)

> not work in FireFox! Replace to word-break: break-all; or add overflow-wrap: break-word;

I'll fix it. Thanks! 👍

**Comment by nao-pon** [comment]
Is there any functional problem as the buttons overlap with titles on the quick look?

Then the vertical scroll bar problem will not be reproduced in Chrome, Firefox, Opera. I do not know how to improve with IE and Edge.

**Chrome**
![chrome](https://user-images.githubusercontent.com/1412630/47564735-f4af0a00-d960-11e8-9f89-d036d092c1b9.png)
**Firefox**
![firefox](https://user-images.githubusercontent.com/1412630/47564736-f547a080-d960-11e8-8bd7-e38cf5741d3e.png)
**Opera**
![opera](https://user-images.githubusercontent.com/1412630/47564737-f547a080-d960-11e8-8fd3-420aa98242d9.png)

**Comment by nao-pon** [comment]
@johnfort Please make another Issue for different issues.

**Comment by johnfort** [comment]
@nao-pon Of course there is a problem with the function. In the style that I draw, it merges into one and for beauty I want to use dots.

MS Edge ? I'll think about it...
