### ISSUE TITLE
Go to parent in workzone when list view

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2726]
The item "go to parent" must be on work zone as in "TotalComander", "FAR"...
This is real need functionality...
<img width="342" alt="default" src="https://user-images.githubusercontent.com/17702803/47117456-14fa0d00-d26d-11e8-9261-b797ed503a83.png">

**Comment by nao-pon** [comment]
@fortcms Please use a client option `uiOptions.cwd.oldSchool`. see https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L801-L802

**Comment by fortcms** [comment]
@nao-pon Oh, big thanks 👍
