### ISSUE TITLE
how can i open office files using pdfjs

### ISSUE THREAD

**Issue by shiyee** [Studio-42/elFinder#2728]
I am writing a website in local , we can't open office files in intranet. 
now my solution is, when upload a file to server, the FolderMonitor and bat will convert it to pdf. this is ok..
but , i can't get the path of pdf file, how can i get the real path , then i can open it using pdfjs...
some body help me ? thans a lot

**Comment by nao-pon** [comment]
@shiyee If you convert from the original file location with certain rules (such as changing only the extension), there is a method to specify a new plugin by referring to the [PDF preview plugin](https://github.com/Studio-42/elFinder/blob/master/js/commands/quicklook.plugins.js#L344-L392) and replacing the URL.

**Comment by nao-pon** [comment]
@shiyee Please check #2742 to fix this issue. Thanks!

**Comment by shiyee** [comment]
thank you very much👏👏
