### ISSUE TITLE
client bug (empty the folder when no permission)

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2729]
Showed search dialog(( And no destroy...
<img width="893" alt="opera _2018-10-18_220253_localhost" src="https://user-images.githubusercontent.com/17702803/47177701-d2463c80-d321-11e8-8808-00f1582a096d.png">

> array('pattern' => '/(\.ElFinder_quarantine)$/i',
> 	'read' => false,
> 	'write' => true,
> 	'locked' => false
> )

**Comment by nao-pon** [comment]
@fortcms Thanks! 👍
