### ISSUE TITLE
Preference need restructure

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2731]
Lang, dialog, reset grouped by Other. Delete icons size...
<img width="892" alt="opera _2018-10-19_172629_localhost" src="https://user-images.githubusercontent.com/17702803/47224549-77b1ec80-d3c4-11e8-8387-227d34d9d0c7.png">
and I want hide any conf

**Comment by nao-pon** [comment]
@fortcms I'll add command option `width` and `height`. And you can hide any preferences with an option `prefs`.

see https://github.com/Studio-42/elFinder/blob/master/js/commands/preference.js#L32

**Comment by fortcms** [comment]
@nao-pon I known about it (https://github.com/Studio-42/elFinder/blob/master/js/commands/preference.js#L32)
If you add more settings in the future, I may not know about them.
I want to specify only hidden settings.

**Comment by fortcms** [comment]
I believe that the size of the icons here is not needed. Or add sorting ..

**Comment by nao-pon** [comment]
It is meaningful to be able to remember it because you can change the icon size. In addition, the last value is saved automatically for sorting. As for the dialog size, there are many items on the All tab and it is meaningful that the user can change the size of the dialog.

**Comment by nao-pon** [comment]
If you need your own configuration dialog, you can replace the default command with the connector setting.

```
'uiCmdMap' => array('preference' => 'mypreference')
```
