### ISSUE TITLE
'Bind' not working

### ISSUE THREAD

**Issue by dogmaxpeppe** [Studio-42/elFinder#2732]
I want to write a callback that checks some things before uploading. I'm trying to binding the callback like documentation says, but it's like it ignores completely the binding.

Here's the code:

`$opts = array(
    'bind' => array(
        'upload' => 'uploadCheckSize',
    ),
	'roots' => array(
		...
	)
);

function uploadCheckSize($cmd, $result, $args, $elfinder)
{
    ...
    return false;
}`

I tested this callback putting a return with false, so it would never upload anything. Instead, everything is uploaded normally and even if I try to "brake up" the program inserting a fake callback in bind ('uploadUndefined' instead of 'uploadCheckSize') it continues to upload everything.

What am I doing wrong?

**Comment by nao-pon** [comment]
@dogmaxpeppe Please check related issue https://github.com/Studio-42/elFinder/issues/1657 .
