### ISSUE TITLE
I need mini fix dialog-confirm-rm

### ISSUE THREAD

**Issue by fortcms** [Studio-42/elFinder#2733]
<img width="472" alt="default" src="https://user-images.githubusercontent.com/17702803/47242730-5ec32e80-d3f8-11e8-9d48-6abb6d06c499.png">

**Comment by fortcms** [comment]
😆

**Comment by nao-pon** [comment]
@fortcms OK, I'll fix it. Thanks! 👍

**Comment by UnreALi** [comment]
@johnfort your theme looks beautiful. 👍  How can I acquire.

**Comment by johnfort** [comment]
@UnreALi free for all
https://github.com/johnfort/elFinder.themes

**Comment by UnreALi** [comment]
@johnfort tenks good job
