### ISSUE TITLE
double dialog of error (Invalid folder name)

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2734]
<img width="705" alt="default" src="https://user-images.githubusercontent.com/17702803/47255478-907cd980-d47a-11e8-9d5c-c941d68be9fe.png">
Directory ".ElFinder_trash" is trash.
If there is full access to the directory.

**Comment by nao-pon** [comment]
@fortcms Please check your connector configuration [`acceptedName`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#acceptedname).

**Comment by nao-pon** [comment]
Please let me know the procedure to reproduce that state.

**Comment by fortcms** [comment]
Connector:

> array(
	'id'            => '1',
	'driver'        => 'Trash',
	'path'          => SYS_PATH_ROOT . SYS_DIR_TEMP . '.ElFinder_trash',
	'winHashFix'    => DIRECTORY_SEPARATOR !== '/',
	'dateFormat' 	=> 'd.m.Y H:i:s',
	'tmbCrop' 		=> false,
	'tmbSize' 		=> 96,
	'tmbPath'		=> SYS_PATH_ROOT . SYS_DIR_TEMP . '.ElFinder_tmb',
	'tmbURL'		=> GetHost() . '/' . SYS_DIR_ROOT . SYS_DIR_TEMP . '.ElFinder_tmb',
	'uploadDeny'    => array(''),
	'uploadAllow'   => array('all'),
	'uploadOrder'   => array('deny', 'allow')
)

1. Click "Empty folder"
2. Showed dialog: Searching files
3. Showed dialog: Reading folder information
4. Showed dialog: Checking destination folder (1)
5. Showed two dialogs about  of error

**Comment by fortcms** [comment]
@nao-pon I'm not talking about the connector. About the duplicate message.

**Comment by nao-pon** [comment]
I checked with...
```php
array(
	'driver' => 'Trash',
	'path' => '../.ElFinder_trash',
	'uploadDeny' => array(''),
	'uploadAllow' => array('all'),
	'uploadOrder' => array('deny', 'allow')
),
```
There aren't any problems. And, The screenshot you presented is different from normal behavior. "Unable to create folder ".ElFinder_trash"." This is never displayed with the empty command.
