### ISSUE TITLE
Question about error in rar.js

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2736]
<img width="883" alt="default" src="https://user-images.githubusercontent.com/17702803/47266803-1a44a980-d544-11e8-98a2-66de2198cbba.png">

**Comment by nao-pon** [comment]
@johnfort It may be because the file size is too large. Please check if there is a problem with a small file size of about several megabytes. It may be better to limit file size.

**Comment by johnfort** [comment]
@nao-pon I checked on an empty archive. Error repeated.

**Comment by nao-pon** [comment]
@johnfort The rar preview passes the item URL to the rar library. It seems that the URL can not be processed by the rar library for some reason. You can disable rar preview by setting ui option cdns.rar to NULL.

```javascript
cdns: { rar : null }
```

**Comment by nao-pon** [comment]
@johnfort Since rar gets data via the URL via the browser, even if it is a local host, there is no problem if it can access the URL.

You can find out why data can not be acquired with developer tools and so on. If you can not get the data please disable rar preview.

And if you solve, do not forget to close this issue.

**Comment by johnfort** [comment]
@nao-pon For me, it does not matter now. If you have not found an error, then the problem is closed.
I want to see a new viewer:
Quick view only for certain types, and for all others, the "Browse" button.
I want to see the "Delete" button. For example, when cleaning a photo gallery, you need the Delete button.
I want a swipe on left and on right for mobile devices.

**Comment by nao-pon** [comment]
I have no problem with rar preview so I will close it.
