### ISSUE TITLE
Improve viewer

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2737]
Maybe add commands: delete and download, edit for editable (text - textarea, image - image editor) ?
Edit is not important, but the first two are very necessary.

How can I configure the opening of all files through the default viewer?

**Comment by nao-pon** [comment]
@johnfort I can not understand exactly what you want. Please let me know which command you want to do.

**Comment by johnfort** [comment]
@nao-pon double clicking on the file opens it in a popup. It is necessary in the viewer.

**Comment by nao-pon** [comment]
Please try client options [`commandsOptions.open.selectAction`](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L314-L316) and [`commandsOptions.preference.selectActions`](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L639-L641).

**Comment by johnfort** [comment]
> commandsOptions: {
					open: {
						selectAction: 'quicklook'
					}
				}
