### ISSUE TITLE
Unable to access file informations after upload on Javascript

### ISSUE THREAD

**Issue by dogmaxpeppe** [Studio-42/elFinder#2740]
I want to access to filenames of file uploaded after an upload action. I launched a console.log(event) on event object in callback to see how to access files, and there is a property called "data", like this:

`w.Event {type: "upload", timeStamp: 1540304894260, jQuery331007710222095257557: true}
altKey: (...)
bubbles: (...)
button: (...)
buttons: (...)
cancelable: (...)
changedTouches: (...)
char: (...)
charCode: (...)
clientX: (...)
clientY: (...)
ctrlKey: (...)
data: {added: Array(1), removed: Array(0), changed: Array(1), debug: {…}, _multiupload: false}
...`

Unfortunately, I can only see it but I cannot access it when I try to do `event.data`. How can I access to this property?

**Comment by nao-pon** [comment]
@dogmaxpeppe `event.data.added` is files infometion array.

```javascript
elFinderInstance.bind('upload', function(e, fm) {
    fm.log(e.data);
});
```

**Comment by dogmaxpeppe** [comment]
> @dogmaxpeppe `event.data.added` is files infometion array.
> 
> ```js
> elFinderInstance.bind('upload', function(e, fm) {
>     fm.log(e.data);
> });
> ```

Ok, but how can I save it into a variable? I need them to log these informations to the backend. I tried to assign with variable = fm.log(e.data) but it didn't work.

**Comment by nao-pon** [comment]
@dogmaxpeppe That is basic in JavaScript.

```javascript
var data = e.data;
// or for Added items
var files = e.data.added || [];
```

**Comment by dogmaxpeppe** [comment]
> @dogmaxpeppe That is basic in JavaScript.
> 
> ```js
> var data = e.data;
> // or for Added items
> var files = e.data.added || [];
> ```

Yep sorry I've resolved it, I understood that in that bind you can access to data not only with log, but normally as usual. Instead, in another bind you can't, so it confused me.

Thanks for help.
