### ISSUE TITLE
Preview PDF with android's system

### ISSUE THREAD

**Issue by MisterOl71** [Studio-42/elFinder#2743]
Hi !
I have a server in a private network. When i preview a PDF's file with my computer, it's ok. When i trie to do the same thing with my android's phone, elfinder try to open the docs.google.com.
Where i can fix that ?
Thanks !

**Comment by nao-pon** [comment]
@MisterOl71 If GoogleDocs preview is not available due to network restrictions, please disable GoogleDocs preview. (also sharecad and officeOnline)

```javascript
quicklook : {
	// to enable CAD-Files and 3D-Models preview with sharecad.org
	sharecadMimes : [],
	// to enable preview with Google Docs Viewer
	googleDocsMimes : [],
	// to enable preview with Microsoft Office Online Viewer
	// these MIME types override "googleDocsMimes"
	officeOnlineMimes : []
}
```

**Comment by nao-pon** [comment]
@MisterOl71 Please check #2742 .

**Comment by MisterOl71** [comment]
It's a perfect match !
Thanks
