### ISSUE TITLE
css: need mini fix for spinner

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2748]
open: elFinder/css/dialog.css
see line: 147 (.elfinder-spinner) and 475 (.elfinder-info-spinner)
remove lines: 475-481
replace lines 147-154 to:

> .elfinder-spinner,
.elfinder-info-spinner {
    display: inline-block;
    margin: 0 5px;
    width: 14px;
    height: 14px;
    background: url("../../img/scripts/elfinder/spinner-mini.gif") center center no-repeat;
    vertical-align: inherit;
}

<img width="694" alt="default" src="https://user-images.githubusercontent.com/17702803/47576085-4b5e1900-d94c-11e8-8ec6-37f4751a4c72.png">
Why do this? see next..
<img width="476" alt="default" src="https://user-images.githubusercontent.com/17702803/47576385-025a9480-d94d-11e8-8c59-6b4558df8e16.png">
remove lines: 462-464

And add

> .elfinder-rtl .elfinder-info-tb tr td:first-child {
    text-align: left;
}

**Comment by johnfort** [comment]
@nao-pon add class .elfinder-spinner for:
.elfinder-resize-spinner
.elfinder-navbar-spinner

**Comment by nao-pon** [comment]
@johnfort "elfinder-navbar-spinner" will be integrated into "elfinder-spinner". On the other hand, since "elfinder-resize-spinner" is actually a progress bar, it will not be integrated. Thanks!

**Comment by johnfort** [comment]
@nao-pon All that is undefined, abstract, is a spinner. In fact, the progress bar is not used anywhere =)

**Comment by nao-pon** [comment]
@johnfort I'll change CSS class name `elfinder-resize-spinner` to `elfinder-resize-loading`
