### ISSUE TITLE
Problem in mobile with tabs

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2749]
If I touch tab in workzone, I have drop menu. 
I can’t drag tabs or resize. The menu is interfering.

**Comment by nao-pon** [comment]
@johnfort Please try to call `elfinderInstance.disable()` when the drop menu is opened.

**Comment by nao-pon** [comment]
I understood. Taping the list header to sort it will display an unnecessary context menu, right? So I'll fix it. Thanks! 👍

**Comment by nao-pon** [comment]
01378c8 was make a bug that is impossible to open contextmenu of the file. I'll fix it.
