### ISSUE TITLE
elFinder cant't shows file system

### ISSUE THREAD

**Issue by Guille270** [Studio-42/elFinder#2750]
Hello,

I'm using elFinder to manage photos in a php server (Codeigniter 3), I used in a xampp local windows server and all goes perfect. Later I used a php 5.6.38 linux sever (Codeigniter 3) and all went well, but now I'm using the same project in another linux server (with php 5.6.38 and with 7.1) (Codeigniter 3) and crashes all time. The error is showing problems with deprecated functions and I dont know how I can fix the problem because the project is running in 2 different servers and all goes perfect. I post the error here. I tried to follow this [thread](https://github.com/Studio-42/elFinder/issues/2425) but didn't help me 

Can anyone helps me? Thank you so much.

/mnt/web117/d2/53/59095953/htdocs/intranet/uploads/39/956 <div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;"> <h4>A PHP Error was encountered</h4> <p>Severity: 8192</p> <p>Message: ini_set(): Use of iconv.internal_encoding is deprecated</p> <p>Filename: php/elFinder.class.php</p> <p>Line Number: 464</p> <p>Backtrace:</p> <p style="margin-left:10px"> File: /mnt/web117/d2/53/59095953/htdocs/intranet/application/vendor/studio-42/elfinder/php/elFinder.class.php<br /> Line: 464<br /> Function: ini_set	</p> <p style="margin-left:10px"> File: /mnt/web117/d2/53/59095953/htdocs/intranet/application/controllers/Explorer_c.php<br /> Line: 104<br /> Function: __construct </p> <p style="margin-left:10px"> File: /mnt/web117/d2/53/59095953/htdocs/intranet/index.php<br /> Line: 315<br /> Function: require_once </p> </div> <div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;"> <h4>A PHP Error was encountered</h4> <p>Severity: 8192</p> <p>Message: ini_set(): Use of mbstring.internal_encoding is deprecated</p> <p>Filename: php/elFinder.class.php</p> <p>Line Number: 467</p> <p>Backtrace:</p> <p style="margin-left:10px"> File: /mnt/web117/d2/53/59095953/htdocs/intranet/application/vendor/studio-42/elfinder/php/elFinder.class.php<br /> Line: 467<br /> Function: ini_set	</p> <p style="margin-left:10px"> File: /mnt/web117/d2/53/59095953/htdocs/intranet/application/controllers/Explorer_c.php<br /> Line: 104<br /> Function: __construct </p> <p style="margin-left:10px"> File: /mnt/web117/d2/53/59095953/htdocs/intranet/index.php<br /> Line: 315<br /> Function: require_once </p> </div>{"cwd":{"isowner":false,"ts":1540638672,"mime":"directory","read":1,"write":1,"size":0,"hash":"l1_Lw","name":"Tasacion","rootRev":"","options":{"path":"","url":"","tmbUrl":"","disabled":["chmod"],"separator":"\/","copyOverwrite":1,"uploadOverwrite":1,"uploadMaxSize":2147483647,"uploadMaxConn":3,"uploadMime":{"firstOrder":"deny","allow":["image","text\/plain","application\/pdf"],"deny":["all"]},"dispInlineRegex":"^(?:(?:image|video|audio)|application\/(?:x-mpegURL|dash\\+xml)|(?:text\/plain|application\/pdf)$)","jpgQuality":100,"archivers":{"create":["application\/x-tar","application\/x-gzip","application\/x-bzip2","application\/x-xz","application\/zip"],"extract":["application\/x-tar","application\/x-gzip","application\/x-bzip2","application\/x-xz","application\/zip"],"createext":{"application\/x-tar":"tar","application\/x-gzip":"tgz","application\/x-bzip2":"tbz","application\/x-xz":"xz","application\/zip":"zip"}},"uiCmdMap":[],"syncChkAsTs":1,"syncMinMs":10000,"i18nFolderName":0,"tmbCrop":1,"substituteImg":true,"csscls":"elfinder-navbar-root-local"},"volumeid":"l1_","locked":1,"isroot":1,"phash":"","url":"#elf_l1_Lw","root":"l1_Lw"},"options":{"path":"Tasacion","url":"","tmbUrl":"","disabled":["chmod"],"separator":"\/","copyOverwrite":1,"uploadOverwrite":1,"uploadMaxSize":2147483647,"uploadMaxConn":3,"uploadMime":{"firstOrder":"deny","allow":["image","text\/plain","application\/pdf"],"deny":["all"]},"dispInlineRegex":"^(?:(?:image|video|audio)|application\/(?:x-mpegURL|dash\\+xml)|(?:text\/plain|application\/pdf)$)","jpgQuality":100,"archivers":{"create":["application\/x-tar","application\/x-gzip","application\/x-bzip2","application\/x-xz","application\/zip"],"extract":["application\/x-tar","application\/x-gzip","application\/x-bzip2","application\/x-xz","application\/zip"],"createext":{"application\/x-tar":"tar","application\/x-gzip":"tgz","application\/x-bzip2":"tbz","application\/x-xz":"xz","application\/zip":"zip"}},"uiCmdMap":[],"syncChkAsTs":1,"syncMinMs":10000,"i18nFolderName":0,"tmbCrop":1,"substituteImg":true},"files":[{"isowner":false,"ts":1540638672,"mime":"directory","read":1,"write":1,"size":0,"hash":"l1_Lw","name":"Tasacion","rootRev":"","options":{"path":"","url":"","tmbUrl":"","disabled":["chmod"],"separator":"\/","copyOverwrite":1,"uploadOverwrite":1,"uploadMaxSize":2147483647,"uploadMaxConn":3,"uploadMime":{"firstOrder":"deny","allow":["image","text\/plain","application\/pdf"],"deny":["all"]},"dispInlineRegex":"^(?:(?:image|video|audio)|application\/(?:x-mpegURL|dash\\+xml)|(?:text\/plain|application\/pdf)$)","jpgQuality":100,"archivers":{"create":["application\/x-tar","application\/x-gzip","application\/x-bzip2","application\/x-xz","application\/zip"],"extract":["application\/x-tar","application\/x-gzip","application\/x-bzip2","application\/x-xz","application\/zip"],"createext":{"application\/x-tar":"tar","application\/x-gzip":"tgz","application\/x-bzip2":"tbz","application\/x-xz":"xz","application\/zip":"zip"}},"uiCmdMap":[],"syncChkAsTs":1,"syncMinMs":10000,"i18nFolderName":0,"tmbCrop":1,"substituteImg":true,"csscls":"elfinder-navbar-root-local"},"volumeid":"l1_","locked":1,"isroot":1,"phash":"","url":"#elf_l1_Lw"}],"api":"2.1034","uplMaxSize":"32M","uplMaxFile":"20","netDrivers":["ziparchive"],"maxTargets":1000,"textMimes":["application\/x-empty","application\/javascript","application\/json","application\/xhtml+xml","audio\/x-mp3-playlist","application\/x-web-config","application\/docbook+xml","application\/x-php","application\/x-perl","application\/x-awk","application\/x-config","application\/x-csh","application\/xml","application\/sql"]}

**Comment by nao-pon** [comment]
@Guille270 Please check with the latest version of elFinder or [Nightly Build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by Guille270** [comment]
> @Guille270 Please check with the latest version of elFinder or [Nightly Build](https://github.com/Studio-42/elFinder/archive/2.1.zip).
Thanks for reply. I'm working with CodeIgniter 3 I must do something special for this new version? I delete all files in my vendor/studio-42/elfinder and i paste all new files on it. I remove my view and I paste the "elFinder.html" (is on the zip) in my views folder. And i put the $connector in the url attribute on js. But I just see a white screen and a console error 

Uncaught SyntaxError: Unexpected token <                                  main.default.js:1

**Comment by nao-pon** [comment]
@Guille270 I do not know about CodeIgniter well, but probably the path to main.default.js is incorrect. You will first need to check elFinder without any integration.
