### ISSUE TITLE
html layout (title of dialogs)

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2752]
Naoki Sawada plz, see the code where the dialog box are created.
Not everywhere there is a single set of css classes.

Example,
help

> ui-widget-header ui-dialog-titlebar-close ui-corner-all elfinder-titlebar-button

pref

> ui-widget-header ui-dialog-titlebar-close ui-corner-all elfinder-titlebar-button elfinder-titlebar-button-right

edit

> ui-widget-header ui-dialog-titlebar-close ui-corner-all elfinder-titlebar-button elfinder-titlebar-button-right

**Comment by nao-pon** [comment]
@johnfort Each command has its own class name in the container of the dialog.

`elfinder-dialog-help`, `elfinder-dialog-preference` and `elfinder-dialog-edit`.

**Comment by johnfort** [comment]
Pay attention to elfinder-titlebar-button-right

**Comment by nao-pon** [comment]
@johnfort I do not understand the meaning well. The `elfinder-titlebar-button-right` class is given to buttons in the dialog header for Windows clients.

**Comment by nao-pon** [comment]
@johnfort Did you solve?

**Comment by nao-pon** [comment]
@johnfort OK, I understood. Also fix the dialog header of Quicklook so that it will be outputted in the same HTML structure as other dialogs. Also, unify "elfinder-platformWin" class to "elfinder-titlebar-button-right" class.
