### ISSUE TITLE
Uploading multiple files interrupted with dot files

### ISSUE THREAD

**Issue by dogmaxpeppe** [Studio-42/elFinder#2753]
When I try to upload multiple files or folders, if there is a file with an initial dot, the remaining files to upload will not be uploaded.

Example:
If I upload multiple files:

- `a.txt`
- `b.txt`
- `.filedotted`
- `c.txt`
- `d.txt`

`c.txt` and `d.txt` will not be uploaded.

This behavior occurs also when I upload folder. If I upload a folder with a initial dotted file, the remaining files to upload in that folder will not be uploaded. This problem doesn't affect subfolders or sibling folders, that will be uploaded correctly (obviously if there's not a initial dotted file).

**Comment by nao-pon** [comment]
@dogmaxpeppe Currently it is an action to cancel uploading when uploading errors occur, but I will modify it so that it will not cancel items that can be uploaded. Thanks! 👍
