### ISSUE TITLE
Issue on Mobile. Is Elfinder ready?

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#2756]
@nao-pon 

Only on mobile, not always, but most of the times elfinder not starting.
It does not even fire the "init" handler.

I am using "$().ready(function(){" to start the elfinder definition but anyway it seems in some cases, most of them, only on mobile it does not work.

It seems to me that the elfinder lib is not ready, is there a way to control this?

It is difficult for me to debug as it is a webview calling my html from an iOS app.
If I run the same on a PC I do not have issues.

Thanks as usual for your help.

Giorgio

**Comment by nao-pon** [comment]
@ghigio2000 Is [elFinder demo site](https://studio-42.github.io/elFinder/) displayed on your mobile device? At least I have not seen this problem.

**Comment by ghigio2000** [comment]
@nao-pon 
It is happening only in a webview called from the iOS app.
It does not happen in Safari from the same mobile device.

I know the webview browser of iOS app is not 100% like the Safari browser, but I frankly do not know how to debug it.

Do you have any suggestion?

**Comment by nao-pon** [comment]
@ghigio2000 About WebView, I do not have any solutions. I do not know it well.

**Comment by ghigio2000** [comment]
Thank you anyway
I hope I solved
