### ISSUE TITLE
Uploading .MSG files

### ISSUE THREAD

**Issue by BuffaloBrennan** [Studio-42/elFinder#2757]
Hi Everyone

Hopefully this will be easy.  I can use the connector to restrict uploads to specific types currently I have it configured as: 

         'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
         'uploadAllow'   => array('image', 'text/plain', 'application/pdf', 'text/csv', 
         'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
         'application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'),

However, my users need to upload files with the extensions **.MSG** files (Saved from Outlook) - can this be done?

Thank you in advance for any help given

**Comment by nao-pon** [comment]
@BuffaloBrennan In your environment, which MIME type is detected when uploading?

![capture_elfinder](https://user-images.githubusercontent.com/1412630/47855178-33443900-de27-11e8-9319-b9053682777c.png)

**Comment by BuffaloBrennan** [comment]
None it just says "Unable to upload "Test File.msg".  File type not allowed.

I have MS office 365 installed on my machine.  I've tried adding 'application/vnd.ms-outlook' to uploadAllow - but still getting exactly the same message.   

We have a work around of storing them as PDFs instead of .MSG files.... but it's nagging at me now... so brain needs to find a solution.

**Comment by BuffaloBrennan** [comment]
PS..   MS Outlook is also installed on the server and I MIME type for extenstion .MSG in IIS 7

**Comment by nao-pon** [comment]
Try the latest version or [Nightly Build](https://github.com/Studio-42/elFinder/archive/2.1.zip), can you see the MIME Type with the error message?

**Comment by BuffaloBrennan** [comment]
Installed the latest version... all the folders/files now have green pins showing they are locked... but that's the next stage.   The MIME is application/octet-stream - I'm sure I tried that one...

![image](https://user-images.githubusercontent.com/25584497/47940171-c0e45f00-dee1-11e8-8ac3-4cbe6337d001.png)

**Comment by BuffaloBrennan** [comment]
I've reverted back to the old version on the main server at the moment... as I can not figure out how to stop the files from being locked.... I'll try again on another development machine in the near future.

**Comment by BuffaloBrennan** [comment]
A HA... found the solution for this particular problem

I modified the file php\mime.types   and added msg to the application/octet-stream entry worked a treat (so far):

![image](https://user-images.githubusercontent.com/25584497/47941569-8e893080-dee6-11e8-92bf-0c43ba89c3d5.png)

**Comment by nao-pon** [comment]
@BuffaloBrennan 

> I modified the file php\mime.types and added msg to the application/octet-stream entry worked a treat (so far) and added 'application/octet-stream' to the allowUpload list

If non-administrator can upload the item it is very dangerous. "application/octet-stream" contains the executable file and includes the unknown file type.

The best bet is to add "application/vnd.ms-outlook" to `[additionalMimeMap](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#additionalMimeMap)` in the connector root setting. (require elFinder >= 2.1.22)

```php
'additionalMimeMap' => array(
    'msg:application/octet-stream' => 'application/vnd.ms-outlook',
    'msg:application/CDFV2-corrupt' => 'application/vnd.ms-outlook',
),
```
