### ISSUE TITLE
tabs - no single

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2758]
pref tabs:
does not have .ui-state-hover

help tabs:
have .ui-tabs-active only after click and stays there even after switching to another

online-converter tabs:
does not have .ui-tabs-selected

@nao-pon There is no single tabbed building model. Can you fix it?

**Comment by nao-pon** [comment]
@johnfort The online-converter tab uses the tabs plugin of jQuery - UI, but help and preferences are rendering by own script. This is because the tabs plugin is not mandatory. Therefore, I will modify it to be a class similar to the tabs plugin when rendering by own script. Thanks! 👍

**Comment by nao-pon** [comment]
Fixed at 5a3f78f4588cbec1f0084cfefeb649430c2de790 .
