### ISSUE TITLE
how to create a .json file

### ISSUE THREAD

**Issue by d0coco** [Studio-42/elFinder#2759]
How to create a .json file, and open it by new page, i want to get the callback function for click the edit file submenu ,  Can someone help me

**Comment by nao-pon** [comment]
@d0coco What did you try and what did not go wrong?

**Comment by d0coco** [comment]
I want to create a json file in elfinder and double-click to open it with another browser page

**Comment by nao-pon** [comment]
Have you added "application/json" to the [uploadable MIME-Type](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadAllow)?

**Comment by d0coco** [comment]
yes, I added it to the elfinder.mimetypes. Js file，But the right menu doesn't appear

**Comment by d0coco** [comment]
![image](https://user-images.githubusercontent.com/13317362/47947655-a0f18180-df5b-11e8-88f1-88b74abcb20b.png)
![image](https://user-images.githubusercontent.com/13317362/47947663-b9fa3280-df5b-11e8-9fed-5aa93920dea8.png)

**Comment by nao-pon** [comment]
> I added it to the elfinder.mimetypes. Js file

No, [`uploadable MIME-Type`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadAllow) is a connector root option. Please double check the [Wiki](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1).

**Comment by d0coco** [comment]
I see. Thank you.
How do I add my own button to the edit submenu
![image](https://user-images.githubusercontent.com/13317362/47947978-5b848280-df62-11e8-919a-1298ba3aa1e9.png)

**Comment by nao-pon** [comment]
@d0coco Please try set connector root option [`dispInlineRegex`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#dispInlineRegex).

Default value: `'^(?:(?:video|audio)|image/(?!.+\+xml)|application/(?:ogg|x-mpegURL|dash\+xml)|(?:text/plain|application/pdf)$)'`

To

`'^(?:(?:video|audio)|image/(?!.+\+xml)|application/(?:ogg|x-mpegURL|dash\+xml|json)|(?:text/plain|application/pdf)$)'`

Then... you will can open .json into new window by dblclick on the item in cwd.
