### ISSUE TITLE
chunk upload bug

### ISSUE THREAD

**Issue by laiyangwen** [Studio-42/elFinder#2762]
file1=  50M ,split by 10M
send 5 count is right,
but it  send 6 count,because of:
elFinder-2.1.42 efinder.full.js  line  6534:  

while(start <= blobSize) 

it should  update to:  while(start < blobSize)  

bug code :
`	chunked[chunkID] = 0;
							while(start <= blobSize) {
								chunk = blob[blobSlice](start, end);
								chunk._chunk = blob.name + '.' + (++chunks) + '_' + total + '.part';
								chunk._cid   = chunkID;
								chunk._range = start + ',' + chunk.size + ',' + blobSize;
								chunk._mtime = blobMtime;
								chunked[chunkID]++;
								`

**Comment by nao-pon** [comment]
@laiyangwen Yes, that's right. So, I'll fix it. Thanks! 👍
