### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by d0coco** [Studio-42/elFinder#2763]
![image](https://user-images.githubusercontent.com/13317362/48068582-24d29480-e20e-11e8-8a59-9a033f3cdd7b.png)

**Comment by johnfort** [comment]
@d0coco https://github.com/Studio-42/elFinder/blob/master/README.md#requirements

**Comment by d0coco** [comment]
Access elfinder.html times this error, but access elfinder.src. html was correct

**Comment by nao-pon** [comment]
@d0coco In the distribution package elfinder.html, load elfinder.min.js. It does not use elfinder.js. I guess you have customized something by yourself.

**Comment by d0coco** [comment]
i got it ,thank you
