### ISSUE TITLE
Math height. Fullscreen textarea

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2764]
deducts Padding =( May be use css box-sizing ?

**Comment by nao-pon** [comment]
@johnfort Specifically, which part?

**Comment by johnfort** [comment]
.elfinder-dialog-edit .elfinder-maximized ... -> .elfinder-edit-editor ...
I am use left & right padding for wrapper textarea

**Comment by nao-pon** [comment]
OK, I thought that designation of padding by inline to the maximize element is unnecessary so I will delete it. Thanks! 👍
