### ISSUE TITLE
 upload a big File and chunkEnable  ==false will case a js error

### ISSUE THREAD

**Issue by laiyangwen** [Studio-42/elFinder#2766]
2.1.42 
elfinder.full.js 6576
if ((fm.uplMaxSize && size + blobSize >= fm.uplMaxSize) || fcnt > fm.uplMaxFile){
							size = 0;
							fcnt = 1;
							c++;
						}
need change to: add chunkEnable  ,otherwise will cause a js error,when upload a big File and chunkEnable  ==false

if (chunkEnable && ((fm.uplMaxSize && size + blobSize >= fm.uplMaxSize) || fcnt > fm.uplMaxFile)) {
							size = 0;
							fcnt = 1;
							c++;
						}

**Comment by nao-pon** [comment]
@laiyangwen How about next?

'if ((fm.uplMaxSize && size + blobSize >= fm.uplMaxSize) || fcnt > fm.uplMaxFile) {'

to

`if ((fm.uplMaxSize && size + blobSize > fm.uplMaxSize) || fcnt > fm.uplMaxFile) {`
