### ISSUE TITLE
Fresh install not working

### ISSUE THREAD

**Issue by patackett** [Studio-42/elFinder#2767]
I just downloaded and installed version 2.1.42 following the simple steps:

 1. Download and unzip one of the [builds](#downloads) below to your PHP server
 2. Rename `/php/connector.minimal.php-dist` to `/php/connector.minimal.php`
 3. Load `/elfinder.html` in your browser to run elFinder

When I load elfinder.html in a browser I get a blank screen.  There are a couple of javascript errors but not seeing anything to troubleshoot the problem.  Any help would be appreciated.  Thanks

![image](https://user-images.githubusercontent.com/1315497/48580818-2e36bd80-e8ee-11e8-9ef2-ba22697019d3.png)

**Comment by nao-pon** [comment]
@patackett I checked 2.1.42, but there was no problem. What browser do you use?
