### ISSUE TITLE
Extremely slow transfer speeds

### ISSUE THREAD

**Issue by willi552** [Studio-42/elFinder#2772]
elFinder has very slow transfer speeds for me, both upload and download. I have attached a link where I am uploading a **~37MB** to two different servers (one in my country, one in different country) with identical configurations and the elFinder demo website.
Here is a screencast - https://streamable.com/sukuh. 
The elFinder demo website seems to be extremely fast compared to my own sites. Is it because I have configured elFinder improperly? My configuration is the same as the one that elFinder comes with when it is downloaded from Github, except for `connector.minimal.php`, where I have altered it to allow all file types for upload.
Please let me know if you need any other information.
Also, where can I find the elFinder configuration for the demo sites?

**Comment by nao-pon** [comment]
@willi552 It seems that the network transfer rate is slow or the server's processing capacity is low. The speed does not change with the setting of the item that can be uploaded.

**Comment by willi552** [comment]
I don't think it's because of the network transfer speed or processing speed because I am able to transfer files at regular speeds through SFTP or with a different web file manager. I also don't expect two different servers to have similar upload rates, as seen in the video. Server A is located in the next country over, hosted on Amazon Web Services on a t2.micro instance (1 vCPU, 1GiB RAM). Server B is hosted in my city with 4 vCPUs and 4GiB RAM.
I will try again today with different builds and see if that helps.

**Comment by willi552** [comment]
Actually, you are right. I tried running elFinder locally in Docker and it was faster. Thanks.
https://streamable.com/doax0
