### ISSUE TITLE
Missing HTTP Cookie From CKEditor PopUp

### ISSUE THREAD

**Issue by maa3x** [Studio-42/elFinder#2773]
Hi.

I'm using elFinder with Laravel and CKEditor. In the backend there is a middleware for checking access permissions to current route but it doesn't work for elFinder popups opened from CKEditor. I found there are no cookies sent to the server in that popups so the backend do not have access to request sessions and permissions check wont work.

What I have to do to add HTTP cookies to the request headers in the popup?

**Comment by nao-pon** [comment]
@maa3x The sending of cookies is completely under the control of the browser. If you use the Cross Origin Request, please deepen your understanding of Cross Origin Request.

**Comment by maa3x** [comment]
@nao-pon I know what is CORS and the elFinder is on the same origin as the page that open the pop-up to elFinder.
So we haven't CORS problem here.
