### ISSUE TITLE
How to hide "Also Treeview" sort option?

### ISSUE THREAD

**Issue by mauleous** [Studio-42/elFinder#2774]
Hi elFinder masters,

Is there a way to hide the "Also Treeview" sort option (both in context menu and in toolbar), and also make sure the treeview is always sorted alphabetically?

Cheers,
Maul

**Comment by nao-pon** [comment]
@mauleous At currently, there is no option like that, so I will make it possible with the ui option `sortAlsoTreeview : null`. Thanks! 👍
