### ISSUE TITLE
Not Compatible with Cyrillic

### ISSUE THREAD

**Issue by ArniXXX** [Studio-42/elFinder#2779]
Sometime you uses function basename. But this function too old and has a problem with Cyrillic sumbols.

Could you change your basename() to this?

```
array_pop(explode(DIRECTORY_SEPARATOR, $path));
```

Thanks!

**Comment by ArniXXX** [comment]
> @ArniXXX Please set the main option [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale) or the volume root setting [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale-1) appropriately.

Try it. It doesn't works.

**Comment by nao-pon** [comment]
@ArniXXX PHP's built-in function [basename()](https://php.net/manual/function.basename.php) functions normally by setting the locale correctly. Since the locale affects other functions, please properly specify the locale in which basename() functions properly.
