### ISSUE TITLE
open file without extension

### ISSUE THREAD

**Issue by bgbruno** [Studio-42/elFinder#2780]
Hello,

by default in #elfinder for detection file type I use file "mime.types"
but there is no definiction for extension like "no extension"

I have set "'mimeDetect' => 'internal'"
https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#mimeDetect
because I use more resolution for icons file type like "json, njs, mjs, flow" and many others

then I cannot open undetected "files without extension"

would be great set "no extension" or "all else extension" to open by default like "text"

Q is there any settings for that - or any idea where improve code?
https://stackoverflow.com/questions/53572543/open-file-without-extension-in-elfinder

**Comment by nao-pon** [comment]
@bgbruno Please use the volume driver option [`mimeTypeUnknown`](https://github.com/Studio-42/elFinder/blob/0c3079c505cdf1626677a5de41f8046831362426/php/elFinderVolumeDriver.class.php#L320-L321) (elFinder >= 2.1.43).

**Comment by bgbruno** [comment]
thx @nao-pon 

in that app I have deployed v2.1.11 - and I see that option was fixed @2018-11-24

also I have set $connector.php
`'mimeDetect' => 'internal'`

Q for what version that driver option is?
Q it's ok use that with "mimeDetect internal"?
Q pls I have to write that in $connector.php or overwrite $elFinderVolumeDriver.class.php ?

**Comment by nao-pon** [comment]
@bgbruno The `mimeTypeUnknown` option requires 2.1.43 or later. When using `'mimeDetect'=>'internal'`, all file types not defined in [`mime.types`](https://github.com/Studio-42/elFinder/blob/master/php/mime.types) will be of the MIME type specified by the `mimeTypeUnknown` option.
