### ISSUE TITLE
Event for a file that's too big

### ISSUE THREAD

**Issue by thany** [Studio-42/elFinder#2783]
I can't find which event to use to respond to files being uploaded that are too big. For wrong filetypes, I get a signal from `uploadfail` which is just perfect. I would expect the same event to be fired for files that are too big (but of the correct filetype).

I am getting the dialog that says my file was too big, which proves it does know about filesizes, and it is possible for 'something' to be fired. But what?

Is there another event that I'm missing? Is it a bug?

I'm on elfinder 2.1.42 and testing on the latest Firefox Dev.

**Comment by nao-pon** [comment]
@thany This is a bug. I will fix this. Thanks! 👍

**Comment by nao-pon** [comment]
@thany I misread the source code. The `uploadfail` event is triggered when an error is received from the backend. The data includes backend response. On the other hand, uploading may be canceled before being sent to the back end. For that, I will create a new event `xhruploadfail`. The data includes the file object that was about to be sent.

Rel. #2784

**Comment by nao-pon** [comment]
Fixed via 290e4588f3c1636cd5e6f7320c474ab0c0953944 .
