### ISSUE TITLE
Event uploadfail needs more information

### ISSUE THREAD

**Issue by thany** [Studio-42/elFinder#2784]
The `uploadfail` event contains very little information. If the filetype is not allowed, I would expect it to pass which filetype it blocked, or at least the filename. There's nothing on that in the event object.

There is also an array in there, in `event.data.removed`. I thought maybe that's the array of files removed from the upload, but then I'd expect it to contain information on the (single) file I dropped in. But alas, the array is empty. Not sure why; it's probably used for something else then, I guess.

So can we have more information in this event please?

Or does it already? I'm using elfinder 2.1.42.

**Comment by nao-pon** [comment]
See #2783 (make new event `xhruploadfail`).
