### ISSUE TITLE
Unable to drag and drop a file into an existing folder

### ISSUE THREAD

**Issue by JCharlesSL** [Studio-42/elFinder#2785]
Dear all,

I had not realized about this before.

It seems strange but after selecting and dragging the file, the mouse icon changes to crosshair and not-allowed, it is correct, but it also occurs when moving the dragged file over the existing folders.

I do not know why, but sometimes after many tests and/or changing the top toolbar to text label, it suddenly works, and then the folder is displayed surrounded by a blue border and the mouse icon changed to an arrow. Now, it is allowed to drop the file into that folder.

I have tested it by using different Internet browsers and the results were the same. The instance is created under a JQuery UI tab without any particular setting.

Thanks,

J Charles

**Comment by nao-pon** [comment]
@JCharlesSL There is a problem with event handling of the droppable element in the current version. There is a problem that event handling can not be performed correctly when the tree view width is large and it overlaps the lower layer of CWD. I will fix it. Thanks! 👍

**Comment by JCharlesSL** [comment]
You got it. Thanks a lot.
Glad to have helped.
