### ISSUE TITLE
File no found in "zipdl" in NFS share

### ISSUE THREAD

**Issue by Tab3r** [Studio-42/elFinder#2786]
Hi, we are using elFinder 2.1.40, and we found a strange bug.

We mounted a share directory with NFS in our linux machine on read-only mode, and define a local file system connector to this NFS share. When the user tries to download a directory as a ZIP file (zipdl command), the web brower returns an error "Error: Not file found", and the json returned show the following error:

`"WARNING: link(): Invalid cross-device link in elFinderVolumeDriver.class.php line 3907."`

I tried to figure out the problem, and i found that the link linux command cannot be used in different partitions in diferent devices. The function: `public function zipdl($hashes)` line 2455, only test if is a local filesystem and mark as "canLink" property to true, but not always is possible to do a hard link in linux.

Thank you, and i hope it can helps you to improve this fantastic library!

**Comment by Tab3r** [comment]
Hi, again.

We are still trying to figure out our error.

I commented the code in `function getItemsInHand($hashes, $dir = null, $canLink = null)` where the "link" is used... but still return the same error.

I put the NFS file system in read-write mode, `.quarentine` and `.tmb` directories were created, but still same error. 

I launched the url like: 
`connector?initial_folder=&cmd=zipdl&download=1&targets%5B%5D=l1_RVNU[..]UxJREFE&targets%5B%5D=5c06b[..]2&targets%5B%5D=AX_[..]D.zip&targets%5B%5D=application%2Fzip&AX_04_CALIDAD.zip`
And i got a 404, not found. 

I really don´t know which could be my next steps.

Thank you in advance.

**Comment by nao-pon** [comment]
@Tab3r The behavior looks odd. The zipdl command requires keeping of a PHP session. Is the client able to keeping the session?

Can you debug the next part of elFinder.class.php?

https://github.com/Studio-42/elFinder/blob/281a509c59ba5649c10490bdc5e0790dec3c60f0/php/elFinder.class.php#L1695-L1706

**Comment by Tab3r** [comment]
Thank you!...

Our app is reseting the session in every query.

Your advice it solves our problem.

Again, thank you!
