### ISSUE TITLE
cannot open without internet

### ISSUE THREAD

**Issue by aminbaik** [Studio-42/elFinder#2787]
Hello,
i cant open elfinder if i dont have internet connection on the client side.
should i have internet ? or anyway to resolve that ?
thanks.

**Comment by nao-pon** [comment]
@aminbaik Please save all JavaScript etc. read from CDN to your local and read it. Maybe, using "[elfinder.legacy.html](https://github.com/Studio-42/elFinder/blob/master/elfinder.legacy.html)" will be easier to migrate.

**Comment by aminbaik** [comment]
it's work thanks u :)
