### ISSUE TITLE
unzip problem

### ISSUE THREAD

**Issue by aminbaik** [Studio-42/elFinder#2793]
Hello,
I am running elfinder under iis with windows authentication and everything work fine ,
when I loging as administrator the extract option for zip files is working fine. but its not on the other users.
so what the problem ?
thanks.

**Comment by nao-pon** [comment]
@aminbaik It seems to be a file system write permission issue. Please specify the PHP writable directory in [`commonTempPath`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#commontemppath--217) of connector main option.
