### ISSUE TITLE
How to Upload a file to elfinder(Web File Manager) through console application using c#? I am completely new to elfinder. 

### ISSUE THREAD

**Issue by creedrahul** [Studio-42/elFinder#2795]
Hi All,
I am trying to add file to elfinder Web File Manager using the console application in c#. So far i have tried to use elfinderConnector but could not successfully add a file to the portal. Can someone please point me to some example that can help me. I am completely new to Elfinder.

Any help is appreciated. Thanks

**Comment by nao-pon** [comment]
@creedrahul Is it possible to solve by uploading directly to the file system on the Web server?
