### ISSUE TITLE
Custom Icons in Toolbar

### ISSUE THREAD

**Issue by alexandrovsergii** [Studio-42/elFinder#2797]
Is it possible to use custom icons in toolbar?

**Comment by johnfort** [comment]
What is it problem? Edit css...

**Comment by alexandrovsergii** [comment]
The problem is that we cannot load our custom css file using cssAutoLoad property
We have initiated it as described in doc, i.e
'cssAutoLoad' => [ Url::home(true) . 'css/elfinder/elfinder.css'],
but css is not loaded.

We have checked sources and seemed we found a reason
In elfinder.js file when you check this.options.cssAutoLoad property   
there is the following string (#975):
if (self.cssloaded === null) { ..
}

This condition is always false because cssloaded property is not null, it is just false
Can you check this issue?
Our  ElFinder version is 2.1.43.
Thanks!

**Comment by nao-pon** [comment]
@alexandrovsergii When using the `cssAutoLoad` option, please do not load elfinder.min.css or elfinder.full.css in HTML. "css/elfinder.min.css" and "css/elfinder.theme.css" are automatically loaded.

**Comment by sptik12** [comment]
We don't load elfinder.min.css or elfinder.full.css in HTML.
We just try to load our custom css file.
It is not loaded because of the following reason:
	if (this.options.cssAutoLoad) {
		(function() {
			var baseUrl = self.baseUrl;
			if (self.cssloaded === null) {
                                ........................
				// additional CSS files
				if (Array.isArray(self.options.cssAutoLoad)) {
					self.loadCss(self.options.cssAutoLoad);
				}
			}
			self.options.cssAutoLoad = false;
		})();
	}
This is your code (elfinder.full.js).
Condition if (self.cssloaded === null)  is always false 
self.cssloaded is not null here.

It seems you should fix this code to 
if (!self.cssloaded) {
.......

**Comment by nao-pon** [comment]
@alexandrovsergii I changed the [line 18 of elfinder.html](https://github.com/Studio-42/elFinder/blob/e6cd8f771fe63df964932793b3177e22ffe95273/elfinder.html#L18) as follows and tried it. The result is no problem. 

```javascript
					cssAutoLoad : ['css/test.css'],
					url : 'php/connector.minimal.php' // connector URL (REQUIRED)
```

**Comment by sptik12** [comment]
You are right,  if you change line 18 in elfinder.html, the result is no problem.
But if you try to make a similar change in elfinder.legacy.html, it doesn't load test.css

**Comment by sptik12** [comment]
Ok, it's clear now.

But we still cannot solve our problem.
Can you give an advice?

Our applicatioin is written in Yii2 and we use this package https://github.com/alexantr/yii2-elfinder 
to integrate ElFinder in our application.  As you can see in it's code, this package initialize ElFinder similary to way described in elfinder.legacy.htm. We haven't access to package layout, so we cannot load custom css file in html ourself, all what we can - pass to ElFinder any parameters described in ElFinder docs. But  passing of cssAutoLoad property don't work here,

Please help.
