### ISSUE TITLE
I want to limit the number of files I can upload

### ISSUE THREAD

**Issue by ji-ryoo** [Studio-42/elFinder#2798]
I want to limit the number of files I can upload

We become indebted to.

I have implemented elfinder and made it available to users.

There is a user who uploads a lot of files.

Therefore, I'd like to limit the number of files I can upload. For example, 1000 files.

As I think that it is better to have more files to upload, I changed the type of ajax from get to post.

In addition, php.ini has the following settings.
post - max - size = 500 M
upload_max_filesize = 500 M
max_file_uploads = 20

In the situation of this setting, the following occurs when trying the following things.

Uploading a folder containing 1000 files will complete up to 400 updates. There is no error at that time.

Increasing max_file_uploads increases the number of files that can be uploaded.

The user uploads a large number of files, and in fact it is not able to upload completely, but there is no error.
As a result, the user misrecognizes.

Since that is the case, we want to make restrictions on elfinder side, and when we reach the limit, we will issue an error.

Is there any way?

**Comment by nao-pon** [comment]
@ji-ryoo A bug when uploading multiple files was found on the client side. That is a bug where not all files are uploaded. I will fix it.

On the other hand, since there is no option to limit the number of files, I will consider that.

Thanks! 👍

**Comment by nao-pon** [comment]
@ji-ryoo I fixed a bug when uploading multiple files via #2799. You can check the outcome of this fix in a [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

Now, regarding the restriction function of the number of files that can be uploaded, the elFinder client handles file upload in multiple steps. Therefore, I think that limiting the number of files that can be uploaded has little meaning. Do you need that option?

**Comment by ji-ryoo** [comment]
Thanks!!

I uploaded a folder containing 30000 files, the file will go out of the folder like #2593. Why...?

So, I uploaded it with one request with reference to #1667.

```
   'bind' => [
       'open' => [
           function ($ cmd, & $ result, $ args) {
               if (! empty ($ args ['init'])) {
                   $ result ['uplMaxFile'] = 1;
               }
           }
       ]
   ],
```

Then the problem was solved.
Perhaps I think that the upper limit of the file upload is gone, so the restriction function is not necessary at the moment.

**Comment by nao-pon** [comment]
> Perhaps I think that the upper limit of the file upload is gone, so the restriction function is not necessary at the moment.

OK, I'll close this.

> I uploaded a folder containing 30000 files, the file will go out of the folder like #2593. Why...?

Is PHP setting `post_max_size` sufficient? Is it set several megaby larger than `upload_max_filesize`? If you still have problems, please create a new issue.

Thanks.
