### ISSUE TITLE
thumbnail ftp

### ISSUE THREAD

**Issue by masihfathi** [Studio-42/elFinder#2800]
hi and thanks for this great project.
I use FTP volume driver and it works great but thumbnails of uploaded files icon not shown, after some try,  I see when config tmbPath to stores in the local server where elfinder files exists, it works correctly and thumbnails shown but the problem is that I want to store all files  on FTP server (included thumbnail files and nothing stored on the local server).
is it possible to change this behavior to load and create thumbnails in FTP server?
if it is not possible how can be possible to disable thumbnail creating for FTP server driver in the elfinder config? Is it adequate to not set tmb path and tmb url to disable thumbnail creating?

**Comment by nao-pon** [comment]
@masihfathi 

> is it possible to change this behavior to load and create thumbnails in FTP server?

In order to do that it is necessary to extend the "elFinderVolumeFTP" class by yourself.

> how can be possible to disable thumbnail creating for FTP server driver in the elfinder config? Is it adequate to not set tmb path and tmb url to disable thumbnail creating?

That's right. That's not a problem.

**Comment by masihfathi** [comment]
thanks for your reply

**Comment by vahidalvandi** [comment]
i use laravel package and connect  to ftp volume but On the contrary, local don't create .tmb folder and tmb file .
