### ISSUE TITLE
Unicode problem

### ISSUE THREAD

**Issue by aminbaik** [Studio-42/elFinder#2801]
Hello,
I am using elfinder and I can add files, folders that is in named in Arabic 
I am set encoding ,local in system volume file to windows-1256 
everything is work fine except when I try to extract or compress an Arabic files. it's not working 
when I extract any file it's give me in other characters like: 받…  and when I try to compress it its give me unable to create archive.
so what I have to do ?
thanks.

**Comment by nao-pon** [comment]
@aminbaik When PHP is less than 7.1 on Windows server, character encoding can not be handled properly. Using PHP 7.1 or above will solve the problem.

Thanks.

**Comment by aminbaik** [comment]
Hello, 
I upgrade it to 7.1 but still have the same problem...
thanks.

**Comment by nao-pon** [comment]
@aminbaik I only have Windows in Japanese environment, so I can not debug other languages. Please let me know if you have any information.

Thanks!

**Comment by aminbaik** [comment]
I still have the same problem with Arabic language on zip files only...
thanks.

**Comment by nao-pon** [comment]
@aminbaik Decompressing the zip archive uses the shell command on the server or PHP's ZipArchive class. Basically, if a file containing a file name other than UTF-8 is included, you need to set your own archiver settings.

Do you have a alternate code or command setting that can handle the character encoding you use?

**Comment by aminbaik** [comment]
how I can set it ? thanks.

**Comment by nao-pon** [comment]
If you have functions `yourCustomCompressor() / yourCustomDecompressor()` that you process with PHP it looks like this.

```php
<?php

function yourCustomCompressor($workingDir, $files, $zipFilename) {
    // see elFinderVolumeDriver::zipArchiveZip()
}

function yourCustomDecompressor($zipPath, $toDir) {
    // see elFinderVolumeDriver::zipArchiveUnzip()
}

$opts = array(
    'roots' => array(
        'driver' => 'LocalFileSystem',
        'path'   => '/path/to/files/',
        'archivers' => array(
            'create' => array(
                'application/zip' => array(
                    'cmd' => 'phpfunction',
                    'argc' => 'yourCustomCompressor',
                    'ext' => 'zip'
                )
            ),
            'extract' => array(
                'application/zip' => array(
                    'cmd' => 'phpfunction',
                    'argc' => 'yourCustomDecompressor',
                    'ext' => 'zip'
                )
            )
        )
    )
);
// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```

**Comment by aminbaik** [comment]
Hello,
where i have to add it ?

**Comment by nao-pon** [comment]
@aminbaik This is the connector to which elFinder client is connected. For default configuration it is "php/connector.minimal.php".
