### ISSUE TITLE
Php 7.3

### ISSUE THREAD

**Issue by oitsuki** [Studio-42/elFinder#2804]
Hello,
When I tried to access inside a directory I have this error

`
Les données ne sont pas au format JSON.
<br /> <b>Deprecated</b>: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in <b>//......../elFinder-master/php/elFinderVolumeDriver.class.php</b> on line <b>6236</b><br /> <br /> <b>Deprecated</b>: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in <b>//......../elFinder-master/php/elFinderVolumeDriver.class.php</b> on line <b>6236</b><br /> {"cwd":{"isowner":false,"ts":1545218261,"mime":"directory","read":1,"write":1,"size":0,"hash":"l1_ZGVmYXVsdA","name":"default","phash":"l1_Lw","volumeid":"l1_"},"options":{"path":"images\/default","url":"\/shop\/sources\/images\/","tmbUrl":"\/shop\/sources\/images\/.tmb\/","disabled":["chmod"],"separator":"\/","copyOverwrite":1,"uploadOverwrite":1,"uploadMaxSize":9223372036854775807,"uploadMaxConn":3,"uploadMime":{"firstOrder":"deny","allow":["image","text\/plain"],"deny":["all"]},"dispInlineRegex":"^(?:(?:video|audio)|image\/(?!.+\\+xml)|application\/(?:ogg|x-mpegURL|dash\\+xml)|(?:text\/plain|application\/pdf)$)","jpgQuality":100,"archivers":{"create":["application\/x-tar","application\/x-gzip","application\/x-bzip2","application\/zip"],"extract":["application\/x-tar","application\/x-gzip","application\/x-bzip2","application\/zip"],"createext":{"application\/x-tar":"tar","application\/x-gzip":"tgz","application\/x-bzip2":"tbz","application\/zip":"zip"}},"uiCmdMap":[],"syncChkAsTs":1,"syncMinMs":10000,"i18nFolderName":0,"tmbCrop":1,"substituteImg":true,"trashHash":"t1_Lw"},"files":[{"isowner":false,"mime":"image\/gif","ts":1545218261,"read":1,"write":1,"size":"5886","hash":"l1_ZGVmYXVsdC9sb2FkaW5nLmdpZg","name":"loading.gif","phash":"l1_ZGVmYXVsdA","tmb":1},{"isowner":false,"mime":"image\/gif","ts":1545218260,"read":1,"write":1,"size":"43","hash":"l1_ZGVmYXVsdC9waXhlbF90cmFucy5naWY","name":"pixel_trans.gif","phash":"l1_ZGVmYXVsdA","tmb":1},{"isowner":false,"mime":"image\/png","ts":1545218261,"read":1,"write":1,"size":"2509","hash":"l1_ZGVmYXVsdC9ub3Bob3RvLnBuZw","name":"nophoto.png","phash":"l1_ZGVmYXVsdA","tmb":1}],"debug":{"connector":"php","phpver":"7.3.0-2+0~20181217092659.24+stretch~1.gbp54e52f","time":0.0172269344329834,"memory":"4387Kb \/ 625Kb \/ 128M","upload":"","volumes":[{"id":"l1_","name":"localfilesystem","mimeDetect":"finfo","imgLib":"imagick"},{"id":"t1_","name":"trash","mimeDetect":"finfo","imgLib":"imagick"}],"mountErrors":["Driver \"elFinderVolume\" does not exist"],"phpErrors":["DEPRECATED: 
`

**Comment by nao-pon** [comment]
@oitsuki 

This problem has already been fixed in 2.1.44.

- https://github.com/Studio-42/elFinder/commit/b7fc3e078a069ef52fb5b7eaf22c8d06f162d401

Thanks.
