### ISSUE TITLE
Call event after finish of all folder/file uploads

### ISSUE THREAD

**Issue by hardiktailored** [Studio-42/elFinder#2806]
I am trying to call an event "after all folder/file upload finishes" using bind method like below:

       elf.bind('mkdir mkfile duplicate upload paste move', function(event) {

            //This will allow us to not open permission when moving from Trash to Home volume
            if (event.data.hashes) {
                var hash_array = $.map(event.data.hashes, function(value, index) {
                    return [value];
                });
                if (hash_array.length > 0) {
                 //MY Code to update database for a use-case
                }
            } else {
                //Call "permissions_on_add" cmd after getting first pool of data add
                elf.exec('permissions_on_add', event.data.added[0].hash, event.data.added);
            }

        });

But the bind event gets fired on each folder/file uploads. I want to sync all folder/file data with database once upload process finishes for each. See image below:

![screenshot-multiple-file-upload](https://user-images.githubusercontent.com/19186404/50372026-87c89100-05ec-11e9-920f-df885ddf8ac2.png)

**Comment by nao-pon** [comment]
@hardiktailored Since users can start a new upload during uploading, there is no status to end all uploads. Instead, you can detect that there is no upload dialog with the following code.

```javascript
// `fm` is elFinder instance
fm.bind('upload', function(e) {
	var ntfNode = fm.getUI('notify');
	requestAnimationFrame(function() {
		var hasDialog = ntfNode.children('.elfinder-notify-upload').length? true : false;
		if (! hasDialog) {
			fm.log('All uploads was done.');
		}
	})
})
```

**Comment by hardiktailored** [comment]
Already did the similar but when user chooses same folder and accepts to overwrite same folder, that uploading process pop-up opens very late. And hence my code gets undesired result.
Code below:

        if ($('span.elfinder-notify-msg').is(':visible') && typeof int === 'undefined') {
            var int = self.setInterval(open_permission_model, 1000);
            $("#openmodel").hide();
        } else {
            $("#openmodel").show();
            window.clearInterval(int);
            return false;
        }

But I will try your code. Thanks.

**Comment by nao-pon** [comment]
@hardiktailored Please check `e.data.added` and process it when the file is added.

```javascript
fm.bind('upload', function(e) {
	if (e.data && e.data.added && e.data.added.length) {
		var ntfNode = fm.getUI('notify');
		requestAnimationFrame(function() {
			var hasDialog = ntfNode.children('.elfinder-notify-upload').length? true : false;
			if (! hasDialog) {
				fm.log('All uploads was done.');
			}
		});
	}
});
```

**Comment by hardiktailored** [comment]
@nao-pon Thanks for your time to reply back. But this isn't working. I am getting event.data multiple times when uploading a folder(with other folders and files in it). I write event.data, event.data.added and event.data.added.length in console with above code. See the console log result in screen-shot.

![console-log](https://user-images.githubusercontent.com/19186404/50469250-9a1e4280-09d1-11e9-932b-437c82b7643f.png)

I am using it in Laravel application with [Wrapper package](https://github.com/barryvdh/laravel-elfinder) so I am not sure this is issue with wrapper. I will check with plain setup of elFinder.

**Comment by nao-pon** [comment]
@hardiktailored While uploading multiple files, event.data.added may be notified more than once depending on its contents. This is the specification of elFinder. By keeping these values while the dialog is displayed, you can process the values collectively when the dialog disappears.

**Comment by hardiktailored** [comment]
@nao-pon Yes, that is intended but the problem is, to check dialog disappeared or not. Using above code this isn't possible that is why I was asking about event to know that the process of uploading finished for all files and dialog disappeared. But unable to do so.

Use case: I want to show popup, to folder uploader, to set permissions for each role of my application at the end of upload process finishes. But what happens is, the permission setup pop-up, which I added in bind, gets displayed before upload process finishes. And that is creating problem. I am setting first hash name in pop-up title(i.e. Folder name) and other child folder/file hashes, I set in hidden fields to update permissions for all at once. But without knowing uploading finished event, it is difficult to show final ready pop-up.

You can see in the below screen-shot that popup gets displayed though uploading still is in progress as visible in back of the permission pop-up.

![shared-files-upload-permission](https://user-images.githubusercontent.com/19186404/50471700-ec646100-09db-11e9-9155-4626e485dbdc.png)

I am trying other ways like setting z-index of progress bar higher than the permission pop-up and adding back-drop, etc. But I am not sure how user friendly it would be. Thanks for your support.

**Comment by nao-pon** [comment]
@hardiktailored It can be solved by delaying the timing to check the dialog. I tried a simple test script. It seems to work well.

```javascript
var uploadFiles = [];
fm.bind('upload', function(e) {
    if (e.data && e.data.added && e.data.added.length) {
        var ntfNode = fm.getUI('notify');
        uploadFiles = uploadFiles.concat(e.data.added);
        setTimeout(function() {
            var hasDialog = ntfNode.children('.elfinder-notify-upload').length? true : false;
            var cnt;
            if (! hasDialog && (cnt = uploadFiles.length)) {
                uploadFiles = [];
                alert(cnt + ' item are added.');
            }
        }, 100);
    }
});
```

**Comment by hardiktailored** [comment]
Time related condition would not work. I am still getting alert before upload finishes with above code. See screen-shot:

![screenshot](https://user-images.githubusercontent.com/19186404/50505594-a28e8000-0a9a-11e9-91f4-6a440adef57d.png)

**Comment by nao-pon** [comment]
@hardiktailored I tried it, it seems to work well.

- https://output.jsbin.com/yumeyus/ (live demo)
- https://jsbin.com/yumeyus/edit?js (JavaScript)

**Comment by hardiktailored** [comment]
@nao-pon Yes, demo working well. Upload progress pop-up gets open almost immediately in demo but not in my case. I have server-side implementation so I think the issue is with my code. The problem comes only when I see loader with point and screen gets stuck for a while, and I do upload immediately.
Thank you.

**Comment by nao-pon** [comment]
@hardiktailored No worries!
