### ISSUE TITLE
Upload dialog not work properly

### ISSUE THREAD

**Issue by applibs** [Studio-42/elFinder#2807]
Upload dialog works bad.
Buttons of upload dialog are created by this code:
`return $('<div class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only elfinder-tabstop elfinder-focus"><span class="ui-button-text">'+fm.i18n(caption)+'</span></div>')`

When I click DIV it show me OS dialog to select file, but when I click SPAN which is text of button then nothing happen. So clicking into DIV is only small space between button text and button border. It must work on all button elemens DIV and SPAN.

**Comment by nao-pon** [comment]
@applibs I have tested the latest elFinder with the following browsers, but there is nothing wrong.

- Edge 42.17134.1.0
- Firefox 64.0
- ie 11.472.17134.0
- Chrome 71.0.3578.98
- Opera 57.0.3098.106

**Comment by applibs** [comment]
On this code:
```
return $('<div class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only elfinder-tabstop elfinder-focus"><span class="ui-button-text">'+fm.i18n(caption)+'</span></div>')
					.append(form)
					.on('click', function(e) {
						if (e.target === this) {
							e.stopPropagation();
							e.preventDefault();
							input.trigger('click');
						}
					})
					.on('mouseenter mouseleave', function(e) {
						$(this).toggleClass(hover, e.type === 'mouseenter');
					});
```
and on this condition
`if (e.target === this)`

- when I click text in span, e.target = span and this = div, condition never fire.
- when I click into space between text and border then e.target = div and this = div, condition will fire and trigger click event.

**Comment by nao-pon** [comment]
@applibs I found a cause. Usually, the <form> element completely covers the <div> element, but this problem occurs if the <form> element is not completely covered under the influence of other style sheets. So I will fix this.

Thanks! 👍
