### ISSUE TITLE
Undefined ERROR_COPY_INTO_ITSELF

### ISSUE THREAD

**Issue by applibs** [Studio-42/elFinder#2809]
At elFinderVolumeDrives.class.php is this line:
`return $this->setError(elFinder::ERROR_COPY_INTO_ITSELF, $errpath);`
but nowhere is defined: constant ERROR_COPY_INTO_ITSELF.

**Comment by nao-pon** [comment]
@applibs Thanks! 👍

**Comment by applibs** [comment]
@nao-pon I recommend to you using best IDE phpStorm which will help you to identify many warnings and bugs. Please install PHPStorm EAP version which is free and after "Inspect code" you will see many many warnings which is good to fix it. Before Inspection is good to install some PHP plugins in PHPStorm settings.

**Comment by nao-pon** [comment]
@applibs I am trying the phpStorm you recommended. This is the best way to find bugs. This is a bit heavy, but I'd like to use it for coding checking. Well, I also recognized other bugs you reported, so I will fix it in a few days. Thank you!

**Comment by applibs** [comment]
Great. Install this Settings -> Plugins: "Php Inspections (EA Extended)", it will find many other warnings and bugs. And please be carefully, sometimes IDE wants to help fix it automatically by button(with yellow bulb) when you browse Inspector results , but some auto-fixes works bad. Soo it is good to find issues and fix it by recommendations but by hands.
For example: Inspection recommend replace == to ===, but at some situations code types are not strict and code can stop work properly., etc...
Any help in future is not problem from me. I believe that you will like it and never use other IDE.

**Comment by applibs** [comment]
And I forget, taht you can get free license of phpStorm when you work on open source.
https://www.jetbrains.com/opensource/

**Comment by nao-pon** [comment]
@applibs Yah! I applied for use as an open source project. Thanks! 👍
