### ISSUE TITLE
Undefined class

### ISSUE THREAD

**Issue by applibs** [Studio-42/elFinder#2812]
see: elFinder.class.php

```
/**
	 * Default root (storage)
	 *
	 * @var elFinderStorageDriver
	 **/
	protected $default = null;
```

what is elFinderStorageDriver ?
This is on more places.

**Comment by nao-pon** [comment]
@applibs Do you know how to return it in the function document of "imageMagickConvertPrepare()"?

**Comment by applibs** [comment]
I think that its impossible.

**Comment by nao-pon** [comment]
OK, I done. Thanks! 👍
