### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by applibs** [Studio-42/elFinder#2814]
elFinderVolumeDriver.class.php:
function: protected function checkExtractItems($path, $checks = null)
code:
```
if (is_dir($path)) {
	...
} 
else {
	...
	else if ($chkName && ! $this->nameAccepted($name, false))
	**$name is undefined**
	
	...
	
	else if ($chkWritable && ! $this->attr($path, 'write', null, $isDir))
	**$isDir is undefiner**
}
```

variables are defined in if (is_dir($path)) condition by foreach.

**Comment by nao-pon** [comment]
It fixed via 896af8cb44f7eb51a280ba834bc4799f8d634703 . I made a typo in the commit log.
