### ISSUE TITLE
No image thumbnails

### ISSUE THREAD

**Issue by michalheger** [Studio-42/elFinder#2819]
Hello

I've got a problem to show image thumbnails, instead of showing file icon.

I run s simple foreach to assign users folders based on DB.
foreach($boxes as $box){
	
	$bx = array(
		'driver'        => 'LocalFileSystem',           // driver fo accessing file system (REQUIRED)
		'path'          => '/mnt/photobox/' . @$box['id'] . '/photo/',                 // path to files (REQUIRED)
		//'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
		'alias'			=> $box['name'],
		//'trashHash'     => 't1_Lw',                     // elFinder's hash of trash folder
		'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
		'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
		'uploadAllow'   => array('none'), // Mimetype `image` and `text/plain` allowed to upload
		'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
		'accessControl' => 'access',
		'disabled' => array('extract', 'mkdir', 'upload','emptydir'),                    // disable and hide dot starting files (OPTIONAL)
		'imgLib'     => 'imagick',
        //'tmbPath' => '/mnt/photobox/' . @$box['id'] . '/tbm',
	);
	$opts['roots'][$i]=$bx;
	$i++;

that works, but i don't have any thumbnails, (tried tmbPath)
There is my JSON from connector:
CWD key:
"cwd":
"cwd": {
    "isowner": false,
    "ts": 1547468979,
    "mime": "directory",
    "read": 1,
    "write": 0,
    "size": 0,
    "hash": "l1_dGh1bWJz",
    "name": "thumbs",
    "phash": "l1_Lw",
    "volumeid": "l1_",
    "url": null,
    "root": "l1_Lw"
  },
options:
"options": {
    "path": "London N14 6DB/thumbs",
    "url": "",
    "tmbUrl": "",
    "disabled": [
      "extract",
      "mkdir",
      "upload",
      "emptydir",
      "chmod"
    ],
    "separator": "/",
    "copyOverwrite": 1,
    "uploadOverwrite": 1,
    "uploadMaxSize": 9223372036854776000,
    "uploadMaxConn": 3,
    "uploadMime": {
      "firstOrder": "deny",
      "allow": [
        "none"
      ],
      "deny": [
        "all"
      ]
    },
    "dispInlineRegex": "^(?:(?:video|audio)|image/(?!.+\\+xml)|application/(?:ogg|x-mpegURL|dash\\+xml)|(?:text/plain|application/pdf)$)",
    "jpgQuality": 100,
    "archivers": {
      "create": [
        "application/x-tar",
        "application/x-gzip",
        "application/x-xz",
        "application/zip"
      ],
      "extract": [
        "application/x-tar",
        "application/x-gzip",
        "application/x-xz",
        "application/zip"
      ],
      "createext": {
        "application/x-tar": "tar",
        "application/x-gzip": "tgz",
        "application/x-xz": "xz",
        "application/zip": "zip"
      }
    },
    "uiCmdMap": [],
    "syncChkAsTs": 1,
    "syncMinMs": 10000,
    "i18nFolderName": 0,
    "tmbCrop": 1,
    "substituteImg": true,
    "onetimeUrl": false
  },
Files:
"files": [
    {
      "isowner": false,
      "ts": 1547479632,
      "mime": "directory",
      "read": 1,
      "write": 1,
      "size": 0,
      "hash": "l1_Lw",
      "name": "London N14 6DB",
      "rootRev": "",
      "options": {
        "path": "",
        "url": "",
        "tmbUrl": "",
        "disabled": [
          "extract",
          "mkdir",
          "upload",
          "emptydir",
          "chmod"
        ],...

I found a problem with no tmb key in files array, but i can't find out, why it's been missing.

Thanks for any reply.

**Comment by nao-pon** [comment]
@michalheger If it differs from the default configuration, make sure to set [`tmbPath`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#tmbPath) and [`tmbURL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#tmburl).

Thanks!
