### ISSUE TITLE
runs with tinymce 5RC2 ? yes !

### ISSUE THREAD

**Issue by toastbrotch** [Studio-42/elFinder#2821]
someone managed to get elFinder working with tinymce 5RC1? instructions for tinymce 4 seem not to work. i was not able to get it working yet...

**Comment by nao-pon** [comment]
@toastbrotch It can be used by using iframe. I have created a demo page. And I am currently planning an example that does not use iframes.  The document will be serviced once it is completed.

Demo: https://hypweb.net/elFinder-nightly/demo/tinymce/v5i.html

Thanks! 👍

**Comment by johnfort** [comment]
Do you want to specify paths in tinymce or edit files in elfinder?

**Comment by toastbrotch** [comment]
i dont understand your question.

i want to use elfinder to select/upload/manage and possibly edit images (but tinymce5 imagetools are quite good! btw: is it possible to use the tinymce 5 imagetools from within elfinder to edit the files?)

**Comment by nao-pon** [comment]
A dialog version was also made.

- https://hypweb.net/elFinder-nightly/demo/tinymce/v5d.html

Then, I will investigate tinymce 5 imagetools from now.

**Comment by toastbrotch** [comment]
thanx for that demo! awesome!

regarding my question using tinymc imagetools from inside elfinder: this might has to be a separated issue in the tracker here...

**Comment by johnfort** [comment]
@toastbrotch ```
getFileCallback: function( file, el ){
				$('.mce-open').parent().children('input[id^="mceu_"]').val(file['path']);
			}
```

**Comment by nao-pon** [comment]
@toastbrotch , @johnfort 

I configured to be able to save image editing results on TinyMCE through elFinder.

- https://hypweb.net/elFinder-nightly/demo/2.1/tinymce5.html 👍

**Comment by nao-pon** [comment]
I made the [tinymceElfinder](https://github.com/nao-pon/tinymceElfinder) that elFinder integrator for TinyMCE 4 and 5. Using it makes integration easier.

**Comment by toastbrotch** [comment]
> I configured to be able to save image editing results on TinyMCE through elFinder.
>     * https://hypweb.net/elFinder-nightly/demo/2.1/tinymce5.html +1

how do i configure where the image should go? is it that "uploadTargetHash"? where does this come from? defined somehow in the connector? thanx for help...

**Comment by nao-pon** [comment]
@toastbrotch The folder hash value on elFinder is a hashed version of the path on elFinder.

see. https://github.com/Studio-42/elFinder/issues/1564

Maybe, your case is 'l1_Lw' - **l**(LocalVolumeDriver)**1**(1st)_**Lw**(/)

**Comment by toastbrotch** [comment]
@nao-pon: thanx! that was it. sorry, i was not able to find that issue...

**Comment by toastbrotch** [comment]
> https://hypweb.net/elFinder-nightly/demo/2.1/tinymce5.html
hm. just found out, that ie11 reports a syntax error on 
```
const getfm = open => {
```
at the "=>". any ideas?

**Comment by toastbrotch** [comment]
seems ie11 does not support arrow functions... i've let the whole thing thru https://babeljs.io and added bluebird.min.js (http://bluebirdjs.com/docs/getting-started.html)
