### ISSUE TITLE
How to get the path in getFileCallback

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2823]
My system is at the level above the root domain (php root).
Domain: X:/Server/domains/localhost/
Application: X:/Server/domains/localhost/newApp/

`new elFinderConnector(new elFinder( 'roots' -> 'path' = 'X:/Server/domains/localhost/newApp/' ));`

I have the path: 'newApp/images/image.png'. Value "file['path']" in getFileCallback function. This is problem manifested on all third-party hosting.

p.s. file['url'] value cannot be used: &cmd=file&target=l1_aW1hZ2VzL2Zhdmljb24ucG5n

**Comment by johnfort** [comment]
I need a path regarding the application path to the images in tinymce =)

**Comment by nao-pon** [comment]
@johnfort Try the `fm.path()` function.

```javascript
fm.path(file.hash, false/*i18n*/, true/*async*/).done(function(path) {
    // tips: path contain volume root name
    fm.log(path);
}).fail(function() {
    // error handling
});
```

**Comment by johnfort** [comment]
@nao-pon mmm? Where to use it ? "Error in `getFileCallback`. fm.path is not a function"

**Comment by nao-pon** [comment]
@johnfort 

```javascript
getFileCallBack : function(file, fm) {
    fm.path(file.hash, false, true).done(function(path) {
        // tips: path contain volume root name
        fm.log(path);
    }).fail(function() {
    	// error handling
    });
}
```

**Comment by johnfort** [comment]
fm.log(path): 'newApp/images/image.png'
p.s. This option did not fit (

**Comment by nao-pon** [comment]
For security reasons, we can not get the full path of the server on the client side. When processing something on the server, it is necessary to process it on the connector side.

**Comment by johnfort** [comment]
Listen. При написанни текста через WYSIWYG например, вставки изображений должны иметь путь относительно корня системы (CMS).
CMS can be located at any level of nesting from the root of the domain.
Users may have different access levels in elFinder, but the file paths in the text must be from the CMS root.

What are the options for solving this problem?

**Comment by nao-pon** [comment]
Please use [`URL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#url) of the connector route option. Can you cope with by changing the setting value dynamically for each access right?

**Comment by johnfort** [comment]
URL option work for cmd:Download only, but not work for cmd:getfile
<img width="646" alt="default" src="https://user-images.githubusercontent.com/17702803/51657012-177aaa00-1fb4-11e9-803d-0a0c1cf1ad74.png">
<img width="381" alt="2" src="https://user-images.githubusercontent.com/17702803/51657011-16e21380-1fb4-11e9-86c1-b467520b46f5.png">

**Comment by nao-pon** [comment]
Please use the value of file.url in gtFileCallback.

**Comment by johnfort** [comment]
Watch it.
JS only "static":
`
getFileCallback: function( file, fm ){
	$('.mce-open').parent().children('input[id^="mceu_"]').val(file['url'].replace(/\\/g, '/'));
}
`
JS NOT "dynamic":
`
/* getFileCallback: function( file, fm ){
	if( /* low access */ )
		$('.mce-open').parent().children('input[id^="mceu_"]').val(file['url'].replace(/\\/g, '/'));
	else
		$('.mce-open').parent().children('input[id^="mceu_"]').val(file['path'].replace(/\\/g, '/'));
} */
`

PHP "dynamic":
`
if( /* low access */ ){
	$opts['roots'][0]['path'] .= SYS_DIR_UPLOADS;
	$opts['roots'][0]['URL'] .= SYS_DIR_UPLOADS;
}
`
I do not use $opts['roots'][0]['URL'] = '/'; as def val, coz tinymce REQUIRES path without '/' at the beginning. To determine the dimensions.

![opera _2019-01-24_224857_localhost](https://user-images.githubusercontent.com/17702803/51704571-724ee880-202a-11e9-882d-886a12bcdf17.png)
![opera _2019-01-24_224947_localhost](https://user-images.githubusercontent.com/17702803/51704572-724ee880-202a-11e9-9bfd-92be03f58dc6.png)

**Comment by johnfort** [comment]
@nao-pon maybe this is proplem of mce... Coz if I want use '/' at the beginning for src attr, auto dimensions not work =)))
What U about it ?

**Comment by johnfort** [comment]
You did not understand me(
> My application (system) is at the level above the root domain (php root).
> Domain: X:/server/domains/localhost/
> Application: X:/server/domains/localhost/application/
cmd: getfile ** ALWAYS ** requires returning the path RELATING TO THE APPLICATION without a slash at the beginning.
If I used conf:
```php
$opts['roots'][0]['path'] = 'application/';
$opts['roots'][0]['URL'] = '/';
if(!System::Access()->isSystem){
	$opts['roots'][0]['path'] .= 'uploads/';
	$opts['roots'][0]['URL'] .= 'uploads/';
}
```
```javascript
getFileCallback: function( file, fm ){
	$('.mce-open').parent().children('input[id^="mceu_"]').val(file['url'].substr(1).replace(/\\/g, '/'));
}
```
It is very good ! Problem solved. **BUT**
<img width="290" alt="default" src="https://user-images.githubusercontent.com/17702803/51744553-4460b700-20b1-11e9-8c27-012bff06d0a5.png">

**Comment by johnfort** [comment]
It is possible that I did not understand you.
I solved the problem of code below:
```php
if(isset($_GET['getfile']) || !System::Access()->isSystem)
	$opts['roots'][0]['URL'] = '/application/';
if(!System::Access()->isSystem){
	$opts['roots'][0]['path'] .= 'uploads/';
	$opts['roots'][0]['URL'] .= 'uploads/';
}
```
```javascript
getFileCallback: function( file, fm ){
	$('.mce-open').parent().children('input[id^="mceu_"]').val(file['url'].substr(dir_root.length + 1).replace(/\\/g, '/'));
}
```

**Comment by johnfort** [comment]
```php
$opts['roots'][0]['path'] = $_SERVER['DOCUMENT_ROOT'] . '/application/';
if(isset($_GET['getfile']) || !System::Access()->isSystem)
	$opts['roots'][0]['URL'] = './';
if(!System::Access()->isSystem){
	$opts['roots'][0]['path'] .= 'uploads/';
	$opts['roots'][0]['URL'] .= 'uploads/';
}
```
```javascript
getFileCallback: function( file, fm ){
	$('.mce-open').parent().children('input[id^="mceu_"]').val(file['url'].substr(2).replace(/\\/g, '/'));
}
```

Using './' we get the correct link in the dialog: "Get info" and two extra characters in file ['url'];
@nao-pon 👍 👍 👍 👍

**Comment by nao-pon** [comment]
@johnfort Congrats! 👍
