### ISSUE TITLE
Freezes browser: elfinder in dialog

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2824]
If u has:
<script src="scripts/elFinder/elfinder.js" charset="utf-8"></script>
<script src="scripts/elFinder/i18n/elfinder.ru.js" charset="utf-8"></script>
AND
`var elFinderBrowser = function( callback, value, meta ){
		var opts = {
			url: 'call.php?get=elfinder',
			requestType: 'post',
			lang: 'not-ru',`

**Comment by nao-pon** [comment]
@johnfort Is the loaded "scripts/elFinder/elfinder.js" built "elfinder.min.js" or "elfinder.full.js"?

**Comment by nao-pon** [comment]
I made a live demo and tried it, but it seems to be no problem.

- https://jsbin.com/zecobes/edit?html,output

**Comment by johnfort** [comment]
@nao-pon http://tyrego.ru/uploads/tiny_and_elf//index.html
freezes Opera, FF

**Comment by nao-pon** [comment]
@johnfort I fixed it. Please try [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip). Thanks! 👍
