### ISSUE TITLE
Chinese file/folder display error when doc or ppt file exist

### ISSUE THREAD

**Issue by manctm** [Studio-42/elFinder#2825]
After testing many times... 
I find that .... if we got a doc or ppt file in that folder, then Chinese file display error will happen. 
But if using docx or pptx file, no error ...

![screen shot 2019-01-22 at 6 52 07 pm](https://user-images.githubusercontent.com/20414615/51531018-43444580-1e77-11e9-8261-72953e17067d.png)
![screen shot 2019-01-22 at 6 54 50 pm](https://user-images.githubusercontent.com/20414615/51531020-43dcdc00-1e77-11e9-9574-a9578be26689.png)

**Comment by nao-pon** [comment]
@manctm Please let us know your detailed server environment (OS, OS character encoding, PHP version etc ...). elFinder may not handle character encoding other than UTF-8 normally.

Thanks.

**Comment by manctm** [comment]
my server is Ubuntu Linux 18.04.1 , PHP 7.2.10,  LANG=en_US.UTF-8

the display error only occur when the folder contain doc / ppt / xls file and some files or folder which name begin with Chinese character. BUT, if contain docx / pptx / xlsx, no error occur.

**Comment by nao-pon** [comment]
Is the same result if you change the connector's **main** option [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale) to `'zh_CN.UTF-8'`?

`'locale' => 'zh_CN.UTF-8'`

**Comment by manctm** [comment]
after changed the locale to zh_CN.UTF-8, but same result.

(** attach a zipped Chinese name doc file for your testing)
[單元1.1 主權誰屬.DOC.zip](https://github.com/Studio-42/elFinder/files/2785742/1.1.DOC.zip)

**Comment by nao-pon** [comment]
I uploaded it to the demo site, but it seems that there is no problem.

- https://studio-42.github.io/elFinder/#elf_l2_Y25fdGVzdA

Is the character encoding of the server file system UTF - 8 correct?

**Comment by ji-ryoo** [comment]
i have same issue.
No problem when creating .pptx with Japanese file name.
In case of .ppt with Japanese file name, Japanese is missing.
On Windows 10.
