### ISSUE TITLE
Connector: root option 'separator' not work (

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2827]
If use OS Win10 & option "'separator' 	=> '/',", than root not displayed =)

**Comment by nao-pon** [comment]
@johnfort The windows server needs to use `\` as the separator.

**Comment by nao-pon** [comment]
Please convert with JavaScript.

For example ...

```javascript
path = path.replace(/\\/g, '/');
```

**Comment by johnfort** [comment]
@nao-pon okay 😆
