### ISSUE TITLE
help: image dimension, upload hooks

### ISSUE THREAD

**Issue by toastbrotch** [Studio-42/elFinder#2832]
hi all
i'm trying to show the image dimensions in the list view. on client i have
```
cwd : {
  listView : {
    columns : [\'date\', \'size\', \'dim\', \'kind\'],
  }
},
```
so i have this column, but what needs to be configured in the connector that those dimensions are included in the answer? i just have one LocalFileSystem in the default connector.minimal.php

second question: during upload of zip and html files i need to do some regexes to change paths, what is the best way to add this?

thanx a lot!

**Comment by nao-pon** [comment]
@toastbrotch Yes, `dim` or` width` and `height` must be returned from the connector. When `width` and` height` are used, the following settings are required on the client side.

```javascript
listView : {
	columns : ['url', 'date', 'size', 'kind', 'dim']
},
replacement : {
	dim : function(f, fm) {
		return f.dim? f.dim : ((f.width > 0 && f.height > 0)? (f.width + 'x' + f.height) : '');
	}
}
```

-------------------

> second question: during upload of zip and html files i need to do some regexes to change paths, what is the best way to add this?

Use the 'bind' option on the connector side. Are the following links useful for you?

- https://github.com/Studio-42/elFinder/issues?utf8=%E2%9C%93&q=label%3Ahowto+upload+bind

**Comment by toastbrotch** [comment]
@nao-pon . thanx
what if those dim/width/height are not returned by the connector?(just one localfilesystem)

2. thanx. jep bind and especially https://github.com/Studio-42/elFinder/issues/1661#issuecomment-247985736 is the information i was looking for. thanx...

**Comment by nao-pon** [comment]
@toastbrotch One way to do this is to extend the elFinderVolumeLocalFileSystem class.

```php
class elFinderVolumeMyLocalFileSystem extends elFinderVolumeLocalFileSystem
{
    protected function stat($path) {
        $file = parent::stat($path);
        if ($file) {
            $dim = $this->_dimensions($this->convEncIn($path, true), $file['mime']);
            if ($dim) {
                $file['dim'] = $dim;
            }
        }
        return $file;
    }
}
```

```php
$opts = array(
    'roots'  => array(
        array(
            'driver' => 'MyLocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    )
);
```

**Comment by toastbrotch** [comment]
@nao-pon you are awesome! works perfect. where is your donate-button?

**Comment by nao-pon** [comment]
@toastbrotch Thanks! There is a donate button in [demo site](https://studio-42.github.io/elFinder/).

![190131-002929](https://user-images.githubusercontent.com/1412630/51992354-2f8c8500-24f0-11e9-93d3-4d27eff73a87.png)

**Comment by toastbrotch** [comment]
@nao-pon i managed to get the bind working `'bind' => array('upload' => array('uploadCallBack')),` as explained in the other issue, but how do i tell the client to refresh/reload as i rename some files?

**Comment by alivato** [comment]
Hi.

I use elfinder with tinymce / textpattern cms
How can I hide dimensition(html) then I upload and paste image?
?
How to make the fields empty or 0? (not asked in html)

[https://i.ibb.co/4jYYFDn/321.jpg](url)

I don't want to specify width and height in html.
I already have it written in CSS


```
<script type="text/javascript" src="http://site.com/textpattern/js/tinymce/tinymce.min.js"></script>

<script type="text/javascript">
    tinymce.init({
        selector: 'textarea',
        file_picker_callback: elFinderBrowser,
        images_upload_handler: elFinderBrowser,
        menubar: false,
        plugins: ["autolink link image media table code"],      
        toolbar: ["autolink link image media table code"],
        relative_urls: false
    }); 

function elFinderBrowser (callback, value, meta) {
  tinymce.activeEditor.windowManager.open({
    file: 'http://site.com/textpattern/js/elfinder/elfinder.html', // use an absolute path!
    title: 'elFinder 2.1',
    width: 900,  
    height: 450,
    resizable: 'yes'
  }, {
    oninsert: function (file, fm) {
      var url, reg, info;

      // URL normalization
      url = fm.convAbsUrl(file.url);
      
      // Make file info
      info = file.name + ' (' + fm.formatSize(file.size) + ')';

      // Provide file and text for the link dialog
      if (meta.filetype == 'file') {
        callback(url, {text: info, title: info});
      }

      // Provide image and alt text for the image dialog
      if (meta.filetype == 'image') {
        callback(url, {alt: info});
      }

      // Provide alternative source and posted for the media dialog
      if (meta.filetype == 'media') {
        callback(url);
      }
    }
  });
  return false;
}

</script>  


<script type="text/javascript">
    $(document).ready(function() {
        //your code here
    });
</script>

```
