### ISSUE TITLE
File limit

### ISSUE THREAD

**Issue by edison009** [Studio-42/elFinder#2835]
I am using elfinder with servlet as backend. It accepts only 5 files for single upload and not able to do with more than that. please let me know how to resolve it

**Comment by nao-pon** [comment]
@edison009 You can limit the number of simultaneous uploads in max_file_uploads of PHP setting, elFinder can make asynchronous request, so it may not make much sense.

For the upload quota, I think the following link will be helpful.

- https://github.com/Studio-42/elFinder/issues/1467

**Comment by nao-pon** [comment]
@edison009 I seem to have misread the question. I think that this is a problem with the servlet backend so please ask the servlet developer.
