### ISSUE TITLE
Setting CWD icons size not working

### ISSUE THREAD

**Issue by StreamZero** [Studio-42/elFinder#2836]
Hi, i'm using elFinder 2.1.46,
i have the preference menu disabled so i want to manually set a icon size in the file manager.
I tried to set "iconsView" with the "size: 3" and "sizeMax: 3" values in the elFinder options file but it's not working. I also tried removing the browser cache but the icon size are still the same.

**Comment by nao-pon** [comment]
@StreamZero The setting is correct with that. However, if the last size is stored in the local storage of the browser, it will take precedence. Please try resetting your personal preferences.

![190131-010519](https://user-images.githubusercontent.com/1412630/51994565-69f82100-24f4-11e9-9b84-14a9f4a1f431.png)

**Comment by StreamZero** [comment]
I'm having the same problem with a fresh installation, a different domain and in incognito mode.

**Comment by nao-pon** [comment]
@StreamZero I found elFinder's bug so i'll fix it. Thanks! 👍
