### ISSUE TITLE
[Feature Request] Support Video.js HTML5 Video Player 

### ISSUE THREAD

**Issue by zero77** [Studio-42/elFinder#2841]
Can you please add support for Video.js its an open source HTML5 & Flash video player, it provides support for a wide range of video, audio types and plugins.
Thanks

Git:
https://github.com/videojs/video.js

Documentation / API:
https://docs.videojs.com/

**Comment by nao-pon** [comment]
@zero77 In the modern browser, what is the advertisement of video.js compared to the media preview of elFinder?

Thanks!

**Comment by zero77** [comment]
@nao-pon 
> In the modern browser, what is the advertisement of video.js compared to the media preview of elFinder?

It could be a problem at my end but, i can't seem to be able to play these formats mkv, avi, mpg, wmv although, there may be others.

I think an advantage of Video.js would be that any media playing problems could be taken care of by their developers, which would leave you with more time.

**Comment by nao-pon** [comment]
@zero77 I could not find the corresponding [video.js plugins](https://videojs.com/plugins/) for them.

**Comment by zero77** [comment]
@nao-pon 
I red somewhere they were supported but, i will confirm that.

**Comment by zero77** [comment]
@nao-pon 
It looks like you are right, it doesn't seem to be supported.
Should i closed this and open another issue on adding support for supporting mkv, avi, mpg, wmv formats.
