### ISSUE TITLE
Folder download on demo website

### ISSUE THREAD

**Issue by MathJohnson** [Studio-42/elFinder#2843]
When I go to [https://studio-42.github.io/elFinder/#elf_l1_VGlwcw](https://studio-42.github.io/elFinder/#elf_l1_VGlwcw) I can download folder/s as zip. Why can't I do that if I use elfinder library from this GitHub project? Download button doesn't even show up when I right click on folder.

![alt text](https://i.imgur.com/MKeScvY.jpg)

 I am using same version of **elfinder.full.js** as demo website and **.NET Core connector**.

**Comment by DustinHays** [comment]
I understand that connector must support zipdl command, but how does it affect the front-end? It should still display option to download even though the command is not implemented in back-end yet.

**Comment by nao-pon** [comment]
@MathJohnson If the connector identifies API 2.1012 or later as the result of the first [open command](https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#open), the command will be displayed.

**Comment by DustinHays** [comment]
Thank you, now the command is shown. I have another question. There is always only one command sent to the server, but API documentation states that there are two calls to the server. Second command is never sent in my case.

Here is the only command sent:

![alt text](https://i.imgur.com/3xLZVVI.jpg)

And here is response from the server:

![alt text](https://i.imgur.com/zr8jqLy.png)

I also noticed that my request is **GET**, but when I check demo on your website, the first request is **POST**. The version of API is **2.1046**.
