### ISSUE TITLE
Size request with wrong targets

### ISSUE THREAD

**Issue by programmeraren** [Studio-42/elFinder#2845]
I have noticed that most targets are sent in the requests as 'targets[]' and works very well. This is also what is stated in the Client-Server API spec.

However, this does not seem to be true when Elfinder sends the size command request which looks like below:
 ```
cmd: size
targets[0]: home_L1Rlc3RBUi9IL0hlag_E_E
targets[1]: home_L1Rlc3RBUi9IL0hvcHA_E
_: 1549187523353
```
The size command is issued from Elfinder e.g. when right-clicking on a folder and select the 'Show Info' option.

I suppose this is a bug and should be fixed so that the targets are sent as below instead:
 ```
cmd: size
targets[]: home_L1Rlc3RBUi9IL0hlag_E_E
targets[]: home_L1Rlc3RBUi9IL0hvcHA_E
_: 1549187523353
```

Tested with version 2.1.46 of Elfinder Client in Chrome on Windows 10.
Thanks!

**Comment by nao-pon** [comment]
@programmeraren I fixed it. Thanks! 👍
