### ISSUE TITLE
Places document in Wiki?

### ISSUE THREAD

**Issue by mjyu51** [Studio-42/elFinder#2847]
Is there any detailed documentation for "Places"? Such what is it, how to set/config it? I tried to search Wiki but there is very little found. I would suggest to put a document regarding "Places" to Wiki.

Thanks.

**Comment by nao-pon** [comment]
@mjyu51 I added a reference image into the [Wiki](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#ui). Thanks! 👍
