### ISSUE TITLE
requirements in README.md incomplete

### ISSUE THREAD

**Issue by toastbrotch** [Studio-42/elFinder#2848]
> jQuery UI 1.9.0+ (require draggable, droppable, resizable, selectable and slider)

if i have just this in jquery-ui 1.10.4 or 1.12.1 the image-editor does not appear when clicking on icon.... i had not time to debug further

**Comment by nao-pon** [comment]
@toastbrotch elFinder jQuery-UI button widget. I fixed it. Thanks! 👍
