### ISSUE TITLE
how to use lightbox on "open" of files ?

### ISSUE THREAD

**Issue by toastbrotch** [Studio-42/elFinder#2849]
for example i use http://www.jacklmoore.com/colorbox/
so it could be called like `$.colorbox({href:"thankyou.html"});` instead of opening a new window, when clicking the "open"-icon or double-click

is this possible? thanx for pointing me in the right direction...

**Comment by nao-pon** [comment]
@toastbrotch Sorry, I mistake write commit log.

**Comment by nao-pon** [comment]
@toastbrotch You can use a client option [`getFileCallback`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#getfilecallback).

```javascript
getFileCallback : function(file, elFinderInstance) {
    var url = file.url;
    var absoluteUrl = elFinderInstance.convAbsUrl(url);
    $.colorbox({ href: absoluteUrl });
}
```

**Comment by toastbrotch** [comment]
awesome! thanx a lot. works perfectly!

**Comment by toastbrotch** [comment]
sorry. but this works only on double-click a file. not if i click the "open"-file button or via contex-menu "open". (maybe i forgot to add: this is a standalone elfinder version)

**Comment by nao-pon** [comment]
@toastbrotch Please try next client options.

```javascript
commandsOptions : {
    open : {
        selectAction : 'getfile'
    },
    preference : {
        selectActions : ['getfile', 'edit/download', 'resize/edit/download', 'download', 'quicklook']
    }
}
```

**Comment by toastbrotch** [comment]
that made the trick! awesome what is configurable...
