### ISSUE TITLE
Zipdl sends GET request instead of POST

### ISSUE THREAD

**Issue by DustinHays** [Studio-42/elFinder#2850]
Today I tested **zipdl** command. I noticed that if I select multiple files and choose Download, the client sends GET request instead of POST. 

Therefore, request looks like in the image below and obviously it exceeds the maximum URL length. Why does it send **GET request instead of POST**? I checked demo website ([https://studio-42.github.io/elFinder](https://studio-42.github.io/elFinder)) and it sends POST request for all the **targets[]**. I am using API version **2.1046**, version **2.1.39 (2018-06-05)** of elFinder (elfinder.full.js) and **.NET Core connector**. What am I doing wrong?

![alt text](https://i.imgur.com/eUjhju9.png)

**Comment by nao-pon** [comment]
@DustinHays There is an option [`requestType`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#requesttype) of the client options.

**Comment by DustinHays** [comment]
Thank you, this solved the problem. You can close the issue.
