### ISSUE TITLE
How to launch elfinder from another location

### ISSUE THREAD

**Issue by philouphil** [Studio-42/elFinder#2852]
Hello,

Default installation works very well (last version), but I wonder how to make elfinder.html works if I move this file to another location.

Of course I've tried to change all the relatives paths but without success.

I would like to have the elfinder "launch page" in a folder, the differents files (.php , .js, .css) in another folder, and folder "files" in another location too.

Something like this :

- /
      -- /www
            ---- /folderA
                   ------ /**files**
            ---- /folderB
                ------ **elfinder.html**
           ---- /elfinder
                 **------ /css
                 ------ /img
                 ------ /js
                 ------ /php**
                 ------ ...

**Comment by nao-pon** [comment]
@philouphil The path of main.default.js referenced in elfinder.html, the path of elfinder.min.js and connector.minimal.php referenced in main.default.js, and the path of files referenced in connector.minimal.php are Please correctly set.

Thanks!
