### ISSUE TITLE
MS Document Thumbnails

### ISSUE THREAD

**Issue by webcontributor** [Studio-42/elFinder#2853]
We have some ms office documents, we want to generate thumbnail previews. How do we enable this ?

**Comment by nao-pon** [comment]
@webcontributor In elFinder's PHP connector, you can register functions for creating thumbnails by MIME type.

**For example**
```php
$opts = array(
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/',
            'imgConverter' => array(
                /**
                 * Convert Document To Image
                 *
                 * @param  string $file video source file path
                 * @param  array  $stat file stat array
                 * @param  object $self volume driver object
                 *
                 * @return bool
                 */
                'application/vnd.openxmlformats-officedocument.wordprocessingml.document' => function($tempFilePath, $stat, $self) {
                    $tmbData = yourCreatedToMakeFunc($tempFilePath);
                    file_put_contents($tempFilePath, $tmbData);
                    return true;
                }
            )
        )
    )
);
```

**Comment by webcontributor** [comment]
Thanks for you quick reply,  What is yourCreatedToMakeFunc do?

**Comment by nao-pon** [comment]
@webcontributor I do not know in detail. You need to procure functions that convert office documents to thumbnails yourself.

**Comment by webcontributor** [comment]
Ok sure, can you please help me in 1 more thing,  i want to hide all directories in only in right side gui not in left sidebar and other files will remain as it is. Please help.

**Comment by nao-pon** [comment]
There is an option [`ui`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#ui) of client options.

**Comment by webcontributor** [comment]
Nao Pon sorry to disturb for again,  but i am unable to hide directories. So it is very urgent. Please help. 

Thanks

**Comment by nao-pon** [comment]
@webcontributor 
```javascript
ui: ['toolbar', 'stat']
```
see live demo - https://jsbin.com/netuhah/edit?js,output
