### ISSUE TITLE
security of elfinder

### ISSUE THREAD

**Issue by mehrdadshirvan** [Studio-42/elFinder#2854]
hi  
i use elfinder in extact in package (laravel 5.7) 
if i open the link localhost/elFinder/elfinder.html in cpanel  too
elfinder open with all access
.........................................................
but i just allow for admin not every one 
i can`t deny with route
i deny from .htaccess but only for all 
if any way to fixed it or some way plz show me 
tnx ♥

**Comment by nao-pon** [comment]
@mehrdadshirvan You can configure the connector config dynamically based on the role of the current user.

For example... https://studio-42.github.io/elFinder/#elf_l1_QmFzaWNBdXRoRXhhbXBsZQ
