### ISSUE TITLE
iconsize bigger than default not working (or i miss something)

### ISSUE THREAD

**Issue by toastbrotch** [Studio-42/elFinder#2856]
hi nao-pon 

i have this config and try to have the 72px version of the icons. in the connector i've set the thumbs to 72px which is working. but on the client is see no change when defining the size. also there are still the same classes for the image and surrounding elements. as far as i understand other classes should be used (which are defined in the default css).
```
$(document).ready(function() {
    $('#elfinder').elfinder({
            url : connectorUrl,
            uiOptions : {
                cwd : {
                    iconsView : {
                        size: 2,
                        sizeMax: 3,
                    },
                },
            },
        },
    );
});
```
sizeMax is reflected correctly for the slider-size at the preferences workspace-menu but not which size is selected...(jep i removed the local storage of the browser, but no effect)
do i miss something?

**Comment by nao-pon** [comment]
@toastbrotch Perhaps this is a duplicated to #2836.

**Comment by toastbrotch** [comment]
hm. no. if i reset my settings as described it shows me the 48px version. if i'm right, it shoult at least then show me the 72px. right?

**Comment by nao-pon** [comment]
@toastbrotch Yes, Please try the [nightly build](https://github.com/Studio-42/elFinder/tree/2.1).

**Comment by toastbrotch** [comment]
your patch #2836 works... thanx. i've missed that one!

**Comment by nao-pon** [comment]
@toastbrotch Thank you for verifying! 👍
