### ISSUE TITLE
[cmd:fullscreen] add an option of fullscreen mode screen/window

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#2858]
I think that the full screen is not in demand in this implementation. I need as like tinymce. Or the option to choose during initial setup.
I think it is worth remaking the default implementation by analogy to tinymce.
@nao-pon What about think ?

**Comment by nao-pon** [comment]
@johnfort About "full screen of the device", It might be useful on small screen devices like mobile devices. How about a plan that changing the "full screen of the device" / "full window on the browser" by user setting?

**Comment by nao-pon** [comment]
@johnfort I tried it with user setting, and its work is quite nice. I will try to implement this.

**Comment by nao-pon** [comment]
@johnfort Please try with `commandOptions.fullscreen.mode` to `'window'` on the [nightly build](https://github.com/Studio-42/elFinder/tree/2.1).

```javascript
commandOptions: {
    fullscreen: {
        mode: 'window'
    }
}
```

Thanks! 👍

**Comment by johnfort** [comment]
@nao-pon mobile dev?)

**Comment by nao-pon** [comment]
@johnfort Options can be changed by the `bootCallback` option function.

For example
``` javascript
var options = {
    url : 'php/connector.php',
    bootCallback : function(fm, extraObj) {
        fm.options.commandsOptions.fullscreen.mode = fm.UA.Mobile? 'screen' : 'window';
    }
}
```
