### ISSUE TITLE
Readable drives were not found.

### ISSUE THREAD

**Issue by aftabir** [Studio-42/elFinder#2860]
Hi 
I'm using elfinder with laravel and i did all it's instalition form here https://github.com/barryvdh/elfinder-flysystem-driver

but when i want to open elfinder it gaves me this error

backend error Readable drives were not found.

by the way I use ckeditor with elfinder 

tnx for ur helping

**Comment by nao-pon** [comment]
@aftabir The[ `path`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#path) option is not set correctly. Or, the specified directory can not be found, or PHP does not have read permission.

Thanks!

**Comment by aftabir** [comment]
I've just used this (according to  installation)

'disks' => [
    'local',
    'my-disk' => [
        'URL' => url('to/disk'),
        'alias' => 'Local storage',
    ]
],



'public' => [
    'driver' => 'local',
    'root'   => base_path().'/public',
],

**Comment by nao-pon** [comment]
@aftabir Ask barryvdh/elfinder-flysystem-driver for information on setting barryvdh/elfinder-flysystem-driver. Configure so that the correct value is set to the setting value `path` of the elFinder connector.

**Comment by aftabir** [comment]
@nao-pon  ok thanks a lot
