### ISSUE TITLE
How to edit cpp (c++) files ?

### ISSUE THREAD

**Issue by munish48** [Studio-42/elFinder#2861]
Hey @nao-pon , Thanks for awesome file management tool, you are doing a great job :) .

I have a question, i have some cpp (c++) files, i want to edit them directly in elfinder, i have integrated code mirror as my editor, but unfortunatly 'edit file' context menu is not coming only for cpp (c++) files. Please help me how to resolve this issue.

Thanks
Munish Thakur
India

**Comment by nao-pon** [comment]
@munish48 Is the file extension ".cpp"? If you are using the official PHP connector, MIME-Type will be detected as "text/x-c" and it should be editable.

**Comment by munish48** [comment]
@nao-pon , yes its working fine :)
Thanks for your Help.

Munish Thakur
India
