### ISSUE TITLE
sync deplay

### ISSUE THREAD

**Issue by bgbruno** [Studio-42/elFinder#2862]
Hello,

when I have set "sync" for example to basic "1000"
https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#sync

I open 10tabs

and then every other operation like "open dir" or "open file withing ace" takes approx 10seconds 😮

**Q can you help?
Q pls how it works?
Q why that delay?**

Bruno

**Comment by nao-pon** [comment]
@bgbruno AutoSync is checked on the server side by long polling method. It may take up to 30 seconds for the inquiry time. Therefore, if you open elFinder on many tabs, the number of concurrent connections reaches the upper limit, waiting for a request will occur. That is the cause of this problem.

I plan to incorporate an action that does not query the server for AutoSync when the tab is not displayed.

Thanks! 👍

**Comment by nao-pon** [comment]
> number of concurrent connections reaches the upper limit, waiting for a request will occur
OK
*Q pls where in code is this sync action?*

Perhaps the browser limits the number of concurrent accesses per host. It is not a limitation of elFinder.

> That is the cause of this problem
*Q pls this problem occurs per user device or by server ?*

It probably comes from the browser. However, in some cases it may be restricted by the server. You can see it by observing the HTTP session.

> I plan to incorporate an action that does not query the server for AutoSync when the tab is not displayed.
*Q thx that would be awesome - any ETA?*

It will be included in the next version. Before that you can try it with [Nightly Build](https://github.com/Studio-42/elFinder/tree/2.1).

Thanks! 👍
