### ISSUE TITLE
cssAutoLoad is not working

### ISSUE THREAD

**Issue by cristiangervasi** [Studio-42/elFinder#2863]
Hi, i'm using the latest release (2.1.48) and when i add something to the cssAutoLoad array, no additional files are loaded and the theme remains the default one. 

I have tried both with fresh installation and by upgrading an old one (from 2.1.46 to 2.1.48) and the same thing is happening. 

I also tried the manual way by setting cssAutoLoad to false and loading each css file in the <head> section but the layout seems "corrupted".

Has something changed css related in the new release? I'm using the latest "RobiNN1/elFinder-Material-Theme" and it was working perfectly in version 2.1.46.

As always thank you for your work and support.

**Comment by nao-pon** [comment]
@cristiangervasi I am fixing this because backwards compatibility is broken.

However, there are new ways in theme designation.

Use options `themes` and `theme`.
```javascript
themes : {
	// You can specify a manifest.
	default : 'https://cdn.jsdelivr.net/gh/RobiNN1/elFinder-Material-Theme/manifests/material-default.json'
},
theme : 'default',
url : 'php/connector.minimal.php' // connector URL (REQUIRED)
```

Thanks! 👍

**Comment by RobiNN1** [comment]
It still doesn't work properly. See https://github.com/RobiNN1/elFinder-Material-Theme/issues/8#issuecomment-487611803

**Comment by RobiNN1** [comment]
It's still not fixed

**Comment by nao-pon** [comment]
@RobiNN1 It turned out that this problem cannot be solved without setting a default theme. I will fix this.

Thanks! 👍
