### ISSUE TITLE
Folder size in Column

### ISSUE THREAD

**Issue by KlausHB** [Studio-42/elFinder#2864]
Hi dio and friends!

I just installed elFinder on my QNAP hoping to get rid of the FileStation for pushing directories ;-)
Really nice work I must say!

As a Mac user I am used to get the size of all folders shown in Finder list view  (CMD+J, there is my loved option)

Any Chance to see all folders size in ellFilder?

Best regards 

Klaus

**Comment by nao-pon** [comment]
@KlausHB The calculation of the total size of the files contained in the folder is burdensome on the server, so it is calculated only when the user needs it.

Thanks!

**Comment by KlausHB** [comment]
Thanx for Your answer,

I do not get the clue, maybe be cause it is very short ;-)
You said "so it is calculated only when the user needs it". Is there a button I am missing?
Or do You mean, that I have to get the size for every single folder? Even in my my root of /share, there are dozens of folders. This is no way, someone wanna go.

macOS has this feature in Finder for years by now. Just CMD+J and one checkbox.(calculate all folder size)...voilla!
Then You see at one glance exactly what folder is what size, and You are able to sort size column with one Klick.
Of course You can switch it on and off there to.

Btw. FreeCommander, And TotalCommander has this feature, and even MidnightCommander (shell mc) can do, if you mark the 1st line (dots) and press spacebar.

It would be sooo cool, if I could do that with elFinder instead of opening a terminal via ssh.
And if I do it via Network (Windows or Mac) then copy 1 TB takes a long time, because it all runs over the network.

Allmost everyone is complaining about FIle Station. With this feature elFinder would be the King of file managers on qnap.

There are solutions for this out there:
https://www.youtube.com/watch?v=rPUet6Ulfb8 <https://www.youtube.com/watch?v=rPUet6Ulfb8>

Any hint how to include something like this via Plugin / Extension?
The I would do this part and offer the solution to the comunity

Best regards

Klaus

**Comment by nao-pon** [comment]
@KlausHB There are many costs involved in calculating the total size of the files contained in a folder. It is not realistic to always calculate their size, especially if the folder contains so many files and descendant folders. Therefore, elFinder is designed to calculate only when the user needs it. Please refer to the following video.

![elfinder-folder-size](https://user-images.githubusercontent.com/1412630/54475814-53eeb780-4839-11e9-9f17-3d9f3e8a42ca.gif)

If you want to always show the total folder size, you need to create your own driver that includes the folder size in the file information.
