### ISSUE TITLE
Move files strange behavior

### ISSUE THREAD

**Issue by adolforo** [Studio-42/elFinder#2865]
Hi,

I'm using version 2.1.48 (not the minimal, but the complete).
I have several "roots" configured (all from the local disk) in the connector.
When I drag/drop files from one directory to another with the Caps key pressed, the behavior is of uploading from the first directory to the second but what it uploads is the "connector.minimal.php" file with size of 0 bytes.

That could be happening ?

**Comment by adolforo** [comment]
This happens in Firefox and you can move the selected file or the "connector.minimal.php" that appears sometimes but always with size 0 bytes.
In Chrome, drag & drop with caps key between directories has no effect.

**Comment by nao-pon** [comment]
@adolforo That is probably the function of the drag-out works and the server is getting through the URL. The server seems to be unable to read for its URL.

Even so, normally, while holding down the Alt key, dragging will be handled via the URL, but have you changed the Firefox key binding?

**Comment by adolforo** [comment]
Holding down the Alt key, Ctrl key, Caps key (uppercase key), they are normal gestures that are used for operations with files (copy, move, ... etc).

I have done some tests with the following results:

- When you drag a file **from outside** of elfinder (i.e. **from the client's file explorer** to an elfinder directory)
    
	-> the behavior is **normal in all browsers** (upload the file)
	
- When you drag a file **from within** elfinder (i.e. from one directory of elfinder to another)

	- **drag + alt key**
	  - Firefox : causes the "upload" of a defective file to the destination directory (*)
	  - Chrome : idem (*)
	  - Safari : idem (*)
	- **drag + uppercase key**
	  - Firefox : causes the "upload" of a defective 

file to the destination directory (*)
	  - Chrome : the drag does not occur, has no effect
	  - Safari : the drag does not occur, has no effect
	- **drag + Ctrl key**
	  - Firefox copy the file correctly
	  - Chrome copy the file correctly
	  - Safari copy the file correctly

#### Development and test environment :
- Server 	
	- Debian 9 + Apache 2.4 + MySQL 5.7 + PHP 5.6 (all updated)
	- I have created a new virtual host and I have put a clean, untouched copy of elfinder Versión: 2.1.48 (2.1-src Nightly: 802a690)
	- I have changed in the file "connector.minimal.php" :
	  - 'uploadDeny'  => array('all'),   ---------->   'uploadDeny' => array(''),
	  - 'uploadAllow' => array('image/x-ms-bmp', ...etc),   ---------->   'uploadAllow' => array('all'),
- Clients
	- Windows 7 Professional + Firefox Quantum 65.0.2 + Google Chrome Versión 72.0.3626.121 (Build oficial)
	- Mac OSX El Capitan + Safari 11.1
	- macOS Mojave + Safari 12.0.3

### (*)
As an example, I have passed ("upload") a video file called "video_01.mp4" **from one directory to another** and the result has been a defective **"video_01.mp4" which, in reality, is an html file** with the content that I attached (is renamed as "video_01.txt").
(the "<title>casa.net</title>" in the file, is the test domain)
[video_01.txt](https://github.com/Studio-42/elFinder/files/2958248/video_01.txt)

**Comment by nao-pon** [comment]
@adolforo It seems that detection of Alt key and Uppercase key is only confused with Firefox. It may be a jQuery specification.

Well, let's talk about the behavior of elFinder when dragging out.

If you start dragging while holding down the Alt key, elFinder starts HTML 5 specification dragging. In the drag data, the URL of the item is set, so if you drop it into elFinder, the content will be retrieved from the URL on the web server side and the file will be saved.

Therefore, to save content successfully, you need to configure the web server to allow the web server to retrieve data using the URL pointed to by the item in elFinder. In a typical configuration, this should work without problems, but depending on the server configuration it may not work correctly.

Please check if your item can be obtained from the URL of the item indicated by elFinder on your web server.

**Comment by adolforo** [comment]
The server has the correct URL because when copying or moving files from one directory to another, it works perfectly.
Copying (uploading) from the client also works well.
The malfunction comes when you press "Shift" or "Alt" when you start dragging between elfinder directories.
I have modified the Javascript file and I wanted to ask for your opinion.
When you start to drag, 2 events occur in the file "**elfinder.full.js**":

```
line 16388: 
.on ('dragstart', function (e) {
     var dt = e.dataTransfer || e.originalEvent.dataTransfer || null;
     .... etc

```
```
line 17223: 
.dragstart (function (e) {
    var target = $ (e.data.target),
        oe = e.data.originalEvent;
    .... etc

```
But when you press "Alt" or "Shift" when you start to drag, **only that of line 16388 occurs**.

For this, I modified the source for the case of pressing any key of these when starting the drag as follows:

```
line 16388: 
.on ('dragstart', function (e) {
    // added ini
    if (e.originalEvent.shiftKey || e.originalEvent.altKey) {
       e.preventDefault ();
       e.stopPropagation ();
       e.originalEvent.preventDefault ();
       e.originalEvent.stopPropagation ();
       return;
    }
   // added end
... rest of original code

```
In this way, it **seems that everything works correctly and no error occurs**.

Do you think this modification is correct?
It is necessary to treat the two events ("e" and "e.originalEvent") or would it be enough with just one?
Can this affect the functioning of "elfinder"? (in my tests, it goes well).

Thanks for your opinion.

**Comment by nao-pon** [comment]
@adolforo The fix blocks the drag out of elFinder's features.

If you start dragging while holding down the alt key (or shift key), elFidner will be in HTML5 drag and drop mode, which will allow you to drag out of the elFinder out. It exports items by URL. On the other hand, normal drag and drop is only valid in elFinder, which is handled by jQuery. It is not affected by the item URL, as it is manipulated by the item ID, not the URL. You need to understand that.

**Comment by adolforo** [comment]
I fully understand this operation.

When I drag an element in this way to my desktop, for example, I get a link (direct access) to this element.

However, in my (simple) application I do not need this functionality, just move/copy files WITHIN the elfinder and upload/download files through the corresponding menus.

For this, I only need to press the "Ctrl" key (for copy) and the other 2 keys ("Alt" and "Shift") do not need them and, however, can produce the effects already explained.

Therefore, I believe that I will leave it like this (only for the purpose of my application) and I will continue to test if it affects the correct functioning.

Thank you very much for your help and your patience.

**Comment by nao-pon** [comment]
@adolforo I understood that there is such a demand. I consider adding an option to disable the dragout feature.

**Comment by nao-pon** [comment]
@adolforo I done. Please try with client option `uiOptions.cwd.matekeyDragout` to `false`.

```javascript
var options = {
    url : 'php/connector.php',
    uiOptions : {
        cwd : {
            metakeyDragout : false
        }
    }
}
$('#elfinder').elfinder(options);
```
