### ISSUE TITLE
How do I view a file with a custom viewer?

### ISSUE THREAD

**Issue by shiyee** [Studio-42/elFinder#2870]
Hi Sir,

You make a good file manager, thank you.

I have a question , I want to view files using a custom viewer, for example , use pdf.js to open pdf files. 

how can I do that.

thank you.

**Comment by nao-pon** [comment]
@shiyee For example, [quicklook.googledocs.js](https://github.com/Studio-42/elFinder/blob/master/js/extras/quicklook.googledocs.js) has a sample to preview on `<iframe>`.

**Comment by shiyee** [comment]
Thank you very much
