### ISSUE TITLE
How to implement photopea. 

### ISSUE THREAD

**Issue by inmanturbo** [Studio-42/elFinder#2879]
I can't seem to figure out how to use photopea for editing pdf or any other mime. The icon just spins and spins and it never loads. Also, it's not working on the demo site. Is there an extension or api key I'm missing or something? Thank you so much for your great work!

**Comment by nao-pon** [comment]
@inmanturbo You do not need to use API Keys or anything special to use Photopea. You can open PDF files with Photopea on the demo site.

![elfinder-photopea](https://user-images.githubusercontent.com/1412630/54917467-39a29100-4f3f-11e9-821d-2149975f6a1a.gif)

However, there is a problem with saving files in PDF format. Photopea seems to be unable to save files in PDF format. (It may be a bug of Photopea)

I fix elFinder to save the file format that Photopea can not save in PSD format.

Thanks! 👍
