### ISSUE TITLE
Can not upload PDF and PSD files

### ISSUE THREAD

**Issue by Mical2018** [Studio-42/elFinder#2881]
Can not upload PDF and PSD files
But there are these options in the menu. Why?

**Comment by nao-pon** [comment]
@Mical2018 

> But there are these options in the menu.

What is it like? Can you show we an image?

**Comment by Mical2018** [comment]
![OZF__ 4SAT J1KE`{F7908X](https://user-images.githubusercontent.com/37858004/55526278-07272f80-56c7-11e9-8691-8be322712455.png)
You can see from the picture that the PDF file cannot be uploaded
But it does exist in the demo
In addition, I also want to know how to encrypt folders or files, I did not find this option

**Comment by Atercia** [comment]
me too

**Comment by nao-pon** [comment]
@Mical2018 , @Atercia Please check a connector roots option [`uploadAllow`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadAllow), [`uploadDeny`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadDeny) and [`uploadOrder`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadOrder).
