### ISSUE TITLE
Downloaded files 0ko and preview blank with Mysql (with ftp no problem)

### ISSUE THREAD

**Issue by Nounours13** [Studio-42/elFinder#2883]
Hi,
When i use Mysql connector I can do anythink. I can upload file also but the only problem, is for download file (or make a preview).
If i make a double click (or right click and download) the file is downloaded but it's blank (0Ko).
I've no error on javascript console and also on php (I've error_reporting(-1)) and no error also on mysql (I've enabled the query log and there is no error on Query	SELECT content FROM files WHERE id=78 for example)
The only preview that work is for the txt file but if I download this file it make also a 0 Ko file.
I've changed the configuration to FTP and in this mode no problem. All is good.

If anybody have an idea where is my mistake. Thanks 

PS: PHP 7.2.7 - Mysql 5.7.11 (My database is on utf8 -- UTF-8 Unicode utf8_general_ci) - Codeigniter 3.1.10 - Jquery 3.3.1 . Tested on Windows 10 (ver 1809) and Ubuntu 18.10

**Comment by nao-pon** [comment]
@Nounours13 I found typo while checking the source file.

Line 670
`$fp = $this->tmbPath`
Change to
`$fp = $this->tmpPath`
Please try to fix it. Are there any changes in the results?

**Comment by Nounours13** [comment]
Hi Nao-pon,
Thanks a lot, this is the solution.
Now Elfinder works at 100%.

Have a got day !!!

**Comment by nao-pon** [comment]
@Nounours13 Thank you for verifying! :+1:
