### ISSUE TITLE
shared folder 

### ISSUE THREAD

**Issue by aminbaik** [Studio-42/elFinder#2884]
Hello,
I have a dfs name space \\domain\data 
and it's have three folders 
folder 1 on same server of elfinder 
folder 2 on same server of elfinder 
folder 3 on server 2 
when I open the elfinder it's show only folder 1 and folder 2 … 
folder 3 not show in ! 
but if I access \\doamin\data from windows it's show me three folders.
so where is the problem ?
?

**Comment by nao-pon** [comment]
@aminbaik elFinder's PHP connector reads and writes files with the privileges of the PHP execution account. Check the permissions to the PHP run account.

Thanks.
