### ISSUE TITLE
Change text web ftp bug

### ISSUE THREAD

**Issue by Ho2x** [Studio-42/elFinder#2887]
Hello,

I have a problem, when I want to create a file (ex: test.php) with code inside, when saving it transforms all my code ...

Example
<! DOCTYPE html PUBLIC "- // W3C // DTD XHTML 1.0 Strict // EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

becomes:

& lt;! DOCTYPE html & gt;
& Lt; html & gt;
& Lt; head & gt;
& lt; title & gt; This is a test page with PHP tags & lt; / title & gt;
& lt; meta charset = & quot; utf-8 & quot; / & Gt;

Use : ispconfig whmcs https://github.com/cwispy/

**Comment by nao-pon** [comment]
@Ho2x That's because it is sanitized as HTML by the application you are using. Please review what is the cause.

Thanks.

**Comment by Ho2x** [comment]
I do not know the cause of the problem. When I save a file in HTML or php format. All my code changes.

**Comment by nao-pon** [comment]
@Ho2x I guess this problem is not due to elFinder, but to the application you are integrating. Please ask that developer.
