### ISSUE TITLE
zipdl files 

### ISSUE THREAD

**Issue by Skorefin** [Studio-42/elFinder#2888]
Am using the Simple logging example.
Need/like to log zipdl ZIP file name & the files zipped/contained within the ZIP.file created.

Ta

**Comment by nao-pon** [comment]
@Skorefin Currently, file names and folder names of the first depth can be detected. However, items deeper than that can not be detected.

**Comment by Skorefin** [comment]
Can you please provide example to achieve this in recommended fashion?

Ta

**Comment by nao-pon** [comment]
@Skorefin For example about bind function ...

```php
'zipdl' => [
    function($cmd, $result, $args, $elfinder, $volume) {
        if (empty($args['download']) && !empty($args['targets'])) {
            $files = [];
            foreach ($args['targets'] as $hash) {
                if ($file = $volume->file($hash)) {
                    $files[] = $file;
                }
            }
            // $files include items stat
        }
    }
],
```

**Comment by Skorefin** [comment]
Legend, many thanks, will give it a spin!

**Comment by Skorefin** [comment]
Got zipdl logging working with your assist, thanks again. Output;

zipdl [Sat, 13 Apr 2019 23:21:40 -0700] "admin" [120.20.89.165]
	
Dir:  /home/xxxxxx/public_html/assets/files/test 1/test/Sales                             	677 KB • Files: 5 Dirs: 5
	File: /home/xxxxxx/public_html/assets/files/test 1/test/5_webp_a.jpg.webp                  	11.2 KB
	File: /home/xxxxxx/public_html/assets/files/test 1/test/5_webp_a.webp                      	57.3 KB
	File: /home/xxxxxx/public_html/assets/files/test 1/test/Heavens_Chinese_Web.pdf 

However, notice that with "file" binding only "Read" of text files appear in log?
Want/need to log all files read.

        if ($volume && !empty($cmd) && ($cmd === "get" || $cmd === "file")) {
            $path = $volume->getPath($args['target']);
            $log .= ($cmd === 'get'? 'Read' : 'Download').' ['.date(DATE_RFC2822)."]" . ' "'.$uname.'" ' .'['.$ip_address."]"."\n" . "\tFile: " . $path . "\n";
		}

**Comment by nao-pon** [comment]
@Skorefin When the `URL` of the connector roots option is specified, it will be performed via the URL when downloading. Do not specify the `URL` option to download using the file command.

**Comment by Skorefin** [comment]
Disabling the root "URL" config option does enable logging other file access. However, it also disables image thumbnails and MS Office documents Previews etc.

Any other suggestions to log all file types access without these side-effects?

Thanks

**Comment by nao-pon** [comment]
@Skorefin Another option is to capture client-side events and send arbitrary data to the server. Please implement the method to send to the server yourself.

```javascript
var elf = $('#elfinder').elfinder(opts).elfinder('instance');
elf.bind('exec', function(e, fm) {
    fm.log(e.data);
});
```
