### ISSUE TITLE
How to use my own generated thumbnails?

### ISSUE THREAD

**Issue by uru** [Studio-42/elFinder#2889]
Hi,

I use thumbor library (https://thumbor.readthedocs.io/en/latest/) that resizes the images from the address line. For this reason, I would like to place images generated from the address line in Elfinder. But I'm not sure of that Elfinder options allow this.

If there is no such option, what do you think about the development of placing of 'self' parameter into the url?

For example:
`'tmbURL' => https://example.com/200x200/filters:proportio(0.5)/{self},`

Thank you

**Comment by nao-pon** [comment]
@uru Please try connector roots options...

```php
'tmbURL' => 'https://example.com/200x200/filters:proportio(0.5)/YOURDOMAIN/ELFINDERROOT/',
```

**Comment by uru** [comment]
I tried once, but this solution isn't suitable for our structure. Because our application works behind the load balancer and we don't store any static files.
In fact, all I want is to be able to call the thumbnail image from a different address (tmbURL) with the same filename.

**Comment by nao-pon** [comment]
@uru If so, create a new driver that inherits from the LocalFileSystem driver and include the `tmb` URL parameter in the file stat.

```php
class elFinderVolumeMyLocalFileSystem extends elFinderVolumeLocalFileSystem
{
    protected function stat($path) {
        $file = parent::stat($path);
        if ($file) {
            if (substr($file['mime'], 0, 6) === 'image/') {
                $file['tmb'] = 'Your tmb URL/' . rawurlencode($file['name']);
            }
        }
        return $file;
    }
}
```

And include root options.
```php
'driver' => 'MyLocalFileSystem',
'tmbURL' => '',
```

**Comment by uru** [comment]
Thank you @nao-pon. This solution is works for me.
