### ISSUE TITLE
Adding custom toolbar/context menu options

### ISSUE THREAD

**Issue by crk4** [Studio-42/elFinder#289]
How can i add a custom toolbar/context menu option so that i can implement my custom functionality into it. for example i will have a full screen option available on the toolbar so that the user can be able to switch the file manager into full screen mode. 
Is there any way to achieve this one?. any suggestions.....!   thank u.......

**Comment by troex** [comment]
thanks! feel free to update wiki https://github.com/Studio-42/elFinder/wiki/Custom-context-menu-command
