### ISSUE TITLE
[Feature Request] 2 folders view simultaneously

### ISSUE THREAD

**Issue by mammnon** [Studio-42/elFinder#2891]
Hi,

it would be amazing to be able to split the view to see two folders at the same time and easily drag&drop files from one side to the others. 

Maybe there is already a workaround loading 2 elfinder instance in two separate DIV but obviously drag&drop functions are not working. Any suggestions?

**Comment by nao-pon** [comment]
@mammnon You can copy files (by upload) between multiple instances by starting dragging with Alt key.
