### ISSUE TITLE
Elfinder on DLink 320L can't write

### ISSUE THREAD

**Issue by dorepac** [Studio-42/elFinder#2896]
Hello everyone!

I've got this issue yesterday first time, when second HDD was inserted. Elfinder cant copy/paste HDD1-->HDD2 or on the same HDD for that matter, seems like rights were missing, but I didnt change anything. Please help.

**Comment by nao-pon** [comment]
@dorepac I guess the problem is due to your server environment. If so, you can not solve it if you ask here.
