### ISSUE TITLE
zoho editor saveing error

### ISSUE THREAD

**Issue by choowolms** [Studio-42/elFinder#2897]
![캡처11](https://user-images.githubusercontent.com/24289274/55974644-16a80900-5cc3-11e9-8cec-dbdc95ad8ed6.PNG)

Why is this message coming out?

[Server info]
php - 7.0.33
apache - 2.4
mariadb

**Comment by nao-pon** [comment]
@choowolms In Zoho Editor, edited file data is sent from Zoho server to the connector endpoint of elFinder by POST request. If the connector endpoint of elFinder is not opened outside, saving of content fails.

Thanks.
