### ISSUE TITLE
TS-221

### ISSUE THREAD

**Issue by etl** [Studio-42/elFinder#2899]
I see blank screen, no files, just "files" icon. TS-221 - clean installed.

**Comment by nao-pon** [comment]
@etl I do not know what "TS-221" is. Check the permissions for the connector's execution account.

**Comment by etl** [comment]
That's Qnap Ts-221 NAS

**Comment by nao-pon** [comment]
If it uses a PHP connector, check the permissions for the PHP execution account. Also, I do not know about the setting of Qnap.
