### ISSUE TITLE
Cannot read property 'promise' of null

### ISSUE THREAD

**Issue by JulienPlanchetCoineo** [Studio-42/elFinder#2904]
Hello all, I got this problem when I upload certain files
Sometimes, I got 

> POST http://localhost:50589/el-finder/file-system/connector 404 (Not Found)

And after this, I have :

> Uncaught TypeError: Cannot read property 'promise' of null
    at getFile (elfinder.full.js:6301)
    at XMLHttpRequest.<anonymous> (elfinder.full.js:6553)

If I chek the debugger, files = null.

But, for some other files, I havn't any problem.

Do you have an idea how to fix it ?

Thanks

**Comment by JulienPlanchetCoineo** [comment]
Anyone have an idea ?

**Comment by nao-pon** [comment]
@JulienPlanchetCoineo This seems to be a problem with error handling. I will fix this.

Thanks! 👍
