### ISSUE TITLE
Share file url

### ISSUE THREAD

**Issue by ptoews** [Studio-42/elFinder#2905]
We would like to use this nice interface as a background file management system for a static website. We have many users that are not that technically inclined and would love if there was a super-easy way to get the (absolute) file url of an uploaded file to paste it into the website. I know that you can get the URL by selecting the file, clicking on info, right clicking the link shown and clicking on 'Copy link address'. But this is a little bit too cumbersome for the most frequently used operation.

What do you think about an additional command that e.g. instantly copies the link to the clipboard? Or is there already an easier way that I missed? It would be very helpful for our use case. I already tried to implement a custom command, but got stuck (#2906).

**Comment by vfishv** [comment]
right click menu add “Copy link address” is a good idea

**Comment by nao-pon** [comment]
@ptoews , @vfishv One way is to use the [getFileCallback](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#getFileCallback) option.

```javascript
getFileCallback : function(file, fm) {
    var execCopy = function(string) {
        var temp = document.createElement('textarea');

        temp.value = string;
        temp.selectionStart = 0;
        temp.selectionEnd = temp.value.length;

        var s = temp.style;
        s.position = 'fixed';
        s.left = '-100%';

        document.body.appendChild(temp);
        temp.focus();
        var result = document.execCommand('copy');
        temp.blur();
        document.body.removeChild(temp);

        return result;
    };
    if (execCopy(fm.convAbsUrl(file.url))) {
        fm.toast({msg: 'Copied the item URL to the clipboard!'});
    }
}
```

**Comment by ptoews** [comment]
@nao-pon Thanks, that looks great! But I'm not sure how to use this code, is this supposed to be inserted somewhere as a custom command?

**Comment by nao-pon** [comment]
@ptoews Please check the [Wiki](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#getFileCallback).
