### ISSUE TITLE
Automatic start mount network volume window on start page - old issue

### ISSUE THREAD

**Issue by jovigor** [Studio-42/elFinder#2907]
I leave message [HERE ](https://github.com/Studio-42/elFinder/issues/2828) couple days ago...
 
I tried but no success.
Can you please describe step by step, where should i put this code:
var opts = {
url : 'php/connector.minimal.php'
};
var fm = $('#elfinder').elfinder(opts).elfinder('instance');
fm.one('open', function(e, fm) {
fm.exec('netmount');
});
Thanks

**Comment by nao-pon** [comment]
@jovigor Please use an event 'opendone' insteard 'open'.

```javascript
var opts = {
    url : 'php/connector.minimal.php'
};
var fm = $('#elfinder').elfinder(opts).elfinder('instance');
fm.one('opendone', function(e, fm) {
    fm.exec('netmount');
});
```
