### ISSUE TITLE
GPX (uppercase extension) does not upload

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#2908]
Hi,

if I drag and drop a file with gpx extension it works properly. If I rename the extension to GPX it does not work "...File type not allowed...".
While it works if I do the same with a KMZ file.
What should I do to fix it?

**Comment by nao-pon** [comment]
@ghigio2000 This is a bug of `elFinderVolumeDriver::mimetype()`, so I'll fix it.

Thanks! 👍
