### ISSUE TITLE
Getting File upload order while renaming

### ISSUE THREAD

**Issue by R4dix** [Studio-42/elFinder#2909]
Hello Everyone,

i want to rename my the uploaded files based on the order they are uploaded. 
If I drag & drop 20 files into elFinder for example, how can i access the order they where droped in there? 

Thank you for your support!

**Comment by nao-pon** [comment]
@R4dix If 20 files are uploaded in a single request, they will be uploaded in the order selected by the user, but this will be affected by the operating system and browser specifications. Also, depending on the size of the file to be uploaded, one file may be divided into multiple requests, in which case the order of processing by the server will be undefined.

Thanks.
