### ISSUE TITLE
Can't download folder with firefox

### ISSUE THREAD

**Issue by KiboOst** [Studio-42/elFinder#2910]
Hi,

With own project or even your demos, on last Firefox (windows) we can't download a folder. It produce a can't find file error.
Same for several files selected.

elfinder/php/connector.minimal.php?cmd=zipdl&download=1&targets[]=l1_xxxxxxxx&targets[]=xxxxxx&targets[]=js-3.zip&targets[]=&js-3.zip.

Works on Chrome.

**Comment by nao-pon** [comment]
@KiboOst I tested using Firefox 66.0.3 on the demo site, but it seems to be fine.

**Comment by KiboOst** [comment]
Hi thanks for testing.

Just tested here : https://studio-42.github.io/elFinder/
And it works !!

Is there something special in php connector or js creation to do for it ?

**Comment by KiboOst** [comment]
I have look the doc and some examples but can't get how to set zipdl command to work. Any pointer regarding this ?

**Comment by KiboOst** [comment]
Ok I have set tmpPath to connector

When downloading a folder, still got the error. But I a xxx.blurb file in the tmpPath and if I rename it to xxx.zip it is the good file !

**Comment by KiboOst** [comment]
Hi,

trying to download elfinder/js flder:
404 --- /php/connector.minimal.php?cmd=zipdl&download=1&targets[]=l1_cGx1Z2lucy9qZWV4cGxvcmVyLzNyZHBhcnR5L2VsZmluZGVyL2pz&targets[]=5cc95b94ec9c6&targets[]=js.zip&targets[]=&js.zip

file elfzdltWtosa created in tmpPath

debug:
`array(3) {
  ["$cmd"]=>
  string(5) "zipdl"
  ["$result"]=>
  array(1) {
    ["zipdl"]=>
    array(3) {
      ["file"]=>
      string(13) "5cc95b94ec9c6"
      ["name"]=>
      string(6) "js.zip"
      ["mime"]=>
      string(0) ""
    }
  }
  ["$args"]=>
  array(5) {
    ["targets"]=>
    array(1) {
      [0]=>
      string(55) "l1_cGx1Z2lucy9qZWV4cGxvcmVyLzNyZHBhcnR5L2VsZmluZGVyL2pz"
    }
    ["download"]=>
    string(0) ""
    ["reqid"]=>
    string(14) "16a728db69211c"
    ["debug"]=>
    string(0) ""
    ["sessionCloseEarlier"]=>
    bool(true)
  }
}
array(3) {
  ["$cmd"]=>
  string(5) "zipdl"
  ["$result"]=>
  array(3) {
    ["error"]=>
    string(14) "File not found"
    ["header"]=>
    string(22) "HTTP/1.x 404 Not Found"
    ["raw"]=>
    bool(true)
  }
  ["$args"]=>
  array(5) {
    ["targets"]=>
    array(4) {
      [0]=>
      string(55) "l1_cGx1Z2lucy9qZWV4cGxvcmVyLzNyZHBhcnR5L2VsZmluZGVyL2pz"
      [1]=>
      string(13) "5cc95b94ec9c6"
      [2]=>
      string(6) "js.zip"
      [3]=>
      string(0) ""
    }
    ["download"]=>
    string(1) "1"
    ["reqid"]=>
    string(0) ""
    ["debug"]=>
    string(0) ""
    ["sessionCloseEarlier"]=>
    bool(true)
  }
}`

Connector config:

`$opts = array(
  'debug'=>true,
  'bind' => array('zipdl download' => array(function($cmd, $result, $args) {
      debug(array('$cmd' => $cmd, '$result' => $result, '$args' => $args));
    })
),
  'roots' => array(
    array(
      'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
      'path'          => dirname(__FILE__) . '/../../../../../',         // path to files (REQUIRED)
      'URL'           => dirname($_SERVER['PHP_SELF']) . '/../../../../../', // URL to files (REQUIRED)
      'accessControl' => 'access',             // disable and hide dot starting files (OPTIONAL)
      'startPath'     => dirname(__FILE__) . '/../../../../../',
      'tmpPath'       => dirname(__FILE__) . '/../../../jeexTmp',
      'utf8fix'       => true
    )
  )
);`

**Comment by nao-pon** [comment]
@KiboOst The zipdl command uses PHP session variables to locate downloaded files. Therefore, Firefox session continuation may not work on your site.

**Comment by KiboOst** [comment]
@nao-pon hey, many thanks for your answer !!

I just added @session_start(); in the connector php file, and all works like a charm now !!

Thanks for your time ;-)

**Comment by nao-pon** [comment]
@KiboOst Congratulations! 👍

**Comment by tru-wp-dev** [comment]
no still its not working.. please provide where to add session_start ? also I have added but not effect.
