### ISSUE TITLE
Hidden PDFTollbar

### ISSUE THREAD

**Issue by robinzz94** [Studio-42/elFinder#2911]
Could the PDF viewer toolbar be disabled?

![image](https://user-images.githubusercontent.com/4943305/56998968-f1e0dc00-6b72-11e9-9408-b8cea517a8af.png)

**Comment by nao-pon** [comment]
@robinzz94 Try to set `false` to [`commandsOptions.quickllok.pdfToolbar`](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L352-L353) of the client option.

**Comment by robinzz94** [comment]
Negative, I do not function

This is the configuration?

![image](https://user-images.githubusercontent.com/4943305/57025203-2056c980-6bfc-11e9-95f0-abf36c6ab85c.png)

**Comment by robinzz94** [comment]
The result is the same

![image](https://user-images.githubusercontent.com/4943305/57025285-585e0c80-6bfc-11e9-9ee1-29e63429c7b1.png)

**Comment by nao-pon** [comment]
@robinzz94 I created a live demo on jsbin.

- JavaScript: https://jsbin.com/relewub/edit?js
- Demo: https://output.jsbin.com/relewub#elf_l1_TUlNRS10eXBlcw
