### ISSUE TITLE
PHP7 support? Error: Unable to connect to backend.

### ISSUE THREAD

**Issue by MostafaFathi** [Studio-42/elFinder#2913]
I'm running PHP7 on my production server, and elfinder doesn't work there, but it works in my localhost with PHP5 so i guess this is not compatible with PHP7?

there is no errors.
![Capture](https://user-images.githubusercontent.com/13615013/57288723-b25e4680-70c2-11e9-87ce-74e325f5aeb8.PNG)

**Comment by nao-pon** [comment]
@MostafaFathi Yes, elFinder works fine with PHP 7. I am working on PHP 7.3.3.

**Comment by MostafaFathi** [comment]
thx for response,
but elFinder not working with PHP 7.2.14 on my localhost.
no errors but also no qnap folders, why ??

**Comment by MostafaFathi** [comment]
@nao-pon , i solved problem by set ftp enabled in wamp>php>extensions>ftp.

**Comment by nao-pon** [comment]
OK, :+1:
