### ISSUE TITLE
Technical support

### ISSUE THREAD

**Issue by Mical2018** [Studio-42/elFinder#2915]
I want to know how to add the supported file format, and how to add the password to the file or folder. Do I need to install other programs to support it?

**Comment by nao-pon** [comment]
@Mical2018 

> I want to know how to add the supported file format

Please read the Wiki ([uploadAllow](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadallow), [uploadDeny](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploaddeny) and [uploadOrder](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadorder)).

>  how to add the password to the file or folder

For example, there is a method that uses the [basic authentication](https://studio-42.github.io/elFinder/#elf_l1_QmFzaWNBdXRoRXhhbXBsZQ) mechanism and [dynamically configures the read permission](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#accesscontrol) based on login information.

**Comment by Mical2018** [comment]
@nao-pon I should have known about these problems, thank you, I should have read more Wiki
