### ISSUE TITLE
TUI image editor file not loading and Edit File Sub menu customization

### ISSUE THREAD

**Issue by dewshare** [Studio-42/elFinder#2916]
Hi

When I click on TUI Image Editor, it gives me following error on console,

Loading failed for the <script> with source “https://uicdn.toast.com/tui-image-editor/v3.5.1/tui-image-editor.min.js”.

Kindly let me know how can I change this URL to a working URL, as I see this URL does not load any file, 404 not found error. but another link with v3.5.2 is working.

![submenu](https://user-images.githubusercontent.com/32006488/57577974-5c134e00-749c-11e9-89d6-fc156fddfa44.png)

My 2nd question is, How can i change edit file sub menu, I need only TUI Image editor this time, I want hide other items in this menu ?

Kindly guide me, I shall be thankful

**Comment by nao-pon** [comment]
@dewshare Please check a commit 89ce314 to fix tui.image-editor version. And you can copy "js/extras/editors.default.js" to "editors.js" etc, leaving only the editors you need. As "editors.defaul.js" is specified as read by "main.default.js", copy "main.default.js" to "main.js" etc., edit it to your liking, require.js Use to specify reading.

**Comment by dewshare** [comment]
> 
> 
> @dewshare Please check a commit [89ce314](https://github.com/Studio-42/elFinder/commit/89ce314a482cdc31d0898127098a77961eb9d685) to fix tui.image-editor version. And you can copy "js/extras/editors.default.js" to "editors.js" etc, leaving only the editors you need. As "editors.defaul.js" is specified as read by "main.default.js", copy "main.default.js" to "main.js" etc., edit it to your liking, require.js Use to specify reading.

thanks for help, It worked !
