### ISSUE TITLE
$_SESSION and elfinder

### ISSUE THREAD

**Issue by pbasmo** [Studio-42/elFinder#2921]
Hi
I downloaded the latest version 2.1.49 to install it on my website (with an old version 2.1.29).
When i am already logged in my website, my datas $_SESSION are lost when i start elfinder.html.
I saw there is several main options like 'session', 'sessionCacheKey' ... but i dont know how configure them to keep my datas $_SESSION.
Thanks for your help

**Comment by pbasmo** [comment]
Hi,
I think i solved my problem.
I disabled the lines 134 and 138 (session_start) on script elFinderSession.php
After testing my datas $_SESSION are kept and elfinder works fine.
Regards

**Comment by nao-pon** [comment]
@pbasmo Start a session in your application before creating an instance of the elFinder class in the php connector.

Thanks!

**Comment by ramiwi** [comment]
Im calling session_start() before creating the tinymceElfinder object but my sessions are still destroyed.

**Comment by egrefin** [comment]
Same problem here.
I just put session_start(); at the very beginning of the connector.minimal.php file and it works perfectly.
