### ISSUE TITLE
[Question/Feature] Directory Event : Get hash of files when renaming/moving/deleting parent folder ?

### ISSUE THREAD

**Issue by Shotman** [Studio-42/elFinder#2923]
I have the need to get the hashes of every files that are inside a given directory on move/rename (it's the "same" event more or less) and delete.

Currently I only have on the JS events the hash of the folder itself but nothing about the files that might be inside it or even inside other nested folders.

Is there any way to get that ?

Thank you

**Comment by nao-pon** [comment]
@Shotman In the elFinder API, there are a `tree` command for getting subfolders and an` ls` command for getting items in a folder. Use those commands and make requests recursively.

```javascript
var options = {
    url  : 'php/connector.php'
}
var elf = $('#elfinder').elfinder(options).elfinder('instance');
var target = 'TARGET HASH';

// example for to get folder info
elf.request({cmd: 'tree', target: target}).done(
    function(e) {
        elf.log(e);
    }
);

//  example for to get item hashes
elf.request({cmd: 'ls', target: target}).done(
    function(e) {
        elf.log(e);
    }
);
```
