### ISSUE TITLE
In fact, the upload is successful. But an error is displayed.

### ISSUE THREAD

**Issue by ji-ryoo** [Studio-42/elFinder#2924]
hello

When i upload in a folder including multiple files  , elfinder displays error dialog.
But i seem to  upload successfully.
i got error dialog.

![error](https://user-images.githubusercontent.com/36890599/58610395-4dbf9180-82e6-11e9-8698-91c1309cde7e.png)

for example..

pattern 1:
【SUCCESS】 1000 files(128KB) in a folder

pattern 2:
【SUCCESS】 2 files(12MB) in a folder

pattern 3:
 【FAIL】 3 files(12MB) in a folder
 
pattern 4:
 【SUCCESS】 1 file(499MB) 
 
pattern 4:
 【FAIL】 2 files(499MB) in a folder 
 
Why?? 

our setting

## elfinder
ver 2.1.44
upload | post

```
// Documentation for connector options:
// https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options
$opts = array(
	// 'debug' => true,
	'maxTargets' => 1000,
	'roots' => array(
		// Items volume
		array(
			'tmbPath'       => '/opt/app-root/src/.tmb20181206t',
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '/opt/app-root/src/public_html',                 // path to files (REQUIRED)
//		'trashHash'     => 't1_Lw',                     // elFinder's hash of trash folder
			'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('all'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'uploadMaxSize' => '500m',
			'alias'         => 'Document Root',
			'accessControl' => 'access',
			'attributes'    => array(),
			'acceptedName'  => '/^[^\/\0]+$/',
			'statOwner'     => 'True',//to change parmission
			'quarantine'		=> '/opt/app-root/src/public_html/.quarantine'
		),
```

## Php
max_file_uploads | 50
memory_limit | 128M
max_input_vars | 20000
post_max_size | 500M
upload_max_filesize | 500M

**Comment by nao-pon** [comment]
@ji-ryoo It must be memory_limit> post_max_size> upload_max_filesize in your PHP configuration.

For example, try the following settings.

memory_limit | 128M
post_max_size | 60M
upload_max_filesize | 50M
