### ISSUE TITLE
When uploading an image thumbnails are being created for png files only

### ISSUE THREAD

**Issue by westcoastbc** [Studio-42/elFinder#2925]
I am using ElFinder 2.1.49. When I upload an image thumbnails are only created correctly for png files. Is there some configuration I have to set to accept other file types?
Thumbnails are created for other file types but they are not correct. I get the following for gif files:

![image](https://user-images.githubusercontent.com/51208292/58661166-0af8bc00-82dc-11e9-8267-e283cf40ea24.png)

**Comment by westcoastbc** [comment]
Does anyone have any suggestions?

**Comment by westcoastbc** [comment]
I really need to get this solved. The demo program supports thumbnails for more file types than just png yet it only seems to work for png files only on my site. Does anyone have any suggestions what I should be looking for?

**Comment by westcoastbc** [comment]
Does anyone have a suggestion?

**Comment by nao-pon** [comment]
@westcoastbc If you are using a PHP connector, check the support status of GD. Or enable the PHP Imagick extension.

**Comment by westcoastbc** [comment]
How do I install and enable Imagick ?

**Comment by nao-pon** [comment]
@westcoastbc It does PHP configuration on the server. Please check with Google for details.

**Comment by westcoastbc** [comment]
I installed Iamgick and that solved the problem
