### ISSUE TITLE
File in Japneese Language not working

### ISSUE THREAD

**Issue by munish48** [Studio-42/elFinder#2927]
hey @nao-pon ,

I am facing problem when uploading a Japanese doc file in elfinder, my file name is 
会社施設使用願2.doc , after upload it is showing 2.doc, please help what is issue there.

Thanks
Munish

**Comment by nao-pon** [comment]
@munish48 It is known that PHP 7.0 and earlier do not handle file names containing multibyte characters correctly on Windows servers. Try PHP 7.1 or higher.
