### ISSUE TITLE
Thumbnail not created

### ISSUE THREAD

**Issue by farhadst** [Studio-42/elFinder#2929]
Hi
I use from elfinder on my site fine.
But after change webserver from Apache to litespeed , if upload any new image thumbnail preview not showing
In fact, the new thumbnail is not created and the ones shown are already created

![IMG_20190605_102342_131](https://user-images.githubusercontent.com/8976056/58933523-c312e280-877c-11e9-9eb9-4ee2b342e4b9.jpg)

**Comment by nao-pon** [comment]
@farhadst Please check [server requirements for make thumbnail](https://github.com/Studio-42/elFinder#server).

**Comment by farhadst** [comment]
Hi
After update php from 7.1 to 7.2.19 and update litespeed api to V7.4 , problem fixed
