### ISSUE TITLE
No Issue just Help with Python

### ISSUE THREAD

**Issue by dorel14** [Studio-42/elFinder#2934]
Hello 
I've read this help text
https://github.com/Studio-42/elFinder/wiki/Using-elFinder-2.x-UI-with-1.x-connector

Where do i put this code 
`$().ready(function() {
	$('#finder').elfinder({
		url : '../elfinder-1.x/src/connectors/php/connector.php',
		transport : new elFinderSupportVer1(),
		// more options
	});
});`

Thx

**Comment by nao-pon** [comment]
@dorel14 All you need to do is add the client option `transport: new elFinderSupportVer1 (),`. For example, [elfinder.html](https://github.com/Studio-42/elFinder/blob/master/elfinder.html#L18).
