### ISSUE TITLE
Multilingual support for Elfinder UI

### ISSUE THREAD

**Issue by gadangmadhulika** [Studio-42/elFinder#2935]
Hi @nao-pon 
I would like to work on multilingual support for Elfinder UI Elements (For example Russian language)

**Comment by nao-pon** [comment]
@gadangmadhulika That's great if you send better language files. You can use the “[i18n Translation Tool](https://studio-42.github.io/elFinder/tools/langman/#2.1:ru)”.

Thanks! 👍
