### ISSUE TITLE
How to get Volume information

### ISSUE THREAD

**Issue by mjyu51** [Studio-42/elFinder#2936]
When bind the command such as "upload.pre", $volume is passed to the handler. Is there document that can tell:
1) Volume path (absolute path);
2) Volume capacity
3) Used space
etc?

Thanks,

**Comment by nao-pon** [comment]
@mjyu51 Documentation on that matter is not in place. Please refer to the source code or debug the variable contents directly.  Note that Volume capacity and Used space are not supported, so you need to extend them yourself.

```php
function debug() {
    $arg = func_get_args();
    ob_start();
    foreach($arg as $v) {
        var_dump($v);
    }
    $o = ob_get_contents();
    ob_end_clean();
    file_put_contents('.debug.txt', $o, FILE_APPEND);
}
debug($volume);
```

**Comment by mjyu51** [comment]
Thanks! I got it worked out.
