### ISSUE TITLE
How to get target path from hash (front end js)

### ISSUE THREAD

**Issue by mjyu51** [Studio-42/elFinder#2937]
For upload, I need to check the target available space. in command js upload, I have the target path hash, how to convert it to absolute path? (so that I can use Ajax to get the available space).
Thanks

**Comment by nao-pon** [comment]
@mjyu51 Please  check #1564. Thanks!

**Comment by mjyu51** [comment]
I have read #1564 carefully but it is not what I wanted. 
I would like to get the file full path on the server (such as /mnt/abc/data/share/a.txt). I would to know this information in the javascript code (front end). 
I tried file.url  and it  can somehow work. But I would like to see if there an "official" way.  (also when I use hash, I may not be able to use file.url)
Thanks,

**Comment by nao-pon** [comment]
@mjyu51 For security reasons, the front end can not know the full path on the server. Use file.url if you like it.

Thanks!
