### ISSUE TITLE
bind "upload.pre", uploading large file hangs 

### ISSUE THREAD

**Issue by mjyu51** [Studio-42/elFinder#2938]
Testing bind "upload.pre". It worked well for uploading small files -- reported "test error" on front. B if uploaded file is large (such as 100MB), it will hang there forever. Is this a bug? How to fix it? 

function CheckSpace($cmd, &$args, $elfinder, $volume) {
     return array(
             'preventexec' => true,
             'results' => array('error' => 'test error')
                    );
}

bind: 
       $opts["bind"] =  array(
                        'upload.pre' => 'CheckSpace'
                    );

**Comment by nao-pon** [comment]
@mjyu51 I checked the behavior when uploading chunks, but it did not hang. Do you submit more detailed data?

**Comment by mjyu51** [comment]
Please use large amount of SMALL files. I can reproduce this behavior.

**Comment by nao-pon** [comment]
@mjyu51 'upload.pre' is called for each file, so if possible, reduce the cost of executing the callback function.

Thanks!
