### ISSUE TITLE
forcing elfinder to use sudo ?

### ISSUE THREAD

**Issue by mammnon** [Studio-42/elFinder#2939]
Hi,

The php connector is great, thanks.

I would like to access files as if apache were root. (apache must not start as root). I added the apache user in the sudo file to give all permissions without password confirmation, but all  commands issued by elfinder must be prefixed with "sudo"  .

I need you!
thanks

**Comment by nao-pon** [comment]
@mammnon I'm not thinking about putting sudo on every command issued by elFinder. Please consider allowing commands to run under Apache.

**Comment by mammnon** [comment]
ok thanks anyway.

I found out that nginx with php is awesome and way faster than apache (OTB). Plus I can manage rights in a very smart way and add capabilities to the php-fpm daemon. 
So I fixed the issue with a workaround. 

Still I love your work work.

Regards
