### ISSUE TITLE
Language not recognized in firefox (60) but is ok with chromium (73)

### ISSUE THREAD

**Issue by CratesDeThebes** [Studio-42/elFinder#2943]
I found that in the latest elFinder 2.1, the lang function in main.default.js is triggering an error and prevents the displaying of any content. This happens with firefox 60.7.0esr and not with chromium 73.0.3683.75 .

Error message:
TypeError: fullLang is undefined in main.js:25:4

Work around: Comment the lang function and replace it by lang = 'en_EN'

**Comment by nao-pon** [comment]
@CratesDeThebes I tried with Firefox 67.0.2, but that's fine. However, I found a place where error handling was insufficient. Please change it as follows and try it.

(Line 24 or 25)
```javascript
lang = fullLang.substr(0,2);
```
to
```javascript
lang = (fullLang || 'en').substr(0,2);
```
