### ISSUE TITLE
Can't organize files (no paste option)

### ISSUE THREAD

**Issue by jbvidex** [Studio-42/elFinder#2947]
Hi,

elFinder 2.1.42 comes bundled with the MailWizz email application that we use at work. We have quite a few images in our library now, so I was trying to organize them today. I found that I am unable to move or copy images into folders. There is no paste option, and drag-n-drop doesn't work. I can create a new folder, but can't move images into it!

Any suggestions?

**Comment by nao-pon** [comment]
@jbvidex I think that depends on your configuration.

**Comment by jbvidex** [comment]
Can you elaborate on the proper configuration?

**Comment by nao-pon** [comment]
@jbvidex I recommend that you read the wiki and learn about its configuration in the standalone elFinder.
