### ISSUE TITLE
Unable to active zoho editor

### ISSUE THREAD

**Issue by stianjaco** [Studio-42/elFinder#2949]
I'm trying to get the zoho editor to work.. Is there anything else i need to do then add my API key for zoho?
I've done this, but the plugin/editor does not seem to load, I dont get context menu to edit excel files

**Comment by nao-pon** [comment]
@stianjaco In general, you can use the editor simply by setting the Zoho API key.

https://github.com/Studio-42/elFinder/blob/master/php/connector.php-dist#L90-L92
