### ISSUE TITLE
move is slow

### ISSUE THREAD

**Issue by bgbruno** [Studio-42/elFinder#2954]
Hello - when I moving directory with hundreds files is very slow and "heavy load php process" which takes even minute without any cancelation so I have to wait for timeout.

Q why is that?
Q how can I skip that?

Bruno

**Comment by nao-pon** [comment]
@bgbruno elFinder checks files one by one with the settings and determines if the operation is possible. Therefore, the operation tends to be heavy depending on the number of items.

I start thinking about being able to cancel a time-consuming process.

Thank you!

**Comment by bgbruno** [comment]
@nao-pon thx - I have to cancel that "time-consuming process" stop by killing heavy loaded php process to protect cpu load

for example I move one directory - where is hundreds or thousands files, for example "node_modules"

**Q pls why it's necessary "checks files one by one" ?**

**Comment by nao-pon** [comment]
> Q pls why it's necessary "checks files one by one" ?

Because elFinder is a web application, it is a security requirement.

**Comment by bgbruno** [comment]
it is a security requirement
I know you made it like that @nao-pon - originally "php function rename" don't do that
Q is there some security issue that I don't see? :-)

**Comment by nao-pon** [comment]
> Q is there some security issue that I don't see? :-)

Since elFinder can move items from other volumes, it is necessary to check the directory contents.

**Comment by bgbruno** [comment]
I see - in that case it would be great make exception in "local fs"

Q what you think @nao-pon ?

**Comment by nao-pon** [comment]
@bgbruno There was my misconception. I have checked the source code, copying or moving within the same volume has not been checked within the directory. Also use PHP's copy or rename command on local file systems.

**Comment by bgbruno** [comment]
OK I understand

Q pls @nao-pon can you navigate me to that code - so I can check where is issue on my side?

**Comment by mjyu51** [comment]
Recently I looked at the code. The flow of the process is:
1. elFinder.class.php  has  paste() function (in which args has the list of files to be copied).  for each file/folder to be copied, it calls elFinderVolumeDriver.class.php 's  paste function 
2. In the paste function of elFinderVolumeDriver.class.php it calls copy() or copyFrom() ; copy function handles copy within volume and copyFrom handles copy between volume
3. copy will call _copy() function which is implemented by the "real" volume elfFinderVolumeDriverLocalFileSystem.class.php, in which it actually use php copy function to do the real copy job.
4. copyFrom seems to use saveCE function , in which it seem that it uses file stream, open file can copy file stream to destination.

I hope this help a little bit and @nao-pon  pls correct me if something is wrong.

**Comment by mjyu51** [comment]
@nao-pon， moving large amount of files or large file(s) could be really an issue as you have to keep the page open. Using a backend task (Daemon) could a solution for this. Would it be possible to consider this?

**Comment by nao-pon** [comment]
@mjyu51 There is no mistake in the sequence you presented.

There is a risk of accumulating unwanted tasks as background process using Demon etc. There is a risk that the web application elFinder handles it. So I don't think about having such a feature.

Another approach is to set up a new configuration that allows PHP functions to copy and move files between volumes of the local file system.

**Comment by nao-pon** [comment]
@bgbruno Are you having problems moving files within the same volume?

**Comment by nao-pon** [comment]
> Another approach is to set up a new configuration that allows PHP functions to copy and move files between volumes of the local file system.

I examined this, but gave up because VolumeDriver's copy / move function can only process in its own volume.

**Comment by nao-pon** [comment]
For this issue, I would like to close the copy / move command by making it cancelable.

**Comment by bgbruno** [comment]
backend task (Daemon) could a solution for this
@mjyu51 I think this could solve that issue

There is a risk of accumulating unwanted tasks as background process using Demon
@nao-pon that is true - but that can be cancelable - but I agree this can bring a lot of debugging

Another approach ... allows PHP functions to copy and move
I think this will be the best solution - rename,move should be fast like native operations

Are you having problems moving files within the same volume?
@nao-pon yes it's on local storage the same volume

VolumeDriver's copy / move function can only process in its own volume
OK

For this issue, I would like to close the copy / move command by making it cancelable
@nao-pon that not solve the origin issue - we need to know rename,move dirs with a lot of files in it - stop operation makes oppisite effect :-)

**Comment by nao-pon** [comment]
@bgbruno 
Summary:
If it is in the same volume (LocalFS) on elFinder, it is processed using PHP's copy / rename function. If it is still slow, the only option is to speed up the server's file system.

When copying and moving between volumes on elFinder, the processing speed is slow. This is by the elFinder specification. Therefore, cancellation was made possible as a minimum measure.

Thanks!

**Comment by bgbruno** [comment]
the same volume (LocalFS ... is processed using PHP's copy / rename function
**Q OK pls can you direct me to that code lines?**

If it is still slow, the only option is to speed up the server's file system.
that is not the issue - "#os rename,move" is super fast - unless problem is in origin "#php rename,move", I tested it

**Comment by nao-pon** [comment]
@bgbruno 
> Q OK pls can you direct me to that code lines?

class elFinderVolumeLocalFileSystem `_copy()` and `_move()`.

https://github.com/Studio-42/elFinder/blob/15cc46ea27e1700fc0d37d5244f8ff2d698d1fe8/php/elFinderVolumeLocalFileSystem.class.php#L910-L950

**Comment by mjyu51** [comment]
@nao-pon , Is it possible to do this:
$elf= new elFinder($opts);
$elf->paste($args);
Assuming that we know args.
Thanks,
