### ISSUE TITLE
Client side events issues

### ISSUE THREAD

**Issue by badochov** [Studio-42/elFinder#2957]
```javascript
elFinder.bind('change', function (e) {
    console.log(e);
    console.log(e.type);

    console.log(e.data._event.type);
    console.log(JSON.stringify(_.cloneDeep(e)));
    console.log(e.data);
    console.log(e.data._event);
    console.log(e === e.data._event);
    console.log(e.type==='mkdir');
    console.log(e.data._event.type);

    var cache = [];
    console.log(JSON.parse(JSON.stringify(e, function(key, value) {
        if (typeof value === 'object' && value !== null) {
            if (cache.indexOf(value) !== -1) {
                // Duplicate reference found, discard key
                return;
            }
            // Store value in our collection
            cache.push(value);
        }
        return value;
    })).data);
    cache = null; // Enable garbage collection
    return false;
}
```
That is output of first log
![image](https://user-images.githubusercontent.com/26444395/60891227-336dc180-a25d-11e9-95d2-b9111a85224b.png)

but when i try to access e.data._event the same object is returned not prop _event of prop data of e.

I was trying to solved this problem for few hours but have no idea why does it happen.

**Comment by badochov** [comment]
It happens due to circular structure but i dont know how to fix it

**Comment by nao-pon** [comment]
@badochov What is your goal?

**Comment by badochov** [comment]
i was trying to check event such as mkdir,rm and so on since they aren't in documentation but were there but after all i found out that i can just setup listeners for those events. Please add them to documentation or fix this issue

**Comment by nao-pon** [comment]
I also know that the documentation is not well maintained. However, I do not have enough time to maintain the documentation. Anyone can edit the document. We always welcome informative edits.

And, Having circular references in JavaScript objects is not a good thing. So I fix it.

Thanks!

**Comment by badochov** [comment]
Thanks, I'll edit it in free time
