### ISSUE TITLE
When unzipping,"Invalid backend response. Data is not JSON"

### ISSUE THREAD

**Issue by ji-ryoo** [Studio-42/elFinder#2959]
hello.

When I unzip a zip Including 6000 files , elfinder says "Invalid backend response. Data is not JSON".
Error displayed about 2～3 minutes after starting unzip.
I can not unzip completely.
There is no problem if the number of files is small.
I think timeout is not problem.

elfinder ver 2.1.44
php 7.0

## connector.minimal.php
`'uploadMaxSize' => '100g',`
`'maxTargets' => 0,`

## elfinder.html
`uploadMaxChunkSize : 1048576000,`

## php.ini
`memory_limit = 2G`
`post_max_size = 2G`
`upload_max_filesize = 2G`
`max_file_uploads = 1000000`
`max_input_vars = 200000`
`max_execution_time = 30000`

Are there any other relevant parameters?

**Comment by ji-ryoo** [comment]
I set error_reporting / display_errors but No errors.
"Invalid backend response. Data is not JSON" only.

**Comment by ji-ryoo** [comment]
I think file cause is that filename is shift-jis.

**Comment by nao-pon** [comment]
@ji-ryoo If your server's unzip command has the "-O" option, try the following...

```php
$opts = array(
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    )
);

// set 
define('ELFINDER_UNZIP_PATH', 'unzip -O sjis');

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```

**Comment by ji-ryoo** [comment]
@nao-pon 
i tried it. But it could not solve this problem.(`unzip -Ocp932` is same)

**Comment by nao-pon** [comment]
@ji-ryoo Perhaps that affects the server environment. Have you updated the server's PHP, unzip command etc?
