### ISSUE TITLE
Japanese file/folder display error.

### ISSUE THREAD

**Issue by ji-ryoo** [Studio-42/elFinder#2962]
This problem is similar to #2825

In various cases, there are times when Japanese can be displayed and sometimes can not be displayed

When Japanese file names are correctly displayed, the icons will be in binary format.
ppt icons  should originally display Japanese file names.
![issue](https://user-images.githubusercontent.com/36890599/61283741-8f55be80-a7f8-11e9-9db3-e30772ac55bc.png)

I do not know the reason at all.

**Comment by nao-pon** [comment]
@ji-ryoo What is the PHP version? If it is less than PHP 7.1, file systems other than UTF-8 may not be handled properly. Do you have similar issues with PHP 7.1 or higher?

**Comment by ji-ryoo** [comment]
@nao-pon php7.2 and 7.0. Both did not work well.
In the above image, when I reload the browser, all Japanese disappeared.

**Comment by ji-ryoo** [comment]
Sorry .My container's locale was not set correctly.
I set ja_JP.UTF-8. It worked!
```docker
RUN localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
```

**Comment by appleboy** [comment]
Same problem with other languages. I don't know why need to set locale for dependency.
