### ISSUE TITLE
url path to readable format

### ISSUE THREAD

**Issue by bgbruno** [Studio-42/elFinder#2963]
Hello @nao-pon ,

I have it in my mind a long time

I would like use "browser url omnibox" like native "fs path" and change it by text if I want and remember structure

so I thinking about "change unreadable path" like
`elf_l1_cmVhZGFibGUtcGF0aC9pbm5lci1wYXRo`
to "readable path" like
`elf//readable-path/inner-path`

it would be great if I can switch that format in settings

**Q pls where you create this path translation and would be the best create convertor?**

**Comment by nao-pon** [comment]
@bgbruno It is managed by the decode / encode function. You can override them to get the behavior you want.

https://github.com/Studio-42/elFinder/blob/ab0ac89a89238929f283fccc9bdfb81c2bbe7ec4/php/elFinderVolumeDriver.class.php#L3746-L3808

**Comment by bgbruno** [comment]
thx @nao-pon
