### ISSUE TITLE
Confirmation dialog for `move` commands

### ISSUE THREAD

**Issue by arnisjuraga** [Studio-42/elFinder#2967]
As mentioned #920 - it's really easy to move files and folders by accidental mouse drag.

Is it possible to easy configure, set confirmation dialog for move command?

**Comment by nao-pon** [comment]
@arnisjuraga Currently it is not easy to configure. But that is a good idea. I will add new options to make this possible.

Thanks! 👍

**Comment by nao-pon** [comment]
@arnisjuraga I done. Please try client option...

```javascript
commandsOptions : {
    paste : {
        moveConfirm : true // Display confirmation dialog when moving items
    }
}
```
