### ISSUE TITLE
Doesnt work upload the multiple file

### ISSUE THREAD

**Issue by Mesut90** [Studio-42/elFinder#2968]
I have elfinder.connector and elfinder.connector.aspnet dlls. I dont use core. I taking a fault when I try to upload multiple file. The fault name is "Unable to connect to backend.". But It work when I try to upload only one file. I investigated of dll, I saw the problem, First file go to folder as 0kb, After works a function on dll, getimagesize(). This function can't return with a value because file is 0kb.

**Comment by nao-pon** [comment]
@Mesut90 This problem seems to be a problem with the elfinder.connector.aspnet connector. Please ask the developer of the elfinder.connector.aspnet connector.
