### ISSUE TITLE
api param upload example

### ISSUE THREAD

**Issue by bgbruno** [Studio-42/elFinder#2972]
Hello @nao-pon ,

I want use your "API Upload"
https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#upload

but in definition there is no example for value of variable "upload"
`upload[] : array of multipart files to upload`

I try use "browser blob"
[https://{{app_domain}}/connector.php?cmd=upload&target=l1_{{dir_btoa}}&upload[]=blob:https://{{app_domain}}/{{browser_uuid}}]()
or "browser isolated filename"
[https://{{app_domain}}/connector.php?cmd=upload&target=l1_{{dir_btoa}}&upload[]=https_{{app_domain}}_0:Isolated_{{browser_uuid}}]()

both not work and I get error
`Notice:  Undefined index: scheme in ... elFinder.class.php on line 2534`
https://github.com/Studio-42/elFinder/blob/master/php/elFinder.class.php#L2534

I looked to your code
https://github.com/Studio-42/elFinder/blob/master/js/commands/paste.js
https://github.com/Studio-42/elFinder/blob/master/js/commands/upload.js
and I don't see what values are inputs in the process
or where is "api url calling"

**Q what values are entering the variable "api url: upload[]" ?**

Bruno

**Comment by nao-pon** [comment]
@bgbruno The upload parameter needs to send the browser file object by POST method.

- https://developer.mozilla.org/docs/Web/API/File
- https://www.php.net/manual/features.file-upload.post-method.php

**Comment by bgbruno** [comment]
ah of course thx @nao-pon ☺️ - I test it and confirm @later

**Comment by bgbruno** [comment]
Hello @nao-pon ,

I use standard "fetch post"
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Uploading_multiple_files

with data
```
var formData = new FormData();
formData.append('cmd', 'upload');
formData.append('target', 'l1_' + remote_btoa_path);
formData.append('upload[]', file_isolated_path);
```

with header
`headers: { 'Content-Type': 'application/x-www-form-urlencoded' }`

into body
`body: formData`

and everytime I get this error
`{"error":["errUpload","errUploadTotalSize"]}`

it's small 4KB file
through your interface is no problem with huge files

**Q any idea why that error?**
**Q can I get more "error info" ?**
**Q where in your code can I debug what comes to server?**


Bruno

**Comment by nao-pon** [comment]
@bgbruno `upload[]` should be set to a file object.
