### ISSUE TITLE
Mount network volume

### ISSUE THREAD

**Issue by mlh-ajay** [Studio-42/elFinder#2974]
I'm Using elFinder in MVC Project.
All were working great. Its working like charm.
But Mount network volume not showing. (Its showing in only PHP).
Please suggest for getting that option so i can connect to FTP Server.

**Comment by nao-pon** [comment]
@mlh-ajay What kind of MVC project do you use? If your server program is other than PHP, you need to geta connector that supports FTP.

**Comment by mlh-ajay** [comment]
Thanks for your Quick Response. Actually i was unable to reply earlier because of i m out of work for some days. But glad to see you response very fast..

Sorry i was forgot to mentioned. I m Using **Asp.Net MVC.**

**Comment by nao-pon** [comment]
@mlh-ajay "Asm.Net MVC" is not covered here. Please ask that Developer.
