### ISSUE TITLE
Can i update my Elfinder from 2.0 rc1 to 2.x or elfinder master by keeping my files save from server (cannot upload many files again).

### ISSUE THREAD

**Issue by Rana-Babar** [Studio-42/elFinder#2977]
Hi, can someone help me with the update of my version from Elfinder 2.0 rc1 to any latest version by keeping all my data save from server. I am having issue in extraction of files in my current version 2.0 rc1. 
Actually, it doesn't show me the extract button Clickable.

Hope to hear from you soon.
Thanks in advance. 
<img width="783" alt="Screen Shot 2019-08-07 at 2 55 04 PM" src="https://user-images.githubusercontent.com/53805724/62613766-8baee680-b923-11e9-9ec7-af99c5003faa.png">

**Comment by nao-pon** [comment]
@Rana-Babar If you haven't changed the code yourself, you are likely to upgrade by overwriting the "php" directory.

Be sure to back up your existing "php" directory before trying it out.
