### ISSUE TITLE
hide certain folders from all users

### ISSUE THREAD

**Issue by petrakid** [Studio-42/elFinder#2978]
Greetings!  My CMS stores all site images and uploaded content in an /assets/ folder.  Included in this folder are other folders (/carousel_images/, /landing_images/, etc) which I don't want users to see, potentially.  However I DO want them to see other folders, such as the /res/ folder or the /uploads/ folder, both with are in the same /assets/ folder.  How can I hide certain folders from users while not hiding others?  I really don't want to remake my folder structure if necessary.

**Comment by stalker780** [comment]
Check https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#accesscontrol

There is an example how you can hide .hidden folders and files with names starting with dot. You can do the same checking folder/file name
