### ISSUE TITLE
When will 2.1.50 be released?

### ISSUE THREAD

**Issue by vitek-rostislav** [Studio-42/elFinder#2981]
Hi, I just want to ask, when do you plan to release a new version, please? The release would be helpful for us in Shopsys (see https://github.com/Studio-42/elFinder/pull/2917#issuecomment-506609089), and I believe not only for us as there are quite a lot of fixes in the master since the last release  :slightly_smiling_face:

**Comment by nao-pon** [comment]
@vitek-rostislav Thank you for letting me know that! I will prepare for the release. Maybe released in a few days.

Thanks! 👍

**Comment by nao-pon** [comment]
I done. Thanks!
