### ISSUE TITLE
Error in selecting information to display content

### ISSUE THREAD

**Issue by pualz** [Studio-42/elFinder#2982]
1. Select a folder;

2. Click "View Details";

3. Click on other folders;

Error! The information displayed is the first folder information.

**Comment by mjyu51** [comment]
I don't think this is an error. It is simply because the dialog is modaless and it is not closed.

**Comment by pualz** [comment]
OK！Thank you for your answer .

I suggest：If you click on other folders, Close the last "View Details" dialog.

**Comment by nao-pon** [comment]
@pualz Please use quicklook to synchronize selected folders and display information.
