### ISSUE TITLE
lock all *.cs files

### ISSUE THREAD

**Issue by russh3l** [Studio-42/elFinder#2983]
i tried search but couldnt find .. 

i want to lock just all *.cs files ..

any help ?

**Comment by nao-pon** [comment]
@russh3l Please use an option [`attributes`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#attributes) of the volume root.

```php
array(
    array(
        'pattern' => '~\.cs$~',
        'read'    => true,
        'write'   => false,
        'locked'  => true
    )
)
```
