### ISSUE TITLE
conflict css with bootstrap 3.4.1

### ISSUE THREAD

**Issue by kevind11** [Studio-42/elFinder#2985]
Hello, when i try to use the latest version of elfinder with css from bootstrap 3.4.1 its cause misalignment in the top close and minimize button of the quicklook modal, also when the quicklook modal become fullscreen the close button is not showing. 
![Top button misalignment](https://user-images.githubusercontent.com/31906744/63740352-dab0c180-c8ba-11e9-9c00-44d6342b6293.png)
![Top button misalignment 2](https://user-images.githubusercontent.com/31906744/63740353-dab0c180-c8ba-11e9-9b9c-d22dca57c52e.png)
![Close button not showing](https://user-images.githubusercontent.com/31906744/63740351-da182b00-c8ba-11e9-8b3a-56ddedecdd15.png)

**Comment by nao-pon** [comment]
@kevind11 I done. Thanks! 👍

**Comment by kevind11** [comment]
Thank you too
