### ISSUE TITLE
MimeType text/x-twig for twig template

### ISSUE THREAD

**Issue by daebak74** [Studio-42/elFinder#2986]
Hello,
how to add in uploadAllow the mimetype text/x-twig for give permision to upload twig files ?

Thanks.

**Comment by daebak74** [comment]
At this moment I added in file mime.types text/html -> html htm twig and work.

**Comment by nao-pon** [comment]
@daebak74 I recommend using the volume option ['additionalMimeMap'](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#additionalMimeMap).

```php
'additionalMimeMap' => array(
    'twig:text/plain' => 'text/html',
    'twig:text/x-twig' => 'text/html'
)
```
