### ISSUE TITLE
show tree with files

### ISSUE THREAD

**Issue by bgbruno** [Studio-42/elFinder#2990]
Hello,

I would like show in tree directories with files

Q pls how can I do that?

**Comment by nao-pon** [comment]
@bgbruno elFinder doesn't have that function. For now, there are no plans to install it.

Thanks.

**Comment by bgbruno** [comment]
@nao-pon thx for confirmation

Q how would you suggest to do it? where in code?

**Comment by nao-pon** [comment]
@bgbruno Implementing this is not easy because the API and client processes are not supposed to display the file in the tree. So I don't have a plan to implement this.

**Comment by bgbruno** [comment]
I understand that

Q can you show me where is great to start to implement it?

**Comment by nao-pon** [comment]
@bgbruno First, you will need to modify [js/ui/tree.js](https://github.com/Studio-42/elFinder/blob/master/js/ui/tree.js). Check the source code for details.
