### ISSUE TITLE
[Bug] Elfinder destroys $_SESSION variables by himself

### ISSUE THREAD

**Issue by Fabibulle** [Studio-42/elFinder#2991]
Hello guys,
When I use elfinder like this 
`<a href="../Include/elFinder/1/elfinder.src.php" target="_blank">click here</a>`
When i click on it i have my Elfinder page (no problem with that).
But on the inital page, the $_SESSION are destroyed! 
Am I the only one to have this problem? What Elfinder does to me variables sessions? 
thank you

edit : in php/elFinderSession.php, i deleted these lines : (in function close() ) 

```
            if ($this->fixCookieRegist === true) {
                // regist cookie only once for apache2 SAPI
                $cParm = session_get_cookie_params();
                setcookie(session_name(), session_id(), 0, $cParm['path'], $cParm['domain'], $cParm['secure'], $cParm['httponly']);
                $this->fixCookieRegist = false;
            } */
```
And my variables seem to not be destroyed this time. :)

**Comment by nao-pon** [comment]
@Fabibulle If this works badly in an integrated environment, you can use your own session handler.

For example ...

```php
class myelFinderSession extends elFinderSession
{
    /**
     * {@inheritdoc}
     */
    public function __construct()
    {
        parent::__construct();
        $this->fixCookieRegist = false;
        return $this;
    }
}
$session = new myelFinderSession(array());
$opts = array(
    'session'=> $session,
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    )
);
```
