### ISSUE TITLE
Hide / show folder problem with php variable

### ISSUE THREAD

**Issue by Edotor** [Studio-42/elFinder#2993]
Hi all, I have a big problem with my connector config:
by default I hide all folder that are inside the principal folder named "files" with this command line  'defaults' => ['hidden' => true].
The problem is that I post a variable to the connector and from time to time, depending on the user connected, he passes a different $_POST['folder'] and therefore the same user should only see that folder without seeing the others. but it does not work!

the problem for me is here: 

`   
 'attributes' => array(
        array(  
            'pattern' => '!^/'.$my_folder.'!',
            'hidden' => false
        )
`
to the pattern, because if I put manually the string instead of the php variable $my_folder, it works fine, instead if I put the reference to the variable, it doesn't work, showing me all the folders inside  ../files/

This is my code into connector:

```php
$my_folder = $_POST['folder'];

$opts = array(
    'roots' => array(
        array(
            'driver' => 'LocalFileSystem', // driver for accessing file system (REQUIRED)
            'path' => ''../files/'.$my_folder.'/', // path to files (REQUIRED)
            'startPath'  => '../files/'.$my_folder.'/',
            'URL' => 'dirname($_SERVER['PHP_SELF']) . '/../files/'.$my_folder.'/', // URL to files (REQUIRED)
            'accessControl' => 'access',             // disable and hide dot starting files (OPTIONAL)
            'defaults' => ['hidden' => true]
        ),
    ),
    'attributes' => array(
        array(  
            'pattern' => '!^/'.$my_folder.'!',
            'hidden' => false
        )
    )
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();

```

Help Please!!!

**Comment by nao-pon** [comment]
@Edotor I recommend changing the root folder itself according to the user's role.

However, in many cases, restricting with post data creates security vulnerabilities. Please implement it after solving that point.

```php
$my_folder = $_POST['folder'];

$opts = array(
    'roots' => array(
        array(
            'driver' => 'LocalFileSystem', // driver for accessing file system (REQUIRED)
            'path' => ''../files/'.$my_folder.'/', // path to files (REQUIRED)
            'URL' => 'dirname($_SERVER['PHP_SELF']) . '/../files/'.$my_folder.'/', // URL to files (REQUIRED)
            'accessControl' => 'access'             // disable and hide dot starting files (OPTIONAL)
        ),
    )
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```
