### ISSUE TITLE
Logging of Remove shows blank file name

### ISSUE THREAD

**Issue by Skorefin** [Studio-42/elFinder#2994]
Hi,
All logging used from standard example code works except the following;

>         if (!empty($result['removed'])) {
            foreach ($result['removed'] as $file) {
                // removed file contain additional field "realpath"
                $log .= "\tREMOVED: " . $elfinder->realpath($file['hash']) . "\n";
            }
        }

Log file in rm cases shows;

> 	REMOVED: 
	ADDED: /home/kalara/public_html/assets/files/.trash/Chi Beach Club/Kalara-Welcome-Pack-2019 1.pdf
	CHANGED: /home/kalara/public_html/assets/files/.trash/Chi Beach Club

All other log records show file name.

Any clue while file name is blank for file removal?

Thanks

**Comment by nao-pon** [comment]
@Skorefin Since the file has been deleted, the file information cannot be obtained. However, there is a way to keep the file name etc. before deletion on the client side and retrieve them after deletion. It is possible to send that information from the client side to the server side.

rel. https://github.com/Studio-42/elFinder/issues/2464

**Comment by Skorefin** [comment]
That makes sense, thanks. 
Do you have example/best method  to retrieve files names client side & make available on server?

**Comment by nao-pon** [comment]
@Skorefin I am rethinking and suggesting a way to handle only on the connector side.
```php
class myEventHandler
{
    private $targets;
    function pre($cmd, $args, $elfinder, $volume) {
        $this->targets = array();
        if (!empty($args['targets'])) {
            foreach ($args['targets'] as $hash) {
                $this->targets['hash'] = $volume->file($hash);
            }
        }
    }
    function post($cmd, $result, $args, $elfinder, $volume) {
        $removed = array();
        if (!empty($result['removed'])) {
            if (!empty($this->targets['hash'])) {
                $removed[] = $this->targets['hash'];
            }
        }
        // You got removed file info in $removed
    }
}
$myEvHandler = new myEventHandler();
$opts = array(
    'roots'  => array(
        array(
            'bind' => array(
                'rm.pre' => array(array($myEvHandler, 'pre')),
                'rm' => array(array($myEvHandler, 'post'))
            ),
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    )
);
// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```

**Comment by Skorefin** [comment]
Server side better option me thinks.
Will give it a try. Once again, many thanks.
