### ISSUE TITLE
css/theme.css net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by padre** [Studio-42/elFinder#2997]
From version 2.1.43 elfinder erroneously loads theme.css. 

For example, if the elfinder page is domain.com/a/b/elfinder and the elfinder folder is hosted at domain.com/elfinder try to load domain.com/a/b/css/theme.css instead of domain.com/elfinder/css/theme.css.

**Comment by nao-pon** [comment]
@padre Please try using the `baseUrl` option.

```javascript
var options = {
    baseUrl = '/elfinder/',
    url  : 'php/connector.php',
    lang : 'en'
}
$('#elfinder').elfinder(options);
```
