### ISSUE TITLE
How to use Elfinder.class.php as standalone utility

### ISSUE THREAD

**Issue by mjyu51** [Studio-42/elFinder#2998]
Is there a way to use Elfinder.class.php as a standalone utility? I mean, not through elfinderConnector, just as a independent class. 
For example, create the options and then 
$elf= new elFinder(options);
$elf->exec('paste', $args);
or even directly $elf->paste($args)

Thanks!

**Comment by nao-pon** [comment]
@mjyu51 Since the exec function is public, `$elf->exec('paste', $args);` can be executed. On the other hand, `$elf->paste($args)` cannot be executed because it is not public.

**Comment by mjyu51** [comment]
That is my initial thought. Theoretically I should be able to do this. But when I tried it I found it seems that it does not work.
It looks like elFinder.class.php rely on session ? that means it may not work purely on the server by itself?

**Comment by nao-pon** [comment]
@mjyu51 What is results of `$elf->exec('paste', $args)`?

**Comment by mjyu51** [comment]
It seems that it does no  print anything. But nothing happens--- The files were not pasted (copied).

**Comment by nao-pon** [comment]
@mjyu51 Increase the error level of the PHP (`error_reporting (-1);`) to observe the error message and `$elf->exec('paste', $args)` to be observed in the return value with `var_dump()`, please try it.
