### ISSUE TITLE
How to set default preferences

### ISSUE THREAD

**Issue by zengenuity** [Studio-42/elFinder#3000]
I want to change the default preference for which file types can be created. 

<img width="466" alt="Screen Shot 2019-09-19 at 11 02 05 AM" src="https://user-images.githubusercontent.com/1405821/65256166-1b23e980-dacd-11e9-9804-8c058e028a1a.png">

I've searched everywhere in the documentation, but I can't find any information about how to set default preferences. I know the user can change this setting in the Preferences dialog, but I want to set the default values. Is there a way to do that?

<img width="642" alt="Screen Shot 2019-09-19 at 11 02 36 AM" src="https://user-images.githubusercontent.com/1405821/65256237-33940400-dacd-11e9-9173-1da7b4c0b5c1.png">

**Comment by nao-pon** [comment]
@zengenuity The text file can be set with "[commandsOptions.edit.makeTextMimes](https://github.com/Studio-42/elFinder/blob/3a1b46ffdacceb4242c9a6ed74da13b473c5828d/js/elFinder.options.js#L404-L405)". There are no setting items for other file types. Do you want to make new option to set the default selection state?

**Comment by zengenuity** [comment]
Thank you! That's mostly what I'm looking for. My goal was to add PHP file as an option under the New File button and context menu, and using commandsOptions.edit.makeTextMimes allows me to do that.

The only remaining question is whether there is a setting to remove the image type files from the new file list. makeTextMimes setting only allows me to customize the text ones. Is there another setting for image types?

<img width="433" alt="Screen Shot 2019-09-19 at 11 55 38 AM" src="https://user-images.githubusercontent.com/1405821/65260578-963cce00-dad4-11e9-95e8-5eca8c68931d.png">

**Comment by nao-pon** [comment]
@zengenuity By disabling the editor that can create a new image, it will disappear from the menu. There is no setting to turn off default by setting ON / OFF, so I plan to add it.

To change the editor to load, load your own editors.js instead of js/extras/editors.default.js.

**Comment by nao-pon** [comment]
@zengenuity I added an option `commandsOptions.edit.mkfileHideMimes`. (bc20fc74c5e0ce70a8bb9aa1d1b7ee77b48963eb)

You can try this option with the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

Thanks! 👍

**Comment by zengenuity** [comment]
I just tested it, and it worked. 

Adding: 
```
mkfileHideMimes: ['image/x-sketch', 'image/x-adobe-dng', 'image/x-portable-pixmap', 'image/vnd.adobe.photoshop', 'image/x-pixlr-data', 'image/webp', 'image/x-ms-bmp']` 
```
to `commandOptions.edit` hid all the listed formats from the New File dialog.

Thanks!
