### ISSUE TITLE
Upload Buttons

### ISSUE THREAD

**Issue by RaulZhn** [Studio-42/elFinder#3002]
Currently I am trying to remove the "Remove" and "Backup" buttons from uploading an existing file. Is this set in the commands or options?

**Comment by nao-pon** [comment]
@RaulZhn Please try a client option [`overwriteUploadConfirm`](https://github.com/Studio-42/elFinder/blob/bc20fc74c5e0ce70a8bb9aa1d1b7ee77b48963eb/js/elFinder.options.js#L113-L119) to `false`.

```javascript
var options = {
    url  : 'php/connector.php',
    overwriteUploadConfirm : false
}
$('#elfinder').elfinder(options);
```
