### ISSUE TITLE
How to integrate with tinyMCE 5

### ISSUE THREAD

**Issue by sbillard** [Studio-42/elFinder#3003]
I have integrated elFinder as the file manager for tinyMCE 5, but have one problem. The elFinder content does not fill the tinyMCE window.
<img width="1253" alt="2019-09-23 09_06_08-Development Admin_ Albums-Album" src="https://user-images.githubusercontent.com/2474007/65442766-a8bf4c00-dde1-11e9-8852-50fba4cf4f73.png">

How do I get the elFinder content use the full area?

**Comment by nao-pon** [comment]
@sbillard Please use cliant options `height` and `heightBase`.

```javascript
var options = {
    url  : 'php/connector.php',
    height : '100%',
    heightBase: $(DomNodeForHeightReference)
}
$('#elfinder').elfinder(options);
```
