### ISSUE TITLE
How to allow all type of files in elFinder?

### ISSUE THREAD

**Issue by ayeshamullani786** [Studio-42/elFinder#3007]
I am trying to uploadAllow the zip and html files. It shows Unable to upload "file_name.zip". File type not allowed. (application/zip) same with html files also can u please help me out.
public function connector()
{
$user = $this->session->userdata('user_account');
$user_id = base64_encode($user['user_id']);
$this->load->helper('url');
$opts = array(
'roots' => array(
array(
'driver' => 'LocalFileSystem',
'path' => 'uploads/'.base64_decode($user_id).'/',
'URL' => base_url().'uploads/'.base64_decode($user_id).'/',
'uploadDeny' => array('all'), // All Mimetypes not allowed to upload
'uploadAllow' => array('image', 'text/plain', 'text/html','application/pdf','application/zip'),// Mimetype image and text/plain allowed to upload
'uploadOrder' => array('deny', 'allow'), // allowed Mimetype image and text/plain only
'accessControl' => array($this, 'elfinderAccess'),// disable and hide dot starting files (OPTIONAL)
// more elFinder options here
)
),
);

   $connector = new elFinderConnector(new elFinder($opts));
   $connector->run();
}

**Comment by b33m4p** [comment]
'uploadDeny' => array(''), // All Mimetypes not allowed to upload
'uploadAllow' => array('all'),// Mimetype image and text/plain allowed to upload
