### ISSUE TITLE
Forum - Demo Page

### ISSUE THREAD

**Issue by jughead47** [Studio-42/elFinder#301]
I know this is not the place to put this, but on the elfinder.org page (http://elfinder.org/forum/), the Forum does not work correctly. Any page of the forums you click beyond the first one responds with this:

"Service Limit Reached!
There are more topics in forum, but the free version of this software is only able to display the 15 most recently active topics.
To allow unlimited access to this forum the admin needs to upgrade. "

Also, the forums do not allow me to reply or start a new post even after signing in.

Getting the forum up and working correctly so people can actually use it  can help a lot of people with problems.

**Comment by troex** [comment]
use StackOverflow for general question on elfinder
