### ISSUE TITLE
not work create .tmb in ftp

### ISSUE THREAD

**Issue by vahidalvandi** [Studio-42/elFinder#3011]
i use it in laravel

    'disks' =>[
        'ftp' => [
            'alias' => 'Cloud Storage',
            'path' => 'public_html/1',
            'URL' => 'https://bk.mysie.com/1',
            'imgLib'     => 'auto',
            'tmbPath'    => 'public_html/1/.tmb',
            'tmpPath'    => 'public_html/1/.tmp',
            'quarantine' => 'public_html/1/.quarantine',
            'attributes' => array(
                array(
                    'pattern' => '/\/\./',
                    'read' => false,
                    'write' => false,
                    'locked' => true,
                    'hidden' => true
                )
            )
        ]
      ]
it work fine with upload file and create folder but cant create .tmb folder
i work many hour for solve this but i can't solve.
please help me

**Comment by nao-pon** [comment]
@vahidalvandi Try setting the option [`tmbURL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#tmburl) correctly.

**Comment by vahidalvandi** [comment]
please show Official config for ftp

**Comment by nao-pon** [comment]
@vahidalvandi If the image content file size is not large, you can treat the image itself as a thumbnail.

```php
'disks' =>[
    'ftp' => [
        'alias' => 'Cloud Storage',
        'path' => 'public_html/1',
        'URL' => 'https://bk.mysie.com/1',
        'tmbURL' => 'self',
        'attributes' => array(
            array(
                'pattern' => '/\/\./',
                'read' => false,
                'write' => false,
                'locked' => true,
                'hidden' => true
            )
        )
    ]
  ]
```

**Comment by vahidalvandi** [comment]
> @vahidalvandi If the image content file size is not large, you can treat the image itself as a thumbnail.
> 
> ```
> 'disks' =>[
>     'ftp' => [
>         'alias' => 'Cloud Storage',
>         'path' => 'public_html/1',
>         'URL' => 'https://bk.mysie.com/1',
>         'tmbURL' => 'self',
>         'attributes' => array(
>             array(
>                 'pattern' => '/\/\./',
>                 'read' => false,
>                 'write' => false,
>                 'locked' => true,
>                 'hidden' => true
>             )
>         )
>     ]
>   ]
> ```

ok it solve tmb preview , i need tmp for use in product list . or a resize folder ...

**Comment by nao-pon** [comment]
@vahidalvandi The file name of the thumbnail is determined based on the file information. Thumbnails are recreated when they change.
You can create a new FTP volume driver with modified functions as needed.

https://github.com/Studio-42/elFinder/blob/ab0ac89a89238929f283fccc9bdfb81c2bbe7ec4/php/elFinderVolumeDriver.class.php#L5288-L5295
