### ISSUE TITLE
how can i check current elfinder version ?

### ISSUE THREAD

**Issue by russh3l** [Studio-42/elFinder#3012]
how can i check current elfinder version ?

**Comment by ytsurk** [comment]
Press the blue info icon and do not use your bots to SPAM the web!

**Comment by russh3l** [comment]
> Press the blue info icon.

from where ?

**Comment by nao-pon** [comment]
@russh3l Help icon is that.

![191130-120335](https://user-images.githubusercontent.com/1412630/69894901-c670da80-1369-11ea-8b85-a0d0cae4d6f6.png)
