### ISSUE TITLE
May i use it in Vue Project？

### ISSUE THREAD

**Issue by zhengzhi530** [Studio-42/elFinder#3015]
hi master,
    May i use it in Vue Project？and how to import these js file into my .vue? 
     I expect for your reply. 
                                                                                                          thanks！

![image](https://user-images.githubusercontent.com/13163577/67064471-3ef65000-f19d-11e9-9903-ffba1eb9f48f.png)

**Comment by nao-pon** [comment]
@zhengzhi530 I'm not sure about the Vue project. Please ask in the Vue Project community.
