### ISSUE TITLE
Extending Google Drive Mount time. 

### ISSUE THREAD

**Issue by dbetauk** [Studio-42/elFinder#3016]
Hello Sir, 

I would like to extend the session time for google drive mount from 1 hour to 6 hours. 

Would you be able to tell me which file I should look for that? 

Thank you.

**Comment by nao-pon** [comment]
@dbetauk GoogleDrive expiration date cannot be changed. It is a specification on the GoogleDrive side. Instead, you can get a permanent session with offline access.

![191020-184145](https://user-images.githubusercontent.com/1412630/67157644-cee8f500-f369-11e9-911c-7d454df661f9.png)

**Comment by dbetauk** [comment]
Thank you for for this!

Have a great day.
