### ISSUE TITLE
[cmd:edit] CodeMirror lib URL don't work as relative path when using RequireJS

### ISSUE THREAD

**Issue by Offerel** [Studio-42/elFinder#3018]
in elfinder.html i want to use a local copy of codemirror (or ace editor). For this to make work, i use the following in elfinder.html:
```
define('elFinderConfig', {
...
},
managers : {
					// 'DOM Element ID': { /* elFinder options of this DOM Element */ }
					'elfinder': { 
						cdns : {
						// for editor etc.
						ace        : null, // or your location
						codemirror : 'js/codemirror', // or your location
						ckeditor   : 'js/ckeditor',
						tinymce    : null, // or your location
						simplemde  : null, // or your location
						// for quicklook etc.
						hls        : null, // or your location
						dash       : null, // or your location
						prettify   : null, // or your location
						psd        : null, // or your location
						rar        : null, // or your location
						zlibUnzip  : null, // or your location
						zlibGunzip : null  // or your location
					}
					}
				}
```
i have downloaded and extracted full zip of `codemirror to /elfinder/js/codemirror` so that in this directory codemirror.js and codemirror.css are available (minifyed versions are genereated to). But then i now try to edit a php or js file, i get a 404 error: `https://mydomain.com/elfinder/js/js/codemirror/codemirror.min.js`. Why is the folder /js/js there instead of only one /js folder? How do i define that correctly?

Or is there some other way to use a local instance?

**Comment by Offerel** [comment]
Small Update:
It seems to be a bug in the codemirror implementation itself. I tried the same approach by using ACE Editor and there i had no problems. I can edit the files with that editor. It doesn't make any difference for my use case, if i use ACE or CodeMirror, so i stick with ACE for now. But i keep this issue alive, since i think someone should solve it for CodeMirror to.

**Comment by nao-pon** [comment]
@Offerel The default editor of elFinder is configured to read from cdnjs. I think CodeMirror has a read error because the folder structure is different between official and cdnjs.

There is a way to get CodeMirror from GitHub of cdnjs.

```
git init
git config core.sparsecheckout true
git remote add origin https://github.com/cdnjs/cdnjs.git
echo ajax/libs/codemirror/5.48.4 > .git/info/sparse-checkout
git pull origin master
```

Attached the file obtained by this method.
[cdnjs-CodeMirror-5.48.4.zip](https://github.com/Studio-42/elFinder/files/3763137/cdnjs-CodeMirror-5.48.4.zip)

**Comment by nao-pon** [comment]
@Offerel If doubling the "js" folder, can you solve it by changing `codemirror: 'js / codemirror',` to `codemirror: 'codemirror',`?

**Comment by Offerel** [comment]
No. I tried that also, but in that case it didn't find the first request and i get a 404 error for codemirror.min.js and codemirror.min.css. I think the first script (codemirror.min.js) loads fine and after some path finding doubles the first part of the path (inside codemirror scripts). Since i'm not really a JS expert, it's better you raise the issue upstream.

**Comment by nao-pon** [comment]
@Offerel I tested the previous zip by unzipping it locally. That was no problem.

- elfinder.html
- cdnjs-CodeMirror-5.48.4 folder
```javascript
cdns : {
    codemirror: 'cdnjs-CodeMirror-5.48.4'
},
```

**Comment by nao-pon** [comment]
@Offerel There seems to be a problem with the relative path judgment when using requirejs. There is no problem using an absolute path.

**Comment by nao-pon** [comment]
@Offerel I fixed this problem. You can try the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

Thanks! 👍

**Comment by Offerel** [comment]
I can confirm that your nightly build solves that issue. Many thx for that.
