### ISSUE TITLE
Thumbnails are recreated with different name

### ISSUE THREAD

**Issue by Offerel** [Studio-42/elFinder#3020]
I tried now the first time using the thumbnails. The problem is, that for the same images, the thumbnail will be created again and again, also, when the image didn't change in the meantime. Maybe i made something wrong when i configured the array?
```

array(
	'driver'        => 'LocalFileSystem',
	'path'          => $path,
	'uploadAllow'   => array('all'),
	'alias'		=> $storage_name,
	'uploadOrder'   => array('deny', 'allow'),
	'accessControl' => 'access',
	'tmbPath' 	=> '/tmp/elfindertmb',
	'tmbURL'        => 'self',
	'imglib'        => 'auto',
	'quarantine' 	=> '/tmp'
)
```

**Comment by Offerel** [comment]
strange. Now the old thumbnails are loaded and not created again. I have no idea whats happen before.

**Comment by nao-pon** [comment]
@Offerel If 'tmbURL' is "self", the image file itself is used. Specify the correct URL for the thumbnail directory.
