### ISSUE TITLE
Feature request: avoid traffic through the server using javascript clients for certains space providers

### ISSUE THREAD

**Issue by LeonSebastianCoimbra** [Studio-42/elFinder#3022]
Many space providers (dropbox, google drive and so on) provides also a javascript library to access their files (directly, without accessing it through a server where it si implemented the correspondant driver).

Assuming that there is no CORS problems (or that they can be overcome), is it possible to generalize ElFinder allowing it to choose if to retrieve the informations it needs through the classical connection or a javascript component?

This can be achieved, for instance, creating a standard interface for the calls that must be done to have the data: the default implementation will calls the server (as it is now) but it will be possible to replace it with a custom implementation that connects with dropbox or google drive or so on.

Furthermore, if it is possible to decide for every folder (or element inside the tree) which driver to use it will even more flexible.

With that, it will be possible for ElFinder to avoid traffic through the main server, with the result to lower the costs in case of a cloud installation (where the network traffic is payed).

Thanks for the attention and your work.

**Comment by nao-pon** [comment]
@LeonSebastianCoimbra Your opinion is correct and I have a similar opinion.

elFinder has `transport` as a client option. By using this option, you can implement data query by JavaScript.

We are always looking forward to pull requests that enable this functionality.

**Comment by LeonSebastianCoimbra** [comment]
Thanks for the tip, i will look into it and eventually make a report

**Comment by LeonSebastianCoimbra** [comment]
In the end, I did not implement (yet... I postponed it for the future) a full javascript connection to the external space providers, but I use the usual approach through a centralized connector.

But I did use "transport" to implement my own way to intercept the lack of authorization for a specific data source; in your example (https://studio-42.github.io/elFinder/#elf_g2_Lw) you mount (prior to use it) the remote site through a dialog and then populate the tree with the new root (the connection to the external space provider), while I, instead, start already with a tree filled with the list of all the possible roots for external space providers. 

All the roots starts initially closed: when the user click on one of them, if they already have the authorization the content will be loaded, otherwise a pop-up will alert the user of the missing authorization and then it starts the OAuth2 procedure.

To do so, i had to act on the "open" and "tree" requests, intercepting them and do checks and operations before their execution (eventually stopping their execution).

The steps are:
1. the user click on a root folder (a command "open" is triggered)
2. the command is intercepted, it is verified that it is not yet authorized and an authorization function is executed async (with parameters that identify the original command). The original procedure (the one that rise the "open" command) go to an end (without consequences, the command "open" is nullified)
3. the user complete with success the OAuth2 procedure, the status is now authenticated and a new "open" command is executed by the javascript



To implement step 2 i tried with the following:

- using "transport" as you suggest (it is the final implementation)
- using bindings (like in https://github.com/Studio-42/elFinder/wiki/Client-event-API)
- "hacking" the elfinder via something similar to:

`
        // Wrap all the ElFinder commands
        for (var cmd in fm._commands) {
            // Use "const" not "var", "var" is evaluated at call time
            const cCmd = cmd;
            const myFM = fm;

            if (myFM._commands[cCmd]['exec'] != undefined) {
                myFM._commands[cCmd]['_exec'] = myFM._commands[cCmd]['exec'];
                myFM._commands[cCmd]['exec'] = function () {

                    // NOTE: this hack is valid for standard ElFinder commands, not for the ui plug-ins (the ones defined
                    //       in the js/ui subfolder in the sources). The "tree" command is not intercepted here.
                    switch (cCmd) {
                        case 'open':
                            ...
                            request the authentication in an async way... this method ends without producing results
                            ...
                            return ___ a valid response that abort the command without errors ___;
                    }

                    // In this case the wrapper execute the original code.
                    return myFM._commands[cCmd]._exec.apply(this, arguments);
                }
            }
        }
`

The last example works fine but not in Firefox (72.0.2): when this code is called the _commands array is still empty, even if it is called on an "fm" object that has correctly been instantiated (in Chrome and Edge it works fine).



To execute step 3 i had some problems: i was able to call (from javascript) the "open" command with something like that:

`
var command = fm.one("open", function () {
  // Debug
  // console.log(arguments);
}).getCommand("open");
//
command.exec(opts.target, { thash: opts.target });
`

But i didn't find anything similar also for the command "tree" (it is a plug-in... it can not be executed like the "commands").

Plus, looking at the implementation of the "open" command i can not see how to call him with other parameters (like "init", "reload", "tree").


For my workflow, the way to call the "open" command is more than sufficient and instead of triggering a "tree" command i can again use an "open" command for my particular case, but it would be nice to be able to pass other parameters as well to the "open" command and also execute the "tree" command by javascript.

I checked the documentation and on-line but i didn't find anything related to this case... also the argument "execute commands by javascript" can be an interesting topic for a wiki page.

**Comment by LeonSebastianCoimbra** [comment]
Is there a way to stop the execution of a command once it is intercepted inside "transport"? Returning an empty Deferred (return $.Deferred();) does not works....

**Comment by nao-pon** [comment]
@LeonSebastianCoimbra About the tree command:

UI commands and connector commands do not always match. There is no tree command on the UI side, so if you need to query the connector side, use the fm.request () function. (fm is an elFinder client instance)

```javascript
fm.request({cmd: 'tree', target: 'targetDirHash'}).done(function(data) {}).fail(function(error) {});
```

About cancellation on "transport":

Reject $.Deferred() object.
```javascript
var dfd  = $.Deferred();

dfd.reject('error message if need it.'); // In some Sync/Async code....

return dfd;
```

**Comment by LeonSebastianCoimbra** [comment]
Thanks again for the all the tips.

**Comment by LeonSebastianCoimbra** [comment]
I'm sorry, i think i will not able to submit any proposal because i was moved on another job... Thanks for the help done up until now.
