### ISSUE TITLE
Change/add keybinding howto?

### ISSUE THREAD

**Issue by Offerel** [Studio-42/elFinder#3023]
Is there some way, that i can specify my own keybinding? For example i want to use "F4" for edit files. Per default this seems to be CTRL + E, but it didn't work in Firefox, maybe that is bind to a other function. Didn't tested Chrome for now.

**Comment by nao-pon** [comment]
@Offerel You can use a client option `commandsOptions.edit.shortcuts` to use "F4" shortcut.

```javascript
var options = {
    url  : 'php/connector.php',
    commandsOptions : {
        edit : {
            shortcuts : [{
                pattern : 'ctrl+e f4'
            }]
        }
    }
}
$('#elfinder').elfinder(options);
```

**However**, when I checked with Firefox on our demo site, there was no problem with the shortcut for "CTRL + E".

**Comment by Offerel** [comment]
Indeed, Firefox is not the problem. I have bind CTRL + E to KeePass... my fault. However, since i'm a big fan of TotalCommander i use mostly F4 to edit files. So i think it's a nice idea to have F4 bind also in elFinder. I can confirm that this works for me.
