### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by sirdash** [Studio-42/elFinder#3024]
hi
can not install this package
1 upload to the host
2 Rename /php/connector.minimal.php-dist to /php/connector.minimal.php
3 Load /elfinder.html in browser but show error

**error 1 is js alert**
script error for "extract/editors-default.main".
http://reguirejs.org/doc/errors.html#scripterror

**error 2 is js alert**
Script error for "elfinder".
http://reguirejs.org/doc/errors.html#scripterror

**Comment by nao-pon** [comment]
@sirdash Did you download the built package? This is the package.

- https://github.com/Studio-42/elFinder/releases
