### ISSUE TITLE
How to open different dialog with ckeditor 4 type (link, image, flash)

### ISSUE THREAD

**Issue by freewings89** [Studio-42/elFinder#3025]
At first, thank you for a good library. I have some troubles when integrated elFinder into my CMS. I'm using it with CKEditor 4 as the integrated method in your guide. Image upload and image manager is all good but i don't know how to open different dialog for different file type and folder like how can i config elFinder to open a new dialog file manager for flash files and folder for store flash files (different from images folder) when  i click "Flash" button in my editor and then "Browse Server". The same as when i click "Link" button and "Browse Server", the dialog should show for diffrent folder that store doc and pdf file.
Hope someone can help. Thanks

**Comment by nao-pon** [comment]
@freewings89 There is an option of client side [`startPathHash`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#startpathhash) or Alternatively, you can specify URL hash. (e.g https://studio-42.github.io/elFinder/#elf_l3_Q0tFX0ltZ3M )
