### ISSUE TITLE
Get files selected info on select event

### ISSUE THREAD

**Issue by daebak74** [Studio-42/elFinder#3027]
Hi, the getFileCallback fire on dblclick event I need to get files array on select event. Is there a way ?

Thanks.

**Comment by carriopablo** [comment]
You can get the elFinder instance
`var elFinder = $('#elfinder').elfinder(options).elfinder('instance');`
or if it's currently initzialiced
`var elFinder = $('#elfinder').elfinder('instance');`

And then get an array of selected files with the selectedFiles:
`var files = elFinder.selectedFiles();`

**Comment by daebak74** [comment]
@carriopablo thanks works! But in select event there is a vay? For example for the single selected file I do 

```
.bind('select', function(event) { // called on file(s) select/unselect
  var file= fm.file(event.data.selected[0]);
});
```

**Comment by jonatmoy** [comment]
Hello, this function doesn't return the path do you have a solution ?

**Comment by gicupc** [comment]
try this code:
.bind('select', function(e,fma) {
               $.each(e.data.files || fma.selected(), function(i, h) {
                  var url=fma.url(h);
                  console.log(url);
              });
});
