### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by wbrackenbury** [Studio-42/elFinder#3030]
Hello,

On the documentation page for Client-Server API v2.1 (https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1), the description for the `editor` command appears to be the same as for the `duplicate` command. Is this intentional?

Thank you!

**Comment by nao-pon** [comment]
@wbrackenbury That's wrong documentation. I fixed it. Thanks! 👍
