### ISSUE TITLE
FTP Connector C#

### ISSUE THREAD

**Issue by AniRithwin** [Studio-42/elFinder#3031]
Can anyone provide the source to connect FTP in elFinder ASP.NET MVC

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
