### ISSUE TITLE
Problem with file preview

### ISSUE THREAD

**Issue by daebak74** [Studio-42/elFinder#3035]
I have a strange issue that I would to investigate but until now I didn't find how.
If I select a file and click on preview the modal sow correctly the preview but if I click on the button next or previous even if I see that in file list the next one is selected the preview in modal not fire the preload of the new file. Where I can find the quicklook event of next button for make some debug ? 

Thanks.

**Comment by nao-pon** [comment]
@daebak74 I can't reproduce this problem. https://github.com/Studio-42/elFinder/blob/master/js/commands/quicklook.plugins.js , https://github.com/Studio-42/elFinder/blob/master/js/commands/quicklook.js are it.

**Comment by daebak74** [comment]
@nao-pon Yes I know I think any problem with some other plugin. Thanks for the information.
