### ISSUE TITLE
error when trying to mount google drive

### ISSUE THREAD

**Issue by gustavognu** [Studio-42/elFinder#3036]
![Captura de pantalla de 2019-11-20 12-25-18](https://user-images.githubusercontent.com/49495898/69267207-50fb5200-0b92-11ea-9980-f09995158861.png)
can someone help me how to correct this problem, I have added my values ​​in the variables
ELFINDER_GOOGLEDRIVE_CLIENTID and ELFINDER_GOOGLEDRIVE_CLIENTSECRET based on google from my account

thanks.

**Comment by nao-pon** [comment]
@gustavognu Is the required GoogleDrive library installed on the server and is it loadable?

For example, run `composer require google/apiclient:^2.0` in the server's elFinder php directory to enable `require './vendor/autoload.php';` in connector.minimal.php.
