### ISSUE TITLE
Upload problem when multiple folder, files if their names are same in ftp

### ISSUE THREAD

**Issue by russh3l** [Studio-42/elFinder#3041]
Hello,

When i try to upload same folders or files with in FTP; Elfinder stuck with "Reading folder information" and it doesnt start upload but if i try to upload one bye one its running. 

Any idea ?

**Comment by nao-pon** [comment]
@russh3l I can't reproduce this problem. Do you have more detailed information?

**Comment by russh3l** [comment]
> @russh3l I can't reproduce this problem. Do you have more detailed information?

example i have these folders in elfinder

folder1/folder2/folder3/xxx.jpg

and im uploading these same path from my desktop to elfinder, elfinder ask to me **"File named "folder1" already exists.
Replace old file with new one?"**

when i select **Yes** elfinder get stuck on "Reading folder information" and this is endless, never ends.

but if i dont have **folder1** folders or same name folders in elfinder i can upload without problem.
if i want to replace **xxx.jpg** i have go to full path for replace it.

**.jpg is just example.**

**Comment by nao-pon** [comment]
@russh3l Are you using the PHP connector bundled with elFinder?

**Comment by russh3l** [comment]
@nao-pon yes im using the php connector

**Comment by nao-pon** [comment]
@russh3l I have tested and found that using the Watermark plugin to upload many image files at once can cause PHP to hang. Does your problem match that?

**Comment by russh3l** [comment]
@nao-pon I dont sure but it looks match .. 

i can upload and replace many files if i am in path

also i can upload folders if these folders are not in path

just cant upload and overwrite with same folders 

i can take record a video if you want

**Comment by nao-pon** [comment]
@russh3l Uploading without an image file is fine if the Watermark plugin is the cause. Can you test on a folder that does not contain image files?

Also, having a video may help me find the problem.
