### ISSUE TITLE
Unable to have the correct name for a custom command

### ISSUE THREAD

**Issue by jgagnon-planiso** [Studio-42/elFinder#3044]
Hello,

I have created a custom command button, but I cannot have the right tooltip. Instead of the button's name, I have the command name. In fact, the name is added in the fm.messages array with the init binding in the creation process of elfinder. If I put the name in the js i18n and in the elfinder min js file, it works. However, the problem I do not have access to thoses files when I'm in the production environment and the files cannot be edited and saved. Is there any other way to have it or is it possible to correct the script to have this fixed?

Thanks

**Comment by nao-pon** [comment]
@jgagnon-planiso You can extend the message in the callback function of the `init` event. For example, in the demo site, i18nFolderMsgs.js is added in main.js.

- https://github.com/Studio-42/elFinder/blob/gh-pages/main.js
- https://github.com/Studio-42/elFinder/blob/gh-pages/i18nFolderMsgs.js

**Comment by jgagnon-planiso** [comment]
It doesn't work always, only randomly...

**Comment by nao-pon** [comment]
@jgagnon-planiso Try disabling or clearing the browser cache to verify.

**Comment by jgagnon-planiso** [comment]
It doesn't work.
