### ISSUE TITLE
Access windows share folder with credentials

### ISSUE THREAD

**Issue by irsan-dimyati** [Studio-42/elFinder#3046]
How to access windows share folder with credentials?

**Comment by nao-pon** [comment]
@irsan-dimyati Can you explain your goals in more detail?

**Comment by irsan-dimyati** [comment]
I want to access share folder in windows server using authentication.
in example //SERVER-NAME/ShareFolder
with username and password to access that folder..

**Comment by irsan-dimyati** [comment]
Any update or link for my question @nao-pon ?

**Comment by nao-pon** [comment]
@irsan-dimyati Please try assign a drive letter by network mount and try accessing it.
