### ISSUE TITLE
[Question] elfinder & codemirror: codemirror custom theme

### ISSUE THREAD

**Issue by osworx** [Studio-42/elFinder#3050]
According this tutorial (wiki) here: https://github.com/Studio-42/elFinder/wiki/Using-custom-editor-to-edit-files-within-elfinder
I am not able to call/assign a custom codemirror theme.

Loading a custom theme for elfinder works perfectly (see https://github.com/Studio-42/elFinder/wiki/How-to-load-CSS-with-RequireJS%3F & cssAutoLoad ) 
but no change with codemirror.
Maybe some "hidden" trick nowhere mentioned? ;)

**Comment by nao-pon** [comment]
@osworx The first thing I should say is that Wiki articles are out of date. The latest implementation is in "[js/extras/editors.default.js](https://github.com/Studio-42/elFinder/blob/master/js/extras/editors.default.js#L1514-L1669)". It is also loaded by default in release packages.

With that implementation, you can easily configure CodeMirror options.

```javascript
$('#elfinder').elfinder('instance').bind('editEditorPrepare', function(e, fm) {
	if (e.data && e.data.id && e.data.id === 'codemirror') {
		fm.loadCss(fm.convAbsUrl(fm.options.cdns.codemirror) + '/theme/monokai.css');
		e.data.opts.theme = 'monokai';
	}
});
```
