### ISSUE TITLE
File Download Configurations

### ISSUE THREAD

**Issue by mrgr4v1ty** [Studio-42/elFinder#3051]
Hey everybody,

I have a special situation. I'm using Laravel/VueJS (SPA) and web token authentication. The problem is that I cant download any file from Elfinder. 

- The browser says, "Failed - Server problem."
- I don't get any errors in the browser console nor network tab.
- I tested the API with Postman (and web token), and everything is fine.
- I don't have any connection problems at all.
- This is my connection config:
`title : 'File Manager',
                            url : this.$store.state.app.urls.elfinder.connector,
                            customHeaders: {
                                Authorization: window.axios.defaults.headers.common['Authorization'],
                            },
                            customData: {
                                _token: $('meta[name="csrf-token"]').attr('content')
                            },
                            useBrowserHistory : false,
                            autoOpen : false,
                            width : '80%',
                            height: '50%',`
- As you can see I have added necessary headers (thats why the connection works).

So I'm thinking if **customHeaders** are directly passed to all Elfinder ajax requests or not?

**Comment by nao-pon** [comment]
@mrgr4v1ty If the URL of the file is configured as a static URL in the elFinder connector settings, the browser will issue a request for downloading the file. In that case, the custom data will not be sent, so we assume that the download will fail.

Is it possible to get a file only with the session information that used cookies on your system?

In addition, I think that CSRF countermeasures when downloading a file are not so important if downloading the file does not cause any action on the server side.

**Comment by mrgr4v1ty** [comment]
About the CSRF you are right, I put it there when I was trying to test everything I could.
The point I want to mention is that I CAN download a file with Axios request to an Elfinder URL.
For example:
`https://localhost/filemanager/connector?_token=Hd3voF5NGGjNElm7bIBRVN4aFdDl4zTsNXaf0Qww&cmd=file&target=f1_RGFuaWFsL1NpZ25hdHVyZXMgSVJJVC9tYXR0aWFfc2lnbi5qcGc`
is an address that using **Axios get** method, and **responseType blob** is downloadable (i have set Axios to import necessary tokens).

I don't know if saying this gives you some idea or not.

thanks in advance,

**Comment by nao-pon** [comment]
@mrgr4v1ty  Yes, If you do not set the connector volume option [`URL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#url), it will be processed through the connector and the request will include custom data.

**Comment by mrgr4v1ty** [comment]
> @mrgr4v1ty Yes, If you do not set the connector volume option [`URL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#url), it will be processed through the connector and the request will include custom data.

was this a reply to my question on the first comment?

**Comment by nao-pon** [comment]
@mrgr4v1ty If the volume option [`URL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#url) of the **connector roots** is set, the download URL will be a static file URL with the file path appended to the URL, and no custom data will be added.

On the other hand, if the [`URL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#url) option is not set, the download URL will be via the connector (cmd=file) and the custom data will be included in the GET query.

Note that the [`URL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#url) option is a **connector-side option**.

(My English is written in Google Translate so it may be difficult to understand.)

**Comment by mrgr4v1ty** [comment]
Ok I understand, I didn't set URL option on server-side connectors, so the custom data are included. are custom headers also included in this situation?

**Comment by nao-pon** [comment]
@mrgr4v1ty Since the browser requests the file download directly, the HTTP header cannot be rewritten.

**Comment by mrgr4v1ty** [comment]
So, In this case, the problem is custom headers. Any idea how can I change the builtin download method to, for example, use Axios library?

**Comment by nao-pon** [comment]
@mrgr4v1ty Is it possible to pick up the GET query on the connector side and deal with it? If you can't do that, there is a way to get a Blob object with Ajax and download it with the <a> tag, but the process is complicated.

**Comment by mrgr4v1ty** [comment]
I don't know what you mean about picking up the GET query on the connector side.
Also, if you think the procedure of getting Blob with Ajax is documented anywhere, please let me know so I can read about it,

thanks a lot

**Comment by nao-pon** [comment]
I speculated that your system is validating tokens with custom headers. And I thought about doing it using a GET query. And Ajax downloads can be found in several implementations on [Google](https://www.google.com/search?q=download+file+via+ajax&oq=download+file+via+ajax).

**Comment by mrgr4v1ty** [comment]
I know how to download a file using ajax, I mentioned that I could download a file (elfinder URL) with ajax (Axios library in fact). But the problem is in Elfinder UI, how can I overtake the function that is responsible for downloading file and put my customized function?

is it possible in connector configuration, or should I change the source code?

**Comment by nao-pon** [comment]
It is not yet documented, but there is a connector roots option `uiCmdMap`. This option allows you to change the command on the UI side for each volume root.

As an example, #2562 is helpful.
