### ISSUE TITLE
[Question/Feature] + Developer setting disable Cache/Proxy

### ISSUE THREAD

**Issue by osworx** [Studio-42/elFinder#3055]
While developing for elFinder, it is boring to wait or close the browser (FF) each time aI want to see if a new function/setting/function is working.

Is there something I have overlooked?
A setting to disable (temporary while developing) this cahce/proxy?

If not, could it be added?
thx

**Comment by nao-pon** [comment]
@osworx For browser cache, when you open the browser developer tools, there is a checkbox for "Disable cache" on the Network tab.

**Comment by osworx** [comment]
@nao-pon Thx, but I have never enabled any cache - while developing.
Beside this, the dev console is also always open (just to see any response) and this checkbox of course also checked.
But it seems, that elFinder is caching some settings in the background regardless of such settings.
Maybe an issue with the stored values in the localStorage (and checking them)?

**Comment by nao-pon** [comment]
Certainly user settings are stored in local storage. The PHP connector also has a session cache enabled. A sure way to clear them completely is to open a guest window in Chrome.
