### ISSUE TITLE
Strange behaviour when using tmbURL

### ISSUE THREAD

**Issue by osworx** [Studio-42/elFinder#3056]
https://github.com/Studio-42/elFinder/blob/95147a1a2b6378ffc776a4835a1ea569246cf428/php/connector.minimal.php-dist#L141

According line above, whenever I define the **tmpURL** (beside the **path**), I recieve folling error:
```
mountErrors
    0
        Driver "elFinderVolumeTrash" : Root folder does not exist.
```
If only path is defined, it works.
~~Does no matter if the folder still exist or has to be created new (during initializing).~~
Sorry, incorrect info!
Message is shown when folder DOES NOT exist already!
So, I suggest an additional check and if NOT exist, create it new.
This is an important issue, because the standard values **../files/.trash/** and **/../files/.trash/.tmb/** of elFinder cannot (or should not) be used inside this system I am working on.

Could it be that the **tmbURL** should not be defined (beside **path**)?
Current definition is like:
```
array(
	'id'		=> '1',
	'driver'	=> 'Trash',
	'alias'		=> 'Mülleimer',
	'path'		=> DIR_IMAGE . '.trash/',
	'tmbURL'	=> HTTPS_CATALOG . 'image/.trash/'
)
```

Beside this, there is also another problem with the tmb (.tmb) folder, but I open another thread for this.

**Comment by nao-pon** [comment]
@osworx If you specify `tmbURL` appropriately, thumbnails will be displayed, otherwise thumbnails will not be displayed. It's just an influence.

**Comment by osworx** [comment]
@nao-pon How do you define "appropriately" correctly?
Currently I have defined tmbURL only once (1st root folder) and elFinder does what I told him to do: 
* only 1 .tmb folder
* thumbnails everywhere

But when I follow the tutorial(s) and define the same .tmb URL in each (root) folder, folders are created but no thumbnails are displayed.

And when I do not create custom folders and use the default settings, I will have .tmb and .quarantine folders everywhere.
The more, with the default settings these folders are created inside a directory public access should not be granted and possible.

**Comment by nao-pon** [comment]
@osworx Check that the relationship between `tmbPath` and `tmbURL` is correct. The default value of `tmbPath` is "files/.tmb". If you change `tmbURL`, also set `tmbPath` correctly.

**Comment by osworx** [comment]
Both tmbPath and tmbURL are correct - defined both to the same!
And both are defined only once - in the first root definition (and that works as I want).

As written, if tmpPath and tmpURL are defined in each root definition, it does not work.
See also for such my question for "default/common" definitions for all (instead of defining them again and again).

But why should they be "**files**" - a folder I do not want (because I do not have and do not want to have a folder called **files** somewhere).

Beside this, defining the folder to "somewhat" (in my case **image/.tmb**) works also.
And you should give the users (developers) the freedom to define there dirs and paths as they need it - and not the system wants ...

**Comment by nao-pon** [comment]
Of course, you can freely specify where to save thumbnails. I tested with the same destination on three drives. It was fine.

For example...
```php
$defArr = array(
    'tmbPath'=> '/absolute/path/to/.tmb',
    'tmbURL' => 'https://URL/to/.tmb',
);
$opts = array(
    'roots'  => array(
        array_merge(array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'https://URL/to/files/'
        ), $defArr),
        array_merge(array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files1/',
            'URL'    => 'https://URL/to/files1/'
        ), $defArr),
        array_merge(array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files2/',
            'URL'    => 'https://URL/to/files2/'
        ), $defArr),
    )
);
```

**Comment by nao-pon** [comment]
@osworx The directory specified by the 'path' option must be created in advance.
Does the latest nightly have the same problem with the 'tmbPath' option?

**Comment by nao-pon** [comment]
@osworx Does the [latest nightly](https://github.com/Studio-42/elFinder/archive/2.1.zip) still have this problem?

**Comment by osworx** [comment]
Did not test it with the latest nightly until yet.
Will try it when I have a few minutes and report back asap.
