### ISSUE TITLE
[Question] Global settings possible?

### ISSUE THREAD

**Issue by osworx** [Studio-42/elFinder#3058]
Based on this page here: https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1
I am not able to find something to define settings **valid for all folders (roots)**.
While I can define per drive (roots), is there a possibility to define settings valid for all roots (local folders) entries?
Without a "global setting" I have to define always the same for each roots entry.

In detail I am thinking in settings for upload*, tmb*, winHashFix and accessControl

Sorry if I have that overseen ..

**Comment by nao-pon** [comment]
@osworx There is no global setting for volume drivers. However, you can simplify the configuration by providing an array of default settings and merging the arrays.

**Comment by osworx** [comment]
Thx for the answer - this is what I though ..

But one problem still exists.
For example: defining per {root} different definitions (e.g. tmbPath and/or tmbUrl) will not work.
It works only, when defined only once in the first {root}!
Strange!

**Comment by nao-pon** [comment]
@osworx That's strange, so double check your settings.

**Comment by osworx** [comment]
How many times do you think I have checked and tried before posting here - countless!

**Comment by nao-pon** [comment]
Is this issue related to #3059? Currently, there is a bug that the path with the drive letter of Windows server is not processed correctly.

**Comment by osworx** [comment]
I would say everything using that function _absPath() and use NOT *nix will have troubles ..
So, yes.

**Comment by nao-pon** [comment]
@osworx Does the latest nightly have the same problem with the 'tmbPath' option?

**Comment by nao-pon** [comment]
@osworx Does the latest nightly have the same problem?
