### ISSUE TITLE
Plugin Dropbox2 failed suddenly

### ISSUE THREAD

**Issue by osworx** [Studio-42/elFinder#3060]
After configuring and successfully connecting to Dropbox (using Dropbox2 plugin), after several hours I am getting this message:
![elfinder_dropbox2_error_invalid_access_token_crippled](https://user-images.githubusercontent.com/1905204/70924058-34372a80-2029-11ea-9098-8b54c1e96bb3.png)

Result of that line (1090) here inside elFinder.class.php - function exec(..)
`'error' => htmlspecialchars($e->getMessage()),`

The more, elFinder stops after that output working, no filemanager anymore.
Maybe the output could be better fomatted, and instead a exit elFinder go ahead .. ?

p.s.: the error was my own, wrong definition of the access_token.

**Comment by nao-pon** [comment]
@osworx Has this problem been solved? You can close this  if you have solved it.

**Comment by osworx** [comment]
Hello, basicall yes.
Because I am doing it right now in another way.
But the wrong formatted message output will be the same if such come again.
btw: it should be mentioned that with defining the `access_token `no authentification is needed anymore (1 step less).
