### ISSUE TITLE
getConnectorUrl() return wrong URL (mixed https and wrong port 80)

### ISSUE THREAD

**Issue by osworx** [Studio-42/elFinder#3062]
Using the latest release of elFinder and the Dropbox2 extension.
If **access_token** is not defined, the workflow is to call Dropbox and authenticate the whole thing.
That works if at Dropbox a Redirect Url is set.

But the `elFinder function getConnectiorUrl()` is building a wrong Url.
https://github.com/Studio-42/elFinder/blob/95147a1a2b6378ffc776a4835a1ea569246cf428/php/elFinder.class.php#L4531

Example: instead of 
http://localhost/myweb/admin/index.php?route=extension/module/filemanager_extended&cmd=netmount&protocol=dropbox2&host=1

it builds (wrong):
https://localhost:80/myweb/admin/index.php?cmd=netmount&protocol=dropbox2&host=1

which leads in FireFox to an SSL warning (of course, mixing https and port 80 will not work together).
And because of the wrong return url the returned access_token cannot be stored.

Beside this, it would be good to have an (new) option to define the base return url (or parts of it) if elFinder is embedded (like mine) in another system and not used as stand alone application.

Taking above sample, the return url should have **route=extension/module/filemanager_extended** (this part should be defineable).

But primary the mixing of https and wrong port should be fixed asap.
Because the getConnectorUrl() is used also in all other connectors.

**Comment by nao-pon** [comment]
@osworx What is your server's `$_SERVER['HTTPS']` value?

**Comment by nao-pon** [comment]
@osworx I fixed this. If there is any problem, please reopen with the message.

**Comment by osworx** [comment]
> 
> 
> @osworx What is your server's `$_SERVER['HTTPS']` value?

Empty, nothing.
