### ISSUE TITLE
Incorrect configuration of the backend. No readable volume.

### ISSUE THREAD

**Issue by Ludo-Boa** [Studio-42/elFinder#3063]
Hi.
I get this error "Incorrect configuration of the backend. No readable volume." in my file manager.
I do not understand where the problem comes from.
Has anyone ever encountered this problem?

**Comment by nao-pon** [comment]
@Ludo-Boa Enable [debug mode on the connector](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#debug) and observe if any messages are displayed.
