### ISSUE TITLE
[announcement] there is a problem with Guzzle 6.5.0

### ISSUE THREAD

**Issue by nao-pon** [Studio-42/elFinder#3065]
There is a problem with Guzzle 6.5.0 bug in GoogleDrive connector etc. so we need to exclude 6.5.0 with the following command.

`composer require guzzlehttp/guzzle:'>=6.3.0 <6.5.0 || ^6.5.1'`

see https://github.com/guzzle/guzzle/issues/2448

**Comment by osworx** [comment]
And where to define this?
Sorry, but I am using Composer not that many times.

**Comment by nao-pon** [comment]
The issue has been resolved in the released Guzzle 6.5.2. So, `composer update` will solve it.

rel. https://github.com/guzzle/guzzle/issues/2488
