### ISSUE TITLE
"Unable to upload......transfer error"

### ISSUE THREAD

**Issue by BuffaloBrennan** [Studio-42/elFinder#3068]
Hopefully I can explain this ok.  Using php 7.2 and 2.1 I think.

I'm trying to use elFinder to upload files larger than 12MB but getting a load error.  If I use the following code on a php page the files upload fine - no problems:

![image](https://user-images.githubusercontent.com/25584497/71413324-8e4b7780-2649-11ea-9a1b-ee1711fe8dec.png)

but when using elFinder I get the error message:

![image](https://user-images.githubusercontent.com/25584497/71413365-c8b51480-2649-11ea-8723-7872de895ab5.png)

I've checked the PHP.INI and both fields used for max upload and max post (sorry forgot them at the moment) are both set to 200M

Im using the following connector with the 'uploadMaxSize' also set to 200M:

![image](https://user-images.githubusercontent.com/25584497/71413451-247f9d80-264a-11ea-84e6-5fc00b9bf47c.png)

Thank you for any assistance in advance

Shane Brennan

**Comment by nao-pon** [comment]
@BuffaloBrennan elFinder does chunked upload for large file uploads. It seems that the upload of the chunk failed. Is there any restriction on the frequency of access to the server?
