### ISSUE TITLE
Mkdir command have a isssues when I use Java server.

### ISSUE THREAD

**Issue by wayn111** [Studio-42/elFinder#3069]
When I upload the directory, the `mkdir` command will add a `upload[]` arg for upload files, below is code:
```
name? formData.append('upload[]', file, name) : formData.append('upload[]', file);
```
when formData add 3th arg `name`, the server revice file path not include parent directory path,so I edit this code is 
```
formData.append('upload[]', file)
```
only this, the server  revice file path include parent directory path.
Can you solve this?

**Comment by nao-pon** [comment]
@wayn111 According to the browser specifications, a file name can be specified as the third argument. Can't fix it on the Java connector side?

- https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects#Sending_files_using_a_FormData_object

**Comment by wayn111** [comment]
@nao-pon  Thank you for your reply, I have solve this question, thanks.

**Comment by nao-pon** [comment]
That's fine, but in elFinder, you can use non-directory type storage (GoogleDrive) as follows ...

```javascript
formData.append ('upload_path []', path);
```

It will pass the folder hashes on elFinder as `upload_path`,  they are same order to the `upload`. Can you process with that values?

**Comment by nao-pon** [comment]
@wayn111 OK, I made to send relative path on folder uploading. Thanks!
