### ISSUE TITLE
Box connector issues (some)

### ISSUE THREAD

**Issue by osworx** [Studio-42/elFinder#3073]
Created new test project with composer only.
Added elFinder, Google API 2, Dropbox and ziparchive - all via composer.
Therefore elFinder is currently latest nightly version 2.51

box is defined as:
2x define(..)
and
```
$roots[] = [
	'driver'		=> 'Dropbox2',
	'consumerKey'		=> 'KEY',
	'consumerSecret'	=> 'SECRET',
	'path'			=> '/'
];
```
Connecting to box works perfectly (new window), granting access also, but coming return the original window is the same .. and nothing is added (but **code** which will be used as access_token later is defined and coming back from box) - the first popup window is displayed again

![grafik](https://user-images.githubusercontent.com/1905204/71529314-72afcd80-28e4-11ea-89d4-ac3eabf47f6f.png)

At initialization an error is shown (debug enabled):
```
mountErrors

Driver "elFinderVolumeBox" : Required option `accessToken` is undefined.
```

Compared to the Dropbox connector, defining (inside the $roots array) 
`'accessToken' => 'TOKEN' `
solves the error, but establish no connection!
Beside this, **accessToken** or **access_token** is nowhere mentioned!

**Comment by nao-pon** [comment]
@osworx It's same to OneDrive. See #2121.

**Comment by nao-pon** [comment]
@osworx The latest nightly has been modified to properly handle refresh tokens. Try the latest nightly.
