### ISSUE TITLE
Authentification (return) URL not useable (elFinder 2.51 nightly)

### ISSUE THREAD

**Issue by osworx** [Studio-42/elFinder#3074]
Currently all net drives use a URL like:
`http(s):// myreturnurl[dot]com`
and then (some vars depend on the used connector/net drive):
`?cmd=netmount&protocol=dropbox2&host=1`

which leads to:
`http(s):// myreturnurl[dot]com?cmd=netmount&protocol=dropbox2&host=1`
(which could be correct in some cases).

Protocol can be some (like box, googledrive, dropbox2, etc.).

Bascially when using elFinder with another 'framework' or 'system' (e,g, a CMS) .. this is useless!
Why?
1. creating the base url cannot be used
A URL like `http(s):// myreturnurl[dot]com` is not that what many systems may need.
Instead this part should be configurable.
What if the system needs:

`http(s):// myreturnurl[dot]com/index.php?myFunction/mySubFunction`

2. second part of the URL should NOT start with ?
Why?
Taken the sample `http(s):// myreturnurl[dot]com/index.php?myFunction/mySubFunction`
I have already the ? in the URL - so useless.
The second part should start also with a configurable option, either ? when needed or &

Using the ampersand & would be correct in this case and lead to following (correct):
`http(s):// myreturnurl[dot]com/index.php?route=myFunction/mySubFunction&cmd=netmount&protocol=dropbox2&host=1`

But currently I get (2x ?):
`http(s):// myreturnurl[dot]com/index.php?route=myFunction/mySubFunction?cmd=netmount&protocol=dropbox2&host=1`

So if the connector/return URL could be globally defined and used inside the function 
`getConnectorUrl()`
in the **elFinder.class.php**, 
elFinder would be much more flexibel and could be much easier integrated into other system.

**Comment by nao-pon** [comment]
@osworx In order to handle such a case, the constant `ELFINDER_CONNECTOR_URL` has been provided. Define a value for this constant. 

- 51d0747b3b38b4beb33046248d7bf9f3254a2a61
- 5141b12bfdfc37c0af6c012196f26e3886121c58

Or you can set it for each volume with the volume option `url`.

```php
array(
	'driver'	    => 'Dropbox2',
	'consumerKey'	=> 'YOUR_KEY_HERE',
	'consumerSecret'=> 'YOUR_SECRET_HERE',
	'access_token'	=> 'YOUR_ACCESS_TOKEN_HERE',
	'path'		    => '/',
	'url'           => 'http(s)://myreturnurl[dot]com/index.php?myFunction/mySubFunction',
)
```

**Comment by osworx** [comment]
Okay, but that will not be valid for the second part of the url:
`&cmd=netmount&protocol=dropbox2&host=1` (dropbox2 here as sample)
which will be added in any case - or not?

Because this will add a second **&** to the url!

**Comment by nao-pon** [comment]
@osworx You are right. I will fix this.

Thanks! 👍
