### ISSUE TITLE
Unwanted/Unneeded calls to net drives & unmount permanent

### ISSUE THREAD

**Issue by osworx** [Studio-42/elFinder#3077]
3 issues:
1. every time when elFinder and the filemanager is opened, all defined net drives are looped through and initialized.
No matter if a "permanent" option is set or not.
It should be enough to initialize when open the connect popup or select in that window

2. if a net drive is already mounted (as permanent via option), it should be not selecteable inside the popup to reconnect again
And no "reinit" again (see # 1)

3. if a net drive is mounted as permanent, I am missing an option to unmount

**Comment by nao-pon** [comment]
@osworx 

1. Certainly the current specification is not good for performance. I will improve to delay the actual connection as much as possible.

2. Permanent mounting with the roots option is performed by the administrator, and mounting using the popup is performed by the user, and each has different characteristics. To mount using the popup, you need to set PHP constants. See comments in connector.minimal.php.dist.

3. Users cannot unmount if mounted permanently with the roots option.
