### ISSUE TITLE
elFinder 2.1.50 & Dropbox and/or GoogleDrive (test)

### ISSUE THREAD

**Issue by osworx** [Studio-42/elFinder#3079]
Because of too many unsuccessfully attempts to create a successfull integration of elFinder with net drives into a CMS, I have created today - as final test - a simple testszenario.

Overall: using elFinder with 2 net drive options (DropBox, GoogleDrive) result in a package over 36 MB!
For a distribution for end consumers (as module/pugin into their existing system) is this too much!
Here the devs should see what can be minimized.

Case 1: under Windows
Environement:
* Win10 (Ultimate) 32bit
* XAMPP with php 7.2.4, apache 2.4
* Browser FireFox 71.0

Here are the results:

elFinder 2.1.50 (files from standard downloadable versionfrom github)

szenario 1: 
- using elfinder.legacy.html
- no net drives, no external libraries

result: working, no errors

szenario 2 (Dropbox):
- using elfinder.legacy.html
- using DropbBox2 connector (composer require kunalvarma05/dropbox-php-sdk )

note: dropbox library added in folder php

dropbox config:
default roots array PLUS
// dropbox

> array(
> 	'driver'		=> 'Dropbox2',
> 	// same as app_key
> 	'consumerKey'		=> 'j18xxxxxxxxxxx',
> 	// same as app_secret
> 	'consumerSecret'	=> 'g5xxxxxxxxxxxx',
> 	'path'			=> '/'
> )

result:

A. opening elfinder (calling elfinder.legacy.html only)

> errors:
> mountErrors
>         Driver "elFinderVolumeDropbox2" : Required option "access_token" or "refresh_token" is undefined.
> 
> phpErrors
>         NOTICE: Undefined index: tokens in elFinderVolumeDropbox2.class.php line 449.

B. calling Dropbox to mount net drive, successfully granted and return
result is the opened window which displayes the result only:

{"exit":true,
**"error":"errReauthRequire",**
"debug":{
	"connector":"php",
	"phpver":"7.2.4",
	"time":1.3214271068572998,
	"memory":"5030Kb / 3188Kb / 512M",
	"upload":"",
	"volumes":[{
		"id":"l1_","name":
		"localfilesystem",
		"mimeDetect":"finfo",
		"imgLib":"gd"
	},{
		"id":"t1_",
		"name":"trash",
		"mimeDetect":"finfo",
		"imgLib":"gd"
	}],
	**"mountErrors":[
		"Driver \"elFinderVolumeDropbox2\" : Required option \"access_token\" or \"refresh_token\" is undefined."],
	"phpErrors":[
		"NOTICE: Undefined index: tokens in elFinderVolumeDropbox2.class.php line 449.",
		"WARNING: ini_set(): A session is active. You cannot change the session module's ini settings at this time in elFinderSession.php line 130.",
		"NOTICE: Undefined index: user in elFinderVolumeDropbox2.class.php line 329."**
	]}
}

szenario 3 (Google APi Flysystem):
- using elfinder.legacy.html
- using composer require nao-pon/flysystem-google-drive:~1.1 nao-pon/elfinder-flysystem-driver-ext

note: flysystem added in folder php
note2: tried flysystem, because the other option to use the original Google API is resulting in some bugs in their libraries!

google settings:
standard root array PLUS

> array(
> 	'driver'	=> 'FlysystemGoogleDriveNetmount',
> 	'client_id'	=> '66xxxxxx.apps.googleusercontent.com',
> 	'client_secret'	=> 'jw-xxxxxxxxxxxxxxx',
> 	'path'		=> '/'
> )

result:
A. opening elfinder (calling elfinder.legacy.html only)
errors:

**mountErrors
        Driver "elFinderVolumeFlysystemGoogleDriveNetmount" : refresh token must be passed in or set as part of setAccessToken**

phpErrors
        WARNING: unlink(\$RECYCLE.BIN): Permission denied in elFinderFlysystemGoogleDriveNetmount.php line 250.
        WARNING: unlink(\GitHub): Permission denied in elFinderFlysystemGoogleDriveNetmount.php line 250.
        WARNING: unlink(\System Volume Information): Permission denied in elFinderFlysystemGoogleDriveNetmount.php line 250.
        WARNING: unlink(\_S_V_N_local): Permission denied in elFinderFlysystemGoogleDriveNetmount.php line 250.
        WARNING: unlink(\_android_backup): Permission denied in elFinderFlysystemGoogleDriveNetmount.php line 250.
        WARNING: unlink(\android): Permission denied in elFinderFlysystemGoogleDriveNetmount.php line 250.
        WARNING: unlink(\server): Permission denied in elFinderFlysystemGoogleDriveNetmount.php line 250.

**The more, because of the bug _absPath() elFinder tries to unlink files in folders it should NEVER touch!**

B. connecting to GoogleDrive via popup, opening new window and granting access works perfectly
C. result (return from GoogleDrive) - same authentication window with result (only relevant part from whole output):

> "exit":true,
> "error":"errReauthRequire"

plus phpErrors:
**"NOTICE: Undefined index: user in elFinderFlysystemGoogleDriveNetmount.php line 129."**

I would say, this says more than enough!
Short conclusion: trying to use elFinder under Windows with net drives is a "waste of time" because of too many bugs everywhere!

Case 2: liveserver 
Environement:
* Linux
* php 7.3.13
* apache 2.4
* Browser FireFox 71.0

Szenarios same as above.

szenario 1:  same result, working, no errors
szenario 2 (DropBox):

szenario 3 (GoogleDrive): 
* after calling elFinder:

> mountErrors
>         Driver "elFinderVolumeFlysystemGoogleDriveNetmount" : refresh token must be passed in or set as part of setAccessToken
> 
> phpErrors
>         WARNING: unlink(/tmp): Permission denied in elFinderFlysystemGoogleDriveNetmount.php line 250.
> 

* after calling GoogleDrive (authentification works) - same window as authentfication, but with errors:
	

> "exit":true,
> 	"error":"errReauthRequire",

	

> "mountErrors":[
> 		"Driver \"elFinderVolumeFlysystemGoogleDriveNetmount\" : refresh token must be passed in or set as part of setAccessToken"],
> 	"phpErrors":[
> 		"WARNING: unlink(\/tmp): Permission denied in elFinderFlysystemGoogleDriveNetmount.php line 250.",
> 		"NOTICE: Undefined index: user in elFinderFlysystemGoogleDriveNetmount.php line 129."
> 	]

No dropbox try, guess the same laming errors as above!

Overall result on Linux server with net drives: also not useable.
Boring, boring .. and boring.
Maybe the elFinder and the libraries will be fixed and published when they are ready for work.

For me, this is it for the moment, tired of being a test user, tired of trying and trying over and over again useless settings.

**Comment by nao-pon** [comment]
@osworx When mounting using a network command (pop-up dialog), it is necessary to specify a PHP constant. You do not need to add connector settings to roots. Check the source code comments in php / connector.minimal.php.dist.

The size of the external library can't be helped by me as long as that library is used.

If the external library is too big to be included in the distribution package, you can also create a small app that issues php commands on the server side and gets it with composer.

**Comment by osworx** [comment]
> 
> 
> @osworx When mounting using a network command (pop-up dialog), it is necessary to specify a PHP constant. You do not need to add connector settings to roots. Check the source code comments in [php/connector.minimal.php.dist](https://github.com/Studio-42/elFinder/blob/master/php/connector.minimal.php-dist#L44-L52).

Both (PHP Constant and variable as shown above) are defined - this cannot be the reason.

> 
> The size of the external library can't be helped by me as long as that library is used.
> 
> If the external library is too big to be included in the distribution package, you can also create a small app that issues php commands on the server side and gets it with composer.

No option, as already written, the final product shall be available for noobs and no one of them know what composer is ..
And I cannot know if composer is available on their servers (local or live).
But I will have another way to get the files they will need.

The minimal connector php does not show how to add nor which param shall be sued if the drive should be **permanent**.
For DropBox e.g. the **access_token** has to be defined and that can be done only within the $roots array.

Also if the drive should be a "children" of a parent group, the **phash** param has to be defined.

Without adding connector settings (as you say), these things will never work.
And if NO popup to connect net drives shall be used (which is possible - just to mention), the connectors has to be defined.

Or I am wrong?
In general, the documentation is very spare and should be updated!

**Comment by nao-pon** [comment]
@osworx As you say, there are certainly missing examples of configuration details. Currently, there is conenctor.php.dist in the master or 2.1-src branch, which is not included in the distribution package. I will consider keeping this as connector.maximal.php.dist and including it in the distribution package.
