### ISSUE TITLE
Download Popup won't go away even after the download is complete

### ISSUE THREAD

**Issue by kevind11** [Studio-42/elFinder#3081]
![Screen Shot 2020-01-02 at 11 13 02](https://user-images.githubusercontent.com/31906744/71652461-669a9480-2d58-11ea-84ac-4539d070c17f.png)
![Screen Shot 2020-01-02 at 11 13 23](https://user-images.githubusercontent.com/31906744/71652462-67332b00-2d58-11ea-895c-11af356d8589.png)

Hello, when i try to download the file from the right click menu, the download popup indicator won't go away even though the file has been downloaded.
I'm using elfinder with Version: 2.1.50 - protocol version: 2.1050

**Comment by nao-pon** [comment]
@kevind11 This problem seems to occur when browser cookies are disabled. I will fix this.

Thanks! 👍

**Comment by doobo** [comment]
There is still this problem！
