### ISSUE TITLE
connector option "disable" > not all values working

### ISSUE THREAD

**Issue by osworx** [Studio-42/elFinder#3085]
elFinder v.2.1.50
Command "disabled" defined with (as array):

> 'archive', 'chmod', 'duplicate', 'extract', 'file', 'get', 'mkdir', 'mkfile', 'paste', 'rename', 'resize', 'rm', 'upload', 'zipdl'

and assigned to  a root-folder.

Unforunetaly these commands are still working (while they should NOT) in Toolbar and Context Menu:

> file get paste upload

All others are disabled.

And that's strange, because when I check e.g. "upload", I can find this code (VolumeDriver):
```
if ($this->commandDisabled('upload')) {
       return $this->setError(elFinder::ERROR_PERM_DENIED);
}
```

**Comment by nao-pon** [comment]
@osworx For the file and get commands, there are bugs that invalid setting does not work on the connector side. There is also a problem on the client side, and I will fix it. However, regarding the paste and upload commands, I cannot reproduce the problem. So, please provide steps to reproduce those problems in a minimal configuration of elFinder.

Thanks!

**Comment by osworx** [comment]
Disabled commands as described above.
Then I expect that **file get paste and upload are disabled** - while they are not:
![grafik](https://user-images.githubusercontent.com/1905204/72050342-2f306880-32c1-11ea-8943-2a5a2625b5c6.png)

As you can see all other commands are disabled, only those not.
But if someone wants to restrict access (and actions) on files or inside folders, they should work also.

In this context I am missing also to be able to disable **copy** as well.

**Comment by nao-pon** [comment]
@osworx That's fine because you can't see "Paste" and "Upload" in the context menu you showed. If "URL" is not set in the volume root setting and "File" is disabled, "Open" and "Download" should be disabled, so fix that. "Copy" will be disabled if you do not have read permission for the file.

**Comment by osworx** [comment]
If I define the permissions like that:
```

$rootPerms = [
    // file permissions
	'attributes' => [
		[
			'pattern'	=> '/config.php|index.php|php.ini|.htaccess|system/',
			'read'		=> false,
			'write'		=> false,
			'locked'	=> true,
			'hidden'	=> true
		]
	]
];
```

I get this result:
![grafik](https://user-images.githubusercontent.com/1905204/72074423-315eeb00-32f2-11ea-8d5d-30970741238b.png)

Define the permission like that:

```
$rootPerms = [
	// folder and file permissions (locked and hidden are not used here)
	'defaults' => [
        'read'		=> true,
        'write'		=> false
    ],
    // file permissions
	'attributes' => [
		[
			'pattern'	=> '/config.php|index.php|php.ini|.htaccess|system/',
			'read'		=> false,
			'write'		=> false,
			'locked'	=> true,
			'hidden'	=> true
		]
	]
];
```

I get this result:
![grafik](https://user-images.githubusercontent.com/1905204/72074564-7125d280-32f2-11ea-8ff7-294e64b0d6cb.png)

The disabled definition is defined like that:
```php
$rootDisabled['disabled'] = ['archive', 'chmod', 'duplicate', 'extract', 'file', 'get', 'mkdir', 'mkfile', 'paste', 'rename', 'resize', 'rm', 'upload', 'zipdl'];
```

Either I make something wong, or there are bugs ..

The general purpose of these settings are, to display the files, but the visitor should not be able to view, copy or download nor to edit these files.
Currently he can view, copy and download such files.

p.s.: this pattern is used because with the **access callback** I hide only folders/directories starting with a . (dot), otherwise files like a **.htaccess** are not accessable/visible!

**Comment by nao-pon** [comment]
In the screenshot, files that match the pattern you specified '/config.php|index.php|php.ini|.htaccess|system/' do not appear to appear as specified. It looks fine.

**Comment by osworx** [comment]
@nao-pon Yes, the pattern as shown works as expected (tested already with many different settings).
In conjunction with the **access callback** (where I block only directories - see param **$isDir**) many different options for hiding files are possible.

inside function access( .. ):
```
if( !$isDir ) {
	return;
}
```

**Comment by nao-pon** [comment]
@osworx I fixed some problems with the "disabled" option. However, keep in mind that the "file" command is for viewing / downloading a file via the connector, and the "get" content is for getting the file content via the connector. They do not affect retrieval via URL.

To prohibit file acquisition by the access user, prohibit it with the read attribute.
