### ISSUE TITLE
Missing defintion ELFINDER_CONNECTOR_URL in latest 2.1.51 package

### ISSUE THREAD

**Issue by osworx** [Studio-42/elFinder#3086]
You have added a new parameter https://github.com/Studio-42/elFinder/blob/1aa6fbf89ca9f66025fb13dc83801da6b05872df/php/connector.minimal.php-dist#L21
and
https://github.com/Studio-42/elFinder/blob/1aa6fbf89ca9f66025fb13dc83801da6b05872df/php/elFinder.class.php#L4558

but I cannot see that in the latest release (package).

Also missing the new check (for example. box & dropbox2)
https://github.com/Studio-42/elFinder/blob/1aa6fbf89ca9f66025fb13dc83801da6b05872df/php/elFinderVolumeDropbox2.class.php#L334
and
https://github.com/Studio-42/elFinder/blob/1aa6fbf89ca9f66025fb13dc83801da6b05872df/php/elFinderVolumeBox.class.php#L732

in the latest release.

When will these (important) changes be published?

**Comment by nao-pon** [comment]
@osworx Version 2.1.51 was actually tagged before the fix, as I forgot to release it. It will be reflected in Version 2.1.52.
