### ISSUE TITLE
elFinder adds classes "ui-draggable-disabled" and "ui-state-disabled" if click does not happen exactly on file name

### ISSUE THREAD

**Issue by vincenzo-mennella** [Studio-42/elFinder#3087]
Hi,
as said in title, if you don't click exactly on the filename, elFinder adds classes "ui-draggable-disabled" and "ui-state-disabled" to the clicked row.

![image](https://user-images.githubusercontent.com/7009056/72059036-7c1c3b00-32d1-11ea-97da-58fa47b50134.png)

If you click slightly below or on on every other part of the blue selection line, the filename acquires the mentioned classes.

**Comment by nao-pon** [comment]
@vincenzo-mennella I can't reproduce it correctly. Is there same problem in [our demo site](https://studio-42.github.io/elFinder/)?

**Comment by vincenzo-mennella** [comment]
Hi @nao-pon, thank you for your reply!
No, I can not reproduce it on your demo site. I'm using elFinder version 2.1.51, jQuery 1.8.2 and jQueryUI 1.9.0 (unfortunately I can not easly upgrade them)

Tried to remove the theme from elFinder, but the problem persists.

**Comment by nao-pon** [comment]
OK, I fixed it. Thanks! 👍

**Comment by vincenzo-mennella** [comment]
I have manually applied your patch and can confirm that it's working fine now!

Thank you!
