### ISSUE TITLE
Php 7.4 curly braces error

### ISSUE THREAD

**Issue by anndro** [Studio-42/elFinder#3089]
local.ERROR: Array and string offset access syntax with curly braces is deprecated {"userId":1,"exception":"[object] (ErrorException(code: 0): Array and string offset access syntax with curly braces is deprecated at --/vendor/studio-42/elfinder/php/elFinder.class.php:2614)

**Comment by nao-pon** [comment]
@anndro Thank you to notification. This problem was fixed via [this PR](https://github.com/Studio-42/elFinder/pull/3070). Please wait release Version 2.1.52.

**Comment by anndro** [comment]
Problem occurs at version 2.1.10. But When I check latest commits, it fixed on master branch. But not published yet latest release 2.1.51. Manually fixed on php/elFinder.class.php file to change 

` if ($url{0} != '/') { // Relative path`
to 
`if ($url[0] != '/') { // Relative path`

**Comment by anndro** [comment]
> @anndro Thank you to notification. This problem was fixed via [this PR](https://github.com/Studio-42/elFinder/pull/3070). Please wait release Version 2.1.52.

Thank you :)
