### ISSUE TITLE
Djvu view

### ISSUE THREAD

**Issue by Dndi312** [Studio-42/elFinder#3091]
Hello, how to view djvu files, for example, when you open a pdf file, viewing goes on, and when you open a djvu file, it immediately downloads ...

**Comment by nao-pon** [comment]
@Dndi312 There is a volume root option [`dispInlineRegex`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#dispInlineRegex) that specifies the file types that can be displayed inline in the browser. The default values are as follows:

```php
dispInlineRegex' => '^(?:(?:video|audio)|image/(?!.+\+xml)|application/(?:ogg|x-mpegURL|dash\+xml)|(?:text/plain|application/pdf)$)',
```

The default value allows Djvu's MIME type (image/vnd.djvu) to be displayed inline, so it will only be displayed inline if **your browser can display image/vnd.djvu**.

**Comment by Dndi312** [comment]
oh, ok thanks
