### ISSUE TITLE
 Encoding

### ISSUE THREAD

**Issue by Dndi312** [Studio-42/elFinder#3092]
I have such a problem, in general, when I upload files with the name of the Cyrillic, that is, files with Russian names, they are loaded, but when I open it gives an error that the file was not found, how to fix it?

![error](https://user-images.githubusercontent.com/59817678/72597924-fa638780-3938-11ea-8a26-6801a7af1e3b.jpg)

**Comment by nao-pon** [comment]
@Dndi312 The [`encoding`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding) and [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale-1) of the volume root options must be the same as the server's file system. However, for a Windows server you should use PHP 7.1 or higher and do not need to set these values.

**Comment by Dndi312** [comment]
Thank U!)
