### ISSUE TITLE
PHP 7.4: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by Kronos1026** [Studio-42/elFinder#3094]
Hello,

please replace in line:

https://github.com/Studio-42/elFinder/blob/783709d6b97cafba586b0aa61e48b271407821fb/php/elFinder.class.php#L2614

`if ($url[0] != '/') { // Relative path `

curly braces with brackets

PHP RFC: Deprecate curly brace syntax for accessing array elements and string offsets: https://wiki.php.net/rfc/deprecate_curly_braces_array_access

Thanks,
Alexey

**Comment by nao-pon** [comment]
@Kronos1026 Thank you to notification. This problem was fixed via [this PR](https://github.com/Studio-42/elFinder/pull/3070). Please wait release Version 2.1.52.

rel. #3089
