### ISSUE TITLE
PDF/  disable download button 

### ISSUE THREAD

**Issue by Dndi312** [Studio-42/elFinder#3096]
Hello everyone!

There is such a problem, in general I want to do so, when viewing pdf files there was no download button, how can I do this?

I looked at the code
in elfinder.full.js but there was nothing to download about it

	/**
	 * PDF preview plugin
	 *
	 * @param elFinder.commands.quicklook
	 **/
	function(ql) {
				var fm      = ql.fm,
			mime    = 'application/pdf',
			preview = ql.preview,
			active  = false;
			
		if ((fm.UA.Safari && fm.OS === 'mac' && !fm.UA.iOS) || fm.UA.IE) {
			active = true;
		} else {
			$.each(navigator.plugins, function(i, plugins) {
				$.each(plugins, function(i, plugin) {
					if (plugin.type === mime) {
						return !(active = true);
					}
				});
			});
		}

		active && preview.on(ql.evUpdate, function(e) {
			var file = e.file, node;
			
			if (file.mime === mime && ql.dispInlineRegex.test(file.mime)) {
				e.stopImmediatePropagation();
				ql.hideinfo();
				node = $('<object class="elfinder-quicklook-preview-pdf" data="'+fm.openUrl(file.hash)+'" type="application/pdf" />')
					.appendTo(preview);
			}
			
		});
		
			
	},

**Comment by nao-pon** [comment]
@Dndi312 There is an option "[commandsOprions.quicklook.pdfToolbar](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L356-L357)" in the client options.

**ex.**
```javascript
var options = {
    url  : 'php/connector.php',
    commandsOptions : {
        quicklook : {
            pdfToolbar : false
        }
    }
}
$('#elfinder').elfinder(options);
```
