### ISSUE TITLE
"Unable to create archive" error deletes my files

### ISSUE THREAD

**Issue by pqr** [Studio-42/elFinder#3097]
elFinder version 2.1.52
driver: LocalFileSystem
PHP Version 7.3.11 (php-fpm, nginx, ubuntu 16.04)

When I select several files and click download button I get popup error message: "Unable to create archive".
What is more - selected files is being deleted!

Downgraded to 2.1.51 - error gone, this version works fine.

I found similar issue: https://github.com/Studio-42/elFinder/issues/3042, some noticable info: my folder with files is on different device than /tmp (my be it's releated).

**Comment by nao-pon** [comment]
@pqr I have created a new bug in 3527c2a1af5524f9f53c43c46e2fffc4a4fbb81a. I will release 2.1.53 as soon as possible after the fix.

Thanks! 👍
