### ISSUE TITLE
MOVE fails

### ISSUE THREAD

**Issue by stollar** [Studio-42/elFinder#3101]
When I try to move a .mkv file it fails. Error message:
Unable to move "filename". File type not allowed.
Tried debugging and the list of allowable mime-types for move is only 6 (some images and plan text).

**Comment by nao-pon** [comment]
@stollar Move internally deletes the file and then adds the file. Therefore, a setting that allows you to upload that file type is required. Check the "[uploadAllow](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadallow)" item in the connector options.
