### ISSUE TITLE
iPad resolution and Thumbnail

### ISSUE THREAD

**Issue by marcbth** [Studio-42/elFinder#3102]
Hello, everybody,

thanks a lot for Elfinder.

i just installed Elfinder via git.

now to my problems:

1. on the iPad i can't see the navigation on top and there is no fullscreen.

2. thumbnails are not visible.

as attachment pictures

Maybe there's a solution.

Thank you very much in advance.

Cliff
![IMG_0031](https://user-images.githubusercontent.com/23519079/73497573-63c4ab00-43bb-11ea-98eb-52856b13cf71.jpg)
![IMG_0030](https://user-images.githubusercontent.com/23519079/73497574-63c4ab00-43bb-11ea-8873-22a4dfdee387.jpg)

**Comment by marcbth** [comment]
Hello,

for the 1

showSelectCheckboxUA : ['Mobile'],

i works 

but i have no automatic fullscreen

**Comment by marcbth** [comment]
i found this

var options = {
    url : 'php/connector.php',
    bootCallback : function(fm, extraObj) {
        fm.options.commandsOptions.fullscreen.mode = fm.UA.Mobile? 'screen' : 'window';
    }
}

but in which file?

**Comment by marcbth** [comment]
when i open a image then

192.168.178.79/elFinder/php/home/soulm/share/music/Anastacia - Anastacia/folder.jpg?_t=1259264706

404 file not found

the original path is home/soulm/share/music/Anastacia - Anastacia/folder.jpg

**Comment by nao-pon** [comment]
@marcbth On mobile browsers, the top toolbar is hidden by default. You can view it by swiping from the top. See [`uiOptions.toolbarExtra.autoHideUA`](https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js#L818-L819) in Client Options.

The reason why the thumbnail is not displayed and the display is a 404 error is a mismatch between the connector option [`path`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#path) and [`URL`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#url) values. Recheck your settings.
