### ISSUE TITLE
WARNING: setcookie(): Unrecognized key 'lifetime'

### ISSUE THREAD

**Issue by lianee** [Studio-42/elFinder#3103]
`WARNING: setcookie(): Unrecognized key 'lifetime' found in the options array in elFinderSession.php line 227.`

`session_get_cookie_params()` returns a `lifetime` key that generates a warning in `setcookie()`.

`unset($cParm['lifetime']);` before `setcookie()` fixes it.

**Comment by nao-pon** [comment]
@lianee Thanks! 👍
