### ISSUE TITLE
nameAccepted() broke outputJson() sometimes

### ISSUE THREAD

**Issue by TechCatOther** [Studio-42/elFinder#3104]
I found that function nameAccepted() check for names and return errors on json_encode $name. But other users of nameAccepted write this error and $name of file to errors array, then try to json_encode it. As result nothing output in outputJSON().

`  'warning' => 
  array (
    0 => 'errSave',
    1 => '����������',
  ),
`
https://github.com/Studio-42/elFinder/blob/a35eabc9eb93cc68b764a0b9f846a6acd26ef392/php/elFinderConnector.class.php#L355

**Comment by nao-pon** [comment]
@TechCatOther Does this issue occur when unpacking the archive? If so, this problem may occur if the file name in the archive is not UTF-8. Some measures may be required.

**Comment by TechCatOther** [comment]
Yes. It's happend when extract files from archive. Users got strange message about JSON, but all files with correct names already extracted.

**Comment by nao-pon** [comment]
@TechCatOther I tried to fix it. Can you verify with the following file?

- https://github.com/Studio-42/elFinder/blob/extract_encode/php/elFinder.class.php
- https://github.com/Studio-42/elFinder/blob/extract_encode/php/elFinderVolumeDriver.class.php

**Comment by TechCatOther** [comment]
Thanks a lot. Now extracting correct.

**Comment by nao-pon** [comment]
@TechCatOther Thank you for your verifying! I merged it to master branch.
