### ISSUE TITLE
Sharable Link

### ISSUE THREAD

**Issue by furkankahvecii** [Studio-42/elFinder#3109]
Can I make a shareable link with Elfinder? Can users download some of their files to people with link addresses ? Sorry for my english.

**Comment by mjyu51** [comment]
I believe in the context menu, there is a  link that is available. You may use that for sharing with friend. There might be a security issue.

To have a better (or "standard") Share, you may consider the following:
1) create a context menu "Share"
2) when clicked , pop up a dialog in which you may ask the password for protection, expiration and other information. Backend creates a hash for the file/dir and display on the dialog;
3) share the hash dir with others;
4) create a "download" PHP code to check password/expiration etc and download file.
You may need a small database/file to record the password and expiration information. You may also need to check if the logged in user has the privilege to create a "share"
