### ISSUE TITLE
Cannot open file with double click

### ISSUE THREAD

**Issue by jgagnon-planiso** [Studio-42/elFinder#3110]
Hello,

Since a while, I cannot open a file with double clicks. Client options doesn't content any getFileCallbacks, I do not bind any dblclick events neither. What could prevent opening a file this way? For the folders, I can open them by double clicks though.

Thanks

**Comment by nao-pon** [comment]
@jgagnon-planiso Since no other similar problems have been reported, it may be due to your configuration or operating environment. Are there any errors in the browser console?
