### ISSUE TITLE
Add a close button on the notify dialog?

### ISSUE THREAD

**Issue by mjyu51** [Studio-42/elFinder#3111]
Can we add a close button like this: (so that we can close the notify dialog)

![image](https://user-images.githubusercontent.com/7358699/74613925-c8307b80-50d8-11ea-8c4f-b2db1612ad6d.png)

**Comment by nao-pon** [comment]
@mjyu51 Sometimes we want to hide it. The notification dialog is shared by all notifications, so once you hide it, it will reappear if you get another notification. Do you like that feeling?

**Comment by mjyu51** [comment]
@nao-pon , If we can make it an option for the user/developer, it will be much more powerful. I understood that notifications share the the dialog. I am wondering if it could be possible to add an option to the shared notifications dialog with this top-right cross button for closing all notifications and the dialog ( like a standard "window" with close button.
This will be much more flexible.

Thanks,

**Comment by nao-pon** [comment]
@mjyu51 The display / non-display option of the close button is set in the notification dialog collectively (set at initialization). Also add a minimize button (always enabled). When minimized, it becomes a small icon with a percentage and a progress bar in one corner of the screen. Click the icon to return to its original size.

**Comment by mjyu51** [comment]
@nao-pon, this is GREAT! Thanks.
