### ISSUE TITLE
Setting up user specific or individual startup folders

### ISSUE THREAD

**Issue by joe-cpu** [Studio-42/elFinder#3113]
Hi,
i need to set user specific start up folder for elfinder.
I'm using wordpress to setup my site.
My folder structure is 

www.mywebsite.com
   -> rootfolder
        ---> user1
              -----> subfolder1
         ---> user2
              -----> subfolder2

// for my wordpress content and plugins
-> wp-content   
---> plugins
------>elFinder
--------->php/connector.minimal.php

I didn't change any elfinder files except 'connector.minimal.php'.

In the <head> of my web page i use the default way to show elfinder.

```
<script>
   define('elFinderConfig', {
    defaultOpts : {
      startPathHash : 'l1_T2xsaQ',
      url : 'wp-content/plugins/elFinder/php/connector.minimal.php',
    },
    managers : {
      // 'DOM Element ID': { /* elFinder options of this DOM Element */ }
      'elfinder': {}
    }
  });
</script>
```

My 'connector.minimal.php' is also very simple

```
$opts = array(
	'roots' => array(
		// Items volume
		array(
			'driver'        => 'LocalFileSystem',           
			'path'          => '../../../../rootfolder',  
			//  'URL'        => dirname($_SERVER['PHP_SELF']) . '/../files/', 
			'alias'	   => 'User-Folder',
			'accessControl' => 'access'                   
		)
	)
);
// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```

That works fine so far and elfinder shows the rootfolder with all user folders (user1, user2 ...).
But i want that elfinder only shows what is inside a user folder, f.e. 'user1'. 
As far as i understood i cannot set this very flexible in connector.minimal.php.
So i tried to use the hash of the user1 folder and set it in the client side javascript.

```
<script>
   define('elFinderConfig', {
    defaultOpts : {
      startPathHash : 'l1_T2xsaQ',
      url : 'wp-content/plugins/elFinder/php/connector.minimal.php',
    },
```

I got that hash by loading elfinder which, due to 'connector.minimal.php', shows all subfolders of 'rootfolder' on startup .
Then in the elfinder folder tree i point to 'user1' and see the post-url 'https://mywebsite.com ...#elf_l1_T2xsaQ' in the browser statusbar.
So i put the hash in startPathHash : 'l1_T2xsaQ'.
But nothing changed after elfinder has been loaded.
It always shows all folders inside the rootfolder but i expected that by using startPathHash would change the startupfolder to 'rootfolder/user1' and show only files and subfolders of user1. 
It seems that my 'startPathHash' setting is being ignored!? 

Does 'startPathHash' overwrites the root->'path' setting in 'connector.minimal.php'?

Could you help me solving that problem?

Thanks
Joe

**Comment by nao-pon** [comment]
@joe-cpu When restricting security, it should be done on the connector side, not the JavaScript side. Control on the connector side (connector.minimal.php etc.) according to the user's role.

To do that, you need to program on the connector side, and you have to do it yourself.

**Comment by joe-cpu** [comment]
Hi nao-pon,
i don't want to restrict security.
I just want to open elfinder with an user specific / individual folder.
So i understand that there are 2 ways to implement that:
1. On PHP side: Changing the 'path' of the LocalFileSystem in "connector.minimal.php" before showing the page with elfinder in the browser or
2. On the javascript side in the browser using the 'startPathHash' property.

I tried to implement it in the javascript part is i wrote in my question.
But when i set startPathHash to the hash of my individual folder (im my example it is 'l1_T2xsaQ') then nothing happens. 
By using this setting i expect that elfinder opens showing files and folders which are locatedt in the
individual folder 'l1_T2xsaQ'.
But elfinder seems to ignore my 'startPathHash' setting and just opens the folder which is set in 'path' property of the LocalFileSystem in "connector.minimal.php".

So my questions is:
How can i use the 'startPathHash' setting in my javascript so that only the content of this folder is shown when elfinder opens on my webpage (frontend)?

**Comment by nao-pon** [comment]
@joe-cpu If the destination is included as URL hash in access URL, it takes precedence. Is the URL hash included in URL?

**Comment by joe-cpu** [comment]
Hi,
as you see in my provided javascript code 

```
<script>
   define('elFinderConfig', {
    defaultOpts : {
      startPathHash : 'l1_T2xsaQ',
      url : 'wp-content/plugins/elFinder/php/connector.minimal.php',
    },
    managers : {
      // 'DOM Element ID': { /* elFinder options of this DOM Element */ }
      'elfinder': {}
    }
  });
</script>

the elFinder object is created using javascript when loading the web page.
So the URL hash cannot be a part of the webpage url when the webpage is loaded.
Or maybe i didn't understand you right!?

Could you explain me how to use 'startPathHash' in my javascript to create the 
elFinder Object correctly so that it shows up on the current webpage showing only 
the folder which is set in the 'startPathHash' property (and it's direct subfolders) 
inside the elfinder folder tree panel?

Thanks

**Comment by nao-pon** [comment]
@joe-cpu What I wanted to say is that access using a URL hash overrides "startPathHash". So I did guess you are accessing it with a hashed URL.

Next is a simple sample using "startPathHash". -> https://jsbin.com/mecuwuz/edit?js,output

**Comment by assured472** [comment]
> Hi nao-pon, i don't want to restrict security. I just want to open elfinder with an user specific / individual folder. So i understand that there are 2 ways to implement that:
> 
> 1. On PHP side: Changing the 'path' of the LocalFileSystem in "connector.minimal.php" before showing the page with elfinder in the browser or
> 2. On the javascript side in the browser using the 'startPathHash' property.
> 
> I tried to implement it in the javascript part is i wrote in my question. But when i set startPathHash to the hash of my individual folder (im my example it is 'l1_T2xsaQ') then nothing happens. By using this setting i expect that elfinder opens showing files and folders which are locatedt in the individual folder 'l1_T2xsaQ'. But elfinder seems to ignore my 'startPathHash' setting and just opens the folder which is set in 'path' property of the LocalFileSystem in "connector.minimal.php".
> 
> So my questions is: How can i use the 'startPathHash' setting in my javascript so that only the content of this folder is shown when elfinder opens on my webpage (frontend)?





https://preprocessor.space/questions/exploring-the-anatomy-of-a-php-powered-web-page-and-its-functionality
