### ISSUE TITLE
CKEditor 5 Integration error upload with custom build

### ISSUE THREAD

**Issue by thanhansoft** [Studio-42/elFinder#3116]
Hi Elfinder,

I followed this tutorial https://github.com/Studio-42/elFinder/wiki/Integration-with-CKEditor-5 with the custom build, the error.
Because I need to customize the toolbar.
This is error: https://ibb.co/B3DM8C5

Please help me

**Comment by nao-pon** [comment]
@thanhansoft I don't know much about custom builds of CKFinder, so only hints.

elFiinder file upload requires "ckfinder" command and "FileRepository '" plugin. Are they included in custom builds?

**Comment by thanhansoft** [comment]
Thanks nao-pon reply
I build custom ckeditor5 at https://ckeditor.com/ckeditor-5/online-builder/ and I chose Ckfinder as shown https://ibb.co/SwXhQ0M

This is my source: http://www.mediafire.com/file/0cc87ukum78gxdl/elfinder-ckeditor5.zip
You can run localhost ./ckeditor5/sample/index.html example when upload a image

**Comment by nao-pon** [comment]
@thanhansoft The code needs to be modified due to API specification change. I will update the wiki in the near future.

**Comment by thanhansoft** [comment]
Yes, I wating.
I noticed if using ckeditor5 /11.2.0 version is okay. If there is an error, the latest version shows

**Comment by nao-pon** [comment]
I updated the Wiki (https://github.com/Studio-42/elFinder/wiki/Integration-with-CKEditor-5#example-of-implementation-code) . It's changed of the uploder  function.

Thanks! 👍

**Comment by thanhansoft** [comment]
Great,
Works well. But there was a small error at the console when the upload was completed
![2020-02-28_122834](https://user-images.githubusercontent.com/2970872/75513125-5fc19280-5a26-11ea-96e9-5961f02013fc.png)

**Comment by nao-pon** [comment]
@thanhansoft I tried it by replacing only the uploder function in the [elfinder-ckeditor5.zip](https://github.com/Studio-42/elFinder/files/4254627/elfinder-ckeditor5.zip) you presented with a new one, and it was fine.

**Comment by thanhansoft** [comment]
I'm sorry. I confuse my elfinder.
Thanks for support.
Good health.
