### ISSUE TITLE
Latest version not available in CDNJS

### ISSUE THREAD

**Issue by LeonSebastianCoimbra** [Studio-42/elFinder#3117]
This is curious: if you try to access to the elfinder page on cdnjs (https://cdnjs.com/libraries/elfinder/) you see that the latest usable version is the 2.1.50, but you also see that in the dropdown list of the versions you can select the 2.1.53....

This is an anomaly, since by default CDNJS should present always the latest version available...

What to do then if you want to use the latest version? Well, for the ones like me that use libman (microsoft/.net solution to download client side libraries) it is possible to create a configuration script (called libman.json) like the following one:

`

{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "provider": "cdnjs",
      "library": "elfinder@2.1.53",
      "destination": "wwwroot/lib/elfinder2/"
    }
 ]
}
`

And then run "libman.exe restore" (from the same directory where the script is) to download the package.

The process start but then end claiming:

`

Microsoft.Web.LibraryManager.Contracts.ResourceDownloadException: Non è stato possibile scaricare la risorsa da "https://cdnjs.cloudflare.com/ajax/libs/elfinder/2.1.53/sounds /rm.wav" ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
`

It seems to be an authorization problem on some files of the package. Version 2.1.51 and 2.1.52 suffers of the same problem.

Maybe this is the same reason why CDNJS show version 2.1.50 as the latest one downloadable (and in effect it works!!).

**Comment by nao-pon** [comment]
@LeonSebastianCoimbra cdn.js does not host media files, so "rm.wav" cannot be found. That is known.

However, I don't know why 2.1.50 is the default even though 2.1.53 is up to date. If you have any problems with elFinder, please let me know.

**Comment by LeonSebastianCoimbra** [comment]
Nono, elFinder is  fine.

What i was trying to achieve is to automate the acquisition of the library (using a central repository) just like i did for other libraries, aka by getting it from CDNJS.

I expected to be able to download the latest version from there, but CDNJS acts weird... like i wrote before.

I can obviously insert it manually into my project (as I am doing now), but if I had been able to standardize this dependence like the others I would have been happier.

Seeing the strange behavior of CDNJS I thought to report it.

**Comment by nao-pon** [comment]
@LeonSebastianCoimbra OK, please report it to Issues on cdn.js. And please let me know if you understand something.

**Comment by LeonSebastianCoimbra** [comment]
Wasn't it you or someone from your staff who uploaded to CDNJS? I opened this issue on the basis of this assumption, but maybe I was wrong ... If so, I'm sorry. I will open a request on CDNJS and as soon as I have something I will let you know. Thank you for your time.

**Comment by nao-pon** [comment]
Well, it seems that cdn.js detects the new release of elFinder and automatically creates a package.

**Comment by nao-pon** [comment]
Take a look at https://github.com/cdnjs/cdnjs/issues/13709.

**Comment by LeonSebastianCoimbra** [comment]
Saw it, i close this issue since it is not related to ElFinder and it is linked with the corresponding one in CDNJS.

Thanks for your time.
