### ISSUE TITLE
Right click menu - Open option missing when using connector

### ISSUE THREAD

**Issue by Snowmanko** [Studio-42/elFinder#3121]
Hi,

we are missing open option in rightclick menu when trying to rightclick on files. We are using connector to transfer files to users. Files are not publically accessible from URL.

`'roots' => [
        [
            'driver'        => 'LocalFileSystem',
            'path'          => storage_path('uploads/files'),
            'alias'         => 'Files folder',
            'attributes'    => [[ //this is used to hide system files like .quarantine and .tmb
                'pattern' => '~/\.~',
                'read' => false,
                'write' => false,
                'hidden' => true,
                'locked' => true
            ]]
        ]
    ],
`
URL link to files looks like this:

`https://example.com/app/filemanager/elfinder_connector?item_id=%2Fstorage%2Fapp%2Fexample.com%2Fresources%2Fdata%2Ffiles&module=file-repository&uploadEnabled=1&_token=w5fxOHLGHhthqJtkgOa8Uzlc5bwxL19BgUsdyQdc&cmd=file&target=l1_dGVzdC50eHQ`

We are disabling these actions in config: 
'rename', 'rm', 'delete', 'copy', 'duplicate', 'mkfile', 'upload', 'mkdir', 'edit', 'textarea'

@nao-pon can you please give us suggestion where to look for problem?

**Comment by nao-pon** [comment]
@Snowmanko Please check client option [`contextmenu.files`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#contextmenu). Of course, the item must have read permission.

**Comment by Snowmanko** [comment]
Hi, thanks for advice, this is already configured. Our problem is that when we apply https://github.com/Studio-42/elFinder/wiki/Disable-real-file-path-from-being-shown open option is not there. When we remove "URL option" from config (as I menioned we need to use connector because our files are not accessible from public URL) open option is not shown with same configuration as when "URL option" is there.

**Comment by nao-pon** [comment]
I can't reproduce this problem so I can't debug it. Can you reproduce this problem using a [plain package](https://github.com/Studio-42/elFinder/archive/2.1.zip)?
