### ISSUE TITLE
Usage with webpack

### ISSUE THREAD

**Issue by flohw** [Studio-42/elFinder#3123]
Hello,

I was using elfinder with CKEditor 4 in an AngularJS application. Everything worked well and was easy to configure. I was using a popup (its url was on a symfony application with elfinder bundle).

I am migrating my AngularJS application to Angular (version 9 at the moment) and CKEditor 5 and I am using webpack (wich was part of the process on my previous app)

I am able to display and make elFinder popin works by adding jquery, jqueryui and elfinder via cdn into my template via script tags (HtmlWebpackPlugin) but I can't figure out how to import jquery, jqueryui and elfinder and make them work together. I get the `dialogelfinder is not a function` error. My code to display the popin `import * as $ from 'jquery';` and later in my Angular component: `$('<div/>').dialogelfinder({...})` which come from your wiki.

Any help would be appreciate.

As a side question : did you have any plan to provide an elFinder npm package ?

**Comment by nao-pon** [comment]
@flohw According to the error message, the elFinder script does not seem to be loaded. Check that it is loaded correctly. Also, I don't really understand npm packages.

**Comment by flohw** [comment]
Hello @nao-pon sorry for the delay, I switched project and as this is not a top required feature, I left that apart for now.

This is what I understood, I think I have to found a workaround about that. Hopefully someone will help you about npm package as I don't know how to do either.

I will post a solution here if I found one.

Thank you for your answer.

**Comment by KevinSleegers** [comment]
@flohw Have you been able to make it work with Webpack? Currently facing similar issues when importing jQuery, jQuery UI and Elfinder via imports with Webpack.

**Comment by flohw** [comment]
Hi @KevinSleegers,

No, I didn't found any solution. Sorry.
