### ISSUE TITLE
Can't connect to ftp and netmounts don't show

### ISSUE THREAD

**Issue by devilkto** [Studio-42/elFinder#3124]
I can't connect with the network mounts, only using the connection info on the connector.minimal.
When I try to log in to my ftp with the netmount it only gives me a error saying Unable to open "ftp-server". Folder not found.
How can I log in to the ftp with the netmout like in the demos?

Best Regards
![elfinder error](https://user-images.githubusercontent.com/62031173/76449665-3fd98980-63ab-11ea-9755-51ee64df87ff.png)

**Comment by nao-pon** [comment]
@devilkto If the FTP connection information you entered is correct, the server environment may not be able to use PHP's FTP function. Ask your server administrator.
