### ISSUE TITLE
dialogelfinder close

### ISSUE THREAD

**Issue by pehser** [Studio-42/elFinder#3129]
Подскажите как сделать чтоб окно dialogelfinder закрывалось по Esc?
Tell me how to make the dialogelfinder window close by Esc?
```
$('<div id="editor" />').dialogelfinder({
            url: 'core/elfinder/php/connector.php',
            width: '80%',
            height: '600px',
            getFileCallback: function (file) {
                $('#editor').remove();
            }
        })
```

**Comment by nao-pon** [comment]
@pehser The ESC key is assigned to close dialogs and cancel drag operations on the elFinder, so the elFinder itself cannot be closed using the ESC key.
