### ISSUE TITLE
PHP 7.4.3 error: Unrecognized key 'lifetime' found in the options array

### ISSUE THREAD

**Issue by RobiNN1** [Studio-42/elFinder#3130]
elFinder: 2.1.54
PHP 7.4.3

File: elFinder\php\elFinderSession.php
Error message: setcookie(): Unrecognized key 'lifetime' found in the options array

**Comment by nao-pon** [comment]
@RobiNN1 I fixed @ 8c231e5cf92987e9e90d4caf04c2c7932fe8b350 but it reverted next commit 30998556dc08ca7424518999f421982cc745e462 ... I don't know why... maybe I made a mistake. So I patched again.

Thanks! 👍
