### ISSUE TITLE
how can i change timezone of elfinder ?

### ISSUE THREAD

**Issue by russh3l** [Studio-42/elFinder#3133]
my php.ini date.timezone settings are true but when i edit or upload some files elfinder showing three hours ago

**Comment by nao-pon** [comment]
@russh3l There is no time zone setting in the elFinder client. The time zone depends on the device's time zone, such as the personal computer you are viewing. Is your device's time zone set correctly?

**Comment by russh3l** [comment]
> @russh3l There is no time zone setting in the elFinder client. The time zone depends on the device's time zone, such as the personal computer you are viewing. Is your device's time zone set correctly?

i found the problem i think elfinder is running with Universal Time 
now my server local time and universal time are different

**Comment by nao-pon** [comment]
@russh3l The time handled by elFinder is Unixtime (epoch time). Not affected by time zone. If the time is not correct, the server's Unixtime is not set correctly.
