### ISSUE TITLE
NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': error in GetInfo

### ISSUE THREAD

**Issue by gadangmadhulika** [Studio-42/elFinder#3135]
Hi @nao-pon 
Iam getting below error on server when i open GetInfo on a file.Please check the screencast below.
https://www.screencast.com/t/RfMVU05387xI
Following  is the Error
md5 : | NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://hosturl/dashboard/js/worker/calcfilehash.js' failed to load.
-- | --
sha256 : | NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://hosturl/dashboard/js/worker/calcfilehash.js' failed to load.

**Comment by nao-pon** [comment]
@gadangmadhulika Is the reported URL 'http: //hosturl/dashboard/js/worker/calcfilehash.js' the correct URL? elFinder automatically detects the baseUrl, but the result may not be correct. In that case, you can specify the correct baseUrl in the client option specification.

for example...
```javascript
var options = {
    // become 'http://hosturl/dashboard/elfinder/js/worker/calcfilehash.js'
    baseUrl : 'http://hosturl/dashboard/elfinder/',
    url  : 'php/connector.php',
    lang : 'en'
}
$('#elfinder').elfinder(options);
```

If that doesn't work, observe the error in your browser's developer console and let us know.

**Comment by gadangmadhulika** [comment]
Hi @nao-pon 
I ran this below command then network error occurred.
$ php artisan elfinder:publish

**Comment by nao-pon** [comment]
@gadangmadhulika What are the errors in the browser Developer Tools console?

**Comment by gadangmadhulika** [comment]
Hi @nao-pon 
I can't see any console errors.
baseUrl : 'http://localhost:8000/dashboard/elfinder/',

**Comment by nao-pon** [comment]
@gadangmadhulika Is the response normally obtained by accessing “http://localhost:8000/dashboard/elfinder/js/worker/calcfilehash.js” with a browser?

**Comment by gadangmadhulika** [comment]
I tried without using php artisan elfinder:publish command then i don't get that issue.

**Comment by applibs** [comment]
I used downloaded elFinder and I see this error too.
