### ISSUE TITLE
How to display file overwrite prompt when copy or paste file in the same-level directory in which already exists a same name file.

### ISSUE THREAD

**Issue by hanalice** [Studio-42/elFinder#3139]
I am trying to get the file overwrite prompt to display when user copy or cut a file into a directory without entering into it, and a duplicate file already exists in that directory.

Both scenarios assume that the same file exists in the directory already:

- When I copy/cut and paste a file into the directory(in this case, I enter into the directory), it displays a file overwrite prompt.
- When I copy/cut and paste into the directory(in this case, I don't enter into the directory, I just select the directory), it does not display a file overwrite prompt; but automatically overwrites the file that already exists in the directory.

I realize that the cached files(which is stored in fm.files()) might have relation with this, but I don't konw the cache policy.
Has anyone gotten around to successfully displaying this prompt? Any help or advice would be greatly appreciate

**Comment by nao-pon** [comment]
@hanalice There seems to be no problem in our demo site.
![paste-test](https://user-images.githubusercontent.com/1412630/78007061-b9e0ab00-7378-11ea-9226-b59b56121db7.gif)

**Comment by hanalice** [comment]
> @hanalice There seems to be no problem in our demo site.
> ![paste-test](https://user-images.githubusercontent.com/1412630/78007061-b9e0ab00-7378-11ea-9226-b59b56121db7.gif)
My elfinder is a bit out-of-date. May you give me the direction of thinking about the fm cache?

**Comment by nao-pon** [comment]
@hanalice fm.files cache is limited to items in the current working directory and other directories (not including files) and items being copied.

**Comment by hanalice** [comment]
> @hanalice fm.files cache is limited to items in the current working directory and other directories (not including files) and items being copied.

thanks for the quick response. I still have a question,see as the screenshot:
![image](https://user-images.githubusercontent.com/18046501/78109453-cc67ec80-742b-11ea-9061-3c5594e9674f.png)
in the picture, always call a function valid(data.list) but my data structure is like { "cwd":  {...}, "files": [...], "options": {...}}, data doesn't have a property called list. Has the data structure changed in the current version?

**Comment by nao-pon** [comment]
@hanalice It already exists as of 2.0-beta (on 10 Jul 2011).

https://github.com/Studio-42/elFinder/blob/dd28d7914ce2d59e355ab2abbd17ad9d1dab4cbe/php/elFinder.class.php#L464-L482

**Comment by hanalice** [comment]
> @hanalice It already exists as of 2.0-beta (on 10 Jul 2011).
> 
> https://github.com/Studio-42/elFinder/blob/dd28d7914ce2d59e355ab2abbd17ad9d1dab4cbe/php/elFinder.class.php#L464-L482

Thanks very much for your patience, and I know how to fix the problem in my version.

**Comment by hanalice** [comment]
@nao-pon Thanks very much for your patience, and I already know how to fix my problem in my version.
