### ISSUE TITLE
how to change "mount network volume" caption

### ISSUE THREAD

**Issue by ashickur-rahman** [Studio-42/elFinder#3141]
I have connected dropbox with elfinder using Dropbox2 driver. The problem I am facing the volume is caption like "Root@dropbox" . I want to give it a actual cation like - "office dropbox " . How to do this?

**Comment by nao-pon** [comment]
@ashickur-rahman If you have mounted Dropbox as a permanent volume in the connector settings, you can use the [`alias`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#alias) option.

**Comment by ashickur-rahman** [comment]
Thanks. solved.
