### ISSUE TITLE
File Upload in MYSQL connector fails - SOLUTION FOUND

### ISSUE THREAD

**Issue by Duolabs** [Studio-42/elFinder#3142]
Hi all,
Thank you for sharing this great piece of magic.

I want to let you know that using version 2.1.55 if you use connector.minimal.php with MYSQL and you try to upload a file from your harddrive it fails. The file starts to upload but it is not INSERT in the MySQL database.

**The workaround I found is to copy&paste the 

> function debug()

 from connector.maximal.php and then it all works as it should.**

No problems with LocalFileSystem connector.

It would be nice if you take a look at it.

Hope this will help the community.

**Comment by nao-pon** [comment]
@Duolabs Thanks for letting me know! 👍  I fixed this. I am considering releasing v2.1.56 as soon as possible.
