### ISSUE TITLE
how can i change edit file default window size ? 

### ISSUE THREAD

**Issue by russh3l** [Studio-42/elFinder#3143]
how can i change edit file default window size ?

**Comment by nao-pon** [comment]
@russh3l Please check client option [`commandsOptions.edit.dialogWidth`](https://github.com/Studio-42/elFinder/blob/37519c120f6befe3e82232f1a199374c3f9154b2/js/elFinder.options.js#L411-L414).
https://github.com/Studio-42/elFinder/blob/37519c120f6befe3e82232f1a199374c3f9154b2/js/elFinder.options.js#L411-L414
