### ISSUE TITLE
Download PDF file only not in browser window preview

### ISSUE THREAD

**Issue by Ange7** [Studio-42/elFinder#3146]
Hello

Is it possible to download PDF file only when i double click ? Actually the file is preview in browser window. 

But i would like for PDF file open in Adobe Reader (for example) 

i try with dispInlineRegex but didn't work

Thank you

**Comment by nao-pon** [comment]
@Ange7 If you set the'dispInlineRegex' setting to not match `application/pdf`, PDF files will be downloaded by most popular browsers.

for example...
`'dispInlineRegex' => '^(?:(?:video|audio)|image/(?!.+\+xml)|application/(?:ogg|x-mpegURL|dash\+xml)|text/plain$)',`

**Comment by Ange7** [comment]
so just `'dispInlineRegex' => '^(?:application/pdf$)', ?

**Comment by nao-pon** [comment]
@Ange7 No, please  exclude "application/pdf". If you do not allow any inline display (display in browser), specify `(?!)`.
