### ISSUE TITLE
Style looks broken when using jQuery 3.5.0

### ISSUE THREAD

**Issue by ctrlaltca** [Studio-42/elFinder#3148]
Hi, I recently composer-upgraded my php application and jQuery was upgraded from 3.4.x to 3.5.0. Now elFinder looks partially broken, like if the row height and columns width calculation are not performed correctly:

![Schermata 2020-04-15 alle 20 51 36](https://user-images.githubusercontent.com/1631111/79376770-f0aee780-7f5a-11ea-98c4-9341aea2a999.png)

I can easily reproduce this problem by chaging the jquery version from 3.4.1 to 3.5.0 in elfinder.legacy.html.

**Comment by nao-pon** [comment]
@ctrlaltca I'll fix this. Thanks! 👍 

ref. https://jquery.com/upgrade-guide/3.5/

**Comment by nao-pon** [comment]
I done. Please try to check with the [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by ctrlaltca** [comment]
I can confirm it's working fine on the nightly build, thank you!

**Comment by SamMousa** [comment]
For me it doesn't work with dev-master & jquery 3.5

**Comment by 667bdrm** [comment]
I confirm that latest 2.1 branch has no ui issues on Drupal 9 which begin using jQuery 3.5.1 in core.
