### ISSUE TITLE
unable extract dot files FTP driver

### ISSUE THREAD

**Issue by arielesp** [Studio-42/elFinder#3152]
![error_extract_zip](https://user-images.githubusercontent.com/10634047/79926105-6d860980-8412-11ea-9fd6-30a87d43bc00.png)

files starting with dot ... error extracting from zip

how to solve?

thanks

**Comment by nao-pon** [comment]
@arielesp Are you limiting files that start with a dot? For example, the connector.minimal.php "access" function is restricted to files that start with a dot.

**Comment by arielesp** [comment]
> @arielesp Are you limiting files that start with a dot? For example, the connector.minimal.php "access" function is restricted to files that start with a dot.

nops
I already tried edit this function... and disable it... some tip ?

**Comment by nao-pon** [comment]
@arielesp In the our demo site, if you mount the FTP server by network mount, this dot file is not limited. Ie the FTP network mount volume on the our demo site should be fine. If there is a problem on the our demo site, It is due to the FTP server side.

**Comment by arielesp** [comment]
HI
really in demo site dot files are editable
could you send me correct function 'access' to try here, please ?
thanks

**Comment by nao-pon** [comment]
@arielesp It doesn't specify the 'accessControl' option.
