### ISSUE TITLE
Unable to use a Dropbox volume as the only one in connector's roots option

### ISSUE THREAD

**Issue by cristiangervasi** [Studio-42/elFinder#3154]
Hi, i'm using the latest version of ElFinder (2.1.56). 

I'm trying to set a Dropbox volume as the only one when the page boots up.

When I try to set a single Dropbox volume in connector `roots` option, ElFinder doesn't start correctly and gives me this error:
`Uncaught Error: Call to a member function listFolder() on null in D:\laragon\www\elfinder\php\elFinderVolumeDropbox2.class.php:628`.

Meanwhile, when I set exactly the same Dropbox volume after a LocalFileSystem volume like the one included in the `connector.maximal.php-dist` example, the page boots up correctly and ElFinder work as expected with both volumes.

I checked the source code of that file and it seems that the `$this->service` variable is null when the `cacheDir()` function is called, but I can't figure out how to avoid this.

How can I fix this? Thank you for your awesome work on ElFinder!

**Comment by nao-pon** [comment]
@cristiangervasi This is affected by a bug in the elFinder PHP connector. I will fix this.

Thanks! 👍
