### ISSUE TITLE
Elfinder connector return URI for OneDrive gives 404 page not found

### ISSUE THREAD

**Issue by froid24** [Studio-42/elFinder#3156]
I am using elfinder in a Laravel 5.7 project with barryvdh integration wrapper. I have configured the OneDrive network mount and the onedrive app with the following return uri:

https://myapp.com/elfinder/connector/netmount/onedrive/1

But when trying to authorise, the return URI called by OneDrive gives a 404 page not found:

https://myapp.com/elfinder/connector/netmount/onedrive/1?code=zzzzzzz-zzzzz-zzzz-zzzz-zzzzzzzzz

Anything other than the following gives a 404 page not found:
https://myapp.com/elfinder/connector

This is also the one in the route list of the laravel.

So do I need to do something more? Register the above complete route ( with /netmount/onedrive/1)? It would be expected for the package to do that...

Thanks in advance for the help.

Cheers!

**Comment by RAMKUMARIITR** [comment]
check redirect_uri variable in elFinderVolumeOneDrive.class.php 

if redirect_uri should me your connector_path/netmount/onedrive/1

add this also in your connector in the top.

> `define('ELFINDER_CONNECTOR_URL', 'http://localhost/2020/elfinder-2.1/php/connector.minimal.php'); `

**Comment by RAMKUMARIITR** [comment]
FROM :: https://myapp.com/elfinder/connector/netmount/onedrive/1
TO :: https://myapp.com/elfinder/connector.php/netmount/onedrive/1

you missed file extension

**Comment by nao-pon** [comment]
@froid24 We need to use PATH_INFO as OneDrive cannot include GET parameters in the redirect destination.

@RAMKUMARIITR Thanks! :+1:
