### ISSUE TITLE
file name with tips-social-distancing-quarantine-isolation-031620.pdf not showing..

### ISSUE THREAD

**Issue by apuhalder007** [Studio-42/elFinder#3157]
This filename tips-social-distancing-quarantine-isolation-031620.pdf not showing in the list view. please help me out.
[tips-social-distancing-quarantine-isolation-031620.pdf](https://github.com/Studio-42/elFinder/files/4597449/tips-social-distancing-quarantine-isolation-031620.pdf)

**Comment by nao-pon** [comment]
@apuhalder007 The file will display fine on the demo site. I think it depends on the environment of your server.
Please provide information such as elFinder version, connector type and configuration values.
