### ISSUE TITLE
Resize: reduce quality without changing dimensions

### ISSUE THREAD

**Issue by jkurzend** [Studio-42/elFinder#3158]
Would be great if we could use the resize tool to change the quality of a jpg without changing dimensions (currently, an error message is shown ("image size not changed").

![image](https://user-images.githubusercontent.com/38737655/81384207-9b0ccb80-9111-11ea-94de-0a67fb53e74b.png)

**Comment by nao-pon** [comment]
@jkurzend That's true. I will consider if this can be improved. Thanks! :+1:
