### ISSUE TITLE
No Confirm request dialog on file delete

### ISSUE THREAD

**Issue by ghigio2000** [Studio-42/elFinder#3160]
Hi,

I am not getting any Confirm Request dialog when I delete a file.
I tried on your demo site (https://studio-42.github.io/elFinder/#elf_l2_Lw) and it happen the same.
I felt it was a configuration in my browser, but I do not block pop-ups.
Any idea?

thanks for your help
Giorgio

**Comment by nao-pon** [comment]
@ghigio2000 Please check client options `commandsOptions.rm.quickTrash`.

https://github.com/Studio-42/elFinder/blob/cb3203c9fea8dc434da2ab50484d7a73ad4be2ff/js/elFinder.options.js#L681-L682
