### ISSUE TITLE
On archive single file returns "undefined" with file zip name

### ISSUE THREAD

**Issue by munish48** [Studio-42/elFinder#3161]
Hello Dev Team,

Please fix this issue "On archive single file returns "undefined" with file zip name", screenshot is given below. Also is there any restriction to Archive file name "config" ? Please reply ASAP :)

![image](https://user-images.githubusercontent.com/24403435/81931776-41703980-9608-11ea-9b4c-19021c92617b.png)

Thanks & Regards
Munish Thakur

**Comment by nao-pon** [comment]
@munish48 This issue occurs immediately after adding / deleting files in the volume root folder. This is a connector side bug, so I will fix it.

Thanks! 👍
