### ISSUE TITLE
when entering a folder, the name of the previous folder is displayed

### ISSUE THREAD

**Issue by kainpro** [Studio-42/elFinder#3162]
Hello good afternoon, is there any way to change this number when entering a folder for a text that says return? Even if I create a folder inside the elfinder, it generates it with a numbering, but the name I have placed is visible.
![image](https://user-images.githubusercontent.com/65268233/82095522-c6b92400-96c4-11ea-89f3-f0de29a41c3d.png)

**Comment by nao-pon** [comment]
@kainpro I'm sorry, but I can't understand what's happening. Will it be reproduced on our demo site?
