### ISSUE TITLE
Unable to mount onedrive [no error popups] 

### ISSUE THREAD

**Issue by RAMKUMARIITR** [Studio-42/elFinder#3164]
I want very urgent help from you people regarding onedrive mount in elfinder.
   I generated clientid and clientsecret for my onedrive by creating application in "Azure active directory"

   I did some modifications in connector.php, connector.minimal.php. 
   There are no errors popping up but onedrive volume is not mounting.

   If Possible please share connector.php and ondriveconnector.php scripts. 

my connector.php
`<?php
// Enable FTP connector netmount
$useFtpNetMount = true;

// Set root path/url
define('ELFINDER_ROOT_PATH', dirname(__FILE__));
define('ELFINDER_ROOT_URL' , dirname($_SERVER['SCRIPT_NAME']));
$opts = array(
	'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => ELFINDER_ROOT_PATH . '/files/', // path to files (REQUIRED)
			'URL'           => ELFINDER_ROOT_URL  . '/files/', // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		),
		// Trash volume
		array(
			'id'            => '1',
			'driver'        => 'Trash',
			'path'          => ELFINDER_ROOT_PATH . '/files/.trash/',
			'tmbURL'        => ELFINDER_ROOT_URL . '/files/.trash/.tmb/',
			'uploadDeny'    => array('all'),                // Recomend the same settings as the original volume that uses the trash
			'uploadAllow'   => array('image', 'text/plain'),// Same as above
			'uploadOrder'   => array('deny', 'allow'),      // Same as above
			'accessControl' => 'access',                    // Same as above
		)
	),
    'optionsNetVolumes' => array(
        '*' => array( // "*" is all of netmount volumes
            'tmbURL'    => dirname($_SERVER['PHP_SELF']) . '/../files/.tmbNetmount/',
            'tmbPath'   => '../files/.tmbNetmount',
            'tmbGcMaxlifeHour' => 1,  // 1 hour
            'tmbGcPercentage'  => 10, // 10 execute / 100 tmb querys
            'plugin' => array(
                'AutoResize' => array(
                    'enable' => false
                ),
                'Watermark' => array(
                    'enable' => false
                ),
                'Normalizer' => array(
                    'enable' => false
                ),
                'Sanitizer' => array(
                    'enable' => false
                )
            ),
        )
    )
);

// Thumbnail settings for cloud volumes
$tmbConfig = array(
    'tmbPath'          => '../files/.tmbCloud',
    'tmbURL'           => dirname($_SERVER['PHP_SELF']) . '/../files/.tmbCloud/',
    'tmbGcMaxlifeHour' => 2160, // 90 days
    'tmbGcPercentage'  => 5,    // 5 execute / 100 tmb querys
); 
// FTP volume
$opts['roots'][] = array_merge($tmbConfig, array(
    'phash'  => 'g1_Lw', // set parent to Volume group (g1_) root "/" (Lw)
    'driver' => 'FTP',
    'host'   => '18.176.240.163',
    'user'   => 'anonomus',
    'path'   => 'solar',
    'owner'  => false,
));

//////////////////////////////////////////////////////////////////////
// load composer autoload.php
require './vendor/autoload.php';

// Enable FTP connector netmount
if ($useFtpNetMount) {
	elFinder::$netDrivers['ftp'] = 'FTP';
}
// // Enable network mount
 elFinder::$netDrivers['onedrive'] = 'OneDrive';
 define('ELFINDER_ONEDRIVE_CLIENTID',     'added from OneDrive azure active directory application api');
 define('ELFINDER_ONEDRIVE_CLIENTSECRET', 'added from OneDrive azure active directory application api');
// ===============================================

 * @param  string  $attr  attribute name (read|write|locked|hidden)
 * @param  string  $path  file path relative to volume root directory started with directory separator
 * @return bool|null
 **/
function access($attr, $path, $data, $volume, $isDir, $relpath) {
	return basename($path)[0] === '.'            // if file/folder begins with '.' (dot) with out volume root
			 && strlen($relpath) !== 1
		? !($attr == 'read' || $attr == 'write') // set read+write to false, other (locked+hidden) set to true
		:  null;                                 // else elFinder decide it itself
}

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
// end connector`

**Comment by RAMKUMARIITR** [comment]
arrays in connector.php file


`$opts = array(
	'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => ELFINDER_ROOT_PATH . '/files/', // path to files (REQUIRED)
			'URL'           => ELFINDER_ROOT_URL  . '/files/', // URL to files (REQUIRED)
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image', 'text/plain'),// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		),
		// Trash volume
		array(
			'id'            => '1',
			'driver'        => 'Trash',
			'path'          => ELFINDER_ROOT_PATH . '/files/.trash/',
			'tmbURL'        => ELFINDER_ROOT_URL . '/files/.trash/.tmb/',
			'uploadDeny'    => array('all'),                // Recomend the same settings as the original volume that uses the trash
			'uploadAllow'   => array('image', 'text/plain'),// Same as above
			'uploadOrder'   => array('deny', 'allow'),      // Same as above
			'accessControl' => 'access',                    // Same as above
		)
	),
    'optionsNetVolumes' => array(
        '*' => array( // "*" is all of netmount volumes
            'tmbURL'    => dirname($_SERVER['PHP_SELF']) . '/../files/.tmbNetmount/',
            'tmbPath'   => '../files/.tmbNetmount',
            'tmbGcMaxlifeHour' => 1,  // 1 hour
            'tmbGcPercentage'  => 10, // 10 execute / 100 tmb querys
            'plugin' => array(
                'AutoResize' => array(
                    'enable' => false
                ),
                'Watermark' => array(
                    'enable' => false
                ),
                'Normalizer' => array(
                    'enable' => false
                ),
                'Sanitizer' => array(
                    'enable' => false
                )
            ),
        )
    )
);


// Thumbnail settings for cloud volumes
$tmbConfig = array(
    'tmbPath'          => '../files/.tmbCloud',
    'tmbURL'           => dirname($_SERVER['PHP_SELF']) . '/../files/.tmbCloud/',
    'tmbGcMaxlifeHour' => 2160, // 90 days
    'tmbGcPercentage'  => 5,    // 5 execute / 100 tmb querys
); 
// FTP volume
$opts['roots'][] = array_merge($tmbConfig, array(
    'phash'  => 'g1_Lw', // set parent to Volume group (g1_) root "/" (Lw)
    'driver' => 'FTP',
    'host'   => '18.176.240.163',
    'user'   => 'anonomus',
    'path'   => 'solar',
    'owner'  => false,
));
// OneDrive volume
// Require constant "ELFINDER_ONEDRIVE_CLIENTID" and "ELFINDER_ONEDRIVE_CLIENTSECRET"
$opts['roots'][] = array_merge($tmbConfig, array(
    'phash'       => 'g1_Lw', // set parent to Volume group (g1_) root "/" (Lw)
    'driver'      => 'OneDrive',
    'path'        => '/', // or folder id as root
    'accessToken' => '',  // @JSON String access token including refresh token
));
`

**Comment by nao-pon** [comment]
@RAMKUMARIITR Access tokens are required for permanent mounts.

If properly configured, OneDrive should be network mountable. You can get an access token by performing a network mount with the account you want to mount.

See the following thread.
 - #2121

**Comment by RAMKUMARIITR** [comment]
> @RAMKUMARIITR Access tokens are required for permanent mounts.
> 
> If properly configured, OneDrive should be network mountable. You can get an access token by performing a network mount with the account you want to mount.
> 
> See the following thread.
> 
> * #2121



> @RAMKUMARIITR Access tokens are required for permanent mounts.
> 
> If properly configured, OneDrive should be network mountable. You can get an access token by performing a network mount with the account you want to mount.
> 
> See the following thread.
> 
> * #2121

YEh! I mounted one drive permanently. but for initial an access token and refresh token, I made little additional PHP which are getting me access token and store it in JSON format.
