### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by Dndi312** [Studio-42/elFinder#3165]
![h2](https://user-images.githubusercontent.com/59817678/82524926-f5fee380-9b51-11ea-993a-86d3bcb0a511.png)
![n1](https://user-images.githubusercontent.com/59817678/82524725-77a24180-9b51-11ea-9f66-1fe291ae1df5.png)
Hello, I have such a question? where you can remove the download button, here and in the context menu ... It is in the code where you can remove?

**Comment by sergiz** [comment]
https://github.com/Studio-42/elFinder/blob/master/js/elFinder.options.js

Here you can search for "download" and see. You can also disable the command alltogether with "commands" property, if you don't need it at all.

**Comment by Dndi312** [comment]
ok thanks then I'll look
