### ISSUE TITLE
Problem with "space" folder 

### ISSUE THREAD

**Issue by unigia** [Studio-42/elFinder#3166]
When on FTP we have a folder with name equal to a space " " elFinder generates a loop and we have generating the following error when we try to access: 
Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/elFinder/php/elFinderVolumeFTP.class.php on line 1341

Can you try, for example, to create a "space" folder on Linux Filesystem with: 
`
mkdir ' '
`
and try if we have the same error.

**Comment by nao-pon** [comment]
@unigia I verified this. It didn't become an infinite loop. However, I found a bug that prevented the folder from being displayed. I will fix this.

Thanks! 👍

**Comment by unigia** [comment]
We have the same error with file that start with space " filename.pdf".
