### ISSUE TITLE
Cannot skip checking for image convertion library

### ISSUE THREAD

**Issue by sergiz** [Studio-42/elFinder#3167]
https://github.com/Studio-42/elFinder/blob/cb3203c9fea8dc434da2ab50484d7a73ad4be2ff/php/elFinderVolumeDriver.class.php#L870-L882

There's no way to skip this check, if you do not have imagick or gd loaded. Could there be another condition added? I guess I'm not the only one that do not have any images to deal with.

**Comment by nao-pon** [comment]
@sergiz OK, I would add an option "none" which does not use the image library.

Thanks! 👍
