### ISSUE TITLE
How to disable image loading on open?

### ISSUE THREAD

**Issue by sergiz** [Studio-42/elFinder#3168]
Hello.

I have thumbnails disabled ("tmbPath" => false in connector), but when I open a directory, the frontend will still go and load all images (download full size using the cmd=file command. How can I disable that?

**Comment by nao-pon** [comment]
@sergiz Please try connector volume root option `'tmbFbSelf' => false`.

https://github.com/Studio-42/elFinder/blob/cb3203c9fea8dc434da2ab50484d7a73ad4be2ff/php/elFinderVolumeDriver.class.php#L369-L370

**Comment by sergiz** [comment]
It's working, thanks!
