### ISSUE TITLE
Impossible to drag internal file in folder 

### ISSUE THREAD

**Issue by Ange7** [Studio-42/elFinder#3169]
Hello,
It's impossible to drag a file in one folder for example
i don't understand why ?
Maybe one option to enable ? 

![](https://framapic.org/hSEqqDIn9Kos/BI3uKBnrZgSK)

> elFinder
> Version: 2.1.26, Version du protocole: 2.1026
> jQuery/jQuery UI: 2.2.4/1.12.1

**Comment by Ange7** [comment]
Just upgrade to new version

> Version: 2.1.56 (2.1-src Nightly: d38a945)
> Version du protocole: 2.1056
> jQuery/jQuery UI: 2.2.4/1.12.1

But same problem

**Comment by Ange7** [comment]
any idea ?

**Comment by nao-pon** [comment]
@Ange7 Is uploading of pdf file permitted?

**Comment by Ange7** [comment]
@nao-pon yes i can upload file

**Comment by nao-pon** [comment]
@Ange7 Is it possible to cut and paste?

**Comment by Ange7** [comment]
@nao-pon yes, i can cut and paste

**Comment by Ange7** [comment]
![Peek 02-06-2020 09-56](https://user-images.githubusercontent.com/4114703/83495026-6c3b0880-a4b7-11ea-9633-c67b62bb9899.gif)

**Comment by Ange7** [comment]
Someone can help me ?

**Comment by Ange7** [comment]
problem not solved...

**Comment by Ange7** [comment]
nobody can help me ?

**Comment by Ange7** [comment]
Help.

**Comment by Ange7** [comment]
@nao-pon can you help me ?

**Comment by Ange7** [comment]
Need help... please @nao-pon ?

**Comment by nao-pon** [comment]
@Ange7 Is the JSON response from the server normal for permissions? Compare the data when you open the parent of the target folder and when the target folder is the current working directory.

**Comment by Ange7** [comment]
Thanks @nao-pon for your answer

I attach on zip file with 2 json file,

first « root_folder » is the main answer when my root folder are open. 
the second is the answer when i open one folder from my root folder. 

I don't see anything in JSON... 

[json.zip](https://github.com/Studio-42/elFinder/files/6121570/json.zip)

Thank you

**Comment by Ange7** [comment]
@nao-pon do you have an idea ?

**Comment by Ange7** [comment]
@nao-pon is it possible cause : 
```
'disabled' => 
      array (
        0 => 'chmod',
      ),
```

?

**Comment by Ange7** [comment]
@nao-pon one year later i don't find solution about my problem...

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.

**Comment by Ange7** [comment]
@nao-pon Why close this discussions without help ?
