### ISSUE TITLE
uploading file in mobile phone, only one file selected.

### ISSUE THREAD

**Issue by hanyingzhong** [Studio-42/elFinder#3170]
multi files can be selected as PC version?

**Comment by nao-pon** [comment]
@hanyingzhong I have tested it and it is possible to upload multiple files on Android 9 + Chrome 83 and iPhone 13.4 + Safari 13.1.

ex. Android 9 + Chrome 83
![20200531_212259](https://user-images.githubusercontent.com/1412630/83352225-0fd7cc00-a385-11ea-843b-aeaff124ca7a.gif)
