### ISSUE TITLE
How to open/show specific folder from AWS S3 bucket

### ISSUE THREAD

**Issue by lshakya** [Studio-42/elFinder#3171]
How can I show a specific folder list while opening elFinder.

I tried as follow, but didn't work.

```
$opts = array(
    // 'debug' => true,
    'roots' => [
                [
            'driver' => 'Flysystem',
            'alias' => 'File Storage',
            'filesystem' => $filesystem,
            'path'   => $aws_url .'/folder1/folder2/folder3/',
            'startPath' => $aws_url .'/folder1/folder2/folder3',
            'URL' => $aws_url ,

            'tmbURL' => 'self'
        ]
    ]
);
// Trying to set Folder3 as root folder
```
Will really appreciate if someone can help.

**Comment by dmarcos89** [comment]
hey, this is bit old but how did you solve it? i have spent days but couldnt solve it!! 
thanks!!

**Comment by nao-pon** [comment]
If the hash is constant when opened in a browser, you can try the UI option `startPathHash`.

https://github.com/Studio-42/elFinder/blob/33eea861cb07196edbde5d9188f65a6ce81be21f/js/elFinder.options.js#L756-L772

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
