### ISSUE TITLE
Elfinder v2.1.56 UI breaks down when used with JQuery v3.5.1

### ISSUE THREAD

**Issue by mghazian** [Studio-42/elFinder#3174]
When elfinder is used with jQuery v3.5.1, I get this:

![image](https://user-images.githubusercontent.com/18474654/83807702-b3a2de00-a6dd-11ea-9544-67cc3bc0b2a4.png)

as opposed of this (using jQuery v3.4.1):

![image](https://user-images.githubusercontent.com/18474654/83807420-3f683a80-a6dd-11ea-9ed8-8296c763da47.png)

This was tested using the following common files:

- jQueryUI v1.12.1
- PopperJs v1.16.0

**Comment by EddieK31** [comment]
Same issues here.  Looks like the folder object are nested.  Don't know if this helps or I am off base, but figured I would post.

![elfinder-next](https://user-images.githubusercontent.com/20583681/83832039-f1841000-a6a5-11ea-8810-156a2052e044.png)

Left pane seems to have a similar issue as well as right click menus.

![ElFinder](https://user-images.githubusercontent.com/20583681/83832158-3dcf5000-a6a6-11ea-9251-07092c05a641.png)

![elfinder_version](https://user-images.githubusercontent.com/20583681/83832246-6bb49480-a6a6-11ea-80e0-0f4079324141.png)

**Comment by nao-pon** [comment]
@mghazian , @EddieK31 I have released Version 2.1.57 which fixes this issue. Please use it.

rel. #3148
