### ISSUE TITLE
Translations missing & Wrong fullscreen button caption

### ISSUE THREAD

**Issue by munish48** [Studio-42/elFinder#3177]
Hey @nao-pon ,

Our QA Team is testing elFinder library, we found some issues.

1) Some translations are missing, i am attaching screenshot. 
Steps: 
a) Select "ar" language.
b) Right click on any folder.
You can see some translations are missing.

Please have a look on screenshot.
![image](https://user-images.githubusercontent.com/24403435/84375318-01977480-abfd-11ea-9cc2-caf76c616a0f.png)

2) After escaping from the full screen, "Reinstate" doesn't change to "Full screen".

Steps:

a) Right click on the window and click on the "Full Screen" option.
b) Then press the "esc" key from your keyboard to escape the full screen.
c) Now after getting back to the default size of the window, again right click on the window and observe the Full screen" option. It's still "Reinstate".

Please have a look on screenshot.
![image](https://user-images.githubusercontent.com/24403435/84375679-900bf600-abfd-11ea-8dfc-7c1e1ce9b858.png)

Thanks
Munish Kumar

**Comment by nao-pon** [comment]
@munish48 The language of the translation is kept by the contributors of each language, so some languages may not be sufficient. We are always looking for PR.

- https://studio-42.github.io/elFinder/tools/langman/#2.1:ar

The display error for full windows is a bug, so I will fix it.

Thanks! 👍
