### ISSUE TITLE
How to use AutoRotate plugin 

### ISSUE THREAD

**Issue by akanendo** [Studio-42/elFinder#3179]
Hi!
I'm using elfinder ver 2-1.57.
This img is reversed in FireFox Browser(77.0.1) windows 10 when upload.

![IMG-0042](https://user-images.githubusercontent.com/57430837/84868136-2edd9a00-b0b7-11ea-82c0-07aa1a6487cf.jpg)

like that↓

![elfinderRoteto](https://user-images.githubusercontent.com/57430837/84868501-bf1bdf00-b0b7-11ea-86f3-784a78c17cdf.png)

This img file has Exif information.
So I thought to remove Exif information or rotate the img.
I wrote connector.minimal.php like that.
```
$opts = array(
	// 'debug' => true,
	'roots' => array(
		// Items volume
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '../files/',                 // path to files (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
			'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image/x-ms-bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/x-icon', 'text/plain'), // Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		),
	),
	'bind' => array(
	     'upload.presave' => array(
			 'Plugin.AutoRotate.onUpLoadPreSave',
			 'Plugin.AutoResize.onUpLoadPreSave',
	     )
	 ),
	'plugin' => array(
		'AutoRotate' => array(
		    'enable'         => true,       // For control by volume driver
		    'quality'        => 95,         // JPEG image save quality
		    'offDropWith'    => null,       // Enabled by default. To disable it if it is dropped with pressing the meta key
		                                    // Alt: 8, Ctrl: 4, Meta: 2, Shift: 1 - sum of each value
		                                    // In case of using any key, specify it as an array
		    'onDropWith'     => null        // Disabled by default. To enable it if it is dropped with pressing the meta key
		                                    // Alt: 8, Ctrl: 4, Meta: 2, Shift: 1 - sum of each value
		                                    // In case of using any key, specify it as an array
		),
		'AutoResize' => array(
			'enable'         => true,       // For control by volume driver
			'maxWidth'       => 1024,       // Path to Water mark image
			'maxHeight'      => 1024,       // Margin right pixel
			'quality'        => 95,         // JPEG image save quality
			'preserveExif'   => false,      // Preserve EXIF data (Imagick only)
			'forceEffect'    => false,      // For change quality of small images
			'targetType'     => IMG_GIF|IMG_JPG|IMG_PNG|IMG_WBMP, // Target image formats ( bit-field )
			'offDropWith'    => null        // To disable it if it is dropped with pressing the meta key
											// Alt: 8, Ctrl: 4, Meta: 2, Shift: 1 - sum of each value
											// In case of using any key, specify it as an array
		)
	),
);
```
But it doesn't work.

Is there a workaround?
Could you provide an example please?

**Comment by nao-pon** [comment]
@akanendo There seems to be no problem with your settings. Make sure you have the exif extension installed in your PHP environment.

**Comment by akanendo** [comment]
@nao-pon 
Thank you!
I checked my PHP environment.

exif extention installed.
↓

`EXIF Support => enabled
EXIF Version => 1.4 $Id: 05041c5f0094cb46d9b516bd624d593b90cc38f9 $
Supported EXIF Version => 0220
Supported filetypes => JPEG,TIFF

Directive => Local Value => Master Value
exif.decode_jis_intel => JIS => JIS
exif.decode_jis_motorola => JIS => JIS
exif.decode_unicode_intel => UCS-2LE => UCS-2LE
exif.decode_unicode_motorola => UCS-2BE => UCS-2BE
exif.encode_jis => no value => no value
exif.encode_unicode => ISO-8859-15 => ISO-8859-15`

PHP version is 5.4.45.

Are there other possible causes?

**Comment by akanendo** [comment]
@nao-pon
I checked setting today.
Actually, I checked another server setting  at that time.

And then the image was displayed correctly.

![20200811](https://user-images.githubusercontent.com/57430837/89876739-0925ca80-dbfa-11ea-80ea-e3d445d7667e.png)

It's working as expected.
Sorry... and thank you!
