### ISSUE TITLE
Webdav drive mount

### ISSUE THREAD

**Issue by CodeLyokoZ** [Studio-42/elFinder#3180]
Is any ideas for mount webdav cloud in elFinder?

**Comment by nao-pon** [comment]
@CodeLyokoZ You can use FlySystem's WebDav adapter via [barryvdh/elfinder-flysystem-driver](https://github.com/barryvdh/elfinder-flysystem-driver).

**Comment by pfleche** [comment]
hi,

I try to use Flysystem driver to connect to a webdav target with elfinder.
I use 2.1.53 version of elfinder.
It is installed on Windows server with IIS.
I am used to use LocalFileSystem driver with Elfinder and it work correctly.
With Flysystem and webdav I have a 500 return code.
I have tried to install the Flysytem driver like this : https://github.com/barryvdh/elfinder-flysystem-driver
The content of my connector.minimal.php below 

require './driver.php';
use Sabre\DAV\Client;
use League\Flysystem\WebDAV\WebDAVAdapter;

$settings = array(
                      'baseUri' => 'http://localhost:8080',
                      'userName' => 'user',
                      'password' => 'pwd',
                  ); 

$client                  = new Client($settings);
$webdavAdapter  = new WebDAVAdapter($client,"/content/default/");
$webdavfs            = new Filesystem($webdavAdapter);

$opts = array(
               'debug' => true,
        	'roots' => array(
                                    // WebDAV		
                                    array(
                                        'driver'        => 'Flysystem',
                                        'filesystem'    => $webdavfs                 
                                    ),
                                 )
             );

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();

Is there another file log than IIS log like \intepub\logs\logfiles ?
Any idea why I have a 500 error code ?

Thanks
