### ISSUE TITLE
Folder upload makes many many dirs, then fails

### ISSUE THREAD

**Issue by mvannes** [Studio-42/elFinder#3181]
Hello,

Using latest elfinder with FTP drivers I've noticed that while uploadMaxSize is recognized and used when I upload a file that exceeds it (in my case maxUploadSize == 72M), when I upload a folder that is much larger, it will begin to create the folder, as well as any subdirs. However, I've limited the max_execution_time to 300s (which should generally be plenty), which means that for large folders many subdirs are made and then not filled.

The behaviour I'm looking for:
- A way to prevent large uploads of folders from making dirs, by seeing how large their combined contents are.
OR
- A way to disable folder uploads. Forcing users to upload an archive and unpacking it works fine for my usecase.

Scrolling through the code, I'm not sure this option exists.

thank you in advance for any response.

**Comment by nao-pon** [comment]
@Mvannes I consider adding a new option that allows the user to limit the number of folders uploaded.

Thanks! 👍
