### ISSUE TITLE
Generate PDF and Video Thumbnails

### ISSUE THREAD

**Issue by Kryptolyser** [Studio-42/elFinder#3183]
Hello there!
Sorry I have to bother you, but my elFinder ver. 2.1.57 doesn't generate any pdf or mp4 thumbnails. How did you do this on your demo website? https://hypweb.net/elFinder-nightly/demo/2.1/#elf_l1_TUlNRS10eXBlcw
Thumbnails for images are generated and shown.
Thx for your help!

**Comment by nao-pon** [comment]
@Kryptolyser Creating thumbnails for video files requires the server's PHP to be able to use the `ffmpeg` command. If you need a path for ffmpeg, define that path (include ffmpeg) in the constant `ELFINDER_FFMPEG_PATH`.

**Comment by Kryptolyser** [comment]
Alright! Thx @nao-pon, I will try this

**Comment by nao-pon** [comment]
And, To create thumbnails for PDF files, you need the `convert` command (imagemagick). Also, the constant `ELFINDER_IMAGEMAGICK_PS` must be defined to `true`.
However, please enable the handling of PDF files only when the vulnerability of https://www.kb.cert.org/vuls/id/332928 has been resolved in your environment.
