### ISSUE TITLE
Possible enhancement - disable submit on search field.

### ISSUE THREAD

**Issue by JupiterJones** [Studio-42/elFinder#3184]
I find I need to hack the search field whenever the elFinder component is located within a form to prevent the form submitting when the user searches for files:

$(".elfinder-button-search input").keypress(function(){if(event.which=="13"){event.preventDefault()}})

Maybe this should be the default behaviour, or an option.

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
