### ISSUE TITLE
symlinks that target directories outside of the root volume don't show in interface.

### ISSUE THREAD

**Issue by hedgehog90** [Studio-42/elFinder#3186]
I have my root set to /home/user1/uploads, if I create the following symlink it doesn't appear in the interface:
`ln -s /home/user2/blah /home/user1/uploads/blah`

I assumed this is just an enforced limitation of elfinder, however if I make the following symlink, it does work:
`ln -s /tmp /home/user1/uploads/temp`

I think possible symlinks targeting /tmp are just an exception to the rule, I can't get any other symlink targeting a directory outside of elfinder's root volume to show up.

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
