### ISSUE TITLE
Problem with session

### ISSUE THREAD

**Issue by Djaizansi** [Studio-42/elFinder#3187]
Hello,

I'm use elFinder in my project. I'm configuring it and i try to use it too but the problem it's that the session are destroy. Indeed, i use the session for connect users :/ (it's project for school, he isn't online so it's ok)

thanks !

**Comment by rhalp10** [comment]
we have the same issue, once the elfinder load the current session will be destroyed.

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
