### ISSUE TITLE
Elfinder first showing issue.

### ISSUE THREAD

**Issue by ppankov85** [Studio-42/elFinder#3188]
I faced some strange issue on first elfinder showing: when page is loaded for a first time, the elfinder component has additional height. After window resizing (e.g. minimize and then maximize browser window) the elfinder component changes his height to normal, as it have to be. Height is set in 'options' as height: '65%', its parent control is a popup window.

Screenshots:
before window resize (directly after page loaded):
![изображение](https://user-images.githubusercontent.com/64863192/86611214-06123b80-bfb7-11ea-9880-d6e38c47c40b.png)
after window resize:
![изображение](https://user-images.githubusercontent.com/64863192/86611145-e7ac4000-bfb6-11ea-88f2-62fba04c0b2c.png)

Any suggestions?

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
