### ISSUE TITLE
Download Folder uncompressed 

### ISSUE THREAD

**Issue by davi1td** [Studio-42/elFinder#3189]
Hi, I searched everywhere but can;t seem to find how to do this. 
When I choose right-click=> Download, how can I change the behavior for the command run, either set to zip uncompressed(store only) and maybe even use tar instead?
Thanks
-TD

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
