### ISSUE TITLE
Unable to create new Folder

### ISSUE THREAD

**Issue by atulk101992** [Studio-42/elFinder#3190]
hi i am using ElFinder for image uploading with Azure Driver in laravel, i am not able to create folder on Driver storage while using Azure, if i used s3 then Elfinder allow me to create new folder but while using Azure it will give error,

![crate-folder-issue](https://user-images.githubusercontent.com/64954523/86922720-a9e02080-c14a-11ea-8f70-7b5ee1b77739.png)

Please help me to solve this issue.

**Comment by psusset** [comment]
Hello,

I've got the same problem. Did you find any solution ?

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
