### ISSUE TITLE
Invalid detection of JS baseUrl

### ISSUE THREAD

**Issue by applibs** [Studio-42/elFinder#3193]
I checked this function:
```
$('head > script').each(function() {
	if(this.src && this.src.match(/js\/elfinder(?:-[a-z0-9_-]+)?\.(?:min|full)\.js$/i)) {
		myTag = $(this);
		return false;
	}
});
```

There are 2 problems:
1. when all my scripts are in body then its not detected and it will generate wrong relative baseUrl later. Please enhance jQuery selector to: "head > script, body > script"
2. When my elfinder url is managed by query vesion like this: "./elfinder/js/elfinder.full.js?version=5631" or anything else then regex will ignore it. Please enhance regex which will accept different url and not only stricted format.

Then theme.css for example is not loaded, because loading from wrong url.

**Comment by nao-pon** [comment]
@applibs I chose not to search inside the <body> because it could affect performance.
Please consider using the client option `baseUrl`.
