### ISSUE TITLE
Don't allow dir rename

### ISSUE THREAD

**Issue by ShinJii89** [Studio-42/elFinder#3194]
Hi,
Is this possible to not allow directories rename but allow files rename?

**Comment by ShinJii89** [comment]
@nao-pon can you answer something? :D

**Comment by ShinJii89** [comment]
@nao-pon is this possible? Still need this feature...

**Comment by sergiz** [comment]
Check "handlers" option on the client-side and "bind" on the server-side.

There's some example for the client'side: https://github.com/Studio-42/elFinder/wiki/Client-event-API

**Comment by ShinJii89** [comment]
> Check "handlers" option on the client-side and "bind" on the server-side.
> 
> There's some example for the client'side: https://github.com/Studio-42/elFinder/wiki/Client-event-API

I don't see there anything to disable "rename Dirs" and enable "rename files" at the same moment :( there's just action "rename" but I guess it's for dir & files at the same moment.

**Comment by sergiz** [comment]
You have to write your own logic of course. You get the necessary data available in your event handler.

**Comment by ShinJii89** [comment]
> You have to write your own logic of course. You get the necessary data available in your event handler.

Can you give me some simple example?:) @nao-pon always gave me examples :D

**Comment by nao-pon** [comment]
@ShinJii89 This is a callback sample of the bind option.

```php
'rename.pre' => function($cmd, $args, $elfinder, $volume) {
	$target = $args['target'];
	if ($file = $volume->file($target)) {
		if ($file['mime'] === 'directory') {
			return [
                'preventexec' => true,
                'results' => [
                    'error' => 'Folders cannot be renamed.'
                ]
            ];
		}
	}
},

```

**Comment by nao-pon** [comment]
@sergiz Thank you for following up!

**Comment by ShinJii89** [comment]
> @ShinJii89 This is a callback sample of the bind option.
> 
> ```
> 'rename.pre' => function($cmd, $args, $elfinder, $volume) {
>     $target = $args['target'];
>     if ($file = $volume->file($target)) {
>         if ($file['mime'] === 'directory') {
>             return [
>                 'preventexec' => true,
>                 'results' => [
>                     'error' => 'Folders cannot be renamed.'
>                 ]
>             ];
>         }
>     }
> },
> ```

You're irreplaceable! Thanks! :)))
