### ISSUE TITLE
Issue with startPathHash & URL hash folder opening

### ISSUE THREAD

**Issue by mrxkon** [Studio-42/elFinder#3196]
Hey there @nao-pon ,

I'm seeing weird misbehavior lately, let me try to explain as much as possible and the good thing is I can also replicate with your hosted demo so I'm not going crazy here haha.

The `startPathHash` is not properly working after I updated to the latest so this might be an unwanted side-effect as well. In the earlier version, we could navigate to other folders just by changing the URL anchor link to a folder hash. On the latest version, there's always a popup saying `Press again to exit` which pretty much breaks the older usage I believe.

To easily replicate:
1. Open the demo page and copy any PathHash from the addressbar
2. Navigate into a different folder.
3. Paste the previous PathHash to the address bar and press enter

- Current version: shows a "Press again to exit" message.
- Expected (previous version): directly navigate to that folder

Video: https://www.loom.com/share/e7a2344687714f02a1b0ec5bb301f648

Please do tell me if this is expected behavior on the latest just in case I'm missing anything, I'm basically using a dynamically driven "startPathHash" via PHP which stopped working so after some testing I stumbled upon the exit message that seemed weird to me (at least I'm pretty sure it wasn't doing it on an earlier version).

Cheers!

**Comment by mrxkon** [comment]
Mhmh, going back and forth to this I figured out that another part of my changes was interfering and everything seems fine. Closing! :D

**Comment by ikiK-CRO** [comment]
What was the change? I have same problem, Aldo am new to this app i wen threw all documentation and I don't know how to open a specific folder on load. Nothing I tired works, and when I console log my test hashes and paths and try them on address bar I also get Press again to exit...
