### ISSUE TITLE
Start with fullscreen in an iframe tag

### ISSUE THREAD

**Issue by marioene** [Studio-42/elFinder#3198]
Hi! First, great package!

I am using elFinder object in a iframe in a project with Bootstrap 4 in Laravel 7.x

I can't find the setting to open initially elFinder in fullscreen mode in that iframe. 

I have tried to modify the file "main.basicauth.js", like in [#1728](https://github.com/Studio-42/elFinder/issues/1728), but without success.

My code from my Laravel project:

```	
<div class="col-7 col-sm-7 col-md-8 col-lg-10 col-xl-10">	
	<div class="embed-responsive embed-responsive-16by9" style="height: 600px">
  		<iframe class="embed-responsive-item" src="http://<ip-address>/elfinder/index.html">/iframe>
	</div> 
</div>
```

If I click manually on Reinstate (Fullscreen) button on the menu bar, the elFinder is maximized in the 600px height area (defined in style of the div).

Any solution is very welcome!

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
