### ISSUE TITLE
rememberLastDir: false Not working php 7.4

### ISSUE THREAD

**Issue by kainpro** [Studio-42/elFinder#3199]
Good afternoon, I currently have problems with this functionality, even deactivating the option, it still does not run. and remembering the previous open directory.

according to the documentation to deactivate it is like this **rememberLastDir: false**

if there is any solution for this? use php 7.4 version

**Comment by sergiz** [comment]
This shouldn't be impacted by the backend, since this functionality is provided only by frontend. Do you have sessionStorage/cookies enabled in your browser?

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
