### ISSUE TITLE
Unable to connect to backend. HTTP error 406.

### ISSUE THREAD

**Issue by Le-Maximilien** [Studio-42/elFinder#3201]
Hello, i`m have a website with elFinder module, and recenrly it`s start showing error "Unable to connect to backend. HTTP error 406.". I tried to update elFinder, but this dont fix this. What`s should i do?

**Comment by jeedomsteph37** [comment]
Hi,
Same problem...

**Comment by Le-Maximilien** [comment]
UPD: If you using hosting REG.RU, just ask suppor to do this: 
<IfModule mod_security.c>
   SecFilterEngine Off
   # and optionally this:
   #SecFilterScanPOST Off
</IfModule>

Thanks to #1574
