### ISSUE TITLE
 zoho editor is not working.

### ISSUE THREAD

**Issue by choowolms** [Studio-42/elFinder#3205]
Hello..

I want to use the zoho editor.

However, it doesn't work with version 2.1.57.

In the past, I used the zoho editor in El Finder, and even now I set it up recalling memories of the past, but the zoho editor was not active.

Could you please let me know if there is a problem with loading the zoho editor in the settings below?

[php]
define('ELFINDER_ZOHO_OFFICE_APIKEY','hidden');

$host = $_GET['host'];

$user = $_GET['user'];

$pass = $_GET['pass'];

// Documentation for connector options:

// https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options

$opts = array( 
        'roots' => array(
                array(
                        'driver' =>'FTP', // driver for accessing file system (REQUIRED)
                        'host' => $host, //'uploadDeny' => array('all'), // All Mimetypes not allowed to upload'uploadAllow' => array('image/x-ms-bmp','image/ gif','image/jpeg','image/png','image/x-icon','text/plain','img/bmp','application/pdf','text/csv','application/ vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.presentationml.presentation', ' application/vnd.ms-powerpoint','application/x-mspublisher','audio/x-ms-wma','application/msword','application/x-mswrite','audio/midi','audio/ mpeg','audio/ogg'), // Mimetype `image` and `text/plain` allowed to upload
                        'uploadOrder' => array('deny','allow'), // allowed Mimetype'accessControl' =>'access',
                        'user' => $user,'pass' => $pass,
                        'path' =>'/'
                ),
        )
);

The editors.default(.min).js file is also loaded from the html file (elfinder.html).

**Comment by choowolms** [comment]
I want to write down all the information, but it is not currently possible, so I only post the edited part.
Sorry.

**Comment by nao-pon** [comment]
@choowolms No problem with our demo site. Please check your settings again.
