### ISSUE TITLE
Why is edit dialog not resizable on "e" and "s"?

### ISSUE THREAD

**Issue by sergiz** [Studio-42/elFinder#3206]
https://github.com/Studio-42/elFinder/blob/e29627fc9c6572dabfb95980374e4e0ab493068d/css/dialog.css#L222-L226

Hello.

Is there a special reason why resizing on "e" and "s" sides is disabled like this?

**Comment by nao-pon** [comment]
@sergiz I'm not involved in the development of this part, so I don't know exactly, but it may be design-like. If you enable it in CSS and there are no functional issues, please customize CSS.

**Comment by nao-pon** [comment]
I presume that the feature is enabled and disabled in CSS to make it customizable in CSS.
