### ISSUE TITLE
Cannot upload folder！

### ISSUE THREAD

**Issue by TreHack** [Studio-42/elFinder#3208]
The version of elfinder is 2.1.57.
I select a folder（contain some files）to upload，the folder make success，but the files cannot upload.
but when I change the elfinder version to 2.1.39, it can mkdir and the files also upload success.
It removed the feature since 2.1.39？

**Comment by nao-pon** [comment]
@TreHack There is no such change.

If you can't upload files, it's possible that you aren't allowed to upload those file types.
