### ISSUE TITLE
Position on (select) given file in a folder - preselected with startPathHash

### ISSUE THREAD

**Issue by nmpetkov** [Studio-42/elFinder#3209]
Is it possible to select (highlite) given file in elfinder file browser window, in similar way as it happens with provided option startPathHash?
Or how to select programmatically given file after elfinder is instantiated?

**Comment by nao-pon** [comment]
@nmpetkov It can be difficult. Because, if there are many items in the folder, some items will not be displayed unless you scroll. This is because there is no implementation that reliably displays even a specific file.
