### ISSUE TITLE
Error on Extract Hidden files

### ISSUE THREAD

**Issue by MiteshShah** [Studio-42/elFinder#3210]
![Screenshot 2020-09-27 at 6 27 55 PM](https://user-images.githubusercontent.com/1223371/94365505-3d444480-00ef-11eb-9944-84af940b4521.png)

If zip archive contains any files start with DOT its give same error.

```
date > .123.txt 
cd ..
zip -r hello3.zip hello
```

**Comment by nao-pon** [comment]
@MiteshShah That's because the volume driver configuration doesn't allow uploading those files. Please allow those file types. However, please be careful about security.
