### ISSUE TITLE
Add Event is not triggering or triggering incorrectly.

### ISSUE THREAD

**Issue by muscankaraoglu** [Studio-42/elFinder#3215]
I would like handle file(s)/folder(s) when they adding but "add" event is not triggering correctly. When I add a file or folder it doesn't trigger an event, it just triggers when I delete the file.

My event usages:
1st: 
`fm.bind('add', function (event, fm) {
    var files = event.data.added;
   console.log(files);
});`

2nd:
`defaultOpts : {			url : 'elfinder/php/connector.minimal.php', 
			handlers : {
				add: function(event, fm){
					var files = event.data.added;
                                        console.log(files);
				},
	 },`

Both events do not work correctly.

Can you give me an idea? Thank you in advance..

**Comment by nao-pon** [comment]
@muscankaraoglu Listen for the `upload`,` paste`, `mkfile`,` mkdir` commands.
