### ISSUE TITLE
Zipdl create temp zip but don't download it

### ISSUE THREAD

**Issue by Diegorossi1977** [Studio-42/elFinder#3221]
Elfinder 2.1.57
installed on wampserver (win10) and apache (linux Debian) with PHP 7.4

This in my connector.minimal.php:
```
$opts = array(
	'debug' => true,
	'roots' => array(
		// Items volume
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
			'path'          => '../files/',                 // path to files (REQUIRED)
			'tmpPath' 		=> '../tmp/',
			'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('all'), 				// Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		),
	)
);

```
If I select multiple file and try to download it, the zipdl create a temporary file in tmpPath directory (../tmp/) but don't download it because the browser (Chrome) respond "file not found"
![CatturaTMPdirectory](https://user-images.githubusercontent.com/74357905/98945463-d76f1900-24f2-11eb-9997-1a0738a25caa.PNG)
![CatturaFileNotFound](https://user-images.githubusercontent.com/74357905/98945465-d8a04600-24f2-11eb-86b1-7d8f1e46d75c.PNG)

The Elfinder dubug don't make some error and this is the response of callback with the Chrome inspector

![CatturaDebugElfinder](https://user-images.githubusercontent.com/74357905/98945747-3765bf80-24f3-11eb-937f-eea8d2193762.PNG)

> {zipdl: {file: "5fad385d7c26d", name: "files_Files.zip", mime: "application/zip"},…}
> debug: {connector: "php", phpver: "7.4.0", time: 0.6851339340209961, memory: "4250Kb / 542Kb / 128M",…}
> backendErrors: []
> connector: "php"
> memory: "4250Kb / 542Kb / 128M"
> mountErrors: []
> phpver: "7.4.0"
> time: 0.6851339340209961
> upload: ""
> volumes: [{id: "l1_", name: "localfilesystem", mimeDetect: "finfo", imgLib: "gd"}]
> zipdl: {file: "5fad385d7c26d", name: "files_Files.zip", mime: "application/zip"}
> file: "5fad385d7c26d"
> mime: "application/zip"
> name: "files_Files.zip"
> 
> {"zipdl":{"file":"5fad385d7c26d","name":"files_Files.zip","mime":"application\/zip"},"debug":{"connector":"php","phpver":"7.4.0","time":0.6851339340209961,"memory":"4250Kb \/ 542Kb \/ 128M","upload":"","volumes":[{"id":"l1_","name":"localfilesystem","mimeDetect":"finfo","imgLib":"gd"}],"mountErrors":[],"backendErrors":[]}}
> 
> 

Can someone help me and tell me where i am wrong???

Thank you for any advice..

**Comment by benny-adiwijaya** [comment]
Hi i got same problem here, is there any clue?

**Comment by benny-adiwijaya** [comment]
https://github.com/Studio-42/elFinder/issues/2910#issuecomment-488300619

this solution work for me

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
