### ISSUE TITLE
elFinder 2.1.x shows [Script error for "elfinder"] right after fresh install

### ISSUE THREAD

**Issue by AlexanderSuvorovN** [Studio-42/elFinder#3223]
I installed elFinder using provided instructions for Git installation and after installation when I enter "http://localhost/elFinder/elfinder.html" in the address line I get following errors (JavaScript alerts):
- Script error for "elfinder"
- Script error for "extras/editors.default.min"
Then nothing happens -- just white blank screen.
If I enter "http://localhost/elFinder/elfinder.src.html" in address bar then elFinder appears.

**Comment by nao-pon** [comment]
You have the wrong file to download. Download it from https://github.com/Studio-42/elFinder#downloads.

The master branch is for development.
