### ISSUE TITLE
How i share the directly between two users ?

### ISSUE THREAD

**Issue by nitiz143** [Studio-42/elFinder#3224]
I have  multiple users but need to define the directory for user a upload docs for user b. No one accees these docs

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
