### ISSUE TITLE
Toolbar cut button not showing

### ISSUE THREAD

**Issue by db1996** [Studio-42/elFinder#3225]
We're using elfinder as a file manager for our CMS with the MySQL volume, so customers can edit and move around files. 

This is what my uiOptions  look like:

`uiOptions: {
    toolbar : [
	['home', 'back', 'forward', 'up', 'reload'],
	['netmount'],
	['mkdir', 'mkfile', 'upload'],
	['open', 'download', 'getfile'],
	['undo', 'redo'],
	['copy', 'cut', 'paste', 'rm', 'empty', 'hide'],
	['duplicate', 'rename', 'edit', 'resize', 'chmod'],
	['selectall', 'selectnone', 'selectinvert'],
	['quicklook', 'info'],
	['extract', 'archive'],
	['search'],
	['view', 'sort'],
	['preference', 'help'],
	['fullscreen']
    ],
},`

The cut button does not show up in the toolbar at all, there's only the copy and the paste button in that section. Is there some reason that function is blocked? The cut function also does not show up in the contextmenu.

**Comment by nao-pon** [comment]
If the command is disabled on the connector side (backend side), the command on the UI side will not be displayed. Check the settings on the connector side.

Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
