### ISSUE TITLE
Unable to see folders and files

### ISSUE THREAD

**Issue by zeesh1979** [Studio-42/elFinder#3230]
Hi,
I copied the source contents into htdocs of my xamp installed on Windows 10. When i open http://localhost/elfinder/elfinder.html it doesnt show files in my directory? is there something i am missing as how to use it?shouldnt it show my files and folders on my laptop?

**Comment by nao-pon** [comment]
Probably there are no items to display in the specified folder.

Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
