### ISSUE TITLE
Not able to upload files bigger than 2GB

### ISSUE THREAD

**Issue by magdesign** [Studio-42/elFinder#3231]
OS: Raspian Stretch 9.11
elFinder Version: 2.1.57
Filesystem: ext4

Not able to upload files bigger than 2048 MB:
![maxsize](https://user-images.githubusercontent.com/5273166/100763244-325ea680-33f5-11eb-9972-355e2d157921.png)

php.ini is configured to:
```
upload_max_filesize = 8000M
post_max_size = 8500M
```
with eXtplorer on the same server I am able to upload 8GB files.

also tried with editing connector.minimal.php:

`	'uploadMaxSize'	  => '80000M'`

Did not help.
Knowing about closed issue: https://github.com/Studio-42/elFinder/issues/903 but there is no solution.
Would be lovely if someone points me into the right direction!

**Comment by nao-pon** [comment]
@magdesign Is your system a 64-bit OS? Limited for 32-bit systems.

**Comment by magdesign** [comment]
its on a RaspberryPi limited to 32- bit.

**Comment by nao-pon** [comment]
elFinder has a limit on the file size that can be uploaded in a 32-bit environment.
