### ISSUE TITLE
can i change file edit view default tab size ?

### ISSUE THREAD

**Issue by russh3l** [Studio-42/elFinder#3236]
can i change file edit view default tab size ?

**Comment by Ange7** [comment]
same question for preview in full screen

**Comment by nao-pon** [comment]
Please check ui option `commandsOptions.edit`.

https://github.com/Studio-42/elFinder/blob/1b9707cb97f5a328aeaec52cefbe9ff1a4c0281d/js/elFinder.options.js#L411-L515
