### ISSUE TITLE
css: pre.elfinder-quicklook-preview-text ?

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#3240]
https://hypweb.net/elFinder-nightly/demo/2.1/files1/pre.elfinder-quicklook-preview-text.png
What for ?)
`.elfinder-quicklook-preview-text-wrapper` already has a background #fff

**Comment by nao-pon** [comment]
@johnfort Yes, it certainly doesn't seem necessary. I will scrutinize this.
