### ISSUE TITLE
Invalid backend response. Data is not JSON.

### ISSUE THREAD

**Issue by neetagit** [Studio-42/elFinder#3245]
Hi we are trying to implement the elfinder in code php project.
We are receiving the popup with error Invalid backend response.Data is not JSON.

In the connector.minimal.php call , "The request has no response data [available"

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
