### ISSUE TITLE
 Readable volumes not available. 

### ISSUE THREAD

**Issue by kkumarsantosh90** [Studio-42/elFinder#3246]
I have applied the elFinder in Open Cart with PHP. The directory creation is Dynamic. 
But for some of the cases it is fine and randomly there is error prompt
"**Invalid backend configuration.
Readable volumes not available.**"

On debug found that parameter URL of OPT get blank for the cases when it is an error.

Any solution please suggest to this..

Many thanks ...

**Comment by nao-pon** [comment]
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.
