### ISSUE TITLE
Request for security contact

### ISSUE THREAD

**Issue by thomas-chauchefoin-sonarsource** [Studio-42/elFinder#3288]
Hi! [We](https://github.com/SonarSourceResearch/) tried to contact the various email addresses found in `README.md` to report a security issue, but we haven't heard back so far. Is there a specific address where we can send our analysis to? Another solution is to create a [Security Advisory](https://docs.github.com/en/code-security/security-advisories/creating-a-security-advisory) and invite me to it so we can discuss it privately. Thanks!

**Comment by nao-pon** [comment]
@thomas-chauchefoin-sonarsource I'm sorry, I overlooked the email. I will confirm it from now on.

**Comment by thomas-chauchefoin-sonarsource** [comment]
@nao-pon No worries, thank you for this ack!
