### ISSUE TITLE
Is a new elFinder release planned?

### ISSUE THREAD

**Issue by Colinax** [Studio-42/elFinder#3290]
Hi,
is there any way to get a new elFinder version `2.1.58`?

The latest version is `2.1.57` from `June 5, 2020` and in the master branch there are some good commits like the "same site cookie" fix, webp support and so on that are worth to be put in an official release.

Greetings

**Comment by nao-pon** [comment]
@Colinax I was away for a while, but I'm back again. Slowly, but move forward.

I will release 2.1.58 soon.
