### ISSUE TITLE
Folder upload does not work

### ISSUE THREAD

**Issue by VitalyEmelyanov** [Studio-42/elFinder#3293]
We are using the elFinder with rails backend and api v1.

After updating the version to 2.1.51, the folder upload stopped working (same issue on the latest version 2.1.57)

Before, at version 2.1.21 it worked fine.

The folder is picked via the button "Select folder". After this the directory is created, however the files are not uploaded

**Current behavior (2.1.51):**

1. The mkdir request is sent
```
cmd: mkdir
target: Lg
dirs[]: 
dirs[]: /test
current: Lg
```
2. The open request is sent
```
cmd: open
reload: 1
target: Lg
tree: 1
compare: 
```

**Expected behavior (2.1.21):**
1. The mkdir request is sent
```
cmd: mkdir
target: Lg
dirs[]: test
current: Lg
```
2. Files are uploaded
```
cmd: upload
current: Lg
upload[]: (binary)
mtime[]: 1575280501
upload_path[]: test
```

**Comment by dup2** [comment]
+1 , also see this, how can we fix this issue?

**Comment by ujinius** [comment]
+1, I also faced with this issue.
Please, help!

**Comment by nao-pon** [comment]
What is the protocol version?

![210611-142814](https://user-images.githubusercontent.com/1412630/121635575-6f50d780-cac1-11eb-9ee4-cb801e781af4.png)

**Comment by VitalyEmelyanov** [comment]
> What is the protocol version?
> 
> ![210611-142814](https://user-images.githubusercontent.com/1412630/121635575-6f50d780-cac1-11eb-9ee4-cb801e781af4.png)

Version: 2.1.51
protocol version: 1
jQuery/jQuery UI: 3.5.1/1.12.1

**Comment by nao-pon** [comment]
@VitalyEmelyanov "protocol version: 1" shouldn't support folder uploads, but since it was possible in 2.1.21, is it partially supported?

The first post suggests that there is a problem with the mkdir parameter target hash prefixed with "/".

When you select a folder from the upload dialog and upload it, "/" is added at the beginning, so DnD was unified to that.

Please ask the developer of the connector.

**Comment by nao-pon** [comment]
further,  Since the open command is sent after the mkdir command, it indicates that an error occurred in the connector response of the mkdir command.

**Comment by kenston** [comment]
@nao-pon, I'm also experiencing the same issue in 2.1.60 where I drag-drop a folder `myDir` which contains one file `myFile.png`. 

**Actual**: Only `myDir` is created but `myFile.png` is not uploaded.
**Expected**: `myDir` is created and `myFile.png` is uploaded under `myDir`.

With my backend remain unchanged, I tried each version of ElFinder JS and manage to identify that https://github.com/Studio-42/elFinder/releases/tag/2.1.42 is the last version where it works as expected, and issue starts to happen beginning https://github.com/Studio-42/elFinder/releases/tag/2.1.43.

See my testing:

**2.1.42**

```
cmd: ls
target: 33747361-e30e-47cc-8817-78c2598042d9_Lw
intersect[]: myDir
reqid: 17e7b245cb2298
```

```
cmd: mkdir
target: 33747361-e30e-47cc-8817-78c2598042d9_Lw
dirs[]: /myDir
reqid: 17e7b245cd31df
```

```
reqid: 17e7b245ce63ab
cmd: upload
target: 33747361-e30e-47cc-8817-78c2598042d9_Lw
upload[]: (binary)
mtime[]: 1633694385
upload_path[]: /myDir/myFile.png
dropWith: 0
```

**2.1.43 and 2.1.60**

```
cmd: ls
target: 33747361-e30e-47cc-8817-78c2598042d9_Lw
intersect[]: myDir
reqid: 17e7b262dcf2ca
```

```
cmd: mkdir
target: 33747361-e30e-47cc-8817-78c2598042d9_Lw
dirs[]: /myDir
reqid: 17e7b262de335c
```

It seems to be missing the `upload` call. Hope these new info above can help isolate the cause.
