### ISSUE TITLE
my own session is broken

### ISSUE THREAD

**Issue by applibs** [Studio-42/elFinder#3298]
I see that elFinderSession.php has:
```
if (session_status() !== PHP_SESSION_ACTIVE) {
    session_start();
}
```
But it will broken my session which is already started before this call.
I fixed it by this code:
```
if (session_status() !== PHP_SESSION_ACTIVE && session_status() !== PHP_SESSION_NONE) {
    session_start();
}
```

**Comment by nao-pon** [comment]
@applibs `PHP_SESSION_NONE` indicates that the session has not started yet, in which case elFinder will need to start the session. Can't it be solved by calling `session_start()` before calling the elFinder constructor?

**Comment by applibs** [comment]
I changed my code, Soo I thing that you can close it.

**Comment by nao-pon** [comment]
@applibs Thanks!
