### ISSUE TITLE
rename file after upload

### ISSUE THREAD

**Issue by troex** [Studio-42/elFinder#332]
Example http://pastebin.com/Eq6XT8Pw

**Comment by chiragparekh** [comment]
Use this:

'bind' => array(
        'upload' => 'sanitize'
    ),

**Comment by nao-pon** [comment]
On elFinder 2.1+, you can use [plugin Sanitizer](https://github.com/Studio-42/elFinder/blob/2.x/php/plugins/Sanitizer/plugin.php) .
