### ISSUE TITLE
Do not control width and height during resizing elfinder node

### ISSUE THREAD

**Issue by ToJIka4** [Studio-42/elFinder#3359]
With flex grid I don't need control width and height via style attribute. So I comment this line
https://github.com/Studio-42/elFinder/blob/6f9ce56601be0839e05c4ca5c05762a18128f890/js/elFinder.js#L3484

Can we have control over it? Also this is solution for #2679

**Comment by nao-pon** [comment]
@ToJIka4 I added an option `noResizeBySelf`.

https://github.com/Studio-42/elFinder/blob/3854a50430dcdb11f7a20004854dc077d254f5b5/js/elFinder.options.js#L1114-L1121

Thanks! 👍
