### ISSUE TITLE
elFinder client does not support case insensitive file name compare

### ISSUE THREAD

**Issue by trannamtrung1st** [Studio-42/elFinder#3366]
**Describe the bug**
I upload 2 files with almost the same name (only 1 letter C with a different case, see attached screenshot). Since the backend is not case-sensitive, the FE should also support it (through configuration or BE response or somewhere else). 
**Actual**: After elFinder client asking me for action, I chose to overwrite the original file. However, 2 files were shown as below and then I press F5, the second file disappeared.

**To Reproduce**
1. Upload a file "a.txt"
2. Upload another file "A.txt"
3. Choose the overwrite action
4. 2 files will appear
5. Press F5 then the second file disappears

**Expected behavior**
Only 1 file appears after all.

**Screenshots**
![image](https://user-images.githubusercontent.com/40495531/123046307-259faf80-d426-11eb-956a-88f7256d9bd0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 2.1.59

**Additional context**
Connector: https://github.com/trannamtrung1st/elFinder.Net.Core

**Comment by nao-pon** [comment]
@trannamtrung1st This issue is a server-side connector issue. I have seen a similar issue with the PHP connector. It seems that the client side needs to be modified accordingly too.

I'm going to fix the PHP connector and client side, but that seems to take some time.

**Comment by trannamtrung1st** [comment]
@nao-pon thanks for the update. In my opinion, since different cases generate different file hashes, it will be hard for the client-side to check for duplication without considering the files' names. Btw, those cases are rare and acceptable so this issue is not too urgent.

**Comment by tukusejssirs** [comment]
@nao-pon, is it possible to configure in elFinder server to force treating the files case-insensitively regardless wheather the file system on the server is case-sensitive (e.g. EXT4 on Linux), ideally per root folder?

I my use case, I manually manage SMB/CIFS file shares from Windows on Linux server. I mounted them with `nocase` option, therefore even on the Linux server, `file` and `FILE` in these shares are treated as the same (I cannot create `FILE` if `file` exists), but there are some issues with elFinder, e.g. when I upload a new file via elFinder with the same name as an existing file, but different case, elFinder replaces the old file without prompt.

**Comment by tukusejssirs** [comment]
@nao-pon, is there a way to work this issue around? If it is not possible to add a function which would determine if a file with a specified name already exists (like a `bind` function), is it possible to hard-code the case-insensitivity?
