### ISSUE TITLE
502 response when connecting to s3 bucket

### ISSUE THREAD

**Issue by drashoor** [Studio-42/elFinder#3367]
**Describe the bug**

![image](https://user-images.githubusercontent.com/6551562/124088972-22c34100-da5c-11eb-91c7-345a18d1ab41.png)

The script works fine but suddenly I have a problem, I connect my elfinder to s3 bucket & 502 resulted in the response.

Message:
**Invalid backend response.
Error occurred on the server side.
HTTP error 502**

the message from the console is:

502 ERROR
The request could not be satisfied.
CloudFront couldn't connect to the origin or the origin returned an incorrect response. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
Request ID: ...

**Comment by nao-pon** [comment]
@drashoor This issue does not seem to be a bug in elFinder. So I close this, but if this issue turns out to be a bug in elFinder, you can reopen it with a more detailed explanation.
