### ISSUE TITLE
Syntax errors on PHP 5.3

### ISSUE THREAD

**Issue by aaburlaka** [Studio-42/elFinder#3370]
Arrays in PHP 5.3 cannot be set by [] so I made 2 changes
![image](https://user-images.githubusercontent.com/633676/124363166-64154580-dc42-11eb-96c3-b63b1340664a.png)

In elFinder.class.php on 2697
`curl_setopt($ch, CURLOPT_RESOLVE, [$info['host'] . ':' . $info['port'] . ':' . $info['ip']]);`
changed to
`curl_setopt($ch, CURLOPT_RESOLVE, array($info['host'] . ':' . $info['port'] . ':' . $info['ip']));`

In elFinderVolumeDriver.class.php on 1283
`$auto_types = [];`
changed to
`$auto_types = array();`

**Comment by nao-pon** [comment]
@aaburlaka I done! Thanks! :+1:
