### ISSUE TITLE
Opening a folder in a new window, makes the left tree-navigation disappear

### ISSUE THREAD

**Issue by crackytsi** [Studio-42/elFinder#3376]
**Describe the bug**
I am using https://github.com/imjoy-team/imjoy-elfinder as backend and the lastest elfinder (2.1.59) as frontend.
When I click on a folder "Open in new window" the folder is correctly opened in a new window, but the tree on the left (directory browse interface) is empty and there is only the "favorites" entry.

**To Reproduce**
1. Install imjoy-elfinder backend
2. Install latest elfinder frontend
3. Open a folder in a new window

**Expected behavior**
Tree navigation is still there

**Screenshots**

**Desktop**
 - OS: LINUX RHEL7
 - Browser chrome, safari

**Screenshot**
![image](https://user-images.githubusercontent.com/11610825/124784013-cf625e80-df45-11eb-9b82-57f53d3fa4f0.png)

**Comment by nao-pon** [comment]
@crackytsi Check elFinder for similar issues with a plain configuration (the php connector included in the downloaded archive).

If the plain configuration is fine, you probably have a bug in your integration, not an elFinder bug.

- https://github.com/Studio-42/elFinder/releases/latest (Download)
- https://github.com/Studio-42/elFinder#builds-compressed (Installation)

**Comment by crackytsi** [comment]
The imjoy-elfinder backend does not support all needed operations.
