### ISSUE TITLE
Thumbnails not showing

### ISSUE THREAD

**Issue by oleshek** [Studio-42/elFinder#3381]
Hi, I have the same problem as [here](https://github.com/Studio-42/elFinder/issues/2296). Thumbnails are generated, access mode to them is 777, and I can view thumbnail from my browser if enter path to them, but they are not related to files.

I'm using: 
[FMElfinderBundle](https://github.com/helios-ag/FMElfinderBundle) v10.1
Symfony 5.2
PHP 8.0.3

```
# config/packages/fm_elfinder.yaml
fm_elfinder:
    #assets_path: / # default is /assets, this is where css/js elfinder files are
    instances:
        form:
            locale: '%kernel.default_locale%' # defaults to current request locale
            editor: form # other choices are tinymce or simple, and form
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            connector:
                debug: true # defaults to false
                roots: # at least one root must be defined
                    uploads:
                        driver: LocalFileSystem
                        path: '%apload_files_base_url%'
                        url: '%apload_files_base_url%'
                        tmb_url: '%apload_files_base_url%/tmb/'
                        tmb_path: '%apload_files_base_url%/tmb/'
                        upload_allow: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'video/mp4', 'audio/mpeg', 'video/quicktime']
                        upload_deny: [ 'all' ]
                        upload_max_size: 20M
```
![img](https://user-images.githubusercontent.com/17884467/126160100-154f80d5-b3f1-40df-9227-440f5a808bae.png)

**Comment by nao-pon** [comment]
Check elFinder for similar issues with a plain configuration (the php connector included in the downloaded archive).

If the plain configuration is fine, you probably have a bug in your integration, not an elFinder bug.

- https://github.com/Studio-42/elFinder/releases/latest (Download)
- https://github.com/Studio-42/elFinder#builds-compressed (Installation)

**Comment by oleshek** [comment]
I have downloaded and unzip your latest version of elFinder. Renamed file `/php/connector.minimal.php-dist` but when opened in browser - saw blank page

**Comment by oleshek** [comment]
Fixed - has wrong path in tmb_url

**Comment by tommynet1** [comment]
Can you tell me which file can setup tmb_url ?  Thanks !
