### ISSUE TITLE
getWorkerUrl !!!!

### ISSUE THREAD

**Issue by johnfort** [Studio-42/elFinder#3401]
`getWorkerUrl : function(filename) {
	return this.convAbsUrl(this.baseUrl + 'js/worker/' + filename);
}`
I want to have another way!
Add & rewrite plz: BaseUrl, BaseUrl_i18n, BaseUrl_help, BaseUrl_workers

**Comment by nao-pon** [comment]
@johnfort I add a new option `workerBaseUrl` into elFinder.options.js.

**Comment by nao-pon** [comment]
https://github.com/Studio-42/elFinder/blob/5b667931b9e675cbf88807be4aa69aa9f95ab7e4/js/elFinder.options.js#L197-L222

help url is fm.i18nBaseUrl + 'help/%s.html.js'

[he](https://github.com/Studio-42/elFinder/blob/5b667931b9e675cbf88807be4aa69aa9f95ab7e4/js/commands/help.js#L218-L221)
