### ISSUE TITLE
Extract zip file broken with version 2.1.59

### ISSUE THREAD

**Issue by zengenuity** [Studio-42/elFinder#3407]
**Describe the bug**
When I extract a zip file to "Here", it gives me an error. 

This doesn't happen if I roll back to 2.1.58. So, it may be related to the changes for this fix: https://github.com/Studio-42/elFinder/issues/3252

<img width="1172" alt="Screen Shot 2021-09-25 at 11 27 28 AM" src="https://user-images.githubusercontent.com/1405821/134776999-c94abfb8-21dc-4f14-b447-f4c85fe91fe6.png">

**To Reproduce**
1. Upload this file: https://ftp.drupal.org/files/projects/drupal-8.9.15.zip. (I'm not sure if there's something specific about the files in this archive, but maybe.)
2. Right-click and choose Extract Files from Archive > Here. 

**Expected behavior**
Should result in a drupal-8.9.15 folder with the files in it. This is what happens on 2.1.58 and earlier.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 93.0.4577.82

If there's more information or help I can give debugging the issue, please let me know. I'm not sure how to get more detailed debugging info about what's exactly happening here.

**Comment by nao-pon** [comment]
@zengenuity I tried it on the demo site and it worked fine except for the files that are not allowed.

It may be due to the difference in the ZIP archiver used in the back end.

What is your ZIP archiver?
