### ISSUE TITLE
Session cache used even if memory cache is configured

### ISSUE THREAD

**Issue by SamMousa** [Studio-42/elFinder#3414]
I've configured elFinder to use the memory store for caching. But in my logs I'm seeing a lot of session usage.
What's worse: elFinder opens & closes the cache constantly, meaning that the session store gets ~50 updates for no obvious reason.

The `elFinder` class has lots of hard coded references to session cache; is there any way to fully disable this?

Will `elFinder ` work if I implement a dummy `elFinderSessionInterface` that just discards all data?

**Comment by joester89** [comment]
Same problem here
