### ISSUE TITLE
Issue with saving directory history in browser for Firefox and Chrome.

### ISSUE THREAD

**Issue by devDev1922** [Studio-42/elFinder#3450]
From few days, I am getting issue with saving directory history in browser. Earlier elfinder loads the last opened directory in the browser. Now a days, when I refresh the page it list the last opened directory and after 5 seconds it reloads the elfinder to the root directory. The hash in the url changes when it automatically reloads the root directory.

**To Reproduce**
1. Navigate to the inner directories of the root directory from the elfinder GUI. You will see with each click the hash value in the url changes.
2. Open the same url without hash or reload the page. It will show the last opened directory for few seconds and then it will reload elfinder to the root directory and change the hash value in the url.

**Expected behavior**
It should load the last opened folder rather reload it to root directory.

**Desktop (please complete the following information):**
 - OS: MAC (Catalina), Windows (19042.1415) (64 bits)
 - Browser: Chrome, Firefox
 - Version : Latest version of Chrome (97.0.4692.71) and Firefox(95.0.2).

Thanks

**Comment by Nguyenhung111223355** [comment]
#3450
