### ISSUE TITLE
Problem with jquery-ui 1.13.0

### ISSUE THREAD

**Issue by gtbu** [Studio-42/elFinder#3451]
I use elfinder 2.1.59 with jquery 2.24 in Typesetter CMS with jquery ui 1.12.1.
When i changed to new jquery-ui 1.13.0 i got the error 👍 Invalid jQuery UI configuration. 
Selectable, draggable and droppable components must be included. 
The klicked page appears in blank.
(the js's are there. In the rest of the CMS jquery ui functions without errors !).

**Comment by gtbu** [comment]
With 1.13.2[ it functions now](https://github.com/gtbu/Typesetter-5.3-p8)

**Comment by stalker780** [comment]
@nao-pon 
With jQueryUI >= 1.12.0 resize/rotate dialog does not open.
I get JS error: Uncaught TypeError: can't access property "classes", s.options is undefined

Latest working jQueryUI is 1.11.4

**Comment by gtbu** [comment]
Can You please add an image of the error (firefox  Ctrl + Shift + K) so that one can see the lines where the error appears.
