### ISSUE TITLE
webp files not allowed

### ISSUE THREAD

**Issue by onderakbulut** [Studio-42/elFinder#3469]
Webp files not allowed,

connector.minimal.php I added Allowed file tyle 'image/webp' but it is not working

`'uploadAllow'   => array('image/x-ms-bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/x-icon', 'text/plain', 'audio/mpeg', 'video/mp4', 'image/webp')`

I'm using elfinder 2.1.60 version
Thanks.

**Comment by AlexJMcloud** [comment]
> Webp files not allowed,
> 
> connector.minimal.php I added Allowed file tyle 'image/webp' but it is not working
> 
> `'uploadAllow' => array('image/x-ms-bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/x-icon', 'text/plain', 'audio/mpeg', 'video/mp4', 'image/webp')`
> 
> I'm using elfinder 2.1.60 version Thanks.

I solved this problem in this version. By editing the file elFinderVolumeDriver.class.php
[elFinderVolumeDriver.class.zip](https://github.com/Studio-42/elFinder/files/9415192/elFinderVolumeDriver.class.zip)

But I have another problem: I can’t figure out how, when converting to wepb (during loading), force elfinder to change the extension to webp (that is, change the original one).

**Comment by AlexJMcloud** [comment]
I solved my problem. Now when uploading images (jpeg, png, bmp) there is a conversion to webp.

**Comment by onderakbulut** [comment]
What about would you try uploading "Avif" files

**Comment by AlexJMcloud** [comment]
> What about would you try uploading "Avif" files

As i understand it, you need to do it according to the same principle as i added webp.  Download my version and search for webp.

**Comment by AlexJMcloud** [comment]
In version 2.1.60 it is missing from mime types. Try adding it to the mime.types file
