### ISSUE TITLE
https://github.com/Studio-42/elFinder/wiki/Integration-with-CKEditor-5 404

### ISSUE THREAD

**Issue by TukuToi** [Studio-42/elFinder#3477]
** What is your document request related to? Please describe. **
https://github.com/Studio-42/elFinder/wiki/Integration-with-CKEditor-5

** Additional context **
The demo linked leads to a 404

** Anyone can create a document **
The document is already there, but the link of demo leads to a 404/

**Comment by nao-pon** [comment]
@TukuToi I fixed it!, Thanks! 👍
