### ISSUE TITLE
Convert image file to JPG, PNG, WEBP

### ISSUE THREAD

**Issue by AlexJMcloud** [Studio-42/elFinder#3507]
How can I make the elfinder plugin available in the menu and be seen by him?
I want to do the conversion of standard image formats myself. And most importantly, how do I save the transformation using the elfinder methods.
Already started writing, but stopped by the fact that I don’t quite understand how to save the result.

**Comment by AlexJMcloud** [comment]
elfinder 2.1.60
I did the conversion to webp, but how do I replace the extension on upload?

**Comment by AlexJMcloud** [comment]
Already resolved this issue.

**Comment by TranHuyQn** [comment]
@AlexJMcloud please share the solution, thank you so much!
