### ISSUE TITLE
Irregular rotation of an image in google chrome.

### ISSUE THREAD

**Issue by alexsilva** [Studio-42/elFinder#3513]
**Describe the bug**
Image rotation does not occur smoothly when clicking rotation buttons. It seems calling animate with `value + 'deg'` causes the problem (the slider doesn't have this problem).

**To Reproduce**
1. Select an image with the 'resize' plugin properly configured and activated.
2. Select the rotate and resize menu.
3. Click on the rotate menu.
4. Click the rotate 90 degrees button.
5. See error

**Expected behavior**
I expect smooth rotation between different angle -90, -180, -270 and -360 or 90, 180, 270 and 360.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [104.0.5112.102 64 bits]

**Additional context**
I already understand that the problem is in the image update function.

[resize.js#L913](https://github.com/Studio-42/elFinder/blob/master/js/commands/resize.js#L913)
```
update : function(value, animate) {
	if (typeof value == 'undefined') {
		rdegree = value = parseInt(degree.val());
	}
	if (typeof animate == 'undefined') {
		animate = true;
	}
	if (! animate || fm.UA.Opera || fm.UA.ltIE8) {
		imgr.rotate(value);
	} else {
		imgr.animate({rotate: value + 'deg'});
	}
	value = value % 360;
	if (value < 0) {
		value += 360;
	}
	degree.val(parseInt(value));

	uidegslider.slider('value', degree.val());
	
	rotate.setQuality();
}
```

See that with this small snippet of code solve the problem for me.
```
} else if (fm.UA.Chrome) {
    imgr.animate({rotate: value});
```

And the complete code with the fix.
```
update : function(value, animate) {
	if (typeof value == 'undefined') {
		rdegree = value = parseInt(degree.val());
	}
	if (typeof animate == 'undefined') {
		animate = true;
	}
	if (! animate || fm.UA.Opera || fm.UA.ltIE8) {
		imgr.rotate(value);
	} else if (fm.UA.Chrome) {
		imgr.animate({rotate: value});
	} else {
		imgr.animate({rotate: value + 'deg'});
	}
	value = value % 360;
	if (value < 0) {
		value += 360;
	}
	degree.val(parseInt(value));

	uidegslider.slider('value', degree.val());
	
	rotate.setQuality();
}
```

**Comment by nao-pon** [comment]
@alexsilva Thanks! 👍
