### ISSUE TITLE
Invalid backend response. Data is not JSON

### ISSUE THREAD

**Issue by itsjmed** [Studio-42/elFinder#3520]
Hi
elFinder js works fine but lately I got this error message 'Invalid backend response. The data is not JSON'. for 1 folder containing many subfolders and files.

It turns out that it deletes session of authentication.

I'm coding with Codeigniter as a PHP framework

any solution?

**Comment by tchau44** [comment]
> Hi elFinder js works fine but lately I got this error message 'Invalid backend response. The data is not JSON'. for 1 folder containing many subfolders and files.
> 
> It turns out that it deletes session of authentication.
> 
> I'm coding with Codeigniter as a PHP framework
> 
> any solution?

Hi @itsjmed ! Are you using ckeditor or other wysywyg ? 
I integrate with ckeditor, tinymce unsuccessfull :(
But i integrate with summernote is successfully :)

You open debug with php connector as below:
`error_reporting(1); `

And view erroro log :)
Post your errors log on this issues

**Comment by itsjmed** [comment]
Thanks for your reply @tchau44 

+error log
`client intended to send too large body: 21567804 bytes, request: "POST /projects/media_connector/ HTTP/1.1"`

**This is a capture of inspect element for browser** 

![image](https://user-images.githubusercontent.com/23057573/191070597-f93ce70e-e926-4709-908a-3e5abeb440ec.png)
