### ISSUE TITLE
Warning on SFTP connection on root dir

### ISSUE THREAD

**Issue by Nounours13** [Studio-42/elFinder#3525]
Hi at all,

I've warning message on root folder on SFTP connection :

0: "WARNING: preg_split() expects parameter 2 to be string, array given in elFinderVolumeSFTPphpseclib.class.php line 452."
1: "NOTICE: Trying to access array offset on value of type bool in elFinderVolumeSFTPphpseclib.class.php line 453."

On other folder there are no problem.
I've  make a var_dump() of $str and effectively is an array.
I think, there a the same code for FTP and SFTP but the return of rawlist is not the same result in FTP and SFTP.

On FTP connection there are no problem.

Regards ...

**Comment by sitecode** [comment]
Thanks for the details @Nounours13. This should be resolved by #3574.
