### ISSUE TITLE
enable downloading of folders

### ISSUE THREAD

**Issue by samthiriot** [Studio-42/elFinder#353]
Hi, 

if you share many small files (like music files, for instance), loading each file individually becomes untractable. 
The only solution is to create a tmp archive, then download it, then erase it. The cons of this solution are obvious: the repository has to be writable; also users often forget to delete the archive after the download.

Here is a simple proposal: enable the "download" feature for directories; in practice this feature creates a temporary archive and launches one unique download. The tmp archive is created in some temporary download and is delete as soon as possible (like, at the end of the transaction). I suppose this feature is not so costly, at is relies only on existing features (archive creation, temporary path for thumbs, download). 

Note that the same approach could be used for multiple file download, at the cost of processor consumption in the server side.

**Comment by MSDehghan** [comment]
+1. agree
