### ISSUE TITLE
Popup on search result with path / last modified date / size

### ISSUE THREAD

**Issue by Caelion** [Studio-42/elFinder#3534]
**Describe the bug**
When you make a research, if you stay on a result item, there is a popup with path / filename / last modified date / size
Currently, these 3 items are wrote without space or dash like pathlastmodifieddatesize
Moreover, a "/" is missing before the last folder and the filename found

**To Reproduce**
1. Make search
2. Place mouse on one result
3. Way for popup

**Expected behavior**
It could be <path"/"filename" - "last modified date" - " size

**Screenshots**
![2022 11 01 15_19_29](https://user-images.githubusercontent.com/48852394/199304745-dfed2507-4b55-4328-8ac7-acd2f1197821.png)

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Browser: Firefox 106.0.1
 - Version 2.1.61

Thank you for your help

**Comment by Lover7Malko** [comment]
HTML, CSS, JSON, XML
