### ISSUE TITLE
Can't download folder in PHP 8.1

### ISSUE THREAD

**Issue by marlonanjos** [Studio-42/elFinder#3543]
**Describe the bug**
If I try to download a folder in PHP 8.1, it throws an Error 500. It works fine in PHP 7.4

The problems seems to be in the function [localFileSystemSymlink](https://github.com/Studio-42/elFinder/blob/3c2cd7cdf2d267ae564a3fee098c90d8f134631a/php/elFinderVolumeLocalFileSystem.class.php#L1466)

If symlink is in disabled_functions, it throws a warning in PHP 7.4:
`PHP Warning:  symlink() has been disabled for security reasons`

In PHP 8.0/8.1 it throws a fatal error:
`PHP Fatal error:  Uncaught Error: Call to undefined function symlink()`

As noted in: https://php.watch/versions/8.0/disable_functions-redeclare

**Comment by alazareff** [comment]
Hi @marlonanjos
Did you manage to solve this problem?

**Comment by marlonanjos** [comment]
Hey @alazareff,

As a workaround you can enable the symlink function in php.ini.
