### ISSUE TITLE
PHP 8.2 Deprecation

### ISSUE THREAD

**Issue by dleffler** [Studio-42/elFinder#3546]
**Describe the bug**
Use of 'self::' in some functions is dprecated in PHP v8.2

**To Reproduce**
1. Open elFinder under PHP v8.2
2. Note the number of warning messages referencing elFinder.class.php line # 795 calling 'self'

**Expected behavior**
Should not throw messages

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 108

**Fix**
Change elFinder.class.php line # 795 to:
```
$doRegist = ($_reqCmd && in_array($_reqCmd, array_map('elFinder::getCmdOfBind', explode(' ', $cmd))));
'''
instead of currently
'''
$doRegist = ($_reqCmd && in_array($_reqCmd, array_map('self::getCmdOfBind', explode(' ', $cmd))));

**Comment by nao-pon** [comment]
I'll fix it. Thanks!
