### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by sectroyer** [Studio-42/elFinder#3571]
Hello.
I would like to report a security in elFinder but I am not sure how to do It exactly. I tried sending an email using a https://xoops.hypweb.net/ website (mentioned here https://github.com/nao-pon) but didn't get any reply. As it's serious issue I wouldn't want to post details on GitHub directly 😞 
Regards.

**Comment by nao-pon** [comment]
@sectroyer I couldn't find your email. Send me an email to hypweb+elfinder@gmail.com and let me know the title. thank you.

**Comment by sectroyer** [comment]
Thank you for fast reply I probably did something wrong using the form. I just sent an email titled "elFinder Security Issue".

**Comment by nao-pon** [comment]
It fixed with Version 2.1.62. @sectroyer Thanks! 👍
