### ISSUE TITLE
Drag&Drop Upload Issue with Firefox 

### ISSUE THREAD

**Issue by instantflorian** [Studio-42/elFinder#3575]
Drag&drop upload fails in Firefox. No file is uploaded. Tested with different file types (jpg, pdf). No special file names.
Notice: This issue does not appear with Google Chrome.

**To Reproduce**
1. Just have a browsertab open with elFinder writeable directory
2. Try to drag a file from Windows Explorer into the directory 
3. See error (i.e. see that no file has been uploaded)

**Expected behavior**
The file is uploaded

**Error message on console**
10:27:45.901 Uncaught TypeError: p.items[n] is undefined
    r https://studio-42.github.io/elFinder/demo/js/elfinder.min.js:25
    exec https://studio-42.github.io/elFinder/demo/js/elfinder.min.js:25
    exec https://studio-42.github.io/elFinder/demo/js/elfinder.min.js:10
    d https://studio-42.github.io/elFinder/demo/js/elfinder.min.js:11
    jQuery 2
elfinder.min.js:25:26654

**Desktop (please complete the following information):**
 - OS: Win 11
 - Firefox
 - Version 114.0.1

**Comment by NulledUI** [comment]
same issue, seems like bug appeared in version 2.1.62 
just checked in 2.6.61 no problem with Drag&Drop Upload in Firefox

**Comment by nao-pon** [comment]
I've reproduced this issue in Firefox 72.0b11. You may have problems with elFinder 2.1.62 and below.
I will fix this issue.

**Comment by nao-pon** [comment]
I have fixed this. Can you confirm that [NIghtly Build](https://github.com/Studio-42/elFinder/archive/2.1.zip) fixed it for you? Don't forget to refresh your browser's cache.

**Comment by instantflorian** [comment]
Thank you very much, the issue is solved and uploading works again as expected.

**Comment by NulledUI** [comment]
> I have fixed this. Can you confirm that [NIghtly Build](https://github.com/Studio-42/elFinder/archive/2.1.zip) fixed it for you? Don't forget to refresh your browser's cache.

Thanks, confirmed, issue has been resolved in commit 98d48fa

**Comment by nao-pon** [comment]
@instantflorian , @NulledUI Thanks! 👍
