### ISSUE TITLE
Readme WARNING says the latest has a serious bug and to update

### ISSUE THREAD

**Issue by JustinWebDev** [Studio-42/elFinder#3580]
**Describe the bug**
Readme WARNING says the latest has a serious bug and to update to the latest.  What?  It says that if you have 'older' than or equal to the latest version, to update.  What am I going to update to if the latest is not advisable?  Version 2.1.62 is the latest.

**To Reproduce**
1. Go to https://github.com/Studio-42/elFinder#readme
2. read the warning at the top:
 "WARNING: IF YOU HAVE OLDER (IN PARTICULAR 2.1.62 OR EARLIER) VERSIONS OF ELFINDER ON PUBLIC SERVERS, IT MAY CAUSE SERIOUS DAMAGE TO YOUR SERVER AND VISITED USER. YOU SHOULD UPDATE TO THE LATEST VERSION OR REMOVE IT FROM THE SERVER."

**Expected behavior**
Give advice that makes sense.

**Comment by nao-pon** [comment]
@JustinWebDev Thank you for pointing that out. I made a mistake with the version number and fixed it. There is no problem with the current latest version 2.1.62.
