### ISSUE TITLE
Drag and drop upload not working

### ISSUE THREAD

**Issue by DrezynSoft** [Studio-42/elFinder#3595]
**Describe the bug**
It is not possible to upload files by drag & drop function in any folder clicking option ,,Send files'' 
![obraz](https://github.com/Studio-42/elFinder/assets/14141877/77209bc1-e9b3-4516-a8b0-6e5c661bd524)

**To Reproduce**
1. Go to any folder of the userfiles directory.
2. Click on Send files.
3. Drag and drop any kind of file on the displayed rectangle for dropping.
4. See error like this (in web console):
![obraz](https://github.com/Studio-42/elFinder/assets/14141877/c03fae61-636b-4fb4-8e4f-ea700b64478a)
More info
![obraz](https://github.com/Studio-42/elFinder/assets/14141877/3349f533-121b-44d3-88a8-ad9fb25ea3e1)
 
**Expected behavior**
Files should be sent without errors and display in given folder.

**Desktop (please complete the following information):**
 - OS: W11
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0
 - Version 117

**Additional context**
I will be happy if it will be resolved. Thanks!
Worth notice that simple upload by click on button works perfect.

**Comment by phstbw** [comment]
After upgrade to 2.1.62, I notice similar issue with drag/drop. When uploading a file through "select file", it works.

Console when using the uncompressed .js-file:

Uncaught TypeError: trf.items[idx] is undefined
    dropUpload https://mysite.ch/wp-content/plugins/elfinder/js/elfinder.full.js?ver=6.3.1:35702

![grafik](https://github.com/Studio-42/elFinder/assets/72500702/4262106a-fc47-4e74-919d-59486c515648)

Any thoughts? Thank you!

**Comment by smartredsolutions** [comment]
same here - I restored dropUpload from Version 2.1.31 and it works fine - the problem only occurs on FF

**Comment by ylp-ineris** [comment]
Same problem here too. And this only seems to happen in Firefox.

**Comment by nao-pon** [comment]
I tried it on Firefox 122.0b1 and there are no problems. Could you try the [elFinder demo site](https://studio-42.github.io/elFinder/) and see if you get a similar error?

**Comment by nao-pon** [comment]
Ah, this is a similar issue to #3575. It has been fixed and will be resolved in the next version.
