### ISSUE TITLE
elFinder is very slow to load,ing too many files

### ISSUE THREAD

**Issue by AzizbekIsmoilov** [Studio-42/elFinder#3609]
elFinder is very slow when loading 280.9 GB 2094260 items (photo , videos files) when opening file manager from Digital Ocean Spaces storage.
- I am using elfinder using mihaildev\elfinder\flysystem\Volume Class
Who made such a solution?

**Comment by AzizbekIsmoilov** [comment]
**I am using Yii2 Libraries**
-https://github.com/MihailDev/yii2-elfinder

-https://github.com/MihailDev/yii2-elfinder-flysystem

-creocoder\flysystem\AwsS3Filesystem


And I use Digital Ocean Spaces with CDN enabled

![elfinder-config](https://github.com/Studio-42/elFinder/assets/76866564/96f383eb-91f2-4013-9cc5-51cfec808155)

**Comment by nao-pon** [comment]
This is by design of elFinder. There is no prospect of fixing this.
