### ISSUE TITLE
After switching to php 8.2 have folder opening problems

### ISSUE THREAD

**Issue by cavid90** [Studio-42/elFinder#3621]
**Describe the bug**
I have switched whole project to php 8.2 and now have problems with opening folder. I click to folder - sometimes it does not open, sometimes it opens but returns back to previous folder. 

**To Reproduce**
1. Create a folder
2. Click to open it
3. It will not open in most times
4. Or it will open but return to previous folder again

**Expected behavior**
It should open and stay inside that folder

**Screenshots**

**Additional context**

**Comment by cavid90** [comment]
https://github.com/Studio-42/elFinder/assets/15789051/8bf9e720-a621-4259-82b7-ef3ec7eb857f

**Comment by nao-pon** [comment]
@cavid90 I tried it with PHP 8.2.12 and there are no problems. You can check PHP errors by enabling debugging.

**Comment by vardanabhanot** [comment]
@nao-pon  @cavid90  This is a Chrome-specific issue, I have been facing it too. But have tested it on Firefox and Edge and there it works fine. My Chrome version is 120.0.6099.130 if that helps.

**Comment by cavid90** [comment]
@vardanabhanot thanks a lot. you were right. I disabled react dev tools and it works ok now
