### ISSUE TITLE
Windows write file with grant permissions after update

### ISSUE THREAD

**Issue by aktolu** [Studio-42/elFinder#3623]
**Describe the bug**
On windows, after update to 2.1.64 version uploaded images is not show thumbs when look at windows directory browsing. Elfinder write file with an grant permission. Not with thumbs, issue is only on original file.

Note: when delete file locally, it's want administrator rights

**To Reproduce**
1. Upload file
2. Look at the windows file system
3. See error

**Expected behavior**
Write files without grant permissions.

**Screenshots**
![Fc0cMC](https://github.com/Studio-42/elFinder/assets/8854485/ce5ee34a-0f23-4a47-a439-eaedc3ba543e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [Firefox
 - Version 121.0

**Additional context**
I didn't found code block of write file to folder. So, didn't fixed my problem.

**Comment by nao-pon** [comment]
I tried elFinder 2.1.64 with XAMPP for Windows 7.3.11 on Windows 10 Home 22H2, and there were no particular problems.
Has there been any change in your Windows environment?

**Comment by aktolu** [comment]
> I tried elFinder 2.1.64 with XAMPP for Windows 7.3.11 on Windows 10 Home 22H2, and there were no particular problems. Has there been any change in your Windows environment?

My php version is 8.2, maybe problem is this

**Comment by nao-pon** [comment]
I tried a new installation of XAMPP for Windows 8.2.12. There is nothing wrong with the default settings. Please check the settings in your environment.

**Comment by aktolu** [comment]
> I tried a new installation of `XAMPP for Windows 8.2.12`. There is nothing wrong with the default settings. Please check the settings in your environment.

I trying to find what is wrong on me. My PHP is not part of XAMPP.

I checked another way(intervention image save function, move_uploaded_file, file_put_contents) file write, it's writing well without grant permissions. Only elfinder have this issue.

Trash files too has same problem.

Thank you, I will let you know if I found a issue :)

**Comment by aktolu** [comment]
I found the problem. My PHP tmp path is "C:/Windows/Temp" and this is a system directory. In this directory access and delete must be pass an administrator confirm.

https://github.com/Studio-42/elFinder/blob/594a08f4b32c8ba77b1e37d92812d09339b72dfc/php/elFinderVolumeLocalFileSystem.class.php#L1069

On this line elfinder firstly copying file with copy() function. I think, this function copy file with permissions.

Solution 1 (remcommended): Change PHP tmp path.
Solution 2: Remove copy() function from /php/elFinderVolumeLocalFileSystem.class.php in _save() function.
