### ISSUE TITLE
Howto -  show notification with progress bar

### ISSUE THREAD

**Issue by wideawakening** [Studio-42/elFinder#364]
Hi there,

I need to show an elfinder notification from a custom JS but I'm not able to make it progressive.
The notification context is an upload.

My first functional approximation is:
<pre>
// start
elfInstance.notify({type : 'upload', cnt : 1});

// success
elfInstance.notify({type : 'upload', cnt : -1});
</pre>

But I want it to show the progression of the upload.
__

Reading the source code there is a hint regarding the progress
<pre>
	/**
	 * Open notification dialog 
	 * and append/update message for required notification type.
	 *
	 * @param  Object  options
	 * @example  
	 * this.notify({
	 *    type : 'copy',
	 *    msg : 'Copy files', // not required for known types @see this.notifyType
	 *    cnt : 3,
	 *    hideCnt : false, // true for not show count
	 *    progress : 10 // progress bar percents (use cnt : 0 to update progress bar)
	 * })
	 * @return elFinder
	 */
</pre>

So I tried something like
<pre>
var prog = bytesLoaded * 100 / bytesTotal;
console.log('file ' + bytesLoaded + '/' + bytesTotal + " (" + prog + ")");
 elfInstance.notify({type : 'upload', cnt: 0, progress: prog });
</pre>

But still with no success :/

Can anyone help me?  Thx in advance =)

**Comment by troex** [comment]
Closed due to inactivity
