### ISSUE TITLE
JsBin src version directly from github 2.x branch

### ISSUE THREAD

**Issue by troex** [Studio-42/elFinder#365]
subj

**Comment by nao-pon** [comment]
@troex There is my [JS Bin](http://jsbin.com/qaxebix/edit?html,output), is it answer of this issue?

**Comment by nao-pon** [comment]
**Newest nightly build files**
- js
    - //studio-42.github.io/elFinder/demo/js/elfinder.full.js or
    - //studio-42.github.io/elFinder/demo/js/elfinder.min.js
- css
    - //studio-42.github.io/elFinder/demo/css/elfinder.full.css or
    - //studio-42.github.io/elFinder/demo/css/elfinder.min.css
    - //studio-42.github.io/elFinder/demo/css/theme.css
