### ISSUE TITLE
Pass url - missing from array.

### ISSUE THREAD

**Issue by simwatts2** [Studio-42/elFinder#373]
I know this has been taken out of the connector array for security reasons. I am looking for a way of getting the requested url if a file has been clicked (not double clicked). What I am trying to accomplish is adding to the stat.js file - the href file URL as well as the file name, appended to bottom of elfinder. 

Is there a simple function that returns this. I know there are call backs for returning and adding, but is there anything simple I can add to the stat.js file.

Or can I even add back the url to the array. Are there many problems with this.

**Comment by troex** [comment]
Closed due to inactivity
