### ISSUE TITLE
Elfinder file manager cannot open in dialog mode.

### ISSUE THREAD

**Issue by tookit** [Studio-42/elFinder#395]
Hi guys,

Here is my init script , I want to open elfiner in a dialog, but it failed.

Can anyone help?

<link rel="stylesheet" type="text/css" media="screen" href="http://elrte.org/release/elrte/css/smoothness/jquery-ui-1.8.13.custom.css" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" ></script> 
<script type="text/javascript" src="http://elrte.org/release/elrte/js/jquery-ui-1.8.13.custom.min.js"></script>
<link rel="stylesheet" type="text/css" media="screen" href="css/elfinder.min.css">
<script type="text/javascript" src="js/elfinder.min.js"></script>
<script type="text/javascript">
$(function(){
    $('#select-button').click(function(){
        var f = $('<div/>').elfinder({
             url : 'php/connector.php',
           
            editorCallback : function(url) {document.getElementById('fileurl').value=url;},
            closeOnEditorCallback : function(){
			},
            docked : false,
            dialog : { title : 'Test', height: 500 },
      });

    });

});

</script>

**Comment by troex** [comment]
Closed due to inactivity
