### ISSUE TITLE
Elfinder Operation Command Strings

### ISSUE THREAD

**Issue by laupkram** [Studio-42/elFinder#400]
ok i do have this list of callbacks for my elfinder command strings shown as keys in the array below

```php
bind' => array(				
				'mkfile'=>'mkFileCallBack',
				'upload'=>'uploadFileFCallBack',
				'duplicate'=>'duplicateFileCallBack',
				'paste'=>'pasteFileCallBack',
				'rename'=>'renameFileCallBack',
				'mkdir'=>'mkdirFileCallBack',
				'mkfile upload duplicate paste rename mkdir'=>'logFileCallBack',
		)
```

now what I want to know is what are the other command strings that can I bind with..? thanks

**Comment by nao-pon** [comment]
Please read source https://github.com/Studio-42/elFinder/blob/2.x/php/elFinder.class.php .
