### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by ghost** [Studio-42/elFinder#406]
Slovak translation of elFinder:

	/**
	 * Slovak translation
	 * @author Martin Kolárik <KolarikMa@gmail.com>
	 * @version 2012-10-12 
	 */

	if (elFinder && elFinder.prototype && typeof(elFinder.prototype.i18) == 'object') {
		elFinder.prototype.i18.sk = {
			translator : 'Martin Kolárik &lt;KolarikMa@gmail.com&gt;',
			language   : 'slovenský',
			direction  : 'ltr',
			dateFormat : 'd.m.Y H:i',
			fancyDateFormat : '$1 H:i',
			messages   : {

			/********************************** errors **********************************/
			'error'                : 'Chyba',
			'errUnknown'           : 'Neznáma chyba.',
			'errUnknownCmd'        : 'Neznámy príkaz.',
			'errJqui'              : 'Nesprávna konfigurácia jQuery UI. Musia byť zahrnuté komponenty selectable, draggable a droppable.',
			'errNode'              : 'Vyžaduje sa vytvorený DOM Element.',
			'errURL'               : 'Nesprávna konfigurácia! Hodnota URL nie je nastavená.',
			'errAccess'            : 'Prístup zamietnutý.',
			'errConnect'           : 'Neviem sa pripojiť k backendu (php konektoru).',
			'errAbort'             : 'Spojenie prerušené.',
			'errTimeout'           : 'Časový limit spojenia vypršal.',
			'errNotFound'          : 'Backend (php konektor) nebol nájdený.',
			'errResponse'          : 'Nesprávna odpoveď backendu (php konektoru).',
			'errConf'              : 'Nesprávna konfigurácia backendu (php konektoru).',
			'errJSON'              : 'PHP JSON modul nie je nainštalovaný.',
			'errNoVolumes'         : 'Nie sú dostupné čitateľné odiely.',
			'errCmdParams'         : 'Nesprávny parameter pre príkaz "$1".',
			'errDataNotJSON'       : 'Dáta nie sú vo formáte JSON.',
			'errDataEmpty'         : 'Dáta sú prázdne.',
			'errCmdReq'            : 'Požiadavka backendu (php konektoru) vyžaduje názov príkazu.',
			'errOpen'              : 'Nemôžem otvoriť "$1".',
			'errNotFolder'         : 'Objekt nie je priečinok.',
			'errNotFile'           : 'Objekt nie je súbor.',
			'errRead'              : 'Nemôžem čítať "$1".',
			'errWrite'             : 'Nemôžem zapisovať do "$1".',
			'errPerm'              : 'Prístup zamietnutý',
			'errLocked'            : '"$1" je zamknutý a nemôže byť premenovaný, presunutý alebo odstránený.',
			'errExists'            : 'Súbor "$1" už existuje.',
			'errInvName'           : 'Nesprávny názov súboru.',
			'errFolderNotFound'    : 'Priečinok nenájdený.',
			'errFileNotFound'      : 'Súbor nenájdený.',
			'errTrgFolderNotFound' : 'Cieľový priečinok "$1" nenájdený.',
			'errPopup'             : 'Váš prehliadač blokuje otváranie vyskakujúcich okien. Pre otvorenie súboru ich povoľte v nastaveniach prehliadača.',
			'errMkdir'             : 'Nemôžem vytvoriť priečinok "$1".',
			'errMkfile'            : 'Nemôžem vytvoriť súbor "$1".',
			'errRename'            : 'Nemôžem premenovať "$1".',
			'errCopyFrom'          : 'Kopírovanie súborov z odielu "$1" nie je povolené.',
			'errCopyTo'            : 'Kopírovanie súborov na odiel "$1" nie je povolené.',
			'errUploadCommon'      : 'Chyba pri nahrávaní.',
			'errUpload'            : 'Nemôžem nahrať "$1".',
			'errUploadNoFiles'     : 'Nenašiel som žiadne súbory pre nahratie.',
			'errMaxSize'           : 'Dáta presahujú maximálnu povolenú veľkosť.',
			'errFileMaxSize'       : 'Dáta presahujú minimálnu povolenú veľkosť.',
			'errUploadMime'        : 'Typ súboru nie je povolený.',
			'errUploadTransfer'    : 'Chyba pri prenose "$1".', 
			'errSave'              : 'Nemôžem uložiť "$1".',
			'errCopy'              : 'Nemôžem kopírovať "$1".',
			'errMove'              : 'Nemôžem presunúť "$1".',
			'errCopyInItself'      : 'Nemôžem presunúť "$1" sám do seba.',
			'errRm'                : 'Nemôžem zmazať "$1".',
			'errExtract'           : 'Nemôžem extrahovať archív "$1".',
			'errArchive'           : 'Nemôžem vytvoriť archív.',
			'errArcType'           : 'Nepodporovaný typ archívu.',
			'errNoArchive'         : 'Súbor nie je archív alebo je typ archívu nepodporovaný.',
			'errCmdNoSupport'      : 'Backend (php konektor) nepodporuje tento príkaz.',
			'errReplByChild'       : 'Priečinok “$1” nemôže byť nahradený súborom, sám ktorý obsahuje.',
			'errArcSymlinks'       : 'Z bezpečnostných dôvodov je zakázané extrahovať archívy, ktoré obsahujú symlinky (odkazy na iné súbory).',
			'errArcMaxSize'        : 'Obsah archívu prekračuje maximálnu povolenú veľkosť.',
			'errResize'            : 'Nemôžem zmeniť veľkosť "$1".',
			'errUsupportType'      : 'Nepodporovaný typ súboru.',

			/******************************* commands names ********************************/
			'cmdarchive'   : 'Vytvoriť archív',
			'cmdback'      : 'Späť',
			'cmdcopy'      : 'Kopírovať',
			'cmdcut'       : 'Vystrihnúť',
			'cmddownload'  : 'Stiahnuť',
			'cmdduplicate' : 'Vytvoriť kópiu',
			'cmdedit'      : 'Upraviť súbor',
			'cmdextract'   : 'Extrahovať súbory',
			'cmdforward'   : 'Vpred',
			'cmdgetfile'   : 'Vybrať súbory',
			'cmdhelp'      : 'O programe',
			'cmdhome'      : 'Domov',
			'cmdinfo'      : 'Detaily',
			'cmdmkdir'     : 'Nový priečinok',
			'cmdmkfile'    : 'Nový textový súbor',
			'cmdopen'      : 'Otvoriť',
			'cmdpaste'     : 'Prilepiť',
			'cmdquicklook' : 'Náhľad',
			'cmdreload'    : 'Obnoviť',
			'cmdrename'    : 'Premenovať',
			'cmdrm'        : 'Zmazať',
			'cmdsearch'    : 'Hladať súbory',
			'cmdup'        : 'O úroveň vyššie',
			'cmdupload'    : 'Nahrať súbory',
			'cmdview'      : 'Zobraziť',
			'cmdresize'    : 'Zmeniť veľkosť',
			'cmdsort'      : 'Zoradiť',

			/*********************************** buttons ***********************************/ 
			'btnClose'  : 'Zatvoriť',
			'btnSave'   : 'Uložiť',
			'btnRm'     : 'Odstrániť',
			'btnApply'  : 'Použiť',
			'btnCancel' : 'Zrušiť',
			'btnNo'     : 'Nie',
			'btnYes'    : 'Áno',

			/******************************** notifications ********************************/
			'ntfopen'     : 'Otváram priečinok',
			'ntffile'     : 'Otváram súbor',
			'ntfreload'   : 'Obnovujem obsah',
			'ntfmkdir'    : 'Vytváram priečinok',
			'ntfmkfile'   : 'Vytváram súbor',
			'ntfrm'       : 'Mažem súbor(y)',
			'ntfcopy'     : 'Kopírujem súbor(y)',
			'ntfmove'     : 'Presúvam súbor(y)',
			'ntfprepare'  : 'Pripravujem kopírovanie súborov',
			'ntfrename'   : 'Premenúvam súbor(y)',
			'ntfupload'   : 'Nahrávam súbor(y)',
			'ntfdownload' : 'Sťahujem súbor(y)',
			'ntfsave'     : 'Ukladám súbor(y)',
			'ntfarchive'  : 'Vytváram archív',
			'ntfextract'  : 'Extrahujem archív',
			'ntfsearch'   : 'Hľadám súbory',
			'ntfsmth'     : 'Som zaneprázdnený... >_<',
			'ntfloadimg'  : 'Načítavam obrázok',

			/************************************ dates **********************************/
			'dateUnknown' : 'Neznámy',
			'Today'       : 'Dnes',
			'Yesterday'   : 'Včera',
			'Jan'         : 'Jan',
			'Feb'         : 'Feb',
			'Mar'         : 'Mar',
			'Apr'         : 'Apr',
			'May'         : 'Máj',
			'Jun'         : 'Jún',
			'Jul'         : 'Júl',
			'Aug'         : 'Aug',
			'Sep'         : 'Sep',
			'Oct'         : 'Okt',
			'Nov'         : 'Nov',
			'Dec'         : 'Dec',
			'January'     : 'Január',
			'February'    : 'Február',
			'March'       : 'Marec',
			'April'       : 'Apríl',
			'May'         : 'Máj',
			'June'        : 'Jún',
			'July'        : 'Júl',
			'August'      : 'August',
			'September'   : 'September',
			'October'     : 'Október',
			'November'    : 'November',
			'December'    : 'December',
			'Sunday'      : 'Nedeľa', 
			'Monday'      : 'Pondelok', 
			'Tuesday'     : 'Utorok', 
			'Wednesday'   : 'Streda', 
			'Thursday'    : 'Štvrtok', 
			'Friday'      : 'Piatok', 
			'Saturday'    : 'Sobota',
			'Sun'         : 'Ned', 
			'Mon'         : 'Pon', 
			'Tue'         : 'Uto', 
			'Wed'         : 'Str', 
			'Thu'         : 'Štv', 
			'Fri'         : 'Pia', 
			'Sat'         : 'Sob',

			/******************************** sort variants ********************************/
			'sortnameDirsFirst' : 'podľa názvu (priečinky prvé)', 
			'sortkindDirsFirst' : 'podľa typu (priečinky prvé)', 
			'sortsizeDirsFirst' : 'podľa veľkosti (priečinky prvé)', 
			'sortdateDirsFirst' : 'podľa dátumu (priečinky prvé)', 
			'sortname'          : 'podľa názvu', 
			'sortkind'          : 'podľa typu', 
			'sortsize'          : 'podľa veľkosti',
			'sortdate'          : 'podľa dátumu',

			/********************************** messages **********************************/
			'confirmReq'      : 'Požadujem potvrdenie.',
			'confirmRm'       : 'Ste si istý, že mám zmazať tento súbor(y)?<br/>Táto akcia nemôže byť vrátená!',
			'confirmRepl'     : 'Nahradiť starší súbor novým?',
			'apllyAll'        : 'Použiť na všetky.',
			'name'            : 'Názov',
			'size'            : 'Veľkosť',
			'perms'           : 'Oprávnenia',
			'modify'          : 'Upravený',
			'kind'            : 'Typ',
			'read'            : 'čítanie',
			'write'           : 'zápis',
			'noaccess'        : 'prístup zamietnutý',
			'and'             : 'a',
			'unknown'         : 'neznámy',
			'selectall'       : 'Vybrať všetky súbory',
			'selectfiles'     : 'Vybrať súbory',
			'selectffile'     : 'Vybrať prvý súbor',
			'selectlfile'     : 'Vybrať posledný súbor',
			'viewlist'        : 'Zobraziť zoznam',
			'viewicons'       : 'Zobraziť ikony',
			'places'          : 'Miesta',
			'calc'            : 'Vypočítať', 
			'path'            : 'Cesta',
			'aliasfor'        : 'Odkaz na',
			'locked'          : 'Zamknutý',
			'dim'             : 'Rozmery',
			'files'           : 'Súbory',
			'folders'         : 'Priečinky',
			'items'           : 'Položky',
			'yes'             : 'áno',
			'no'              : 'nie',
			'link'            : 'Odkaz',
			'searcresult'     : 'Výsledky hľadania',  
			'selected'        : 'Vybrané položky',
			'about'           : 'O',
			'shortcuts'       : 'Odkazy',
			'help'            : 'Nápoveda',
			'webfm'           : 'Webový správca súborov',
			'ver'             : 'Verzia',
			'protocol'        : 'verzia protokolu',
			'homepage'        : 'Domovská stránka',
			'docs'            : 'Dokumentácia',
			'github'          : 'Navštívte nás na Githube',
			'twitter'         : 'Stedujte nás na Twitteri',
			'facebook'        : 'Stedujte nás na Facebooku',
			'team'            : 'Tým',
			'chiefdev'        : 'šéf vývojárov',
			'developer'       : 'vývojár',
			'contributor'     : 'spolupracovník',
			'maintainer'      : 'údržbár',
			'translator'      : 'prekladateľ',
			'icons'           : 'Ikony',
			'dontforget'      : 'and don\'t forget to take your towel',
			'shortcutsof'     : 'Odkazy nie sú povolené',
			'dropFiles'       : 'Potiahnite súbory sem',
			'or'              : 'alebo',
			'selectForUpload' : 'Vyberte súbory na nahratie',
			'moveFiles'       : 'Presunúť súbory',
			'copyFiles'       : 'Kopírovať',
			'rmFromPlaces'    : 'Odstrániť z miest',
			'untitled folder' : 'Nový priečinok',
			'untitled file.txt' : 'Nový súbor.txt',
			'aspectRatio'     : 'Pomer strán',
			'scale'           : 'Mierka',
			'width'           : 'Šírka',
			'height'          : 'Výška',
			'mode'            : 'Mód',
			'resize'          : 'Zmeniť veľkosť',
			'crop'            : 'Orezať',
			'rotate'          : 'Otočiť',
			'rotate-cw'       : 'Otočiť o 90 stupňov +',
			'rotate-ccw'      : 'Otočiť o 90 stupňov -',
			'degree'          : 'Stupňov',

			/********************************** mimetypes **********************************/
			'kindUnknown'     : 'Neznámy',
			'kindFolder'      : 'Priečinok',
			'kindAlias'       : 'Odkaz',
			'kindAliasBroken' : 'Neplatný odkaz',
			'kindApp'         : 'Aplikácia',
			'kindPostscript'  : 'Postscript dokument',
			'kindMsOffice'    : 'Dokument Microsoft Office',
			'kindMsWord'      : 'Dokument Microsoft Word',
			'kindMsExcel'     : 'Tabuľka Microsoft Excel',
			'kindMsPP'        : 'Prezentácia Microsoft Powerpoint',
			'kindOO'          : 'Dokument Open Office',
			'kindAppFlash'    : 'Flash aplikácia',
			'kindPDF'         : 'Dokument PDF',
			'kindTorrent'     : 'Súbor Bittorennt',
			'kind7z'          : '7z archív',
			'kindTAR'         : 'TAR archív',
			'kindGZIP'        : 'GZIP archív',
			'kindBZIP'        : 'BZIP archív',
			'kindZIP'         : 'ZIP archív',
			'kindRAR'         : 'RAR archív',
			'kindJAR'         : 'Java aplikácia',
			'kindTTF'         : 'True Type font',
			'kindOTF'         : 'Open Type font',
			'kindRPM'         : 'RPM balík',
			'kindText'        : 'Textový dokument',
			'kindTextPlain'   : 'Neformátovaný text',
			'kindPHP'         : 'PHP skript',
			'kindCSS'         : 'CSS štýly',
			'kindHTML'        : 'HTML dokument',
			'kindJS'          : 'Javascript',
			'kindRTF'         : 'Rich Text Format',
			'kindC'           : 'Zdrojový kód C',
			'kindCHeader'     : 'Hlavička C',
			'kindCPP'         : 'Zdrojový kód C++',
			'kindCPPHeader'   : 'Hlavička C++',
			'kindShell'       : 'Unix shell script',
			'kindPython'      : 'Zdrojový kód Python',
			'kindJava'        : 'Zdrojový kód Java',
			'kindRuby'        : 'Zdrojový kód Ruby',
			'kindPerl'        : 'Perl skript',
			'kindSQL'         : 'Zdrojový kód SQL',
			'kindXML'         : 'XML dokument',
			'kindAWK'         : 'Zdrojový kód AWK',
			'kindCSV'         : 'CSV dokument',
			'kindDOCBOOK'     : 'Docbook XML dokument',
			'kindImage'       : 'Obrázok',
			'kindBMP'         : 'Obrázok BMP',
			'kindJPEG'        : 'Obrázok JPEG',
			'kindGIF'         : 'Obrázok GIF',
			'kindPNG'         : 'Obrázok PNG',
			'kindTIFF'        : 'Obrázok TIFF',
			'kindTGA'         : 'Obrázok TGA',
			'kindPSD'         : 'Obrázok Adobe Photoshop',
			'kindXBITMAP'     : 'Obrázok X bitmap',
			'kindPXM'         : 'Obrázok Pixelmator',
			'kindAudio'       : 'Audio súbor',
			'kindAudioMPEG'   : 'MPEG audio',
			'kindAudioMPEG4'  : 'MPEG-4 audio',
			'kindAudioMIDI'   : 'MIDI audio',
			'kindAudioOGG'    : 'Ogg Vorbis audio',
			'kindAudioWAV'    : 'WAV audio',
			'AudioPlaylist'   : 'MP3 playlist',
			'kindVideo'       : 'Video súbor',
			'kindVideoDV'     : 'DV video',
			'kindVideoMPEG'   : 'MPEG video',
			'kindVideoMPEG4'  : 'MPEG-4 video',
			'kindVideoAVI'    : 'AVI video',
			'kindVideoMOV'    : 'Quick Time video',
			'kindVideoWM'     : 'Windows Media video',
			'kindVideoFlash'  : 'Flash video',
			'kindVideoMKV'    : 'Matroska video',
			'kindVideoOGG'    : 'Ogg video'
		}
	}
}

**Comment by troex** [comment]
already added as https://github.com/Studio-42/elFinder/blob/master/js/i18n/elfinder.sk.js
