### ISSUE TITLE
Invalid backend response. Data is empty.

### ISSUE THREAD

**Issue by subzeta** [Studio-42/elFinder#423]
Hi,

I'm having a problem that I can't resolve. My directories are like this:

clientes/demo/ficheros/carpetaCliente1
main/
    connector.php

On connector.php file I have this:

$opts = array(
	'roots' => array(
		array(
			'driver'		=> 'LocalFileSystem',
			'mimeDetect' 	=> 'internal',
			'accessControl'	=> 'access',
			'separator'		=> '/',
			'path'			=> '../clientes/demo/ficheros/carpetaCliente1'
		)
	)
);

And the error I'm getting is "Invalid backend response. Data is empty". I've tried everything: putting an absolute path, using dirname(__FILE__)... I can't get it running and I don't know why. This configuration is working in Windows xampp install but not on my Linux shared hosting. Any ideas?

Thanks, I'll really apreciate that you help,

**Comment by RahulSinghChouhan** [comment]
I want to change the access level by different user.
If admin login then he/she should have all the permission
if user logs in the data can be viewed or downloaded only?
any idea how to do that?
