### ISSUE TITLE
Disabling Toolbar Options?

### ISSUE THREAD

**Issue by kriscons** [Studio-42/elFinder#424]
Hi

Is it possible to show and hide (essentially configure) the tool bar icons and prevent file uploading/deleting options?

I would love to use this to allow an Admin to upload/delete and a normal user to only view the files.

Just wondered if there was a file I could manipulate to show/hide the features?

Thanks and great work!

**Comment by willamaya** [comment]
Hello rishijag, is so easy : search file elFinder.min.js   js/elFinder.min.js    and search in the file 

uiOptions:{toolbar:[["back","forward"],["netmount"],["mkdir","mkfile","upload"],["open","download","getfile"],["info"],["quicklook"],["copy","cut","paste"],["rm"],["duplicate","rename","edit","resize"],["extract","archive"],["search"],["view","sort"],["help"]]

and you choose the option that you need in toolbar and deletes the others

**Comment by nao-pon** [comment]
elFinder 2.1+  works with connector option 'disabled'.

**Comment by buckett** [comment]
The disabled option is in the wiki under open: https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#open

**Comment by paulcanning** [comment]
Whats the difference between the ui options `download` and `getfile` ?

**Comment by BobRay** [comment]
The disabled option hides the upload icon for me , but it doesn't prevent uploading via Ctrl-U.

**Comment by nao-pon** [comment]
@kriscons I made new issue(#1842). Thanks!

**Comment by rishiVickey** [comment]
@ChuckNorrison  my right click context menu is only half visible in the bottom of the page. is there any options to align that.
I attached a image below.
![image](https://user-images.githubusercontent.com/74145816/154660030-55976999-6cc8-41c5-9532-d9dae99e282c.png)

**Comment by rishiVickey** [comment]
@nao-pon  can you help me fix the issue mentioned above

**Comment by ChuckNorrison** [comment]
> @ChuckNorrison my right click context menu is only half visible in the bottom of the page. is there any options to align that. I attached a image below. ![image](https://user-images.githubusercontent.com/74145816/154660030-55976999-6cc8-41c5-9532-d9dae99e282c.png)

Hey, its 9 years ago i participated on this project. i dont have an environment with elfinder running. Maybe you can do the trick by tweaking the css. Maybe you can test add a margin-bottom: 50px or something like this to solve the issue.

https://github.com/Studio-42/elFinder/blob/master/css/contextmenu.css

**Comment by rishiVickey** [comment]
@ChuckNorrison  it got resolved. Thanks for the help.
