### ISSUE TITLE
can't down large file

### ISSUE THREAD

**Issue by enlangs** [Studio-42/elFinder#467]
[Sat Jan 12 09:56:57 2013] [error] [client 10.0.16.182] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2757693441 bytes) in /opt/app/elfinder-2.0-rc1/php/elFinderConnector.class.php on line 118, referer: http://10.0.16.163/

then
modify /etc/php.ini  
memory_limit = 3072M

elfFinder nothing to do.

if open it, i can download.

**Comment by nao-pon** [comment]
May be fixed at 2334de1e4379c3ce8f0c954b38f2f31d90d89c45
