### ISSUE TITLE
Getting "TypeError: a.browser is undefined" when using jquery-1.9.0 and jquery-ui-1.9.2

### ISSUE THREAD

**Issue by grumpydeveloper** [Studio-42/elFinder#469]
Hi there,
I am trying to implement elfinder with latest version of jquery and jquery ui but I am getting this error "TypeError: a.browser is undefined". Any help would be really appreciated. 

Thanks 

![erro](https://f.cloud.github.com/assets/2719279/69476/76b8d612-5f5e-11e2-9423-635838c99826.JPG)

**Comment by ashvinimarwal** [comment]
Thank you nao-pon

It's working for me also :)
