### ISSUE TITLE
Support Apache XSendFile module

### ISSUE THREAD

**Issue by joomalungma** [Studio-42/elFinder#475]
It's like an enhancemet. When I start to use you elFinder with big files there appeared some problems with download of big files. I've started to research it and find for my Apache configuration solution with XSendFile module. It' really easy to install and use. So I suggest to add in the root option another one like Use XSendFile (true, false)
I just add 
```php
if ($download) array_unshift ($result['header'],'X-Sendfile:' . $volume->realpath($target));
```

before return result in the elFinder,class,php   method File.

Thanks again for your product,
Nikita

**Comment by geekmug** [comment]
elFinder works great for uploading multi-gigabyte files, but fails miserably (on my default setup) to allow me to download them. From experience with [simogeo/Filemanager](https://github.com/simogeo/Filemanager), I know that using X-SendFile works to support my use.

What was the reason for rejecting this? I can't see an obvious reason for LocalFileSystem to not have an option this type of acceleration module. I'd be willing to contribute a patch if I though it would be accepted.

**Comment by nao-pon** [comment]
@geekmug Thank you for your reply.  I am interested in your patch. Please send us a pull request to determine if we should accept your patch. However, it is also essential to take measures against environments that do not have X-Sendfile and also the HTTP range request.
