### ISSUE TITLE
Use FTP Driver for Download Files

### ISSUE THREAD

**Issue by ChuckNorrison** [Studio-42/elFinder#477]
Hey Guys,

if iam downloading files and check my FTP console, there is nothing happen. My Problem with this is the Windows FIlesystem Problems to workaround with the FTP driver. The download Buttons in Toolbar and contextmenue give me the failure from my Issue posted in #446.

Iam confused, cause with double click on files the Problem dont exists and download works great, also for unicode filenames and path. So i disabled the download buttons as workaround.

Can you check the reason, FTP is only used for uploading files and for navigate folders (MLST) ?

**Comment by nao-pon** [comment]
It is probably fixed in elFinder 2.1.
