### ISSUE TITLE
missing X-Requested-With header

### ISSUE THREAD

**Issue by grikdotnet** [Studio-42/elFinder#484]
When uploading a file ElFinder does not provide the X-Requested-With header. 
This leads to adding a non-JSON debug information to the response.
Is it possible to add an option to add this request header to a request?

**Comment by davo3** [comment]
here is the way of doing that
https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#customHeaders

**Comment by barryvdh** [comment]
The X-Request-With header is common for Ajax requests, but the actual response type should be decided based on the Accept header. If you want JSON back, the `Accept` header should be `application/json` right? Perhaps that would be a good default.

**Comment by troex** [comment]
`customHeaders` is a way to go, `X-Requested-With` is non-standard header I don't see any reason to add it as default
