### ISSUE TITLE
bind before rename

### ISSUE THREAD

**Issue by celevra** [Studio-42/elFinder#495]
Hi,

i need a binde before rename, because i index all the files in elfinder. If a complete folder get renamed, i get only the folder and not the files included, so it is not possible to delete them from the index and add them with the new location.
is there a way i can manage this?

best regards

**Comment by nao-pon** [comment]
elFinder 2.1+ can be bind on before any command from . For example, [Plugin Sanitizer](https://github.com/Studio-42/elFinder/blob/2.x/php/plugins/Sanitizer/plugin.php) .
