### ISSUE TITLE
Setting JPG compression before save (resize, crop, rotate) in GD

### ISSUE THREAD

**Issue by santaclaus21** [Studio-42/elFinder#498]
There should be easy way to set jpeg compression by user in case of resize, crop and maybe rotate (last one is up to implemetation method). Sometimes files are too big or looking bad up to compression level.

It can be done simple in case of PHP GD - one additional param.

I don't know about png or gif - adobe photoshop allow to define colorspace... I'm not sure if in GD is it possible.

**Comment by troex** [comment]
Closed due to inactivity
