### ISSUE TITLE
elFinder Drag-and-Drop does not work in IE9/IE11

### ISSUE THREAD

**Issue by programmeraren** [Studio-42/elFinder#500]
I am very impressed with elFinder and I think it is brilliant!!

Unfortunately drag'n'drop file(s) into the window does not work in IE9! I've tried it locally and with the http://elfinder.org/ demo using a couple of browsers. IE9 does not indicate that the file can be dropped in the file window as the other browsers does. The file can simply not be dropped in the IE9 window.

Tested NOT OK with IE9 (version 9.0.8112.16421).

Tested OK with Googe Chrome (version 24.0.1312.57 m) and Firefox (version 18.0.1).

**Comment by BasVanDerHeijden** [comment]
The same counts for IE11 btw. It would be nice to have support for the newer versions of IE for drag and drop.

**Comment by troex** [comment]
Can some test it with current version at http://studio-42.github.io/elFinder/ ?

**Comment by nao-pon** [comment]
- [x] IE11 (11.0.9600.18282) / Windows 7 64bit - Work fine

**Comment by nao-pon** [comment]
elFinder dose not support DnD upload on IE < 11.
