### ISSUE TITLE
unable to download large files

### ISSUE THREAD

**Issue by CR34L** [Studio-42/elFinder#512]
Hi all,

I'am not able to download larger files (more than 8MByte) via browser. I increased the php ini values:

post_max_size = 64M
upload_max_filesize = 64M

both vars changed in php.ini and .htaccess. 

phpinfo() output is: 
post_max_size	64M
upload_max_filesize	64M

but still nothing changed. Any ideas? File downloads of smaller files is possible without any issues.

cheers.

////// my config //////

Linux 2.6.18-028stab092.1 #1 SMP Wed Jul 20 19:47:12 MSD 2011 x86_64
PHP Version	5.3.2-1ubuntu4.18

/// the files I want to offer are about 10 ---> 30MByte.

**Comment by nao-pon** [comment]
May be fixed by db0ebff2c7753996f44dfb07e060f71f5dbe132e (require `allow_url_fopen` is `on`).
