### ISSUE TITLE
Root folder max size

### ISSUE THREAD

**Issue by D-Ne0** [Studio-42/elFinder#548]
Hi guys,

I want to know if there is a way to set max size of root folder. Say I want to set it to 10 MB, then sum of size of all files inside should not exceed that limit(10 MB).

**Comment by camgullo** [comment]
@D-Ne0 I see you are still active on github, 
I am trying to use your if condition but everytime I enter a value eg. 50M 50K or 5G I get error 

"Invalid backend response.
Error occurred on the server side.
HTTP error 500"

If I enter just a number the error will go away but the if condition won't do anything. 
Hopefully you remember why values to used.

Thanks,
Cam

**Comment by mlewis-everley** [comment]
Just run into this issue, I was able to solve it using @D-Ne0 's suggestion. You need to create a new elFinderVolume and overwrite the `upload` method. For example:

```php
class elFinderVolumeCustomLocalFileSystem extends elFinderVolumeLocalFileSystem
{
    public function upload($fp, $dst, $name, $tmpname, $hashes = array())
    {
        // My code goes here

        return parent::upload($fp, $dst, $name, $tmpname, $hashes);
    }
}
```

Then register the driver in your connector:

```php
$opts = array(
    'roots' => array(
        array(
            'driver' => 'CustomLocalFileSystem', // ' elFinderVolume' is automatically removed
            // Other options go here
        )
    )
);
```

Hope this helps if anyone else stumbles on this issue...
