### ISSUE TITLE
Callback to manipulate input file name

### ISSUE THREAD

**Issue by jjz0393** [Studio-42/elFinder#558]
![elfinder](https://f.cloud.github.com/assets/4109150/359701/e5ade2f2-a16b-11e2-84d0-54c49e7dc793.png)
I'm sure there has to be a way to do this but I'm simply trying to run a regexp against the input file if user renames or uploads a file. I see the acceptedName callback but that only dictates whether it's allowed or not; what i'd like to do is allow the file but first strip out the characters I don't want. 

I modified the volume driver to do that on the backend but when I try to rename through the frontend it says unable to rename file and then refreshes the list with the new file name there anyway (because it did in fact rename the file on the backend, so when it re-runs "open" to refresh the directory, it shows that newly renamed file.. Let me know if that makes sense; see image attachment

**Comment by nao-pon** [comment]
Please use plugin 'Sanitizer' of elFinder 2.1. 

- https://github.com/Studio-42/elFinder/blob/2.x/php/plugins/Sanitizer/plugin.php
