### ISSUE TITLE
Custom columns in "list" view

### ISSUE THREAD

**Issue by anwfr** [Studio-42/elFinder#559]
Hi,

I'd like to use elFinder for a new project but I'm stuck on issue #131 (customize displayed columns of list view).
Columns are still hardcoded in 2.0 in file cwd.js in "template['list']" variable. Do you have any hint about how to override it properly? The idea is to add a new column with custom file info.

Many thanks

**Comment by nao-pon** [comment]
It was on branch 2.1  (#559)
