### ISSUE TITLE
Drag and drop folder upload not working on Linux client

### ISSUE THREAD

**Issue by nicja** [Studio-42/elFinder#568]
I have a problem when trying to upload a folder via drag and drop on linux clients. I've noticed this occurs on the demo site elfinder.org also.

Repro:
* Right click on a blank area in a folder you have permissions to write to.
* Select upload files
* Drag and drop a folder from nautilus into the upload area

Expected:
* Folder is uploaded

Actual
* In firefox I get a "could not connect to backend" error and an aborted POST to connector.php with an empty response.
* In Chrome I get no error and a pending POST to connector.php which never ends.

This was tested on firefox and chrome, ubuntu linux

**Comment by troex** [comment]
Closed due to inactivity
