### ISSUE TITLE
large file upload issue

### ISSUE THREAD

**Issue by neerajjoshi** [Studio-42/elFinder#581]
Hello team,

I am trying to upload files of large size 50 mb to upload through el finder but it gives me error unable to upload file . I have set my file upload limit and post max size to 1024.

Please help as it really needed.

**Comment by shahrachna13** [comment]
I have done changes in php.ini file.
set 512MB as upload_max_filesize
 I have confirmed it by phpinfo() and echo ini_get('upload_max_filesize').

still I can not upload more then 15MB

**Comment by ChuckNorrison** [comment]
i have opened the limit in my iis to max of 4,7 GB works fine

**Comment by nao-pon** [comment]
Please check `post_max_size` too.
And, elFinder 2.1 support chunked file uploding. elFinder 2.1+ doesn't have restrictions of php.ini.
