### ISSUE TITLE
Rename files befor upload them

### ISSUE THREAD

**Issue by D3vm4n** [Studio-42/elFinder#616]
Hi,

is it some how possible to manipulate the fyles befor uploading them?

like rename them or something?

regrads
 Tom

**Comment by nao-pon** [comment]
On elFinder 2.1+, you can use plugins [Sanitizer](https://github.com/Studio-42/elFinder/blob/2.x/php/plugins/Sanitizer/plugin.php) or [Normalizer](https://github.com/Studio-42/elFinder/blob/2.x/php/plugins/Normalizer/plugin.php) .
