### ISSUE TITLE
elfinder.bind is not a function

### ISSUE THREAD

**Issue by D3vm4n** [Studio-42/elFinder#627]
$(function() {
var elfinder = $("#elfinder").elfinder({
lang: "de",
url : "/inc/lib/elFinder/php/connector.php",
customData: { set_driver:"Oracle" ,uid : "51cc333500ec1", f_name : "communication_id", f_value : "244"},
uiOptions: {
toolbar : [
["open" ,"back" , "forward" ,"mkdir", "upload"],
["info" ,"quicklook"],
["reload", "cut", "paste", "home" ,"view" ,"rm"],
["search"]
]
},
contextmenu: {
navbar : ["open", "|", "cut", "paste", "|", "rm", "|", "info"],
cwd : ["reload", "back", "|", "upload", "mkdir", "paste", "|", "info"],
files : 
["getfile", "|","open", "quicklook", "|", "download", "|",  "cut", "paste", "|",
"rm",  "|", "info" ],
}
}).elfinder("instance");
});
</script>
<div id="elfinder"></div>

	$(document).ready(function() {
		console.log(elfinder);
		elfinder.bind('upload', function(event) {alert('test');});
	});

the elfinder is inited abd after that i try to do a bind but i get the error message in firebug that elfinder.bind is not a function. Any suggestions? Thx.

regrads,
Tom

**Comment by nao-pon** [comment]
example:
```javascript
$(document).ready(function() {
    var elfinder = $('#elfinder').elfinder('instance');
    console.log(elfinder);
    elfinder.bind('upload', function(event) {alert('test');});
});
```
