### ISSUE TITLE
node.js backend?

### ISSUE THREAD

**Issue by carlituxman** [Studio-42/elFinder#634]
Hi, know any project to do the backend tu upload files to node.js ??

**Comment by jdnichollsc** [comment]
+1

**Comment by troex** [comment]
there is something https://github.com/sax1johno/node-elfinder not sure it works

**Comment by matankadosh-softangible** [comment]
@troex the module you referenced is not implements at all,
all they did was just to copy the php connector without even implementing it in node.js.

Would very appriciate to have an update on that.
With the uprising on nodeJS it becomes a much more required connector

**Comment by nao-pon** [comment]
See #1382.

**Comment by jdnichollsc** [comment]
Check other option https://github.com/jdnichollsc/Roxy-Fileman-for-Node.js
