### ISSUE TITLE
error occurred when cut and paste

### ISSUE THREAD

**Issue by sherry1026** [Studio-42/elFinder#636]
http://elfinder.org/, cut a file first and then paste it on local directory, An error occurred as follow:

![qq20130706134908](https://f.cloud.github.com/assets/4559743/756294/3fe401f6-e600-11e2-86d9-1acd81079d01.png)

Can you tell me ow to resolve this problem, Thank you!

**Comment by troex** [comment]
this is fixed now, it will append " 1".. " 2" and so on
