### ISSUE TITLE
FTP file list doesn't work

### ISSUE THREAD

**Issue by tobiascapin** [Studio-42/elFinder#644]
I found a little bug for a elFinderVolumeFTP.
When I access to a Filezilla server (windows) connector could list all files (I saw them in json answer using firebug) but the browser did not show them.

After a little debug I found the problem was on "phash" value of files list due to the difference between hash of "/" value of the root and the hash of "\" value of the dirname function of root's folders.

Example:
/ (root: hash with "/" value)
/test (folder, phash with dirname("/test")="\" value)

My workaround was to change the _dirname function of elFinderVolumeFTP.calss.php to this:

	protected function _dirname($path) {
		if(dirname($path)=="\\") return "/";
		return dirname($path);
	}

**Comment by troex** [comment]
not sure if this is still an issue, feel free to reopen it
