### ISSUE TITLE
Filter files in a folder by filename (Hide All Others)

### ISSUE THREAD

**Issue by NitWitStudios** [Studio-42/elFinder#650]
I want to be able to only load/show specific files from a central folder that contains 1000's of client files.

Example: Only show John Smith's files from this list:

adam_smith_2013.png
adam_smith_2012.png
john_smith_2013.png
john_smith_2012.png
john_smith_2011.png
robert_smith_2013.png
robert_smith_2012.png
robert_smith_2011.png
robert_smith_2010.png
*Files are all located in one folder on an FTP server

Is this possible without having to dig real deep into the code?

**Comment by spike-spb** [comment]
Is it possible to do on the client side? I have 2 input fields on the form, the first is used to select a directory, and the second - to select file inside that directory. The second selector should only show *.obj files.

**Comment by troex** [comment]
It's not designed to filter files on the client side, you should do it in connector. using customData you can pass your own settings/values to connector and configure connector to filter files based on your settings.
