### ISSUE TITLE
FTP - Can't upload new file, but can do everything else

### ISSUE THREAD

**Issue by NitWitStudios** [Studio-42/elFinder#651]
So I am able to connect to FTP folders, create new folders and view/download/edit/delete existing folers/files. But I can't upload a new file.
The FTP user has permissions for everything (connecting in FileZilla allows me to create/edit/delete anything) so I know it's not that.

Any ideas?
Using pretty much the default stuff to connect to FTP. Haven't messed with any options:

        array(
	    'alias'	=> 'FTP Test',
            'driver' => 'FTP',
            'host'   => 'MY.FTP.HOST',
            'user'   => 'USER',
            'pass'   => 'PASS',
            'path'   => 'MY/FTP/PATH',
	    //'defaults' => array('read' => true, 'write' => true),
	    //'owner' => true,

		)
*Using ElFinder v2.1

**Comment by dwijonarko** [comment]
I still cannot upload new file this is my config
```
array(
            'driver' => 'FTP',
            'host'   => 'xxx.xxx.xxx.xxx',
            'user'   => 'xxxx',
            'pass'   => 'xxxxx',
            'path'   => '/public_html/_images',
            'URL'    => 'http:/xxxx',
            'tmpPath'=>'tmp',
            'accessControl' => 'access' ,
            'arc'         => '7za',
            'uploadAllow' => array('image/png', 'image/jpeg', 'image/gif', 'application/zip'), 
            'uploadDeny'  => array('all'),
            'uploadOrder' => 'deny,allow'
        )
```

the tmp directory is located on ftp server
