### ISSUE TITLE
can extract / archive supports rar?

### ISSUE THREAD

**Issue by sherry1026** [Studio-42/elFinder#661]
Hello, elfinder 2.x can supports mime of "tar gzip bzip2 zip" for extract or archive operations, can it supports rar?

![mime](https://f.cloud.github.com/assets/4559743/870841/5f5995f6-f838-11e2-8875-27e15649b214.png)

Thank you very much !

**Comment by supun151515** [comment]
Hi ChuckNorrison,
I have done as you mentioned. But still I can't see extract context when I right click on RAR archive. All other archives are working fine.
I have enabled php_rar.dll extension and it is working fine with php(5.6.3).
I am using windows 7 and Xampp.
I am kindly expecting your support,

Regards,
Supun

**Comment by ChuckNorrison** [comment]
Other archives are working? If not, you installed 7-Zip? You need the 7z.exe in your Systemroot. Further its needed to edit the right volume driver. In my Example i worked with the FTP Driver. In your case possible the localfilesystem driver.

Check if you can use 7z.exe within php.

**Comment by supun151515** [comment]
Hi Chuck Norrison,
I have done the above code and it works fine. it extracts fine and returns success result array.
I have edited the elFinderVolumeDriver.class.php
But when I right click on a file and Create Archive->Zip archive or RAR archive not working. it gives an error on console `{"error":["errArchive"]}`
All other (TAR,BZIP, GZIP, XZ,7z) are working great!
Hope you understand...
Thanks,
Supun

**Comment by troex** [comment]
maybe you can different version of rar or unrar utility installed, elFinder supports unix version of rar, for windows you might need to tweak `archivers` connector configuration options.
