### ISSUE TITLE
{"error":"Invalid command ''"}

### ISSUE THREAD

**Issue by husnainAshraf** [Studio-42/elFinder#667]
Using with ruby on rails
made my home controller and i have a function elfinder
but when in put URL in browser localhost/home/elfinder i got {"error":"Invalid command ''"} in result
ubuntu 12.04
rails 3.2.13
ruby 1.9.3

**Comment by ZIedBargaoui** [comment]
Hi Hussain,
Did you manage to solve the problem ? because I'm having the same problem in LocomotiveCMS
