### ISSUE TITLE
How to get matching thumbnails to files?

### ISSUE THREAD

**Issue by manzznam** [Studio-42/elFinder#671]
The generated thumbnails have a hashed name and not the same name as the original file.

Does anyone know how to retrieve the correct thumbnail path for a file uploaded with elfinder? In example i retrieve the filename in a other PHP script and want to retrieve the matching thumbnail in .tmb/ folder as well.
Any ideas?

**Comment by migliori** [comment]
Hi,

Andrew you saved my life.

Thanks

**Comment by andrew2221** [comment]
I'm glad it actually helped someone.. :)

**Comment by kvn-chen** [comment]
Hi 

I have replaced the return value in the function rmbname($stat) with current(explode('.', $stat['name'])).'.png', but it's still not displaying the thumbnails. 

Can anybode help me, what is missing? I can see the generate thumbnails in the hidden folder .tmb, they have the same file name as the original.

Thanks

**Comment by andrew2221** [comment]
Hi,

Can you be a bit more specific, where do you expect the thumbnails to show up? If inside elFinder itself, then it could be a folder permission problem, or php server settings (e.g. suhosin). Also, I don't know if it's a typo or not, but the function name I mentioned was "tmbname", while you wrote "rmbname". Double-check it to be sure.

**Comment by kvn-chen** [comment]
Thanks for your reply, but it has been solved by it self. Just moved it to my webhosting server and it's working there. Yea, maybe there was an permission problem by using it locally.

**Comment by andrew2221** [comment]
Great. :) Keep it up.

**Comment by donShakespeare** [comment]
>Hi. The OP's question I think is relevant to all of us, who does need to use the created thumbnails. After some digging,  ... So on behalf of everyone who needs this:

Great solution. @andrew2221 
Maybe the thinking behind the unreadable hash was/is that the thumbnails are for caching purposes strictly for use of elFinder.
If that is the case, is there a plugin to create thumbnails alongside these elFinder-own thumbnails?

But seeing that `tmb` has several settings `crop`, `size`, etc etc, it seems highly unlikely that elFinder auto-generated thumbnails was not intended to be used by users.

So, question: can @andrew2221 solution be implemented without hacking the core, since, in my setup I don't have access to the core and can't direct end-users to do the alteration?

Can this function be extended at runtime @troex ?
```
protected function tmbname($stat) {
  //return $stat['hash'].$stat['ts'].'.png';
  return current(explode('.', $stat['name'])).'.png';
}
```

I'll go try to write a plugin for this.

Thanks all.

**Comment by donShakespeare** [comment]
Ah, I found it. For anyone still interested. Toss this in your connector.
Be aware, that according to your setup, if roots or folders are sharing the same tmb folder, you will have thumbnail issues. 
That is, if **Folder A** and **Folder B** have images with the same name `mango.gif`,
and if both sharing the same tmb folder, you will see **mango.png** in both folders.

Of course you can add some hash to distinguish files. To solve the root issue (not the different folders in same root), try :
`return current(explode('.', $stat['name'])) . "_" . explode('_', $stat['hash'])[0].'.png';`

Toss this in your connector
```
class elFinderVolumeAwesomeFileSystem extends elFinderVolumeLocalFileSystem
{
    protected function tmbname($stat) {
      //return $stat['hash'].$stat['ts'].'.png'; //original
      return current(explode('.', $stat['name'])).'.png'; //according to this thread
      return current(explode('.', $stat['name'])) . "_" . explode('_', $stat['hash'])[0].'.png'; //append root id
    }
}
```

And then change
```
'driver'        => 'AwesomeFileSystem',
'path'          => '/etc/example/',
'tmbPath'    => 'whatever'
```

See https://github.com/Studio-42/elFinder/issues/1962
and
https://github.com/Studio-42/elFinder/issues/1795#issuecomment-265627105

**Comment by vahidalvandi** [comment]
thanks work fine , but have small problem after upload dont show thumb image but after refresh sub folder show thumb
