### ISSUE TITLE
where to set up uploadTotalSize? Error occurs without activation?

### ISSUE THREAD

**Issue by captan2** [Studio-42/elFinder#675]
Hi guys,

i am wondering why i get this error.
in my connector the file size limit is set to 100M.
In my PHP.ini upload limit, memory limit and post data limit is set to 100M.
My php.ini is located in the php folder of elfinder.

This error occurs when uploading multiple files.

After analyzing the code of elfinder i found the error message code ERROR_UPLOAD_TOTAL_SIZE
I cannot find any code where this is used. Anyway i am getting exactly this error.

How to set total file size limit?
Or how to de(h)activate this check?

I am thankful for every hint that brings me closer to the solution :)

code of elFinder.class.php
![error 2](https://f.cloud.github.com/assets/5365862/1067972/87e38162-13e0-11e3-83cd-cf814fac4747.png)

error message:
![error](https://f.cloud.github.com/assets/5365862/1067970/6896ed58-13e0-11e3-826d-eed520d4042f.png)

**Comment by troex** [comment]
check your `phpinfo()` for the right size of max allowed upload size.
