### ISSUE TITLE
code overlapping

### ISSUE THREAD

**Issue by bobjer** [Studio-42/elFinder#676]
in elFinderVolumeDriver.class.php  public function file() overlapping code after return

    public function file($hash) {
		$path = $this->decode($hash);
		
		return ($file = $this->stat($path)) ? $file : $this->setError(elFinder::ERROR_FILE_NOT_FOUND);
		
		if (($file = $this->stat($path)) != false) {
			if ($realpath) {
				$file['realpath'] = $path;
			}
			return $file;
		}
		return $this->setError(elFinder::ERROR_FILE_NOT_FOUND);
	}

**Comment by troex** [comment]
fixed
