### ISSUE TITLE
Android standard browser unable to download

### ISSUE THREAD

**Issue by D3vm4n** [Studio-42/elFinder#678]
Hi, i have encountered a problem , with android browser on a galaxy tablet. I cant download files. I got the download button in the toolbar but when i click it the download wint start. 

This is a problem now for me cause i made a custom button, that first makes an archive and then downloads it, works exactly the same way as a normal download but archives first. Is there any quick fix for this, or maybe some one else got this problem aswell?

regrads Tom

**Comment by nao-pon** [comment]
elFinder 2.1 dose not have problem.
