### ISSUE TITLE
Double rueqest when downloading on android device

### ISSUE THREAD

**Issue by D3vm4n** [Studio-42/elFinder#679]
Hello, when downloading on an android device thre are 2 ruequests sent.
I made a function where i use the download function, the only difference is that i first archive the directory then download. When its done i delete it.

But with the double reuqest i have the problem that 2 archives are created and only 1 deleted and 1 downloaded, so there stays always 1 on the server.

regrads Tom

**Comment by nao-pon** [comment]
elFinder 2.1.7 will have function that folders/files download as an archive file.
