### ISSUE TITLE
feature: SFTP driver

### ISSUE THREAD

**Issue by nikkas** [Studio-42/elFinder#680]
FTP sends the user-credentials NAKED on the network and anyone can see them. This is the major reason I don't use yet elFinder.
Please (to knowers) write an SFTP driver.

**Comment by mayararajesh** [comment]
warhawk3407  
Hi
I am unable to use your SFTP Driver.When i am working with it is just loading, even i not getting any error.Can u plz help me in it.

**Comment by barryvdh** [comment]
You can also use https://github.com/barryvdh/elfinder-flysystem-driver
That enables support for any Flysystem (https://github.com/thephpleague/flysystem) driver, like SFTP (https://github.com/thephpleague/flysystem-sftp)

**Comment by mayararajesh** [comment]
hi barryvdh
I am unable to use phpleague/flysystem driver beacuse i am using PHP 5.3 and also which is mandatory to use.Can u please suggest any other solution

**Comment by barryvdh** [comment]
Turn error reporting on and track the errors.

Or write your own driver.

Or convince your boss to upgrade to 5.4+, that's safer anyways ;)

**Comment by sitecode** [comment]
Checkout https://github.com/sitecode/elFinder/blob/vd-sftp/php/elFinderVolumeSFTPphpseclib.class.php
I started out with ghost's class above but ended up rewriting it all using the original elFinder FTP driver code. It's based on phpseclib v1.0.
