### ISSUE TITLE
How can I open elfinder in a new window and get selected image path from it?

### ISSUE THREAD

**Issue by proph7** [Studio-42/elFinder#687]
I want to open elfinder in a new window, like
```js
window.open('path_to_el_finder', '_blank', 'height=520,width=950')
```

And if I select some file, I want to get it in my input field.
I think it is possible, but I cannot find the solution.

**Comment by michaeljanea** [comment]
is there a way to do this using pure javascript and using jQuery?

**Comment by rickdgraaff** [comment]
Im sure there is a way to achieve this withouten any Jquery.
I dont know how because i use Jquery all the time.
I dont fancy long JavaScript codes in my projects.

**Comment by michaeljanea** [comment]
i don't think it will be a long code.. here's an example for the CKFinder

var finder = new CKFinder();
finder.callback = function(api){
	api.hideTool('f0');
	api.hideTool('f2');
};
finder.selectActionFunction = function(fileUrl){
	el.parentElement.children[0].value = fileUrl;
};
finder.popup();

**Comment by rickdgraaff** [comment]
Cool! But i still dont know how to build a modal in pure JS.
It just works with Jquery, you'll have to build it yourself.

**Comment by michaeljanea** [comment]
it will be fine if it does not using a modal.
