### ISSUE TITLE
showing error message on double request

### ISSUE THREAD

**Issue by nikolaifedorov** [Studio-42/elFinder#693]
Reproduce:
1. use elFinderSupportVer1.js as transport,
2. find folder with long loading,
3. try loading folder from item 2 (fast clicks some times on this folder)

You will see error: 
```
Unable to connect to backend.
```
In console:
```
elfinder debug: [error] [elfinder] Unable to connect to backend.
```

It is happened because transport do not sets:  'quiet' mode and 'abort' status.
see:
'quiet' mode 
https://github.com/Studio-42/elFinder/blob/2.x/js/proxy/elFinderSupportVer1.js#L49
vs
https://github.com/Studio-42/elFinder/blob/2.x/js/elFinder.js#L1002

'abort' status
https://github.com/Studio-42/elFinder/blob/2.x/js/proxy/elFinderSupportVer1.js#L117
vs
https://github.com/Studio-42/elFinder/blob/2.x/js/elFinder.js#L1003
see doc:
http://api.jquery.com/jQuery.ajax/
```
error
Type: Function( jqXHR jqXHR, String textStatus, String errorThrown )
A function to be called if the request fails.

error callback option is invoked, if the request fails. It receives the jqXHR, a string indicating the error type, and an exception object if applicable. Some built-in errors will provide a string as the exception object: "abort", "timeout", "No Transport".
```

'quiet' mode and 'abort' status used here:
https://github.com/Studio-42/elFinder/blob/2.x/js/elFinder.js#L903

I know how fix it.
in https://github.com/Studio-42/elFinder/blob/2.x/js/proxy/elFinderSupportVer1.js#L117
```
dfrd.reject(error, error['statusText']);
```
in https://github.com/Studio-42/elFinder/blob/2.x/js/proxy/elFinderSupportVer1.js#L49
```
if (xhr.state() == 'pending') {
  xhr.quiet = true;
  xhr.abort();
}
```

**Comment by nao-pon** [comment]
elFinder 1.x and 2.0.x are EOL. 
Please recheck of this issue in [elFinder 2.1 nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).
