### ISSUE TITLE
Question about removal About button with copyright notice.

### ISSUE THREAD

**Issue by kamilrafik** [Studio-42/elFinder#697]
Hello.

I sent an email from address krafik@plexisoft.com with a question about removal About button with copyright notice on it from elfinder with a purpose to use elfinder in our proprietary SaaS system. All this copyright info will be moved to some common file with names of authors of other software that we use.

My email was sent to all main contributors in elfinder project. Please, check your mailboxes for a case if my initial letter was delivered to spam folder. 

Thank you for reading this message.

**Comment by troex** [comment]
You are free to modify the source, also you can 'help' button from toolbar using client configuration option https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#uiOptions
