### ISSUE TITLE
Prevent rename a folder or delete

### ISSUE THREAD

**Issue by ghost** [Studio-42/elFinder#704]
Hello,
How to prevent the deletion of a file or a name change?
In advance thank you

**Comment by dano1066** [comment]
This isnt working for me. Renaming is disabled but it isnt working for delete. I want to disable rename and delete for all users by default. 

'disabled' 		=> array('rename', 'delete'),

**Comment by nao-pon** [comment]
@dano1066 I made mistake, `'disabled' => array('rename', 'rm')` is correct.
