### ISSUE TITLE
А где файл elfinder.min.js

### ISSUE THREAD

**Issue by porcelanosa** [Studio-42/elFinder#710]
Не могу найти в скачанном дистрибутиве файлы для подключения, 
Т.е. в примере, https://github.com/Studio-42/elFinder/wiki/Install#elfinder  указаны файлы, а в папке js их нет https://github.com/Studio-42/elFinder/tree/2.x/js

**Comment by troex** [comment]
Сменился branch, теперь
https://github.com/Studio-42/elFinder/tree/2.0
https://github.com/Studio-42/elFinder/tree/2.1
