### ISSUE TITLE
Special Characters Issues

### ISSUE THREAD

**Issue by thpaiva** [Studio-42/elFinder#719]
Hello, I've found a problem related to files directly put on the root folder wich contains special characters, they don't show, files as ágora.jpg or folders as crianças are not shown because of this problem.

Don't know if has already been solved, but I came up with a solution, so we don't need to cry anymore =)

I've made some changes in the file: elFinderConnector.class.php , so that it changes the charset to UTF-8 using php native function (utf8_encode), and that solved the problem...

I don't know if there is a better solution for this, but, anyway, there it is, I just hope it helps you guys

My code:

http://pastebin.com/PLMjCnwN

**Comment by nao-pon** [comment]
Please recheck of this issue in [elFinder 2.1 nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip). It has roots option [`encoding` & `locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding).
