### ISSUE TITLE
Security of elFinder on the http://elfinder.org/ page

### ISSUE THREAD

**Issue by philouphil** [Studio-42/elFinder#720]
Hey mister Studio-42, could you explain how you have secured your demo page ?
I also would like to allow all file types but without any troubles !

In fact I tried with uploaddeny at first but it doesn't work :

'uploadAllow'     => array(),
'uploadDeny'      => array('text/x-js', 'application/x-php', 'application/x-perl'),
'uploadOrder'     => array('deny', 'allow'),

I still can upload js or php files ...

For php I can use an .htaccess like that :

RemoveHandler .php .phtml .php3 .php4 .php5
RemoveType .php .phtml .php3 .php4 .php5
php_flag engine off

But for the others files I don't know ...

Can anyone help me to safely allow all files uploads?

Thanks a lot

**Comment by troex** [comment]
Demo page used nginx, it's easy to configure nginx to run php only on selected files e.g. connector.php. Try to google for more examples.
