### ISSUE TITLE
hi,guys? why  i can't extract files?

### ISSUE THREAD

**Issue by pyingjie** [Studio-42/elFinder#722]
i download the elFindere-2.x.zip file
![tm20131109175605](https://f.cloud.github.com/assets/5887251/1506379/92694c0a-4925-11e3-8311-b0d6a3ca7ea9.jpg)

**Comment by nao-pon** [comment]
Must be able to either of these commands are executed on the server. (Tar, zip, unzup, rar, 7z, 7za)

In or elFinder 2.1 PHP ZipArchive Class is also available.
