### ISSUE TITLE
scroller with many files

### ISSUE THREAD

**Issue by zba** [Studio-42/elFinder#73]
When there are many files, it should be possible to navigate by scroller not matter on preview state, I think there should be <div style="height:N"> placeholder where N is calculated height of catalog with files, so new files in list would appear when you scroll to their position, for example check the icons directory and try to get select files x* and z* 

По русски - идея такая - считать сколько файлов и прикидывать размер div по вертикали нужный для вмещения этих файлов, подчитывать их в соответсвии со scroll_top (какая-то такая проперти) сейчас трудно проскролить куда нить в середину списка. 
удачи!

**Comment by nao-pon** [comment]
Fixed on 2.1 at 4cc92248e46e3393fdc74d56177aee57abe9d1c2
