### ISSUE TITLE
Multiple image formats on upload

### ISSUE THREAD

**Issue by Sybio** [Studio-42/elFinder#732]
Hello,

I am wondering if it's possible to create automatically multiple image formats (like WordPress) when uploading with elFinder.

For example, when I upload "my-image.jpg", I would like to have in destination folder : 
- my-image.jpg
- my-image-600px.jpg
- my-image-300px.jpg
- ...

I searched a long time but I can't find where is the save method, where I can get the original saved image at the end of the script to reuse it, apply multiple resize and save thumbs ? Or is there a possibility to override the saving action, or something like that ?

I'm using the LocalFileSystem.
In addition, I'm working with a library based on GD so I know how to resize image, but don't know where I can do it.

Thanks for your answer.

**Comment by troex** [comment]
the right way to do this is `bind` configuration option

**Comment by nao-pon** [comment]
c.f. #1331
