### ISSUE TITLE
Chrome Office Viewer

### ISSUE THREAD

**Issue by D3vm4n** [Studio-42/elFinder#734]
Hi,

i got this lovely little extension for Chrome called Chrome Office Viewer
https://chrome.google.com/webstore/detail/chrome-office-viewer-beta/gbkeegbaiigmenfmjfclcdgdpimamgkj?hl=en

If this extension is installed u can open xls, doc, ppt in Chrome. It works fine you guys can install it and try it on elfinder site.

However it doesnt seems in my case, Could some one install it and try if it works?

**Comment by nao-pon** [comment]
elFinder 2.1 supported Google Docs Viewer - https://github.com/Studio-42/elFinder/blob/8394a1bc33f9ecb56407e780d26af610128db2ca/js/elFinder.options.js#L185-L191
