### ISSUE TITLE
cmd Shortcuts still fire when file info displayed

### ISSUE THREAD

**Issue by dleffler** [Studio-42/elFinder#736]
I've successfully implemented a variation to the with a text area in the info dialog.  However, elFinder steals all the cmd shortcuts (like space, etc...) so it's impossible to enter much text.  Perhaps I've overlooked it, but is there an api call or a short bit of code to disable cmd shortcuts?

**Comment by nao-pon** [comment]
@dleffler Perhaps, this is I think specification.
