### ISSUE TITLE
Error in duplicate via copy-paste

### ISSUE THREAD

**Issue by plashenkov** [Studio-42/elFinder#739]
Hello!

Try to copy some file(s) and paste them right here. You will get a error: "The folder “$1” can’t be replaced by an item it contains."

Strange error description, is not it?

I believed this is simply disabling duplicating files by copy-paste, but then I tried to comment out these lines:

```javascript
fparents = fm.parents(file.hash);
if ($.inArray(dst.hash, fparents) !== -1) {

	if ($.map(fparents, function(h) { var d = fm.file(h); return d.phash == dst.hash && d.name == file.name ? d : null }).length) {
		return !dfrd.reject(['errReplByChild', file.name]);
	}
}
```

The purpose of this code (if I understand right) is to prevent replacing a folder with another one which is located inside it and has the same name. I have commented these lines and have found that duplicate via copy-paste works! Just copy & paste, and files are duplicated with postfixes "copy 1".

I will try to fix this by myself, but I will be happy if someone who knows elFinder internals better will help. I suppose the point is in small detail.

**Comment by nao-pon** [comment]
elFinder 2.1+ supported this function.
