### ISSUE TITLE
Path unrecognized while accessing it online.. (Web server path problem)

### ISSUE THREAD

**Issue by manishkumar2686** [Studio-42/elFinder#742]
Language ASP.net, C#;
Web Config code: This code is working fine at my local system (at local host).
<elFinder apiVersion="2.5" localFSRootDirectoryPath="C:\MyImage\Upload" localFSThumbsDirectoryPath="C:\MyImage\Thumbs" rootDirectoryName="Image" uploadMaxSize="1000M" defaultVolumeName="LocalFileSystem" baseUrl="Upload/" baseThumbsUrl="Thumbs/" duplicateFilePattern="Copy of {0}" duplicateDirectoryPattern="Copy of {0}" thumbsSize="48,48"></elFinder>

Problem is here: Below code is not working while i am trying to use it online.
<elFinder apiVersion="2.5" localFSRootDirectoryPath="~/MyImage/Upload" localFSThumbsDirectoryPath="~/MyImage/Thumbs" rootDirectoryName="Image" uploadMaxSize="1000M" defaultVolumeName="LocalFileSystem" baseUrl="Upload/" baseThumbsUrl="Thumbs/" duplicateFilePattern="Copy of {0}" duplicateDirectoryPattern="Copy of {0}" thumbsSize="48,48"></elFinder>

Please help me & let me know how could i write an appropriate path to access it from web server.

Thanks

**Comment by nao-pon** [comment]
Here, we can not support for third-party connector.
