### ISSUE TITLE
root directory change at runtime

### ISSUE THREAD

**Issue by francescodisciascio** [Studio-42/elFinder#743]
Is it possible to change the root directory at runtime?
I'm using Grails and elfinder plugin and I need to change root directory based on the element that user is analyzing in the application.
In config.groovy I've the following:
grails.plugin.elfinder.rootDir = "${userHome}/docm_patients_doc/{patientcf}/"
where patientcf is the id of an entity in my application. When I enter into the show.gsp page of that entity, I need to replace the patientcf with the related value. How can I do it?
I've tried to modify the placeholder before the script and div that shows elfinder in gsp page, but I notice that the path is not modified. Maybe the gsp is not the place in which the placeholder can be modified...

**Comment by nao-pon** [comment]
Please dynamically change the root volume settings on the connector side.
