### ISSUE TITLE
apache/nginx php session configuration for concurrent file download

### ISSUE THREAD

**Issue by saamalik** [Studio-42/elFinder#746]
_This is not a bug. Just a query for how http://elfinder.org server is configured to support concurrent file download for the same user_

I'm running apache with basic php configuration. When attempting to download multiple files, only one file is downloaded at a time. I traced this down to the `session_start` call in _elFinder.class.php_. All concurrent requests block on `session_start` since the PHPSESSID is the same.

A simple workaround is to add `session_write_close` call which unblocks another request blocked at `session_start`. However, I don't see that in the elFinder code and I was wondering how the elFinder.org homepage is configured to allow concurrent file downloads from the same user.

**Comment by troex** [comment]
files are downloaded directly bypassing connector
