### ISSUE TITLE
Preview for pdfs and text files

### ISSUE THREAD

**Issue by francescodisciascio** [Studio-42/elFinder#748]
I need to have a preview not only for images, but also for pdfs and text files. Is it possible?
Thanks for your help

**Comment by nao-pon** [comment]
We can use Google docs online viewer with elFinder >= 2.1.9 .

**Comment by maurorsantos** [comment]
@nao-pon, can you help me with the steps to do this?
I can preview pdf, mp3, mp4 and images, but I can't preview documents like odf, doc, xls, etc...
My elFinder version is 2.1.16
