### ISSUE TITLE
download issue if Statuses Micropublisher is enabled

### ISSUE THREAD

**Issue by liaos** [Studio-42/elFinder#750]
If both elFinder and Statuses Micropublisher are enabled, then download function will stop working.

If I select a file and then click "download" icon, then nothing will happen: 

- no pop up window to browse where to save locally
- and no error message

Any way to get around this issue since we need to have Statuses Micropublisher working as well?

**Comment by nao-pon** [comment]
Please recheck of this issue in [elFinder 2.1 nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).
