### ISSUE TITLE
errUploadTotalSize error while upload files larger then 10M

### ISSUE THREAD

**Issue by ip75** [Studio-42/elFinder#753]
![image](https://f.cloud.github.com/assets/3886308/1788387/6b287c84-6927-11e3-8445-c5566f702757.png)

​#​uname -a
FreeBSD bvgm.org 9.2-STABLE FreeBSD 9.2-STABLE #109 r257837

php version 5.4.23 
json support	enabled
json version	1.2.1

php.ini
; Maximum allowed size for uploaded files.
upload_max_filesize = 300M

web daemon ​lighttpd has no limits to the size of uploaded files​

php/connector.php
        'roots' => array(
                array(
                        'driver'     => 'LocalFileSystem',
                        'path'       => '../files/',
                        'startPath'  => '../files/test/',
                        'URL'        => dirname($_SERVER['PHP_SELF']) . '/../files/',
                        // 'treeDeep'   => 3,
                        // 'alias'      => 'File system',
                        'mimeDetect' => 'internal',
                        'tmbPath'    => '.tmb',
                        'utf8fix'    => true,
                        'tmbCrop'    => false,
                        'tmbBgColor' => 'transparent',
                        'accessControl' => 'access',
                        'acceptedName'    => '/^[^\.].*$/',
                        'uploadMaxSize' => '300m',
                        // 'disabled' => array('extract', 'archive'),
                        //'tmbSize' => 128,
                        'attributes' => array(
                                array(
                                        'pattern' => '/\.js$/',
                                        'read' => true,
                                        'write' => false
                                ),
                                array(
                                        'pattern' => '/^\/icons$/',
                                        'read' => true,
                                        'write' => false
                                )
                        )
                        // 'uploadDeny' => array('application', 'text/xml')
                ),

​code in elFinderConnector.class.php​

		// telepat_mode: on
		if (!$cmd && $isPost) {
			$this->output(array('error' => $this->elFinder->error(elFinder::ERROR_UPLOAD, elFinder::ERROR_UPLOAD_TOTAL_SIZE), 'header' => 'Content-Type: text/html'));
		}
		// telepat_mode: off

​How can I solve this issue?​

**Comment by yonatanmm** [comment]
I have same problem what he have did u have solution

**Comment by ip75** [comment]
; Maximum size of POST data that PHP will accept.
; Its value may be 0 to disable the limit. It is ignored if POST data
reading
; is disabled through enable_post_data_reading.
; http://php.net/post-max-size
post_max_size = 5G

; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 5G





On Mon, Mar 23, 2015 at 3:28 PM, yonatanmm <notifications@github.com> wrote:

> I have same problem what he have did u have solution
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Studio-42/elFinder/issues/753#issuecomment-84971556>.
>



-- 
Yours sincerely,
Igor
