### ISSUE TITLE
Invalid backend response. Data is empty. (resizing picture)

### ISSUE THREAD

**Issue by ratmalwer** [Studio-42/elFinder#758]
Hi 
I have this message resizing a picture. But only on the productive server. on localhost it works perfect. 
Can someone give me a hint? (already tried to disable the following code as i read in another post: $this->_checkArchivers();).

Here the conector.php:

if ($_SERVER['SERVER_NAME'] == 'localhost') {
	$URL1 = 'http://'.$_SERVER['SERVER_NAME'] . '/cms_ml/objekte/'; 
	$path1 = '../../objekte/';
} else {
	$URL1 = 'http://'.$_SERVER['SERVER_NAME'] . '/objekte'; 
	$path1 = '../../objekte/';
}

$opts = array(
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem', 
			'path'          => $path1,     
			'URL'           => $URL1,
			'accessControl' => 'access'          
		)
	)
);

**Comment by nao-pon** [comment]
Please recheck of this issue in [elFinder 2.1 nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).
