### ISSUE TITLE
elfinder not showing images in folder or connecting with elrte

### ISSUE THREAD

**Issue by mschlosser22** [Studio-42/elFinder#766]
I have set up elfinder and elrte according to the docs but for some reason elfinder is not showing any of the files I have in the folder when I open it up via the elrte interface.  It is also not passing the image into elrte.  It is however uploading images to the folder, I just can't see this being done.

Has anyone else had this problem?

**Comment by arturmamedov** [comment]
> 
> 
> Figured it out.. path and URL must be without ending slash...

You save me the day <3 genius!
