### ISSUE TITLE
Rename on upload

### ISSUE THREAD

**Issue by Mushr0000m** [Studio-42/elFinder#767]
Hi !
I try to forbid user from using some character in file name, so I want to rename on upload and on rename so I made :

```
'bind' => array(
    'upload rename' => 'sanitizeName'
)
```

And (inspired from https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#wiki-bind) : 

``` php
public static function sanitizeName($cmd, $result, $args, $elfinder)
{
    $files = $result['added'];
    foreach ($files as $file) {
        $filename = Libraries\Helper::sanitizeFilename($file['name']);
        $arg = array('target' => $file['hash'], 'name' => $filename);
        $elfinder->exec('rename', $arg);
    }

    return true;
}
```

It works on upload but on rename I get an error "can't connect to bakend". I think something is wrong in the sanitizeName function but I don't know if there is an other way to do it "on the fly" ?

Thanks

**Comment by kopiyka** [comment]
Same problem, tried latest nightly version as well as 2.x, 2.1. My code, connector.php

function myCallback($cmd, $result, $args, $elfinder) {
	$files = $result['added'];
	foreach ($files as $i => $file) {
		$filename = $i . 'sdfdfdgdfhhh.jpg'; // just for test
		$arg = array('target' => $file['hash'], 'name' => $filename);
		$elfinder->exec('rename', $arg);
	}
	return true;
}

$opts = array(
	'bind' => array(
		'mkdir mkfile rename duplicate upload rm paste' => 'myCallback'
	),
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',
			'path'          => '../../../image/data/',
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../../../image/data/',
			'accessControl' => 'access',
			'uploadAllow' => array('image'),
			'mimeDetect' => 'internal',
			'startPath' => '../../../image/data/products/',
			'uploadOrder'=> array('allow', 'deny'),
			'fileMode' => 0644,
			'dirMode' => 0755,
			'attributes'   => array(
				array(
					'pattern' => '/.*/',
					'read'  => true,
					'write' => true,
					'locked' => true
				)
			),
		)
	)
);

$connector = new elFinderConnector(new elFinder($opts));
$connector->run();

Why does this code not work?

**Comment by kopiyka** [comment]
Ок, I found the answer
I removed 'locked' => true and now it working

**Comment by webeasystep** [comment]
@nao-pon  thanks very much code works fine but how to replace spaces with underscores ?

**Comment by nao-pon** [comment]
@webeasystep 
```php
            'targets'  => array('\\','/',':','*','?','"','<','>','|', ' '), // target chars
```

**Comment by sauerlu** [comment]
Dear sir,

I'm usingthe  Autoresize Plugin (which works fine).
Now I wanted to add the Sanitizer Plugin. After that, I got the Error: "Unable to connect to backend"

I think something in mei connector.php code is not correct. Here is my code:

...
`$opts = array(
	// 'debug' => true,
	'bind' => array(
    'mkdir.pre mkfile.pre rename.pre' => array(
            'Plugin.Sanitizer.cmdPreprocess'
        ),	
	
// plugin autoresize 	
	'upload.presave' => array(
 			'Plugin.AutoResize.onUpLoadPreSave'
			'Plugin.Sanitizer.onUpLoadPreSave'
 			)
 		),
	
 'plugin' => array(
	   'AutoResize' => array(
        'enable' => true,
        'maxWidth'  => 1200,
        'maxHeight'  => 1200,
        'quality' => 95
        ),
		
       'Sanitizer' => array(
        'enable' => true,
        'targets'  => array('\\','/',':','*','?','"','<','>','|',' '), // target chars
        'replace'  => '_'    // replace to this
        ),
				
    ),
	
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
			'path'          => JPATH_ROOT.'/'.$imagefolder,         // '../files/',         // path to files (REQUIRED)
			'URL'           => JURI::root().$imagefolder,        //dirname($_SERVER['PHP_SELF']) . '/../files/',  // URL to files (REQUIRED)
			'accessControl' => 'access',             // disable and hide dot starting files (OPTIONAL)
			'mimeDetect'    => 'mime_content_type',
			'uploadDeny'    => array('text/x-php'),
			'disabled' => array('mkfile', 'edit')
		)
	)
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();`

Thanks a lot!
F.

**Comment by nao-pon** [comment]
@sauerlu May be...
```php
    'upload.presave' => array(
            'Plugin.AutoResize.onUpLoadPreSave'
            'Plugin.Sanitizer.onUpLoadPreSave'
            )
        ),
```
TO
```php
    'upload.presave' => array(
            'Plugin.AutoResize.onUpLoadPreSave',
            'Plugin.Sanitizer.onUpLoadPreSave'
            )
        ),
```

**Comment by sauerlu** [comment]
Thank you this was the solution. Now I've only one problem to solve, when I dublicate a file **test.jpg** he renames it automaticly to **test copy 1.jpg**. How can I avoid that he uses spaces in the dublicate file name. Is it possible that he renames the copy like: **test_copy_1.jpg** or **testcopy1.jpg**.

Thanks a lot sir.
Frank

**Comment by nao-pon** [comment]
@sauerlu Please see #1505.

**Comment by sauerlu** [comment]
Thanks a lot sir!
