### ISSUE TITLE
elFinder keeps saying 'Loading' on iPad

### ISSUE THREAD

**Issue by mise070** [Studio-42/elFinder#772]
I've the latest edition of elFinder and it works fine on Windows, OSX, Surface 8.1 RT but only on the iPad it keeps saying; 'Loading', without showing any files on the server.  

In the Safari browser in OSX en on Windows this problem doesn't appear. 
Does anyone have any suggestions?

**Comment by nao-pon** [comment]
I recommend elFinder 2.1 for touch devices. Please check on elFinder 2.1 demo site with iPad.

- 2.1 demo: http://hypweb.net/elFinder-nightly/demo/2.1/
- 2.1 latest download: http://nao-pon.github.io/elFinder-nightly/latests/elfinder-2.1.zip
