### ISSUE TITLE
grails.plugin.elfinder.rootDir definition in external config file

### ISSUE THREAD

**Issue by francescodisciascio** [Studio-42/elFinder#779]
I want to define the grails.plugin.elfinder.rootDir path in an external config file.
I have developed my Grails application, and I've installed the elfinder plugin and the connector.
I've used the following in Config.groovy:

    def ENV_NAME = "PROPERTIES_PATH"
    if(!grails.config.location || !(grails.config.location instanceof List)) {
        grails.config.location = []
    }
    if(System.getenv(ENV_NAME)) {
        println "Including configuration file specified in environment: " + System.getenv(ENV_NAME);
        grails.config.location << "file:" + System.getenv(ENV_NAME)
        println(grails.config.location)

    } else if(System.getProperty(ENV_NAME)) {
        println "Including configuration file specified on command line: " + System.getProperty(ENV_NAME);
        grails.config.location << "file:" + System.getProperty(ENV_NAME)
        println(grails.config.location)

    } else {
        println "No external configuration file defined."
    }
And I've created the file appName-config.groovy, in which I have the following:
    grails.plugin.elfinder.rootDir = "/home/francesco/docm_patients_doc/{patientcf}/"

At application startup, Ive the following exception:
    grails.plugin.elfinder.rootDir is not configured
Maybe it is needed to change something in elfinder plugin connector for grails?

**Comment by troex** [comment]
not related to elfinder directly, contact grails connector author
