### ISSUE TITLE
i can add another command in the toolbar?

### ISSUE THREAD

**Issue by jcamiloaa** [Studio-42/elFinder#783]
hi,

I would like to add another command (add notes to an image) but I could not, can someone guide me? thanks 

Similar to these notes: 

http://www.ajaxshake.com/plugin/ES/555/4bc356e9/agregar-notas-a-cualquier-imagen-en-tu-sitio-web-o-blog-jquery-notes.html 

Thanks for your time, 
best regards.

**Comment by troex** [comment]
https://github.com/Studio-42/elFinder/wiki/Custom-context-menu-command
