### ISSUE TITLE
"Select file" option does not appear on the server

### ISSUE THREAD

**Issue by bilssam** [Studio-42/elFinder#786]
I installed Drupal elfinder 7.x-0.8 module with elfinder 1.2 librarie. It's work perfect on localhost but when i moved to online server the "Select file" does not appear (disappeared) both from top menu icons and from contextmenu that appears when right-clicking on a file. I can tell you that in the "Get Info" option of a file the URL path is correct, the file permissions are 777 and all other options work properly.

**Comment by nao-pon** [comment]
elFinder 1.x & 2.0 is EOL. Please use 2.1.x .
