### ISSUE TITLE
Resize image not working

### ISSUE THREAD

**Issue by viap** [Studio-42/elFinder#812]
When i try to chage image size i receive error: errCmdParams, because script send request for resize image without "w" and "h" params.

In HTML resize type buttons doesn't have value, values reset on line:
uitype.buttonset();

I use elfinder 2.1 version, it conflict with bootstrap.js.

**Comment by tofeeq** [comment]
you just need to set the default option for re size

change code 

save = function() {
						var w, h, x, y, d;
						var mode = $('input:checked', uitype).val();

to 

save = function() {
						var w, h, x, y, d;
						var mode = $('input:checked', uitype).val() || 'resize';

on line 10788 onwards
