### ISSUE TITLE
Change root directory MySQL

### ISSUE THREAD

**Issue by christophevond** [Studio-42/elFinder#813]
If you change the path from 1 to anything else for the root, it starts a loop and goes back to tying to use one. Unless I am missing something, it would be nice to have one table and select different roots for different projects.

Root
   Project 1
   Project 2

So have one view start with project 2 as the new root without showing project 1 or the root at all.

This is using build 2.x.

**Comment by nao-pon** [comment]
Please check in [2.1 nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip) if necessary.
