### ISSUE TITLE
Unable to connect to backend with Dropbox Volume

### ISSUE THREAD

**Issue by bobnvic** [Studio-42/elFinder#814]
I've been trying to get the dropbox volume to work on a 2.1 nightly from this week.  Using the included elfinder.html and connector.minimal.php, I uncommented the VolumeDropbox include and defined my dropbox key and secret by editing the included defines.  I added 

```
    array(
                         'driver' => 'Dropbox',
                         'path'  => '/',
    )
```

to $opts.  I have dropbox-php and php oauth installed (and verified they are working).  Accessing the elfinder.html page shows the file directory and clicking on the mount network volume button gives me the dialog with the button to authorize the dropbox.  Once I log in to dropbox and allow access elfinder briefly shows "mounting network volume", then an error dialog appears that says "Unable to connect to backend".  This only happens on the dropbox volume, local files and ftp work fine.  Here is the last GET request that fails:

"GET /test/elFinder/php/connector.minimal.php?cmd=netmount&protocol=dropbox&host=dropbox&path=%2F&user=done&pass=done&_=1395430236761 HTTP/1.1" 500 413

I noticed on the previous json requests that host was dropbox.com instead of just dropbox but don't know if that is signficant.

Any help would be greatly appreciated.

Bob

**Comment by pbertoni** [comment]
> And it is important. The next extentions are required for PHP.
> Dropbox-PHP: http://www.dropbox-php.com/
>  PHP OAuth extension: http://pecl.php.net/package/oauth or PEAR's HTTP_OAUTH package: http://pear.php.net/package/http_oauth (HTTP_OAUTH require HTTP_Request2 and Net_URL2)
But where should I put them ?

**Comment by nao-pon** [comment]
@pbertoni 
How about composer?

composer.json example.
```json
{
    "repositories": [
        {
            "type": "pear",
            "url": "http://pear.php.net"
        }
    ],
    "require": {
        "dropbox-php/dropbox-php": "dev-master",
        "pear-pear.php.net/PEAR" : "*@stable",
        "pear-pear.php.net/HTTP_OAUTH" : "*@stable"
    }
}
```
dirctory example
- elfinder
    - php
        - composer.phar
        - composer.json
        - connector.php

$ cd elfinder/php
$ php composer.phar update

And include composer autoload.php in connector.php
```php
include_once(dirname(__FILE__).'/vendor/autoload.php');
```
