### ISSUE TITLE
remove read only permission for Elfinder plugin on localhost

### ISSUE THREAD

**Issue by naresh-kumar** [Studio-42/elFinder#854]
I just download a theme and with theme Elfinder plugin already installed. I want to test this plugin in localhost on windows. How to remove read only permission ?

Message : " As its a demo, you currently have read-only permission, in your server you may do everything like, upload or delete. It will work on a server only.

i also changed img folder permission 777.

**Comment by nao-pon** [comment]
Please check out the elFinder the latest version.
