### ISSUE TITLE
Download button is not working when i have added elfinder to my template.

### ISSUE THREAD

**Issue by smartguy6666** [Studio-42/elFinder#857]
i am using elfinder in my php project, and once i have added elfinder, the download feature is not working.
when i select any file or folder using elfinder few options become visible:
- New Folder
- New Text file
- Info
- View
and help option is always visible.
these above options are working perfect.
but download option is not working, copy, paste, delete is also not working.

**Comment by nao-pon** [comment]
Please re-open if there is a similar problem by checking in elFinder 2.1.
