### ISSUE TITLE
SFTP Driver

### ISSUE THREAD

**Issue by dedihost** [Studio-42/elFinder#862]
Please, make sftp driver to elfinder.
I try today but without success. I try to manipulate connect functions and some other in elFinderVolumeFTP.class.php.

This is so important for me and my people, i use elfinder from long long time ago with ftp only feature, but now i need to use elfinder with sftp. (its so simple to connect with ssh) and ssh is more reliable and user friendly than ftp servers like proftpd.
Please, add this feature to elfinder.

PP: I try with phpseclib sftp. - http://phpseclib.sourceforge.net/

**Comment by troex** [comment]
there are currently no plans for official SFTP driver, but you can try using https://github.com/barryvdh/elfinder-flysystem-driver

**Comment by sitecode** [comment]
Checkout https://github.com/sitecode/elFinder/blob/vd-sftp/php/elFinderVolumeSFTPphpseclib.class.php It's based on phpseclib v1.0
