### ISSUE TITLE
Windows Ftp Server

### ISSUE THREAD

**Issue by mronline** [Studio-42/elFinder#866]
array(
			'driver' => 'FTP',
			'host' => 'website.com',
			'user' => 'ftpuser',
			'pass' => '1234123',
			'path' => '/',
			'alias' => 'FTP',
			'tmpPath' => '../files/ftp',
		),

![tet](https://cloud.githubusercontent.com/assets/7905030/3290758/185055ee-f57d-11e3-908b-d33b28f7ef32.png)

i'm take error:
Invalid backend configuration. Readable volumes not available.

im include;

include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderConnector.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinder.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeDriver.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeLocalFileSystem.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeMySQL.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeFTP.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeFTPIIS.class.php';

elFinder work to linux ftp server, but not work windows ftp server? elFinder support Windows ftp server ?

**Comment by nao-pon** [comment]
elFinder 2.1 FTP driver supported IIS FTP server. Please use elFinder 2.1 with FTP driver.
