### ISSUE TITLE
Folder and file name become "files" when create on some hosting

### ISSUE THREAD

**Issue by yeszao** [Studio-42/elFinder#871]
Dear All,

I get a problem with elfinder 2.0 rc1 which download from elfinder.org.

When i create a folder or file on the elfinder work space with native language( Chinese ), the folder and file name become "files", no the native language name as i settings.

Elfinder works good on some servers, such as some linux, but it's serious on windows. 

What 's the meter, is there any body met some problems?

**Comment by nao-pon** [comment]
@yarons Please use elFInder 2.1 and set volume root options [`encoding`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding), [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale-1).
