### ISSUE TITLE
Always getting this error from connector.php: {"error":["errUnknownCmd"]}

### ISSUE THREAD

**Issue by Krassus** [Studio-42/elFinder#879]
Hi,

first of all I want to apologize for my bad english. I'll try my best.
Since last night, I keep getting this error: {"error":["errUnknownCmd"]} from the connector.php
I thought it might be my modifications but the original files create the same error. After hours of googling I modified the other php files and found out that the variable $ cmd was empty, so that public function commandExists($cmd) returns false.
You can see the source of my modified connector.php here:
http://www.commodum-mc.de/mod/connector.php.txt

Sincerely yours

Krassus

**Comment by LaercioDF** [comment]
Hello , I have the same error: { "error" : [" errUnknownCmd " ] } which changes you made ​​in connector.php ? I can not download your file.

**Comment by Krassus** [comment]
I don't know why but i deleted all files and started a new project and everything worked fine... So i don't know what the problem was :(
