### ISSUE TITLE
Qucik n' Dirty SVG Thumbs

### ISSUE THREAD

**Issue by LIDJungle** [Studio-42/elFinder#882]
Hey there,

I have added the ability to do SVG thumbs.

I'm using an SVG parser I found here: https://code.google.com/p/phpsvg/

However, it's been a long time since that was updated. I'm looking for a library with a bit more support. Let me know if you know of one.

                require_once "svg/svglib.php";
		// File has been copied over, let's check if it's an SVG
		$info = new SplFileInfo($path);
		if ($info->getExtension() == "svg") {
			$svg = SVGDocument::getInstance($path);
			// Maintain Ratio
			$w = $svg->getWidth();
			$h = $svg->getHeight();
			$hr = $h / $tmbSize;
			$nw = $w / $hr;
			// Export Thumb
			$svg->export($tmb, $tmbSize, $nw);
			return $name;
		}

This goes into the createTmb function in elFinderVolumeDriver.class. You also need to add the mime type to the canCreateTmb function:

	protected function canCreateTmb($path, $stat) {
		return $this->tmbPathWritable 
			&& strpos($path, $this->tmbPath) === false // do not create thumnbnail for thumnbnail
			&& $this->imgLib 
			&& strpos($stat['mime'], 'image') === 0 
			&& ($this->imgLib == 'gd' ? $stat['mime'] == 'image/jpeg' || $stat['mime'] == 'image/png' || $stat['mime'] == 'image/gif' || $stat['mime'] == 'image/svg+xml' : true);
	}

Modify the quicklook.plugins.js, line 10:

         var mimes   = ['image/jpeg', 'image/png', 'image/gif', 'image/svg+xml'],

This will allow you to see SVG files in the preview window.

![preview](https://cloud.githubusercontent.com/assets/5067415/3724714/14916a68-1681-11e4-844f-241518d35140.jpg)

Note that SVG parsing can be (relatively) quite slow. I had a directory of 122 flags, and it took 2-3 minutes to generate thumbs.

I still need to add in auto-cropping for wide images, and better error handling/timeout for broken SVG's. (FYI, do NOT use Inkscape!) Also, the same "canCreateThumbs" array of mime-types also determines what is resizable, etc... So we would need to split the two.

Results:
![svg_thumb](https://cloud.githubusercontent.com/assets/5067415/3724388/b3bbc204-167d-11e4-8929-2df10f15f47c.jpg)

---------------------------------------------------------------------------------------------
Full functions in case you need them:

	protected function canCreateTmb($path, $stat) {
		return $this->tmbPathWritable 
			&& strpos($path, $this->tmbPath) === false // do not create thumnbnail for thumnbnail
			&& $this->imgLib 
			&& strpos($stat['mime'], 'image') === 0 
			&& ($this->imgLib == 'gd' ? $stat['mime'] == 'image/jpeg' || $stat['mime'] == 'image/png' || $stat['mime'] == 'image/gif' || $stat['mime'] == 'image/svg+xml' : true);
	}

	protected function createTmb($path, $stat) {
                require_once "svg/svglib.php";
		error_log("Creating Thumbnail for ".$path);
		if (!$stat || !$this->canCreateTmb($path, $stat)) {
			return false;
		}

		$name = $this->tmbname($stat);
		$tmb  = $this->tmbPath.DIRECTORY_SEPARATOR.$name;

		// copy image into tmbPath so some drivers does not store files on local fs
		if (($src = $this->_fopen($path, 'rb')) == false) {
			return false;
		}

		if (($trg = fopen($tmb, 'wb')) == false) {
			$this->_fclose($src, $path);
			return false;
		}

		while (!feof($src)) {
			fwrite($trg, fread($src, 8192));
		}

		$this->_fclose($src, $path);
		fclose($trg);
		
		$tmbSize = $this->tmbSize;
		
     //INSERT CODE HERE
		// File has been copied over, let's check if it's an SVG
		$info = new SplFileInfo($path);
		if ($info->getExtension() == "svg") {
			$svg = SVGDocument::getInstance($path);
			// Maintain Ratio
			$w = $svg->getWidth();
			$h = $svg->getHeight();
			$hr = $h / $tmbSize;
			$nw = $w / $hr;
			// Export Thumb
			$svg->export($tmb, $tmbSize, $nw);
			return $name;
		}
		
		$result = false;

  		if (($s = getimagesize($tmb)) == false) {
			return false;
		}
		
    		/* If image smaller or equal thumbnail size - just fitting to thumbnail square */
    		if ($s[0] <= $tmbSize && $s[1]  <= $tmbSize) {
     	   		$result = $this->imgSquareFit($tmb, $tmbSize, $tmbSize, 'center', 'middle', $this->options['tmbBgColor'], 'png' );
	    	} else {

	    		if ($this->options['tmbCrop']) {
        
        			/* Resize and crop if image bigger than thumbnail */
	        		if (!(($s[0] > $tmbSize && $s[1] <= $tmbSize) || ($s[0] <= $tmbSize && $s[1] > $tmbSize) ) || ($s[0] > $tmbSize && $s[1] > $tmbSize)) {
    					$result = $this->imgResize($tmb, $tmbSize, $tmbSize, true, false, 'png');
	        		}

				if (($s = getimagesize($tmb)) != false) {
					$x = $s[0] > $tmbSize ? intval(($s[0] - $tmbSize)/2) : 0;
					$y = $s[1] > $tmbSize ? intval(($s[1] - $tmbSize)/2) : 0;
					$result = $this->imgCrop($tmb, $tmbSize, $tmbSize, $x, $y, 'png');
				}

    			} else {
        			$result = $this->imgResize($tmb, $tmbSize, $tmbSize, true, true, 'png');
      			}

			$result = $this->imgSquareFit($tmb, $tmbSize, $tmbSize, 'center', 'middle', $this->options['tmbBgColor'], 'png' );
		}

		if (!$result) {
			unlink($tmb);
			return false;
		}

		return $name;
	}

**Comment by SamMousa** [comment]
Should these previews / thumbnails just work when using imagick?

Also I'm confused about the need for all of this; basic SVG previews / thumbs should / could just work by not doing any conversion and just serving the whole file...

**Comment by remmel** [comment]
I agree with SamMousa, ImageMagick handle svg format, thumbnails should be generated like for others formats
