### ISSUE TITLE
I think it's dead.

### ISSUE THREAD

**Issue by mevsme** [Studio-42/elFinder#889]
Not even working last GitHub version out of the box.

But it's still so damn cool!

**Comment by Jogai** [comment]
Another project from Studio-42 points to elrte.org which seems not affiliated with them anymore. Wouldn't surprise me when they let elfinder.org expire too..

**Comment by dleffler** [comment]
Only 7 days old (as of this moment) - https://github.com/Studio-42/elFinder/tree/2.1

**Comment by buckett** [comment]
I think this can be closed as non-issue.
