### ISSUE TITLE
Support for XDomainRequest

### ISSUE THREAD

**Issue by troex** [Studio-42/elFinder#90]
IE8+ supports [XDomainRequest](http://msdn.microsoft.com/en-us/library/cc288060\(v=vs.85\).aspx) which allows JS to make cross-domain request (it is very similar to usual XMLHttpRequest). It also uses `Access-Control-Allow-Origin` the same as FireFox and WebKit.

This would be a nice feature if elFinder can detect IE and remote connector url (or turn on it manually) and use this type of request instead standard one for cross-domain request.

**Comment by nao-pon** [comment]
Fixed on 2.1 at 77b679923bd8b22149413f4e789c957699e0c1ec
