### ISSUE TITLE
Upload larges files (over 2GB) problem

### ISSUE THREAD

**Issue by ghost** [Studio-42/elFinder#903]
Hi,

I have a problem to upload larges files (size over 2GB) with chunked upload. 
With an file  size at 2047MB the uploading is good but with file size at 2048MB, the file is not copied to destination folder.
In temp directory, there are three files :
- ELFe7344b9d334ddebcdf54bd2b7751f034 to 0B
- ELFe7344b9d334ddebcdf54bd2b7751f034.20_20 to 48MB
- ELF67MAmr to 2024MB
  Chunk size is 100MB.

Edit : Elfinder with "elFinderVolumeLocalFileSystem" on Linux Red Hat 5 32bits

Can you help me ?

Frederic Marche

**Comment by santaclaus21** [comment]
I have got the same problem on Debian (ext3 partition)...

**Comment by nao-pon** [comment]
@santaclaus21 If your php running on 32bit operating system, May be maximum upload size is 2GB. Please set connector roots option `uploadMaxSize` to '2GB'.

If you want to use more than 2GB, please use a 64bit operating system.

**Comment by paulcanning** [comment]
I am using windows 64bit, WAMP 64 bit, PHP 5.6.21 64bit, and I am still unable to upload files larger then 2GB. You stated in https://github.com/Studio-42/elFinder/issues/1395 that this is by designed, as you are using PHP_INT_MAX.

So, either you are lying there, and you can upload files larger then 2GB, or you are lying here as you've told the user to use 64 bit Os to upload 2GB+ files.

Which is it?

**Comment by magdesign** [comment]
I am on debian 32bit ARM having the same issue: not able to upload files bigger than 2GB.

all other php tools are able to upload files bigger than 8GB.

Is there any solution to fix this?
