### ISSUE TITLE
Is there a way to use elFinder in Drupal's Attachment and File fields?

### ISSUE THREAD

**Issue by morgannunan** [Studio-42/elFinder#905]
Hi, I have elFinder running in Drupal 6x and it's running great. I also like that it has its own 'Files' page where I can browse the finder independant of content.

However, I would like to be able to use elFinder when uploading an attachment, using either the default attachment field or a custom field that takes files. Is there a way to integrate elFinder like this?

Thanks.

**Comment by nao-pon** [comment]
You can use [`bind`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#bind).
