### ISSUE TITLE
Modificación traducción español 

### ISSUE THREAD

**Issue by AngelDi** [Studio-42/elFinder#906]
Modificación en la traducción en español del comando 'cmdmkdir' por la falta de una 'c' en carpeta.

Comando 'cmdmkdir'

                  'cmdmkdir'     : 'Nueva carpeta',

**Comment by nao-pon** [comment]
@AngelDi Please use [elFinder translation tool](http://studio-42.github.io/elFinder/tools/langman/#2.1:es) and send PR.
