### ISSUE TITLE
Won't download on IIS6

### ISSUE THREAD

**Issue by Hervie** [Studio-42/elFinder#914]
Looks like there is a problem with download option from context menu (and from toolbar as well) on latest Chrome and IE8 on website hosted on IIS6  :
JS console output:

```
GET http://testweb/elfinder2/php/connector.php?cmd=file&target=l1_dGVtcFxBY3RpdmVQZXJsLTUuMTYuMy4xNjA0LU1TV2luMzIteDg2LTI5ODAyMy56aXA&download=1 net::ERR_INVALID_RESPONSE 
 
jquery.min.js:3(anonymous function)         jquery.min.js:3
f.fn.extend.domManip                        jquery.min.js:4
f.fn.extend.append                          jquery.min.js:3
f.fn.(anonymous function)                   jquery.min.js:4
exec                                        elfinder.min.js:20
(anonymous function)                        elfinder.min.js:15
(anonymous function)                        elfinder.min.js:15
f.event.dispatch                            jquery.min.js:3
h.handle.i                                  jquery.min.js:3
```

I 've found a workaround by entering custom HTTP Header value 'Content-disposition' in IIS Manager for the folder of those files. Now Chrome on doubleclick goes to download, but opens extra popup window. Safari works ok, and asks downoad/open question while Firefox doesn't download at all until doubleclick.

Is there a solution for this, or should I disable right click/toolbar Download option and leave it just for doubleclick?

many thanks.

**Comment by nao-pon** [comment]
Please try elFinder 2.1 and please re-open this issue if you get same problem.
