### ISSUE TITLE
Password ok, FTP server ready

### ISSUE THREAD

**Issue by Ataye** [Studio-42/elFinder#927]
This is more of a problem with the FTP driver than elFinder, but maybe someone else has had this issue?

After connecting and calling ftp_login(), it returns false - not logged in.  however, PHP throws a warning (i've created a simple test page with `ftp_connect()` and then `ftp_login()`):

```PHP Warning:  ftp_login() [<a href='function.ftp-login'>function.ftp-login</a>]: Password ok, FTP server ready in d:\website\test_ftp_connect.php on line 14```

Which looks to me like it has logged in, what with the part that says - `Password ok, FTP server ready`?

Any help would be appreciated.

thanks

**Comment by nao-pon** [comment]
Please try elFinder 2.1 and please re-open this issue if you get same problem.
