### ISSUE TITLE
File and folder it lock

### ISSUE THREAD

**Issue by poljuntha** [Studio-42/elFinder#954]
Hello i can't  upload images because icon not active and file and folder is a lock 
http://juntha.com/images/err1.png

Can anyone help?
Thank

**Comment by dleffler** [comment]
The entire folder 'images' is locked...is it possible you are locking it in the configuration setup for that driver? https://github.com/Studio-42/elFinder/wiki/Simple-file-permissions-control

**Comment by poljuntha** [comment]
Dleffler what is file name? 
or  create new file 

Thank you so much

**Comment by dleffler** [comment]
Whichever php file you use as the 'connector'.  The default one if in /php/connector.php (/php/connector.minimal.php does NOT have this example setting)

**Comment by poljuntha** [comment]
Hello Dleffler  file connector.php  Which inside There are 5 files in the
EX.
elFinder.class.php
elFinderConnector.class.php
elFinderVolumeDriver.class.php
elFinderVolumeLocalFileSystem.class.php
mime.types

I use elfinder with K2 component 
At the time of use. folder and file it a lock 
http://www.juntha.com/images/err1.png

Thank you for help me.

**Comment by dleffler** [comment]
Sorry for the confusion.  Looking at your attached image, you'll notice the 'locked' icon superimposed on each of the files and folders.  This indicates the folders are locked/read-only...therefore elFinder will not allow you to upload a new file, nor change any of the existing files.

The settings which may control this are found in the bottom of the 'php/connector.php' file.  There is an array variable called '$opts' which contains many lines most of which are commented out in the original file.  Within the definition for that variable, there is an item named 'attributes' which itself is an array using a regex expression which then applies file attributes to included files (read, write, hidden, & locked).

**Comment by poljuntha** [comment]
Dleffler Thank you so much for your help.
I would like unlock file and folder 

I'm going to try to do

Thank again.

**Comment by DinoJeremias** [comment]
i need some help because i tried to include the elfinder in a backoffice
but when i try to upload a big number of files it says that a error on the
transfer as occurred.. And i already tried to solve it but it keeps the
same thing. I hope you can help me.
Thanks

*Dino Jeremias*


2015-01-15 14:49 GMT+00:00 poljuntha <notifications@github.com>:
