### ISSUE TITLE
Search for a single root

### ISSUE THREAD

**Issue by T0miii** [Studio-42/elFinder#955]
Hello,

is it somehow possible to search in a single root directory for the specified search term?

i got my elfinder:
  root1:
        test.jpg
        fubar.txt
 root2
       test.jpg

if i search for test.jpg as result i get both test.jpg files. Or if i select root2 and then search fubar ill find the fuber.txt. This is a behaviour i woild not like.

So is it possible to actually search only the selected root?

regrads Tomi

**Comment by nao-pon** [comment]
Hi! Tomi,

Please check #939. It is possible by `disabled` in connector option.

**Comment by T0miii** [comment]
i found that one.
The users should be able to search all roots, but only if they select it. If i disable root1 they can never search it.

**Comment by nao-pon** [comment]
How about the plan which preserves an option about a search in account information on your server side system and designates an option of connector dynamically?
