### ISSUE TITLE
7Zip command line switches wrong, prevent archiving

### ISSUE THREAD

**Issue by dleffler** [Studio-42/elFinder#957]
The '-l' seems to be an unsupported 7z/7za command line switch which prevents creation of archives when defaulting to use 7Zip.  Seems to work if you edit elFindervolumenLocalFileSystem.class.php and remove the '-l' switch from those affected lines.  (since the 'archivers()' option setting doesn't seem to be implemented yet.

**Comment by nao-pon** [comment]
Now check 7z with `7za --help` or `7z`. How about this?
https://github.com/Studio-42/elFinder/blob/85cef104991ce6f7e1eb5520a854cfc134f4d075/php/elFinderVolumeDriver.class.php#L3249-L3281

**Comment by nao-pon** [comment]
I checked Win7 command line with '7z'. "7-Zip 9.38 beta" & "7-zip [64] 9.28 alpha" both are OK.

**Comment by dleffler** [comment]
In both 7.20 and 9.38 beta, there is a 'command' of 'l' to list an archive, but no switch '-l'.  So for lines line #3267 (above), the correct argc value should be

```
'a -tzip'

and NOT

```
'a -tzip -l'

**Comment by nao-pon** [comment]
OK! I understood. It'll be checked now.
