### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by RickCogley** [Studio-42/elFinder#958]
To password protect a site with elFinder, what's the usual way? 
Are people using http_auth?

Best regards
Rick

**Comment by Prgtools** [comment]
Hi, you should use .htaccess file to protect of your file manager.
.htaccess :
<files elfinder.php>
Order Deny,Allow  
Deny from All  
Satisfy Any   
AuthName "PrgtoolsUserAuth"
AuthType Basic
AuthUserFile ".htpasswd"
require valid-user
</files>
----------------
.htpasswd ::
username:pass

**Comment by nao-pon** [comment]
There is Basic Auth example -> http://studio-42.github.io/elFinder/#elf_l1_QmFzaWNBdXRoRXhhbXBsZQ
