### ISSUE TITLE
Nightly 2.x vs. 2.1

### ISSUE THREAD

**Issue by mfive** [Studio-42/elFinder#959]
Hi All,
what is the difference between the Nightly Builds 2.x and 2.1?
And is the Nightly 2.1. the latest build for web production use or is there any newer?
thanx a lot!

**Comment by barryvdh** [comment]
Wondering the same thing. I always just use 2.1, because it's ahead of 2.x, bust most changes are merged back and forth.

**Comment by mfive** [comment]
jes its a little freaky :) i started comparing each line but that takes too long and is error-prone. also how is it if someone likes to include his own feature? for example i have a drag-and-drop feature where you can drag a file/image and drop it within a form to assign i. e. a image to a hidden field...
