### ISSUE TITLE
I can't upload many files togther

### ISSUE THREAD

**Issue by DinoJeremias** [Studio-42/elFinder#960]
i need some help because i tried to include the elfinder in a backoffice
but when i try to upload a big number of files it says that a error on the
transfer as occurred.. And i already tried to solve it but it keeps the
same thing. I hope you can help me.
Thanks
![1](https://cloud.githubusercontent.com/assets/10546941/5759872/c82ef66c-9cc8-11e4-877e-143d5a5fc300.PNG)
![2](https://cloud.githubusercontent.com/assets/10546941/5759874/caf29ad4-9cc8-11e4-8e89-48f0709c4d96.PNG)
*Dino Jeremias*

**Comment by nao-pon** [comment]
elFinder 2.1 supported chunked file uploading. Please try elFinder 2.1. You can download from http://nao-pon.github.io/elFinder-nightly/latests/elfinder-2.1.zip
