### ISSUE TITLE
Sample Connector for S3 Driver in #778?

### ISSUE THREAD

**Issue by RickCogley** [Studio-42/elFinder#961]
Hello - would it be possible for someone to show me what the connector.php entry should look like, for using the S3 driver in 2.1 branch, referenced in #778? I'd like to create a root to browse an S3 bucket.

Thank you in advance.

**Comment by barryvdh** [comment]
Probably something like this:

    array(
        'driver'    => 'S3'
        'accesskey' => '',
        'secretkey' => '',
        'bucket'    => '',
        'path'      => '',
    ),

If you want to use Flysystem (which requires Composer etc), you can look into: https://github.com/Studio-42/elFinder/pull/928
But that's not stable yet.

**Comment by RickCogley** [comment]
Thanks @barryvdh, appreciate the hint! 
Yes, Flysystem does indeed look interesting. It's convenient that it handles a lot of different systems.

**Comment by nao-pon** [comment]
This issue is not a bug. so close. But please advise continuously.
