### ISSUE TITLE
i can't get image url from elfinder into ckeditor  

### ISSUE THREAD

**Issue by surmelihamido** [Studio-42/elFinder#962]
![issue](https://cloud.githubusercontent.com/assets/10569682/5787668/607f2c2c-9e11-11e4-968c-63fedf3442ba.jpg)

i choosed image from elfinder but not get url into ckeditor. i can't see url..

**Comment by barryvdh** [comment]
Did you follow the guide for CKEditor? Any JS errors in your console? Try debugging the return value from elFinder.

**Comment by nao-pon** [comment]
This issue is not a bug. so close. But please advise continuously.
