### ISSUE TITLE
Unable to create new folder

### ISSUE THREAD

**Issue by wood1e** [Studio-42/elFinder#963]
Hi, 

How do I create a new folder? As the 'New Folder icon' is greyed out and therefore unable to create new folder.

**Comment by dleffler** [comment]
Pure guess here, but the folder is probably 'locked' (with a lock icon superimposed).  meaning write is false...this is normally set in the 'connecter' php file

**Comment by nao-pon** [comment]
This issue is not a bug. so close. But please advise continuously.

**Comment by wood1e** [comment]
So if it is not a bug, where do I fix the issue, as I cannot create a FOlder with your Plugin?

**Comment by nao-pon** [comment]
First, please check the settings of your elFinder. To create a holder, you must have write permission for that location.
