### ISSUE TITLE
easy to fix,Translation: Cut -> Ausschneiden

### ISSUE THREAD

**Issue by franz1647** [Studio-42/elFinder#966]
Hi everybody,

a small issue, but easy and quick to fix.
You have a wrong translation. Cut is in German: Ausschneiden
And not: Ausschreiden
Do you see the difference? It is the n not the r :)

Please replace that.

Thx.

See you.

**Comment by barryvdh** [comment]
You can easily submit a pull request, just click on the edit button in the github web interface ;)
