### ISSUE TITLE
Unknown format downloaded picture

### ISSUE THREAD

**Issue by thomasdseao** [Studio-42/elFinder#973]
Hello,

(sorry if I make mistakes English )
I have problems with Elfinder , when I upload a picture and then I open my computer , I get an error message saying "The file an unknown format ." I have this trouble for images, other files It Works perfectly.
PS : The link to the error : http://i.imgur.com/OlUMTEe.jpg
Best Regards,

**Comment by nao-pon** [comment]
Is it saved to server storage as picture? (Please check by FTP etc.)

**Comment by thomasdseao** [comment]
Thank you for the reply,
Yes it is stored as an image on the server. 
If I download the image by the direct link that works. But if I download the picture by the hashed link that does not work.

**Comment by nao-pon** [comment]
Please check the server response by developer tool of a browser. (PHP error messages or white spaces aren't included)

**Comment by thomasdseao** [comment]
Hi,
Here in pictures the console: (I have not server response)
http://i.imgur.com/ALqiZtj.png
http://i.imgur.com/qfP6agn.png

**Comment by nao-pon** [comment]
http://i.imgur.com/qfP6agn.png
Please check response tab.(^_^)b
2015/01/30 17:54 "Thomas" <notifications@github.com>:

**Comment by thomasdseao** [comment]
In the first picture

**Comment by thomasdseao** [comment]
"Failed to load response data"

**Comment by nao-pon** [comment]
Do you use AdBlock extension?

ref.
http://stackoverflow.com/questions/4390134/failed-to-load-resource-under-chrome
2015/01/30 20:34 "Thomas" <notifications@github.com>:

**Comment by thomasdseao** [comment]
I utlise another browser, here is the answer :
http://pastebin.com/qKqYqAks

**Comment by nao-pon** [comment]
That  data encoded by base64. It isn't being encoded in elFinder. Do you have any ideas?

**Comment by thomasdseao** [comment]
I searched for days and no I have no idea.
If you want I can send you the access to the site in private.

**Comment by nao-pon** [comment]
If this phenomenon is made intentionally, It's possible to use PHP function [stream_filter_append()](http://php.net/manual/function.stream-filter-append.php) . But elFinder isn't doing that. Isn't a similar thing being done by your system?

**Comment by thomasdseao** [comment]
I pass URL parameter the name of the destination folder encrypted in addition to the basic url parameter. Is this a problem?
My URL is : connector.php?heyHo=pMmkzpWl&cmd=file&target=l1_bWFpbnRlbmFuY2U0MDQucG5n&download=1

**Comment by nao-pon** [comment]
> I pass URL parameter the name of the destination folder encrypted in addition to the basic url parameter. Is this a problem?

It is not problem.

> My URL is : connector.php?heyHo=pMmkzpWl&cmd=file&target=l1_bWFpbnRlbmFuY2U0MDQucG5n&download=1

elFinder seems to be the old version. Please try nightly build （[2.x](http://nao-pon.github.io/elFinder-nightly/latests/elfinder-2.x.zip) or [2.1](http://nao-pon.github.io/elFinder-nightly/latests/elfinder-2.1.zip)）

**Comment by nao-pon** [comment]
If you need item's URL link on elFinder. You are able to find it in info dialog.

**Comment by nao-pon** [comment]
I misread it. It was a download link, wasn't it? It's OK.

ex. my demo site: http://hypweb.net/elFinder-nightly/demo/2.1/php/connector.minimal.php?heyHo=pMmkzpWl&cmd=file&target=l2_bWFpbnRlbmFuY2U0MDQucG5n&download=1

**Comment by thomasdseao** [comment]
I migrated to version 2.1 and its works! Thank you !

**Comment by nao-pon** [comment]
Congratulations! (^^)v
