### ISSUE TITLE
unable create to archive

### ISSUE THREAD

**Issue by dannzs** [Studio-42/elFinder#977]
Hi, guys..
I have problem with "extract and archive". (unable create to archive)

Please help TT

**Comment by dleffler** [comment]
(w/ v2.1) What OS is the server? (Windows/Linux)...to work on Windows, you'd need to have 7Zip installed and I believe there is a 'switch' issue where elFinder calls the 7za.exe with an invalid switch.

**Comment by nao-pon** [comment]
This issue is not a bug. so close. But please advise continuously.

**Comment by nao-pon** [comment]
Please let us know the appropriate switch.

**Comment by dleffler** [comment]
See ticket #957, remove the -l as it is not (no longer?) a valid 7za.exe switch.

**Comment by nao-pon** [comment]
Oh! I missing. I wrote into #957.

**Comment by dannzs** [comment]
dleffler@ I am use windows 7 64bit. 7zip.exe and 7z.dll 's has been copied in SysWOW64 folder.
elFinderVolumeLocalFileSystem.class.php after after modified :
$this->procExec('7z', $o, $c);
		if ($c == 0) {
			$arcs['create']['application/x-7z-compressed']  = array('cmd' => '7z', 'argc' => 'a', 'ext' => '7z');
			$arcs['extract']['application/x-7z-compressed'] = array('cmd' => '7z', 'argc' => 'e -y', 'ext' => '7z');
			
			if (empty($arcs['create']['application/x-gzip'])) {
				$arcs['create']['application/x-gzip'] = array('cmd' => '7z', 'argc' => 'a -tgzip', 'ext' => 'tar.gz');
			}
			if (empty($arcs['extract']['application/x-gzip'])) {
				$arcs['extract']['application/x-gzip'] = array('cmd' => '7z', 'argc' => 'e -tgzip -y', 'ext' => 'tar.gz');
			}
			if (empty($arcs['create']['application/x-bzip2'])) {
				$arcs['create']['application/x-bzip2'] = array('cmd' => '7z', 'argc' => 'a -tbzip2', 'ext' => 'tar.bz');
			}
			if (empty($arcs['extract']['application/x-bzip2'])) {
				$arcs['extract']['application/x-bzip2'] = array('cmd' => '7z', 'argc' => 'a -tbzip2 -y', 'ext' => 'tar.bz');
			}
			if (empty($arcs['create']['application/zip'])) {
				$arcs['create']['application/zip'] = array('cmd' => '7z', 'argc' => 'a -tzip -l', 'ext' => 'zip');
			}
			if (empty($arcs['extract']['application/zip'])) {
				$arcs['extract']['application/zip'] = array('cmd' => '7z', 'argc' => 'e -tzip -y', 'ext' => 'zip');
			}
			if (empty($arcs['create']['application/x-tar'])) {
				$arcs['create']['application/x-tar'] = array('cmd' => '7z', 'argc' => 'a -ttar -l', 'ext' => 'tar');
			}
			if (empty($arcs['extract']['application/x-tar'])) {
				$arcs['extract']['application/x-tar'] = array('cmd' => '7z', 'argc' => 'e -ttar -y', 'ext' => 'tar');
			}
		}

7za => 7z

**Comment by dannzs** [comment]
nao-pon@ #722 the same issue.

**Comment by Ottiko** [comment]
elFinder can support zip tar gz files? How I can active?

**Comment by nao-pon** [comment]
Must be able to either of these commands are executed on the server. (Tar, zip, unzup, rar, 7z, 7za)

In or elFinder 2.1 PHP ZipArchive Class is also available.
