### ISSUE TITLE
Help with archiving

### ISSUE THREAD

**Issue by yambbkru** [Studio-42/elFinder#978]
Create Archive button and unzip all the time inactive. Did not get to make them active. Help.

**Comment by nao-pon** [comment]
- What's your elFinder version? Please check with [nightly version](http://nao-pon.github.io/elFinder-nightly/latests/elfinder-2.x.zip).
- Which VolumeDriver uses?
- Can PHP uses server command `tar`, `zip`, `rar`, `7za` or `7z` ?

Please check #957, #977 too.

**Comment by yambbkru** [comment]
I'm using version 2.x
About the VolumeDriver I do not understand. Probably elFinderVolumeLocalFileSystem.class.php
Can PHP uses server command tar, zip, rar, 7za or 7z ? I think so.

**Comment by nao-pon** [comment]
Did you check with nightly version? If you are able to upload and make file or folder, maybe any archive command unavailable on your server.
