### ISSUE TITLE
MySql driver not uploading to the server

### ISSUE THREAD

**Issue by ankisa** [Studio-42/elFinder#980]
When I use MySql driver it stores folders in database, but not on server. I can't upload any file.  But I haven't seen many people complain. Should MySql driver store folders and files on server or not?

**Comment by nao-pon** [comment]
MySQL driver included in elFinder can't save contents in the file system. What driver do you use?

**Comment by ankisa** [comment]
I use all three drivers for testing purposes. But I need to store files on server and in database at the same time. That is not possible with elFinder?

**Comment by nao-pon** [comment]
Make your own driver to inherit the class "elFinderVolumeMySQL" or use the command bind.
https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#user-content-bind

Because it is not a elFinder issue to close it.
