### ISSUE TITLE
Elfinder don`t return correct link file to CKeditor

### ISSUE THREAD

**Issue by pelikanek** [Studio-42/elFinder#982]
Hello,

I try your code (on page https://github.com/Studio-42/elFinder/wiki/Integration-with-CKEditor)
<pre>
    // Helper function to get parameters from the query string.
    function getUrlParam(paramName) {
        var reParam = new RegExp('(?:[\?&]|&amp;)' + paramName + '=([^&]+)', 'i') ;
        var match = window.location.search.match(reParam) ;

        return (match && match.length > 1) ? match[1] : '' ;
    }

    $().ready(function() {
        var funcNum = getUrlParam('CKEditorFuncNum');

        var elf = $('#elfinder').elfinder({
            url : 'php/connector.php',
            getFileCallback : function(file) {
                window.opener.CKEDITOR.tools.callFunction(funcNum, file.url);
                window.close();
            },
            resizable: false
        }).elfinder('instance');
    });
</pre>
<p>But it didnt work.</p>
<p>I think it is wrong, I tested it and change this line:</p>
<pre>window.opener.CKEDITOR.tools.callFunction(funcNum, file.url);</pre>
<p>by this way:</p>
<pre>window.opener.CKEDITOR.tools.callFunction(funcNum, file);</pre>
Now it works perfect!

**Comment by nao-pon** [comment]
Thanks @pelikanek

` window.opener.CKEDITOR.tools.callFunction(funcNum, file.url);`
or
` window.opener.CKEDITOR.tools.callFunction(funcNum, file);`
?

see https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#commandsoptions 

`commandsOptions.getfile.onlyURL = false` is `file.url`

`commandsOptions.getfile.onlyURL = true` is `file`

**Comment by barryvdh** [comment]
Maybe change it to `file.url || file` (Or `var url = typeof file == 'string' ? file : file.url;`?
