### ISSUE TITLE
User-Management

### ISSUE THREAD

**Issue by derSteffen** [Studio-42/elFinder#983]
Hello I have a question!

Is there an option for an User-Management, that I can say in this folder only the group XY has an access and in this folder the group ABC can only look, and in this folder everything can do everything?

Thank you very much!

Greetiings

**Comment by derSteffen** [comment]
No hint? Or is there a User-Management intergrated?

**Comment by nao-pon** [comment]
"elFinder" doesn't have the user administrative function, so it's necessary to use it according to the other platforms.

Those generate the option which gives it to elFinder on connector.php by the user login information dynamically.

A connector for XOOPS (CMS) I have developed is the next.

- https://github.com/nao-pon/xelfinder/blob/master/xoops_trust_path/modules/xelfinder/connector.php

**Comment by derSteffen** [comment]
Hello nao-pon,

thank you very much! This link I have found, but it was to complex for me! This is a combination with an other programm (cms: xoops) and elfinder, right?

But in my case I dont have an extra plattform! I want protect elfinder with an login for only memberships (for this I have a solution) .... and then I want difference groupmembers!
 
Is there a simple way that I can manual write a txt, php or htacess-file where I can declare this Name (Member) is in the group XYZ and group XYZ can write in the folder, can create new folder and new files but the home-path is a spezial-folder .. and they can't read or write in the folder secret .... but the group SPECIAL can read and write in the folder secret?

Thank you very much!

Greetings Steffen

**Comment by nao-pon** [comment]
When BASIC authentication of Apache is used, a login user name is obtained in $_SERVER ['PHP_AUTH_USER'], so I think it's the simplest way to use that.

And　you can use `attributes` volume option. ( https://github.com/Studio-42/elFinder/wiki/Simple-file-permissions-control )

**Comment by todakure** [comment]
I'm trying to block access to a specific folder within the elfinder (private) , I am using the example shown in the wiki , but can only block the TEST folder , other folders I can not block ?, which are under another name , not being TEST as shown.


http://pasteboard.co/1ABZTr2N.png


$opts = array(
        // 'debug' => true,
        'roots' => array(
                array(
                        'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
                        'path'          => '../files/',         // path to files (REQUIRED)
                        'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
                        'accessControl' => 'access',             // disable and hide dot starting files (OPTIONAL)
                        'attributes'    => array(
                                                array(
                                                            'pattern' => '/\lider$/', //You can also set permissions for file types by adding, for example, <b>.jpg</b> inside pattern.
                                                            'read'    => true,
                                                            'write'   => false,
                                                            'locked'  => false
                                                     ),
                                                array(
                                                            'pattern' => '/\TEST$/',
                                                            'read'    => true,
                                                            'write'   => false,
                                                            'locked'  => false
                                                )
                                              )
                   )
                )

);

**Comment by nao-pon** [comment]
There is Basic Auth example -> http://studio-42.github.io/elFinder/#elf_l1_QmFzaWNBdXRoRXhhbXBsZQ
