### ISSUE TITLE
Lazy loading on tree list

### ISSUE THREAD

**Issue by MrGorki** [Studio-42/elFinder#984]
Its good to have lazy loading on main content and it is working flawlessly but the tree list on left side is another handicap which tries to load 7000 (in my case) directory at the startup and sometimes breaking down. It will be better to have same lazy loading mechanism on the tree list also

**Comment by nao-pon** [comment]
@MrGorki
I think lazy loading of tree is difficult. A rendering was sped up in a compensation. In 2.1 branch at 760a4156526119f377e0286555af6e36f08284ea .
