### ISSUE TITLE
elFinder 2.0 Beta Issue - Connector Configuration Options Missing?

### ISSUE THREAD

**Issue by Gamerz** [Studio-42/elFinder#99]
So the connector configuration options seem to either be missing or option names have all be renamed. 

I used this master list: (http://elrte.org/redmine/projects/elfinder/wiki/Connector_Configuration_EN#Options) and tested some options on the connector.php...none of them seem to work? Am I doing something wrong?

One major feature I REALLY need that doesn't seem to be working is the MySQL Driver. I've set the settings in the connector.php script by adding another driver array named "MySQL" and it doesn't work....is there any additional things I need to do/set before I can use MySQL driver?

**Comment by harish-php** [comment]
Mysql driver not working for me.. SHould i have to create any directory somewhere named DATABSE ??

{"error":["errConf","errNoVolumes"],"debug":["Driver \"elFinderVolumeMySQL\" : "]}
