### ISSUE TITLE
No response when there are files with multibyte string in the name

### ISSUE THREAD

**Issue by 4Giedrius** [Studio-42/elFinder#990]
File name in question is `altera‡äes.txt`. It seems that `json_encode` is silently crashing while trying to encode it and no response is being received in the frontend.  https://github.com/Studio-42/elFinder/blob/2.x/php/elFinderConnector.class.php#L127

So you would need to encode all the array with `UTF-8`  or if you are not going to support this, you need to check if encoding to JSON went smoothly.

**Comment by nao-pon** [comment]
@4Giedrius elFinder 2.1 supported non-utf8 server's file system encoding and locale by the volume options. ref: Volume option [`encoding`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding), [`locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locale-1)

Please try [elFinder 2.1 Nightly build](http://nao-pon.github.io/elFinder-nightly/latests/elfinder-2.1.zip). ( https://github.com/nao-pon/elFinder-nightly )
