### ISSUE TITLE
an error about the regular expression of  acceptedName

### ISSUE THREAD

**Issue by changkejun** [Studio-42/elFinder#991]
I use elfinder 2  in linux server with PHP 5.3.3.

And I find it is error to upload to files with ja_JP name, or rename to ja_JP name.
When I delete the value of acceptedName in elFinderVolumeDriver.class.php, it is running.
In another environment with PHP 5.3.29, the orginal acceptedName  value is OK.

And, I checked the php ini of the two servers.
php 5.3.29 ->posix enable , pcre enable
php 5.3.33 ->posix disabled, pcre enable
but it seems posix is not used....

I know the key is this line, but I dont know why it refuse japanese characters in PHP 5.3.3.
'acceptedName'    => '/^\w[\w\s\.\%\-\(\)\[\]]*$/u',

**Comment by nao-pon** [comment]
@changkejun Try set [elFinder connector option `locale`](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#locale) to 'ja_JP.UTF8'.
