### ISSUE TITLE
Disable drop state when renaming

### ISSUE THREAD

**Issue by uumailbox** [Studio-42/elFinder#992]
At line 7473 of source,  
the original is: 
"dir.is('.'+droppable) && dir.droppable(active);", 
It seems to be :
"dir.is('.'+droppable) && dir.droppable(act);".

**Comment by nao-pon** [comment]
@uumailbox ,  Are you talking about https://github.com/Studio-42/elFinder/blob/2.x/js/ui/tree.js#L539-L540 ?

**Comment by uumailbox** [comment]
@nao-pon, Yes, that is.

**Comment by uumailbox** [comment]
@nao-pon, Yes, that is.

**Comment by nao-pon** [comment]
Thanks @uumailbox !
