### ISSUE TITLE
Old file list can't correctly refresh, when drag file to dir, 

### ISSUE THREAD

**Issue by uumailbox** [Studio-42/elFinder#993]
At line [ui/cwd.js L605](https://github.com/Studio-42/elFinder/blob/f0205165111e49b0be82558783d4c15a982ffdad/js/ui/cwd.js#L605), 
the original is:
"hash = files[l];",
It should be :
"hash = files[l].hash;".

**Comment by nao-pon** [comment]
@uumailbox 
`files` is array of file hash, is not object. There aren't any problems in my case. Did you get problem?

**Comment by uumailbox** [comment]
hi @nao-pon, I check out with "elFinder 2.1", but i got "files" as a array of Object. So it throw a exeception.

**Comment by nao-pon** [comment]
Did you check on nightly builds?

**Comment by nao-pon** [comment]
The problem are reproduced in my demo site?
http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l2_Lw

**Comment by uumailbox** [comment]
Hi @nao-pon , I have resolved the problem, because I return an array of objects in the backend, the right is "removed" need an array of strings. Thanks, have a good day!
