### ISSUE TITLE
image dimensions - integration with TinyMCE 4.x

### ISSUE THREAD

**Issue by difylos** [Studio-42/elFinder#994]
integration with TinyMCE 4.x 
// pass selected file path to TinyMCE
top.tinymce.activeEditor.windowManager.getParams().setUrl(URL);
How can auto update image dimensions;

**Comment by dleffler** [comment]
I think this is something that has crept into the editor code (along with CKEditor).  According to the api, you only pass the url and the editor should be getting the dimensions itself.  To fix a similar situation with CKEditor's newer image2 plugin, I had to write additional code to directly place the image dimensions into it's insert graphic dialog.  I had not gotten around to coding a fix for TinyMCE though.

**Comment by dleffler** [comment]
Note this issue is fixed in TinyMCE v4.1.9 (according to their changelog)

**Comment by difylos** [comment]
I am using the tinymce 4.1.8
 i will update it and i will tell you

**Comment by difylos** [comment]
No it is not working in TinyMCE v4.1.9

**Comment by nao-pon** [comment]
Please check Wiki - https://github.com/Studio-42/elFinder/wiki/Integration-with-TinyMCE-4.x#alternative-method-using-the-new-tinymce-file_picker_callback-configuration-option
