### ISSUE TITLE
Text gets hidden while renaming

### ISSUE THREAD

**Issue by pbertoni** [Studio-42/elFinder#995]
Entering "Rename" phase, either with F2 or by GUI, correctly puts in this status
![issue1](https://cloud.githubusercontent.com/assets/3540399/6573284/b65625a2-c719-11e4-8bba-6a7719af0113.png)
But a click everythere in the textfield, L/R arrows, home/end buttons, makes the text-to-be-replaced just disappear, as in 
![issue](https://cloud.githubusercontent.com/assets/3540399/6573329/fda367d0-c719-11e4-9a4b-dfe200c3f970.jpg)
Text still remains, e.g. sequence `F2 -> left arrow -> 'a' key -> Enter` on file `foo.dat` produces `afoo.dat`.
I'm using nao-pon's 2.1 Nightly and connecting to a local FS virtual disk.

**Comment by nao-pon** [comment]
@pbertoni , I couldn't see this problem in my demo site. Please check in my demo site.

Demo site: http://hypweb.net/elFinder-nightly/demo/2.1/#elf_l2_Lw

**Comment by pbertoni** [comment]
I noticed that I was using nightly `3e10dc7` (2015-02-19).
Now I've just downloaded nightly `ff1c846` (2015-03-10) from http://nao-pon.github.io/elFinder-nightly/latests/elfinder-2.1.zip and merged it into my website, but problem still remains... what other details can I give you ?

**Comment by nao-pon** [comment]
How about a result on my demo site? If there are no problems, I guess conflicting by the other Java Scripts which are loading on your site.

**Comment by pbertoni** [comment]
On your demo is all ok. The only other plugin I'm using is [datatables](http://www.datatables.net/), which allegedly is the responsible of the conflict. Thanks a lot.
