### ISSUE TITLE
Creating Excel file

### ISSUE THREAD

**Issue by aayushjindal** [Studio-42/elFinder#997]
Hi there,

I have an issue. I am trying to create an excel file from the elfinder. I added a new icon and command, When I click on icon file creates with proper extension. However, when finally file is left focus it runs and says me invalid command.

Can someone please tell me how to create an excel file or what I may be doing wrong?

**Comment by nao-pon** [comment]
Please register a new command to create a class that inherits from elFinder class "$ commands".

- https://github.com/Studio-42/elFinder/blob/c8a66f0ef226532b638d7430b5f22fe72ec4bba2/php/elFinder.class.php#L85

Because it is not a elFinder problems to close it.
