### ISSUE TITLE
After disable URL, image thumbnails not showing

### ISSUE THREAD

**Issue by supun151515** [Studio-42/elFinder#998]
Hi.. 
I have disabled URL from the connector.php because I want to hide actual file path from clients. But now it is not showing image thumbnails.

          $emp_id = '1234567890';
          $opts = array(
	        'roots' => array(
		    array(
			'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
			'path'          => '../../lib/lib_emp/'.$emp_id,         // path to files (REQUIRED)
			//'URL'           => dirname($_SERVER['PHP_SELF']) . '/../../lib/lib_emp/'.$emp_id, // URL to files (REQUIRED)
			'accessControl' => 'access',             // disable and hide dot starting files (OPTIONAL)
			'uploadOverwrite' => false,
			'attributes' => array(
        		array(
            		'pattern' => '/\.txt$/', //You can also set permissions for file types by adding, for example, .jpg inside pattern.
            		'read'    => false,
            		'write'   => false,
            		'locked'  => true
        			)
    			)
	)
	)
     );

Best Regards,
Supun

**Comment by dleffler** [comment]
My guess is you MUST set tmbURL if URL is not set...https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#tmbURL

Code logic in elFinderVolumeLocalFileSystem.class.php ~line 76 bumps to use 'URL' if 'tmbURL' is not set.

**Comment by supun151515** [comment]
Hi dleffler,
I understand what you mean. I have copied URL path to tmbPath as below;

$opts = array(
	'roots' => array(
		array(
			'driver'        	  => 'LocalFileSystem',
			'path'         	  => '../../lib/lib_emp,
			//'URL'           	  => dirname($_SERVER['PHP_SELF']) . '/../../lib/lib_emp',
		        'tmbPath'           => dirname($_SERVER['PHP_SELF']) . '/../../lib/lib_emp',
                       'accessControl'	  => 'access',

But it doesn't work. I have tried again as below and it fails as well;
'tmbPath'           => dirname($_SERVER['PHP_SELF']) . '/../../lib/lib_emp/.tmb',

As I see inside folders, each folder is automatically creates .tmb folder for thumnails.
It means tmbPath is a dynamic path.

Hope you understand and appreciate your answer.

Best Regards,
Supun
