### ISSUE TITLE
Reload elFinder with custom data

### ISSUE THREAD

**Issue by supun151515** [Studio-42/elFinder#999]
Hello everyone,
Since there are no good documentations for elFinder, it is very difficult to troubleshoot issues.

I have 5 dir names in html form. When I click on each item, elFinder should goto that location only.
How can I send data to server with client custom data???

below is my code;
     `$(document).ready(function() {

				$("#getdata").click(function(){
					$('#elfinder').elfinder({
					url : 'php/connector.minimal.php',
					requestType : 'POST'
				}).elfinder('instance');
				});
			});  `

Thank You,
Supun

**Comment by nao-pon** [comment]
Moved to http://stackoverflow.com/questions/29259182/elfinder-load-path-dynamically-from-user-input
